@startuml ОчередьРасчетаПлановыхКалькуляций
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОчередьРасчетаПлановыхКалькуляций as "Очередь расчета плановых калькуляций" <<РегистрыСведений>>
{
..Измерения..
Калькуляция : Документ.Плановая калькуляция
ПартияСпецификацияПродукции : Документ.Этап производства\rСправочник.Ресурсная спецификация\rДокумент.Производство без заказа
Продукция : Справочник.Номенклатура
ХарактеристикаПродукции : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
ПартияСпецификацияПолуфабриката : Документ.Этап производства\rСправочник.Ресурсная спецификация\rДокумент.Производство без заказа
Полуфабрикат : Справочник.Номенклатура
ХарактеристикаПолуфабриката : Справочник.Характеристика номенклатуры
Разделитель : Число 2, 0
ДатаПотребности : Дата
Порядок : Число 10, 0
..Реквизиты..
ОтменаПроведения : Булево
}
@enduml
