@startuml ПредметыПапкиВзаимодействий
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПредметыПапкиВзаимодействий as "Предметы папки взаимодействий" <<РегистрыСведений>>
{
..Измерения..
Взаимодействие : Документ.Исходящее электронное письмо\rДокумент.Запланированное взаимодействие\rДокумент.Входящее электронное письмо\r...
..Ресурсы..
Предмет : Справочник.Маркетинговое мероприятие\rДокумент.Исходящее электронное письмо\rДокумент.Запланированное взаимодействие\r...
ПапкаЭлектронногоПисьма : Справочник.Папка электронных писем
Рассмотрено : Булево
РассмотретьПосле : Дата
}
@enduml
