@startuml СтатусыЗаявокНаВыпускКиЗГИСМ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтатусыЗаявокНаВыпускКиЗГИСМ as "Статусы заявок на выпуск КиЗ ГИСМ" <<РегистрыСведений>>
{
..Измерения..
Документ : Документ.Заказ поставщику\rДокумент.Заявка на выпуск КиЗ для маркировки
..Ресурсы..
ТекущаяЗаявкаНаВыпускКиЗ : Документ.Заявка на выпуск КиЗ для маркировки
СтатусЗаявкиНаВыпускКиЗ : Статусы заявок на выпуск КиЗ
СтатусОбработкиЭмитентом : Статусы обработки эмитентом КиЗ
ДальнейшееДействие : Дальнейшие действия по взаимодействию ГИСМ
ПоступлениеТоваров : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг
КоличествоПоступленийТоваров : Число 3, 0
СтатусПоступления : Состояния поступлений ГИСМ
КПередачеПодтверждения : Булево
ПроцентПодтвержденныхКиЗ : Число 3, 0
}
@enduml
