@startuml НапоминанияПользователя
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НапоминанияПользователя as "Напоминания пользователя" <<РегистрыСведений>>
{
..Измерения..
Пользователь : Справочник.Пользователь
ВремяСобытия : Дата
Источник : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
..Ресурсы..
СрокНапоминания : Дата
..Реквизиты..
Описание : Строка
СпособУстановкиВремениНапоминания : Способы установки времени напоминания
ИнтервалВремениНапоминания : Число 10, 0
ИмяРеквизитаИсточника : Строка
Расписание : Хранилище значения
ПредставлениеИсточника : Строка
Идентификатор : Строка
}
@enduml
