@startuml НастройкиАдресныхСкладов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиАдресныхСкладов as "Настройки адресных складов" <<РегистрыСведений>>
{
..Измерения..
Склад : Справочник.Склад (складская территория)
Помещение : Справочник.Помещение
..Ресурсы..
ГлубинаАнализа : Число 10, 0
МинимальнаяВероятностьОтгрузки : Число 2, 0
УровеньОбслуживанияУпаковокКлассаX : Уровни обслуживания
УровеньОбслуживанияУпаковокКлассаY : Уровни обслуживания
УровеньОбслуживанияУпаковокКлассаZ : Уровни обслуживания
ИспользоватьПрогнозРасходаУпаковок : Булево
РегламентноеЗаданиеРасчетаПоказателейПрогноза : Уникальный идентификатор
ИспользоватьАдресноеХранение : Булево
ИспользоватьАдресноеХранениеСправочно : Булево
ИспользоватьРабочиеУчастки : Булево
УдалитьРегламентноеЗаданиеСозданиеЗаданийНаПодпитку : Уникальный идентификатор
РегламентноеЗаданиеСозданиеЗаданийНаОтбор : Уникальный идентификатор
УдалитьИспользоватьРегламентноеЗаданиеСозданияЗаданийНаПодпитку : Булево
ИспользоватьРегламентноеЗаданиеСозданияЗаданийНаОтбор : Булево
НастройкаФормированияПоРабочимУчасткамОтбор : Строка
ОграничиватьПоВесуОтбор : Булево
ОграничиватьПоОбъемуОтбор : Булево
ОграничениеПоОбъемуОтбор : Число 10, 0
ОграничениеПоВесуОтбор : Число 10, 0
РабочийУчастокОтбор : Справочник.Рабочий участок
ДатаНачалаАдресногоХраненияОстатков : Дата
РегламентныеЗаданияСозданияЗаданийНаПересчетТоваров : Строка
РегламентныеЗаданияСозданияЗаданийНаПеремещение : Строка
}
@enduml
