@startuml ОчередьПередачиДанныхГИСМ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОчередьПередачиДанныхГИСМ as "Очередь передачи данных ГИСМ" <<РегистрыСведений>>
{
..Измерения..
Сообщение : Справочник.Сообщение обмена с ГИСМ
}
@enduml
