@startuml СостоянияНовостей
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияНовостей as "Состояния новостей" <<РегистрыСведений>>
{
..Измерения..
Пользователь : Справочник.Пользователь
Новость : Справочник.Новость
..Ресурсы..
Прочтена : Булево
Пометка : Число 1, 0
ОповещениеВключено : Булево
ДатаНачалаОповещения : Дата
УдаленаИзСпискаНовостей : Булево
}
@enduml
