@startuml РасчетРасходовПоАренде
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РасчетРасходовПоАренде as "Расчет расходов по аренде" <<РегистрыСведений>>
{
..Измерения..
ПериодРасчета : Дата
Организация : Справочник.Организация
ОсновноеСредство : Справочник.Объект эксплуатации
Контрагент : Справочник.Контрагент
ДоговорКонтрагента : Справочник.Договор лизинга
..Ресурсы..
АмортизацияБУ : Число 15, 2
АмортизацияНУ : Число 15, 2
АмортизацияВР : Число 15, 2
АмортизацияПР : Число 15, 2
СуммаПлатежаБезНДС : Число 15, 2
СуммаПлатежаНУ : Число 15, 2
КорректировкаАмортизацииНУ : Число 15, 2
}
@enduml
