@startuml ПерерасчетУдержаний
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПерерасчетУдержаний as "Перерасчет удержаний" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
ПериодДействия : Дата
Удержание : Удержание
ДокументОснование : Документ.Удержание по прочим операциям\rДокумент.Удержание добровольных взносов в НПФ\rДокумент.Удержание профсоюзных взносов\r...
Основание : Документ.Удержание по прочим операциям\rДокумент.Удержание добровольных взносов в НПФ\rДокумент.Данные для расчета зарплаты\r...
ДокументНачисления : Документ.Простой сотрудников\rДокумент.Отпуск\rДокумент.Больничный лист\r...
}
@enduml
