@startuml ТаможенныеДекларацииЭкспортКРегистрации
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ТаможенныеДекларацииЭкспортКРегистрации as "Таможенные декларации экспорт к регистрации" <<РегистрыСведений>>
{
..Измерения..
РеализацияЭкспорт : Документ.Реализация товаров и услуг
..Ресурсы..
СуммаДокумента : Число 15, 2
Организация : Справочник.Организация
Контрагент : Справочник.Контрагент
ДатаРеализации : Дата
Валюта : Справочник.Валюта
}
@enduml
