@startuml ОриентирыАдресныхОбъектов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОриентирыАдресныхОбъектов as "Ориентиры адресных объектов" <<РегистрыСведений>>
{
..Измерения..
Идентификатор : Уникальный идентификатор
КодСубъектаРФ : Число 2, 0
..Ресурсы..
АдресныйОбъект : Уникальный идентификатор
ПочтовыйИндекс : Число 6, 0
Дополнительно : Уникальный идентификатор
Описание : Хранилище значения
}
@enduml
