@startuml СтрокиОтчетностиМониторингаРаботниковСоциальнойСферы
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтрокиОтчетностиМониторингаРаботниковСоциальнойСферы as "Строки отчетности мониторинга работников социальной сферы" <<РегистрыСведений>>
{
..Измерения..
Должность : Справочник.Должность\rСправочник.Позиция
..Ресурсы..
СтрокаОтчетностиМониторингаРаботниковСоциальнойСферы : Справочник.Строка отчетности статистического наблюдения
}
@enduml
