@startuml РассчитанныеОтборыПоНовостям_ДляОбластиДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РассчитанныеОтборыПоНовостям_ДляОбластиДанных as "Рассчитанные отборы по новостям (для области данных)" <<РегистрыСведений>>
{
..Измерения..
Новость : Справочник.Новость
..Реквизиты..
РезультатОтбора : Булево
}
@enduml
