@startuml СоставныеФайлы
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СоставныеФайлы as "Составные файлы" <<РегистрыСведений>>
{
..Измерения..
ГлавныйФайл : Справочник.Файл
ПодчиненныйФайл : Справочник.Файл
..Ресурсы..
ОтносительныйПуть : Строка
}
@enduml
