@startuml СведенияОСертификатахОбменСБанками
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СведенияОСертификатахОбменСБанками as "Сведения о сертификатах обмен с банками" <<РегистрыСведений>>
{
..Измерения..
СертификатЭП : Справочник.Сертификат ключа электронной подписи и шифрования
..Ресурсы..
ПрограммаБанка : Программы банка
}
@enduml
