@startuml ОбработчикиСобытийСинхронизацииДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОбработчикиСобытийСинхронизацииДанных as "Обработчики событий синхронизации данных" <<РегистрыСведений>>
{
..Измерения..
УзелИнформационнойБазы : Синхронизация данных через универсальный формат\rОбмен с подключаемым оборудованием Offline\rОбрабатываемый объект\r...
Событие : Строка
Обработчик : Строка
}
@enduml
