@startuml ПрименениеДополнительныхПериодическихПоказателейРасчетаЗарплатыСотрудниковИспр
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПрименениеДополнительныхПериодическихПоказателейРасчетаЗарплатыСотрудниковИспр as "Применение дополнительных периодических показателей расчета зарплаты сотрудников испр" <<РегистрыСведений>>
{
..Измерения..
РегистраторИзмерение : Документ.Изменение условий оплаты отпуска по уходу за ребенком\rДокумент.Кадровый перевод\rДокумент.Восстановление в должности\r...
ПериодИзмерение : Дата
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
Показатель : Справочник.Показатель
..Ресурсы..
Применение : Булево
ДействуетДо : Дата
ПрименениеПоОкончании : Булево
}
@enduml
