@startuml ПорядокПлатежногоКалендаря
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПорядокПлатежногоКалендаря as "Порядок платежного календаря" <<РегистрыСведений>>
{
..Измерения..
БанковскийСчетКасса : Справочник.Банковский счет организации\rСправочник.Касса
УдалитьОрганизация : Справочник.Организация
УдалитьВалюта : Справочник.Валюта
УдалитьЗначениеГруппировки : Справочник.Статья движения денежных средств\rСправочник.Партнер\rСтрока
..Ресурсы..
ЗначениеПорядка : Число 5, 0
}
@enduml
