@startuml ПериодыДействияДоговоровГражданскоПравовогоХарактера
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПериодыДействияДоговоровГражданскоПравовогоХарактера as "Периоды действия договоров гражданско-правового характера" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ДокументОснование : Документ.Договор авторского заказа\rДокумент.Договор (работы, услуги)
..Ресурсы..
ДатаНачала : Дата
ДатаОкончания : Дата
Подразделение : Справочник.Подразделение
}
@enduml
