@startuml УдалитьОбластиДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьОбластиДанных as "(не используется) Области данных" <<РегистрыСведений>>
{
..Измерения..
ОбластьДанных : Число 7, 0
..Ресурсы..
Представление : Строка
Статус : Статусы областей данных
Префикс : Строка
..Реквизиты..
Повтор : Число 2, 0
ЧасовойПояс : Строка
ИдентификаторВыгрузки : Уникальный идентификатор
ОшибкаОбработки : Булево
Вариант : Строка
}
@enduml
