@startuml ЗначенияПоказателейДляРаспределенияРасходов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗначенияПоказателейДляРаспределенияРасходов as "Значения показателей для распределения расходов" <<РегистрыСведений>>
{
..Измерения..
Подразделение : Справочник.Подразделение
Показатель : Справочник.Правило распределения расходов
..Ресурсы..
ЗначениеПоказателя : Число 15, 2
}
@enduml
