@startuml СостоянияРассылокОтчетов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияРассылокОтчетов as "Состояния рассылок отчетов" <<РегистрыСведений>>
{
..Измерения..
Рассылка : Справочник.Рассылка отчетов
..Ресурсы..
ПоследнийЗапускНачало : Дата
ПоследнийЗапускЗавершение : Дата
УспешныйЗапуск : Дата
Выполнена : Булево
СОшибками : Булево
НомерСеанса : Число 25, 0
}
@enduml
