@startuml ГрафикРаботыСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ГрафикРаботыСотрудников as "График работы сотрудников" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ГоловнаяОрганизация : Справочник.Организация
..Ресурсы..
ГрафикРаботы : Справочник.График работы
ДействуетДо : Дата
УдалитьГрафикРаботыПоОкончании : Справочник.График работы
}
@enduml
