@startuml НастройкиТранспортаОбменаОбластиДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиТранспортаОбменаОбластиДанных as "Настройки транспорта обмена области данных" <<РегистрыСведений>>
{
..Измерения..
Корреспондент : Синхронизация данных через универсальный формат\rОбмен с подключаемым оборудованием Offline\rОбрабатываемый объект\r...
..Ресурсы..
КонечнаяТочкаКорреспондента : Конечная точка
КаталогОбменаИнформацией : Строка
}
@enduml
