@startuml СогласияНаОбработкуПерсональныхДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СогласияНаОбработкуПерсональныхДанных as "Согласия на обработку персональных данных" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Субъект : Справочник.Физическое лицо
..Ресурсы..
Действует : Булево
СрокДействия : Дата
}
@enduml
