@startuml ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников as "Значения периодических показателей расчета зарплаты (для сотрудников)" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
Показатель : Справочник.Показатель
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Приз, подарок\rДокумент.Удержание по прочим операциям\r...
..Ресурсы..
Значение : Число 15, 5
ДействуетДо : Дата
УдалитьЗначениеПоОкончании : Число 15, 5
}
@enduml
