@startuml ДополнительныеРеквизитыУчетнойЗаписи
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДополнительныеРеквизитыУчетнойЗаписи as "Дополнительные реквизиты учетной записи" <<РегистрыСведений>>
{
..Измерения..
УчетнаяЗапись : Справочник.Учетные записи документооборота
..Ресурсы..
ТипКриптопровайдера : Типы крипто провайдеров
НомерОсновнойПоставки1с : Строка
КраткоеНаименование : Строка
ПолноеНаименование : Строка
ИНН : Строка
КПП : Строка
ОГРН : Строка
РегНомерПФР : Строка
РегНомерФСС : Строка
ЭлектроннаяПочта : Строка
ВладелецЭЦПФамилия : Строка
ВладелецЭЦПИмя : Строка
ВладелецЭЦПОтчество : Строка
ВладелецЭЦППодразделение : Строка
ВладелецЭЦПСНИЛС : Строка
ВладелецЭЦПДолжность : Строка
ТелефонМобильный : Строка
ТелефонОсновной : Строка
ТелефонДополнительный : Строка
ПриЗаполненииРегистраСертификатБылДоступен : Булево
КодРегионаФСРАР : Строка
..Реквизиты..
ОтпечатокСертификата : Строка
ДатаОбновления : Дата
}
@enduml
