@startuml СтавкиНалогаНаИмущество
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтавкиНалогаНаИмущество as "Ставки налога на имущество" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
НалоговаяСтавка : Число 3, 2
ОсвобождениеОтНалогообложения : Булево
КодНалоговойЛьготыОсвобождениеОтНалогообложения : Строка
СнижениеНалоговойСтавки : Булево
СниженнаяНалоговаяСтавка : Число 3, 2
УменьшениеСуммыНалогаВПроцентах : Булево
ПроцентУменьшения : Число 5, 2
ПриНаличии1ЛьготыЗаполнять1ЛистРаздела2 : Булево
}
@enduml
