@startuml ПакетыИнформацииПриЗапуске
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПакетыИнформацииПриЗапуске as "Пакеты информации при запуске" <<РегистрыСведений>>
{
..Измерения..
Номер : Число 10, 0
..Ресурсы..
Состав : Хранилище значения
}
@enduml
