@startuml УдалитьАдресныйКлассификатор
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьАдресныйКлассификатор as "(не используется) Адресный классификатор" <<РегистрыСведений>>
{
..Измерения..
ТипАдресногоЭлемента : Число 1, 0
КодАдресногоОбъектаВКоде : Число 2, 0
КодРайонаВКоде : Число 3, 0
КодГородаВКоде : Число 3, 0
КодНаселенногоПунктаВКоде : Число 3, 0
КодУлицыВКоде : Число 4, 0
Код : Число 21, 0
..Ресурсы..
Наименование : Строка
Сокращение : Строка
Индекс : Строка
АльтернативныеНазвания : Строка
ПризнакАктуальности : Число 2, 0
}
@enduml
