@startuml СвязанныеОбъектыОбменСБанками
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СвязанныеОбъектыОбменСБанками as "Связанные объекты обмена с банками" <<РегистрыСведений>>
{
..Измерения..
СсылкаНаОбъект : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
СообщениеОбмена : Документ.Сообщение обмена с банками
}
@enduml
