@startuml СвязиМеждуПартнерами
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СвязиМеждуПартнерами as "Связи между партнерами" <<РегистрыСведений>>
{
..Измерения..
ПервыйПартнер : Справочник.Партнер
ВторойПартнер : Справочник.Партнер
ВидСвязи : Справочник.Вид связи между партнерами
..Реквизиты..
Автор : Справочник.Пользователь
Комментарий : Строка
}
@enduml
