@startuml НаработкиТМЦВЭксплуатации
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НаработкиТМЦВЭксплуатации as "Наработки ТМЦ в эксплуатации" <<РегистрыСведений>>
{
..Измерения..
ИнвентарныйНомер : Строка
..Ресурсы..
Значение : Число 15, 3
ПредельныйОбъем : Число 15, 3
}
@enduml
