@startuml ЛицевыеСчетаСотрудниковПоЗарплатнымПроектам
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЛицевыеСчетаСотрудниковПоЗарплатнымПроектам as "Лицевые счета сотрудников по зарплатным проектам" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
Банк : Справочник.Банк
УдалитьБанк : Строка
..Ресурсы..
НомерЛицевогоСчета : Строка
ЗарплатныйПроект : Справочник.Зарплатный проект
..Реквизиты..
ДокументОснование : Документ.Подтверждение открытия счетов
}
@enduml
