@startuml ОсновныеДанныеКонтрактаДоговораСотрудника
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОсновныеДанныеКонтрактаДоговораСотрудника as "Основные данные контракта, договора сотрудника" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ГоловнаяОрганизация : Справочник.Организация
..Ресурсы..
ДатаДоговораКонтракта : Дата
НомерДоговораКонтракта : Строка
ДатаНачала : Дата
..Реквизиты..
ПоступлениеНаСлужбуВпервые : Булево
}
@enduml
