@startuml СведенияРеглОтчетАлкоЛицензии
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СведенияРеглОтчетАлкоЛицензии as "Сведения регл отчет алко лицензии" <<РегистрыСведений>>
{
..Измерения..
Документ : Документ.Регламентированный отчет
УдалитьИндексСтраницы : Число 10, 0
ИндексСтроки : Число 10, 0
ИДДокИндСтраницы : Строка
Организация : Справочник.Организация
..Ресурсы..
П000000000201 : Строка
П000000000202 : Строка
П000000000203 : Строка
П000000000204 : Строка
П000000000205 : Строка
П000000000206 : Строка
П000000000207 : Строка
..Реквизиты..
Активно : Булево
П0000000VNUTR : Строка
П0000000Адрес : Строка
}
@enduml
