@startuml СпособыОтраженияРасходовПоАмортизацииНМАБухгалтерскийУчет
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СпособыОтраженияРасходовПоАмортизацииНМАБухгалтерскийУчет as "Способы отражения расходов по амортизации НМА (бухгалтерский учет)" <<РегистрыСведений>>
{
..Измерения..
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
Организация : Справочник.Организация
..Ресурсы..
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
СпособОтраженияРасходовЗаданДокументом : Булево
СпособОтраженияРасходов : Документ.Изменение параметров НМА
ПередаватьРасходыВДругуюОрганизацию : Булево
ОрганизацияПолучательРасходов : Справочник.Организация
СчетПередачиРасходов : Счет бухгалтерского учета
}
@enduml
