@startuml ОчередьРасходаТоваровОрганизацийНаПроизводство
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОчередьРасходаТоваровОрганизацийНаПроизводство as "Задания к распределению товаров организаций на производство" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Разделитель : Число 10, 0
ЭтапПроизводства : Документ.Этап производства
ПериодЗаполнения : Дата
}
@enduml
