@startuml АрхивДанныхРегламентированнойОтчетности
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.АрхивДанныхРегламентированнойОтчетности as "Архив данных регламентированной отчетности" <<РегистрыСведений>>
{
..Измерения..
Объект : Документ.Выгрузка регламентированных отчетов
..Ресурсы..
Данные : Строка
..Реквизиты..
ОписаниеДанных : Строка
}
@enduml
