@startuml ПараметрыЦелевогоФинансированияНМА
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПараметрыЦелевогоФинансированияНМА as "Параметры целевого финансирования НМА" <<РегистрыСведений>>
{
..Измерения..
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
..Ресурсы..
ПрименениеЦелевогоФинансирования : Булево
СчетУчета : Счет бухгалтерского учета
СчетАмортизации : Счет бухгалтерского учета
СтатьяДоходов : Статьи доходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
}
@enduml
