@startuml СостоянияОбменСБанками
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияОбменСБанками as "Состояния обмена с банками" <<РегистрыСведений>>
{
..Измерения..
СсылкаНаОбъект : Документ.Заявка на открытие лицевых счетов\rСправочник.Настройка обмена с банком\rДокумент.Списание безналичных ДС\r...
..Ресурсы..
Состояние : Состояния прямого обмена с банками
СообщениеОбмена : Документ.Сообщение обмена с банками
..Реквизиты..
ПредставлениеСостояния : Строка
}
@enduml
