@startuml РеестрКадровыхПриказов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РеестрКадровыхПриказов as "Реестр кадровых приказов" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
Организация : Справочник.Организация
ДокументОснование : Документ.Кадровый перевод\rДокумент.Увольнение\rДокумент.Перемещение в другое подразделение\r...
Номер : Число 10, 0
..Ресурсы..
Дата : Дата
Подразделение : Справочник.Подразделение\rСтрока
Должность : Справочник.Должность\rСтрока
Разряд : Строка\rСправочник.Квалификационный разряд (категория)
ТарифнаяСтавкаНадбавка : Строка
ВидДоговора : Виды договоров с сотрудниками
ВидСобытия : Виды кадровых событий
ДатаПриказа : Дата
НомерПриказа : Строка
Основание : Строка
}
@enduml
