@startuml КлючевыеВидыРабочихЦентров
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КлючевыеВидыРабочихЦентров as "Ключевые виды рабочих центров" <<РегистрыСведений>>
{
..Измерения..
ВидРабочегоЦентра : Справочник.Вид рабочего центра
ПериодРаботы : Дата
..Ресурсы..
Ключевой : Булево
}
@enduml
