@startuml ЗначенияПериодическихПоказателейРасчетаЗарплатыПодразделений
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗначенияПериодическихПоказателейРасчетаЗарплатыПодразделений as "Значения периодических показателей расчета зарплаты (для подразделений)" <<РегистрыСведений>>
{
..Измерения..
Подразделение : Справочник.Подразделение
Показатель : Справочник.Показатель
Организация : Справочник.Организация
..Ресурсы..
Значение : Число 15, 5
ДействуетДо : Дата
ЗначениеПоОкончании : Число 15, 5
}
@enduml
