@startuml СведенияРеглОтчетАлкоПрил13Декларация
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СведенияРеглОтчетАлкоПрил13Декларация as "Сведения регл отчет алко прил13 декларация" <<РегистрыСведений>>
{
..Измерения..
Документ : Документ.Регламентированный отчет
УдалитьИндексСтраницы : Число 10, 0
ИндексСтроки : Число 10, 0
ИДДокИндСтраницы : Строка
Организация : Справочник.Организация
..Ресурсы..
П000010000305 : Строка
П0000100003051 : Строка
П000010000306 : Строка
П000010000307 : Строка
П000010000304 : Число 15, 5
..Реквизиты..
ХешИдПолучателя : Строка
Получатель : Справочник.Контрагент
Активно : Булево
}
@enduml
