@startuml ДополнительныеСведения
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДополнительныеСведения as "Дополнительные сведения" <<РегистрыСведений>>
{
..Измерения..
Объект : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
Свойство : Дополнительный реквизит / сведение
..Ресурсы..
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
}
@enduml
