@startuml РасчетСтавкиНалогаНаПрибыльЗаМесяц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РасчетСтавкиНалогаНаПрибыльЗаМесяц as "Расчет ставки налога на прибыль за месяц" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ПериодРасчета : Дата
..Ресурсы..
Ставка : Число 8, 6
СуммаНалога : Число 18, 2
СуммаБазы : Число 18, 2
}
@enduml
