@startuml ОплаченныеДоговоры
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОплаченныеДоговоры as "Оплаченные договоры" <<РегистрыСведений>>
{
..Измерения..
МесяцНачисления : Дата
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ДоговорАкт : Документ.Договор авторского заказа\rДокумент.Акт приемки выполненных работ\rДокумент.Договор (работы, услуги)
}
@enduml
