@startuml ОбластиДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОбластиДанных as "Области данных" <<РегистрыСведений>>
{
..Ресурсы..
Статус : Статусы областей данных
..Реквизиты..
Вариант : Строка
ИдентификаторВыгрузки : Уникальный идентификатор
ОшибкаОбработки : Булево
Повтор : Число 2, 0
}
@enduml
