@startuml ТарифыВзносовЗаЗанятыхНаРаботахСДосрочнойПенсией
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ТарифыВзносовЗаЗанятыхНаРаботахСДосрочнойПенсией as "Тарифы взносов за занятых на работах с досрочной пенсией" <<РегистрыСведений>>
{
..Ресурсы..
ЗаЗанятыхНаПодземныхИВредныхРаботах : Число 5, 2
ЗаЗанятыхНаТяжелыхИПрочихРаботах : Число 5, 2
}
@enduml
