@startuml ПлановыеАвансыИнтервальный
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПлановыеАвансыИнтервальный as "Плановые авансы интервальный" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ДатаОкончания : Дата
ДатаНачала : Дата
ФизическоеЛицо : Справочник.Физическое лицо
ГоловнаяОрганизация : Справочник.Организация
ПериодЗаписи : Дата
Год : Дата
..Ресурсы..
ПериодПредыдущейЗаписи : Дата
ДействуетДо : Дата
СпособРасчетаАванса : Способы расчета аванса
Аванс : Число 15, 2
..Реквизиты..
РегистраторЗаписи : Документ.Изменение аванса\rДокумент.Изменение условий оплаты отпуска по уходу за ребенком\rДокумент.Изменение оплаты труда\r...
РегистраторСобытия : Документ.Изменение аванса\rДокумент.Изменение условий оплаты отпуска по уходу за ребенком\rДокумент.Изменение оплаты труда\r...
ПустойИнтервал : Булево
}
@enduml
