@startuml Форма57ТРаздел2Сотрудники
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.Форма57ТРаздел2Сотрудники as "Раздел 2, форма 57-Т" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ПериодОтчета : Дата
Сотрудник : Справочник.Сотрудник
..Ресурсы..
НомерСтрокиОтчета : Число 2, 0
}
@enduml
