@startuml СтандартныеВычетыФизическихЛицНДФЛИспр
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтандартныеВычетыФизическихЛицНДФЛИспр as "Стандартные вычеты физических лиц по НДФЛ испр" <<РегистрыСведений>>
{
..Измерения..
РегистраторИзмерение : Документ.Увольнение\rДокумент.Отмена стандартных вычетов НДФЛ\rДокумент.Увольнение списком\r...
ПериодИзмерение : Дата
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
КодВычетаЛичный : Справочник.Вид вычетов НДФЛ
УдалитьКодВычетаЛичный : Справочник.(не используется) Виды вычетов НДФЛ
..Реквизиты..
Основание : Строка
}
@enduml
