@startuml ЗаданияКРасчетуСебестоимости
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗаданияКРасчетуСебестоимости as "Задания к расчету себестоимости" <<РегистрыСведений>>
{
..Измерения..
Месяц : Дата
НомерЗадания : Число 15, 0
Организация : Справочник.Организация
Документ : Документ.Сторнирование начислений\rДокумент.Внутреннее потребление товаров\rДокумент.Назначение планового начисления\r...
}
@enduml
