@startuml БухучетЗарплатыПервичныхДокументов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.БухучетЗарплатыПервичныхДокументов as "Бухучет зарплаты первичных документов" <<РегистрыСведений>>
{
..Измерения..
ДокументОснование : Документ.Единовременное пособие\rДокумент.Приз, подарок\rДокумент.Выплата бывшим сотрудникам\r...
НачислениеУдержание : Справочник.Вид выплаты бывшему сотруднику\rСправочник.Вид прочего дохода\rВиды особых начислений и удержаний\r...
УдалитьСотрудник : Справочник.Сотрудник
..Ресурсы..
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
ОтношениеКЕНВД : Отношение к ЕНВД затрат на зарплату
УдалитьОблагаетсяЕНВД : Булево
}
@enduml
