@startuml ПараметрыАмортизацииОСБУ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПараметрыАмортизацииОСБУ as "Параметры амортизации ОС (бухгалтерский и налоговый учет)" <<РегистрыСведений>>
{
..Измерения..
ОсновноеСредство : Справочник.Объект эксплуатации
Организация : Справочник.Организация
..Ресурсы..
СрокПолезногоИспользованияБУ : Число 4, 0
СрокПолезногоИспользованияНУ : Число 4, 0
КоэффициентАмортизацииБУ : Число 4, 2
КоэффициентУскорения : Число 5, 2
ОбъемПродукцииРаботДляВычисленияАмортизации : Число 10, 0
ПРДляВычисленияАмортизации : Число 15, 2
СрокИспользованияДляВычисленияАмортизации : Число 4, 0
СтоимостьДляВычисленияАмортизации : Число 15, 2
ДатаПоследнегоИзменения : Дата
}
@enduml
