@startuml СостоянияОбменовССайтом
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияОбменовССайтом as "Состояния обменов с сайтом" <<РегистрыСведений>>
{
..Измерения..
НастройкаОбменаССайтом : Узел обмена с сайтом
ДействиеПриОбмене : Действия при обмене с сайтом
..Ресурсы..
РезультатВыполненияОбмена : Результаты обмена с сайтом
ДатаНачала : Дата
ДатаОкончания : Дата
}
@enduml
