@startuml РассчитанныеОтборыПоНовостям_Пользовательские
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РассчитанныеОтборыПоНовостям_Пользовательские as "Рассчитанные отборы по новостям (пользовательские)" <<РегистрыСведений>>
{
..Измерения..
Пользователь : Справочник.Пользователь
Новость : Справочник.Новость
..Реквизиты..
РезультатОтбора : Булево
}
@enduml
