@startuml ИндексыСПАРКРиски
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИндексыСПАРКРиски as "Кэш индексов 1СПАРК Риски" <<РегистрыСведений>>
{
..Измерения..
Контрагент : Справочник.Контрагент
..Ресурсы..
ИндексДолжнойОсмотрительности : Число 3, 0
ИндексПлатежнойДисциплины : Число 3, 0
ИндексФинансовогоРиска : Число 3, 0
Активен : Булево
ТекстСтатуса : Строка
ДатаСтатуса : Дата
КодСтатуса : Число 10, 0
ИдентификаторСобытия : Строка
ИдентификаторТипаСобытия : Строка
ДатаСобытия : Дата
ЗначениеСтарое : Строка
ЗначениеНовое : Строка
ВидОшибки : Виды ошибок 1СПАРК Риски
ТекстОшибки : Строка
..Реквизиты..
ИНН : Строка
ДатаОбновления : Дата
}
@enduml
