@startuml РазмерВычетовНДФЛ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РазмерВычетовНДФЛ as "Размер вычетов НДФЛ" <<РегистрыСведений>>
{
..Измерения..
КодВычета : Справочник.Вид вычетов НДФЛ
..Ресурсы..
Размер : Число 10, 0
ОграничениеПоДоходам : Число 10, 0
}
@enduml
