@startuml ПрогнозныеКурсыСценариев
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПрогнозныеКурсыСценариев as "Прогнозные курсы сценариев" <<РегистрыСведений>>
{
..Измерения..
Сценарий : Справочник.Сценарии бюджетирования
Валюта : Справочник.Валюта
..Ресурсы..
Курс : Число 10, 4
Кратность : Число 10, 0
}
@enduml
