@startuml ОбъектыПроблемСостоянияСистемы
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОбъектыПроблемСостоянияСистемы as "Объекты проблем состояния учета" <<РегистрыСведений>>
{
..Измерения..
Проверка : Справочник.Проверка
Организация : Справочник.Организация
ПроверяемыйПериод : Дата
Проблема : Уникальный идентификатор
Объект : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
СоставнойОбъект : Уникальный идентификатор
..Реквизиты..
Представление : Строка
ЭтоСоставнойОбъект : Булево
РасшифровкаСоставногоОбъекта : Хранилище значения
}
@enduml
