@startuml ГрафикОплатКредитовИДепозитов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ГрафикОплатКредитовИДепозитов as "График оплат" <<РегистрыСведений>>
{
..Измерения..
ВариантГрафика : Справочник.Вариант графика
..Ресурсы..
Сумма : Число 15, 2
Проценты : Число 15, 2
Комиссия : Число 15, 2
}
@enduml
