@startuml ПервоначальныеСведенияОСНалоговыйУчет
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПервоначальныеСведенияОСНалоговыйУчет as "Первоначальные сведения ОС (налоговый учет, версия 2.2)" <<РегистрыСведений>>
{
..Измерения..
ОсновноеСредство : Справочник.Объект эксплуатации
..Ресурсы..
АмортизацияДо2002 : Число 15, 2
АмортизацияДо2009 : Число 15, 2
МетодНачисленияАмортизации : Методы начисления амортизации
Организация : Справочник.Организация
ПервоначальнаяСтоимостьНУ : Число 15, 2
ПорядокВключенияСтоимостиВСоставРасходов : Порядок включения стоимости основных средств в состав расходов (НУ)
СтоимостьДо2002 : Число 15, 2
ФактическийСрокИспользованияДо2009 : Число 4, 0
}
@enduml
