@startuml ОчередьИнсталляцииПоставляемыхДополнительныхОтчетовИОбработокВОбластиДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОчередьИнсталляцииПоставляемыхДополнительныхОтчетовИОбработокВОбластиДанных as "Очередь инсталляции поставляемых дополнительных отчетов и обработок в области данных" <<РегистрыСведений>>
{
..Измерения..
ПоставляемаяОбработка : Справочник.Поставляемый дополнительный отчет или обработка
..Ресурсы..
ПараметрыИнсталляции : Хранилище значения
}
@enduml
