@startuml УчетнаяПолитикаОрганизаций
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УчетнаяПолитикаОрганизаций as "Учетная политика" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
ПлательщикЕНВД : Булево
УчетнаяПолитика : Справочник.Учетная политика организации
ПрименяетсяПБУ18 : Булево
ПлательщикНалогаНаПрибыль : Булево
ПрименяетсяУСН : Булево
ПрименяетсяУСНДоходыМинусРасходы : Булево
}
@enduml
