@startuml КоэффициентИндексацииЗаработка
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КоэффициентИндексацииЗаработка as "Коэффициент индексации заработка" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
..Ресурсы..
Коэффициент : Число 12, 10
}
@enduml
