@startuml СтажиФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтажиФизическихЛиц as "Стажи" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
ВидСтажа : Справочник.Вид стажа
..Ресурсы..
ДатаОтсчета : Дата
РазмерМесяцев : Число 3, 0
РазмерДней : Число 2, 0
ИсчисляетсяСДатыПриема : Булево
Прерван : Булево
}
@enduml
