@startuml СоставыГруппПользователей
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СоставыГруппПользователей as "Составы групп пользователей" <<РегистрыСведений>>
{
..Измерения..
ГруппаПользователей : Справочник.Внешний пользователь\rСправочник.Пользователь\rСправочник.Группа внешних пользователей\r...
Пользователь : Справочник.Внешний пользователь\rСправочник.Пользователь
..Ресурсы..
Используется : Булево
}
@enduml
