@startuml ДоступныеЛицензии
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДоступныеЛицензии as "Доступные лицензии" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторПодписки : Уникальный идентификатор
Услуга : Справочник.Услуги сервиса
..Ресурсы..
ДатаНачалаДействия : Дата
ДатаОкончанияДействия : Дата
КоличествоЛицензий : Число 10, 0
НомерПодписки : Строка
..Реквизиты..
ДатаИзменения : Дата
}
@enduml
