@startuml СообщенияОбменаДанными
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СообщенияОбменаДанными as "Сообщения обмена данными" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторСообщения : Строка
..Ресурсы..
ИмяФайлаСообщения : Строка
ДатаЗакладкиСообщения : Дата
}
@enduml
