@startuml СреднемесячныеНормыВремениГрафиковРаботыСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СреднемесячныеНормыВремениГрафиковРаботыСотрудников as "Среднемесячные нормы времени графиков работы сотрудников" <<РегистрыСведений>>
{
..Измерения..
ГрафикРаботыСотрудников : Справочник.График работы
Год : Число 4, 0
..Ресурсы..
СреднемесячноеЧислоЧасов : Число 8, 5
СреднемесячноеЧислоДней : Число 6, 3
..Реквизиты..
УстановленыВРучную : Булево
}
@enduml
