@startuml АналитикаУчетаПартийПроизводства
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.АналитикаУчетаПартийПроизводства as "Аналитика учета партий производства" <<РегистрыСведений>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Спецификация : Справочник.Ресурсная спецификация
Назначение : Справочник.Назначение
..Ресурсы..
КлючАналитики : Справочник.Ключ аналитики учета партий производства
}
@enduml
