@startuml ИспользованиеПоставляемыхДополнительныхОтчетовИОбработокВОбластяхДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИспользованиеПоставляемыхДополнительныхОтчетовИОбработокВОбластяхДанных as "Использование поставляемых дополнительных отчетов и обработок в областях данных" <<РегистрыСведений>>
{
..Измерения..
ПоставляемаяОбработка : Справочник.Поставляемый дополнительный отчет или обработка
..Ресурсы..
ИспользуемаяОбработка : Справочник.Дополнительный отчет или обработка
}
@enduml
