@startuml ПредставленияОснованийУвольнения
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПредставленияОснованийУвольнения as "Представления оснований увольнения" <<РегистрыСведений>>
{
..Измерения..
Объект : Справочник.Основание увольнения\rСправочник.Основание заключения срочного трудового договора
..Ресурсы..
Использовать : Булево
Наименование : Строка
ТекстОснования : Строка
}
@enduml
