@startuml СведенияРеглОтчетАлкоЖурнал
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СведенияРеглОтчетАлкоЖурнал as "Сведения регл отчет алко журнал" <<РегистрыСведений>>
{
..Измерения..
Документ : Документ.Регламентированный отчет
ИмяРегистра : Строка
ИндексСтраницыРегистра : Число 10, 0
ИндексСтроки : Число 10, 0
Действие : Число 2, 0
Организация : Справочник.Организация
..Ресурсы..
КоличествоСтрок : Число 10, 0
НачальноеЗначение : Строка
МаксИндексСтраницы : Число 10, 0
}
@enduml
