@startuml ЗаработанныеПраваНаОтпуска
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗаработанныеПраваНаОтпуска as "Заработанные права на отпуска" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ВидЕжегодногоОтпуска : Справочник.Вид отпуска
..Ресурсы..
КоличествоДней : Число 6, 2
..Реквизиты..
ДатаНачала : Дата
ДатаОкончания : Дата
КоличествоДнейЗаПериод : Число 8, 5
}
@enduml
