@startuml СведенияРеглОтчетАлкоПрил11Раздел2
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СведенияРеглОтчетАлкоПрил11Раздел2 as "Сведения регл отчет алко прил11 раздел2" <<РегистрыСведений>>
{
..Измерения..
Документ : Документ.Регламентированный отчет
УдалитьИндексСтраницы : Число 10, 0
ИндексСтроки : Число 10, 0
ИДДокИндСтраницы : Строка
Организация : Справочник.Организация
..Ресурсы..
П000020000301 : Строка
П000020000302 : Строка
П000020000303 : Строка
П000020000304 : Строка
П000020000305 : Строка
П000020000306 : Строка
П000020000307 : Строка
П000020000308 : Строка
П000020000391 : Строка
П000020000392 : Строка
П000020000310 : Дата
П000020000311 : Дата
П000020000312 : Строка
П000020000313 : Дата
П000020000314 : Строка
П000020000315 : Строка
П000020000316 : Число 15, 5
..Реквизиты..
ХешИдКодПродПроизв : Строка
ХешИдПоставщика : Строка
ХешИдЛицензии : Строка
ПроизводительИмпортер : Справочник.Контрагент
ДокументПоступления : Документ.Сторнирование начислений\rДокумент.Внутреннее потребление товаров\rДокумент.Назначение планового начисления\r...
Поставщик : Справочник.Контрагент
Активно : Булево
}
@enduml
