@startuml ПервоначальныеСведенияНМАНалоговыйУчет
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПервоначальныеСведенияНМАНалоговыйУчет as "Первоначальные сведения о НМА и НИОКР (налоговый учет)" <<РегистрыСведений>>
{
..Измерения..
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
..Ресурсы..
АмортизацияДо2002 : Число 15, 2
АмортизацияДо2009 : Число 15, 2
ДатаПриобретения : Дата
МетодНачисленияАмортизации : Методы начисления амортизации
НачислятьАмортизацию : Булево
Организация : Справочник.Организация
ПервоначальнаяСтоимостьНУ : Число 15, 2
СрокПолезногоИспользования : Число 4, 0
СтоимостьДо2002 : Число 15, 2
ФактическийСрокИспользованияДо2009 : Число 4, 0
ПорядокУчетаНУ : Порядок включения стоимости основных средств в состав расходов (НУ)
}
@enduml
