@startuml РасчетТранспортногоНалога
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РасчетТранспортногоНалога as "Расчет транспортного налога" <<РегистрыСведений>>
{
..Измерения..
ПериодРасчета : Дата
Организация : Справочник.Организация
ИФНС : Справочник.Регистрация в налоговом органе
КодПоОКТМО : Строка
ОсновноеСредство : Справочник.Объект эксплуатации
ДатаРегистрационныхДанных : Дата
..Ресурсы..
КодВидаТранспортногоСредства : Строка
ИдентификационныйНомер : Строка
Марка : Строка
РегистрационныйЗнак : Строка
НалоговаяБаза : Число 17, 2
ЕдиницаИзмерения : Строка
КоличествоМесяцевВладения : Число 2, 0
НалоговаяСтавка : Число 8, 2
СуммаНалога : Число 15, 0
КоличествоМесяцевЛьготы : Число 2, 0
КодНалоговойЛьготы : Строка
РегиональныйКодЛьготы : Строка
ПроцентУменьшения : Число 4, 2
ЛьготнаяСтавка : Число 8, 2
СуммаНалоговойЛьготы : Число 15, 0
СуммаНалогаКУплате : Число 15, 0
ЭкологическийКласс : Строка
СуммаАвансовыхПлатежей1Кв : Число 15, 0
СуммаАвансовыхПлатежей2Кв : Число 15, 0
СуммаАвансовыхПлатежей3Кв : Число 15, 0
ПовышающийКоэффициент : Число 3, 1
КоличествоЛетПрошедшихСГодаВыпускаТС : Число 3, 0
ДоляВПравеОбщейСобственностиЧислитель : Число 10, 0
ДоляВПравеОбщейСобственностиЗнаменатель : Число 10, 0
ЗарегистрированоВРеестреСистемыПлатон : Булево
СуммаНалоговогоВычета : Число 15, 2
ДатаРегистрации : Дата
ДатаПрекращенияРегистрации : Дата
СуммаПлатыОператоруСистемыПлатон : Число 15, 2
}
@enduml
