@startuml ОграниченныеДокументы
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОграниченныеДокументы as "Ограниченные документы" <<РегистрыСведений>>
{
..Измерения..
Документ : Документ.Ведомость через раздатчика\rДокумент.Ведомость прочих доходов в кассу\rДокумент.Ведомость на счета\r...
}
@enduml
