@startuml СодержимоеТранспортныхКонтейнеров
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СодержимоеТранспортныхКонтейнеров as "Содержимое транспортных контейнеров" <<РегистрыСведений>>
{
..Измерения..
ТранспортноеСообщение : Документ.Транспортное сообщение
ИмяФайла : Строка
..Ресурсы..
Данные : Хранилище значения
..Реквизиты..
Тип : Типы содержимого транспортного контейнера
Размер : Число 10, 0
ЭЦПСертификат : Строка
ЭЦПСтатусПроверки : Статусы проверки ЭЦП
ЭЦПИмяПодписанногоФайла : Строка
ЭЦПЭтоПодписьАбонента : Булево
ТипФайлаОтчетностиПФР : (не используется) Типы файлов отчетности ПФР\rТипы файлов отчетности ПФР
Идентификатор : Строка
ТипСодержимогоФайла : Типы содержимого файлов\r(не используется) Типы содержимого файлов
}
@enduml
