@startuml ПотребностьВСпециалистахНаПериодМобилизации
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПотребностьВСпециалистахНаПериодМобилизации as "Потребность в специалистах на период мобилизации" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Год : Число 4, 0
КатегорияВоинскогоУчета : Категории должностей для учета забронированных\rКатегории должностей для воинского учета
..Ресурсы..
Количество : Число 10, 0
}
@enduml
