@startuml ABCXYZКлассификацияНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ABCXYZКлассификацияНоменклатуры as "ABC/XYZ классификация номенклатуры" <<РегистрыСведений>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
РазделКлассификации : Справочник.Организация\rСправочник.Подразделение\rСправочник.Склад (складская территория)
ТипПараметраКлассификации : Типы параметров классификации
ТипКлассификации : Типы классификации
..Ресурсы..
Класс : XYZ Классификация\rABC Классификация
ЗначениеПараметраКлассификации : Число 15, 2
}
@enduml
