@startuml СтавкаРефинансированияЦБ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтавкаРефинансированияЦБ as "Ставка рефинансирования ЦБ" <<РегистрыСведений>>
{
..Ресурсы..
Размер : Число 5, 2
}
@enduml
