@startuml РазмещениеНоменклатурыПоСкладскимЯчейкам
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РазмещениеНоменклатурыПоСкладскимЯчейкам as "Размещение номенклатуры по складским ячейкам" <<РегистрыСведений>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
Склад : Справочник.Склад (складская территория)
Помещение : Справочник.Помещение
Ячейка : Справочник.Складская ячейка
..Ресурсы..
ОсновнаяЯчейка : Булево
}
@enduml
