@startuml РасчетНалогаНаИмущество
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РасчетНалогаНаИмущество as "Расчет налога на имущество" <<РегистрыСведений>>
{
..Измерения..
ПериодРасчета : Дата
Организация : Справочник.Организация
ВидНалоговойБазы : Налоговая база по налогу на имущество
ИФНС : Справочник.Регистрация в налоговом органе
КодПоОКТМО : Строка
КодВидаИмущества : Строка
ОсновноеСредство : Справочник.Объект эксплуатации
НалоговаяСтавка : Число 3, 2
КодНалоговойЛьготыОсвобождениеОтНалогообложения : Строка
ПонижениеНалоговойСтавки : Булево
КБК : Строка
..Ресурсы..
ДоляСтоимостиЗнаменатель : Число 10, 0
ДоляСтоимостиЧислитель : Число 10, 0
КадастроваяСтоимость : Число 15, 0
КадастровыйНомер : Строка
КадастровыйНомерПомещения : Строка
КоличествоМесяцевВладения : Число 2, 0
НалоговаяБаза : Число 15, 2
НеоблагаемаяКадастроваяСтоимость : Число 15, 0
НеоблагаемаяСредняяСтоимость : Число 15, 2
ОстаточнаяСтоимостьНа0101 : Число 15, 2
ОстаточнаяСтоимостьНа0102 : Число 15, 2
ОстаточнаяСтоимостьНа0103 : Число 15, 2
ОстаточнаяСтоимостьНа0104 : Число 15, 2
ОстаточнаяСтоимостьНа0105 : Число 15, 2
ОстаточнаяСтоимостьНа0106 : Число 15, 2
ОстаточнаяСтоимостьНа0107 : Число 15, 2
ОстаточнаяСтоимостьНа0108 : Число 15, 2
ОстаточнаяСтоимостьНа0109 : Число 15, 2
ОстаточнаяСтоимостьНа0110 : Число 15, 2
ОстаточнаяСтоимостьНа0111 : Число 15, 2
ОстаточнаяСтоимостьНа0112 : Число 15, 2
ОстаточнаяСтоимостьНа3112 : Число 15, 2
ОстаточнаяСтоимостьНедвижимости : Число 15, 2
ОстаточнаяСтоимостьОсновныхСредств : Число 15, 2
СредняяСтоимость : Число 15, 2
СуммаАвансовыхПлатежей : Число 15, 2
СуммаНалога : Число 15, 2
СуммаНалогаКУплате : Число 15, 2
СуммаУменьшенияСуммыНалога : Число 15, 2
УдалитьКодНалоговойЛьготыОсвобождениеОтНалогообложения : Строка
УдалитьНалоговаяСтавка : Число 3, 2
УдалитьПонижениеНалоговойСтавки : Булево
ДоляВПравеОбщейСобственностиЧислитель : Число 10, 0
ДоляВПравеОбщейСобственностиЗнаменатель : Число 10, 0
УсловныйНомер : Строка
ДоляПлощадиЧислитель : Число 10, 0
ДоляПлощадиЗнаменатель : Число 10, 0
}
@enduml
