@startuml ТикетыОбменСБанками
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ТикетыОбменСБанками as "Тикеты обмен с банками" <<РегистрыСведений>>
{
..Измерения..
НастройкаОбмена : Справочник.Настройка обмена с банком\rСправочник.Настройка ЭДО
Идентификатор : Строка
ВидЭД : Виды электронных документов обмена с банками
}
@enduml
