@startuml КвотыАссортимента
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КвотыАссортимента as "Квоты ассортимента" <<РегистрыСведений>>
{
..Измерения..
ТоварнаяКатегория : Справочник.Товарные категории
ОбъектПланирования : Справочник.Форматы магазинов\rСправочник.Склад (складская территория)
Марка : Справочник.Марка (бренд)
КоллекцияНоменклатуры : Справочник.Коллекция (сезон)
..Ресурсы..
Квота : Число 10, 0
ПроцентОтклонения : Число 3, 0
}
@enduml
