@startuml ПрименениеРазрешенийНаИспользованиеВнешнихРесурсовВМоделиСервиса
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПрименениеРазрешенийНаИспользованиеВнешнихРесурсовВМоделиСервиса as "Применение разрешений на использование внешних ресурсов в модели сервиса" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторПакета : Уникальный идентификатор
..Реквизиты..
Состояние : Строка
Результат : Результаты обработки запросов на использование внешних ресурсов в модели сервиса
}
@enduml
