@startuml ЗаданияКОбработкеЭтаповПроизводства
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗаданияКОбработкеЭтаповПроизводства as "Задания к обработке этапов производства" <<РегистрыСведений>>
{
..Измерения..
ЭтапПроизводства : Документ.Этап производства
Идентификатор : Уникальный идентификатор
ДеньРегистрации : Число 7, 0
УдалитьНомерЗадания : Число 15, 0
..Реквизиты..
ОбновитьСостояние : Булево
ЗаполнитьПоОперациям : Булево
}
@enduml
