@startuml СведенияОЛьготахФизическихЛицПострадавшихВАварииЧАЭС
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СведенияОЛьготахФизическихЛицПострадавшихВАварииЧАЭС as "Сведения о льготах физических лиц пострадавших в аварии ЧАЭС" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
КоличествоДнейОтпуска : Число 2, 0
}
@enduml
