@startuml НормативнаяДлительностьПроизводства
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НормативнаяДлительностьПроизводства as "Нормативная длительность производства" <<РегистрыСведений>>
{
..Измерения..
Спецификация : Справочник.Ресурсная спецификация
..Ресурсы..
Длительность : Число 10, 0
ОбщаяДлительность : Число 10, 0
..Реквизиты..
Предел : Число 15, 0
}
@enduml
