@startuml ЗаданияКРаспределениюРасчетовСПоставщиками
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗаданияКРаспределениюРасчетовСПоставщиками as "Задания к распределению расчетов с поставщиками" <<РегистрыСведений>>
{
..Измерения..
Месяц : Дата
НомерЗадания : Число 15, 0
Организация : Справочник.Организация
АналитикаУчетаПоПартнерам : Справочник.Ключ аналитики учета по партнерам
ОбъектРасчетов : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
Документ : Документ.Сторнирование начислений\rДокумент.Внутреннее потребление товаров\rДокумент.Назначение планового начисления\r...
}
@enduml
