@startuml ПравилаРазмещенияТоваровВЯчейках
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПравилаРазмещенияТоваровВЯчейках as "Правила размещения товаров" <<РегистрыСведений>>
{
..Измерения..
СкладскаяГруппаНоменклатуры : Справочник.Складская группа номенклатуры
СкладскаяГруппаУпаковок : Справочник.Складская группа упаковок
Склад : Справочник.Склад (складская территория)
Помещение : Справочник.Помещение
ОбластьХранения : Справочник.Область хранения
..Ресурсы..
Приоритет : Число 3, 0
}
@enduml
