@startuml ПорядокУчетаОСБУ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПорядокУчетаОСБУ as "Порядок учета ОС (бухгалтерский и налоговый учет)" <<РегистрыСведений>>
{
..Измерения..
ОсновноеСредство : Справочник.Объект эксплуатации
Организация : Справочник.Организация
..Ресурсы..
Состояние : Состояния ОС
НачислятьАмортизациюБУ : Булево
НачислятьАмортизациюНУ : Булево
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
СтатьяРасходовАмортизационнойПремии : Статья расходов
АналитикаРасходовАмортизационнойПремии : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ПередаватьРасходыВДругуюОрганизацию : Булево
ОрганизацияПолучательРасходов : Справочник.Организация
СпособОтраженияРасходов : Документ.Изменение параметров ОС
СпособОтраженияРасходовАмортизационнойПремии : Документ.Изменение параметров ОС
НалогообложениеНДС : Типы налогообложения НДС
}
@enduml
