@startuml ЗаданияКПогашениюСтоимостиТМЦВЭксплуатации
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗаданияКПогашениюСтоимостиТМЦВЭксплуатации as "Задания к погашению стоимости ТМЦ в эксплуатации" <<РегистрыСведений>>
{
..Измерения..
Месяц : Дата
Организация : Справочник.Организация
НомерПакета : Число 10, 0
НомерЗадания : Число 15, 0
Документ : Документ.Сторнирование начислений\rДокумент.Внутреннее потребление товаров\rДокумент.Назначение планового начисления\r...
}
@enduml
