@startuml ОперацииДляДиспетчирования
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОперацииДляДиспетчирования as "Операции для диспетчирования" <<РегистрыСведений>>
{
..Измерения..
МаршрутныйЛист : Документ.Маршрутный лист производства
ИдентификаторОперации : Уникальный идентификатор
Начало : Дата
Окончание : Дата
РабочийЦентр : Строка\rСправочник.Рабочий центр
..Ресурсы..
СтатусВыполнения : Статусы выполнения операций
Загрузка : Число 15, 3
..Реквизиты..
Подразделение : Справочник.Подразделение
Штрихкод : Строка
}
@enduml
