@startuml СообщенияОбменаДаннымиОбластейДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СообщенияОбменаДаннымиОбластейДанных as "Сообщения обмена данными областей данных" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторСообщения : Строка
..Ресурсы..
ИмяФайлаСообщения : Строка
ДатаЗакладкиСообщения : Дата
}
@enduml
