@startuml НоменклатураСегмента
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НоменклатураСегмента as "Номенклатура сегмента" <<РегистрыСведений>>
{
..Измерения..
Сегмент : Справочник.Сегмент номенклатуры
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
}
@enduml
