@startuml ЗначенияПоказателейДоплатыЗаРаботуВНочноеВечернееВремя
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗначенияПоказателейДоплатыЗаРаботуВНочноеВечернееВремя as "Значения показателей доплаты за работу в ночное и вечернее время" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
ПроцентДоплатыЗаРаботуВНочноеВремя : Число 4, 0
ПроцентДоплатыЗаРаботуВВечернееВремя : Число 4, 0
}
@enduml
