@startuml РасчетРезерваОтпусков
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РасчетРезерваОтпусков as "Расчет резерва отпусков" <<РегистрыСведений>>
{
..Измерения..
ПериодРасчета : Дата
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
ФОТ : Число 12, 2
СтраховыеВзносы : Число 15, 2
СуммаРезерва : Число 15, 2
СуммаРезерваСтраховыхВзносов : Число 15, 2
ОстатокОтпуска : Число 5, 2
СреднийЗаработок : Число 15, 2
СуммаРезерваНУ : Число 15, 2
СуммаРезерваСтраховыхВзносовНУ : Число 15, 2
ТекущаяСтавкаСтраховыхВзносов : Число 7, 4
СуммаРезерваНакоплено : Число 15, 2
СуммаРезерваСтраховыхВзносовНакоплено : Число 15, 2
СуммаРезерваНакопленоНУ : Число 15, 2
СуммаРезерваСтраховыхВзносовНакопленоНУ : Число 15, 2
СуммаРезерваИсчислено : Число 15, 2
СуммаРезерваСтраховыхВзносовИсчислено : Число 15, 2
СуммаРезерваИсчисленоНУ : Число 15, 2
СуммаРезерваСтраховыхВзносовИсчисленоНУ : Число 15, 2
ФССНесчастныеСлучаи : Число 15, 2
СуммаРезерваФССНесчастныеСлучаи : Число 15, 2
СуммаРезерваФССНесчастныеСлучаиНУ : Число 15, 2
ТекущаяСтавкаФССНесчастныеСлучаи : Число 7, 4
СуммаРезерваФССНесчастныеСлучаиНакоплено : Число 15, 2
СуммаРезерваФССНесчастныеСлучаиНакопленоНУ : Число 15, 2
СуммаРезерваФССНесчастныеСлучаиИсчислено : Число 15, 2
СуммаРезерваФССНесчастныеСлучаиИсчисленоНУ : Число 15, 2
ОтпускАвансом : Число 5, 2
}
@enduml
