@startuml ПраваРолей
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПраваРолей as "Права ролей" <<РегистрыСведений>>
{
..Измерения..
ОбъектМетаданных : Справочник.Идентификатор объекта метаданных
Роль : Справочник.Идентификатор объекта метаданных
..Ресурсы..
Добавление : Булево
Изменение : Булево
ЧтениеБезОграничения : Булево
ДобавлениеБезОграничения : Булево
ИзменениеБезОграничения : Булево
Просмотр : Булево
ИнтерактивноеДобавление : Булево
Редактирование : Булево
}
@enduml
