@startuml КатегорииНовостейПростыеНеобработанные
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КатегорииНовостейПростыеНеобработанные as "Категории новостей (простые, необработанные)" <<РегистрыСведений>>
{
..Измерения..
КатегорияНовостейСтрока : Строка
ЗначениеКатегорииНовостейСтрока : Строка
ЛентаНовостей : Справочник.Лента новостей
УИННовости : Строка
..Реквизиты..
УсловиеОтбора : Строка
}
@enduml
