@startuml ДоступныеОстаткиПланируемыхПоступлений
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДоступныеОстаткиПланируемыхПоступлений as "Доступные остатки планируемых поступлений" <<РегистрыСведений>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Склад : Справочник.Склад (складская территория)
ДатаДоступности : Дата
..Ресурсы..
Количество : Число 15, 3
}
@enduml
