@startuml РасчетНормированияРасходов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РасчетНормированияРасходов as "Расчет нормирования расходов" <<РегистрыСведений>>
{
..Измерения..
ПериодРасчета : Дата
Организация : Справочник.Организация
ВидОперации : Виды расходов (НУ)
..Ресурсы..
ЗатратыГод : Число 15, 2
РасходыГод : Число 15, 2
РасходыМесяц : Число 12, 2
РазницыГод : Число 15, 2
РазницыМесяц : Число 12, 2
СуммаБазы : Число 15, 2
}
@enduml
