@startuml СведенияОРежимахРаботыФормыСотрудника
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СведенияОРежимахРаботыФормыСотрудника as "Сведения о режимах работы формы сотрудника" <<РегистрыСведений>>
{
..Измерения..
РежимРаботы : Режимы работы формы сотрудника
..Ресурсы..
ИспользоватьНачислениеЗарплатыВФормеСотрудника : Булево
ИспользоватьКадровыйУчетВФормеСотрудника : Булево
ИспользоватьНачислениеПоТрудовымДоговорамВФормеСотрудника : Булево
}
@enduml
