@startuml УдалитьПротоколОбменаЕГАИС
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьПротоколОбменаЕГАИС as "(не используется) Протокол обмена с ЕГАИС" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторСессииОбмена : Строка
..Ресурсы..
ТипЗапроса : Типы запросов ЕГАИС
ДатаЗапроса : Дата
ВидДокумента : Виды документов ЕГАИС
ПолученОтказ : Булево
ИдентификаторЗапроса : Строка
..Реквизиты..
ДокументОснование : Документ.Товарно-транспортная накладная ЕГАИС (входящая)\rДокумент.Товарно-транспортная накладная ЕГАИС (исходящая)\rДокумент.Акт постановки на баланс ЕГАИС\r...
Комментарий : Строка
ФайлОбмена : Хранилище значения
}
@enduml
