@startuml ПользователиУчетныхЗаписейДокументооборота
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПользователиУчетныхЗаписейДокументооборота as "Пользователи учетных записей документооборота" <<РегистрыСведений>>
{
..Измерения..
УчетнаяЗапись : Справочник.(не используется) Учетные записи документооборота\rСправочник.Учетные записи документооборота
Пользователь : Справочник.Пользователь
}
@enduml
