@startuml СоответствиеРегОтчетовУведомлениям
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СоответствиеРегОтчетовУведомлениям as "Соответствие рег.отчетов уведомлениям" <<РегистрыСведений>>
{
..Измерения..
РегОтчет : Документ.Регламентированный отчет
..Реквизиты..
Уведомление : Документ.Уведомление о спецрежимах налогообложения
}
@enduml
