@startuml УдалитьХранилищеЭлектронныхПредставленийРегламентированныхОтчетов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьХранилищеЭлектронныхПредставленийРегламентированныхОтчетов as "(не используется) Хранилище электронных представлений регламентированных отчетов" <<РегистрыСведений>>
{
..Измерения..
ЭлектронноеПредставление : Справочник.(не используется) Электронные представления регламентированных отчетов
ИмяФайла : Строка
..Ресурсы..
Данные : Хранилище значения
..Реквизиты..
Размер : Число 10, 0
ТипФайлаОтчетности : (не используется) Типы файлов отчетности ПФР\r(не используется) Типы файлов бухгалтерской отчетности
}
@enduml
