@startuml ОчередьЗаказовККорректировкеСтрокМерныхТоваров
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОчередьЗаказовККорректировкеСтрокМерныхТоваров as "Очередь заказов к корректировке строк мерных товаров" <<РегистрыСведений>>
{
..Измерения..
Заказ : Документ.Этап производства\rДокумент.Заказ поставщику\rДокумент.Заказ на производство\r...
..Реквизиты..
ДатаДобавления : Дата
}
@enduml
