@startuml МинимальнаяОплатаТрудаРФ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.МинимальнаяОплатаТрудаРФ as "Минимальная оплата труда" <<РегистрыСведений>>
{
..Ресурсы..
Размер : Число 10, 0
}
@enduml
