@startuml СостоянияНМАОрганизаций
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияНМАОрганизаций as "Состояния НМА организаций" <<РегистрыСведений>>
{
..Измерения..
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
Организация : Справочник.Организация
..Ресурсы..
Состояние : Виды состояний НМА
}
@enduml
