@startuml ПризнакиАрхивированияФайловДОСКонтролирующимиОрганами
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПризнакиАрхивированияФайловДОСКонтролирующимиОрганами as "Признаки архивирования файлов ДО с контролирующими органами" <<РегистрыСведений>>
{
..Измерения..
Объект : Документ.Транспортное сообщение\rСправочник.Загруженный отчет\rДокумент.Запрос на выписку из ЕГРЮЛ/ЕГРИП\r...
ИмяФайла : Строка
Владелец : Виды архивируемых метаданных ДО
..Ресурсы..
Архивный : Булево
}
@enduml
