@startuml ДомаЗданияСтроения
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДомаЗданияСтроения as "Дома здания строения" <<РегистрыСведений>>
{
..Измерения..
АдресныйОбъект : Уникальный идентификатор
ПочтовыйИндекс : Число 6, 0
КодСубъектаРФ : Число 2, 0
..Ресурсы..
Строения : Хранилище значения
}
@enduml
