@startuml ПлановыйФОТ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПлановыйФОТ as "Плановый ФОТ" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ДатаОкончания : Дата
Начисление : Начисление
ФизическоеЛицо : Справочник.Физическое лицо
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ГоловнаяОрганизация : Справочник.Организация
Год : Дата
..Ресурсы..
ВкладВФОТ : Число 15, 2
Используется : Булево
..Реквизиты..
ПересчетНеТребуется : Булево
ВторичнаяЗапись : Булево
РегистраторСобытия : Документ.Назначение планового начисления\rДокумент.Изменение мест работы\rДокумент.Удержание по прочим операциям\r...
ПериодПредыдущейЗаписи : Дата
}
@enduml
