@startuml ОтборыПоЛентамНовостейПользовательские
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОтборыПоЛентамНовостейПользовательские as "Отборы по лентам новостей, настроенные пользователем" <<РегистрыСведений>>
{
..Измерения..
Пользователь : Справочник.Пользователь
ЛентаНовостей : Справочник.Лента новостей
КатегорияНовостей : Категория новостей
ЗначениеКатегорииНовостей : Булево\rСтрока\rСправочник.Значение категорий новостей\r...
..Реквизиты..
УстановленоПрограммно : Булево
}
@enduml
