@startuml РазрешенияНаИспользованиеВнешнихРесурсовОбластейДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РазрешенияНаИспользованиеВнешнихРесурсовОбластейДанных as "Разрешения на использование внешних ресурсов областей данных" <<РегистрыСведений>>
{
..Измерения..
ТипПрограммногоМодуля : Справочник.Идентификатор объекта метаданных
ИдентификаторПрограммногоМодуля : Уникальный идентификатор
ТипВладельца : Справочник.Идентификатор объекта метаданных
ИдентификаторВладельца : Уникальный идентификатор
КлючРазрешения : Строка
..Реквизиты..
ТелоРазрешения : Строка
ПредставлениеПрограммногоМодуля : Строка
ПредставлениеВладельца : Строка
}
@enduml
