@startuml МестаВыплатыЗарплатыПодразделений
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.МестаВыплатыЗарплатыПодразделений as "Места выплаты зарплаты подразделений" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
..Ресурсы..
Вид : Виды мест выплаты зарплаты
МестоВыплаты : Справочник.Зарплатный проект\rСправочник.Касса\rСправочник.Физическое лицо
}
@enduml
