@startuml РеестрОтпусков
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РеестрОтпусков as "Реестр отпусков" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ДокументОснование : Документ.Отпуск без сохранения оплаты списком\rДокумент.Отпуск\rДокумент.Больничный лист\r...
Номер : Число 10, 0
..Ресурсы..
ВидОтпуска : Строка\rСправочник.Вид отпуска
НачалоПериодаЗаКоторыйПредоставляетсяОтпуск : Дата
КонецПериодаЗаКоторыйПредоставляетсяОтпуск : Дата
КоличествоДнейОтпуска : Число 10, 2
ДатаНачалаПериодаОтсутствия : Дата
ДатаОкончанияПериодаОтсутствия : Дата
ВидДоговора : Виды договоров с сотрудниками
Основание : Строка
}
@enduml
