@startuml ПКУСотрудниковИспр
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПКУСотрудниковИспр as "ПКУ сотрудников испр" <<РегистрыСведений>>
{
..Измерения..
РегистраторИзмерение : Документ.Изменение оплаты труда\rДокумент.Кадровый перевод\rДокумент.Начальная штатная расстановка\r...
ПериодИзмерение : Дата
Сотрудник : Справочник.Сотрудник
..Ресурсы..
ПКУ : Справочник.Квалификационный разряд (категория)
ДействуетДо : Дата
ПКУПоОкончании : Справочник.Квалификационный разряд (категория)
}
@enduml
