@startuml ДанныеОбработанныеВЦентральномУзлеРИБ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДанныеОбработанныеВЦентральномУзлеРИБ as "Данные обработанные в центральном узле РИБ" <<РегистрыСведений>>
{
..Измерения..
УзелПланаОбмена : Синхронизация данных через универсальный формат\rОбмен с подключаемым оборудованием Offline\rОбрабатываемый объект\r...
ОбъектМетаданных : Справочник.Идентификатор объекта метаданных
Данные : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
Очередь : Число 10, 0
КлючУникальности : Уникальный идентификатор
..Реквизиты..
ЗначенияОтборовНезависимогоРегистра : Хранилище значения
}
@enduml
