@startuml ОчередьПолученияКвитанцийОФиксацииГИСМ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОчередьПолученияКвитанцийОФиксацииГИСМ as "Очередь получения квитанций о фиксации ГИСМ" <<РегистрыСведений>>
{
..Измерения..
Сообщение : Справочник.Сообщение обмена с ГИСМ
..Ресурсы..
Данные : Хранилище значения
GLN : Строка
}
@enduml
