@startuml ВеличинаПрожиточногоМинимума
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ВеличинаПрожиточногоМинимума as "Величина прожиточного минимума" <<РегистрыСведений>>
{
..Измерения..
ПрожиточныйМинимум : Справочник.Прожиточный минимум
..Ресурсы..
Размер : Число 15, 2
}
@enduml
