@startuml ЗамерыОбластиСтатистики
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗамерыОбластиСтатистики as "Замеры области статистики" <<РегистрыСведений>>
{
..Измерения..
ПериодОкончание : Дата
ОперацияСтатистики : Уникальный идентификатор
ОбластьСтатистики : Уникальный идентификатор
ИдентификаторУдаления : Дата
..Ресурсы..
КоличествоЗначений : Число 10, 0
}
@enduml
