@startuml ПрименениеДополнительныхПериодическихПоказателейРасчетаЗарплатыСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПрименениеДополнительныхПериодическихПоказателейРасчетаЗарплатыСотрудников as "Применение дополнительных периодических показателей расчета зарплаты сотрудников" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
Показатель : Справочник.Показатель
..Ресурсы..
Применение : Булево
ДействуетДо : Дата
ПрименениеПоОкончании : Булево
}
@enduml
