@startuml СезонныеКоэффициенты
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СезонныеКоэффициенты as "Сезонные коэффициенты" <<РегистрыСведений>>
{
..Измерения..
СезоннаяГруппа : Справочник.Сезонные группы номенклатуры
СезоннаяГруппаБизнесРегиона : Справочник.Сезонные группы бизнес-регионов
Периодичность : Периодичность
НомерПериода : Число 3, 0
..Ресурсы..
Коэффициент : Число 15, 3
}
@enduml
