@startuml ПорядокУплатыНалоговНаМестах
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПорядокУплатыНалоговНаМестах as "Порядок уплаты авансов по налогам" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Налог : Виды имущественных налогов
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
..Ресурсы..
УплачиваютсяАвансы : Булево
}
@enduml
