@startuml ПорядокОтраженияРасходов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПорядокОтраженияРасходов as "Порядок отражения расходов" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение\rСправочник.Партнер
СтатьяРасходов : Статья расходов
Документ : Документ.Внутреннее потребление товаров\rДокумент.Расходный кассовый ордер\rДокумент.Приобретение товаров и услуг\r...
..Ресурсы..
СчетУчета : Счет бухгалтерского учета
ОтражениеВУСН : Отражение в УСН
СпособНастройкиСчетовУчета : Способы настройки счетов учета
СчетУчетаНУ : Счет бухгалтерского учета
СтатьяРасходовНУ : Статья расходов\rСтатьи доходов
ВидСубконто : Вид субконто
ВидСубконтоНУ : Вид субконто
СчетСписанияОСНО : Счет бухгалтерского учета
СчетСписанияЕНВД : Счет бухгалтерского учета
}
@enduml
