@startuml ЗнаниеЯзыковФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗнаниеЯзыковФизическихЛиц as "Знание языков физических лиц" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
Язык : Справочник.Язык
..Ресурсы..
СтепеньЗнанияЯзыка : Справочник.Степень знания языка
}
@enduml
