@startuml ПлановыеНачисленияИнтервальный
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПлановыеНачисленияИнтервальный as "Плановые начисления интервальный" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ДатаОкончания : Дата
ДатаНачала : Дата
Начисление : Начисление
ФизическоеЛицо : Справочник.Физическое лицо
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ГоловнаяОрганизация : Справочник.Организация
ПериодЗаписи : Дата
Год : Дата
..Ресурсы..
ПериодПредыдущейЗаписи : Дата
Используется : Булево
Размер : Число 15, 2
ДействуетДо : Дата
..Реквизиты..
РегистраторЗаписи : Документ.Назначение планового начисления\rДокумент.Изменение мест работы\rДокумент.Изменение условий оплаты отпуска по уходу за ребенком\r...
РегистраторСобытия : Документ.Назначение планового начисления\rДокумент.Изменение мест работы\rДокумент.Изменение условий оплаты отпуска по уходу за ребенком\r...
ПересчетНеТребуется : Булево
ВторичнаяЗапись : Булево
ПустойИнтервал : Булево
}
@enduml
