@startuml ТоварыКДоставке
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ТоварыКДоставке as "Товары к доставке" <<РегистрыСведений>>
{
..Измерения..
ЗаданиеНаПеревозку : Документ.Задание на перевозку
Распоряжение : Документ.Передача давальцу\rДокумент.Приобретение товаров и услуг\rДокумент.Заказ поставщику\r...
Склад : Справочник.Склад (складская территория)
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
..Ресурсы..
Количество : Число 15, 3
..Реквизиты..
ВсеТовары : Булево
ПолучательОтправитель : Справочник.Подразделение\rСправочник.Партнер\rСтрока\r...
Вес : Число 15, 3
Объем : Число 18, 6
}
@enduml
