@startuml НачислениеАмортизацииОССпециальныйКоэффициентНалоговыйУчет
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НачислениеАмортизацииОССпециальныйКоэффициентНалоговыйУчет as "Специальный коэффициент для амортизации ОС (налог. учет)" <<РегистрыСведений>>
{
..Измерения..
ОсновноеСредство : Справочник.Объект эксплуатации
Организация : Справочник.Организация
..Ресурсы..
СпециальныйКоэффициент : Число 5, 2
}
@enduml
