@startuml РеестрДокументов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РеестрДокументов as "Реестр документов" <<РегистрыСведений>>
{
..Измерения..
ТипСсылки : Справочник.Идентификатор объекта метаданных
Организация : Справочник.Организация
ХозяйственнаяОперация : Хозяйственные операции
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
НаправлениеДеятельности : Справочник.Направление деятельности
Подразделение : Справочник.Подразделение
МестоХранения : Справочник.Подразделение\rСправочник.Банковский счет организации\rСправочник.Касса\r...
ДатаДокументаИБ : Дата
Ссылка : Документ.Внутреннее потребление товаров\rДокумент.Подготовка к передаче НМА\rДокумент.Списание ОС\r...
РазделительЗаписи : Строка
..Ресурсы..
НомерДокументаИБ : Строка
Статус : Статусы перемещений товаров\rСтатусы акта о расхождениях\rСтатусы сборок товаров\r...
Ответственный : Справочник.Пользователь
ДополнительнаяЗапись : Булево
Дополнительно : Строка
Комментарий : Строка
Проведен : Булево
ПометкаУдаления : Булево
ДатаПервичногоДокумента : Дата
НомерПервичногоДокумента : Строка
Сумма : Число 15, 2
Валюта : Справочник.Валюта
Договор : Справочник.Договор между организациями\rСправочник.Договор с контрагентом\rСправочник.Договор лизинга
}
@enduml
