@startuml ПравилаОтраженияВМеждународномУчете
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПравилаОтраженияВМеждународномУчете as "Правила отражения в международном учете" <<РегистрыСведений>>
{
..Измерения..
УчетнаяПолитика : Справочник.Учетная политика
ШаблонПроводки : Справочник.Соотвествие счетов регл. и международного учета\rСправочник.Соответствие оборотов регл. и международного учета\rСправочник.Шаблон проводки
}
@enduml
