@startuml ЗначенияБазовыхТарифов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗначенияБазовыхТарифов as "Значения базовых тарифов" <<РегистрыСведений>>
{
..Измерения..
ТарифнаяСетка : Справочник.Тарифная группа
..Ресурсы..
Тариф : Число 15, 2
}
@enduml
