@startuml ГрафикЭтаповПроизводства2_2
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ГрафикЭтаповПроизводства2_2 as "График этапов производства 2.2" <<РегистрыСведений>>
{
..Измерения..
Распоряжение : Документ.Заказ на производство
СтатусГрафика : Число 1, 0
ЭтапПроизводства : Документ.Этап производства
..Ресурсы..
НачалоЭтапа : Дата
ОкончаниеЭтапа : Дата
ОкончаниеПредварительногоБуфера : Дата
НачалоЗавершающегоБуфера : Дата
НачалоСледующегоЭтапа : Дата
НаКритическомПути : Булево
ОграничиваетСрокВыпуска : Булево
ОграниченПоМатериалам : Булево
ОграниченПоОборудованию : Булево
..Реквизиты..
РазмещениеВыпуска : Способы привязки операций производства
}
@enduml
