@startuml СтавкиНалогаНаПрибыльВБюджетСубъектовРФ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтавкиНалогаНаПрибыльВБюджетСубъектовРФ as "Ставки налога на прибыль в бюджет субъектов РФ" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
..Ресурсы..
СтавкаСубъектРФ : Число 5, 2
}
@enduml
