@startuml ИсторияИспользованияШтатногоРасписания
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИсторияИспользованияШтатногоРасписания as "История использования штатного расписания" <<РегистрыСведений>>
{
..Измерения..
ПозицияШтатногоРасписания : Справочник.Позиция
Дата : Дата
..Ресурсы..
Используется : Булево
КоличествоСтавок : Число 7, 2
ГрафикРаботыСотрудников : Справочник.График работы
..Реквизиты..
УсловияПриема : Строка
ФОТ : Число 19, 2
ФОТМин : Число 19, 2
ФОТМакс : Число 19, 2
РайонныйКоэффициентРазмер : Число 15, 2
РайонныйКоэффициентРазмерМин : Число 15, 2
РайонныйКоэффициентРазмерМакс : Число 15, 2
СевернаяНадбавкаРазмер : Число 15, 2
СевернаяНадбавкаРазмерМин : Число 15, 2
СевернаяНадбавкаРазмерМакс : Число 15, 2
ОкладТариф : Число 15, 3
ОкладТарифМин : Число 15, 3
ОкладТарифМакс : Число 15, 3
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОтношениеКЕНВД : Отношение к ЕНВД затрат на зарплату
СтатьяФинансирования : Справочник.Статья финансирования
ТарифнаяСетка : Справочник.Тарифная группа
РазрядКатегория : Справочник.Квалификационный разряд (категория)
ТарифнаяСеткаНадбавки : Справочник.Тарифная группа
РазрядКатегорияНадбавки : Справочник.Квалификационный разряд (категория)
НадбавкаЗаВредностьРазмер : Число 15, 2
НадбавкаЗаВредностьРазмерМин : Число 15, 2
НадбавкаЗаВредностьРазмерМакс : Число 15, 2
ВзимаютсяВзносыЗаЗанятыхНаРаботахСДосрочнойПенсией : Виды работ с досрочной пенсией
ОснованиеДосрочногоНазначенияПенсии : Справочник.Основание для досрочной пенсии
ОсобыеУсловияТрудаПФР : Справочник.Особое условие труда
КодПозицииСпискаПФР : Справочник.Льготная профессия (ПФР)
ВыплачиваетсяНадбавкаЗаВредность : Булево
ПроцентНадбавкиЗаВредность : Число 5, 2
ФОТУправленческий : Число 19, 2
ФОТУправленческийМин : Число 19, 2
ФОТУправленческийМакс : Число 19, 2
}
@enduml
