@startuml НастройкиЗарплатаКадрыРасширенная
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиЗарплатаКадрыРасширенная as "Настройки зарплата кадры  (расширенный)" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
УдалитьИспользоватьВилкуСтавокВШтатномРасписании : Булево
УдалитьИзменятьПраваНаОтпускаПоСотрудникам : Булево
УдалитьИспользоватьИзменениеПравНаОтпускаПоСотрудникам : Булево
ДатаВыплатыАвансаНеПозжеЧем : Число 2, 0
ДатаВыплатыЗарплатыНеПозжеЧем : Число 2, 0
ПроцентДоплатыЗаДниНетрудоспособности : Число 3, 0
ИспользоватьТерриториальныеУсловияПФР : Булево
ВыплачиватьЗарплатуВПоследнийДеньМесяца : Булево
ИспользоватьОбособленныеТерритории : Булево
ИспользоватьОсобыеУсловияТруда : Булево
ИспользуютсяТерриторииЗаПределамиРФ : Булево
}
@enduml
