@startuml СведенияОВзносахВПФР
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СведенияОВзносахВПФР as "Сведения о взносах в ПФР" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
НачисленоСтраховая : Число 15, 2
НачисленоНакопительная : Число 15, 2
УплаченоСтраховая : Число 15, 2
УплаченоНакопительная : Число 15, 2
ЗадолженностьСтраховая : Число 15, 2
ЗадолженностьНакопительная : Число 15, 2
}
@enduml
