@startuml СтатусыОтправки
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтатусыОтправки as "Статусы отправки" <<РегистрыСведений>>
{
..Измерения..
Объект : Документ.Выгрузка регламентированных отчетов\rДокумент.Сведения о заработке и стаже застрахованных лиц, СЗВ-ИСХ\rДокумент.2-НДФЛ для передачи в ИФНС\r...
..Ресурсы..
Статус : Статусы отправки
..Реквизиты..
Основание : Справочник.(не используется) Отправки в ФСС\rСправочник.Отправки в ФСС\rСправочник.Отправки отчетности
}
@enduml
