@startuml ПооперационноеРасписание2_2
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПооперационноеРасписание2_2 as "Пооперационное расписание 2.2" <<РегистрыСведений>>
{
..Измерения..
Этап : Документ.Этап производства
Операция : Справочник.Операция
ИдентификаторОперации : Число 25, 0
НомерПартии : Число 10, 0
РабочийЦентр : Строка\rСправочник.Рабочий центр
МодельРасписания : Уникальный идентификатор
МодельПланирования : Справочник.Модель пооперационного планирования
ЭтоУдалениеОперации : Булево
Начало : Дата
Окончание : Дата
ТактПараллельнойЗагрузки : Уникальный идентификатор
..Ресурсы..
ВремяПлан : Число 10, 0
Загрузка : Число 15, 3
ЭтоПереналадка : Булево
КоличествоПартии : Число 15, 3
Коэффициент : Число 10, 0
Создано : Число 15, 3
ОжиданиеПредшествующих : Число 15, 3
НачатыПредшествующие : Число 15, 3
МожноВыполнять : Число 15, 3
Выполняется : Число 15, 3
Выполнено : Число 15, 3
ВремяПерехода : Число 10, 0
..Реквизиты..
Подразделение : Справочник.Подразделение
Вспомогательная : Булево
Моделирование : Булево
ЛеваяГраница : Дата
ПраваяГраница : Дата
ДополнительнаяЗапись : Булево
ДлительностьИнтервала : Число 10, 0
}
@enduml
