@startuml УдалитьНастройкиОбменаФСС
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьНастройкиОбменаФСС as "(не используется) Настройки обмена с ФСС" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
ИспользоватьОбмен : Булево
СертификатСтрахователяОтпечаток : Строка
СертификатФССОтпечаток : Строка
ИспользоватьАвтонастройку : Булево
}
@enduml
