@startuml РасчетНалогаУСН
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РасчетНалогаУСН as "Расчет налога, уплачиваемого при УСН" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ПериодРасчета : Дата
..Ресурсы..
ОбъектНалогообложения : Объекты налогообложения по УСН
Доходы : Число 15, 2
Расходы : Число 15, 2
ПеренесенныеУбытки : Число 15, 2
НалоговаяБаза : Число 15, 2
СтавкаНалогаУСН : Число 5, 2
НалогВсего : Число 15, 2
РасходыУменьшающиеНалог : Число 15, 2
ПроцентУменьшенияНалога : Число 3, 0
УменьшениеНалогаФакт : Число 15, 2
НалогИсчисленныйВсего : Число 15, 2
МинимальныйНалог : Число 15, 2
АвансовыеПлатежи : Число 15, 2
НалогКУплате : Число 15, 2
}
@enduml
