@startuml НастройкиТранспортаОбмена
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиТранспортаОбмена as "Параметры подключения" <<РегистрыСведений>>
{
..Измерения..
Узел : Синхронизация данных через универсальный формат\rОбмен с подключаемым оборудованием Offline\rОбрабатываемый объект\r...
..Ресурсы..
COMАутентификацияОперационнойСистемы : Булево
COMВариантРаботыИнформационнойБазы : Число 1, 0
COMИмяИнформационнойБазыНаСервере1СПредприятия : Строка
COMИмяПользователя : Строка
COMИмяСервера1СПредприятия : Строка
COMКаталогИнформационнойБазы : Строка
EMAILМаксимальныйДопустимыйРазмерСообщения : Число 10, 0
EMAILСжиматьФайлИсходящегоСообщения : Булево
EMAILУчетнаяЗапись : Справочник.Учетная запись электронной почты
EMAILТранслитерироватьИменаФайловСообщенийОбмена : Булево
FILEКаталогОбменаИнформацией : Строка
FILEСжиматьФайлИсходящегоСообщения : Булево
FILEТранслитерироватьИменаФайловСообщенийОбмена : Булево
FTPСжиматьФайлИсходящегоСообщения : Булево
FTPСоединениеМаксимальныйДопустимыйРазмерСообщения : Число 10, 0
FTPСоединениеПассивноеСоединение : Булево
FTPСоединениеПользователь : Строка
FTPСоединениеПорт : Число 5, 0
FTPСоединениеПуть : Строка
FTPТранслитерироватьИменаФайловСообщенийОбмена : Булево
WSURLВебСервиса : Строка
WSЗапомнитьПароль : Булево
WSИмяПользователя : Строка
WSИспользоватьПередачуБольшогоОбъемаДанных : Булево
ВидТранспортаСообщенийОбменаПоУмолчанию : Виды транспорта сообщений обмена
КоличествоЭлементовВТранзакцииВыгрузкиДанных : Число 10, 0
КоличествоЭлементовВТранзакцииЗагрузкиДанных : Число 10, 0
УдалитьCOMПарольПользователя : Строка
УдалитьFTPСоединениеПароль : Строка
УдалитьWSПароль : Строка
УдалитьПарольАрхиваСообщенияОбмена : Строка
}
@enduml
