@startuml ПлановыеЕжегодныеОтпуска
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПлановыеЕжегодныеОтпуска as "Плановые ежегодные отпуска" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
Сотрудник : Справочник.Сотрудник
ДатаНачала : Дата
..Ресурсы..
Запланирован : Булево
Перенесен : Булево
..Реквизиты..
ДокументПланирования : Документ.График отпусков
КоличествоДней : Число 3, 0
ВидОтпуска : Справочник.Вид отпуска
ДатаОкончания : Дата
ПеренесеннаяДатаНачала : Дата
ДокументПереноса : Документ.Перенос отпуска
}
@enduml
