@startuml НастройкиЗарплатаКадры
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиЗарплатаКадры as "Настройки зарплата кадры" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
ПрименятьСевернуюНадбавку : Булево
ПрименятьРайонныйКоэффициент : Булево
ПрименятьСевернуюНадбавкуВПодразделениях : Булево
ПрименятьРайонныйКоэффициентВПодразделениях : Булево
УдалитьФормироватьПроводкиВКонцеПериода : Булево
УдалитьИспользуетсяТрудФармацевтов : Булево
УдалитьИспользуетсяТрудЧленовЛетныхЭкипажей : Булево
УдалитьИспользуетсяТрудЧленовЭкипажейМорскихСудов : Булево
УдалитьИспользуетсяТрудШахтеров : Булево
}
@enduml
