@startuml СведенияОбИнвалидностиФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СведенияОбИнвалидностиФизическихЛиц as "Сведения об инвалидности физических лиц" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
Инвалидность : Булево
ДействуетДо : Дата
ИнвалидностьПоОкончании : Булево
ДатаРегистрацииИзменений : Дата
..Реквизиты..
ДатаВыдачи : Дата
СрокДействияСправки : Дата
}
@enduml
