@startuml Ассортимент
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.Ассортимент as "Ассортимент" <<РегистрыСведений>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
ОбъектПланирования : Справочник.Форматы магазинов\rСправочник.Склад (складская территория)
..Ресурсы..
РольАссортимента : Роли ассортимента
РазрешеныЗакупки : Булево
РазрешеныПродажи : Булево
ВидЦены : Справочник.Вид цены
КоллекцияНоменклатуры : Справочник.Коллекция (сезон)
РейтингПродаж : Справочник.Рейтинг продаж номенклатуры
}
@enduml
