@startuml СоответствиеНоменклатурыМобильногоПриложения1СЗаказы
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СоответствиеНоменклатурыМобильногоПриложения1СЗаказы as "Соответствие номенклатуры мобильного приложения "1С: Заказы клиентов"" <<РегистрыСведений>>
{
..Измерения..
ИдНоменклатуры : Строка
ИдХарактеристики : Строка
ИдУпаковки : Строка
ИдОбъектаМП : Строка
}
@enduml
