@startuml ТаблицыГруппДоступа
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ТаблицыГруппДоступа as "Таблицы групп доступа" <<РегистрыСведений>>
{
..Измерения..
Таблица : Справочник.Идентификатор объекта метаданных
ГруппаДоступа : Справочник.Группа доступа
..Ресурсы..
Изменение : Булево
..Реквизиты..
ТипТаблицы : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
}
@enduml
