@startuml ПоследнийОбменСБанками
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПоследнийОбменСБанками as "Последний обмен с банками" <<РегистрыСведений>>
{
..Измерения..
БанковскийСчет : Справочник.Банковский счет организации
..Ресурсы..
ДатаВыгрузки : Дата
ДатаНачалаЗагрузки : Дата
ДатаКонцаЗагрузки : Дата
}
@enduml
