@startuml ПериодическиеСвойстваНовостей
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПериодическиеСвойстваНовостей as "Периодические свойства новостей" <<РегистрыСведений>>
{
..Измерения..
Новость : Справочник.Новость
..Ресурсы..
ВажностьОбщая : Число 1, 0
Актуальность : Булево
}
@enduml
