@startuml НастройкиТранспортаОбменаОбластейДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиТранспортаОбменаОбластейДанных as "Настройки транспорта обмена областей данных" <<РегистрыСведений>>
{
..Измерения..
КонечнаяТочкаКорреспондента : Конечная точка
..Ресурсы..
FILEКаталогОбменаИнформацией : Строка
FILEСжиматьФайлИсходящегоСообщения : Булево
FTPСжиматьФайлИсходящегоСообщения : Булево
FTPСоединениеМаксимальныйДопустимыйРазмерСообщения : Число 10, 0
FTPСоединениеПассивноеСоединение : Булево
FTPСоединениеПользователь : Строка
FTPСоединениеПорт : Число 5, 0
FTPСоединениеПуть : Строка
ВидТранспортаСообщенийОбменаПоУмолчанию : Виды транспорта сообщений обмена
УдалитьFTPСоединениеПароль : Строка
УдалитьПарольАрхиваСообщенияОбмена : Строка
}
@enduml
