@startuml РасценкиРаботСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РасценкиРаботСотрудников as "Расценки работ сотрудников" <<РегистрыСведений>>
{
..Измерения..
ВидРабот : Справочник.Вид работ сотрудников
КвалификационныйРазряд : Справочник.Квалификационный разряд (категория)
..Ресурсы..
Расценка : Число 15, 2
}
@enduml
