@startuml ПривязкаНовостейКМетаданным
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПривязкаНовостейКМетаданным as "Привязка новостей к метаданным" <<РегистрыСведений>>
{
..Измерения..
Метаданные : Строка
Форма : Строка
Событие : Строка
Новость : Справочник.Новость
..Ресурсы..
Важность : Число 1, 0
Актуальность : Булево
ПоказыватьВФормеОбъекта : Булево
ЭтоПостояннаяНовость : Булево
}
@enduml
