@startuml ИсполнителиЗадач
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИсполнителиЗадач as "Исполнители задач" <<РегистрыСведений>>
{
..Измерения..
РольИсполнителя : Справочник.Роль исполнителя
Исполнитель : Справочник.Внешний пользователь\rСправочник.Пользователь
ОсновнойОбъектАдресации : Справочник.Организация\rСправочник.Подразделение\rСправочник.Склад (складская территория)
ДополнительныйОбъектАдресации : Справочник.Организация\rСправочник.Подразделение\rСправочник.Склад (складская территория)
..Реквизиты..
ГруппаИсполнителейЗадач : Справочник.Группа исполнителей задач
}
@enduml
