@startuml ЗначенияСтроковыхРеквизитов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗначенияСтроковыхРеквизитов as "Значения строковых реквизитов" <<РегистрыСведений>>
{
..Измерения..
ВидСтроки : Строка
ЗначениеСтроки : Строка
}
@enduml
