@startuml ОперацииМаршрутовПроизводства
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОперацииМаршрутовПроизводства as "Операции маршрутов производства" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторОперации : Уникальный идентификатор
..Ресурсы..
РабочийЦентрМаршрута : Справочник.Рабочий центр\rСправочник.Вид рабочего центра
ВремяШтучное : Число 10, 1
УдалитьВремяВыполнения : Число 10, 1
ВремяПЗ : Число 10, 1
УдалитьВремяЗаключительное : Число 10, 1
ДатаЗапуска : Дата
ДатаВыпуска : Дата
НомерСледующейОперации : Число 5, 0
..Реквизиты..
МаршрутныйЛист : Документ.Маршрутный лист производства
Распоряжение : Документ.Заказ на производство
ВариантНаладки : Справочник.Вариант наладки
Непрерывная : Булево
НомерОперации : Число 5, 0
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Количество : Число 15, 3
Загрузка : Число 15, 3
Подразделение : Справочник.Подразделение
Спецификация : Справочник.Ресурсная спецификация
МаршрутнаяКарта : Справочник.Маршрутная карта
Операция : Строка\rСправочник.Операция
СтатусВыполнения : Статусы выполнения операций
Приоритет : Справочник.Приоритет
ВремяВыполнения : Число 10, 1
ВремяВыполненияЕдИзм : Единицы измерения времени
}
@enduml
