@startuml НастройкаПередачиМатериаловВПроизводство
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкаПередачиМатериаловВПроизводство as "Настройка передачи материалов в производство" <<РегистрыСведений>>
{
..Измерения..
Подразделение : Справочник.Подразделение
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
..Ресурсы..
Склад : Справочник.Склад (складская территория)
ОснованиеДляПолучения : Основания для получения материалов в производстве
}
@enduml
