@startuml ДанныеОВремениДляРасчетаСреднегоОбщийКорректировка
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДанныеОВремениДляРасчетаСреднегоОбщийКорректировка as "Данные о времени для расчета общего среднего заработка (корректировка)" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
Месяц : Дата
ПорядокРасчета : Порядок расчета среднего заработка общий
..Ресурсы..
ОтработаноДней : Число 5, 2
ОтработаноДнейШестидневка : Число 5, 2
ОтработаноДнейПятидневка : Число 5, 2
ОтработаноЧасовПятидневка : Число 5, 2
ОтработаноДнейКалендарных : Число 5, 2
}
@enduml
