@startuml АналитикаУчетаНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.АналитикаУчетаНоменклатуры as "Аналитика учета номенклатуры" <<РегистрыСведений>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Серия : Справочник.Серия номенклатуры
Склад : Справочник.Организация\rСправочник.Подразделение\rСправочник.Партнер\r...
Назначение : Справочник.Назначение
СтатьяКалькуляции : Справочник.Статьи калькуляции
..Ресурсы..
КлючАналитики : Справочник.Ключ аналитики учета номенклатуры
}
@enduml
