@startuml УченыеЗванияФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УченыеЗванияФизическихЛиц as "Ученые звания физических лиц" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
НомерПоПорядку : Число 2, 0
..Ресурсы..
УченоеЗвание : Справочник.Ученое звание
ДатаПрисвоенияУченогоЗвания : Дата
АттестатСерия : Строка
АттестатНомер : Строка
АттестатВыданОрганизация : Строка
НаучнаяСпециальность : Справочник.Специальность
}
@enduml
