@startuml ГрафикиРаботыПоВидамВремени
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ГрафикиРаботыПоВидамВремени as "Графики работы по видам времени" <<РегистрыСведений>>
{
..Измерения..
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
Месяц : Дата
ПериодРегистрации : Дата
ВидУчетаВремени : Справочник.Вид рабочего времени
Дата : Дата
ВремяВЧасах : Булево
ВЦеломЗаПериод : Булево
Территория : Справочник.Территория
УсловияТруда : Справочник.Условия труда
..Ресурсы..
ОсновноеЗначение : Число 5, 2
ДополнительноеЗначение : Число 5, 2
ОсновноеЗначениеНорма : Число 5, 2
ДополнительноеЗначениеНорма : Число 5, 2
..Реквизиты..
План : Булево
}
@enduml
