@startuml ПараметрыАмортизацииОСБухгалтерскийУчет
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПараметрыАмортизацииОСБухгалтерскийУчет as "Параметры амортизации ОС (бухгалтерский учет, версия 2.2)" <<РегистрыСведений>>
{
..Измерения..
ОсновноеСредство : Справочник.Объект эксплуатации
Организация : Справочник.Организация
..Ресурсы..
СрокПолезногоИспользования : Число 4, 0
ОбъемПродукцииРабот : Число 10, 0
СрокИспользованияДляВычисленияАмортизации : Число 4, 0
СтоимостьДляВычисленияАмортизации : Число 15, 2
ОбъемПродукцииРаботДляВычисленияАмортизации : Число 10, 0
КоэффициентАмортизации : Число 4, 2
КоэффициентУскорения : Число 5, 2
}
@enduml
