@startuml КонтактыВзаимодействий
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КонтактыВзаимодействий as "Контакты взаимодействий" <<РегистрыСведений>>
{
..Измерения..
Взаимодействие : Документ.Исходящее электронное письмо\rДокумент.Запланированное взаимодействие\rДокумент.Входящее электронное письмо\r...
Контакт : Справочник.Строковый контакт взаимодействий\rСправочник.Пользователь\rСправочник.Партнер\r...
}
@enduml
