@startuml КэшПрограммныхИнтерфейсов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КэшПрограммныхИнтерфейсов as "Кэш программных интерфейсов" <<РегистрыСведений>>
{
..Измерения..
Идентификатор : Строка
ТипДанных : Типы данных кэша программных интерфейсов
..Ресурсы..
ДатаОбновления : Дата
Данные : Хранилище значения
}
@enduml
