@startuml ВремяРегистрацииДокументовПлановыхНачислений
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ВремяРегистрацииДокументовПлановыхНачислений as "Время регистрации документов плановых начислений" <<РегистрыСведений>>
{
..Измерения..
Дата : Дата
Сотрудник : Справочник.Сотрудник
Документ : Документ.Назначение планового начисления\rДокумент.Изменение аванса\rДокумент.Изменение мест работы\r...
..Ресурсы..
ВремяРегистрации : Дата
Проведен : Булево
}
@enduml
