@startuml ПравилаОтправкиМакетовПенсионныхДел
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПравилаОтправкиМакетовПенсионныхДел as "Правила отправки макетов пенсионных дел" <<РегистрыСведений>>
{
..Измерения..
УчетнаяЗапись : Справочник.Учетные записи документооборота
ОрганПФР : Справочник.Органы ПФР
..Ресурсы..
Данные : Хранилище значения
}
@enduml
