@startuml ПараметрыАмортизацииНМАУУ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПараметрыАмортизацииНМАУУ as "Параметры амортизации НМА (управленческий учет)" <<РегистрыСведений>>
{
..Измерения..
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
Организация : Справочник.Организация
..Ресурсы..
СрокИспользования : Число 10, 0
КоэффициентУскорения : Число 4, 3
МетодНачисленияАмортизации : Способы начисления амортизации нематериальных активов
ЛиквидационнаяСтоимость : Число 15, 2
}
@enduml
