@startuml ДопустимыеСочетанияКодовГруппСтажа
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДопустимыеСочетанияКодовГруппСтажа as "Допустимые сочетания кодов групп стажа" <<РегистрыСведений>>
{
..Измерения..
НомерПравила : Строка
КодУсловийТруда : Строка
КодПозицииСписка : Строка
КодОснованияИсчисляемогоСтажа : Строка
ФорматФОВ : Строка
КодОснованияВыслугиЛет : Строка
..Реквизиты..
ТипШаблонаКПС : Строка
ПериодС : Число 4, 0
ПериодПо : Число 4, 0
}
@enduml
