@startuml ХранилищеЭлектронныхПредставленийРегламентированныхОтчетов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ХранилищеЭлектронныхПредставленийРегламентированныхОтчетов as "Хранилище электронных представлений регламентированных отчетов" <<РегистрыСведений>>
{
..Измерения..
ЭлектронноеПредставление : Справочник.Загруженный отчет
ИмяФайла : Строка
..Ресурсы..
Данные : Хранилище значения
..Реквизиты..
Размер : Число 10, 0
ТипФайлаОтчетности : Типы содержимого транспортного контейнера\rТипы файлов бухгалтерской отчетности\rТипы файлов отчетности ПФР
}
@enduml
