@startuml УдалитьВложенияНеформализованныхДокументов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьВложенияНеформализованныхДокументов as "(не используется) Вложения неформализованных документов" <<РегистрыСведений>>
{
..Измерения..
НеформализованныйДокумент : Справочник.(не используется) Переписка с контролирующими органами
ИмяФайла : Строка
..Ресурсы..
Данные : Хранилище значения
..Реквизиты..
Тип : Типы вложений неформализованных документов налогоплательщика
Размер : Число 10, 0
}
@enduml
