@startuml ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудниковИнтервальный
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудниковИнтервальный as "Значения периодических показателей расчета зарплаты (для сотрудников) интервальный" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ДатаОкончания : Дата
ДатаНачала : Дата
ФизическоеЛицо : Справочник.Физическое лицо
Показатель : Справочник.Показатель
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Приз, подарок\rДокумент.Удержание по прочим операциям\r...
Организация : Справочник.Организация
ПериодЗаписи : Дата
Год : Дата
..Ресурсы..
ПериодПредыдущейЗаписи : Дата
Значение : Число 15, 5
ДействуетДо : Дата
..Реквизиты..
РегистраторЗаписи : Документ.Назначение планового начисления\rДокумент.Изменение мест работы\rДокумент.Изменение условий оплаты отпуска по уходу за ребенком\r...
РегистраторСобытия : Документ.Назначение планового начисления\rДокумент.Изменение мест работы\rДокумент.Изменение условий оплаты отпуска по уходу за ребенком\r...
ПустойИнтервал : Булево
}
@enduml
