@startuml НастройкиУчетаПособийСоциальногоСтрахования
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиУчетаПособийСоциальногоСтрахования as "Настройки учета пособий социального страхования" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
ДатаПередачиФССВыплатыПособий : Дата
}
@enduml
