@startuml ДополнительныеРеквизитыУчетнойЗаписиПолучатели
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДополнительныеРеквизитыУчетнойЗаписиПолучатели as "Дополнительные реквизиты учетной записи (получатели)" <<РегистрыСведений>>
{
..Измерения..
УчетнаяЗапись : Справочник.Учетные записи документооборота
ТипПолучателя : Типы контролирующих органов
КодПолучателя : Строка
КПП : Строка
..Реквизиты..
ДатаОбновления : Дата
}
@enduml
