@startuml ПрофессииФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПрофессииФизическихЛиц as "Профессии физических лиц" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
Профессия : Справочник.Профессия рабочего
}
@enduml
