@startuml ПравилаУточненияСчетовВМеждународномУчете
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПравилаУточненияСчетовВМеждународномУчете as "Правила уточнения счетов (международный учет)" <<РегистрыСведений>>
{
..Измерения..
ГруппаФинансовогоУчета : Справочник.Группа финансового учета доходов/расходов\rСправочник.Группа финансового учета внеоборотных активов\rСправочник.Группа финансового учета расчетов\r...
ШаблонПроводки : Справочник.Шаблон проводки
ВидДвижения : Виды движений бухгалтерии
..Ресурсы..
СчетУчета : Международный план счетов
}
@enduml
