@startuml ТраншиЗаймаСотруднику
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ТраншиЗаймаСотруднику as "Транши займа сотруднику" <<РегистрыСведений>>
{
..Измерения..
ДоговорЗайма : Документ.Договор займа сотруднику
ДатаПредоставления : Дата
..Ресурсы..
Сумма : Число 15, 2
ДатаПогашения : Дата
РазмерПогашения : Число 15, 2
..Реквизиты..
Организация : Справочник.Организация
}
@enduml
