@startuml ДатыПоследнейЗагрузкиПочтовыхСообщений
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДатыПоследнейЗагрузкиПочтовыхСообщений as "Даты последней загрузки почтовых сообщений" <<РегистрыСведений>>
{
..Измерения..
УчетнаяЗапись : Справочник.Учетная запись электронной почты
..Ресурсы..
ДатаЗагрузкиПисем : Дата
}
@enduml
