@startuml НастройкиРасчетаЗарплатыРасширенный
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиРасчетаЗарплатыРасширенный as "Настройки расчета зарплаты (расширенный)" <<РегистрыСведений>>
{
..Ресурсы..
АвтоматическиОграничиватьИспользованиеДокументов : Булево
ВыбиратьВидНачисленияВыходногоПособия : Булево
ВыбиратьВидНачисленияДоплатыДоСреднегоЗаработка : Булево
ВыбиратьВидНачисленияДоплатыЗаДниБолезни : Булево
ВыбиратьВидНачисленияДоплатыЗаСовмещение : Булево
ВыбиратьВидНачисленияДополнительногоОтпуска : Булево
ВыбиратьВидНачисленияЕдиновременнойВыплатыКОтпуску : Булево
ВыбиратьВидНачисленияКомпенсацииДнейЧасовПриУвольнении : Булево
ВыбиратьВидНачисленияКомпенсацииДополнительногоОтпуска : Булево
ВыбиратьВидНачисленияКомпенсацииОсновногоОтпуска : Булево
ВыбиратьВидНачисленияМесячногоДенежногоСодержания : Булево
ВыбиратьВидНачисленияОплатыДнейБолезни : Булево
ВыбиратьВидНачисленияОплатыДнейБолезниЗаСчетРаботодателя : Булево
ВыбиратьВидНачисленияОплатыДнейБолезниПоПричинеНесчастногоСлучаяНаПроизводстве : Булево
ВыбиратьВидНачисленияОплатыДнейБолезниПоПричинеПрофзаболевания : Булево
ВыбиратьВидНачисленияОплатыДнейУходаЗаДетьмиИнвалидами : Булево
ВыбиратьВидНачисленияОплатыКомандировки : Булево
ВыбиратьВидНачисленияОплатыМатериальнойПомощиКОтпуску : Булево
ВыбиратьВидНачисленияОплатыОтпускаПоБеременностиИРодам : Булево
ВыбиратьВидНачисленияОплатыПростоя : Булево
ВыбиратьВидНачисленияОсновногоОтпуска : Булево
ВыбиратьВидНачисленияОтгул : Булево
ВыбиратьВидНачисленияОтпускБезОплаты : Булево
ВыбиратьВидНачисленияПереводаНаОплатуПоСреднемуЗаработку : Булево
ВыбиратьВидНачисленияПособияПоУходуЗаРебенкомДоПолутораЛет : Булево
ВыбиратьВидНачисленияПособияПоУходуЗаРебенкомДоПолутораЛетВоеннослужащим : Булево
ВыбиратьВидНачисленияПособияПоУходуЗаРебенкомДоТрехЛет : Булево
ВыбиратьВидНачисленияПрочихНевыходов : Булево
ВыбиратьВидНеоплачиваемогоВремениБолезни : Булево
ВыбиратьВидНеоплачиваемогоВремениОтпускаПоБеременностиИРодам : Булево
ВыбиратьВидУдержанияВознагражденияПлатежногоАгента : Булево
ВыбиратьВидУдержанияВСчетРасчетовПоПрочимОперациям : Булево
ВыбиратьВидУдержанияДобровольныхВзносовВНПФ : Булево
ВыбиратьВидУдержанияДСВ : Булево
ВыбиратьВидУдержанияЗаНеотработанныеДниОтпуска : Булево
ВыбиратьВидУдержанияИсполнительногоЛиста : Булево
ВыбиратьВидУдержанияПрофсоюзныхВзносов : Булево
ВыполнятьДоначислениеПерерасчетЗарплатыОтдельнымДокументом : Булево
ВыполнятьРасчетЗарплатыПоПодразделениям : Булево
ИспользоватьВнутрисменныеОтгулы : Булево
ИспользоватьВнутрисменныеОтпускаБезОплаты : Булево
ИспользоватьВыплатыБывшимСотрудникам : Булево
ИспользоватьДобровольныеВзносыВНПФ : Булево
ИспользоватьДоплатуДоСохраняемогоДенежногоСодержанияЗаДниБолезни : Булево
ИспользоватьДоплатуДоСреднегоЗаработка : Булево
ИспользоватьДоплатуЗаВремяКомандировки : Булево
ИспользоватьДоплатуЗаДниБолезни : Булево
ИспользоватьДоходыВНатуральнойФорме : Булево
ИспользоватьДСВ : Булево
ИспользоватьЕдиновременнуюВыплатуКОтпуску : Булево
ИспользоватьИндексациюЗаработка : Булево
ИспользоватьИндивидуальныйГрафикПриСменеГрафикаРаботы : Булево
ИспользоватьИсполнительныеЛисты : Булево
ИспользоватьКвалификационнуюНадбавку : Булево
ИспользоватьКраткосрочныеИзмененияОплатыТрудаВЗависимостиОтВыполняемойРаботы : Булево
ИспользоватьМатериальнуюПомощь : Булево
ИспользоватьМатериальнуюПомощьПриОтпуске : Булево
ИспользоватьНадбавкуЗаВредность : Булево
ИспользоватьНачисленияПоДоговорам : Булево
ИспользоватьНесколькоПлановыхНачислений : Булево
ИспользоватьНесколькоТарифныхСтавок : Булево
ИспользоватьОплатуВнутрисменныхКомандировок : Булево
ИспользоватьОплатуВнутрисменныхПростоев : Булево
ИспользоватьОплатуКомандировок : Булево
ИспользоватьОплатуПереработокСуммированногоУчета : Булево
ИспользоватьОплатуПоСреднемуЗаработку : Булево
ИспользоватьОплатуПоСреднемуЗаработкуВнутрисменную : Булево
ИспользоватьОплатуПраздничныхИВыходных : Булево
ИспользоватьОплатуПростоев : Булево
ИспользоватьОплатуСверхурочных : Булево
ИспользоватьОтгулы : Булево
ИспользоватьОтпускаБезОплаты : Булево
ИспользоватьОтпускаДляПострадавшихВАварииЧАЭС : Булево
ИспользоватьОтпускаУчебные : Булево
ИспользоватьПереводыНаОплатуПоСреднемуЗаработку : Булево
ИспользоватьПризыПодарки : Булево
ИспользоватьПрофсоюзныеВзносы : Булево
ИспользоватьПрочиеУдержанияВПользуТретьихЛиц : Булево
ИспользоватьРасчетПервойПоловиныМесяца : Булево
ИспользоватьРегистрациюПрочихДоходов : Булево
ИспользоватьСдельныйЗаработок : Булево
ИспользоватьСовмещениеПрофессийДолжностей : Булево
ИспользоватьТарифныеСеткиПриРасчетеЗарплаты : Булево
ИспользоватьТарифныеСеткиПриРасчетеЗарплатыБюджет : Булево
ИспользоватьТарифныеСеткиПриРасчетеЗарплатыХозрасчет : Булево
ИспользоватьУдержанияВСчетРасчетовПоПрочимОперациям : Булево
ИспользоватьУчетВнутрисменныхПрочихНевыходов : Булево
ИспользоватьУчетВремениСотрудниковВЧасах : Булево
ИспользоватьУчетПрочихНевыходов : Булево
НачислятьРазовуюПремиюОтдельнымДокументом : Булево
НачислятьРазовыеНачисленияОтдельнымДокументом : Булево
ОграничиватьНачалоРасчетногоПериодаСреднегоЗаработкаДатойПриема : Булево
ОплачиватьДлительныеКомандировкиПомесячно : Булево
ПереноситьДанныеВДругойУчетСреднегоЗаработка : Булево
ПорядокРасчетаСтоимостиЕдиницыВремени : Порядок расчета стоимости часа (дня) оплаты труда сотрудников
РазрешеноИзменениеПКУВКадровыхДокументах : Булево
РегистрироватьКомпенсациюЗаЗадержкуЗарплатыВДоходахСтраховыхВзносов : Булево
СпособУдержанияИзлишнеНачисленныхОтпускных : Способы удержания излишне начисленных отпускных
}
@enduml
