@startuml НастройкиКомандПечати
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиКомандПечати as "Настройки команд печати" <<РегистрыСведений>>
{
..Измерения..
Владелец : Справочник.Идентификатор объекта метаданных
УникальныйИдентификатор : Строка
..Ресурсы..
Видимость : Булево
}
@enduml
