@startuml НастройкаКонтроляОбеспечения
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкаКонтроляОбеспечения as "Настройка контроля обеспечения" <<РегистрыСведений>>
{
..Измерения..
Склад : Справочник.Склад (складская территория)
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
..Ресурсы..
Контролировать : Булево
}
@enduml
