@startuml ВерсииПодсистемОбластейДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ВерсииПодсистемОбластейДанных as "Версии подсистем областей данных" <<РегистрыСведений>>
{
..Измерения..
ИмяПодсистемы : Строка
..Ресурсы..
Версия : Строка
..Реквизиты..
ВыполненаРегистрацияОтложенныхОбработчиков : Булево
}
@enduml
