@startuml ПредоставлениеСоциальныхВычетовУРаботодателя
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПредоставлениеСоциальныхВычетовУРаботодателя as "Предоставление социальных вычетов у работодателя" <<РегистрыСведений>>
{
..Измерения..
ГоловнаяОрганизация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
КатегорияВзносов : Категории удержаний
ДокументОснование : Документ.Удержание добровольных взносов в НПФ\rДокумент.Удержание добровольных страховых взносов\rДокумент.Перенос данных
..Ресурсы..
НеПредоставлятьВычет : Булево
ДействуетДо : Дата
НеПредоставлятьВычетПоОкончании : Булево
}
@enduml
