@startuml ОбъектыИнтегрированныеС1СДокументооборотом
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОбъектыИнтегрированныеС1СДокументооборотом as "Объекты, интегрированные с 1С:Документооборотом" <<РегистрыСведений>>
{
..Измерения..
Объект : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
ТипОбъектаДокументооборота : Строка
ИдентификаторОбъектаДокументооборота : Строка
}
@enduml
