@startuml ЗначенияПоказателейУдержаний
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗначенияПоказателейУдержаний as "Значения показателей удержаний" <<РегистрыСведений>>
{
..Измерения..
РегистраторИзмерение : Документ.Сторнирование начислений\rДокумент.Начисление по договорам\rДокумент.Простой сотрудников\r...
ИдентификаторСтроки : Число 7, 0
Показатель : Справочник.Показатель
..Ресурсы..
Значение : Число 15, 5
}
@enduml
