@startuml СостоянияЗаказовПоставщикам
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияЗаказовПоставщикам as "Состояния заказов поставщикам" <<РегистрыСведений>>
{
..Измерения..
Заказ : Документ.Заказ поставщику
..Ресурсы..
Состояние : Состояния заказов поставщикам
ДатаСобытия : Дата
..Реквизиты..
СуммаОплаты : Число 15, 2
ПроцентОплаты : Число 3, 0
СуммаПоступления : Число 15, 2
ПроцентПоступления : Число 3, 0
СуммаДолга : Число 15, 2
ПроцентДолга : Число 3, 0
ЕстьРасхожденияОрдерНакладная : Булево
}
@enduml
