@startuml ИдентификаторыОбъектовВерсийРасширений
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИдентификаторыОбъектовВерсийРасширений as "Идентификаторы объектов версий расширений" <<РегистрыСведений>>
{
..Измерения..
ВерсияРасширений : Справочник.Версия расширений
ПолноеИмяОбъекта : Строка
Идентификатор : Справочник.Идентификатор объекта метаданных расширения
}
@enduml
