@startuml ИсторияПоказателейПоШтатномуРасписанию
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИсторияПоказателейПоШтатномуРасписанию as "История показателей по штатному расписанию" <<РегистрыСведений>>
{
..Измерения..
Дата : Дата
ПозицияШтатногоРасписания : Справочник.Позиция
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Показатель : Справочник.Показатель
..Ресурсы..
Значение : Число 15, 5
ЗначениеМин : Число 15, 5
ЗначениеМакс : Число 15, 5
}
@enduml
