@startuml АктивированныеАгентыРезервногоКопирования
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.АктивированныеАгентыРезервногоКопирования as "Активированные агенты резервного копирования" <<РегистрыСведений>>
{
..Измерения..
MachineGuid : Строка
..Реквизиты..
ДатаПроверки : Дата
АгентКопированияАктивированНаТекущийЛогин : Булево
СрокОкончанияПодписки : Дата
АгентКопированияАктивированНаДругойЛогин : Булево
}
@enduml
