@startuml НакопленныеСтажиФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НакопленныеСтажиФизическихЛиц as "Накопленные стажи физических лиц" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
ВидСтажа : Справочник.Вид стажа
ДатаНачала : Дата
ДатаОкончания : Дата
..Ресурсы..
РазмерМесяцев : Число 3, 0
РазмерДней : Число 2, 0
Прерван : Булево
}
@enduml
