@startuml СостоянияКонтрагентовБЭД
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияКонтрагентовБЭД as "Состояния контрагентов БЭД" <<РегистрыСведений>>
{
..Измерения..
Контрагент : Справочник.Контрагент
..Ресурсы..
Состояние : Состояния контрагента БЭД
..Реквизиты..
ИНН : Строка
КПП : Строка
}
@enduml
