@startuml ПериодыБолезниУходаЗаДетьми
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПериодыБолезниУходаЗаДетьми as "Периоды болезни, ухода за детьми и пр." <<РегистрыСведений>>
{
..Измерения..
ГоловнаяОрганизация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
Год : Число 4, 0
Начало : Дата
Окончание : Дата
..Ресурсы..
ВидБолезниУходаЗаДетьми : Строка
Дни : Число 10, 0
}
@enduml
