@startuml УдалитьХранимыеФайлыВерсий
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьХранимыеФайлыВерсий as "(не используется) Хранимые файлы версий" <<РегистрыСведений>>
{
..Измерения..
ВерсияФайла : Справочник.Версия файла
..Ресурсы..
ХранимыйФайл : Хранилище значения
}
@enduml
