@startuml КатегорииНовостейИнтервалыВерсий
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КатегорииНовостейИнтервалыВерсий as "Категории новостей, интервалы версий" <<РегистрыСведений>>
{
..Измерения..
Новость : Справочник.Новость
КатегорияНовостей : Категория новостей
Продукт : Строка
ВерсияОТ : Строка
ВерсияДО : Строка
}
@enduml
