@startuml СобытияМониторингаСПАРКРиски
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СобытияМониторингаСПАРКРиски as "События мониторинга 1СПАРК Риски" <<РегистрыСведений>>
{
..Измерения..
Идентификатор : Уникальный идентификатор
Контрагент : Справочник.Контрагент
..Ресурсы..
ТипСобытияИдентификатор : Уникальный идентификатор
ДатаМониторинга : Дата
НовоеЗначение : Строка
СтароеЗначение : Строка
}
@enduml
