@startuml ПрименениеПлановыхНачисленийИспр
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПрименениеПлановыхНачисленийИспр as "Применение плановых начислений испр" <<РегистрыСведений>>
{
..Измерения..
РегистраторИзмерение : Документ.Изменение условий оплаты отпуска по уходу за ребенком\rДокумент.Восстановление в должности\rДокумент.Возврат из отпуска по уходу\r...
ПериодИзмерение : Дата
Сотрудник : Справочник.Сотрудник
..Ресурсы..
Применение : Булево
ДействуетДо : Дата
ПрименениеПоОкончании : Булево
}
@enduml
