@startuml ДоступныеВерсииАгентаКопированияОблачногоАрхива
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДоступныеВерсииАгентаКопированияОблачногоАрхива as "Доступные версии агента копирования облачного архива" <<РегистрыСведений>>
{
..Измерения..
ВерсияПодсистемы : Строка
ВерсияАгентаКопирования : Строка
ТипОС : Строка
ВерсияОС : Строка
..Реквизиты..
ВерсияАгентаКопированияДляСортировки : Строка
СрокГодностиАгентаКопирования : Дата
РазмерДистрибутиваБайт : Число 10, 0
СсылкаНаСкачивание : Строка
КонтрольнаяСумма : Строка
ТекстЧтоНовогоВВерсии : Строка
ТекстПорядокОбновления : Строка
}
@enduml
