@startuml ОчередьПередачиДанныхЕГАИС
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОчередьПередачиДанныхЕГАИС as "Очередь передачи данных ЕГАИС" <<РегистрыСведений>>
{
..Измерения..
Сообщение : Справочник.Сообщение обмена с ЕГАИС
..Ресурсы..
ОрганизацияЕГАИС : Справочник.Организация ЕГАИС
}
@enduml
