@startuml ГрафикНачисленийКредитовИДепозитов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ГрафикНачисленийКредитовИДепозитов as "График начислений" <<РегистрыСведений>>
{
..Измерения..
ВариантГрафика : Справочник.Вариант графика
..Ресурсы..
Проценты : Число 15, 2
Комиссия : Число 15, 2
}
@enduml
