@startuml ЗамерыОперацииСтатистики
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗамерыОперацииСтатистики as "Замеры операции статистики" <<РегистрыСведений>>
{
..Измерения..
ПериодОкончание : Дата
ОперацияСтатистики : Уникальный идентификатор
ИдентификаторУдаления : Дата
..Ресурсы..
КоличествоЗначений : Число 15, 3
СуммаЗначений : Число 15, 3
}
@enduml
