@startuml АмортизационныеГруппыОКОФ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.АмортизационныеГруппыОКОФ as "Амортизационные группы ОКОФ" <<РегистрыСведений>>
{
..Измерения..
ОКОФ : Справочник.Элемент классификатора ОКОФ
АмортизационнаяГруппа : Амортизационные группы
..Ресурсы..
Примечание : Строка
}
@enduml
