@startuml ДанныеОбъектовДляРегистрацииВОбменах
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДанныеОбъектовДляРегистрацииВОбменах as "Данные объектов для регистрации в обменах" <<РегистрыСведений>>
{
..Измерения..
Ссылка : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
УзелИнформационнойБазы : Синхронизация данных через универсальный формат\rОбмен с подключаемым оборудованием Offline\rОбрабатываемый объект\r...
}
@enduml
