@startuml ВерсииОбъектов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ВерсииОбъектов as "Версии объектов" <<РегистрыСведений>>
{
..Измерения..
Объект : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
НомерВерсии : Число 10, 0
..Ресурсы..
ВерсияОбъекта : Хранилище значения
ТабличныеДокументы : Хранилище значения
..Реквизиты..
АвторВерсии : Синхронизация данных через универсальный формат\rОбмен с подключаемым оборудованием Offline\rСправочник.Внешний пользователь\r...
ДатаВерсии : Дата
Комментарий : Строка
ТипВерсииОбъекта : Типы версий объекта
ВерсияПроигнорирована : Булево
РазмерДанных : Число 15, 0
КонтрольнаяСумма : Строка
ЕстьДанныеВерсии : Булево
ВерсияВладелец : Число 10, 0
Узел : Строка
Синхронизируется : Булево
Смещение : Число 10, 0
}
@enduml
