@startuml МестонахождениеОС
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.МестонахождениеОС as "Местонахождение ОС" <<РегистрыСведений>>
{
..Измерения..
ОсновноеСредство : Справочник.Объект эксплуатации
..Ресурсы..
Организация : Справочник.Организация
МОЛ : Справочник.Физическое лицо
Местонахождение : Справочник.Подразделение
АдресМестонахождения : Строка
Арендатор : Справочник.Организация\rСправочник.Контрагент
ПодразделениеАрендатора : Справочник.Подразделение
МОЛАрендатора : Справочник.Физическое лицо
АдресМестонахожденияАрендатора : Строка
..Реквизиты..
ОтражатьВРеглУчете : Булево
ОтражатьВУпрУчете : Булево
}
@enduml
