@startuml ДокументыПоНМА
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДокументыПоНМА as "Документы по НМА" <<РегистрыСведений>>
{
..Измерения..
ТипСсылки : Справочник.Идентификатор объекта метаданных
ХозяйственнаяОперация : Хозяйственные операции
НомерЗаписи : Число 10, 0
Дата : Дата
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Ссылка : Документ.Внутреннее потребление товаров\rДокумент.Подготовка к передаче НМА\rДокумент.Переоценка НМА\r...
ДополнительнаяЗапись : Булево
..Ресурсы..
Проведен : Булево
ОтражатьВРеглУчете : Булево
ОтражатьВУпрУчете : Булево
}
@enduml
