@startuml СтрокиОтчетностиРасходовИЧисленностиРаботниковГосударственныхОрганов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтрокиОтчетностиРасходовИЧисленностиРаботниковГосударственныхОрганов as "Строки отчетности расходов и численности работников государственных органов" <<РегистрыСведений>>
{
..Измерения..
Должность : Справочник.Должность
..Ресурсы..
СтрокаОтчетностиРасходовИЧисленностиРаботниковГосударственныхОрганов : Справочник.Строка отчетности расходов и численности
}
@enduml
