@startuml НачальныеОстаткиОтпусков
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НачальныеОстаткиОтпусков as "Начальные остатки отпусков" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ВидЕжегодногоОтпуска : Справочник.Вид отпуска
ДатаОстатка : Дата
РабочийГодНачало : Дата
..Ресурсы..
УдалитьРабочийГодНачало : Дата
РабочийГодОкончание : Дата
КоличествоДней : Число 5, 2
}
@enduml
