@startuml УдалитьБлокировкиСеансовОбластиДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьБлокировкиСеансовОбластиДанных as "(не используется) Блокировки сеансов области данных" <<РегистрыСведений>>
{
..Измерения..
ОбластьДанных : Число 7, 0
..Ресурсы..
НачалоБлокировки : Дата
КонецБлокировки : Дата
СообщениеБлокировки : Строка
Эксклюзивная : Булево
}
@enduml
