@startuml ЖурналУчетаСчетовФактур
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЖурналУчетаСчетовФактур as "Журнал учета счетов-фактур" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Контрагент : Справочник.Организация\rСправочник.Контрагент
СчетФактура : Документ.Запись книги покупок\rДокумент.Счет-фактура полученный (аванс)\rДокумент.Таможенная декларация на импорт\r...
ЧастьЖурнала : Части журнала учета счетов-фактур
ИндексСтроки : Число 10, 0
Сторно : Булево
ИсправленныйСчетФактура : Документ.Счет-фактура полученный (аванс)\rДокумент.Счет-фактура выданный (аванс)\rДокумент.Счет-фактура выданный\r...
СчетФактураВыданныйПокупателю : Документ.Счет-фактура выданный\rДокумент.Счет-фактура выданный комиссионеру (агенту)
СчетФактураПолученныйОтПродавца : Документ.Счет-фактура полученный
ИсправлениеСобственнойОшибки : Булево
..Ресурсы..
ДатаВыставленияПолучения : Дата
КодСпособаВыставленияПолучения : Число 1, 0
КодВидаОперации : Строка
НомерСчетаФактуры : Строка
ДатаСчетаФактуры : Дата
НомерИсправления : Строка
ДатаИсправления : Дата
НомерКорректировочногоСчетаФактуры : Строка
ДатаКорректировочногоСчетаФактуры : Дата
НомерИсправленияКорректировочногоСчетаФактуры : Строка
ДатаИсправленияКорректировочногоСчетаФактуры : Дата
Валюта : Справочник.Валюта
СуммаПоСчетуФактуре : Число 15, 2
СуммаНДС : Число 15, 2
СуммаПоСчетуФактуреРазницаУменьшение : Число 15, 2
СуммаПоСчетуФактуреРазницаУвеличение : Число 15, 2
СуммаНДСРазницаУменьшение : Число 15, 2
СуммаНДСРазницаУвеличение : Число 15, 2
ПоСтавкеБезНДС : Булево
СчетФактураНеВыставляется : Булево
Продавец : Справочник.Контрагент
КППКонтрагента : Строка
Посредник : Справочник.Организация\rСправочник.Контрагент
УдалитьСчетФактураВыданныйПокупателю : Документ.Счет-фактура выданный\rДокумент.Счет-фактура выданный комиссионеру (агенту)
Субкомиссионер : Справочник.Организация\rСправочник.Контрагент
КодВидаСделки : Строка
НомерСчетаФактурыПродавца : Строка
СуммаПоСчетуФактуреКомиссия : Число 15, 2
СуммаНДСКомиссия : Число 15, 2
СуммаПоСчетуФактуреРазницаУменьшениеКомиссия : Число 15, 2
СуммаПоСчетуФактуреРазницаУвеличениеКомиссия : Число 15, 2
СуммаНДСРазницаУменьшениеКомиссия : Число 15, 2
СуммаНДСРазницаУвеличениеКомиссия : Число 15, 2
КодВидаОперацииКомиссия : Строка
ДатаСчетаФактурыПродавца : Дата
ИННКонтрагента : Строка
ИННПродавца : Строка
КПППродавца : Строка
ИННСубкомиссионера : Строка
КППСубкомиссионера : Строка
}
@enduml
