@startuml ЖурналОтчетовСтатусы
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЖурналОтчетовСтатусы as "Журнал отчетов статусы" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Ссылка : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
..Ресурсы..
Статус : Строка
..Реквизиты..
НаименованиеОтчета : Строка
ВидКонтролирующегоОргана : Типы контролирующих органов
КодКонтролирующегоОргана : Строка
ВариантОтчета : Строка
ДатаНачала : Дата
ФинансовыйПериод : Строка
ДатаОкончания : Дата
ПометкаУдаления : Булево
СостояниеСдачиОтчетности : Состояние сдачи отчетности
НеОтправляетсяВКонтролирующийОрган : Булево
ПредставлениеКонтролирующегоОргана : Строка
Комментарий : Строка
ЕстьКритическиеОшибкиОтправки : Булево
Непрочтенное : Булево
Скрыт : Булево
ИндексКартинки : Число 1, 0
}
@enduml
