@startuml ГруппыЗначенийДоступа
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ГруппыЗначенийДоступа as "Группы значений доступа" <<РегистрыСведений>>
{
..Измерения..
ЗначениеДоступа : Справочник.Статьи бюджетов\rСправочник.Вид номенклатуры\rСправочник.Номенклатура\r...
ГруппаЗначенийДоступа : Справочник.Статьи бюджетов\rСправочник.Вид номенклатуры\rСправочник.Номенклатура\r...
ГруппаДанных : Число 1, 0
}
@enduml
