@startuml ДанныеПроизводственногоКалендаря
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДанныеПроизводственногоКалендаря as "Данные производственного календаря" <<РегистрыСведений>>
{
..Измерения..
ПроизводственныйКалендарь : Справочник.Производственный календарь
Дата : Дата
Год : Число 4, 0
..Ресурсы..
ВидДня : Виды дней производственного календаря
ДатаПереноса : Дата
}
@enduml
