@startuml ОстаткиНаБанковскихСчетахПоДаннымВыписок
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОстаткиНаБанковскихСчетахПоДаннымВыписок as "Остатки на банковских счетах по данным выписок" <<РегистрыСведений>>
{
..Измерения..
БанковскийСчет : Справочник.Банковский счет организации
..Ресурсы..
НачальныйОстаток : Число 15, 2
Поступление : Число 15, 2
Списание : Число 15, 2
КонечныйОстаток : Число 15, 2
}
@enduml
