@startuml ЗаданияКРасчетуАмортизацииОС
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗаданияКРасчетуАмортизацииОС as "Задания к расчету амортизации ОС" <<РегистрыСведений>>
{
..Измерения..
Месяц : Дата
Организация : Справочник.Организация
НомерПакета : Число 10, 0
НомерЗадания : Число 15, 0
Документ : Документ.Списание ОС\rДокумент.Передача ОС арендатору\rДокумент.Принятие к учету ОС\r...
}
@enduml
