@startuml ЗаданияКРасчетуОчередиПроизводственныхОпераций
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗаданияКРасчетуОчередиПроизводственныхОпераций as "Задания к расчету очереди производственных операций" <<РегистрыСведений>>
{
..Измерения..
ОбъектРасчета : Документ.Этап производства
Идентификатор : Уникальный идентификатор
ДеньРегистрации : Число 7, 0
}
@enduml
