@startuml ОрганизацииДляОбменаГИСМ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОрганизацииДляОбменаГИСМ as "Организации для обмена с ГИСМ" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
..Ресурсы..
GLN : Строка
}
@enduml
