@startuml УдалитьНастройкиВерсионированияОбъектов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьНастройкиВерсионированияОбъектов as "(не используется) Настройки версионирования объектов" <<РегистрыСведений>>
{
..Измерения..
ТипОбъекта : Строка
..Ресурсы..
Вариант : Варианты версионирования объектов
Использовать : Булево
СрокХраненияВерсий : Сроки хранения версий
}
@enduml
