@startuml НачислениеАмортизацииОСБухгалтерскийУчет
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НачислениеАмортизацииОСБухгалтерскийУчет as "Начисление амортизации ОС (бухгалтерский учет, версия 2.2)" <<РегистрыСведений>>
{
..Измерения..
ОсновноеСредство : Справочник.Объект эксплуатации
Организация : Справочник.Организация
..Ресурсы..
НачислятьАмортизацию : Булево
}
@enduml
