@startuml СостоянияЭтаповПроизводства
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияЭтаповПроизводства as "Состояния этапов производства" <<РегистрыСведений>>
{
..Измерения..
Распоряжение : Документ.Заказ на производство
Этап : Документ.Этап производства
..Ресурсы..
СостояниеНаМежцеховомУровне : Состояния этапов на межцеховом уровне
СостояниеНаВнутрицеховомУровне : Состояния этапов на внутрицеховом уровне
ТребуетОбеспечения : Булево
ТребуетОформленияВыработки : Булево
СостояниеОпераций : Состояния операций этапа производства
..Реквизиты..
КодСостоянияНаВнутрицеховомУровне : Число 1, 0
}
@enduml
