@startuml СведенияРеглОтчетАлкоПрил14Декларация
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СведенияРеглОтчетАлкоПрил14Декларация as "Сведения регл отчет алко прил14 декларация" <<РегистрыСведений>>
{
..Измерения..
Документ : Документ.Регламентированный отчет
УдалитьИндексСтраницы : Число 10, 0
ИндексСтроки : Число 10, 0
ИДДокИндСтраницы : Строка
Организация : Справочник.Организация
..Ресурсы..
П000010000308 : Строка
П000010000309 : Строка
П000010000310 : Число 15, 5
..Реквизиты..
Активно : Булево
}
@enduml
