@startuml ИспользованиеПоставляемыхРасширенийВОбластяхДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИспользованиеПоставляемыхРасширенийВОбластяхДанных as "Использование поставляемых расширений в областях данных" <<РегистрыСведений>>
{
..Измерения..
ПоставляемоеРасширение : Справочник.Поставляемое расширение
..Ресурсы..
ИспользуемоеРасширение : Уникальный идентификатор
Инсталляция : Уникальный идентификатор
}
@enduml
