@startuml СведенияОНачисленияхДляРасчетаСреднегоЗаработкаФСС
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СведенияОНачисленияхДляРасчетаСреднегоЗаработкаФСС as "Сведения о начислениях для расчета среднего заработка (ФСС)" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
ГоловнаяОрганизация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
Месяц : Дата
ПорядокРасчета : Порядок расчета среднего заработка ФСС
СтатьяФинансирования : Справочник.Статья финансирования
..Ресурсы..
Сумма : Число 15, 2
..Реквизиты..
ДанныеИзУчетаСреднегоОбщий : Булево
}
@enduml
