@startuml ТрудоваяДеятельностьФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ТрудоваяДеятельностьФизическихЛиц as "Трудовая деятельность" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
НомерПоПорядку : Число 2, 0
..Ресурсы..
Организация : Строка
ДатаНачала : Дата
ДатаОкончания : Дата
Должность : Строка
Обязанности : Строка
СфераДеятельностиКомпании : Строка
}
@enduml
