@startuml ПорядокУчетаНМАУУ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПорядокУчетаНМАУУ as "Порядок учета НМА (управленческий учет)" <<РегистрыСведений>>
{
..Измерения..
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
Организация : Справочник.Организация
..Ресурсы..
Состояние : Виды состояний НМА
НачислятьАмортизациюУУ : Булево
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
СпособОтраженияРасходов : Документ.Изменение параметров НМА
ПередаватьРасходыВДругуюОрганизацию : Булево
ОрганизацияПолучательРасходов : Справочник.Организация
}
@enduml
