@startuml ОчередьИзвлеченияТекста
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОчередьИзвлеченияТекста as "Очередь извлечения текста" <<РегистрыСведений>>
{
..Измерения..
ИсточникТекста : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rСправочник.Присоединенные файлы (Поступление безналичных денежных средств)\r...
}
@enduml
