@startuml ЗапросыРазрешенийНаИспользованиеВнешнихРесурсовОбластейДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗапросыРазрешенийНаИспользованиеВнешнихРесурсовОбластейДанных as "Запросы разрешений на использование внешних ресурсов областей данных" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторыЗапросов : Уникальный идентификатор
..Ресурсы..
ТипПрограммногоМодуля : Справочник.Идентификатор объекта метаданных
ИдентификаторПрограммногоМодуля : Уникальный идентификатор
ТипВладельца : Справочник.Идентификатор объекта метаданных
ИдентификаторВладельца : Уникальный идентификатор
БезопасныйРежим : Булево\rСтрока
..Реквизиты..
РежимЗамещения : Булево
ДобавляемыеРазрешения : Строка
УдаляемыеРазрешения : Строка
}
@enduml
