@startuml НастройкиРасчетаСреднегоЗаработка
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиРасчетаСреднегоЗаработка as "Настройки расчета среднего заработка" <<РегистрыСведений>>
{
..Ресурсы..
ИспользоватьОсновныеНачисленияБезИндексации : Булево
ИспользоватьОтработаноДней : Булево
ИспользоватьОтработаноПоПятидневке : Булево
ИспользоватьОтработаноПоШестидневке : Булево
ИспользоватьОтработаноЧасов : Булево
ИспользоватьПремииЗаГодПроцентом : Булево
ИспользоватьПремииЗаГодПроцентомБезИндексации : Булево
ИспользоватьПремииЗаГодСуммой : Булево
ИспользоватьПремииЗаГодСуммойБезИндексации : Булево
ИспользоватьПремииПроцентом : Булево
ИспользоватьПремииПроцентомБезИндексации : Булево
ИспользоватьПремииСуммой : Булево
ИспользоватьПремииСуммойБезИндексации : Булево
СреднийЗаработокФССРазличаетсяПоПорядкуРасчета : Булево
}
@enduml
