@startuml СвязиПоказателейБюджетов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СвязиПоказателейБюджетов as "Связи показателей бюджетов" <<РегистрыСведений>>
{
..Измерения..
СтатьяБюджетов : Справочник.Статьи бюджетов
СвязанныйПоказательБюджетов : Справочник.Показатели бюджетов
..Ресурсы..
Расход : Булево
Аналитика1 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика2 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика3 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика4 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика5 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика6 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТранслироватьАналитику1 : Булево
ТранслироватьАналитику2 : Булево
ТранслироватьАналитику3 : Булево
ТранслироватьАналитику4 : Булево
ТранслироватьАналитику5 : Булево
ТранслироватьАналитику6 : Булево
Коэффициент : Число 5, 2
АдресТрансляцииАналитики1 : Число 1, 0
АдресТрансляцииАналитики2 : Число 1, 0
АдресТрансляцииАналитики3 : Число 1, 0
АдресТрансляцииАналитики4 : Число 1, 0
АдресТрансляцииАналитики5 : Число 1, 0
АдресТрансляцииАналитики6 : Число 1, 0
}
@enduml
