@startuml НаработкиОбъектовЭксплуатации
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НаработкиОбъектовЭксплуатации as "Наработки объектов эксплуатации" <<РегистрыСведений>>
{
..Измерения..
ОбъектЭксплуатации : Справочник.Объект эксплуатации\rСправочник.Узел объекта эксплуатации
ПоказательНаработки : Справочник.Показатель наработки
..Ресурсы..
Значение : Число 15, 3
СреднесуточноеЗначение : Число 15, 3
..Реквизиты..
КорректировочнаяЗапись : Булево
}
@enduml
