@startuml СтавкиНалогаНаИмуществоПоОтдельнымОсновнымСредствам
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтавкиНалогаНаИмуществоПоОтдельнымОсновнымСредствам as "Ставки налога на имущество по отдельным основным средствам" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ОсновноеСредство : Справочник.Объект эксплуатации
КодПоОКАТО : Строка
КодПоОКТМО : Строка
..Ресурсы..
ПостановкаНаУчетВНалоговомОргане : Постановка на учет в налоговом органе
НалоговыйОрган : Справочник.Регистрация в налоговом органе
ПорядокНалогообложения : Порядок налогообложения имущества
НалоговаяСтавка : Число 3, 2
КодНалоговойЛьготыОсвобождениеОтНалогообложения : Строка
СниженнаяНалоговаяСтавка : Число 3, 2
УдалитьВидИмущества : Удалить виды имущества
ДоляСтоимостиЧислитель : Число 10, 0
ДоляСтоимостиЗнаменатель : Число 10, 0
НалоговаяБаза : Налоговая база по налогу на имущество
КадастроваяСтоимость : Число 15, 2
НеоблагаемаяКадастроваяСтоимость : Число 15, 2
КадастровыйНомер : Строка
КадастровыйНомерПомещения : Строка
ДатаРегистрацииПраваСобственности : Дата
ДатаПрекращенияПраваСобственности : Дата
ИспользуетсяТолькоВДеятельностиОблагаемойЕНВД : Булево
ДвижимоеИмуществоПодлежащееНалогообложению : Булево
КодВидаИмущества : Строка
ДоляВПравеОбщейСобственностиЧислитель : Число 10, 0
ДоляВПравеОбщейСобственностиЗнаменатель : Число 10, 0
УсловныйНомер : Строка
КБК : Строка
ДоляПлощадиЧислитель : Число 10, 0
ДоляПлощадиЗнаменатель : Число 10, 0
}
@enduml
