@startuml НастройкиПользователейБИП
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиПользователейБИП as "Настройки пользователей БИП" <<РегистрыСведений>>
{
..Измерения..
Пользователь : Справочник.Пользователь
..Ресурсы..
РазрешенаНастройкаОтборов : Булево
НастройкиПоказаНовостей : Хранилище значения
}
@enduml
