@startuml ДатыПередачиТоваровНаКомиссию
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДатыПередачиТоваровНаКомиссию as "Даты передачи товаров на комиссию" <<РегистрыСведений>>
{
..Измерения..
ВидЗапасов : Справочник.Вид запасов
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
НомерГТД : Справочник.Номер ГТД
Соглашение : Справочник.Соглашение об условиях продаж
Организация : Справочник.Организация
..Ресурсы..
ДатаПередачи : Дата
}
@enduml
