@startuml ЖурналСобытийЭД
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЖурналСобытийЭД as "Журнал событий ЭДО" <<РегистрыСведений>>
{
..Измерения..
ПрисоединенныйФайл : Справочник.Присоединенный файл (Электронный документ)
НомерЗаписи : Число 10, 0
..Ресурсы..
ВладелецЭД : Документ.Входящий электронный документ\rДокумент.Исходящий электронный документ
Дата : Дата
Пользователь : Справочник.Пользователь
СтатусЭД : Статусы ЭД
УдалитьСтатусЭД : Строка
Ответственный : Справочник.Пользователь
..Реквизиты..
Комментарий : Строка
}
@enduml
