@startuml ПрименениеПлановыхНачислений
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПрименениеПлановыхНачислений as "Применение плановых начислений" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
..Ресурсы..
Применение : Булево
ДействуетДо : Дата
ПрименениеПоОкончании : Булево
}
@enduml
