@startuml БухучетРаспределениеОсновногоЗаработка
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.БухучетРаспределениеОсновногоЗаработка as "Бухучет распределение основного заработка" <<РегистрыСведений>>
{
..Измерения..
ПериодРегистрации : Дата
Сотрудник : Справочник.Сотрудник
Организация : Справочник.Организация
СтатьяФинансирования : Справочник.Статья финансирования
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОблагаетсяЕНВД : Булево
..Ресурсы..
ДоляРаспределения : Число 14, 3
}
@enduml
