@startuml ДанныеПроизводственногоКалендаряПомесячно
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДанныеПроизводственногоКалендаряПомесячно as "Данные производственного календаря помесячно" <<РегистрыСведений>>
{
..Измерения..
ПроизводственныйКалендарь : Справочник.Производственный календарь
Год : Число 4, 0
Месяц : Дата
..Ресурсы..
КалендарныхДней : Число 5, 0
РабочихДней : Число 5, 0
РабочихЧасовДлительностьНедели40Часов : Число 5, 2
РабочихЧасовДлительностьНедели36Часов : Число 5, 2
РабочихЧасовДлительностьНедели24Часа : Число 5, 2
}
@enduml
