@startuml РемонтыРабочихЦентров
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РемонтыРабочихЦентров as "Ремонты рабочих центров" <<РегистрыСведений>>
{
..Измерения..
ЗаказНаРемонт : Документ.Заказ на ремонт
РабочийЦентр : Справочник.Рабочий центр
ДатаНачала : Дата
ДатаЗавершения : Дата
}
@enduml
