@startuml ВсеОбновленияСПАРКОбщее
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ВсеОбновленияСПАРКОбщее as "Все обновления 1СПАРК Риски (общее)" <<РегистрыСведений>>
{
..Измерения..
ВидОбновления : Строка
..Ресурсы..
ДатаПоследнегоОбновления : Дата
ДатаСледующегоОбновления : Дата
}
@enduml
