@startuml ИсторияПодарочныхСертификатов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИсторияПодарочныхСертификатов as "История подарочных сертификатов" <<РегистрыСведений>>
{
..Измерения..
ПодарочныйСертификат : Справочник.Подарочный сертификат
..Ресурсы..
Статус : Статусы подарочных сертификатов
}
@enduml
