@startuml НаградыФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НаградыФизическихЛиц as "Награды" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
НомерПоПорядку : Число 2, 0
..Ресурсы..
Награда : Справочник.Награда
НомерПриказа : Строка
ДатаПриказа : Дата
НаименованиеПриказа : Строка
}
@enduml
