@startuml СчетаФактурыКомиссионерамКОформлению
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СчетаФактурыКомиссионерамКОформлению as "Счета-фактуры комиссионерам к оформлению" <<РегистрыСведений>>
{
..Измерения..
ОтчетКомиссионера : Документ.Отчет комиссионера (агента) о продажах\rДокумент.Отчет по комиссии между организациями
Покупатель : Справочник.Организация\rСправочник.Контрагент
ДатаСчетаФактуры : Дата
НомерСчетаФактуры : Строка
..Ресурсы..
СуммаСНДС : Число 15, 2
СуммаНДС : Число 15, 2
..Реквизиты..
Валюта : Справочник.Валюта
Организация : Справочник.Организация
Комиссионер : Справочник.Организация\rСправочник.Контрагент
}
@enduml
