@startuml ПорядокРасчетаСтоимостиЕдиницыВремениСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПорядокРасчетаСтоимостиЕдиницыВремениСотрудников as "Порядок расчета стоимости единицы времени сотрудников" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
ПорядокРасчета : Порядок расчета стоимости часа (дня) оплаты труда сотрудников
ДействуетДо : Дата
ПорядокРасчетаПоОкончании : Порядок расчета стоимости часа (дня) оплаты труда сотрудников
}
@enduml
