@startuml РасчетРазницВОценкеАктивовИОбязательств
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РасчетРазницВОценкеАктивовИОбязательств as "Расчет разниц в оценке активов и обязательств" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ВидАктивовИОбязательств : Виды активов и обязательств
Субконто1 : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
Субконто2 : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
Субконто3 : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
ВидРазницыПБУ18 : Вид разниц по ПБУ 18/02
Счет : Счет бухгалтерского учета
..Ресурсы..
НачальныйОстаток : Число 15, 2
Признаны : Число 15, 2
ПеренесеныНаДругиеОбъекты : Число 15, 2
ПовлиялиНаРазницыВОценкеРасходовННП : Число 15, 2
ПовлиялиНаРазницыВОценкеРасходовНеННП : Число 15, 2
КонечныйОстаток : Число 15, 2
}
@enduml
