@startuml ОчередьПроизводственныхОпераций
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОчередьПроизводственныхОпераций as "Очередь производственных операций" <<РегистрыСведений>>
{
..Измерения..
Подразделение : Справочник.Подразделение
Этап : Документ.Этап производства
Операция : Справочник.Операция
ИдентификаторОперации : Число 25, 0
..Ресурсы..
Запланировано : Число 15, 3
Создано : Число 15, 3
ОжиданиеПредшествующих : Число 15, 3
НачатыПредшествующие : Число 15, 3
МожноВыполнять : Число 15, 3
Выполняется : Число 15, 3
Выполнено : Число 15, 3
..Реквизиты..
Распоряжение : Документ.Заказ на производство
МаршрутнаяКарта : Справочник.Маршрутная карта
КоэффициентМаршрутнойКарты : Число 15, 3
ВремяВыполнения : Число 10, 1
ВремяВыполненияЕдИзм : Единицы измерения времени
НомерОперации : Число 10, 0
НомерСледующейОперации : Число 10, 0
Порядок : Число 1, 0
}
@enduml
