@startuml УдалитьСведенияОНачисленияхДляРасчетаСреднегоЗаработкаОбщий
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьСведенияОНачисленияхДляРасчетаСреднегоЗаработкаОбщий as "(Не используется) Сведения о начислениях для расчета среднего заработка (общий)" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
Месяц : Дата
ПорядокРасчета : Порядок расчета среднего заработка общий
СоставнаяЧасть : Учет начислений в среднем заработке общий
СтатьяФинансирования : Справочник.Статья финансирования
Индексируется : Булево
Год : Число 4, 0
ДатаНачалаБазовогоПериода : Дата
КоличествоМесяцев : Число 2, 0
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
Сумма : Число 15, 2
..Реквизиты..
ДанныеИзУчетаСреднегоФСС : Булево
}
@enduml
