@startuml НастройкиОтправителя
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиОтправителя as "Настройки отправителя" <<РегистрыСведений>>
{
..Измерения..
КаналСообщений : Строка
Получатель : Конечная точка
}
@enduml
