@startuml РазрешенияНаИспользованиеВнешнихРесурсов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РазрешенияНаИспользованиеВнешнихРесурсов as "Разрешения на использование внешних ресурсов" <<РегистрыСведений>>
{
..Измерения..
ТипПрограммногоМодуля : Справочник.Идентификатор объекта метаданных
ИдентификаторПрограммногоМодуля : Уникальный идентификатор
ТипВладельца : Справочник.Идентификатор объекта метаданных
ИдентификаторВладельца : Уникальный идентификатор
КлючРазрешения : Строка
..Реквизиты..
ТелоРазрешения : Строка
ДополнениеРазрешения : Строка
ПредставлениеПрограммногоМодуля : Строка
ПредставлениеВладельца : Строка
}
@enduml
