@startuml НачисленияПодключаемыеХарактеристики
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НачисленияПодключаемыеХарактеристики as "Подключаемые характеристики начислений" <<РегистрыСведений>>
{
..Измерения..
Объект : Начисление
Свойство : Подключаемая характеристика начисления
ИдентификаторИсточника : Строка
..Ресурсы..
Значение : Булево
}
@enduml
