@startuml ПлановыеНачисленияПоДоговорам
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПлановыеНачисленияПоДоговорам as "Плановые начисления по договорам" <<РегистрыСведений>>
{
..Измерения..
МесяцНачисления : Дата
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ДоговорАкт : Документ.Договор авторского заказа\rДокумент.Акт приемки выполненных работ\rДокумент.Договор (работы, услуги)
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
КодДохода : Справочник.Вид дохода НДФЛ
УдалитьКодДохода : Справочник.(не используется) Виды доходов НДФЛ
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
КодДоходаСтраховыеВзносы : Справочник.Вид дохода по страховым взносам
УдалитьКодДоходаСтраховыеВзносы : Справочник.(не используется) Виды доходов (взносы)
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОтношениеКЕНВД : Отношение к ЕНВД затрат на зарплату
Подразделение : Справочник.Подразделение
Сумма : Число 15, 2
СуммаВычета : Число 15, 2
СуммаЕНВД : Число 15, 2
ДатаНачала : Дата
ДатаОкончания : Дата
ЗаключенСоСтудентомРаботающимВСтудотряде : Булево
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
ПланируемаяДатаВыплаты : Дата
Территория : Справочник.Территория
..Реквизиты..
Договор : Документ.Договор авторского заказа\rДокумент.Договор (работы, услуги)
}
@enduml
