@startuml СоответствиеНоменклатурыЕГАИС
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СоответствиеНоменклатурыЕГАИС as "Соответствие номенклатуры ЕГАИС" <<РегистрыСведений>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
..Ресурсы..
АлкогольнаяПродукция : Справочник.Алкогольная продукция ЕГАИС
..Реквизиты..
Порядок : Число 10, 0
}
@enduml
