@startuml СвойстваЛокальныхКомпьютеровДляОблачногоАрхива
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СвойстваЛокальныхКомпьютеровДляОблачногоАрхива as "Свойства локальных компьютеров (для облачного архива)" <<РегистрыСведений>>
{
..Измерения..
ИмяКомпьютера : Строка
..Реквизиты..
MachineGuid : Строка
ДатаПроверки : Дата
ТипОС : Строка
ВерсияОС : Строка
ПрисутствуютФайлыСертификатов : Булево
ВерсияАгентаКопирования : Строка
КаталогУстановки : Строка
АгентКопированияУстановлен : Булево
ЛогинАдминистратораОС : Строка
}
@enduml
