@startuml ВыполнениеОперацийЗакрытияМесяца
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ВыполнениеОперацийЗакрытияМесяца as "Выполнение операций закрытия месяца" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ПериодРасчета : Дата
Операция : Операции закрытия месяца
РасчетВыполняется : Булево
..Ресурсы..
ДатаНачала : Дата
ДатаОкончания : Дата
БылиОшибки : Булево
..Реквизиты..
Длительность : Число 15, 0
ИдентификаторРасчета : Уникальный идентификатор
ИнформацияОЗапускеРасчета : Строка
}
@enduml
