@startuml ПараметрыТорговыхТочек
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПараметрыТорговыхТочек as "Параметры торговых точек" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ТорговаяТочка : Справочник.Торговая точка
..Ресурсы..
КодПоОКТМО : Строка
ТипТорговойТочки : Типы торговых точек
ВидТорговойДеятельности : Виды торговой деятельности облагаемые сбором
ОснованиеПользования : Основания пользования торговой точкой
ПостановкаНаУчетВНалоговомОргане : Постановка на учет в налоговом органе
НалоговыйОрган : Справочник.Регистрация в налоговом органе
ВидОбъектаНедвижимости : Виды объектов недвижимости облагаемых торговым сбором
КадастровыйНомер : Строка
НомерРазрешения : Строка
ПлощадьТорговогоЗала : Число 9, 2
КодНалоговойЛьготы : Строка
Ставка : Число 8, 0
СуммаЛьготы : Число 8, 0
СуммаСбора : Число 8, 0
Уведомление : Документ.Сторнирование начислений\rДокумент.Внутреннее потребление товаров\rДокумент.Назначение планового начисления\r...
ДатаПодачиУведомления : Дата
..Реквизиты..
ВидОперации : Виды операций торговые точки
РасшифровкаРасчета : Строка
}
@enduml
