@startuml СостоянияЭД
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияЭД as "Состояния электронных документов" <<РегистрыСведений>>
{
..Измерения..
СсылкаНаОбъект : Документ.Входящий электронный документ\rДокумент.Возврат товаров от клиента\rДокумент.Исходящий электронный документ\r...
..Ресурсы..
СостояниеВерсииЭД : Состояния версий электронных документов
ЭлектронныйДокумент : Документ.Входящий электронный документ\rДокумент.Исходящий электронный документ\rСправочник.Присоединенный файл (Электронный документ)
ДействияСНашейСтороны : Сводные состояния электронных документов
ДействияСоСтороныДругогоУчастника : Сводные состояния электронных документов
..Реквизиты..
Комментарий : Строка
ПредставлениеСостояния : Строка
}
@enduml
