@startuml НеразделенныеПользователи
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НеразделенныеПользователи as "Неразделенные пользователи" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторПользователяИБ : Уникальный идентификатор
..Ресурсы..
ПорядковыйНомер : Число 5, 0
ИмяПользователя : Строка
}
@enduml
