@startuml СостоянияДокументовОткрытияЛицевыхСчетов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияДокументовОткрытияЛицевыхСчетов as "Состояния документов открытия лицевых счетов" <<РегистрыСведений>>
{
..Измерения..
ДокументОткрытияЛицевыхСчетов : Документ.Заявка на открытие лицевых счетов
..Ресурсы..
Состояние : Состояние заявки на открытие лицевого счета сотрудника
Организация : Справочник.Организация
}
@enduml
