@startuml РасчетСтоимостиНалоговыхАктивовИОбязательств
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РасчетСтоимостиНалоговыхАктивовИОбязательств as "Расчет стоимости налоговых активов и обязательств" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ВидАктивовИОбязательств : Виды активов и обязательств
ВидАктивовИОбязательствПБУ18 : Виды активов и обязательств (по ПБУ18/02)
..Ресурсы..
Признаны : Число 15, 2
Списаны : Число 15, 2
ПризнаныСписаныНеННП : Число 15, 2
}
@enduml
