@startuml ПроцентЕНВДДляУчетаЗатратНаЗарплату
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПроцентЕНВДДляУчетаЗатратНаЗарплату as "Процент ЕНВД для учета затрат на зарплату" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Месяц : Дата
..Ресурсы..
Процент : Число 8, 5
}
@enduml
