@startuml ДатыЗапретаИзменения
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДатыЗапретаИзменения as "Даты запрета изменения (загрузки) данных" <<РегистрыСведений>>
{
..Измерения..
Раздел : Раздел дат запрета изменения
Объект : Справочник.Организация\rСправочник.Банковский счет организации\rСправочник.Касса\r...
Пользователь : Справочник.Внешний пользователь\rСправочник.Пользователь\rСправочник.Группа внешних пользователей\r...
..Ресурсы..
ДатаЗапрета : Дата
..Реквизиты..
ОписаниеДатыЗапрета : Строка
Комментарий : Строка
}
@enduml
