@startuml ОтветыНаЗапросыВыпискиИзЕГРЮЛ_ЕГРИП
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОтветыНаЗапросыВыпискиИзЕГРЮЛ_ЕГРИП as "Ответы на запросы выписок из ЕГРЮЛ/ЕГРИП" <<РегистрыСведений>>
{
..Измерения..
Запрос : Документ.Запрос на выписку из ЕГРЮЛ/ЕГРИП
ИмяФайла : Строка
..Ресурсы..
Данные : Хранилище значения
..Реквизиты..
Размер : Число 10, 0
РезультатОбработкиЗапроса : Строка
}
@enduml
