@startuml ДокументыСОшибкамиПроверкиКонтрагентов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДокументыСОшибкамиПроверкиКонтрагентов as "Документы с ошибками проверки контрагентов" <<РегистрыСведений>>
{
..Измерения..
Документ : Документ.Сторнирование начислений\rДокумент.Внутреннее потребление товаров\rДокумент.Назначение планового начисления\r...
}
@enduml
