@startuml ПлановыйФОТИтоги
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПлановыйФОТИтоги as "Плановый ФОТ итоги" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ДатаОкончания : Дата
Год : Дата
ГоловнаяОрганизация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
ОсновноеНачисление : Начисление
ВидТарифнойСтавки : Виды тарифных ставок
ТарифнаяСтавка : Число 15, 2
СовокупнаяТарифнаяСтавка : Число 15, 5
ФОТ : Число 15, 2
Надбавка : Число 15, 2
Используется : Булево
ПоказательТарифнойСтавки : Справочник.Показатель
..Реквизиты..
РегистраторСобытия : Документ.Назначение планового начисления\rДокумент.Изменение мест работы\rДокумент.Удержание по прочим операциям\r...
ПериодПредыдущейЗаписи : Дата
}
@enduml
