@startuml РазмерыГосударственныхПособий
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РазмерыГосударственныхПособий as "Размеры государственных пособий" <<РегистрыСведений>>
{
..Ресурсы..
ПриПостановкеНаУчетВРанниеСрокиБеременности : Число 10, 2
ПриРожденииРебенка : Число 10, 2
МинимумПособияПоУходуЗаПервымРебенкомДоПолутораЛет : Число 10, 2
МинимумПособияПоУходуЗаПоследующимРебенкомДоПолутораЛет : Число 10, 2
МаксимумПособияПоУходуЗаРебенкомДоПолутораЛет : Число 10, 2
ПоУходуЗаРебенкомДоТрехЛет : Число 10, 2
ВСвязиСоСмертью : Число 10, 2
}
@enduml
