@startuml СведенияОПользователях
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СведенияОПользователях as "Сведения о пользователях" <<РегистрыСведений>>
{
..Измерения..
Пользователь : Справочник.Внешний пользователь\rСправочник.Пользователь
..Ресурсы..
ПотребоватьСменуПароляПриВходе : Булево
СрокДействияНеОграничен : Булево
СрокДействия : Дата
ПросрочкаРаботыВПрограммеДоЗапрещенияВхода : Число 3, 0
ДатаРазрешенияВходаВПрограмму : Дата
ДатаПоследнейАктивности : Дата
ДатаАвтоматическогоЗапрещенияВхода : Дата
ДатаНачалаИспользованияПароля : Дата
ИспользованныеПароли : Хранилище значения
..Реквизиты..
ПоследнийИспользуемыйКлиент : Строка
}
@enduml
