@startuml ЦелевыеЗначенияВариантовАнализа
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЦелевыеЗначенияВариантовАнализа as "Целевые значения вариантов анализа" <<РегистрыСведений>>
{
..Измерения..
ВариантАнализа : Справочник.Вариант анализа целевого показателя
..Ресурсы..
ВидЦелевогоЗначения : Виды целевых значений вариантов анализа
ЦелевоеЗначение : Число 15, 2
ЦелевойДиапазонМинимум : Число 15, 2
ЦелевойДиапазонМаксимум : Число 15, 2
ВидОтклоненияОтЦелевогоЗначения : Виды отклонений от целевых значений показателей
ГраничноеНегативноеОтклонение : Число 15, 2
ГраничноеПозитивноеОтклонение : Число 15, 2
ПриведенноеГраничноеНегативноеОтклонение : Число 15, 2
ПриведенноеГраничноеПозитивноеОтклонение : Число 15, 2
}
@enduml
