@startuml КэшИменДокументовДляОбработкиПоПравилу
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КэшИменДокументовДляОбработкиПоПравилу as "Кэш имен документов для обработки по правилу" <<РегистрыСведений>>
{
..Измерения..
Правило : Справочник.Правила получения фактических данных по статьям бюджетов
ИмяВидаДокумента : Строка
}
@enduml
