@startuml КоэффициентыРаспределенияСреднегоЗаработка
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КоэффициентыРаспределенияСреднегоЗаработка as "Коэффициенты распределения среднего заработка" <<РегистрыСведений>>
{
..Измерения..
ДокументОснование : Документ.Командировка\rДокумент.Отпуск по уходу за ребенком
СтатьяФинансирования : Справочник.Статья финансирования
..Ресурсы..
Коэффициент : Число 15, 2
}
@enduml
