@startuml РеквизитыПлатежныхДокументовПеречисленияЗарплаты
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РеквизитыПлатежныхДокументовПеречисленияЗарплаты as "Реквизиты платежных документов перечисления зарплаты" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ПлатежныйДокумент : Документ.Списание безналичных ДС\rДокумент.Заявка на расходование ДС
..Ресурсы..
ЗарплатныйПроект : Справочник.Зарплатный проект
Номер : Строка
Дата : Дата
СпособВыплаты : Справочник.Способ выплаты зарплаты
МесяцВыплаты : Дата
СуммаПоДокументу : Число 15, 2
..Реквизиты..
СпособВыплатыПредставление : Строка
МесяцВыплатыПредставление : Строка
}
@enduml
