@startuml ДанныеПоследнихОповещений
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДанныеПоследнихОповещений as "Данные последних оповещений" <<РегистрыСведений>>
{
..Измерения..
ВидОповещения : Справочник.Вид оповещений клиентам
ИсточникОповещения : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
Подписчик : Справочник.Партнер
..Ресурсы..
ДанныеПоследнегоОповещения : Хранилище значения
}
@enduml
