@startuml УдалитьФайлыСведенийРОКИ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьФайлыСведенийРОКИ as "(не используется) Кэш файлов с ресурса общей ключевой информации "Такском"" <<РегистрыСведений>>
{
..Измерения..
УчетнаяЗапись : Справочник.(не используется) Учетные записи документооборота
ИмяРесурса : Строка
..Ресурсы..
Данные : Хранилище значения
..Реквизиты..
Расшифрован : Булево
ДатаФайла : Дата
Размер : Число 10, 0
}
@enduml
