@startuml ИспользованиеДополнительныхОтчетовИОбработокСервисаВАвтономномРабочемМесте
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИспользованиеДополнительныхОтчетовИОбработокСервисаВАвтономномРабочемМесте as "Использование дополнительных отчетов и обработок сервиса в автономном рабочем месте" <<РегистрыСведений>>
{
..Измерения..
ДополнительныйОтчетИлиОбработка : Справочник.Дополнительный отчет или обработка
..Ресурсы..
Поставляемый : Булево
}
@enduml
