@startuml СведенияКонтрактаДоговораСотрудникаИспр
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СведенияКонтрактаДоговораСотрудникаИспр as "Сведения контракта, договора сотрудника (испр.)" <<РегистрыСведений>>
{
..Измерения..
РегистраторИзмерение : Документ.Кадровый перевод\rДокумент.Восстановление в должности\rДокумент.Кадровый перевод списком\r...
ПериодИзмерение : Дата
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ГоловнаяОрганизация : Справочник.Организация
..Ресурсы..
ВидДоговора : Виды договоров с сотрудниками
ПредставительНанимателя : Справочник.Физическое лицо
ДолжностьПредставителяНанимателя : Справочник.Должность
ОснованиеПредставителяНанимателя : Строка
ВидАктаГосоргана : Строка
Должность : Справочник.Должность
ДатаОкончания : Дата
СрочныйДоговор : Булево
СезонныйДоговор : Булево
СрокЗаключенияДоговора : Строка
ОснованиеСрочногоДоговора : Справочник.Основание заключения срочного трудового договора
ОборудованиеРабочегоМеста : Строка
ИныеУсловияДоговора : Строка
УдалитьДатаДоговораКонтракта : Дата
УдалитьДатаНачала : Дата
УдалитьНомерДоговораКонтракта : Строка
УдалитьПоступлениеНаСлужбуВпервые : Булево
УдалитьСпособПоступленияНаСлужбу : Строка
Организация : Справочник.Организация
}
@enduml
