@startuml КадроваяИсторияСотрудниковИспр
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КадроваяИсторияСотрудниковИспр as "Кадровая история сотрудников испр" <<РегистрыСведений>>
{
..Измерения..
РегистраторИзмерение : Документ.Кадровый перевод\rДокумент.Увольнение\rДокумент.Перемещение в другое подразделение\r...
ПериодИзмерение : Дата
Сотрудник : Справочник.Сотрудник
ГоловнаяОрганизация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ВидСобытия : Виды кадровых событий
ДолжностьПоШтатномуРасписанию : Справочник.Позиция
КоличествоСтавок : Число 22, 20
Должность : Справочник.Должность
ВидЗанятости : Виды занятости
ВидДоговора : Виды договоров с сотрудниками
ДействуетДо : Дата
ГоловнойСотрудник : Справочник.Сотрудник
ЭтоГоловнойСотрудник : Булево
УдалитьОрганизацияПоОкончании : Справочник.Организация
УдалитьПодразделениеПоОкончании : Справочник.Подразделение
УдалитьДолжностьПоШтатномуРасписаниюПоОкончании : Справочник.Позиция
УдалитьДолжностьПоОкончании : Справочник.Должность
УдалитьКоличествоСтавокПоОкончании : Число 22, 20
УдалитьВидСобытияПоОкончании : Виды кадровых событий
УдалитьВидЗанятостиПоОкончании : Виды занятости
УдалитьВидДоговораПоОкончании : Виды договоров с сотрудниками
..Реквизиты..
ПервичныйДокумент : Документ.Кадровый перевод\rДокумент.Увольнение\rДокумент.Восстановление в должности\r...
}
@enduml
