@startuml ГрафикРаботыСотрудниковИнтервальный
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ГрафикРаботыСотрудниковИнтервальный as "График работы сотрудников интервальный" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ДатаОкончания : Дата
ДатаНачала : Дата
ГоловнаяОрганизация : Справочник.Организация
ПериодЗаписи : Дата
Год : Дата
..Ресурсы..
ПериодПредыдущейЗаписи : Дата
ГрафикРаботы : Справочник.График работы
ДействуетДо : Дата
..Реквизиты..
РегистраторЗаписи : Документ.Кадровый перевод\rДокумент.Изменение графика работы списком\rДокумент.Начальная штатная расстановка\r...
РегистраторСобытия : Документ.Кадровый перевод\rДокумент.Изменение графика работы списком\rДокумент.Начальная штатная расстановка\r...
ПустойИнтервал : Булево
}
@enduml
