@startuml ЖурналФискальныхОпераций
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЖурналФискальныхОпераций as "Журнал фискальных операций" <<РегистрыСведений>>
{
..Измерения..
ДокументОснование : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
ИдентификаторЗаписи : Строка
..Ресурсы..
Дата : Дата
Организация : Справочник.Организация
ТорговыйОбъект : Справочник.Кассы ККМ\rСправочник.Касса\rСправочник.Склад (складская территория)
Устройство : Справочник.Экземпляр подключаемого оборудования
ТипОперации : Типы операции кассового узла
ФискальнаяОперацияТипРасчета : Типы расчета денежными средствами
ФискальнаяОперацияВариантОтправкиЭлектронногоЧека : Варианты отправки электронного чека покупателю
ФискальнаяОперацияКонтактныеДанныеЭлектронногоЧека : Строка
ФискальнаяОперацияНомерЧекаККМ : Число 8, 0
ФискальнаяОперацияНомерСменыККМ : Число 8, 0
ФискальнаяОперацияСумма : Число 15, 2
ФискальнаяОперацияСуммаОплатыНаличные : Число 15, 2
ФискальнаяОперацияСуммаОплатыПлатежнаяКарта : Число 15, 2
ФискальнаяОперацияСуммаПредоплаты : Число 15, 2
ФискальнаяОперацияСуммаКредит : Число 15, 2
Данные : Хранилище значения
}
@enduml
