@startuml ДоступностьТоваровДляВнешнихПользователей
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДоступностьТоваровДляВнешнихПользователей as "Доступность товаров для внешних пользователей" <<РегистрыСведений>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Склад : Справочник.Склад (складская территория)
..Ресурсы..
Доступно : Число 15, 3
}
@enduml
