@startuml ЗаданияКЗакрытиюМесяца
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗаданияКЗакрытиюМесяца as "Задания к закрытию месяца" <<РегистрыСведений>>
{
..Измерения..
Месяц : Дата
Операция : Операции закрытия месяца
Организация : Справочник.Организация
НомерЗадания : Число 15, 0
Документ : Документ.Сторнирование начислений\rДокумент.Внутреннее потребление товаров\rДокумент.Назначение планового начисления\r...
}
@enduml
