@startuml КодировкиФайлов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КодировкиФайлов as "Кодировки файлов" <<РегистрыСведений>>
{
..Измерения..
Файл : Справочник.Присоединенный файл (Отчет комиссионера)\rСправочник.Присоединенные файлы (Поступление безналичных денежных средств)\rСправочник.Присоединенный файл (Сообщение обмена с банками)\r...
..Ресурсы..
Кодировка : Строка
}
@enduml
