@startuml ОсновныеСредстваМеждународныйУчет
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОсновныеСредстваМеждународныйУчет as "Основные средства (Международный учет)" <<РегистрыСведений>>
{
..Измерения..
ОсновноеСредство : Справочник.Объект эксплуатации
..Ресурсы..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Состояние : Состояния ОС
ИнвентарныйНомер : Строка
СчетУчета : Международный план счетов
ВидАктива : Виды внеоборотных активов
ЛиквидационнаяСтоимость : Число 15, 2
ЛиквидационнаяСтоимостьПредставления : Число 15, 2
ПорядокУчета : Порядок учета стоимости внеоборотных активов
МетодНачисленияАмортизации : Способы начисления амортизации основных средств
СчетАмортизации : Международный план счетов
СрокИспользования : Число 10, 0
ПоказательНаработки : Справочник.Показатель наработки
ОбъемНаработки : Число 15, 3
КоэффициентУскорения : Число 4, 3
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
}
@enduml
