@startuml ПорядокУчетаОС
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПорядокУчетаОС as "Порядок учета ОС" <<РегистрыСведений>>
{
..Измерения..
ОсновноеСредство : Справочник.Объект эксплуатации
..Ресурсы..
ГруппаФинансовогоУчета : Справочник.Группа финансового учета внеоборотных активов
НаправлениеДеятельности : Справочник.Направление деятельности
ПоказательНаработки : Справочник.Показатель наработки
ОбъемНаработки : Число 15, 3
..Реквизиты..
ОтражатьВРеглУчете : Булево
ОтражатьВУпрУчете : Булево
}
@enduml
