@startuml ПроблемыСостоянияСистемы
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПроблемыСостоянияСистемы as "Проблемы состояния учета" <<РегистрыСведений>>
{
..Измерения..
Проверка : Справочник.Проверка
Организация : Справочник.Организация
ПроверяемыйПериод : Дата
Проблема : Уникальный идентификатор
..Ресурсы..
Представление : Строка
Важность : Варианты важности проблемы состояния системы
ДополнительнаяИнформация : Хранилище значения
Отложена : Булево
}
@enduml
