@startuml ПартнерыСегмента
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПартнерыСегмента as "Партнеры сегмента" <<РегистрыСведений>>
{
..Измерения..
Сегмент : Справочник.Сегмент клиентов
Партнер : Справочник.Партнер
}
@enduml
