@startuml СчетчикиВыгрузок
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СчетчикиВыгрузок as "Счетчики выгрузок" <<РегистрыСведений>>
{
..Измерения..
Тип : Типы счетчиков выгрузки
Организация : Справочник.Организация\rСтрока
ИФНС : Строка
НомерКвартала : Число 1, 0
..Ресурсы..
Значение : Число 8, 0
}
@enduml
