@startuml УсловияУдержанияПоИсполнительномуДокументу
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УсловияУдержанияПоИсполнительномуДокументу as "Условия удержания по исполнительному документу" <<РегистрыСведений>>
{
..Измерения..
ИсполнительныйДокумент : Документ.Исполнительный лист
..Ресурсы..
СпособРасчета : Способы расчета удержания по исполнительному документу
ВидБазы : Виды базы удержания по исполнительному документу
Процент : Число 5, 2
Сумма : Число 15, 2
Числитель : Число 2, 0
Знаменатель : Число 2, 0
ПрожиточныйМинимум : Справочник.Прожиточный минимум
Предел : Число 15, 2
УчитыватьБольничныеЛисты : Булево
ПлатежныйАгент : Справочник.Контрагент
ТарифПлатежногоАгента : Справочник.Тариф платежного агента
..Реквизиты..
ФизическоеЛицо : Справочник.Физическое лицо
Организация : Справочник.Организация
Получатель : Справочник.Контрагент
}
@enduml
