@startuml СоответствиеВидовНоменклатуры1СБизнесСеть
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СоответствиеВидовНоменклатуры1СБизнесСеть as "Соответствие видов номенклатуры 1С:Бизнес-сеть" <<РегистрыСведений>>
{
..Измерения..
ВидНоменклатуры : Справочник.Вид номенклатуры
ИдентификаторКатегории : Строка
..Реквизиты..
ПредставлениеКатегории : Строка
}
@enduml
