@startuml ОчередьСообщенийВ1СДокументооборот
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОчередьСообщенийВ1СДокументооборот as "Очередь сообщений в 1С:Документооборот" <<РегистрыСведений>>
{
..Измерения..
МоментВремени : Число 20, 0
Идентификатор : Уникальный идентификатор
..Ресурсы..
Данные : Хранилище значения
КоличествоПопытокОтправки : Число 10, 0
..Реквизиты..
ТекстСообщенияОбОшибке : Строка
ДатаСоздания : Дата
}
@enduml
