@startuml СвойстваКонтрагентовСПАРКРиски
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СвойстваКонтрагентовСПАРКРиски as "Свойства контрагентов 1СПАРК Риски" <<РегистрыСведений>>
{
..Измерения..
Контрагент : Справочник.Контрагент
..Реквизиты..
ИНН : Строка
ИННКорректный : Булево
СвояОрганизация : Булево
}
@enduml
