@startuml НовыеДокументыВСервисеЭДО
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НовыеДокументыВСервисеЭДО as "Новые документы в сервисе ЭДО" <<РегистрыСведений>>
{
..Измерения..
ПрофильЭДО : Справочник.Профиль настроек ЭДО
..Ресурсы..
ЕстьНовыеЭД : Булево
}
@enduml
