@startuml ДанныеСостоянийСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДанныеСостоянийСотрудников as "Данные состояний сотрудников" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ДокументОснование : Документ.Сторнирование начислений\rДокумент.Изменение условий оплаты отпуска по уходу за ребенком\rДокумент.Простой сотрудников\r...
Сторно : Булево
Состояние : Состояния сотрудника
Начало : Дата
Окончание : Дата
..Ресурсы..
ВидВремени : Справочник.Вид рабочего времени
ОкончаниеПредположительно : Дата
}
@enduml
