@startuml ПлановыеНачисленияИспр
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПлановыеНачисленияИспр as "Плановые начисления испр" <<РегистрыСведений>>
{
..Измерения..
РегистраторИзмерение : Документ.Сторнирование начислений\rДокумент.Изменение условий оплаты отпуска по уходу за ребенком\rДокумент.Кадровый перевод\r...
ПериодИзмерение : Дата
Сотрудник : Справочник.Сотрудник
Начисление : Начисление
ФизическоеЛицо : Справочник.Физическое лицо
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ГоловнаяОрганизация : Справочник.Организация
..Ресурсы..
Используется : Булево
Размер : Число 15, 2
ДействуетДо : Дата
УдалитьИспользуетсяПоОкончании : Булево
УдалитьРазмерПоОкончании : Число 15, 2
}
@enduml
