@startuml ЗапросыРазрешенийНаИспользованиеВнешнихРесурсовВМоделиСервиса
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗапросыРазрешенийНаИспользованиеВнешнихРесурсовВМоделиСервиса as "Запросы разрешений на использование внешних ресурсов в модели сервиса" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторЗапроса : Уникальный идентификатор
..Ресурсы..
ТипПрограммногоМодуля : Справочник.Идентификатор объекта метаданных
ИдентификаторПрограммногоМодуля : Уникальный идентификатор
ТипВладельца : Справочник.Идентификатор объекта метаданных
ИдентификаторВладельца : Уникальный идентификатор
БезопасныйРежим : Булево\rСтрока
..Реквизиты..
РежимЗамещения : Булево
ДобавляемыеРазрешения : Строка
УдаляемыеРазрешения : Строка
}
@enduml
