@startuml ЭлектронныеПодписи
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЭлектронныеПодписи as "Электронные подписи" <<РегистрыСведений>>
{
..Измерения..
ПодписанныйОбъект : Справочник.Присоединенный файл (Отчет комиссионера)\rСправочник.Присоединенные файлы (Поступление безналичных денежных средств)\rСправочник.Присоединенный файл (Сообщение обмена с банками)\r...
ПорядковыйНомер : Число 10, 0
..Ресурсы..
ДатаПроверкиПодписи : Дата
ИмяФайлаПодписи : Строка
Комментарий : Строка
КомуВыданСертификат : Строка
Отпечаток : Строка
Подпись : Хранилище значения
ПодписьВерна : Булево
Сертификат : Хранилище значения
ДатаПодписи : Дата
УстановившийПодпись : Справочник.Пользователь
}
@enduml
