@startuml СчетаБухгалтерскогоУчетаОС
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СчетаБухгалтерскогоУчетаОС as "Счета бухгалтерского учета ОС (версия 2.2)" <<РегистрыСведений>>
{
..Измерения..
ОсновноеСредство : Справочник.Объект эксплуатации
Организация : Справочник.Организация
..Ресурсы..
СчетУчета : Счет бухгалтерского учета
СчетНачисленияАмортизации : Счет бухгалтерского учета
ГруппаФинансовогоУчета : Справочник.Группа финансового учета внеоборотных активов
}
@enduml
