@startuml ПрименяемыеТарифыСтраховыхВзносов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПрименяемыеТарифыСтраховыхВзносов as "Применяемые тарифы страховых взносов" <<РегистрыСведений>>
{
..Измерения..
ГоловнаяОрганизация : Справочник.Организация
..Ресурсы..
ВидТарифа : Справочник.Вид тарифа страховых взносов
УдалитьВидТарифа : Справочник.(не используется) Виды тарифов страховых взносов
ДатаРегистрацииИзменений : Дата
}
@enduml
