@startuml РасписаниеРаботыРабочихЦентров
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РасписаниеРаботыРабочихЦентров as "Расписание работы рабочих центров" <<РегистрыСведений>>
{
..Измерения..
МаршрутныйЛист : Документ.Маршрутный лист производства
ДатаИнтервала : Дата
..Ресурсы..
ВариантНаладки : Справочник.Вариант наладки
ВремяПереналадки : Число 10, 0
ВремяПереналадкиВРабочееВремя : Число 10, 0
ВремяРаботы : Число 10, 0
ВремяРаботыВРабочееВремя : Число 10, 0
ВремяРаботыИзмененоПользователем : Булево
Загрузка : Число 15, 3
Количество : Число 15, 0
Начало : Дата
НачалоПриРучномВводеРасписания : Дата
Окончание : Дата
Порядок : Число 10, 0
ПроблемыПриФормированииРасписания : Строка
РабочийЦентр : Справочник.Рабочий центр
РасписаниеВведеноВручную : Булево
}
@enduml
