@startuml НастройкиОбменаФТС
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиОбменаФТС as "Настройки обмена с ФТС" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
ИспользоватьОбмен : Булево
СертификатАбонентаОтпечаток : Строка
СертификатФТСОтпечаток : Строка
ИспользоватьАвтонастройку : Булево
Логин : Строка
Пароль : Строка
}
@enduml
