@startuml НастройкиВерсионированияОбъектов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиВерсионированияОбъектов as "Настройки версионирования объектов" <<РегистрыСведений>>
{
..Измерения..
ТипОбъекта : Справочник.Идентификатор объекта метаданных
..Ресурсы..
Вариант : Варианты версионирования объектов
Использовать : Булево
СрокХраненияВерсий : Сроки хранения версий
}
@enduml
