@startuml ЗначенияНемонетарныхПоказателей
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗначенияНемонетарныхПоказателей as "Значения немонетарных показателей" <<РегистрыСведений>>
{
..Измерения..
Показатель : Справочник.Немонетарный показатель
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
..Ресурсы..
Значение : Число 15, 3
..Реквизиты..
Автор : Справочник.Пользователь
ПричинаИзменения : Строка
}
@enduml
