@startuml НормативнаяДлительностьЭтаповПроизводства
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НормативнаяДлительностьЭтаповПроизводства as "Нормативная длительность этапов производства" <<РегистрыСведений>>
{
..Измерения..
Этап : Справочник.Этап ресурсной спецификации
Спецификация : Справочник.Ресурсная спецификация
..Ресурсы..
ДнейДоОкончания : Число 10, 0
..Реквизиты..
ДлительностьВДнях : Число 10, 0
ДлительностьВЧасах : Число 10, 3
}
@enduml
