@startuml РабочиеКаталогиФайлов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РабочиеКаталогиФайлов as "Рабочие каталоги файлов" <<РегистрыСведений>>
{
..Измерения..
Папка : Справочник.Папка
Пользователь : Справочник.Пользователь
..Ресурсы..
Путь : Строка
}
@enduml
