@startuml НастройкиОбменаЕГАИС
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиОбменаЕГАИС as "Настройки обмена с ЕГАИС" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторФСРАР : Строка
РабочееМесто : Справочник.Рабочее место
УдалитьИзмерениеОрганизация : Справочник.Организация\rСправочник.Контрагент
УдалитьИзмерениеСклад : Справочник.Партнер\rСправочник.Склад (складская территория)
..Ресурсы..
АдресУТМ : Строка
ПортУТМ : Число 6, 0
Таймаут : Число 3, 0
ОбменНаСервере : Булево
ЗагружатьВходящиеДокументы : Булево
ОбменНаКлиентеРасписание : Хранилище значения
ОбменНаКлиентеПоРасписанию : Булево
УдалитьРесурсОрганизация : Справочник.Организация\rСправочник.Контрагент
УдалитьРесурсСклад : Справочник.Партнер\rСправочник.Склад (складская территория)
УдалитьОрганизацияЕГАИС : Справочник.Организация ЕГАИС
}
@enduml
