@startuml СоответствиеЗначенийРеквизитов1СБизнесСеть
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СоответствиеЗначенийРеквизитов1СБизнесСеть as "Соответствие значений реквизитов 1С:Бизнес-сеть" <<РегистрыСведений>>
{
..Измерения..
ВидНоменклатуры : Справочник.Вид номенклатуры
РеквизитОбъекта : Дополнительный реквизит / сведение\rСтрока
Значение : Справочник.Дополнительное значение (иерархия)\rСправочник.Марка (бренд)\rСправочник.Дополнительное значение\r...
..Ресурсы..
ИдентификаторЗначенияРеквизитаКатегории : Строка
Автоподстановка : Булево
..Реквизиты..
ПредставлениеЗначенияРеквизитаКатегории : Строка
}
@enduml
