@startuml МакетыКомпоновкиДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.МакетыКомпоновкиДанных as "Макеты компоновки данных" <<РегистрыСведений>>
{
..Измерения..
Отчет : Справочник.Идентификатор объекта метаданных
КлючВарианта : Строка
..Ресурсы..
МакетКомпоновкиДанных : Хранилище значения
ВерсияКонфигурации : Строка
}
@enduml
