@startuml СостоянияПредметовВзаимодействий
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияПредметовВзаимодействий as "Состояния предметов взаимодействий" <<РегистрыСведений>>
{
..Измерения..
Предмет : Справочник.Маркетинговое мероприятие\rДокумент.Исходящее электронное письмо\rДокумент.Запланированное взаимодействие\r...
..Ресурсы..
КоличествоНеРассмотрено : Число 10, 0
ДатаПоследнегоВзаимодействия : Дата
Активен : Булево
}
@enduml
