@startuml МестоПозицииШтатногоРасписанияВСтруктуреПредприятия
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.МестоПозицииШтатногоРасписанияВСтруктуреПредприятия as "Место позиции штатного расписания в структуре предприятия" <<РегистрыСведений>>
{
..Измерения..
Позиция : Справочник.Позиция
..Ресурсы..
Подразделение : Справочник.Подразделение
}
@enduml
