@startuml ПКУСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПКУСотрудников as "ПКУ сотрудников" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
..Ресурсы..
ПКУ : Справочник.Квалификационный разряд (категория)
ДействуетДо : Дата
ПКУПоОкончании : Справочник.Квалификационный разряд (категория)
}
@enduml
