@startuml СостоянияЗаказовНаПроизводство
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияЗаказовНаПроизводство as "Состояния заказов на производство в очереди заказов" <<РегистрыСведений>>
{
..Измерения..
Заказ : Документ.Заказ на производство
..Ресурсы..
СостояниеЭтапов : Состояния заказов на производство в очереди
СостояниеОбеспечения : Состояния заказов на производство в очереди
СостояниеВыпуска : Состояния заказов на производство в очереди
}
@enduml
