@startuml НоменклатураПродаваемаяСовместно
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НоменклатураПродаваемаяСовместно as "Номенклатура, продаваемая совместно" <<РегистрыСведений>>
{
..Измерения..
НоменклатураПредпосылка : Справочник.Номенклатура
ХарактеристикаПредпосылка : Справочник.Характеристика номенклатуры
НоменклатураСледствие : Справочник.Номенклатура
ХарактеристикаСледствие : Справочник.Характеристика номенклатуры
ВариантАнализа : Варианты анализа номенклатуры продаваемой совместно
ДобавленоАвтоматически : Булево
..Ресурсы..
ПроцентСлучаев : Число 5, 2
КоличествоСлучаев : Число 15, 2
}
@enduml
