@startuml ОбластиДействияСертификатовНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОбластиДействияСертификатовНоменклатуры as "Области действия сертификатов номенклатуры" <<РегистрыСведений>>
{
..Измерения..
ВидНоменклатуры : Справочник.Вид номенклатуры
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Серия : Справочник.Серия номенклатуры
СертификатНоменклатуры : Справочник.Сертификат номенклатуры
}
@enduml
