@startuml ПредельнаяВеличинаБазыСтраховыхВзносов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПредельнаяВеличинаБазыСтраховыхВзносов as "Предельная величина базы страховых взносов" <<РегистрыСведений>>
{
..Ресурсы..
РазмерФСС : Число 15, 2
РазмерПФР : Число 15, 2
РазмерФОМС : Число 15, 2
}
@enduml
