@startuml ПервоначальныеСведенияНМАБухгалтерскийУчет
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПервоначальныеСведенияНМАБухгалтерскийУчет as "Первоначальные сведения о НМА и НИОКР (бухгалтерский учет)" <<РегистрыСведений>>
{
..Измерения..
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
..Ресурсы..
Организация : Справочник.Организация
ПервоначальнаяСтоимость : Число 15, 2
СпособПоступления : Способы поступления активов
НачислятьАмортизацию : Булево
СпособНачисленияАмортизации : Способы начисления амортизации нематериальных активов
СрокПолезногоИспользования : Число 4, 0
ОбъемПродукцииРаботДляВычисленияАмортизации : Число 10, 0
Коэффициент : Число 3, 2
РезервПереоценкиСтоимости : Число 15, 2
РезервПереоценкиАмортизации : Число 15, 2
}
@enduml
