@startuml БуферОперацийСтатистики
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.БуферОперацийСтатистики as "Буфер операций статистики" <<РегистрыСведений>>
{
..Измерения..
ДатаЗаписи : Число 15, 0
ИдентификаторУдаления : Число 11, 0
ИдентификаторЗаписи : Уникальный идентификатор
..Ресурсы..
ОперацияСтатистики : Уникальный идентификатор
КомментарийСтатистики : Уникальный идентификатор
ОбластьСтатистики : Уникальный идентификатор
Значение : Число 15, 3
}
@enduml
