@startuml ДатыОбновленияСтандартныхСписковНовостей
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДатыОбновленияСтандартныхСписковНовостей as "Даты обновления стандартных списков новостей" <<РегистрыСведений>>
{
..Измерения..
Список : Строка\rКатегория новостей
..Ресурсы..
ТекущаяВерсияНаКлиенте : Дата
ТекущаяВерсияНаСервере : Дата
}
@enduml
