@startuml МаксимальныйРазмерЕжемесячнойСтраховойВыплаты
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.МаксимальныйРазмерЕжемесячнойСтраховойВыплаты as "Максимальный размер ежемесячной страховой выплаты" <<РегистрыСведений>>
{
..Ресурсы..
Размер : Число 15, 2
}
@enduml
