@startuml ЗаданияКФормированиюЗаписейКнигиПокупокПродаж
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗаданияКФормированиюЗаписейКнигиПокупокПродаж as "Задания к формированию записей книги покупок/продаж" <<РегистрыСведений>>
{
..Измерения..
Месяц : Дата
НомерЗадания : Число 15, 0
Организация : Справочник.Организация
СчетФактура : Документ.Сторнирование начислений\rДокумент.Внутреннее потребление товаров\rДокумент.Назначение планового начисления\r...
}
@enduml
