@startuml ПредопределенныеВариантыОтчетовВерсийРасширений
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПредопределенныеВариантыОтчетовВерсийРасширений as "Предопределенные варианты отчетов версий расширений" <<РегистрыСведений>>
{
..Измерения..
Отчет : Справочник.Идентификатор объекта метаданных расширения
Вариант : Справочник.Предопределенный вариант отчета
ВерсияРасширений : Справочник.Версия расширений
КлючВарианта : Строка
}
@enduml
