@startuml УдалитьМестоСотрудникаВСтруктуреПредприятия
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьМестоСотрудникаВСтруктуреПредприятия as "(не используется) Место сотрудника в структуре предприятия" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
..Ресурсы..
Подразделение : Справочник.Подразделение
}
@enduml
