@startuml ИсточникиДанныхВариантовАнализаЦелевыхПоказателей
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИсточникиДанныхВариантовАнализаЦелевыхПоказателей as "Источники данных вариантов анализа целевых показателей" <<РегистрыСведений>>
{
..Измерения..
ВариантАнализа : Справочник.Вариант анализа целевого показателя
ВариантОтображения : Варианты отображения вариантов анализа
..Ресурсы..
ДатаРасчета : Дата
ИсточникДанных : Хранилище значения
}
@enduml
