@startuml СведенияОВремениДляРасчетаСреднегоФCC
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СведенияОВремениДляРасчетаСреднегоФCC as "Сведения о времени для расчета среднего (ФCC)" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
ГоловнаяОрганизация : Справочник.Организация
Месяц : Дата
Сотрудник : Справочник.Сотрудник
..Ресурсы..
ОтработаноДнейКалендарных : Число 7, 2
ДнейБолезниУходаЗаДетьми : Число 5, 2
..Реквизиты..
ДанныеИзУчетаСреднегоОбщий : Булево
ДанныеРассчитаныАвтоматически : Булево
}
@enduml
