@startuml ДокументыПоОС
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДокументыПоОС as "Документы по ОС" <<РегистрыСведений>>
{
..Измерения..
ТипСсылки : Справочник.Идентификатор объекта метаданных
ХозяйственнаяОперация : Хозяйственные операции
НомерЗаписи : Число 10, 0
Дата : Дата
ОсновноеСредство : Справочник.Объект эксплуатации
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Ссылка : Документ.Внутреннее потребление товаров\rДокумент.Списание ОС\rДокумент.Передача ОС арендатору\r...
ДополнительнаяЗапись : Булево
..Ресурсы..
Проведен : Булево
ОтражатьВРеглУчете : Булево
ОтражатьВУпрУчете : Булево
}
@enduml
