@startuml СостоянияКонтактовВзаимодействий
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияКонтактовВзаимодействий as "Состояния контактов взаимодействий" <<РегистрыСведений>>
{
..Измерения..
Контакт : Справочник.Строковый контакт взаимодействий\rСправочник.Пользователь\rСправочник.Партнер\r...
..Ресурсы..
КоличествоНеРассмотрено : Число 10, 0
ДатаПоследнегоВзаимодействия : Дата
}
@enduml
