@startuml ОтменаКорректировокПланаПроизводства
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОтменаКорректировокПланаПроизводства as "Отмена корректировок плана производства" <<РегистрыСведений>>
{
..Измерения..
ПланПроизводства : Документ.План производства
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Спецификация : Справочник.Ресурсная спецификация
ДатаЗапуска : Дата
ДатаВыпуска : Дата
ДатаВыпускаПолуфабриката : Дата
ЭтоПолуфабрикат : Булево
..Ресурсы..
Количество : Число 15, 3
ДатаКорректировки : Дата
АвторКорректировки : Справочник.Пользователь
Комментарий : Строка
}
@enduml
