@startuml УсловияДоговораГПХ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УсловияДоговораГПХ as "Условия договора ГПХ" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
Договор : Документ.Договор авторского заказа\rДокумент.Договор (работы, услуги)
..Ресурсы..
КодДохода : Справочник.Вид дохода НДФЛ
КодВычета : Справочник.Вид вычетов НДФЛ
КодДоходаСтраховыеВзносы : Справочник.Вид дохода по страховым взносам
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОтношениеКЕНВД : Отношение к ЕНВД затрат на зарплату
Подразделение : Справочник.Подразделение
Сумма : Число 15, 2
РазмерЕжемесячногоАвансовогоПлатежа : Число 15, 2
СуммаВычета : Число 15, 2
СуммаЕНВД : Число 15, 2
ДатаНачала : Дата
ДатаОкончания : Дата
ЗаключенСоСтудентомРаботающимВСтудотряде : Булево
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
ПланируемаяДатаВыплаты : Дата
Территория : Справочник.Территория
}
@enduml
