@startuml ПорядокОтраженияНоменклатурыПереданной
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПорядокОтраженияНоменклатурыПереданной as "Порядок отражения номенклатуры переданной" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ГруппаФинансовогоУчета : Справочник.Группа финансового учета номенклатуры
..Ресурсы..
СчетУчетаПередачиНаКомиссию : Счет бухгалтерского учета
СчетУчетаВыручкиОтПродаж : Счет бухгалтерского учета
СчетУчетаСебестоимостиПродаж : Счет бухгалтерского учета
СчетУчетаНДСПриПродаже : Счет бухгалтерского учета
СтатьяДоходовОСНО : Статьи доходов
СчетУчетаПередачиВПереработку : Счет бухгалтерского учета
СчетУчетаЗатратыНаПриобретение : Счет бухгалтерского учета
}
@enduml
