@startuml ДатыЗагрузкиПоследнихНовостей
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДатыЗагрузкиПоследнихНовостей as "Даты загрузки последних новостей" <<РегистрыСведений>>
{
..Измерения..
ЛентаНовостей : Справочник.Лента новостей
..Ресурсы..
ДатаЗагрузкиПоследнихНовостей : Дата
КоличествоНеудачПриЗагрузкеНовостей : Число 5, 0
ДатаПоследнейПопыткиЗагрузкиНовостей : Дата
}
@enduml
