@startuml НормативыРаспределенияПлановПродажПоКатегориям
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НормативыРаспределенияПлановПродажПоКатегориям as "Нормативы распределения планов продаж по категориям" <<РегистрыСведений>>
{
..Измерения..
ТоварнаяКатегория : Справочник.Товарные категории
Реквизит : Дополнительный реквизит / сведение\rСтрока
..Ресурсы..
Норматив : Документ.Норматив распределения планов продаж по категориям
Действует : Булево
ПоХарактеристикам : Булево
}
@enduml
