@startuml АдресныеОбъекты
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.АдресныеОбъекты as "Адресные объекты" <<РегистрыСведений>>
{
..Измерения..
Уровень : Число 2, 0
КодСубъектаРФ : Число 2, 0
КодОкруга : Число 1, 0
КодРайона : Число 3, 0
КодГорода : Число 3, 0
КодВнутригородскогоРайона : Число 3, 0
КодНаселенногоПункта : Число 3, 0
КодУлицы : Число 4, 0
КодДополнительногоЭлемента : Число 4, 0
КодПодчиненногоЭлемента : Число 3, 0
Идентификатор : Уникальный идентификатор
..Ресурсы..
ПочтовыйИндекс : Число 6, 0
Наименование : Строка
Сокращение : Строка
Дополнительно : Уникальный идентификатор
КодКЛАДР : Число 17, 0
Актуален : Булево
}
@enduml
