@startuml СтатусыЗапросовРеестровСчетовФактур
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтатусыЗапросовРеестровСчетовФактур as "Статусы запросов реестров счетов-фактур" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Контрагент : Справочник.Контрагент
НалоговыйПериод : Дата
ИдентификаторЗапроса : Строка
..Ресурсы..
ДатаЗаписи : Дата
ДатаЗапроса : Дата
ЭлектроннаяПочта : Строка
ТипЗапроса : Типы запросов реестров счетов фактур
СтатусЗапроса : Статусы реестров счетов фактур
Сумма : Число 15, 2
СуммаНДС : Число 15, 2
Отметка : Булево
ИдентификаторПочтовогоСообщения : Строка
ДанныеРеестра : Хранилище значения
}
@enduml
