@startuml ПериодыАктуальностиОбъектовЭксплуатации
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПериодыАктуальностиОбъектовЭксплуатации as "Периоды актуальности объектов эксплуатации" <<РегистрыСведений>>
{
..Измерения..
ОбъектЭксплуатации : Справочник.Объект эксплуатации
}
@enduml
