@startuml ГраницыКонтролируемостиСделок
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ГраницыКонтролируемостиСделок as "Границы контролируемости сделок" <<РегистрыСведений>>
{
..Измерения..
ОсобенностьОтнесенияСделкиККонтролируемой : Особенности отнесения сделок к контролируемым
..Ресурсы..
ПредельнаяСумма : Число 15, 0
}
@enduml
