@startuml ЗаданияКОтражениюЭкземпляровБюджета
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗаданияКОтражениюЭкземпляровБюджета as "Задания к отражению экземпляров бюджета" <<РегистрыСведений>>
{
..Измерения..
НомерЗадания : Число 15, 0
Документ : Документ.Экземпляр бюджета
..Ресурсы..
ДокументПроведенОжидаетПроверки : Булево
}
@enduml
