@startuml СостоянияУспешныхОбменовДанными
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияУспешныхОбменовДанными as "Состояния успешных обменов данными" <<РегистрыСведений>>
{
..Измерения..
УзелИнформационнойБазы : Синхронизация данных через универсальный формат\rОбмен с подключаемым оборудованием Offline\rОбрабатываемый объект\r...
ДействиеПриОбмене : Действия при обмене
..Ресурсы..
ДатаОкончания : Дата
}
@enduml
