@startuml СчетаРеглУчетаТребующиеНастройки
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СчетаРеглУчетаТребующиеНастройки as "Счета регл учета требующие настройки" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
АналитикаУчета : Статья расходов\rСправочник.Категории эксплуатации\rСправочник.Банковский счет организации\r...
МестоУчета : Справочник.Подразделение\rСправочник.Партнер\rСправочник.Склад (складская территория)
ВидСчета : Виды счетов регламентированного учета
}
@enduml
