@startuml СведенияРеглОтчетАлкоПрил15Производство
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СведенияРеглОтчетАлкоПрил15Производство as "Сведения регл отчет алко прил15 производство" <<РегистрыСведений>>
{
..Измерения..
Документ : Документ.Регламентированный отчет
УдалитьИндексСтраницы : Число 10, 0
ИндексСтроки : Число 10, 0
ИДДокИндСтраницы : Строка
Организация : Справочник.Организация
..Ресурсы..
П000011000313 : Строка
П000011000314 : Строка
П000011000315 : Число 15, 5
..Реквизиты..
Активно : Булево
}
@enduml
