@startuml НазначениеДополнительныхОбработок
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НазначениеДополнительныхОбработок as "Назначение дополнительных обработок" <<РегистрыСведений>>
{
..Измерения..
ОбъектНазначения : Справочник.Идентификатор объекта метаданных
ТипФормы : Строка
УдалитьТипОбъекта : Строка
..Ресурсы..
ИспользоватьЗаполнениеОбъекта : Булево
ИспользоватьОтчеты : Булево
ИспользоватьСозданиеСвязанныхОбъектов : Булево
}
@enduml
