@startuml СпециальностиФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СпециальностиФизическихЛиц as "Специальности физических лиц" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
Специальность : Справочник.Специальность
..Ресурсы..
РазрядКатегория : Справочник.Квалификационный разряд (категория)
ДействуетПо : Дата
..Реквизиты..
Основание : Строка
Серия : Строка
Номер : Строка
КемВыдан : Строка
ДокументРегистратор : Строка
}
@enduml
