@startuml ФотографииФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ФотографииФизическихЛиц as "Фотографии физических лиц" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
Фотография : Хранилище значения
}
@enduml
