@startuml НастройкиПечатиОбъектов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиПечатиОбъектов as "Настройки печати объектов" <<РегистрыСведений>>
{
..Измерения..
ТипОбъекта : Строка
Организация : Справочник.Организация
Партнер : Справочник.Партнер
..Ресурсы..
Настройки : Хранилище значения
}
@enduml
