@startuml ПараметрыМежоперационныхПереходов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПараметрыМежоперационныхПереходов as "Параметры межоперационных переходов" <<РегистрыСведений>>
{
..Измерения..
Подразделение : Справочник.Подразделение
ВидРабочегоЦентраИсточник : Справочник.Вид рабочего центра
ВидРабочегоЦентраПриемник : Справочник.Вид рабочего центра
..Ресурсы..
ВремяПерехода : Число 10, 1
ВремяПереходаЕдИзм : Единицы измерения времени
}
@enduml
