@startuml ОтветыНаЗапросыИОН
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОтветыНаЗапросыИОН as "Ответы на запросы ИОН" <<РегистрыСведений>>
{
..Измерения..
Запрос : Документ.Запрос на информационное обслуживание налогоплательщика
ИмяФайла : Строка
..Ресурсы..
Данные : Хранилище значения
..Реквизиты..
Размер : Число 10, 0
ТипСодержимого : Типы содержимого файлов
}
@enduml
