@startuml ВерсииПодсистем
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ВерсииПодсистем as "Версии подсистем" <<РегистрыСведений>>
{
..Измерения..
ИмяПодсистемы : Строка
..Ресурсы..
Версия : Строка
..Реквизиты..
ПланОбновления : Хранилище значения
ЭтоОсновнаяКонфигурация : Булево
ВыполненаРегистрацияОтложенныхОбработчиков : Булево
}
@enduml
