@startuml СостоянияКонтрагентов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияКонтрагентов as "Состояния контрагентов" <<РегистрыСведений>>
{
..Измерения..
Контрагент : Справочник.Контрагент
..Ресурсы..
Состояние : Состояния существования контрагента
..Реквизиты..
ИНН : Строка
КПП : Строка
}
@enduml
