@startuml СтатусОбменовСЯндексКассой
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтатусОбменовСЯндексКассой as "Статус обменов с сервисом Яндекс.Касса" <<РегистрыСведений>>
{
..Измерения..
НастройкаЯндексКассы : Справочник.Настройка Яндекс.Кассы
..Ресурсы..
ДатаПоследнегоУспешногоОбмена : Дата
..Реквизиты..
Организация : Справочник.Организация
}
@enduml
