@startuml РучныеИзмененияГрафиковРаботы
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РучныеИзмененияГрафиковРаботы as "Ручные изменения графиков работы" <<РегистрыСведений>>
{
..Измерения..
ГрафикРаботы : Справочник.График работы
Год : Число 4, 0
ДатаГрафика : Дата
..Ресурсы..
РучноеИзменение : Булево
}
@enduml
