@startuml ТребуетсяСправочноеУказаниеСерий
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ТребуетсяСправочноеУказаниеСерий as "Требуется справочное указание серий" <<РегистрыСведений>>
{
..Измерения..
Спецификация : Справочник.Ресурсная спецификация
Номенклатура : Справочник.Номенклатура
ВидСтрокиСпецификации : Виды строк дерева спецификаций
}
@enduml
