@startuml ЗаданияКРасчетуДлительностиПроизводства
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗаданияКРасчетуДлительностиПроизводства as "Задания к расчету нормативной длительности производства" <<РегистрыСведений>>
{
..Измерения..
ОбъектРасчета : Справочник.Ресурсная спецификация\rСправочник.Подразделение\rСправочник.График работы
НомерЗадания : Число 15, 0
..Реквизиты..
ДатаДобавления : Дата
РасчетДнейДоОкончания : Булево
}
@enduml
