@startuml СтатусыОформленияДокументовЕГАИС
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтатусыОформленияДокументовЕГАИС as "Статусы оформления документов ЕГАИС" <<РегистрыСведений>>
{
..Измерения..
Документ : Документ.Товарно-транспортная накладная ЕГАИС (входящая)\rДокумент.Чек ККМ на возврат\rДокумент.Чек ЕГАИС на возврат\r...
Основание : Документ.Внутреннее потребление товаров\rДокумент.Товарно-транспортная накладная ЕГАИС (входящая)\rДокумент.Возврат товаров от клиента\r...
..Ресурсы..
СтатусОформления : Статусы оформления документов ЕГАИС
..Реквизиты..
Контрагент : Справочник.Организация\rСправочник.Контрагент
ТорговыйОбъект : Справочник.Партнер\rСправочник.Склад (складская территория)
Ответственный : Справочник.Пользователь\rСправочник.Партнер\rСправочник.Контактное лицо
Дата : Дата
Номер : Строка
}
@enduml
