@startuml ПодчиненностьПодразделенийОрганизаций
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПодчиненностьПодразделенийОрганизаций as "Подчиненность подразделений организаций" <<РегистрыСведений>>
{
..Измерения..
Подразделение : Справочник.Подразделение
ВышестоящееПодразделение : Справочник.Подразделение
Организация : Справочник.Организация
}
@enduml
