@startuml ДокументыПоВыпущеннойПродукции
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДокументыПоВыпущеннойПродукции as "Документы по выпущенной продукции для распределения" <<РегистрыСведений>>
{
..Измерения..
Дата : Дата
ДокументРегистратор : Документ.Внутреннее потребление товаров\rДокумент.Передача давальцу\rДокумент.Возврат товаров от клиента\r...
Организация : Справочник.Организация
ДокументВыпуска : Документ.Пересортица товаров\rДокумент.Выпуск продукции и выполнение работ\rДокумент.Сборка (разборка) товаров\r...
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
НалогообложениеНДС : Типы налогообложения НДС
Подразделение : Справочник.Подразделение
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ДокументРеализации : Документ.Реализация товаров и услуг\rДокумент.Отчет о розничных продажах
..Ресурсы..
КоличествоПродукции : Число 15, 3
}
@enduml
