@startuml Пользователи1СБизнесСеть
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.Пользователи1СБизнесСеть as "Пользователи 1С:Бизнес-сеть" <<РегистрыСведений>>
{
..Измерения..
СсылкаНаОбъект : Справочник.Организация\rСправочник.Пользователь
..Ресурсы..
Идентификатор : Строка
}
@enduml
