@startuml ПервоначальныеСведенияНМА
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПервоначальныеСведенияНМА as "Первоначальные сведения НМА" <<РегистрыСведений>>
{
..Измерения..
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
Организация : Справочник.Организация
..Ресурсы..
СпособПоступления : Способы поступления активов
ПервоначальнаяСтоимостьУУ : Число 15, 2
ПервоначальнаяСтоимостьБУ : Число 15, 2
ПервоначальнаяСтоимостьНУ : Число 15, 2
ПервоначальнаяСтоимостьПР : Число 15, 2
ПервоначальнаяСтоимостьВР : Число 15, 2
МетодНачисленияАмортизацииБУ : Способы начисления амортизации нематериальных активов
МетодНачисленияАмортизацииНУ : Методы начисления амортизации
Коэффициент : Число 3, 2
АмортизацияДо2002 : Число 15, 2
АмортизацияДо2009 : Число 15, 2
СтоимостьДо2002 : Число 15, 2
ФактическийСрокИспользованияДо2009 : Число 4, 0
ДатаПриобретения : Дата
ДатаПринятияКУчетуУУ : Дата
ДатаПринятияКУчетуБУ : Дата
ДокументПринятияКУчетуУУ : Документ.Ввод остатков внеоборотных активов\rДокумент.Принятие к учету НМА
ДокументПринятияКУчетуБУ : Документ.Ввод остатков внеоборотных активов\rДокумент.Принятие к учету НМА\rДокумент.Принятие к учету НМА
ДокументСписания : Документ.Подготовка к передаче НМА\rДокумент.Списание НМА
ПорядокУчетаНУ : Порядок учета стоимости внеоборотных активов
}
@enduml
