@startuml ДанныеПоКонтрагентамКонтролируемыхСделок
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДанныеПоКонтрагентамКонтролируемыхСделок as "Данные по контрагентам контролируемых сделок" <<РегистрыСведений>>
{
..Измерения..
Контрагент : Справочник.Контрагент
..Ресурсы..
ЯвляетсяПлательщикомНалогаНаПрибыль : Булево
ЯвляетсяПлательщикомНДПИ : Булево
ЯвляетсяПлательщикомЕСХН : Булево
ЯвляетсяПлательщикомЕНВД : Булево
ЗарегистрированВОЭЗ : Булево
КодВидаДеятельностиФизическогоЛица : Строка
ФизическоеЛицо : Справочник.Физическое лицо
}
@enduml
