@startuml ПорядокОтраженияДоходов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПорядокОтраженияДоходов as "Порядок отражения доходов" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
СтатьяДоходов : Статьи доходов
..Ресурсы..
СчетУчета : Счет бухгалтерского учета
СтатьяДоходовРегл : Статьи доходов
}
@enduml
