@startuml УдалитьГосударственныеПособия
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьГосударственныеПособия as "(не используется) Государственные пособия" <<РегистрыСведений>>
{
..Измерения..
ВидПособия : Удалить виды государственных пособий
..Ресурсы..
Размер : Число 10, 2
}
@enduml
