@startuml ОчередьСообщенийОбменаСПодключаемымОборудованием
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОчередьСообщенийОбменаСПодключаемымОборудованием as "Очередь сообщений обмена с подключаемым оборудованием" <<РегистрыСведений>>
{
..Измерения..
ПодключаемоеОборудование : Справочник.Экземпляр подключаемого оборудования
ИдентификаторПередачи : Строка
ПорядковыйНомер : Число 10, 0
..Ресурсы..
Отправлен : Булево
ДанныеПакета : Хранилище значения
}
@enduml
