@startuml УстаревшиеВидыЗапасовСОстатками
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УстаревшиеВидыЗапасовСОстатками as "Устаревшие виды запасов с остатками" <<РегистрыСведений>>
{
..Измерения..
ВидЗапасов : Справочник.Вид запасов
}
@enduml
