@startuml ОтветыНаЗапросыИОС
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОтветыНаЗапросыИОС as "Ответы на запросы ИОС" <<РегистрыСведений>>
{
..Измерения..
Запрос : Документ.Запрос на информационное обслуживание страхователя
ИмяФайла : Строка
..Ресурсы..
Данные : Хранилище значения
..Реквизиты..
Размер : Число 10, 0
ОтветОтрицательный : Булево
ТипСодержимогоФайла : Типы содержимого файлов
}
@enduml
