@startuml СтатусФизическихЛицКакНалогоплательщиковНДФЛВторичный
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтатусФизическихЛицКакНалогоплательщиковНДФЛВторичный as "Статус физических лиц как налогоплательщиков НДФЛВторичный" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
ДатаНачала : Дата
ДатаОкончания : Дата
..Ресурсы..
Статус : Справочник.Статус налогоплательщика
РезидентРФНаКонецМесяца : Булево
ПрименяетсяСтавкаПункта1Статьи224НК : Булево
Год : Дата
РезидентРФНаКонецКвартала1 : Булево
РезидентРФНаКонецКвартала2 : Булево
РезидентРФНаКонецКвартала3 : Булево
РезидентРФНаКонецГода : Булево
СтатусНаКонецКвартала1 : Справочник.Статус налогоплательщика
СтатусНаКонецКвартала2 : Справочник.Статус налогоплательщика
СтатусНаКонецКвартала3 : Справочник.Статус налогоплательщика
СтатусНаКонецГода : Справочник.Статус налогоплательщика
}
@enduml
