@startuml ДействиеСкидокНаценок
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДействиеСкидокНаценок as "Действие скидок (наценок)" <<РегистрыСведений>>
{
..Измерения..
Источник : Справочник.Соглашение об условиях продаж\rСправочник.Вид карт лояльности\rСправочник.Склад (складская территория)
СкидкаНаценка : Справочник.Скидки (наценки)
..Ресурсы..
Статус : Статусы действия скидок
СегментПартнеров : Справочник.Сегмент клиентов
..Реквизиты..
Комментарий : Строка
Ответственный : Справочник.Внешний пользователь\rСправочник.Пользователь
}
@enduml
