@startuml ОчередьПереоформленияРасходныхОрдеров
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОчередьПереоформленияРасходныхОрдеров as "Очередь переоформления расходных ордеров" <<РегистрыСведений>>
{
..Измерения..
Склад : Справочник.Склад (складская территория)
Получатель : Справочник.Подразделение\rСправочник.Партнер\rСправочник.Склад (складская территория)
}
@enduml
