@startuml СоставГруппСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СоставГруппСотрудников as "Состав групп сотрудников" <<РегистрыСведений>>
{
..Измерения..
ГруппаСотрудников : Справочник.Группа сотрудников
Сотрудник : Справочник.Сотрудник
}
@enduml
