@startuml ОперацииРасчетаЗарплаты
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОперацииРасчетаЗарплаты as "Операции расчета зарплаты" <<РегистрыСведений>>
{
..Измерения..
Документ : Документ.Начисление зарплаты и взносов\rДокумент.Начисление за первую половину месяца
..Ресурсы..
ВидОперации : Справочник.Вид операции
}
@enduml
