@startuml ГрафикПлатежей
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ГрафикПлатежей as "График платежей" <<РегистрыСведений>>
{
..Измерения..
ОбъектОплаты : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\rДокумент.Таможенная декларация на импорт\r...
БанковскийСчетКасса : Справочник.Банковский счет организации\rСправочник.Касса
ДатаПлатежа : Дата
ПлательщикПолучатель : Справочник.Организация\rСправочник.Контрагент\rСправочник.Физическое лицо
Организация : Справочник.Организация
ПоступлениеСписание : Типы движения денежных средств
Валюта : Справочник.Валюта
..Ресурсы..
Сумма : Число 15, 2
..Реквизиты..
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
ХозяйственнаяОперация : Хозяйственные операции
ОбластьПланирования : Области планирования платежей
Подразделение : Справочник.Подразделение
НаправлениеДеятельности : Справочник.Направление деятельности
Приоритет : Справочник.Приоритет оплаты
Ответственный : Справочник.Пользователь
ТипОбъектаОплаты : Справочник.Идентификатор объекта метаданных
Номер : Строка
Дата : Дата
СуммаДокумента : Число 15, 2
ФормаОплаты : Формы оплаты
ДатаАктуальностиГрафика : Дата
}
@enduml
