@startuml УдалитьРазмерВычетовНДФЛ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьРазмерВычетовНДФЛ as "(не используется) Размер вычетов НДФЛ" <<РегистрыСведений>>
{
..Измерения..
КодВычета : Справочник.(не используется) Виды вычетов НДФЛ
..Ресурсы..
Размер : Число 10, 0
ОграничениеПоДоходам : Число 10, 0
}
@enduml
