@startuml СобытияОСОрганизаций
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СобытияОСОрганизаций as "События ОС организаций" <<РегистрыСведений>>
{
..Измерения..
ОсновноеСредство : Справочник.Объект эксплуатации
Организация : Справочник.Организация
..Ресурсы..
Событие : Справочник.Событие ОС
..Реквизиты..
НазваниеДокумента : Строка
НомерДокумента : Строка
СуммаЗатратБУ : Число 15, 2
СуммаЗатратНУ : Число 15, 2
СуммаЗатратУСН : Число 15, 2
}
@enduml
