@startuml ДолиСписанияКосвенныхРасходов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДолиСписанияКосвенныхРасходов as "Доли списания косвенных расходов подразделений" <<РегистрыСведений>>
{
..Измерения..
ПериодРасчета : Дата
Организация : Справочник.Организация
..Ресурсы..
ДоляРасходовНаРекламу : Число 10, 8
ДоляПредставительскихРасходов : Число 10, 8
ДоляРасходовНаДобровольноеМедицинскоеСтрахование : Число 10, 8
ДоляРасходовНаДобровольноеСтрахованиеЖизни : Число 10, 8
ДоляРасходовНаДобровольноеСтрахованиеОтНесчастныхСлучаев : Число 10, 8
ДоляРасходовНаВозмещениеПроцентовРаботникам : Число 10, 8
ДоляЕНВД : Число 10, 8
ДоляТранспортныхРасходов : Число 10, 8
ДоляРезервовПоСомнительнымДолгамНУ : Число 10, 8
}
@enduml
