@startuml ПодчиненияУзловОбъектовЭксплуатации
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПодчиненияУзловОбъектовЭксплуатации as "Подчинения узлов объектов эксплуатации" <<РегистрыСведений>>
{
..Измерения..
Узел : Справочник.Узел объекта эксплуатации
..Ресурсы..
Родитель : Справочник.Узел объекта эксплуатации
ОбъектЭксплуатации : Справочник.Объект эксплуатации
}
@enduml
