@startuml УдалитьНачальныеОстаткиОтпусков
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьНачальныеОстаткиОтпусков as "(не используется) Начальные остатки отпусков" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ВидЕжегодногоОтпуска : Справочник.Вид отпуска
..Ресурсы..
ДатаНачальныхОстатков : Дата
КоличествоДней : Число 5, 2
}
@enduml
