@startuml БезопасноеХранилищеДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.БезопасноеХранилищеДанных as "Безопасное хранилище данных" <<РегистрыСведений>>
{
..Измерения..
Владелец : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rСправочник.Присоединенные файлы (Поступление безналичных денежных средств)\r...
..Ресурсы..
Данные : Хранилище значения
}
@enduml
