@startuml ФизическиеЛицаДокументов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ФизическиеЛицаДокументов as "Физические лица документов" <<РегистрыСведений>>
{
..Измерения..
ДокументФизическогоЛица : Документ.Назначение планового начисления\rДокумент.Подтверждение открытия счетов\rДокумент.Изменение аванса\r...
ФизическоеЛицо : Справочник.Физическое лицо
}
@enduml
