@startuml ОтражениеДокументовВРеглУчете
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОтражениеДокументовВРеглУчете as "Отражение документов в регл учете" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ДатаОтражения : Дата
..Ресурсы..
Статус : Статусы отражения документов в регл учете
Комментарий : Строка
..Реквизиты..
ИдентификаторСтатуса : Уникальный идентификатор
}
@enduml
