@startuml УдалитьИсторияИспользованияДолжностей
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьИсторияИспользованияДолжностей as "(не используется) История использования должностей" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Должность : Справочник.Должность
..Ресурсы..
Используется : Булево
}
@enduml
