@startuml ПлановыеНачисления
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПлановыеНачисления as "Плановые начисления" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
Начисление : Начисление
ФизическоеЛицо : Справочник.Физическое лицо
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ГоловнаяОрганизация : Справочник.Организация
..Ресурсы..
Используется : Булево
Размер : Число 15, 2
ДействуетДо : Дата
УдалитьИспользуетсяПоОкончании : Булево
УдалитьРазмерПоОкончании : Число 15, 2
..Реквизиты..
ПересчетНеТребуется : Булево
ВторичнаяЗапись : Булево
}
@enduml
