@startuml УдалитьУчастникиОбменовЭДЧерезОператоровЭДО
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьУчастникиОбменовЭДЧерезОператоровЭДО as "(не используется) Участники обменов ЭД через операторов ЭДО" <<РегистрыСведений>>
{
..Измерения..
СоглашениеОбИспользованииЭД : Справочник.Настройка ЭДО
Участник : Справочник.Контрагент
..Ресурсы..
АдресЭП : Строка
ВерсияРегламентаЭДО : Версии регламента обмена1 С
ДатаИзмененияСтатуса : Дата
Идентификатор : Строка
Статус : Статусы участников обмена ЭД
ФорматФайловОбменаЭД : Форматы файлов обмена ЭД
..Реквизиты..
ОписаниеОшибки : Строка
}
@enduml
