@startuml ДанныеПервичныхДокументов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДанныеПервичныхДокументов as "Данные первичных документов" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Документ : Документ.Внутреннее потребление товаров\rДокумент.Подготовка к передаче НМА\rДокумент.Списание ОС\r...
..Ресурсы..
Номер : Строка
Дата : Дата
ДатаРегистратора : Дата
НомерРегистратора : Строка
}
@enduml
