@startuml УдалитьСреднемесячныеНормыВремениГрафиковРаботыСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьСреднемесячныеНормыВремениГрафиковРаботыСотрудников as "(Не используется) среднемесячные нормы времени графиков работы сотрудников" <<РегистрыСведений>>
{
..Измерения..
ГрафикРаботыСотрудников : Справочник.График работы
..Ресурсы..
СреднемесячноеЧислоЧасов : Число 3, 0
СреднемесячноеЧислоДней : Число 4, 1
..Реквизиты..
УстановленыВРучную : Булево
}
@enduml
