@startuml РассчитанныеОтборыПоНовостям_РедкоМеняющиеся
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РассчитанныеОтборыПоНовостям_РедкоМеняющиеся as "Рассчитанные отборы по новостям (редко меняющиеся)" <<РегистрыСведений>>
{
..Измерения..
Новость : Справочник.Новость
..Реквизиты..
РезультатОтбора : Булево
РезультатОтбораПоПродукту : Число 1, 0
РезультатОтбораПоВерсииПродукта : Число 1, 0
РезультатОтбораПоВерсииПлатформы : Число 1, 0
}
@enduml
