@startuml ПрогнозыРасходаУпаковок
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПрогнозыРасходаУпаковок as "Прогнозы расхода упаковок" <<РегистрыСведений>>
{
..Измерения..
Склад : Справочник.Склад (складская территория)
Помещение : Справочник.Помещение
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Серия : Справочник.Серия номенклатуры
Упаковка : Справочник.Упаковка
..Ресурсы..
СреднедневноеПотребление : Число 15, 3
СреднеквадратическоеОтклонение : Число 15, 3
ВероятностьОтгрузкиВТечениеДня : Число 5, 2
НормативноеКоличествоЗапаса : Число 15, 3
НазначеноПользователем : Булево
Класс : XYZ Классификация
..Реквизиты..
СтатусУказанияСерий : Число 2, 0
}
@enduml
