@startuml ПрименениеСтандартныхВычетовПоНДФЛВторичный
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПрименениеСтандартныхВычетовПоНДФЛВторичный as "Применение стандартных вычетов по НДФЛ (вторичные данные)" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
ДатаНачала : Дата
ДатаОкончания : Дата
..Ресурсы..
ГоловнаяОрганизация : Справочник.Организация
ПрименятьВычеты : Булево
}
@enduml
