@startuml БлокировкиСеансовОбластейДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.БлокировкиСеансовОбластейДанных as "Блокировки сеансов областей данных" <<РегистрыСведений>>
{
..Ресурсы..
НачалоБлокировки : Дата
КонецБлокировки : Дата
СообщениеБлокировки : Строка
Эксклюзивная : Булево
}
@enduml
