@startuml НематериальныеАктивыМеждународныйУчет
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НематериальныеАктивыМеждународныйУчет as "Нематериальные активы (Международный учет)" <<РегистрыСведений>>
{
..Измерения..
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
..Ресурсы..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Состояние : Виды состояний НМА
СчетУчета : Международный план счетов
ЛиквидационнаяСтоимость : Число 15, 2
ЛиквидационнаяСтоимостьПредставления : Число 15, 2
МетодНачисленияАмортизации : Способы начисления амортизации нематериальных активов
ПорядокУчета : Порядок учета стоимости внеоборотных активов
СчетАмортизации : Международный план счетов
СрокИспользования : Число 10, 0
ОбъемНаработки : Число 15, 3
КоэффициентУскорения : Число 4, 3
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
}
@enduml
