@startuml ТерриторииСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ТерриторииСотрудников as "Территории сотрудников" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ГоловнаяОрганизация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
Территория : Справочник.Территория
ДействуетДо : Дата
ТерриторияПоОкончании : Справочник.Территория
}
@enduml
