@startuml ПорядокОтраженияТМЦВЭксплуатации
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПорядокОтраженияТМЦВЭксплуатации as "Порядок отражения ТМЦ в эксплуатации" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
КатегорияЭксплуатации : Справочник.Категории эксплуатации
..Ресурсы..
СчетУчета : Счет бухгалтерского учета
СчетЗабалансовогоУчета : Счет бухгалтерского учета
}
@enduml
