@startuml ЖурналНовыхСобытий
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЖурналНовыхСобытий as "Журнал новых событий" <<РегистрыСведений>>
{
..Измерения..
Ссылка : Документ.Выгрузка регламентированных отчетов\rДокумент.Сведения о заработке и стаже застрахованных лиц, СЗВ-ИСХ\rДокумент.2-НДФЛ для передачи в ИФНС\r...
..Ресурсы..
Просмотрено : Булево
ПоказатьПользователю : Булево
..Реквизиты..
СеансСвязи : Справочник.Сеансы связи с контролирующими органами
Статус : Строка
Организация : Справочник.Организация
ДатаСобытия : Дата
КонтролирующийОрган : Строка
Группа : Группы новых событий документооборота с контролирующими органами
Состояние : Состояние сдачи отчетности
Порядок : Число 10, 0
ОтправленоПолучено : Дата
ЕстьОтвет : Булево
НеОтправляетсяВКонтролирующийОрган : Булево
Наименование : Строка
ЕстьКритическиеОшибкиОтправки : Булево
Скрыт : Булево
}
@enduml
