@startuml ОчередьСобытийДляОповещенийКлиентам
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОчередьСобытийДляОповещенийКлиентам as "Очередь событий для оповещений клиентам" <<РегистрыСведений>>
{
..Измерения..
ВидОповещения : Справочник.Вид оповещений клиентам
ИсточникОповещения : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
Подписчик : Справочник.Партнер
..Реквизиты..
ДатаОтправки : Дата
ДатаАктуальностиОтправки : Дата
}
@enduml
