@startuml ЗаданияКРасчетуАмортизацииНМА
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗаданияКРасчетуАмортизацииНМА as "Задания к расчету амортизации НМА" <<РегистрыСведений>>
{
..Измерения..
Месяц : Дата
Организация : Справочник.Организация
НомерПакета : Число 10, 0
НомерЗадания : Число 15, 0
Документ : Документ.Подготовка к передаче НМА\rДокумент.Переоценка НМА\rДокумент.Подготовка к передаче НМА\r...
}
@enduml
