@startuml УдалитьОтветыНаЗапросыВыпискиИзЕГРЮЛ_ЕГРИП
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьОтветыНаЗапросыВыпискиИзЕГРЮЛ_ЕГРИП as "(Не используется) Ответы на запросы выписок из ЕГРЮЛ/ЕГРИП" <<РегистрыСведений>>
{
..Измерения..
Запрос : Документ.(Не используется) Запрос на выписку из ЕГРЮЛ/ЕГРИП
ИмяФайла : Строка
..Ресурсы..
Данные : Хранилище значения
..Реквизиты..
Размер : Число 10, 0
РезультатОбработкиЗапроса : Строка
}
@enduml
