@startuml УченыеСтепениФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УченыеСтепениФизическихЛиц as "Ученые степени физических лиц" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
НомерПоПорядку : Число 2, 0
..Ресурсы..
УченаяСтепень : Справочник.Ученая степень
ДатаПрисужденияУченойСтепени : Дата
УдалитьОтрасльНауки : Строка
ДиссертационныйСовет : Строка
ДипломСерияНомер : Строка
ДипломВыданОрганизация : Строка
}
@enduml
