@startuml БронированиеСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.БронированиеСотрудников as "Бронирование сотрудников" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
Организация : Справочник.Организация
}
@enduml
