@startuml НачислениеАмортизацииНМАСпециальныйКоэффициентНалоговыйУчет
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НачислениеАмортизацииНМАСпециальныйКоэффициентНалоговыйУчет as "Специальный коэффициент для амортизации НМА (налог. учет)" <<РегистрыСведений>>
{
..Измерения..
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
Организация : Справочник.Организация
..Ресурсы..
СпециальныйКоэффициент : Число 5, 2
}
@enduml
