@startuml ИсторияЕжегодныхОтпусковПоШтатномуРасписанию
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИсторияЕжегодныхОтпусковПоШтатномуРасписанию as "История ежегодных отпусков по штатному расписанию" <<РегистрыСведений>>
{
..Измерения..
Дата : Дата
ПозицияШтатногоРасписания : Справочник.Позиция
ВидЕжегодногоОтпуска : Справочник.Вид отпуска
..Ресурсы..
КоличествоДнейВГод : Число 2, 0
}
@enduml
