@startuml РегистрацииВНалоговомОргане
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РегистрацииВНалоговомОргане as "Регистрации подразделений" <<РегистрыСведений>>
{
..Измерения..
Подразделение : Справочник.Подразделение
Организация : Справочник.Организация
..Ресурсы..
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
}
@enduml
