@startuml ИсторияИзмененияФорматовМагазинов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИсторияИзмененияФорматовМагазинов as "История изменения форматов магазинов" <<РегистрыСведений>>
{
..Измерения..
Склад : Справочник.Склад (складская территория)
..Ресурсы..
ФорматМагазина : Справочник.Форматы магазинов
КонтролироватьАссортимент : Булево
..Реквизиты..
Автор : Справочник.Пользователь
ДатаЗаписи : Дата
}
@enduml
