@startuml НастройкиВариантовОтчетов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиВариантовОтчетов as "Настройки вариантов отчетов" <<РегистрыСведений>>
{
..Измерения..
Пользователь : Справочник.Внешний пользователь\rСправочник.Пользователь
Подсистема : Справочник.Идентификатор объекта метаданных
Вариант : Справочник.Вариант отчета
..Ресурсы..
Видимость : Булево
БыстрыйДоступ : Булево
}
@enduml
