@startuml ПерерасчетЗарплаты
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПерерасчетЗарплаты as "Перерасчет зарплаты" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ПериодДействия : Дата
Основание : Документ.Сторнирование начислений\rДокумент.Назначение планового начисления\rДокумент.Изменение мест работы\r...
ДокументНачисления : Документ.Простой сотрудников\rДокумент.Отпуск без сохранения оплаты списком\rДокумент.Отпуск\r...
Доначисление : Булево
}
@enduml
