@startuml ГрафикиАмортизацииОСБухгалтерскийУчет
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ГрафикиАмортизацииОСБухгалтерскийУчет as "Графики амортизации ОС (бухгалтерский учет)" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ОсновноеСредство : Справочник.Объект эксплуатации
..Ресурсы..
ГрафикАмортизации : Справочник.Годовой график амортизации ОС
}
@enduml
