@startuml НумераторПачекПФР
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НумераторПачекПФР as "Нумератор пачек ПФР" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Год : Число 4, 0
..Ресурсы..
НомерПачки : Число 5, 0
}
@enduml
