@startuml ВоинскийУчет
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ВоинскийУчет as "Воинский учет" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
ОтношениеКВоинскойОбязанности : Отношение к воинской обязанности
ОтношениеКВоинскомуУчету : Отношение к воинскому учету
КатегорияЗапаса : Категории запаса военнообязанных
Звание : Справочник.Воинское звание
Состав : Справочник.Состав военнослужащих
ВУС : Строка
Годность : Годность к военной службе
Военкомат : Справочник.Военкомат
НаличиеМобпредписания : Булево
НомерКомандыПартии : Строка
ПунктПеречня : Справочник.Должность (профессия) для бронирования
}
@enduml
