@startuml НумерацияЧековККТ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НумерацияЧековККТ as "Нумерация чеков ККТ" <<РегистрыСведений>>
{
..Измерения..
ПодключаемоеОборудование : Справочник.Экземпляр подключаемого оборудования
КассоваяСмена : Документ.Кассовая смена
..Ресурсы..
ПорядковыйНомер : Число 10, 0
}
@enduml
