@startuml ПользовательскиеМакетыПечати
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПользовательскиеМакетыПечати as "Пользовательские макеты печати" <<РегистрыСведений>>
{
..Измерения..
ИмяМакета : Строка
Объект : Строка
..Ресурсы..
Макет : Хранилище значения
..Реквизиты..
Использование : Булево
}
@enduml
