@startuml РаспределениеПоТерриториямУсловиямТруда
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РаспределениеПоТерриториямУсловиямТруда as "Распределение по территориям и условиям труда" <<РегистрыСведений>>
{
..Измерения..
РегистраторИзмерение : Документ.Сторнирование начислений\rДокумент.Простой сотрудников\rДокумент.Отпуск без сохранения оплаты списком\r...
ИдентификаторСтроки : Число 7, 0
Территория : Справочник.Территория
УсловияТруда : Справочник.Условия труда
ИдентификаторСтрокиПоказателей : Число 7, 0
..Ресурсы..
ДоляРаспределения : Число 15, 5
Результат : Число 15, 2
СуммаВычета : Число 13, 0
}
@enduml
