@startuml СхемыОбеспечения
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СхемыОбеспечения as "Схемы обеспечения" <<РегистрыСведений>>
{
..Измерения..
СхемаОбеспечения : Справочник.Схема обеспечения
Склад : Справочник.Форматы магазинов\rСправочник.Склад (складская территория)
..Ресурсы..
СпособОбеспеченияПотребностей : Справочник.Способ обеспечения потребностей
}
@enduml
