@startuml ПротоколыРасчетаПартийИСебестоимости
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПротоколыРасчетаПартийИСебестоимости as "Протоколы расчета партий и себестоимости" <<РегистрыСведений>>
{
..Измерения..
Идентификатор : Строка
..Ресурсы..
Протокол : Хранилище значения
..Реквизиты..
ДлительностьРасчета : Строка
ПериодРасчета : Дата
ПредставлениеОрганизаций : Строка
ВариантРасчета : Варианты расчета партий и себестоимости
БылиОшибки : Булево
ОписаниеОшибок : Строка
}
@enduml
