@startuml БухучетЗарплатыОрганизаций
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.БухучетЗарплатыОрганизаций as "Бухучет зарплаты организаций" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОтношениеКЕНВД : Отношение к ЕНВД затрат на зарплату
СтатьяФинансирования : Справочник.Статья финансирования
}
@enduml
