@startuml ТекущаяТарифнаяСтавкаСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ТекущаяТарифнаяСтавкаСотрудников as "Текущая тарифная ставка сотрудников" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
Сотрудник : Справочник.Сотрудник
ГоловнаяОрганизация : Справочник.Организация
ТекущаяОрганизация : Справочник.Организация
..Ресурсы..
ТекущаяТарифнаяСтавка : Число 15, 2
ТекущийФОТ : Число 15, 2
ТекущаяНадбавка : Число 15, 2
ТекущийСпособРасчетаАванса : Способы расчета аванса
ТекущийАванс : Число 15, 2
}
@enduml
