@startuml ЗаданияКОтражениюВБюджетировании
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗаданияКОтражениюВБюджетировании as "Задания к отражению в бюджетировании" <<РегистрыСведений>>
{
..Измерения..
НомерЗадания : Число 15, 0
Документ : Документ.Сторнирование начислений\rДокумент.Внутреннее потребление товаров\rДокумент.Назначение планового начисления\r...
ПериодЗаписи : Дата
..Ресурсы..
ИмяВидаДокумента : Строка
}
@enduml
