@startuml НаследованиеНастроекПравОбъектов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НаследованиеНастроекПравОбъектов as "Наследование настроек прав объектов" <<РегистрыСведений>>
{
..Измерения..
Объект : Справочник.Папка
Родитель : Справочник.Папка
..Ресурсы..
Наследовать : Булево
..Реквизиты..
УровеньИспользования : Число 1, 0
}
@enduml
