@startuml НастройкиСинхронизацииФайлов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиСинхронизацииФайлов as "Настройки синхронизации файлов" <<РегистрыСведений>>
{
..Измерения..
ВладелецФайла : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
ТипВладельцаФайла : Справочник.Идентификатор объекта метаданных
УчетнаяЗапись : Справочник.Учетная запись синхронизации файлов
..Ресурсы..
ПравилоОтбора : Хранилище значения
Синхронизировать : Булево
ЭтоФайл : Булево
..Реквизиты..
Наименование : Строка
}
@enduml
