@startuml РезультатыОбменаДанными
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РезультатыОбменаДанными as "Предупреждения при синхронизации данных" <<РегистрыСведений>>
{
..Измерения..
ПроблемныйОбъект : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
ТипПроблемы : Типы проблем обмена данными
..Ресурсы..
УзелИнформационнойБазы : Синхронизация данных через универсальный формат\rОбмен с подключаемым оборудованием Offline\rОбрабатываемый объект\r...
ДатаВозникновения : Дата
Причина : Строка
Пропущена : Булево
..Реквизиты..
ПометкаУдаления : Булево
НомерДокумента : Строка
ДатаДокумента : Дата
}
@enduml
