@startuml ШаблоныПечатиМашиночитаемыхФорм
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ШаблоныПечатиМашиночитаемыхФорм as "Шаблоны печати машиночитаемых форм" <<РегистрыСведений>>
{
..Измерения..
ИмяФайлаШаблона : Строка
..Ресурсы..
Шаблон : Хранилище значения
..Реквизиты..
Размер : Число 15, 0
ДатаДобавления : Дата
}
@enduml
