@startuml ДлительностьПереналадки
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДлительностьПереналадки as "Длительность переналадки" <<РегистрыСведений>>
{
..Измерения..
ВидРабочегоЦентра : Справочник.Вид рабочего центра
ТекущийВариантНаладки : Справочник.Вариант наладки
СледующийВариантНаладки : Справочник.Вариант наладки
..Ресурсы..
ВремяПереналадки : Число 10, 0
}
@enduml
