@startuml ЗаданияКРасчетуГрафикаПроизводства
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗаданияКРасчетуГрафикаПроизводства as "Задания к расчету графика производства" <<РегистрыСведений>>
{
..Измерения..
Распоряжение : Документ.Заказ на производство
ЭтапПроизводства : Документ.Этап производства
НомерЗадания : Число 15, 0
}
@enduml
