@startuml ВариантыОбеспеченияРаботами
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ВариантыОбеспеченияРаботами as "Порядок применения способов обеспечения работами" <<РегистрыСведений>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
СпособОбеспеченияПотребностей : Справочник.Способ обеспечения потребностей
..Реквизиты..
РеквизитДопУпорядочивания : Число 5, 0
}
@enduml
