@startuml УдалитьОчередьИзвлеченияТекста
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьОчередьИзвлеченияТекста as "(не используется) Очередь извлечения текста" <<РегистрыСведений>>
{
..Измерения..
ОбластьДанных : Число 7, 0
ИсточникТекста : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rСправочник.Присоединенные файлы (Поступление безналичных денежных средств)\r...
}
@enduml
