@startuml ПодписываемыеВидыЭД
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПодписываемыеВидыЭД as "Подписываемые виды электронных документов" <<РегистрыСведений>>
{
..Измерения..
СертификатЭП : Справочник.Сертификат ключа электронной подписи и шифрования
ВидЭД : Виды электронных документов\rВиды электронных документов обмена с банками
..Ресурсы..
Использовать : Булево
}
@enduml
