@startuml НеобрабатываемыеТранспортныеСообщения
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НеобрабатываемыеТранспортныеСообщения as "Необрабатываемые транспортные сообщения" <<РегистрыСведений>>
{
..Измерения..
ТранспортноеСообщение : Документ.Транспортное сообщение
Пользователь : Справочник.Пользователь
}
@enduml
