@startuml ВычетыПоДоходамНДФЛ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ВычетыПоДоходамНДФЛ as "Вычеты к доходам по НДФЛ" <<РегистрыСведений>>
{
..Измерения..
КодДохода : Справочник.Вид дохода НДФЛ
..Ресурсы..
ГодовойВычет : Число 15, 2
НормативЗатрат : Число 15, 2
}
@enduml
