@startuml СтатистикаКонфигурации
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтатистикаКонфигурации as "Статистика конфигурации" <<РегистрыСведений>>
{
..Измерения..
ВидСтатистики : Число 1, 0
ИдентификаторОбластиСтатистики : Уникальный идентификатор
ОперацияСтатистики : Уникальный идентификатор
..Ресурсы..
Значение : Число 15, 3
}
@enduml
