@startuml СостоянияОбменовДаннымиОбластейДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияОбменовДаннымиОбластейДанных as "Состояния обменов данными областей данных" <<РегистрыСведений>>
{
..Измерения..
УзелИнформационнойБазы : Синхронизация данных через универсальный формат\rОбмен с подключаемым оборудованием Offline\rОбрабатываемый объект\r...
ДействиеПриОбмене : Действия при обмене
..Ресурсы..
РезультатВыполненияОбмена : Результаты выполнения обмена
ДатаНачала : Дата
ДатаОкончания : Дата
}
@enduml
