@startuml ЖурналОбменСБанками
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЖурналОбменСБанками as "Журнал обмен с банками" <<РегистрыСведений>>
{
..Измерения..
НастройкаОбмена : Справочник.Настройка обмена с банком
Пользователь : Справочник.Внешний пользователь\rСправочник.Пользователь
Индекс : Число 10, 0
..Ресурсы..
Запись : Строка
}
@enduml
