@startuml ОтправкиОтчетностиКОбработке
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОтправкиОтчетностиКОбработке as "Отправки отчетности к обработке" <<РегистрыСведений>>
{
..Измерения..
Идентификатор : Строка
..Ресурсы..
Статус : Статусы отправки отчетности
ТребуетАудита : Булево
}
@enduml
