@startuml УдалитьЗамерыВремени3
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьЗамерыВремени3 as "(не используется) Замеры времени 3" <<РегистрыСведений>>
{
..Измерения..
КлючеваяОперация : Справочник.Ключевая операция
ДатаНачалаЗамера : Число 14, 0
НомерСеанса : Число 15, 0
ДатаЗаписиНачалоЧаса : Дата
..Ресурсы..
ВремяВыполнения : Число 15, 3
ВесЗамера : Число 10, 0
Комментарий : Строка
..Реквизиты..
ДатаЗаписи : Дата
ДатаОкончания : Число 14, 0
Пользователь : Строка
ДатаЗаписиЛокальная : Дата
}
@enduml
