@startuml НастройкиВзаиморасчетовССотрудниками
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиВзаиморасчетовССотрудниками as "Настройки взаиморасчетов с сотрудниками" <<РегистрыСведений>>
{
..Ресурсы..
ПроверятьЗаполнениеФинансированияВВедомостях : Булево
ПроверятьСоответствиеНачисленийИВыплат : Булево
}
@enduml
