@startuml РесурсыМеханизмаОнлайнСервисовРО
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РесурсыМеханизмаОнлайнСервисовРО as "Ресурсы механизма онлайн сервисов РО" <<РегистрыСведений>>
{
..Измерения..
Тип : Типы ресурсов механизма онлайн-сервисов РО
..Ресурсы..
Данные : Строка
..Реквизиты..
Имя : Строка
ДатаПолучения : Дата
}
@enduml
