@startuml ЖурналРегистрацииАгентаКопированияОблачногоАрхива
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЖурналРегистрацииАгентаКопированияОблачногоАрхива as "Журнал регистрации агента копирования облачного архива" <<РегистрыСведений>>
{
..Измерения..
ИмяКомпьютера : Строка
ДатаСообщения : Дата
ТипСообщения : Строка
ТекстСообщения : Строка
}
@enduml
