@startuml ПериодическиеЗначенияПоказателейРасчетаЗарплаты
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПериодическиеЗначенияПоказателейРасчетаЗарплаты as "Периодические значения показателей расчета зарплаты" <<РегистрыСведений>>
{
..Измерения..
Показатель : Справочник.Показатель
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
..Ресурсы..
Значение : Число 15, 3
}
@enduml
