@startuml ПлановыеАвансыИспр
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПлановыеАвансыИспр as "Плановые авансы испр" <<РегистрыСведений>>
{
..Измерения..
РегистраторИзмерение : Документ.Изменение аванса\rДокумент.Изменение условий оплаты отпуска по уходу за ребенком\rДокумент.Изменение оплаты труда\r...
ПериодИзмерение : Дата
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ГоловнаяОрганизация : Справочник.Организация
..Ресурсы..
СпособРасчетаАванса : Способы расчета аванса
Аванс : Число 15, 2
ДействуетДо : Дата
СпособРасчетаАвансаПоОкончании : Способы расчета аванса
АвансПоОкончании : Число 15, 2
}
@enduml
