@startuml НастройкиУчетаВремени
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиУчетаВремени as "Настройки учета времени" <<РегистрыСведений>>
{
..Ресурсы..
УчитыватьНочныеЧасы : Булево
УчитыватьВечерниеЧасы : Булево
ИспользоватьНесколькоВидовПлановогоВремени : Булево
УчитыватьВремяНаКормлениеРебенка : Булево
ПроверятьСоответствиеФактическогоВремениПлановому : Булево
}
@enduml
