@startuml ДанныеБизнесПроцессов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДанныеБизнесПроцессов as "Бизнес-процессы" <<РегистрыСведений>>
{
..Измерения..
БизнесПроцесс : Задание\rСогласование заявки на возврат товаров от клиента\rСогласование закупки\r...
..Ресурсы..
Номер : Строка
Дата : Дата
Завершен : Булево
Стартован : Булево
Автор : Справочник.Пользователь
ДатаЗавершения : Дата
Наименование : Строка
ПометкаУдаления : Булево
}
@enduml
