@startuml СвойстваТранспортныхСообщений
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СвойстваТранспортныхСообщений as "Свойства транспортных сообщений" <<РегистрыСведений>>
{
..Измерения..
УчетнаяЗапись : Справочник.(не используется) Учетные записи документооборота\rСправочник.Учетные записи документооборота
ТранспортноеСообщение : Документ.Транспортное сообщение
..Ресурсы..
ДатаПолучения : Дата
ТребуетВнимания : Булево
ТребуетРасшифровки : Булево
}
@enduml
