@startuml АналогиВПроизводстве
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.АналогиВПроизводстве as "Аналоги в производстве" <<РегистрыСведений>>
{
..Измерения..
Материал : Справочник.Номенклатура
ХарактеристикаМатериала : Справочник.Характеристика номенклатуры
Спецификация : Справочник.Ресурсная спецификация
КлючСвязиСпецификация : Уникальный идентификатор
Подразделение : Справочник.Подразделение
ЗаказКлиента : Документ.Заказ клиента
ЗаказНаПроизводство : Документ.Заказ на производство\rДокумент.Заказ на производство
Изделие : Справочник.Номенклатура
ХарактеристикаИзделия : Справочник.Характеристика номенклатуры
Аналог : Справочник.Номенклатура
ХарактеристикаАналога : Справочник.Характеристика номенклатуры
..Ресурсы..
ПериодЗавершения : Дата
УпаковкаМатериала : Справочник.Упаковка
КоличествоМатериала : Число 15, 3
КоличествоУпаковокМатериала : Число 15, 3
УпаковкаАналога : Справочник.Упаковка
КоличествоАналога : Число 10, 3
КоличествоУпаковокАналога : Число 10, 3
}
@enduml
