@startuml СостоянияСинхронизацииТорговыеПредложения
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияСинхронизацииТорговыеПредложения as "Состояние синхронизации (Торговые предложения)" <<РегистрыСведений>>
{
..Измерения..
ТорговоеПредложение : Справочник.Соглашение об условиях продаж
Организация : Справочник.Организация
..Ресурсы..
ДатаСинхронизации : Дата
Состояние : Состояния синхронизации (торговые предложения)
ДействиеСинхронизации : Действия синхронизации (торговые предложения)
..Реквизиты..
ОписаниеОшибки : Строка
УведомлятьОЗаказах : Булево
АдресЭлектроннойПочты : Строка
ДополнительноеОписание : Строка
ВыгружатьКартинки : Булево
}
@enduml
