@startuml ВсеОбновленияНовостей
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ВсеОбновленияНовостей as "Все обновления новостей" <<РегистрыСведений>>
{
..Измерения..
ВидОбновления : Строка
ЛентаНовостей : Справочник.Лента новостей
..Ресурсы..
ДатаПоследнегоОбновления : Дата
ДатаСледующегоОбновления : Дата
}
@enduml
