@startuml НастройкаЗаполненияСвободныхСтрокФормСтатистики
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкаЗаполненияСвободныхСтрокФормСтатистики as "Настройка заполнения свободных строк форм статистики" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ОбъектНаблюдения : Справочник.Объект наблюдения
ДетализацияОбъектаНаблюдения : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Классификатор услуг населению (ОКУН)\rСправочник.ОКВЭД
..Ресурсы..
Настройка : Строка
..Реквизиты..
ПредставлениеНастройки : Строка
}
@enduml
