@startuml ЗарплатаКадрыДолиСписанияКосвенныхРасходов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗарплатаКадрыДолиСписанияКосвенныхРасходов as "Зарплата кадры доли списания косвенных расходов" <<РегистрыСведений>>
{
..Измерения..
ПериодРасчета : Дата
Организация : Справочник.Организация
..Ресурсы..
ДоляРезервовОтпусков : Число 10, 8
}
@enduml
