@startuml ДампыПлатформы
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДампыПлатформы as "Дампы платформы" <<РегистрыСведений>>
{
..Измерения..
ДатаРегистрации : Число 14, 0
ВариантДампа : Строка
ВерсияПлатформы : Число 24, 0
..Ресурсы..
ИмяФайла : Строка
}
@enduml
