@startuml ДополнительныеАдресныеСведения
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДополнительныеАдресныеСведения as "Дополнительные адресные сведения" <<РегистрыСведений>>
{
..Измерения..
Идентификатор : Уникальный идентификатор
КодСубъектаРФ : Число 2, 0
..Ресурсы..
OKATO : Число 11, 0
ОКТМО : Число 11, 0
КодИФНСФЛ : Число 4, 0
КодИФНСЮЛ : Число 4, 0
КодУчасткаИФНСФЛ : Число 4, 0
КодУчасткаИФНСЮЛ : Число 4, 0
}
@enduml
