@startuml УдалитьДополнительныеФайлыУведомлений
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьДополнительныеФайлыУведомлений as "(не используется) Дополнительные файлы уведомлений" <<РегистрыСведений>>
{
..Измерения..
Уведомление : Документ.Уведомление о спецрежимах налогообложения
ВидДополнительногоФайла : Строка
..Ресурсы..
СодержимоеФайла : Хранилище значения
..Реквизиты..
ИмяФайла : Строка
Размер : Число 15, 0
ДатаИзмененияФайла : Дата
ДатаДобавления : Дата
}
@enduml
