@startuml РасчетРезервовПоСомнительнымДолгам
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РасчетРезервовПоСомнительнымДолгам as "Расчет резервов по сомнительным долгам" <<РегистрыСведений>>
{
..Измерения..
ПериодРасчета : Дата
Организация : Справочник.Организация
Контрагент : Справочник.Организация\rСправочник.Контрагент
ДоговорКонтрагента : Справочник.Договор между организациями\rСправочник.Договор с контрагентом
ДокументРасчетовСКонтрагентом : Документ.Возврат товаров от клиента\rДокумент.Отчет комиссионера (агента) о продажах\rДокумент.Отчет давальцу\r...
..Ресурсы..
СуммаЗадолженности : Число 12, 2
НачисленоРанееБУ : Число 15, 2
НачисленоРанееНУ : Число 15, 2
НачисленоБУ : Число 15, 2
НачисленоНУ : Число 12, 2
ВосстановленоБУ : Число 12, 2
ВосстановленоНУ : Число 12, 2
ПрисоединеноБУ : Число 15, 2
НачисленоСНачалаГодаНУ : Число 15, 2
ДатаВозникновенияЗадолженности : Дата
СрокЗадолженности : Число 4, 0
ВстречнаяЗадолженность : Число 12, 2
}
@enduml
