@startuml ОшибочныеРеквизитыКонтрагентов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОшибочныеРеквизитыКонтрагентов as "Ошибочные реквизиты контрагентов" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Контрагент : Справочник.Контрагент
СчетФактура : Документ.Счет-фактура полученный
ИсходныйСчетФактура : Документ.Счет-фактура полученный
..Ресурсы..
ИНН : Строка
КПП : Строка
}
@enduml
