@startuml ФайлыВРабочемКаталоге
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ФайлыВРабочемКаталоге as "Файлы в рабочем каталоге" <<РегистрыСведений>>
{
..Измерения..
Файл : Справочник.Присоединенный файл (Отчет комиссионера)\rСправочник.Присоединенные файлы (Поступление безналичных денежных средств)\rСправочник.Присоединенный файл (Сообщение обмена с банками)\r...
Пользователь : Справочник.Пользователь
..Ресурсы..
Путь : Строка
Размер : Число 10, 0
ДатаПомещенияВРабочийКаталог : Дата
НаЧтение : Булево
ВРабочемКаталогеВладельца : Булево
}
@enduml
