@startuml УчетнаяПолитикаОрганизацийДляМеждународногоУчета
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УчетнаяПолитикаОрганизацийДляМеждународногоУчета as "Учетная политика организаций (международный учет)" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
УчетнаяПолитика : Справочник.Учетная политика
}
@enduml
