@startuml ИерархияПартнеров
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИерархияПартнеров as "Иерархия партнеров" <<РегистрыСведений>>
{
..Измерения..
Партнер : Справочник.Партнер
Родитель : Справочник.Партнер
..Реквизиты..
Уровень : Число 10, 0
}
@enduml
