@startuml СлужебныеАдресныеСведения
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СлужебныеАдресныеСведения as "Служебные адресные сведения" <<РегистрыСведений>>
{
..Измерения..
Тип : Строка
Идентификатор : Число 2, 0
Ключ : Строка
..Ресурсы..
Значение : Строка
}
@enduml
