@startuml КодыТоваровПодключаемогоОборудованияOffline
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КодыТоваровПодключаемогоОборудованияOffline as "Коды товаров подключаемого оборудования offline" <<РегистрыСведений>>
{
..Измерения..
ПравилоОбмена : Справочник.Правила обмена с подключаемым оборудованием offline
Код : Число 15, 0
..Ресурсы..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
Используется : Булево
}
@enduml
