@startuml ПоставляемыеДанныеТребующиеОбработки
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПоставляемыеДанныеТребующиеОбработки as "Поставляемые данные требующие обработки" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторФайла : Уникальный идентификатор
КодОбработчика : Строка
..Ресурсы..
КоличествоПопыток : Число 10, 0
}
@enduml
