@startuml ПараметрыРаботыПрограммы
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПараметрыРаботыПрограммы as "Параметры работы программы" <<РегистрыСведений>>
{
..Измерения..
ИмяПараметра : Строка
..Ресурсы..
ХранилищеПараметра : Хранилище значения
}
@enduml
