@startuml ДокументыСреднегоЗаработка
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДокументыСреднегоЗаработка as "Документы среднего заработка" <<РегистрыСведений>>
{
..Измерения..
ДокументОснование : Документ.Отпуск\rДокумент.Больничный лист\rДокумент.Отсутствие с сохранением оплаты\r...
Сотрудник : Справочник.Сотрудник
..Ресурсы..
ДатаНачалаСобытия : Дата
}
@enduml
