@startuml СостоянияВнутреннихЗаказов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияВнутреннихЗаказов as "Состояния внутренних заказов" <<РегистрыСведений>>
{
..Измерения..
Заказ : Документ.Заказ на сборку (разборку)\rДокумент.Заказ на перемещение\rДокумент.Заказ на внутреннее потребление
..Ресурсы..
Состояние : Состояния внутренних заказов
..Реквизиты..
ЕстьРасхожденияОрдерНакладная : Булево
}
@enduml
