@startuml РазрешенныеДляРедактированияЛентыНовостей
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РазрешенныеДляРедактированияЛентыНовостей as "Разрешенные для редактирования ленты новостей" <<РегистрыСведений>>
{
..Измерения..
Пользователь : Справочник.Пользователь
ЛентаНовостей : Справочник.Лента новостей
}
@enduml
