@startuml ТребуетсяОформлениеСчетаФактуры
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ТребуетсяОформлениеСчетаФактуры as "Требуется оформление счета-фактуры" <<РегистрыСведений>>
{
..Измерения..
Основание : Документ.Отчет давальцу\rДокумент.Возврат товаров поставщику\rДокумент.Отчет по комиссии между организациями\r...
Организация : Справочник.Организация
Контрагент : Справочник.Организация\rСправочник.Контрагент
..Реквизиты..
Валюта : Справочник.Валюта
}
@enduml
