@startuml СостоянияДокументовЗачисленияЗарплаты
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияДокументовЗачисленияЗарплаты as "Состояния документов зачисления зарплаты" <<РегистрыСведений>>
{
..Измерения..
ДокументЗачисленияЗарплаты : Документ.Списание безналичных ДС\rДокумент.Ведомость в банк\rДокумент.Ведомость прочих доходов в банк\r...
..Ресурсы..
Состояние : Состояние зачисления зарплаты
Год : Число 4, 0
НомерРеестра : Число 10, 0
Организация : Справочник.Организация
}
@enduml
