@startuml ГрафикТраншейКредитовИДепозитов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ГрафикТраншейКредитовИДепозитов as "График траншей" <<РегистрыСведений>>
{
..Измерения..
ВариантГрафика : Справочник.Вариант графика
..Ресурсы..
Сумма : Число 15, 2
}
@enduml
