@startuml ФайлыСведенийСпецоператоры
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ФайлыСведенийСпецоператоры as "Кэш файлов с ресурсов операторов электронного документооборота по универсальной схеме" <<РегистрыСведений>>
{
..Измерения..
УчетнаяЗапись : Справочник.Учетные записи документооборота
..Ресурсы..
Данные : Хранилище значения
..Реквизиты..
ДатаФайла : Дата
Размер : Число 10, 0
}
@enduml
