@startuml ПлановыеАвансы
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПлановыеАвансы as "Плановые авансы" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ГоловнаяОрганизация : Справочник.Организация
..Ресурсы..
СпособРасчетаАванса : Способы расчета аванса
Аванс : Число 15, 2
ДействуетДо : Дата
СпособРасчетаАвансаПоОкончании : Способы расчета аванса
АвансПоОкончании : Число 15, 2
}
@enduml
