@startuml ДатыПоступленияТоваровОрганизаций
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДатыПоступленияТоваровОрганизаций as "Даты поступления товаров организаций" <<РегистрыСведений>>
{
..Измерения..
ВидЗапасов : Справочник.Вид запасов
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Серия : Справочник.Серия номенклатуры
Назначение : Справочник.Назначение
НомерГТД : Справочник.Номер ГТД
..Ресурсы..
ДатаПоступления : Дата
}
@enduml
