@startuml ЗначенияПоказателейНачислений
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗначенияПоказателейНачислений as "Значения показателей начислений" <<РегистрыСведений>>
{
..Измерения..
РегистраторИзмерение : Документ.Сторнирование начислений\rДокумент.Простой сотрудников\rДокумент.Отпуск без сохранения оплаты списком\r...
ИдентификаторСтроки : Число 7, 0
Показатель : Справочник.Показатель
..Ресурсы..
Значение : Число 15, 5
}
@enduml
