@startuml ДанныеОВремениДляРасчетаСреднегоФССИспр
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДанныеОВремениДляРасчетаСреднегоФССИспр as "Данные о времени для расчета среднего (ФСС) (испр)" <<РегистрыСведений>>
{
..Измерения..
РегистраторИзмерение : Документ.Сторнирование начислений\rДокумент.Простой сотрудников\rДокумент.Отпуск без сохранения оплаты списком\r...
ФизическоеЛицо : Справочник.Физическое лицо
ГоловнаяОрганизация : Справочник.Организация
Месяц : Дата
ДокументОснование : Документ.Сторнирование начислений\rДокумент.Простой сотрудников\rДокумент.Отпуск без сохранения оплаты списком\r...
ВидБолезниУходаЗаДетьми : Начисление
..Ресурсы..
ОтработанДень1 : Булево
ОтработанДень2 : Булево
ОтработанДень3 : Булево
ОтработанДень4 : Булево
ОтработанДень5 : Булево
ОтработанДень6 : Булево
ОтработанДень7 : Булево
ОтработанДень8 : Булево
ОтработанДень9 : Булево
ОтработанДень10 : Булево
ОтработанДень11 : Булево
ОтработанДень12 : Булево
ОтработанДень13 : Булево
ОтработанДень14 : Булево
ОтработанДень15 : Булево
ОтработанДень16 : Булево
ОтработанДень17 : Булево
ОтработанДень18 : Булево
ОтработанДень19 : Булево
ОтработанДень20 : Булево
ОтработанДень21 : Булево
ОтработанДень22 : Булево
ОтработанДень23 : Булево
ОтработанДень24 : Булево
ОтработанДень25 : Булево
ОтработанДень26 : Булево
ОтработанДень27 : Булево
ОтработанДень28 : Булево
ОтработанДень29 : Булево
ОтработанДень30 : Булево
ОтработанДень31 : Булево
НеотработанДень1 : Булево
НеотработанДень2 : Булево
НеотработанДень3 : Булево
НеотработанДень4 : Булево
НеотработанДень5 : Булево
НеотработанДень6 : Булево
НеотработанДень7 : Булево
НеотработанДень8 : Булево
НеотработанДень9 : Булево
НеотработанДень10 : Булево
НеотработанДень11 : Булево
НеотработанДень12 : Булево
НеотработанДень13 : Булево
НеотработанДень14 : Булево
НеотработанДень15 : Булево
НеотработанДень16 : Булево
НеотработанДень17 : Булево
НеотработанДень18 : Булево
НеотработанДень19 : Булево
НеотработанДень20 : Булево
НеотработанДень21 : Булево
НеотработанДень22 : Булево
НеотработанДень23 : Булево
НеотработанДень24 : Булево
НеотработанДень25 : Булево
НеотработанДень26 : Булево
НеотработанДень27 : Булево
НеотработанДень28 : Булево
НеотработанДень29 : Булево
НеотработанДень30 : Булево
НеотработанДень31 : Булево
БолезньУходЗаДетьмиДень1 : Булево
БолезньУходЗаДетьмиДень2 : Булево
БолезньУходЗаДетьмиДень3 : Булево
БолезньУходЗаДетьмиДень4 : Булево
БолезньУходЗаДетьмиДень5 : Булево
БолезньУходЗаДетьмиДень6 : Булево
БолезньУходЗаДетьмиДень7 : Булево
БолезньУходЗаДетьмиДень8 : Булево
БолезньУходЗаДетьмиДень9 : Булево
БолезньУходЗаДетьмиДень10 : Булево
БолезньУходЗаДетьмиДень11 : Булево
БолезньУходЗаДетьмиДень12 : Булево
БолезньУходЗаДетьмиДень13 : Булево
БолезньУходЗаДетьмиДень14 : Булево
БолезньУходЗаДетьмиДень15 : Булево
БолезньУходЗаДетьмиДень16 : Булево
БолезньУходЗаДетьмиДень17 : Булево
БолезньУходЗаДетьмиДень18 : Булево
БолезньУходЗаДетьмиДень19 : Булево
БолезньУходЗаДетьмиДень20 : Булево
БолезньУходЗаДетьмиДень21 : Булево
БолезньУходЗаДетьмиДень22 : Булево
БолезньУходЗаДетьмиДень23 : Булево
БолезньУходЗаДетьмиДень24 : Булево
БолезньУходЗаДетьмиДень25 : Булево
БолезньУходЗаДетьмиДень26 : Булево
БолезньУходЗаДетьмиДень27 : Булево
БолезньУходЗаДетьмиДень28 : Булево
БолезньУходЗаДетьмиДень29 : Булево
БолезньУходЗаДетьмиДень30 : Булево
БолезньУходЗаДетьмиДень31 : Булево
}
@enduml
