@startuml ПервоначальныеСведенияОС
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПервоначальныеСведенияОС as "Первоначальные сведения ОС" <<РегистрыСведений>>
{
..Измерения..
ОсновноеСредство : Справочник.Объект эксплуатации
Организация : Справочник.Организация
..Ресурсы..
СпособПоступления : Способы поступления активов
ПорядокУчетаБУ : Порядок погашения стоимости ОС
ПорядокУчетаНУ : Порядок включения стоимости основных средств в состав расходов (НУ)
ПорядокУчетаУУ : Порядок учета стоимости внеоборотных активов
МетодНачисленияАмортизацииБУ : Способы начисления амортизации основных средств
МетодНачисленияАмортизацииНУ : Методы начисления амортизации
СтоимостьДо2002 : Число 15, 2
АмортизацияДо2002 : Число 15, 2
АмортизацияДо2009 : Число 15, 2
ФактическийСрокИспользованияДо2009 : Число 4, 0
ПервоначальнаяСтоимостьБУ : Число 15, 2
ПервоначальнаяСтоимостьНУ : Число 15, 2
ДоговорЛизинга : Справочник.Договор лизинга
ДатаВводаВЭксплуатациюБУ : Дата
ДатаВводаВЭксплуатациюУУ : Дата
ДокументВводаВЭксплуатациюБУ : Документ.Принятие к учету ОС\rДокумент.Поступление арендованных ОС\rДокумент.Ввод остатков внеоборотных активов\r...
ДокументВводаВЭксплуатациюУУ : Документ.Ввод остатков внеоборотных активов\rДокумент.Принятие к учету ОС
ДокументСнятияСУчета : Документ.Списание ОС\rДокумент.Перемещение ОС\rДокумент.Подготовка к передаче ОС\r...
ВариантПримененияЦелевогоФинансирования : Варианты применения целевого финансирования
}
@enduml
