@startuml ВременноПребывающиеПринятыеПоДолгосрочнымДоговорам
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ВременноПребывающиеПринятыеПоДолгосрочнымДоговорам as "Временно пребывающие иностранные граждане, принятые по долгосрочным договорам" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
ГоловнаяОрганизация : Справочник.Организация
..Ресурсы..
ПринятПоДолгосрочномуДоговору : Булево
ДействуетДо : Дата
ПринятПоДолгосрочномуДоговоруПоОкончании : Булево
ДатаРегистрацииИзменений : Дата
}
@enduml
