@startuml ПрименениеРазрешенийНаИспользованиеВнешнихРесурсовОбластейДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПрименениеРазрешенийНаИспользованиеВнешнихРесурсовОбластейДанных as "Применение разрешений на использование внешних ресурсов областей данных" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторПакета : Уникальный идентификатор
..Реквизиты..
Состояние : Строка
Результат : Результаты обработки запросов на использование внешних ресурсов в модели сервиса
}
@enduml
