@startuml ДополнительныеФайлыРегламентированныхОтчетов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДополнительныеФайлыРегламентированныхОтчетов as "Дополнительные файлы регламентированных отчетов" <<РегистрыСведений>>
{
..Измерения..
РегламентированныйОтчет : Документ.Регламентированный отчет
ВидДополнительногоФайла : Строка
..Ресурсы..
СодержимоеФайла : Хранилище значения
..Реквизиты..
ИмяФайла : Строка
Размер : Число 15, 0
ДатаИзмененияФайла : Дата
ДатаДобавления : Дата
}
@enduml
