@startuml СобытияКалендаряБухгалтера
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СобытияКалендаряБухгалтера as "События календаря бухгалтера" <<РегистрыСведений>>
{
..Измерения..
Пользователь : Справочник.Пользователь
ПоследняяДатаДействия : Дата
ИсточникОтчета : Строка
ЗаПериодС : Дата
ЗаПериодПо : Дата
Организация : Справочник.Организация
ТипСообщения : Сообщения для рег отчетов
ДатаПоказа : Дата
..Ресурсы..
ФормаОтчета : Строка
Периодичность : Строка
Название : Строка
Налогоплательщик : Строка
НарастающийИтог : Булево
}
@enduml
