@startuml ОтборыПоЛентамНовостейОбщие
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОтборыПоЛентамНовостейОбщие as "Отборы по лентам новостей, настроенные администратором" <<РегистрыСведений>>
{
..Измерения..
ЛентаНовостей : Справочник.Лента новостей
КатегорияНовостей : Категория новостей
ЗначениеКатегорииНовостей : Булево\rСтрока\rСправочник.Значение категорий новостей\r...
}
@enduml
