@startuml СтавкаКомпенсацииЗаЗадержкуЗарплаты
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтавкаКомпенсацииЗаЗадержкуЗарплаты as "Ставка компенсации за задержку зарплаты" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
Ставка : Число 7, 5
}
@enduml
