@startuml ДействиеСкидокНаценокПоНоменклатуре
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДействиеСкидокНаценокПоНоменклатуре as "Действие скидок (наценок) по номенклатуре" <<РегистрыСведений>>
{
..Измерения..
Источник : Справочник.Условие предоставления скидки (наценки)\rСправочник.Скидки (наценки)
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
..Ресурсы..
Статус : Статусы действия скидок
..Реквизиты..
Комментарий : Строка
Ответственный : Справочник.Внешний пользователь\rСправочник.Пользователь
}
@enduml
