@startuml ПооперационноеРасписание
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПооперационноеРасписание as "Пооперационное расписание" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторОперации : Уникальный идентификатор
Начало : Дата
Окончание : Дата
РабочийЦентр : Строка\rСправочник.Рабочий центр
МаршрутныйЛист : Документ.Маршрутный лист производства
МодельРасписания : Уникальный идентификатор
МодельПланирования : Справочник.Модель пооперационного планирования
ЭтоУдалениеОперации : Булево
ТактПараллельнойЗагрузки : Уникальный идентификатор
..Ресурсы..
ВремяПлан : Число 10, 0
ВремяПерехода : Число 10, 0
Загрузка : Число 15, 3
ЭтоПереналадка : Булево
СтатусВыполнения : Статусы выполнения операций
..Реквизиты..
Подразделение : Справочник.Подразделение
Вспомогательная : Булево
Моделирование : Булево
ДатаИзмененияСтатуса : Дата
Штрихкод : Строка
}
@enduml
