@startuml СтатусыУведомленийОбОтгрузкеМаркированныхТоваровГИСМ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтатусыУведомленийОбОтгрузкеМаркированныхТоваровГИСМ as "Статусы уведомлений об отгрузке маркированных товаров ГИСМ" <<РегистрыСведений>>
{
..Измерения..
Документ : Документ.Возврат товаров поставщику\rДокумент.Реализация товаров и услуг
..Ресурсы..
ТекущееУведомлениеОбОтгрузке : Документ.Уведомление об отгрузке маркированных товаров
Статус : Состояния уведомлений об отгрузке маркированных товаров ГИСМ
ДальнейшееДействие : Дальнейшие действия по взаимодействию ГИСМ
ПроцентПодтвержденныхКиЗ : Число 3, 0
}
@enduml
