@startuml СтатусыСинхронизацииФайловСОблачнымСервисом
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтатусыСинхронизацииФайловСОблачнымСервисом as "Статусы синхронизации файлов с облачным сервисом" <<РегистрыСведений>>
{
..Измерения..
Файл : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
УчетнаяЗапись : Справочник.Учетная запись синхронизации файлов
..Ресурсы..
Href : Строка
Etag : Строка
УникальныйИдентификатор1С : Уникальный идентификатор
ЭтоФайл : Булево
ЭтоВладелецФайла : Булево
ВладелецФайла : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
Синхронизирован : Булево
ДатаСинхронизацииНачало : Дата
ДатаСинхронизацииЗавершение : Дата
НомерСеанса : Число 25, 0
}
@enduml
