@startuml ВзаимозависимыеЛица
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ВзаимозависимыеЛица as "Взаимозависимые лица" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Контрагент : Справочник.Организация\rСправочник.Контрагент
..Ресурсы..
ТипВзаимозависимости : Типы взаимозависимости
}
@enduml
