@startuml СтроковыеСведенияФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтроковыеСведенияФизическихЛиц as "Строковые сведения физических лиц" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Контрагент\rСправочник.Физическое лицо
..Ресурсы..
Документы : Строка
ЗнаниеЯзыков : Строка
Награды : Строка
Образование : Строка
ПовышениеКвалификации : Строка
Переподготовка : Строка
Профессии : Строка
СоставСемьи : Строка
Специальности : Строка
ТрудоваяДеятельность : Строка
}
@enduml
