@startuml НастройкиОбменаРПН
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиОбменаРПН as "Настройки обмена с РПН" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
ИспользоватьОбмен : Булево
СертификатАбонентаОтпечаток : Строка
СертификатРПНОтпечаток : Строка
ИспользоватьАвтонастройку : Булево
EMail : Строка
Пароль : Строка
ОбменНапрямую : Булево
}
@enduml
