@startuml ОтветыНаВопросыАнкет
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОтветыНаВопросыАнкет as "Ответы на вопросы анкет" <<РегистрыСведений>>
{
..Измерения..
Анкета : Документ.Анкета
Вопрос : Справочник.Вопрос шаблона анкеты
ЭлементарныйВопрос : Вопрос для анкетирования
НомерЯчейки : Число 10, 0
..Ресурсы..
Ответ : Булево\rСтрока\rДата\r...
..Реквизиты..
ОткрытыйОтвет : Строка
}
@enduml
