@startuml ОтправленныеОповещенияПоБюджетнымЗадачам
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОтправленныеОповещенияПоБюджетнымЗадачам as "Отправленные оповещения по бюджетным задачам" <<РегистрыСведений>>
{
..Измерения..
БюджетнаяЗадача : Бюджетная задача
ВидОповещения : Виды оповещений бюджетных задач
..Реквизиты..
ВидОтправленногоОповещения : Виды оповещений бюджетных задач
}
@enduml
