@startuml ЖурналОтправокВКонтролирующиеОрганы
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЖурналОтправокВКонтролирующиеОрганы as "Журнал отправок в контролирующие органы" <<РегистрыСведений>>
{
..Измерения..
СтраницаЖурнала : Страницы журнала отчетность
Организация : Справочник.Организация\rСтрока
Ссылка : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
..Ресурсы..
СтатусОтправки : Строка
..Реквизиты..
ПометкаУдаления : Булево
Наименование : Строка
ПредставлениеПериода : Строка
ВидКонтролирующегоОргана : Типы контролирующих органов\rСтрока
КодКонтролирующегоОргана : Строка
ПредставлениеКонтролирующегоОргана : Строка
ЕстьОтвет : Булево
СостояниеСдачиОтчетности : Состояние сдачи отчетности
ДатаСоздания : Дата
НеОтправляетсяВКонтролирующийОрган : Булево
ЕстьКритическиеОшибкиОтправки : Булево
Непрочтенное : Булево
Скрыт : Булево
ЕстьПриcоединенныйФайл : Булево
}
@enduml
