@startuml СтавкиНалогаНаПрибыльДляВсехОрганизаций
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтавкиНалогаНаПрибыльДляВсехОрганизаций as "Ставки налога на прибыль" <<РегистрыСведений>>
{
..Ресурсы..
СтавкаФБ : Число 5, 2
СтавкаСубъектРФ : Число 5, 2
}
@enduml
