@startuml ГрафикРаботыСотрудниковИспр
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ГрафикРаботыСотрудниковИспр as "График работы сотрудников испр" <<РегистрыСведений>>
{
..Измерения..
РегистраторИзмерение : Документ.Кадровый перевод\rДокумент.Изменение графика работы списком\rДокумент.Начальная штатная расстановка\r...
ПериодИзмерение : Дата
Сотрудник : Справочник.Сотрудник
ГоловнаяОрганизация : Справочник.Организация
..Ресурсы..
ГрафикРаботы : Справочник.График работы
ДействуетДо : Дата
УдалитьГрафикРаботыПоОкончании : Справочник.График работы
}
@enduml
