@startuml ПакетыАмортизацииОС
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПакетыАмортизацииОС as "Пакеты амортизации ОС" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ОсновноеСредство : Справочник.Объект эксплуатации
..Ресурсы..
НомерПакета : Число 10, 0
}
@enduml
