@startuml СостоянияЗаказовКлиентов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияЗаказовКлиентов as "Состояния заказов клиентов" <<РегистрыСведений>>
{
..Измерения..
Заказ : Документ.Заявка на возврат товаров от клиента\rДокумент.Заказ клиента\rДокумент.Заказ давальца
..Ресурсы..
Состояние : Состояния заказов клиентов\rСостояния заявок на возврат товаров от клиентов
ДатаСобытия : Дата
..Реквизиты..
СуммаОплаты : Число 15, 2
ПроцентОплаты : Число 3, 0
СуммаОтгрузки : Число 15, 2
ПроцентОтгрузки : Число 3, 0
СуммаДолга : Число 15, 2
ПроцентДолга : Число 3, 0
ЕстьРасхожденияОрдерНакладная : Булево
}
@enduml
