@startuml БлокировкиСкладскихЯчеек
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.БлокировкиСкладскихЯчеек as "Блокировки складских ячеек" <<РегистрыСведений>>
{
..Измерения..
Ячейка : Справочник.Складская ячейка
..Ресурсы..
ТипБлокировки : Типы блокировок складских ячеек
}
@enduml
