@startuml СессииОбменаСообщениямиСистемы
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СессииОбменаСообщениямиСистемы as "Сессии обмена сообщениями системы" <<РегистрыСведений>>
{
..Измерения..
Сессия : Уникальный идентификатор
..Ресурсы..
ДатаНачала : Дата
ЗавершенаУспешно : Булево
ЗавершенаСОшибкой : Булево
Данные : Хранилище значения
}
@enduml
