@startuml СчетчикВыгрузокОтчетностиВБанк
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СчетчикВыгрузокОтчетностиВБанк as "Счетчик выгрузок отчетности в банк" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация\rСтрока
День : Дата
..Ресурсы..
Значение : Число 8, 0
}
@enduml
