@startuml ПримененияЕНВД
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПримененияЕНВД as "Применения ЕНВД" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Склад : Справочник.Склад (складская территория)
..Ресурсы..
РозничнаяТорговляОблагаетсяЕНВД : Булево
}
@enduml
