@startuml Удалить_АктивныеПредметыВзаимодействий
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.Удалить_АктивныеПредметыВзаимодействий as "(не используется) Активные предметы взаимодействий" <<РегистрыСведений>>
{
..Измерения..
Предмет : Справочник.Маркетинговое мероприятие\rСправочник.Претензия клиента\rСправочник.Сделка с клиентом\r...
}
@enduml
