@startuml СостоянияПересчетовЯчеек
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияПересчетовЯчеек as "Состояния пересчетов ячеек" <<РегистрыСведений>>
{
..Измерения..
Ячейка : Справочник.Складская ячейка
..Ресурсы..
Состояние : Состояния пересчетов ячеек
ДатаПоследнегоПересчета : Дата
}
@enduml
