@startuml НастройкиСтатистикиПерсонала
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиСтатистикиПерсонала as "Настройки статистики персонала" <<РегистрыСведений>>
{
..Ресурсы..
ИспользоватьОтчетностьМониторингаРаботниковСоциальнойСферы : Булево
ФормаОтчетностиМониторингаРаботниковСоциальнойСферы : Виды форм мониторинга работников социальной сферы
}
@enduml
