@startuml ХозяйственныеОперацииНеОтражаемыеВМеждународномУчете
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ХозяйственныеОперацииНеОтражаемыеВМеждународномУчете as "Хозяйственные операции, не отражаемые в международном учете" <<РегистрыСведений>>
{
..Измерения..
УчетнаяПолитика : Справочник.Учетная политика
Операция : Справочник.Хозяйственная операция
}
@enduml
