@startuml ПорядокОтраженияПрочихОпераций
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПорядокОтраженияПрочихОпераций as "Порядок отражения прочих операций" <<РегистрыСведений>>
{
..Измерения..
Документ : Документ.Внутреннее потребление товаров\rДокумент.Подготовка к передаче НМА\rДокумент.Списание ОС\r...
ИдентификаторСтроки : Строка
..Ресурсы..
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Организация : Справочник.Организация
Дата : Дата
}
@enduml
