@startuml ЗагруженныеВерсииАдресныхСведений
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗагруженныеВерсииАдресныхСведений as "Загруженные версии адресных сведений" <<РегистрыСведений>>
{
..Измерения..
КодСубъектаРФ : Число 2, 0
..Ресурсы..
Версия : Строка
ДатаВерсии : Дата
ДатаЗагрузки : Дата
}
@enduml
