@startuml УдалитьСтраныМира
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьСтраныМира as "(не используется) Страны мира" <<РегистрыСведений>>
{
..Измерения..
ОбластьДанных : Число 10, 0
..Ресурсы..
Значение : Хранилище значения
}
@enduml
