@startuml НастройкиИспользованияСтраховыхВзносовПоКлассамУсловийТруда
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиИспользованияСтраховыхВзносовПоКлассамУсловийТруда as "Настройки использования страховых взносов по классам условий труда" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
ИспользоватьПФРЗаЗанятыхНаПодземныхИВредныхРаботахОпасный : Булево
ИспользоватьПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный1 : Булево
ИспользоватьПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный2 : Булево
ИспользоватьПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный3 : Булево
ИспользоватьПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный4 : Булево
ИспользоватьПФРЗаЗанятыхНаТяжелыхИПрочихРаботахОпасный : Булево
ИспользоватьПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный1 : Булево
ИспользоватьПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный2 : Булево
ИспользоватьПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный3 : Булево
ИспользоватьПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный4 : Булево
}
@enduml
