@startuml БухучетПлановыхНачислений
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.БухучетПлановыхНачислений as "Бухучет плановых начислений" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
Организация : Справочник.Организация
Начисление : Виды особых начислений и удержаний\rНачисление\rСтрока
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
..Ресурсы..
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
ОтношениеКЕНВД : Отношение к ЕНВД затрат на зарплату
Используется : Булево
ДействуетДо : Дата
..Реквизиты..
УдалитьДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
}
@enduml
