@startuml РегламентныеЗаданияЗакрытияМесяца
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РегламентныеЗаданияЗакрытияМесяца as "Регламентные задания закрытия месяца" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
РегламентноеЗадание : Уникальный идентификатор
ЗакрываемыйПериодОУ : Дата
ЗакрываемыйПериодРУ : Дата
ЗакрываемыйПериодМУ : Дата
Использование : Булево
}
@enduml
