@startuml ОперацииСтатистики
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОперацииСтатистики as "Операции статистики" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторОперации : Уникальный идентификатор
ХешНаименования : Строка
..Ресурсы..
Наименование : Строка
..Реквизиты..
КоличествоУникальныхКомментариев : Число 5, 0
}
@enduml
