@startuml КомментарииСтатистики
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КомментарииСтатистики as "Комментарии статистики" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторКомментария : Уникальный идентификатор
ХешНаименования : Строка
..Ресурсы..
Наименование : Строка
}
@enduml
