@startuml ПланРемонтов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПланРемонтов as "План ремонтов" <<РегистрыСведений>>
{
..Измерения..
ОбъектЭксплуатации : Справочник.Объект эксплуатации\rСправочник.Узел объекта эксплуатации
ВидРемонта : Справочник.Вид ремонта
..Реквизиты..
РемонтныйЦикл : Булево
}
@enduml
