@startuml ПолучателиУдержаний
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПолучателиУдержаний as "Получатели удержаний" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
Удержание : Удержание
ДокументОснование : Документ.Удержание по прочим операциям\rДокумент.Удержание добровольных взносов в НПФ\rДокумент.Удержание профсоюзных взносов\r...
..Ресурсы..
Контрагент : Справочник.Контрагент
}
@enduml
