@startuml ПараметрыИсчисленияПроцентаСевернойНадбавкиФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПараметрыИсчисленияПроцентаСевернойНадбавкиФизическихЛиц as "Параметры исчисления процента северной надбавки физических лиц" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
УдалитьПроцентСевернойНадбавки : Число 5, 2
ПроцентСевернойНадбавкиИзменяется : Булево
ПорядокИсчисленияПроцентаСевернойНадбавки : Порядок начисления северных надбавок
}
@enduml
