@startuml ПараметрыЦелевогоФинансированияОС
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПараметрыЦелевогоФинансированияОС as "Параметры целевого финансирования ОС" <<РегистрыСведений>>
{
..Измерения..
ОсновноеСредство : Справочник.Объект эксплуатации
..Ресурсы..
ПрименениеЦелевогоФинансирования : Булево
СчетУчета : Счет бухгалтерского учета
СчетАмортизации : Счет бухгалтерского учета
СтатьяДоходов : Статьи доходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
}
@enduml
