@startuml РезервныеКопииОблачногоАрхива
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РезервныеКопииОблачногоАрхива as "Резервные копии облачного архива" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторИБ : Строка
ДатаСоздания : Дата
ИдентификаторФайла : Строка
..Реквизиты..
РазмерФайла : Число 15, 0
ИмяИБ : Строка
}
@enduml
