@startuml СостоянияСогласованияВДокументообороте
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияСогласованияВДокументообороте as "Состояния согласования в 1С:Документообороте" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторОбъектаДокументооборота : Строка
..Ресурсы..
Состояние : Состояния согласования в 1С:Документообороте
..Реквизиты..
Установил : Строка
ДатаУстановки : Дата
}
@enduml
