@startuml ПроцессыДляЗапуска
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПроцессыДляЗапуска as "Процессы для запуска" <<РегистрыСведений>>
{
..Измерения..
БизнесПроцесс : Задание
..Ресурсы..
ДатаОтложенногоСтарта : Дата
Состояние : Состояния процессов для запуска
..Реквизиты..
ПричинаОтменыСтарта : Строка
}
@enduml
