@startuml ПорядокРасчетаСтоимостиЕдиницыВремениСотрудниковИспр
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПорядокРасчетаСтоимостиЕдиницыВремениСотрудниковИспр as "Порядок расчета стоимости единицы времени сотрудников испр" <<РегистрыСведений>>
{
..Измерения..
РегистраторИзмерение : Документ.Изменение условий оплаты отпуска по уходу за ребенком\rДокумент.Изменение оплаты труда\rДокумент.Кадровый перевод\r...
ПериодИзмерение : Дата
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
ПорядокРасчета : Порядок расчета стоимости часа (дня) оплаты труда сотрудников
ДействуетДо : Дата
ПорядокРасчетаПоОкончании : Порядок расчета стоимости часа (дня) оплаты труда сотрудников
}
@enduml
