@startuml СведенияТаможенныхДекларацийЭкспорт
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СведенияТаможенныхДекларацийЭкспорт as "Сведения таможенных деклараций на экспорт" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ДокументОтгрузки : Документ.Реализация товаров и услуг
КодТС : Строка
ВидДокумента : Строка
НомерТСД : Строка
ДатаТСД : Дата
..Ресурсы..
НомерТаможеннойДекларации : Строка
КодОперации : Строка
Примечание : Строка
}
@enduml
