@startuml ОбластиСтатистики
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОбластиСтатистики as "Области статистики" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторОбласти : Уникальный идентификатор
ХешНаименования : Строка
СобиратьСтатистикуКонфигурации : Булево
..Ресурсы..
Наименование : Строка
}
@enduml
