@startuml СхемыОбеспеченияПроизводства
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СхемыОбеспеченияПроизводства as "Схемы обеспечения производства" <<РегистрыСведений>>
{
..Измерения..
СхемаОбеспечения : Справочник.Схема обеспечения
Подразделение : Справочник.Подразделение
..Ресурсы..
Склад : Справочник.Склад (складская территория)
}
@enduml
