@startuml ДвоичныеДанныеФайлов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДвоичныеДанныеФайлов as "Двоичные данные файлов" <<РегистрыСведений>>
{
..Измерения..
Файл : Справочник.Присоединенный файл (Отчет комиссионера)\rСправочник.Присоединенные файлы (Поступление безналичных денежных средств)\rСправочник.Присоединенный файл (Сообщение обмена с банками)\r...
..Ресурсы..
ДвоичныеДанныеФайла : Хранилище значения
}
@enduml
