@startuml СостоянияУспешныхОбменовДаннымиОбластейДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияУспешныхОбменовДаннымиОбластейДанных as "Состояния успешных обменов данными областей данных" <<РегистрыСведений>>
{
..Измерения..
УзелИнформационнойБазы : Синхронизация данных через универсальный формат\rОбмен с подключаемым оборудованием Offline\rОбрабатываемый объект\r...
ДействиеПриОбмене : Действия при обмене
..Ресурсы..
ДатаОкончания : Дата
}
@enduml
