@startuml УдалитьОбразованиеФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьОбразованиеФизическихЛиц as "(Не используется) Образование физических лиц" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
НомерПоПорядку : Число 2, 0
..Ресурсы..
ВидОбразования : Справочник.Вид образования
ВидПослевузовскогоОбразования : Справочник.Вид образования
УчебноеЗаведение : Справочник.Учебное заведение
Специальность : Справочник.Специальность
Диплом : Строка
ГодОкончания : Число 4, 0
Квалификация : Строка
}
@enduml
