@startuml УдалитьСтатусыЗастрахованныхФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьСтатусыЗастрахованныхФизическихЛиц as "(не используется) Статусы застрахованных физических лиц" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
ВидЗастрахованногоЛица : Виды застрахованных лиц обязательного страхования
}
@enduml
