@startuml СуммыДокументовВВалютеРегл
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СуммыДокументовВВалютеРегл as "Суммы документов в валюте регл. учета" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторСтроки : Строка
..Ресурсы..
СуммаБезНДС : Число 15, 2
СуммаНДС : Число 15, 2
СуммаБезНДСРегл : Число 15, 2
БазаНДСРегл : Число 15, 2
СуммаНДСРегл : Число 15, 2
СуммаБезНДСУпр : Число 15, 2
СуммаНДСУпр : Число 15, 2
БазаНДСУпр : Число 15, 2
..Реквизиты..
Валюта : Справочник.Валюта
СтавкаНДС : Ставки НДС
ТипРасчетов : Типы расчетов с партнерами
АналитикаУчетаПоПартнерам : Справочник.Ключ аналитики учета по партнерам
}
@enduml
