@startuml УведомленияОПрочтении
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УведомленияОПрочтении as "Уведомления о прочтении" <<РегистрыСведений>>
{
..Измерения..
Письмо : Документ.Входящее электронное письмо
..Ресурсы..
ТребуетсяОтправка : Булево
ДатаПрочтения : Строка
..Реквизиты..
Пользователь : Справочник.Пользователь
}
@enduml
