@startuml НомераОтсканированныхФайлов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НомераОтсканированныхФайлов as "Номера отсканированных файлов" <<РегистрыСведений>>
{
..Измерения..
Владелец : Документ.Внутреннее потребление товаров\rДокумент.Акт о расхождениях после перемещения\rДокумент.Подтверждение открытия счетов\r...
..Ресурсы..
Номер : Число 9, 0
}
@enduml
