@startuml РейтингАктивностиОбластейДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РейтингАктивностиОбластейДанных as "Рейтинг активности областей данных" <<РегистрыСведений>>
{
..Ресурсы..
Рейтинг : Число 7, 0
}
@enduml
