@startuml УдалитьОбластиКРезервномуКопированию
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьОбластиКРезервномуКопированию as "(не используется) Области к резервному копированию" <<РегистрыСведений>>
{
..Измерения..
ОбластьДанных : Число 7, 0
}
@enduml
