@startuml РолиФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РолиФизическихЛиц as "Роли физических лиц" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
Организация : Справочник.Организация
Роль : Роли физических лиц
ИдентификаторЗаписи : Уникальный идентификатор
}
@enduml
