@startuml ПараметрыЗарегистрированныхДанныхУчетаВремениСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПараметрыЗарегистрированныхДанныхУчетаВремениСотрудников as "Параметры зарегистрированных данных учета времени сотрудников" <<РегистрыСведений>>
{
..Измерения..
Месяц : Дата
Сотрудник : Справочник.Сотрудник
ПериодРегистрации : Дата
ВидДанных : Виды данных учета времени сотрудников
ДокументОснование : Документ.Данные для расчета зарплаты\rДокумент.Индивидуальный график\rДокумент.Работа сверхурочно\r...
ТипИсточникаДанных : Справочник.Идентификатор объекта метаданных
..Ресурсы..
УстановленДень1 : Число 1, 0
УстановленДень2 : Число 1, 0
УстановленДень3 : Число 1, 0
УстановленДень4 : Число 1, 0
УстановленДень5 : Число 1, 0
УстановленДень6 : Число 1, 0
УстановленДень7 : Число 1, 0
УстановленДень8 : Число 1, 0
УстановленДень9 : Число 1, 0
УстановленДень10 : Число 1, 0
УстановленДень11 : Число 1, 0
УстановленДень12 : Число 1, 0
УстановленДень13 : Число 1, 0
УстановленДень14 : Число 1, 0
УстановленДень15 : Число 1, 0
УстановленДень16 : Число 1, 0
УстановленДень17 : Число 1, 0
УстановленДень18 : Число 1, 0
УстановленДень19 : Число 1, 0
УстановленДень20 : Число 1, 0
УстановленДень21 : Число 1, 0
УстановленДень22 : Число 1, 0
УстановленДень23 : Число 1, 0
УстановленДень24 : Число 1, 0
УстановленДень25 : Число 1, 0
УстановленДень26 : Число 1, 0
УстановленДень27 : Число 1, 0
УстановленДень28 : Число 1, 0
УстановленДень29 : Число 1, 0
УстановленДень30 : Число 1, 0
УстановленДень31 : Число 1, 0
ПорядокФормированияИндивидуальныхСведений : Порядок формирования индивидуальных сведений учета времени
}
@enduml
