@startuml НастройкиАвторизацииВ1СДокументообороте
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиАвторизацииВ1СДокументообороте as "Настройки авторизации в 1С;Документообороте" <<РегистрыСведений>>
{
..Измерения..
Пользователь : Справочник.Пользователь
ПарольСохранен : Булево
ХешИмениКомпьютера : Число 10, 0
..Ресурсы..
ИмяПользователя : Строка
ЧастьПароляВИнформационнойБазе : Строка
ВременныйФайлЧастиПароля : Строка
ИспользуетсяАутентификацияОС : Булево
}
@enduml
