@startuml ЗначенияНефинансовыхПоказателей
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗначенияНефинансовыхПоказателей as "Значения нефинансовых показателей" <<РегистрыСведений>>
{
..Измерения..
НефинансовыйПоказатель : Справочник.Нефинансовые показатели бюджетов
Сценарий : Справочник.Сценарии бюджетирования
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Аналитика1 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика2 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика3 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика4 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика5 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика6 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
НомерПодПериода : Число 3, 0
..Ресурсы..
ЗначениеПоказателя : Число 20, 6
Валюта : Справочник.Валюта
ДатаОкончания : Дата
}
@enduml
