@startuml ПлатежныеДокументыПеречисленияЗарплаты
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПлатежныеДокументыПеречисленияЗарплаты as "Платежные документы перечисления зарплаты" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Ведомость : Документ.Ведомость в банк\rДокумент.Ведомость прочих доходов в банк
ПлатежныйДокумент : Документ.Списание безналичных ДС\rДокумент.Заявка на расходование ДС
}
@enduml
