@startuml УдалитьИсторияИспользованияПодразделений
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьИсторияИспользованияПодразделений as "(не используется) История использования подразделений" <<РегистрыСведений>>
{
..Измерения..
Подразделение : Справочник.Подразделение
..Ресурсы..
Используется : Булево
}
@enduml
