@startuml РежимыПодключенияВнешнихМодулейОбластейДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РежимыПодключенияВнешнихМодулейОбластейДанных as "Режимы подключения внешних модулей областей данных" <<РегистрыСведений>>
{
..Измерения..
ТипПрограммногоМодуля : Справочник.Идентификатор объекта метаданных расширения\rСправочник.Идентификатор объекта метаданных
ИдентификаторПрограммногоМодуля : Уникальный идентификатор
..Ресурсы..
БезопасныйРежим : Булево\rСтрока
..Реквизиты..
ПредставлениеПрограммногоМодуля : Строка
}
@enduml
