@startuml НепринятыеКОбработкеПочтовымСерверомИсходящиеПисьма
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НепринятыеКОбработкеПочтовымСерверомИсходящиеПисьма as "Непринятые к обработке почтовым сервером исходящие письма" <<РегистрыСведений>>
{
..Измерения..
Письмо : Документ.Исходящее электронное письмо
..Ресурсы..
КоличествоПопыток : Число 1, 0
..Реквизиты..
ИнформацияООшибке : Строка
}
@enduml
