@startuml ВложенияНеформализованныхДокументов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ВложенияНеформализованныхДокументов as "Вложения неформализованных документов" <<РегистрыСведений>>
{
..Измерения..
НеформализованныйДокумент : Справочник.Переписка с контролирующими органами
ИмяФайла : Строка
..Ресурсы..
Данные : Хранилище значения
..Реквизиты..
Тип : Типы вложений неформализованных документов налогоплательщика
Размер : Число 10, 0
}
@enduml
