@startuml СтандартныеВычетыПоНДФЛВторичный
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтандартныеВычетыПоНДФЛВторичный as "Стандартные вычеты по НДФЛВторичный" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
ПериодРегистрацииНачало : Дата
ПериодРегистрацииОкончание : Дата
ДатаНачала : Дата
ДатаОкончания : Дата
КодВычета : Справочник.Вид вычетов НДФЛ
ЛичныйВычет : Булево
..Ресурсы..
Количество : Число 2, 0
..Реквизиты..
Основание : Строка
}
@enduml
