@startuml ИнцидентыОграничениеСкоростиОтсылки
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИнцидентыОграничениеСкоростиОтсылки as "Ограничение скорости отсылки инцидентов" <<РегистрыСведений>>
{
..Измерения..
ТипИнцидента : Строка
..Ресурсы..
ПоследняяОтсылка : Дата
}
@enduml
