@startuml ШаблоныЭВФОтчетовСтатистики
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ШаблоныЭВФОтчетовСтатистики as "Шаблоны ЭВФ отчетов статистики" <<РегистрыСведений>>
{
..Измерения..
ИмяФайлаШаблона : Строка
..Ресурсы..
Шаблон : Хранилище значения
ОКУД : Строка
КодШаблона : Строка
Наименование : Строка
КодПериодичности : Число 3, 0
КодФормы : Число 3, 0
Шифр : Строка
Версия : Строка
..Реквизиты..
ДатаДобавления : Дата
Размер : Число 15, 0
}
@enduml
