@startuml УдалитьСтраховыеВзносыСкидкиКДоходам
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьСтраховыеВзносыСкидкиКДоходам as "(не используется) Скидки к доходам при исчислении страховых взносов" <<РегистрыСведений>>
{
..Измерения..
ВидДохода : Справочник.(не используется) Виды доходов (взносы)
..Ресурсы..
ГодоваяСкидка : Число 15, 2
НормативЗатрат : Число 15, 2
}
@enduml
