@startuml ВыполнениеПроверокСостоянияСистемы
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ВыполнениеПроверокСостоянияСистемы as "Выполнение проверок состояния учета" <<РегистрыСведений>>
{
..Измерения..
Проверка : Справочник.Проверка
Организация : Справочник.Организация
ПроверяемыйПериод : Дата
..Ресурсы..
ДатаВыполнения : Дата
ВыявленыПроблемы : Булево
ПричинаОтказаОтПроверки : Строка
}
@enduml
