@startuml НастройкиЛьготСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиЛьготСотрудников as "Настройки льгот сотрудников" <<РегистрыСведений>>
{
..Ресурсы..
ИспользоватьЛьготыСотрудников : Булево
ИспользоватьИндивидуальныеЛьготыСотрудников : Булево
}
@enduml
