@startuml УдалитьИсторияНачисленийПоШтатномуРасписанию
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьИсторияНачисленийПоШтатномуРасписанию as "(не используется) История начислений по штатному расписанию" <<РегистрыСведений>>
{
..Измерения..
Дата : Дата
ПозицияШтатногоРасписания : Справочник.Позиция
Начисление : Начисление
Показатель : Справочник.Показатель
..Ресурсы..
Значение : Число 15, 3
ЗначениеМин : Число 15, 3
ЗначениеМакс : Число 15, 3
..Реквизиты..
Размер : Число 15, 2
РазмерМин : Число 15, 2
РазмерМакс : Число 15, 2
}
@enduml
