@startuml СкрытыеРегламентированныеОтчеты
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СкрытыеРегламентированныеОтчеты as "Скрытые регламентированные отчеты" <<РегистрыСведений>>
{
..Измерения..
РегламентированныйОтчет : Справочник.Регламентированные отчеты
УдалитьРегламентированныйОтчет : Справочник.(не используется) Регламентированные отчеты
}
@enduml
