@startuml ПакетыОтчетности
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПакетыОтчетности as "Пакеты отчетности" <<РегистрыСведений>>
{
..Измерения..
ОтправкаОтчетности : Справочник.Отправки отчетности
ИмяФайла : Строка
..Ресурсы..
Данные : Хранилище значения
}
@enduml
