@startuml СостоянияСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияСотрудников as "Состояния сотрудников" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
Год : Дата
..Ресурсы..
Состояние : Состояния сотрудника
ВидВремени : Справочник.Вид рабочего времени
ДействуетДо : Дата
ОкончаниеПредположительно : Дата
}
@enduml
