@startuml ГражданствоФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ГражданствоФизическихЛиц as "Гражданство физических лиц" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
Страна : Справочник.Страна мира
ИНН : Строка
УдалитьИмеетПравоНаПенсиюИПособияПоСоцстраху : Булево
УдалитьВидЗастрахованногоЛица : Виды застрахованных лиц обязательного страхования
}
@enduml
