@startuml СостоянияПапокПисем
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияПапокПисем as "Состояния папок писем" <<РегистрыСведений>>
{
..Измерения..
Папка : Справочник.Папка электронных писем
..Ресурсы..
КоличествоНеРассмотрено : Число 10, 0
}
@enduml
