@startuml ПакетыДляОтправки
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПакетыДляОтправки as "Пакеты для отправки" <<РегистрыСведений>>
{
..Измерения..
НомерПакета : Число 11, 0
..Реквизиты..
ТелоПакета : Строка
ХешПакета : Строка
}
@enduml
