@startuml УдалитьПараметрыИнтернетПоддержкиПользователей
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьПараметрыИнтернетПоддержкиПользователей as "(не используется) Параметры Интернет-поддержки пользователей" <<РегистрыСведений>>
{
..Измерения..
Имя : Строка
Пользователь : Уникальный идентификатор
..Ресурсы..
Значение : Строка
..Реквизиты..
ОбластьВидимости : Строка
}
@enduml
