@startuml КэшДанныхПартионногоУчета
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КэшДанныхПартионногоУчета as "Кэш данных партионного учета" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторРасчета : Уникальный идентификатор
ТипДанных : Типы данных кэша партионного учета
НомерПорцииДанных : Число 10, 0
..Реквизиты..
Данные : Хранилище значения
МинимальныйНомерУзла : Число 15, 0
МаксимальныйНомерУзла : Число 15, 0
}
@enduml
