@startuml ВариантыОбеспеченияТоварами
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ВариантыОбеспеченияТоварами as "Варианты обеспечения товарами" <<РегистрыСведений>>
{
..Измерения..
Склад : Справочник.Склад (складская территория)
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
СпособОбеспеченияПотребностей : Справочник.Способ обеспечения потребностей
..Реквизиты..
РеквизитДопУпорядочивания : Число 5, 0
}
@enduml
