@startuml ДатыЗапретаФормированияПроводокМеждународныйУчет
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДатыЗапретаФормированияПроводокМеждународныйУчет as "Даты запрета формирования проводок по международному учету" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
ДатаЗапрета : Дата
}
@enduml
