@startuml КорзинаПокупателя
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КорзинаПокупателя as "Корзина покупателя" <<РегистрыСведений>>
{
..Измерения..
ОбъектАвторизации : Справочник.Партнер\rСправочник.Контактное лицо
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
НоменклатураНабора : Справочник.Номенклатура
ХарактеристикаНабора : Справочник.Характеристика номенклатуры
..Ресурсы..
КоличествоУпаковок : Число 15, 3
Цена : Число 15, 2
..Реквизиты..
ДатаПомещения : Дата
Валюта : Справочник.Валюта
КОформлению : Булево
}
@enduml
