@startuml ПоказателиСовокупнойТарифнойСтавкиСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПоказателиСовокупнойТарифнойСтавкиСотрудников as "Показатели совокупной тарифной ставки сотрудников" <<РегистрыСведений>>
{
..Измерения..
Показатель : Справочник.Показатель
}
@enduml
