@startuml НаличиеФайлов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НаличиеФайлов as "Наличие файлов" <<РегистрыСведений>>
{
..Измерения..
ОбъектСФайлами : Документ.Внутреннее потребление товаров\rДокумент.Акт о расхождениях после перемещения\rДокумент.Подтверждение открытия счетов\r...
..Ресурсы..
ЕстьФайлы : Булево
..Реквизиты..
ИдентификаторОбъекта : Строка
}
@enduml
