@startuml ОсновныеСпецификации
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОсновныеСпецификации as "Основные спецификации" <<РегистрыСведений>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Подразделение : Справочник.Подразделение
..Ресурсы..
МодельФормированияСтоимости : Типы моделей формирования стоимости
ПравилоРаспределения : Справочник.Правило распределения расходов
Спецификация : Справочник.Ресурсная спецификация
ОтражатьЗатратыДокументом : Булево
..Реквизиты..
ПолноеНаименованиеМодели : Строка
ТребуетсяНастройка : Булево
}
@enduml
