@startuml ШтрихкодыНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ШтрихкодыНоменклатуры as "Штрихкоды номенклатуры" <<РегистрыСведений>>
{
..Измерения..
Штрихкод : Строка
..Ресурсы..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
}
@enduml
