@startuml МестонахождениеОСБухгалтерскийУчет
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.МестонахождениеОСБухгалтерскийУчет as "Местонахождение ОС (бухгалтерский учет, версия 2.2)" <<РегистрыСведений>>
{
..Измерения..
ОсновноеСредство : Справочник.Объект эксплуатации
Организация : Справочник.Организация
..Ресурсы..
МОЛ : Справочник.Физическое лицо
Местонахождение : Справочник.Подразделение
АдресМестонахождения : Строка
}
@enduml
