@startuml УдалитьРегистрацияЗемельныхУчастков
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьРегистрацияЗемельныхУчастков as "(не используется) Регистрация земельных участков" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ОсновноеСредство : Справочник.Объект эксплуатации
..Ресурсы..
ВключатьВНалоговуюБазу : Булево
КодКатегорииЗемель : Строка
КадастровыйНомер : Строка
КадастроваяСтоимость : Число 15, 2
ОбщаяСобственность : Булево
ДоляВПравеОбщейСобственностиЧислитель : Число 10, 0
ДоляВПравеОбщейСобственностиЗнаменатель : Число 10, 0
ЖилищноеСтроительство : Булево
ДатаНачалаПроектирования : Дата
ДатаРегистрацииПравНаОбъектНедвижимости : Дата
ПостановкаНаУчетВНалоговомОргане : Постановка на учет в налоговом органе
НалоговыйОрган : Справочник.Регистрация в налоговом органе
КодПоОКТМО : Строка
КодПоОКАТО : Строка
КБК : Строка
НалоговаяСтавка : Число 5, 4
НалоговаяЛьготаПоНалоговойБазе : Вид налоговой льготы по налоговой базе по земельному налогу
КодНалоговойЛьготыОсвобождениеОтНалогообложенияПоСтатье395 : Строка
КодНалоговойЛьготыУменьшениеНалоговойБазыПоСтатье391 : Строка
УменьшениеНалоговойБазыПоСтатье391 : Булево
УменьшениеНалоговойБазыНаСумму : Булево
ДоляНеОблагаемойНалогомПлощадиЧислитель : Число 10, 0
ДоляНеОблагаемойНалогомПлощадиЗнаменатель : Число 10, 0
НеОблагаемаяНалогомСумма : Число 15, 2
СниженнаяНалоговаяСтавка : Число 5, 4
ПроцентУменьшенияСуммыНалога : Число 7, 4
СуммаУменьшенияСуммыНалога : Число 15, 2
..Реквизиты..
ВидЗаписи : Вид записи о регистрации
Комментарий : Строка
}
@enduml
