@startuml РеквизитыУведомленияИФНСНаЗачетАвансовыхПлатежей
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РеквизитыУведомленияИФНСНаЗачетАвансовыхПлатежей as "Реквизиты уведомления ИФНС на зачет авансовых платежей" <<РегистрыСведений>>
{
..Измерения..
ГоловнаяОрганизация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
Год : Число 4, 0
..Ресурсы..
НомерУведомления : Строка
ДатаУведомления : Дата
КодНалоговогоОргана : Строка
}
@enduml
