@startuml ИдентификаторыДокументовОснованийВладельцевЭД
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИдентификаторыДокументовОснованийВладельцевЭД as "Идентификаторы документов-оснований Владельцев ЭД" <<РегистрыСведений>>
{
..Измерения..
ЭлектронныйДокумент : Документ.Входящий электронный документ\rДокумент.Исходящий электронный документ\rСправочник.Присоединенный файл (Электронный документ)
ИдентификаторДокументаОснования : Строка
..Ресурсы..
ОснованиеПолучено : Булево
..Реквизиты..
ДокументОснование : Документ.Входящий электронный документ\rДокумент.Возврат товаров от клиента\rДокумент.Исходящий электронный документ\r...
ДокументПотомок : Документ.Входящий электронный документ\rДокумент.Исходящий электронный документ\rДокумент.(не используется) Произвольный электронный документ
}
@enduml
