@startuml ОшибкиРасчетаПартийИСебестоимости
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОшибкиРасчетаПартийИСебестоимости as "Ошибки расчета партий и себестоимости" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ВариантРасчета : Варианты расчета партий и себестоимости
ТипОшибки : Типы ошибок партионного учета и себестоимости
..Ресурсы..
ИдентификаторПротокола : Строка
}
@enduml
