@startuml ПутиКПрограммамЭлектроннойПодписиИШифрованияНаСерверахLinux
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПутиКПрограммамЭлектроннойПодписиИШифрованияНаСерверахLinux as "Пути к программам электронной подписи и шифрования на серверах Linux" <<РегистрыСведений>>
{
..Измерения..
Программа : Справочник.Программа электронной подписи и шифрования
ИмяКомпьютера : Строка
..Ресурсы..
Комментарий : Строка
ПутьКПрограмме : Строка
}
@enduml
