@startuml ИнцидентыОткрытые
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИнцидентыОткрытые as "Инциденты открытые" <<РегистрыСведений>>
{
..Измерения..
ТипИнцидента : Строка
КодИнцидента : Строка
..Ресурсы..
ИнцидентАктуален : Булево
}
@enduml
