@startuml ПодтверждениеОплатыНДСВБюджет
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПодтверждениеОплатыНДСВБюджет as "Подтверждение оплаты НДС в бюджет" <<РегистрыСведений>>
{
..Измерения..
СчетФактура : Документ.Таможенная декларация на импорт\rДокумент.Первичный документ\rДокумент.Заявление о ввозе товаров из ЕАЭС\r...
Состояние : Состояния оплаты НДС в бюджет
РучнаяКорректировка : Булево
НомерДокументаПеречисленияНалога : Строка
ДатаДокументаПеречисленияНалога : Дата
..Ресурсы..
Сумма : Число 15, 2
НомерОтметкиОРегистрации : Строка
ДатаПодтвержденияОплаты : Дата
СтрокаПлатежноРасчетныеДокументы : Строка
ВидАгентскогоДоговора : Виды агентских договоров
ЗаявкаНаРасходованиеДенежныхСредств : Документ.Заявка на расходование ДС
}
@enduml
