@startuml ТарифыСтраховыхВзносов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ТарифыСтраховыхВзносов as "Тарифы страховых взносов" <<РегистрыСведений>>
{
..Измерения..
ВидТарифа : Справочник.Вид тарифа страховых взносов
..Ресурсы..
ПФР : Число 5, 2
ПФРНакопительная : Число 5, 2
ФСС : Число 5, 2
ФССсИностранцев : Число 5, 2
ФФОМС : Число 5, 2
ТФОМС : Число 5, 2
}
@enduml
