@startuml ПараметрыАмортизацииНМАБУ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПараметрыАмортизацииНМАБУ as "Параметры амортизации НМА (бухгалтерский и налоговый учет)" <<РегистрыСведений>>
{
..Измерения..
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
Организация : Справочник.Организация
..Ресурсы..
СрокПолезногоИспользованияБУ : Число 4, 0
СрокПолезногоИспользованияНУ : Число 4, 0
КоэффициентБУ : Число 3, 2
}
@enduml
