@startuml СтоимостьТоваров
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтоимостьТоваров as "Стоимость товаров" <<РегистрыСведений>>
{
..Измерения..
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
Организация : Справочник.Организация
РазделУчета : Разделы учета себестоимости товаров
..Ресурсы..
Стоимость : Число 23, 10
СтоимостьДопРасходы : Число 23, 10
СтоимостьЗабалансовая : Число 23, 10
СтоимостьБезНДС : Число 23, 10
СтоимостьДопРасходыБезНДС : Число 23, 10
Трудозатраты : Число 23, 10
ПостатейныеПостоянныеСНДС : Число 23, 10
ПостатейныеПеременныеСНДС : Число 23, 10
ПостатейныеПостоянныеБезНДС : Число 23, 10
ПостатейныеПеременныеБезНДС : Число 23, 10
СтоимостьРегл : Число 23, 10
СтоимостьЗабалансоваяРегл : Число 23, 10
ДопРасходыРегл : Число 23, 10
ТрудозатратыРегл : Число 23, 10
ПостатейныеПостоянныеРегл : Число 23, 10
ПостатейныеПеременныеРегл : Число 23, 10
ПостояннаяРазница : Число 23, 10
ВременнаяРазница : Число 23, 10
СтоимостьУпр : Число 23, 10
ДопРасходыУпр : Число 23, 10
ТрудозатратыУпр : Число 23, 10
ПостатейныеПостоянныеУпр : Число 23, 10
ПостатейныеПеременныеУпр : Число 23, 10
}
@enduml
