@startuml НастройкиЗаймовСотрудникам
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиЗаймовСотрудникам as "Настройки займов сотрудникам" <<РегистрыСведений>>
{
..Ресурсы..
ИспользоватьЗаймыСотрудникам : Булево
}
@enduml
