@startuml ПорядокВыплатыДокументов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПорядокВыплатыДокументов as "Порядок выплаты документов" <<РегистрыСведений>>
{
..Измерения..
ДокументОснование : Документ.Единовременное пособие\rДокумент.Перенос затрат\rДокумент.Возврат НДФЛ\r...
..Ресурсы..
ПорядокВыплаты : Характер выплаты зарплаты
}
@enduml
