@startuml УдалитьКомплектыОтчетностиПерсучета
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьКомплектыОтчетностиПерсучета as "(не используется) Комплекты отчетности персучета" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ОтчетныйПериод : Дата
НомерКомплекта : Число 3, 0
..Ресурсы..
Состояние : Состояние комплекта отчетности персучета
АДВ_6_2 : Документ.Опись сведений АДВ-6-2
РСВ : Документ.Регламентированный отчет
АДВ_11 : Документ.Ведомость уплаты взносов АДВ-11
}
@enduml
