@startuml ЗаблокированныеДляПолученияУчетныеЗаписи
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗаблокированныеДляПолученияУчетныеЗаписи as "Заблокированные для получения учетные записи" <<РегистрыСведений>>
{
..Измерения..
УчетнаяЗапись : Справочник.Учетная запись электронной почты
..Ресурсы..
ДатаБлокировки : Дата
}
@enduml
