@startuml УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников as "Удалить значения совокупных тарифных ставок сотрудников" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
Значение : Число 15, 5
ВидТарифнойСтавки : Виды тарифных ставок
ДействуетДо : Дата
ЗначениеПоОкончании : Число 15, 5
ВидТарифнойСтавкиПоОкончании : Виды тарифных ставок
..Реквизиты..
ВторичнаяЗапись : Булево
}
@enduml
