@startuml ПакетыАмортизацииНМА
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПакетыАмортизацииНМА as "Пакеты амортизации НМА" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
..Ресурсы..
НомерПакета : Число 10, 0
}
@enduml
