@startuml Организации1СБизнесСеть
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.Организации1СБизнесСеть as "Организации 1С:Бизнес-сеть" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
}
@enduml
