@startuml БухучетЗарплатыСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.БухучетЗарплатыСотрудников as "Бухучет зарплаты сотрудников" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ДокументОснование : Документ.Кадровый перевод\rДокумент.Перемещение в другое подразделение\rДокумент.Восстановление в должности\r...
..Ресурсы..
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОтношениеКЕНВД : Отношение к ЕНВД затрат на зарплату
СтатьяФинансирования : Справочник.Статья финансирования
ДействуетДо : Дата
СпособОтраженияЗарплатыВБухучетеПоОкончании : Справочник.Способ отражения зарплаты
ОтношениеКЕНВДПоОкончании : Отношение к ЕНВД затрат на зарплату
СтатьяФинансированияПоОкончании : Справочник.Статья финансирования
}
@enduml
