@startuml УдалитьВерсииПодсистем
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьВерсииПодсистем as "(не используется) Версии подсистем" <<РегистрыСведений>>
{
..Измерения..
ОбластьДанных : Число 7, 0
ИмяПодсистемы : Строка
..Ресурсы..
Версия : Строка
..Реквизиты..
ПланОбновления : Хранилище значения
}
@enduml
