@startuml ПорядокОтраженияНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПорядокОтраженияНоменклатуры as "Порядок отражения номенклатуры" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Склад : Справочник.Склад (складская территория)
ГруппаФинансовогоУчета : Справочник.Группа финансового учета номенклатуры
..Ресурсы..
СчетУчетаНаСкладе : Счет бухгалтерского учета
СчетУчетаВыручкиОтПродаж : Счет бухгалтерского учета
СчетУчетаСебестоимостиПродаж : Счет бухгалтерского учета
СчетУчетаНДСПриПродаже : Счет бухгалтерского учета
СтатьяДоходовОСНО : Статьи доходов
СчетУчетаНДСПриЗакупке : Счет бухгалтерского учета
СчетУчетаВПути : Счет бухгалтерского учета
СчетУчетаНДСВПути : Счет бухгалтерского учета
СчетУчетаВыручкиОтПродажЕНВД : Счет бухгалтерского учета
СчетУчетаСебестоимостиПродажЕНВД : Счет бухгалтерского учета
СтатьяДоходовЕНВД : Статьи доходов
}
@enduml
