@startuml ОбластиПерсональныхДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОбластиПерсональныхДанных as "Области персональных данных" <<РегистрыСведений>>
{
..Измерения..
ИмяОбласти : Строка
..Ресурсы..
ИспользованиеСобытийЖурналаРегистрации : Булево
}
@enduml
