@startuml НастройкиОбменаФСС
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиОбменаФСС as "Настройки обмена с ФСС" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
ИспользоватьОбмен : Булево
СертификатСтрахователяОтпечаток : Строка
СертификатФССОтпечаток : Строка
СертификатФССЭЛНОтпечаток : Строка
ТестовыйСерверФССЭЛН : Булево
ИспользоватьАвтонастройку : Булево
}
@enduml
