@startuml ПроцентыСевернойНадбавкиФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПроцентыСевернойНадбавкиФизическихЛиц as "Проценты северной надбавки физических лиц" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
ПроцентСевернойНадбавки : Число 5, 2
ДействуетДо : Дата
}
@enduml
