@startuml НеобходимыеКорректировкиСтажаПФР
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НеобходимыеКорректировкиСтажаПФР as "Необходимые корректировки стажа ПФР" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
ОтчетныйПериод : Дата
}
@enduml
