@startuml АналитикаУчетаПоПартнерам
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.АналитикаУчетаПоПартнерам as "Аналитика учета по партнерам" <<РегистрыСведений>>
{
..Измерения..
Партнер : Справочник.Партнер
Организация : Справочник.Организация
Контрагент : Справочник.Организация\rСправочник.Контрагент
Договор : Справочник.Договор между организациями\rСправочник.Договор с контрагентом
НаправлениеДеятельности : Справочник.Направление деятельности
..Ресурсы..
КлючАналитики : Справочник.Ключ аналитики учета по партнерам
}
@enduml
