@startuml СтатистикаСделокСКлиентами
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтатистикаСделокСКлиентами as "Статистика сделок с клиентами" <<РегистрыСведений>>
{
..Измерения..
ЭтапПроцесса : Справочник.Этап процесса
Сделка : Справочник.Сделка с клиентом
..Ресурсы..
ДатаНачала : Дата
ДатаОкончания : Дата
Продолжительность : Число 10, 0
Потенциал : Число 15, 2
Результат : Статусы сделок
..Реквизиты..
Ответственный : Справочник.Пользователь
}
@enduml
