@startuml ОтражениеВРегламентированномУчетеНастройкиОрганизаций
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОтражениеВРегламентированномУчетеНастройкиОрганизаций as "Отражение в регламентированном учете настройки организаций" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
ФормироватьПроводкиВКонцеПериода : Булево
}
@enduml
