@startuml УдалитьФайлыСведенийСпецоператоры
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьФайлыСведенийСпецоператоры as "(не используется) Кэш файлов с ресурсов операторов электронного документооборота по универсальной схеме" <<РегистрыСведений>>
{
..Измерения..
УчетнаяЗапись : Справочник.(не используется) Учетные записи документооборота
..Ресурсы..
Данные : Хранилище значения
..Реквизиты..
ДатаФайла : Дата
Размер : Число 10, 0
}
@enduml
