@startuml ПоложенныеВидыЕжегодныхОтпусковИспр
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПоложенныеВидыЕжегодныхОтпусковИспр as "Положенные виды ежегодных отпусков испр" <<РегистрыСведений>>
{
..Измерения..
РегистраторИзмерение : Документ.Кадровый перевод\rДокумент.Восстановление в должности\rДокумент.Кадровый перевод списком\r...
ПериодИзмерение : Дата
Сотрудник : Справочник.Сотрудник
ВидЕжегодногоОтпуска : Справочник.Вид отпуска
..Ресурсы..
КоличествоДнейВГод : Число 2, 0
Используется : Булево
ДействуетДо : Дата
ИспользуетсяПоОкончании : Булево
КоличествоДнейВГодПоОкончании : Число 15, 2
..Реквизиты..
ВторичнаяЗапись : Булево
ПересчетНеТребуется : Булево
}
@enduml
