@startuml ПорядокОтраженияРасчетовСПартнерами
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПорядокОтраженияРасчетовСПартнерами as "Порядок отражения расчетов с партнерами" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
..Ресурсы..
СчетУчетаРасчетовСКлиентами : Счет бухгалтерского учета
СчетУчетаАвансовПолученных : Счет бухгалтерского учета
УдалитьСчетУчетаРасчетовПоВознаграждению : Счет бухгалтерского учета
СчетУчетаРасчетовСПоставщиками : Счет бухгалтерского учета
СчетУчетаАвансовВыданных : Счет бухгалтерского учета
СчетУчетаРасчетовПоПретензиям : Счет бухгалтерского учета
СчетУчетаРасчетовСКлиентамиТара : Счет бухгалтерского учета
СчетУчетаРасчетовСПоставщикамиТара : Счет бухгалтерского учета
СчетУчетаРасчетовСКредиторамиОсновнойДолг : Счет бухгалтерского учета
СчетУчетаРасчетовСКредиторамиПроценты : Счет бухгалтерского учета
СчетУчетаРасчетовСКредиторамиКомиссия : Счет бухгалтерского учета
СчетУчетаРасчетовСДебиторамиОсновнойДолг : Счет бухгалтерского учета
СчетУчетаРасчетовСДебиторамиПроценты : Счет бухгалтерского учета
СчетУчетаРасчетовСДебиторамиКомиссия : Счет бухгалтерского учета
СчетУчетаНеотфактурованныеПоставки : Счет бухгалтерского учета
}
@enduml
