@startuml УдалитьГруппыЗначенийДоступа
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьГруппыЗначенийДоступа as "(не используется) Группы значений доступа" <<РегистрыСведений>>
{
..Измерения..
ВидДоступа : (Не используется) Вид доступа
ЗначениеДоступа : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
ТолькоВидДоступа : Булево
ГруппаЗначенийДоступа : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
ГруппаОбновляемыхДанных : Число 1, 0
..Ресурсы..
НаследоватьПраваРодителей : Булево
}
@enduml
