@startuml СостоянияПлановыхКалькуляций
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияПлановыхКалькуляций as "Состояния плановых калькуляций" <<РегистрыСведений>>
{
..Измерения..
Калькуляция : Документ.Плановая калькуляция
..Ресурсы..
Состояние : Строка
}
@enduml
