@startuml ТоварныеОграничения
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ТоварныеОграничения as "Товарные ограничения" <<РегистрыСведений>>
{
..Измерения..
Склад : Справочник.Склад (складская территория)
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Группировка : Справочник.Группировка поддерживаемых запасов
..Ресурсы..
СтраховоеКоличествоЗапаса : Число 15, 3
МинимальноеКоличествоЗапаса : Число 15, 3
МаксимальноеКоличествоЗапаса : Число 15, 3
НормаПотребления : Число 15, 3
МетодОбеспеченияПотребностей : Методы обеспечения потребностей
УпаковкаЗаказа : Справочник.Упаковка
ОбеспечениеЗаказовПриПоддержанииЗапаса : Обеспечение заказов при поддержании запаса
СреднедневноеПотребление : Число 15, 3
СреднееОтклонениеПотребления : Число 15, 3
..Реквизиты..
РеквизитДопУпорядочивания : Число 5, 0
ДатаРасчетаРекомендаций : Дата
ЭтоДействующийПараметр : Булево
ЕстьРекомендацияПоИзменению : Булево
ЭтоГруппировка : Булево
}
@enduml
