@startuml ПараметрыРаботыВерсийРасширений
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПараметрыРаботыВерсийРасширений as "Параметры работы версий расширений" <<РегистрыСведений>>
{
..Измерения..
ВерсияРасширений : Справочник.Версия расширений
ИмяПараметра : Строка
..Ресурсы..
ХранилищеПараметра : Хранилище значения
}
@enduml
