@startuml ИзмененияОбщихДанныхУзлов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИзмененияОбщихДанныхУзлов as "Изменения общих данных узлов" <<РегистрыСведений>>
{
..Измерения..
УзелИнформационнойБазы : Синхронизация данных через универсальный формат\rОбмен с подключаемым оборудованием Offline\rОбрабатываемый объект\r...
..Ресурсы..
НомерСообщения : Число 15, 0
}
@enduml
