@startuml СтатусыИнформированияГИСМ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтатусыИнформированияГИСМ as "Статусы информирования ГИСМ" <<РегистрыСведений>>
{
..Измерения..
Документ : Документ.Внутреннее потребление товаров\rДокумент.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\r...
..Ресурсы..
ТекущееУведомление : Документ.Уведомление об импорте маркированных товаров\rДокумент.Уведомление о списании КиЗ для маркировки\rДокумент.Уведомление о ввозе маркированных товаров из ЕАЭС
Статус : Статусы информирования ГИСМ
ДальнейшееДействие : Дальнейшие действия по взаимодействию ГИСМ
}
@enduml
