@startuml ДатыОтработкиПоВидамОповещений
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДатыОтработкиПоВидамОповещений as "Даты отработки по видам оповещений" <<РегистрыСведений>>
{
..Измерения..
ВидОповещения : Справочник.Вид оповещений клиентам
..Ресурсы..
ДатаПоследнегоОповещения : Дата
}
@enduml
