@startuml ВсеОбновленияОблачногоАрхива
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ВсеОбновленияОблачногоАрхива as "Все обновления облачного архива" <<РегистрыСведений>>
{
..Измерения..
ВидОбновления : Строка
..Ресурсы..
ДатаПоследнегоОбновления : Дата
ДатаСледующегоОбновления : Дата
}
@enduml
