@startuml УсловияОплатыОтпускаПоУходуЗаРебенкомИспр
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УсловияОплатыОтпускаПоУходуЗаРебенкомИспр as "Условия оплаты отпуска по уходу за ребенком испр" <<РегистрыСведений>>
{
..Измерения..
РегистраторИзмерение : Документ.Изменение условий оплаты отпуска по уходу за ребенком\rДокумент.Отпуск по уходу за ребенком
ПериодИзмерение : Дата
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
СреднийДневнойЗаработок : Число 15, 2
МинимальныйСреднедневнойЗаработок : Число 8, 2
КоличествоДетей : Число 2, 0
КоличествоПервыхДетей : Число 1, 0
ПрименятьЛьготыПриНачисленииПособия : Булево
ДатаНачалаСобытия : Дата
РасчетПоПравилам2010Года : Булево
ФинансированиеФедеральнымБюджетом : Основания финансирования пособия федеральным бюджетом
ДоляНеполногоВремени : Число 4, 3
РайонныйКоэффициентРФнаНачалоСобытия : Число 3, 2
..Реквизиты..
СтраховойСлучай : Документ.Отпуск по уходу за ребенком
}
@enduml
