@startuml СоответствиеУсловийПродажМобильногоПриложения1СЗаказы
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СоответствиеУсловийПродажМобильногоПриложения1СЗаказы as "Соответствие условий продаж мобильного приложения "1С: Заказы клиентов"" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ВидЦены : Справочник.Вид цены
Партнер : Справочник.Партнер
Соглашение : Справочник.Соглашение об условиях продаж
Контрагент : Справочник.Контрагент
Договор : Справочник.Договор с контрагентом
ИдУсловиеПродаж : Строка
}
@enduml
