@startuml КурсыВалют
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КурсыВалют as "Курсы валют" <<РегистрыСведений>>
{
..Измерения..
Валюта : Справочник.Валюта
..Ресурсы..
Курс : Число 10, 4
Кратность : Число 10, 0
}
@enduml
