@startuml СоставДокументовЗарплатаКадры
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СоставДокументовЗарплатаКадры as "Состав документов зарплата кадры" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
ДокументФизическогоЛица : Документ.Назначение планового начисления\rДокумент.Подтверждение открытия счетов\rДокумент.Изменение аванса\r...
Сотрудник : Справочник.Сотрудник
ГоловнойСотрудник : Справочник.Сотрудник
}
@enduml
