@startuml ДокументыПоТребованиюФНС
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДокументыПоТребованиюФНС as "Документы по требованию ФНС" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ВидДокументаФНС : Виды представляемых документов
СканированныйДокумент : Справочник.Сканированные документы для передачи в электронном виде
Источник : Документ.Приобретение товаров и услуг\rДокумент.Таможенная декларация на импорт\rДокумент.Возврат товаров поставщику\r...
НомерСтрокиИсточника : Число 3, 0
..Реквизиты..
Направление : Направления документа по требованию ФНС
Контрагент : Справочник.Контрагент
КонтрагентПредставление : Строка
ДатаДокумента : Дата
НомерДокумента : Строка
СуммаДокумента : Число 17, 2
ИдентификаторВыбора : Уникальный идентификатор
ЕстьЭлектронныйДокумент : Булево
Готовность : Булево
}
@enduml
