@startuml НастройкиПроверкиОтчетностиПерсУчета
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиПроверкиОтчетностиПерсУчета as "Настройки проверки отчетности персонифицированного учета" <<РегистрыСведений>>
{
..Ресурсы..
ВыполнятьПроверкуНаСервере : Булево
ПроверятьПрограммойCheckXML : Булево
ПроверятьПрограммойCheckUFA : Булево
КаталогПрограммыCheckXML : Строка
КаталогПрограммыCheckUFA : Строка
}
@enduml
