@startuml ПрименениеСтандартныхВычетовПоНДФЛ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПрименениеСтандартныхВычетовПоНДФЛ as "Применение стандартных вычетов по НДФЛ" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
ГоловнаяОрганизация : Справочник.Организация
}
@enduml
