@startuml СтатусыПроверкиДокументов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтатусыПроверкиДокументов as "Статусы проверки документов" <<РегистрыСведений>>
{
..Измерения..
Документ : Документ.Внутреннее потребление товаров\rДокумент.Подготовка к передаче НМА\rДокумент.Списание ОС\r...
Организация : Справочник.Организация
..Ресурсы..
СтатусПроверки : Этапы проверки документа в регл учете
..Реквизиты..
Проверил : Справочник.Пользователь
ДатаПроверки : Дата
Изменил : Справочник.Пользователь
ДатаИзменения : Дата
}
@enduml
