@startuml ДанныеОбОплатеТрудаДляПодбораСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДанныеОбОплатеТрудаДляПодбораСотрудников as "Данные об оплате труда для подбора сотрудников" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ИдентификаторЗаписи : Уникальный идентификатор
..Ресурсы..
Филиал : Справочник.Организация
ТарифнаяСтавка : Число 15, 2
ФОТ : Число 15, 2
Надбавка : Число 15, 2
СпособРасчетаАванса : Способы расчета аванса
Аванс : Число 15, 2
}
@enduml
