@startuml ОсновныеМаршрутныеКарты
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОсновныеМаршрутныеКарты as "Основные маршрутные карты" <<РегистрыСведений>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Подразделение : Справочник.Подразделение
..Ресурсы..
МаршрутнаяКарта : Справочник.Маршрутная карта
}
@enduml
