@startuml ОтключенныеЛентыНовостейДляОбластиДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОтключенныеЛентыНовостейДляОбластиДанных as "Отключенные ленты новостей (для области данных)" <<РегистрыСведений>>
{
..Измерения..
ЛентаНовостей : Справочник.Лента новостей
..Реквизиты..
ПричинаОтключения : Строка
}
@enduml
