@startuml ЗамещениеПланов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗамещениеПланов as "Замещение планов" <<РегистрыСведений>>
{
..Измерения..
ЗамещающийПлан : Документ.План закупок\rДокумент.План продаж\rДокумент.План продаж по категориям\r...
ЗамещенныйПлан : Документ.План закупок\rДокумент.План продаж\rДокумент.План продаж по категориям\r...
ЗамещенныйПериод : Дата
ВидПлана : Справочник.Вид плана
..Ресурсы..
КЗамещению : Булево
КОтменеЗамещения : Булево
}
@enduml
