@startuml КорректирующиеФормыРСВ_1
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КорректирующиеФормыРСВ_1 as "Корректирующие формы РСВ 1" <<РегистрыСведений>>
{
..Измерения..
ПериодФормирования : Дата
КорректируемыйПериод : Дата
Организация : Справочник.Организация
..Ресурсы..
ОтчетРСВ_1 : Документ.Регламентированный отчет
Состояние : Состояние комплекта отчетности персучета
}
@enduml
