@startuml СтатусФизическихЛицКакНалогоплательщиковНДФЛ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтатусФизическихЛицКакНалогоплательщиковНДФЛ as "Статус физических лиц как налогоплательщиков НДФЛ" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
Статус : Справочник.Статус налогоплательщика
УдалитьСтатус : Справочник.(не используется) Статусы налогоплательщиков (НДФЛ)
}
@enduml
