@startuml СостоянияОбменовЭДЧерезОператоровЭДО
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияОбменовЭДЧерезОператоровЭДО as "Состояния обменов ЭД через операторов ЭДО" <<РегистрыСведений>>
{
..Измерения..
ПрофильНастроекЭДО : Справочник.Профиль настроек ЭДО
УдалитьСоглашениеОбИспользованииЭД : Справочник.Настройка ЭДО
..Ресурсы..
ДатаПолученияЭД : Дата
ДатаПоследнегоПолученияПриглашений : Дата
}
@enduml
