@startuml ЗначенияГруппДоступаПоУмолчанию
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗначенияГруппДоступаПоУмолчанию as "Значения групп доступа по умолчанию" <<РегистрыСведений>>
{
..Измерения..
ГруппаДоступа : Справочник.Группа доступа
ТипЗначенийДоступа : Справочник.Статьи бюджетов\rСправочник.Вид номенклатуры\rСправочник.Номенклатура\r...
..Ресурсы..
ВсеРазрешены : Булево
..Реквизиты..
ВсеРазрешеныБезИсключений : Булево
БезНастройки : Булево
}
@enduml
