@startuml УдалитьВычетыПоДоходамНДФЛ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьВычетыПоДоходамНДФЛ as "(не используется) Вычеты к доходам по НДФЛ" <<РегистрыСведений>>
{
..Измерения..
КодДохода : Справочник.(не используется) Виды доходов НДФЛ
..Ресурсы..
ГодовойВычет : Число 15, 2
НормативЗатрат : Число 15, 2
}
@enduml
