@startuml ПросмотренныеДанныеИнформационногоЦентра
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПросмотренныеДанныеИнформационногоЦентра as "Просмотренные данные информационного центра" <<РегистрыСведений>>
{
..Измерения..
Пользователь : Справочник.Пользователь
ДанныеИнформационногоЦентра : Справочник.Данные информационного центра
..Ресурсы..
Просмотрены : Булево
}
@enduml
