@startuml ИсторияНачисленийПоШтатномуРасписанию
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИсторияНачисленийПоШтатномуРасписанию as "История начислений по штатному расписанию" <<РегистрыСведений>>
{
..Измерения..
Дата : Дата
ПозицияШтатногоРасписания : Справочник.Позиция
Начисление : Начисление
ИдентификаторСтрокиВидаРасчета : Число 7, 0
..Ресурсы..
Размер : Число 15, 2
РазмерМин : Число 15, 2
РазмерМакс : Число 15, 2
}
@enduml
