@startuml НастройкиКадровогоУчета
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиКадровогоУчета as "Настройки кадрового учета" <<РегистрыСведений>>
{
..Ресурсы..
ИспользоватьРаботуНаНеполнуюСтавку : Булево
ИспользоватьПереносОстатковОтпускаПриУвольненииПереводом : Булево
КонтролироватьУникальностьТабельныхНомеров : Булево
ПравилоФормированияПредставленияЭлементовСправочникаСотрудники : Варианты правил формирования представления элементов справочника сотрудники
ПечататьТ6ДляОтпусковПоБеременностиИРодам : Булево
}
@enduml
