@startuml ЗамерыКомментарииСтатистики
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗамерыКомментарииСтатистики as "Замеры комментарии статистики" <<РегистрыСведений>>
{
..Измерения..
ПериодОкончание : Дата
ОперацияСтатистики : Уникальный идентификатор
КомментарийСтатистики : Уникальный идентификатор
ИдентификаторУдаления : Дата
..Ресурсы..
КоличествоЗначений : Число 10, 0
}
@enduml
