@startuml НаборыЗначенийДоступа
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НаборыЗначенийДоступа as "Наборы значений доступа" <<РегистрыСведений>>
{
..Измерения..
Объект : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
НомерНабора : Число 10, 0
ЗначениеДоступа : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rСправочник.Присоединенные файлы (Поступление безналичных денежных средств)\r...
Уточнение : Справочник.Идентификатор объекта метаданных
..Ресурсы..
Чтение : Булево
Изменение : Булево
..Реквизиты..
СтандартноеЗначение : Булево
ЗначениеБезГрупп : Булево
}
@enduml
