@startuml ИсторияСпециальностейПоШтатномуРасписанию
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИсторияСпециальностейПоШтатномуРасписанию as "История специальностей по штатному расписанию" <<РегистрыСведений>>
{
..Измерения..
Дата : Дата
ПозицияШтатногоРасписания : Справочник.Позиция
Специальность : Справочник.Специальность
}
@enduml
