@startuml ЦеныНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЦеныНоменклатуры as "Цены номенклатуры" <<РегистрыСведений>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
ВидЦены : Справочник.Вид цены
..Ресурсы..
Цена : Число 15, 2
Упаковка : Справочник.Упаковка
Валюта : Справочник.Валюта
}
@enduml
