@startuml КэшВспомогательныхДанныхВидаБюджета
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КэшВспомогательныхДанныхВидаБюджета as "Кэш вспомогательных данных вида бюджета" <<РегистрыСведений>>
{
..Измерения..
ВидБюджета : Справочник.Вид бюджета
ВидКэша : Виды кэша бюджета
РежимФормирования : Режимы формирования бюджетных отчетов
..Ресурсы..
ЗначениеБулево : Булево
ЗначениеДвоичныеДанные : Хранилище значения
}
@enduml
