@startuml УдалитьФайлыДокументовРеализацииПолномочийНалоговыхОрганов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьФайлыДокументовРеализацииПолномочийНалоговыхОрганов as "(не используется) Файлы документов реализации полномочий налоговых органов" <<РегистрыСведений>>
{
..Измерения..
Документ : Справочник.(не используется) Документы реализации полномочий налоговых органов
ИмяФайла : Строка
..Ресурсы..
Данные : Хранилище значения
..Реквизиты..
Размер : Число 10, 0
ТипСодержимого : (не используется) Типы содержимого файлов
}
@enduml
