@startuml УдалитьОчередьЗаданий
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьОчередьЗаданий as "(не используется) Очередь заданий" <<РегистрыСведений>>
{
..Измерения..
ОбластьДанных : Число 7, 0
Идентификатор : Строка
..Ресурсы..
Использование : Булево
ЗапланированныйМоментЗапуска : Дата
СостояниеЗадания : Состояния заданий
ИсполняющееФоновоеЗадание : Уникальный идентификатор
ЭксклюзивноеВыполнение : Булево
Шаблон : Справочник.Шаблон задания
НомерПопытки : Число 3, 0
УдалитьРегламентноеЗадание : Уникальный идентификатор
ИмяМетода : Строка
Параметры : Хранилище значения
ДатаНачалаПоследнегоЗапуска : Дата
Ключ : Строка
ИнтервалПовтораПриАварийномЗавершении : Число 10, 0
Расписание : Хранилище значения
КоличествоПовторовПриАварийномЗавершении : Число 10, 0
}
@enduml
