@startuml ЗависимостиПравДоступа
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗависимостиПравДоступа as "Зависимости прав доступа" <<РегистрыСведений>>
{
..Измерения..
ПодчиненнаяТаблица : Справочник.Идентификатор объекта метаданных
ТипВедущейТаблицы : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
}
@enduml
