@startuml ВсеОбновленияСПАРКРазделенное
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ВсеОбновленияСПАРКРазделенное as "Все обновления 1СПАРК Риски (разделенное)" <<РегистрыСведений>>
{
..Измерения..
ВидОбновления : Строка
..Ресурсы..
ДатаПоследнегоОбновления : Дата
ДатаСледующегоОбновления : Дата
}
@enduml
