@startuml ПараметрыАмортизацииОСУУ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПараметрыАмортизацииОСУУ as "Параметры амортизации ОС (управленческий учет)" <<РегистрыСведений>>
{
..Измерения..
ОсновноеСредство : Справочник.Объект эксплуатации
Организация : Справочник.Организация
..Ресурсы..
СрокИспользования : Число 10, 0
СрокИспользованияДляВычисленияАмортизации : Число 4, 0
КоэффициентУскорения : Число 4, 3
МетодНачисленияАмортизации : Способы начисления амортизации основных средств
ЛиквидационнаяСтоимость : Число 15, 2
ДатаПоследнегоИзменения : Дата
ОбъемПродукцииРаботДляВычисленияАмортизации : Число 10, 0
}
@enduml
