@startuml СведенияРеглОтчетАлкоПрил12Раздел2
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СведенияРеглОтчетАлкоПрил12Раздел2 as "Сведения регл отчет алко прил12 раздел2" <<РегистрыСведений>>
{
..Измерения..
Документ : Документ.Регламентированный отчет
УдалитьИндексСтраницы : Число 10, 0
ИндексСтроки : Число 10, 0
ИДДокИндСтраницы : Строка
Организация : Справочник.Организация
..Ресурсы..
П000020000301 : Строка
П000020000302 : Строка
П000020000303 : Строка
П000020000304 : Строка
П000020000305 : Строка
П000020000306 : Строка
П000020000307 : Строка
П000020000308 : Строка
П000020000309 : Дата
П000020000310 : Строка
П000020000311 : Строка
П000020000312 : Число 15, 5
..Реквизиты..
ХешИдКодПродПроизв : Строка
ХешИдПоставщика : Строка
ПроизводительИмпортер : Справочник.Контрагент
ДокументПоступления : Документ.Сторнирование начислений\rДокумент.Внутреннее потребление товаров\rДокумент.Назначение планового начисления\r...
Поставщик : Справочник.Контрагент
Активно : Булево
}
@enduml
