@startuml СклоненияПредставленийОбъектов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СклоненияПредставленийОбъектов as "Склонения представлений объектов" <<РегистрыСведений>>
{
..Измерения..
ХешПредставления : Строка
Объект : Справочник.Должность\rСправочник.Подразделение\rСправочник.Позиция\r...
..Ресурсы..
ИменительныйПадеж : Строка
РодительныйПадеж : Строка
ДательныйПадеж : Строка
ВинительныйПадеж : Строка
ТворительныйПадеж : Строка
ПредложныйПадеж : Строка
}
@enduml
