@startuml ЗначенияГруппДоступа
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗначенияГруппДоступа as "Значения групп доступа" <<РегистрыСведений>>
{
..Измерения..
ГруппаДоступа : Справочник.Группа доступа
ЗначениеДоступа : Справочник.Статьи бюджетов\rСправочник.Вид номенклатуры\rСправочник.Номенклатура\r...
..Ресурсы..
ЗначениеРазрешено : Булево
}
@enduml
