@startuml РасчетДолейБазыНалогаНаПрибыль
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РасчетДолейБазыНалогаНаПрибыль as "Расчет долей базы налога на прибыль" <<РегистрыСведений>>
{
..Измерения..
ПериодРасчета : Дата
Организация : Справочник.Организация
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
..Ресурсы..
ДоляНалоговойБазы : Число 12, 10
РасходыПоОплатеТруда : Число 12, 2
СтоимостьАмортизируемогоИмущества : Число 12, 2
СтоимостьОСПрошлыхМесяцев : Число 12, 2
СтоимостьОССледующегоМесяца : Число 12, 2
}
@enduml
