@startuml НастройкиПравОбъектов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиПравОбъектов as "Настройки прав объектов" <<РегистрыСведений>>
{
..Измерения..
Объект : Справочник.Папка
Пользователь : Справочник.Внешний пользователь\rСправочник.Пользователь\rСправочник.Группа внешних пользователей\r...
Право : Строка
Таблица : Справочник.Идентификатор объекта метаданных
..Ресурсы..
ПравоЗапрещено : Булево
НаследованиеРазрешено : Булево
..Реквизиты..
ПорядокНастройки : Число 4, 0
УровеньРазрешенияПрава : Число 1, 0
УровеньЗапрещенияПрава : Число 1, 0
УровеньРазрешенияЧтения : Число 1, 0
УровеньЗапрещенияЧтения : Число 1, 0
УровеньРазрешенияИзменения : Число 1, 0
УровеньЗапрещенияИзменения : Число 1, 0
}
@enduml
