@startuml ДоступностьРабочихЦентров
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДоступностьРабочихЦентров as "Доступность рабочих центров" <<РегистрыСведений>>
{
..Измерения..
РабочийЦентр : Справочник.Рабочий центр
Начало : Дата
Окончание : Дата
}
@enduml
