@startuml УдалитьОтветыНаЗапросыИОН
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьОтветыНаЗапросыИОН as "(не используется) Ответы на запросы ИОН" <<РегистрыСведений>>
{
..Измерения..
Запрос : Документ.(не используется) Запрос на информационное обслуживание налогоплательщика
ИмяФайла : Строка
..Ресурсы..
Данные : Хранилище значения
..Реквизиты..
Размер : Число 10, 0
ТипСодержимого : (не используется) Типы содержимого файлов
}
@enduml
