@startuml БухучетПлановыхУдержаний
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.БухучетПлановыхУдержаний as "Бухучет плановых удержаний" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
Организация : Справочник.Организация
Удержание : Удержание
ДокументОснование : Документ.Удержание по прочим операциям\rДокумент.Удержание добровольных взносов в НПФ\rДокумент.Удержание профсоюзных взносов\r...
..Ресурсы..
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
ДействуетДо : Дата
СтатьяФинансированияПоОкончании : Справочник.Статья финансирования
СтатьяРасходовПоОкончании : Справочник.Статья расходов
ИспользуетсяПоОкончании : Булево
}
@enduml
