@startuml СостояниеПодписанияЭД
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостояниеПодписанияЭД as "Состояние подписания электронных документов" <<РегистрыСведений>>
{
..Измерения..
Объект : Документ.Сообщение обмена с банками\rСправочник.Присоединенный файл (Электронный документ)
Идентификатор : Строка
..Ресурсы..
ИдентификаторРодителя : Строка
Порядок : Число 10, 0
Требование : Требования к подписанию ЭД
Подписант : Справочник.Пользователь
Сертификат : Справочник.Сертификат ключа электронной подписи и шифрования
Организация : Справочник.Организация
..Реквизиты..
Текущий : Булево
}
@enduml
