@startuml РабочиеМестаУдержаний
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РабочиеМестаУдержаний as "Рабочие места удержаний" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
ДокументОснование : Документ.Удержание по прочим операциям\rДокумент.Удержание добровольных взносов в НПФ\rДокумент.Данные для расчета зарплаты\r...
..Ресурсы..
РабочееМесто : Справочник.Сотрудник
}
@enduml
