@startuml ФайлыСведенийРОКИ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ФайлыСведенийРОКИ as "Кэш файлов с ресурса общей ключевой информации "Такском"" <<РегистрыСведений>>
{
..Измерения..
УчетнаяЗапись : Справочник.Учетные записи документооборота
ИмяРесурса : Строка
..Ресурсы..
Данные : Хранилище значения
..Реквизиты..
Расшифрован : Булево
ДатаФайла : Дата
Размер : Число 10, 0
}
@enduml
