@startuml УспешныеОбменыССайтом
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УспешныеОбменыССайтом as "Успешные обмены с сайтом" <<РегистрыСведений>>
{
..Измерения..
НастройкаОбменаССайтом : Узел обмена с сайтом
ДействиеПриОбмене : Действия при обмене с сайтом
..Ресурсы..
ДатаОкончания : Дата
}
@enduml
