@startuml УдалитьДанныеДляПодбораСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьДанныеДляПодбораСотрудников as "(не используется) Данные для подбора сотрудников" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Филиал : Справочник.Организация
Подразделение : Справочник.Подразделение
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
Должность : Справочник.Должность
ДолжностьПоШтатномуРасписанию : Справочник.Позиция
УдалитьПоДоговоруГПХ : Булево
..Ресурсы..
ВидСобытия : Виды кадровых событий
КоличествоСтавок : Число 22, 20
КоличествоСтавокПредставление : Строка
ВидЗанятости : Виды занятости
ВидДоговора : Виды договоров с сотрудниками
Окончание : Дата
ТарифнаяСтавка : Число 15, 2
ФОТ : Число 15, 2
Надбавка : Число 15, 2
СпособРасчетаАванса : Способы расчета аванса
Аванс : Число 15, 2
}
@enduml
