@startuml ПроцентныеСтавкиКредитовИДепозитов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПроцентныеСтавкиКредитовИДепозитов as "Ставки процента и комиссии" <<РегистрыСведений>>
{
..Измерения..
Договор : Справочник.Договор кредита (депозита)
..Ресурсы..
Процент : Число 15, 2
Комиссия : Число 15, 2
..Реквизиты..
АвторИзменения : Справочник.Пользователь
ДатаИзменения : Дата
}
@enduml
