@startuml ПараметрыОбменСБанками
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПараметрыОбменСБанками as "Параметры обмена с банками" <<РегистрыСведений>>
{
..Измерения..
НастройкаОбмена : Справочник.Настройка обмена с банком\rСправочник.Настройка ЭДО
..Ресурсы..
ПоследняяДатаПолученияЭД : Дата
НомерЗапроса : Число 10, 0
ИспользоватьЖурналирование : Булево
КаталогДляЖурналирования : Строка
}
@enduml
