@startuml УдалитьНепрочтеннаяПерепискаСКонтролирующимиОрганами
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьНепрочтеннаяПерепискаСКонтролирующимиОрганами as "(не используется) Непрочтенная переписка с контролирующими органами" <<РегистрыСведений>>
{
..Измерения..
НепрочтенноеСообщение : Справочник.Переписка с контролирующими органами\rСправочник.Документы реализации полномочий налоговых органов
}
@enduml
