@startuml ОсновныеДанныеКонтрактаДоговораСотрудникаИспр
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОсновныеДанныеКонтрактаДоговораСотрудникаИспр as "Основные данные контракта, договора сотрудника (испр.)" <<РегистрыСведений>>
{
..Измерения..
РегистраторИзмерение : Документ.Кадровый перевод\rДокумент.Кадровый перевод списком\rДокумент.Прием на работу\r...
ПериодИзмерение : Дата
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ГоловнаяОрганизация : Справочник.Организация
..Ресурсы..
ДатаДоговораКонтракта : Дата
НомерДоговораКонтракта : Строка
ДатаНачала : Дата
..Реквизиты..
ПоступлениеНаСлужбуВпервые : Булево
}
@enduml
