@startuml УдалитьНаборыЗначенийДоступа
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьНаборыЗначенийДоступа as "(не используется) Наборы значений доступа" <<РегистрыСведений>>
{
..Измерения..
Объект : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
НомерНабора : Число 10, 0
ВидДоступа : (Не используется) Вид доступа
ЗначениеДоступа : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
..Ресурсы..
Чтение : Булево
Изменение : Булево
}
@enduml
