@startuml ПодразделенияЗаПределамиРФ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПодразделенияЗаПределамиРФ as "Подразделения за пределами РФ" <<РегистрыСведений>>
{
..Измерения..
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ДатаОкончания : Дата
..Реквизиты..
Организация : Справочник.Организация
}
@enduml
