@startuml ПубличныеИдентификаторыСинхронизируемыхОбъектов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПубличныеИдентификаторыСинхронизируемыхОбъектов as "Публичные идентификаторы синхронизируемых объектов" <<РегистрыСведений>>
{
..Измерения..
Идентификатор : Строка
Ссылка : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
УзелИнформационнойБазы : Синхронизация данных через универсальный формат\rОбмен с подключаемым оборудованием Offline\rОбрабатываемый объект\r...
}
@enduml
