@startuml ПервоначальныеСведенияОСБухгалтерскийУчет
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПервоначальныеСведенияОСБухгалтерскийУчет as "Первоначальные сведения ОС (бухгалтерский учет, версия 2.2)" <<РегистрыСведений>>
{
..Измерения..
ОсновноеСредство : Справочник.Объект эксплуатации
..Ресурсы..
Организация : Справочник.Организация
ИнвентарныйНомер : Строка
СпособПоступления : Способы поступления активов
ПервоначальнаяСтоимость : Число 15, 2
СпособНачисленияАмортизации : Способы начисления амортизации основных средств
ПоказательНаработки : Справочник.Показатель наработки
ПорядокПогашенияСтоимости : Порядок погашения стоимости ОС
ГруппаОС : Группы ОС
КодПоОКОФ : Справочник.Элемент классификатора ОКОФ
ШифрПоЕНАОФ : Справочник.Элемент классификатора ЕНАОФ
АмортизационнаяГруппа : Амортизационные группы
ДоговорЛизинга : Справочник.Договор лизинга
РезервПереоценкиСтоимости : Число 15, 2
РезервПереоценкиАмортизации : Число 15, 2
}
@enduml
