@startuml ОчередьРасчетаПланаПроизводства
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОчередьРасчетаПланаПроизводства as "Очередь расчета плана производства" <<РегистрыСведений>>
{
..Измерения..
ПланПроизводства : Документ.План производства
Разделитель : Число 10, 0
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Спецификация : Справочник.Ресурсная спецификация
ДатаВыпуска : Дата
Подразделение : Справочник.Подразделение
Сценарий : Справочник.Сценарии товарного планирования
Назначение : Справочник.Назначение
ВыпускПолуфабрикатов : Булево
ПланПроизводстваПересчет : Документ.План производства
Проведение : Булево
..Ресурсы..
УдалитьКоличество : Число 15, 3
УдалитьСценарий : Справочник.Сценарии товарного планирования
ПересчитатьВсеПотребности : Булево
..Реквизиты..
ЕстьОшибкиРасчета : Булево
}
@enduml
