@startuml УдалитьДанныеДляПодбораДоговорниковГПХ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьДанныеДляПодбораДоговорниковГПХ as "(не используется) Данные для подбора договорников ГПХ" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ДатаНачала : Дата
ИдентификаторДоговора : Уникальный идентификатор
..Ресурсы..
Филиал : Справочник.Организация
Подразделение : Справочник.Подразделение
ДатаОкончания : Дата
}
@enduml
