@startuml ОрганизацииВКоторыхРаботалиСотрудники
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОрганизацииВКоторыхРаботалиСотрудники as "Организации в которых работали сотрудники" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
Организация : Справочник.Организация
}
@enduml
