@startuml ОчередьИнсталляцииПоставляемыхРасширенийВОбластиДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОчередьИнсталляцииПоставляемыхРасширенийВОбластиДанных as "Очередь инсталляции поставляемых расширений в области данных" <<РегистрыСведений>>
{
..Измерения..
ПоставляемоеРасширение : Справочник.Поставляемое расширение
..Ресурсы..
ПараметрыИнсталляции : Хранилище значения
}
@enduml
