@startuml ЗаданияКРасчетуСтоимостиВНА
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗаданияКРасчетуСтоимостиВНА as "Задания к расчету стоимости внеоборотных активов" <<РегистрыСведений>>
{
..Измерения..
Месяц : Дата
Организация : Справочник.Организация
ОбъектУчета : Справочник.Объект эксплуатации\rСправочник.Нематериальные активы и расходы на НИОКР\rСправочник.Объект строительства
НомерЗадания : Число 15, 0
Документ : Документ.Переоценка НМА\rДокумент.Подготовка к передаче НМА\rДокумент.Списание ОС\r...
}
@enduml
