@startuml УдалитьСостоянияДокументовЗачисленияЗарплаты
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьСостоянияДокументовЗачисленияЗарплаты as "(не используется) Состояния документов зачисления зарплаты" <<РегистрыСведений>>
{
..Измерения..
Документ : Документ.Списание безналичных ДС\rДокумент.Ведомость в банк\rДокумент.Заявка на расходование ДС
..Ресурсы..
Состояние : Состояние зачисления зарплаты
Год : Число 4, 0
НомерРеестра : Число 10, 0
}
@enduml
