@startuml НДССостояниеРеализации0
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НДССостояниеРеализации0 as "НДС состояние реализации 0%" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ДокументРеализации : Документ.Первичный документ\rДокумент.Реализация товаров и услуг\rДокумент.Акт выполненных работ
ДатаРеализации : Дата
Контрагент : Справочник.Контрагент
..Ресурсы..
Состояние : НДС состояния по реализации 0%
СтавкаНДС : Ставки НДС
ДатаПодтверждения : Дата
..Реквизиты..
Комментарий : Строка
}
@enduml
