@startuml РеестрКадровыхПриказовИспр
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РеестрКадровыхПриказовИспр as "Реестр кадровых приказов испр" <<РегистрыСведений>>
{
..Измерения..
РегистраторИзмерение : Документ.Кадровый перевод\rДокумент.Увольнение\rДокумент.Перемещение в другое подразделение\r...
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
Организация : Справочник.Организация
ДокументОснование : Документ.Кадровый перевод\rДокумент.Увольнение\rДокумент.Перемещение в другое подразделение\r...
Номер : Число 10, 0
..Ресурсы..
Дата : Дата
Подразделение : Справочник.Подразделение
Должность : Справочник.Должность
Разряд : Справочник.Квалификационный разряд (категория)
ТарифнаяСтавкаНадбавка : Строка
ВидДоговора : Виды договоров с сотрудниками
ВидСобытия : Виды кадровых событий
ДатаПриказа : Дата
НомерПриказа : Строка
Основание : Строка
}
@enduml
