@startuml РазрядыКатегорииСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РазрядыКатегорииСотрудников as "Разряды, категории сотрудников" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
..Ресурсы..
РазрядКатегория : Справочник.Квалификационный разряд (категория)
ДействуетДо : Дата
РазрядКатегорияПоОкончании : Справочник.Квалификационный разряд (категория)
}
@enduml
