@startuml ПланированиеЗагрузкиВидовРабочихЦентров
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПланированиеЗагрузкиВидовРабочихЦентров as "Планирование загрузки видов рабочих центров" <<РегистрыСведений>>
{
..Измерения..
Распоряжение : Документ.Заказ на производство
ЭтапПроизводства : Документ.Этап производства
СтатусГрафика : Число 1, 0
ВидРабочегоЦентра : Справочник.Вид рабочего центра
ДатаИнтервала : Дата
..Ресурсы..
Занято : Число 8, 0
}
@enduml
