@startuml УдалитьФорматыОбменаЕГАИС
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьФорматыОбменаЕГАИС as "(не используется) Форматы обмена ЕГАИС" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторФСРАР : Строка
..Ресурсы..
ФорматОбмена : Форматы обмена ЕГАИС
}
@enduml
