@startuml КадроваяИсторияСотрудниковИнтервальный
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КадроваяИсторияСотрудниковИнтервальный as "Кадровая история сотрудников интервальный" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ДатаОкончания : Дата
ДатаНачала : Дата
ГоловнаяОрганизация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
ПериодЗаписи : Дата
Год : Дата
..Ресурсы..
ПериодПредыдущейЗаписи : Дата
ВидСобытия : Виды кадровых событий
Организация : Справочник.Организация
Должность : Справочник.Должность
ВидЗанятости : Виды занятости
ГоловнойСотрудник : Справочник.Сотрудник
ЭтоГоловнойСотрудник : Булево
Подразделение : Справочник.Подразделение
ДолжностьПоШтатномуРасписанию : Справочник.Позиция
КоличествоСтавок : Число 22, 20
ВидДоговора : Виды договоров с сотрудниками
ДействуетДо : Дата
..Реквизиты..
РегистраторЗаписи : Документ.Кадровый перевод\rДокумент.Начальная штатная расстановка\rДокумент.Увольнение\r...
РегистраторСобытия : Документ.Кадровый перевод\rДокумент.Начальная штатная расстановка\rДокумент.Увольнение\r...
ПустойИнтервал : Булево
}
@enduml
