@startuml ДоходыПредыдущегоМестаРаботыНДФЛ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДоходыПредыдущегоМестаРаботыНДФЛ as "Доходы с предыдущего места работы (НДФЛ)" <<РегистрыСведений>>
{
..Измерения..
ГоловнаяОрганизация : Справочник.Организация
МесяцНалоговогоПериода : Дата
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
Размер : Число 15, 2
}
@enduml
