@startuml ЗанятыеЛицензии
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗанятыеЛицензии as "Занятые лицензии" <<РегистрыСведений>>
{
..Измерения..
Услуга : Справочник.Услуги сервиса
ИдентификаторЛицензии : Строка
КонтекстЛицензии : Строка
..Ресурсы..
КоличествоЛицензий : Число 10, 0
..Реквизиты..
ДатаИзменения : Дата
НомерПодписки : Строка
ДатаОтключенияПодписки : Дата
}
@enduml
