@startuml УдалитьРейтингАктивностиОбластейДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьРейтингАктивностиОбластейДанных as "(Не используется) Рейтинг активности областей данных" <<РегистрыСведений>>
{
..Измерения..
ОбластьДанных : Число 7, 0
..Ресурсы..
Рейтинг : Число 7, 0
}
@enduml
