@startuml НастройкаПередачиТоваровМеждуОрганизациями
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкаПередачиТоваровМеждуОрганизациями as "Настройка передачи товаров между организациями" <<РегистрыСведений>>
{
..Измерения..
ОрганизацияВладелец : Справочник.Организация
ТипЗапасов : Типы запасов
ОрганизацияПродавец : Справочник.Организация
..Ресурсы..
СпособПередачиТоваров : Способы передачи товаров
Валюта : Справочник.Валюта
Договор : Справочник.Договор между организациями
ВидЦены : Справочник.Вид цены
}
@enduml
