@startuml СтраховыеВзносыСкидкиКДоходам
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтраховыеВзносыСкидкиКДоходам as "Скидки к доходам при исчислении страховых взносов" <<РегистрыСведений>>
{
..Измерения..
ВидДохода : Справочник.Вид дохода по страховым взносам
..Ресурсы..
ГодоваяСкидка : Число 15, 2
НормативЗатрат : Число 15, 2
}
@enduml
