@startuml МестаВыплатыЗарплатыСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.МестаВыплатыЗарплатыСотрудников as "Места выплаты зарплаты сотрудников" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
Вид : Виды мест выплаты зарплаты
МестоВыплаты : Справочник.Банковский счет\rСправочник.Зарплатный проект\rСправочник.Касса\r...
}
@enduml
