@startuml СчетаБухгалтерскогоУчетаНМА
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СчетаБухгалтерскогоУчетаНМА as "Счета бухгалтерского учета нематериальных активов" <<РегистрыСведений>>
{
..Измерения..
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
Организация : Справочник.Организация
..Ресурсы..
СчетУчета : Счет бухгалтерского учета
СчетНачисленияАмортизации : Счет бухгалтерского учета
}
@enduml
