@startuml ОтражениеДокументовВМеждународномУчете
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОтражениеДокументовВМеждународномУчете as "Отражение документов в международном учете" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ДатаОтражения : Дата
..Ресурсы..
Статус : Статусы отражения в международном учете
УчетнаяПолитика : Справочник.Учетная политика
Комментарий : Строка
}
@enduml
