@startuml ПричиныИзмененияАдресныхСведений
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПричиныИзмененияАдресныхСведений as "Причины изменения адресных сведений" <<РегистрыСведений>>
{
..Измерения..
Идентификатор : Уникальный идентификатор
КодСубъектаРФ : Число 2, 0
ИзмененныйОбъект : Уникальный идентификатор
..Ресурсы..
СодержитОписание : Булево
Описание : Хранилище значения
}
@enduml
