@startuml НастройкиУчетныхЗаписейЭлектроннойПочты
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиУчетныхЗаписейЭлектроннойПочты as "Настройки учетных записей электронной почты" <<РегистрыСведений>>
{
..Измерения..
УчетнаяЗаписьЭлектроннойПочты : Справочник.Учетная запись электронной почты
..Ресурсы..
ВключатьПодписьДляНовыхСообщений : Булево
ФорматПодписиДляНовыхСообщений : Способы редактирования электронных писем
ПодписьДляНовыхСообщенийПростойТекст : Строка
ПодписьДляНовыхСообщенийФорматированныйДокумент : Хранилище значения
ВключатьПодписьПриОтветеПересылке : Булево
ФорматПодписиПриОтветеПересылке : Способы редактирования электронных писем
ПодписьПриОтветеПересылкеПростойТекст : Строка
ПодписьПриОтветеПересылкеФорматированныйДокумент : Хранилище значения
УдалитьПерсональнаяУчетнаяЗапись : Булево
ОтветственныйЗаОбработкуПисем : Справочник.Пользователь
ОтветственныйЗаВедениеПапок : Справочник.Пользователь
УдалятьПисьмаПослеОтправки : Булево
ПомещатьПисьмоВПапкуПисьмаОснования : Булево
НеИспользоватьВоВстроенномПочтовомКлиенте : Булево
ВПредставлениеВключатьИмяПользователя : Булево
ОбработкаПисемВыполняетсяВДругомПочтовомКлиенте : Булево
}
@enduml
