@startuml РасчетСтоимостиНалоговыхАктивовИОбязательствПослеИзмененияСтавкиНалогаНаПрибыль
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РасчетСтоимостиНалоговыхАктивовИОбязательствПослеИзмененияСтавкиНалогаНаПрибыль as "Расчет стоимости налоговых активов и обязательств после изменения ставки налога на прибыль" <<РегистрыСведений>>
{
..Измерения..
ПериодРасчета : Дата
Организация : Справочник.Организация
Вид : Виды активов и обязательств
ВидАктивовИОбязательствПБУ18 : Виды активов и обязательств (по ПБУ18/02)
Реформация : Булево
..Ресурсы..
НоваяСумма : Число 15, 2
СтараяСумма : Число 15, 2
Разница : Число 15, 2
НоваяСтавка : Число 15, 6
СтараяСтавка : Число 15, 6
}
@enduml
