@startuml СтавкаВзносаНаСтрахованиеОтНесчастныхСлучаев
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтавкаВзносаНаСтрахованиеОтНесчастныхСлучаев as "Ставка взноса на страхование от несчастных случаев" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
Ставка : Число 8, 3
}
@enduml
