@startuml ОплатаВедомостейНаВыплатуЗарплаты
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОплатаВедомостейНаВыплатуЗарплаты as "Сведения об оплате ведомостей на выплату заработной платы" <<РегистрыСведений>>
{
..Измерения..
Ведомость : Документ.Ведомость через раздатчика\rДокумент.Ведомость прочих доходов в кассу\rДокумент.Ведомость на счета\r...
ФизическоеЛицо : Справочник.Физическое лицо
Организация : Справочник.Организация
}
@enduml
