@startuml МножителиПартийИПолуфабрикатов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.МножителиПартийИПолуфабрикатов as "Множители партий и полуфабрикатов" <<РегистрыСведений>>
{
..Измерения..
Калькуляция : Документ.Плановая калькуляция
ПартияСпецификацияПродукции : Документ.Этап производства\rСправочник.Ресурсная спецификация\rДокумент.Производство без заказа
Продукция : Справочник.Номенклатура
ХарактеристикаПродукции : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
ПартияСпецификацияПолуфабриката : Документ.Этап производства\rСправочник.Ресурсная спецификация\rДокумент.Производство без заказа
Полуфабрикат : Справочник.Номенклатура
ХарактеристикаПолуфабриката : Справочник.Характеристика номенклатуры
Порядок : Число 10, 0
..Ресурсы..
Числитель : Число 18, 6
Знаменатель : Число 18, 6
КоличествоПолуфабриката : Число 15, 3
Стоимость : Число 15, 2
СтоимостьБезНДС : Число 15, 2
СтоимостьРегл : Число 15, 2
Трудозатраты : Число 15, 2
ТрудозатратыРегл : Число 15, 2
ПостатейныеПостоянные : Число 15, 2
ПостатейныеПостоянныеБезНДС : Число 15, 2
ПостатейныеПостоянныеРегл : Число 15, 2
ПостатейныеПеременные : Число 15, 2
ПостатейныеПеременныеБезНДС : Число 15, 2
ПостатейныеПеременныеРегл : Число 15, 2
..Реквизиты..
РасчетЗавершен : Булево
ПартияВыпущена : Булево
}
@enduml
