@startuml НастройкиВзаиморасчетовПоПрочимДоходам
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиВзаиморасчетовПоПрочимДоходам as "Настройки взаиморасчетов по прочим доходам" <<РегистрыСведений>>
{
..Ресурсы..
ИспользоватьВзаиморасчетыПоПрочимДоходам : Булево
ИспользоватьВедомостиДляВыплатыПрочихДоходов : Булево
}
@enduml
