@startuml НастройкиУчетаСтраховыхВзносов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиУчетаСтраховыхВзносов as "Настройки учета страховых взносов" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
ИспользуетсяТрудФармацевтов : Булево
ИспользуетсяТрудЧленовЛетныхЭкипажей : Булево
ИспользуетсяТрудЧленовЭкипажейМорскихСудов : Булево
ИспользуетсяТрудШахтеров : Булево
ИспользуютсяРаботыСДосрочнойПенсией : Булево
ПрименяютсяРезультатыСпециальнойОценкиУсловийТруда : Булево
}
@enduml
