@startuml ОтложенноеОткрытиеЛицевыхСчетовСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОтложенноеОткрытиеЛицевыхСчетовСотрудников as "Отложенное открытие лицевых счетов сотрудников" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
..Реквизиты..
Должность : Справочник.Должность
ЭмбоссированныйТекст1 : Строка
ЭмбоссированныйТекст2 : Строка
ЭмбоссированныйТекст3 : Строка
СистемаРасчетовПоБанковскимКартам : Строка
СуммаПервоначальногоПополнения : Число 15, 2
ЯвляетсяЗарплатнойКартой : Булево
ОплатаЗарплатнойКарты : Виды оплаты зарплатной карты
ЯвляетсяСотрудникомБанка : Булево
ИспользуетсяОвердрафт : Булево
КатегорияСотрудника : Категории сотрудников обмена с банками
ЯвляетсяУчастникомБонуснойПрограммы : Булево
БонуснаяПрограмма : Бонусные программы банков
НомерУчастникаБонуснойПрограммы : Строка
ТарифСледующийГод : Число 15, 2
ТарифТекущийГод : Число 15, 2
ИспользованиеДоставкиКорреспонденции : Булево
СпособРассылкиОтчета : Способы доставки корреспонденции банка
АдресЭлектроннойПочты : Строка
СчетДебета : Строка
НомерМобильногоТелефона : Строка
НомерМобильногоТелефонаПредставление : Строка
ОператорСвязи : Строка
ИспользованиеМобильногоБанка : Булево
ТарифМобильногоБанка : Тарифы мобильного банка
РазрешитьПередачуИнформацииВБКИ : Булево
КонтрольнаяИнформация : Строка
НомерМиграционнойКарты : Строка
ДатаНачалаПребыванияМиграционнойКарты : Дата
ДатаОкончанияПребыванияМиграционнойКарты : Дата
ВидМиграционногоДокумента : Справочник.Вид документа физических лиц
НомерМиграционногоДокумента : Строка
ДатаНачалаПребыванияМиграционногоДокумента : Дата
ДатаОкончанияПребыванияМиграционногоДокумента : Дата
ПрогнозируемыйМесячныйДоход : Число 15, 2
ДеньВыплатыЗарплаты : Число 2, 0
КодВидаВклада : Строка
КодПодвидаВклада : Строка
ВалютаВклада : Справочник.Валюта
АдресДляИнформирования : Строка
АдресДляИнформированияПредставление : Строка
АдресМестаРаботы : Строка
АдресМестаРаботыПредставление : Строка
ИдентификаторДизайна : Строка
ПВК : Строка
ПриложениеКартаКод : Строка
ПриложениеКартаПараметры : Строка
СтраховойНомерПФР : Строка
}
@enduml
