@startuml СтандартныеВычетыФизическихЛицНДФЛ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтандартныеВычетыФизическихЛицНДФЛ as "Стандартные вычеты физических лиц по НДФЛ" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
КодВычетаЛичный : Справочник.Вид вычетов НДФЛ
УдалитьКодВычетаЛичный : Справочник.(не используется) Виды вычетов НДФЛ
..Реквизиты..
Основание : Строка
}
@enduml
