@startuml УдалитьЗначенияСовокупныхТарифныхСтавокСотрудниковИспр
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьЗначенияСовокупныхТарифныхСтавокСотрудниковИспр as "(не используется) Удалить значения совокупных тарифных ставок сотрудников испр" <<РегистрыСведений>>
{
..Измерения..
РегистраторИзмерение : Документ.Назначение планового начисления\rДокумент.Изменение мест работы\rДокумент.Изменение условий оплаты отпуска по уходу за ребенком\r...
ПериодИзмерение : Дата
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
Значение : Число 15, 5
ВидТарифнойСтавки : Виды тарифных ставок
ДействуетДо : Дата
ЗначениеПоОкончании : Число 15, 5
ВидТарифнойСтавкиПоОкончании : Виды тарифных ставок
}
@enduml
