@startuml БлокировкиПооперационногоРасписания2_2
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.БлокировкиПооперационногоРасписания2_2 as "Блокировки пооперационного расписания 2.2" <<РегистрыСведений>>
{
..Измерения..
НомерСеанса : Число 6, 0
НачалоСеанса : Дата
Подразделение : Справочник.Подразделение
Этап : Документ.Этап производства
Операция : Справочник.Операция
ИдентификаторОперации : Число 25, 0
ПричинаБлокировки : Причины блокировок пооперационного расписания
..Реквизиты..
Пользователь : Справочник.Пользователь
}
@enduml
