@startuml АналитикаУчетаНаборов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.АналитикаУчетаНаборов as "Аналитика учета наборов" <<РегистрыСведений>>
{
..Измерения..
НоменклатураНабора : Справочник.Номенклатура
ХарактеристикаНабора : Справочник.Характеристика номенклатуры
..Ресурсы..
КлючАналитики : Справочник.Ключ аналитики учета наборов
}
@enduml
