@startuml ФайлыДокументовРеализацииПолномочийНалоговыхОрганов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ФайлыДокументовРеализацииПолномочийНалоговыхОрганов as "Файлы документов реализации полномочий налоговых органов" <<РегистрыСведений>>
{
..Измерения..
Документ : Справочник.Ответы на требования о представлении документов\rСправочник.Документы реализации полномочий налоговых органов\rСправочник.Сканированные документы для передачи в электронном виде
ИмяФайла : Строка
..Ресурсы..
Данные : Хранилище значения
..Реквизиты..
Размер : Число 10, 0
ТипСодержимого : Типы содержимого файлов
НомерСтраницы : Число 3, 0
}
@enduml
