@startuml СостоянияИРеквизитыДоставки
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияИРеквизитыДоставки as "Состояния и реквизиты доставки" <<РегистрыСведений>>
{
..Измерения..
Распоряжение : Документ.Передача давальцу\rДокумент.Приобретение товаров и услуг\rДокумент.Заказ поставщику\r...
Склад : Справочник.Склад (складская территория)
ПолучательОтправитель : Справочник.Подразделение\rСправочник.Партнер\rСтрока\r...
Перевозчик : Справочник.Партнер
СпособДоставки : Способы доставки
Зона : Справочник.Зоны доставки
..Ресурсы..
Адрес : Строка
Состояние : Состояния доставки
ДоставитьПолностью : Булево
..Реквизиты..
АдресЗначенияПолей : Строка
ВремяС : Дата
ВремяПо : Дата
ДополнительнаяИнформация : Строка
Номер : Строка
Дата : Дата
ОсобыеУсловияПеревозки : Булево
ОсобыеУсловияПеревозкиОписание : Строка
РазбиватьРасходныеОрдераПоРаспоряжениям : Булево
}
@enduml
