@startuml УдалитьСтатусыРегламентированныхОтчетов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьСтатусыРегламентированныхОтчетов as "(не используется) Статусы регламентированных отчетов" <<РегистрыСведений>>
{
..Измерения..
Отчет : Документ.Регламентированный отчет
..Ресурсы..
Статус : (не используется) Статусы регламентированных отчетов
}
@enduml
