@startuml ИсточникиПервичногоИнтереса
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИсточникиПервичногоИнтереса as "Источники первичного интереса" <<РегистрыСведений>>
{
..Измерения..
Сделка : Справочник.Сделка с клиентом
Партнер : Справочник.Партнер
..Ресурсы..
КаналПервичногоИнтереса : Канал рекламного воздействия
ИсточникПервичногоИнтереса : Справочник.Маркетинговое мероприятие\rСправочник.Пользователь\rСправочник.Партнер\r...
}
@enduml
