@startuml УдалитьТарифыСтраховыхВзносов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьТарифыСтраховыхВзносов as "(не используется) Тарифы страховых взносов" <<РегистрыСведений>>
{
..Измерения..
ВидТарифа : Справочник.(не используется) Виды тарифов страховых взносов
..Ресурсы..
ПФР : Число 5, 2
ПФРНакопительная : Число 5, 2
ФСС : Число 5, 2
ФФОМС : Число 5, 2
ТФОМС : Число 5, 2
}
@enduml
