@startuml ЗамерыСтатистики
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗамерыСтатистики as "Замеры статистики" <<РегистрыСведений>>
{
..Измерения..
ТипЗаписи : Число 1, 0
ПериодЗаписи : Дата
Ключ : Строка
ОперацияСтатистики : Уникальный идентификатор
..Ресурсы..
ЗначениеОперации : Число 15, 3
..Реквизиты..
ИдентификаторУдаления : Дата
}
@enduml
