@startuml СтатусыДокументовЕГАИС
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтатусыДокументовЕГАИС as "Статусы документов ЕГАИС" <<РегистрыСведений>>
{
..Измерения..
Документ : Документ.Товарно-транспортная накладная ЕГАИС (входящая)\rДокумент.Чек ККМ на возврат\rДокумент.Чек ЕГАИС на возврат\r...
..Ресурсы..
Статус : Статусы обработки акта списания ЕГАИС\rСтатусы обработки передачи в регистр №2 ЕГАИС\rСтатусы обработки возврата из регистра №2 ЕГАИС\r...
ДальнейшееДействие1 : Дальнейшие действия по взаимодействию ЕГАИС
ДальнейшееДействие2 : Дальнейшие действия по взаимодействию ЕГАИС
ДальнейшееДействие3 : Дальнейшие действия по взаимодействию ЕГАИС
КвитанцияПолученЕГАИС : Булево
КвитанцияПроведенЕГАИС : Булево
УведомлениеОРегистрацииДвижения : Булево
}
@enduml
