@startuml МестаВыплатыЗарплатыОрганизаций
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.МестаВыплатыЗарплатыОрганизаций as "Места выплаты зарплаты организаций" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
Вид : Виды мест выплаты зарплаты
МестоВыплаты : Справочник.Зарплатный проект\rСправочник.Касса\rСправочник.Физическое лицо
}
@enduml
