@startuml СеансыВерсийРасширений
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СеансыВерсийРасширений as "Сеансы версий расширений" <<РегистрыСведений>>
{
..Измерения..
ВерсияРасширений : Справочник.Версия расширений
НомерСеанса : Число 10, 0
НачалоСеанса : Дата
}
@enduml
