@startuml ИсторияРегистрацийВОрганеПФР
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИсторияРегистрацийВОрганеПФР as "История регистраций в органе ПФР" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
РегистрационныйНомерПФР : Строка
}
@enduml
