@startuml ЗначенияРазовыхПоказателейРасчетаЗарплатыПодразделений
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗначенияРазовыхПоказателейРасчетаЗарплатыПодразделений as "Значения разовых показателей расчета зарплаты (для подразделений)" <<РегистрыСведений>>
{
..Измерения..
ПериодДействия : Дата
Подразделение : Справочник.Подразделение
Показатель : Справочник.Показатель
Организация : Справочник.Организация
..Ресурсы..
Значение : Число 15, 5
}
@enduml
