@startuml РегистрацияТранспортныхСредств
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РегистрацияТранспортныхСредств as "Регистрация транспортных средств" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ОсновноеСредство : Справочник.Объект эксплуатации
..Ресурсы..
ВключатьВНалоговуюБазу : Булево
РегистрационныйЗнак : Строка
ИдентификационныйНомер : Строка
Марка : Строка
ПостановкаНаУчетВНалоговомОргане : Постановка на учет в налоговом органе
НалоговыйОрган : Справочник.Регистрация в налоговом органе
КодПоОКТМО : Строка
КодПоОКАТО : Строка
КодВидаТранспортногоСредства : Строка
НалоговаяБаза : Число 17, 2
ЕдиницаИзмеренияНалоговойБазы : Строка
НалоговаяСтавка : Число 8, 2
НалоговаяЛьгота : Виды налоговых льгот по транспортному налогу
КодНалоговойЛьготы : Строка
ЛьготнаяСтавка : Число 8, 2
ПроцентУменьшения : Число 4, 2
СуммаУменьшения : Число 17, 2
РегиональныйКодЛьготы : Строка
ЭкологическийКласс : Строка
УдалитьЭкологическийКласс : Строка
ОбщаяСобственность : Булево
ДоляВПравеОбщейСобственностиЧислитель : Число 10, 0
ДоляВПравеОбщейСобственностиЗнаменатель : Число 10, 0
ПовышающийКоэффициент : Число 3, 1
НалоговаяСтавкаЗависитОтГодаВыпускаТС : Булево
..Реквизиты..
ВидЗаписи : Вид записи о регистрации
Комментарий : Строка
}
@enduml
