@startuml СпособыОтраженияРасходовПоАмортизацииОСБухгалтерскийУчет
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СпособыОтраженияРасходовПоАмортизацииОСБухгалтерскийУчет as "Способы отражения расходов по амортизации ОС (бухгалтерский учет, версия 2.2)" <<РегистрыСведений>>
{
..Измерения..
ОсновноеСредство : Справочник.Объект эксплуатации
Организация : Справочник.Организация
..Ресурсы..
СтатьяРасходов : Статья расходов
СпособОтраженияРасходовЗаданДокументом : Булево
СпособОтраженияРасходов : Документ.Изменение параметров ОС
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ПередаватьРасходыВДругуюОрганизацию : Булево
ОрганизацияПолучательРасходов : Справочник.Организация
СчетПередачиРасходов : Счет бухгалтерского учета
}
@enduml
