@startuml УдалитьВоенкоматыОрганизаций
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьВоенкоматыОрганизаций as "(не используется) Военкоматы организаций" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
Военкомат : Справочник.Военкомат
}
@enduml
