@startuml ДополнительныеНастройкиЗарплатаКадры
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДополнительныеНастройкиЗарплатаКадры as "Дополнительные настройки" <<РегистрыСведений>>
{
..Ресурсы..
ВыводитьПолныеФИОВСписочныхПечатныхФормах : Булево
УдалятьПрефиксыОрганизацииИИБИзНомеровКадровыхПриказов : Булево
ВыводитьПолнуюИерархиюПодразделений : Булево
НастройкаУпорядочиванияСпискаСотрудников : Строка
ОтражениеВзаиморасчетовССотрудниками : Варианты отражения взаиморасчетов с сотрудниками
}
@enduml
