@startuml ПакетыПогашенияСтоимостиТМЦ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПакетыПогашенияСтоимостиТМЦ as "Пакеты погашения стоимости ТМЦ в эксплуатации" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Партия : Справочник.Партии ТМЦ в эксплуатации
..Ресурсы..
НомерПакета : Число 10, 0
}
@enduml
