@startuml СтандартныеВычетыНаДетейНДФЛ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтандартныеВычетыНаДетейНДФЛ as "Стандартные вычеты физических лиц на детей" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
КодВычета : Справочник.Вид вычетов НДФЛ
МесяцРегистрации : Дата
ДатаДействия : Дата
..Ресурсы..
КоличествоДетей : Число 2, 0
ДействуетДо : Дата
КоличествоДетейПоОкончании : Число 2, 0
..Реквизиты..
Основание : Строка
}
@enduml
