@startuml АналитикаУчетаПартий
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.АналитикаУчетаПартий as "Аналитика учета партий" <<РегистрыСведений>>
{
..Измерения..
ГруппаФинансовогоУчета : Справочник.Группа финансового учета номенклатуры
Поставщик : Справочник.Партнер
Контрагент : Справочник.Организация\rСправочник.Контрагент
НалогообложениеНДС : Типы налогообложения НДС
СтавкаНДС : Ставки НДС
ВидЦенности : Виды ценностей
КодСтроки : Число 10, 0
..Ресурсы..
КлючАналитики : Справочник.Ключ аналитики учета партий
}
@enduml
