@startuml ИзменениеСведенийФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИзменениеСведенийФизическихЛиц as "Изменение сведений физических лиц" <<РегистрыСведений>>
{
..Измерения..
ДатаЗаписи : Дата
ФизическоеЛицо : Справочник.Физическое лицо
КатегорияСведений : Категории сведений о физических лицах
..Ресурсы..
ПрежнееЗначение : Строка
УстановленноеЗначение : Строка
}
@enduml
