@startuml ОтборыПоЛентамНовостейДляОбластиДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОтборыПоЛентамНовостейДляОбластиДанных as "Отборы по лентам новостей, настроенные для области данных" <<РегистрыСведений>>
{
..Измерения..
ЛентаНовостей : Справочник.Лента новостей
КатегорияНовостей : Категория новостей
ЗначениеКатегорииНовостей : Булево\rСтрока\rСправочник.Значение категорий новостей\r...
}
@enduml
