@startuml ОчередьПолученияДанныхГИСМ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОчередьПолученияДанныхГИСМ as "Очередь получения данных ГИСМ" <<РегистрыСведений>>
{
..Измерения..
GLN : Строка
output_id : Число 19, 0
..Ресурсы..
Данные : Хранилище значения
ДатаРегистрации : Дата
..Реквизиты..
action_id : Число 10, 0
}
@enduml
