@startuml РолиСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РолиСотрудников as "Роли сотрудников" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
РольСотрудника : Роли сотрудников
}
@enduml
