@startuml СертификатыШифрования
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СертификатыШифрования as "Сертификаты шифрования" <<РегистрыСведений>>
{
..Измерения..
ЗашифрованныйОбъект : Справочник.Присоединенный файл (Отчет комиссионера)\rСправочник.Присоединенные файлы (Поступление безналичных денежных средств)\rСправочник.Присоединенный файл (Сообщение обмена с банками)\r...
ПорядковыйНомер : Число 10, 0
..Ресурсы..
Представление : Строка
Сертификат : Хранилище значения
Отпечаток : Строка
}
@enduml
