@startuml СвойстваХранилищаОблачногоАрхива
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СвойстваХранилищаОблачногоАрхива as "Свойства хранилища облачного архива" <<РегистрыСведений>>
{
..Измерения..
Свойство : Строка
..Реквизиты..
ДатаПроверки : Дата
Значение : Булево\rСтрока\rДата\r...
}
@enduml
