@startuml ДокументыФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДокументыФизическихЛиц as "Документы физических лиц" <<РегистрыСведений>>
{
..Измерения..
Физлицо : Справочник.Контрагент\rСправочник.Физическое лицо
ВидДокумента : Справочник.Вид документа физических лиц
..Ресурсы..
Серия : Строка
Номер : Строка
ДатаВыдачи : Дата
СрокДействия : Дата
КемВыдан : Строка
КодПодразделения : Строка
ЯвляетсяДокументомУдостоверяющимЛичность : Булево
Представление : Строка
УдалитьВидДокумента : Справочник.Вид документа физических лиц
}
@enduml
