@startuml ПорядокУчетаНМА
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПорядокУчетаНМА as "Порядок учета НМА" <<РегистрыСведений>>
{
..Измерения..
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
Организация : Справочник.Организация
..Ресурсы..
ГруппаФинансовогоУчета : Справочник.Группа финансового учета внеоборотных активов
НаправлениеДеятельности : Справочник.Направление деятельности
ОбъемНаработки : Число 15, 3
..Реквизиты..
ОтражатьВУпрУчете : Булево
ОтражатьВРеглУчете : Булево
}
@enduml
