@startuml ОчередьФормированияКорректировокИзлишковИНедостачПоТоварнымМестам
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОчередьФормированияКорректировокИзлишковИНедостачПоТоварнымМестам as "Очередь формирования корректировок излишков и недостач по товарным местам" <<РегистрыСведений>>
{
..Измерения..
Склад : Справочник.Склад (складская территория)
Помещение : Справочник.Помещение
}
@enduml
