@startuml ПараметрыПериодовСтажаПФР
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПараметрыПериодовСтажаПФР as "Параметры периодов стажа ПФР" <<РегистрыСведений>>
{
..Измерения..
ГоловнаяОрганизация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
ТипДоговора : Типы договоров СЗВ-6-3
Начало : Дата
Окончание : Дата
Приоритет : Состояния сотрудника
Сторно : Булево
ДокументОснование : Документ.Сторнирование начислений\rДокумент.Изменение условий оплаты отпуска по уходу за ребенком\rДокумент.Кадровый перевод\r...
ДатаНачалаСобытия : Дата
Сотрудник : Справочник.Сотрудник
..Ресурсы..
ВидСтажаПФР : Виды стажа перс. учета с 2014 года
Должность : Справочник.Должность\rСправочник.Условия труда
Подразделение : Справочник.Территория\rСправочник.Подразделение
ДолжностьПоШтатномуРасписанию : Справочник.Позиция
ГрафикРаботы : Справочник.График работы
ИспользованиеРесурсаВидСтажаПФР : Значение ресурса регистров состояний сотрудника
КоличествоСтавок : Число 5, 2
Территория : Справочник.Территория
УсловияТруда : Справочник.Условия труда
ТерриториальныеУсловия : Справочник.Территориальное условие
УдалитьТерриториальныеУсловия : Справочник.(не используется) Территориальные условия
ОсобыеУсловияТруда : Справочник.Особое условие труда
УдалитьОсобыеУсловияТруда : Справочник.(не используется) Особые условия труда ПФР
ОснованиеВыслугиЛет : Справочник.Основание для досрочной пенсии
УдалитьОснованиеВыслугиЛет : Справочник.(не используется) Основания для досрочной пенсии
ИспользованиеРесурсаОрганизация : Значение ресурса регистров состояний сотрудника
ИспользованиеРесурсаПодразделение : Значение ресурса регистров состояний сотрудника
ИспользованиеРесурсаДолжность : Значение ресурса регистров состояний сотрудника
ИспользованиеРесурсаДолжностьПоШтатномуРасписанию : Значение ресурса регистров состояний сотрудника
Организация : Справочник.Организация
ИспользованиеРесурсаГрафикРаботы : Значение ресурса регистров состояний сотрудника
ИспользованиеРесурсаКоличествоСтавок : Значение ресурса регистров состояний сотрудника
ИспользованиеРесурсаТерритория : Значение ресурса регистров состояний сотрудника
ИспользованиеРесурсаУсловияТруда : Значение ресурса регистров состояний сотрудника
ИспользованиеРесурсаТерриториальныеУсловия : Значение ресурса регистров состояний сотрудника
ИспользованиеРесурсаОсобыеУсловияТруда : Значение ресурса регистров состояний сотрудника
ИспользованиеРесурсаОснованиеВыслугиЛет : Значение ресурса регистров состояний сотрудника
ВнутреннееСовместительство : Булево
ИспользованиеРесурсаВнутреннееСовместительство : Значение ресурса регистров состояний сотрудника
}
@enduml
