@startuml МестоУчетаНМА
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.МестоУчетаНМА as "Место учета НМА" <<РегистрыСведений>>
{
..Измерения..
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
..Ресурсы..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
..Реквизиты..
ОтражатьВРеглУчете : Булево
ОтражатьВУпрУчете : Булево
}
@enduml
