@startuml РасчетЗемельногоНалога
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РасчетЗемельногоНалога as "Расчет земельного налога" <<РегистрыСведений>>
{
..Измерения..
ПериодРасчета : Дата
Организация : Справочник.Организация
ИФНС : Справочник.Регистрация в налоговом органе
ОсновноеСредство : Справочник.Объект эксплуатации
ПериодСтроительства : Строка
КадастроваяСтоимость : Число 15, 0
..Ресурсы..
КадастровыйНомер : Строка
КБК : Строка
КодПоОКТМО : Строка
КодКатегорииЗемель : Строка
УдалитьКадастроваяСтоимость : Число 15, 0
ДоляВПравеОбщейСобственностиЧислитель : Число 10, 0
ДоляВПравеОбщейСобственностиЗнаменатель : Число 10, 0
УменьшениеНалоговойБазыНаСумму : Булево
НеОблагаемаяНалогомСумма : Число 15, 0
УменьшениеНалоговойБазыПоСтатье391 : Булево
КодНалоговойЛьготыУменьшениеНалоговойБазыПоСтатье391 : Строка
НалоговаяЛьготаПоНалоговойБазе : Вид налоговой льготы по налоговой базе по земельному налогу
ДоляНеоблагаемойПлощадиЧислитель : Число 10, 0
ДоляНеоблагаемойПлощадиЗнаменатель : Число 10, 0
НалоговаяБаза : Число 15, 2
КоличествоМесяцевВладения : Число 2, 0
КоличествоМесяцевПримененияЛьготы : Число 2, 0
НалоговаяСтавка : Число 5, 4
СуммаНалога : Число 15, 0
КодНалоговойЛьготыОсвобождениеОтНалогообложенияПоСтатье395 : Строка
СуммаНалоговойЛьготыВВидеУменьшенияСуммыНалога : Число 15, 0
СуммаНалоговойЛьготыВВидеСниженияНалоговойСтавки : Число 15, 0
ПредставлениеНалоговойЛьготы : Строка
СуммаНалогаКУплате : Число 15, 0
СуммаАвансовыхПлатежей1Кв : Число 15, 0
СуммаАвансовыхПлатежей2Кв : Число 15, 0
СуммаАвансовыхПлатежей3Кв : Число 15, 0
СниженнаяНалоговаяСтавка : Число 5, 4
ПроцентУменьшенияСуммыНалога : Число 7, 4
УдалитьПериодСтроительства : Строка
КоличествоМесяцевИспользования : Число 2, 0
}
@enduml
