@startuml УдалитьИсключаемыеИзОстатковОтпусковПериоды
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьИсключаемыеИзОстатковОтпусковПериоды as "(не используется) исключаемые из остатков отпусков периоды" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
..Ресурсы..
ДатаНачалаОтсутствия : Дата
ДатаОкончанияОтсутствия : Дата
..Реквизиты..
ЯвляетсяОтпускомБезСохраненияЗарплаты : Булево
}
@enduml
