@startuml КатегорииНовостейПростые
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КатегорииНовостейПростые as "Категории новостей, простые" <<РегистрыСведений>>
{
..Измерения..
Новость : Справочник.Новость
КатегорияНовостей : Категория новостей
ЗначениеКатегорииНовостей : Булево\rСтрока\rСправочник.Значение категорий новостей\r...
..Реквизиты..
УсловиеОтбора : Строка
}
@enduml
