@startuml КомментарииОперацииСтатистики
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КомментарииОперацииСтатистики as "Комментарии операции статистики" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторОперации : Уникальный идентификатор
ИдентификаторКомментария : Уникальный идентификатор
}
@enduml
