@startuml РазмерВычетовНДФЛВторичный
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РазмерВычетовНДФЛВторичный as "Размер вычетов НДФЛВторичный" <<РегистрыСведений>>
{
..Измерения..
КодВычета : Справочник.Вид вычетов НДФЛ
ДатаНачала : Дата
ДатаОкончания : Дата
..Ресурсы..
Размер : Число 10, 0
ОграничениеПоДоходам : Число 10, 0
}
@enduml
