@startuml СчетаФактурыКомитентовКРегистрации
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СчетаФактурыКомитентовКРегистрации as "Счета фактуры комитентов к регистрации" <<РегистрыСведений>>
{
..Измерения..
СчетФактураВыданный : Документ.Счет-фактура выданный\rДокумент.Счет-фактура выданный комиссионеру (агенту)
Комитент : Справочник.Контрагент
..Ресурсы..
СуммаСНДС : Число 15, 2
СуммаНДС : Число 15, 2
..Реквизиты..
Валюта : Справочник.Валюта
Организация : Справочник.Организация
Дата : Дата
Покупатель : Справочник.Организация\rСправочник.Контрагент
Субкомиссионер : Справочник.Организация\rСправочник.Контрагент
}
@enduml
