@startuml СтатусыУведомленийОПоступленииМаркированныхТоваровГИСМ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СтатусыУведомленийОПоступленииМаркированныхТоваровГИСМ as "Статусы уведомлений о поступлении маркированных товаров ГИСМ" <<РегистрыСведений>>
{
..Измерения..
Документ : Документ.Уведомление о поступлении маркированных товаров
..Ресурсы..
Статус : Состояния уведомлений о поступлении маркированных товаров ГИСМ
ДальнейшееДействие : Дальнейшие действия по взаимодействию ГИСМ
ПоступлениеТоваров : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг
КоличествоПоступленийТоваров : Число 2, 0
СтатусПоступления : Состояния поступлений ГИСМ
КПередачеПодтверждения : Булево
ПроцентПодтвержденныхКиЗ : Число 3, 0
}
@enduml
