@startuml ИдентификационныеДанныеПользователей
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИдентификационныеДанныеПользователей as "Идентификационные данные пользователей" <<РегистрыСведений>>
{
..Измерения..
Пользователь : Справочник.Пользователь
..Ресурсы..
Штрихкод : Строка
МагнитныйКод : Строка
}
@enduml
