@startuml ТерриториальныеУсловияПФР
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ТерриториальныеУсловияПФР as "Территориальные условия местностей" <<РегистрыСведений>>
{
..Измерения..
СтруктурнаяЕдиница : Справочник.Организация\rСправочник.Территория\rСправочник.Подразделение
..Ресурсы..
ТерриториальныеУсловияПФР : Справочник.Территориальное условие
УдалитьТерриториальныеУсловияПФР : Справочник.(не используется) Территориальные условия
}
@enduml
