@startuml КлассыУсловийТрудаПоДолжностям
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КлассыУсловийТрудаПоДолжностям as "Классы условий труда по должностям" <<РегистрыСведений>>
{
..Измерения..
Должность : Справочник.Должность\rСправочник.Позиция\rСправочник.Условия труда
..Ресурсы..
КлассУсловийТруда : Классы условий труда по результатам специальной оценки
ДатаРегистрацииИзменений : Дата
}
@enduml
