@startuml ТекущиеКадровыеДанныеСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ТекущиеКадровыеДанныеСотрудников as "Текущие кадровые данные сотрудников" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
Сотрудник : Справочник.Сотрудник
ГоловнаяОрганизация : Справочник.Организация
ТекущаяОрганизация : Справочник.Организация
..Ресурсы..
ТекущееПодразделение : Справочник.Подразделение
ТекущаяДолжность : Справочник.Должность
ДатаПриема : Дата
ДатаУвольнения : Дата
ТекущаяДолжностьПоШтатномуРасписанию : Справочник.Позиция
ОсновноеРабочееМестоВОрганизации : Булево
ТекущийВидДоговора : Виды договоров с сотрудниками
ТекущийВидЗанятости : Виды занятости
УдалитьТекущаяОрганизация : Справочник.Организация
ТекущаяТерритория : Справочник.Территория
}
@enduml
