@startuml ТранспортныеКонтейнеры
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ТранспортныеКонтейнеры as "Транспортные контейнеры" <<РегистрыСведений>>
{
..Измерения..
ТранспортноеСообщение : Документ.Транспортное сообщение
ИмяФайла : Строка
..Ресурсы..
Данные : Хранилище значения
..Реквизиты..
Размер : Число 10, 0
}
@enduml
