@startuml УдалитьЗамерыВремени2
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьЗамерыВремени2 as "(не используется) Замеры времени 2" <<РегистрыСведений>>
{
..Измерения..
КлючеваяОперация : Справочник.Ключевая операция
ДатаНачалаЗамера : Дата
НомерСеанса : Число 15, 0
..Ресурсы..
ВремяВыполнения : Число 15, 3
Комментарий : Строка
..Реквизиты..
ДатаЗаписи : Дата
ДатаОкончания : Дата\rЧисло 15, 0
Пользователь : Строка
ДатаЗаписиЛокальная : Дата
}
@enduml
