@startuml ХранилищеСертификатов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ХранилищеСертификатов as "Хранилище сертификатов" <<РегистрыСведений>>
{
..Измерения..
ТипХранилища : Тип хранилища сертификатов
Идентификатор : Строка
..Ресурсы..
Наименование : Строка
ДатаНачала : Дата
ДатаОкончания : Дата
Отпечаток : Строка
СерийныйНомер : Строка
Сертификат : Хранилище значения
}
@enduml
