@startuml НормативныйГрафикЭтаповПроизводства
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НормативныйГрафикЭтаповПроизводства as "Нормативный график этапов производства" <<РегистрыСведений>>
{
..Измерения..
ЭтапПроизводства : Документ.Этап производства
Распоряжение : Документ.Заказ на производство
..Ресурсы..
Ресурсоемкость : Число 10, 0
ДлительностьДоВыпуска : Число 14, 4
ДлительностьДоЗапуска : Число 14, 4
..Реквизиты..
ЭтапыСНулевойДлительностьюУпорядочены : Булево
}
@enduml
