@startuml СведенияОРежимахРаботыФормыСотрудникаРасширенный
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СведенияОРежимахРаботыФормыСотрудникаРасширенный as "Сведения о режимах работы формы сотрудника расширенный" <<РегистрыСведений>>
{
..Измерения..
РежимРаботы : Режимы работы формы сотрудника
..Ресурсы..
ИспользоватьНачисленияПоДоговорамВФормеСотрудника : Булево
ИспользоватьВоинскийУчетВФормеСотрудника : Булево
ИспользоватьЛичныеДанныеВФормеСотрудника : Булево
}
@enduml
