@startuml ABCXYZКлассификацияКлиентов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ABCXYZКлассификацияКлиентов as "ABC/XYZ классификация клиентов" <<РегистрыСведений>>
{
..Измерения..
Партнер : Справочник.Партнер
ТипПараметраКлассификации : Типы параметров классификации
ТипКлассификации : Типы классификации
..Ресурсы..
Класс : XYZ Классификация\rABC Классификация\rСтадии взаимоотношений с клиентами
ЗначениеПараметраКлассификации : Число 15, 2
}
@enduml
