@startuml БлокировкиПооперационногоРасписания
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.БлокировкиПооперационногоРасписания as "Блокировки пооперационного расписания" <<РегистрыСведений>>
{
..Измерения..
НомерСеанса : Число 6, 0
НачалоСеанса : Дата
Подразделение : Справочник.Подразделение
ИдентификаторОперации : Уникальный идентификатор
ПричинаБлокировки : Причины блокировок пооперационного расписания
..Реквизиты..
Пользователь : Справочник.Пользователь
}
@enduml
