@startuml НастройкиВоинскогоУчета
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиВоинскогоУчета as "Настройки воинского учета" <<РегистрыСведений>>
{
..Ресурсы..
ИспользоватьВоинскийУчет : Булево
ИспользоватьБронированиеГраждан : Булево
ИспользуетсяТрудЛетноПодъемногоСостава : Булево
ИспользуетсяТрудПлавсостава : Булево
}
@enduml
