@startuml ИсторияРегистрацийВНалоговомОргане
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИсторияРегистрацийВНалоговомОргане as "История регистраций в налоговом органе" <<РегистрыСведений>>
{
..Измерения..
СтруктурнаяЕдиница : Справочник.Организация\rСправочник.Территория\rСправочник.Подразделение
..Ресурсы..
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
}
@enduml
