@startuml СведенияОФайлах
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СведенияОФайлах as "Сведения о файлах" <<РегистрыСведений>>
{
..Измерения..
Файл : Справочник.Присоединенный файл (Отчет комиссионера)\rСправочник.Присоединенные файлы (Поступление безналичных денежных средств)\rСправочник.Присоединенный файл (Сообщение обмена с банками)\r...
..Ресурсы..
Автор : Справочник.Внешний пользователь\rСправочник.Учетная запись синхронизации файлов\rСправочник.Пользователь
ДатаСоздания : Дата
ВладелецФайла : Документ.Внутреннее потребление товаров\rДокумент.Акт о расхождениях после перемещения\rДокумент.Подтверждение открытия счетов\r...
ИндексКартинки : Число 10, 0
НомерКартинкиПодписанЗашифрован : Число 10, 0
Наименование : Строка
Описание : Строка
ПометкаУдаления : Булево
Размер : Число 10, 0
Расширение : Строка
Редактирует : Справочник.Учетная запись синхронизации файлов\rСправочник.Пользователь
ХранитьВерсии : Булево
}
@enduml
