@startuml НастройкиОткрытияФормПриНачалеРаботыСистемы
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиОткрытияФормПриНачалеРаботыСистемы as "Настройки открытия форм при начале работы программы" <<РегистрыСведений>>
{
..Измерения..
Пользователь : Справочник.Пользователь
ОткрываемаяФорма : Формы, открываемые при запуске программы
..Ресурсы..
Параметры : Хранилище значения
ОткрыватьПоУмолчанию : Булево
ТекстовоеПредставлениеПараметров : Строка
}
@enduml
