@startuml КалендарныеГрафики
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КалендарныеГрафики as "Календарные графики" <<РегистрыСведений>>
{
..Измерения..
Календарь : Справочник.График работы
Год : Число 4, 0
ДатаГрафика : Дата
..Ресурсы..
ДеньВключенВГрафик : Булево
КоличествоДнейВГрафикеСНачалаГода : Число 3, 0
}
@enduml
