@startuml ПорядокОтраженияПроизводства
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПорядокОтраженияПроизводства as "Порядок отражения производства" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
МестоПроизводства : Справочник.Подразделение\rСправочник.Партнер
..Ресурсы..
СчетУчета : Счет бухгалтерского учета
}
@enduml
