@startuml НастройкаРаспределенияПоНаправлениямДеятельности
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкаРаспределенияПоНаправлениямДеятельности as "Настройка распределения по направлениям деятельности" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Номенклатура : Справочник.Номенклатура
Подразделение : Справочник.Подразделение
Партнер : Справочник.Партнер
..Ресурсы..
СпособРаспределения : Справочник.Способ распределения доходов и расходов по направлениям деятельности\rСправочник.Направление деятельности
Используется : Булево
}
@enduml
