@startuml СоответствиеРеквизитовНоменклатуры1СБизнесСеть
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СоответствиеРеквизитовНоменклатуры1СБизнесСеть as "Соответствие реквизитов номенклатуры 1С:Бизнес-сеть" <<РегистрыСведений>>
{
..Измерения..
ВидНоменклатуры : Справочник.Вид номенклатуры
РеквизитОбъекта : Дополнительный реквизит / сведение\rСтрока
ИдентификаторРеквизитаКатегории : Строка
..Реквизиты..
ПредставлениеРеквизитаКатегории : Строка
}
@enduml
