@startuml НастройкиШтатногоРасписания
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиШтатногоРасписания as "Настройки штатного расписания" <<РегистрыСведений>>
{
..Ресурсы..
ИспользоватьВилкуСтавокВШтатномРасписании : Булево
ИспользоватьИндексациюШтатногоРасписания : Булево
ИспользоватьИсториюИзмененияШтатногоРасписания : Булево
ИспользоватьРазрядыКатегорииКлассыДолжностейИПрофессийВШтатномРасписании : Булево
ИспользоватьШтатноеРасписание : Булево
НеИспользоватьВилкуСтавокВШтатномРасписании : Булево
НеИспользоватьИсториюИзмененияШтатногоРасписания : Булево
НеИспользоватьШтатноеРасписание : Булево
ПроверятьНаСоответствиеШтатномуРасписаниюАвтоматически : Булево
ПредставлениеТарифовИНадбавок : Представление тарифов и надбавок
УдалитьИспользоватьСтатьиФинансированияВКадровомУчете : Булево
ИспользоватьБронированиеПозиций : Булево
ДнейСохраненияБрони : Число 3, 0
}
@enduml
