@startuml УчетнаяПолитикаПоНДФЛ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УчетнаяПолитикаПоНДФЛ as "Учетная политика по НДФЛ" <<РегистрыСведений>>
{
..Измерения..
ГоловнаяОрганизация : Справочник.Организация
..Ресурсы..
ОсобенностиИсчисленияНДФЛ : Особенности исчисления НДФЛ
}
@enduml
