@startuml УдалитьСостоянияПодработок
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьСостоянияПодработок as "(не используется) Состояния подработок" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ГоловнаяОрганизация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
ВидСобытия : Виды кадровых событий
ДействуетДо : Дата
ВидСобытияПоОкончании : Виды кадровых событий
..Реквизиты..
Организация : Справочник.Организация
ДолжностьПоШтатномуРасписанию : Справочник.Позиция
Подразделение : Справочник.Подразделение
Должность : Справочник.Должность
КоличествоСтавок : Число 22, 20
ВидЗанятости : Виды занятости
ОтсутствующийСотрудник : Справочник.Сотрудник
ВидДоговора : Виды договоров с сотрудниками
}
@enduml
