@startuml ГруппыЗаявокПлатежногоКалендаря
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ГруппыЗаявокПлатежногоКалендаря as "Группы заявок платежного календаря" <<РегистрыСведений>>
{
..Измерения..
ЗаявкаНаРасходованиеДенежныхСредств : Документ.Сторнирование начислений\rДокумент.Внутреннее потребление товаров\rДокумент.Назначение планового начисления\r...
..Ресурсы..
Группа : Строка
ДатаНазначения : Дата
}
@enduml
