@startuml НастройкиОблачногоАрхиваНаЛокальномКомпьютере
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиОблачногоАрхиваНаЛокальномКомпьютере as "Настройки Облачного архива на локальном компьютере" <<РегистрыСведений>>
{
..Измерения..
ИмяКомпьютера : Строка
..Реквизиты..
ДатаПроверки : Дата
Расписание : Хранилище значения
КаталогЛогов : Строка
КаталогСтатистики : Строка
КаталогРабочий : Строка
}
@enduml
