@startuml ОбластиТребующиеОбработкиПоставляемыхДанных
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОбластиТребующиеОбработкиПоставляемыхДанных as "Области требующие обработки поставляемых данных" <<РегистрыСведений>>
{
..Измерения..
ИдентификаторФайла : Уникальный идентификатор
КодОбработчика : Строка
ОбластьДанных : Число 7, 0
}
@enduml
