@startuml ТарифыВзносовПоРезультатамСпециальнойОценкиУсловийТруда
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ТарифыВзносовПоРезультатамСпециальнойОценкиУсловийТруда as "Тарифы взносов по результатам специальной оценки условий труда" <<РегистрыСведений>>
{
..Измерения..
КлассУсловийТруда : Классы условий труда по результатам специальной оценки
..Ресурсы..
Тариф : Число 5, 2
}
@enduml
