@startuml РассчитанныеОтборыПоНовостям_Общие
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РассчитанныеОтборыПоНовостям_Общие as "Рассчитанные отборы по новостям (общие)" <<РегистрыСведений>>
{
..Измерения..
Новость : Справочник.Новость
..Реквизиты..
РезультатОтбора : Булево
}
@enduml
