@startuml СвязиМеждуФизЛицами
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СвязиМеждуФизЛицами as "Связи между физическими лицами" <<РегистрыСведений>>
{
..Измерения..
ФизЛицо1 : Справочник.Физическое лицо
ФизЛицо2 : Справочник.Физическое лицо
ВидСвязи : Справочник.Вид связи между физическими лицами
..Реквизиты..
Автор : Справочник.Пользователь
Комментарий : Строка
}
@enduml
