@startuml ПользовательскиеНастройкиДоступаКОбработкам
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПользовательскиеНастройкиДоступаКОбработкам as "Пользовательские настройки доступа к обработкам" <<РегистрыСведений>>
{
..Измерения..
ДополнительныйОтчетИлиОбработка : Справочник.Дополнительный отчет или обработка
ИдентификаторКоманды : Строка
Пользователь : Справочник.Внешний пользователь\rСправочник.Пользователь
..Ресурсы..
Доступно : Булево
}
@enduml
