@startuml СпособыОтраженияРасходовПоИмущественнымНалогам
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СпособыОтраженияРасходовПоИмущественнымНалогам as "Способы отражения расходов по имущественным налогам" <<РегистрыСведений>>
{
..Измерения..
ОсновноеСредство : Справочник.Объект эксплуатации
Организация : Справочник.Организация
..Ресурсы..
СтатьяРасходов : Статья расходов
СпособОтраженияРасходовЗаданДокументом : Булево
СпособОтраженияРасходов : Документ.Регистрация земельных участков\rДокумент.Изменение параметров ОС\rДокумент.Изменение способа отражения имущественных налогов\r...
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
}
@enduml
