@startuml ПорядокОтраженияПодарочныхСертификатов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПорядокОтраженияПодарочныхСертификатов as "Порядок отражения подарочных сертификатов" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ВидСертификата : Справочник.Вид подарочных сертификатов
..Ресурсы..
СчетУчета : Счет бухгалтерского учета
}
@enduml
