@startuml ДанныеДляПодбораСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДанныеДляПодбораСотрудников as "Данные для подбора сотрудников" <<РегистрыСведений>>
{
..Измерения..
Наименование : Строка
Сотрудник : Справочник.Сотрудник
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
ИдентификаторЗаписи : Уникальный идентификатор
ПоДоговоруГПХ : Булево
..Ресурсы..
Филиал : Справочник.Организация
Подразделение : Справочник.Подразделение
Должность : Справочник.Должность
ДолжностьПоШтатномуРасписанию : Справочник.Позиция
ЭтоГоловнойСотрудник : Булево
ВидСобытия : Виды кадровых событий
КоличествоСтавок : Число 22, 20
КоличествоСтавокПредставление : Строка
ВидЗанятости : Виды занятости
ВидДоговора : Виды договоров с сотрудниками
Начало : Дата
Окончание : Дата
МестоВСтруктуреПредприятия : Справочник.Подразделение
УдалитьТарифнаяСтавка : Число 15, 2
УдалитьФОТ : Число 15, 2
УдалитьНадбавка : Число 15, 2
УдалитьСпособРасчетаАванса : Способы расчета аванса
УдалитьАванс : Число 15, 2
}
@enduml
