@startuml ЗначенияТарифов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗначенияТарифов as "Значения тарифов" <<РегистрыСведений>>
{
..Измерения..
ТарифнаяСетка : Справочник.Тарифная группа
РазрядКатегория : Справочник.Квалификационный разряд (категория)
..Ресурсы..
РазрядныйКоэффициент : Число 15, 4
Тариф : Число 15, 2
Используется : Булево
}
@enduml
