@startuml РедактируемыеРеквизитыКодаДоходаНДФЛ
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РедактируемыеРеквизитыКодаДоходаНДФЛ as "Редактируемые реквизиты кода дохода НДФЛ" <<РегистрыСведений>>
{
..Измерения..
КодДохода : Справочник.Вид дохода НДФЛ
..Ресурсы..
СоответствуетОплатеТруда : Булево
}
@enduml
