@startuml УсловияДоговораЗаймаСотруднику
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УсловияДоговораЗаймаСотруднику as "Условия договора займа сотруднику" <<РегистрыСведений>>
{
..Измерения..
ДоговорЗайма : Документ.Договор займа сотруднику
..Ресурсы..
Сумма : Число 15, 2
ДатаОкончания : Дата
ПроцентнаяСтавка : Число 4, 2
РазмерПлатежа : Число 15, 2
РазмерПогашения : Число 15, 2
ДатаНачалаПогашения : Дата
ОграничениеПлатежа : Число 15, 2
МатериальнаяВыгодаОблагаетсяНДФЛ : Булево
..Реквизиты..
Организация : Справочник.Организация
}
@enduml
