@startuml ДолжностиПодключаемыеХарактеристики
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ДолжностиПодключаемыеХарактеристики as "Подключаемые характеристики должностей" <<РегистрыСведений>>
{
..Измерения..
Объект : Справочник.Должность
Свойство : Подключаемая характеристика должности
ИдентификаторИсточника : Строка
..Ресурсы..
Значение : Булево\rСправочник.Строка отчетности статистического наблюдения\rСправочник.Строка отчетности расходов и численности
}
@enduml
