@startuml СостоянияВБракеФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияВБракеФизическихЛиц as "Состояния в браке физических лиц" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
СостояниеВБраке : Справочник.Семейное положение
}
@enduml
