@startuml ТоварыДругогоКачества
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ТоварыДругогоКачества as "Товары другого качества" <<РегистрыСведений>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
НоменклатураБрак : Справочник.Номенклатура
..Ресурсы..
ГрадацияКачества : Градации качества
}
@enduml
