@startuml ИнцидентыОтложенныеПроверки
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИнцидентыОтложенныеПроверки as "Инциденты отложенные проверки" <<РегистрыСведений>>
{
..Измерения..
ТипИнцидента : Строка
..Ресурсы..
ВремяСледующегоСтарта : Дата
}
@enduml
