@startuml ПрименениеСтандартныхВычетовПоНДФЛИспр
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПрименениеСтандартныхВычетовПоНДФЛИспр as "Применение стандартных вычетов по НДФЛ испр" <<РегистрыСведений>>
{
..Измерения..
РегистраторИзмерение : Документ.Увольнение\rДокумент.Отмена стандартных вычетов НДФЛ\rДокумент.Увольнение списком\r...
ПериодИзмерение : Дата
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
ГоловнаяОрганизация : Справочник.Организация
}
@enduml
