@startuml КонтрагентыНаМониторингеСПАРКРиски
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КонтрагентыНаМониторингеСПАРКРиски as "Контрагенты на мониторинге 1СПАРК Риски" <<РегистрыСведений>>
{
..Измерения..
Контрагент : Справочник.Контрагент
РучноеДобавление : Булево
..Ресурсы..
Поставлен : Булево
ДатаПостановки : Дата
..Реквизиты..
ИдентификаторЗапроса : Уникальный идентификатор
Пользователь : Справочник.Пользователь\rСправочник.Партнер\rСправочник.Контактное лицо
ТипОшибки : Виды ошибок 1СПАРК Риски
ДатаДобавления : Дата
}
@enduml
