@startuml СостоянияОСОрганизаций
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостоянияОСОрганизаций as "Состояния ОС организаций (версия 2.2)" <<РегистрыСведений>>
{
..Измерения..
ОсновноеСредство : Справочник.Объект эксплуатации
Организация : Справочник.Организация
..Ресурсы..
ДатаСостояния : Дата
Состояние : Состояния ОС
}
@enduml
