@startuml КадроваяИсторияСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КадроваяИсторияСотрудников as "Кадровая история сотрудников" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ГоловнаяОрганизация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Должность : Справочник.Должность
ДолжностьПоШтатномуРасписанию : Справочник.Позиция
КоличествоСтавок : Число 22, 20
ВидСобытия : Виды кадровых событий
ВидЗанятости : Виды занятости
ВидДоговора : Виды договоров с сотрудниками
ДействуетДо : Дата
ГоловнойСотрудник : Справочник.Сотрудник
ЭтоГоловнойСотрудник : Булево
УдалитьОрганизацияПоОкончании : Справочник.Организация
УдалитьПодразделениеПоОкончании : Справочник.Подразделение
УдалитьДолжностьПоШтатномуРасписаниюПоОкончании : Справочник.Позиция
УдалитьДолжностьПоОкончании : Справочник.Должность
УдалитьКоличествоСтавокПоОкончании : Число 22, 20
УдалитьВидСобытияПоОкончании : Виды кадровых событий
УдалитьВидЗанятостиПоОкончании : Виды занятости
УдалитьВидДоговораПоОкончании : Виды договоров с сотрудниками
..Реквизиты..
УдалитьПервичныйДокумент : Документ.Кадровый перевод\rДокумент.Увольнение\rДокумент.Восстановление в должности\r...
}
@enduml
