@startuml ЖурналСобытийОбменСБанками
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЖурналСобытийОбменСБанками as "Журнал событий 1С:ДиректБанк" <<РегистрыСведений>>
{
..Измерения..
Сообщение : Документ.Сообщение обмена с банками
Идентификатор : Уникальный идентификатор
..Ресурсы..
Пользователь : Справочник.Пользователь
Статус : Статусы обмена с банками
}
@enduml
