@startuml ПсевдонимыПредопределенныхУзлов
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПсевдонимыПредопределенныхУзлов as "Псевдонимы предопределенных узлов" <<РегистрыСведений>>
{
..Измерения..
Корреспондент : Синхронизация данных через универсальный формат\rОбмен с подключаемым оборудованием Offline\rОбрабатываемый объект\r...
..Ресурсы..
КодУзла : Строка
}
@enduml
