@startuml ПлановыеУдержания
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПлановыеУдержания as "Плановые удержания" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
Удержание : Удержание
ДокументОснование : Документ.Удержание по прочим операциям\rДокумент.Удержание добровольных взносов в НПФ\rДокумент.Удержание профсоюзных взносов\r...
..Ресурсы..
Используется : Булево
Размер : Число 15, 2
ДействуетДо : Дата
ИспользуетсяПоОкончании : Булево
РазмерПоОкончании : Число 15, 2
}
@enduml
