@startuml НастройкиИнтеграцииСоСпринтером
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиИнтеграцииСоСпринтером as "Параметры интеграции с ПК "Спринтер" компании "Такском"" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
КодАбонента : Строка
КаталогПрограммыЭлектроннойПочты : Строка
КаталогОтправкиДанныхОтчетности : Строка
}
@enduml
