@startuml ПараметрыАмортизацииОСНалоговыйУчет
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПараметрыАмортизацииОСНалоговыйУчет as "Параметры амортизации ОС (налоговый учет, версия 2.2)" <<РегистрыСведений>>
{
..Измерения..
ОсновноеСредство : Справочник.Объект эксплуатации
Организация : Справочник.Организация
..Ресурсы..
СрокПолезногоИспользования : Число 4, 0
КоэффициентАмортизации : Число 4, 2
ПРДляВычисленияАмортизации : Число 15, 2
}
@enduml
