@startuml ОбщиеНастройкиУзловИнформационныхБаз
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ОбщиеНастройкиУзловИнформационныхБаз as "Общие настройки узлов информационных баз" <<РегистрыСведений>>
{
..Измерения..
УзелИнформационнойБазы : Синхронизация данных через универсальный формат\rОбмен с подключаемым оборудованием Offline\rОбрабатываемый объект\r...
..Ресурсы..
ВыполнитьКорректировкуИнформацииСопоставления : Булево
НачальнаяВыгрузкаДанных : Булево
ПользовательДляСинхронизацииДанных : Справочник.Пользователь
ВыполнитьОтправкуДанных : Булево
ВерсияКорреспондента : Строка
..Реквизиты..
НомерОтправленного : Число 10, 0
НомерОтправленногоНачальнаяВыгрузкаДанных : Число 10, 0
}
@enduml
