@startuml РазрядыКатегорииСотрудниковИспр
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.РазрядыКатегорииСотрудниковИспр as "Разряды, категории сотрудников испр" <<РегистрыСведений>>
{
..Измерения..
РегистраторИзмерение : Документ.Изменение оплаты труда\rДокумент.Кадровый перевод\rДокумент.Изменение квалификационного разряда (категории) сотрудника\r...
ПериодИзмерение : Дата
Сотрудник : Справочник.Сотрудник
..Ресурсы..
РазрядКатегория : Справочник.Квалификационный разряд (категория)
ДействуетДо : Дата
РазрядКатегорияПоОкончании : Справочник.Квалификационный разряд (категория)
}
@enduml
