@startuml НастройкиРасчетаРезервовОтпусков
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.НастройкиРасчетаРезервовОтпусков as "Настройки расчета резервов отпусков" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
..Ресурсы..
ФормироватьРезервОтпусковБУ : Булево
ФормироватьРезервОтпусковНУ : Булево
МетодНачисленияРезерваОтпусков : Методы начисления резервов отпусков
НормативОтчисленийВРезервОтпусков : Число 4, 2
ПредельнаяВеличинаОтчисленийВРезервОтпусков : Число 15, 2
ОпределятьИзлишкиЕжемесячно : Булево
}
@enduml
