@startuml ПерерасчетСреднегоЗаработка
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПерерасчетСреднегоЗаработка as "Перерасчет среднего заработка" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ДокументСреднегоЗаработка : Документ.Сторнирование начислений\rДокумент.Отпуск\rДокумент.Больничный лист\r...
ДокументОснование : Документ.Сторнирование начислений\rДокумент.Простой сотрудников\rДокумент.Отпуск без сохранения оплаты списком\r...
}
@enduml
