@startuml УдалитьСоставыСемейФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.УдалитьСоставыСемейФизическихЛиц as "(не используется) Составы семей физических лиц" <<РегистрыСведений>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
НомерПоПорядку : Число 2, 0
..Ресурсы..
СтепеньРодства : Справочник.Степень родства
ФИО : Строка
ДатаРождения : Дата
}
@enduml
