@startuml ПодпискиПолучателей
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПодпискиПолучателей as "Подписки получателей" <<РегистрыСведений>>
{
..Измерения..
КаналСообщений : Строка
Получатель : Конечная точка
}
@enduml
