@startuml КатегорииНовостейИнтервалыВерсийНеобработанные
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.КатегорииНовостейИнтервалыВерсийНеобработанные as "Категории новостей (интервалы версий, необработанные)" <<РегистрыСведений>>
{
..Измерения..
КатегорияНовостейСтрока : Строка
ЛентаНовостей : Справочник.Лента новостей
УИННовости : Строка
Продукт : Строка
ВерсияОТ : Строка
ВерсияДО : Строка
}
@enduml
