@startuml ВариантыПереупаковки
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ВариантыПереупаковки as "Варианты переупаковки" <<РегистрыСведений>>
{
..Измерения..
Упаковка : Справочник.Упаковка
Источник : Справочник.Упаковка
МаксимальнаяУпаковкаВВетви : Справочник.Упаковка
..Ресурсы..
Количество : Число 10, 3
}
@enduml
