@startuml ИдентификаторыПолученныхЭлектронныхПисем
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ИдентификаторыПолученныхЭлектронныхПисем as "Идентификаторы полученных электронных писем" <<РегистрыСведений>>
{
..Измерения..
УчетнаяЗапись : Справочник.Учетная запись электронной почты
Идентификатор : Строка
..Ресурсы..
ДатаПолучения : Дата
}
@enduml
