@startuml СчетаРеглУчетаИгнорируемыеПриОтраженииВМеждународномУчете
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СчетаРеглУчетаИгнорируемыеПриОтраженииВМеждународномУчете as "Счета регл. учета, игнорируемые при отражении в международном учете" <<РегистрыСведений>>
{
..Измерения..
УчетнаяПолитика : Справочник.Учетная политика
СчетРеглУчета : Счет бухгалтерского учета
}
@enduml
