@startuml ПредельныеСуммыУдержанийСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ПредельныеСуммыУдержанийСотрудников as "Предельные суммы удержаний сотрудников" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
Удержание : Удержание
ДокументОснование : Документ.Удержание по прочим операциям\rДокумент.Удержание добровольных взносов в НПФ\rДокумент.Удержание профсоюзных взносов\r...
..Ресурсы..
ПрекратитьПоДостижениюПредела : Булево
Сумма : Число 15, 2
}
@enduml
