@startuml СостояниеНастройкиЗаполненияФормСтатистики
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СостояниеНастройкиЗаполненияФормСтатистики as "Состояние настройки заполнения форм статистики" <<РегистрыСведений>>
{
..Измерения..
Организация : Справочник.Организация
ФормаСтатистики : Справочник.Формы статистики
}
@enduml
