@startuml ЗначенияРазовыхПоказателейРасчетаЗарплатыОрганизаций
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗначенияРазовыхПоказателейРасчетаЗарплатыОрганизаций as "Значения разовых показателей расчета зарплаты (для организаций)" <<РегистрыСведений>>
{
..Измерения..
ПериодДействия : Дата
Организация : Справочник.Организация
Показатель : Справочник.Показатель
..Ресурсы..
Значение : Число 15, 5
}
@enduml
