@startuml БухучетЗарплатыПодразделений
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.БухучетЗарплатыПодразделений as "Бухучет зарплаты подразделений" <<РегистрыСведений>>
{
..Измерения..
Подразделение : Справочник.Подразделение
ИдентификаторСтроки : Число 2, 0
..Ресурсы..
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОтношениеКЕНВД : Отношение к ЕНВД затрат на зарплату
СтатьяФинансирования : Справочник.Статья финансирования
ДоляРаспределения : Число 14, 3
}
@enduml
