@startuml СведенияКонтрактаДоговораСотрудника
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.СведенияКонтрактаДоговораСотрудника as "Сведения контракта, договора сотрудника" <<РегистрыСведений>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ГоловнаяОрганизация : Справочник.Организация
..Ресурсы..
ПредставительНанимателя : Справочник.Физическое лицо
ДолжностьПредставителяНанимателя : Справочник.Должность
ОснованиеПредставителяНанимателя : Строка
ВидАктаГосоргана : Строка
ДатаОкончания : Дата
СрочныйДоговор : Булево
СезонныйДоговор : Булево
СрокЗаключенияДоговора : Строка
ОснованиеСрочногоДоговора : Справочник.Основание заключения срочного трудового договора
ОборудованиеРабочегоМеста : Строка
ИныеУсловияДоговора : Строка
УдалитьДатаНачала : Дата
УдалитьДатаДоговораКонтракта : Дата
УдалитьНомерДоговораКонтракта : Строка
УдалитьПоступлениеНаСлужбуВпервые : Булево
УдалитьСпособПоступленияНаСлужбу : Строка
Организация : Справочник.Организация
}
@enduml
