@startuml ЦеныНоменклатурыПоставщиков
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЦеныНоменклатурыПоставщиков as "Цены номенклатуры поставщиков" <<РегистрыСведений>>
{
..Измерения..
Партнер : Справочник.Партнер
ВидЦеныПоставщика : Справочник.Вид цены поставщика
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
УдалитьСоглашение : Справочник.Соглашение об условиях закупок
..Ресурсы..
Цена : Число 15, 2
Упаковка : Справочник.Упаковка
Валюта : Справочник.Валюта
..Реквизиты..
НоменклатураПоставщика : Справочник.Номенклатура поставщика
}
@enduml
