@startuml ОперацияМеждународный
'!include templates.wsd
'..\include templates.wsd
class Документ.ОперацияМеждународный as "Операция (международный учет)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
СодержаниеОперации : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
ВводитьПериодПоСтрокам : Булево
..Табличная часть \n ЗаполнениеДвижений..
Документ : Документ.Внутреннее потребление товаров\rДокумент.Подготовка к передаче НМА\rДокумент.Списание ОС\r...
Примечание : Строка
..Движения..
ФактическиеДанныеБюджетирования : Обороты
Международный : РегистрБухгалтерии
}
@enduml
