@startuml ЗаказНаРемонт
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаказНаРемонт as "Заказ на ремонт" <<Документы>>
{
..Реквизиты..
ОбъектЭксплуатации : Справочник.Объект эксплуатации
Статус : Статусы заказов на ремонт
ДатаНачала : Дата
ДатаЗавершения : Дата
НаименованиеРабот : Строка
Подразделение : Справочник.Подразделение
ТехРешение : Строка
Ответственный : Справочник.Пользователь
Организация : Справочник.Организация
РемонтноеМероприятие : Справочник.Ремонтное мероприятие
ДатаНачалаФактическая : Дата
ДатаЗавершенияФактическая : Дата
Назначение : Справочник.Назначение
МаксимальныйКодРемонта : Число 10, 0
МаксимальныйКодСтрокиНоменклатуры : Число 10, 0
МаксимальныйКодСтрокиТрудозатрат : Число 10, 0
ХозяйственнаяОперация : Хозяйственные операции
Комментарий : Строка
Автор : Справочник.Пользователь
НаправлениеДеятельности : Справочник.Направление деятельности
ДоступныТрудозатраты : Булево
..Табличная часть \n Ремонты..
Узел : Справочник.Узел объекта эксплуатации
ВидРемонта : Справочник.Вид ремонта
РемонтныйЦикл : Булево
СтатьяРасходов : Статья расходов
КодРемонта : Число 10, 0
СпособОтраженияЗарплаты : Справочник.Способ отражения зарплаты
..Табличная часть \n МатериалыИРаботы..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
КодСтроки : Число 10, 0
Отменено : Булево
Склад : Справочник.Склад (складская территория)
ВариантОбеспечения : Варианты обеспечения
КодРемонта : Число 10, 0
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
..Табличная часть \n Трудозатраты..
ВидРабот : Справочник.Вид работ сотрудников
Количество : Число 15, 3
Отменено : Булево
Бригада : Справочник.Бригады
КодРемонта : Число 10, 0
КодСтроки : Число 10, 0
..Табличная часть \n РабочиеЦентры..
РабочийЦентр : Справочник.Рабочий центр
ДатаНачала : Дата
ДатаЗавершения : Дата
..Табличная часть \n УстраняемыеДефекты..
Дефект : Документ.Регистрация дефекта
..Движения..
ТоварыКОтгрузке : Остатки
ПланРемонтов : РегистрСведений
ГрафикОтгрузкиТоваров : Остатки
РемонтыРабочихЦентров : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
ПериодыАктуальностиОбъектовЭксплуатации : РегистрСведений
ОбеспечениеЗаказов : Остатки
ОбеспечениеЗаказовРаботами : Остатки
СвободныеОстатки : Остатки
ТрудозатратыКОформлению : Остатки
ЗаказыНаВнутреннееПотребление : Остатки
}
@enduml
