@startuml ВосстановлениеВДолжности
'!include templates.wsd
'..\include templates.wsd
class Документ.ВосстановлениеВДолжности as "Восстановление в должности" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
Должность : Справочник.Должность
ДолжностьПоШтатномуРасписанию : Справочник.Позиция
ДатаВосстановления : Дата
КоличествоСтавок : Число 22, 20
ВидЗанятости : Виды занятости
ГрафикРаботы : Справочник.График работы
СпособРасчетаАванса : Способы расчета аванса
Аванс : Число 15, 2
УсловияПриема : Строка
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
НачисленияУтверждены : Булево
УправленческиеНачисленияУтверждены : Булево
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОтношениеКЕНВД : Отношение к ЕНВД затрат на зарплату
СтатьяФинансирования : Справочник.Статья финансирования
ИсправленныйДокумент : Документ.Восстановление в должности
ПорядокРасчетаСтоимостиЕдиницыВремени : Порядок расчета стоимости часа (дня) оплаты труда сотрудников
СовокупнаяТарифнаяСтавка : Число 15, 5
ВидТарифнойСтавки : Виды тарифных ставок
РазрядКатегория : Справочник.Квалификационный разряд (категория)
ВидДоговора : Виды договоров с сотрудниками
СрочныйДоговор : Булево
ДатаЗавершенияТрудовогоДоговора : Дата
ОснованиеСрочногоДоговора : Справочник.Основание заключения срочного трудового договора
СрокЗаключенияДоговора : Строка
ОснованиеПредставителяНанимателя : Строка
СпособПоступленияНаСлужбу : Строка
ПоступлениеНаСлужбуВпервые : Булево
ВидАктаГосоргана : Строка
ОборудованиеРабочегоМеста : Строка
ИныеУсловияДоговора : Строка
Грейд : Строка
Территория : Справочник.Территория
ПКУ : Справочник.Квалификационный разряд (категория)
СезонныйДоговор : Булево
ДатаУвольнения : Дата
ДокументУвольнения : Документ.Увольнение
КомпенсироватьМоральныйВред : Булево
СуммаКомпенсации : Число 15, 2
ДатаВыплатыКомпенсаций : Дата
ОснованиеВосстановленияВДолжности : Строка
Бухгалтер : Справочник.Физическое лицо
РаботникКадровойСлужбы : Справочник.Физическое лицо
Исполнитель : Справочник.Физическое лицо
ДолжностьИсполнителя : Справочник.Должность
ДатаПрисвоения : Дата
КлассныйЧинРанг : Строка
Решение : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Начисления..
Начисление : Начисление
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Размер : Число 15, 2
..Табличная часть \n УправленческиеНачисления..
Начисление : Начисление
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Размер : Число 15, 2
..Табличная часть \n Показатели..
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Показатель : Справочник.Показатель
Значение : Число 15, 5
..Табличная часть \n ЕжегодныеОтпуска..
ВидЕжегодногоОтпуска : Справочник.Вид отпуска
КоличествоДнейВГод : Число 2, 0
..Табличная часть \n Льготы..
Льгота : Начисление
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Размер : Число 15, 2
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
СведенияКонтрактаДоговораСотрудника : РегистрСведений
ПорядокРасчетаСтоимостиЕдиницыВремениСотрудников : РегистрСведений
ЗанятыеПозицииШтатногоРасписания : Остатки
УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников : РегистрСведений
ПКУСотрудников : РегистрСведений
ГрафикРаботыСотрудников : РегистрСведений
ПрименениеДополнительныхПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
ДанныеСостоянийСотрудников : РегистрСведений
ПрименениеПлановыхНачислений : РегистрСведений
ПлановыеАвансы : РегистрСведений
КадроваяИсторияСотрудников : РегистрСведений
ТерриторииСотрудников : РегистрСведений
РазрядыКатегорииСотрудников : РегистрСведений
ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
БухучетПлановыхНачислений : РегистрСведений
ПоложенныеВидыЕжегодныхОтпусков : РегистрСведений
ПараметрыПериодовСтажаПФР : РегистрСведений
ПлановыеНачисления : РегистрСведений
РеестрКадровыхПриказов : РегистрСведений
}
@enduml
