@startuml ЗаявлениеНаПредоставлениеСтандартныхВычетовПоНДФЛ
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаявлениеНаПредоставлениеСтандартныхВычетовПоНДФЛ as "Заявление на вычеты по НДФЛ" <<Документы>>
{
..Реквизиты..
Месяц : Дата
Организация : Справочник.Организация
Сотрудник : Справочник.Физическое лицо
КодВычетаЛичный : Справочник.Вид вычетов НДФЛ
УдалитьКодВычетаЛичный : Справочник.(не используется) Виды вычетов НДФЛ
ИзменитьВычетыНаДетей : Булево
ИзменитьЛичныйВычет : Булево
Ответственный : Справочник.Пользователь
Комментарий : Строка
ДокументПодтверждающийПравоНаЛичныйВычет : Строка
..Табличная часть \n ВычетыНаДетей..
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
ДействуетДо : Дата
ДокументПодтверждающийПравоНаВычет : Строка
..Движения..
СтандартныеВычетыФизическихЛицНДФЛ : РегистрСведений
УдалитьСтандартныеВычетыНаДетейНДФЛ : РегистрСведений
ПрименениеСтандартныхВычетовПоНДФЛ : РегистрСведений
СтандартныеВычетыНаДетейНДФЛ : РегистрСведений
}
@enduml
