@startuml ЗаявкаНаОткрытиеЛицевыхСчетовСотрудников
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаявкаНаОткрытиеЛицевыхСчетовСотрудников as "Заявка на открытие лицевых счетов" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ЗарплатныйПроект : Справочник.Зарплатный проект
НомерРеестра : Число 10, 0
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
ФизическоеЛицо : Справочник.Физическое лицо
Должность : Справочник.Должность
ЭмбоссированныйТекст1 : Строка
ЭмбоссированныйТекст2 : Строка
ЭмбоссированныйТекст3 : Строка
СистемаРасчетовПоБанковскимКартам : Строка
СуммаПервоначальногоПополнения : Число 15, 2
ЯвляетсяЗарплатнойКартой : Булево
ОплатаЗарплатнойКарты : Виды оплаты зарплатной карты
ЯвляетсяСотрудникомБанка : Булево
ИспользуетсяОвердрафт : Булево
КатегорияСотрудника : Категории сотрудников обмена с банками
ЯвляетсяУчастникомБонуснойПрограммы : Булево
БонуснаяПрограмма : Бонусные программы банков
НомерУчастникаБонуснойПрограммы : Строка
ТарифСледующийГод : Число 15, 2
ТарифТекущийГод : Число 15, 2
ИспользованиеДоставкиКорреспонденции : Булево
СпособРассылкиОтчета : Способы доставки корреспонденции банка
АдресЭлектроннойПочты : Строка
СчетДебета : Строка
НомерМобильногоТелефона : Строка
НомерМобильногоТелефонаПредставление : Строка
ОператорСвязи : Строка
ИспользованиеМобильногоБанка : Булево
ТарифМобильногоБанка : Тарифы мобильного банка
РазрешитьПередачуИнформацииВБКИ : Булево
КонтрольнаяИнформация : Строка
НомерМиграционнойКарты : Строка
ДатаНачалаПребыванияМиграционнойКарты : Дата
ДатаОкончанияПребыванияМиграционнойКарты : Дата
ВидМиграционногоДокумента : Справочник.Вид документа физических лиц
НомерМиграционногоДокумента : Строка
ДатаНачалаПребыванияМиграционногоДокумента : Дата
ДатаОкончанияПребыванияМиграционногоДокумента : Дата
ПрогнозируемыйМесячныйДоход : Число 15, 2
ТабельныйНомер : Строка
ДатаПриема : Дата
ДеньВыплатыЗарплаты : Число 2, 0
КодВидаВклада : Строка
КодПодвидаВклада : Строка
ВалютаВклада : Справочник.Валюта
ДокументВид : Справочник.Вид документа физических лиц
ДокументСерия : Строка
ДокументНомер : Строка
ДокументДатаВыдачи : Дата
ДокументСрокДействия : Дата
ДокументКемВыдан : Строка
ДокументКодПодразделения : Строка
ДокументПредставление : Строка
ДокументНомерСерия : Строка
Пол : Пол физического лица
ДатаРождения : Дата
МестоРождения : Строка
МестоРожденияПредставление : Строка
АдресДляИнформирования : Строка
АдресДляИнформированияПредставление : Строка
АдресМестаРаботы : Строка
АдресМестаРаботыПредставление : Строка
АдресПоПрописке : Строка
АдресПоПропискеПредставление : Строка
АдресМестаПроживания : Строка
АдресМестаПроживанияПредставление : Строка
ТелефонДомашний : Строка
ТелефонДомашнийПредставление : Строка
ТелефонРабочий : Строка
ТелефонРабочийПредставление : Строка
ЯвляетсяРезидентом : Булево
Гражданство : Справочник.Страна мира
Фамилия : Строка
Имя : Строка
Отчество : Строка
ИдентификаторСтрокиФикс : Число 5, 0
ИдентификаторДизайна : Строка
ПВК : Строка
ПриложениеКартаКод : Строка
ПриложениеКартаПараметры : Строка
СтраховойНомерПФР : Строка
..Табличная часть \n ФиксацияИзменений..
ИмяРеквизита : Строка
Путь : Строка
ИдентификаторСтроки : Число 5, 0
}
@enduml
