@startuml РегистрацияПрочихКонтролируемыхСделок
'!include templates.wsd
'..\include templates.wsd
class Документ.РегистрацияПрочихКонтролируемыхСделок as "Регистрация прочих контролируемых сделок" <<Документы>>
{
..Реквизиты..
УведомлениеОКонтролируемойСделке : Документ.Уведомление о контролируемых сделках
Организация : Справочник.Организация
Контрагент : Справочник.Контрагент
ДоговорКонтрагента : Справочник.Договор с контрагентом
ВалютаДокумента : Справочник.Валюта
СуммаДокумента : Число 15, 2
Комментарий : Строка
..Табличная часть \n Сделки..
ДатаСовершенияСделки : Дата
ПредметСделки : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР
НаименованиеПредметаСделки : Строка
Количество : Число 10, 3
ЕдиницаИзмерения : Справочник.Упаковка
СуммаБезНДСВРублях : Число 15, 2
СуммаБезНДСВВалютеРасчетов : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДСВРублях : Число 15, 2
СуммаНДСВВалютеРасчетов : Число 15, 2
ТипПредметаСделки : Типы предметов контролируемых сделок
ТипКонтролируемойСделки : Типы контролируемых сделок
СтранаПроисхожденияПредметаСделки : Справочник.Страна мира
Грузоотправитель : Справочник.Организация\rСправочник.Контрагент
Грузополучатель : Справочник.Организация\rСправочник.Контрагент
ОперацияОблагаетсяЕНВД : Булево
..Движения..
КонтролируемыеСделкиОрганизаций : Обороты
}
@enduml
