@startuml ИндексацияШтатногоРасписания
'!include templates.wsd
'..\include templates.wsd
class Документ.ИндексацияШтатногоРасписания as "Индексация штатного расписания" <<Документы>>
{
..Реквизиты..
МесяцИндексации : Дата
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
КоэффициентИндексации : Число 5, 4
Ответственный : Справочник.Пользователь
Комментарий : Строка
ВидИндексацииГосударственныхСлужащих : Строка
ИндексацияВоеннослужащих : Булево
..Табличная часть \n ИндексируемыеПоказатели..
Показатель : Справочник.Показатель
СпособОкругления : Справочник.Способ округления
..Табличная часть \n Позиции..
ПозицияШтатногоРасписания : Справочник.Позиция
ИдентификаторСтрокиПозиции : Число 5, 0
ОкладТариф : Число 15, 3
ОкладТарифМин : Число 15, 3
ОкладТарифМакс : Число 15, 3
ФОТ : Число 19, 2
ФОТМин : Число 19, 2
ФОТМакс : Число 19, 2
РайонныйКоэффициентРазмер : Число 15, 2
РайонныйКоэффициентРазмерМин : Число 15, 2
РайонныйКоэффициентРазмерМакс : Число 15, 2
СевернаяНадбавкаРазмер : Число 15, 2
СевернаяНадбавкаРазмерМин : Число 15, 2
СевернаяНадбавкаРазмерМакс : Число 15, 2
УдалитьТарифнаяСетка : Справочник.Тарифная группа
УдалитьТарифнаяСеткаНадбавки : Справочник.Тарифная группа
УдалитьРазрядКатегорияНадбавки : Справочник.Квалификационный разряд (категория)
НадбавкаЗаВредностьРазмер : Число 15, 2
НадбавкаЗаВредностьРазмерМин : Число 15, 2
НадбавкаЗаВредностьРазмерМакс : Число 15, 2
..Табличная часть \n Начисления..
ИдентификаторСтрокиПозиции : Число 5, 0
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Начисление : Начисление
Размер : Число 15, 2
РазмерМин : Число 15, 2
РазмерМакс : Число 15, 2
..Табличная часть \n Показатели..
ИдентификаторСтрокиПозиции : Число 5, 0
Показатель : Справочник.Показатель
Значение : Число 15, 5
ЗначениеМин : Число 15, 5
ЗначениеМакс : Число 15, 5
..Движения..
УдалитьИсторияИспользованияДолжностей : РегистрСведений
ИсторияПоказателейПоШтатномуРасписанию : РегистрСведений
ИсторияИспользованияШтатногоРасписания : РегистрСведений
УдалитьИсторияИспользованияПодразделений : РегистрСведений
ИсторияНачисленийПоШтатномуРасписанию : РегистрСведений
}
@enduml
