@startuml ПередачаМатериаловВПроизводство
'!include templates.wsd
'..\include templates.wsd
class Документ.ПередачаМатериаловВПроизводство as "Передача материалов в производство" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Склад : Справочник.Склад (складская территория)
Распоряжение : Документ.Заказ на производство\rДокумент.Заказ материалов в производство\rДокумент.Корректировка заказа материалов\r...
Подразделение : Справочник.Подразделение
Ответственный : Справочник.Пользователь
Комментарий : Строка
ПередачаПоРаспоряжениям : Булево
ХозяйственнаяОперация : Хозяйственные операции
Статус : Статусы передач материалов в производство
ПотреблениеДляДеятельности : Типы налогообложения НДС
СостояниеЗаполненияМногооборотнойТары : Состояния заполнения многооборотной тары
ВидыЗапасовУказаныВручную : Булево
ВидЦены : Справочник.Вид цены
НаправлениеДеятельности : Справочник.Направление деятельности
ДокументОснование : Документ.Приобретение товаров и услуг\rДокумент.Поступление сырья от давальца\rДокумент.Заказ давальца
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
НазначениеОтправителя : Справочник.Назначение
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
КодСтроки : Число 10, 0
СтатусУказанияСерий : Число 2, 0
Распоряжение : Документ.Заказ на производство\rДокумент.Заказ материалов в производство\rДокумент.Корректировка заказа материалов\r...
ИдентификаторСтроки : Строка
Серия : Справочник.Серия номенклатуры
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
СтатусУказанияСерийОтправитель : Число 2, 0
СтатусУказанияСерийПолучатель : Число 2, 0
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
..Табличная часть \n ВидыЗапасов..
АналитикаУчетаНоменклатуры : Справочник.Номенклатура\rСправочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
ИдентификаторСтроки : Строка
ФизическоеЛицо : Справочник.Физическое лицо
ОбъектЭксплуатации : Справочник.Объект эксплуатации
ВидЗапасовПолучателя : Справочник.Вид запасов
Серия : Справочник.Серия номенклатуры
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
Назначение : Справочник.Назначение
..Табличная часть \n Серии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
НазначениеОтправителя : Справочник.Назначение
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ТоварыКОтгрузке : Остатки
ЗаказыМатериаловВПроизводство : Остатки
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ТоварыКОформлениюОтчетовКомитенту : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНМатериалы : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
Международный : РегистрБухгалтерии
НДСЗаписиКнигиПродаж : Обороты
ТоварыОрганизацийКПередаче : Остатки
КнигаУчетаДоходовИРасходов : Обороты
МатериалыИРаботыВПроизводстве : Остатки
СвободныеОстатки : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
ПартииПроизводственныхЗатрат : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
