@startuml РегламентированныйОтчет
'!include templates.wsd
'..\include templates.wsd
class Документ.РегламентированныйОтчет as "Регламентированный отчет" <<Документы>>
{
..Реквизиты..
Вид : Число 3, 0
ВидОтчетности : Виды отчетности
ВыбраннаяФорма : Строка
ДанныеОтчета : Хранилище значения
ДатаНачала : Дата
ДатаОкончания : Дата
ДатаПодписи : Дата
ДеревоНастройкиСтраниц : Хранилище значения
ЕдиницаИзмерения : Порядки округления отчетности
ИсточникОтчета : Строка
КодНалоговогоОргана : Строка
КодНалоговогоОрганаПосредника : Строка
Комментарий : Строка
НаименованиеОтчета : Строка
НомерПачки : Число 5, 0
Организация : Справочник.Организация
Период : Строка
Периодичность : Периодичность
ПредставлениеВида : Строка
ПредставлениеПериода : Строка
ТочностьЕдиницыИзмерения : Число 1, 0
ФорматВыгрузки : Строка
УдалитьКПП : Строка
КПП : Строка
СтатусОтчета : Строка
Банк : Справочник.Банк
Идентификатор : Строка
}
@enduml
