@startuml ЗаказНаСборку
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаказНаСборку as "Заказ на сборку (разборку)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Склад : Справочник.Склад (складская территория)
ДокументОснование : Документ.Заказ клиента
Ответственный : Справочник.Пользователь
Статус : Статусы внутренних заказов
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Комментарий : Строка
НачалоСборкиРазборки : Дата
ОкончаниеСборкиРазборки : Дата
ЖелаемаяДатаПоступления : Дата
ДлительностьСборкиРазборки : Число 3, 0
МаксимальныйКодСтроки : Число 10, 0
ВариантКомплектации : Справочник.Вариант комплектации
Сделка : Справочник.Сделка с клиентом
Подразделение : Справочник.Подразделение
СтатусУказанияСерий : Число 2, 0
Назначение : Справочник.Назначение
НазначениеТовары : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
ВариантОбеспечения : Варианты обеспечения
КоличествоУпаковокОтменено : Число 15, 3
КоличествоОтменено : Число 15, 3
НаправлениеДеятельности : Справочник.Направление деятельности
ХозяйственнаяОперация : Хозяйственные операции
ОбосабливатьПоНазначениюЗаказа : Булево
ВариантПриемкиТоваров : Варианты приемки товаров
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Упаковка : Справочник.Упаковка
Количество : Число 15, 3
КоличествоУпаковок : Число 15, 3
КодСтроки : Число 10, 0
СтатусУказанияСерий : Число 2, 0
УказыватьСерии : Булево
ВариантОбеспечения : Варианты обеспечения
Серия : Справочник.Серия номенклатуры
Отменено : Булево
..Табличная часть \n Серии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
УдалитьУказыватьСерии : Булево
..Движения..
ТоварыКОтгрузке : Остатки
ГрафикОтгрузкиТоваров : Остатки
ЗаказыНаСборку : Остатки
ФактическиеДанныеБюджетирования : Обороты
ОбеспечениеЗаказов : Остатки
ДвижениеТоваров : Обороты
СвободныеОстатки : Остатки
ГрафикПоступленияТоваров : Остатки
ТоварыКПоступлению : Остатки
}
@enduml
