@startuml ДопЛистКнигиПродажДляПередачиВЭлектронномВиде
'!include templates.wsd
'..\include templates.wsd
class Документ.ДопЛистКнигиПродажДляПередачиВЭлектронномВиде as "Доп. лист книги продаж для передачи в электронном виде" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
НалоговыйПериод : Дата
ПериодСоставления : Дата
НомерДополнительногоЛиста : Число 10, 0
Реорганизация : Булево
ВсегоПродаж : Число 15, 2
СуммаБезНДС18 : Число 15, 2
НДС18 : Число 15, 2
СуммаБезНДС10 : Число 15, 2
НДС10 : Число 15, 2
НДС0 : Число 15, 2
СуммаБезНДС20 : Число 15, 2
НДС20 : Число 15, 2
СуммаСовсемБезНДС : Число 15, 2
ВсегоПродажДо : Число 15, 2
СуммаБезНДС18До : Число 15, 2
НДС18До : Число 15, 2
СуммаБезНДС10До : Число 15, 2
НДС10До : Число 15, 2
НДС0До : Число 15, 2
СуммаБезНДС20До : Число 15, 2
НДС20До : Число 15, 2
СуммаСовсемБезНДСДо : Число 15, 2
ПериодПоСКНП : Строка
ИФНС : Справочник.Регистрация в налоговом органе
Подписант : Справочник.Физическое лицо
Ответственный : Справочник.Пользователь
Комментарий : Строка
ПредставлениеОтчета : Хранилище значения
ДанныеОтчета : Хранилище значения
..Табличная часть \n ТабличнаяЧасть..
ДатаНомер : Строка
НомерДатаИсправления : Строка
НомерДатаКорректировки : Строка
НомерДатаИсправленияКорректировки : Строка
ДатаОплаты : Строка
Покупатель : Строка
ПокупательИНН : Строка
ПокупательКПП : Строка
ВсегоПродаж : Число 15, 2
СуммаБезНДС18 : Число 15, 2
НДС18 : Число 15, 2
СуммаБезНДС10 : Число 15, 2
НДС10 : Число 15, 2
НДС0 : Число 15, 2
СуммаБезНДС20 : Число 15, 2
НДС20 : Число 15, 2
СуммаСовсемБезНДС : Число 15, 2
Ном : Число 10, 0
СчетФактура : Строка
}
@enduml
