@startuml КассоваяСмена
'!include templates.wsd
'..\include templates.wsd
class Документ.КассоваяСмена as "Кассовая смена" <<Документы>>
{
..Реквизиты..
ДатаПервогоНепереданногоФД : Дата
ДатаСменыККТ : Дата
КассаККМ : Справочник.Кассы ККМ\rСправочник.Касса
КоличествоНепереданныхФД : Число 10, 0
КоличествоФД : Число 10, 0
КоличествоЧеков : Число 10, 0
Комментарий : Строка
НачалоКассовойСмены : Дата
НеобходимаСтрочнаяЗаменаФН : Булево
НомерСменыККТ : Число 10, 0
ОкончаниеКассовойСмены : Дата
Организация : Справочник.Организация
ПамятьФНПереполнена : Булево
ПревышеноВремяОжиданияОтветаОФД : Булево
РесурсФНИсчерпан : Булево
Статус : Статусы кассовой смены
ФДОЗакрытииСмены : Хранилище значения
ФискальноеУстройство : Справочник.Экземпляр подключаемого оборудования
СтатусРегламентныхОпераций : Статусы регламентных операций кассовой смены
}
@enduml
