@startuml ПереводКДругомуРаботодателю
'!include templates.wsd
'..\include templates.wsd
class Документ.ПереводКДругомуРаботодателю as "Перевод к другому работодателю" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ДатаУвольнения : Дата
НоваяОрганизация : Справочник.Организация
ДатаПриема : Дата
Должность : Справочник.Должность
ГрафикРаботы : Справочник.График работы
КоличествоСтавок : Число 22, 20
ДолжностьПоШтатномуРасписанию : Справочник.Позиция
СпособРасчетаАванса : Способы расчета аванса
Аванс : Число 15, 2
СтатьяТКРФ : Справочник.Основание увольнения
УдалитьСтатьяТКРФ : Справочник.(не используется) Основания увольнения
ПереноситьОстаткиОтпуска : Булево
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
РуководительНовойОрганизации : Справочник.Физическое лицо
ДолжностьРуководителяНовойОрганизации : Справочник.Должность
РазрядКатегория : Справочник.Квалификационный разряд (категория)
Ответственный : Справочник.Пользователь
Комментарий : Строка
ПКУ : Справочник.Квалификационный разряд (категория)
..Табличная часть \n ДанныеОДоходах..
Месяц : Дата
Сумма : Число 13, 2
..Табличная часть \n ДанныеОЗаработкеДляРасчетаПособий..
Месяц : Дата
Сумма : Число 13, 2
..Табличная часть \n Начисления..
Действие : Действия с начислениями и удержаниями
Начисление : Начисление
ИдентификаторСтрокиВидаРасчета : Число 7, 0
..Табличная часть \n Показатели..
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Показатель : Справочник.Показатель
Значение : Число 15, 5
}
@enduml
