@startuml ПерерасчетНДФЛ
'!include templates.wsd
'..\include templates.wsd
class Документ.ПерерасчетНДФЛ as "Перерасчет НДФЛ" <<Документы>>
{
..Реквизиты..
НалоговыйПериод : Число 4, 0
Организация : Справочник.Организация
МесяцПерерасчета : Дата
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
ОбособленноеПодразделение : Справочник.Территория\rСправочник.Подразделение
Сотрудник : Справочник.Физическое лицо
КатегорияДохода : Категории доходов НДФЛ
МесяцНалоговогоПериода : Дата
НалогПоСтавке09 : Число 10, 0
НалогПоСтавке13 : Число 10, 0
НалогПоСтавке35 : Число 10, 0
ЗачтеноАвансовыхПлатежейПоСтавке09 : Число 10, 0
ЗачтеноАвансовыхПлатежейПоСтавке13 : Число 10, 0
ЗачтеноАвансовыхПлатежейПоСтавке35 : Число 10, 0
УдалитьНалогПоСтавке13КЗачетуВозврату : Число 10, 0
УдалитьНалогПоСтавке35КЗачетуВозврату : Число 10, 0
ПримененныйВычетЛичный : Число 12, 2
ПримененныйВычетЛичныйКодВычета : Справочник.Вид вычетов НДФЛ
УдалитьПримененныйВычетЛичныйКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
ПримененныйВычетЛичныйКЗачетуВозврату : Число 12, 2
ПримененныйВычетЛичныйКЗачетуВозвратуКодВычета : Справочник.Вид вычетов НДФЛ
УдалитьПримененныйВычетЛичныйКЗачетуВозвратуКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
ИдентификаторСтрокиНДФЛ : Число 7, 0
УдалитьПримененныйВычетНаДетей : Число 12, 2
УдалитьПримененныйВычетНаДетейДвойной : Число 12, 2
УдалитьПримененныйВычетНаДетейДвойнойВторой : Число 12, 2
УдалитьПримененныйВычетНаДетейИнвалидов : Число 15, 2
УдалитьПримененныйВычетНаДетейИнвалидовДвойной : Число 15, 2
УдалитьПримененныйВычетНаДетейИнвалидовДвойнойВторой : Число 12, 2
УдалитьПримененныйВычетИмущественныйРасходы : Число 12, 2
УдалитьПримененныйВычетИмущественныйПроцентыПоКредитам : Число 12, 2
УдалитьПримененныйВычетИмущественныйПроцентыПриПерекредитовании : Число 12, 2
УдалитьПримененныйВычетНаВторогоРебенка : Число 12, 2
УдалитьПримененныйВычетНаВторогоРебенкаДвойной : Число 12, 2
УдалитьПримененныйВычетНаВторогоРебенкаДвойнойВторой : Число 12, 2
УдалитьПримененныйВычетНаТретьегоРебенка : Число 12, 2
УдалитьПримененныйВычетНаТретьегоРебенкаДвойной : Число 12, 2
УдалитьПримененныйВычетНаТретьегоРебенкаДвойнойВторой : Число 12, 2
..Табличная часть \n ПримененныеВычетыНаДетейИИмущественные..
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
РазмерВычета : Число 12, 2
ИдентификаторСтрокиНДФЛ : Число 7, 0
..Табличная часть \n КорректировкиВыплаты..
ФизическоеЛицо : Справочник.Физическое лицо
ОбособленноеПодразделение : Справочник.Территория\rСправочник.Подразделение
КорректировкаВыплаты : Число 15, 2
ИдентификаторСтроки : Число 7, 0
..Движения..
РасчетыНалогоплательщиковСБюджетомПоНДФЛ : Остатки
ВзаиморасчетыССотрудниками : Остатки
НачисленияУдержанияПоСотрудникам : Обороты
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
ИмущественныеВычетыНДФЛ : Остатки
ПредоставленныеСтандартныеИСоциальныеВычетыНДФЛ : Обороты
БухучетНачисленияУдержанияПоСотрудникам : Обороты
ЗарплатаКВыплате : Остатки
АвансовыеПлатежиИностранцевПоНДФЛ : Остатки
}
@enduml
