@startuml СписаниеЗатратНаВыпуск
'!include templates.wsd
'..\include templates.wsd
class Документ.СписаниеЗатратНаВыпуск as "Списание затрат на выпуск" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Спецификация : Справочник.Ресурсная спецификация
Ответственный : Справочник.Пользователь
Комментарий : Строка
АналитикаУчетаПродукции : Справочник.Ключ аналитики учета номенклатуры
Назначение : Справочник.Назначение
Количество : Число 15, 3
Подразделение : Справочник.Подразделение
..Табличная часть \n ВыходныеИзделия..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Упаковка : Справочник.Упаковка
ДоляСтоимости : Число 10, 0
Распоряжение : Документ.Выпуск продукции и выполнение работ
КодСтроки : Число 10, 0
Подразделение : Справочник.Подразделение
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
..Табличная часть \n ВозвратныеОтходы..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Упаковка : Справочник.Упаковка
СтатьяКалькуляции : Справочник.Статьи калькуляции
Распоряжение : Документ.Выпуск продукции и выполнение работ
КодСтроки : Число 10, 0
Подразделение : Справочник.Подразделение
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
..Табличная часть \n МатериалыИУслуги..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
СтатьяКалькуляции : Справочник.Статьи калькуляции
Количество : Число 15, 3
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
Назначение : Справочник.Назначение
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
Подразделение : Справочник.Подразделение
..Табличная часть \n Трудозатраты..
ВидРабот : Справочник.Вид работ сотрудников
Количество : Число 15, 3
СтатьяКалькуляции : Справочник.Статьи калькуляции
Подразделение : Справочник.Подразделение
..Табличная часть \n Серии..
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Серия : Справочник.Серия номенклатуры
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Подразделение : Справочник.Подразделение
СтатьяКалькуляции : Справочник.Статьи калькуляции
..Движения..
ТрудозатратыНезавершенногоПроизводства : Остатки
ДвиженияСерийТоваров : Обороты
ПрочиеРасходы : Остатки
ФактическиеДанныеБюджетирования : Обороты
МатериалыИРаботыВПроизводстве : Остатки
РаспоряженияНаСписаниеПоНормативам : Остатки
ПартииПроизводственныхЗатрат : Остатки
ПартииНезавершенногоПроизводства : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
