@startuml Встреча
'!include templates.wsd
'..\include templates.wsd
class Документ.Встреча as "Встреча" <<Документы>>
{
..Реквизиты..
Автор : Справочник.Пользователь
Важность : Варианты важности взаимодействия
ДатаНачала : Дата
ДатаОкончания : Дата
МестоПроведенияВстречи : Строка
Описание : Строка
Ответственный : Справочник.Пользователь
Удалить_Рассмотрено : Булево
Удалить_РассмотретьПосле : Дата
УдалитьПредмет : Справочник.Маркетинговое мероприятие\rДокумент.Исходящее электронное письмо\rДокумент.Запланированное взаимодействие\r...
СписокУчастников : Строка
ВзаимодействиеОснование : Документ.Исходящее электронное письмо\rДокумент.Запланированное взаимодействие\rДокумент.Входящее электронное письмо\r...
Тема : Строка
Комментарий : Строка
..Табличная часть \n Участники..
Контакт : Справочник.Строковый контакт взаимодействий\rСправочник.Пользователь\rСправочник.Партнер\r...
ПредставлениеКонтакта : Строка
КакСвязаться : Строка
..Табличная часть \n НаборыЗначенийДоступа..
НомерНабора : Число 4, 0
ЗначениеДоступа : Справочник.Статьи бюджетов\rСправочник.Вид номенклатуры\rСправочник.Номенклатура\r...
Уточнение : Справочник.Идентификатор объекта метаданных
Чтение : Булево
Изменение : Булево
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
