@startuml ТранспортноеСообщение
'!include templates.wsd
'..\include templates.wsd
class Документ.ТранспортноеСообщение as "Транспортное сообщение" <<Документы>>
{
..Реквизиты..
ЦиклОбмена : Справочник.Циклы обмена
Тип : Типы транспортных сообщений
Отправитель : Справочник.(не используется) Налоговые органы\rСправочник.(не используется) Серверы документооборота\rСправочник.Налоговые органы\r...
Получатель : Справочник.(не используется) Налоговые органы\rСправочник.(не используется) Серверы документооборота\rСправочник.Налоговые органы\r...
УчетнаяЗапись : Справочник.(не используется) Учетные записи документооборота\rСправочник.Учетные записи документооборота
Статус : Статусы писем
Тема : Строка
ТекстПисьма : Строка
ИдентификаторСообщения : Строка
ДатаТранспорта : Дата
Важность : Число 1, 0
Кодировка : Строка
ОтКогоАдрес : Строка
ОтКогоПредставление : Строка
Основание : Документ.Транспортное сообщение
ПротоколСОшибкой : Булево
НеОбрабатывать : Булево
..Табличная часть \n ДополнительныеРеквизитыЗаголовка..
Тип : Строка\rТипы дополнительных реквизитов
Значение : Строка
..Табличная часть \n Кому..
АдресЭлектроннойПочты : Строка
Представление : Строка
..Табличная часть \n Копии..
АдресЭлектроннойПочты : Строка
Представление : Строка
..Табличная часть \n СкрытыеКопии..
АдресЭлектроннойПочты : Строка
Представление : Строка
..Табличная часть \n СертификатыПолучателей..
Сертификат : Справочник.Сертификат 1С-Отчетности
}
@enduml
