@startuml ПередачаОСАрендатору
'!include templates.wsd
'..\include templates.wsd
class Документ.ПередачаОСАрендатору as "Передача ОС арендатору (2.2)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ПодразделениеАрендатора : Справочник.Подразделение
ПодразделениеПолучатель : Справочник.Подразделение
РасчетыМеждуОрганизациямиАрендатор : Булево
Арендатор : Справочник.Организация\rСправочник.Контрагент
СчетУчета : Счет бухгалтерского учета
СчетАмортизации : Счет бухгалтерского учета
СчетУчетаАрендатора : Счет бухгалтерского учета
НачислятьАмортизацию : Булево
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ОС..
ОсновноеСредство : Справочник.Объект эксплуатации
ЗалоговаяСтоимость : Число 15, 2
..Табличная часть \n НачисленнаяАмортизация..
ОбъектУчета : Справочник.Объект эксплуатации
Подразделение : Справочник.Подразделение
СуммаБУ : Число 15, 2
СуммаНУ : Число 15, 2
СуммаПР : Число 15, 2
СуммаВР : Число 15, 2
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ЭтоАмортизационнаяПремия : Булево
ДокументАмортизационнойПремии : Документ.Принятие к учету ОС\rДокумент.Модернизация ОС
ПередаватьРасходыВДругуюОрганизацию : Булево
ОрганизацияПолучательРасходов : Справочник.Организация
СчетПередачиРасходов : Счет бухгалтерского учета
ЭтоЦелевыеСредства : Булево
НаправлениеДеятельности : Справочник.Направление деятельности
..Движения..
МестонахождениеОСБухгалтерскийУчет : РегистрСведений
ПрочиеДоходы : Остатки
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
СпособыОтраженияРасходовПоАмортизацииОСБухгалтерскийУчет : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
СостоянияОСОрганизаций : РегистрСведений
Международный : РегистрБухгалтерии
НачислениеАмортизацииОСБухгалтерскийУчет : РегистрСведений
СчетаБухгалтерскогоУчетаОС : РегистрСведений
ВыручкаИСебестоимостьПродаж : Обороты
НачислениеАмортизацииОСНалоговыйУчет : РегистрСведений
}
@enduml
