@startuml КассовыйЧекКоррекции
'!include templates.wsd
'..\include templates.wsd
class Документ.КассовыйЧекКоррекции as "Кассовый чек коррекции" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
КассаККМ : Справочник.Кассы ККМ\rСправочник.Касса
СуммаДокумента : Число 15, 2
ТипРасчета : Типы расчета денежными средствами
ТипКоррекции : Число 1, 0
Ответственный : Справочник.Пользователь
Комментарий : Строка
НомерЧекаККМ : Число 8, 0
Предписание : Строка
ПробитЧек : Булево
ОснованиеДляКоррекции : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
ДатаДокументаОснования : Дата
НомерДокументаОснования : Строка
ПодключаемоеОборудование : Справочник.Экземпляр подключаемого оборудования
ПредставлениеОснования : Строка
СистемаНалогообложения : Типы систем налогообложения ККТ
СуммаБезНДС : Число 10, 2
СуммаНДС0 : Число 10, 2
СуммаНДС10 : Число 10, 2
СуммаНДС18 : Число 10, 2
СуммаНДС110 : Число 10, 2
СуммаНДС118 : Число 10, 2
..Табличная часть \n Оплата..
ТипОплаты : Типы оплаты ККТ
Сумма : Число 10, 2
}
@enduml
