@startuml РегистрацияНаработокТМЦВЭксплуатации
'!include templates.wsd
'..\include templates.wsd
class Документ.РегистрацияНаработокТМЦВЭксплуатации as "Регистрация наработок ТМЦ в эксплуатации" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Наработки..
ПартияТМЦВЭксплуатации : Справочник.Партии ТМЦ в эксплуатации
ТекущееЗначение : Число 15, 3
ПредельныйОбъем : Число 15, 3
..Движения..
НаработкиТМЦВЭксплуатации : РегистрСведений
}
@enduml
