@startuml КорректировкаИзлишковНедостачПоТоварнымМестам
'!include templates.wsd
'..\include templates.wsd
class Документ.КорректировкаИзлишковНедостачПоТоварнымМестам as "Корректировка излишков и недостач по товарным местам" <<Документы>>
{
..Реквизиты..
Склад : Справочник.Склад (складская территория)
Помещение : Справочник.Помещение
Комментарий : Строка
..Табличная часть \n Товары..
ВидОперации : Виды операций корректировок остатков товаров
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
Упаковка : Справочник.Упаковка
Количество : Число 15, 3
КоличествоУпаковок : Число 15, 3
..Движения..
ТоварныеМестаКОтражениюИзлишковНедостач : Остатки
ДвиженияСерийТоваров : Обороты
ТоварыКОформлениюИзлишковНедостач : Остатки
ТоварыНаСкладах : Остатки
ОбеспечениеЗаказов : Остатки
СвободныеОстатки : Остатки
}
@enduml
