@startuml РаспределениеВозвратныхОтходов
'!include templates.wsd
'..\include templates.wsd
class Документ.РаспределениеВозвратныхОтходов as "Распределение возвратных отходов" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ВыпускПодДеятельность : Типы налогообложения НДС
НаправлениеДеятельности : Справочник.Направление деятельности
ПравилоРаспределения : Справочник.Правило распределения расходов
БазаРаспределения : Типы показателей для распределения статей расходов
КоличествоПоПравилу : Число 15, 3
СтатьяКалькуляции : Справочник.Статьи калькуляции
ВидЦены : Справочник.Вид цены
Подразделение : Справочник.Подразделение
Получатель : Справочник.Подразделение\rСправочник.Склад (складская территория)
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
Количество : Число 15, 3
Назначение : Справочник.Назначение
Цена : Число 15, 2
Сумма : Число 15, 2
Ответственный : Справочник.Пользователь
Комментарий : Строка
УдалитьВидЗапасов : Справочник.Вид запасов
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
Валюта : Справочник.Валюта
..Табличная часть \n ПартииПроизводства..
ПартияПроизводства : Документ.Этап производства\rДокумент.Отчет переработчика\rДокумент.Выпуск продукции и выполнение работ\r...
Подразделение : Справочник.Подразделение
Этап : Документ.Этап производства\rДокумент.Производство без заказа
СтатьяКалькуляции : Справочник.Статьи калькуляции
Количество : Число 15, 3
АналитикаУчетаПартийПроизводства : Справочник.Ключ аналитики учета партий производства
..Табличная часть \n ОтборПоГруппамПродукции..
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
..Табличная часть \n ОтборПоМатериалам..
Материал : Справочник.Номенклатура
..Табличная часть \n ОтборПоВидамРабот..
ВидРабот : Справочник.Вид работ сотрудников
..Табличная часть \n Серии..
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Серия : Справочник.Серия номенклатуры
Назначение : Справочник.Назначение
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n ВидыЗапасов..
АналитикаУчетаНоменклатуры : Справочник.Номенклатура\rСправочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
Подразделение : Справочник.Подразделение
Получатель : Справочник.Подразделение\rСправочник.Склад (складская территория)
ПартияПроизводства : Документ.Этап производства\rДокумент.Производство без заказа
АналитикаУчетаПартийПроизводства : Справочник.Ключ аналитики учета партий производства
Этап : Документ.Этап производства\rДокумент.Производство без заказа
СтатьяКалькуляции : Справочник.Статьи калькуляции
Количество : Число 15, 3
Сумма : Число 15, 2
..Движения..
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
Международный : РегистрБухгалтерии
НДСЗаписиКнигиПродаж : Обороты
ОбеспечениеЗаказовРаботами : Остатки
МатериалыИРаботыВПроизводстве : Остатки
СвободныеОстатки : Остатки
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
}
@enduml
