@startuml ОтзывСогласияНаОбработкуПерсональныхДанных
'!include templates.wsd
'..\include templates.wsd
class Документ.ОтзывСогласияНаОбработкуПерсональныхДанных as "Отзыв согласия на обработку персональных данных" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ЮридическийАдресОрганизации : Строка
ОтветственныйЗаОбработкуПерсональныхДанных : Справочник.Пользователь
Субъект : Справочник.Физическое лицо
ДатаОтзыва : Дата
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Движения..
СогласияНаОбработкуПерсональныхДанных : РегистрСведений
}
@enduml
