@startuml АктВыполненныхВнутреннихРабот
'!include templates.wsd
'..\include templates.wsd
class Документ.АктВыполненныхВнутреннихРабот as "Акт выполненных внутренних работ" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ОрганизацияПолучатель : Справочник.Организация
Подразделение : Справочник.Подразделение
ХозяйственнаяОперация : Хозяйственные операции
ПеремещениеПодДеятельность : Типы налогообложения НДС
НаправлениеДеятельности : Справочник.Направление деятельности
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Подразделение : Справочник.Подразделение
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
СебестоимостьТоваров : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
НДСЗаписиКнигиПродаж : Обороты
МатериалыИРаботыВПроизводстве : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
НДСЗаписиКнигиПокупок : Обороты
}
@enduml
