@startuml ИзменениеМестРаботы
'!include templates.wsd
'..\include templates.wsd
class Документ.ИзменениеМестРаботы as "Изменение мест работы" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ДатаОкончания : Дата
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Сотрудник
ИдентификаторСтрокиСотрудника : Число 7, 0
МестоРаботы : Справочник.Место работы
СовокупнаяТарифнаяСтавка : Число 15, 5
ВидТарифнойСтавки : Виды тарифных ставок
ФизическоеЛицо : Справочник.Физическое лицо
..Табличная часть \n Начисления..
ИдентификаторСтрокиСотрудника : Число 7, 0
Начисление : Начисление
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Действие : Действия с начислениями и удержаниями
Размер : Число 15, 3
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n Показатели..
ИдентификаторСтрокиСотрудника : Число 7, 0
Показатель : Справочник.Показатель
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Значение : Число 15, 5
УдалитьСотрудник : Справочник.Сотрудник
..Движения..
УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников : РегистрСведений
ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
БухучетПлановыхНачислений : РегистрСведений
ПлановыеНачисления : РегистрСведений
}
@enduml
