@startuml ПеремещениеНМА2_4
'!include templates.wsd
'..\include templates.wsd
class Документ.ПеремещениеНМА2_4 as "Перемещение НМА" <<Документы>>
{
..Реквизиты..
ОтражатьВУпрУчете : Булево
ОтражатьВРеглУчете : Булево
ХозяйственнаяОперация : Хозяйственные операции
Организация : Справочник.Организация
ОрганизацияПолучатель : Справочник.Организация
Подразделение : Справочник.Подразделение
ПодразделениеПолучатель : Справочник.Подразделение
УдалитьМОЛ : Справочник.Физическое лицо
УдалитьМОЛПолучатель : Справочник.Физическое лицо
НачислениеАмортизации : Число 10, 0
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n НМА..
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
..Движения..
ПервоначальныеСведенияНМАНалоговыйУчет : РегистрСведений
ПорядокУчетаНМА : РегистрСведений
НематериальныеАктивыМеждународныйУчет : РегистрСведений
ПорядокУчетаНМАУУ : РегистрСведений
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
ПервоначальныеСведенияНМА : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
СтоимостьНМА : Остатки
Хозрасчетный : РегистрБухгалтерии
ПорядокУчетаНМАБУ : РегистрСведений
ОтражениеДокументовВМеждународномУчете : РегистрСведений
АмортизацияНМА : Остатки
Международный : РегистрБухгалтерии
ПараметрыАмортизацииНМАБУ : РегистрСведений
МестоУчетаНМА : РегистрСведений
ПервоначальныеСведенияНМАБухгалтерскийУчет : РегистрСведений
ВыручкаИСебестоимостьПродаж : Обороты
ПараметрыАмортизацииНМАУУ : РегистрСведений
}
@enduml
