@startuml ПроцессПодготовкиБюджетов
'!include templates.wsd
'..\include templates.wsd
class Документ.ПроцессПодготовкиБюджетов as "Процесс подготовки бюджетов" <<Документы>>
{
..Реквизиты..
Ответственный : Справочник.Пользователь
МодельБюджетирования : Справочник.Модели бюджетирования
Комментарий : Строка
ГруппаЭтапов : Справочник.Этап подготовки бюджетов
Статус : Статусы расчетов бюджетов по модели
НачалоПериода : Дата
КонецПериода : Дата
Периодичность : Периодичность
ДополнениеКОписанию : Строка
..Табличная часть \n НастройкиИерархии..
ГруппаЭтапов : Справочник.Этап подготовки бюджетов
ЭтапПодготовкиБюджетов : Справочник.Этап подготовки бюджетов
ЭтапПодготовкиБюджетовОснование : Справочник.Этап подготовки бюджетов
Код : Число 10, 0
Периодичность : Периодичность
..Табличная часть \n НастройкиРасчета..
Период : Дата
ЭтапПодготовкиБюджетов : Справочник.Этап подготовки бюджетов
ЭтапПодготовкиБюджетовОснование : Справочник.Этап подготовки бюджетов
Ответственный : Справочник.Пользователь
Длительность : Число 3, 0
ТипДлительности : Типы сроков этапов подготовки бюджетов
НеВыполняется : Булево
ВыполнятьАвтоматически : Булево
}
@enduml
