@startuml ПриемНаРаботуСписком
'!include templates.wsd
'..\include templates.wsd
class Документ.ПриемНаРаботуСписком as "Прием на работу списком" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ДатаСобытия : Дата
НачисленияУтверждены : Булево
ИсправленныйДокумент : Документ.Прием на работу списком
ВидДоговора : Виды договоров с сотрудниками
ОснованиеПредставителяНанимателя : Строка
БронированиеПозиции : Булево
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ИдентификаторСтрокиСотрудника : Число 7, 0
Подразделение : Справочник.Подразделение
Должность : Справочник.Должность
ДолжностьПоШтатномуРасписанию : Справочник.Позиция
ДатаПриема : Дата
КоличествоСтавок : Число 22, 20
ВидЗанятости : Виды занятости
ДлительностьИспытательногоСрока : Число 4, 1
ГрафикРаботы : Справочник.График работы
СпособРасчетаАванса : Способы расчета аванса
Аванс : Число 15, 2
УсловияПриема : Строка
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОтношениеКЕНВД : Отношение к ЕНВД затрат на зарплату
СтатьяФинансирования : Справочник.Статья финансирования
ПорядокРасчетаСтоимостиЕдиницыВремени : Порядок расчета стоимости часа (дня) оплаты труда сотрудников
СовокупнаяТарифнаяСтавка : Число 15, 5
ВидТарифнойСтавки : Виды тарифных ставок
РазрядКатегория : Справочник.Квалификационный разряд (категория)
ТрудовойДоговорНомер : Строка
ТрудовойДоговорДата : Дата
СрочныйДоговор : Булево
СезонныйДоговор : Булево
ДатаЗавершенияТрудовогоДоговора : Дата
ОснованиеСрочногоДоговора : Справочник.Основание заключения срочного трудового договора
СрокЗаключенияДоговора : Строка
СпособПоступленияНаСлужбу : Строка
ПоступлениеНаСлужбуВпервые : Булево
ВидАктаГосоргана : Строка
ОборудованиеРабочегоМеста : Строка
ИныеУсловияДоговора : Строка
Грейд : Строка
Территория : Справочник.Территория
РазрешениеНаРаботу : Строка
РазрешениеНаПроживание : Строка
УсловияОказанияМедпомощи : Строка
ДатаПрисвоения : Дата
КлассныйЧинРанг : Строка
ПКУ : Справочник.Квалификационный разряд (категория)
Решение : Строка
..Табличная часть \n Начисления..
ИдентификаторСтрокиСотрудника : Число 7, 0
Начисление : Начисление
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Размер : Число 15, 2
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n УправленческиеНачисления..
ИдентификаторСтрокиСотрудника : Число 7, 0
Начисление : Начисление
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Размер : Число 15, 2
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n Показатели..
ИдентификаторСтрокиСотрудника : Число 7, 0
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Показатель : Справочник.Показатель
Значение : Число 15, 5
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n ЕжегодныеОтпуска..
ИдентификаторСтрокиСотрудника : Число 7, 0
ВидЕжегодногоОтпуска : Справочник.Вид отпуска
КоличествоДнейВГод : Число 2, 0
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n Льготы..
ИдентификаторСтрокиСотрудника : Число 7, 0
Льгота : Начисление
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Размер : Число 15, 2
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
СведенияКонтрактаДоговораСотрудника : РегистрСведений
ПорядокРасчетаСтоимостиЕдиницыВремениСотрудников : РегистрСведений
ЗанятыеПозицииШтатногоРасписания : Остатки
УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников : РегистрСведений
ПКУСотрудников : РегистрСведений
ГрафикРаботыСотрудников : РегистрСведений
ПрименениеДополнительныхПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
ДанныеСостоянийСотрудников : РегистрСведений
ПлановыеАвансы : РегистрСведений
КадроваяИсторияСотрудников : РегистрСведений
ОсновныеДанныеКонтрактаДоговораСотрудника : РегистрСведений
ТерриторииСотрудников : РегистрСведений
РазрядыКатегорииСотрудников : РегистрСведений
ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
БухучетПлановыхНачислений : РегистрСведений
ПоложенныеВидыЕжегодныхОтпусков : РегистрСведений
ПараметрыПериодовСтажаПФР : РегистрСведений
ПлановыеНачисления : РегистрСведений
РеестрКадровыхПриказов : РегистрСведений
}
@enduml
