@startuml ДвижениеПрочихАктивовПассивов
'!include templates.wsd
'..\include templates.wsd
class Документ.ДвижениеПрочихАктивовПассивов as "Движение прочих активов и пассивов" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Валюта : Справочник.Валюта
Комментарий : Строка
Ответственный : Справочник.Пользователь
Источник : Типы статей активов пассивов
Получатель : Типы статей активов пассивов
Увеличение : Булево
Описание : Строка
..Табличная часть \n ДанныеОтражения..
СтатьяИсточник : Статья расходов\rСтатья актива/пассива\rСтатьи доходов
НаправлениеДеятельностиИсточник : Справочник.Направление деятельности
ПодразделениеИсточник : Справочник.Подразделение
АналитикаАктивовПассивовИсточник : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
АналитикаДоходовИсточник : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
АналитикаРасходовИсточник : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
СтатьяПолучатель : Статья расходов\rСтатья актива/пассива\rСтатьи доходов
НаправлениеДеятельностиПолучатель : Справочник.Направление деятельности
ПодразделениеПолучатель : Справочник.Подразделение
АналитикаАктивовПассивовПолучатель : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
АналитикаДоходовПолучатель : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
АналитикаРасходовПолучатель : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Сумма : Число 15, 2
СуммаБезНДС : Число 15, 2
ДатаОтражения : Дата
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ПрочиеДоходы : Остатки
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
РасходыПриУСН : Остатки
ФактическиеДанныеБюджетирования : Обороты
КнигаУчетаДоходовИРасходов : Обороты
ВыручкаИСебестоимостьПродаж : Обороты
}
@enduml
