@startuml РегистрацияНаработок
'!include templates.wsd
'..\include templates.wsd
class Документ.РегистрацияНаработок as "Регистрация наработок" <<Документы>>
{
..Реквизиты..
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Наработки..
ОбъектЭксплуатации : Справочник.Объект эксплуатации\rСправочник.Узел объекта эксплуатации
ПоказательНаработки : Справочник.Показатель наработки
Значение : Число 15, 3
СреднесуточноеЗначение : Число 15, 3
..Табличная часть \n РасчетныеНаработки..
ОбъектЭксплуатации : Справочник.Объект эксплуатации\rСправочник.Узел объекта эксплуатации
ПоказательНаработки : Справочник.Показатель наработки
Значение : Число 15, 3
СреднесуточноеЗначение : Число 15, 3
..Движения..
НаработкиОбъектовЭксплуатации : РегистрСведений
ПериодыАктуальностиОбъектовЭксплуатации : РегистрСведений
}
@enduml
