@startuml РегламентнаяОперация
'!include templates.wsd
'..\include templates.wsd
class Документ.РегламентнаяОперация as "Регламентная операция" <<Документы>>
{
..Реквизиты..
ТипОперации : Типы регламентных операций
Комментарий : Строка
Организация : Справочник.Организация
..Движения..
РасчетНалогаНаИмущество : РегистрСведений
РасчетСтавкиНалогаНаПрибыльЗаМесяц : РегистрСведений
КнигаУчетаДоходовИРасходовРаздел2 : Обороты
ПрочиеРасходы : Остатки
РасчетРезервовПоСомнительнымДолгам : РегистрСведений
РасчетРазницВОценкеАктивовИОбязательств : РегистрСведений
ПартииПрочихРасходов : Остатки
РасчетДолейБазыНалогаНаПрибыль : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
РасчетЗемельногоНалога : РегистрСведений
РасходыПриУСНОСиНМА : Остатки
РасходыПриУСНМатериалы : Остатки
РасходыПриУСН : Остатки
РасчетНормированияРасходов : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
РасчетНалогаУСН : РегистрСведений
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
РасчетРасходовПоАренде : РегистрСведений
Международный : РегистрБухгалтерии
РасходыПриУСНТовары : Остатки
КнигаУчетаДоходовИРасходов : Обороты
РасчетСтоимостиНалоговыхАктивовИОбязательствПослеИзмененияСтавкиНалогаНаПрибыль : РегистрСведений
ДолиСписанияКосвенныхРасходов : РегистрСведений
РасчетТранспортногоНалога : РегистрСведений
РасчетСтоимостиНалоговыхАктивовИОбязательств : РегистрСведений
}
@enduml
