@startuml УдержаниеДобровольныхСтраховыхВзносов
'!include templates.wsd
'..\include templates.wsd
class Документ.УдержаниеДобровольныхСтраховыхВзносов as "Удержание добровольных страховых взносов" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Удержание : Удержание
ДатаНачала : Дата
ДатаОкончания : Дата
Действие : Действия с удержаниями
ДокументОснование : Документ.Удержание добровольных страховых взносов
НеПредоставлятьСоциальныйВычетУРаботодателя : Булево
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
БухучетЗаданВДокументе : Булево
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
УдалитьДействие : Действия с начислениями и удержаниями
УдалитьРазмер : Число 15, 2
УдалитьФизическоеЛицо : Справочник.Физическое лицо
..Табличная часть \n Удержания..
ФизическоеЛицо : Справочник.Физическое лицо
РабочееМесто : Справочник.Сотрудник
Размер : Число 15, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
..Табличная часть \n Показатели..
Показатель : Справочник.Показатель
Значение : Число 15, 5
ИдентификаторСтрокиВидаРасчета : Число 7, 0
..Движения..
БухучетПлановыхУдержаний : РегистрСведений
РабочиеМестаУдержаний : РегистрСведений
ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
ПредоставлениеСоциальныхВычетовУРаботодателя : РегистрСведений
ПлановыеУдержания : РегистрСведений
}
@enduml
