@startuml ИзменениеПлановыхНачислений
'!include templates.wsd
'..\include templates.wsd
class Документ.ИзменениеПлановыхНачислений as "Изменение плановых начислений" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
УдалитьДолжностьПоШтатномуРасписанию : Справочник.Позиция
УдалитьДолжность : Справочник.Должность
ДатаИзменения : Дата
ДатаОкончания : Дата
Основание : Документ.Утверждение штатного расписания\rДокумент.Утверждение тарифной группы\rДокумент.Изменение штатного расписания
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ГлавныйБухгалтер : Справочник.Физическое лицо
ИдентификаторСтрокиПозиции : Число 5, 0
КраткийСоставДокумента : Строка
УчитыватьКакИндексациюЗаработка : Булево
РазныеСрокиДляРазныхСотрудников : Булево
ЭтоОтражениеИзмененияШтатногоРасписания : Булево
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n УдалитьНачисления..
Начисление : Начисление
Действие : Действия с начислениями и удержаниями
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Сотрудник
ДатаИзменения : Дата
ДатаОкончания : Дата
СовокупнаяТарифнаяСтавка : Число 15, 5
КоэффициентИндексации : Число 9, 8
ВидТарифнойСтавки : Виды тарифных ставок
ИдентификаторСтрокиСотрудника : Число 7, 0
..Табличная часть \n НачисленияСотрудников..
Начисление : Начисление
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Действие : Действия с начислениями и удержаниями
Размер : Число 15, 3
ИдентификаторСтрокиСотрудника : Число 7, 0
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n ПоказателиСотрудников..
Показатель : Справочник.Показатель
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Значение : Число 15, 5
ИдентификаторСтрокиСотрудника : Число 7, 0
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Табличная часть \n УдалитьПоказателиПозиции..
ЗначениеПоказателяМин : Число 15, 5
ЗначениеПоказателяМакс : Число 15, 5
Показатель : Справочник.Показатель
..Движения..
УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников : РегистрСведений
КоэффициентИндексацииЗаработка : РегистрСведений
ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
БухучетПлановыхНачислений : РегистрСведений
ПлановыеНачисления : РегистрСведений
}
@enduml
