@startuml АмортизацияНМА2_4
'!include templates.wsd
'..\include templates.wsd
class Документ.АмортизацияНМА2_4 as "Амортизация НМА и списание расходов по НИОКР" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
НомерПакета : Число 10, 0
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Движения..
ПрочиеДоходы : Остатки
ПорядокУчетаНМАУУ : РегистрСведений
ПрочиеРасходы : Остатки
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ПартииРасходовНаСебестоимостьТоваров : Остатки
ФактическиеДанныеБюджетирования : Обороты
СтоимостьНМА : Остатки
Хозрасчетный : РегистрБухгалтерии
ПорядокУчетаНМАБУ : РегистрСведений
ОтражениеДокументовВМеждународномУчете : РегистрСведений
АмортизацияНМА : Остатки
Международный : РегистрБухгалтерии
ВыручкаИСебестоимостьПродаж : Обороты
}
@enduml
