@startuml Анкета
'!include templates.wsd
'..\include templates.wsd
class Документ.Анкета as "Анкета" <<Документы>>
{
..Реквизиты..
Опрос : Документ.Проведение опроса
Респондент : Справочник.Пользователь\rСправочник.Партнер\rСправочник.Контактное лицо\r...
ДатаРедактирования : Дата
РедактируемыйРаздел : Справочник.Вопрос шаблона анкеты\rСтрока
Комментарий : Строка
Интервьюер : Справочник.Пользователь
ШаблонАнкеты : Справочник.Шаблон анкеты
РежимАнкетирования : Режимы анкетирования
..Табличная часть \n Состав..
Вопрос : Справочник.Вопрос шаблона анкеты
ЭлементарныйВопрос : Вопрос для анкетирования
НомерЯчейки : Число 10, 0
Ответ : Булево\rСтрока\rДата\r...
ОткрытыйОтвет : Строка
..Движения..
ОтветыНаВопросыАнкет : РегистрСведений
}
@enduml
