@startuml РегистрацияПереработок
'!include templates.wsd
'..\include templates.wsd
class Документ.РегистрацияПереработок as "Регистрация переработок" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ПериодСуммированногоУчетаНачало : Дата
ПериодСуммированногоУчетаОкончание : Дата
Ответственный : Справочник.Пользователь
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
Комментарий : Строка
КраткийСоставДокумента : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Сотрудник
НормаЧасов : Число 7, 2
ОтработаноЧасов : Число 7, 2
ОтработаноЧасовВПраздники : Число 7, 2
Сверхурочно1_5 : Число 7, 2
Сверхурочно2 : Число 7, 2
СпособКомпенсацииПереработки : Способы компенсации переработки
Сверхурочно0 : Число 7, 2
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Движения..
ЗначенияРазовыхПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
ЗначенияОперативныхПоказателейРасчетаЗарплатыСотрудников : Обороты
ДниЧасыОтгулов : Остатки
}
@enduml
