@startuml ПоступлениеПредметовЛизинга
'!include templates.wsd
'..\include templates.wsd
class Документ.ПоступлениеПредметовЛизинга as "Поступление предметов лизинга" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ГруппаФинансовогоУчета : Справочник.Группа финансового учета внеоборотных активов
Контрагент : Справочник.Контрагент
СчетУчета : Счет бухгалтерского учета
Комментарий : Строка
Ответственный : Справочник.Пользователь
ДоговорЛизинга : Справочник.Договор лизинга
Валюта : Справочник.Валюта
НалогообложениеНДС : Типы налогообложения НДС
ЦенаВключаетНДС : Булево
СуммаДокумента : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
ВалютаВзаиморасчетов : Справочник.Валюта
ЗакупкаПодДеятельность : Типы налогообложения НДС
НомерВходящегоДокумента : Строка
ДатаВходящегоДокумента : Дата
Курс : Число 10, 4
Кратность : Число 10, 0
..Табличная часть \n ОС..
ОсновноеСредство : Справочник.Объект эксплуатации
ИнвентарныйНомер : Строка
СтатьяРасходов : Статья расходов
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
СуммаНДСВзаиморасчетов : Число 15, 2
ИдентификаторСтроки : Строка
СуммаНУ : Число 15, 2
..Движения..
МестонахождениеОСБухгалтерскийУчет : РегистрСведений
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
ПервоначальныеСведенияОС : РегистрСведений
НДСПредъявленный : Остатки
ПервоначальныеСведенияОСБухгалтерскийУчет : РегистрСведений
ПорядокУчетаОСБУ : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
СостоянияОСОрганизаций : РегистрСведений
Международный : РегистрБухгалтерии
МестонахождениеОС : РегистрСведений
СчетаБухгалтерскогоУчетаОС : РегистрСведений
ПорядокУчетаОС : РегистрСведений
ПервоначальныеСведенияОСНалоговыйУчет : РегистрСведений
СтоимостьОС : Остатки
}
@enduml
