@startuml НормативРаспределенияПлановПродажПоКатегориям
'!include templates.wsd
'..\include templates.wsd
class Документ.НормативРаспределенияПлановПродажПоКатегориям as "Норматив распределения планов продаж по категориям" <<Документы>>
{
..Реквизиты..
ДатаНачалаДействия : Дата
Ответственный : Справочник.Пользователь
Операция : Операции нормативов распределения
Комментарий : Строка
ТоварнаяКатегория : Справочник.Товарные категории
Реквизит : Дополнительный реквизит / сведение\rСтрока
ВариантЗаполнения : Число 1, 0
ПорядокДолейРаспределения : Число 1, 0
..Табличная часть \n НормативыПоРеквизитам..
Значение : Справочник.Коллекция (сезон)\rСправочник.Марка (бренд)\rСправочник.Производитель\r...
ДоляРаспределения : Число 10, 0
ДоляНормированная : Число 10, 9
ЭтоПустоеЗначение : Булево
..Табличная часть \n НормативыПоСвойствам..
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ДоляРаспределения : Число 10, 0
ДоляНормированная : Число 10, 9
ЭтоПустоеЗначение : Булево
..Движения..
НормативыРаспределенияПлановПродажПоКатегориям : РегистрСведений
}
@enduml
