@startuml ПоступлениеТоваров
'!include templates.wsd
'..\include templates.wsd
class Документ.ПоступлениеТоваров as "Поступление товаров" <<Документы>>
{
..Реквизиты..
Валюта : Справочник.Валюта
Партнер : Справочник.Партнер
Соглашение : Справочник.Соглашение об условиях закупок
ХозяйственнаяОперация : Хозяйственные операции
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Склад : Справочник.Склад (складская территория)
Контрагент : Справочник.Контрагент
СуммаДокумента : Число 15, 2
Менеджер : Справочник.Пользователь
ЦенаВключаетНДС : Булево
Комментарий : Строка
НомерВходящегоДокумента : Строка
ДатаВходящегоДокумента : Дата
Сделка : Справочник.Сделка с клиентом
Договор : Справочник.Договор с контрагентом
Автор : Справочник.Пользователь
НаправлениеДеятельности : Справочник.Направление деятельности
ВидЦеныПоставщика : Справочник.Вид цены поставщика
Распоряжение : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\rДокумент.Этап производства\r...
РегистрироватьЦеныПоставщика : Булево
ВариантПриемкиТоваров : Варианты приемки товаров
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
НоменклатураПоставщика : Справочник.Номенклатура поставщика
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Цена : Число 15, 2
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
НомерГТД : Справочник.Номер ГТД
Назначение : Справочник.Назначение
СтатусУказанияСерий : Число 2, 0
СтатусУказанияСерийНаСкладах : Число 2, 0
СтатусУказанияСерийТоварыУПартнеров : Число 2, 0
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
АналитикаУчетаНоменклатурыТоварыУПартнеров : Справочник.Ключ аналитики учета номенклатуры
АналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
ВидЗапасов : Справочник.Вид запасов
Серия : Справочник.Серия номенклатуры
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n ВидыЗапасов..
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
АналитикаУчетаНоменклатурыТоварыУПартнеров : Справочник.Ключ аналитики учета номенклатуры
АналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
СуммаСНДС : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
ВидЗапасовНаСкладе : Справочник.Вид запасов
..Табличная часть \n Серии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
..Движения..
ДвиженияСерийТоваров : Обороты
ТоварыУПартнеров : Остатки
РезервыТоваровОрганизаций : Остатки
СебестоимостьТоваров : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ЦеныНоменклатурыПоставщиков : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
Международный : РегистрБухгалтерии
ДвижениеТоваров : Обороты
СвободныеОстатки : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
ТоварыОрганизаций : Остатки
ТоварыКПоступлению : Остатки
}
@enduml
