@startuml СчетФактураКомиссионеру
'!include templates.wsd
'..\include templates.wsd
class Документ.СчетФактураКомиссионеру as "Счет-фактура выданный комиссионеру (агенту)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Комиссионер : Справочник.Организация\rСправочник.Контрагент
ДокументОснование : Документ.Отчет комиссионера (агента) о продажах\rДокумент.Отчет по комиссии между организациями
СтрокаПлатежноРасчетныеДокументы : Строка
Валюта : Справочник.Валюта
ВыставленВЭлектронномВиде : Булево
ДатаВыставления : Дата
КодВидаОперации : Строка
СчетФактураОснование : Документ.Счет-фактура выданный комиссионеру (агенту)
НомерИсправления : Строка
Исправление : Булево
Сводный : Булево
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ПлатежноРасчетныеДокументы..
НомерПлатежноРасчетногоДокумента : Строка
ДатаПлатежноРасчетногоДокумента : Дата
..Табличная часть \n Покупатели..
Покупатель : Справочник.Организация\rСправочник.Контрагент
НомерСчетаФактуры : Строка
КПППокупателя : Строка
ИННПокупателя : Строка
..Движения..
ФактическиеДанныеБюджетирования : Обороты
НДСЗаписиКнигиПродаж : Обороты
ЖурналУчетаСчетовФактур : РегистрСведений
}
@enduml
