@startuml ВыбытиеАрендованныхОС
'!include templates.wsd
'..\include templates.wsd
class Документ.ВыбытиеАрендованныхОС as "Выбытие арендованных ОС" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Арендодатель : Справочник.Контрагент
Комментарий : Строка
Ответственный : Справочник.Пользователь
ДокументОснование : Документ.Поступление арендованных ОС\rДокумент.Инвентаризация ОС
ДокументНаОсновании : Булево
..Табличная часть \n ОС..
ОсновноеСредство : Справочник.Объект эксплуатации
..Движения..
ОтражениеДокументовВРеглУчете : РегистрСведений
ПервоначальныеСведенияОС : РегистрСведений
ПорядокУчетаОСБУ : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
СостоянияОСОрганизаций : РегистрСведений
Международный : РегистрБухгалтерии
СтоимостьОС : Остатки
}
@enduml
