@startuml ПринятиеКУчетуНМА
'!include templates.wsd
'..\include templates.wsd
class Документ.ПринятиеКУчетуНМА as "Принятие к учету НМА (2.2)" <<Документы>>
{
..Реквизиты..
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ВариантПримененияЦелевогоФинансирования : Варианты применения целевого финансирования
ВариантРаздельногоУчетаНДС : Варианты раздельного учета НДС
ВидОбъектаУчета : Виды объектов учета НМА
Комментарий : Строка
КоэффициентБУ : Число 3, 2
НалогообложениеНДС : Типы налогообложения НДС
НаправлениеДеятельности : Справочник.Направление деятельности
НачислятьАмортизациюБУ : Булево
НачислятьАмортизациюНУ : Булево
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
ОбъемНаработкиБУ : Число 10, 0
Организация : Справочник.Организация
ОрганизацияПолучательРасходов : Справочник.Организация
Ответственный : Справочник.Пользователь
ПередаватьРасходыВДругуюОрганизацию : Булево
Подразделение : Справочник.Подразделение
ПорядокСписанияНИОКРНаРасходыНУ : Порядок списания НИОКР (НУ)
ПорядокУчетаНУ : Порядок включения стоимости основных средств в состав расходов (НУ)
СпециальныйКоэффициентНУ : Число 6, 2
СпособНачисленияАмортизацииБУ : Способы начисления амортизации нематериальных активов
СпособПоступления : Способы поступления активов
СрокИспользованияБУ : Число 4, 0
СрокИспользованияНУ : Число 4, 0
СтатьяДоходов : Статьи доходов
СтатьяРасходов : Статья расходов
СуммаЦелевыхСредств : Число 15, 2
СчетАмортизацииЦФ : Счет бухгалтерского учета
СчетНачисленияАмортизации : Счет бухгалтерского учета
СчетПередачиРасходов : Счет бухгалтерского учета
СчетУчета : Счет бухгалтерского учета
СчетУчетаЦФ : Счет бухгалтерского учета
..Табличная часть \n ЦелевоеФинансирование..
Счет : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Сумма : Число 15, 2
..Движения..
ПервоначальныеСведенияНМАНалоговыйУчет : РегистрСведений
СчетаБухгалтерскогоУчетаНМА : РегистрСведений
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ПараметрыЦелевогоФинансированияНМА : РегистрСведений
НачислениеАмортизацииНМАСпециальныйКоэффициентНалоговыйУчет : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
СостоянияНМАОрганизаций : РегистрСведений
ПервоначальныеСведенияНМАБухгалтерскийУчет : РегистрСведений
ВыручкаИСебестоимостьПродаж : Обороты
СпособыОтраженияРасходовПоАмортизацииНМАБухгалтерскийУчет : РегистрСведений
}
@enduml
