@startuml СписаниеОСМеждународныйУчет
'!include templates.wsd
'..\include templates.wsd
class Документ.СписаниеОСМеждународныйУчет as "Списание ОС (международный учет)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Ответственный : Справочник.Пользователь
Комментарий : Строка
СчетРасходов : Международный план счетов
СчетРасходовСубконто1 : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСтатья расходов\r...
СчетРасходовСубконто2 : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСтатья расходов\r...
СчетРасходовСубконто3 : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСтатья расходов\r...
ПричинаСписания : Справочник.Причина списания ОС
ДокументОснование : Документ.Списание ОС
..Табличная часть \n ОсновныеСредства..
ОсновноеСредство : Справочник.Объект эксплуатации
..Движения..
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ФактическиеДанныеБюджетирования : Обороты
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
ВыручкаИСебестоимостьПродаж : Обороты
ОсновныеСредстваМеждународныйУчет : РегистрСведений
}
@enduml
