@startuml ПоступлениеАрендованныхОС
'!include templates.wsd
'..\include templates.wsd
class Документ.ПоступлениеАрендованныхОС as "Поступление арендованных ОС" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ГруппаФинансовогоУчета : Справочник.Группа финансового учета внеоборотных активов
Подразделение : Справочник.Подразделение
Арендодатель : Справочник.Контрагент
СчетУчета : Счет бухгалтерского учета
Комментарий : Строка
Ответственный : Справочник.Пользователь
..Табличная часть \n ОС..
ОсновноеСредство : Справочник.Объект эксплуатации
ЗалоговаяСтоимость : Число 15, 2
ИнвентарныйНомер : Строка
..Движения..
МестонахождениеОСБухгалтерскийУчет : РегистрСведений
ОтражениеДокументовВРеглУчете : РегистрСведений
ПервоначальныеСведенияОС : РегистрСведений
ПервоначальныеСведенияОСБухгалтерскийУчет : РегистрСведений
ПорядокУчетаОСБУ : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
СостоянияОСОрганизаций : РегистрСведений
Международный : РегистрБухгалтерии
МестонахождениеОС : РегистрСведений
СчетаБухгалтерскогоУчетаОС : РегистрСведений
ПорядокУчетаОС : РегистрСведений
ПервоначальныеСведенияОСНалоговыйУчет : РегистрСведений
СтоимостьОС : Остатки
}
@enduml
