@startuml ПереносЗатратНаПерсоналМеждуСтатьями
'!include templates.wsd
'..\include templates.wsd
class Документ.ПереносЗатратНаПерсоналМеждуСтатьями as "Перенос затрат между статьями финансирования" <<Документы>>
{
..Реквизиты..
ПериодРегистрации : Дата
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
СтатьяФинансирования : Справочник.Статья финансирования
СуммаИтого : Строка
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Затраты..
ИдентификаторСтрокиЗатрат : Уникальный идентификатор
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
Начисление : Виды взаиморасчетов с сотрудниками\rВиды особых начислений и удержаний\rНачисление\r...
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
СтатьяРасходов : Справочник.Статья расходов
СтатьяФинансирования : Справочник.Статья финансирования
Сумма : Число 15, 2
Зарплата : Число 15, 2
ПФРДоПредельнойВеличины : Число 15, 2
ПФРСПревышения : Число 15, 2
ПФРПоСуммарномуТарифу : Число 15, 2
ФСС : Число 15, 2
ФССНесчастныеСлучаи : Число 15, 2
ФФОМС : Число 15, 2
ПФРНаДоплатуЛетчикам : Число 15, 2
ПФРНаДоплатуШахтерам : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботах : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботах : Число 15, 2
ПФРСтраховая : Число 15, 2
ПФРНакопительная : Число 15, 2
ТФОМС : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахБезСпецОценки : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахСпецОценка : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахБезСпецОценки : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахСпецОценка : Число 15, 2
..Табличная часть \n Переносы..
ИдентификаторСтрокиЗатрат : Уникальный идентификатор
ИдентификаторСтрокиПереноса : Уникальный идентификатор
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
СтатьяРасходов : Справочник.Статья расходов
СтатьяФинансирования : Справочник.Статья финансирования
Сумма : Число 15, 2
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Движения..
ВзаиморасчетыССотрудниками : Остатки
НачисленияУдержанияПоСотрудникам : Обороты
ПособияПоСоциальномуСтрахованию : Обороты
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаОбщий : Обороты
СтраховыеВзносыПоФизическимЛицам : Обороты
СведенияОДоходахНДФЛ : Обороты
БухучетНачисленияУдержанияПоСотрудникам : Обороты
ЗарплатаКВыплате : Остатки
ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаФСС : Обороты
}
@enduml
