@startuml ЗаявлениеОВвозеТоваров
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаявлениеОВвозеТоваров as "Заявление о ввозе товаров из ЕАЭС" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Контрагент : Справочник.Контрагент
Договор : Справочник.Договор с контрагентом
Ответственный : Справочник.Пользователь
Комментарий : Строка
СуммаДокумента : Число 15, 2
СтруктураРеквизитовВыгрузки : Хранилище значения
УдалитьОплатаПодтверждена : Булево
УдалитьДатаПодтвержденияОплаты : Дата
ИспользоватьАкцизы : Булево
НомерДоговора : Строка
ДатаДоговора : Дата
Валюта : Справочник.Валюта
ОтветственноеЛицо : Справочник.Лицо с правом подписи
УдалитьДатаДокументаПеречисленияНалога : Дата
УдалитьНомерДокументаПеречисленияНалога : Строка
ДатаОтправки : Дата
Подразделение : Справочник.Подразделение
УдалитьНомерОтметкиОРегистрации : Строка
..Табличная часть \n Товары..
АдвалорнаяСтавкаАкциза : Число 10, 2
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
УдалитьАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
УдалитьАналитикаУчетаПартийЗаявление : Справочник.Ключ аналитики учета партий
Валюта : Справочник.Валюта
ВесНеттоКг : Число 15, 2
ВидЗапасов : Справочник.Вид запасов
ВидТранспорта : Строка
ДатаПринятияНаУчет : Дата
ДатаСчетаФактуры : Дата
ДатаТСД : Дата
Договор : Справочник.Договор с контрагентом
ДокументПоступления : Документ.Приобретение товаров и услуг
ЕдиницаИзмерения : Справочник.Упаковка
ЗакупкаПодДеятельность : Типы налогообложения НДС
КодВидаТранспорта : Строка
Количество : Число 15, 3
НалоговаяБазаАкцизы : Число 15, 2
НалоговаяБазаНДС : Число 15, 2
Номенклатура : Справочник.Номенклатура
НоменклатураПоставщика : Справочник.Номенклатура поставщика
НомерСчетаФактуры : Строка
Подразделение : Справочник.Подразделение
Серия : Справочник.Серия номенклатуры
СерияНомерТСД : Строка
Склад : Справочник.Склад (складская территория)
СтавкаНДС : Ставки НДС
СтатСтоимостьДолларыСША : Число 15, 2
СуммаАкциза : Число 15, 2
СуммаНДС : Число 15, 2
ТвердаяСтавкаАкциза : Число 10, 2
ФактурнаяСтоимость : Число 15, 2
Характеристика : Справочник.Характеристика номенклатуры
ИдентификаторСтроки : Строка
НомерТД : Справочник.Номер ГТД
КоличествоПоТНВЭД : Число 15, 3
КодТНВЭД : Справочник.ТН ВЭД
..Табличная часть \n УчастникиСделки..
РольПродавца : Субъекты гражданско-правовых отношений
Продавец : Справочник.Контрагент
РольПокупателя : Субъекты гражданско-правовых отношений
Покупатель : Справочник.Контрагент
НомерДоговора : Строка
ДатаДоговора : Дата
НомерСпецификации : Строка
ДатаСпецификации : Дата
ТипГражданскоПравовыхОтношений : Типы гражданско-правовых отношений
..Табличная часть \n Спецификации..
НомерСпецификации : Строка
ДатаСпецификации : Дата
..Движения..
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СебестоимостьТоваров : Остатки
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
Закупки : Обороты
НДСЗаписиКнигиПродаж : Обороты
ТоварыКОформлениюЗаявленийОВвозе : Остатки
ВыручкаИСебестоимостьПродаж : Обороты
НДСЗаписиКнигиПокупок : Обороты
ЖурналУчетаСчетовФактур : РегистрСведений
}
@enduml
