@startuml ОперацияПоПлатежнойКарте
'!include templates.wsd
'..\include templates.wsd
class Документ.ОперацияПоПлатежнойКарте as "Операция по платежной карте" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ХозяйственнаяОперация : Хозяйственные операции
Валюта : Справочник.Валюта
Контрагент : Справочник.Контрагент
СуммаДокумента : Число 15, 2
ЭквайринговыйТерминал : Справочник.Эквайринговый терминал
НомерПлатежнойКарты : Строка
ЗаявкаНаРасходованиеДенежныхСредств : Документ.Заявка на расходование ДС
ОплатаВыполнена : Булево
КодАвторизации : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
НеКонтролироватьЗаполнениеЗаявки : Булево
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
Подразделение : Справочник.Подразделение
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
НаправлениеДеятельности : Справочник.Направление деятельности
Договор : Справочник.Договор с контрагентом
УдалитьНомерЧекаККМ : Число 8, 0
УдалитьВариантОтправкиЭлектронногоЧека : Варианты отправки электронного чека покупателю
УдалитьКонтактныеДанныеЭлектронногоЧека : Строка
..Табличная часть \n РасшифровкаПлатежа..
Партнер : Справочник.Партнер
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
ОснованиеПлатежа : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\rДокумент.Отчет комиссионера (агента) о продажах\r...
Заказ : Документ.Возврат товаров от клиента\rДокумент.Эквайринговая операция\rДокумент.Отчет комиссионера (агента) о продажах\r...
Сумма : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
ВалютаВзаиморасчетов : Справочник.Валюта
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
..Движения..
ПрочиеДоходы : Остатки
РасчетыСКлиентами : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДенежныеСредстваКонтрагент : Обороты
ДенежныеСредстваВПути : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
ДенежныеСредстваКВыплате : Остатки
РасчетыСКлиентамиПоДокументам : Остатки
РасчетыПоЭквайрингу : Остатки
}
@enduml
