@startuml ЗаявкаНаРасходованиеДенежныхСредств
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаявкаНаРасходованиеДенежныхСредств as "Заявка на расходование денежных средств" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Статус : Статусы заявок на расходование денежных средств
ХозяйственнаяОперация : Хозяйственные операции
СуммаДокумента : Число 15, 2
Валюта : Справочник.Валюта
ФормаОплатыНаличная : Булево
ФормаОплатыБезналичная : Булево
ФормаОплатыПлатежнаяКарта : Булево
БанковскийСчет : Справочник.Банковский счет организации
Касса : Справочник.Касса
НазначениеПлатежа : Строка
ЖелательнаяДатаПлатежа : Дата
Контрагент : Справочник.Контрагент
БанковскийСчетКонтрагента : Справочник.Банковский счет
ПодотчетноеЛицо : Справочник.Физическое лицо
ОрганизацияПолучатель : Справочник.Организация
БанковскийСчетПолучатель : Справочник.Банковский счет организации
КассаПолучатель : Справочник.Касса
Подразделение : Справочник.Подразделение
КтоЗаявил : Справочник.Пользователь
КтоРешил : Справочник.Пользователь
Комментарий : Строка
ФормаОплатыЗаявки : Формы оплаты
ДатаПлатежа : Дата
ДокументОснование : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\rДокумент.Таможенная декларация на импорт\r...
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
Автор : Справочник.Пользователь
ВалютаКонвертации : Справочник.Валюта
СуммаПослеКонвертации : Число 15, 2
КурсКонвертации : Число 10, 4
ПланированиеСуммы : Способы планирования оплаты заявок
НомерВедомостиНаВыплатуЗарплаты : Строка
ДатаВедомостиНаВыплатуЗарплаты : Дата
СверхЛимита : Булево
СтатьяАктивовПассивов : Статья актива/пассива
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
ИдентификаторПлатежа : Строка
ХозяйственнаяОперацияПоЗарплате : Хозяйственные операции
ДатаАвансовогоОтчета : Дата
ДоговорСУчастникомГОЗ : Булево
ПлатежиПо275ФЗ : Булево
ТипПлатежаФЗ275 : Справочник.Типы платежей 275-ФЗ
ПредметОплаты : Строка
ВариантОплаты : Варианты оплаты поставщику
ПунктКонтрактаПредмета : Строка
ПунктКонтрактаОплаты : Строка
СтатьяКалькуляции : Справочник.Статьи калькуляции
ПеречислениеВБюджет : Булево
ВидПеречисленияВБюджет : Виды перечислений в бюджет
КодОКАТО : Строка
ПоказательОснования : Строка
ПоказательПериода : Строка
ПоказательНомера : Строка
ПоказательДаты : Строка
ПоказательТипа : Строка
СтатусСоставителя : Строка
КодБК : Строка
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
ТипНалога : Типы налогов
НДФЛПоВедомостям : Булево
ПриоритетОплаты : Справочник.Приоритет оплаты
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
ИННПлательщика : Строка
КПППлательщика : Строка
ТекстПлательщика : Строка
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
НаправлениеДеятельности : Справочник.Направление деятельности
Договор : Справочник.Договор между организациями\rСправочник.Договор с контрагентом
..Табличная часть \n РасшифровкаПлатежа..
Партнер : Справочник.Партнер
Заказ : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\rДокумент.Таможенная декларация на импорт\r...
Сумма : Число 15, 2
ВалютаВзаиморасчетов : Справочник.Валюта
СуммаВзаиморасчетов : Число 15, 2
СтатьяРасходов : Статья расходов\rСтатья актива/пассива
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
ДоговорКредитаДепозита : Справочник.Договор кредита (депозита)
ДоговорЛизинга : Справочник.Договор лизинга
ТипПлатежаПоЛизингу : Типы платежей по лизингу
Комментарий : Строка
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
ДоговорЗаймаСотруднику : Документ.Договор займа сотруднику
ТипСуммыКредитаДепозита : Типы сумм графика кредитов и депозитов
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Подразделение : Справочник.Подразделение
НаправлениеДеятельности : Справочник.Направление деятельности
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
Ведомость : Документ.Ведомость через раздатчика\rДокумент.Ведомость на счета\rДокумент.Ведомость в банк\r...
Организация : Справочник.Организация
..Табличная часть \n ЛицевыеСчетаСотрудников..
ФизическоеЛицо : Справочник.Физическое лицо
ЛицевойСчет : Справочник.Банковский счет
Сумма : Число 15, 2
..Табличная часть \n ДоговорыСЗаказчиками..
ДоговорСЗаказчиком : Справочник.Договор между организациями\rСправочник.Договор с контрагентом
Процент : Число 5, 2
Сумма : Число 15, 2
..Табличная часть \n ПодтверждающиеДокументы..
ВидДокумента : Справочник.Вид документа
Номер : Строка
Дата : Дата
Сумма : Число 15, 2
Файл : Справочник.Присоединенный файл (Договоры с контрагентами)\rСправочник.Присоединенный файл (Договоры кредитов и депозитов)\rСправочник.Присоединенный файл (Договоры между организациями)
..Табличная часть \n РаспределениеПоСчетам..
БанковскийСчетКасса : Справочник.Банковский счет организации\rСправочник.Касса
Сумма : Число 15, 2
ДатаПлатежа : Дата
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
РасчетыСКлиентами : Остатки
ДвиженияДенежныхСредств : Обороты
ДвиженияДенежныеСредстваКонтрагент : Обороты
ФактическиеДанныеБюджетирования : Обороты
ЛимитыРасходаДенежныхСредств : Обороты
РасчетыСПоставщиками : Остатки
ДенежныеСредстваКВыплате : Остатки
РасчетыСКлиентамиПоДокументам : Остатки
РасчетыСПоставщикамиПоДокументам : Остатки
ДвиженияДенежныеСредстваДоходыРасходы : Обороты
}
@enduml
