@startuml ОтчетОператораСистемыПлатон
'!include templates.wsd
'..\include templates.wsd
class Документ.ОтчетОператораСистемыПлатон as "Отчет оператора системы "Платон"" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
Договор : Справочник.Договор с контрагентом
Подразделение : Справочник.Подразделение
Валюта : Справочник.Валюта
ВалютаВзаиморасчетов : Справочник.Валюта
НомерВходящегоДокумента : Строка
ДатаВходящегоДокумента : Дата
ДатаПлатежа : Дата
ФормаОплаты : Формы оплаты
ПорядокОплаты : Порядок оплаты
СуммаДокумента : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
ЦенаВключаетНДС : Булево
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
БанковскийСчетОрганизации : Справочник.Банковский счет организации
БанковскийСчетКонтрагента : Справочник.Банковский счет
ПорядокРасчетов : Детализация расчетов
КоличествоДокументов : Строка
КоличествоЛистов : Строка
НаправлениеДеятельности : Справочник.Направление деятельности
Курс : Число 10, 4
Кратность : Число 10, 0
ХозяйственнаяОперация : Хозяйственные операции
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
Менеджер : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ОС..
ОсновноеСредство : Справочник.Объект эксплуатации
Сумма : Число 15, 2
СуммаСНДС : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
НаправлениеДеятельности : Справочник.Направление деятельности
Подразделение : Справочник.Подразделение
ИдентификаторСтроки : Строка
..Табличная часть \n РасшифровкаПлатежа..
Заказ : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Приобретение товаров и услуг\r...
Сумма : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ПрочиеДоходы : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
ДвиженияКонтрагентДоходыРасходы : Обороты
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНОСиНМА : Остатки
РасходыПриУСНМатериалы : Остатки
РасходыПриУСН : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
РасчетыСПоставщиками : Остатки
Международный : РегистрБухгалтерии
Закупки : Обороты
РасходыПриУСНТовары : Остатки
РасчетыСПоставщикамиПоДокументам : Остатки
КнигаУчетаДоходовИРасходов : Обороты
МатериалыИРаботыВПроизводстве : Остатки
ВыручкаИСебестоимостьПродаж : Обороты
}
@enduml
