@startuml ОтчетЕГАИС
'!include templates.wsd
'..\include templates.wsd
class Документ.ОтчетЕГАИС as "Отчет ЕГАИС" <<Документы>>
{
..Реквизиты..
ВидДокумента : Виды документов ЕГАИС
ОрганизацияЕГАИС : Справочник.Организация ЕГАИС
Ответственный : Справочник.Пользователь
Комментарий : Строка
Период : Дата
АлкогольнаяПродукция : Справочник.Алкогольная продукция ЕГАИС
Справка2 : Справочник.Справка к ТТН по форме 2
КодФСРАР : Справочник.Организация ЕГАИС\rСтрока
..Табличная часть \n ДвиженияМеждуРегистрами..
ВидДокумента : Виды документов ЕГАИС
ИдентификаторЕГАИС : Строка
Количество : Число 15, 3
ДокументОснование : Документ.Товарно-транспортная накладная ЕГАИС (входящая)\rДокумент.Товарно-транспортная накладная ЕГАИС (исходящая)\rДокумент.Акт постановки на баланс ЕГАИС\r...
ДатаРегистрацииДвижений : Дата
ОписаниеОперации : Строка
НомерСправки2 : Строка
..Табличная часть \n ДвиженияПоСправке2..
ВидДокумента : Виды документов ЕГАИС
ИдентификаторЕГАИС : Строка
Количество : Число 15, 3
ДокументОснование : Документ.Товарно-транспортная накладная ЕГАИС (входящая)\rДокумент.Товарно-транспортная накладная ЕГАИС (исходящая)\rДокумент.Акт постановки на баланс ЕГАИС\r...
ОписаниеОперации : Строка
ДатаРегистрацииДвижений : Дата
..Табличная часть \n ИнформацияОбОрганизацииЕГАИС..
ТипОрганизации : Типы организаций ЕГАИС
Наименование : Строка
НаименованиеПолное : Строка
ИНН : Строка
КПП : Строка
КодСтраны : Число 3, 0
КодРегиона : Число 3, 0
ПочтовыйИндекс : Число 6, 0
ПредставлениеАдреса : Строка
..Табличная часть \n НеобработанныеТТН..
ИдентификаторЕГАИС : Строка
НомерТТН : Строка
ДатаТТН : Дата
КодГрузоотправителя : Строка
..Табличная часть \n ОбработанныеЧеки..
КоличествоЧековПродаж : Число 10, 0
КоличествоЧековНаВозврат : Число 10, 0
..Табличная часть \n ОстаткиАлкогольнойПродукции..
КодАлкогольнойПродукции : Строка
Количество : Число 15, 3
НомерСправки2 : Строка
}
@enduml
