@startuml ЕдиновременноеПособиеЗаСчетФСС
'!include templates.wsd
'..\include templates.wsd
class Документ.ЕдиновременноеПособиеЗаСчетФСС as "Единовременное пособие за счет ФСС" <<Документы>>
{
..Реквизиты..
ПериодРегистрации : Дата
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
ВидПособия : Перечень пособий социального страхования
ДатаСобытия : Дата
Начислено : Число 13, 2
ПорядокВыплаты : Характер выплаты зарплаты
ПланируемаяДатаВыплаты : Дата
ИсправленныйДокумент : Документ.Единовременное пособие
ПредставлениеПериода : Строка
СтатьяФинансирования : Справочник.Статья финансирования
Ответственный : Справочник.Пользователь
Комментарий : Строка
ПособиеНаПогребениеСотруднику : Булево
..Движения..
НачисленияУдержанияПоКонтрагентамАкционерам : Обороты
ВзаиморасчетыССотрудниками : Остатки
НачисленияУдержанияПоСотрудникам : Обороты
РасчетыСФондамиПоСтраховымВзносам : Остатки
ПорядокВыплатыДокументов : РегистрСведений
ПособияПоСоциальномуСтрахованию : Обороты
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
СведенияОДоходахСтраховыеВзносы : Обороты
БухучетНачисленияУдержанияПоКонтрагентамАкционерам : Обороты
ЗарплатаКВыплатеАвансом : Остатки
НачисленияУдержанияПоСотрудникамАвансом : Обороты
БухучетНачисленияУдержанияПоСотрудникам : Обороты
ЗарплатаКВыплате : Остатки
}
@enduml
