@startuml ЗапросАкцизныхМарокЕГАИС
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗапросАкцизныхМарокЕГАИС as "Запрос акцизных марок ЕГАИС" <<Документы>>
{
..Реквизиты..
ОрганизацияЕГАИС : Справочник.Организация ЕГАИС
Ответственный : Справочник.Пользователь
Комментарий : Строка
ДокументОснование : Строка
..Табличная часть \n Товары..
АлкогольнаяПродукция : Справочник.Алкогольная продукция ЕГАИС
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
ТипМарки : Строка
СерияМарки : Строка
НомерМарки : Строка
КодАкцизнойМарки : Строка
}
@enduml
