@startuml РеализацияТоваровУслуг
'!include templates.wsd
'..\include templates.wsd
class Документ.РеализацияТоваровУслуг as "Реализация товаров и услуг" <<Документы>>
{
..Реквизиты..
АдресДоставки : Строка
БанковскийСчетОрганизации : Справочник.Банковский счет организации
БанковскийСчетКонтрагента : Справочник.Банковский счет
БанковскийСчетГрузоотправителя : Справочник.Банковский счет
БанковскийСчетГрузополучателя : Справочник.Банковский счет
Валюта : Справочник.Валюта
ВалютаВзаиморасчетов : Справочник.Валюта
Грузоотправитель : Справочник.Контрагент
Грузополучатель : Справочник.Контрагент
ДатаПлатежа : Дата
ДатаРаспоряжения : Дата
ДоверенностьВыдана : Строка
ДоверенностьДата : Дата
ДоверенностьЛицо : Строка
ДоверенностьНомер : Строка
ЗаказКлиента : Документ.Заявка на возврат товаров от клиента\rДокумент.Заказ клиента
Организация : Справочник.Организация
Контрагент : Справочник.Контрагент
Менеджер : Справочник.Пользователь
НалогообложениеНДС : Типы налогообложения НДС
СуммаДокумента : Число 15, 2
Партнер : Справочник.Партнер
Подразделение : Справочник.Подразделение
Сделка : Справочник.Сделка с клиентом
СкидкиРассчитаны : Булево
Склад : Справочник.Склад (складская территория)
Согласован : Булево
Соглашение : Справочник.Соглашение об условиях продаж
СуммаВзаиморасчетов : Число 15, 2
Комментарий : Строка
ФормаОплаты : Формы оплаты
ХозяйственнаяОперация : Хозяйственные операции
ЦенаВключаетНДС : Булево
Касса : Справочник.Касса
Отпустил : Справочник.Физическое лицо
ОтпустилДолжность : Строка
РеализацияПоЗаказам : Булево
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
КартаЛояльности : Справочник.Карты лояльности
Договор : Справочник.Договор с контрагентом
Основание : Строка
Статус : Статусы реализаций товаров услуг
Автор : Справочник.Пользователь
СуммаПредоплаты : Число 15, 2
СуммаПредоплатыЗаТару : Число 15, 2
СпособДоставки : Способы доставки
ЗонаДоставки : Справочник.Зоны доставки
АдресДоставкиЗначенияПолей : Строка
ПеревозчикПартнер : Справочник.Партнер
ВремяДоставкиС : Дата
ВремяДоставкиПо : Дата
АдресДоставкиПеревозчика : Строка
АдресДоставкиПеревозчикаЗначенияПолей : Строка
ДополнительнаяИнформацияПоДоставке : Строка
КонтактноеЛицо : Справочник.Контактное лицо
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
ПорядокРасчетов : Детализация расчетов
ВернутьМногооборотнуюТару : Булево
ДатаВозвратаМногооборотнойТары : Дата
СостояниеЗаполненияМногооборотнойТары : Состояния заполнения многооборотной тары
ВидыЗапасовУказаныВручную : Булево
ТребуетсяЗалогЗаТару : Булево
ОснованиеДата : Дата
ОснованиеНомер : Строка
ДопоставкаПоРеализации : Документ.Возврат товаров от клиента\rДокумент.Реализация товаров и услуг
ДатаПереходаПраваСобственности : Дата
ВариантОформленияПродажи : Варианты оформления продажи
ИдентификаторПлатежа : Строка
ОсобыеУсловияПеревозки : Булево
ОсобыеУсловияПеревозкиОписание : Строка
НаправлениеДеятельности : Справочник.Направление деятельности
Курс : Число 10, 4
Кратность : Число 10, 0
ПорядокОплаты : Порядок оплаты
ЕстьМаркируемаяПродукцияГИСМ : Булево
УдалитьЕстьАлкогольнаяПродукцияДляРеализацииРозницаЕГАИС : Булево
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ВидЦены : Справочник.Вид цены
Цена : Число 15, 2
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
КодСтроки : Число 10, 0
СуммаРучнойСкидки : Число 15, 2
СуммаАвтоматическойСкидки : Число 15, 2
ПроцентРучнойСкидки : Число 5, 2
ПроцентАвтоматическойСкидки : Число 5, 2
КлючСвязи : Число 10, 0
Склад : Справочник.Склад (складская территория)
СтатусУказанияСерий : Число 2, 0
СуммаВзаиморасчетов : Число 15, 2
ЗаказКлиента : Документ.Заявка на возврат товаров от клиента\rДокумент.Заказ клиента
СрокПоставки : Число 10, 0
ИдентификаторСтроки : Строка
Серия : Справочник.Серия номенклатуры
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
НоменклатураНабора : Справочник.Номенклатура
ХарактеристикаНабора : Справочник.Характеристика номенклатуры
АналитикаУчетаНаборов : Справочник.Ключ аналитики учета наборов
КодТНВЭД : Справочник.ТН ВЭД
..Табличная часть \n СкидкиНаценки..
КлючСвязи : Число 10, 0
СкидкаНаценка : Справочник.Скидки (наценки)
Сумма : Число 15, 2
НапомнитьПозже : Булево
..Табличная часть \n ВидыЗапасов..
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
СуммаСНДС : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
ИдентификаторСтроки : Строка
СуммаВзаиморасчетов : Число 15, 2
ЗаказКлиента : Документ.Заявка на возврат товаров от клиента\rДокумент.Заказ клиента
СуммаРучнойСкидки : Число 15, 2
СуммаАвтоматическойСкидки : Число 15, 2
АналитикаУчетаНаборов : Справочник.Ключ аналитики учета наборов
Цена : Число 15, 2
ВидЗапасовПолучателя : Справочник.Вид запасов
КодТНВЭД : Справочник.ТН ВЭД
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n РасшифровкаПлатежа..
Заказ : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
Сумма : Число 15, 2
ВалютаВзаиморасчетов : Справочник.Валюта
СуммаВзаиморасчетов : Число 15, 2
..Табличная часть \n Серии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Склад : Справочник.Склад (складская территория)
..Движения..
ТоварыКОтгрузке : Остатки
ПрочиеДоходы : Остатки
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
РасчетыСКлиентами : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииТоваровПереданныеНаКомиссию : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ТоварыКОформлениюОтчетовКомитенту : Остатки
ПереданнаяВозвратнаяТара : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНМатериалы : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ЗаказыКлиентов : Остатки
ОбеспечениеЗаказов : Остатки
ТоварыПереданныеНаКомиссию : Остатки
Международный : РегистрБухгалтерии
РасходыПриУСНТовары : Остатки
НДСЗаписиКнигиПродаж : Обороты
РасчетыСКлиентамиПоДокументам : Остатки
ТоварыОрганизацийКПередаче : Остатки
КнигаУчетаДоходовИРасходов : Обороты
МатериалыИРаботыВПроизводстве : Остатки
ВыручкаИСебестоимостьПродаж : Обороты
СвободныеОстатки : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
НДССостояниеРеализации0 : РегистрСведений
ПартииПроизводственныхЗатрат : Остатки
УслугиКОформлениюОтчетовПринципалу : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
