@startuml ЗаказПереработчику
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаказПереработчику as "Заказ переработчику" <<Документы>>
{
..Реквизиты..
Автор : Справочник.Внешний пользователь\rСправочник.Пользователь
АдресДоставки : Строка
АдресДоставкиЗначенияПолей : Строка
АдресДоставкиПеревозчика : Строка
АдресДоставкиПеревозчикаЗначенияПолей : Строка
БанковскийСчет : Справочник.Банковский счет организации
БанковскийСчетГрузоотправителя : Справочник.Банковский счет
БанковскийСчетГрузополучателя : Справочник.Банковский счет
Валюта : Справочник.Валюта
ВернутьМногооборотнуюТару : Булево
ВидЦены : Справочник.Вид цены
ВозвратПорчи : Булево
ВремяДоставкиПо : Дата
ВремяДоставкиС : Дата
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
ГрафикОплаты : Справочник.График оплаты
Грузоотправитель : Справочник.Контрагент
Грузополучатель : Справочник.Контрагент
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
ГруппировкаЗатрат : Группировки затрат в заказе переработчику
ДатаОтгрузки : Дата
ДатаПервогоПоступления : Дата
ДатаПоДаннымПартнера : Дата
ДатаПоступления : Дата
Договор : Справочник.Договор с контрагентом
ДокументОснование : Документ.Заказ клиента
ДополнительнаяИнформация : Строка
ДополнительнаяИнформацияПоДоставке : Строка
ЖелаемаяДатаОтгрузки : Дата
ЖелаемаяДатаПоступления : Дата
ЗакупкаПодДеятельность : Типы налогообложения НДС
ЗонаДоставки : Справочник.Зоны доставки
Касса : Справочник.Касса
Комментарий : Строка
КонтактноеЛицо : Справочник.Контактное лицо
Контрагент : Справочник.Контрагент
МаксимальныйНомерГруппыЗатрат : Число 10, 0
МатериалыМаксимальныйКодСтроки : Число 10, 0
Менеджер : Справочник.Пользователь
Назначение : Справочник.Назначение
НеОтгружатьЧастями : Булево
Номенклатура : Справочник.Номенклатура
НомерПоДаннымПартнера : Строка
Организация : Справочник.Организация
Партнер : Справочник.Партнер
ПеревозчикПартнер : Справочник.Партнер
ПереработкаПоЗаказу : Булево
Подразделение : Справочник.Подразделение
ПорядокРасчетов : Детализация расчетов
ПоступлениеОднойДатой : Булево
Приоритет : Справочник.Приоритет
ПроверятьУказаниеРаботы : Булево
ПродукцияМаксимальныйКодСтроки : Число 10, 0
Распоряжение : Документ.Этап производства\rДокумент.Заказ на производство
Руководитель : Справочник.Лицо с правом подписи
Сделка : Справочник.Сделка с клиентом
СкидкиРассчитаны : Булево
Склад : Справочник.Склад (складская территория)
Согласован : Булево
Содержание : Строка
СостояниеЗаполненияМногооборотнойТары : Состояния заполнения многооборотной тары
СпособДоставки : Способы доставки
СрокВозвратаМногооборотнойТары : Число 3, 0
СтавкаНДС : Ставки НДС
Статус : Статусы заказов переработчикам
СтатьяКалькуляции : Справочник.Статьи калькуляции
Сумма : Число 15, 2
СуммаАвансаДоПодтверждения : Число 15, 2
СуммаДокумента : Число 15, 2
СуммаЗалоговая : Число 15, 2
СуммаНДС : Число 15, 2
СуммаПредоплатыДоПоступления : Число 15, 2
СуммаСНДС : Число 15, 2
ФормаОплаты : Формы оплаты
Характеристика : Справочник.Характеристика номенклатуры
ХозяйственнаяОперация : Хозяйственные операции
ОсобыеУсловияПеревозки : Булево
ОсобыеУсловияПеревозкиОписание : Строка
НаправлениеДеятельности : Справочник.Направление деятельности
ПорядокОплаты : Порядок оплаты
УслугиПоПереработке : Варианты оформления услуг документов переработки
УчетСырьяПоНазначениям : Булево
Удалить_Покупатель : Строка
Удалить_ДатаРожденияПокупателя : Дата
Удалить_ПричинаВозврата : Строка
Удалить_ВидДокументаПокупателя : Справочник.Вид документа физических лиц
Удалить_СерияДокументаПокупателя : Строка
Удалить_НомерДокументаПокупателя : Строка
Удалить_ДатаВыдачиДокументаПокупателя : Дата
Удалить_СрокДействияДокументаПокупателя : Дата
Удалить_КемВыданДокументПокупателя : Строка
Удалить_КодПодразделенияДокументаПокупателя : Строка
ОбосабливатьПоНазначениюПродукции : Булево
ВариантПриемкиТоваров : Варианты приемки товаров
..Табличная часть \n Продукция..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ДатаПоступления : Дата
КодСтроки : Число 10, 0
Отменено : Булево
ПричинаОтмены : Справочник.Причина отмены заказов поставщикам
Склад : Справочник.Склад (складская территория)
Назначение : Справочник.Назначение
ДоляСтоимости : Число 10, 0
Спецификация : Справочник.Ресурсная спецификация
НомерГруппыЗатрат : Число 10, 0
..Табличная часть \n ВозвратныеОтходы..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ДатаПоступления : Дата
Цена : Число 15, 2
Сумма : Число 15, 2
КодСтроки : Число 10, 0
Отменено : Булево
ПричинаОтмены : Справочник.Причина отмены заказов поставщикам
Склад : Справочник.Склад (складская территория)
Назначение : Справочник.Назначение
ВидЦены : Справочник.Вид цены
НомерГруппыЗатрат : Число 10, 0
СтатьяКалькуляции : Справочник.Статьи калькуляции
..Табличная часть \n Материалы..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ВидЦены : Справочник.Вид цены
Цена : Число 15, 2
Сумма : Число 15, 2
ДатаОтгрузки : Дата
Отменено : Булево
ПричинаОтмены : Справочник.Причина отмены заказов клиентов
КодСтроки : Число 10, 0
КлючСвязи : Число 10, 0
Склад : Справочник.Склад (складская территория)
СрокПоставки : Число 10, 0
СтатусУказанияСерий : Число 2, 0
ВариантОбеспечения : Варианты обеспечения
Серия : Справочник.Серия номенклатуры
Назначение : Справочник.Назначение
НомерГруппыЗатрат : Число 10, 0
СтатьяКалькуляции : Справочник.Статьи калькуляции
..Табличная часть \n Услуги..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Сумма : Число 15, 2
СуммаНДС : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаСНДС : Число 15, 2
СтатьяКалькуляции : Справочник.Статьи калькуляции
Спецификация : Справочник.Ресурсная спецификация
Этап : Справочник.Этап ресурсной спецификации
Распоряжение : Документ.Этап производства\rДокумент.Заказ на производство
КодСтрокиПродукция : Число 10, 0
КодСтрокиЭтапыГрафик : Число 10, 0
Начало : Дата
УдалитьНазначение : Справочник.Назначение
НомерГруппыЗатрат : Число 10, 0
..Табличная часть \n ЭтапыГрафикаОплаты..
ВариантОплаты : Варианты оплаты поставщику
ДатаПлатежа : Дата
ПроцентПлатежа : Число 5, 2
СуммаПлатежа : Число 15, 2
..Табличная часть \n РаспоряжениеСпецификация..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Количество : Число 15, 3
КоличествоПоЗаказу : Число 15, 3
КоличествоОтклонение : Число 15, 3
Склад : Справочник.Подразделение\rСправочник.Склад (складская территория)
ТипДвиженияЗапасов : Типы движения запасов
ЗаказатьНаСклад : Булево
ВариантОбеспечения : Варианты обеспечения
УказыватьСерии : Булево
Серия : Справочник.Серия номенклатуры
Назначение : Справочник.Назначение
ДатаОтгрузки : Дата
НомерГруппыЗатрат : Число 10, 0
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ТоварыКОтгрузке : Остатки
ГрафикОтгрузкиТоваров : Остатки
ЭтапыПроизводства : Обороты
ФактическиеДанныеБюджетирования : Обороты
ЗаказыКлиентов : Остатки
ОбеспечениеЗаказов : Остатки
РасчетыСПоставщиками : Остатки
УслугиПереработчиковКОформлению : Остатки
ДвижениеТоваров : Обороты
ОбеспечениеЗаказовРаботами : Остатки
РасчетыСПоставщикамиПоДокументам : Остатки
ЗаказыНаПроизводствоСпецификации : Остатки
СвободныеОстатки : Остатки
ПереработкаПоГрафикуПроизводства : Остатки
ГрафикПоступленияТоваров : Остатки
ЗаказыПоставщикам : Остатки
ТоварыКПоступлению : Остатки
}
@enduml
