@startuml УведомлениеОПолучателеДокументов
'!include templates.wsd
'..\include templates.wsd
class Документ.УведомлениеОПолучателеДокументов as "Уведомление о получателе документов" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ДляВсехПодразделений : Булево
Получатель : Справочник.Регистрация в налоговом органе
ЗаданиеЯвноРеквизитовПолучателяДокументов : Булево
ИдентификаторАбонента : Строка
НаименованиеПолучателяДокументов : Строка
ИННПолучателяДокументов : Строка
КПППолучателяДокументов : Строка
ПолучательДокументовЯвляетсяФизическимЛицом : Булево
ФамилияПолучателяДокументов : Строка
ИмяПолучателяДокументов : Строка
ОтчествоПолучателяДокументов : Строка
..Табличная часть \n ДолжностныеЛицаПолучателяДокументов..
Фамилия : Строка
Имя : Строка
Отчество : Строка
}
@enduml
