@startuml ИнвентаризацияРасчетов
'!include templates.wsd
'..\include templates.wsd
class Документ.ИнвентаризацияРасчетов as "Акт инвентаризации расчетов" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ДокументОснованиеВид : Строка
ДокументОснованиеНомер : Строка
ДокументОснованиеДата : Дата
ПричинаПроведенияИнвентаризации : Строка
ДатаНачалаИнвентаризации : Дата
ДатаОкончанияИнвентаризации : Дата
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Задолженность..
ДебиторКредитор : Справочник.Организация\rСправочник.Контрагент\rСтрока\r...
СчетРасчетов : Счет бухгалтерского учета
Подтверждено : Число 15, 2
НеПодтверждено : Число 15, 2
ИстекСрокДавности : Число 15, 2
ВидЗадолженности : Типы задолженности
..Табличная часть \n СчетаУчета..
СчетУчета : Счет бухгалтерского учета
..Табличная часть \n ИнвентаризационнаяКомиссия..
ФИОПолные : Строка
Председатель : Булево
Должность : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
