@startuml ЧекККМ
'!include templates.wsd
'..\include templates.wsd
class Документ.ЧекККМ as "Чек ККМ" <<Документы>>
{
..Реквизиты..
Архивный : Булево
Валюта : Справочник.Валюта
ВидЦены : Справочник.Вид цены
КассаККМ : Справочник.Кассы ККМ
Кассир : Справочник.Пользователь
Комментарий : Строка
НалогообложениеНДС : Типы налогообложения НДС
Организация : Справочник.Организация
ПолученоНаличными : Число 15, 2
СкидкиРассчитаны : Булево
Склад : Справочник.Склад (складская территория)
Статус : Статусы чеков ККМ
СуммаДокумента : Число 15, 2
ФормаОплаты : Формы оплаты
ЦенаВключаетНДС : Булево
ОтложенДо : Дата
КартаЛояльности : Справочник.Карты лояльности
Партнер : Справочник.Партнер
ИспользоватьОплатуБонуснымиБаллами : Булево
УдалитьАдресЧекаЕГАИС : Строка
УдалитьПодписьЧекаЕГАИС : Строка
КассоваяСмена : Документ.Кассовая смена
УдалитьНомерЧекаККМ : Число 8, 0
УдалитьВариантОтправкиЭлектронногоЧека : Варианты отправки электронного чека покупателю
УдалитьКонтактныеДанныеЭлектронногоЧека : Строка
..Табличная часть \n Товары..
КлючСвязи : Число 10, 0
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Цена : Число 15, 2
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
ПроцентАвтоматическойСкидки : Число 5, 2
СуммаАвтоматическойСкидки : Число 15, 2
ПроцентРучнойСкидки : Число 5, 2
СуммаРучнойСкидки : Число 15, 2
СтатусУказанияСерий : Число 2, 0
Продавец : Справочник.Пользователь
Помещение : Справочник.Помещение
Серия : Справочник.Серия номенклатуры
СуммаБонусныхБалловКСписанию : Число 15, 2
СуммаБонусныхБалловКСписаниюВВалюте : Число 15, 2
СуммаНачисленныхБонусныхБалловВВалюте : Число 15, 2
НоменклатураНабора : Справочник.Номенклатура
ХарактеристикаНабора : Справочник.Характеристика номенклатуры
Штрихкод : Строка
ИдентификаторСтроки : Строка
НоменклатураЕГАИС : Справочник.Алкогольная продукция ЕГАИС
..Табличная часть \n ОплатаПлатежнымиКартами..
ЭквайринговыйТерминал : Справочник.Эквайринговый терминал
НомерПлатежнойКарты : Строка
Сумма : Число 15, 2
СсылочныйНомер : Строка
КодАвторизации : Строка
НомерЧекаЭТ : Строка
..Табличная часть \n СкидкиНаценки..
КлючСвязи : Число 10, 0
СкидкаНаценка : Справочник.Скидки (наценки)
Сумма : Число 15, 2
НапомнитьПозже : Булево
..Табличная часть \n Серии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Помещение : Справочник.Помещение
..Табличная часть \n ПодарочныеСертификаты..
ПодарочныйСертификат : Справочник.Подарочный сертификат
Сумма : Число 15, 2
СуммаВВалютеСертификата : Число 15, 2
..Табличная часть \n БонусныеБаллы..
БонуснаяПрограммаЛояльности : Справочник.Бонусные программы лояльности
ДатаНачисления : Дата
ДатаСписания : Дата
СуммаБонусныхБаллов : Число 15, 2
..Табличная часть \n АкцизныеМарки..
ИдентификаторСтроки : Строка
КодАкцизнойМарки : Строка
..Движения..
ДвиженияСерийТоваров : Обороты
ИсторияПодарочныхСертификатов : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ПодарочныеСертификаты : Остатки
ДенежныеСредстваВПути : Остатки
ФактическиеДанныеБюджетирования : Обороты
ДенежныеСредстваВКассахККМ : Остатки
ТоварыНаСкладах : Остатки
СвободныеОстатки : Остатки
БонусныеБаллы : Остатки
РасчетыПоЭквайрингу : Остатки
}
@enduml
