@startuml РеализацияПодарочныхСертификатов
'!include templates.wsd
'..\include templates.wsd
class Документ.РеализацияПодарочныхСертификатов as "Реализация подарочных сертификатов" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Валюта : Справочник.Валюта
СуммаДокумента : Число 15, 2
Кассир : Справочник.Пользователь
Комментарий : Строка
КассаККМ : Справочник.Кассы ККМ
ПолученоНаличными : Число 15, 2
Статус : Статусы чеков ККМ
КассоваяСмена : Документ.Кассовая смена
Партнер : Справочник.Партнер
УдалитьНомерЧекаККМ : Число 8, 0
УдалитьВариантОтправкиЭлектронногоЧека : Варианты отправки электронного чека покупателю
УдалитьКонтактныеДанныеЭлектронногоЧека : Строка
..Табличная часть \n ПодарочныеСертификаты..
ПодарочныйСертификат : Справочник.Подарочный сертификат
Сумма : Число 15, 2
..Табличная часть \n ОплатаПлатежнымиКартами..
ЭквайринговыйТерминал : Справочник.Эквайринговый терминал
НомерПлатежнойКарты : Строка
Сумма : Число 15, 2
КодАвторизации : Строка
СсылочныйНомер : Строка
НомерЧекаЭТ : Строка
..Движения..
ИсторияПодарочныхСертификатов : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДенежныеСредстваКонтрагент : Обороты
ПодарочныеСертификаты : Остатки
ДенежныеСредстваВПути : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ДенежныеСредстваВКассахККМ : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
РасчетыПоЭквайрингу : Остатки
}
@enduml
