@startuml МатериальнаяПомощь
'!include templates.wsd
'..\include templates.wsd
class Документ.МатериальнаяПомощь as "Материальная помощь" <<Документы>>
{
..Реквизиты..
ПериодРегистрации : Дата
Организация : Справочник.Организация
УдалитьСотрудник : Справочник.Сотрудник
УдалитьФизическоеЛицо : Справочник.Физическое лицо
ВидРасчета : Начисление
УдалитьВидМатериальнойПомощи : Удалить налогообложение материальной помощи
ПорядокВыплаты : Характер выплаты зарплаты
ПланируемаяДатаВыплаты : Дата
Начислено : Число 13, 2
УдалитьНалоговыйВычет : Число 13, 2
УдалитьКоличествоДетей : Число 2, 0
УдалитьВычетПредоставленныйДругомуРодителю : Число 15, 2
УдалитьКодДоходаНДФЛ : Справочник.(не используется) Виды доходов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
УдалитьКодДоходаСтраховыеВзносы : Справочник.(не используется) Виды доходов (взносы)
Удержано : Число 13, 2
ОснованиеВыплаты : Строка
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОтношениеКЕНВД : Отношение к ЕНВД затрат на зарплату
ИсправленныйДокумент : Документ.Материальная помощь
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
КраткийСоставДокумента : Строка
УдалитьОблагаетсяЕНВД : Булево
ДокументОснование : Строка
ДокументРассчитан : Булево
Рассчитал : Справочник.Пользователь
Ответственный : Справочник.Пользователь
Комментарий : Строка
ДоначислитьЗарплатуПриНеобходимости : Булево
..Табличная часть \n Начисления..
Сотрудник : Справочник.Сотрудник
Результат : Число 15, 2
Подразделение : Справочник.Подразделение
ФиксРасчет : Булево
ФиксЗаполнение : Булево
ИдентификаторСтрокиВидаРасчета : Число 7, 0
СуммаВычета : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
КоличествоДетей : Число 2, 0
ВычетПредоставленныйДругомуРодителю : Число 15, 2
ФиксСуммаВычета : Булево
ПериодДействия : Дата
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ПериодРегистрацииВремени : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n НачисленияПерерасчет..
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Результат : Число 13, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
Сторно : Булево
СторнируемыйДокумент : Документ.Приз, подарок\rДокумент.Простой сотрудников\rДокумент.Отпуск без сохранения оплаты списком\r...
Сотрудник : Справочник.Сотрудник
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
СуммаВычета : Число 15, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
ФиксСторно : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ПериодРегистрацииВремени : Дата
ВремяВЧасах : Булево
ВидУчетаВремени : Справочник.Вид рабочего времени
ОплаченоДней : Число 15, 2
ОплаченоЧасов : Число 15, 2
РезультатВТомЧислеЗаСчетФБ : Число 15, 2
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ПериодДействия : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n НДФЛ..
ФизическоеЛицо : Справочник.Физическое лицо
МесяцНалоговогоПериода : Дата
Подразделение : Справочник.Территория\rСправочник.Подразделение
Налог : Число 10, 0
ЗачтеноАвансовыхПлатежей : Число 10, 0
УдалитьНалогКЗачетуВозврату : Число 10, 0
ПримененныйВычетЛичный : Число 12, 2
ПримененныйВычетЛичныйКодВычета : Справочник.Вид вычетов НДФЛ
УдалитьПримененныйВычетЛичныйКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
ПримененныйВычетЛичныйКЗачетуВозврату : Число 12, 2
ПримененныйВычетЛичныйКЗачетуВозвратуКодВычета : Справочник.Вид вычетов НДФЛ
УдалитьПримененныйВычетЛичныйКЗачетуВозвратуКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
ИдентификаторСтрокиНДФЛ : Число 7, 0
ФиксСтрока : Булево
ФиксРасчет : Булево
КатегорияДохода : Категории доходов НДФЛ
..Табличная часть \n Показатели..
Показатель : Справочник.Показатель
Значение : Число 15, 5
ИдентификаторСтрокиВидаРасчета : Число 7, 0
..Табличная часть \n ПримененныеВычетыНаДетейИИмущественные..
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
РазмерВычета : Число 12, 2
ИдентификаторСтрокиНДФЛ : Число 7, 0
..Табличная часть \n Удержания..
ФизическоеЛицо : Справочник.Физическое лицо
ДатаНачала : Дата
ДатаОкончания : Дата
ДокументОснование : Документ.Удержание по прочим операциям\rДокумент.Удержание добровольных взносов в НПФ\rДокумент.Удержание профсоюзных взносов\r...
Получатель : Справочник.Контрагент
ПлатежныйАгент : Справочник.Контрагент
Удержание : Удержание
ФиксРасчет : Булево
Результат : Число 13, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ФиксСтрока : Булево
ФиксЗаполнение : Булево
Сотрудник : Справочник.Сотрудник
ФиксСторно : Булево
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Табличная часть \n РаспределениеРезультатовНачислений..
ИдентификаторСтроки : Число 7, 0
Территория : Справочник.Территория
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОблагаетсяЕНВД : Булево
Результат : Число 13, 2
..Табличная часть \n РаспределениеРезультатовУдержаний..
ИдентификаторСтроки : Число 7, 0
ВидУдержания : Виды особых начислений и удержаний\rУдержание
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
Результат : Число 13, 2
..Табличная часть \n РаспределениеПоТерриториямУсловиямТруда..
ИдентификаторСтроки : Число 7, 0
Территория : Справочник.Территория
УсловияТруда : Справочник.Условия труда
ДоляРаспределения : Число 15, 5
Результат : Число 15, 2
ИдентификаторСтрокиПоказателей : Число 7, 0
СуммаВычета : Число 13, 0
..Табличная часть \n КорректировкиВыплаты..
ФизическоеЛицо : Справочник.Физическое лицо
КорректировкаВыплаты : Число 15, 2
ИдентификаторСтроки : Число 7, 0
ФиксСтрока : Булево
ФиксРасчет : Булево
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
Удержания : РегистрРасчета
РасчетыНалогоплательщиковСБюджетомПоНДФЛ : Остатки
ДанныеОВремениДляРасчетаСреднегоФСС : РегистрСведений
ЗначенияПоказателейУдержаний : РегистрСведений
ВзаиморасчетыССотрудниками : Остатки
НачисленияУдержанияПоСотрудникам : Обороты
ПорядокВыплатыДокументов : РегистрСведений
УдержанияДоПределаПоСотрудникам : Остатки
РаспределениеПоТерриториямУсловиямТруда : РегистрСведений
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
ДанныеОВремениДляРасчетаСреднегоОбщий : Обороты
СведенияОДоходахСтраховыеВзносы : Обороты
ИмущественныеВычетыНДФЛ : Остатки
ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаОбщий : Обороты
ЗначенияПоказателейНачислений : РегистрСведений
ПредоставленныеСтандартныеИСоциальныеВычетыНДФЛ : Обороты
ЗарплатаКВыплатеАвансом : Остатки
УдержанияПоИсполнительнымДокументам : Обороты
Начисления : РегистрРасчета
СведенияОДоходахНДФЛ : Обороты
НачисленияУдержанияПоСотрудникамАвансом : Обороты
БухучетНачисленияУдержанияПоСотрудникам : Обороты
ЗарплатаКВыплате : Остатки
ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаФСС : Обороты
АвансовыеПлатежиИностранцевПоНДФЛ : Остатки
}
@enduml
