@startuml ОтпускПоУходуЗаРебенком
'!include templates.wsd
'..\include templates.wsd
class Документ.ОтпускПоУходуЗаРебенком as "Отпуск по уходу за ребенком" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Сотрудник : Справочник.Физическое лицо
ОсновнойСотрудник : Справочник.Сотрудник
ДатаНачала : Дата
ДатаОкончания : Дата
ДатаОкончанияПособияДоПолутораЛет : Дата
ДатаОкончанияПособияДоТрехЛет : Дата
СреднийДневнойЗаработок : Число 15, 2
МинимальныйСреднедневнойЗаработок : Число 15, 2
КоличествоДетей : Число 2, 0
КоличествоПервыхДетей : Число 1, 0
ВыплачиватьПособиеДоПолутораЛет : Булево
ПособиеДоПолутораЛет : Начисление
ВыплачиватьПособиеДоТрехЛет : Булево
ПособиеДоТрехЛет : Начисление
РазмерПособияДоТрехЛетФиксированнойСуммой : Число 15, 2
ПериодРасчетаСреднегоЗаработкаНачало : Дата
ПериодРасчетаСреднегоЗаработкаОкончание : Дата
ФиксПериодРасчетаСреднегоЗаработка : Булево
ПериодРасчетаСреднегоЗаработкаПервыйГод : Число 4, 0
ПериодРасчетаСреднегоЗаработкаВторойГод : Число 4, 0
ПрименятьЛьготыПриНачисленииПособия : Булево
ИзменитьНачисления : Булево
НеНачислятьЗарплатуИНеВыплачиватьАвансВоВремяОтпуска : Булево
УдалитьПереноситьДанныеВДругойУчетСреднегоЗаработка : Булево
УчитыватьЗаработокПредыдущихСтрахователей : Булево
РасчетПоПравилам2010Года : Булево
ФинансированиеФедеральнымБюджетом : Основания финансирования пособия федеральным бюджетом
НачисленияУтверждены : Булево
ПособиеВыплачиваетсяФСС : Булево
ДоляНеполногоВремени : Число 4, 3
РайонныйКоэффициентРФнаНачалоСобытия : Число 3, 2
ПериодРегистрации : Дата
РассчитатьЗарплату : Булево
ОсвобождатьСтавку : Булево
ПорядокВыплаты : Характер выплаты зарплаты
ПланируемаяДатаВыплаты : Дата
Начислено : Число 13, 2
Удержано : Число 13, 2
ИсправленныйДокумент : Документ.Отпуск по уходу за ребенком
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ИзменитьЛьготы : Булево
Решение : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Начисления..
Действие : Действия с начислениями и удержаниями
Начисление : Начисление
РабочееМесто : Справочник.Сотрудник
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Размер : Число 15, 2
..Табличная часть \n Показатели..
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Показатель : Справочник.Показатель
Значение : Число 15, 5
Действие : Действия с начислениями и удержаниями
РабочееМесто : Справочник.Сотрудник
..Табличная часть \n СреднийЗаработокФСС..
ФизическоеЛицо : Справочник.Физическое лицо
УдалитьСотрудник : Справочник.Сотрудник
ПорядокРасчета : Порядок расчета среднего заработка ФСС
СтатьяФинансирования : Справочник.Статья финансирования
Период : Дата
Сумма : Число 15, 2
УдалитьКорректировка : Булево
Источник : Источники данных для расчета среднего заработка
..Табличная часть \n ОтработанноеВремяДляСреднегоФСС..
ФизическоеЛицо : Справочник.Физическое лицо
УдалитьСотрудник : Справочник.Сотрудник
Период : Дата
ОтработаноДнейКалендарных : Число 7, 2
ДнейБолезниУходаЗаДетьми : Число 7, 0
УдалитьКорректировка : Булево
Источник : Источники данных для расчета среднего заработка
..Табличная часть \n СреднийЗаработокДанныеСтрахователей..
ФизическоеЛицо : Справочник.Физическое лицо
Год : Число 4, 0
Страхователь : Справочник.Работодатель\rСправочник.Организация
Сумма : Число 15, 2
ДнейБолезниУходаЗаДетьми : Число 5, 2
..Табличная часть \n ДанныеОДетях..
Очередность : Число 2, 0
ДатаРожденияРебенка : Дата
ВидПодтверждающегоДокумента : Виды подтверждающих документов отпуска по уходу
НаименованиеПодтверждающегоДокумента : Строка
ДатаДокумента : Дата
СерияДокумента : Строка
НомерДокумента : Строка
НаличиеРешенияСудаОЛишенииПрав : Булево
Фамилия : Строка
Имя : Строка
Отчество : Строка
ИдентификаторСтроки : Строка
..Табличная часть \n ПересчетТарифныхСтавок..
РабочееМесто : Справочник.Сотрудник
ПорядокРасчетаСтоимостиЕдиницыВремени : Порядок расчета стоимости часа (дня) оплаты труда сотрудников
СовокупнаяТарифнаяСтавка : Число 15, 5
ВидТарифнойСтавки : Виды тарифных ставок
..Табличная часть \n Взносы..
ФизическоеЛицо : Справочник.Физическое лицо
ДатаПолученияДохода : Дата
ФФОМС : Число 15, 2
ФФОМСЕНВД : Число 15, 2
ТФОМС : Число 15, 2
ТФОМСЕНВД : Число 15, 2
ФСС : Число 15, 2
ФССЕНВД : Число 15, 2
ФССНесчастныеСлучаи : Число 15, 2
ПФРНакопительная : Число 15, 2
ПФРНакопительнаяЕНВД : Число 15, 2
ПФРСтраховая : Число 15, 2
ПФРСтраховаяЕНВД : Число 15, 2
ПФРПоСуммарномуТарифу : Число 15, 2
ПФРПоСуммарномуТарифуЕНВД : Число 15, 2
ПФРНаДоплатуЛетчикам : Число 15, 2
ПФРНаДоплатуШахтерам : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботах : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботах : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахОпасный : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный1 : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный2 : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный3 : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный4 : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахОпасный : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный1 : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный2 : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный3 : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный4 : Число 15, 2
ПФРДоПредельнойВеличины : Число 15, 2
ПФРДоПредельнойВеличиныЕНВД : Число 15, 2
ПФРСПревышения : Число 15, 2
ПФРСПревышенияЕНВД : Число 15, 2
..Табличная часть \n ОплатаТруда..
Начисление : Начисление
ДатаНачала : Дата
ДатаОкончания : Дата
Результат : Число 13, 2
Подразделение : Справочник.Подразделение
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
Сотрудник : Справочник.Сотрудник
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ВидУчетаВремени : Справочник.Вид рабочего времени
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
ВремяВЧасах : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ПериодРегистрацииВремени : Дата
СуммаВычета : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
ОплаченоДней : Число 15, 2
ОплаченоЧасов : Число 15, 2
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ПериодДействия : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n УправленческиеНачисления..
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Результат : Число 13, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ВидУчетаВремени : Справочник.Вид рабочего времени
ВремяВЧасах : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ПериодРегистрацииВремени : Дата
ОплаченоДней : Число 7, 2
ОплаченоЧасов : Число 7, 2
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ПериодДействия : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n НДФЛ..
ФизическоеЛицо : Справочник.Физическое лицо
МесяцНалоговогоПериода : Дата
Подразделение : Справочник.Территория\rСправочник.Подразделение
Налог : Число 10, 0
ЗачтеноАвансовыхПлатежей : Число 10, 0
УдалитьНалогКЗачетуВозврату : Число 10, 0
ПримененныйВычетЛичный : Число 12, 2
ПримененныйВычетЛичныйКодВычета : Справочник.Вид вычетов НДФЛ
УдалитьПримененныйВычетЛичныйКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
ПримененныйВычетЛичныйКЗачетуВозврату : Число 12, 2
ПримененныйВычетЛичныйКЗачетуВозвратуКодВычета : Справочник.Вид вычетов НДФЛ
УдалитьПримененныйВычетЛичныйКЗачетуВозвратуКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
ИдентификаторСтрокиНДФЛ : Число 7, 0
ФиксСтрока : Булево
ФиксРасчет : Булево
КатегорияДохода : Категории доходов НДФЛ
..Табличная часть \n ПогашениеЗаймов..
ФизическоеЛицо : Справочник.Физическое лицо
ДоговорЗайма : Документ.Договор займа сотруднику
НачисленоПроцентов : Число 15, 2
ПогашениеПроцентов : Число 15, 2
ПогашениеЗайма : Число 15, 2
МатериальнаяВыгода : Число 15, 2
НалогНаМатериальнуюВыгоду : Число 13, 0
СтавкаНалогообложенияМатвыгоды : НДФЛ ставки налогообложения резидента
Подразделение : Справочник.Подразделение
ИдентификаторСтроки : Число 7, 0
..Табличная часть \n ПримененныеВычетыНаДетейИИмущественные..
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
РазмерВычета : Число 12, 2
ИдентификаторСтрокиНДФЛ : Число 7, 0
..Табличная часть \n Удержания..
ФизическоеЛицо : Справочник.Физическое лицо
ДатаНачала : Дата
ДатаОкончания : Дата
ДокументОснование : Документ.Удержание по прочим операциям\rДокумент.Удержание добровольных взносов в НПФ\rДокумент.Удержание профсоюзных взносов\r...
Получатель : Справочник.Контрагент
ПлатежныйАгент : Справочник.Контрагент
Удержание : Удержание
ФиксРасчет : Булево
Результат : Число 13, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ФиксЗаполнение : Булево
ФиксСтрока : Булево
Сотрудник : Справочник.Сотрудник
ФиксСторно : Булево
..Табличная часть \n РаспределениеРезультатовНачислений..
ИдентификаторСтроки : Число 7, 0
Территория : Справочник.Территория
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОблагаетсяЕНВД : Булево
Результат : Число 13, 2
..Табличная часть \n РаспределениеРезультатовУдержаний..
ИдентификаторСтроки : Число 7, 0
ВидУдержания : Виды особых начислений и удержаний\rУдержание
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
Результат : Число 13, 2
..Табличная часть \n Льготы..
Действие : Действия с начислениями и удержаниями
Льгота : Начисление
РабочееМесто : Справочник.Сотрудник
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Размер : Число 15, 2
..Табличная часть \n ОплатаЛьгот..
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Результат : Число 13, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
СуммаВычета : Число 15, 2
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ВидУчетаВремени : Справочник.Вид рабочего времени
ВремяВЧасах : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ПериодРегистрацииВремени : Дата
ОплаченоДней : Число 7, 2
ОплаченоЧасов : Число 7, 2
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ПериодДействия : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n ПериодыБолезниУходаЗаДетьми..
Начало : Дата
Окончание : Дата
Дни : Число 10, 0
ВидБолезниУходаЗаДетьми : Строка
Источник : Источники данных для расчета среднего заработка
УдалитьКорректировка : Булево
..Табличная часть \n РаспределениеПоТерриториямУсловиямТруда..
ИдентификаторСтроки : Число 7, 0
Территория : Справочник.Территория
УсловияТруда : Справочник.Условия труда
ДоляРаспределения : Число 15, 5
Результат : Число 15, 2
ИдентификаторСтрокиПоказателей : Число 7, 0
СуммаВычета : Число 13, 0
..Табличная часть \n КорректировкиВыплаты..
ФизическоеЛицо : Справочник.Физическое лицо
КорректировкаВыплаты : Число 15, 2
ИдентификаторСтроки : Число 7, 0
ФиксСтрока : Булево
ФиксРасчет : Булево
..Движения..
УдалитьИсключаемыеИзОстатковОтпусковПериоды : РегистрСведений
Удержания : РегистрРасчета
РасчетыНалогоплательщиковСБюджетомПоНДФЛ : Остатки
ДанныеОВремениДляРасчетаСреднегоФСС : РегистрСведений
ЗначенияПоказателейУдержаний : РегистрСведений
ВзаиморасчетыССотрудниками : Остатки
ОтработанноеВремяПоСотрудникамАвансом : Обороты
НачисленияУдержанияПоСотрудникам : Обороты
ПорядокРасчетаСтоимостиЕдиницыВремениСотрудников : РегистрСведений
ЗанятыеПозицииШтатногоРасписания : Остатки
ОтработанноеВремяПоСотрудникамКорректировка : Обороты
УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников : РегистрСведений
УсловияОплатыОтпускаПоУходуЗаРебенком : РегистрСведений
ПрименениеДополнительныхПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
РасчетыСФондамиПоСтраховымВзносам : Остатки
ПорядокВыплатыДокументов : РегистрСведений
ПособияПоСоциальномуСтрахованию : Обороты
УдержанияДоПределаПоСотрудникам : Остатки
ДанныеСостоянийСотрудников : РегистрСведений
РаспределениеПоТерриториямУсловиямТруда : РегистрСведений
ПрименениеПлановыхНачислений : РегистрСведений
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
ДанныеОВремениДляРасчетаСреднегоОбщий : Обороты
ФактическиеОтпуска : Обороты
СведенияОДоходахСтраховыеВзносы : Обороты
ИмущественныеВычетыНДФЛ : Остатки
ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаОбщий : Обороты
ЗначенияПоказателейНачислений : РегистрСведений
СтраховыеВзносыПоФизическимЛицам : Обороты
ПредоставленныеСтандартныеИСоциальныеВычетыНДФЛ : Обороты
ЗарплатаКВыплатеАвансом : Остатки
УдержанияПоИсполнительнымДокументам : Обороты
ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
ОтработанноеВремяПоСотрудникам : Обороты
Начисления : РегистрРасчета
РеестрОтпусков : РегистрСведений
ИсчисленныеСтраховыеВзносы : Обороты
БухучетПлановыхНачислений : РегистрСведений
СведенияОДоходахНДФЛ : Обороты
НачисленияУдержанияПоСотрудникамАвансом : Обороты
БухучетНачисленияУдержанияПоСотрудникам : Обороты
КоэффициентыРаспределенияСреднегоЗаработка : РегистрСведений
ЗарплатаКВыплате : Остатки
ПараметрыПериодовСтажаПФР : РегистрСведений
ПлановыеНачисления : РегистрСведений
ВзаиморасчетыПоЗаймамСотрудникам : Остатки
ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаФСС : Обороты
АвансовыеПлатежиИностранцевПоНДФЛ : Остатки
}
@enduml
