@startuml ПлановаяКалькуляция
'!include templates.wsd
'..\include templates.wsd
class Документ.ПлановаяКалькуляция as "Плановая калькуляция" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Статус : Статусы плановых калькуляций
ДатаНачалаДействия : Дата
ДатаОкончанияДействия : Дата
ДетализироватьСтатьиКалькуляции : Булево
ВидЦены : Справочник.Вид цены
Ответственный : Справочник.Пользователь
Комментарий : Строка
КалькуляционнаяЕдиница : Число 15, 3
ОбъектКалькуляции : Объекты калькуляции
ВыводитьИерархиюСтатейКалькуляции : Булево
Валюта : Справочник.Валюта
ИспользоватьОрганизацию : Булево
СуммаПоДокументу : Число 15, 3
КраткийСоставДокумента : Строка
..Табличная часть \n ДействиеКалькуляции..
Объект : Справочник.Номенклатура\rДокумент.Заказ на производство\rСправочник.Ресурсная спецификация\r...
Характеристика : Справочник.Характеристика номенклатуры
КодСтрокиЗаказаНаПроизводство : Число 10, 0
ИспользоватьХарактеристику : Булево
..Табличная часть \n СтатьиКалькуляции..
СтатьяКалькуляции : Справочник.Статьи калькуляции
СпособРасчета : Способы расчета затрат плановой калькуляции
Формула : Строка
Сумма : Число 15, 2
..Табличная часть \n ВозвратныеОтходы..
СтатьяКалькуляции : Справочник.Статьи калькуляции
ОписаниеИзделия : Строка
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Цена : Число 15, 2
Сумма : Число 15, 2
ВидЦены : Справочник.Вид цены
..Табличная часть \n МатериалыИУслуги..
СтатьяКалькуляции : Справочник.Статьи калькуляции
ПрименениеМатериала : Строка
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Цена : Число 15, 2
Сумма : Число 15, 2
ВидЦены : Справочник.Вид цены
Калькуляция : Документ.Плановая калькуляция
..Табличная часть \n Трудозатраты..
СтатьяКалькуляции : Справочник.Статьи калькуляции
НазначениеРабот : Строка
ВидРабот : Справочник.Вид работ сотрудников
Количество : Число 15, 3
Расценка : Число 15, 2
Сумма : Число 15, 2
..Табличная часть \n СтатьиРасходов..
СтатьяКалькуляции : Справочник.Статьи калькуляции
СтатьяРасходов : Статья расходов
РасчетПоФормуле : Булево
Формула : Строка
Сумма : Число 15, 2
..Табличная часть \n ВлияющиеСтатьиКалькуляции..
СтатьяКалькуляции : Справочник.Статьи калькуляции
ВлияющаяСтатьяКалькуляции : Справочник.Статьи калькуляции
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
