@startuml ИзменениеУсловийДоговораЗаймаСотруднику
'!include templates.wsd
'..\include templates.wsd
class Документ.ИзменениеУсловийДоговораЗаймаСотруднику as "Изменение условий договора займа сотруднику" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
ДоговорЗайма : Документ.Договор займа сотруднику
Сумма : Число 15, 2
ДатаИзменений : Дата
ДатаОкончания : Дата
ПроцентнаяСтавка : Число 4, 2
РазмерПлатежа : Число 15, 2
РазмерПогашения : Число 15, 2
ДатаНачалаПогашения : Дата
ОграничениеПлатежа : Число 15, 2
МатериальнаяВыгодаОблагаетсяНДФЛ : Булево
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ТраншиЗайма..
ДатаПредоставления : Дата
Сумма : Число 15, 2
РазмерПогашения : Число 15, 2
ДатаПогашения : Дата
..Движения..
УсловияДоговораЗаймаСотруднику : РегистрСведений
ТраншиЗаймаСотруднику : РегистрСведений
}
@enduml
