@startuml ЗаявлениеСотрудникаНаВыплатуПособия
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаявлениеСотрудникаНаВыплатуПособия as "Заявление сотрудника на выплату пособия" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ДокументОснование : Документ.Единовременное пособие\rДокумент.Отпуск\rДокумент.Больничный лист\r...
Перерасчет : Булево
КодПричиныПерерасчета : Строка
НаименованиеТерриториальногоОрганаФСС : Строка
ПолучательНеЯвляетсяЗаявителем : Булево
ФамилияЗаявителя : Строка
ИмяЗаявителя : Строка
ОтчествоЗаявителя : Строка
ВидДокументаУдостоверяющегоЛичностьЗаявителя : Справочник.Вид документа физических лиц
СерияДокументаУдостоверяющегоЛичностьЗаявителя : Строка
НомерДокументаУдостоверяющегоЛичностьЗаявителя : Строка
ДатаВыдачиДокументаУдостоверяющегоЛичностьЗаявителя : Дата
КемВыданДокументУдостоверяющийЛичностьЗаявителя : Строка
Гражданство : Справочник.Страна мира
ВидПособия : Пособия назначаемые ФСС
СпособВыплатыПособия : Способы выплаты пособия выплачиваемого ФСС
Банк : Справочник.Банк
НаименованиеБанка : Строка
БИКБанка : Строка
НомерЛицевогоСчета : Строка
ФамилияПолучателя : Строка
ИмяПолучателя : Строка
ОтчествоПолучателя : Строка
АдресПолучателяФактический : Строка
АдресПолучателяРегистрации : Строка
ТелефонПолучателя : Строка
ДатаРожденияПолучателя : Дата
ВидДокументаУдостоверяющегоЛичностьПолучателя : Справочник.Вид документа физических лиц
СерияДокументаУдостоверяющегоЛичностьПолучателя : Строка
НомерДокументаУдостоверяющегоЛичностьПолучателя : Строка
ДатаВыдачиДокументаУдостоверяющегоЛичностьПолучателя : Дата
ДатаДействияДокументаУдостоверяющегоЛичностьПолучателя : Дата
КемВыданДокументУдостоверяющийЛичностьПолучателя : Строка
ВидДокументаНаПроживание : Справочник.Вид документа физических лиц
СерияДокументаНаПроживание : Строка
НомерДокументаНаПроживание : Строка
ДатаВыдачиДокументаНаПроживание : Дата
НомерЛисткаНетрудоспособности : Строка
ДатаЛисткаНетрудоспособности : Дата
ДатаСправкиОПостановкеНаУчетВРанниеСрокиБеременности : Дата
НомерСправкиОПостановкеНаУчетВРанниеСрокиБеременности : Строка
ФормаСправкиОРожденииРебенка : Формы справки о рождении ребенка
ДатаСправкиОРожденииРебенка : Дата
НомерСправкиОРожденииРебенка : Строка
ДатаСвидетельстваОРождении : Дата
СерияСвидетельстваОРождении : Строка
НомерСвидетельстваОРождении : Строка
ДатаИногоДокументаПодтверждающегоРождение : Дата
НомерИногоДокументаПодтверждающегоРождение : Строка
ДатаРешенияОбОпеке : Дата
НомерРешенияОбОпеке : Строка
ДатаРешенияОбУсыновлении : Дата
НомерРешенияОбУсыновлении : Строка
ДатаДоговораОПередачеРебенкаВПриемнуюСемью : Дата
НомерДоговораОПередачеРебенкаВПриемнуюСемью : Строка
НаличиеОдногоИзДокументовНаПредыдущихДетей : Булево
НаличиеСвидетельстваОСмертиПредыдущихДетей : Булево
СправкаОНеполученииПособия : Родители предоставившие справку о неполучении пособия
ДатаСправкиОНеполученииПособияОтОтца : Дата
НомерСправкиОНеполученииПособияОтОтца : Строка
ДатаСправкиОНеполученииПособияОтМатери : Дата
НомерСправкиОНеполученииПособияОтМатери : Строка
ДатаСправкиОНеполученииПособияПоДругимМестамРаботы : Дата
НомерСправкиОНеполученииПособияПоДругимМестамРаботы : Строка
ОтношениеКОсобойЗоне : Отношение к особой зоне
ВидОсобойЗоныПроживанияРаботы : Вид особой зоны проживания или работы
НаименованиеОрганизации : Строка
РайонныйКоэффициент : Число 3, 2
ТипЗанятостиРаботника : Виды занятости
ДатаНачалаТрудовогоДоговораПолучателя : Дата
ДатаОкончанияТрудовогоДоговораПолучателя : Дата
ИННПолучателя : Строка
СНИЛСПолучателя : Строка
СтатусНалогоплательщикаПолучателя : Справочник.Статус налогоплательщика
УдалитьСтатусНалогоплательщикаПолучателя : Справочник.(не используется) Статусы налогоплательщиков (НДФЛ)
ЗамененыКалендарныеГодыРасчетаСреднегоЗаработка : Булево
ПервыйЗамененныйГод : Число 4, 0
ВторойЗамененныйГод : Число 4, 0
ПервыйРасчетныйГод : Число 4, 0
ВторойРасчетныйГод : Число 4, 0
СчитатьПоПравилам2010Года : Булево
ДатаНачалаРасчетногоПериода : Дата
ДатаОкончанияРасчетногоПериода : Дата
ЧислоКалендарныхДнейРасчетногоПериода : Число 3, 0
НеполноеРабочееВремя : Булево
РазмерСтавки : Число 3, 2
ДолжностнойОклад : Число 9, 2
СреднийЗаработокЗаРасчетныйПериод : Число 9, 2
ДатаПриказаОПредоставленииОтпускаПоУходуЗаРебенком : Дата
НомерПриказаОПредоставленииОтпускаПоУходуЗаРебенком : Строка
ДатаНачалаОтпускаПоУходуЗаРебенком : Дата
ДатаОкончанияОтпускаПоУходуЗаРебенком : Дата
ДатаПриказаОЗаменеПослеродовогоОтпуска : Дата
НомерПриказаОЗаменеПослеродовогоОтпуска : Строка
ПериодПростоя1ДатаНачала : Дата
ПериодПростоя1ДатаОкончания : Дата
ПериодПростоя1СреднийЗаработок : Число 8, 2
ПериодПростоя2ДатаНачала : Дата
ПериодПростоя2ДатаОкончания : Дата
ПериодПростоя2СреднийЗаработок : Число 8, 2
НеоплачиваемыйПериод1ДатаНачала : Дата
НеоплачиваемыйПериод2ДатаНачала : Дата
НеоплачиваемыйПериод1ДатаОкончания : Дата
НеоплачиваемыйПериод2ДатаОкончания : Дата
ДолжностьУполномоченного : Справочник.Должность
ФИОУполномоченного : Строка
ТелефонУполномоченного : Строка
ЗаработокПервыйГодРасчета : Число 13, 2
ЗаработокВторойГодРасчета : Число 13, 2
ПорядокРасчетаСреднегоЗаработка : Способы расчета среднего заработка для оплаты пособия
МРОТ : Число 15, 2
ДатаЗаявленияОЗаменеРасчетныхГодов : Дата
НомерЗаявленияОЗамененРасчетныхГодов : Строка
ВидРеестра : Виды реестров сведений необходимых для назначения и выплаты пособий
ИдентификаторСтрокиОснования : Строка
ФамилияРебенка : Строка
ИмяРебенка : Строка
ОтчествоРебенка : Строка
ДатаРожденияРебенка : Дата
УдалитьБанк : Строка
УдалитьКоррСчетБанка : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
КоличествоОплаченныхДнейНетрудоспособностиИнвалида : Число 3, 0
ФинансированиеФедеральнымБюджетом : Основания финансирования пособия федеральным бюджетом
НомерКартыМИР : Строка
ДатаПредставленияПакетаДокументов : Дата
..Табличная часть \n ФиксацияИзменений..
ИмяРеквизита : Строка
Путь : Строка
ИдентификаторСтроки : Число 5, 0
..Табличная часть \n КонтактнаяИнформация..
Тип : Типы контактной информации
Вид : Справочник.Вид контактной информации
Представление : Строка
ЗначенияПолей : Строка
Страна : Строка
Регион : Строка
Город : Строка
АдресЭП : Строка
ДоменноеИмяСервера : Строка
НомерТелефона : Строка
НомерТелефонаБезКодов : Строка
}
@enduml
