@startuml УведомлениеОПравеНаИмущественныйВычетДляНДФЛ
'!include templates.wsd
'..\include templates.wsd
class Документ.УведомлениеОПравеНаИмущественныйВычетДляНДФЛ as "Уведомление НО о праве на вычеты" <<Документы>>
{
..Реквизиты..
НалоговыйПериод : Число 4, 0
Организация : Справочник.Организация
Сотрудник : Справочник.Физическое лицо
ПрименятьВычетыС : Дата
РасходыНаСтроительствоПриобретение : Число 15, 2
ПроцентыПоКредитам : Число 15, 2
ПроцентыПриПерекредитовании : Число 15, 2
НомерУведомления : Строка
ДатаУведомления : Дата
КодНалоговогоОргана : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
РасходыНаСвоеОбучение : Число 15, 2
РасходыНаОбучениеДетей : Число 15, 2
РасходыНаЛечение : Число 15, 2
СтраховыеВзносыНаМедУслуги : Число 15, 2
РасходыНаДорогостоящееЛечение : Число 15, 2
ВзносыНаДобровольноеСтрахованиеЖизни : Число 15, 2
..Движения..
ИмущественныеВычетыНДФЛ : Остатки
}
@enduml
