@startuml ЗапросНаИнформационноеОбслуживаниеНалогоплательщика
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗапросНаИнформационноеОбслуживаниеНалогоплательщика as "Запрос на информационное обслуживание налогоплательщика" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Получатель : Справочник.Регистрация в налоговом органе
ДатаНачалаПериода : Дата
ДатаОкончанияПериода : Дата
ВидУслуги : Виды услуг при информационном обслуживании налогоплательщика
ФорматОтвета : Формат ответа на запрос на информационное обслуживание налогоплательщика
АдресПредставленияСправки : Строка
ДополнительныйПараметр : Число 1, 0
ФорматЗапроса : Форматы документооборота с ФНС
КоличествоНалогов : Количество налогов для сверки ИОН
..Табличная часть \n ЗапрашиваемыеНалоги..
КБК : Строка
ОКАТО : Строка
Налог : Строка
}
@enduml
