@startuml СведенияОСтраховомСтажеЗастрахованныхЛицСЗВ_СТАЖ
'!include templates.wsd
'..\include templates.wsd
class Документ.СведенияОСтраховомСтажеЗастрахованныхЛицСЗВ_СТАЖ as "Сведения о страховом стаже застрахованных лиц, СЗВ-СТАЖ" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Год : Число 4, 0
ТипСведений : Типы сведений СЗВ-СТАЖ
ИмяФайлаДляПФР : Строка
ДокументПринятВПФР : Булево
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ФайлСформирован : Булево
КраткийСоставДокумента : Строка
ОтчетныйПериод : Дата
ОкончаниеОтчетногоПериода : Дата
НачисленыВзносыНаОПС : Булево
НачисленыВзносыПоДТ : Булево
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Физическое лицо
СтраховойНомерПФР : Строка
Фамилия : Строка
Имя : Строка
Отчество : Строка
СотрудникУволен : Булево
ДатаВыходаНаПенсию : Дата
ФиксСтаж : Булево
..Табличная часть \n ЗаписиОСтаже..
Сотрудник : Справочник.Физическое лицо
НомерОсновнойЗаписи : Число 2, 0
НомерДополнительнойЗаписи : Число 2, 0
ДатаНачалаПериода : Дата
ДатаОкончанияПериода : Дата
ОсобыеУсловияТруда : Справочник.Особое условие труда
КодПозицииСписка : Справочник.Льготная профессия (ПФР)
ОснованиеИсчисляемогоСтажа : Справочник.Основание для исчисления стажа
ПервыйПараметрИсчисляемогоСтажа : Число 3, 0
ВторойПараметрИсчисляемогоСтажа : Число 2, 0
ТретийПараметрИсчисляемогоСтажа : Справочник.Доп. сведение для исчисления стажа
ОснованиеВыслугиЛет : Справочник.Основание для досрочной пенсии
ПервыйПараметрВыслугиЛет : Число 4, 0
ВторойПараметрВыслугиЛет : Число 4, 0
ТретийПараметрВыслугиЛет : Число 5, 2
ТерриториальныеУсловия : Справочник.Территориальное условие
ПараметрТерриториальныхУсловий : Число 3, 2
ЗамещениеГосударственныхМуниципальныхДолжностей : Справочник.Замещение государственных муниципальных должностей ПФР
..Табличная часть \n ДосрочноеНазначениеПенсии..
Подразделение : Справочник.Подразделение
Должность : Справочник.Должность
КоличествоРабочихМест : Число 10, 2
КоличествоРаботающих : Число 10, 0
ХарактерВыполняемыхРабот : Строка
ПервичныеДокументы : Строка
ОснованиеВыслугиЛет : Справочник.Особое условие труда
КодПозицииСписка : Справочник.Льготная профессия (ПФР)
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
}
@enduml
