@startuml ЭкземплярБюджета
'!include templates.wsd
'..\include templates.wsd
class Документ.ЭкземплярБюджета as "Экземпляр бюджета" <<Документы>>
{
..Реквизиты..
МодельБюджетирования : Справочник.Модели бюджетирования
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Сценарий : Справочник.Сценарии бюджетирования
НачалоПериода : Дата
ОкончаниеПериода : Дата
ВидБюджета : Справочник.Вид бюджета
Ответственный : Справочник.Пользователь
Комментарий : Строка
Статус : Статусы планов
ГраницаФактДанных : Дата
Аналитика1 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика2 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика3 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика4 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика5 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика6 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
..Табличная часть \n АналитикаСтатейБюджетов..
ИдентификаторСтроки : Строка
СтатьяБюджетов : Справочник.Статьи бюджетов\rСправочник.Показатели бюджетов
Аналитика1 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика2 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика3 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика4 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика5 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика6 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Валюта : Справочник.Валюта
..Табличная часть \n ОборотыПоСтатьямБюджетов..
ИдентификаторСтроки : Строка
ПериодПланирования : Дата
Сумма : Число 15, 2
Количество : Число 10, 3
СуммаВВалюте : Число 15, 2
Значение : Булево\rСтрока\rЧисло 15, 2
НомерПоПорядку : Число 15, 0
Примечание : Строка
..Табличная часть \n АналитикаЗначений..
ИдентификаторСтроки : Строка
РедактируемоеЗначение : Строка
ВидАналитики1 : Аналитики статей бюджетов
ВидАналитики2 : Аналитики статей бюджетов
ВидАналитики3 : Аналитики статей бюджетов
ВидАналитики4 : Аналитики статей бюджетов
ВидАналитики5 : Аналитики статей бюджетов
ВидАналитики6 : Аналитики статей бюджетов
Аналитика1 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика2 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика3 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика4 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика5 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика6 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
КоличествоИспользуемыхАналитик : Число 1, 0
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ОборотыБюджетов : Обороты
}
@enduml
