@startuml ВосстановлениеНДСПоОбъектамНедвижимости
'!include templates.wsd
'..\include templates.wsd
class Документ.ВосстановлениеНДСПоОбъектамНедвижимости as "Восстановление НДС по объектам недвижимости" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
Комментарий : Строка
ОтражатьВосстановлениеВКнигеПродаж : Булево
СчетСписанияНДС : Счет бухгалтерского учета
СубконтоСписанияНДС1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
СубконтоСписанияНДС2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
СубконтоСписанияНДС3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
РучнаяКорректировка : Булево
..Табличная часть \n ОбъектыНедвижимости..
КлючСтроки : Число 10, 0
ОбъектНедвижимости : Справочник.Объект эксплуатации
ИспользуетсяДляОперацийНеОблагаемыхНДС : Булево
ДатаНачалаИспользованияДляОпераций : Дата
ДатаВводаВЭксплуатациюБУ : Дата
ДатаНачисленияАмортизацииНУ : Дата
СтоимостьОбъектаНедвижимости : Число 15, 2
СуммаНДСПоПодряднымРаботам : Число 15, 2
СуммаНДСПоСМРДляСобственногоПотребления : Число 15, 2
СуммаНДСПоОбъектуНедвижимости : Число 15, 2
ДоляВыручкиНеОблагаемаяНДС : Число 15, 2
СуммаНДСПоПодряднымРаботамВосстановлена : Число 15, 2
СуммаНДСПоСМРДляСобственногоПотребленияВосстановлена : Число 15, 2
СуммаНДСПоОбъектуНедвижимостиВосстановлена : Число 15, 2
..Табличная часть \n СчетаФактуры..
КлючСтроки : Число 10, 0
ВидЦенности : Виды ценностей
КодОперацииДляДекларации : Коды операций по объектам недвижимости
Поставщик : Справочник.Контрагент
СчетФактура : Документ.Первичный документ
СуммаБезНДС : Число 15, 2
СтавкаНДС : Ставки НДС
НДС : Число 15, 2
СуммаБезНДСВосстановлена : Число 15, 2
НДСВосстановлен : Число 15, 2
..Движения..
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
НДСЗаписиКнигиПродаж : Обороты
}
@enduml
