@startuml ЖурналУчетаСчетовФактурДляПередачиВЭлектронномВиде
'!include templates.wsd
'..\include templates.wsd
class Документ.ЖурналУчетаСчетовФактурДляПередачиВЭлектронномВиде as "Журнал учета счетов-фактур для передачи в электронном виде" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
НалоговыйПериод : Дата
ПериодСоставления : Дата
Реорганизация : Булево
ПериодПоСКНП : Строка
ИФНС : Справочник.Регистрация в налоговом органе
Подписант : Справочник.Физическое лицо
Ответственный : Справочник.Пользователь
Комментарий : Строка
ПредставлениеОтчета : Хранилище значения
ДанныеОтчета : Хранилище значения
..Табличная часть \n ВыставленныеСчетаФактуры..
ДатаПередачиПолучения : Строка
КодСпособаВыставления : Строка
КодВидаОперации : Строка
НомерСчетаФактуры : Строка
ДатаСчетаФактуры : Строка
НомерКорректировочногоСчетаФактуры : Строка
ДатаКорректировочногоСчетаФактуры : Строка
НомерИсправления : Строка
ДатаИсправления : Строка
КонтрагентНаименование : Строка
КонтрагентИННКПП : Строка
Валюта : Строка
СуммаДокумента : Число 15, 2
СуммаНДС : Число 15, 2
СуммаДокументаРазницаУменьшение : Число 15, 2
СуммаДокументаРазницаУвеличение : Число 15, 2
СуммаНДСРазницаУменьшение : Число 15, 2
СуммаНДСРазницаУвеличение : Число 15, 2
Ном : Число 10, 0
СчетФактура : Документ.Первичный документ
..Табличная часть \n ПолученныеСчетаФактуры..
ДатаПередачиПолучения : Строка
КодСпособаВыставления : Строка
КодВидаОперации : Строка
НомерСчетаФактуры : Строка
ДатаСчетаФактуры : Строка
НомерКорректировочногоСчетаФактуры : Строка
ДатаКорректировочногоСчетаФактуры : Строка
НомерИсправления : Строка
ДатаИсправления : Строка
КонтрагентНаименование : Строка
КонтрагентИННКПП : Строка
Валюта : Строка
СуммаДокумента : Число 15, 2
СуммаНДС : Число 15, 2
СуммаДокументаРазницаУменьшение : Число 15, 2
СуммаДокументаРазницаУвеличение : Число 15, 2
СуммаНДСРазницаУменьшение : Число 15, 2
СуммаНДСРазницаУвеличение : Число 15, 2
Ном : Число 10, 0
СчетФактура : Документ.Первичный документ
}
@enduml
