@startuml ПроизводственнаяОперация2_2
'!include templates.wsd
'..\include templates.wsd
class Документ.ПроизводственнаяОперация2_2 as "Производственная операция" <<Документы>>
{
..Реквизиты..
Этап : Документ.Этап производства
Операция : Справочник.Операция
ИдентификаторОперации : Число 25, 0
Статус : Статусы производственных операций
Подразделение : Справочник.Подразделение
Исполнитель : Справочник.Бригады\rСправочник.Физическое лицо
ВидРабочегоЦентра : Справочник.Вид рабочего центра
РабочийЦентр : Справочник.Рабочий центр
ВариантНаладки : Справочник.Вариант наладки
Количество : Число 15, 3
ВремяВыполнения : Число 10, 1
ВремяВыполненияЕдИзм : Единицы измерения времени
Ответственный : Справочник.Пользователь
Комментарий : Строка
ДатаВыполнения : Дата
НомерОперацииЭтапа : Число 6, 0
НомерПартии : Число 10, 0
НаОснованииПланирования : Булево
..Табличная часть \n ВыходныеИзделия..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Упаковка : Справочник.Упаковка
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
..Табличная часть \n ВыходныеИзделияСерии..
Серия : Справочник.Серия номенклатуры
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Количество : Число 15, 3
..Табличная часть \n МатериалыИРаботы..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Упаковка : Справочник.Упаковка
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
НоменклатураМаршрутнойКарты : Справочник.Номенклатура
ХарактеристикаМаршрутнойКарты : Справочник.Характеристика номенклатуры
УпаковкаМаршрутнойКарты : Справочник.Упаковка
..Табличная часть \n Трудозатраты..
ВидРабот : Справочник.Вид работ сотрудников
Количество : Число 15, 3
Исполнитель : Справочник.Бригады\rСправочник.Физическое лицо
НазначениеРабот : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ДвиженияСерийТоваров : Обороты
}
@enduml
