@startuml ВыемкаДенежныхСредствИзКассыККМ
'!include templates.wsd
'..\include templates.wsd
class Документ.ВыемкаДенежныхСредствИзКассыККМ as "Выемка денежных средств из кассы ККМ" <<Документы>>
{
..Реквизиты..
КассаККМ : Справочник.Кассы ККМ
Кассир : Справочник.Пользователь
Организация : Справочник.Организация
СуммаДокумента : Число 15, 2
Валюта : Справочник.Валюта
Комментарий : Строка
..Движения..
ДвиженияДенежныхСредств : Обороты
СуммыДокументовВВалютеРегл : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДенежныеСредстваВПути : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ДенежныеСредстваВКассахККМ : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
}
@enduml
