@startuml УвольнениеСписком
'!include templates.wsd
'..\include templates.wsd
class Документ.УвольнениеСписком as "Увольнение списком" <<Документы>>
{
..Реквизиты..
ПериодРегистрации : Дата
Организация : Справочник.Организация
ДатаСобытия : Дата
Начислено : Число 13, 2
Удержано : Число 13, 2
ИсправленныйДокумент : Документ.Увольнение списком
ДокументРассчитан : Булево
Рассчитал : Справочник.Пользователь
ПредставлениеПериода : Строка
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ГлавныйБухгалтер : Справочник.Физическое лицо
Бухгалтер : Справочник.Физическое лицо
РаботникКадровойСлужбы : Справочник.Физическое лицо
ДолжностьРаботникаКадровойСлужбы : Справочник.Должность
Исполнитель : Справочник.Физическое лицо
ДолжностьИсполнителя : Справочник.Должность
ВидДоговора : Виды договоров с сотрудниками
ПорядокВыплаты : Характер выплаты зарплаты
ПланируемаяДатаВыплаты : Дата
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Сотрудник
ИдентификаторСтрокиСотрудника : Число 7, 0
ФизическоеЛицо : Справочник.Физическое лицо
ДатаУвольнения : Дата
СтатьяТКРФ : Справочник.Основание увольнения
ОснованиеУвольнения : Строка
ВыходноеПособие : Начисление
ДнейЧасовВыходногоПособия : Число 7, 2
СуммированныйУчет : Булево
ДнейКомпенсацииУдержанияОтпуска : Число 5, 2
ПризнакКомпенсацииУдержанияОтпуска : Компенсация (удержание) отпуска при увольнении
ВидРасчетаКомпенсацииУдержанияОтпуска : Начисление\rУдержание
РабочийГодС : Дата
РабочийГодПо : Дата
ПериодРасчетаСреднегоЗаработкаНачало : Дата
ПериодРасчетаСреднегоЗаработкаОкончание : Дата
ФиксПериодРасчетаСреднегоЗаработка : Булево
СреднийЗаработок : Число 15, 2
СреднийЗаработокПоРабочимДням : Число 15, 2
СреднийЗаработокВыходногоПособия : Число 15, 2
УдалитьПереноситьДанныеВДругойУчетСреднегоЗаработка : Булево
РасчетДенежногоСодержания : Булево
СохраняемоеДенежноеСодержание : Число 13, 2
МесячноеДенежноеСодержание : Число 13, 2
КоличествоМесяцевВыплатыДенежногоСодержания : Число 2, 0
ВидРасчетаМесячноеДенежноеСодержание : Начисление
ДолжностьЗамещаласьМенее12Месяцев : Булево
Сверхурочно1_5 : Число 7, 2
Сверхурочно2 : Число 7, 2
ПрименятьВычетыПослеУвольнения : Булево
Решение : Строка
ДатаУведомленияОбУвольнении : Дата
КоличествоДнейЧасовКомпенсацииПриУвольнении : Число 7, 2
КомпенсацияЗаНеотработанныеДниЧасыПриУвольнении : Начисление
ВыплачиватьКомпенсациюНеотработанныхДнейЧасовПриУвольнении : Булево
ДоначислитьЗарплатуПриНеобходимости : Булево
..Табличная часть \n ДанныеОбИндексации..
Сотрудник : Справочник.Сотрудник
ИдентификаторСтрокиСотрудника : Число 7, 0
Период : Дата
КоэффициентИндексации : Число 9, 8
..Табличная часть \n ДополнительныеОтпуска..
ИдентификаторСтрокиСотрудника : Число 7, 0
ВидОтпуска : Справочник.Вид отпуска
ДнейКомпенсацииУдержания : Число 5, 2
ВидРасчетаКомпенсацииУдержания : Начисление\rУдержание
ПризнакКомпенсацииУдержания : Компенсация (удержание) отпуска при увольнении
НачалоПериодаЗаКоторыйПредоставляетсяОтпуск : Дата
КонецПериодаЗаКоторыйПредоставляетсяОтпуск : Дата
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n Взносы..
ИдентификаторСтрокиСотрудника : Число 7, 0
ФизическоеЛицо : Справочник.Физическое лицо
ДатаПолученияДохода : Дата
ФФОМС : Число 15, 2
ФФОМСЕНВД : Число 15, 2
ТФОМС : Число 15, 2
ТФОМСЕНВД : Число 15, 2
ФСС : Число 15, 2
ФССЕНВД : Число 15, 2
ФССНесчастныеСлучаи : Число 15, 2
ПФРНакопительная : Число 15, 2
ПФРНакопительнаяЕНВД : Число 15, 2
ПФРСтраховая : Число 15, 2
ПФРСтраховаяЕНВД : Число 15, 2
ПФРПоСуммарномуТарифу : Число 15, 2
ПФРПоСуммарномуТарифуЕНВД : Число 15, 2
ПФРНаДоплатуЛетчикам : Число 15, 2
ПФРНаДоплатуШахтерам : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботах : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботах : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахОпасный : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный1 : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный2 : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный3 : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный4 : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахОпасный : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный1 : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный2 : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный3 : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный4 : Число 15, 2
ПФРДоПредельнойВеличины : Число 15, 2
ПФРДоПредельнойВеличиныЕНВД : Число 15, 2
ПФРСПревышения : Число 15, 2
ПФРСПревышенияЕНВД : Число 15, 2
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n НДФЛ..
ИдентификаторСтрокиСотрудника : Число 7, 0
ФизическоеЛицо : Справочник.Физическое лицо
МесяцНалоговогоПериода : Дата
Подразделение : Справочник.Территория\rСправочник.Подразделение
Налог : Число 10, 0
ЗачтеноАвансовыхПлатежей : Число 10, 0
УдалитьНалогКЗачетуВозврату : Число 10, 0
ПримененныйВычетЛичный : Число 12, 2
ПримененныйВычетЛичныйКодВычета : Справочник.Вид вычетов НДФЛ
УдалитьПримененныйВычетЛичныйКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
ПримененныйВычетЛичныйКЗачетуВозврату : Число 12, 2
ПримененныйВычетЛичныйКЗачетуВозвратуКодВычета : Справочник.Вид вычетов НДФЛ
УдалитьПримененныйВычетЛичныйКЗачетуВозвратуКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
ИдентификаторСтрокиНДФЛ : Число 7, 0
ФиксСтрока : Булево
ФиксРасчет : Булево
УдалитьСотрудник : Справочник.Сотрудник
КатегорияДохода : Категории доходов НДФЛ
..Табличная часть \n Начисления..
Сотрудник : Справочник.Сотрудник
ИдентификаторСтрокиСотрудника : Число 7, 0
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Результат : Число 13, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
СуммаВычета : Число 15, 2
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ВидУчетаВремени : Справочник.Вид рабочего времени
ВремяВЧасах : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ПериодРегистрацииВремени : Дата
ОплаченоДней : Число 15, 2
ОплаченоЧасов : Число 15, 2
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ПериодДействия : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n НачисленияПерерасчет..
Сотрудник : Справочник.Сотрудник
ИдентификаторСтрокиСотрудника : Число 7, 0
Подразделение : Справочник.Подразделение
Начисление : Начисление
Результат : Число 13, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
Сторно : Булево
СторнируемыйДокумент : Документ.Приз, подарок\rДокумент.Простой сотрудников\rДокумент.Отпуск без сохранения оплаты списком\r...
ФиксРасчет : Булево
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ДатаНачала : Дата
ДатаОкончания : Дата
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
СуммаВычета : Число 15, 2
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ВидУчетаВремени : Справочник.Вид рабочего времени
ВремяВЧасах : Булево
ПериодРегистрацииВремени : Дата
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксСторно : Булево
ОплаченоДней : Число 15, 2
ОплаченоЧасов : Число 15, 2
РезультатВТомЧислеЗаСчетФБ : Число 15, 2
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ПериодДействия : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n УправленческиеНачисления..
Сотрудник : Справочник.Сотрудник
ИдентификаторСтрокиСотрудника : Число 7, 0
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Результат : Число 13, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ВидУчетаВремени : Справочник.Вид рабочего времени
ВремяВЧасах : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ПериодРегистрацииВремени : Дата
ОплаченоДней : Число 7, 2
ОплаченоЧасов : Число 7, 2
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ПериодДействия : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n ОтработанноеВремяДляСреднегоОбщий..
Сотрудник : Справочник.Сотрудник
ИдентификаторСтрокиСотрудника : Число 7, 0
ПорядокРасчета : Порядок расчета среднего заработка общий
Период : Дата
ОтработаноДней : Число 7, 2
ОтработаноДнейПятидневка : Число 7, 2
ОтработаноЧасов : Число 7, 2
ОтработаноДнейШестидневка : Число 7, 2
ОтработаноДнейКалендарных : Число 7, 2
НормаДнейПроизводственныйКалендарь : Число 7, 2
ОтработаноЧасовПятидневка : Число 5, 2
НормаЧасовПроизводственныйКалендарь : Число 5, 2
УдалитьКорректировка : Булево
Источник : Источники данных для расчета среднего заработка
..Табличная часть \n ПогашениеЗаймов..
ИдентификаторСтрокиСотрудника : Число 7, 0
ФизическоеЛицо : Справочник.Физическое лицо
ДоговорЗайма : Документ.Договор займа сотруднику
НачисленоПроцентов : Число 15, 2
ПогашениеПроцентов : Число 15, 2
ПогашениеЗайма : Число 15, 2
МатериальнаяВыгода : Число 15, 2
НалогНаМатериальнуюВыгоду : Число 13, 0
СтавкаНалогообложенияМатвыгоды : НДФЛ ставки налогообложения резидента
Подразделение : Справочник.Подразделение
ИдентификаторСтроки : Число 7, 0
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n Показатели..
ИдентификаторСтрокиСотрудника : Число 7, 0
Показатель : Справочник.Показатель
Значение : Число 15, 5
ИдентификаторСтрокиВидаРасчета : Число 7, 0
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n Пособия..
Сотрудник : Справочник.Сотрудник
ИдентификаторСтрокиСотрудника : Число 7, 0
Подразделение : Справочник.Подразделение
ВидЗанятости : Виды занятости
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Результат : Число 13, 2
РезультатВТомЧислеЗаСчетФБ : Число 15, 2
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ОплаченоДней : Число 7, 2
ОплаченоЧасов : Число 7, 2
СуммаВсегоПоУходуЗаПервымРебенком : Число 15, 2
СуммаСверхНормПоУходуЗаПервымРебенком : Число 15, 2
СуммаВсегоПоУходуЗаВторымРебенком : Число 15, 2
СуммаСверхНормПоУходуЗаВторымРебенком : Число 15, 2
ФинансированиеФедеральнымБюджетом : Основания финансирования пособия федеральным бюджетом
СтраховойСлучай : Документ.Отпуск по уходу за ребенком
КоличествоДетей : Число 2, 0
КоличествоПервыхДетей : Число 1, 0
ПериодДействия : Дата
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ПериодРегистрацииВремени : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n ПособияПерерасчет..
Сотрудник : Справочник.Сотрудник
ИдентификаторСтрокиСотрудника : Число 7, 0
Подразделение : Справочник.Подразделение
ВидЗанятости : Виды занятости
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Результат : Число 13, 2
РезультатВТомЧислеЗаСчетФБ : Число 15, 2
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
ФиксСторно : Булево
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ОплаченоДней : Число 7, 2
ОплаченоЧасов : Число 7, 2
СуммаВсегоПоУходуЗаПервымРебенком : Число 15, 2
СуммаСверхНормПоУходуЗаПервымРебенком : Число 15, 2
СуммаВсегоПоУходуЗаВторымРебенком : Число 15, 2
СуммаСверхНормПоУходуЗаВторымРебенком : Число 15, 2
Сторно : Булево
СторнируемыйДокумент : Документ.Приз, подарок\rДокумент.Простой сотрудников\rДокумент.Отпуск без сохранения оплаты списком\r...
ФинансированиеФедеральнымБюджетом : Основания финансирования пособия федеральным бюджетом
СтраховойСлучай : Документ.Отпуск по уходу за ребенком
КоличествоДетей : Число 2, 0
КоличествоПервыхДетей : Число 1, 0
ПериодДействия : Дата
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ПериодРегистрацииВремени : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n ПримененныеВычетыНаДетейИИмущественные..
ИдентификаторСтрокиСотрудника : Число 7, 0
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
РазмерВычета : Число 12, 2
ИдентификаторСтрокиНДФЛ : Число 7, 0
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n СреднийЗаработокОбщий..
Сотрудник : Справочник.Сотрудник
ИдентификаторСтрокиСотрудника : Число 7, 0
ПорядокРасчета : Порядок расчета среднего заработка общий
СоставнаяЧасть : Учет начислений в среднем заработке общий
СтатьяФинансирования : Справочник.Статья финансирования
Период : Дата
Индексируется : Булево
Сумма : Число 15, 2
УдалитьКорректировка : Булево
Год : Число 4, 0
ДатаНачалаБазовогоПериода : Дата
КоличествоМесяцев : Число 3, 0
Источник : Источники данных для расчета среднего заработка
..Табличная часть \n Удержания..
ИдентификаторСтрокиСотрудника : Число 7, 0
ФизическоеЛицо : Справочник.Физическое лицо
ДатаНачала : Дата
ДатаОкончания : Дата
Удержание : Удержание
ДокументОснование : Документ.Удержание по прочим операциям\rДокумент.Удержание добровольных взносов в НПФ\rДокумент.Удержание профсоюзных взносов\r...
Получатель : Справочник.Контрагент
ПлатежныйАгент : Справочник.Контрагент
ФиксРасчет : Булево
Результат : Число 13, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ФиксЗаполнение : Булево
ФиксСтрока : Булево
УдалитьСотрудник : Справочник.Сотрудник
Сотрудник : Справочник.Сотрудник
ФиксСторно : Булево
..Табличная часть \n РаспределениеРезультатовНачислений..
ИдентификаторСтрокиСотрудника : Число 7, 0
ИдентификаторСтроки : Число 7, 0
Территория : Справочник.Территория
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОблагаетсяЕНВД : Булево
Результат : Число 13, 2
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n РаспределениеРезультатовУдержаний..
ИдентификаторСтрокиСотрудника : Число 7, 0
ИдентификаторСтроки : Число 7, 0
ВидУдержания : Виды особых начислений и удержаний\rУдержание
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
Результат : Число 13, 2
..Табличная часть \n ДенежноеСодержание..
Сотрудник : Справочник.Сотрудник
ИдентификаторСтрокиСотрудника : Число 7, 0
Начисление : Начисление
УдалитьСоставнаяЧасть : Учет начислений в среднем заработке общий
НазначениеРасчета : Строка
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Результат : Число 15, 2
ФиксРасчет : Булево
..Табличная часть \n ДенежноеСодержаниеФактическиеНачисления..
Сотрудник : Справочник.Сотрудник
ИдентификаторСтрокиСотрудника : Число 7, 0
НазначениеРасчета : Строка
СоставнаяЧасть : Строка
Период : Дата
Сумма : Число 15, 2
Корректировка : Булево
Начисление : Начисление
..Табличная часть \n Льготы..
Сотрудник : Справочник.Сотрудник
ИдентификаторСтрокиСотрудника : Число 7, 0
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Результат : Число 13, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
СуммаВычета : Число 15, 2
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ВидУчетаВремени : Справочник.Вид рабочего времени
ВремяВЧасах : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ПериодРегистрацииВремени : Дата
ОплаченоДней : Число 7, 2
ОплаченоЧасов : Число 7, 2
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ПериодДействия : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n КадровыйРезерв..
ИдентификаторСтрокиСотрудника : Число 7, 0
ПозицияРезерва : Строка
ВидРезерва : Строка
Действие : Строка
Статус : Состояния согласования
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n РаспределениеПоТерриториямУсловиямТруда..
ИдентификаторСтрокиСотрудника : Число 7, 0
ИдентификаторСтроки : Число 7, 0
Территория : Справочник.Территория
УсловияТруда : Справочник.Условия труда
ДоляРаспределения : Число 15, 5
Результат : Число 15, 2
ИдентификаторСтрокиПоказателей : Число 7, 0
УдалитьСотрудник : Справочник.Сотрудник
СуммаВычета : Число 13, 0
..Табличная часть \n КорректировкиВыплаты..
ИдентификаторСтрокиСотрудника : Число 7, 0
ФизическоеЛицо : Справочник.Физическое лицо
КорректировкаВыплаты : Число 15, 2
ИдентификаторСтроки : Число 7, 0
ФиксСтрока : Булево
ФиксРасчет : Булево
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
Удержания : РегистрРасчета
ОценочныеОбязательства : Остатки
РасчетыНалогоплательщиковСБюджетомПоНДФЛ : Остатки
ДанныеОВремениДляРасчетаСреднегоФСС : РегистрСведений
УдалитьВыплатаОтпусковЗаСчетРезерва : Обороты
ЗначенияПоказателейУдержаний : РегистрСведений
ВзаиморасчетыССотрудниками : Остатки
НачисленияУдержанияПоСотрудникам : Обороты
ЗанятыеПозицииШтатногоРасписания : Остатки
ОтработанноеВремяПоСотрудникамКорректировка : Обороты
УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников : РегистрСведений
ЗначенияРазовыхПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
УдалитьСостоянияПодработок : РегистрСведений
РасчетыСФондамиПоСтраховымВзносам : Остатки
ПорядокВыплатыДокументов : РегистрСведений
ПособияПоСоциальномуСтрахованию : Обороты
УдержанияДоПределаПоСотрудникам : Остатки
ДанныеСостоянийСотрудников : РегистрСведений
РаспределениеПоТерриториямУсловиямТруда : РегистрСведений
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
ПлановыеАвансы : РегистрСведений
ДанныеОВремениДляРасчетаСреднегоОбщий : Обороты
КадроваяИсторияСотрудников : РегистрСведений
ОценочныеОбязательстваПоСотрудникам : Остатки
ФактическиеОтпуска : Обороты
СведенияОДоходахСтраховыеВзносы : Обороты
ИмущественныеВычетыНДФЛ : Остатки
СтандартныеВычетыФизическихЛицНДФЛ : РегистрСведений
ЗначенияОперативныхПоказателейРасчетаЗарплатыСотрудников : Обороты
ПособияПоУходуЗаРебенком : Обороты
ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаОбщий : Обороты
ПрименениеСтандартныхВычетовПоНДФЛ : РегистрСведений
ЗначенияПоказателейНачислений : РегистрСведений
СтраховыеВзносыПоФизическимЛицам : Обороты
ПредоставленныеСтандартныеИСоциальныеВычетыНДФЛ : Обороты
ТерриторииСотрудников : РегистрСведений
СтандартныеВычетыНаДетейНДФЛ : РегистрСведений
ЗарплатаКВыплатеАвансом : Остатки
УдержанияПоИсполнительнымДокументам : Обороты
ОтработанноеВремяПоСотрудникам : Обороты
Начисления : РегистрРасчета
РеестрОтпусков : РегистрСведений
ИсчисленныеСтраховыеВзносы : Обороты
БухучетПлановыхНачислений : РегистрСведений
СведенияОДоходахНДФЛ : Обороты
БухучетНачисленияУдержанияПоСотрудникам : Обороты
ЗарплатаКВыплате : Остатки
ПараметрыПериодовСтажаПФР : РегистрСведений
ПлановыеНачисления : РегистрСведений
ПлановыеУдержания : РегистрСведений
РеестрКадровыхПриказов : РегистрСведений
ВзаиморасчетыПоЗаймамСотрудникам : Остатки
ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаФСС : Обороты
АвансовыеПлатежиИностранцевПоНДФЛ : Остатки
}
@enduml
