@startuml СверкаВзаиморасчетов
'!include templates.wsd
'..\include templates.wsd
class Документ.СверкаВзаиморасчетов as "Сверка взаиморасчетов" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Контрагент : Справочник.Контрагент
Партнер : Справочник.Партнер
Договор : Справочник.Договор с контрагентом
НачалоПериода : Дата
КонецПериода : Дата
Статус : Статусы сверок взаиморасчетов
Менеджер : Справочник.Пользователь
Комментарий : Строка
ДолжностьРуководителяКонтрагента : Строка
ФИОРуководителяКонтрагента : Строка
РасшифровкаПоЗаказам : Булево
РасшифровкаПоПартнерам : Булево
РасшифровкаПоДоговорам : Булево
КонтактноеЛицо : Справочник.Контактное лицо
Руководитель : Справочник.Лицо с правом подписи
..Табличная часть \n ДанныеКонтрагента..
РасчетныйДокумент : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\rДокумент.Таможенная декларация на импорт\r...
ОписаниеДокумента : Строка
Партнер : Справочник.Партнер
Договор : Справочник.Договор с контрагентом
СуммаДолгПартнера : Число 15, 2
СуммаНашДолг : Число 15, 2
ВалютаВзаиморасчетов : Справочник.Валюта
}
@enduml
