@startuml ОтчетКомитенту
'!include templates.wsd
'..\include templates.wsd
class Документ.ОтчетКомитенту as "Отчет комитенту о продажах" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
Соглашение : Справочник.Соглашение об условиях закупок
Валюта : Справочник.Валюта
СуммаДокумента : Число 15, 2
Подразделение : Справочник.Подразделение
Менеджер : Справочник.Пользователь
НалогообложениеНДС : Типы налогообложения НДС
ЦенаВключаетНДС : Булево
СпособРасчетаВознаграждения : Способы расчета комиссионного вознаграждения
ПроцентВознаграждения : Число 5, 2
СуммаВознаграждения : Число 15, 2
СтавкаНДСВознаграждения : Ставки НДС
СуммаНДСВознаграждения : Число 15, 2
УдержатьВознаграждение : Булево
Услуга : Справочник.Номенклатура
ФормаОплаты : Формы оплаты
БанковскийСчет : Справочник.Банковский счет организации
Касса : Справочник.Касса
ДатаПлатежа : Дата
НачалоПериода : Дата
КонецПериода : Дата
Комментарий : Строка
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
Договор : Справочник.Договор с контрагентом
КонтактноеЛицо : Справочник.Контактное лицо
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
ПорядокРасчетов : Детализация расчетов
ВидыЗапасовУказаныВручную : Булево
ИдентификаторПлатежа : Строка
НаправлениеДеятельности : Справочник.Направление деятельности
ПорядокОплаты : Порядок оплаты
..Табличная часть \n Товары..
НоменклатураПоставщика : Справочник.Номенклатура поставщика
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Цена : Число 15, 2
Сумма : Число 15, 2
СуммаНДС : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаСНДС : Число 15, 2
ЦенаПродажи : Число 15, 2
СуммаПродажи : Число 15, 2
СуммаВознаграждения : Число 15, 2
ДатаСчетаФактуры : Дата
Покупатель : Справочник.Организация\rСправочник.Контрагент
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
СчетФактураВыставленный : Документ.Счет-фактура выданный\rДокумент.Счет-фактура выданный комиссионеру (агенту)
..Табличная часть \n ЭтапыГрафикаОплаты..
ДатаПлатежа : Дата
ПроцентПлатежа : Число 5, 2
СуммаПлатежа : Число 15, 2
..Табличная часть \n ВидыЗапасов..
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
СуммаСНДС : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 3
СуммаВознаграждения : Число 15, 2
ДатаСчетаФактуры : Дата
Покупатель : Справочник.Организация\rСправочник.Контрагент
ИдентификаторСтроки : Строка
СчетФактураВыставленный : Документ.Счет-фактура выданный\rДокумент.Счет-фактура выданный комиссионеру (агенту)
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n РасшифровкаПлатежаСКлиентом..
Заказ : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
Сумма : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
..Табличная часть \n РасшифровкаПлатежаСПоставщиком..
Заказ : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Приобретение товаров и услуг\r...
Сумма : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
..Движения..
РасчетыСКлиентами : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
ДвиженияНоменклатураДоходыРасходы : Обороты
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
НДСПредъявленный : Остатки
ТоварыКОформлениюОтчетовКомитенту : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
РасчетыСПоставщиками : Остатки
Международный : РегистрБухгалтерии
Закупки : Обороты
НДСЗаписиКнигиПродаж : Обороты
РасчетыСКлиентамиПоДокументам : Остатки
РасчетыСПоставщикамиПоДокументам : Остатки
КнигаУчетаДоходовИРасходов : Обороты
ВыручкаИСебестоимостьПродаж : Обороты
УслугиКОформлениюОтчетовПринципалу : Остатки
}
@enduml
