@startuml РаспределениеНДС
'!include templates.wsd
'..\include templates.wsd
class Документ.РаспределениеНДС as "Распределение НДС" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
Комментарий : Строка
ВыручкаНДС : Число 15, 2
ВыручкаНеНДС : Число 15, 2
ВыручкаЕНВД : Число 15, 2
ВыручкаНДС0 : Число 15, 2
СписатьНДСПоРасходамАктивамНаСтатьиОтражения : Число 1, 0
СтатьяРасходовНеНДС : Статья расходов
АналитикаРасходовНеНДС : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
СтатьяРасходовЕНВД : Статья расходов
АналитикаРасходовЕНВД : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
БазаРаспределенияУстанавливаетсяВручную : Булево
ПрименитьПравило5Процентов : Булево
ВыручкаНДС0СырьевыеТоварыУслуги : Число 15, 2
ВыручкаНДС0НесырьевыеТовары : Число 15, 2
НачалоПериода : Дата
..Табличная часть \n ДокументыЭкспорт..
Документ : Документ.Реализация товаров и услуг\rСтрока\rДокумент.Акт выполненных работ
СуммаВыручки : Число 15, 2
КорректировкаВыручки : Число 15, 2
..Движения..
ПараметрыАмортизацииОСБухгалтерскийУчет : РегистрСведений
ПервоначальныеСведенияНМАНалоговыйУчет : РегистрСведений
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
НДСПредъявленный : Остатки
ПервоначальныеСведенияОСБухгалтерскийУчет : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
СтоимостьНМА : Остатки
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
НДСЗаписиКнигиПродаж : Обороты
АмортизацияОС : Остатки
ПервоначальныеСведенияНМАБухгалтерскийУчет : РегистрСведений
НДСЗаписиКнигиПокупок : Обороты
ПервоначальныеСведенияОСНалоговыйУчет : РегистрСведений
СтоимостьОС : Остатки
}
@enduml
