@startuml СчетФактураКомитента
'!include templates.wsd
'..\include templates.wsd
class Документ.СчетФактураКомитента as "Счет-фактура полученный от комитента (принципала)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Исправление : Булево
НомерИсправления : Строка
ДатаИсправления : Дата
ПолученВЭлектронномВиде : Булево
Валюта : Справочник.Валюта
КодВидаОперации : Строка
Комитент : Справочник.Контрагент
ДатаСоставления : Дата
СуммаСНДС : Число 15, 2
СуммаНДС : Число 15, 2
Комментарий : Строка
Сводный : Булево
ИННКомитента : Строка
КППКомитента : Строка
Ответственный : Справочник.Пользователь
..Табличная часть \n Покупатели..
Покупатель : Справочник.Организация\rСправочник.Контрагент
СчетФактураВыданный : Документ.Счет-фактура выданный\rДокумент.Счет-фактура выданный комиссионеру (агенту)
Субкомиссионер : Справочник.Организация\rСправочник.Контрагент
СуммаСНДС : Число 15, 2
СуммаНДС : Число 15, 2
ИННСубкомиссионера : Строка
КППСубкомиссионера : Строка
..Движения..
ФактическиеДанныеБюджетирования : Обороты
ЖурналУчетаСчетовФактур : РегистрСведений
}
@enduml
