@startuml ПланЗакупок
'!include templates.wsd
'..\include templates.wsd
class Документ.ПланЗакупок as "План закупок" <<Документы>>
{
..Реквизиты..
Подразделение : Справочник.Подразделение
Статус : Статусы планов
Периодичность : Периодичность
НачалоПериода : Дата
ОкончаниеПериода : Дата
Ответственный : Справочник.Пользователь
ОбновитьДополнить : Число 1, 0
ИзменитьРезультатНа : Число 5, 2
ТочностьОкругления : Число 1, 0
ПользовательскиеНастройки : Хранилище значения
Комментарий : Строка
Сценарий : Справочник.Сценарии товарного планирования
ВидПлана : Справочник.Вид плана
СуммаДокумента : Число 15, 2
ПланироватьПоСумме : Булево
Валюта : Справочник.Валюта
ЗаполненоАвтоматически : Булево
Партнер : Справочник.Партнер
Соглашение : Справочник.Соглашение об условиях закупок
Склад : Справочник.Склад (складская территория)
КроссТаблица : Булево
Календарь : Справочник.Производственный календарь
ЗаполнятьПланОплат : Булево
СтруктураНастроек : Хранилище значения
ЗаполнятьПоФормуле : Булево
ОтражаетсяВБюджетировании : Булево
СтатьяБюджетов : Справочник.Статьи бюджетов
СценарийБюджетирования : Справочник.Сценарии бюджетирования
ОтражаетсяВБюджетированииОплаты : Булево
СтатьяБюджетовОплат : Справочник.Статьи бюджетов
ОтражаетсяВБюджетированииОплатыКредит : Булево
СтатьяБюджетовОплатКредит : Справочник.Статьи бюджетов
Замещающий : Булево
Назначение : Справочник.Назначение
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
Количество : Число 15, 3
КоличествоУпаковок : Число 15, 3
Склад : Справочник.Склад (складская территория)
ДатаПоступления : Дата
Партнер : Справочник.Партнер
Соглашение : Справочник.Соглашение об условиях закупок
ВидЦеныПоставщика : Справочник.Вид цены поставщика
Цена : Число 15, 2
Сумма : Число 15, 2
ДополнительныеПараметры : Хранилище значения
Отменено : Булево
Комментарий : Строка
Назначение : Справочник.Назначение
Замещен : Булево
..Табличная часть \n ПравилоЗаполнения..
Использование : Булево
Исключать : Булево
ВариантПреобразования : Варианты преобразования
Источник : Справочник.Источник данных планирования
Период : Хранилище значения
Дата : Хранилище значения
ТипЭлемента : Число 1, 0
НомерСтрокиРодитель : Число 5, 0
ПользовательскиеНастройки : Хранилище значения
ИзменитьРезультатНа : Число 5, 2
Присоединять : Булево
..Табличная часть \n ПланОплаты..
ВариантОплаты : Варианты оплаты поставщику
ДатаПлатежа : Дата
ПроцентПлатежа : Число 5, 2
СуммаПлатежа : Число 15, 2
СуммаЗадолженности : Число 15, 2
СуммаОтгрузок : Число 15, 2
СуммаПлатежей : Число 15, 2
Комментарий : Строка
ДатаПоступления : Дата
Замещен : Булево
..Табличная часть \n ЭтапыГрафикаОплаты..
ВариантОплаты : Варианты оплаты поставщику
Сдвиг : Число 10, 0
ПроцентПлатежа : Число 5, 2
ПроцентЗалогаЗаТару : Число 5, 2
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ОборотыБюджетов : Обороты
ПланыЗакупок : Обороты
ФактическиеДанныеБюджетирования : Обороты
ПланыОплатПоставщикам : Обороты
}
@enduml
