@startuml ПриемкаТоваровНаХранение
'!include templates.wsd
'..\include templates.wsd
class Документ.ПриемкаТоваровНаХранение as "Приемка товаров на хранение" <<Документы>>
{
..Реквизиты..
Валюта : Справочник.Валюта
Партнер : Справочник.Партнер
Соглашение : Справочник.Соглашение об условиях закупок
ХозяйственнаяОперация : Хозяйственные операции
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Склад : Справочник.Склад (складская территория)
Контрагент : Справочник.Контрагент
СуммаДокумента : Число 15, 2
Менеджер : Справочник.Пользователь
ЗаказПоставщику : Документ.Заказ поставщику
ЦенаВключаетНДС : Булево
Комментарий : Строка
Согласован : Булево
НомерВходящегоДокумента : Строка
ДатаВходящегоДокумента : Дата
Сделка : Справочник.Сделка с клиентом
Принял : Справочник.Физическое лицо
ПринялДолжность : Строка
ПоступлениеПоЗаказам : Булево
РегистрироватьЦеныПоставщика : Булево
Договор : Справочник.Договор с контрагентом
Автор : Справочник.Пользователь
Руководитель : Справочник.Лицо с правом подписи
ДопоступлениеПоДокументу : Документ.Отгрузка товаров с хранения\rДокумент.Приемка товаров на хранение
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
СпособДоставки : Способы доставки
ПеревозчикПартнер : Справочник.Партнер
ЗонаДоставки : Справочник.Зоны доставки
ВремяДоставкиС : Дата
ВремяДоставкиПо : Дата
АдресДоставки : Строка
АдресДоставкиЗначенияПолей : Строка
ДополнительнаяИнформацияПоДоставке : Строка
АдресДоставкиПеревозчика : Строка
АдресДоставкиПеревозчикаЗначенияПолей : Строка
ОсобыеУсловияПеревозки : Булево
ОсобыеУсловияПеревозкиОписание : Строка
НаправлениеДеятельности : Справочник.Направление деятельности
Сдал : Строка
СдалДолжность : Строка
СостояниеЗаполненияМногооборотнойТары : Состояния заполнения многооборотной тары
ВидЦеныПоставщика : Справочник.Вид цены поставщика
ВариантПриемкиТоваров : Варианты приемки товаров
..Табличная часть \n Товары..
НоменклатураПоставщика : Справочник.Номенклатура поставщика
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Цена : Число 15, 2
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
КодСтроки : Число 10, 0
НомерГТД : Справочник.Номер ГТД
Склад : Справочник.Склад (складская территория)
ЗаказПоставщику : Документ.Заказ поставщику
СтатусУказанияСерий : Число 2, 0
Сделка : Справочник.Сделка с клиентом
ВидЗапасов : Справочник.Вид запасов
ИдентификаторСтроки : Строка
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
АналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n Серии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Склад : Справочник.Склад (складская территория)
..Движения..
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ЦеныНоменклатурыПоставщиков : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
Международный : РегистрБухгалтерии
ДвижениеТоваров : Обороты
ТоварыПринятые : Остатки
СвободныеОстатки : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
ТоварыОрганизаций : Остатки
ПринятаяВозвратнаяТара : Остатки
ГрафикПоступленияТоваров : Остатки
ЗаказыПоставщикам : Остатки
ТоварыКПоступлению : Остатки
}
@enduml
