@startuml ВводОстатков
'!include templates.wsd
'..\include templates.wsd
class Документ.ВводОстатков as "Ввод начальных остатков" <<Документы>>
{
..Реквизиты..
ТипОперации : Типы операций ввода остатков
Организация : Справочник.Организация
Склад : Справочник.Склад (складская территория)
Ответственный : Справочник.Пользователь
Комментарий : Строка
Помещение : Справочник.Помещение
ДополнятьНомера : Булево
Префикс : Строка
Партнер : Справочник.Партнер
Валюта : Справочник.Валюта
НалогообложениеНДС : Типы налогообложения НДС
СоглашениеСКомиссионером : Справочник.Соглашение об условиях продаж
СоглашениеСКомитентом : Справочник.Соглашение об условиях закупок
ОрганизацияПолучатель : Справочник.Организация
Контрагент : Справочник.Контрагент
Договор : Справочник.Договор с контрагентом
Подразделение : Справочник.Подразделение
ЦенаВключаетНДС : Булево
ЗонаПриемки : Справочник.Складская ячейка
ВидПодарочногоСертификата : Справочник.Вид подарочных сертификатов
Менеджер : Справочник.Пользователь
СоглашениеСКлиентом : Справочник.Соглашение об условиях продаж
ЗаказПереработчику : Документ.Заказ переработчику
НаправлениеДеятельности : Справочник.Направление деятельности
УдалитьРазделУчета : (не используется) Разделы ввода начальных остатков
ОтражатьВОперативномУчете : Булево
ОтражатьВБУиНУ : Булево
ОтражатьВУУ : Булево
ВидЦенностиНДС : Виды ценностей
ВидДеятельностиНДС : Типы налогообложения НДС
Партия : Документ.Первичный документ
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Цена : Число 15, 2
Сумма : Число 15, 2
СуммаБезНДС : Число 15, 2
СуммаНДС : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаРегл : Число 15, 2
НДСРегл : Число 15, 2
НомерГТД : Справочник.Номер ГТД
СтатусУказанияСерий : Число 2, 0
ВидЗапасов : Справочник.Вид запасов
УдалитьАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
СуммаПР : Число 15, 2
СуммаВР : Число 15, 2
Серия : Справочник.Серия номенклатуры
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ПредусмотренЗалогЗаТару : Булево
КодСтроки : Число 10, 0
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
СуммаСНДС : Число 15, 2
ИдентификаторСтроки : Строка
..Табличная часть \n Кассы..
Касса : Справочник.Касса
Сумма : Число 15, 2
СуммаРегл : Число 15, 2
СуммаУпр : Число 15, 2
..Табличная часть \n КассыККМ..
КассаККМ : Справочник.Кассы ККМ
Сумма : Число 15, 2
СуммаРегл : Число 15, 2
СуммаУпр : Число 15, 2
..Табличная часть \n БанковскиеСчета..
БанковскийСчет : Справочник.Банковский счет организации
Сумма : Число 15, 2
СуммаРегл : Число 15, 2
СуммаУпр : Число 15, 2
..Табличная часть \n РасчетыМеждуОрганизациями..
ВалютаВзаиморасчетов : Справочник.Валюта
Сумма : Число 15, 2
ОбъектРасчетов : Справочник.Договор между организациями\rДокумент.Отчет по комиссии между организациями\rТипы договоров между организациями\r...
НомерРасчетногоДокумента : Строка
ДатаРасчетногоДокумента : Дата
ДатаПлатежа : Дата
СуммаРегл : Число 15, 2
СуммаУпр : Число 15, 2
..Табличная часть \n РасчетыСПартнерами..
Партнер : Справочник.Партнер
Контрагент : Справочник.Организация\rСправочник.Контрагент
Договор : Справочник.Договор с контрагентом
ВалютаВзаиморасчетов : Справочник.Валюта
Сумма : Число 15, 2
НомерРасчетногоДокумента : Строка
ДатаРасчетногоДокумента : Дата
ДатаПлатежа : Дата
СуммаРегл : Число 15, 2
СуммаУпр : Число 15, 2
ОбъектРасчетов : Документ.Приобретение товаров и услуг\rДокумент.Таможенная декларация на импорт\rДокумент.Отчет комиссионера (агента) о продажах\r...
ДокументРасчетов : Документ.Первичный документ
..Табличная часть \n РасчетыСПодотчетниками..
ПодотчетноеЛицо : Справочник.Физическое лицо
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
Валюта : Справочник.Валюта
Сумма : Число 15, 2
СуммаРегл : Число 15, 2
СуммаУпр : Число 15, 2
..Табличная часть \n РасчетыПоЭквайрингу..
ТипДенежныхСредств : Типы денежных средств по эквайрингу
Валюта : Справочник.Валюта
ЭквайринговыйТерминал : Справочник.Эквайринговый терминал
НомерПлатежнойКарты : Строка
ДатаПлатежа : Дата
Сумма : Число 15, 2
СуммаРегл : Число 15, 2
СуммаУпр : Число 15, 2
..Табличная часть \n Серии..
Количество : Число 15, 3
КоличествоУпаковок : Число 15, 3
Номенклатура : Справочник.Номенклатура
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
Упаковка : Справочник.Упаковка
Характеристика : Справочник.Характеристика номенклатуры
..Табличная часть \n ПрочиеАктивыПассивы..
НаправлениеДеятельности : Справочник.Направление деятельности
Статья : Статья актива/пассива
Аналитика : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
Сумма : Число 15, 2
..Табличная часть \n ПодарочныеСертификаты..
ПодарочныйСертификат : Справочник.Подарочный сертификат
СуммаВВалютеСертификата : Число 15, 2
Штрихкод : Строка
МагнитныйКод : Строка
СерийныйНомер : Строка
ДатаАктивации : Дата
СуммаРегл : Число 15, 2
СуммаУпр : Число 15, 2
..Табличная часть \n РасчетыПоДоговорамКредитовИДепозитов..
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
Договор : Справочник.Договор кредита (депозита)
ТипСуммы : Типы сумм графика кредитов и депозитов
Сумма : Число 15, 2
СуммаРегл : Число 15, 2
СуммаУпр : Число 15, 2
..Табличная часть \n ТМЦВЭксплуатации..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Количество : Число 15, 3
Сумма : Число 15, 2
СуммаПР : Число 15, 2
СуммаВР : Число 15, 2
ПервоначальнаяСумма : Число 15, 2
КатегорияЭксплуатации : Справочник.Категории эксплуатации
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ФизическоеЛицо : Справочник.Физическое лицо
ДатаПередачиВЭксплуатацию : Дата
ПартияТМЦВЭксплуатации : Справочник.Партии ТМЦ в эксплуатации
ИнвентарныйНомер : Строка
..Табличная часть \n ПрочиеРасходы..
НаправлениеДеятельности : Справочник.Направление деятельности
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаБезНДС : Число 15, 2
СуммаНДС : Число 15, 2
СуммаРегл : Число 15, 2
НДСРегл : Число 15, 2
СуммаПР : Число 15, 2
СуммаВР : Число 15, 2
ИдентификаторСтроки : Строка
УдалитьАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
СуммаУпр : Число 15, 2
..Табличная часть \n ФинансовыйРезультатРасходы..
НаправлениеДеятельности : Справочник.Направление деятельности
СтатьяРасходов : Статья расходов
СуммаРасходов : Число 15, 2
ДатаОтражения : Дата
..Табличная часть \n ФинансовыйРезультатДоходы..
НаправлениеДеятельности : Справочник.Направление деятельности
СтатьяДоходов : Статьи доходов
СуммаДоходов : Число 15, 2
ДатаОтражения : Дата
..Табличная часть \n ОптовыеПродажи..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Количество : Число 15, 3
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Цена : Число 15, 2
СтавкаНДС : Ставки НДС
Сумма : Число 15, 2
СуммаБезНДС : Число 15, 2
СуммаНДС : Число 15, 2
СуммаРегл : Число 15, 2
НДСРегл : Число 15, 2
ДатаОтражения : Дата
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
..Табличная часть \n РозничныеПродажи..
ВидКартыЛояльности : Справочник.Вид карт лояльности
ШтрихКод : Строка
МагнитныйКод : Строка
КартаЛояльности : Справочник.Карты лояльности
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Количество : Число 15, 3
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Цена : Число 15, 2
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаБезНДС : Число 15, 2
СуммаРегл : Число 15, 2
НДСРегл : Число 15, 2
ДатаОтражения : Дата
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
АналитикаУчетаПоПартнерам : Справочник.Ключ аналитики учета по партнерам
ВидЗапасов : Справочник.Вид запасов
..Табличная часть \n НДСПредъявленный..
Партнер : Справочник.Партнер
Контрагент : Справочник.Организация\rСправочник.Контрагент
ДокументПоступления : Документ.Первичный документ
ДокументРеализации : Документ.Первичный документ
СтавкаНДС : Ставки НДС
СуммаБезНДС : Число 15, 2
НДС : Число 15, 2
НДСУпр : Число 15, 2
..Табличная часть \n РасходыПриУСН..
Партнер : Справочник.Партнер
Контрагент : Справочник.Организация\rСправочник.Контрагент
ДокументВозникновенияРасходов : Документ.Первичный документ
ВидРасходов : Виды расходов УСН
СтатьяРасходов : Статья расходов
СуммаРасходов : Число 15, 2
НДС : Число 15, 2
СуммаОплаты : Число 15, 2
СуммаОтгрузки : Число 15, 2
..Табличная часть \n ДетализацияПартий..
ИдентификаторСтроки : Строка
Партнер : Справочник.Партнер
Контрагент : Справочник.Организация\rСправочник.Контрагент
ДокументПоступления : Документ.Первичный документ
ВидЦенности : Виды ценностей
СтавкаНДС : Ставки НДС
СуммаРегл : Число 15, 2
НДСРегл : Число 15, 2
НДСУпр : Число 15, 2
..Движения..
ДенежныеСредстваУПодотчетныхЛиц : Остатки
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
РасчетыСКлиентами : Остатки
ПартииТоваровОрганизаций : Остатки
ИсторияПодарочныхСертификатов : РегистрСведений
ПрочиеРасходы : Остатки
ТоварыКОформлениюИзлишковНедостач : Остатки
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииТоваровПереданныеНаКомиссию : Остатки
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДенежныеСредстваБезналичные : Остатки
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ДенежныеСредстваНаличные : Остатки
ПереданнаяВозвратнаяТара : Остатки
ПодарочныеСертификаты : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНОСиНМА : Остатки
РасходыПриУСНМатериалы : Остатки
РасходыПриУСН : Остатки
ДенежныеСредстваВПути : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ДенежныеСредстваВКассахККМ : Остатки
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
РасчетыСПоставщиками : Остатки
ТоварыПереданныеНаКомиссию : Остатки
ФинансовыеРезультаты : Обороты
Международный : РегистрБухгалтерии
Закупки : Обороты
РасходыПриУСНТовары : Остатки
НДСЗаписиКнигиПродаж : Обороты
РасчетыСКлиентамиПоДокументам : Остатки
РасчетыСПоставщикамиПоДокументам : Остатки
ТоварыПереданныеПереработчику : Остатки
МатериалыИРаботыВПроизводстве : Остатки
ВыручкаИСебестоимостьПродаж : Обороты
РасчетыПоДоговорамКредитовИДепозитов : Остатки
СвободныеОстатки : Остатки
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
ТМЦВЭксплуатации : Обороты
ПринятаяВозвратнаяТара : Остатки
НДССостояниеРеализации0 : РегистрСведений
ТоварыВЯчейках : Остатки
ПартииПроизводственныхЗатрат : Остатки
РасчетыПоЭквайрингу : Остатки
}
@enduml
