@startuml ОтчетДавальцу
'!include templates.wsd
'..\include templates.wsd
class Документ.ОтчетДавальцу as "Отчет давальцу" <<Документы>>
{
..Реквизиты..
БанковскийСчетКонтрагента : Справочник.Банковский счет
БанковскийСчетОрганизации : Справочник.Банковский счет организации
Валюта : Справочник.Валюта
ВалютаВзаиморасчетов : Справочник.Валюта
ДатаПлатежа : Дата
ДополнительнаяИнформация : Строка
ДополнительнаяИнформацияШапки : Строка
ЗаказДавальца : Документ.Заказ давальца
Касса : Справочник.Касса
Комментарий : Строка
Контрагент : Справочник.Контрагент
Менеджер : Справочник.Пользователь
НалогообложениеНДС : Типы налогообложения НДС
Организация : Справочник.Организация
Партнер : Справочник.Партнер
Подразделение : Справочник.Подразделение
Сделка : Справочник.Сделка с клиентом
СкидкиРассчитаны : Булево
Согласован : Булево
СуммаВзаиморасчетов : Число 15, 2
СуммаДокумента : Число 15, 2
ФормаОплаты : Формы оплаты
ЦенаВключаетНДС : Булево
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
КартаЛояльности : Справочник.Карты лояльности
Договор : Справочник.Договор с контрагентом
Автор : Справочник.Пользователь
КонтактноеЛицо : Справочник.Контактное лицо
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
ПорядокРасчетов : Детализация расчетов
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
СтавкаНДС : Ставки НДС
Содержание : Строка
НаправлениеДеятельности : Справочник.Направление деятельности
Курс : Число 10, 4
Кратность : Число 10, 0
ПорядокОплаты : Порядок оплаты
..Табличная часть \n Продукция..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Количество : Число 15, 3
ВидЦены : Справочник.Вид цены
Цена : Число 15, 2
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
КодСтроки : Число 10, 0
СуммаВзаиморасчетов : Число 15, 2
ЗаказДавальца : Документ.Заказ давальца
ИдентификаторСтроки : Строка
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n РасшифровкаПлатежа..
Заказ : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
Сумма : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
..Движения..
ПрочиеДоходы : Остатки
ТрудозатратыНезавершенногоПроизводства : Остатки
РасчетыСКлиентами : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
УслугиДавальцуКОформлению : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
НДСЗаписиКнигиПродаж : Обороты
РасчетыСКлиентамиПоДокументам : Остатки
ВыручкаИСебестоимостьПродаж : Обороты
ДвиженияНоменклатураНоменклатура : Обороты
ПрочиеРасходыНезавершенногоПроизводства : Остатки
ПартииПроизводственныхЗатрат : Остатки
ВыпускПродукции : Обороты
ПартииНезавершенногоПроизводства : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
