@startuml ПакетОбменСБанками
'!include templates.wsd
'..\include templates.wsd
class Документ.ПакетОбменСБанками as "Пакет прямого обмена с банками" <<Документы>>
{
..Реквизиты..
ВнешнийИдентификатор : Строка
Идентификатор : Строка
Направление : Направления ЭД
НастройкаОбмена : Справочник.Настройка обмена с банком
Организация : Справочник.Организация
Статус : Статусы пакетов электронных документов
Комментарий : Строка
..Табличная часть \n Сообщения..
Сообщение : Документ.Сообщение обмена с банками
}
@enduml
