@startuml УдалитьКассоваяСмена
'!include templates.wsd
'..\include templates.wsd
class Документ.УдалитьКассоваяСмена as "Кассовая смена (удалить)" <<Документы>>
{
..Реквизиты..
Валюта : Справочник.Валюта
ВидЦены : Справочник.Вид цены
КассаККМ : Справочник.Кассы ККМ
Кассир : Справочник.Пользователь
НалогообложениеНДС : Типы налогообложения НДС
НачалоКассовойСмены : Дата
ОкончаниеКассовойСмены : Дата
Организация : Справочник.Организация
Склад : Справочник.Склад (складская территория)
СтатусКассовойСмены : Удалить статусы кассовой смены
ЦенаВключаетНДС : Булево
Комментарий : Строка
НоваяКассоваяСмена : Документ.Кассовая смена
}
@enduml
