@startuml РасчетСебестоимостиТоваров
'!include templates.wsd
'..\include templates.wsd
class Документ.РасчетСебестоимостиТоваров as "Расчет себестоимости товаров" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
МетодОценки : Методы оценки стоимости товаров
ПредварительныйРасчет : Булево
ПредставлениеОрганизаций : Строка
Комментарий : Строка
..Табличная часть \n Организации..
Организация : Справочник.Организация
..Движения..
ПрочиеДоходы : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииТоваровПереданныеНаКомиссию : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
СтоимостьТоваров : РегистрСведений
ФинансовыеРезультаты : Обороты
Международный : РегистрБухгалтерии
Закупки : Обороты
ВыручкаИСебестоимостьПродаж : Обороты
ДвиженияНоменклатураНоменклатура : Обороты
НДСЗаписиКнигиПокупок : Обороты
ПрочиеРасходыНезавершенногоПроизводства : Остатки
ПартииПроизводственныхЗатрат : Остатки
ПартииНезавершенногоПроизводства : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
