@startuml СчетНаОплатуКлиенту
'!include templates.wsd
'..\include templates.wsd
class Документ.СчетНаОплатуКлиенту as "Счет на оплату клиенту" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
СуммаДокумента : Число 15, 2
Валюта : Справочник.Валюта
ДокументОснование : Документ.Отчет комиссионера (агента) о продажах\rДокумент.Отчет давальцу\rСправочник.Договор с контрагентом\r...
ФормаОплаты : Формы оплаты
БанковскийСчет : Справочник.Банковский счет организации
Касса : Справочник.Касса
ДополнительнаяИнформация : Строка
ЧастичнаяОплата : Булево
Аннулирован : Булево
Менеджер : Справочник.Пользователь
НазначениеПлатежа : Строка
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
Комментарий : Строка
Договор : Справочник.Договор с контрагентом
КонтактноеЛицо : Справочник.Контактное лицо
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
ИдентификаторПлатежа : Строка
..Табличная часть \n ЭтапыГрафикаОплаты..
ДатаПлатежа : Дата
ПроцентПлатежа : Число 5, 2
СуммаПлатежа : Число 15, 2
ЭтоЗалогЗаТару : Булево
}
@enduml
