@startuml ПоступлениеОтПереработчика
'!include templates.wsd
'..\include templates.wsd
class Документ.ПоступлениеОтПереработчика as "Поступление от переработчика" <<Документы>>
{
..Реквизиты..
Автор : Справочник.Пользователь
БанковскийСчетГрузоотправителя : Справочник.Банковский счет
БанковскийСчетКонтрагента : Справочник.Банковский счет
БанковскийСчетОрганизации : Справочник.Банковский счет организации
Валюта : Справочник.Валюта
ВидЦены : Справочник.Вид цены
Грузоотправитель : Справочник.Контрагент
ДатаВходящегоДокумента : Дата
Договор : Справочник.Договор с контрагентом
ЗаказПереработчику : Документ.Заказ переработчику
ЗакупкаПодДеятельность : Типы налогообложения НДС
Комментарий : Строка
Контрагент : Справочник.Контрагент
МаксимальныйКодСтроки : Число 10, 0
Менеджер : Справочник.Пользователь
НомерВходящегоДокумента : Строка
Организация : Справочник.Организация
Партнер : Справочник.Партнер
Подразделение : Справочник.Подразделение
ПоступлениеПоЗаказам : Булево
Принял : Справочник.Физическое лицо
ПринялДолжность : Строка
Распоряжение : Документ.Этап производства\rДокумент.Заказ на производство\rДокумент.Заказ переработчику
Руководитель : Справочник.Лицо с правом подписи
Сделка : Справочник.Сделка с клиентом
Склад : Справочник.Склад (складская территория)
Согласован : Булево
СуммаДокумента : Число 15, 2
ХозяйственнаяОперация : Хозяйственные операции
НаправлениеДеятельности : Справочник.Направление деятельности
УчетСырьяПоНазначениям : Булево
ВариантПриемкиТоваров : Варианты приемки товаров
..Табличная часть \n Товары..
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
КодСтроки : Число 10, 0
Склад : Справочник.Склад (складская территория)
ЗаказПереработчику : Документ.Заказ переработчику
НомерПаспорта : Строка
СтатусУказанияСерий : Число 2, 0
Сделка : Справочник.Сделка с клиентом
ВидЗапасов : Справочник.Вид запасов
ИдентификаторСтроки : Строка
УдалитьАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
УдалитьСертификат : Строка
Назначение : Справочник.Назначение
ДокументПередачи : Документ.Передача сырья переработчику
Цена : Число 15, 2
Сумма : Число 15, 2
Серия : Справочник.Серия номенклатуры
Распоряжение : Документ.Этап производства\rДокумент.Заказ на производство\rДокумент.Заказ переработчику
..Табличная часть \n ТоварыСерии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Склад : Справочник.Склад (складская территория)
..Табличная часть \n ВозвратныеОтходы..
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
КодСтроки : Число 10, 0
Склад : Справочник.Склад (складская территория)
ЗаказПереработчику : Документ.Заказ переработчику
НомерПаспорта : Строка
СтатусУказанияСерий : Число 2, 0
Сделка : Справочник.Сделка с клиентом
ВидЗапасов : Справочник.Вид запасов
ИдентификаторСтроки : Строка
УдалитьАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
УдалитьСертификат : Строка
Назначение : Справочник.Назначение
ДокументПередачи : Документ.Передача сырья переработчику
Цена : Число 15, 2
Сумма : Число 15, 2
Серия : Справочник.Серия номенклатуры
Распоряжение : Документ.Этап производства\rДокумент.Заказ на производство\rДокумент.Заказ переработчику
..Табличная часть \n ВозвратныеОтходыСерии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Склад : Справочник.Склад (складская территория)
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ТрудозатратыНезавершенногоПроизводства : Остатки
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНМатериалы : Остатки
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
Международный : РегистрБухгалтерии
ДвижениеТоваров : Обороты
РасходыПриУСНТовары : Остатки
НДСЗаписиКнигиПродаж : Обороты
КнигаУчетаДоходовИРасходов : Обороты
МатериалыИРаботыВПроизводстве : Остатки
СвободныеОстатки : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
ТоварыОрганизаций : Остатки
ПрочиеРасходыНезавершенногоПроизводства : Остатки
ЗаказыПоставщикам : Остатки
ПартииПроизводственныхЗатрат : Остатки
ВыпускПродукции : Обороты
ТоварыПолученныеОтПереработчика : Остатки
ПартииНезавершенногоПроизводства : Остатки
ТоварыКПоступлению : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
