@startuml СписаниеНДСНаРасходы
'!include templates.wsd
'..\include templates.wsd
class Документ.СписаниеНДСНаРасходы as "Списание НДС на расходы" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Поставщик : Справочник.Организация\rСправочник.Контрагент
СчетФактура : Документ.Запись книги покупок\rДокумент.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\r...
СтатьяРасходов : Статья расходов
Подразделение : Справочник.Подразделение
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Комментарий : Строка
СуммаБезНДС : Число 15, 2
СуммаНДС : Число 15, 2
Ответственный : Справочник.Пользователь
СуммаНДСУпр : Число 15, 2
..Табличная часть \n Ценности..
ВидЦенности : Виды ценностей
ВидДеятельностиНДС : Типы налогообложения НДС
РеализацияЭкспорт : Документ.Реализация товаров и услуг\rДокумент.Акт выполненных работ
СтавкаНДС : Ставки НДС
СуммаБезНДС : Число 15, 2
НДС : Число 15, 2
НДСУпр : Число 15, 2
..Движения..
ПрочиеРасходы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
НДСПредъявленный : Остатки
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
}
@enduml
