@startuml АмортизацияОС
'!include templates.wsd
'..\include templates.wsd
class Документ.АмортизацияОС as "Амортизация и износ основных средств (2.2)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n НачисленнаяАмортизация..
ОбъектУчета : Справочник.Объект эксплуатации
Подразделение : Справочник.Подразделение
НаправлениеДеятельности : Справочник.Направление деятельности
СуммаБУ : Число 15, 2
СуммаНУ : Число 15, 2
СуммаПР : Число 15, 2
СуммаВР : Число 15, 2
СтатьяРасходов : Статья расходов
ЭтоАмортизационнаяПремия : Булево
ДокументАмортизационнойПремии : Документ.Принятие к учету ОС\rДокумент.Модернизация ОС
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ПередаватьРасходыВДругуюОрганизацию : Булево
ОрганизацияПолучательРасходов : Справочник.Организация
СчетПередачиРасходов : Счет бухгалтерского учета
ЭтоЦелевыеСредства : Булево
..Движения..
ПрочиеДоходы : Остатки
ПрочиеРасходы : Остатки
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ПартииРасходовНаСебестоимостьТоваров : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
ВыручкаИСебестоимостьПродаж : Обороты
}
@enduml
