@startuml ПеремещениеМатериаловВПроизводстве
'!include templates.wsd
'..\include templates.wsd
class Документ.ПеремещениеМатериаловВПроизводстве as "Перемещение материалов в производстве" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ПодразделениеОтправитель : Справочник.Подразделение
ПодразделениеПолучатель : Справочник.Подразделение
Статус : Статусы перемещения материалов в производстве
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n МатериалыИРаботы..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
СтатусУказанияСерий : Число 2, 0
СтатусУказанияСерийОтправитель : Число 2, 0
СтатусУказанияСерийПолучатель : Число 2, 0
Назначение : Справочник.Назначение
НазначениеОтправителя : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
..Табличная часть \n Серии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
НазначениеОтправителя : Справочник.Назначение
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ДвиженияСерийТоваров : Обороты
ПрочиеРасходы : Остатки
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
МатериалыИРаботыВПроизводстве : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
ПартииПроизводственныхЗатрат : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
