@startuml ЗаказНаПроизводство
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаказНаПроизводство as "Заказ на производство (2.1)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Статус : Статусы заказов на производство
Ответственный : Справочник.Пользователь
СтатусГрафикаПроизводства : Статусы графика производства в заказе на производство
КоличествоОшибок : Число 6, 0
Комментарий : Строка
Очередь : Число 31, 15
ЗаказПодДеятельность : Типы налогообложения НДС
Назначение : Справочник.Назначение
ИгнорироватьОграниченияДоступностиВидовРабочихЦентров : Булево
ИгнорироватьОграниченияДоступностиМатериалов : Булево
НаПустойЗавод : Булево
ДокументОснование : Документ.Заказ материалов в производство\rДокумент.Заявка на возврат товаров от клиента\rДокумент.Заказ на сборку (разборку)\r...
ЗадействоватьРезервДоступности : Булево
Приоритет : Справочник.Приоритет
ПроизводствоПоЗаказу : Булево
Заказ : Документ.Заказ давальца
НаправлениеДеятельности : Справочник.Направление деятельности
ОбосабливатьПоНазначениюЗаказа : Булево
..Табличная часть \n Продукция..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Спецификация : Справочник.Ресурсная спецификация
ДатаПотребности : Дата
НачатьНеРанее : Дата
РазмещениеВыпуска : Способы привязки операций производства
Склад : Справочник.Склад (складская территория)
Подразделение : Справочник.Подразделение
Назначение : Справочник.Назначение
ИзмененияЗапрещены : Булево
КодСтроки : Число 10, 0
КлючСвязи : Уникальный идентификатор
КлючСвязиМатериалыИУслуги : Уникальный идентификатор
КлючСвязиПродукция : Уникальный идентификатор
ОптимальноеКоличествоПередачиМеждуЭтапами : Число 15, 0
СостояниеСпецификации : Число 2, 0
ЕстьСоответствиеСтандартнойСпецификации : Булево
ГрафикРассчитан : Булево
..Табличная часть \n Этапы..
Этап : Справочник.Этап ресурсной спецификации
НомерЭтапа : Число 4, 0
НомерСледующегоЭтапа : Число 4, 0
Подразделение : Справочник.Подразделение
Количество : Число 15, 0
Непрерывный : Булево
ПланироватьРаботуВидовРабочихЦентров : Булево
ДлительностьЭтапа : Число 10, 0
ЕдиницаИзмеренияДлительностиЭтапа : Единицы измерения времени
ЕдиницаИзмерения : Строка
ПредварительныйБуфер : Число 10, 0
ЗавершающийБуфер : Число 10, 0
ОдновременноПроизводимоеКоличествоЕдиницПартийИзделий : Число 10, 0
ЕдиницаИзмеренияПредварительногоБуфера : Единицы измерения времени
ЕдиницаИзмеренияЗавершающегоБуфера : Единицы измерения времени
МаршрутнаяКарта : Справочник.Маршрутная карта
Описание : Строка
КлючСвязи : Уникальный идентификатор
КлючСвязиПродукция : Уникальный идентификатор
КлючСвязиЭтапы : Уникальный идентификатор
КлючСвязиПолуфабрикат : Уникальный идентификатор
КоличествоЭтаповНаЕдиницуСледующегоЭтапа : Число 15, 0
НаименованиеЭтапа : Строка
ЭтапВосстановленияБрака : Булево
КлючСвязиЭтапыБрак : Уникальный идентификатор
ПроизводствоНаСтороне : Булево
Партнер : Справочник.Партнер
ГрафикРаботыПартнера : Справочник.График работы
УслугаПереработчика : Справочник.Номенклатура
ХарактеристикаУслугиПереработчика : Справочник.Характеристика номенклатуры
СтатьяКалькуляции : Справочник.Статьи калькуляции
Спецификация : Справочник.Ресурсная спецификация
..Табличная часть \n ВыходныеИзделия..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Этап : Справочник.Этап ресурсной спецификации
Склад : Справочник.Склад (складская территория)
Подразделение : Справочник.Подразделение
ДоляСтоимости : Число 10, 0
КлючСвязи : Уникальный идентификатор
КлючСвязиПродукция : Уникальный идентификатор
КлючСвязиЭтапы : Уникальный идентификатор
КлючСвязиПолуфабрикат : Уникальный идентификатор
ПроизводитсяВПроцессе : Булево
Назначение : Справочник.Назначение
..Табличная часть \n ВозвратныеОтходы..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Этап : Справочник.Этап ресурсной спецификации
Склад : Справочник.Склад (складская территория)
Подразделение : Справочник.Подразделение
КлючСвязи : Уникальный идентификатор
КлючСвязиПродукция : Уникальный идентификатор
КлючСвязиЭтапы : Уникальный идентификатор
КлючСвязиПолуфабрикат : Уникальный идентификатор
ПроизводитсяВПроцессе : Булево
СтатьяКалькуляции : Справочник.Статьи калькуляции
ОписаниеИзделия : Строка
КлючСвязиМатериалыИУслуги : Уникальный идентификатор
Назначение : Справочник.Назначение
..Табличная часть \n МатериалыИУслуги..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Этап : Справочник.Этап ресурсной спецификации
Склад : Справочник.Склад (складская территория)
СтатьяКалькуляции : Справочник.Статьи калькуляции
ИспользуетсяАвтовыбор : Булево
СведенияАвтовыбора : Строка
ПрименениеМатериала : Строка
ПроизводитсяВПроцессе : Булево
ВариантОбеспечения : Варианты обеспечения
ДатаПотребности : Дата
ЗаказатьНаСклад : Булево
КлючСвязи : Уникальный идентификатор
КлючСвязиПродукция : Уникальный идентификатор
КлючСвязиЭтапы : Уникальный идентификатор
КлючСвязиСпецификация : Уникальный идентификатор
Запланировать : Булево
СтатусУказанияСерий : Число 2, 0
УказыватьСерии : Булево
Серия : Справочник.Серия номенклатуры
КодСтроки : Число 10, 0
СтатусУказанияСерийОтправитель : Число 2, 0
СтатусУказанияСерийПолучатель : Число 2, 0
Подразделение : Справочник.Подразделение
КлючСвязиЭтапыСтрока : Строка
Отменено : Булево
ИсточникПолученияПолуфабриката : Справочник.Ресурсная спецификация\rСправочник.Этап ресурсной спецификации
КлючСвязиЭтапВыпуска : Уникальный идентификатор
Назначение : Справочник.Назначение
..Табличная часть \n Трудозатраты..
ВидРабот : Справочник.Вид работ сотрудников
Количество : Число 15, 3
СтатьяКалькуляции : Справочник.Статьи калькуляции
КлючСвязи : Уникальный идентификатор
КлючСвязиПродукция : Уникальный идентификатор
КлючСвязиЭтапы : Уникальный идентификатор
НазначениеРабот : Строка
..Табличная часть \n ВидыРабочихЦентров..
ВидРабочегоЦентра : Справочник.Вид рабочего центра
ВремяРаботы : Число 10, 1
ЕдиницаИзмерения : Единицы измерения времени
ВариантНаладки : Справочник.Вариант наладки
Использовать : Булево
Загрузка : Число 15, 3
КлючСвязиЭтапы : Уникальный идентификатор
КлючСвязиПродукция : Уникальный идентификатор
КлючСвязи : Уникальный идентификатор
..Табличная часть \n АльтернативныеВидыРабочихЦентров..
ВидРабочегоЦентра : Справочник.Вид рабочего центра
ВремяРаботы : Число 10, 1
ЕдиницаИзмерения : Единицы измерения времени
Использовать : Булево
УчитыватьДоступностьПоГрафикуРаботы : Булево
ВариантНаладки : Справочник.Вариант наладки
Загрузка : Число 15, 3
КлючСвязиЭтапы : Уникальный идентификатор
КлючСвязиВидыРабочихЦентров : Уникальный идентификатор
КлючСвязиПродукция : Уникальный идентификатор
КлючСвязи : Уникальный идентификатор
..Табличная часть \n ПродукцияГрафик..
Начало : Дата
Окончание : Дата
СделаныИзменения : Булево
КлючСвязиПродукция : Уникальный идентификатор
..Табличная часть \n ЭтапыГрафик..
Этап : Справочник.Этап ресурсной спецификации
Подразделение : Справочник.Подразделение
Количество : Число 15, 0
Отказано : Число 15, 0
НачалоПредварительногоБуфера : Дата
НачалоЭтапа : Дата
ОкончаниеЭтапа : Дата
ОкончаниеЗавершающегоБуфера : Дата
НомерЭтапа : Число 4, 0
НомерСледующегоЭтапа : Число 4, 0
КодСтроки : Число 10, 0
КлючСвязи : Уникальный идентификатор
КлючСвязиПродукция : Уникальный идентификатор
КлючСвязиЭтапы : Уникальный идентификатор
Спецификация : Справочник.Ресурсная спецификация
..Табличная часть \n ВыходныеИзделияГрафик..
ДатаЗапуска : Дата
ДатаВыпуска : Дата
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
КлючСвязиПродукция : Уникальный идентификатор
КлючСвязиЭтапыГрафик : Уникальный идентификатор
КлючСвязиВыходныеИзделия : Уникальный идентификатор
..Табличная часть \n ВозвратныеОтходыГрафик..
ДатаВыпуска : Дата
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
КлючСвязиПродукция : Уникальный идентификатор
КлючСвязиЭтапыГрафик : Уникальный идентификатор
КлючСвязиВозвратныеОтходы : Уникальный идентификатор
..Табличная часть \n МатериалыИУслугиГрафик..
ДатаПотребности : Дата
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
КлючСвязиПродукция : Уникальный идентификатор
КлючСвязиЭтапыГрафик : Уникальный идентификатор
КлючСвязиМатериалыИУслуги : Уникальный идентификатор
ВариантОбеспечения : Варианты обеспечения
..Табличная часть \n ТрудозатратыГрафик..
ДатаПотребности : Дата
Количество : Число 15, 3
КлючСвязиПродукция : Уникальный идентификатор
КлючСвязиЭтапыГрафик : Уникальный идентификатор
КлючСвязиТрудозатраты : Уникальный идентификатор
..Табличная часть \n ЗанятостьВидовРабочихЦентров..
ВидРабочегоЦентра : Справочник.Вид рабочего центра
ДатаИнтервала : Дата
Количество : Число 8, 1
КлючСвязиПродукция : Уникальный идентификатор
КлючСвязиЭтапыГрафик : Уникальный идентификатор
КлючСвязиЭтапы : Уникальный идентификатор
НомерСтрокиПродукция : Число 5, 0
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n ЭтапыВосстановленияБрака..
КлючСвязиПродукция : Уникальный идентификатор
КлючСвязиЭтапы : Уникальный идентификатор
МаршрутныйЛист : Документ.Маршрутный лист производства
Количество : Число 15, 0
КлючСвязиЭтапыБрак : Уникальный идентификатор
..Движения..
ТоварыКОтгрузке : Остатки
ЗаказыМатериаловВПроизводство : Остатки
ГрафикОтгрузкиТоваров : Остатки
ЭтапыПроизводства : Обороты
ФактическиеДанныеБюджетирования : Обороты
ДоступностьВидовРабочихЦентров : Обороты
ОбеспечениеЗаказов : Остатки
ДвижениеТоваров : Обороты
ОбеспечениеЗаказовРаботами : Остатки
БракВПроизводстве : Остатки
ЗаказыМатериаловСУчетомКорректировок : Обороты
ЗаказыНаПроизводствоТрудозатраты : Остатки
ЗаказыНаПроизводствоСпецификации : Остатки
СвободныеОстатки : Остатки
ПереработкаПоГрафикуПроизводства : Остатки
ГрафикПоступленияТоваров : Остатки
}
@enduml
