@startuml СообщениеОбменСБанками
'!include templates.wsd
'..\include templates.wsd
class Документ.СообщениеОбменСБанками as "Сообщение обмена с банками" <<Документы>>
{
..Реквизиты..
Банк : Справочник.Банк
ВидЭД : Виды электронных документов обмена с банками
ВнешнийИдентификатор : Строка
ДатаДокументаОтправителя : Дата
ДатаИзмененияВнешнегоСтатуса : Дата
ДатаИзмененияСтатуса : Дата
ДатаСообщения : Дата
ДополнительнаяИнформация : Строка
ДополнительныеДанные : Хранилище значения
Идентификатор : Строка
Комментарий : Строка
Направление : Направления ЭД
НастройкаОбмена : Справочник.Настройка обмена с банком
НомерДокументаОтправителя : Строка
НомерСчета : Строка
Организация : Справочник.Организация
ПредставлениеДокумента : Строка
ПричинаОтклонения : Строка
СообщениеРодитель : Документ.Сообщение обмена с банками
Состояние : Состояния прямого обмена с банками
Статус : Статусы обмена с банками
СуммаДокумента : Число 15, 2
ПредставлениеПрогрессаПодписания : Строка
..Табличная часть \n УдалитьСтатусыЭлектронныхПодписей..
ДатаПроверкиПодписи : Дата
ПодписьВерна : Булево
}
@enduml
