@startuml ПередачаСырьяПереработчику
'!include templates.wsd
'..\include templates.wsd
class Документ.ПередачаСырьяПереработчику as "Передача сырья переработчику" <<Документы>>
{
..Реквизиты..
Автор : Справочник.Пользователь
АдресДоставки : Строка
БанковскийСчетГрузоотправителя : Справочник.Банковский счет
БанковскийСчетГрузополучателя : Справочник.Банковский счет
БанковскийСчетКонтрагента : Справочник.Банковский счет
БанковскийСчетОрганизации : Справочник.Банковский счет организации
Валюта : Справочник.Валюта
ВернутьМногооборотнуюТару : Булево
ВидыЗапасовУказаныВручную : Булево
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
Грузоотправитель : Справочник.Контрагент
Грузополучатель : Справочник.Контрагент
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
ДатаВозвратаМногооборотнойТары : Дата
ДатаРаспоряжения : Дата
ДоверенностьВыдана : Строка
ДоверенностьДата : Дата
ДоверенностьЛицо : Строка
ДоверенностьНомер : Строка
Договор : Справочник.Договор с контрагентом
ЗаказПереработчику : Документ.Заказ переработчику
Касса : Справочник.Касса
Комментарий : Строка
КонтактноеЛицо : Справочник.Контактное лицо
Контрагент : Справочник.Контрагент
Менеджер : Справочник.Пользователь
Организация : Справочник.Организация
Основание : Строка
ОснованиеДата : Дата
ОснованиеНомер : Строка
Отпустил : Справочник.Физическое лицо
ОтпустилДолжность : Строка
Партнер : Справочник.Партнер
ПередачаПоЗаказам : Булево
Подразделение : Справочник.Подразделение
Руководитель : Справочник.Лицо с правом подписи
Сделка : Справочник.Сделка с клиентом
Склад : Справочник.Склад (складская территория)
Согласован : Булево
СостояниеЗаполненияМногооборотнойТары : Состояния заполнения многооборотной тары
СуммаДокумента : Число 15, 2
АдресДоставкиЗначенияПолей : Строка
ДополнительнаяИнформацияПоДоставке : Строка
ПеревозчикПартнер : Справочник.Партнер
СпособДоставки : Способы доставки
ХозяйственнаяОперация : Хозяйственные операции
ОсобыеУсловияПеревозки : Булево
ОсобыеУсловияПеревозкиОписание : Строка
НаправлениеДеятельности : Справочник.Направление деятельности
ЗонаДоставки : Справочник.Зоны доставки
АдресДоставкиПеревозчика : Строка
АдресДоставкиПеревозчикаЗначенияПолей : Строка
ВремяДоставкиС : Дата
ВремяДоставкиПо : Дата
ВидЦены : Справочник.Вид цены
УчетСырьяПоНазначениям : Булево
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
УдалитьВидЦены : Справочник.Вид цены
Цена : Число 15, 2
Сумма : Число 15, 2
КодСтроки : Число 10, 0
КлючСвязи : Число 10, 0
Склад : Справочник.Склад (складская территория)
СтатусУказанияСерий : Число 2, 0
ЗаказПереработчику : Документ.Заказ переработчику
СрокПоставки : Число 10, 0
ИдентификаторСтроки : Строка
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
Серия : Справочник.Серия номенклатуры
..Табличная часть \n Серии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Склад : Справочник.Склад (складская территория)
..Табличная часть \n ВидыЗапасов..
ВидЗапасов : Справочник.Вид запасов
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ИдентификаторСтроки : Строка
Склад : Справочник.Склад (складская территория)
ЗаказПереработчику : Документ.Заказ переработчику
КодСтроки : Число 10, 0
НомерГТД : Справочник.Номер ГТД
ЗалоговаяСтоимость : Число 15, 2
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ВидЗапасовПолучателя : Справочник.Вид запасов
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ТоварыКОтгрузке : Остатки
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ТоварыКОформлениюОтчетовКомитенту : Остатки
ПереданнаяВозвратнаяТара : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНМатериалы : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ЗаказыКлиентов : Остатки
ОбеспечениеЗаказов : Остатки
Международный : РегистрБухгалтерии
РасходыПриУСНТовары : Остатки
НДСЗаписиКнигиПродаж : Обороты
ТоварыОрганизацийКПередаче : Остатки
КнигаУчетаДоходовИРасходов : Обороты
ТоварыПереданныеПереработчику : Остатки
МатериалыИРаботыВПроизводстве : Остатки
СвободныеОстатки : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
ПартииПроизводственныхЗатрат : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
