@startuml ПроизводствоБезЗаказа
'!include templates.wsd
'..\include templates.wsd
class Документ.ПроизводствоБезЗаказа as "Производство без заказа" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ГруппировкаЗатрат : Группировки затрат в производстве без заказа
ВыпускПодДеятельность : Типы налогообложения НДС
НаправлениеДеятельности : Справочник.Направление деятельности
ВидЦены : Справочник.Вид цены
Ответственный : Справочник.Пользователь
Комментарий : Строка
ВидыЗапасовУказаныВручную : Булево
Валюта : Справочник.Валюта
ЕстьМаркируемаяПродукцияГИСМ : Булево
РаспоряжениеДляТрудозатрат : Булево
МаксимальныйКодСтрокиВыходныеИзделия : Число 10, 0
МаксимальныйКодСтрокиТрудозатраты : Число 10, 0
..Табличная часть \n ВыходныеИзделия..
НаправлениеВыпуска : Хозяйственные операции
Получатель : Статья расходов\rСправочник.Подразделение\rСтатья актива/пассива\r...
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Упаковка : Справочник.Упаковка
Спецификация : Справочник.Ресурсная спецификация
Назначение : Справочник.Назначение
ДоляСтоимости : Число 10, 0
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
УдалитьВидЗапасов : Справочник.Вид запасов
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
АналитикаУчетаПартийПроизводства : Справочник.Ключ аналитики учета партий производства
НомерГруппыЗатрат : Число 10, 0
ИдентификаторСтроки : Строка
ОсновноеИзделиеГруппыЗатрат : Булево
ПередатьДавальцу : Булево
КодСтроки : Число 10, 0
..Табличная часть \n ВыходныеИзделияСерии..
Серия : Справочник.Серия номенклатуры
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Получатель : Справочник.Подразделение\rСправочник.Склад (складская территория)
Назначение : Справочник.Назначение
Количество : Число 15, 3
..Табличная часть \n ПобочныеИзделия..
Подразделение : Справочник.Подразделение
НаправлениеВыпуска : Хозяйственные операции
Получатель : Статья расходов\rСправочник.Подразделение\rСтатья актива/пассива\r...
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Упаковка : Справочник.Упаковка
Назначение : Справочник.Назначение
Цена : Число 15, 2
Сумма : Число 15, 2
СтатьяКалькуляции : Справочник.Статьи калькуляции
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
НомерГруппыЗатрат : Число 10, 0
УдалитьВидЗапасов : Справочник.Вид запасов
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
АналитикаУчетаПартийПроизводства : Справочник.Ключ аналитики учета партий производства
ИдентификаторСтроки : Строка
ПередатьДавальцу : Булево
..Табличная часть \n ПобочныеИзделияСерии..
Серия : Справочник.Серия номенклатуры
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Получатель : Справочник.Подразделение\rСправочник.Склад (складская территория)
Назначение : Справочник.Назначение
Количество : Число 15, 3
..Табличная часть \n МатериалыИРаботы..
Отправитель : Справочник.Подразделение\rСправочник.Склад (складская территория)
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Упаковка : Справочник.Упаковка
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
СтатьяКалькуляции : Справочник.Статьи калькуляции
НомерГруппыЗатрат : Число 10, 0
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
АналитикаУчетаПартийПроизводства : Справочник.Ключ аналитики учета партий производства
..Табличная часть \n Трудозатраты..
Подразделение : Справочник.Подразделение
ВидРабот : Справочник.Вид работ сотрудников
Количество : Число 15, 3
СтатьяКалькуляции : Справочник.Статьи калькуляции
АналитикаУчетаПартийПроизводства : Справочник.Ключ аналитики учета партий производства
НомерГруппыЗатрат : Число 10, 0
Исполнитель : Справочник.Бригады\rСправочник.Физическое лицо
КодСтроки : Число 10, 0
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n ВидыЗапасовМатериалыИРаботы..
АналитикаУчетаНоменклатуры : Справочник.Номенклатура\rСправочник.Ключ аналитики учета номенклатуры
АналитикаУчетаПартийПроизводства : Справочник.Ключ аналитики учета партий производства
СтатьяКалькуляции : Справочник.Статьи калькуляции
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
ВидЗапасовПолучателя : Справочник.Вид запасов
..Табличная часть \n ВидыЗапасовВыходныеИзделия..
АналитикаУчетаНоменклатуры : Справочник.Номенклатура\rСправочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
НаправлениеВыпуска : Хозяйственные операции
Получатель : Статья расходов\rСправочник.Подразделение\rСтатья актива/пассива\r...
АналитикаУчетаПартийПроизводства : Справочник.Ключ аналитики учета партий производства
Спецификация : Справочник.Ресурсная спецификация
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
ИдентификаторСтроки : Строка
ПередатьДавальцу : Булево
КодСтроки : Число 10, 0
Количество : Число 15, 3
ДоляСтоимости : Число 10, 0
..Табличная часть \n ВидыЗапасовПобочныеИзделия..
АналитикаУчетаНоменклатуры : Справочник.Номенклатура\rСправочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Подразделение : Справочник.Подразделение
НаправлениеВыпуска : Хозяйственные операции
Получатель : Статья расходов\rСправочник.Подразделение\rСтатья актива/пассива\r...
АналитикаУчетаПартийПроизводства : Справочник.Ключ аналитики учета партий производства
СтатьяКалькуляции : Справочник.Статьи калькуляции
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
ИдентификаторСтроки : Строка
ПередатьДавальцу : Булево
Количество : Число 15, 3
Сумма : Число 15, 2
..Движения..
ТрудозатратыНезавершенногоПроизводства : Остатки
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ТоварыКОформлениюОтчетовКомитенту : Остатки
Хозрасчетный : РегистрБухгалтерии
УслугиДавальцуКОформлению : Остатки
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
Международный : РегистрБухгалтерии
НДСЗаписиКнигиПродаж : Обороты
ОбеспечениеЗаказовРаботами : Остатки
ТоварыОрганизацийКПередаче : Остатки
МатериалыИРаботыВПроизводстве : Остатки
СвободныеОстатки : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
ТрудозатратыКОформлению : Остатки
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
ПрочиеРасходыНезавершенногоПроизводства : Остатки
ПартииПроизводственныхЗатрат : Остатки
ВыпускПродукции : Обороты
}
@enduml
