@startuml ФормированиеЗаписейРаздела7ДекларацииНДС
'!include templates.wsd
'..\include templates.wsd
class Документ.ФормированиеЗаписейРаздела7ДекларацииНДС as "Формирование записей раздела 7 декларации по НДС" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
Комментарий : Строка
РучнаяКорректировка : Булево
..Табличная часть \n НеоблагаемыеНДСОперации..
КодОперации : Справочник.Коды операций раздела 7 декларации по НДС
Контрагент : Справочник.Организация\rСправочник.Контрагент
СуммаРеализации : Число 15, 2
СуммаПриобретения : Число 15, 2
НДСПрямой : Число 15, 2
КлючСтроки : Число 5, 0
ДокументРеализации : Документ.Отчет комиссионера (агента) о продажах\rДокумент.Отчет давальцу\rДокумент.Первичный документ\r...
НДСРаспределенный : Число 15, 2
..Табличная часть \n ПодтверждающиеДокументы..
ТипДокумента : Справочник.Типы документов подтверждающих льготу по НДС
НомерДокумента : Строка
ДатаДокумента : Дата
КлючСтроки : Число 5, 0
..Движения..
НДСЗаписиРаздела7Декларации : Обороты
}
@enduml
