@startuml ОтчетБанкаПоОперациямЭквайринга
'!include templates.wsd
'..\include templates.wsd
class Документ.ОтчетБанкаПоОперациямЭквайринга as "Отчет банка по операциям эквайринга" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
БанковскийСчет : Справочник.Банковский счет организации
Эквайер : Справочник.Контрагент
Валюта : Справочник.Валюта
СуммаПокупок : Число 15, 2
СуммаВозвратов : Число 15, 2
СуммаКомиссии : Число 15, 2
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
СуммаДокумента : Число 15, 2
Подразделение : Справочник.Подразделение
..Табличная часть \n Покупки..
ДатаПлатежа : Дата
НомерПлатежнойКарты : Строка
Сумма : Число 15, 2
КодАвторизации : Строка
ЭквайринговыйТерминал : Справочник.Эквайринговый терминал
ИдентификаторСтроки : Строка
..Табличная часть \n Возвраты..
ДатаПлатежа : Дата
НомерПлатежнойКарты : Строка
Сумма : Число 15, 2
КодАвторизации : Строка
ЭквайринговыйТерминал : Справочник.Эквайринговый терминал
ИдентификаторСтроки : Строка
..Движения..
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
РасходыПриУСН : Остатки
ДенежныеСредстваВПути : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
ДвиженияДенежныеСредстваДоходыРасходы : Обороты
КнигаУчетаДоходовИРасходов : Обороты
РасчетыПоЭквайрингу : Остатки
}
@enduml
