@startuml АннулированиеПодарочныхСертификатов
'!include templates.wsd
'..\include templates.wsd
class Документ.АннулированиеПодарочныхСертификатов as "Аннулирование подарочных сертификатов" <<Документы>>
{
..Реквизиты..
Менеджер : Справочник.Пользователь
Комментарий : Строка
Организация : Справочник.Организация
..Табличная часть \n ПодарочныеСертификаты..
ПодарочныйСертификат : Справочник.Подарочный сертификат
СуммаВВалютеСертификата : Число 15, 2
СтатьяДоходов : Статьи доходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
..Движения..
ПрочиеДоходы : Остатки
ИсторияПодарочныхСертификатов : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияКонтрагентДоходыРасходы : Обороты
ПодарочныеСертификаты : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
}
@enduml
