@startuml ЗапросВФССОПроверкеРаботодателя
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗапросВФССОПроверкеРаботодателя as "Запрос в ФСС о проверке работодателя" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ВидПособия : Перечень пособий социального страхования
РегистрационныйНомерФСС : Строка
ДополнительныйКодФСС : Строка
КодПодчиненностиФСС : Строка
НаименованиеТерриториальногоОрганаФСС : Строка
АдресОрганизации : Строка
СтраховойНомерПФР : Строка
Фамилия : Строка
Имя : Строка
Отчество : Строка
Адрес : Строка
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Страхователи..
Справка : Документ.Справка для расчета пособий (входящая)
Страхователь : Справочник.Работодатель
ПериодРаботыС : Дата
ПериодРаботыПо : Дата
РегистрационныйНомерФСС : Строка
ДополнительныйКодФСС : Строка
КодПодчиненностиФСС : Строка
НаименованиеТерриториальногоОрганаФСС : Строка
ИНН : Строка
КПП : Строка
..Табличная часть \n ФиксацияИзменений..
ИмяРеквизита : Строка
Путь : Строка
ИдентификаторСтроки : Число 5, 0
}
@enduml
