@startuml ОперацияБух
'!include templates.wsd
'..\include templates.wsd
class Документ.ОперацияБух as "Операция (регламентированный учет)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
СуммаОперации : Число 15, 2
Содержание : Строка
УдалитьСпособЗаполнения : Строка
УдалитьСторнируемыйДокумент : Документ.Сторнирование начислений\rДокумент.Внутреннее потребление товаров\rДокумент.Назначение планового начисления\r...
Ответственный : Справочник.Пользователь
Комментарий : Строка
ТиповаяОперация : Документ.Сторнирование начислений\rДокумент.Внутреннее потребление товаров\rДокумент.Назначение планового начисления\r...
СуммаУУ : Число 15, 2
..Табличная часть \n ЗапрашиваемыеПараметры..
Имя : Строка
Представление : Строка
Значение : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
..Табличная часть \n ТаблицаРегистровСведений..
Имя : Строка
..Табличная часть \n ТаблицаРегистровНакопления..
Имя : Строка
..Табличная часть \n ЗаполнениеДвижений..
Документ : Документ.Сторнирование начислений\rДокумент.Внутреннее потребление товаров\rДокумент.Назначение планового начисления\r...
Примечание : Строка
..Движения..
ОтражениеДокументовВРеглУчете : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
НДСЗаписиКнигиПродаж : Обороты
НДСЗаписиКнигиПокупок : Обороты
ЖурналУчетаСчетовФактур : РегистрСведений
}
@enduml
