@startuml ТТНИсходящаяЕГАИС
'!include templates.wsd
'..\include templates.wsd
class Документ.ТТНИсходящаяЕГАИС as "Товарно-транспортная накладная ЕГАИС (исходящая)" <<Документы>>
{
..Реквизиты..
ВидОперации : Виды операций ТТН ЕГАИС (исходящей)
Идентификатор : Строка
ИдентификаторЕГАИС : Строка
УдалитьСтатусОбработки : Статусы обработки ТТН ЕГАИС (исходящей)
ДатаРегистрацииДвижений : Дата
НомерТТН : Строка
ДатаТТН : Дата
ДатаОтгрузки : Дата
Грузоотправитель : Справочник.Организация ЕГАИС
Грузополучатель : Справочник.Организация ЕГАИС
Поставщик : Справочник.Организация ЕГАИС
Основание : Строка
Упакована : Булево
ТипДоставки : Строка
Перевозчик : Строка
Автомобиль : Строка
Прицеп : Строка
Заказчик : Строка
Водитель : Строка
ПунктПогрузки : Строка
ПунктРазгрузки : Строка
Перенаправление : Строка
Экспедитор : Строка
СуммаДокумента : Число 15, 2
Комментарий : Строка
Ответственный : Справочник.Пользователь
ЕстьРасхождения : Булево
ДокументОснование : Документ.Возврат товаров поставщику\rДокумент.Перемещение товаров\rДокумент.Возврат между организациями\r...
..Табличная часть \n Товары..
АлкогольнаяПродукция : Справочник.Алкогольная продукция ЕГАИС
ИдентификаторУпаковки : Строка
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
Количество : Число 15, 3
КоличествоУпаковок : Число 15, 3
КоличествоФакт : Число 15, 3
Сумма : Число 15, 2
Цена : Число 17, 4
НомерПартии : Строка
Справка2 : Справочник.Справка к ТТН по форме 2
НомерСправки2Покупателя : Строка
..Движения..
ОстаткиАлкогольнойПродукцииЕГАИС : Остатки
}
@enduml
