@startuml РеестрДанныхЭЛНЗаполняемыхРаботодателем
'!include templates.wsd
'..\include templates.wsd
class Документ.РеестрДанныхЭЛНЗаполняемыхРаботодателем as "Реестр ЭЛН для отправки в ФСС" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
СтатусДокумента : Статусы заявлений и реестров на выплату пособий
РегистрационныйНомерФСС : Строка
ДополнительныйКодФСС : Строка
КодПодчиненностиФСС : Строка
РеестрСоставил : Справочник.Физическое лицо
ТелефонСоставителя : Строка
АдресЭлектроннойПочтыСоставителя : Строка
Руководитель : Справочник.Физическое лицо
ГлавныйБухгалтер : Справочник.Физическое лицо
Ответственный : Справочник.Пользователь
Комментарий : Строка
НомерЗапросаЗаДень : Число 5, 0
..Табличная часть \n ДанныеЭЛН..
ЛистокНетрудоспособности : Документ.Больничный лист
НомерЛисткаНетрудоспособности : Строка
Сотрудник : Справочник.Сотрудник
ВидЗанятости : Виды занятости
СНИЛС : Строка
ИНН : Строка
СтажЛет : Число 2, 0
СтажМесяцев : Число 2, 0
СтажРасширенныйЛет : Число 2, 0
СтажРасширенныйМесяцев : Число 2, 0
УсловияИсчисленияКод1 : Строка
УсловияИсчисленияКод2 : Строка
УсловияИсчисленияКод3 : Строка
ДатаАктаН1 : Дата
ДатаНачалаРаботы : Дата
ПриступитьКРаботеС : Дата
ДатаНачалаОплаты : Дата
ДатаОкончанияОплаты : Дата
ДатаНачалаОплатыФСС : Дата
ДатаОкончанияОплатыФСС : Дата
БазаДляРасчетаСреднегоЗаработка : Число 15, 2
СреднийДневнойЗаработок : Число 15, 2
СуммаОплатыЗаСчетРаботодателя : Число 15, 2
СуммаОплатыЗаСчетФСС : Число 15, 2
ИдентификаторСтрокиФикс : Число 5, 0
ФинансированиеФедеральнымБюджетом : Основания финансирования пособия федеральным бюджетом
Хеш : Строка
}
@enduml
