@startuml ПланПродаж
'!include templates.wsd
'..\include templates.wsd
class Документ.ПланПродаж as "План продаж по номенклатуре" <<Документы>>
{
..Реквизиты..
Комментарий : Строка
Подразделение : Справочник.Подразделение
Статус : Статусы планов
Периодичность : Периодичность
НачалоПериода : Дата
ОкончаниеПериода : Дата
Менеджер : Справочник.Пользователь
ОбновитьДополнить : Число 1, 0
ИзменитьРезультатНа : Число 5, 2
ТочностьОкругления : Число 1, 0
ПользовательскиеНастройки : Хранилище значения
РаспределитьПоРабочимДням : Булево
Сценарий : Справочник.Сценарии товарного планирования
ВидПлана : Справочник.Вид плана
СуммаДокумента : Число 15, 2
ПланироватьПоСумме : Булево
Валюта : Справочник.Валюта
ЗаполненоАвтоматически : Булево
КроссТаблица : Булево
Партнер : Справочник.Партнер
Соглашение : Справочник.Соглашение об условиях продаж
Склад : Справочник.Склад (складская территория)
ГрафикОплаты : Справочник.График оплаты
Календарь : Справочник.Производственный календарь
Договор : Справочник.Договор с контрагентом
ЗаполнятьПланОплат : Булево
СтруктураНастроек : Хранилище значения
ЗаполнятьПоФормуле : Булево
ОтражаетсяВБюджетировании : Булево
СтатьяБюджетов : Справочник.Статьи бюджетов
СценарийБюджетирования : Справочник.Сценарии бюджетирования
Ответственный : Справочник.Пользователь
ФорматМагазина : Справочник.Форматы магазинов
ОтражаетсяВБюджетированииОплаты : Булево
СтатьяБюджетовОплат : Справочник.Статьи бюджетов
ОтражаетсяВБюджетированииОплатыКредит : Булево
СтатьяБюджетовОплатКредит : Справочник.Статьи бюджетов
Замещающий : Булево
Назначение : Справочник.Назначение
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ДатаОтгрузки : Дата
Отменено : Булево
Склад : Справочник.Склад (складская территория)
Комментарий : Строка
Цена : Число 15, 2
Сумма : Число 15, 2
Партнер : Справочник.Партнер
Соглашение : Справочник.Соглашение об условиях продаж
ДополнительныеПараметры : Хранилище значения
Назначение : Справочник.Назначение
Замещен : Булево
..Табличная часть \n ПравилоЗаполнения..
Использование : Булево
Исключать : Булево
ВариантПреобразования : Варианты преобразования
Источник : Справочник.Источник данных планирования
Период : Хранилище значения
Дата : Хранилище значения
ТипЭлемента : Число 1, 0
НомерСтрокиРодитель : Число 5, 0
ПользовательскиеНастройки : Хранилище значения
ИзменитьРезультатНа : Число 5, 2
Присоединять : Булево
..Табличная часть \n ПланОплаты..
ВариантОплаты : Варианты оплаты клиентом
ДатаПлатежа : Дата
ПроцентПлатежа : Число 5, 2
СуммаПлатежа : Число 15, 2
СуммаЗадолженности : Число 15, 2
СуммаОтгрузок : Число 15, 2
СуммаПлатежей : Число 15, 2
Комментарий : Строка
ДатаОтгрузки : Дата
Замещен : Булево
..Табличная часть \n ЭтапыГрафикаОплаты..
ВариантОплаты : Варианты оплаты клиентом
Сдвиг : Число 10, 0
ПроцентПлатежа : Число 5, 2
ПроцентЗалогаЗаТару : Число 5, 2
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ПланыПродаж : Обороты
ОборотыБюджетов : Обороты
ФактическиеДанныеБюджетирования : Обороты
ПланыОплатКлиентов : Обороты
}
@enduml
