@startuml КонтролируемаяСделка
'!include templates.wsd
'..\include templates.wsd
class Документ.КонтролируемаяСделка as "Лист 1А" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
УведомлениеОКонтролируемойСделке : Документ.Уведомление о контролируемых сделках
ТипВзаимозависимости : Типы взаимозависимости
Контрагент : Справочник.Организация\rСправочник.Контрагент
Договор : Справочник.Договор между организациями\rСправочник.Договор с контрагентом\rСправочник.Договор кредита (депозита)\r...
ПредметСделки : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР
НаименованиеПредметаСделки : Строка
Строка121СтороныВзаимозависимыПоКодексу : Булево
Строка122СделкаВОбластиВнешнейТорговли : Булево
Строка123СделкаСКонтрагентомСЛьготнымНалогообложением : Булево
Строка124СделкаСНезависимымПосредником : Булево
Строка131СуммаДоходовПоСделкамПревышаетПредел : Булево
Строка132СделкаСПлательщикомНДПИ : Булево
Строка133СделкаСКонтрагентомНаСпецрежимах : Булево
Строка134СделкаСПлательщикомНалогаНаПрибыль : Булево
Строка135СделкаСРезидентомОЭЗ : Булево
КодНаименованияСделки : Строка
КодСтороныСделки : Строка
СпособОпределенияЦеныСделки : Справочник.Способ определения цены контролируемой сделки
КомментарийКПункту7 : Строка
СуммаДоходов : Число 15, 2
СуммаДоходовРегулируемых : Число 15, 2
СуммаРасходов : Число 15, 2
СуммаРасходовРегулируемых : Число 15, 2
ТипПредметаСделки : Типы предметов контролируемых сделок
СтранаПроисхожденияПредметаСделки : Справочник.Страна мира
ТипСделки : Типы контролируемых сделок
РедактироватьСуммыСделок : Булево
КодТНВЭД : Справочник.ТН ВЭД
КодОКП : Справочник.ОКП
КодОКВЭД : Справочник.ОКВЭД
ДатаДоговора : Дата
НомерДоговора : Строка
..Табличная часть \n Сделки..
ДатаСовершенияСделки : Дата
Количество : Число 15, 3
ЕдиницаИзмерения : Справочник.Упаковка
Цена : Число 12, 0
КодУсловийПоставки : Строка
Стоимость : Число 15, 2
СтранаОтправкиТовара : Справочник.Страна мира
КодРегионаОтправкиТовара : Строка
ГородОтправкиТовара : Строка
НаселенныйПунктОтправкиТовара : Строка
СтранаСовершенияСделки : Справочник.Страна мира
КодРегионаСовершенияСделки : Строка
ГородСовершенияСделки : Строка
НаселенныйПунктСовершенияСделки : Строка
}
@enduml
