@startuml УведомлениеОбОтгрузкеМаркированныхТоваровГИСМ
'!include templates.wsd
'..\include templates.wsd
class Документ.УведомлениеОбОтгрузкеМаркированныхТоваровГИСМ as "Уведомление об отгрузке маркированных товаров" <<Документы>>
{
..Реквизиты..
Основание : Документ.Возврат товаров поставщику\rДокумент.Реализация товаров и услуг
НомерГИСМ : Число 19, 0
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Контрагент : Справочник.Контрагент
ВидОборотаТовара : Вид оборота товара ГИСМ
Ответственный : Справочник.Пользователь
Комментарий : Строка
GLNКонтрагента : Строка
КонтрагентНеЗарегистрированВГИСМ : Булево
КодТаможенногоОргана : Строка
ДатаРегистрацииДекларации : Дата
РегистрационныйНомерДекларации : Строка
..Табличная часть \n НомераКиЗ..
НомерКиЗ : Строка
RFIDTID : Строка
RFIDEPC : Строка
Стоимость : Число 15, 2
СуммаНДС : Число 15, 2
Подтверждено : Булево
ДатаПодтверждения : Дата
}
@enduml
