@startuml ВыгрузкаРегламентированныхОтчетов
'!include templates.wsd
'..\include templates.wsd
class Документ.ВыгрузкаРегламентированныхОтчетов as "Выгрузка регламентированных отчетов" <<Документы>>
{
..Реквизиты..
ПериодПо : Дата
Организация : Справочник.Организация
КодНалоговогоОргана : Строка
Комментарий : Строка
ОтборПоНалоговомуОргану : Булево
ПредставлениеПериода : Строка
..Табличная часть \n Основная..
Основание : Документ.Регламентированный отчет
НомерСтрокиТекстаВыгрузки : Число 5, 0
..Табличная часть \n Выгрузки..
Тип : Версии форматов выгрузки
ИмяФайла : Строка
Текст : Строка
..Движения..
АрхивДанныхРегламентированнойОтчетности : РегистрСведений
}
@enduml
