@startuml ИзменениеСпособаОтраженияИмущественныхНалогов
'!include templates.wsd
'..\include templates.wsd
class Документ.ИзменениеСпособаОтраженияИмущественныхНалогов as "Изменение способа отражения имущественных налогов" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ОС..
ОсновноеСредство : Справочник.Объект эксплуатации
..Табличная часть \n ОтражениеРасходов..
Подразделение : Справочник.Подразделение
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Коэффициент : Число 10, 0
..Движения..
СпособыОтраженияРасходовПоИмущественнымНалогам : РегистрСведений
}
@enduml
