@startuml ПоясненияКДекларацииПоНДС
'!include templates.wsd
'..\include templates.wsd
class Документ.ПоясненияКДекларацииПоНДС as "Пояснения к декларации по НДС" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Требование : Справочник.Документы реализации полномочий налоговых органов
НалоговыйОрган : Справочник.Налоговые органы
ОписьВходящихДокументов : Справочник.Описи входящих документов, полученных из налоговых органов
Декларация : Справочник.Загруженный отчет\rСтрока\rДокумент.Регламентированный отчет
ПояснИнОсн : Строка
..Табличная часть \n КнигаПокупок..
РезультатПроверки : Результат проверки строки декларации
НомерСтрокиДекларации : Число 12, 0
КодОшибки : Число 10, 0
ГрафаОшибки : Строка
НомерСчетаФактуры : Строка
ДатаСчетаФактуры : Дата
НомерИсправленияСчетаФактуры : Число 3, 0
ДатаИсправленияСчетаФактуры : Дата
НомерКорректировочногоСчетаФактуры : Строка
ДатаКорректировочногоСчетаФактуры : Дата
НомерИсправленияКорректировочногоСчетаФактуры : Число 3, 0
ДатаИсправленияКорректировочногоСчетаФактуры : Дата
НомерТаможеннойДекларации : Строка
КодВалюты : Строка
Стоимость : Число 19, 2
СуммаНДС : Число 19, 2
КодВидаОперации : Строка
ДокументОплаты : Строка
ДатаПринятияНаУчет : Строка
Продавец : Строка
ПосредникИНН : Строка
НомерСчетаФактурыРасхождение : Строка
ДатаСчетаФактурыРасхождение : Дата
НомерИсправленияСчетаФактурыРасхождение : Число 3, 0
ДатаИсправленияСчетаФактурыРасхождение : Дата
НомерКорректировочногоСчетаФактурыРасхождение : Строка
ДатаКорректировочногоСчетаФактурыРасхождение : Дата
НомерИсправленияКорректировочногоСчетаФактурыРасхождение : Число 3, 0
ДатаИсправленияКорректировочногоСчетаФактурыРасхождение : Дата
НомерТаможеннойДекларацииРасхождение : Строка
КодВалютыРасхождение : Строка
СтоимостьРасхождение : Число 19, 2
СуммаНДСРасхождение : Число 19, 2
КодВидаОперацииРасхождение : Строка
ДокументОплатыРасхождение : Строка
ДатаПринятияНаУчетРасхождение : Строка
ПродавецРасхождение : Строка
ПосредникИННРасхождение : Строка
ПериодОтраженияЗаписи : Строка
..Табличная часть \n КнигаПокупокДл..
РезультатПроверки : Результат проверки строки декларации
НомерСтрокиДекларации : Число 12, 0
КодОшибки : Число 10, 0
ГрафаОшибки : Строка
НомерСчетаФактуры : Строка
ДатаСчетаФактуры : Дата
НомерИсправленияСчетаФактуры : Число 3, 0
ДатаИсправленияСчетаФактуры : Дата
НомерКорректировочногоСчетаФактуры : Строка
ДатаКорректировочногоСчетаФактуры : Дата
НомерИсправленияКорректировочногоСчетаФактуры : Число 3, 0
ДатаИсправленияКорректировочногоСчетаФактуры : Дата
НомерТаможеннойДекларации : Строка
КодВалюты : Строка
Стоимость : Число 19, 2
СуммаНДС : Число 19, 2
КодВидаОперации : Строка
ДокументОплаты : Строка
ДатаПринятияНаУчет : Строка
Продавец : Строка
ПосредникИНН : Строка
НомерСчетаФактурыРасхождение : Строка
ДатаСчетаФактурыРасхождение : Дата
НомерИсправленияСчетаФактурыРасхождение : Число 3, 0
ДатаИсправленияСчетаФактурыРасхождение : Дата
НомерКорректировочногоСчетаФактурыРасхождение : Строка
ДатаКорректировочногоСчетаФактурыРасхождение : Дата
НомерИсправленияКорректировочногоСчетаФактурыРасхождение : Число 3, 0
ДатаИсправленияКорректировочногоСчетаФактурыРасхождение : Дата
НомерТаможеннойДекларацииРасхождение : Строка
КодВалютыРасхождение : Строка
СтоимостьРасхождение : Число 19, 2
СуммаНДСРасхождение : Число 19, 2
КодВидаОперацииРасхождение : Строка
ДокументОплатыРасхождение : Строка
ДатаПринятияНаУчетРасхождение : Строка
ПродавецРасхождение : Строка
ПосредникИННРасхождение : Строка
ПериодОтраженияЗаписи : Строка
..Табличная часть \n КнигаПродаж..
РезультатПроверки : Результат проверки строки декларации
НомерСтрокиДекларации : Число 12, 0
КодОшибки : Число 10, 0
ГрафаОшибки : Строка
НомерСчетаФактуры : Строка
ДатаСчетаФактуры : Дата
НомерИсправленияСчетаФактуры : Число 3, 0
ДатаИсправленияСчетаФактуры : Дата
НомерКорректировочногоСчетаФактуры : Строка
ДатаКорректировочногоСчетаФактуры : Дата
НомерИсправленияКорректировочногоСчетаФактуры : Число 3, 0
ДатаИсправленияКорректировочногоСчетаФактуры : Дата
КодВалюты : Строка
СтоимостьВсего : Число 19, 2
Стоимость18 : Число 19, 2
Стоимость10 : Число 19, 2
Стоимость0 : Число 19, 2
СуммаНДС18 : Число 19, 2
СуммаНДС10 : Число 19, 2
СтоимостьОсвобождаемая : Число 19, 2
КодВидаОперации : Строка
ДокументОплаты : Строка
Покупатель : Строка
ПосредникИНН : Строка
НомерСчетаФактурыРасхождение : Строка
ДатаСчетаФактурыРасхождение : Дата
НомерИсправленияСчетаФактурыРасхождение : Число 3, 0
ДатаИсправленияСчетаФактурыРасхождение : Дата
НомерКорректировочногоСчетаФактурыРасхождение : Строка
ДатаКорректировочногоСчетаФактурыРасхождение : Дата
НомерИсправленияКорректировочногоСчетаФактурыРасхождение : Число 3, 0
ДатаИсправленияКорректировочногоСчетаФактурыРасхождение : Дата
КодВалютыРасхождение : Строка
СтоимостьВсегоРасхождение : Число 19, 2
Стоимость18Расхождение : Число 19, 2
Стоимость10Расхождение : Число 19, 2
Стоимость0Расхождение : Число 19, 2
СуммаНДС18Расхождение : Число 19, 2
СуммаНДС10Расхождение : Число 19, 2
СтоимостьОсвобождаемаяРасхождение : Число 19, 2
КодВидаОперацииРасхождение : Строка
ДокументОплатыРасхождение : Строка
ПокупательРасхождение : Строка
ПосредникИННРасхождение : Строка
ПериодОтраженияЗаписи : Строка
..Табличная часть \n КнигаПродажДл..
РезультатПроверки : Результат проверки строки декларации
НомерСтрокиДекларации : Число 12, 0
КодОшибки : Число 10, 0
ГрафаОшибки : Строка
НомерСчетаФактуры : Строка
ДатаСчетаФактуры : Дата
НомерИсправленияСчетаФактуры : Число 3, 0
ДатаИсправленияСчетаФактуры : Дата
НомерКорректировочногоСчетаФактуры : Строка
ДатаКорректировочногоСчетаФактуры : Дата
НомерИсправленияКорректировочногоСчетаФактуры : Число 3, 0
ДатаИсправленияКорректировочногоСчетаФактуры : Дата
КодВалюты : Строка
СтоимостьВсего : Число 19, 2
Стоимость18 : Число 19, 2
Стоимость10 : Число 19, 2
Стоимость0 : Число 19, 2
СуммаНДС18 : Число 19, 2
СуммаНДС10 : Число 19, 2
СтоимостьОсвобождаемая : Число 19, 2
КодВидаОперации : Строка
ДокументОплаты : Строка
Покупатель : Строка
ПосредникИНН : Строка
НомерСчетаФактурыРасхождение : Строка
ДатаСчетаФактурыРасхождение : Дата
НомерИсправленияСчетаФактурыРасхождение : Число 3, 0
ДатаИсправленияСчетаФактурыРасхождение : Дата
НомерКорректировочногоСчетаФактурыРасхождение : Строка
ДатаКорректировочногоСчетаФактурыРасхождение : Дата
НомерИсправленияКорректировочногоСчетаФактурыРасхождение : Число 3, 0
ДатаИсправленияКорректировочногоСчетаФактурыРасхождение : Дата
КодВалютыРасхождение : Строка
СтоимостьВсегоРасхождение : Число 19, 2
Стоимость18Расхождение : Число 19, 2
Стоимость10Расхождение : Число 19, 2
Стоимость0Расхождение : Число 19, 2
СуммаНДС18Расхождение : Число 19, 2
СуммаНДС10Расхождение : Число 19, 2
СтоимостьОсвобождаемаяРасхождение : Число 19, 2
КодВидаОперацииРасхождение : Строка
ДокументОплатыРасхождение : Строка
ПокупательРасхождение : Строка
ПосредникИННРасхождение : Строка
ПериодОтраженияЗаписи : Строка
..Табличная часть \n ЖурналУчетаВыставленныхСчетовФактур..
РезультатПроверки : Результат проверки строки декларации
НомерСтрокиДекларации : Число 12, 0
КодОшибки : Число 10, 0
ГрафаОшибки : Строка
НомерСчетаФактуры : Строка
ДатаСчетаФактуры : Дата
НомерИсправленияСчетаФактуры : Число 3, 0
ДатаИсправленияСчетаФактуры : Дата
НомерКорректировочногоСчетаФактуры : Строка
ДатаКорректировочногоСчетаФактуры : Дата
НомерИсправленияКорректировочногоСчетаФактуры : Число 3, 0
ДатаИсправленияКорректировочногоСчетаФактуры : Дата
КодВидаОперации : Строка
ПокупательИНН : Строка
ПосредническаяДеятельность : Строка
НомерСчетаФактурыРасхождение : Строка
ДатаСчетаФактурыРасхождение : Дата
НомерИсправленияСчетаФактурыРасхождение : Число 3, 0
ДатаИсправленияСчетаФактурыРасхождение : Дата
НомерКорректировочногоСчетаФактурыРасхождение : Строка
ДатаКорректировочногоСчетаФактурыРасхождение : Дата
НомерИсправленияКорректировочногоСчетаФактурыРасхождение : Число 3, 0
ДатаИсправленияКорректировочногоСчетаФактурыРасхождение : Дата
КодВидаОперацииРасхождение : Строка
ПокупательИННРасхождение : Строка
ПосредническаяДеятельностьРасхождение : Строка
ПериодОтраженияЗаписи : Строка
..Табличная часть \n ЖурналУчетаПолученныхСчетовФактур..
НомерСтрокиДекларации : Число 12, 0
КодОшибки : Число 10, 0
ГрафаОшибки : Строка
РезультатПроверки : Результат проверки строки декларации
НомерСчетаФактуры : Строка
ДатаСчетаФактуры : Дата
НомерИсправленияСчетаФактуры : Число 3, 0
ДатаИсправленияСчетаФактуры : Дата
НомерКорректировочногоСчетаФактуры : Строка
ДатаКорректировочногоСчетаФактуры : Дата
НомерИсправленияКорректировочногоСчетаФактуры : Число 3, 0
ДатаИсправленияКорректировочногоСчетаФактуры : Дата
КодВидаСделки : Строка
КодВалюты : Строка
КодВидаОперации : Строка
ПродавецИНН : Строка
СубкомиссионерИНН : Строка
Стоимость : Число 19, 2
СуммаНДС : Число 19, 2
РазницаСтоимостиУменьшение : Число 19, 2
РазницаСтоимостиУвеличение : Число 19, 2
РазницаСуммыНДСУменьшение : Число 19, 2
РазницаСуммыНДСУвеличение : Число 19, 2
НомерСчетаФактурыРасхождение : Строка
ДатаСчетаФактурыРасхождение : Дата
НомерИсправленияСчетаФактурыРасхождение : Число 3, 0
ДатаИсправленияСчетаФактурыРасхождение : Дата
НомерКорректировочногоСчетаФактурыРасхождение : Строка
ДатаКорректировочногоСчетаФактурыРасхождение : Дата
НомерИсправленияКорректировочногоСчетаФактурыРасхождение : Число 3, 0
ДатаИсправленияКорректировочногоСчетаФактурыРасхождение : Дата
КодВидаСделкиРасхождение : Строка
КодВалютыРасхождение : Строка
КодВидаОперацииРасхождение : Строка
ПродавецИННРасхождение : Строка
СубкомиссионерИННРасхождение : Строка
СтоимостьРасхождение : Число 19, 2
СуммаНДСРасхождение : Число 19, 2
РазницаСтоимостиУменьшениеРасхождение : Число 19, 2
РазницаСтоимостиУвеличениеРасхождение : Число 19, 2
РазницаСуммыНДСУменьшениеРасхождение : Число 19, 2
РазницаСуммыНДСУвеличениеРасхождение : Число 19, 2
ПериодОтраженияЗаписи : Строка
..Табличная часть \n ВыставленныеСчетаФактурыНеплательщиковНДС..
КодОшибки : Число 10, 0
ГрафаОшибки : Строка
РезультатПроверки : Результат проверки строки декларации
НомерСчетаФактуры : Строка
ДатаСчетаФактуры : Дата
КодВалюты : Строка
ПокупательИНН : Строка
СтоимостьБезНДС : Число 19, 2
СуммаНДС : Число 19, 2
Стоимость : Число 19, 2
НомерСчетаФактурыРасхождение : Строка
ДатаСчетаФактурыРасхождение : Дата
КодВалютыРасхождение : Строка
ПокупательИННРасхождение : Строка
СтоимостьБезНДСРасхождение : Число 19, 2
СуммаНДСРасхождение : Число 19, 2
СтоимостьРасхождение : Число 19, 2
ПериодОтраженияЗаписи : Строка
..Табличная часть \n Контрагенты..
ИдентификаторЗначения : Строка
ИНН : Строка
КПП : Строка
..Табличная часть \n ДокументыОплаты..
ИдентификаторЗначения : Строка
Номер : Строка
Дата : Дата
..Табличная часть \n ДатыПринятияНаУчет..
ИдентификаторЗначения : Строка
ДатаПринятияНаУчет : Дата
..Табличная часть \n ПосредническаяДеятельность..
ИдентификаторЗначения : Строка
НомерСчетаФактуры : Строка
ДатаСчетаФактуры : Дата
КодВалюты : Строка
Стоимость : Число 19, 2
СуммаНДС : Число 19, 2
РазницаСтоимостиУменьшение : Число 19, 2
РазницаСтоимостиУвеличение : Число 19, 2
РазницаСуммыНДСУменьшение : Число 19, 2
РазницаСуммыНДСУвеличение : Число 19, 2
ПродавецИНН : Строка
..Табличная часть \n СведКС..
НомКС : Строка
ПоясненКС : Строка
ФормулировкаНарушения : Строка
НормаЗакона : Строка
ДанныеДекларации : Строка
КонтрольноеCоотношение : Строка
..Табличная часть \n НетКнигаПрод..
РезультатПроверки : Результат проверки строки декларации
НомерСчетаФактуры : Строка
ДатаСчетаФактуры : Дата
СтоимостьВсего : Число 19, 2
Раздел : Строка
ПокупательИНН : Строка
ПокупательИННРасхождение : Строка
ПокупательКПП : Строка
ПокупательКППРасхождение : Строка
ПосредникИНН : Строка
ПосредникИННРасхождение : Строка
ПосредникКПП : Строка
ПосредникКППРасхождение : Строка
КодВидаОперации : Строка
КодВидаОперацииРасхождение : Строка
НомерСчетаФактурыРасхождение : Строка
ДатаСчетаФактурыРасхождение : Дата
СтоимостьВсегоРасхождение : Число 19, 2
РазделРасхождение : Строка
СтоимостьРубВсего : Число 19, 2
СтоимостьРубВсегоРасхождение : Число 19, 2
НаименованиеКонтрагента : Строка
}
@enduml
