@startuml ВводВыводДенежныхСредствПоНаправлению
'!include templates.wsd
'..\include templates.wsd
class Документ.ВводВыводДенежныхСредствПоНаправлению as "Ввод\вывод денежных средств по направлению" <<Документы>>
{
..Реквизиты..
НаправлениеОтправитель : Справочник.Направление деятельности
НаправлениеПолучатель : Справочник.Направление деятельности
Сумма : Число 15, 2
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Движения..
ПрочиеАктивыПассивы : Остатки
}
@enduml
