@startuml ЗаявлениеВФССОВозмещенииВыплатРодителямДетейИнвалидов
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаявлениеВФССОВозмещенииВыплатРодителямДетейИнвалидов as "Заявление в ФСС о возмещении выплат родителям детей-инвалидов" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
НаименованиеТерриториальногоОрганаФСС : Строка
РегистрационныйНомерФСС : Строка
ДополнительныйКодФСС : Строка
КодПодчиненностиФСС : Строка
ИНН : Строка
КПП : Строка
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
АдресОрганизации : Строка
АдресЭлектроннойПочтыОрганизации : Строка
Банк : Справочник.Банк
НаименованиеБанка : Строка
НомерЛицевогоСчета : Строка
НомерСчета : Строка
БИКБанка : Строка
СтатусДокумента : Статусы заявлений и реестров на выплату пособий
ТелефонСоставителя : Строка
ЗаявлениеСоставил : Справочник.Физическое лицо
УдалитьБанк : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Оплаты..
Сотрудник : Справочник.Сотрудник
Статус : Строка
СреднедневнойЗаработок : Число 15, 2
ДокументОснование : Документ.Оплата дней ухода за детьми-инвалидами
КоличествоСтраниц : Число 2, 0
СуммаПособия : Число 15, 2
СуммаВзносов : Число 15, 2
ИдентификаторСтрокиФикс : Число 5, 0
..Табличная часть \n ФиксацияИзменений..
ИмяРеквизита : Строка
Путь : Строка
ИдентификаторСтроки : Число 5, 0
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
}
@enduml
