@startuml РегистрУчета
'!include templates.wsd
'..\include templates.wsd
class Документ.РегистрУчета as "Регистр учета" <<Документы>>
{
..Реквизиты..
ВидРегистра : Справочник.Вид регистра учета
НачалоПериода : Дата
КонецПериода : Дата
Организация : Справочник.Организация
ПодразделениеОрганизации : Справочник.Подразделение
ВключатьОбособленныеПодразделения : Булево
Описание : Строка
ФорматСохраненияФайла : Форматы сохранения отчетов
}
@enduml
