@startuml ВозвратИзОтпускаПоУходуЗаРебенком
'!include templates.wsd
'..\include templates.wsd
class Документ.ВозвратИзОтпускаПоУходуЗаРебенком as "Возврат из отпуска по уходу" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Сотрудник : Справочник.Физическое лицо
ОсновнойСотрудник : Справочник.Сотрудник
ДатаВозврата : Дата
ДокументОснование : Документ.Отпуск по уходу за ребенком
ИзменитьНачисления : Булево
ИзменитьАванс : Булево
НачисленияУтверждены : Булево
ЗаниматьСтавку : Булево
ИсправленныйДокумент : Документ.Возврат из отпуска по уходу
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ГлавныйБухгалтер : Справочник.Физическое лицо
РуководительКадровойСлужбы : Справочник.Физическое лицо
ДолжностьРуководителяКадровойСлужбы : Справочник.Должность
ИзменитьЛьготы : Булево
Решение : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Начисления..
Действие : Действия с начислениями и удержаниями
Начисление : Начисление
РабочееМесто : Справочник.Сотрудник
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Размер : Число 15, 2
..Табличная часть \n Показатели..
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Показатель : Справочник.Показатель
Значение : Число 15, 5
Действие : Действия с начислениями и удержаниями
РабочееМесто : Справочник.Сотрудник
..Табличная часть \n Авансы..
РабочееМесто : Справочник.Сотрудник
СпособРасчетаАванса : Способы расчета аванса
Аванс : Число 15, 2
..Табличная часть \n ПересчетТарифныхСтавок..
РабочееМесто : Справочник.Сотрудник
ПорядокРасчетаСтоимостиЕдиницыВремени : Порядок расчета стоимости часа (дня) оплаты труда сотрудников
СовокупнаяТарифнаяСтавка : Число 15, 5
ВидТарифнойСтавки : Виды тарифных ставок
..Табличная часть \n Льготы..
Действие : Действия с начислениями и удержаниями
Льгота : Начисление
РабочееМесто : Справочник.Сотрудник
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Размер : Число 15, 2
..Движения..
УдалитьИсключаемыеИзОстатковОтпусковПериоды : РегистрСведений
ПорядокРасчетаСтоимостиЕдиницыВремениСотрудников : РегистрСведений
ЗанятыеПозицииШтатногоРасписания : Остатки
УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников : РегистрСведений
ПрименениеДополнительныхПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
ДанныеСостоянийСотрудников : РегистрСведений
ПрименениеПлановыхНачислений : РегистрСведений
ПлановыеАвансы : РегистрСведений
ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
РеестрОтпусков : РегистрСведений
БухучетПлановыхНачислений : РегистрСведений
ПараметрыПериодовСтажаПФР : РегистрСведений
ПлановыеНачисления : РегистрСведений
}
@enduml
