@startuml ВводОстатковВнеоборотныхАктивов2_4
'!include templates.wsd
'..\include templates.wsd
class Документ.ВводОстатковВнеоборотныхАктивов2_4 as "Ввод остатков внеоборотных активов" <<Документы>>
{
..Реквизиты..
АдресМестонахождения : Строка
ВидАктивов : Виды внеоборотных активов
ГруппаФинансовогоУчета : Справочник.Группа финансового учета внеоборотных активов
Комментарий : Строка
Контрагент : Справочник.Организация\rСправочник.Контрагент
Местонахождение : Справочник.Подразделение
МОЛ : Справочник.Физическое лицо
НаправлениеДеятельности : Справочник.Направление деятельности
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
ОтражатьВРеглУчете : Булево
ОтражатьВУпрУчете : Булево
ПрименениеЦелевогоФинансирования : Булево
РасчетыМеждуОрганизациямиАрендатор : Булево
ХозяйственнаяОперация : Хозяйственные операции
НалогообложениеНДС : Типы налогообложения НДС
..Табличная часть \n ОС..
АдресМестонахожденияАрендатора : Строка
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
АналитикаРасходовАмортизационнойПремии : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаРасходовБУ : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаРасходовНалог : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаРасходовУУ : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ВариантРаздельногоУчетаНДС : Варианты раздельного учета НДС
ВключитьАмортизационнуюПремиюВСоставРасходов : Булево
ГрафикАмортизации : Справочник.Годовой график амортизации ОС
ГруппаФинансовогоУчета : Справочник.Группа финансового учета внеоборотных активов
ДатаМодернизацииБУ : Дата
ДатаМодернизацииУУ : Дата
ДатаПринятияКУчетуБУ : Дата
ДатаПринятияКУчетуУУ : Дата
ДоговорЛизинга : Справочник.Договор лизинга
ЕстьРезервПереоценки : Булево
ЕстьРезервПереоценкиРегл : Булево
ЕстьСобытияМодернизацииБУ : Булево
ЕстьСобытияМодернизацииУУ : Булево
ЗалоговаяСтоимость : Число 15, 2
КорректировкаСтоимостиАрендованногоИмуществаНУ : Число 15, 2
КоэффициентАмортизацииБУ : Число 4, 2
КоэффициентУскоренияБУ : Число 5, 2
КоэффициентУскоренияУУ : Число 4, 3
ЛиквидационнаяСтоимость : Число 15, 2
МетодНачисленияАмортизацииБУ : Способы начисления амортизации основных средств
МетодНачисленияАмортизацииУУ : Способы начисления амортизации основных средств
МОЛ : Справочник.Физическое лицо
МОЛАрендатора : Справочник.Физическое лицо
НазваниеДокументаМодернизации : Строка
НазваниеДокументаПринятияКУчету : Строка
НакопленнаяАмортизацияБУ : Число 15, 2
НакопленнаяАмортизацияБУЦФ : Число 15, 2
НакопленнаяАмортизацияНУ : Число 15, 2
НакопленнаяАмортизацияНУДо2009 : Число 15, 2
НакопленнаяАмортизацияНУЦФ : Число 15, 2
НакопленнаяАмортизацияПР : Число 15, 2
НакопленнаяАмортизацияПРЦФ : Число 15, 2
НакопленнаяАмортизацияУУ : Число 15, 2
НалогообложениеНДС : Типы налогообложения НДС
НачислятьАмортизациюБУ : Булево
НачислятьАмортизациюНУ : Булево
НачислятьАмортизациюУУ : Булево
НачислятьИзносБУ : Булево
НомерДокументаМодернизации : Строка
НомерДокументаПринятияКУчету : Строка
ОбъемНаработки : Число 15, 3
ОбъемНаработкиОстаточныйБУ : Число 10, 0
ОбъемНаработкиОстаточныйУУ : Число 10, 0
ОрганизацияПолучательРасходов : Справочник.Организация
ОсновноеСредство : Справочник.Объект эксплуатации
ПервоначальнаяСтоимостьБУ : Число 15, 2
ПервоначальнаяСтоимостьНУ : Число 15, 2
ПервоначальнаяСтоимостьОтличается : Булево
ПервоначальнаяСтоимостьПР : Число 15, 2
ПервоначальнаяСтоимостьУУ : Число 15, 2
ПередаватьРасходыВДругуюОрганизацию : Булево
Подразделение : Справочник.Подразделение
ПодразделениеАрендатора : Справочник.Подразделение
ПоказательНаработки : Справочник.Показатель наработки
ПорядокУчетаБУ : Порядок погашения стоимости ОС
ПорядокУчетаНУ : Порядок включения стоимости основных средств в состав расходов (НУ)
ПорядокУчетаУУ : Порядок учета стоимости внеоборотных активов
ПрименениеЦелевогоФинансирования : Булево
РезервПереоценкиАмортизации : Число 15, 2
РезервПереоценкиАмортизацииРегл : Число 15, 2
РезервПереоценкиСтоимости : Число 15, 2
РезервПереоценкиСтоимостиРегл : Число 15, 2
СобытиеМодернизации : Справочник.Событие ОС
СобытиеПринятияКУчету : Справочник.Событие ОС
СпециальныйКоэффициентНУ : Число 5, 2
СпособПоступления : Способы поступления активов
СрокИспользованияБУ : Число 4, 0
СрокИспользованияНУ : Число 4, 0
СрокИспользованияНУДо2009 : Число 4, 0
СрокИспользованияУУ : Число 10, 0
СтатьяДоходов : Статьи доходов
СтатьяРасходовАмортизационнойПремии : Статья расходов
СтатьяРасходовБУ : Статья расходов
СтатьяРасходовНалог : Статья расходов
СтатьяРасходовУУ : Статья расходов
СтоимостьДляВычисленияАмортизации : Число 15, 2
СуммаКапитальныхВложенийВключаемыхВРасходыНУ : Число 15, 2
ТекущаяСтоимостьБУ : Число 15, 2
ТекущаяСтоимостьБУЦФ : Число 15, 2
ТекущаяСтоимостьНУ : Число 15, 2
ТекущаяСтоимостьНУЦФ : Число 15, 2
ТекущаяСтоимостьПР : Число 15, 2
ТекущаяСтоимостьПРЦФ : Число 15, 2
ТекущаяСтоимостьУУ : Число 15, 2
..Табличная часть \n НМА..
АмортизацияДо2009 : Число 15, 2
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
АналитикаРасходовБУ : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаРасходовУУ : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ВидОбъектаУчета : Виды объектов учета НМА
ГруппаФинансовогоУчета : Справочник.Группа финансового учета внеоборотных активов
ДатаПринятияКУчетуБУ : Дата
ДатаПринятияКУчетуУУ : Дата
ДатаПриобретения : Дата
ЕстьРезервПереоценки : Булево
ЕстьРезервПереоценкиРегл : Булево
КоэффициентБУ : Число 3, 2
КоэффициентУскоренияУУ : Число 4, 3
ЛиквидационнаяСтоимость : Число 15, 2
МетодНачисленияАмортизацииБУ : Способы начисления амортизации нематериальных активов
МетодНачисленияАмортизацииНУ : Методы начисления амортизации
МетодНачисленияАмортизацииУУ : Способы начисления амортизации нематериальных активов
НакопленнаяАмортизацияБУ : Число 15, 2
НакопленнаяАмортизацияБУЦФ : Число 15, 2
НакопленнаяАмортизацияВР : Число 15, 2
НакопленнаяАмортизацияНУ : Число 15, 2
НакопленнаяАмортизацияНУЦФ : Число 15, 2
НакопленнаяАмортизацияПР : Число 15, 2
НакопленнаяАмортизацияПРЦФ : Число 15, 2
НакопленнаяАмортизацияУУ : Число 15, 2
НачислятьАмортизациюБУ : Булево
НачислятьАмортизациюНУ : Булево
НачислятьАмортизациюУУ : Булево
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
ОбъемНаработки : Число 15, 3
ОрганизацияПолучательРасходов : Справочник.Организация
ПервоначальнаяСтоимостьБУ : Число 15, 2
ПервоначальнаяСтоимостьНУ : Число 15, 2
ПервоначальнаяСтоимостьОтличается : Булево
ПервоначальнаяСтоимостьУУ : Число 15, 2
ПередаватьРасходыВДругуюОрганизацию : Булево
ПорядокУчетаБУ : Порядок учета стоимости внеоборотных активов
ПорядокУчетаНУ : Порядок учета стоимости внеоборотных активов
ПорядокУчетаУУ : Порядок учета стоимости внеоборотных активов
ПрименениеЦелевогоФинансирования : Булево
РезервПереоценкиАмортизации : Число 15, 2
РезервПереоценкиАмортизацииРегл : Число 15, 2
РезервПереоценкиСтоимости : Число 15, 2
РезервПереоценкиСтоимостиРегл : Число 15, 2
СпециальныйКоэффициентНУ : Число 6, 2
СпособПоступления : Способы поступления активов
СрокИспользованияБУ : Число 4, 0
СрокИспользованияНУ : Число 4, 0
СрокИспользованияНУДо2009 : Число 4, 0
СрокИспользованияУУ : Число 4, 0
СтатьяДоходов : Статьи доходов
СтатьяРасходовБУ : Статья расходов
СтатьяРасходовУУ : Статья расходов
ТекущаяСтоимостьБУ : Число 15, 2
ТекущаяСтоимостьБУЦФ : Число 15, 2
ТекущаяСтоимостьВР : Число 15, 2
ТекущаяСтоимостьНУ : Число 15, 2
ТекущаяСтоимостьНУЦФ : Число 15, 2
ТекущаяСтоимостьПР : Число 15, 2
ТекущаяСтоимостьПРЦФ : Число 15, 2
ТекущаяСтоимостьУУ : Число 15, 2
..Табличная часть \n АрендованныеОС..
ОсновноеСредство : Справочник.Объект эксплуатации
ДатаПринятияКУчету : Дата
ЗалоговаяСтоимость : Число 15, 2
ДоговорЛизинга : Справочник.Договор лизинга
..Табличная часть \n РасчетыПоДоговорамЛизинга..
ДоговорЛизинга : Справочник.Договор лизинга
ТипЗадолженности : Типы начислений по лизингу
СчетУчета : Счет бухгалтерского учета
Сумма : Число 15, 2
СуммаРегл : Число 15, 2
СальдоДебетовое : Булево
ДокументАванса : Документ.Списание безналичных ДС
..Табличная часть \n ПрочиеРасходы..
ВнеоборотныйАктив : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
СтатьяРасходов : Статья расходов
Сумма : Число 15, 2
СуммаНДС : Число 15, 2
СуммаРегл : Число 15, 2
СуммаПР : Число 15, 2
СуммаВР : Число 15, 2
ИдентификаторСтроки : Строка
НаправлениеДеятельности : Справочник.Направление деятельности
Подразделение : Справочник.Подразделение
..Движения..
ПараметрыАмортизацииОСБухгалтерскийУчет : РегистрСведений
МестонахождениеОСБухгалтерскийУчет : РегистрСведений
ПараметрыАмортизацииОСУУ : РегистрСведений
ПорядокУчетаНМА : РегистрСведений
ПорядокУчетаНМАУУ : РегистрСведений
ПараметрыАмортизацииОСНалоговыйУчет : РегистрСведений
ПрочиеРасходы : Остатки
СобытияОСОрганизаций : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ПараметрыАмортизацииОСБУ : РегистрСведений
ОтражениеДокументовВРеглУчете : РегистрСведений
ПервоначальныеСведенияОС : РегистрСведений
ПараметрыЦелевогоФинансированияНМА : РегистрСведений
СпособыОтраженияРасходовПоАмортизацииОСБухгалтерскийУчет : РегистрСведений
ПервоначальныеСведенияОСБухгалтерскийУчет : РегистрСведений
НачислениеАмортизацииНМАСпециальныйКоэффициентНалоговыйУчет : РегистрСведений
ПорядокУчетаОСБУ : РегистрСведений
ПараметрыЦелевогоФинансированияОС : РегистрСведений
ПервоначальныеСведенияНМА : РегистрСведений
ГрафикиАмортизацииОСБухгалтерскийУчет : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
СтоимостьНМА : Остатки
Хозрасчетный : РегистрБухгалтерии
ПорядокУчетаНМАБУ : РегистрСведений
ОтражениеДокументовВМеждународномУчете : РегистрСведений
СостоянияОСОрганизаций : РегистрСведений
АмортизацияНМА : Остатки
Международный : РегистрБухгалтерии
НачислениеАмортизацииОСБухгалтерскийУчет : РегистрСведений
МестонахождениеОС : РегистрСведений
ПорядокУчетаОСУУ : РегистрСведений
СчетаБухгалтерскогоУчетаОС : РегистрСведений
ПараметрыАмортизацииНМАБУ : РегистрСведений
МестоУчетаНМА : РегистрСведений
ПорядокУчетаОС : РегистрСведений
АмортизацияОС : Остатки
НачислениеАмортизацииОССпециальныйКоэффициентНалоговыйУчет : РегистрСведений
СпособыОтраженияРасходовПоИмущественнымНалогам : РегистрСведений
ПервоначальныеСведенияОСНалоговыйУчет : РегистрСведений
ПараметрыАмортизацииНМАУУ : РегистрСведений
СтоимостьОС : Остатки
НачислениеАмортизацииОСНалоговыйУчет : РегистрСведений
}
@enduml
