@startuml ИсходящаяСправкаОЗаработкеДляРасчетаПособий
'!include templates.wsd
'..\include templates.wsd
class Документ.ИсходящаяСправкаОЗаработкеДляРасчетаПособий as "Исходящая справка для расчета пособий" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ГодС : Число 4, 0
ГодПо : Число 4, 0
Фамилия : Строка
Имя : Строка
Отчество : Строка
СтраховойНомерПФР : Строка
АдресПоПрописке : Строка
ВидДокумента : Справочник.Вид документа физических лиц
СерияДокумента : Строка
НомерДокумента : Строка
КемВыданДокумент : Строка
ДатаВыдачиДокумента : Дата
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ГлавныйБухгалтер : Справочник.Физическое лицо
НаименованиеТерриториальногоОрганаФСС : Строка
РегистрационныйНомерФСС : Строка
ДополнительныйКодФСС : Строка
КодПодчиненностиФСС : Строка
ТелефонОрганизации : Строка
УдалитьРуководитель : Строка
УдалитьДолжностьРуководителя : Строка
УдалитьГлавныйБухгалтер : Строка
УдалитьПериодРаботыПо : Дата
УдалитьПериодРаботыС : Дата
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ДанныеОЗаработке..
РасчетныйГод : Число 4, 0
Заработок : Число 15, 2
УдалитьДнейБолезниУходаЗаДетьми : Число 7, 2
ИдентификаторСтрокиФикс : Число 5, 0
..Табличная часть \n ПериодыРаботы..
ПериодРаботыС : Дата
ПериодРаботыПо : Дата
..Табличная часть \n ДниБолезниУходаЗаДетьми..
Дни : Число 5, 0
ПериодС : Дата
ПериодПо : Дата
НаименованиеПериода : Строка
ИдентификаторСтрокиФикс : Число 5, 0
..Табличная часть \n ФиксацияИзменений..
ИмяРеквизита : Строка
Путь : Строка
ИдентификаторСтроки : Число 5, 0
}
@enduml
