@startuml СписаниеОС
'!include templates.wsd
'..\include templates.wsd
class Документ.СписаниеОС as "Списание ОС (2.2)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ПричинаСписания : Справочник.Причина списания ОС
СобытиеОС : Справочник.Событие ОС
Ответственный : Справочник.Пользователь
Комментарий : Строка
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
СчетВыбытияОС : Счет бухгалтерского учета
ЧастичнаяЛиквидация : Булево
ДокументОснование : Документ.Инвентаризация ОС
ДокументНаОсновании : Булево
..Табличная часть \n ОС..
ОсновноеСредство : Справочник.Объект эксплуатации
СуммаСписанияБУ : Число 15, 2
СуммаСписанияНУ : Число 15, 2
СуммаСписанияПР : Число 15, 2
СуммаСписанияВР : Число 15, 2
..Табличная часть \n ПриходуемыеМЦ..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Количество : Число 15, 3
..Табличная часть \n НачисленнаяАмортизация..
ОбъектУчета : Справочник.Объект эксплуатации
Подразделение : Справочник.Подразделение
СуммаБУ : Число 15, 2
СуммаНУ : Число 15, 2
СуммаПР : Число 15, 2
СуммаВР : Число 15, 2
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ЭтоАмортизационнаяПремия : Булево
ДокументАмортизационнойПремии : Документ.Принятие к учету ОС\rДокумент.Модернизация ОС
ПередаватьРасходыВДругуюОрганизацию : Булево
ОрганизацияПолучательРасходов : Справочник.Организация
СчетПередачиРасходов : Счет бухгалтерского учета
ЭтоЦелевыеСредства : Булево
НаправлениеДеятельности : Справочник.Направление деятельности
..Движения..
ПараметрыАмортизацииОСБухгалтерскийУчет : РегистрСведений
ПрочиеДоходы : Остатки
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
СобытияОСОрганизаций : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
СостоянияОСОрганизаций : РегистрСведений
Международный : РегистрБухгалтерии
НачислениеАмортизацииОСБухгалтерскийУчет : РегистрСведений
ВыручкаИСебестоимостьПродаж : Обороты
НачислениеАмортизацииОСНалоговыйУчет : РегистрСведений
}
@enduml
