@startuml ВыработкаНМА
'!include templates.wsd
'..\include templates.wsd
class Документ.ВыработкаНМА as "Выработка НМА" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Комментарий : Строка
Ответственный : Справочник.Пользователь
..Табличная часть \n НМА..
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
Количество : Число 15, 3
..Движения..
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
Международный : РегистрБухгалтерии
ВыработкаНМА : Обороты
}
@enduml
