@startuml УдалитьФормированиеСоставаБригады
'!include templates.wsd
'..\include templates.wsd
class Документ.УдалитьФормированиеСоставаБригады as "(не используется) Формирование состава бригады" <<Документы>>
{
..Реквизиты..
Подразделение : Справочник.Подразделение
Бригада : Справочник.Бригады
НачалоПериода : Дата
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Физическое лицо
НормативныйКТУ : Число 5, 2
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
