@startuml ПриобретениеТоваровУслуг
'!include templates.wsd
'..\include templates.wsd
class Документ.ПриобретениеТоваровУслуг as "Приобретение товаров и услуг" <<Документы>>
{
..Реквизиты..
Валюта : Справочник.Валюта
Партнер : Справочник.Партнер
ХозяйственнаяОперация : Хозяйственные операции
Подразделение : Справочник.Подразделение
Склад : Справочник.Склад (складская территория)
Контрагент : Справочник.Контрагент
СуммаДокумента : Число 15, 2
СуммаВзаиморасчетовПоЗаказу : Число 15, 2
Менеджер : Справочник.Пользователь
ЗаказПоставщику : Документ.Заказ поставщику
ПодотчетноеЛицо : Справочник.Физическое лицо
ЦенаВключаетНДС : Булево
ВалютаВзаиморасчетов : Справочник.Валюта
Комментарий : Строка
ДатаПлатежа : Дата
ЗакупкаПодДеятельность : Типы налогообложения НДС
ФормаОплаты : Формы оплаты
Согласован : Булево
НалогообложениеНДС : Типы налогообложения НДС
СуммаВзаиморасчетов : Число 15, 2
БанковскийСчетОрганизации : Справочник.Банковский счет организации
НомерВходящегоДокумента : Строка
ДатаВходящегоДокумента : Дата
Грузоотправитель : Справочник.Контрагент
БанковскийСчетКонтрагента : Справочник.Банковский счет
БанковскийСчетГрузоотправителя : Справочник.Банковский счет
Сделка : Справочник.Сделка с клиентом
Принял : Справочник.Физическое лицо
ПринялДолжность : Строка
ПоступлениеПоЗаказам : Булево
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
РегистрироватьЦеныПоставщика : Булево
Договор : Справочник.Договор с контрагентом
Автор : Справочник.Пользователь
Руководитель : Справочник.Лицо с правом подписи
ПорядокРасчетов : Детализация расчетов
ВернутьМногооборотнуюТару : Булево
ДатаВозвратаМногооборотнойТары : Дата
СостояниеЗаполненияМногооборотнойТары : Состояния заполнения многооборотной тары
ТребуетсяЗалогЗаТару : Булево
ДопоступлениеПоДокументу : Документ.Приобретение товаров и услуг\rДокумент.Возврат товаров поставщику
НазначениеАванса : Строка
КоличествоДокументов : Строка
КоличествоЛистов : Строка
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
СпособДоставки : Способы доставки
ПеревозчикПартнер : Справочник.Партнер
ЗонаДоставки : Справочник.Зоны доставки
ВремяДоставкиС : Дата
ВремяДоставкиПо : Дата
АдресДоставки : Строка
АдресДоставкиЗначенияПолей : Строка
ДополнительнаяИнформацияПоДоставке : Строка
АдресДоставкиПеревозчика : Строка
АдресДоставкиПеревозчикаЗначенияПолей : Строка
ОсобыеУсловияПеревозки : Булево
ОсобыеУсловияПеревозкиОписание : Строка
НаправлениеДеятельности : Справочник.Направление деятельности
УдалитьТоварноТранспортнаяНакладнаяЕГАИС : Документ.Товарно-транспортная накладная ЕГАИС (входящая)
ЕстьАлкогольнаяПродукция : Булево
Соглашение : Справочник.Соглашение об условиях закупок
Организация : Справочник.Организация
Курс : Число 10, 4
Кратность : Число 10, 0
ПорядокОплаты : Порядок оплаты
ЕстьМаркируемаяПродукцияГИСМ : Булево
ЕстьКиЗГИСМ : Булево
ВариантПриемкиТоваров : Варианты приемки товаров
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
НоменклатураПоставщика : Справочник.Номенклатура поставщика
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Цена : Число 15, 2
ВидЦеныПоставщика : Справочник.Вид цены поставщика
ПроцентРучнойСкидки : Число 5, 2
СуммаРучнойСкидки : Число 15, 2
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
КодСтроки : Число 10, 0
НомерГТД : Справочник.Номер ГТД
Склад : Справочник.Склад (складская территория)
ЗаказПоставщику : Документ.Заказ поставщику
УдалитьНомерСтрокиДокументаПоставщика : Число 5, 0
Сертификат : Строка
НомерПаспорта : Строка
СтатусУказанияСерий : Число 2, 0
УдалитьСтатусУказанияСерийНаСкладах : Число 2, 0
УдалитьСтатусУказанияСерийТоварыУПартнеров : Число 2, 0
Сделка : Справочник.Сделка с клиентом
СуммаВзаиморасчетов : Число 15, 2
СуммаНДСВзаиморасчетов : Число 15, 2
ВидЗапасов : Справочник.Вид запасов
ИдентификаторСтроки : Строка
УдалитьАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
УдалитьАналитикаУчетаНоменклатурыТоварыУПартнеров : Справочник.Ключ аналитики учета номенклатуры
Подразделение : Справочник.Подразделение
СписатьНаРасходы : Булево
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n РасшифровкаПлатежа..
Заказ : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
Сумма : Число 15, 2
ВалютаВзаиморасчетов : Справочник.Валюта
СуммаВзаиморасчетов : Число 15, 2
..Табличная часть \n Серии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Склад : Справочник.Склад (складская территория)
..Табличная часть \n ВидыЗапасов..
ИдентификаторСтроки : Строка
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
УдалитьАналитикаУчетаНоменклатурыТоварыУПартнеров : Справочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
ЗаказПоставщику : Документ.Заказ поставщику
ВидЗапасовПолучателя : Справочник.Вид запасов
Цена : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
СуммаНДСВзаиморасчетов : Число 15, 2
СуммаРучнойСкидки : Число 15, 2
..Движения..
ДенежныеСредстваУПодотчетныхЛиц : Остатки
ПрочиеДоходы : Остатки
ДвиженияСерийТоваров : Обороты
ТоварыУПартнеров : Остатки
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ЦеныНоменклатурыПоставщиков : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ДвиженияКонтрагентДоходыРасходы : Обороты
ДвиженияДенежныеСредстваКонтрагент : Обороты
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНОСиНМА : Остатки
РасходыПриУСНМатериалы : Остатки
РасходыПриУСН : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
РасчетыСПоставщиками : Остатки
Международный : РегистрБухгалтерии
Закупки : Обороты
ДвижениеТоваров : Обороты
РасходыПриУСНТовары : Остатки
НДСЗаписиКнигиПродаж : Обороты
ОбеспечениеЗаказовРаботами : Остатки
РасчетыСПоставщикамиПоДокументам : Остатки
ДвиженияДенежныеСредстваДоходыРасходы : Обороты
КнигаУчетаДоходовИРасходов : Обороты
ТоварыКОформлениюЗаявленийОВвозе : Остатки
МатериалыИРаботыВПроизводстве : Остатки
ВыручкаИСебестоимостьПродаж : Обороты
ДвиженияКонтрагентКонтрагент : Обороты
СвободныеОстатки : Остатки
ТоварыКОформлениюТаможенныхДеклараций : Остатки
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
ПринятаяВозвратнаяТара : Остатки
ГрафикПоступленияТоваров : Остатки
ЗаказыПоставщикам : Остатки
ПартииПроизводственныхЗатрат : Остатки
ТоварыКПоступлению : Остатки
}
@enduml
