@startuml ПередачаДавальцу
'!include templates.wsd
'..\include templates.wsd
class Документ.ПередачаДавальцу as "Передача давальцу" <<Документы>>
{
..Реквизиты..
БанковскийСчетКонтрагента : Справочник.Банковский счет
ДатаРаспоряжения : Дата
ЗаказДавальца : Документ.Заказ давальца
Организация : Справочник.Организация
Контрагент : Справочник.Контрагент
Менеджер : Справочник.Пользователь
СуммаДокумента : Число 15, 2
Партнер : Справочник.Партнер
Подразделение : Справочник.Подразделение
Склад : Справочник.Склад (складская территория)
Согласован : Булево
Комментарий : Строка
Отпустил : Справочник.Физическое лицо
ОтпустилДолжность : Строка
ПередачаПоЗаказам : Булево
Договор : Справочник.Договор с контрагентом
Автор : Справочник.Пользователь
КонтактноеЛицо : Справочник.Контактное лицо
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
ВидыЗапасовУказаныВручную : Булево
ХозяйственнаяОперация : Хозяйственные операции
Сделка : Справочник.Сделка с клиентом
АдресДоставкиЗначенияПолей : Строка
ПеревозчикПартнер : Справочник.Партнер
СпособДоставки : Способы доставки
ДополнительнаяИнформацияПоДоставке : Строка
АдресДоставки : Строка
УдалитьПорядокРасчетов : Детализация расчетов
Грузоотправитель : Справочник.Контрагент
Грузополучатель : Справочник.Контрагент
ДоверенностьВыдана : Строка
ДоверенностьДата : Дата
ДоверенностьЛицо : Строка
ДоверенностьНомер : Строка
БанковскийСчетГрузоотправителя : Справочник.Банковский счет
БанковскийСчетГрузополучателя : Справочник.Банковский счет
БанковскийСчетОрганизации : Справочник.Банковский счет организации
Основание : Строка
ОснованиеДата : Дата
ОснованиеНомер : Строка
ВидЦены : Справочник.Вид цены
Валюта : Справочник.Валюта
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
КодСтроки : Число 10, 0
КлючСвязи : Число 10, 0
Склад : Справочник.Склад (складская территория)
СтатусУказанияСерий : Число 2, 0
ЗаказДавальца : Документ.Заказ давальца
СрокПоставки : Число 10, 0
ИдентификаторСтроки : Строка
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
Серия : Справочник.Серия номенклатуры
Цена : Число 15, 2
Сумма : Число 15, 2
..Табличная часть \n Серии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Склад : Справочник.Склад (складская территория)
..Табличная часть \n ВидыЗапасов..
ВидЗапасов : Справочник.Вид запасов
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ИдентификаторСтроки : Строка
ЗаказДавальца : Документ.Заказ давальца
КодСтроки : Число 10, 0
НомерГТД : Справочник.Номер ГТД
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ТоварыКОтгрузке : Остатки
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ПартииРасходовНаСебестоимостьТоваров : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ЗаказыКлиентов : Остатки
Международный : РегистрБухгалтерии
ТоварыОрганизаций : Остатки
ПартииПроизводственныхЗатрат : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
