@startuml КорректировкаВидаДеятельностиНДС
'!include templates.wsd
'..\include templates.wsd
class Документ.КорректировкаВидаДеятельностиНДС as "Корректировка вида деятельности НДС" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Склад : Справочник.Склад (складская территория)
Комментарий : Строка
ВидыЗапасовУказаныВручную : Булево
НовоеНалогообложениеНДС : Типы налогообложения НДС
НалогообложениеНДС : Типы налогообложения НДС
ДокументПоступления : Документ.Приобретение товаров и услуг\rДокумент.Передача товаров
СохранятьВидЗапасов : Булево
Назначение : Справочник.Назначение
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Количество : Число 15, 3
Серия : Справочник.Серия номенклатуры
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
СтатусУказанияСерий : Число 2, 0
Назначение : Справочник.Назначение
..Табличная часть \n ВидыЗапасов..
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ВидЗапасовОприходование : Справочник.Вид запасов
..Движения..
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНМатериалы : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
РасходыПриУСНТовары : Остатки
НДСЗаписиКнигиПродаж : Обороты
КнигаУчетаДоходовИРасходов : Обороты
ДвиженияНоменклатураНоменклатура : Обороты
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
ПартииЗатратНаВыпуск : Остатки
}
@enduml
