@startuml ПорчаТоваров
'!include templates.wsd
'..\include templates.wsd
class Документ.ПорчаТоваров as "Порча товаров" <<Документы>>
{
..Реквизиты..
Склад : Справочник.Склад (складская территория)
Ответственный : Справочник.Пользователь
Комментарий : Строка
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ПричинаПорчи : Строка
ВидЦены : Справочник.Вид цены
ПриходоватьТоварыПоСебестоимостиСписания : Булево
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ИсточникИнформацииОЦенахДляПечати : Источники информации о ценах для печати
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
ВидыЗапасовУказаныВручную : Булево
ПересчетТоваров : Документ.Пересчет товаров
ВидДеятельностиНДС : Типы налогообложения НДС
Валюта : Справочник.Валюта
..Табличная часть \n Товары..
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
НоменклатураОприходование : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
ХарактеристикаОприходование : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
ПодНазначение : Булево
Цена : Число 15, 2
Серия : Справочник.Серия номенклатуры
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
СтатусУказанияСерий : Число 2, 0
ВидЗапасов : Справочник.Вид запасов
АналитикаУчетаНоменклатурыОприходование : Справочник.Ключ аналитики учета номенклатуры
..Табличная часть \n ВидыЗапасов..
ВидЗапасов : Справочник.Вид запасов
АналитикаУчетаНоменклатурыОприходование : Справочник.Ключ аналитики учета номенклатуры
НомерГТД : Справочник.Номер ГТД
ВидЗапасовОприходование : Справочник.Вид запасов
Количество : Число 15, 3
УдалитьНоменклатураОприходование : Справочник.Номенклатура
УдалитьХарактеристикаОприходование : Справочник.Характеристика номенклатуры
УдалитьПодНазначение : Булево
Сумма : Число 15, 2
УдалитьАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
ИдентификаторСтроки : Строка
УдалитьСерия : Справочник.Серия номенклатуры
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ПрочиеДоходы : Остатки
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
ТоварыКОформлениюИзлишковНедостач : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ТоварыКОформлениюОтчетовКомитенту : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСН : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
Международный : РегистрБухгалтерии
НДСЗаписиКнигиПродаж : Обороты
ТоварыОрганизацийКПередаче : Остатки
КнигаУчетаДоходовИРасходов : Обороты
СвободныеОстатки : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
ПартииЗатратНаВыпуск : Остатки
}
@enduml
