@startuml УдалитьПроизвольныйЭД
'!include templates.wsd
'..\include templates.wsd
class Документ.УдалитьПроизвольныйЭД as "(не используется) Произвольный электронный документ" <<Документы>>
{
..Реквизиты..
Комментарий : Строка
Контрагент : Справочник.Контрагент
Направление : Направления ЭД
Организация : Справочник.Организация
Прочитан : Булево
СтатусДокумента : Статусы ЭД
Текст : Строка
ТребуетсяПодтверждение : Булево
ТипДокумента : Типы ЭД
ДокументОснование : Документ.Входящий электронный документ\rДокумент.Возврат товаров от клиента\rДокумент.Исходящий электронный документ\r...
ДоговорКонтрагента : Справочник.Договор с контрагентом
}
@enduml
