@startuml ПланСборкиРазборки
'!include templates.wsd
'..\include templates.wsd
class Документ.ПланСборкиРазборки as "План сборки (разборки)" <<Документы>>
{
..Реквизиты..
Склад : Справочник.Склад (складская территория)
Статус : Статусы планов
Периодичность : Периодичность
НачалоПериода : Дата
ОкончаниеПериода : Дата
Ответственный : Справочник.Пользователь
ОбновитьДополнить : Число 1, 0
ИзменитьРезультатНа : Число 5, 2
ТочностьОкругления : Число 1, 0
Сценарий : Справочник.Сценарии товарного планирования
ВидПлана : Справочник.Вид плана
ЗаполненоАвтоматически : Булево
КроссТаблица : Булево
Комментарий : Строка
ПользовательскиеНастройки : Хранилище значения
МаксимальныйКодСтрокиТовары : Число 15, 0
СтруктураНастроек : Хранилище значения
ЗаполнятьПоФормуле : Булево
ОтражаетсяВБюджетировании : Булево
СтатьяБюджетов : Справочник.Статьи бюджетов
СценарийБюджетирования : Справочник.Сценарии бюджетирования
ХозяйственнаяОперация : Хозяйственные операции
Замещающий : Булево
Назначение : Справочник.Назначение
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
Количество : Число 15, 3
КоличествоУпаковок : Число 15, 3
ДатаСборкиРазборки : Дата
ВариантКомплектации : Справочник.Вариант комплектации
Склад : Справочник.Склад (складская территория)
Подсборка : Булево
КодСтроки : Число 15, 0
КодСтрокиТовары : Число 15, 0
ДополнительныеПараметры : Хранилище значения
Отменено : Булево
Комментарий : Строка
Назначение : Справочник.Назначение
Замещен : Булево
..Табличная часть \n ПравилоЗаполнения..
Использование : Булево
Исключать : Булево
ВариантПреобразования : Варианты преобразования
Источник : Справочник.Источник данных планирования
Период : Хранилище значения
Дата : Хранилище значения
ТипЭлемента : Число 1, 0
НомерСтрокиРодитель : Число 5, 0
ПользовательскиеНастройки : Хранилище значения
ИзменитьРезультатНа : Число 5, 2
Присоединять : Булево
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ОборотыБюджетов : Обороты
ФактическиеДанныеБюджетирования : Обороты
ПланыСборкиРазборки : Обороты
ПланыПотребленияКомплектующих : Обороты
}
@enduml
