@startuml ПеремещениеОС2_4
'!include templates.wsd
'..\include templates.wsd
class Документ.ПеремещениеОС2_4 as "Перемещение ОС" <<Документы>>
{
..Реквизиты..
АдресМестонахожденияПолучателя : Строка
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаРасходовНалог : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ДокументОснование : Документ.Инвентаризация ОС
ИзменяетсяОтражениеРасходовПоНалогу : Булево
Комментарий : Строка
МОЛ : Справочник.Физическое лицо
МОЛПолучатель : Справочник.Физическое лицо
НачислениеАмортизации : Число 1, 0
Организация : Справочник.Организация
ОрганизацияПолучатель : Справочник.Организация
Ответственный : Справочник.Пользователь
ОтражатьВРеглУчете : Булево
ОтражатьВУпрУчете : Булево
Подразделение : Справочник.Подразделение
ПодразделениеПолучатель : Справочник.Подразделение
СтатьяРасходов : Статья расходов
СтатьяРасходовНалог : Статья расходов
ХозяйственнаяОперация : Хозяйственные операции
..Табличная часть \n ОС..
ОсновноеСредство : Справочник.Объект эксплуатации
..Движения..
ПараметрыАмортизацииОСБухгалтерскийУчет : РегистрСведений
МестонахождениеОСБухгалтерскийУчет : РегистрСведений
ПараметрыАмортизацииОСУУ : РегистрСведений
ПараметрыАмортизацииОСНалоговыйУчет : РегистрСведений
СобытияОСОрганизаций : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ПараметрыАмортизацииОСБУ : РегистрСведений
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
ПервоначальныеСведенияОС : РегистрСведений
СпособыОтраженияРасходовПоАмортизацииОСБухгалтерскийУчет : РегистрСведений
ПервоначальныеСведенияОСБухгалтерскийУчет : РегистрСведений
НачислениеАмортизацииНМАСпециальныйКоэффициентНалоговыйУчет : РегистрСведений
ПорядокУчетаОСБУ : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
СостоянияОСОрганизаций : РегистрСведений
Международный : РегистрБухгалтерии
НачислениеАмортизацииОСБухгалтерскийУчет : РегистрСведений
МестонахождениеОС : РегистрСведений
ПорядокУчетаОСУУ : РегистрСведений
СчетаБухгалтерскогоУчетаОС : РегистрСведений
АмортизацияОС : Остатки
СпособыОтраженияРасходовПоИмущественнымНалогам : РегистрСведений
ПервоначальныеСведенияОСНалоговыйУчет : РегистрСведений
СтоимостьОС : Остатки
НачислениеАмортизацииОСНалоговыйУчет : РегистрСведений
}
@enduml
