@startuml ЗаказНаПеремещение
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаказНаПеремещение as "Заказ на перемещение" <<Документы>>
{
..Реквизиты..
ДлительностьПеремещения : Число 3, 0
ЖелаемаяДатаПоступления : Дата
Комментарий : Строка
МаксимальныйКодСтроки : Число 10, 0
Организация : Справочник.Организация
ОрганизацияПолучатель : Справочник.Организация
Ответственный : Справочник.Пользователь
Подразделение : Справочник.Подразделение
Сделка : Справочник.Сделка с клиентом
СкладОтправитель : Справочник.Склад (складская территория)
СкладПолучатель : Справочник.Склад (складская территория)
Статус : Статусы внутренних заказов
ХозяйственнаяОперация : Хозяйственные операции
Назначение : Справочник.Назначение
ДокументОснование : Документ.Внутреннее потребление товаров\rДокумент.Приобретение товаров и услуг\rДокумент.Заказ материалов в производство\r...
СостояниеЗаполненияМногооборотнойТары : Состояния заполнения многооборотной тары
СпособДоставки : Способы доставки
ПеревозчикПартнер : Справочник.Партнер
ЗонаДоставки : Справочник.Зоны доставки
ВремяДоставкиС : Дата
ВремяДоставкиПо : Дата
АдресДоставкиПеревозчика : Строка
АдресДоставкиЗначенияПолей : Строка
АдресДоставкиПеревозчикаЗначенияПолей : Строка
ДополнительнаяИнформацияПоДоставке : Строка
АдресДоставки : Строка
ОсобыеУсловияПеревозки : Булево
ОсобыеУсловияПеревозкиОписание : Строка
НаправлениеДеятельности : Справочник.Направление деятельности
ИспользоватьДлительностьПеремещения : Булево
ОбосабливатьПоНазначениюЗаказа : Булево
ВариантПриемкиТоваров : Варианты приемки товаров
..Табличная часть \n Товары..
НачалоОтгрузки : Дата
ОкончаниеПоступления : Дата
Количество : Число 15, 3
КоличествоУпаковок : Число 15, 3
Номенклатура : Справочник.Номенклатура
Упаковка : Справочник.Упаковка
Характеристика : Справочник.Характеристика номенклатуры
Отменено : Булево
КодСтроки : Число 10, 0
ВариантОбеспечения : Варианты обеспечения
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
..Движения..
ТоварыКОтгрузке : Остатки
ГрафикОтгрузкиТоваров : Остатки
ФактическиеДанныеБюджетирования : Обороты
ЗаказыНаПеремещение : Остатки
ОбеспечениеЗаказов : Остатки
ДвижениеТоваров : Обороты
СвободныеОстатки : Остатки
ГрафикПоступленияТоваров : Остатки
ТоварыКПоступлению : Остатки
}
@enduml
