@startuml ПеремещениеОСМеждународныйУчет
'!include templates.wsd
'..\include templates.wsd
class Документ.ПеремещениеОСМеждународныйУчет as "Перемещение ОС (международный учет)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ПодразделениеПолучатель : Справочник.Подразделение
Ответственный : Справочник.Пользователь
Комментарий : Строка
ДокументОснование : Документ.Перемещение ОС
..Табличная часть \n ОсновныеСредства..
ОсновноеСредство : Справочник.Объект эксплуатации
..Движения..
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ФактическиеДанныеБюджетирования : Обороты
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
ВыручкаИСебестоимостьПродаж : Обороты
ОсновныеСредстваМеждународныйУчет : РегистрСведений
}
@enduml
