@startuml ЛимитыРасходаДенежныхСредств
'!include templates.wsd
'..\include templates.wsd
class Документ.ЛимитыРасходаДенежныхСредств as "Лимиты расхода денежных средств" <<Документы>>
{
..Реквизиты..
Период : Дата
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Лимиты..
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
ЕстьЛимит : Булево
Сумма : Число 15, 2
..Движения..
ЛимитыРасходаДенежныхСредств : Обороты
}
@enduml
