@startuml ПачкаДокументовСПВ_1
'!include templates.wsd
'..\include templates.wsd
class Документ.ПачкаДокументовСПВ_1 as "Пачка документов СПВ-1" <<Документы>>
{
..Реквизиты..
ОтчетныйПериод : Дата
Организация : Справочник.Организация
КатегорияЗастрахованныхЛиц : Категории застрахованных лиц для ПФР
ТипСведенийСЗВ : Типы сведений СЗВ
НомерПачки : Число 5, 0
ИмяФайлаДляПФР : Строка
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ФайлСформирован : Булево
ДокументПринятВПФР : Булево
ОкончаниеОтчетногоПериода : Дата
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Физическое лицо
СтраховойНомерПФР : Строка
Фамилия : Строка
Имя : Строка
Отчество : Строка
НачисленоСтраховая : Число 15, 2
УплаченоСтраховая : Число 15, 2
НачисленоНакопительная : Число 15, 2
УплаченоНакопительная : Число 15, 2
ДатаСоставления : Дата
..Табличная часть \n ЗаписиОСтаже..
Сотрудник : Справочник.Физическое лицо
НомерОсновнойЗаписи : Число 2, 0
НомерДополнительнойЗаписи : Число 2, 0
ДатаНачалаПериода : Дата
ДатаОкончанияПериода : Дата
ОсобыеУсловияТруда : Справочник.Особое условие труда
УдалитьОсобыеУсловияТруда : Справочник.(не используется) Особые условия труда ПФР
КодПозицииСписка : Справочник.Льготная профессия (ПФР)
ОснованиеИсчисляемогоСтажа : Справочник.Основание для исчисления стажа
УдалитьОснованиеИсчисляемогоСтажа : Справочник.(не используется) Основания для исчисления стажа
ПервыйПараметрИсчисляемогоСтажа : Число 3, 0
ВторойПараметрИсчисляемогоСтажа : Число 2, 0
ТретийПараметрИсчисляемогоСтажа : Справочник.Доп. сведение для исчисления стажа
УдалитьТретийПараметрИсчисляемогоСтажа : Справочник.(не используется) Доп. сведения для исчисления стажа
ОснованиеВыслугиЛет : Справочник.Основание для досрочной пенсии
УдалитьОснованиеВыслугиЛет : Справочник.(не используется) Основания для досрочной пенсии
ПервыйПараметрВыслугиЛет : Число 4, 0
ВторойПараметрВыслугиЛет : Число 4, 0
ТретийПараметрВыслугиЛет : Число 5, 2
ТерриториальныеУсловия : Справочник.Территориальное условие
УдалитьТерриториальныеУсловия : Справочник.(не используется) Территориальные условия
ПараметрТерриториальныхУсловий : Число 5, 2
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
}
@enduml
