@startuml ТТНВходящаяЕГАИС
'!include templates.wsd
'..\include templates.wsd
class Документ.ТТНВходящаяЕГАИС as "Товарно-транспортная накладная ЕГАИС (входящая)" <<Документы>>
{
..Реквизиты..
ВидОперации : Виды операций ТТН ЕГАИС (входящей)
Организация : Справочник.Организация
ТорговыйОбъект : Справочник.Партнер\rСправочник.Склад (складская территория)
Идентификатор : Строка
ИдентификаторЕГАИС : Строка
УдалитьСтатусОбработки : Статусы обработки ТТН ЕГАИС (входящей)
ДатаРегистрацииДвижений : Дата
НомерТТН : Строка
ДатаТТН : Дата
ДатаОтгрузки : Дата
Грузоотправитель : Справочник.Организация ЕГАИС
Грузополучатель : Справочник.Организация ЕГАИС
Поставщик : Справочник.Организация ЕГАИС
Основание : Строка
Упакована : Булево
ТипДоставки : Строка
Перевозчик : Строка
Автомобиль : Строка
Прицеп : Строка
Заказчик : Строка
Водитель : Строка
ПунктПогрузки : Строка
ПунктРазгрузки : Строка
Перенаправление : Строка
Экспедитор : Строка
СуммаДокумента : Число 15, 2
Комментарий : Строка
ЕстьРасхождения : Булево
Ответственный : Справочник.Пользователь
ФорматОбмена : Форматы обмена ЕГАИС
УдалитьЕстьОшибкиПередачиЗапроса : Булево
УдалитьИдентификаторПоследнегоЗапроса : Строка
ДокументОснование : Документ.Приобретение товаров и услуг\rДокумент.Перемещение товаров\rДокумент.Возврат между организациями\r...
..Табличная часть \n Товары..
АлкогольнаяПродукция : Справочник.Алкогольная продукция ЕГАИС
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
ИдентификаторУпаковки : Строка
Количество : Число 15, 3
КоличествоФакт : Число 15, 3
Сумма : Число 15, 2
Цена : Число 17, 4
НомерПартии : Строка
ИдентификаторСтроки : Строка
Справка2 : Справочник.Справка к ТТН по форме 2
НомерСправки2Поставщика : Строка
УдалитьНомерСправки1 : Строка
УдалитьНомерСправки2 : Строка
..Движения..
ОстаткиАлкогольнойПродукцииЕГАИС : Остатки
}
@enduml
