@startuml АктОРасхожденияхПослеПриемки
'!include templates.wsd
'..\include templates.wsd
class Документ.АктОРасхожденияхПослеПриемки as "Акт о расхождениях после приемки" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Валюта : Справочник.Валюта
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
Комментарий : Строка
КонтактноеЛицо : Справочник.Контактное лицо
Соглашение : Справочник.Соглашение об условиях закупок\rСправочник.Соглашение об условиях продаж
Статус : Статусы акта о расхождениях
Менеджер : Справочник.Пользователь
НалогообложениеНДС : Типы налогообложения НДС
ЦенаВключаетНДС : Булево
ХозяйственнаяОперация : Хозяйственные операции
Договор : Справочник.Договор с контрагентом
ДополнительнаяИнформация : Строка
СпособОтраженияРасхождений : Способы отражения актов о расхождения после поступления
ТипОснованияАктаОРасхождении : Типы основания акта о расхождении
Подразделение : Справочник.Подразделение
ОснованиеДляСоставленияАкта : Строка
МестоПриемкиТовара : Строка
ДатаДоставкиТоваров : Дата
ПереченьСопроводительныхДокументов : Строка
ВызываемыйПредставительПартнера : Строка
ВидДокументаВызоваПредставителяПартнера : Строка
НомерДокументаОВызовеПредставителяПартнера : Строка
Грузоотправитель : Справочник.Контрагент
Производитель : Строка
СтраховаяКомпания : Справочник.Партнер
КонтрагентСтраховойКомпании : Справочник.Контрагент
НомерДоговораПоставки : Строка
ДатаДоговораПоставки : Дата
НомерКоммерческогоАкта : Строка
ДатаКоммерческогоАкта : Дата
НомерУдостоверенияОКачестве : Строка
ДатаУдостоверенияОКачестве : Дата
НомерВетеринарногоСвидетельства : Строка
ДатаВетеринарногоСвидетельства : Дата
НомерЖелезнодорожнойНакладной : Строка
ДатаЖелезнодорожнойНакладной : Дата
НомерКоносамента : Строка
ДатаКоносамента : Дата
СпособДоставки : Строка
НомерТранспортногоСредства : Строка
СкладОтправителяТовара : Строка
СведенияОСостоянииТранспортаПоСопроводительнымДокументам : Строка
СведенияОСостоянииТранспортаПоФакту : Строка
УсловияХраненияТовараДоВскрытияНаСкладеПолучателя : Строка
СведенияОТемпературеПриРазгрузке : Число 2, 0
СостояниеТарыИУпаковки : Строка
СодержаниеНаружнойМаркировки : Строка
ДатаВскрытияТары : Дата
ОрганизацияВзвесившаяИОпломбировавшаяТовар : Строка
ПорядокОтбораТовараДляВыборочнойПроверки : Строка
СпособОпределенияКоличества : Строка
МестоОпределенияКоличества : Строка
СведенияОбИсправностиВесоизмерительныхПриборов : Строка
ПрочиеДанные : Строка
ПодробноеОписаниеДефектов : Строка
ЗаключениеКомиссии : Строка
Приложение : Строка
ДокументУдостоверяющийПолномочияПредставителяПартнера : Строка
НомерДокументаУдостоверяющегоПолномочияПредставителяПартнера : Строка
ДатаВыдачиДокументаУдостоверяющегоПолномочияПредставителяПартнера : Дата
КоличествоЛистовПриложения : Число 2, 0
РешениеРуководителя : Строка
КладовщикПринявшийТовар : Строка
МассаБруттоПоДаннымПроизводителя : Число 15, 3
ДатаОтправленияТоваров : Дата
МассаБруттоВПунктеОтправления : Число 15, 3
МассаБруттоВПунктеНазначения : Число 15, 3
КоличествоМестПоДокументамГрузоотправителя : Число 15, 0
КоличествоМестПоФакту : Число 15, 0
МассаБруттоПоДокументамГрузоотправителя : Число 15, 3
МассаБруттоПоФакту : Число 15, 3
МассаНеттоПоДокументамГрузоотправителя : Число 15, 3
МассаНеттоПоФакту : Число 15, 3
МассаТарыПоДокументамГрузоотправителя : Число 15, 3
МассаТарыПоФакту : Число 15, 3
СтепеньЗаполненияПоДокументамГрузоотправителя : Строка
СтепеньЗаполненияПоФакту : Строка
ПредседательКомиссии : Строка
ДолжностьПредседателяКомиссии : Строка
ЧленКомиссии1 : Строка
ДолжностьЧленаКомиссии1 : Строка
ЧленКомиссии2 : Строка
ДолжностьЧленаКомиссии2 : Строка
ЧленКомиссии3 : Строка
ДолжностьЧленаКомиссии3 : Строка
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
ТемператураВТолщеМясаРыбы : Число 2, 0
ДолжностьРуководителя : Строка
ДатаДокументаОВызовеПредставителяПартнера : Дата
ПунктОтправления : Строка
ВариантПриемкиТоваров : Варианты приемки товаров
..Табличная часть \n Товары..
НоменклатураПоставщика : Справочник.Номенклатура поставщика
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ВидЦеныПоставщика : Справочник.Вид цены поставщика
Цена : Число 15, 2
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
ЗаказПоставщику : Документ.Заказ поставщику\rДокумент.Заявка на возврат товаров от клиента
КодСтроки : Число 10, 0
Склад : Справочник.Склад (складская территория)
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
ДокументОснование : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\rДокумент.Приемка товаров на хранение
ЗаполненоПоОснованию : Булево
КоличествоУпаковокПоДокументу : Число 15, 3
КоличествоПоДокументу : Число 15, 3
СуммаПоДокументу : Число 15, 2
СуммаНДСПоДокументу : Число 15, 2
СуммаСНДСПоДокументу : Число 15, 2
НомерПаспорта : Строка
Действие : Варианты действий по расхождениям в акте после приемки
КомментарийПоставщика : Строка
КомментарийМенеджера : Строка
ДокументРеализации : Документ.Реализация товаров и услуг\rДокумент.Отчет о розничных продажах
ПоВинеСтороннейКомпании : Булево
СписатьНаРасходы : Булево
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Подразделение : Справочник.Подразделение
Сделка : Справочник.Сделка с клиентом
НомерГТД : Справочник.Номер ГТД
Сертификат : Строка
..Табличная часть \n Серии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Склад : Справочник.Склад (складская территория)
КоличествоПоДокументу : Число 15, 3
ДокументОснование : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\rДокумент.Приемка товаров на хранение
ЗаполненоПоОснованию : Булево
Действие : Варианты действий по расхождениям в акте после приемки
..Табличная часть \n ПриемкаТоваров..
ДатаПрибытияВПунктНазначения : Дата
ДатаВскрытия : Дата
ДатаВыдачиОрганизациейТранспорта : Дата
ДатаДоставкиНаСкладПолучателя : Дата
ДатаНачалаРазгрузки : Дата
ДатаНачалаПриемки : Дата
ДатаПриостановленияПриемки : Дата
ДатаВозобновленияПриемки : Дата
ДатаОкончанияПриемки : Дата
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ТоварыКОтгрузке : Остатки
ДвиженияСерийТоваров : Обороты
ТоварыКОформлениюИзлишковНедостач : Остатки
ТоварыНаСкладах : Остатки
ОбеспечениеЗаказов : Остатки
ДвижениеТоваров : Обороты
СвободныеОстатки : Остатки
ТоварыКПоступлению : Остатки
}
@enduml
