@startuml ПеремещениеОС
'!include templates.wsd
'..\include templates.wsd
class Документ.ПеремещениеОС as "Перемещение ОС (2.2)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
МОЛ : Справочник.Физическое лицо
Подразделение : Справочник.Подразделение
СобытиеОС : Справочник.Событие ОС
ОрганизацияПолучатель : Справочник.Организация
МОЛПолучатель : Справочник.Физическое лицо
ПодразделениеПолучатель : Справочник.Подразделение
АдресМестонахожденияПолучателя : Строка
НачислениеАмортизации : Число 1, 0
Ответственный : Справочник.Пользователь
Комментарий : Строка
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ХозяйственнаяОперация : Хозяйственные операции (регламентированный учет)
СтатьяРасходовНалог : Статья расходов
АналитикаРасходовНалог : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ИзменяетсяОтражениеРасходовПоНалогу : Булево
ДокументОснование : Документ.Инвентаризация ОС
ДокументНаОсновании : Булево
..Табличная часть \n ОС..
ОсновноеСредство : Справочник.Объект эксплуатации
..Табличная часть \n НачисленнаяАмортизация..
ОбъектУчета : Справочник.Объект эксплуатации
Подразделение : Справочник.Подразделение
СуммаБУ : Число 15, 2
СуммаНУ : Число 15, 2
СуммаПР : Число 15, 2
СуммаВР : Число 15, 2
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ЭтоАмортизационнаяПремия : Булево
ДокументАмортизационнойПремии : Документ.Принятие к учету ОС\rДокумент.Модернизация ОС
ПередаватьРасходыВДругуюОрганизацию : Булево
ОрганизацияПолучательРасходов : Справочник.Организация
СчетПередачиРасходов : Счет бухгалтерского учета
ЭтоЦелевыеСредства : Булево
НаправлениеДеятельности : Справочник.Направление деятельности
..Движения..
ПараметрыАмортизацииОСБухгалтерскийУчет : РегистрСведений
МестонахождениеОСБухгалтерскийУчет : РегистрСведений
ПрочиеДоходы : Остатки
ПараметрыАмортизацииОСНалоговыйУчет : РегистрСведений
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
СобытияОСОрганизаций : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
СпособыОтраженияРасходовПоАмортизацииОСБухгалтерскийУчет : РегистрСведений
ПервоначальныеСведенияОСБухгалтерскийУчет : РегистрСведений
ГрафикиАмортизацииОСБухгалтерскийУчет : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
СостоянияОСОрганизаций : РегистрСведений
Международный : РегистрБухгалтерии
НачислениеАмортизацииОСБухгалтерскийУчет : РегистрСведений
СчетаБухгалтерскогоУчетаОС : РегистрСведений
НачислениеАмортизацииОССпециальныйКоэффициентНалоговыйУчет : РегистрСведений
СпособыОтраженияРасходовПоИмущественнымНалогам : РегистрСведений
ВыручкаИСебестоимостьПродаж : Обороты
ПервоначальныеСведенияОСНалоговыйУчет : РегистрСведений
НачислениеАмортизацииОСНалоговыйУчет : РегистрСведений
}
@enduml
