@startuml ПостоянноеУдержаниеВПользуТретьихЛиц
'!include templates.wsd
'..\include templates.wsd
class Документ.ПостоянноеУдержаниеВПользуТретьихЛиц as "Постоянное удержание в пользу третьих лиц" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Удержание : Удержание
ДатаНачала : Дата
ДатаОкончания : Дата
Действие : Действия с удержаниями
ДокументОснование : Документ.Постоянное удержание в пользу третьих лиц
Контрагент : Справочник.Контрагент
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
БухучетЗаданВДокументе : Булево
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
УдалитьДействие : Действия с начислениями и удержаниями
УдалитьРазмер : Число 15, 2
УдалитьФизическоеЛицо : Справочник.Физическое лицо
..Табличная часть \n Удержания..
ФизическоеЛицо : Справочник.Физическое лицо
РабочееМесто : Справочник.Сотрудник
Размер : Число 15, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
..Табличная часть \n Показатели..
Показатель : Справочник.Показатель
Значение : Число 15, 5
ИдентификаторСтрокиВидаРасчета : Число 7, 0
..Движения..
БухучетПлановыхУдержаний : РегистрСведений
РабочиеМестаУдержаний : РегистрСведений
ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
ПлановыеУдержания : РегистрСведений
}
@enduml
