@startuml ЗаписьКУДиР
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаписьКУДиР as "Запись книги учета доходов и расходов (УСН)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Комментарий : Строка
Ответственный : Справочник.Пользователь
..Табличная часть \n Строки..
ДатаНомер : Строка
Содержание : Строка
Графа4 : Число 15, 2
Графа5 : Число 15, 2
Графа6 : Число 15, 2
Графа7 : Число 15, 2
НДС : Число 15, 2
ДокументВозникновенияРасходов : Документ.Внутреннее потребление товаров\rДокумент.Расходный кассовый ордер\rДокумент.Движение прочих активов и пассивов\r...
ВидРасходов : Виды расходов УСН
СтатьяРасходов : Статья расходов\rСтатья актива/пассива\rТипы налогов\r...
ДоходЕНВД : Число 15, 2
РасходЕНВД : Число 15, 2
Партия : Документ.Внутреннее потребление товаров\rДокумент.Расходный кассовый ордер\rДокумент.Движение прочих активов и пассивов\r...
..Табличная часть \n УменьшениеНалога..
ДатаНомер : Строка
ПериодНачисления : Дата
ПФР : Число 15, 2
ФСС : Число 15, 2
ФОМС : Число 15, 2
ФСС_НС : Число 15, 2
Больничные : Число 15, 2
ДобровольноеСтрахование : Число 15, 2
..Табличная часть \n Строки2..
ЭлементРасходов : Справочник.Объект эксплуатации\rСправочник.Нематериальные активы и расходы на НИОКР
ДатаОплаты : Дата
ДокументВозникновенияРасходов : Документ.Приобретение услуг и прочих активов
Графа3_ДатаВводаВЭксплуатацию : Дата
Графа4_ГосударственнаяРегистрация : Дата
Графа5_ПервоначальнаяСтоимость : Число 15, 2
Графа6_ОстаточнаяСтоимость : Число 15, 2
Графа7_СрокПолезногоИспользования : Число 15, 2
Графа8_КолКварталовВОтчетномПериоде : Число 10, 0
Графа9_КолКварталовВНалПериоде : Число 10, 0
Графа10_ДоляРасходовЗаНалПериод : Число 10, 2
Графа11_ДоляРасходовЗаКвартал : Число 10, 2
Графа12_СуммаРасходовЗаОтчетнПериод : Число 15, 2
Графа13_СуммаРасходовЗаКвартал : Число 15, 2
Графа14_РасходыПрошлыхПериодов : Число 15, 2
Графа15_ОстатокРасходов : Число 15, 2
Графа16_ДатаВыбытия : Дата
..Движения..
КнигаУчетаДоходовИРасходовРаздел2 : Обороты
ФактическиеДанныеБюджетирования : Обороты
КнигаУчетаДоходовИРасходов : Обороты
}
@enduml
