@startuml СчетФактураНаНеподтвержденнуюРеализацию0
'!include templates.wsd
'..\include templates.wsd
class Документ.СчетФактураНаНеподтвержденнуюРеализацию0 as "Счет-фактура на неподтвержденную реализацию по ставке 0%" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ДокументОснование : Документ.Первичный документ\rДокумент.Реализация товаров и услуг\rДокумент.Акт выполненных работ
КодВидаОперации : Строка
Контрагент : Справочник.Контрагент
Комментарий : Строка
СтрокаПлатежноРасчетныеДокументы : Строка
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
ИННКонтрагента : Строка
КППКонтрагента : Строка
Ответственный : Справочник.Пользователь
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
ТипЗапасов : Типы запасов
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
НомерГТД : Справочник.Номер ГТД
..Табличная часть \n ПлатежноРасчетныеДокументы..
НомерПлатежноРасчетногоДокумента : Строка
ДатаПлатежноРасчетногоДокумента : Дата
..Движения..
ОтражениеДокументовВРеглУчете : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
НДСЗаписиКнигиПродаж : Обороты
ЖурналУчетаСчетовФактур : РегистрСведений
}
@enduml
