@startuml ПланПродажПоКатегориям
'!include templates.wsd
'..\include templates.wsd
class Документ.ПланПродажПоКатегориям as "План продаж по категориям" <<Документы>>
{
..Реквизиты..
Комментарий : Строка
Подразделение : Справочник.Подразделение
Статус : Статусы планов
Периодичность : Периодичность
НачалоПериода : Дата
ОкончаниеПериода : Дата
Ответственный : Справочник.Пользователь
Сценарий : Справочник.Сценарии товарного планирования
ВидПлана : Справочник.Вид плана
ЗаполненоАвтоматически : Булево
ФорматМагазина : Справочник.Форматы магазинов
Склад : Справочник.Склад (складская территория)
ОбновитьДополнить : Число 1, 0
ИзменитьРезультатНа : Число 5, 2
ТочностьОкругления : Число 1, 0
ПользовательскиеНастройки : Хранилище значения
СтруктураНастроек : Хранилище значения
ЗаполнятьПоФормуле : Булево
ОтражаетсяВБюджетировании : Булево
СтатьяБюджетов : Справочник.Статьи бюджетов
СценарийБюджетирования : Справочник.Сценарии бюджетирования
КроссТаблица : Булево
Замещающий : Булево
Назначение : Справочник.Назначение
..Табличная часть \n ТоварныеКатегории..
ТоварнаяКатегория : Справочник.Товарные категории
РейтингПродаж : Справочник.Рейтинг продаж номенклатуры
Количество : Число 15, 3
ДатаОтгрузки : Дата
Склад : Справочник.Склад (складская территория)
ДополнительныеПараметры : Хранилище значения
Отменено : Булево
Комментарий : Строка
Назначение : Справочник.Назначение
Замещен : Булево
..Табличная часть \n ПравилоЗаполнения..
Использование : Булево
Исключать : Булево
ВариантПреобразования : Варианты преобразования
Источник : Справочник.Источник данных планирования
Период : Хранилище значения
Дата : Хранилище значения
ТипЭлемента : Число 1, 0
НомерСтрокиРодитель : Число 5, 0
ПользовательскиеНастройки : Хранилище значения
ИзменитьРезультатНа : Число 5, 2
Присоединять : Булево
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ОборотыБюджетов : Обороты
ФактическиеДанныеБюджетирования : Обороты
ПланыПродажПоКатегориям : Обороты
}
@enduml
