@startuml КадровыйПереводСписком
'!include templates.wsd
'..\include templates.wsd
class Документ.КадровыйПереводСписком as "Кадровый перевод списком" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ДатаСобытия : Дата
НачисленияУтверждены : Булево
ИсправленныйДокумент : Документ.Кадровый перевод списком
ВидДоговора : Виды договоров с сотрудниками
ОснованиеПредставителяНанимателя : Строка
БронированиеПозиции : Булево
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ИдентификаторСтрокиСотрудника : Число 7, 0
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ОбособленноеПодразделение : Справочник.Организация
ДатаОкончания : Дата
Должность : Справочник.Должность
ДолжностьПоШтатномуРасписанию : Справочник.Позиция
ВидЗанятости : Виды занятости
КоличествоСтавок : Число 22, 20
ГрафикРаботы : Справочник.График работы
ИзменитьПодразделениеИДолжность : Булево
ИзменитьТерриторию : Булево
ИзменитьГрафикРаботы : Булево
ИзменитьНачисления : Булево
ИзменитьЕжегодныеОтпуска : Булево
ИзменитьАванс : Булево
СпособРасчетаАванса : Способы расчета аванса
Аванс : Число 15, 2
ПричинаПеревода : Строка
ОснованиеПеревода : Строка
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОтношениеКЕНВД : Отношение к ЕНВД затрат на зарплату
СтатьяФинансирования : Справочник.Статья финансирования
ПорядокРасчетаСтоимостиЕдиницыВремени : Порядок расчета стоимости часа (дня) оплаты труда сотрудников
СовокупнаяТарифнаяСтавка : Число 15, 5
ВидТарифнойСтавки : Виды тарифных ставок
РазрядКатегория : Справочник.Квалификационный разряд (категория)
ИзменитьСведенияОДоговореКонтракте : Булево
СменаВидаДоговора : Булево
ТрудовойДоговорНомер : Строка
ТрудовойДоговорДата : Дата
СрочныйДоговор : Булево
СезонныйДоговор : Булево
ДатаЗавершенияТрудовогоДоговора : Дата
ОснованиеСрочногоДоговора : Справочник.Основание заключения срочного трудового договора
СрокЗаключенияДоговора : Строка
СпособПоступленияНаСлужбу : Строка
ПоступлениеНаСлужбуВпервые : Булево
ВидАктаГосоргана : Строка
ОборудованиеРабочегоМеста : Строка
ИныеУсловияДоговора : Строка
Грейд : Строка
НаПериодПереводаСохранятьЛьготныйСтажПФР : Булево
ВидСтажаПФР : Виды стажа перс. учета с 2014 года
ИзменитьЛьготы : Булево
Территория : Справочник.Территория
ДатаПрисвоения : Дата
КлассныйЧинРанг : Строка
ПКУ : Справочник.Квалификационный разряд (категория)
Решение : Строка
..Табличная часть \n Начисления..
ИдентификаторСтрокиСотрудника : Число 7, 0
Действие : Действия с начислениями и удержаниями
Начисление : Начисление
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Размер : Число 15, 2
ХарактерНачисления : Характер планового начисления
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n УправленческиеНачисления..
ИдентификаторСтрокиСотрудника : Число 7, 0
Действие : Действия с начислениями и удержаниями
Начисление : Начисление
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Размер : Число 15, 2
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n Показатели..
ИдентификаторСтрокиСотрудника : Число 7, 0
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Показатель : Справочник.Показатель
Значение : Число 15, 5
Действие : Действия с начислениями и удержаниями
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n ЕжегодныеОтпуска..
ИдентификаторСтрокиСотрудника : Число 7, 0
Действие : Действия с ежегодными отпусками
ВидЕжегодногоОтпуска : Справочник.Вид отпуска
КоличествоДнейВГод : Число 2, 0
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n Льготы..
ИдентификаторСтрокиСотрудника : Число 7, 0
Льгота : Начисление
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Размер : Число 15, 2
Действие : Действия с начислениями и удержаниями
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n КадровыйРезерв..
ИдентификаторСтрокиСотрудника : Число 7, 0
ПозицияРезерва : Строка
ВидРезерва : Строка
Действие : Строка
Статус : Состояния согласования
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
СведенияКонтрактаДоговораСотрудника : РегистрСведений
ПорядокРасчетаСтоимостиЕдиницыВремениСотрудников : РегистрСведений
ЗанятыеПозицииШтатногоРасписания : Остатки
УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников : РегистрСведений
ПКУСотрудников : РегистрСведений
ГрафикРаботыСотрудников : РегистрСведений
ПрименениеДополнительныхПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
ПлановыеАвансы : РегистрСведений
КадроваяИсторияСотрудников : РегистрСведений
ОсновныеДанныеКонтрактаДоговораСотрудника : РегистрСведений
ТерриторииСотрудников : РегистрСведений
РазрядыКатегорииСотрудников : РегистрСведений
ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
БухучетПлановыхНачислений : РегистрСведений
ПоложенныеВидыЕжегодныхОтпусков : РегистрСведений
ПараметрыПериодовСтажаПФР : РегистрСведений
ПлановыеНачисления : РегистрСведений
РеестрКадровыхПриказов : РегистрСведений
}
@enduml
