@startuml ОтменаРегистрацииЗемельныхУчастков
'!include templates.wsd
'..\include templates.wsd
class Документ.ОтменаРегистрацииЗемельныхУчастков as "Отмена регистрации земельных участков" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ОС..
ОсновноеСредство : Справочник.Объект эксплуатации
..Движения..
РегистрацияЗемельныхУчастков : РегистрСведений
}
@enduml
