@startuml ПлановаяКалькуляция2_2
'!include templates.wsd
'..\include templates.wsd
class Документ.ПлановаяКалькуляция2_2 as "Плановая калькуляция" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ПодразделениеДиспетчер : Справочник.Подразделение
ОбъектКалькуляции : Объекты калькуляции
ВидЦены : Справочник.Вид цены
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ОбъектыКалькуляции..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Объект : Документ.Этап производства\rСправочник.Ресурсная спецификация\rДокумент.Заказ на производство
Упаковка : Справочник.Упаковка
Количество : Число 10, 3
КоличествоУпаковок : Число 10, 3
..Движения..
ПлановыеМатериальныеЗатраты : Обороты
ПлановыеПрочиеЗатраты : Обороты
ПлановыеТрудозатраты : Обороты
}
@enduml
