@startuml ОтчетОРозничныхПродажах
'!include templates.wsd
'..\include templates.wsd
class Документ.ОтчетОРозничныхПродажах as "Отчет о розничных продажах" <<Документы>>
{
..Реквизиты..
Валюта : Справочник.Валюта
ВидЦены : Справочник.Вид цены
КассаККМ : Справочник.Кассы ККМ
Комментарий : Строка
НалогообложениеНДС : Типы налогообложения НДС
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
Подразделение : Справочник.Подразделение
Склад : Справочник.Склад (складская территория)
СуммаДокумента : Число 15, 2
ЦенаВключаетНДС : Булево
ПоРезультатамИнвентаризации : Булево
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
ВидыЗапасовУказаныВручную : Булево
ЕстьМаркируемаяПродукцияГИСМ : Булево
УдалитьЕстьАлкогольнаяПродукцияДляСписанияЕГАИС : Булево
КассоваяСмена : Документ.Кассовая смена
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Цена : Число 15, 2
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
ПроцентРучнойСкидки : Число 5, 2
СуммаРучнойСкидки : Число 15, 2
КоличествоУпаковокФакт : Число 15, 3
КоличествоУпаковокУчет : Число 15, 3
СтатусУказанияСерий : Число 2, 0
Партнер : Справочник.Партнер
ИдентификаторСтроки : Строка
Продавец : Справочник.Пользователь
Помещение : Справочник.Помещение
Серия : Справочник.Серия номенклатуры
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
НоменклатураНабора : Справочник.Номенклатура
ХарактеристикаНабора : Справочник.Характеристика номенклатуры
АналитикаУчетаНаборов : Справочник.Ключ аналитики учета наборов
..Табличная часть \n ОплатаПлатежнымиКартами..
ЭквайринговыйТерминал : Справочник.Эквайринговый терминал
КодАвторизации : Строка
НомерПлатежнойКарты : Строка
Сумма : Число 15, 2
ИдентификаторСтроки : Строка
..Табличная часть \n ВидыЗапасов..
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
СуммаСНДС : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
Партнер : Справочник.Партнер
ИдентификаторСтроки : Строка
Продавец : Справочник.Пользователь
СуммаРучнойСкидки : Число 15, 2
АналитикаУчетаНаборов : Справочник.Ключ аналитики учета наборов
..Табличная часть \n Серии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Помещение : Справочник.Помещение
..Табличная часть \n ПодарочныеСертификаты..
ПодарочныйСертификат : Справочник.Подарочный сертификат
Сумма : Число 15, 2
СуммаВВалютеСертификата : Число 15, 2
ИдентификаторСтроки : Строка
..Табличная часть \n НачислениеБонусныхБаллов..
Партнер : Справочник.Партнер
БонуснаяПрограммаЛояльности : Справочник.Бонусные программы лояльности
ДатаНачисления : Дата
ДатаСписания : Дата
СуммаБонусныхБаллов : Число 15, 2
..Табличная часть \n ОплатаБонуснымиБаллами..
Партнер : Справочник.Партнер
БонуснаяПрограммаЛояльности : Справочник.Бонусные программы лояльности
ДатаОплаты : Дата
СуммаБонусныхБаллов : Число 15, 2
..Движения..
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
ИсторияПодарочныхСертификатов : РегистрСведений
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ТоварыКОформлениюОтчетовКомитенту : Остатки
ДвиженияДенежныеСредстваКонтрагент : Обороты
ПодарочныеСертификаты : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНМатериалы : Остатки
ДенежныеСредстваВПути : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ДенежныеСредстваВКассахККМ : Остатки
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
РасходыПриУСНТовары : Остатки
НДСЗаписиКнигиПродаж : Обороты
ТоварыОрганизацийКПередаче : Остатки
КнигаУчетаДоходовИРасходов : Обороты
МатериалыИРаботыВПроизводстве : Остатки
ВыручкаИСебестоимостьПродаж : Обороты
СвободныеОстатки : Остатки
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
БонусныеБаллы : Остатки
ПартииПроизводственныхЗатрат : Остатки
РасчетыПоЭквайрингу : Остатки
УслугиКОформлениюОтчетовПринципалу : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
