@startuml ЭлектронноеПисьмоИсходящее
'!include templates.wsd
'..\include templates.wsd
class Документ.ЭлектронноеПисьмоИсходящее as "Электронное письмо исходящее" <<Документы>>
{
..Реквизиты..
Автор : Справочник.Пользователь
ВнутреннийЗаголовок : Строка
Важность : Варианты важности взаимодействия
ДатаОтправления : Дата
ЕстьВложения : Булево
ИдентификаторНаСервере : Строка
ИдентификаторОснования : Строка
ИдентификаторСообщения : Строка
ИдентификаторСообщенияОтправкаIMAP : Строка
ИдентификаторыОснований : Строка
Кодировка : Строка
Ответственный : Справочник.Пользователь
ОтправительПредставление : Строка
Удалить_Рассмотрено : Булево
Удалить_РассмотретьПосле : Дата
УдалитьПредмет : Справочник.Маркетинговое мероприятие\rДокумент.Исходящее электронное письмо\rДокумент.Запланированное взаимодействие\r...
СписокПолучателейКопий : Строка
СписокПолучателейПисьма : Строка
СписокПолучателейСкрытыхКопий : Строка
СтатусПисьма : Статусы исходящего электронного письма
Текст : Строка
ТекстHTML : Строка
Тема : Строка
ТипТекста : Типы текстов электронных писем
УчетнаяЗапись : Справочник.Учетная запись электронной почты
ВзаимодействиеОснование : Документ.Рассылка клиентам\rДокумент.Исходящее электронное письмо\rДокумент.Запланированное взаимодействие\r...
УведомитьОДоставке : Булево
УведомитьОПрочтении : Булево
ОтображатьТелоИсходногоПисьма : Булево
ВключатьТелоИсходногоПисьма : Булево
УдалятьПослеОтправки : Булево
Размер : Число 10, 0
Комментарий : Строка
ДатаКогдаОтправить : Дата
ДатаАктуальностиОтправки : Дата
УдалитьИдентификаторСообщенияОтправкаIMAP : Строка
..Табличная часть \n ПолучателиПисьма..
Адрес : Строка
Представление : Строка
Контакт : Справочник.Строковый контакт взаимодействий\rСправочник.Пользователь\rСправочник.Партнер\r...
..Табличная часть \n ПолучателиКопий..
Адрес : Строка
Представление : Строка
Контакт : Справочник.Строковый контакт взаимодействий\rСправочник.Пользователь\rСправочник.Партнер\r...
..Табличная часть \n ПолучателиОтвета..
Адрес : Строка
Представление : Строка
Контакт : Справочник.Строковый контакт взаимодействий\rСправочник.Пользователь\rСправочник.Партнер\r...
..Табличная часть \n ПолучателиСкрытыхКопий..
Адрес : Строка
Представление : Строка
Контакт : Справочник.Строковый контакт взаимодействий\rСправочник.Пользователь\rСправочник.Партнер\r...
..Табличная часть \n НаборыЗначенийДоступа..
НомерНабора : Число 4, 0
ЗначениеДоступа : Справочник.Статьи бюджетов\rСправочник.Вид номенклатуры\rСправочник.Номенклатура\r...
Уточнение : Справочник.Идентификатор объекта метаданных
Чтение : Булево
Изменение : Булево
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n НепринятыеВложения..
ИмяВложение : Строка
..Табличная часть \n ПисьмаВложения..
Письмо : Документ.Исходящее электронное письмо\rДокумент.Входящее электронное письмо
ПорядковыйНомерВоВложениях : Число 3, 0
}
@enduml
