@startuml СчетФактураВыданныйАванс
'!include templates.wsd
'..\include templates.wsd
class Документ.СчетФактураВыданныйАванс as "Счет-фактура выданный (аванс)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ДокументОснование : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
Контрагент : Справочник.Организация\rСправочник.Контрагент
Сумма : Число 15, 2
СуммаНДС : Число 15, 2
НомерПлатежноРасчетногоДокумента : Строка
ДатаПлатежноРасчетногоДокумента : Дата
СтрокаПлатежноРасчетныеДокументы : Строка
ВыставленВЭлектронномВиде : Булево
ДатаВыставления : Дата
КодВидаОперации : Строка
ПравилоОтбораАванса : Порядок регистрации счетов-фактур на аванс
Комментарий : Строка
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
СчетФактураОснование : Документ.Счет-фактура выданный (аванс)
Исправление : Булево
НомерИсправления : Строка
Ответственный : Справочник.Пользователь
Подразделение : Справочник.Подразделение
ИННКонтрагента : Строка
КППКонтрагента : Строка
ИдентификаторГосКонтракта : Строка
НалогообложениеНДС : Типы налогообложения НДС
..Табличная часть \n Авансы..
НоменклатураНабора : Справочник.Номенклатура
ХарактеристикаНабора : Справочник.Характеристика номенклатуры
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
ТипЗапасов : Типы запасов
Содержание : Строка
Сумма : Число 14, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 14, 2
..Движения..
ОтражениеДокументовВРеглУчете : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
НДСЗаписиКнигиПродаж : Обороты
НДСЗаписиКнигиПокупок : Обороты
ЖурналУчетаСчетовФактур : РегистрСведений
}
@enduml
