@startuml ПродлениеКонтрактаДоговора
'!include templates.wsd
'..\include templates.wsd
class Документ.ПродлениеКонтрактаДоговора as "Продление контракта, договора" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ДатаПродления : Дата
ТрудовойДоговорНомер : Строка
ТрудовойДоговорДата : Дата
СрочныйДоговор : Булево
СезонныйДоговор : Булево
ДатаЗавершенияТрудовогоДоговора : Дата
ОснованиеСрочногоДоговора : Справочник.Основание заключения срочного трудового договора
СрокЗаключенияДоговора : Строка
ОснованиеПредставителяНанимателя : Строка
ВидАктаГосоргана : Строка
ОборудованиеРабочегоМеста : Строка
ИныеУсловияДоговора : Строка
ПредставительНанимателя : Справочник.Физическое лицо
ДолжностьПредставителяНанимателя : Справочник.Должность
ИсправленныйДокумент : Документ.Продление контракта, договора
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Движения..
СведенияКонтрактаДоговораСотрудника : РегистрСведений
ОсновныеДанныеКонтрактаДоговораСотрудника : РегистрСведений
}
@enduml
