@startuml ПриказНаДоплатуДоСреднегоЗаработка
'!include templates.wsd
'..\include templates.wsd
class Документ.ПриказНаДоплатуДоСреднегоЗаработка as "Приказ на доплату до среднего заработка" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
Начисление : Начисление
Действие : Действия с начислениями и удержаниями
ДатаНачала : Дата
ДатаОкончания : Дата
РазмерДоплатыУтвержден : Булево
ИсправленныйДокумент : Документ.Приказ на доплату до среднего заработка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n НачисленияСотрудника..
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Начисление : Начисление
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Размер : Число 15, 3
..Движения..
УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников : РегистрСведений
БухучетПлановыхНачислений : РегистрСведений
ПлановыеНачисления : РегистрСведений
}
@enduml
