@startuml ВзаимозачетЗадолженности
'!include templates.wsd
'..\include templates.wsd
class Документ.ВзаимозачетЗадолженности as "Взаимозачет задолженности" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
КонтрагентДебитор : Справочник.Организация\rСправочник.Контрагент
КонтрагентКредитор : Справочник.Организация\rСправочник.Контрагент
УдалитьСуммаДокумента : Число 15, 2
УдалитьВалюта : Справочник.Валюта
Комментарий : Строка
Подразделение : Справочник.Подразделение
Ответственный : Справочник.Пользователь
Руководитель : Справочник.Лицо с правом подписи
ВидОперации : Виды операций взаимозачета задолженности
ОрганизацияКредитор : Справочник.Организация
ТипДебитора : Типы участников взаимозачета
ТипКредитора : Типы участников взаимозачета
ДокументОснование : Документ.Приобретение товаров и услуг\rДокумент.Таможенная декларация на импорт\rДокумент.Отчет комиссионера (агента) о продажах\r...
ОбъектРасчетовИнтеркампани : Справочник.Договор между организациями\rДокумент.Отчет по комиссии между организациями\rДокумент.Отчет по комиссии между организациями о списании\r...
СуммаРегл : Число 15, 2
СуммаУпр : Число 15, 2
..Табличная часть \n ДебиторскаяЗадолженность..
ТипРасчетов : Типы расчетов с партнерами
Партнер : Справочник.Партнер
Заказ : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
Сумма : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
ВалютаВзаиморасчетов : Справочник.Валюта
ИдентификаторСтроки : Строка
Организация : Справочник.Организация
СуммаРегл : Число 15, 2
СуммаУпр : Число 15, 2
..Табличная часть \n КредиторскаяЗадолженность..
ТипРасчетов : Типы расчетов с партнерами
Партнер : Справочник.Партнер
Заказ : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
Сумма : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
ВалютаВзаиморасчетов : Справочник.Валюта
ИдентификаторСтроки : Строка
Организация : Справочник.Организация
СуммаРегл : Число 15, 2
СуммаУпр : Число 15, 2
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ПрочиеДоходы : Остатки
РасчетыСКлиентами : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
РасходыПриУСНОСиНМА : Остатки
РасходыПриУСНМатериалы : Остатки
РасходыПриУСН : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
РасчетыСПоставщиками : Остатки
Международный : РегистрБухгалтерии
РасходыПриУСНТовары : Остатки
РасчетыСКлиентамиПоДокументам : Остатки
РасчетыСПоставщикамиПоДокументам : Остатки
КнигаУчетаДоходовИРасходов : Обороты
ДвиженияКонтрагентКонтрагент : Обороты
}
@enduml
