@startuml ПринятиеКУчетуОС
'!include templates.wsd
'..\include templates.wsd
class Документ.ПринятиеКУчетуОС as "Принятие к учету ОС (2.2)" <<Документы>>
{
..Реквизиты..
АдресМестонахождения : Строка
АмортизационнаяГруппа : Амортизационные группы
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаРасходовАмортизационнойПремии : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаРасходовНалог : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ВариантПримененияЦелевогоФинансирования : Варианты применения целевого финансирования
ВариантРаздельногоУчетаНДС : Варианты раздельного учета НДС
ВключитьАмортизационнуюПремиюВСоставРасходов : Булево
ГодоваяНормаАмортизацииБУ : Число 4, 2
ГрафикАмортизации : Справочник.Годовой график амортизации ОС
ГруппаОС : Группы ОС
ДокументНаОсновании : Булево
ДокументНаОснованииИнвентаризации : Булево
ДокументОснование : Документ.Инвентаризация ОС\rДокумент.Поступление предметов лизинга
КодПоОКОФ : Справочник.Элемент классификатора ОКОФ
Комментарий : Строка
КоэффициентУскоренияБУ : Число 6, 2
Местонахождение : Справочник.Подразделение
МетодНачисленияАмортизацииБУ : Способы начисления амортизации основных средств
МОЛ : Справочник.Физическое лицо
НалогообложениеНДС : Типы налогообложения НДС
НаправлениеДеятельности : Справочник.Направление деятельности
НачислятьАмортизациюБУ : Булево
НачислятьАмортизациюНУ : Булево
Организация : Справочник.Организация
ОрганизацияПолучательРасходов : Справочник.Организация
Ответственный : Справочник.Пользователь
ПередаватьРасходыВДругуюОрганизацию : Булево
Подразделение : Справочник.Подразделение
ПорядокУчетаБУ : Порядок погашения стоимости ОС
ПорядокУчетаНУ : Порядок включения стоимости основных средств в состав расходов (НУ)
ПроцентКапитальныхВложенийВключаемыхВРасходыНУ : Число 4, 2
СобытиеОС : Справочник.Событие ОС
СпециальныйКоэффициентНУ : Число 6, 2
СпособПоступления : Способы поступления активов
СрокИспользованияБУ : Число 4, 0
СрокИспользованияНУ : Число 4, 0
СтатьяДоходов : Статьи доходов
СтатьяРасходов : Статья расходов
СтатьяРасходовАмортизационнойПремии : Статья расходов
СтатьяРасходовНалог : Статья расходов
СчетАмортизации : Счет бухгалтерского учета
СчетАмортизацииЦФ : Счет бухгалтерского учета
СчетПередачиРасходов : Счет бухгалтерского учета
СчетУчета : Счет бухгалтерского учета
СчетУчетаЦФ : Счет бухгалтерского учета
ШифрПоЕНАОФ : Справочник.Элемент классификатора ЕНАОФ
..Табличная часть \n ОС..
ОсновноеСредство : Справочник.Объект эксплуатации
ИнвентарныйНомер : Строка
ПоказательНаработки : Справочник.Показатель наработки
ОбъемНаработки : Число 15, 3
СтоимостьБУ : Число 15, 2
СтоимостьНУ : Число 15, 2
СтоимостьПР : Число 15, 2
СтоимостьВР : Число 15, 2
СуммаЦелевыхСредств : Число 15, 2
..Табличная часть \n ЦелевоеФинансирование..
Счет : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Сумма : Число 15, 2
..Движения..
ПараметрыАмортизацииОСБухгалтерскийУчет : РегистрСведений
МестонахождениеОСБухгалтерскийУчет : РегистрСведений
ПараметрыАмортизацииОСНалоговыйУчет : РегистрСведений
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
СобытияОСОрганизаций : РегистрСведений
ОтражениеДокументовВРеглУчете : РегистрСведений
СпособыОтраженияРасходовПоАмортизацииОСБухгалтерскийУчет : РегистрСведений
ПервоначальныеСведенияОСБухгалтерскийУчет : РегистрСведений
ПараметрыЦелевогоФинансированияОС : РегистрСведений
ГрафикиАмортизацииОСБухгалтерскийУчет : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
СостоянияОСОрганизаций : РегистрСведений
Международный : РегистрБухгалтерии
НачислениеАмортизацииОСБухгалтерскийУчет : РегистрСведений
СчетаБухгалтерскогоУчетаОС : РегистрСведений
НачислениеАмортизацииОССпециальныйКоэффициентНалоговыйУчет : РегистрСведений
СпособыОтраженияРасходовПоИмущественнымНалогам : РегистрСведений
ВыручкаИСебестоимостьПродаж : Обороты
ПервоначальныеСведенияОСНалоговыйУчет : РегистрСведений
НачислениеАмортизацииОСНалоговыйУчет : РегистрСведений
}
@enduml
