@startuml ГрафикОтпусков
'!include templates.wsd
'..\include templates.wsd
class Документ.ГрафикОтпусков as "График отпусков" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
КраткийСоставДокумента : Строка
ДатаСобытия : Дата
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
РуководительКадровойСлужбы : Справочник.Физическое лицо
ДолжностьРуководителяКадровойСлужбы : Справочник.Должность
Ответственный : Справочник.Пользователь
Комментарий : Строка
УдалитьДатаВычисленияОстатков : Дата
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ВидОтпуска : Справочник.Вид отпуска
ДатаНачала : Дата
ДатаОкончания : Дата
КоличествоДней : Число 3, 0
УдалитьНачалоПериодаЗаКоторыйПредоставляетсяОтпуск : Дата
УдалитьКонецПериодаЗаКоторыйПредоставляетсяОтпуск : Дата
}
@enduml
