@startuml УстановкаЦенНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Документ.УстановкаЦенНоменклатуры as "Установка цен номенклатуры" <<Документы>>
{
..Реквизиты..
Ответственный : Справочник.Пользователь
Комментарий : Строка
Согласован : Булево
ДокументОснование : Документ.Приобретение товаров и услуг\rДокумент.Этап производства\rДокумент.Заказ поставщику\r...
Статус : Статусы установок цен номенклатуры
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
ВидЦены : Справочник.Вид цены
Цена : Число 15, 2
ЦенаИзмененаВручную : Булево
..Табличная часть \n ВидыЦен..
ВидЦены : Справочник.Вид цены
НастройкиКомпоновкиДанных : Хранилище значения
..Табличная часть \n НаборыЗначенийДоступа..
НомерНабора : Число 4, 0
ЗначениеДоступа : Справочник.Статьи бюджетов\rСправочник.Вид номенклатуры\rСправочник.Номенклатура\r...
Уточнение : Справочник.Идентификатор объекта метаданных
Чтение : Булево
Изменение : Булево
..Движения..
ЦеныНоменклатуры : РегистрСведений
}
@enduml
