@startuml НачальнаяЗадолженностьПоЗарплате
'!include templates.wsd
'..\include templates.wsd
class Документ.НачальнаяЗадолженностьПоЗарплате as "Начальная задолженность по зарплате" <<Документы>>
{
..Реквизиты..
Месяц : Дата
Организация : Справочник.Организация
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
СпособВводаЗадолженности : Способ ввода задолженности по зарплате
..Табличная часть \n ЗадолженностьПоЗарплате..
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
Сумма : Число 13, 2
СуммаПоБухучету : Число 13, 2
ВыплатыЗаПрошлыеПериоды : Число 13, 2
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Движения..
ВзаиморасчетыССотрудниками : Остатки
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
ЗарплатаКВыплате : Остатки
}
@enduml
