@startuml ПоступлениеДенежныхДокументов
'!include templates.wsd
'..\include templates.wsd
class Документ.ПоступлениеДенежныхДокументов as "Поступление денежных документов" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ПодразделениеОтправитель : Справочник.Подразделение
ХозяйственнаяОперация : Хозяйственные операции
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
Договор : Справочник.Договор с контрагентом
ПодотчетноеЛицо : Справочник.Физическое лицо
Ответственный : Справочник.Пользователь
Комментарий : Строка
ДатаВходящегоДокумента : Дата
НомерВходящегоДокумента : Строка
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
Валюта : Справочник.Валюта
СуммаДокумента : Число 15, 2
ВалютаВзаиморасчетов : Справочник.Валюта
СуммаВзаиморасчетов : Число 15, 2
Соглашение : Справочник.Соглашение об условиях закупок
ДатаПлатежа : Дата
ФормаОплаты : Формы оплаты
МОЛ : Справочник.Физическое лицо
ПорядокРасчетов : Детализация расчетов
НазначениеАванса : Строка
КоличествоДокументов : Строка
КоличествоЛистов : Строка
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
НаправлениеДеятельности : Справочник.Направление деятельности
Курс : Число 10, 4
Кратность : Число 10, 0
ПорядокОплаты : Порядок оплаты
..Табличная часть \n ДенежныеДокументы..
НаименованиеДенежногоДокумента : Строка
ДенежныйДокумент : Справочник.Денежный документ
Количество : Число 15, 3
Сумма : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
ИдентификаторСтроки : Строка
Цена : Число 15, 2
Валюта : Справочник.Валюта
ГруппаДокумента : Справочник.Денежный документ
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n РасшифровкаПлатежа..
Заказ : Документ.Приобретение товаров и услуг\rДокумент.Таможенная декларация на импорт\rДокумент.Заказ поставщику\r...
Сумма : Число 15, 2
ВалютаВзаиморасчетов : Справочник.Валюта
СуммаВзаиморасчетов : Число 15, 2
..Движения..
ДенежныеСредстваУПодотчетныхЛиц : Остатки
ДвиженияДенежныхСредств : Обороты
СуммыДокументовВВалютеРегл : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДенежныеСредстваКонтрагент : Обороты
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
РасчетыСПоставщиками : Остатки
Международный : РегистрБухгалтерии
РасчетыСПоставщикамиПоДокументам : Остатки
ДенежныеДокументы : Остатки
}
@enduml
