@startuml ЗаказНаВнутреннееПотребление
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаказНаВнутреннееПотребление as "Заказ на внутреннее потребление" <<Документы>>
{
..Реквизиты..
ЖелаемаяДатаОтгрузки : Дата
Комментарий : Строка
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
Подразделение : Справочник.Подразделение
Склад : Справочник.Склад (складская территория)
Статус : Статусы внутренних заказов
МаксимальныйКодСтроки : Число 10, 0
Сделка : Справочник.Сделка с клиентом
ХозяйственнаяОперация : Хозяйственные операции
ДатаОтгрузки : Дата
НеОтгружатьЧастями : Булево
Назначение : Справочник.Назначение
ДокументОснование : Документ.Заказ на сборку (разборку)\rДокумент.Заказ на перемещение\rДокумент.Заказ на ремонт\r...
СостояниеЗаполненияМногооборотнойТары : Состояния заполнения многооборотной тары
НаправлениеДеятельности : Справочник.Направление деятельности
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ДатаОтгрузки : Дата
Отменено : Булево
КодСтроки : Число 10, 0
СтатьяРасходов : Статья расходов\rСтатья актива/пассива
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ФизическоеЛицо : Справочник.Физическое лицо
СтатусУказанияСерий : Число 2, 0
ВариантОбеспечения : Варианты обеспечения
Серия : Справочник.Серия номенклатуры
КатегорияЭксплуатации : Справочник.Категории эксплуатации
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
..Движения..
ТоварыКОтгрузке : Остатки
ГрафикОтгрузкиТоваров : Остатки
ФактическиеДанныеБюджетирования : Обороты
ОбеспечениеЗаказов : Остатки
СвободныеОстатки : Остатки
ЗаказыНаВнутреннееПотребление : Остатки
}
@enduml
