@startuml ЗаказПоставщику
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаказПоставщику as "Заказ поставщику" <<Документы>>
{
..Реквизиты..
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
Организация : Справочник.Организация
Соглашение : Справочник.Соглашение об условиях закупок
Склад : Справочник.Склад (складская территория)
Валюта : Справочник.Валюта
Менеджер : Справочник.Пользователь
ЦенаВключаетНДС : Булево
Статус : Статусы заказов поставщикам
СуммаДокумента : Число 15, 2
ДополнительнаяИнформация : Строка
ЖелаемаяДатаПоступления : Дата
МаксимальныйКодСтроки : Число 10, 0
Согласован : Булево
ФормаОплаты : Формы оплаты
Касса : Справочник.Касса
БанковскийСчет : Справочник.Банковский счет организации
СуммаАвансаДоПодтверждения : Число 15, 2
СуммаПредоплатыДоПоступления : Число 15, 2
ДатаПервогоПоступления : Дата
ДатаСогласования : Дата
НалогообложениеНДС : Типы налогообложения НДС
ХозяйственнаяОперация : Хозяйственные операции
Комментарий : Строка
НомерПоДаннымПоставщика : Строка
ДатаПоДаннымПоставщика : Дата
Сделка : Справочник.Сделка с клиентом
Подразделение : Справочник.Подразделение
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
РегистрироватьЦеныПоставщика : Булево
Договор : Справочник.Договор с контрагентом
Автор : Справочник.Пользователь
ДокументОснование : Документ.Заказ на производство\rДокумент.Заказ материалов в производство\rДокумент.Заказ переработчику\r...
ПоступлениеОднойДатой : Булево
ДатаПоступления : Дата
ПорядокРасчетов : Детализация расчетов
АдресДоставкиДляПоставщика : Строка
КонтактноеЛицо : Справочник.Контактное лицо
ВернутьМногооборотнуюТару : Булево
СрокВозвратаМногооборотнойТары : Число 3, 0
СостояниеЗаполненияМногооборотнойТары : Состояния заполнения многооборотной тары
ЗакупкаПодДеятельность : Типы налогообложения НДС
ТребуетсяЗалогЗаТару : Булево
СуммаВозвратнойТары : Число 15, 2
Приоритет : Справочник.Приоритет
СпособДоставки : Способы доставки
ПеревозчикПартнер : Справочник.Партнер
ЗонаДоставки : Справочник.Зоны доставки
ВремяДоставкиС : Дата
ВремяДоставкиПо : Дата
АдресДоставки : Строка
АдресДоставкиЗначенияПолей : Строка
ДополнительнаяИнформацияПоДоставке : Строка
АдресДоставкиПеревозчика : Строка
АдресДоставкиПеревозчикаЗначенияПолей : Строка
ОсобыеУсловияПеревозки : Булево
ОсобыеУсловияПеревозкиОписание : Строка
НаправлениеДеятельности : Справочник.Направление деятельности
ПорядокОплаты : Порядок оплаты
ЕстьКиЗГИСМ : Булево
ВариантПриемкиТоваров : Варианты приемки товаров
..Табличная часть \n Товары..
НоменклатураПоставщика : Справочник.Номенклатура поставщика
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ДатаПоступления : Дата
ВидЦеныПоставщика : Справочник.Вид цены поставщика
Цена : Число 15, 2
Сумма : Число 15, 2
ПроцентРучнойСкидки : Число 5, 2
СуммаРучнойСкидки : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
КодСтроки : Число 10, 0
Отменено : Булево
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ПричинаОтмены : Справочник.Причина отмены заказов поставщикам
Склад : Справочник.Склад (складская территория)
Назначение : Справочник.Назначение
Подразделение : Справочник.Подразделение
СписатьНаРасходы : Булево
..Табличная часть \n ЭтапыГрафикаОплаты..
ВариантОплаты : Варианты оплаты поставщику
ДатаПлатежа : Дата
ПроцентПлатежа : Число 5, 2
СуммаПлатежа : Число 15, 2
ПроцентЗалогаЗаТару : Число 5, 2
СуммаЗалогаЗаТару : Число 15, 2
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ЦеныНоменклатурыПоставщиков : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
ОбеспечениеЗаказов : Остатки
РасчетыСПоставщиками : Остатки
ДвижениеТоваров : Обороты
ОбеспечениеЗаказовРаботами : Остатки
РасчетыСПоставщикамиПоДокументам : Остатки
ГрафикПоступленияТоваров : Остатки
ЗаказыПоставщикам : Остатки
ТоварыКПоступлению : Остатки
}
@enduml
