@startuml ЗаданиеТорговомуПредставителю
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаданиеТорговомуПредставителю as "Задание торговому представителю" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
Соглашение : Справочник.Соглашение об условиях продаж
Валюта : Справочник.Валюта
ГрафикОплаты : Справочник.График оплаты
ЦенаВключаетНДС : Булево
Склад : Справочник.Склад (складская территория)
ТорговыйПредставитель : Справочник.Пользователь
ДатаВизитаПлан : Дата
ДатаВизитаФакт : Дата
ВремяНачала : Дата
ВремяОкончания : Дата
Куратор : Справочник.Пользователь
ДетализацияПоНоменклатуре : Булево
СуммаПлан : Число 15, 2
СуммаДокумента : Число 15, 2
НеОтгружатьЧастями : Булево
ЖелаемаяДатаОтгрузки : Дата
Статус : Статусы заданий торговым представителям
ФормаОплаты : Формы оплаты
УсловияОбслуживания : Справочник.Условия обслуживания торговыми представителями
НалогообложениеНДС : Типы налогообложения НДС
ХозяйственнаяОперация : Хозяйственные операции
Комментарий : Строка
Договор : Справочник.Договор с контрагентом
ВернутьМногооборотнуюТару : Булево
СрокВозвратаМногооборотнойТары : Число 3, 0
СостояниеЗаполненияМногооборотнойТары : Состояния заполнения многооборотной тары
ТребуетсяЗалогЗаТару : Булево
..Табличная часть \n Задачи..
ОписаниеЗадачи : Строка
Выполнена : Булево
ОписаниеРезультата : Строка
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковокПлан : Число 15, 3
КоличествоПлан : Число 15, 3
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ВидЦены : Справочник.Вид цены
Цена : Число 15, 2
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
ПроцентРучнойСкидки : Число 5, 2
СуммаРучнойСкидки : Число 15, 2
Комментарий : Строка
ПричинаОтмены : Справочник.Причина отмены заказов клиентов
Содержание : Строка
..Табличная часть \n ЭтапыГрафикаОплаты..
ВариантОплаты : Варианты оплаты клиентом
ДатаПлатежа : Дата
ПроцентПлатежа : Число 5, 2
СуммаПлатежа : Число 15, 2
ПроцентЗалогаЗаТару : Число 5, 2
СуммаЗалогаЗаТару : Число 15, 2
..Табличная часть \n ДолгиПоЗаказам..
ЗаказКлиента : Документ.Заказ клиента
Валюта : Справочник.Валюта
НашДолг : Число 15, 2
ПредставлениеЗаказа : Строка
ДолгКлиента : Число 15, 2
КОплатеПросрочено : Число 15, 2
КОтгрузкеПросрочено : Число 15, 2
..Табличная часть \n РасшифровкаДебиторскойЗадолженности..
ЗаказКлиента : Документ.Заказ клиента
Дата : Дата
РасчетныйДокумент : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
ПредставлениеРасчетногоДокумента : Строка
УменьшениеДолга : Число 15, 2
УвеличениеДолга : Число 15, 2
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
