@startuml КорректировкаНалогообложенияНДСПартийТоваров
'!include templates.wsd
'..\include templates.wsd
class Документ.КорректировкаНалогообложенияНДСПартийТоваров as "Корректировка налогообложения НДС партий товаров" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Комментарий : Строка
ПеремещениеПодДеятельность : Типы налогообложения НДС
..Табличная часть \n ВидыЗапасов..
ДокументПоступления : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\rДокумент.Таможенная декларация на импорт\r...
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
УдалитьАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
Склад : Справочник.Склад (складская территория)
ВидЗапасов : Справочник.Вид запасов
ВидЗапасовПолучателя : Справочник.Вид запасов
Количество : Число 15, 3
Стоимость : Число 15, 2
СтоимостьБезНДС : Число 15, 2
СтоимостьРегл : Число 15, 2
НДСРегл : Число 15, 2
ПостояннаяРазница : Число 15, 2
ВременнаяРазница : Число 15, 2
НомерГТД : Справочник.Номер ГТД
..Движения..
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
НДСЗаписиКнигиПродаж : Обороты
ДвиженияНоменклатураНоменклатура : Обороты
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
ПартииЗатратНаВыпуск : Остатки
}
@enduml
