@startuml ИндивидуальныйГрафик
'!include templates.wsd
'..\include templates.wsd
class Документ.ИндивидуальныйГрафик as "Индивидуальный график" <<Документы>>
{
..Реквизиты..
ПериодРегистрации : Дата
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ДатаНачалаПериода : Дата
ДатаОкончанияПериода : Дата
ПериодВводаДанныхОВремени : Периоды ввода данных о времени
ИсправленныйДокумент : Документ.Индивидуальный график
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ДанныеОВремени..
Сотрудник : Справочник.Сотрудник
Часов1 : Число 5, 2
Часов2 : Число 5, 2
Часов3 : Число 5, 2
Часов4 : Число 5, 2
Часов5 : Число 5, 2
Часов6 : Число 5, 2
Часов7 : Число 5, 2
Часов8 : Число 5, 2
Часов9 : Число 5, 2
Часов10 : Число 5, 2
Часов11 : Число 5, 2
Часов12 : Число 5, 2
Часов13 : Число 5, 2
Часов14 : Число 5, 2
Часов15 : Число 5, 2
Часов16 : Число 5, 2
Часов17 : Число 5, 2
Часов18 : Число 5, 2
Часов19 : Число 5, 2
Часов20 : Число 5, 2
Часов21 : Число 5, 2
Часов22 : Число 5, 2
Часов23 : Число 5, 2
Часов24 : Число 5, 2
Часов25 : Число 5, 2
Часов26 : Число 5, 2
Часов27 : Число 5, 2
Часов28 : Число 5, 2
Часов29 : Число 5, 2
Часов30 : Число 5, 2
Часов31 : Число 5, 2
ВидВремени1 : Справочник.Вид рабочего времени
ВидВремени2 : Справочник.Вид рабочего времени
ВидВремени3 : Справочник.Вид рабочего времени
ВидВремени4 : Справочник.Вид рабочего времени
ВидВремени5 : Справочник.Вид рабочего времени
ВидВремени6 : Справочник.Вид рабочего времени
ВидВремени7 : Справочник.Вид рабочего времени
ВидВремени8 : Справочник.Вид рабочего времени
ВидВремени9 : Справочник.Вид рабочего времени
ВидВремени10 : Справочник.Вид рабочего времени
ВидВремени11 : Справочник.Вид рабочего времени
ВидВремени12 : Справочник.Вид рабочего времени
ВидВремени13 : Справочник.Вид рабочего времени
ВидВремени14 : Справочник.Вид рабочего времени
ВидВремени15 : Справочник.Вид рабочего времени
ВидВремени16 : Справочник.Вид рабочего времени
ВидВремени17 : Справочник.Вид рабочего времени
ВидВремени18 : Справочник.Вид рабочего времени
ВидВремени19 : Справочник.Вид рабочего времени
ВидВремени20 : Справочник.Вид рабочего времени
ВидВремени21 : Справочник.Вид рабочего времени
ВидВремени22 : Справочник.Вид рабочего времени
ВидВремени23 : Справочник.Вид рабочего времени
ВидВремени24 : Справочник.Вид рабочего времени
ВидВремени25 : Справочник.Вид рабочего времени
ВидВремени26 : Справочник.Вид рабочего времени
ВидВремени27 : Справочник.Вид рабочего времени
ВидВремени28 : Справочник.Вид рабочего времени
ВидВремени29 : Справочник.Вид рабочего времени
ВидВремени30 : Справочник.Вид рабочего времени
ВидВремени31 : Справочник.Вид рабочего времени
..Табличная часть \n СотрудникиСИсправлениями..
Сотрудник : Справочник.Сотрудник
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Движения..
ДанныеИндивидуальныхГрафиковСотрудников : Обороты
ДанныеТабельногоУчетаРабочегоВремениСотрудников : Обороты
}
@enduml
