@startuml ВходящаяСправкаОЗаработкеДляРасчетаПособий
'!include templates.wsd
'..\include templates.wsd
class Документ.ВходящаяСправкаОЗаработкеДляРасчетаПособий as "Входящая справка о заработке для расчета пособий" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
Страхователь : Справочник.Работодатель
ПериодРаботыС : Дата
ПериодРаботыПо : Дата
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ДанныеОЗаработке..
РасчетныйГод : Число 4, 0
Заработок : Число 15, 2
ДнейБолезниУходаЗаДетьми : Число 7, 2
..Движения..
ДанныеСтрахователейДляРасчетаСреднегоЗаработкаФСС : Обороты
}
@enduml
