@startuml ОстаткиЕГАИС
'!include templates.wsd
'..\include templates.wsd
class Документ.ОстаткиЕГАИС as "Остатки ЕГАИС" <<Документы>>
{
..Реквизиты..
ОрганизацияЕГАИС : Справочник.Организация ЕГАИС
УдалитьСтатусОбработки : Статусы обработки остатков ЕГАИС
ВидДокумента : Виды документов ЕГАИС
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ОстаткиПоДаннымЕГАИС..
АлкогольнаяПродукция : Справочник.Алкогольная продукция ЕГАИС
Количество : Число 15, 3
Справка2 : Справочник.Справка к ТТН по форме 2
..Табличная часть \n КорректировкаОстатков..
АлкогольнаяПродукция : Справочник.Алкогольная продукция ЕГАИС
Количество : Число 15, 3
Справка2 : Справочник.Справка к ТТН по форме 2
..Движения..
ОстаткиАлкогольнойПродукцииЕГАИС : Остатки
}
@enduml
