@startuml СписаниеНМАМеждународныйУчет
'!include templates.wsd
'..\include templates.wsd
class Документ.СписаниеНМАМеждународныйУчет as "Списание НМА (международный учет)" <<Документы>>
{
..Реквизиты..
ДокументОснование : Документ.Списание НМА
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
ПричинаСписания : Строка
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Ответственный : Справочник.Пользователь
Комментарий : Строка
СчетРасходов : Международный план счетов
СчетРасходовСубконто1 : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСтатья расходов\r...
СчетРасходовСубконто2 : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСтатья расходов\r...
СчетРасходовСубконто3 : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСтатья расходов\r...
..Движения..
НематериальныеАктивыМеждународныйУчет : РегистрСведений
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ФактическиеДанныеБюджетирования : Обороты
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
ВыручкаИСебестоимостьПродаж : Обороты
}
@enduml
