@startuml КорректировкаОбособленногоУчетаЗапасов
'!include templates.wsd
'..\include templates.wsd
class Документ.КорректировкаОбособленногоУчетаЗапасов as "Корректировка обособленного учета запасов" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Склад : Справочник.Склад (складская территория)
Предназначение : Типы предназначения видов запасов
НовоеПредназначение : Типы предназначения видов запасов
Подразделение : Справочник.Подразделение
Менеджер : Справочник.Пользователь
Сделка : Справочник.Сделка с клиентом
НовоеПодразделение : Справочник.Подразделение
НовыйМенеджер : Справочник.Пользователь
НоваяСделка : Справочник.Сделка с клиентом
Комментарий : Строка
ВидыЗапасовУказаныВручную : Булево
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Количество : Число 15, 3
Серия : Справочник.Серия номенклатуры
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
СтатусУказанияСерий : Число 2, 0
..Табличная часть \n ВидыЗапасов..
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ВидЗапасовОприходование : Справочник.Вид запасов
..Движения..
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
СебестоимостьТоваров : Остатки
ПрочиеАктивыПассивы : Остатки
ДетализацияПартийТоваровДляНДСиУСН : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
ФактическиеДанныеБюджетирования : Обороты
ДвиженияНоменклатураНоменклатура : Обороты
ТоварыОрганизаций : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
