@startuml АвансовыйПлатежИностранцаПоНДФЛ
'!include templates.wsd
'..\include templates.wsd
class Документ.АвансовыйПлатежИностранцаПоНДФЛ as "Авансовый платеж по НДФЛ" <<Документы>>
{
..Реквизиты..
ДатаОперации : Дата
НалоговыйПериод : Число 4, 0
Организация : Справочник.Организация
Сотрудник : Справочник.Физическое лицо
Сумма : Число 15, 2
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Движения..
АвансовыеПлатежиИностранцевПоНДФЛ : Остатки
}
@enduml
