@startuml ПрочееОприходованиеТоваров
'!include templates.wsd
'..\include templates.wsd
class Документ.ПрочееОприходованиеТоваров as "Прочее оприходование товаров" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Склад : Справочник.Склад (складская территория)
ВидЦены : Справочник.Вид цены
Подразделение : Справочник.Подразделение
Ответственный : Справочник.Пользователь
Комментарий : Строка
ХозяйственнаяОперация : Хозяйственные операции
СостояниеЗаполненияМногооборотнойТары : Состояния заполнения многооборотной тары
ДокументОснование : Документ.Внутреннее потребление товаров\rДокумент.Списание ОС\rДокумент.Маршрутный лист производства\r...
НаправлениеДеятельности : Справочник.Направление деятельности
Валюта : Справочник.Валюта
ВариантПриемкиТоваров : Варианты приемки товаров
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Цена : Число 15, 2
Сумма : Число 15, 2
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ВидЗапасов : Справочник.Вид запасов
СтатусУказанияСерий : Число 2, 0
ФизическоеЛицо : Справочник.Физическое лицо
СписаниеНаРасходы : Документ.Внутреннее потребление товаров
УдалитьАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
ИдентификаторСтроки : Строка
Серия : Справочник.Серия номенклатуры
Назначение : Справочник.Назначение
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
СтатьяДоходов : Статья актива/пассива\rСтатьи доходов
ПартияТМЦВЭксплуатации : Справочник.Партии ТМЦ в эксплуатации
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
ВидыЗапасов : Строка
НазначениеОтправителя : Справочник.Назначение
НомерГТД : Справочник.Номер ГТД
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
..Табличная часть \n Серии..
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Серия : Справочник.Серия номенклатуры
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
НазначениеОтправителя : Справочник.Назначение
..Табличная часть \n ВидыЗапасов..
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
СкладОтгрузки : Справочник.Склад (складская территория)
ВидЗапасовОтгрузки : Справочник.Вид запасов
ДокументРеализации : Документ.Внутреннее потребление товаров\rДокумент.Движение продукции и материалов\rДокумент.Передача материалов в производство
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Серия : Справочник.Серия номенклатуры
АналитикаУчетаНоменклатурыОтгрузки : Справочник.Ключ аналитики учета номенклатуры
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ПрочиеДоходы : Остатки
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ТоварыКОформлениюОтчетовКомитенту : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНМатериалы : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
Международный : РегистрБухгалтерии
РасходыПриУСНТовары : Остатки
НДСЗаписиКнигиПродаж : Обороты
КнигаУчетаДоходовИРасходов : Обороты
СвободныеОстатки : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
ТМЦВЭксплуатации : Обороты
ПартииПроизводственныхЗатрат : Остатки
ТоварыКПоступлению : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
