@startuml УпаковочныйЛист
'!include templates.wsd
'..\include templates.wsd
class Документ.УпаковочныйЛист as "Упаковочный лист" <<Документы>>
{
..Реквизиты..
Код : Строка
СкладУпаковки : Справочник.Склад (складская территория)
Вид : Виды упаковочных листов
Упаковал : Справочник.Пользователь
Основание : Строка
Комментарий : Строка
РежимПросмотраПоТоварам : Число 1, 0
ВсегоМест : Число 10, 0
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Серия : Справочник.Серия номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
УпаковочныйЛист : Документ.Упаковочный лист
НоменклатураПоставщика : Справочник.Номенклатура поставщика
Комментарий : Строка
ЭтоУпаковочныйЛист : Булево
ЭтоСлужебнаяСтрокаПустогоУпаковочногоЛиста : Число 1, 0
УпаковочныйЛистРодитель : Документ.Упаковочный лист
СтатусУказанияСерий : Число 2, 0
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
