@startuml РаспоряжениеНаПеремещениеДенежныхСредств
'!include templates.wsd
'..\include templates.wsd
class Документ.РаспоряжениеНаПеремещениеДенежныхСредств as "Распоряжение на перемещение денежных средств" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
СуммаДокумента : Число 15, 2
Валюта : Справочник.Валюта
ХозяйственнаяОперация : Хозяйственные операции
БанковскийСчет : Справочник.Банковский счет организации
Касса : Справочник.Касса
БанковскийСчетПолучатель : Справочник.Банковский счет организации
КассаПолучатель : Справочник.Касса
Статус : Статусы распоряжений на перемещение денежных средств
КтоРешил : Справочник.Пользователь
НазначениеПлатежа : Строка
ДатаПлатежа : Дата
Комментарий : Строка
Подразделение : Справочник.Подразделение
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
ПлатежиПо275ФЗ : Булево
ДоговорСЗаказчиком : Справочник.Договор между организациями\rСправочник.Договор с контрагентом
ТипПлатежаФЗ275 : Справочник.Типы платежей 275-ФЗ
..Табличная часть \n ПодтверждающиеДокументы..
ВидДокумента : Справочник.Вид документа
Номер : Строка
Дата : Дата
Сумма : Число 15, 2
Файл : Справочник.Присоединенный файл (Договоры с контрагентами)\rСправочник.Присоединенный файл (Договоры кредитов и депозитов)\rСправочник.Присоединенный файл (Договоры между организациями)
..Движения..
ФактическиеДанныеБюджетирования : Обороты
ДенежныеСредстваКВыплате : Остатки
}
@enduml
