@startuml ЗаписьКнигиПродаж
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаписьКнигиПродаж as "Запись книги продаж" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Контрагент : Справочник.Организация\rСправочник.Контрагент
СуммаДокумента : Число 15, 2
Валюта : Справочник.Валюта
Грузоотправитель : Справочник.Контрагент
Грузополучатель : Справочник.Контрагент
ЗаписьДополнительногоЛиста : Булево
ФормироватьСторнирующиеЗаписиДопЛистовВручную : Булево
КорректируемыйПериод : Дата
ДокументРасчетов : Документ.Запись книги покупок\rДокумент.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\r...
Комментарий : Строка
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
Подразделение : Справочник.Подразделение
КодВидаОперации : Строка
ХозяйственнаяОперация : Хозяйственные операции
ИсправляемыйДокумент : Документ.Запись книги продаж
..Табличная часть \n Ценности..
Номенклатура : Справочник.Номенклатура
ВидЦенности : Виды ценностей
Количество : Число 15, 3
Цена : Число 15, 2
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
НомерГТД : Справочник.Номер ГТД
СторнирующаяЗаписьДопЛиста : Булево
Событие : События по НДС (продажи)
ИдентификаторСтроки : Строка
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
КодТНВЭД : Справочник.ТН ВЭД
..Табличная часть \n ДокументыОплаты..
ДатаОплаты : Дата
ДокументОплаты : Документ.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\rДокумент.Эквайринговая операция\r...
..Табличная часть \n Расхождения..
ВидЦенности : Виды ценностей
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
ИдентификаторСтроки : Строка
..Движения..
СуммыДокументовВВалютеРегл : РегистрСведений
ОтражениеДокументовВРеглУчете : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
НДСЗаписиКнигиПродаж : Обороты
}
@enduml
