@startuml ЛистокСообщенияДляВоенкомата
'!include templates.wsd
'..\include templates.wsd
class Документ.ЛистокСообщенияДляВоенкомата as "Листок сообщения об изменениях" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
Статус : Статусы листков сообщения
ДатаВрученияСотруднику : Дата
ПричинаНевручения : Строка
ОписаниеИзменений : Строка
Подразделение : Справочник.Подразделение
Должность : Справочник.Должность
ДатаРождения : Дата
Образование : Справочник.Вид образования
СемейноеПоложение : Справочник.Семейное положение
Звание : Справочник.Воинское звание
ВУС : Строка
СостояниеЗдоровья : Строка
АдресМестаПроживанияПредставление : Строка
СоставСемьи : Строка
ОтветственныйЗаВУР : Справочник.Физическое лицо
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ФиксацияИзменений..
ИмяРеквизита : Строка
Путь : Строка
ИдентификаторСтроки : Число 5, 0
}
@enduml
