@startuml МодернизацияОС2_4
'!include templates.wsd
'..\include templates.wsd
class Документ.МодернизацияОС2_4 as "Модернизация ОС" <<Документы>>
{
..Реквизиты..
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
АналитикаРасходовАмортизационнойПремии : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ВариантПримененияЦелевогоФинансирования : Варианты применения целевого финансирования
ВидАналитикиКапитализацииРасходов : Виды аналитики капитализации расходов
ВключитьАмортизационнуюПремиюВСоставРасходов : Булево
ДокументВДругомУчете : Документ.Модернизация ОС
Комментарий : Строка
НаправлениеДеятельности : Справочник.Направление деятельности
ОбъектСтроительства : Справочник.Объект строительства
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
ОтражатьВРеглУчете : Булево
ОтражатьВУпрУчете : Булево
Подразделение : Справочник.Подразделение
СтатьяДоходов : Статьи доходов
СтатьяРасходовАмортизационнойПремии : Статья расходов
..Табличная часть \n ОС..
ОсновноеСредство : Справочник.Объект эксплуатации
СуммаКапитальныхВложенийВключаемыхВРасходыНУ : Число 15, 2
СуммаЦелевыхСредств : Число 15, 2
СтоимостьУУ : Число 15, 2
СтоимостьБУ : Число 15, 2
..Табличная часть \n ЦелевоеФинансирование..
Счет : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Сумма : Число 15, 2
..Движения..
ПараметрыАмортизацииОСБухгалтерскийУчет : РегистрСведений
ПараметрыАмортизацииОСУУ : РегистрСведений
ПрочиеДоходы : Остатки
ПараметрыАмортизацииОСНалоговыйУчет : РегистрСведений
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
СобытияОСОрганизаций : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ПараметрыАмортизацииОСБУ : РегистрСведений
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
ПараметрыЦелевогоФинансированияОС : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
ВыручкаИСебестоимостьПродаж : Обороты
СтоимостьОС : Остатки
}
@enduml
