@startuml ИзменениеПараметровНМАМеждународныйУчет
'!include templates.wsd
'..\include templates.wsd
class Документ.ИзменениеПараметровНМАМеждународныйУчет as "Изменение параметров НМА (международный учет)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
Комментарий : Строка
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
ПорядокУчета : Порядок учета стоимости внеоборотных активов
ПорядокУчетаФлаг : Булево
ЛиквидационнаяСтоимость : Число 15, 2
ЛиквидационнаяСтоимостьФлаг : Булево
ЛиквидационнаяСтоимостьПредставления : Число 15, 2
ЛиквидационнаяСтоимостьПредставленияФлаг : Булево
СчетУчета : Международный план счетов
СчетУчетаФлаг : Булево
СчетАмортизации : Международный план счетов
СчетАмортизацииФлаг : Булево
МетодНачисленияАмортизации : Способы начисления амортизации нематериальных активов
МетодНачисленияАмортизацииФлаг : Булево
СрокИспользования : Число 10, 0
СрокИспользованияФлаг : Булево
ОбъемНаработки : Число 15, 3
ОбъемНаработкиФлаг : Булево
КоэффициентУскорения : Число 4, 3
КоэффициентУскоренияФлаг : Булево
СтатьяРасходов : Статья расходов
СтатьяРасходовФлаг : Булево
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаРасходовФлаг : Булево
..Движения..
НематериальныеАктивыМеждународныйУчет : РегистрСведений
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ФактическиеДанныеБюджетирования : Обороты
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
}
@enduml
