@startuml ОтменаСовмещения
'!include templates.wsd
'..\include templates.wsd
class Документ.ОтменаСовмещения as "Отмена совмещения" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
СовмещающийСотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ДатаОтмены : Дата
ДокументОснование : Документ.Совмещение должностей
ОтменаДоплатыУтверждена : Булево
Начисление : Начисление
ИсправленныйДокумент : Документ.Отмена совмещения
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n НачисленияСотрудника..
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Начисление : Начисление
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Размер : Число 15, 3
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников : РегистрСведений
БухучетПлановыхНачислений : РегистрСведений
ПлановыеНачисления : РегистрСведений
}
@enduml
