@startuml СчетФактураПолученныйАванс
'!include templates.wsd
'..\include templates.wsd
class Документ.СчетФактураПолученныйАванс as "Счет-фактура полученный (аванс)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ДокументОснование : Документ.Расходный кассовый ордер\rДокумент.Первичный документ\rДокумент.Возврат товаров поставщику\r...
Контрагент : Справочник.Организация\rСправочник.Контрагент
ДатаСоставления : Дата
Сумма : Число 15, 2
СуммаНДС : Число 15, 2
ПолученВЭлектронномВиде : Булево
КодВидаОперации : Строка
Комментарий : Строка
Исправление : Булево
НомерИсправления : Строка
ДатаИсправления : Дата
СчетФактураОснование : Документ.Счет-фактура полученный (аванс)
Подразделение : Справочник.Подразделение
Ответственный : Справочник.Пользователь
СоставленКомиссионеромОтИмениПродавца : Булево
СводныйКомиссионный : Булево
ИННКонтрагента : Строка
КППКонтрагента : Строка
..Табличная часть \n Авансы..
Сумма : Число 14, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 14, 2
..Табличная часть \n Продавцы..
Продавец : Справочник.Контрагент
ИННПродавца : Строка
КПППродавца : Строка
..Движения..
ОтражениеДокументовВРеглУчете : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
НДСЗаписиКнигиПродаж : Обороты
НДСЗаписиКнигиПокупок : Обороты
ЖурналУчетаСчетовФактур : РегистрСведений
}
@enduml
