@startuml ОтменаРегистрацииТранспортныхСредств
'!include templates.wsd
'..\include templates.wsd
class Документ.ОтменаРегистрацииТранспортныхСредств as "Отмена регистрации транспортных средств" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ОС..
ОсновноеСредство : Справочник.Объект эксплуатации
..Движения..
РегистрацияТранспортныхСредств : РегистрСведений
}
@enduml
