@startuml УведомлениеОСписанииКиЗГИСМ
'!include templates.wsd
'..\include templates.wsd
class Документ.УведомлениеОСписанииКиЗГИСМ as "Уведомление о списании КиЗ для маркировки" <<Документы>>
{
..Реквизиты..
Основание : Документ.Внутреннее потребление товаров
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n НомераКиЗ..
Индивидуализирован : Булево
НомерКиЗ : Строка
RFIDTID : Строка
RFIDEPC : Строка
ПричинаСписания : Причины списания КиЗ ГИСМ
ЗаявкаНаВыпускКиЗ : Документ.Заявка на выпуск КиЗ для маркировки
}
@enduml
