@startuml УведомлениеОКонтролируемыхСделках
'!include templates.wsd
'..\include templates.wsd
class Документ.УведомлениеОКонтролируемыхСделках as "Уведомление о контролируемых сделках" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ОтчетныйГод : Дата
НомерКорректировки : Число 3, 0
ДатаФормированияСпискаСделок : Дата
ДатаЗаполненияУведомления : Дата
КодМестаПредставления : Строка
ГруппироватьСделкиСОдинаковойЦеной : Булево
КодФормыРеорганизации : Строка
ИННРеорганизованнойОрганизации : Строка
КППРеорганизованнойОрганизации : Строка
..Движения..
КонтролируемыеСделкиОрганизаций : Обороты
}
@enduml
