@startuml ВнутреннееПотреблениеТоваров
'!include templates.wsd
'..\include templates.wsd
class Документ.ВнутреннееПотреблениеТоваров as "Внутреннее потребление товаров" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Склад : Справочник.Склад (складская территория)
ЗаказНаВнутреннееПотребление : Документ.Заказ на производство\rДокумент.Заказ материалов в производство\rДокумент.Корректировка заказа материалов\r...
Подразделение : Справочник.Подразделение
Ответственный : Справочник.Пользователь
Комментарий : Строка
ДатаРаспоряжения : Дата
ВидЦены : Справочник.Вид цены
Сделка : Справочник.Сделка с клиентом
ПотреблениеПоЗаказам : Булево
ХозяйственнаяОперация : Хозяйственные операции
ПотреблениеДляДеятельности : Типы налогообложения НДС
СостояниеЗаполненияМногооборотнойТары : Состояния заполнения многооборотной тары
ВидыЗапасовУказаныВручную : Булево
НаправлениеДеятельности : Справочник.Направление деятельности
ЕстьКиЗГИСМ : Булево
ЕстьМаркируемаяПродукцияГИСМ : Булево
УдалитьЕстьАлкогольнаяПродукцияДляСписанияЕГАИС : Булево
ДокументОснование : Документ.Регистрация дефекта\rДокумент.Приобретение товаров и услуг
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
КодСтроки : Число 10, 0
СтатусУказанияСерий : Число 2, 0
СтатьяРасходов : Статья расходов\rСтатья актива/пассива
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ЗаказНаВнутреннееПотребление : Документ.Внутреннее потребление товаров\rДокумент.Заказ на производство\rДокумент.Заказ материалов в производство\r...
ФизическоеЛицо : Справочник.Физическое лицо
ИдентификаторСтроки : Строка
КатегорияЭксплуатации : Справочник.Категории эксплуатации
ПартияТМЦВЭксплуатации : Справочник.Партии ТМЦ в эксплуатации
ИнвентарныйНомер : Строка
Серия : Справочник.Серия номенклатуры
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
Назначение : Справочник.Назначение
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
..Табличная часть \n ВидыЗапасов..
АналитикаУчетаНоменклатуры : Справочник.Номенклатура\rСправочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
СтатьяРасходов : Статья расходов\rСтатья актива/пассива
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ИдентификаторСтроки : Строка
ФизическоеЛицо : Справочник.Физическое лицо
ОбъектЭксплуатации : Справочник.Объект эксплуатации
ВидЗапасовПолучателя : Справочник.Вид запасов
Серия : Справочник.Серия номенклатуры
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
Назначение : Справочник.Назначение
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
..Табличная часть \n Серии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
..Движения..
ТоварыКОтгрузке : Остатки
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ТоварыКОформлениюОтчетовКомитенту : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНОСиНМА : Остатки
РасходыПриУСНМатериалы : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
Международный : РегистрБухгалтерии
РасходыПриУСНТовары : Остатки
НДСЗаписиКнигиПродаж : Обороты
ТоварыОрганизацийКПередаче : Остатки
КнигаУчетаДоходовИРасходов : Обороты
СвободныеОстатки : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
ТМЦВЭксплуатации : Обороты
ПартииПроизводственныхЗатрат : Остатки
ЗаказыНаВнутреннееПотребление : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
