@startuml ОрдерНаОтражениеНедостачТоваров
'!include templates.wsd
'..\include templates.wsd
class Документ.ОрдерНаОтражениеНедостачТоваров as "Ордер на отражение недостач товаров" <<Документы>>
{
..Реквизиты..
Комментарий : Строка
Ответственный : Справочник.Пользователь
Помещение : Справочник.Помещение
Склад : Справочник.Склад (складская территория)
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Упаковка : Справочник.Упаковка
Количество : Число 15, 3
КоличествоУпаковок : Число 15, 3
Ячейка : Справочник.Складская ячейка
СтатусУказанияСерий : Число 2, 0
Серия : Справочник.Серия номенклатуры
..Движения..
ДвиженияСерийТоваров : Обороты
ТоварыКОформлениюИзлишковНедостач : Остатки
ТоварыНаСкладах : Остатки
ОбеспечениеЗаказов : Остатки
СвободныеОстатки : Остатки
ТоварыВЯчейках : Остатки
}
@enduml
