@startuml УстановкаКвотАссортимента
'!include templates.wsd
'..\include templates.wsd
class Документ.УстановкаКвотАссортимента as "Установка квот ассортимента" <<Документы>>
{
..Реквизиты..
ОбъектПланирования : Справочник.Форматы магазинов\rСправочник.Склад (складская территория)
ДатаНачалаДействия : Дата
Ответственный : Справочник.Пользователь
Комментарий : Строка
КоллекцияНоменклатуры : Справочник.Коллекция (сезон)
КвотаВсего : Число 10, 0
..Табличная часть \n ТоварныеКатегории..
ТоварнаяКатегория : Справочник.Товарные категории
Марка : Справочник.Марка (бренд)
Квота : Число 10, 0
ПроцентОтклонения : Число 3, 0
..Движения..
КвотыАссортимента : РегистрСведений
}
@enduml
