@startuml Совмещение
'!include templates.wsd
'..\include templates.wsd
class Документ.Совмещение as "Совмещение должностей" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
СовмещающийСотрудник : Справочник.Сотрудник
ДатаНачала : Дата
ДатаОкончания : Дата
ПричинаСовмещения : Причины совмещения
РазмерДоплатыУтвержден : Булево
Начисление : Начисление
РазмерДоплаты : Число 15, 3
ФОТ : Число 15, 3
ФиксРасчет : Булево
РассчитыватьДоплату : Булево
СпособРасчетаДоплаты : Способы расчета доплаты за совмещение
ОтсутствующийСотрудник : Справочник.Сотрудник
СовмещаемаяДолжность : Справочник.Позиция
ПроцентДоплаты : Число 15, 2
ИсправленныйДокумент : Документ.Совмещение должностей
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОтношениеКЕНВД : Отношение к ЕНВД затрат на зарплату
СовокупнаяТарифнаяСтавка : Число 15, 5
ВидТарифнойСтавки : Виды тарифных ставок
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ФОТСовмещаемый..
Начисление : Начисление
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Размер : Число 15, 2
Использовать : Булево
..Табличная часть \n ФОТСовмещающегоСотрудника..
Начисление : Начисление
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Размер : Число 15, 2
Использовать : Булево
..Табличная часть \n НачисленияСотрудника..
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Начисление : Начисление
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Действие : Действия с начислениями и удержаниями
Размер : Число 15, 3
..Табличная часть \n Показатели..
Показатель : Справочник.Показатель
Значение : Число 15, 5
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников : РегистрСведений
ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
БухучетПлановыхНачислений : РегистрСведений
ПлановыеНачисления : РегистрСведений
}
@enduml
