@startuml ИзменениеКвалификационногоРазряда
'!include templates.wsd
'..\include templates.wsd
class Документ.ИзменениеКвалификационногоРазряда as "Изменение квалификационного разряда (категории) сотрудника" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ДатаИзменения : Дата
РазрядКатегория : Справочник.Квалификационный разряд (категория)
Показатель : Справочник.Показатель
ЗначениеПоказателя : Число 15, 5
НачисленияУтверждены : Булево
СовокупнаяТарифнаяСтавка : Число 15, 5
ВидТарифнойСтавки : Виды тарифных ставок
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Начисления..
Начисление : Начисление
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Размер : Число 15, 2
..Движения..
УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников : РегистрСведений
РазрядыКатегорииСотрудников : РегистрСведений
ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
БухучетПлановыхНачислений : РегистрСведений
ПлановыеНачисления : РегистрСведений
}
@enduml
