@startuml ПризПодарок
'!include templates.wsd
'..\include templates.wsd
class Документ.ПризПодарок as "Приз, подарок" <<Документы>>
{
..Реквизиты..
ПериодРегистрации : Дата
Организация : Справочник.Организация
ВидДоходаСтраховыеВзносы : Справочник.Вид дохода по страховым взносам
ВидПризаПодарка : Виды призов и подарков
ДатаПолученияДохода : Дата
ИсправленныйДокумент : Документ.Приз, подарок
КодВычетаНДФЛ : Справочник.Вид вычетов НДФЛ
КодДоходаНДФЛ : Справочник.Вид дохода НДФЛ
МотивПоощрения : Строка
Начислено : Число 13, 2
Удержано : Число 13, 2
ОтношениеКЕНВД : Отношение к ЕНВД затрат на зарплату
ПредусмотреноКолдоговором : Булево
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
СтатьяРасходов : Справочник.Статья расходов
СтатьяФинансирования : Справочник.Статья финансирования
ДолжностьРуководителя : Справочник.Должность
Руководитель : Справочник.Физическое лицо
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
УдалитьВидДоходаСтраховыеВзносы : Справочник.(не используется) Виды доходов (взносы)
УдалитьКодВычетаНДФЛ : Справочник.(не используется) Виды вычетов НДФЛ
УдалитьКодДоходаНДФЛ : Справочник.(не используется) Виды доходов НДФЛ
УдалитьОблагаетсяЕНВД : Булево
УдалитьСотрудник : Справочник.Сотрудник
УдалитьСуммаВычетаНДФЛ : Число 13, 0
УдалитьСуммаДохода : Число 13, 2
УдалитьСуммаНДФЛ : Число 13, 0
УдалитьФизическоеЛицо : Справочник.Физическое лицо
..Табличная часть \n Начисления..
Сотрудник : Справочник.Сотрудник
Результат : Число 15, 2
Подразделение : Справочник.Подразделение
ФиксРасчет : Булево
ФиксЗаполнение : Булево
СуммаВычета : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
ФиксСуммаВычета : Булево
СуммаНДФЛ : Число 10, 0
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Табличная часть \n НачисленияПерерасчет..
Сотрудник : Справочник.Сотрудник
Результат : Число 15, 2
Подразделение : Справочник.Подразделение
ФиксРасчет : Булево
ФиксЗаполнение : Булево
СуммаВычета : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
ФиксСуммаВычета : Булево
СуммаНДФЛ : Число 10, 0
Сторно : Булево
СторнируемыйДокумент : Документ.Приз, подарок\rДокумент.Простой сотрудников\rДокумент.Отпуск без сохранения оплаты списком\r...
ПериодДействия : Дата
..Движения..
РасчетыНалогоплательщиковСБюджетомПоНДФЛ : Остатки
ВзаиморасчетыССотрудниками : Остатки
НачисленияУдержанияПоСотрудникам : Обороты
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
СведенияОДоходахСтраховыеВзносы : Обороты
СведенияОДоходахНДФЛ : Обороты
БухучетНачисленияУдержанияПоСотрудникам : Обороты
ЗарплатаКВыплате : Остатки
ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаФСС : Обороты
}
@enduml
