@startuml БронированиеГражданПребывающихВЗапасе
'!include templates.wsd
'..\include templates.wsd
class Документ.БронированиеГражданПребывающихВЗапасе as "Бронирование граждан" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
ФизическоеЛицо : Справочник.Физическое лицо
..Движения..
БронированиеСотрудников : РегистрСведений
}
@enduml
