@startuml УведомлениеОПоступленииМаркированныхТоваровГИСМ
'!include templates.wsd
'..\include templates.wsd
class Документ.УведомлениеОПоступленииМаркированныхТоваровГИСМ as "Уведомление о поступлении маркированных товаров" <<Документы>>
{
..Реквизиты..
НомерГИСМ : Число 19, 0
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Контрагент : Справочник.Контрагент
ВидОборотаТовара : Вид оборота товара ГИСМ
Ответственный : Справочник.Пользователь
Комментарий : Строка
GLNКонтрагента : Строка
НомерВходящегоДокумента : Строка
ДатаВходящегоДокумента : Дата
..Табличная часть \n НомераКиЗ..
НомерКиЗ : Строка
RFIDTID : Строка
RFIDEPC : Строка
Стоимость : Число 15, 2
СуммаНДС : Число 15, 2
СостояниеПодтверждения : Состояния отправки подтверждения ГИСМ
ДокументПоступления : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг
}
@enduml
