@startuml ЗаявкаНаВозвратТоваровОтКлиента
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаявкаНаВозвратТоваровОтКлиента as "Заявка на возврат товаров от клиента" <<Документы>>
{
..Реквизиты..
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
Организация : Справочник.Организация
Соглашение : Справочник.Соглашение об условиях продаж
Сделка : Справочник.Сделка с клиентом
Склад : Справочник.Склад (складская территория)
Валюта : Справочник.Валюта
Менеджер : Справочник.Пользователь
ЦенаВключаетНДС : Булево
Статус : Статусы заявок на возврат товаров от клиентов
СуммаДокумента : Число 15, 2
СуммаЗамены : Число 15, 2
ДополнительнаяИнформация : Строка
ЖелаемаяДатаПоступления : Дата
ВозвращаемыеТоварыМаксимальныйКодСтроки : Число 10, 0
Согласован : Булево
ДатаПервогоПоступления : Дата
ДатаСогласования : Дата
НалогообложениеНДС : Типы налогообложения НДС
ХозяйственнаяОперация : Хозяйственные операции
ДокументРеализации : Документ.Реализация товаров и услуг\rДокумент.Отчет о розничных продажах
ЖелаемаяДатаОтгрузки : Дата
ДатаОтгрузки : Дата
АдресДоставки : Строка
СкидкиРассчитаны : Булево
НеОтгружатьЧастями : Булево
ФормаОплаты : Формы оплаты
БанковскийСчет : Справочник.Банковский счет организации
БанковскийСчетКонтрагента : Справочник.Банковский счет
Касса : Справочник.Касса
ГрафикОплаты : Справочник.График оплаты
СуммаАвансаДоОбеспечения : Число 15, 2
СуммаПредоплатыДоОтгрузки : Число 15, 2
ЗаменяющиеТоварыМаксимальныйКодСтроки : Число 10, 0
ЧекККМ : Документ.Чек ККМ
Комментарий : Строка
ВозвратПорчи : Булево
Грузоотправитель : Справочник.Контрагент
Грузополучатель : Справочник.Контрагент
БанковскийСчетГрузоотправителя : Справочник.Банковский счет
БанковскийСчетГрузополучателя : Справочник.Банковский счет
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
КартаЛояльности : Справочник.Карты лояльности
Договор : Справочник.Договор с контрагентом
ДатаПоступления : Дата
ПоступлениеОднойДатой : Булево
ПорядокРасчетов : Детализация расчетов
ВидДокументаПокупателя : Справочник.Вид документа физических лиц
СерияДокументаПокупателя : Строка
НомерДокументаПокупателя : Строка
ДатаВыдачиДокументаПокупателя : Дата
СрокДействияДокументаПокупателя : Дата
КемВыданДокументПокупателя : Строка
КодПодразделенияДокументаПокупателя : Строка
ДатаРожденияПокупателя : Дата
Покупатель : Строка
ПричинаВозврата : Строка
СпособДоставки : Способы доставки
ПеревозчикПартнер : Справочник.Партнер
ЗонаДоставки : Справочник.Зоны доставки
ВремяДоставкиС : Дата
ВремяДоставкиПо : Дата
АдресДоставкиПеревозчика : Строка
АдресДоставкиЗначенияПолей : Строка
АдресДоставкиПеревозчикаЗначенияПолей : Строка
ДополнительнаяИнформацияПоДоставке : Строка
Назначение : Справочник.Назначение
Подразделение : Справочник.Подразделение
КонтактноеЛицо : Справочник.Контактное лицо
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
ВернутьМногооборотнуюТару : Булево
СрокВозвратаМногооборотнойТары : Число 3, 0
СостояниеЗаполненияМногооборотнойТары : Состояния заполнения многооборотной тары
СуммаВозвратнойТары : Число 15, 2
ТребуетсяЗалогЗаТару : Булево
СпособКомпенсации : Способы компенсации возвратов товаров
ДатаВозвратаДенежныхСредств : Дата
Приоритет : Справочник.Приоритет
ИдентификаторПлатежа : Строка
ЗаполнятьЦеныЗаменяющихТоваровПоВозвращаемым : Булево
ОсобыеУсловияПеревозки : Булево
ОсобыеУсловияПеревозкиОписание : Строка
НаправлениеДеятельности : Справочник.Направление деятельности
ПорядокОплаты : Порядок оплаты
ВариантПриемкиТоваров : Варианты приемки товаров
..Табличная часть \n ВозвращаемыеТовары..
Номенклатура : Справочник.Номенклатура
НоменклатураОприходование : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
ХарактеристикаОприходование : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
ДатаПоступления : Дата
Количество : Число 15, 3
ВидЦены : Справочник.Вид цены
Цена : Число 15, 2
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
КодСтроки : Число 10, 0
Порча : Булево
СтатусУказанияСерий : Число 2, 0
Отменено : Булево
ДокументРеализации : Документ.Реализация товаров и услуг\rДокумент.Отчет о розничных продажах
Серия : Справочник.Серия номенклатуры
НоменклатураНабора : Справочник.Номенклатура
ХарактеристикаНабора : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
..Табличная часть \n ЗаменяющиеТовары..
ДатаОтгрузки : Дата
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ВидЦены : Справочник.Вид цены
Цена : Число 15, 2
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
ПроцентРучнойСкидки : Число 5, 2
СуммаРучнойСкидки : Число 15, 2
ПроцентАвтоматическойСкидки : Число 5, 2
СуммаАвтоматическойСкидки : Число 15, 2
КодСтроки : Число 10, 0
Отменено : Булево
КлючСвязи : Число 10, 0
ПричинаОтмены : Справочник.Причина отмены заказов клиентов
СрокПоставки : Число 10, 0
Содержание : Строка
СтатусУказанияСерий : Число 2, 0
ВариантОбеспечения : Варианты обеспечения
Серия : Справочник.Серия номенклатуры
НоменклатураНабора : Справочник.Номенклатура
ХарактеристикаНабора : Справочник.Характеристика номенклатуры
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n СкидкиНаценки..
КлючСвязи : Число 10, 0
СкидкаНаценка : Справочник.Скидки (наценки)
Сумма : Число 15, 2
НапомнитьПозже : Булево
..Табличная часть \n ЭтапыГрафикаОплаты..
ВариантОплаты : Варианты оплаты клиентом
ДатаПлатежа : Дата
ПроцентПлатежа : Число 5, 2
СуммаПлатежа : Число 15, 2
ПроцентЗалогаЗаТару : Число 5, 2
СуммаЗалогаЗаТару : Число 15, 2
СуммаОтклоненияМерныхТоваров : Число 15, 2
..Табличная часть \n ВозвращаемыеСерии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
НоменклатураОприходование : Справочник.Номенклатура
ХарактеристикаОприходование : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
..Движения..
ТоварыКОтгрузке : Остатки
ЗаявкиНаВозвратТоваровОтКлиентов : Остатки
РасчетыСКлиентами : Остатки
ГрафикОтгрузкиТоваров : Остатки
ФактическиеДанныеБюджетирования : Обороты
ЗаказыКлиентов : Остатки
ОбеспечениеЗаказов : Остатки
ДвижениеТоваров : Обороты
ОбеспечениеЗаказовРаботами : Остатки
РасчетыСКлиентамиПоДокументам : Остатки
СвободныеОстатки : Остатки
ГрафикПоступленияТоваров : Остатки
ТоварыКПоступлению : Остатки
}
@enduml
