@startuml ЛистКассовойКниги
'!include templates.wsd
'..\include templates.wsd
class Документ.ЛистКассовойКниги as "Лист кассовой книги" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
КассоваяКнига : Справочник.Кассовая книга
Ответственный : Справочник.Пользователь
СуммаПоступления : Число 15, 2
СуммаВыдачи : Число 15, 2
СуммаКонечныйОстаток : Число 15, 2
КоличествоДокументовНаЛисте : Число 10, 0
ТипЛиста : Типы листов кассовой книги
НомераЛистов : Строка
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
..Табличная часть \n КассовыеОрдера..
НомерЛиста : Число 10, 0
Документ : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер
Приход : Число 15, 2
Расход : Число 15, 2
Валюта : Справочник.Валюта
КорреспондирующийСчет : Строка
}
@enduml
