@startuml ЭлектронныйДокументВходящий
'!include templates.wsd
'..\include templates.wsd
class Документ.ЭлектронныйДокументВходящий as "Входящий электронный документ" <<Документы>>
{
..Реквизиты..
ВерсияРегламентаЭДО : Версии регламента обмена1 С
ВидЭД : Виды электронных документов
ДатаДокументаОтправителя : Дата
ДатаИзмененияСостоянияЭДО : Дата
ДоговорКонтрагента : Справочник.Договор с контрагентом
Комментарий : Строка
Контрагент : Справочник.Организация\rСправочник.Контрагент
НаименованиеДокументаОтправителя : Строка
НастройкаЭДО : Справочник.Настройка ЭДО
НомерВерсииЭД : Число 3, 0
НомерДокументаОтправителя : Строка
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
ПричинаОтклонения : Строка
ПрофильНастроекЭДО : Справочник.Профиль настроек ЭДО
Прочитан : Булево
СостояниеЭДО : Состояния версий электронных документов
СуммаДокумента : Число 15, 2
Текст : Строка
ТипДокумента : Типы ЭД
ТипЭлементаВерсииЭД : Типы элементов версии электронных документов
ТребуетсяИзвещение : Булево
ТребуетсяПодтверждение : Булево
УникальныйИД : Строка
..Табличная часть \n ДокументыОснования..
ДокументОснование : Документ.Входящий электронный документ\rДокумент.Возврат товаров от клиента\rДокумент.Исходящий электронный документ\r...
СпособОбработки : Строка
..Табличная часть \n ИдентификаторыОснованийВладельцаФайла..
ИдентификаторДокументаОснования : Строка
ИдентификаторЭДДокументаОснования : Строка
}
@enduml
