@startuml ПересортицаТоваров
'!include templates.wsd
'..\include templates.wsd
class Документ.ПересортицаТоваров as "Пересортица товаров" <<Документы>>
{
..Реквизиты..
Комментарий : Строка
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
Подразделение : Справочник.Подразделение
Склад : Справочник.Склад (складская территория)
ВидЦены : Справочник.Вид цены
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
СтатьяРасходов : Статья расходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
СтатьяДоходов : Статьи доходов
ПриходоватьТоварыПоСебестоимостиСписания : Булево
ВидыЗапасовУказаныВручную : Булево
ПересчетТоваров : Документ.Пересчет товаров
НаправлениеДеятельности : Справочник.Направление деятельности
ВидДеятельностиНДС : Типы налогообложения НДС
УдалитьЕстьАлкогольнаяПродукцияДляПостановкиНаБалансЕГАИС : Булево
УдалитьЕстьАлкогольнаяПродукцияДляСписанияЕГАИС : Булево
Валюта : Справочник.Валюта
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
НоменклатураОприходование : Справочник.Номенклатура
ХарактеристикаОприходование : Справочник.Характеристика номенклатуры
НазначениеОприходование : Справочник.Назначение
СерияОприходование : Справочник.Серия номенклатуры
СтатусУказанияСерийОприходование : Число 2, 0
НомерГТД : Справочник.Номер ГТД
Цена : Число 15, 2
Количество : Число 15, 3
ВидЗапасов : Справочник.Вид запасов
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
АналитикаУчетаНоменклатурыОприходование : Справочник.Ключ аналитики учета номенклатуры
..Табличная часть \n ВидыЗапасов..
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
УдалитьНоменклатураОприходование : Справочник.Номенклатура
УдалитьХарактеристикаОприходование : Справочник.Характеристика номенклатуры
Сумма : Число 15, 2
УдалитьАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
ВидЗапасовОприходование : Справочник.Вид запасов
ИдентификаторСтроки : Строка
УдалитьСерияОприходование : Справочник.Серия номенклатуры
УдалитьНазначениеОприходование : Справочник.Назначение
АналитикаУчетаНоменклатурыОприходование : Справочник.Ключ аналитики учета номенклатуры
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ПрочиеДоходы : Остатки
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
ТоварыКОформлениюИзлишковНедостач : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ТоварыКОформлениюОтчетовКомитенту : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
Международный : РегистрБухгалтерии
НДСЗаписиКнигиПродаж : Обороты
ТоварыОрганизацийКПередаче : Остатки
СвободныеОстатки : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
ПартииЗатратНаВыпуск : Остатки
}
@enduml
