@startuml НачислениеЗаПервуюПоловинуМесяца
'!include templates.wsd
'..\include templates.wsd
class Документ.НачислениеЗаПервуюПоловинуМесяца as "Начисление за первую половину месяца" <<Документы>>
{
..Реквизиты..
МесяцНачисления : Дата
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ОкончаниеПериодаНачисления : Дата
Начислено : Число 13, 2
Удержано : Число 13, 2
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Начисления..
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Результат : Число 13, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
СуммаВычета : Число 15, 2
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ВидУчетаВремени : Справочник.Вид рабочего времени
ВремяВЧасах : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ПериодРегистрацииВремени : Дата
ОплаченоДней : Число 7, 2
ОплаченоЧасов : Число 7, 2
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ПериодДействия : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n НДФЛ..
ФизическоеЛицо : Справочник.Физическое лицо
МесяцНалоговогоПериода : Дата
Подразделение : Справочник.Территория\rСправочник.Подразделение
Налог : Число 10, 0
ЗачтеноАвансовыхПлатежей : Число 10, 0
УдалитьНалогКЗачетуВозврату : Число 10, 0
ПримененныйВычетЛичный : Число 12, 2
ПримененныйВычетЛичныйКодВычета : Справочник.Вид вычетов НДФЛ
УдалитьПримененныйВычетЛичныйКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
ПримененныйВычетЛичныйКЗачетуВозврату : Число 12, 2
ПримененныйВычетЛичныйКЗачетуВозвратуКодВычета : Справочник.Вид вычетов НДФЛ
УдалитьПримененныйВычетЛичныйКЗачетуВозвратуКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
ИдентификаторСтрокиНДФЛ : Число 7, 0
ФиксСтрока : Булево
ФиксРасчет : Булево
КатегорияДохода : Категории доходов НДФЛ
..Табличная часть \n Показатели..
Показатель : Справочник.Показатель
Значение : Число 15, 5
ИдентификаторСтрокиВидаРасчета : Число 7, 0
..Табличная часть \n УдалитьПособия..
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Результат : Число 15, 2
РезультатВТомЧислеЗаСчетФБ : Число 15, 2
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ОплаченоДней : Число 7, 2
ОплаченоЧасов : Число 7, 2
СуммаВсегоПоУходуЗаПервымРебенком : Число 15, 2
СуммаСверхНормПоУходуЗаПервымРебенком : Число 15, 2
СуммаВсегоПоУходуЗаВторымРебенком : Число 15, 2
СуммаСверхНормПоУходуЗаВторымРебенком : Число 15, 2
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ПериодРегистрацииВремени : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n ПримененныеВычетыНаДетейИИмущественные..
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
РазмерВычета : Число 12, 2
ИдентификаторСтрокиНДФЛ : Число 7, 0
..Табличная часть \n Удержания..
ФизическоеЛицо : Справочник.Физическое лицо
ДатаНачала : Дата
ДатаОкончания : Дата
ДокументОснование : Документ.Удержание по прочим операциям\rДокумент.Удержание добровольных взносов в НПФ\rДокумент.Удержание профсоюзных взносов\r...
Получатель : Справочник.Контрагент
ПлатежныйАгент : Справочник.Контрагент
Удержание : Удержание
ФиксРасчет : Булево
Результат : Число 13, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ФиксСтрока : Булево
ФиксЗаполнение : Булево
Сотрудник : Справочник.Сотрудник
ФиксСторно : Булево
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Табличная часть \n РаспределениеРезультатовНачислений..
ИдентификаторСтроки : Число 7, 0
Территория : Справочник.Территория
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОблагаетсяЕНВД : Булево
Результат : Число 13, 2
..Табличная часть \n РаспределениеРезультатовУдержаний..
ИдентификаторСтроки : Число 7, 0
ВидУдержания : Виды особых начислений и удержаний\rУдержание
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
Результат : Число 13, 2
..Табличная часть \n РаспределениеПоТерриториямУсловиямТруда..
ИдентификаторСтроки : Число 7, 0
Территория : Справочник.Территория
УсловияТруда : Справочник.Условия труда
ДоляРаспределения : Число 15, 5
Результат : Число 15, 2
ИдентификаторСтрокиПоказателей : Число 7, 0
СуммаВычета : Число 13, 0
..Движения..
БухучетНачисленияУдержанияПоСотрудникамАвансом : Обороты
ОтработанноеВремяПоСотрудникамАвансом : Обороты
ЗарплатаКВыплатеАвансом : Остатки
НачисленияУдержанияПоСотрудникамАвансом : Обороты
}
@enduml
