@startuml ИндексацияЗаработка
'!include templates.wsd
'..\include templates.wsd
class Документ.ИндексацияЗаработка as "Индексация заработка" <<Документы>>
{
..Реквизиты..
МесяцИндексации : Дата
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
КоэффициентИндексации : Число 5, 4
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ГлавныйБухгалтер : Справочник.Физическое лицо
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
ВидИндексацииГосударственныхСлужащих : Строка
ИндексацияВоеннослужащих : Булево
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Сотрудник
КоэффициентИндексации : Число 9, 8
ФиксСтрока : Булево
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Табличная часть \n Показатели..
Показатель : Справочник.Показатель
СпособОкругления : Справочник.Способ округления
..Табличная часть \n ЗначенияПоказателей..
Сотрудник : Справочник.Сотрудник
Показатель : Справочник.Показатель
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Значение : Число 15, 5
КоэффициентИндексации : Число 9, 8
..Табличная часть \n НачисленияСотрудников..
Сотрудник : Справочник.Сотрудник
Начисление : Начисление
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Размер : Число 15, 2
..Табличная часть \n ПересчетТарифныхСтавок..
Сотрудник : Справочник.Сотрудник
СовокупнаяТарифнаяСтавка : Число 15, 5
ВидТарифнойСтавки : Виды тарифных ставок
..Движения..
УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников : РегистрСведений
КоэффициентИндексацииЗаработка : РегистрСведений
ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
БухучетПлановыхНачислений : РегистрСведений
ПлановыеНачисления : РегистрСведений
}
@enduml
