@startuml ПоступлениеСырьяОтДавальца
'!include templates.wsd
'..\include templates.wsd
class Документ.ПоступлениеСырьяОтДавальца as "Поступление сырья от давальца" <<Документы>>
{
..Реквизиты..
Партнер : Справочник.Партнер
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Склад : Справочник.Склад (складская территория)
Контрагент : Справочник.Контрагент
Менеджер : Справочник.Пользователь
ЗаказДавальца : Документ.Заказ давальца
Комментарий : Строка
Согласован : Булево
БанковскийСчетОрганизации : Справочник.Банковский счет организации
НомерВходящегоДокумента : Строка
ДатаВходящегоДокумента : Дата
Грузоотправитель : Справочник.Контрагент
БанковскийСчетКонтрагента : Справочник.Банковский счет
БанковскийСчетГрузоотправителя : Справочник.Банковский счет
Принял : Справочник.Физическое лицо
ПринялДолжность : Строка
ПоступлениеПоЗаказам : Булево
Договор : Справочник.Договор с контрагентом
Автор : Справочник.Пользователь
Руководитель : Справочник.Лицо с правом подписи
СуммаДокумента : Число 15, 2
Валюта : Справочник.Валюта
ВернутьМногооборотнуюТару : Булево
ДатаВозвратаМногооборотнойТары : Дата
СостояниеЗаполненияМногооборотнойТары : Состояния заполнения многооборотной тары
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
Сделка : Справочник.Сделка с клиентом
ТребуетсяЗалогЗаТару : Булево
ВариантПриемкиТоваров : Варианты приемки товаров
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
КодСтроки : Число 10, 0
Склад : Справочник.Склад (складская территория)
ЗаказДавальца : Документ.Заказ давальца
Сертификат : Строка
НомерПаспорта : Строка
СтатусУказанияСерий : Число 2, 0
ВидЗапасов : Справочник.Вид запасов
ИдентификаторСтроки : Строка
УдалитьАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
Цена : Число 15, 2
Сумма : Число 15, 2
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
Серия : Справочник.Серия номенклатуры
..Табличная часть \n Серии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Склад : Справочник.Склад (складская территория)
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
Международный : РегистрБухгалтерии
ДвижениеТоваров : Обороты
СвободныеОстатки : Остатки
ТоварыОрганизаций : Остатки
ПринятаяВозвратнаяТара : Остатки
ЗаказыПоставщикам : Остатки
ПартииПроизводственныхЗатрат : Остатки
ТоварыКПоступлению : Остатки
}
@enduml
