@startuml КорректировкаНазначенияТоваров
'!include templates.wsd
'..\include templates.wsd
class Документ.КорректировкаНазначенияТоваров as "Корректировка назначения товаров" <<Документы>>
{
..Реквизиты..
Комментарий : Строка
Организация : Справочник.Организация
ВидыЗапасовУказаныВручную : Булево
ВидОперации : Виды операций корректировки назначения
ДокументПоРаспоряжению : Булево
Назначение : Справочник.Назначение
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Склад : Справочник.Склад (складская территория)
Помещение : Справочник.Помещение
Ячейка : Справочник.Складская ячейка
ИсходноеНазначение : Справочник.Назначение
НовоеНазначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ИсходноеНазначениеДвиженияПоСкладскимРегистрам : Булево
Заказ : Документ.Сторнирование начислений\rДокумент.Внутреннее потребление товаров\rДокумент.Назначение планового начисления\r...
АналитикаУчетаНоменклатурыОприходование : Справочник.Ключ аналитики учета номенклатуры
..Табличная часть \n ВидыЗапасов..
ВидЗапасов : Справочник.Вид запасов
АналитикаУчетаНоменклатурыОприходование : Справочник.Ключ аналитики учета номенклатуры
НомерГТД : Справочник.Номер ГТД
ВидЗапасовОприходование : Справочник.Вид запасов
Количество : Число 15, 3
УдалитьНазначение : Справочник.Назначение
УдалитьНовоеНазначение : Справочник.Назначение
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
УдалитьОрганизация : Справочник.Организация
НовоеНазначениеПустое : Булево
..Движения..
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
СебестоимостьТоваров : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
Международный : РегистрБухгалтерии
НДСЗаписиКнигиПродаж : Обороты
СвободныеОстатки : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
ТоварыОрганизаций : Остатки
ТоварыВЯчейках : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
