@startuml ТабельУчетаРабочегоВремени
'!include templates.wsd
'..\include templates.wsd
class Документ.ТабельУчетаРабочегоВремени as "Табель учета рабочего времени" <<Документы>>
{
..Реквизиты..
ПериодРегистрации : Дата
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ДатаНачалаПериода : Дата
ДатаОкончанияПериода : Дата
ПериодВводаДанныхОВремени : Периоды ввода данных о времени
ИсправленныйДокумент : Документ.Табель
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
РаботникКадровойСлужбы : Справочник.Физическое лицо
ДолжностьРаботникаКадровойСлужбы : Справочник.Должность
Исполнитель : Справочник.Физическое лицо
ДолжностьИсполнителя : Справочник.Должность
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ДанныеОВремени..
Сотрудник : Справочник.Сотрудник
Часов1 : Число 5, 2
Часов2 : Число 5, 2
Часов3 : Число 5, 2
Часов4 : Число 5, 2
Часов5 : Число 5, 2
Часов6 : Число 5, 2
Часов7 : Число 5, 2
Часов8 : Число 5, 2
Часов9 : Число 5, 2
Часов10 : Число 5, 2
Часов11 : Число 5, 2
Часов12 : Число 5, 2
Часов13 : Число 5, 2
Часов14 : Число 5, 2
Часов15 : Число 5, 2
Часов16 : Число 5, 2
Часов17 : Число 5, 2
Часов18 : Число 5, 2
Часов19 : Число 5, 2
Часов20 : Число 5, 2
Часов21 : Число 5, 2
Часов22 : Число 5, 2
Часов23 : Число 5, 2
Часов24 : Число 5, 2
Часов25 : Число 5, 2
Часов26 : Число 5, 2
Часов27 : Число 5, 2
Часов28 : Число 5, 2
Часов29 : Число 5, 2
Часов30 : Число 5, 2
Часов31 : Число 5, 2
ВидВремени1 : Справочник.Вид рабочего времени
ВидВремени2 : Справочник.Вид рабочего времени
ВидВремени3 : Справочник.Вид рабочего времени
ВидВремени4 : Справочник.Вид рабочего времени
ВидВремени5 : Справочник.Вид рабочего времени
ВидВремени6 : Справочник.Вид рабочего времени
ВидВремени7 : Справочник.Вид рабочего времени
ВидВремени8 : Справочник.Вид рабочего времени
ВидВремени9 : Справочник.Вид рабочего времени
ВидВремени10 : Справочник.Вид рабочего времени
ВидВремени11 : Справочник.Вид рабочего времени
ВидВремени12 : Справочник.Вид рабочего времени
ВидВремени13 : Справочник.Вид рабочего времени
ВидВремени14 : Справочник.Вид рабочего времени
ВидВремени15 : Справочник.Вид рабочего времени
ВидВремени16 : Справочник.Вид рабочего времени
ВидВремени17 : Справочник.Вид рабочего времени
ВидВремени18 : Справочник.Вид рабочего времени
ВидВремени19 : Справочник.Вид рабочего времени
ВидВремени20 : Справочник.Вид рабочего времени
ВидВремени21 : Справочник.Вид рабочего времени
ВидВремени22 : Справочник.Вид рабочего времени
ВидВремени23 : Справочник.Вид рабочего времени
ВидВремени24 : Справочник.Вид рабочего времени
ВидВремени25 : Справочник.Вид рабочего времени
ВидВремени26 : Справочник.Вид рабочего времени
ВидВремени27 : Справочник.Вид рабочего времени
ВидВремени28 : Справочник.Вид рабочего времени
ВидВремени29 : Справочник.Вид рабочего времени
ВидВремени30 : Справочник.Вид рабочего времени
ВидВремени31 : Справочник.Вид рабочего времени
Территория1 : Справочник.Территория
Территория2 : Справочник.Территория
Территория3 : Справочник.Территория
Территория4 : Справочник.Территория
Территория5 : Справочник.Территория
Территория6 : Справочник.Территория
Территория7 : Справочник.Территория
Территория8 : Справочник.Территория
Территория9 : Справочник.Территория
Территория10 : Справочник.Территория
Территория11 : Справочник.Территория
Территория12 : Справочник.Территория
Территория13 : Справочник.Территория
Территория14 : Справочник.Территория
Территория15 : Справочник.Территория
Территория16 : Справочник.Территория
Территория17 : Справочник.Территория
Территория18 : Справочник.Территория
Территория19 : Справочник.Территория
Территория20 : Справочник.Территория
Территория21 : Справочник.Территория
Территория22 : Справочник.Территория
Территория23 : Справочник.Территория
Территория24 : Справочник.Территория
Территория25 : Справочник.Территория
Территория26 : Справочник.Территория
Территория27 : Справочник.Территория
Территория28 : Справочник.Территория
Территория29 : Справочник.Территория
Территория30 : Справочник.Территория
Территория31 : Справочник.Территория
УсловияТруда1 : Справочник.Условия труда
УсловияТруда2 : Справочник.Условия труда
УсловияТруда3 : Справочник.Условия труда
УсловияТруда4 : Справочник.Условия труда
УсловияТруда5 : Справочник.Условия труда
УсловияТруда6 : Справочник.Условия труда
УсловияТруда7 : Справочник.Условия труда
УсловияТруда8 : Справочник.Условия труда
УсловияТруда9 : Справочник.Условия труда
УсловияТруда10 : Справочник.Условия труда
УсловияТруда11 : Справочник.Условия труда
УсловияТруда12 : Справочник.Условия труда
УсловияТруда13 : Справочник.Условия труда
УсловияТруда14 : Справочник.Условия труда
УсловияТруда15 : Справочник.Условия труда
УсловияТруда16 : Справочник.Условия труда
УсловияТруда17 : Справочник.Условия труда
УсловияТруда18 : Справочник.Условия труда
УсловияТруда19 : Справочник.Условия труда
УсловияТруда20 : Справочник.Условия труда
УсловияТруда21 : Справочник.Условия труда
УсловияТруда22 : Справочник.Условия труда
УсловияТруда23 : Справочник.Условия труда
УсловияТруда24 : Справочник.Условия труда
УсловияТруда25 : Справочник.Условия труда
УсловияТруда26 : Справочник.Условия труда
УсловияТруда27 : Справочник.Условия труда
УсловияТруда28 : Справочник.Условия труда
УсловияТруда29 : Справочник.Условия труда
УсловияТруда30 : Справочник.Условия труда
УсловияТруда31 : Справочник.Условия труда
..Табличная часть \n СотрудникиСИсправлениями..
Сотрудник : Справочник.Сотрудник
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Движения..
ДанныеОперативногоУчетаРабочегоВремениСотрудников : Обороты
ДанныеСводногоУчетаРабочегоВремениСотрудников : Обороты
ДанныеИндивидуальныхГрафиковСотрудников : Обороты
ВытесняемоеПлановоеВремяСотрудников : Обороты
ПараметрыПериодовСтажаПФР : РегистрСведений
ДанныеТабельногоУчетаРабочегоВремениСотрудников : Обороты
}
@enduml
