@startuml ИзделияИЗатратыНЗП
'!include templates.wsd
'..\include templates.wsd
class Документ.ИзделияИЗатратыНЗП as "Изделия и затраты НЗП" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Спецификация : Справочник.Ресурсная спецификация
Количество : Число 15, 3
КоличествоУпаковок : Число 15, 3
Упаковка : Справочник.Упаковка
Назначение : Справочник.Назначение
Комментарий : Строка
Ответственный : Справочник.Пользователь
Подразделение : Справочник.Подразделение
..Табличная часть \n МатериалыИУслуги..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Количество : Число 15, 3
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Подразделение : Справочник.Подразделение
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
..Табличная часть \n Трудозатраты..
ВидРабот : Справочник.Вид работ сотрудников
Количество : Число 15, 3
Подразделение : Справочник.Подразделение
}
@enduml
