@startuml ПоручениеЭкспедитору
'!include templates.wsd
'..\include templates.wsd
class Документ.ПоручениеЭкспедитору as "Поручение экспедитору" <<Документы>>
{
..Реквизиты..
АдресДоставки : Строка
ВремяДоставкиПо : Дата
ВремяДоставкиС : Дата
ЗонаДоставки : Справочник.Зоны доставки
КонтактноеЛицо : Справочник.Контактное лицо
ДополнительнаяИнформацияПоДоставке : Строка
Пункт : Справочник.Подразделение\rСправочник.Партнер\rСтрока\r...
Склад : Справочник.Склад (складская территория)
СпособДоставки : Способы доставки
АдресДоставкиЗначенияПолей : Строка
Ответственный : Справочник.Пользователь
ОсобыеУсловияПеревозкиОписание : Строка
ДатаВыполнения : Дата
..Табличная часть \n Основания..
Основание : Документ.Сторнирование начислений\rДокумент.Внутреннее потребление товаров\rДокумент.Назначение планового начисления\r...
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
