@startuml ОтражениеРасхожденийПриИнкассацииДенежныхСредств
'!include templates.wsd
'..\include templates.wsd
class Документ.ОтражениеРасхожденийПриИнкассацииДенежныхСредств as "Отражение расхождений при инкассации денежных средств" <<Документы>>
{
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
РасходныйКассовыйОрдер : Документ.Расходный кассовый ордер
Касса : Справочник.Касса
Основание : Строка
БанковскийСчет : Справочник.Банковский счет организации
СуммаПоДаннымКассовыхДокументов : Число 15, 2
СуммаПоФакту : Число 15, 2
Сумма : Число 15, 2
Валюта : Справочник.Валюта
Ответственный : Справочник.Пользователь
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
СтатьяДоходов : Статьи доходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
Комментарий : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ПрочиеДоходы : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
РасходыПриУСН : Остатки
ДенежныеСредстваВПути : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
ДвиженияДенежныеСредстваДоходыРасходы : Обороты
КнигаУчетаДоходовИРасходов : Обороты
ВыручкаИСебестоимостьПродаж : Обороты
}
@enduml
