@startuml КорректировкаРеализации
'!include templates.wsd
'..\include templates.wsd
class Документ.КорректировкаРеализации as "Корректировка реализации" <<Документы>>
{
..Реквизиты..
ДокументОснование : Документ.Реализация услуг и прочих активов\rДокумент.Реализация товаров и услуг\rДокумент.Акт выполненных работ
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
Соглашение : Справочник.Соглашение об условиях продаж
Организация : Справочник.Организация
Договор : Справочник.Договор с контрагентом
Склад : Справочник.Склад (складская территория)
Подразделение : Справочник.Подразделение
Сделка : Справочник.Сделка с клиентом
Валюта : Справочник.Валюта
ВалютаВзаиморасчетов : Справочник.Валюта
Менеджер : Справочник.Пользователь
СуммаДокумента : Число 15, 2
ДатаПлатежа : Дата
ФормаОплаты : Формы оплаты
ЦенаВключаетНДС : Булево
НалогообложениеНДС : Типы налогообложения НДС
ПродажаПоЗаказам : Булево
ПодразделениеДоходы : Справочник.Подразделение
СтатьяДоходов : Статьи доходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
ПодразделениеРасходы : Справочник.Подразделение
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Согласован : Булево
Отпустил : Справочник.Физическое лицо
ОтпустилДолжность : Строка
Основание : Строка
Грузополучатель : Справочник.Контрагент
Грузоотправитель : Справочник.Контрагент
БанковскийСчетОрганизации : Справочник.Банковский счет организации
БанковскийСчетКонтрагента : Справочник.Банковский счет
БанковскийСчетГрузоотправителя : Справочник.Банковский счет
БанковскийСчетГрузополучателя : Справочник.Банковский счет
АдресДоставки : Строка
ДоверенностьНомер : Строка
ДоверенностьДата : Дата
ДоверенностьВыдана : Строка
ДоверенностьЛицо : Строка
Комментарий : Строка
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
ПорядокРасчетов : Детализация расчетов
ВидКорректировки : Хозяйственные операции
СуммаВзаиморасчетов : Число 15, 2
ОснованиеДата : Дата
ОснованиеНомер : Строка
АктОРасхожденияхПослеОтгрузкиОснование : Документ.Акт о расхождениях после отгрузки
ВариантОформленияПродажи : Варианты оформления продажи
НаправлениеДеятельности : Справочник.Направление деятельности
Курс : Число 10, 4
Кратность : Число 10, 0
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Содержание : Строка
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ВидЦены : Справочник.Вид цены
Цена : Число 15, 2
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
ЗаказКлиента : Документ.Заявка на возврат товаров от клиента\rДокумент.Заказ клиента
КодСтроки : Число 10, 0
Склад : Справочник.Склад (складская территория)
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
ВариантОтражения : Варианты отражения корректировок реализаций
НоменклатураНабора : Справочник.Номенклатура
ХарактеристикаНабора : Справочник.Характеристика номенклатуры
СтатьяДоходов : Статьи доходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
КодТНВЭД : Справочник.ТН ВЭД
..Табличная часть \n Расхождения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Содержание : Строка
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
ЗаказКлиента : Документ.Заявка на возврат товаров от клиента\rДокумент.Заказ клиента
КодСтроки : Число 10, 0
Склад : Справочник.Склад (складская территория)
ВариантОтражения : Варианты отражения корректировок реализаций
ИдентификаторСтроки : Строка
Серия : Справочник.Серия номенклатуры
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
СтатусУказанияСерий : Число 2, 0
СуммаВзаиморасчетов : Число 15, 2
НоменклатураНабора : Справочник.Номенклатура
ХарактеристикаНабора : Справочник.Характеристика номенклатуры
АналитикаУчетаНаборов : Справочник.Ключ аналитики учета наборов
СтатьяДоходов : Статьи доходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
КодТНВЭД : Справочник.ТН ВЭД
..Табличная часть \n ВидыЗапасовКорректировкаВыручки..
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
СуммаСНДС : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
Склад : Справочник.Склад (складская территория)
ЗаказКлиента : Документ.Заявка на возврат товаров от клиента\rДокумент.Заказ клиента
Упаковка : Справочник.Упаковка
ИдентификаторСтроки : Строка
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
СуммаВзаиморасчетов : Число 15, 2
АналитикаУчетаНаборов : Справочник.Ключ аналитики учета наборов
КодТНВЭД : Справочник.ТН ВЭД
..Табличная часть \n ВидыЗапасовОприходование..
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
СуммаСНДС : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
Склад : Справочник.Склад (складская территория)
СкладОтгрузки : Справочник.Склад (складская территория)
ЗаказКлиента : Документ.Заявка на возврат товаров от клиента\rДокумент.Заказ клиента
ВидЗапасовОтгрузки : Справочник.Вид запасов
НаДоходыРасходы : Булево
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
ИдентификаторСтроки : Строка
УдалитьАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
СуммаВзаиморасчетов : Число 15, 2
АналитикаУчетаНаборов : Справочник.Ключ аналитики учета наборов
КодТНВЭД : Справочник.ТН ВЭД
..Табличная часть \n ВидыЗапасовСписание..
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
СуммаСНДС : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
Склад : Справочник.Склад (складская территория)
ЗаказКлиента : Документ.Заявка на возврат товаров от клиента\rДокумент.Заказ клиента
НаДоходыРасходы : Булево
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
ИдентификаторСтроки : Строка
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
СуммаВзаиморасчетов : Число 15, 2
АналитикаУчетаНаборов : Справочник.Ключ аналитики учета наборов
КодТНВЭД : Справочник.ТН ВЭД
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ПрочиеДоходы : Остатки
РезервыТоваровОрганизаций : Остатки
РасчетыСКлиентами : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
ТоварыКОформлениюИзлишковНедостач : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ДвиженияКонтрагентДоходыРасходы : Обороты
ТоварыКОформлениюОтчетовКомитенту : Остатки
ПереданнаяВозвратнаяТара : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНОСиНМА : Остатки
РасходыПриУСНМатериалы : Остатки
РасходыПриУСН : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
Международный : РегистрБухгалтерии
Закупки : Обороты
РасходыПриУСНТовары : Остатки
НДСЗаписиКнигиПродаж : Обороты
РасчетыСКлиентамиПоДокументам : Остатки
ТоварыОрганизацийКПередаче : Остатки
КнигаУчетаДоходовИРасходов : Обороты
МатериалыИРаботыВПроизводстве : Остатки
ВыручкаИСебестоимостьПродаж : Обороты
СвободныеОстатки : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
ПартииПроизводственныхЗатрат : Остатки
УслугиКОформлениюОтчетовПринципалу : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
