@startuml ВыплатаБывшимСотрудникам
'!include templates.wsd
'..\include templates.wsd
class Документ.ВыплатаБывшимСотрудникам as "Выплата бывшим сотрудникам" <<Документы>>
{
..Реквизиты..
ПериодРегистрации : Дата
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ВидВыплаты : Справочник.Вид выплаты бывшему сотруднику
КодВычетаНДФЛ : Справочник.Вид вычетов НДФЛ
УдалитьКодВычетаНДФЛ : Справочник.(не используется) Виды вычетов НДФЛ
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОтношениеКЕНВД : Отношение к ЕНВД затрат на зарплату
ПланируемаяДатаВыплаты : Дата
ВсегоВыплачено : Число 13, 2
Исполнитель : Справочник.Физическое лицо
ДолжностьИсполнителя : Справочник.Должность
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
УдалитьОблагаетсяЕНВД : Булево
ДатаПлатежаНДФЛ : Дата
ПеречислениеНДФЛРеквизиты : Строка
РегистрироватьВыплатуВедомостью : Булево
..Табличная часть \n НачисленияУдержанияВзносы..
ФизическоеЛицо : Справочник.Физическое лицо
Начислено : Число 13, 2
НДФЛ : Число 13, 0
СуммаВычета : Число 15, 2
КВыплате : Число 13, 2
ФФОМС : Число 15, 2
ФФОМСЕНВД : Число 15, 2
ТФОМС : Число 15, 2
ТФОМСЕНВД : Число 15, 2
ФСС : Число 15, 2
ФССЕНВД : Число 15, 2
ФССНесчастныеСлучаи : Число 15, 2
ПФРНакопительная : Число 15, 2
ПФРНакопительнаяЕНВД : Число 15, 2
ПФРСтраховая : Число 15, 2
ПФРСтраховаяЕНВД : Число 15, 2
ПФРПоСуммарномуТарифу : Число 15, 2
ПФРПоСуммарномуТарифуЕНВД : Число 15, 2
ПФРДоПредельнойВеличины : Число 15, 2
ПФРДоПредельнойВеличиныЕНВД : Число 15, 2
ПФРСПревышения : Число 15, 2
ПФРСПревышенияЕНВД : Число 15, 2
Удержано : Число 13, 2
..Табличная часть \n НДФЛ..
ФизическоеЛицо : Справочник.Физическое лицо
МесяцНалоговогоПериода : Дата
Подразделение : Справочник.Территория\rСправочник.Подразделение
Налог : Число 10, 0
ЗачтеноАвансовыхПлатежей : Число 10, 0
УдалитьНалогКЗачетуВозврату : Число 10, 0
ПримененныйВычетЛичный : Число 12, 2
ПримененныйВычетЛичныйКодВычета : Справочник.Вид вычетов НДФЛ
ПримененныйВычетЛичныйКЗачетуВозврату : Число 12, 2
ПримененныйВычетЛичныйКЗачетуВозвратуКодВычета : Справочник.Вид вычетов НДФЛ
ИдентификаторСтрокиНДФЛ : Число 7, 0
ФиксСтрока : Булево
ФиксРасчет : Булево
КатегорияДохода : Категории доходов НДФЛ
..Табличная часть \n ПримененныеВычетыНаДетейИИмущественные..
КодВычета : Справочник.Вид вычетов НДФЛ
РазмерВычета : Число 12, 2
ИдентификаторСтрокиНДФЛ : Число 7, 0
..Табличная часть \n Удержания..
ФизическоеЛицо : Справочник.Физическое лицо
ДатаНачала : Дата
ДатаОкончания : Дата
ДокументОснование : Документ.Удержание по прочим операциям\rДокумент.Удержание добровольных взносов в НПФ\rДокумент.Удержание профсоюзных взносов\r...
Получатель : Справочник.Контрагент
ПлатежныйАгент : Справочник.Контрагент
Удержание : Удержание
ФиксРасчет : Булево
Результат : Число 13, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
..Табличная часть \n Показатели..
Показатель : Справочник.Показатель
Значение : Число 15, 5
ИдентификаторСтрокиВидаРасчета : Число 7, 0
..Движения..
РасчетыНалогоплательщиковСБюджетомПоНДФЛ : Остатки
НачисленияУдержанияПоКонтрагентамАкционерам : Обороты
РасчетыСФондамиПоСтраховымВзносам : Остатки
ПособияПоСоциальномуСтрахованию : Обороты
УдержанияДоПределаПоСотрудникам : Остатки
ВзаиморасчетыСКонтрагентамиАкционерами : Остатки
СведенияОДоходахСтраховыеВзносы : Обороты
ИмущественныеВычетыНДФЛ : Остатки
СтраховыеВзносыПоФизическимЛицам : Обороты
ПредоставленныеСтандартныеИСоциальныеВычетыНДФЛ : Обороты
БухучетНачисленияУдержанияПоКонтрагентамАкционерам : Обороты
УдержанияПоИсполнительнымДокументам : Обороты
РасчетыНалоговыхАгентовСБюджетомПоНДФЛ : Остатки
ИсчисленныеСтраховыеВзносы : Обороты
СведенияОДоходахНДФЛ : Обороты
АвансовыеПлатежиИностранцевПоНДФЛ : Остатки
}
@enduml
