@startuml ПринятиеКУчетуОС2_4
'!include templates.wsd
'..\include templates.wsd
class Документ.ПринятиеКУчетуОС2_4 as "Принятие к учету ОС" <<Документы>>
{
..Реквизиты..
АдресМестонахождения : Строка
АмортизационнаяГруппа : Амортизационные группы
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
АналитикаРасходовАмортизационнойПремии : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаРасходовБУ : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаРасходовНалог : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаРасходовУУ : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ВариантПримененияЦелевогоФинансирования : Варианты применения целевого финансирования
ВариантРаздельногоУчетаНДС : Варианты раздельного учета НДС
ВидАналитикиКапитализацииРасходов : Виды аналитики капитализации расходов
ВключитьАмортизационнуюПремиюВСоставРасходов : Булево
ГодоваяНормаАмортизацииБУ : Число 4, 2
ГрафикАмортизации : Справочник.Годовой график амортизации ОС
ГруппаОС : Группы ОС
ГруппаФинансовогоУчета : Справочник.Группа финансового учета внеоборотных активов
ДокументВДругомУчете : Документ.Ввод остатков внеоборотных активов\rДокумент.Принятие к учету ОС
ДокументОснование : Документ.Инвентаризация ОС\rДокумент.Поступление предметов лизинга
Комментарий : Строка
КоэффициентУскоренияБУ : Число 6, 2
КоэффициентУскоренияУУ : Число 4, 3
Местонахождение : Справочник.Подразделение
МетодНачисленияАмортизацииБУ : Способы начисления амортизации основных средств
МетодНачисленияАмортизацииУУ : Способы начисления амортизации основных средств
МОЛ : Справочник.Физическое лицо
НалогообложениеНДС : Типы налогообложения НДС
НаправлениеДеятельности : Справочник.Направление деятельности
НачислятьАмортизациюБУ : Булево
НачислятьАмортизациюНУ : Булево
НачислятьАмортизациюУУ : Булево
ОбъектСтроительства : Справочник.Объект строительства
Организация : Справочник.Организация
ОрганизацияПолучательРасходов : Справочник.Организация
Ответственный : Справочник.Пользователь
ОтражатьВРеглУчете : Булево
ОтражатьВУпрУчете : Булево
ПередаватьРасходыВДругуюОрганизацию : Булево
ПорядокУчетаБУ : Порядок погашения стоимости ОС
ПорядокУчетаНУ : Порядок включения стоимости основных средств в состав расходов (НУ)
ПорядокУчетаУУ : Порядок учета стоимости внеоборотных активов
ПроцентКапитальныхВложенийВключаемыхВРасходыНУ : Число 4, 2
СпециальныйКоэффициентНУ : Число 6, 2
СпособПоступления : Способы поступления активов
СрокИспользованияБУ : Число 4, 0
СрокИспользованияНУ : Число 4, 0
СрокИспользованияУУ : Число 10, 0
СтатьяДоходов : Статьи доходов
СтатьяРасходовАмортизационнойПремии : Статья расходов
СтатьяРасходовБУ : Статья расходов
СтатьяРасходовНалог : Статья расходов
СтатьяРасходовУУ : Статья расходов
ТипСтоимости : Типы стоимости ОС
ХозяйственнаяОперация : Хозяйственные операции
ЧастичныйВводВЭксплуатацию : Булево
..Табличная часть \n ОС..
ОсновноеСредство : Справочник.Объект эксплуатации
ПоказательНаработки : Справочник.Показатель наработки
ОбъемНаработки : Число 15, 3
СтоимостьУУ : Число 15, 2
СтоимостьБУ : Число 15, 2
СтоимостьНУ : Число 15, 2
СтоимостьПР : Число 15, 2
СтоимостьВР : Число 15, 2
СуммаЦелевыхСредств : Число 15, 2
ЛиквидационнаяСтоимость : Число 15, 2
..Табличная часть \n ЦелевоеФинансирование..
Счет : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Сумма : Число 15, 2
..Движения..
ПараметрыАмортизацииОСБухгалтерскийУчет : РегистрСведений
МестонахождениеОСБухгалтерскийУчет : РегистрСведений
ПараметрыАмортизацииОСУУ : РегистрСведений
ПараметрыАмортизацииОСНалоговыйУчет : РегистрСведений
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
СобытияОСОрганизаций : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ПараметрыАмортизацииОСБУ : РегистрСведений
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
ПервоначальныеСведенияОС : РегистрСведений
СпособыОтраженияРасходовПоАмортизацииОСБухгалтерскийУчет : РегистрСведений
ПервоначальныеСведенияОСБухгалтерскийУчет : РегистрСведений
ПорядокУчетаОСБУ : РегистрСведений
ПараметрыЦелевогоФинансированияОС : РегистрСведений
ГрафикиАмортизацииОСБухгалтерскийУчет : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
СостоянияОСОрганизаций : РегистрСведений
Международный : РегистрБухгалтерии
НачислениеАмортизацииОСБухгалтерскийУчет : РегистрСведений
МестонахождениеОС : РегистрСведений
ПорядокУчетаОСУУ : РегистрСведений
СчетаБухгалтерскогоУчетаОС : РегистрСведений
ПорядокУчетаОС : РегистрСведений
АмортизацияОС : Остатки
НачислениеАмортизацииОССпециальныйКоэффициентНалоговыйУчет : РегистрСведений
СпособыОтраженияРасходовПоИмущественнымНалогам : РегистрСведений
ВыручкаИСебестоимостьПродаж : Обороты
ПервоначальныеСведенияОСНалоговыйУчет : РегистрСведений
СтоимостьОС : Остатки
НачислениеАмортизацииОСНалоговыйУчет : РегистрСведений
}
@enduml
