@startuml ПланПроизводства
'!include templates.wsd
'..\include templates.wsd
class Документ.ПланПроизводства as "План производства" <<Документы>>
{
..Реквизиты..
Подразделение : Справочник.Подразделение
Статус : Статусы планов
Периодичность : Периодичность
НачалоПериода : Дата
ОкончаниеПериода : Дата
Ответственный : Справочник.Пользователь
ОбновитьДополнить : Число 1, 0
ИзменитьРезультатНа : Число 5, 2
ТочностьОкругления : Число 1, 0
ПользовательскиеНастройки : Хранилище значения
Комментарий : Строка
Сценарий : Справочник.Сценарии товарного планирования
ВидПлана : Справочник.Вид плана
ЗаполненоАвтоматически : Булево
КроссТаблица : Булево
СтруктураНастроек : Хранилище значения
ЗаполнятьПоФормуле : Булево
ОтражаетсяВБюджетировании : Булево
СтатьяБюджетов : Справочник.Статьи бюджетов
СценарийБюджетирования : Справочник.Сценарии бюджетирования
Замещающий : Булево
Назначение : Справочник.Назначение
УправлениеПроизводством2_2 : Булево
НачалоПериодаЗамещения : Дата
..Табличная часть \n Продукция..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
Количество : Число 15, 3
КоличествоУпаковок : Число 15, 3
ДатаЗапуска : Дата
ДатаВыпуска : Дата
Спецификация : Справочник.Ресурсная спецификация
ДополнительныеПараметры : Хранилище значения
Отменено : Булево
Комментарий : Строка
Полуфабрикат : Булево
Назначение : Справочник.Назначение
Замещен : Булево
ДатаВыпускаПродукцииПолуфабриката : Дата
..Табличная часть \n ПравилоЗаполнения..
Использование : Булево
Исключать : Булево
ВариантПреобразования : Варианты преобразования
Источник : Справочник.Источник данных планирования
Период : Хранилище значения
Дата : Хранилище значения
ТипЭлемента : Число 1, 0
НомерСтрокиРодитель : Число 5, 0
ПользовательскиеНастройки : Хранилище значения
ИзменитьРезультатНа : Число 5, 2
Присоединять : Булево
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ОборотыБюджетов : Обороты
ФактическиеДанныеБюджетирования : Обороты
ПланыЗанятостиТрудовыхРесурсов : Обороты
ПланыПроизводства : Обороты
ПланыЗанятостиВидовРабочихЦентров : Обороты
ПланыПотребленияМатериалов : Обороты
}
@enduml
