@startuml ОтчетПереработчика
'!include templates.wsd
'..\include templates.wsd
class Документ.ОтчетПереработчика as "Отчет переработчика" <<Документы>>
{
..Реквизиты..
Автор : Справочник.Пользователь
БанковскийСчетКонтрагента : Справочник.Банковский счет
БанковскийСчетОрганизации : Справочник.Банковский счет организации
Валюта : Справочник.Валюта
ВалютаВзаиморасчетов : Справочник.Валюта
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
ГруппировкаЗатрат : Группировки затрат в заказе переработчику
ДатаПлатежа : Дата
ДатаПоДаннымПартнера : Дата
Договор : Справочник.Договор с контрагентом
ЗаказПереработчику : Документ.Заказ переработчику
ЗакупкаПодДеятельность : Типы налогообложения НДС
Комментарий : Строка
Контрагент : Справочник.Контрагент
Кратность : Число 10, 0
Курс : Число 10, 4
МаксимальныйНомерГруппыЗатрат : Число 10, 0
Менеджер : Справочник.Пользователь
НаправлениеДеятельности : Справочник.Направление деятельности
Номенклатура : Справочник.Номенклатура
НомерПоДаннымПартнера : Строка
Организация : Справочник.Организация
Партнер : Справочник.Партнер
Подразделение : Справочник.Подразделение
ПоЗаказам : Булево
ПорядокОплаты : Порядок оплаты
ПорядокРасчетов : Детализация расчетов
ПроверятьУказаниеРаботы : Булево
Руководитель : Справочник.Лицо с правом подписи
Сделка : Справочник.Сделка с клиентом
Согласован : Булево
СоглашениеНаПередачу : Справочник.Соглашение об условиях продаж
Содержание : Строка
СтавкаНДС : Ставки НДС
СтатьяКалькуляции : Справочник.Статьи калькуляции
Сумма : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
СуммаВзаиморасчетовПоЗаказу : Число 15, 2
СуммаДокумента : Число 15, 2
СуммаНДС : Число 15, 2
СуммаНДСВзаиморасчетов : Число 15, 2
СуммаСНДС : Число 15, 2
ФормаОплаты : Формы оплаты
Характеристика : Справочник.Характеристика номенклатуры
ХозяйственнаяОперация : Хозяйственные операции
УслугиПоПереработке : Варианты оформления услуг документов переработки
УчетСырьяПоНазначениям : Булево
МаксимальныйКодСтрокиПродукция : Число 10, 0
..Табличная часть \n Продукция..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
УдалитьТипСтоимости : Типы стоимости выходных изделий
КодСтроки : Число 10, 0
ЗаказПереработчику : Документ.Заказ переработчику
ДоляСтоимости : Число 10, 0
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
Спецификация : Справочник.Ресурсная спецификация
ДокументПоступления : Документ.Поступление от переработчика
НомерГруппыЗатрат : Число 10, 0
ЭтапПроизводства : Документ.Этап производства
ВидЗапасов : Справочник.Вид запасов
УдалитьЦена : Число 15, 2
УдалитьСумма : Число 15, 2
АналитикаУчетаПартийПроизводства : Справочник.Ключ аналитики учета партий производства
ОсновноеИзделиеГруппыЗатрат : Булево
..Табличная часть \n ВозвратныеОтходы..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Цена : Число 15, 2
Сумма : Число 15, 2
КодСтроки : Число 10, 0
Назначение : Справочник.Назначение
ВидЦены : Справочник.Вид цены
НомерГруппыЗатрат : Число 10, 0
ЭтапПроизводства : Документ.Этап производства
ДокументПоступления : Документ.Поступление от переработчика
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ЗаказПереработчику : Документ.Заказ переработчику
ВидЗапасов : Справочник.Вид запасов
СтатьяКалькуляции : Справочник.Статьи калькуляции
АналитикаУчетаПартийПроизводства : Справочник.Ключ аналитики учета партий производства
..Табличная часть \n Материалы..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ЗаказПереработчику : Документ.Заказ переработчику
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
СтатьяКалькуляции : Справочник.Статьи калькуляции
ДокументПоступления : Документ.Поступление от переработчика
НомерГруппыЗатрат : Число 10, 0
ЭтапПроизводства : Документ.Этап производства
АналитикаУчетаПартийПроизводства : Справочник.Ключ аналитики учета партий производства
..Табличная часть \n Услуги..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Сумма : Число 15, 2
СуммаНДС : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаСНДС : Число 15, 2
СтатьяКалькуляции : Справочник.Статьи калькуляции
ДокументПоступления : Документ.Поступление от переработчика
НомерГруппыЗатрат : Число 10, 0
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
УдалитьИдентификаторСтроки : Строка
ЭтапПроизводства : Документ.Этап производства
ИдентификаторСтроки : Строка
АналитикаУчетаПартийПроизводства : Справочник.Ключ аналитики учета партий производства
..Табличная часть \n ВидыЗапасов..
ЗаказПереработчику : Документ.Заказ переработчику
НомерГруппыЗатрат : Число 10, 0
ВидЗапасов : Справочник.Вид запасов
Количество : Число 15, 3
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
СтатьяКалькуляции : Справочник.Статьи калькуляции
ДокументПоступления : Документ.Поступление от переработчика
ЭтапПроизводства : Документ.Этап производства
АналитикаУчетаПартийПроизводства : Справочник.Ключ аналитики учета партий производства
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n РасшифровкаПлатежа..
Заказ : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Приобретение товаров и услуг\r...
Сумма : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
..Движения..
ПрочиеДоходы : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСН : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
РасчетыСПоставщиками : Остатки
Международный : РегистрБухгалтерии
УслугиПереработчиковКОформлению : Остатки
НДСЗаписиКнигиПродаж : Обороты
РасчетыСПоставщикамиПоДокументам : Остатки
КнигаУчетаДоходовИРасходов : Обороты
ТоварыПереданныеПереработчику : Остатки
МатериалыИРаботыВПроизводстве : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
НДСЗаписиКнигиПокупок : Обороты
ГрафикПоступленияТоваров : Остатки
ПрочиеРасходыНезавершенногоПроизводства : Остатки
ПартииПроизводственныхЗатрат : Остатки
ВыпускПродукции : Обороты
ТоварыПолученныеОтПереработчика : Остатки
ПартииНезавершенногоПроизводства : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
