@startuml МаршрутныйЛистПроизводства
'!include templates.wsd
'..\include templates.wsd
class Документ.МаршрутныйЛистПроизводства as "Маршрутный лист производства" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Статус : Статусы маршрутных листов производства
Этап : Справочник.Этап ресурсной спецификации
Спецификация : Справочник.Ресурсная спецификация
СпецификацияПолуфабриката : Справочник.Ресурсная спецификация
ЭтапПродукции : Справочник.Этап ресурсной спецификации
МаршрутнаяКарта : Справочник.Маршрутная карта
Подразделение : Справочник.Подразделение
Распоряжение : Документ.Заказ на производство
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КодСтроки : Число 10, 0
КодСтрокиЭтапыГрафик : Число 10, 0
Начало : Дата
Окончание : Дата
Непрерывный : Булево
Запланировано : Число 15, 0
Произведено : Число 15, 0
Брак : Число 15, 0
ОдновременноПроизводимоеКоличествоЕдиницПартийИзделий : Число 15, 0
НачалоРаботыКлючевогоРабочегоЦентраПоГрафику : Дата
ОкончаниеРаботыКлючевогоРабочегоЦентраПоГрафику : Дата
ФактическоеОкончаниеРаботыКлючевогоРабочегоЦентра : Дата
ПредварительныйБуфер : Число 10, 0
ЕдиницаИзмеренияПредварительногоБуфера : Единицы измерения времени
ЗавершающийБуфер : Число 10, 0
ЕдиницаИзмеренияЗавершающегоБуфера : Единицы измерения времени
ГотовоКРаботеКлючевогоРабочегоЦентра : Булево
ДатаВыполненияРаботВПредварительномБуфере : Дата
ПорядокВыполненияОперацийЗадаетсяПроизвольно : Булево
Диспетчер : Справочник.Пользователь
ПланироватьРаботуВидовРабочихЦентров : Булево
ЗавершеноВыполнениеМаршрутногоЛиста : Булево
ДлительностьЭтапа : Число 10, 0
ЕдиницаИзмеренияДлительностиЭтапа : Единицы измерения времени
ЗатраченоВремениОтПредварительногоБуфера : Число 3, 0
ЗатраченоВремениОтЗавершающегоБуфера : Число 3, 0
ПричинаЗадержкиПредварительныйБуфер : Справочник.Причина задержки выполнения этапов производства
ПричинаЗадержкиЗавершающийБуфер : Справочник.Причина задержки выполнения этапов производства
ФактическоеОкончание : Дата
ДатаВыполненияРаботВЗавершающемБуфере : Дата
ЗатраченоВремениОтДлительностиЭтапа : Число 3, 0
ПричинаЗадержкиЭтап : Справочник.Причина задержки выполнения этапов производства
ЗавершенаРаботаКлючевогоРабочегоЦентра : Булево
ОкончаниеВыполненияОпераций : Дата
ОписаниеБрака : Строка
Назначение : Справочник.Назначение
Комментарий : Строка
ЭтапВосстановленияБрака : Булево
ДатаВыполненияОпераций : Дата
СостояниеРасписания : Состояния расписания рабочих центров
УправлениеМаршрутнымиЛистами : Управление маршрутными листами
МаксимальныйКодСтрокиИзделия : Число 10, 0
МаксимальныйКодСтрокиМатериалы : Число 10, 0
МаксимальныйКодСтрокиТрудозатраты : Число 10, 0
НоменклатураПолуфабриката : Справочник.Номенклатура
ХарактеристикаПолуфабриката : Справочник.Характеристика номенклатуры
ДопроизводствоМаршрутногоЛиста : Документ.Маршрутный лист производства
ПеренесенНаДругойИнтервал : Булево
ФактическоеНачало : Дата
ФактическоеНачалоВыполненияОпераций : Дата
НомерПартии : Число 10, 0
Приоритет : Справочник.Приоритет
ЕстьМаркируемаяПродукцияГИСМ : Булево
ВариантПриемкиТоваров : Варианты приемки товаров
..Табличная часть \n Операции..
Операция : Строка\rСправочник.Операция
РабочийЦентр : Справочник.Рабочий центр
ВидРабочегоЦентра : Справочник.Вид рабочего центра
РабочийЦентрПоРасписанию : Справочник.Рабочий центр
НомерОперации : Число 5, 0
НомерСледующейОперации : Число 5, 0
Начало : Дата
СтатусВыполнения : Статусы выполнения операций
РасписаниеВведеноВручную : Булево
Окончание : Дата
ВремяВыполнения : Число 10, 1
ВремяВыполненияЕдИзм : Единицы измерения времени
ВремяШтучное : Число 10, 1
ВремяШтучноеЕдИзм : Единицы измерения времени
ВремяПЗ : Число 10, 1
ВремяПЗЕдИзм : Единицы измерения времени
ВариантНаладки : Справочник.Вариант наладки
Загрузка : Число 15, 3
Непрерывная : Булево
Приоритет : Справочник.Приоритет
КлючСвязи : Уникальный идентификатор
..Табличная часть \n ВыходныеИзделия..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
КоличествоУпаковокОтклонение : Число 15, 3
КоличествоОтклонение : Число 15, 3
Упаковка : Справочник.Упаковка
Получатель : Справочник.Подразделение\rСправочник.Склад (складская территория)
КлючСвязиОперации : Уникальный идентификатор
ДоляСтоимости : Число 10, 0
КодСтроки : Число 10, 0
КоличествоУпаковокФакт : Число 15, 3
КоличествоФакт : Число 15, 3
ПроизводитсяВПроцессе : Булево
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
Назначение : Справочник.Назначение
..Табличная часть \n ВозвратныеОтходы..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
КоличествоУпаковокОтклонение : Число 15, 3
КоличествоОтклонение : Число 15, 3
Упаковка : Справочник.Упаковка
Получатель : Справочник.Подразделение\rСправочник.Склад (складская территория)
КлючСвязиОперации : Уникальный идентификатор
КодСтроки : Число 10, 0
СтатьяКалькуляции : Справочник.Статьи калькуляции
ОписаниеИзделия : Строка
КоличествоУпаковокФакт : Число 15, 3
КоличествоФакт : Число 15, 3
ПроизводитсяВПроцессе : Булево
Назначение : Справочник.Назначение
..Табличная часть \n МатериалыИУслуги..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
КоличествоУпаковокОтклонение : Число 15, 3
КоличествоОтклонение : Число 15, 3
Упаковка : Справочник.Упаковка
СтатьяКалькуляции : Справочник.Статьи калькуляции
ИспользуетсяАвтовыбор : Булево
ПрименениеМатериала : Строка
СведенияАвтовыбора : Строка
КлючСвязиОперации : Уникальный идентификатор
Назначение : Справочник.Назначение
КоличествоУпаковокФакт : Число 15, 3
КоличествоФакт : Число 15, 3
СтатусУказанияСерий : Число 2, 0
Серия : Справочник.Серия номенклатуры
ПроизводитсяВПроцессе : Булево
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ДатаРасхода : Дата
МатериалИзрасходован : Булево
КодСтроки : Число 10, 0
..Табличная часть \n Трудозатраты..
ВидРабот : Справочник.Вид работ сотрудников
Количество : Число 15, 3
КоличествоОтклонение : Число 15, 3
Бригада : Справочник.Бригады
СтатьяКалькуляции : Справочник.Статьи калькуляции
КлючСвязиОперации : Уникальный идентификатор
СодержаниеРабот : Строка
КоличествоФакт : Число 15, 3
КодСтроки : Число 10, 0
НазначениеРабот : Строка
..Табличная часть \n ВидыРабочихЦентров..
ВидРабочегоЦентра : Справочник.Вид рабочего центра
РабочийЦентр : Справочник.Рабочий центр
ВариантНаладки : Справочник.Вариант наладки
ДатаИнтервала : Дата
ВремяРаботы : Число 10, 0
ВремяРаботыНорматив : Число 10, 0
Загрузка : Число 15, 3
ЗагрузкаНорматив : Число 15, 3
..Табличная часть \n ВспомогательныеРабочиеЦентры..
РабочийЦентр : Справочник.Рабочий центр\rСправочник.Вид рабочего центра
КлючСвязиОперации : Уникальный идентификатор
..Табличная часть \n РаспоряжениеСпецификация..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Количество : Число 15, 3
КоличествоПоЗаказу : Число 15, 3
КоличествоОтклонение : Число 15, 3
Получатель : Справочник.Подразделение\rСправочник.Склад (складская территория)
Назначение : Справочник.Назначение
ПроизводитсяВПроцессе : Булево
..Табличная часть \n РаспоряжениеТрудозатраты..
ВидРабот : Справочник.Вид работ сотрудников
КоличествоПоЗаказу : Число 15, 3
Количество : Число 15, 3
КоличествоОтклонение : Число 15, 3
..Табличная часть \n ЗанятостьВидовРабочихЦентровПоГрафику..
ВидРабочегоЦентра : Справочник.Вид рабочего центра
ВариантНаладки : Справочник.Вариант наладки
ДатаИнтервала : Дата
ВремяРаботы : Число 10, 0
ВремяРаботыНорматив : Число 10, 0
Загрузка : Число 15, 3
ЗагрузкаНорматив : Число 15, 3
..Табличная часть \n ВыходныеИзделияСерии..
Серия : Справочник.Серия номенклатуры
КоличествоФакт : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Получатель : Справочник.Подразделение\rСправочник.Склад (складская территория)
Назначение : Справочник.Назначение
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ОперацииМаршрутовПроизводства : РегистрСведений
ДвиженияСерийТоваров : Обороты
СебестоимостьТоваров : Остатки
ПрочиеАктивыПассивы : Остатки
ДетализацияПартийТоваровДляНДСиУСН : Остатки
ЭтапыПроизводства : Обороты
НДСПредъявленный : Остатки
ДоступностьВидовРабочихЦентров : Обороты
ОбеспечениеЗаказов : Остатки
ДвижениеТоваров : Обороты
НДСЗаписиКнигиПродаж : Обороты
ОбеспечениеЗаказовРаботами : Остатки
БракВПроизводстве : Остатки
ЗаказыНаПроизводствоТрудозатраты : Остатки
МатериалыИРаботыВПроизводстве : Остатки
ЗаказыНаПроизводствоСпецификации : Остатки
ТрудозатратыКОформлению : Остатки
СостоянияРабочихЦентров : Обороты
ПотребностьВМатериалахВПроизводстве : Обороты
ГрафикПоступленияТоваров : Остатки
ПартииПроизводственныхЗатрат : Остатки
ПартииНезавершенногоПроизводства : Остатки
ТоварыКПоступлению : Остатки
РаспоряженияНаВыпускПродукции : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
