@startuml ПрекращениеПодработки
'!include templates.wsd
'..\include templates.wsd
class Документ.ПрекращениеПодработки as "Прекращение подработки" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ГоловнойСотрудник : Справочник.Сотрудник
СовмещающийСотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ДатаОкончания : Дата
ДокументОснование : Документ.Назначение подработки
ИсправленныйДокумент : Документ.Прекращение подработки
Ответственный : Справочник.Пользователь
Комментарий : Строка
УдалитьУтверждено : Булево
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников : РегистрСведений
УдалитьСостоянияПодработок : РегистрСведений
ДанныеСостоянийСотрудников : РегистрСведений
КадроваяИсторияСотрудников : РегистрСведений
БухучетПлановыхНачислений : РегистрСведений
ПлановыеНачисления : РегистрСведений
}
@enduml
