@startuml НачислениеДивидендов
'!include templates.wsd
'..\include templates.wsd
class Документ.НачислениеДивидендов as "Начисление дивидендов" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ДатаВыплаты : Дата
Комментарий : Строка
Ответственный : Справочник.Пользователь
Валюта : Справочник.Валюта
СуммаДокумента : Число 15, 2
ПроводкиПоРаботникам : Булево
ВключатьВДекларациюПоНалогуНаПрибыль : Булево
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
Начислено : Число 13, 2
СтавкаНДФЛ : Ставки НДФЛ
НДФЛ : Число 13, 2
ВычетПоНДФЛ : Число 15, 2
КВыплате : Число 13, 2
ПрочийАкционер : Булево
Контрагент : Справочник.Контрагент
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
..Табличная часть \n ЮридическиеЛица..
Контрагент : Справочник.Контрагент
Начислено : Число 13, 2
СтавкаНалогаНаПрибыль : Число 2, 0
НалогНаПрибыль : Число 13, 2
КВыплате : Число 13, 2
УдалитьСтавкаНалогаНаПрибыль : Ставки НДФЛ
..Движения..
РасчетыНалогоплательщиковСБюджетомПоНДФЛ : Остатки
НачисленияУдержанияПоКонтрагентамАкционерам : Обороты
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
РасходыПриУСН : Остатки
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
КнигаУчетаДоходовИРасходов : Обороты
БухучетНачисленияУдержанияПоКонтрагентамАкционерам : Обороты
РасчетыНалоговыхАгентовСБюджетомПоНДФЛ : Остатки
СведенияОДоходахНДФЛ : Обороты
}
@enduml
