@startuml ПрекращениеСтандартныхВычетовНДФЛ
'!include templates.wsd
'..\include templates.wsd
class Документ.ПрекращениеСтандартныхВычетовНДФЛ as "Отмена стандартных вычетов НДФЛ" <<Документы>>
{
..Реквизиты..
Месяц : Дата
Организация : Справочник.Организация
Сотрудник : Справочник.Физическое лицо
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Движения..
СтандартныеВычетыФизическихЛицНДФЛ : РегистрСведений
УдалитьСтандартныеВычетыНаДетейНДФЛ : РегистрСведений
ПрименениеСтандартныхВычетовПоНДФЛ : РегистрСведений
СтандартныеВычетыНаДетейНДФЛ : РегистрСведений
}
@enduml
