@startuml КорректировкаПоОрдеруНаТовары
'!include templates.wsd
'..\include templates.wsd
class Документ.КорректировкаПоОрдеруНаТовары as "Корректировка по ордеру на товары" <<Документы>>
{
..Реквизиты..
Комментарий : Строка
Ответственный : Справочник.Пользователь
Помещение : Справочник.Помещение
Склад : Справочник.Склад (складская территория)
Ордер : Документ.Расходный ордер на товары\rДокумент.Ордер на перемещение товаров
ЗонаОтгрузки : Справочник.Складская ячейка
ОрдерПолучатель : Документ.Расходный ордер на товары\rДокумент.Ордер на перемещение товаров
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
Упаковка : Справочник.Упаковка
ВидОперации : Виды операций корректировок остатков товаров
Количество : Число 15, 3
КоличествоУпаковок : Число 15, 3
СтатусУказанияСерий : Число 2, 0
..Движения..
ДвиженияСерийТоваров : Обороты
ТоварыКОформлениюИзлишковНедостач : Остатки
ТоварыКОтбору : Остатки
ТоварыНаСкладах : Остатки
ОбеспечениеЗаказов : Остатки
СвободныеОстатки : Остатки
ТоварыВЯчейках : Остатки
}
@enduml
