@startuml ИзменениеПараметровОС
'!include templates.wsd
'..\include templates.wsd
class Документ.ИзменениеПараметровОС as "Изменение параметров ОС (2.2)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ГрафикАмортизации : Справочник.Годовой график амортизации ОС
СобытиеОС : Справочник.Событие ОС
Ответственный : Справочник.Пользователь
Комментарий : Строка
ГрафикАмортизацииФлаг : Булево
СрокИспользованияБУ : Число 4, 0
СрокИспользованияБУФлаг : Булево
СрокИспользованияНУ : Число 4, 0
СрокИспользованияНУФлаг : Булево
ОбъемНаработкиБУ : Число 15, 3
ОбъемНаработкиБУФлаг : Булево
КоэффициентАмортизацииБУ : Число 4, 2
КоэффициентАмортизацииБУФлаг : Булево
КоэффициентУскоренияБУ : Число 5, 2
КоэффициентУскоренияБУФлаг : Булево
СпециальныйКоэффициентНУ : Число 5, 2
СпециальныйКоэффициентНУФлаг : Булево
ОтражениеАмортизационныхРасходовФлаг : Булево
ДокументОснование : Документ.Принятие к учету ОС\rДокумент.Модернизация ОС\rДокумент.Ввод остатков внеоборотных активов\r...
СчетУчета : Счет бухгалтерского учета
СчетУчетаФлаг : Булево
СчетАмортизации : Счет бухгалтерского учета
СчетАмортизацииФлаг : Булево
..Табличная часть \n ОС..
ОсновноеСредство : Справочник.Объект эксплуатации
..Табличная часть \n ОтражениеАмортизационныхРасходов..
Подразделение : Справочник.Подразделение
НаправлениеДеятельности : Справочник.Направление деятельности
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
СтатьяРасходовАмортизационнойПремии : Статья расходов
АналитикаРасходовАмортизационнойПремии : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
СтатьяРасходовНалог : Статья расходов
АналитикаРасходовНалог : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Коэффициент : Число 10, 0
ПередаватьРасходыВДругуюОрганизацию : Булево
ОрганизацияПолучательРасходов : Справочник.Организация
СчетПередачиРасходов : Счет бухгалтерского учета
..Табличная часть \n НачисленнаяАмортизация..
ОбъектУчета : Справочник.Объект эксплуатации
Подразделение : Справочник.Подразделение
СуммаБУ : Число 15, 2
СуммаНУ : Число 15, 2
СуммаПР : Число 15, 2
СуммаВР : Число 15, 2
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ЭтоАмортизационнаяПремия : Булево
ДокументАмортизационнойПремии : Документ.Принятие к учету ОС\rДокумент.Модернизация ОС
ПередаватьРасходыВДругуюОрганизацию : Булево
ОрганизацияПолучательРасходов : Справочник.Организация
СчетПередачиРасходов : Счет бухгалтерского учета
ЭтоЦелевыеСредства : Булево
НаправлениеДеятельности : Справочник.Направление деятельности
..Движения..
ПараметрыАмортизацииОСБухгалтерскийУчет : РегистрСведений
ПрочиеДоходы : Остатки
ПараметрыАмортизацииОСНалоговыйУчет : РегистрСведений
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
СобытияОСОрганизаций : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
СпособыОтраженияРасходовПоАмортизацииОСБухгалтерскийУчет : РегистрСведений
ГрафикиАмортизацииОСБухгалтерскийУчет : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
СчетаБухгалтерскогоУчетаОС : РегистрСведений
НачислениеАмортизацииОССпециальныйКоэффициентНалоговыйУчет : РегистрСведений
СпособыОтраженияРасходовПоИмущественнымНалогам : РегистрСведений
ВыручкаИСебестоимостьПродаж : Обороты
}
@enduml
