@startuml ТаможеннаяДекларацияЭкспорт
'!include templates.wsd
'..\include templates.wsd
class Документ.ТаможеннаяДекларацияЭкспорт as "Таможенная декларация на экспорт" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
КодОперации : Строка
Примечание : Строка
СборСопроводительныхДокументовЗавершен : Булево
Комментарий : Строка
Автор : Справочник.Пользователь
ДокументОснование : Документ.Реализация товаров и услуг
Ответственный : Справочник.Пользователь
..Табличная часть \n ДокументыОснования..
ДокументОснование : Документ.Реализация товаров и услуг
..Табличная часть \n СопроводительныеДокументы..
КодТС : Строка
ВидДокумента : Строка
НомерТСД : Строка
ДатаТСД : Дата
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
СведенияТаможенныхДекларацийЭкспорт : РегистрСведений
}
@enduml
