@startuml СписаниеНМА2_4
'!include templates.wsd
'..\include templates.wsd
class Документ.СписаниеНМА2_4 as "Списание НМА" <<Документы>>
{
..Реквизиты..
ОтражатьВУпрУчете : Булево
ОтражатьВРеглУчете : Булево
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ЧастичнаяЛиквидация : Булево
ДокументВДругомУчете : Документ.Списание НМА
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n НМА..
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
СуммаСписанияУУ : Число 15, 2
СуммаСписанияБУ : Число 15, 2
СуммаСписанияНУ : Число 15, 2
СуммаСписанияПР : Число 15, 2
СуммаСписанияВР : Число 15, 2
..Движения..
ПервоначальныеСведенияНМАНалоговыйУчет : РегистрСведений
ПрочиеДоходы : Остатки
ПорядокУчетаНМАУУ : РегистрСведений
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
ПервоначальныеСведенияНМА : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
СтоимостьНМА : Остатки
Хозрасчетный : РегистрБухгалтерии
ПорядокУчетаНМАБУ : РегистрСведений
ОтражениеДокументовВМеждународномУчете : РегистрСведений
АмортизацияНМА : Остатки
Международный : РегистрБухгалтерии
МестоУчетаНМА : РегистрСведений
ПервоначальныеСведенияНМАБухгалтерскийУчет : РегистрСведений
ВыручкаИСебестоимостьПродаж : Обороты
}
@enduml
