@startuml ПереносДанных
'!include templates.wsd
'..\include templates.wsd
class Документ.ПереносДанных as "Перенос данных" <<Документы>>
{
..Реквизиты..
ПериодРегистрации : Дата
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
Комментарий : Строка
НалогСОтсроченнойУплатой : Булево
..Табличная часть \n ТаблицаРегистров..
Имя : Строка
..Движения..
УдалитьИсключаемыеИзОстатковОтпусковПериоды : РегистрСведений
Удержания : РегистрРасчета
ОплаченныеДоговоры : РегистрСведений
ОценочныеОбязательства : Остатки
ОтветыНаВопросыАнкет : РегистрСведений
ДанныеОперативногоУчетаРабочегоВремениСотрудников : Обороты
РасчетыНалогоплательщиковСБюджетомПоНДФЛ : Остатки
БухучетПлановыхУдержаний : РегистрСведений
ДанныеОВремениДляРасчетаСреднегоФСС : РегистрСведений
УдалитьВыплатаОтпусковЗаСчетРезерва : Обороты
НачисленияУдержанияПоКонтрагентамАкционерам : Обороты
БухучетНачисленияУдержанияПоСотрудникамАвансом : Обороты
УсловияДоговораЗаймаСотруднику : РегистрСведений
УдалитьИсторияИспользованияДолжностей : РегистрСведений
ЗначенияПоказателейУдержаний : РегистрСведений
ПлановыеНачисленияПоДоговорам : РегистрСведений
СведенияКонтрактаДоговораСотрудника : РегистрСведений
ИсторияСпециальностейПоШтатномуРасписанию : РегистрСведений
ИсторияПоказателейПоШтатномуРасписанию : РегистрСведений
ВзаиморасчетыССотрудниками : Остатки
ОтработанноеВремяПоСотрудникамАвансом : Обороты
НачисленияУдержанияПоСотрудникам : Обороты
ПорядокРасчетаСтоимостиЕдиницыВремениСотрудников : РегистрСведений
ВыполненныеРаботыСотрудников : Обороты
ЗанятыеПозицииШтатногоРасписания : Остатки
ОтработанноеВремяПоСотрудникамКорректировка : Обороты
ЗначенияПериодическихПоказателейРасчетаЗарплатыПодразделений : РегистрСведений
УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников : РегистрСведений
УсловияОплатыОтпускаПоУходуЗаРебенком : РегистрСведений
ПКУСотрудников : РегистрСведений
ЗначенияРазовыхПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
ДанныеСводногоУчетаРабочегоВремениСотрудников : Обороты
УсловияДоговораГПХ : РегистрСведений
УдалитьСостоянияПодработок : РегистрСведений
УплатаНДФЛНалоговымиАгентамиКРаспределению : Остатки
ГрафикРаботыСотрудников : РегистрСведений
ПрименениеДополнительныхПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
ИсторияИспользованияШтатногоРасписания : РегистрСведений
РасчетыСФондамиПоСтраховымВзносам : Остатки
ПорядокВыплатыДокументов : РегистрСведений
ПособияПоСоциальномуСтрахованию : Обороты
УсловияУдержанияПоИсполнительномуДокументу : РегистрСведений
УдержанияДоПределаПоСотрудникам : Остатки
ДанныеСостоянийСотрудников : РегистрСведений
КоэффициентИндексацииЗаработка : РегистрСведений
РаспределениеПоТерриториямУсловиямТруда : РегистрСведений
РабочиеМестаУдержаний : РегистрСведений
ПрименениеПлановыхНачислений : РегистрСведений
ЗначенияОперативныхПоказателейРасчетаЗарплатыПодразделений : Обороты
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
ПлановыеАвансы : РегистрСведений
УдалитьИсторияИспользованияПодразделений : РегистрСведений
ЗначенияРазовыхПоказателейРасчетаЗарплатыПодразделений : РегистрСведений
ЗначенияРазовыхПоказателейРасчетаЗарплатыОрганизаций : РегистрСведений
ДанныеОВремениДляРасчетаСреднегоОбщий : Обороты
ДанныеИндивидуальныхГрафиковСотрудников : Обороты
РасчетРезерваОтпусков : РегистрСведений
ПериодыУходаЗаБольнымиРодственниками : Обороты
ВытесняемоеПлановоеВремяСотрудников : Обороты
КадроваяИсторияСотрудников : РегистрСведений
ВзаиморасчетыСКонтрагентамиАкционерами : Остатки
ОценочныеОбязательстваПоСотрудникам : Остатки
ЗначенияТарифов : РегистрСведений
СогласияНаОбработкуПерсональныхДанных : РегистрСведений
ФактическиеОтпуска : Обороты
ОсновныеДанныеКонтрактаДоговораСотрудника : РегистрСведений
СведенияОДоходахСтраховыеВзносы : Обороты
ИмущественныеВычетыНДФЛ : Остатки
СтандартныеВычетыФизическихЛицНДФЛ : РегистрСведений
УдалитьСтандартныеВычетыНаДетейНДФЛ : РегистрСведений
ИсторияНачисленийПоШтатномуРасписанию : РегистрСведений
ЗначенияОперативныхПоказателейРасчетаЗарплатыОрганизаций : Обороты
ЗначенияОперативныхПоказателейРасчетаЗарплатыСотрудников : Обороты
ПособияПоУходуЗаРебенком : Обороты
ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаОбщий : Обороты
ПрименениеСтандартныхВычетовПоНДФЛ : РегистрСведений
ИсторияЕжегодныхОтпусковПоШтатномуРасписанию : РегистрСведений
ЗначенияПоказателейНачислений : РегистрСведений
ПериодыДействияДоговоровГражданскоПравовогоХарактера : РегистрСведений
СтраховыеВзносыПоФизическимЛицам : Обороты
ПредоставленныеСтандартныеИСоциальныеВычетыНДФЛ : Обороты
ТерриторииСотрудников : РегистрСведений
СтандартныеВычетыНаДетейНДФЛ : РегистрСведений
ЗначенияБазовыхТарифов : РегистрСведений
РазрядыКатегорииСотрудников : РегистрСведений
НачисленияПоДоговорамГПХ : Обороты
БухучетНачисленияУдержанияПоКонтрагентамАкционерам : Обороты
ЗарплатаКВыплатеАвансом : Остатки
УдержанияПоИсполнительнымДокументам : Обороты
ТраншиЗаймаСотруднику : РегистрСведений
ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
РасчетыНалоговыхАгентовСБюджетомПоНДФЛ : Остатки
ОтработанноеВремяПоСотрудникам : Обороты
Начисления : РегистрРасчета
РеестрОтпусков : РегистрСведений
ИсчисленныеСтраховыеВзносы : Обороты
ЗначенияПериодическихПоказателейРасчетаЗарплатыОрганизаций : РегистрСведений
БухучетПлановыхНачислений : РегистрСведений
СведенияОДоходахНДФЛ : Обороты
ПредоставлениеСоциальныхВычетовУРаботодателя : РегистрСведений
АрхивДанныхРегламентированнойОтчетности : РегистрСведений
ПоложенныеВидыЕжегодныхОтпусков : РегистрСведений
БронированиеСотрудников : РегистрСведений
НачисленияУдержанияПоСотрудникамАвансом : Обороты
ДниЧасыОтгулов : Остатки
БухучетНачисленияУдержанияПоСотрудникам : Обороты
СтраховыеВзносыПереданныеВПФР : Остатки
КоэффициентыРаспределенияСреднегоЗаработка : РегистрСведений
НачальныеОстаткиОтпусков : РегистрСведений
ЗарплатаКВыплате : Остатки
ПараметрыПериодовСтажаПФР : РегистрСведений
ПлановыеНачисления : РегистрСведений
ОплатаВедомостейНаВыплатуЗарплаты : РегистрСведений
ДанныеТабельногоУчетаРабочегоВремениСотрудников : Обороты
ПлановыеУдержания : РегистрСведений
РеестрКадровыхПриказов : РегистрСведений
УдалитьИсторияНачисленийПоШтатномуРасписанию : РегистрСведений
БухучетРаспределениеОсновногоЗаработка : РегистрСведений
ВзаиморасчетыПоЗаймамСотрудникам : Остатки
ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаФСС : Обороты
АвансовыеПлатежиИностранцевПоНДФЛ : Остатки
ДанныеСтрахователейДляРасчетаСреднегоЗаработкаФСС : Обороты
}
@enduml
