@startuml ДоступностьРабочихЦентров
'!include templates.wsd
'..\include templates.wsd
class Документ.ДоступностьРабочихЦентров as "Доступность рабочих центров" <<Документы>>
{
..Реквизиты..
ВидРабочегоЦентра : Справочник.Вид рабочего центра
ВнесеныРучныеИзменения : Булево
ДатаГрафика : Дата
..Табличная часть \n Интервалы..
РабочийЦентр : Справочник.Рабочий центр
ДатаГрафика : Дата
ВремяНачала : Дата
ВремяОкончания : Дата
Количество : Число 10, 2
..Табличная часть \n Доступность..
РабочийЦентр : Справочник.Рабочий центр
Количество : Число 10, 0
ВнесеныРучныеИзменения : Булево
..Движения..
ДоступностьРабочихЦентров : РегистрСведений
ДоступностьВидовРабочихЦентров : Обороты
СостоянияРабочихЦентров : Обороты
}
@enduml
