@startuml ДоговорЗаймаСотруднику
'!include templates.wsd
'..\include templates.wsd
class Документ.ДоговорЗаймаСотруднику as "Договор займа сотруднику" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
СпособПредоставления : Способы предоставления займа сотруднику
Сумма : Число 15, 2
ДатаПредоставления : Дата
ДатаОкончания : Дата
ПроцентнаяСтавка : Число 4, 2
СпособПогашения : Способы погашения займа сотруднику
ВидПлатежей : Виды платежей погашения займа сотруднику
РазмерПлатежа : Число 15, 2
РазмерПогашения : Число 15, 2
ДатаНачалаПогашения : Дата
ОграничениеПлатежа : Число 15, 2
МатериальнаяВыгодаОблагаетсяНДФЛ : Булево
ЗаемПоДоговоруВыданПолностью : Булево
ДатаВыдачи : Дата
ФормаРасчетов : Формы оплаты
ЗаемЧастичноПогашен : Булево
ДатаПогашения : Дата
ПогашеннаяСуммаЗайма : Число 15, 2
ПогашенныеПроценты : Число 15, 2
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ТраншиЗайма..
ДатаПредоставления : Дата
Сумма : Число 15, 2
РазмерПогашения : Число 15, 2
ДатаПогашения : Дата
..Движения..
УсловияДоговораЗаймаСотруднику : РегистрСведений
ТраншиЗаймаСотруднику : РегистрСведений
ВзаиморасчетыПоЗаймамСотрудникам : Остатки
}
@enduml
