@startuml ВозвратТоваровМеждуОрганизациями
'!include templates.wsd
'..\include templates.wsd
class Документ.ВозвратТоваровМеждуОрганизациями as "Возврат товаров между организациями" <<Документы>>
{
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
Склад : Справочник.Склад (складская территория)
Валюта : Справочник.Валюта
ВидЦены : Справочник.Вид цены
ЦенаВключаетНДС : Булево
НалогообложениеНДС : Типы налогообложения НДС
СуммаДокумента : Число 15, 2
Организация : Справочник.Организация
БанковскийСчетОрганизации : Справочник.Банковский счет организации
ОрганизацияПолучатель : Справочник.Организация
БанковскийСчетОрганизацииПолучателя : Справочник.Банковский счет организации
Грузоотправитель : Справочник.Контрагент
БанковскийСчетГрузоотправителя : Справочник.Банковский счет
Грузополучатель : Справочник.Контрагент
БанковскийСчетГрузополучателя : Справочник.Банковский счет
АдресДоставки : Строка
ДоверенностьНомер : Строка
ДоверенностьДата : Дата
ДоверенностьВыдана : Строка
ДоверенностьЛицо : Строка
Подразделение : Справочник.Подразделение
Менеджер : Справочник.Пользователь
Комментарий : Строка
РасчетыЧерезОтдельногоКонтрагента : Булево
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
БанковскийСчетКонтрагента : Справочник.Банковский счет
НомерВходящегоДокумента : Строка
ДатаВходящегоДокумента : Дата
ДокументПоступления : Документ.Передача товаров
УдалитьПоТоварамКОформлению : Булево
ВидыЗапасовУказаныВручную : Булево
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
Договор : Справочник.Договор между организациями
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
Отпустил : Справочник.Физическое лицо
ОтпустилДолжность : Строка
Основание : Строка
ОснованиеДата : Дата
ОснованиеНомер : Строка
НаправлениеДеятельности : Справочник.Направление деятельности
ДоговорПродажи : Справочник.Договор с контрагентом
ДоговорПокупки : Справочник.Договор с контрагентом
УдалитьЕстьАлкогольнаяПродукцияДляРеализацииЕГАИС : Булево
ГруппаФинансовогоУчетаПолучателя : Справочник.Группа финансового учета расчетов
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ВидЦены : Справочник.Вид цены
Цена : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
Сумма : Число 15, 2
СуммаСНДС : Число 15, 2
Серия : Справочник.Серия номенклатуры
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
СтатусУказанияСерий : Число 2, 0
Назначение : Справочник.Назначение
ПоТоварамКОформлению : Булево
..Табличная часть \n ВидыЗапасов..
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
СуммаСНДС : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
ВидЗапасовПолучателя : Справочник.Вид запасов
ИдентификаторСтроки : Строка
УдалитьАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ДокументРеализации : Документ.Передача товаров
ВидЗапасовОтгрузки : Справочник.Вид запасов
СкладОтгрузки : Справочник.Склад (складская территория)
ПоТоварамКОформлению : Булево
..Табличная часть \n РасшифровкаПлатежа..
Заказ : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\rДокумент.Таможенная декларация на импорт\r...
Сумма : Число 15, 2
ВалютаВзаиморасчетов : Справочник.Валюта
СуммаВзаиморасчетов : Число 15, 2
..Движения..
ПрочиеДоходы : Остатки
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
РасчетыСКлиентами : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииТоваровПереданныеНаКомиссию : Остатки
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ТоварыКОформлениюОтчетовКомитенту : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНМатериалы : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
РасчетыСПоставщиками : Остатки
ТоварыПереданныеНаКомиссию : Остатки
Международный : РегистрБухгалтерии
Закупки : Обороты
РасходыПриУСНТовары : Остатки
НДСЗаписиКнигиПродаж : Обороты
РасчетыСКлиентамиПоДокументам : Остатки
ТоварыОрганизацийКПередаче : Остатки
РасчетыСПоставщикамиПоДокументам : Остатки
КнигаУчетаДоходовИРасходов : Обороты
ВыручкаИСебестоимостьПродаж : Обороты
ДвиженияНоменклатураНоменклатура : Обороты
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
ПартииЗатратНаВыпуск : Остатки
}
@enduml
