@startuml ЗаявкаНаВыпускКиЗГИСМ
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаявкаНаВыпускКиЗГИСМ as "Заявка на выпуск КиЗ для маркировки" <<Документы>>
{
..Реквизиты..
НомерГИСМ : Число 19, 0
Основание : Документ.Заказ поставщику\rДокумент.Заявка на выпуск КиЗ для маркировки
НомерДоговора : Строка
ДатаДоговора : Дата
СпособПолучения : Способы получения изготовленных КиЗ
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Контрагент : Справочник.Контрагент
Ответственный : Справочник.Пользователь
Комментарий : Строка
ДляМаркировкиОстатков : Булево
АдресДоставки : Строка
АдресДоставкиСтрокой : Строка
Автор : Справочник.Пользователь
GLNКонтрагента : Строка
..Табличная часть \n ЗаказанныеКиЗ..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Количество : Число 12, 0
..Табличная часть \n ВыпущенныеКиЗ..
ВидКиЗ : Виды КиЗ
RFIDTID : Строка
ДокументПоступления : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг
НомерКиЗ : Строка
СостояниеПодтверждения : Состояния отправки подтверждения ГИСМ
GTIN : Строка
СерийныйНомер : Строка
ДляМаркировкиОстатков : Булево
СпособВыпускаВОборот : Способы выпуска в оборот ГИСМ
РазмерКиЗ : Размеры КиЗ
RFIDEPC : Строка
Комментарий : Строка
ДатаВыпуска : Дата
ДатаРеализации : Дата
}
@enduml
