@startuml ПеремещениеВДругоеПодразделение
'!include templates.wsd
'..\include templates.wsd
class Документ.ПеремещениеВДругоеПодразделение as "Перемещение в другое подразделение" <<Документы>>
{
..Реквизиты..
ДатаПеремещения : Дата
Организация : Справочник.Организация
ПодразделениеПрежнее : Справочник.Подразделение
ОрганизацияНовая : Справочник.Организация
ПодразделениеНовое : Справочник.Подразделение
ПричинаПеревода : Строка
ОснованиеПеревода : Строка
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ИсправленныйДокумент : Документ.Перемещение в другое подразделение
Территория : Справочник.Территория
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Сотрудник
Должность : Справочник.Должность
ДолжностьПоШтатномуРасписанию : Справочник.Позиция
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОтношениеКЕНВД : Отношение к ЕНВД затрат на зарплату
СтатьяФинансирования : Справочник.Статья финансирования
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Движения..
ЗанятыеПозицииШтатногоРасписания : Остатки
КадроваяИсторияСотрудников : РегистрСведений
ТерриторииСотрудников : РегистрСведений
ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
ПараметрыПериодовСтажаПФР : РегистрСведений
РеестрКадровыхПриказов : РегистрСведений
}
@enduml
