@startuml ПересчетТоваров
'!include templates.wsd
'..\include templates.wsd
class Документ.ПересчетТоваров as "Пересчет товаров" <<Документы>>
{
..Реквизиты..
Исполнитель : Справочник.Пользователь
Комментарий : Строка
ОтборПересчета : Хранилище значения
Ответственный : Справочник.Пользователь
Помещение : Справочник.Помещение
Склад : Справочник.Склад (складская территория)
Статус : Статусы пересчетов товаров
ПечататьКоличествоПоУчету : Булево
УчетныеДанныеЗаполнены : Булево
ЯчейкаКонсолидацииИзлишковТоваров : Справочник.Складская ячейка
ЯчейкаКонсолидацииИспорченныхТоваров : Справочник.Складская ячейка
ИспользоватьОтдельнуюЯчейкуИзлишков : Булево
ИспользоватьОтдельнуюЯчейкуПорчи : Булево
БлокироватьЯчейки : Булево
..Табличная часть \n Товары..
Количество : Число 15, 3
КоличествоФакт : Число 15, 3
КоличествоУпаковок : Число 15, 3
КоличествоУпаковокФакт : Число 15, 3
Номенклатура : Справочник.Номенклатура
Упаковка : Справочник.Упаковка
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Ячейка : Справочник.Складская ячейка
ИзлишекПорча : Булево
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
..Движения..
ТоварныеМестаКОтражениюИзлишковНедостач : Остатки
ДвиженияСерийТоваров : Обороты
ТоварыКОформлениюИзлишковНедостач : Остатки
БлокировкиСкладскихЯчеек : РегистрСведений
ТоварыНаСкладах : Остатки
ОбеспечениеЗаказов : Остатки
СвободныеОстатки : Остатки
ТоварыВЯчейках : Остатки
}
@enduml
