@startuml ЗаказМатериаловВПроизводство
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаказМатериаловВПроизводство as "Заказ материалов в производство" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ЦеховаяКладовая : Справочник.Склад (складская территория)
Склад : Справочник.Склад (складская территория)
ДатаОтгрузки : Дата
ЖелаемаяДатаОтгрузки : Дата
МаксимальныйКодСтроки : Число 10, 0
Назначение : Справочник.Назначение
НеОтгружатьЧастями : Булево
Ответственный : Справочник.Пользователь
СостояниеЗаполненияМногооборотнойТары : Состояния заполнения многооборотной тары
УправлениеПроизводством2_2 : Булево
Статус : Статусы заказов материалов в производство
ХозяйственнаяОперация : Хозяйственные операции
Комментарий : Строка
ДокументОснование : Документ.Заказ на производство\rДокумент.Заказ материалов в производство\rДокумент.Заказ на сборку (разборку)\r...
ДлительностьПеремещения : Число 3, 0
ЖелаемаяДатаПоступления : Дата
ИспользоватьДлительностьПеремещения : Булево
НаправлениеДеятельности : Справочник.Направление деятельности
ОбосабливатьПоНазначениюЗаказа : Булево
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
НачалоОтгрузки : Дата
Отменено : Булево
КодСтроки : Число 10, 0
СтатусУказанияСерий : Число 2, 0
ВариантОбеспечения : Варианты обеспечения
Серия : Справочник.Серия номенклатуры
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
ОкончаниеПоступления : Дата
..Движения..
ТоварыКОтгрузке : Остатки
ЗаказыМатериаловВПроизводство : Остатки
ГрафикОтгрузкиТоваров : Остатки
ФактическиеДанныеБюджетирования : Обороты
ОбеспечениеЗаказов : Остатки
ДвижениеТоваров : Обороты
ЗаказыМатериаловСУчетомКорректировок : Обороты
СвободныеОстатки : Остатки
ГрафикПоступленияТоваров : Остатки
}
@enduml
