@startuml СписаниеОС2_4
'!include templates.wsd
'..\include templates.wsd
class Документ.СписаниеОС2_4 as "Списание ОС" <<Документы>>
{
..Реквизиты..
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ДокументВДругомУчете : Документ.Списание ОС
ДокументОснование : Документ.Инвентаризация ОС
Комментарий : Строка
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
ОтражатьВРеглУчете : Булево
ОтражатьВУпрУчете : Булево
Подразделение : Справочник.Подразделение
ПричинаСписания : Справочник.Причина списания ОС
СобытиеОС : Справочник.Событие ОС
СтатьяРасходов : Статья расходов
ХозяйственнаяОперация : Хозяйственные операции
ЧастичнаяЛиквидация : Булево
..Табличная часть \n ОС..
ОсновноеСредство : Справочник.Объект эксплуатации
СуммаСписанияУУ : Число 15, 2
СуммаСписанияБУ : Число 15, 2
СуммаСписанияНУ : Число 15, 2
СуммаСписанияПР : Число 15, 2
СуммаСписанияВР : Число 15, 2
..Табличная часть \n ПриходуемыеМЦ..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Количество : Число 15, 3
..Движения..
ПараметрыАмортизацииОСБухгалтерскийУчет : РегистрСведений
МестонахождениеОСБухгалтерскийУчет : РегистрСведений
ПрочиеДоходы : Остатки
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
СобытияОСОрганизаций : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
ПервоначальныеСведенияОС : РегистрСведений
СпособыОтраженияРасходовПоАмортизацииОСБухгалтерскийУчет : РегистрСведений
ПорядокУчетаОСБУ : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
СостоянияОСОрганизаций : РегистрСведений
Международный : РегистрБухгалтерии
НачислениеАмортизацииОСБухгалтерскийУчет : РегистрСведений
МестонахождениеОС : РегистрСведений
ПорядокУчетаОСУУ : РегистрСведений
АмортизацияОС : Остатки
ВыручкаИСебестоимостьПродаж : Обороты
СтоимостьОС : Остатки
НачислениеАмортизацииОСНалоговыйУчет : РегистрСведений
}
@enduml
