@startuml НазначениеПлановогоНачисления
'!include templates.wsd
'..\include templates.wsd
class Документ.НазначениеПлановогоНачисления as "Назначение планового начисления" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Начисление : Начисление
ДатаНазначения : Дата
ДатаОкончания : Дата
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОтношениеКЕНВД : Отношение к ЕНВД затрат на зарплату
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Сотрудник
ДатаНазначения : Дата
ДатаОкончания : Дата
СовокупнаяТарифнаяСтавка : Число 15, 5
ВидТарифнойСтавки : Виды тарифных ставок
Размер : Число 15, 3
ИдентификаторСтрокиСотрудника : Число 7, 0
..Табличная часть \n ПоказателиСотрудников..
Показатель : Справочник.Показатель
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Значение : Число 15, 5
ИдентификаторСтрокиСотрудника : Число 7, 0
УдалитьСотрудник : Справочник.Сотрудник
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Движения..
УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников : РегистрСведений
ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
БухучетПлановыхНачислений : РегистрСведений
ПлановыеНачисления : РегистрСведений
}
@enduml
