@startuml ПереоценкаНМА2_4
'!include templates.wsd
'..\include templates.wsd
class Документ.ПереоценкаНМА2_4 as "Переоценка НМА" <<Документы>>
{
..Реквизиты..
ОтражатьВУпрУчете : Булево
ОтражатьВРеглУчете : Булево
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
СтатьяДоходов : Статьи доходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ДокументВДругомУчете : Документ.Переоценка НМА
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n НМА..
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
СтоимостьУУ : Число 15, 2
СтоимостьБУ : Число 15, 2
..Движения..
ПрочиеДоходы : Остатки
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
ПервоначальныеСведенияНМА : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
СтоимостьНМА : Остатки
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
АмортизацияНМА : Остатки
Международный : РегистрБухгалтерии
ВыручкаИСебестоимостьПродаж : Обороты
}
@enduml
