@startuml УдалитьЗапросНаВыпискуИзЕГРЮЛ_ЕГРИП
'!include templates.wsd
'..\include templates.wsd
class Документ.УдалитьЗапросНаВыпискуИзЕГРЮЛ_ЕГРИП as "(Не используется) Запрос на выписку из ЕГРЮЛ/ЕГРИП" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ПараметрЗапроса : Строка
ВидПараметраЗапроса : (Не используется) Виды параметров запроса на выписку из ЕГРЮЛ/ЕГРИП
}
@enduml
