@startuml ИсполнительныйЛист
'!include templates.wsd
'..\include templates.wsd
class Документ.ИсполнительныйЛист as "Исполнительный лист" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
ВидИсполнительногоДокумента : Виды исполнительных документов
РеквизитыИсполнительногоДокумента : Строка
Получатель : Справочник.Контрагент
АдресПолучателя : Строка
АдресПолучателяПредставление : Строка
ДатаДействия : Дата
ДатаОкончания : Дата
СпособРасчета : Способы расчета удержания по исполнительному документу
ВидБазы : Виды базы удержания по исполнительному документу
Удержание : Удержание
Процент : Число 5, 2
Сумма : Число 13, 2
Числитель : Число 2, 0
Знаменатель : Число 2, 0
ПрожиточныйМинимум : Справочник.Прожиточный минимум
ПрекратитьПоДостижениюПредела : Булево
Предел : Число 15, 2
УчитыватьБольничныеЛисты : Булево
ПлатежныйАгент : Справочник.Контрагент
ТарифПлатежногоАгента : Справочник.Тариф платежного агента
УдержаниеВознагражденияПлатежногоАгента : Удержание
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
УсловияУдержанияПоИсполнительномуДокументу : РегистрСведений
УдержанияДоПределаПоСотрудникам : Остатки
ПредельныеСуммыУдержанийСотрудников : РегистрСведений
ПлановыеУдержания : РегистрСведений
}
@enduml
