@startuml КорректировкаПриобретения
'!include templates.wsd
'..\include templates.wsd
class Документ.КорректировкаПриобретения as "Корректировка приобретения" <<Документы>>
{
..Реквизиты..
ДокументОснование : Документ.Приобретение товаров и услуг\rДокумент.Приобретение услуг и прочих активов
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
Соглашение : Справочник.Соглашение об условиях закупок
Организация : Справочник.Организация
Договор : Справочник.Договор с контрагентом
Склад : Справочник.Склад (складская территория)
Подразделение : Справочник.Подразделение
Сделка : Справочник.Сделка с клиентом
Валюта : Справочник.Валюта
ВалютаВзаиморасчетов : Справочник.Валюта
Менеджер : Справочник.Пользователь
СуммаДокумента : Число 15, 2
ДатаПлатежа : Дата
ФормаОплаты : Формы оплаты
ЦенаВключаетНДС : Булево
НалогообложениеНДС : Типы налогообложения НДС
ПоступлениеПоЗаказам : Булево
СтатьяДоходов : Статья актива/пассива\rСтатьи доходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
СтатьяРасходов : Статья расходов\rСтатья актива/пассива
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Согласован : Булево
НомерВходящегоДокумента : Строка
ДатаВходящегоДокумента : Дата
Комментарий : Строка
ПорядокРасчетов : Детализация расчетов
ВидКорректировки : Хозяйственные операции
СуммаВзаиморасчетов : Число 15, 2
АктОРасхожденияхПослеПриемкиОснование : Документ.Акт о расхождениях после приемки
НаправлениеДеятельности : Справочник.Направление деятельности
АналитикаАктивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
СчетУчетаАктивов : Счет бухгалтерского учета
Субконто1Активов : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2Активов : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3Активов : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
АналитикаПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
СчетУчетаПассивов : Счет бухгалтерского учета
Субконто1Пассивов : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2Пассивов : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3Пассивов : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Курс : Число 10, 4
Кратность : Число 10, 0
..Табличная часть \n Товары..
НоменклатураПоставщика : Справочник.Номенклатура поставщика
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Содержание : Строка
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Цена : Число 15, 2
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
ЗаказПоставщику : Документ.Заказ поставщику
КодСтроки : Число 10, 0
Склад : Справочник.Склад (складская территория)
НомерГТД : Справочник.Номер ГТД
СтатьяРасходов : Статья расходов\rСтатья актива/пассива
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Сделка : Справочник.Сделка с клиентом
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
СуммаВзаиморасчетов : Число 15, 2
СуммаНДСВзаиморасчетов : Число 15, 2
Подразделение : Справочник.Подразделение
СписатьНаРасходы : Булево
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
..Табличная часть \n Расхождения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Содержание : Строка
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Цена : Число 15, 2
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
ЗаказПоставщику : Документ.Заказ поставщику
КодСтроки : Число 10, 0
Склад : Справочник.Склад (складская территория)
НомерГТД : Справочник.Номер ГТД
СтатьяРасходов : Статья расходов\rСтатья актива/пассива
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Сделка : Справочник.Сделка с клиентом
ВариантОтражения : Варианты отражения корректировок поступлений
ВидЗапасов : Справочник.Вид запасов
УдалитьАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
ИдентификаторСтроки : Строка
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
СуммаВзаиморасчетов : Число 15, 2
СуммаНДСВзаиморасчетов : Число 15, 2
Подразделение : Справочник.Подразделение
СписатьНаРасходы : Булево
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n ВидыЗапасов..
ИдентификаторСтроки : Строка
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
НомерГТД : Справочник.Номер ГТД
ВидЗапасов : Справочник.Вид запасов
Количество : Число 15, 3
ЗаказПоставщику : Документ.Заказ поставщику
ВидЗапасовПолучателя : Справочник.Вид запасов
Цена : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
СуммаНДСВзаиморасчетов : Число 15, 2
Сделка : Справочник.Сделка с клиентом
ВариантОтражения : Варианты отражения корректировок поступлений
КодСтроки : Число 10, 0
Подразделение : Справочник.Подразделение
СписатьНаРасходы : Булево
СтатьяРасходов : Статья расходов\rСтатья актива/пассива
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
..Движения..
ПрочиеДоходы : Остатки
ТоварыУПартнеров : Остатки
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
ТоварыКОформлениюИзлишковНедостач : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ДвиженияКонтрагентДоходыРасходы : Обороты
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНМатериалы : Остатки
РасходыПриУСН : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
РасчетыСПоставщиками : Остатки
Международный : РегистрБухгалтерии
Закупки : Обороты
ДвижениеТоваров : Обороты
РасходыПриУСНТовары : Остатки
НДСЗаписиКнигиПродаж : Обороты
РасчетыСПоставщикамиПоДокументам : Остатки
КнигаУчетаДоходовИРасходов : Обороты
МатериалыИРаботыВПроизводстве : Остатки
ВыручкаИСебестоимостьПродаж : Обороты
СвободныеОстатки : Остатки
ТоварыОрганизаций : Остатки
ПринятаяВозвратнаяТара : Остатки
ПартииПроизводственныхЗатрат : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
