@startuml РаспределениеПроизводственныхЗатрат
'!include templates.wsd
'..\include templates.wsd
class Документ.РаспределениеПроизводственныхЗатрат as "Распределение материалов и работ" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Серия : Справочник.Серия номенклатуры
КоличествоФакт : Число 15, 3
КоличествоФактНЗП : Число 15, 3
Ответственный : Справочник.Пользователь
Комментарий : Строка
СтатусУказанияСерий : Число 2, 0
Количество : Число 15, 3
Назначение : Справочник.Назначение
ПравилоРаспределения : Справочник.Правило распределения расходов
БазаРаспределения : Типы показателей для распределения статей расходов
КоличествоКРаспределениюПоПравилу : Число 15, 3
СтатьяКалькуляции : Справочник.Статьи калькуляции
Склад : Справочник.Склад (складская территория)
Распределить : Число 15, 3
НовоеПроизводство : Булево
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
КоличествоПоЭтапамВручную : Число 15, 3
КоличествоНаСтатьиРасходов : Число 15, 3
..Табличная часть \n ЭтапыГрафикаПроизводства..
ЗаказНаПроизводство : Документ.Заказ на производство\rДокумент.Заказ переработчику
КодСтрокиПродукция : Число 10, 0
Этап : Справочник.Этап ресурсной спецификации
СтатьяКалькуляции : Справочник.Статьи калькуляции
Количество : Число 15, 3
..Табличная часть \n ПартииПроизводства..
ПартияПроизводства : Документ.Этап производства\rДокумент.Отчет переработчика\rДокумент.Выпуск продукции и выполнение работ\r...
Подразделение : Справочник.Подразделение
Этап : Документ.Этап производства\rДокумент.Производство без заказа
СтатьяКалькуляции : Справочник.Статьи калькуляции
Количество : Число 15, 3
АналитикаУчетаПартийПроизводства : Справочник.Ключ аналитики учета партий производства
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ИдентификаторСтроки : Строка
..Табличная часть \n ВыпускиБезРаспоряжения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Серия : Справочник.Серия номенклатуры
Спецификация : Справочник.Ресурсная спецификация
СтатьяКалькуляции : Справочник.Статьи калькуляции
Количество : Число 15, 3
ДокументВыпуска : Документ.Выпуск продукции и выполнение работ
КодСтроки : Число 10, 0
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
..Табличная часть \n ПрочиеРасходы..
СтатьяРасходов : Статья расходов\rСтатья актива/пассива
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
Количество : Число 15, 3
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
ИдентификаторСтроки : Строка
..Табличная часть \n Серии..
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Серия : Справочник.Серия номенклатуры
Назначение : Справочник.Назначение
КоличествоКРаспределениюПоПравилу : Число 15, 3
..Табличная часть \n ОтборПоГруппамПродукции..
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
..Табличная часть \n ОтборПоМатериалам..
Материал : Справочник.Номенклатура
..Табличная часть \n ОтборПоВидамРабот..
ВидРабот : Справочник.Вид работ сотрудников
..Табличная часть \n ВидыЗапасов..
АналитикаУчетаНоменклатуры : Справочник.Номенклатура\rСправочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
СтатьяРасходов : Статья расходов\rСтатья актива/пассива
КорАналитикаУчетаНоменклатуры : Справочник.Номенклатура\rСправочник.Ключ аналитики учета номенклатуры
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
ХозяйственнаяОперация : Хозяйственные операции
ПартияПроизводства : Документ.Этап производства\rДокумент.Производство без заказа
АналитикаУчетаПартийПроизводства : Справочник.Ключ аналитики учета партий производства
Количество : Число 15, 3
ИдентификаторСтроки : Строка
ВидЗапасовПолучателя : Справочник.Вид запасов
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ТоварыКОтгрузке : Остатки
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ТоварыКОформлениюОтчетовКомитенту : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНМатериалы : Остатки
РасходыПриУСН : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
Международный : РегистрБухгалтерии
РасходыПриУСНТовары : Остатки
НДСЗаписиКнигиПродаж : Обороты
КнигаУчетаДоходовИРасходов : Обороты
МатериалыИРаботыВПроизводстве : Остатки
СвободныеОстатки : Остатки
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
ПартииПроизводственныхЗатрат : Остатки
ПартииНезавершенногоПроизводства : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
