@startuml ЗаявлениеОПодтвержденииПраваНаЗачетАвансовПоНДФЛ
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаявлениеОПодтвержденииПраваНаЗачетАвансовПоНДФЛ as "Заявление о подтверждении права на зачет авансов по НДФЛ" <<Документы>>
{
..Реквизиты..
НалоговыйПериод : Число 4, 0
Организация : Справочник.Организация
ИдентификаторФайла : Строка
ФайлСформирован : Булево
НалоговыйПериодДата : Дата
КодИФНС : Строка
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
КоличествоПодтверждающихДокументов : Число 3, 0
Руководитель : Справочник.Физическое лицо
ДокументПринятВНалоговыйОрган : Булево
Телефон : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Физическое лицо
ИНН : Строка
Фамилия : Строка
Имя : Строка
Отчество : Строка
ВидДокумента : Справочник.Вид документа физических лиц
СерияДокумента : Строка
НомерДокумента : Строка
КемВыданДокумент : Строка
ДатаВыдачиДокумента : Дата
ДатаРождения : Дата
ФиксИНН : Булево
ФиксФамилия : Булево
ФиксИмя : Булево
ФиксОтчество : Булево
ФиксДатаРождения : Булево
ФиксВидДокумента : Булево
ФиксСерияДокумента : Булево
ФиксНомерДокумента : Булево
ФиксДатаВыдачиДокумента : Булево
ФиксКемВыданДокумент : Булево
}
@enduml
