@startuml ПереоценкаНМА
'!include templates.wsd
'..\include templates.wsd
class Документ.ПереоценкаНМА as "Переоценка НМА (2.2)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Ответственный : Справочник.Пользователь
Комментарий : Строка
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
Стоимость : Число 15, 2
СчетДооценки : Счет бухгалтерского учета
СтатьяДоходов : Статьи доходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
..Табличная часть \n НачисленнаяАмортизация..
ОбъектУчета : Справочник.Нематериальные активы и расходы на НИОКР
Подразделение : Справочник.Подразделение
СуммаБУ : Число 15, 2
СуммаНУ : Число 15, 2
СуммаПР : Число 15, 2
СуммаВР : Число 15, 2
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ПередаватьРасходыВДругуюОрганизацию : Булево
ОрганизацияПолучательРасходов : Справочник.Организация
СчетПередачиРасходов : Счет бухгалтерского учета
ЭтоЦелевыеСредства : Булево
НаправлениеДеятельности : Справочник.Направление деятельности
..Движения..
ПрочиеДоходы : Остатки
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
ПервоначальныеСведенияНМАБухгалтерскийУчет : РегистрСведений
ВыручкаИСебестоимостьПродаж : Обороты
}
@enduml
