@startuml ПачкаДокументовАДВ_1
'!include templates.wsd
'..\include templates.wsd
class Документ.ПачкаДокументовАДВ_1 as "Пачка документов АДВ-1" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
НомерПачки : Число 5, 0
ИмяФайлаДляПФР : Строка
ДокументПринятВПФР : Булево
Исполнитель : Справочник.Физическое лицо
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ФайлСформирован : Булево
ОкончаниеОтчетногоПериода : Дата
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Физическое лицо
АдресРегистрации : Строка
АдресФактический : Строка
Телефоны : Строка
Фамилия : Строка
Имя : Строка
Отчество : Строка
Пол : Пол физического лица
ДатаРождения : Дата
МестоРождения : Строка
Гражданство : Справочник.Страна мира
ВидДокумента : Справочник.Вид документа физических лиц
СерияДокумента : Строка
НомерДокумента : Строка
ДатаВыдачи : Дата
КемВыдан : Строка
АдресРегистрацииПредставление : Строка
АдресФактическийПредставление : Строка
МестоРожденияПредставление : Строка
}
@enduml
