@startuml ИзменениеСостоянияОС
'!include templates.wsd
'..\include templates.wsd
class Документ.ИзменениеСостоянияОС as "Изменение состояния ОС" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
СобытиеОС : Справочник.Событие ОС
ВлияетНаНачислениеАмортизации : Булево
НачислятьАмортизацию : Булево
ОтражатьВБухгалтерскомУчете : Булево
ОтражатьВНалоговомУчете : Булево
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ОС..
ОсновноеСредство : Справочник.Объект эксплуатации
..Движения..
СобытияОСОрганизаций : РегистрСведений
СостоянияОСОрганизаций : РегистрСведений
НачислениеАмортизацииОСБухгалтерскийУчет : РегистрСведений
НачислениеАмортизацииОСНалоговыйУчет : РегистрСведений
}
@enduml
