@startuml РаспределениеОсновногоЗаработка
'!include templates.wsd
'..\include templates.wsd
class Документ.РаспределениеОсновногоЗаработка as "Распределение основного заработка" <<Документы>>
{
..Реквизиты..
ПериодРегистрации : Дата
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n РаспределениеОсновногоЗаработка..
СтатьяФинансирования : Справочник.Статья финансирования
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОблагаетсяЕНВД : Булево
ДоляРаспределения : Число 14, 3
..Движения..
БухучетРаспределениеОсновногоЗаработка : РегистрСведений
}
@enduml
