@startuml РасходныйОрдерНаТовары
'!include templates.wsd
'..\include templates.wsd
class Документ.РасходныйОрдерНаТовары as "Расходный ордер на товары" <<Документы>>
{
..Реквизиты..
ВсегоМест : Число 10, 0
ДатаОтгрузки : Дата
ЗаданиеНаПеревозку : Документ.Задание на перевозку
ЗонаОтгрузки : Справочник.Складская ячейка
Комментарий : Строка
Контролер : Справочник.Пользователь
Ответственный : Справочник.Пользователь
ОтгрузкаПоЗаданиюНаПеревозку : Булево
Получатель : Справочник.Подразделение\rСправочник.Партнер\rСправочник.Физическое лицо\r...
Помещение : Справочник.Помещение
ПорядокДоставки : Строка
Приоритет : Справочник.Приоритет
РежимПросмотраПоТоварам : Число 1, 0
Склад : Справочник.Склад (складская территория)
СкладскаяОперация : Складские операции
Статус : Статусы расходных ордеров
..Табличная часть \n ТоварыПоРаспоряжениям..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
Распоряжение : Документ.Внутреннее потребление товаров\rДокумент.Акт о расхождениях после перемещения\rДокумент.Этап производства\r...
Количество : Число 15, 3
..Табличная часть \n ОтгружаемыеТовары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
ЭтоУпаковочныйЛист : Булево
ЭтоСлужебнаяСтрокаПустогоУпаковочногоЛиста : Число 1, 0
УпаковочныйЛистРодитель : Документ.Упаковочный лист
УпаковочныйЛист : Документ.Упаковочный лист
Упаковка : Справочник.Упаковка
Количество : Число 15, 3
КоличествоУпаковок : Число 15, 3
Действие : Действия со строками ордеров на отгрузку
..Движения..
ТоварыКОтгрузке : Остатки
ДвиженияСерийТоваров : Обороты
ТоварыКОтбору : Остатки
ТоварыНаСкладах : Остатки
ТоварыВЯчейках : Остатки
}
@enduml
