@startuml ПереносОтпуска
'!include templates.wsd
'..\include templates.wsd
class Документ.ПереносОтпуска as "Перенос отпуска" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ВидОтпуска : Справочник.Вид отпуска
ИсходнаяДатаНачала : Дата
ДатаНачала : Дата
ДатаОкончания : Дата
КоличествоДней : Число 3, 0
ПереносПоИнициативеСотрудника : Булево
ПричинаПереноса : Строка
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
