@startuml АмортизацияОС2_4
'!include templates.wsd
'..\include templates.wsd
class Документ.АмортизацияОС2_4 as "Амортизация и износ основных средств" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
НомерПакета : Число 10, 0
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Движения..
ПрочиеРасходы : Остатки
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ПартииРасходовНаСебестоимостьТоваров : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
НачислениеАмортизацииОСБухгалтерскийУчет : РегистрСведений
АмортизацияОС : Остатки
ВыручкаИСебестоимостьПродаж : Обороты
СтоимостьОС : Остатки
НачислениеАмортизацииОСНалоговыйУчет : РегистрСведений
}
@enduml
