@startuml ПодготовкаКПередачеНМА2_4
'!include templates.wsd
'..\include templates.wsd
class Документ.ПодготовкаКПередачеНМА2_4 as "Подготовка к передаче НМА" <<Документы>>
{
..Реквизиты..
ОтражатьВУпрУчете : Булево
ОтражатьВРеглУчете : Булево
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n НМА..
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
..Движения..
ПрочиеДоходы : Остатки
ПорядокУчетаНМАУУ : РегистрСведений
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
ПервоначальныеСведенияНМА : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
СтоимостьНМА : Остатки
Хозрасчетный : РегистрБухгалтерии
ПорядокУчетаНМАБУ : РегистрСведений
ОтражениеДокументовВМеждународномУчете : РегистрСведений
АмортизацияНМА : Остатки
Международный : РегистрБухгалтерии
ВыручкаИСебестоимостьПродаж : Обороты
}
@enduml
