@startuml СправкиСПАРКРиски
'!include templates.wsd
'..\include templates.wsd
class Документ.СправкиСПАРКРиски as "Справки 1СПАРК Риски" <<Документы>>
{
..Реквизиты..
ИНН : Строка
Контрагент : Справочник.Контрагент
Пользователь : Справочник.Пользователь
Состояние : Состояния справки 1СПАРК Риски
Идентификатор : Уникальный идентификатор
}
@enduml
