@startuml ВозвратНДФЛ
'!include templates.wsd
'..\include templates.wsd
class Документ.ВозвратНДФЛ as "Возврат НДФЛ" <<Документы>>
{
..Реквизиты..
Месяц : Дата
Организация : Справочник.Организация
Сотрудник : Справочник.Физическое лицо
ПорядокВыплаты : Характер выплаты зарплаты
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n СуммыВозврата..
НалоговыйПериод : Число 4, 0
УдалитьОбособленноеПодразделение : Справочник.Территория\rСправочник.Подразделение
ПоСтавке13 : Число 10, 0
ПоСтавке09 : Число 10, 0
ПоСтавке35 : Число 10, 0
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
МесяцНалоговогоПериода : Дата
КатегорияДохода : Категории доходов НДФЛ
..Движения..
РасчетыНалогоплательщиковСБюджетомПоНДФЛ : Остатки
ВзаиморасчетыССотрудниками : Остатки
НачисленияУдержанияПоСотрудникам : Обороты
ПорядокВыплатыДокументов : РегистрСведений
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
ЗарплатаКВыплатеАвансом : Остатки
РасчетыНалоговыхАгентовСБюджетомПоНДФЛ : Остатки
ЗарплатаКВыплате : Остатки
}
@enduml
