@startuml ИнвентаризацияНаличныхДенежныхСредств
'!include templates.wsd
'..\include templates.wsd
class Документ.ИнвентаризацияНаличныхДенежныхСредств as "Инвентаризация наличных денежных средств" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
КассоваяКнига : Справочник.Кассовая книга
Кассир : Справочник.Лицо с правом подписи
Руководитель : Справочник.Лицо с правом подписи
Ответственный : Справочник.Пользователь
ПоследнийНомерПКО : Строка
ПоследнийНомерРКО : Строка
СуммаПоУчетуВсего : Число 15, 2
СуммаПоФактуВсего : Число 15, 2
Комментарий : Строка
..Табличная часть \n Кассы..
Касса : Справочник.Касса
СуммаПоУчету : Число 15, 2
СуммаПоФакту : Число 15, 2
СуммаРасхождения : Число 15, 2
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
Подразделение : Справочник.Подразделение
СтатьяДоходовРасходов : Статья расходов\rСтатьи доходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ИдентификаторСтроки : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ПрочиеДоходы : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДенежныеСредстваНаличные : Остатки
РасходыПриУСН : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
ДвиженияДенежныеСредстваДоходыРасходы : Обороты
КнигаУчетаДоходовИРасходов : Обороты
}
@enduml
