@startuml ОприходованиеИзлишковТоваров
'!include templates.wsd
'..\include templates.wsd
class Документ.ОприходованиеИзлишковТоваров as "Оприходование излишков товаров" <<Документы>>
{
..Реквизиты..
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
Комментарий : Строка
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
Подразделение : Справочник.Подразделение
Склад : Справочник.Склад (складская территория)
СтатьяДоходов : Статьи доходов
ВидЦены : Справочник.Вид цены
ПересчетТоваров : Документ.Пересчет товаров
НаправлениеДеятельности : Справочник.Направление деятельности
Основание : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг
УдалитьЕстьАлкогольнаяПродукцияДляПостановкиНаБалансЕГАИС : Булево
Валюта : Справочник.Валюта
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Количество : Число 15, 3
Цена : Число 15, 2
Сумма : Число 15, 2
НомерГТД : Справочник.Номер ГТД
ВидЗапасов : Справочник.Вид запасов
УдалитьАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
ИдентификаторСтроки : Строка
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ПрочиеДоходы : Остатки
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
ТоварыКОформлениюИзлишковНедостач : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
Международный : РегистрБухгалтерии
СвободныеОстатки : Остатки
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
}
@enduml
