@startuml РаспределениеДоходовИРасходовПоНаправлениямДеятельности
'!include templates.wsd
'..\include templates.wsd
class Документ.РаспределениеДоходовИРасходовПоНаправлениямДеятельности as "Распределение доходов и расходов по направлениям деятельности" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
РаспределениеПоВсемОрганизациям : Булево
ПредставлениеОрганизаций : Строка
НаправлениеДеятельности : Справочник.Направление деятельности
..Табличная часть \n Доходы..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
СтатьяДоходов : Статьи доходов
СпособРаспределения : Справочник.Способ распределения доходов и расходов по направлениям деятельности
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
Сумма : Число 15, 2
ТребуетсяСпособРаспределения : Булево
НаправлениеДеятельности : Справочник.Направление деятельности
СуммаУпр : Число 15, 2
СуммаРегл : Число 15, 2
..Табличная часть \n Расходы..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
СтатьяРасходов : Статья расходов
СпособРаспределения : Справочник.Способ распределения доходов и расходов по направлениям деятельности
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Сумма : Число 15, 2
ТребуетсяСпособРаспределения : Булево
НаправлениеДеятельности : Справочник.Направление деятельности
СуммаУпр : Число 15, 2
СуммаРегл : Число 15, 2
ПостояннаяРазница : Число 15, 2
ВременнаяРазница : Число 15, 2
..Движения..
ПрочиеДоходы : Остатки
ПрочиеРасходы : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
РасчетНормированияРасходов : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ФинансовыеРезультаты : Обороты
Международный : РегистрБухгалтерии
ДолиСписанияКосвенныхРасходов : РегистрСведений
}
@enduml
