@startuml ПереводНаОплатуПоСреднемуЗаработку
'!include templates.wsd
'..\include templates.wsd
class Документ.ПереводНаОплатуПоСреднемуЗаработку as "Перевод на оплату по среднему заработку" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ВидРасчета : Начисление
ДатаНачалаСобытия : Дата
ДатаНачала : Дата
ДатаОкончания : Дата
ПериодРасчетаСреднегоЗаработкаНачало : Дата
ПериодРасчетаСреднегоЗаработкаОкончание : Дата
ФиксПериодРасчетаСреднегоЗаработка : Булево
СреднийЗаработок : Число 15, 2
ПроцентОплаты : Число 6, 2
ИсправленныйДокумент : Документ.Перевод на оплату по среднему заработку
РазмерОплатыУтвержден : Булево
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ДанныеОбИндексации..
Сотрудник : Справочник.Сотрудник
Период : Дата
КоэффициентИндексации : Число 9, 8
..Табличная часть \n ОтработанноеВремяДляСреднегоОбщий..
Сотрудник : Справочник.Сотрудник
ПорядокРасчета : Порядок расчета среднего заработка общий
Период : Дата
ОтработаноДней : Число 7, 2
ОтработаноДнейПятидневка : Число 7, 2
ОтработаноЧасов : Число 7, 2
ОтработаноДнейШестидневка : Число 7, 2
ОтработаноДнейКалендарных : Число 7, 2
НормаДнейПроизводственныйКалендарь : Число 7, 2
ОтработаноЧасовПятидневка : Число 5, 2
НормаЧасовПроизводственныйКалендарь : Число 5, 2
Источник : Источники данных для расчета среднего заработка
..Табличная часть \n СреднийЗаработокОбщий..
Сотрудник : Справочник.Сотрудник
ПорядокРасчета : Порядок расчета среднего заработка общий
СоставнаяЧасть : Учет начислений в среднем заработке общий
СтатьяФинансирования : Справочник.Статья финансирования
Период : Дата
Индексируется : Булево
Сумма : Число 15, 2
Год : Число 4, 0
ДатаНачалаБазовогоПериода : Дата
КоличествоМесяцев : Число 3, 0
Источник : Источники данных для расчета среднего заработка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n КоэффициентыРаспределенияСреднегоЗаработка..
СтатьяФинансирования : Справочник.Статья финансирования
Коэффициент : Число 15, 2
..Движения..
ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
КоэффициентыРаспределенияСреднегоЗаработка : РегистрСведений
ПлановыеНачисления : РегистрСведений
}
@enduml
