@startuml ПрекращениеПлановогоНачисления
'!include templates.wsd
'..\include templates.wsd
class Документ.ПрекращениеПлановогоНачисления as "Прекращение планового начисления" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ДокументОснование : Документ.Назначение планового начисления
Начисление : Начисление
ДатаПрекращения : Дата
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Сотрудник
ДатаПрекращения : Дата
СовокупнаяТарифнаяСтавка : Число 15, 5
ВидТарифнойСтавки : Виды тарифных ставок
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Движения..
УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников : РегистрСведений
БухучетПлановыхНачислений : РегистрСведений
ПлановыеНачисления : РегистрСведений
}
@enduml
