@startuml ВозвратПодарочныхСертификатов
'!include templates.wsd
'..\include templates.wsd
class Документ.ВозвратПодарочныхСертификатов as "Возврат подарочных сертификатов" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Валюта : Справочник.Валюта
СуммаДокумента : Число 15, 2
Кассир : Справочник.Пользователь
Комментарий : Строка
Статус : Статусы чеков ККМ
КассаККМ : Справочник.Кассы ККМ
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
РеализацияПодарочныхСертификатов : Документ.Реализация подарочных сертификатов
ВыданоНаличными : Число 15, 2
КассоваяСмена : Документ.Кассовая смена
Партнер : Справочник.Партнер
УдалитьНомерЧекаККМ : Число 8, 0
УдалитьВариантОтправкиЭлектронногоЧека : Варианты отправки электронного чека покупателю
УдалитьКонтактныеДанныеЭлектронногоЧека : Строка
..Табличная часть \n ПодарочныеСертификаты..
ПодарочныйСертификат : Справочник.Подарочный сертификат
Сумма : Число 15, 2
ИдентификаторСтроки : Строка
..Табличная часть \n ОплатаПлатежнымиКартами..
ЭквайринговыйТерминал : Справочник.Эквайринговый терминал
НомерПлатежнойКарты : Строка
Сумма : Число 15, 2
КодАвторизации : Строка
СсылочныйНомер : Строка
НомерЧекаЭТ : Строка
ОплатаОтменена : Булево
..Движения..
ИсторияПодарочныхСертификатов : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДенежныеСредстваКонтрагент : Обороты
ПодарочныеСертификаты : Остатки
ДенежныеСредстваВПути : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ДенежныеСредстваВКассахККМ : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
РасчетыПоЭквайрингу : Остатки
}
@enduml
