@startuml ПеремещениеВЭксплуатации
'!include templates.wsd
'..\include templates.wsd
class Документ.ПеремещениеВЭксплуатации as "Перемещение в эксплуатации" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Ответственный : Справочник.Пользователь
Комментарий : Строка
ПодразделениеПолучатель : Справочник.Подразделение
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
ПартияТМЦВЭксплуатации : Справочник.Партии ТМЦ в эксплуатации
Количество : Число 15, 3
ФизическоеЛицо : Справочник.Физическое лицо
ФизическоеЛицоПолучатель : Справочник.Физическое лицо
..Движения..
ФактическиеДанныеБюджетирования : Обороты
ТМЦВЭксплуатации : Обороты
}
@enduml
