@startuml ДоступностьВидаРабочихЦентров
'!include templates.wsd
'..\include templates.wsd
class Документ.ДоступностьВидаРабочихЦентров as "Доступность вида рабочих центров" <<Документы>>
{
..Реквизиты..
ВидРабочегоЦентра : Справочник.Вид рабочего центра
ДатаИнтервала : Дата
Количество : Число 10, 2
..Движения..
ДоступностьВидовРабочихЦентров : Обороты
}
@enduml
