@startuml УтверждениеТарифнойСетки
'!include templates.wsd
'..\include templates.wsd
class Документ.УтверждениеТарифнойСетки as "Утверждение тарифной группы" <<Документы>>
{
..Реквизиты..
ТарифнаяСетка : Справочник.Тарифная группа
ДатаВступленияВСилу : Дата
НеобходимРасчетФОТ : Булево
БазовыйТарифГруппы : Число 10, 2
ВидТарифнойСетки : Виды тарифных сеток
СпособОкругления : Справочник.Способ округления
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Тарифы..
РазрядКатегория : Справочник.Квалификационный разряд (категория)
РазрядныйКоэффициент : Число 15, 4
Тариф : Число 15, 2
Отменить : Булево
..Табличная часть \n УдалитьНачисленияСотрудников..
Сотрудник : Справочник.Сотрудник
Начисление : Начисление
Размер : Число 15, 2
..Табличная часть \n УдалитьПоказатели..
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
Показатель : Справочник.Показатель
Значение : Число 15, 5
..Табличная часть \n УдалитьШтатноеРасписание..
Позиция : Справочник.Позиция
Показатель : Справочник.Показатель
Значение : Число 15, 5
ЗначениеМин : Число 15, 5
ЗначениеМакс : Число 15, 5
РазрядКатегория : Справочник.Квалификационный разряд (категория)
..Табличная часть \n УдалитьПересчетТарифныхСтавок..
Сотрудник : Справочник.Сотрудник
СовокупнаяТарифнаяСтавка : Число 15, 5
ВидТарифнойСтавки : Виды тарифных ставок
..Движения..
ИсторияПоказателейПоШтатномуРасписанию : РегистрСведений
УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников : РегистрСведений
ИсторияИспользованияШтатногоРасписания : РегистрСведений
КоэффициентИндексацииЗаработка : РегистрСведений
ЗначенияТарифов : РегистрСведений
ИсторияНачисленийПоШтатномуРасписанию : РегистрСведений
ЗначенияБазовыхТарифов : РегистрСведений
ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
БухучетПлановыхНачислений : РегистрСведений
ПлановыеНачисления : РегистрСведений
}
@enduml
