@startuml АктПриемкиВыполненныхРаботОказанныхУслуг
'!include templates.wsd
'..\include templates.wsd
class Документ.АктПриемкиВыполненныхРаботОказанныхУслуг as "Акт приемки выполненных работ" <<Документы>>
{
..Реквизиты..
МесяцНачисления : Дата
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
Договор : Документ.Договор авторского заказа\rДокумент.Договор (работы, услуги)
Результат : Число 15, 2
СуммаВычета : Число 15, 2
Подразделение : Справочник.Подразделение
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОтношениеКЕНВД : Отношение к ЕНВД затрат на зарплату
СуммаЕНВД : Число 15, 2
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ПланируемаяДатаВыплаты : Дата
Ответственный : Справочник.Пользователь
Комментарий : Строка
Территория : Справочник.Территория
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ПлановыеНачисленияПоДоговорам : РегистрСведений
}
@enduml
