@startuml ОтчетКомиссионераОСписании
'!include templates.wsd
'..\include templates.wsd
class Документ.ОтчетКомиссионераОСписании as "Отчет комиссионера о списании" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
Соглашение : Справочник.Соглашение об условиях продаж
Валюта : Справочник.Валюта
СуммаДокумента : Число 15, 2
СтатьяДоходов : Статьи доходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Подразделение : Справочник.Подразделение
Менеджер : Справочник.Пользователь
НалогообложениеНДС : Типы налогообложения НДС
ЦенаВключаетНДС : Булево
ДатаПлатежа : Дата
НачалоПериода : Дата
КонецПериода : Дата
ПоРезультатамИнвентаризации : Булево
НомерВходящегоДокумента : Строка
ДатаВходящегоДокумента : Дата
Комментарий : Строка
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
Договор : Справочник.Договор с контрагентом
ПорядокРасчетов : Детализация расчетов
ВидыЗапасовУказаныВручную : Булево
ИдентификаторПлатежа : Строка
НаправлениеДеятельности : Справочник.Направление деятельности
ПорядокОплаты : Порядок оплаты
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковокУчет : Число 15, 3
КоличествоУпаковокФакт : Число 15, 3
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ВидЦены : Справочник.Вид цены
Цена : Число 15, 2
Сумма : Число 15, 2
СуммаНДС : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаСНДС : Число 15, 2
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
..Табличная часть \n ВидыЗапасов..
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
СуммаСНДС : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
ИдентификаторСтроки : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n РасшифровкаПлатежа..
Заказ : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
Сумма : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
..Движения..
ПрочиеДоходы : Остатки
РасчетыСКлиентами : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииТоваровПереданныеНаКомиссию : Остатки
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ДвиженияКонтрагентДоходыРасходы : Обороты
ТоварыКОформлениюОтчетовКомитенту : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ТоварыПереданныеНаКомиссию : Остатки
Международный : РегистрБухгалтерии
РасходыПриУСНТовары : Остатки
РасчетыСКлиентамиПоДокументам : Остатки
КнигаУчетаДоходовИРасходов : Обороты
ПартииЗатратНаВыпуск : Остатки
}
@enduml
