@startuml ОтчетПоКомиссииМеждуОрганизациями
'!include templates.wsd
'..\include templates.wsd
class Документ.ОтчетПоКомиссииМеждуОрганизациями as "Отчет по комиссии между организациями" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Комиссионер : Справочник.Организация
Валюта : Справочник.Валюта
СуммаДокумента : Число 15, 2
Подразделение : Справочник.Подразделение
Менеджер : Справочник.Пользователь
НалогообложениеНДС : Типы налогообложения НДС
ЦенаВключаетНДС : Булево
СпособРасчетаВознаграждения : Способы расчета комиссионного вознаграждения
ПроцентВознаграждения : Число 5, 2
СуммаВознаграждения : Число 15, 2
СтавкаНДСВознаграждения : Ставки НДС
СуммаНДСВознаграждения : Число 15, 2
УдержатьВознаграждение : Булево
Услуга : Справочник.Номенклатура
ДатаПлатежа : Дата
ВидЦены : Справочник.Вид цены
ФормаОплаты : Формы оплаты
НачалоПериода : Дата
КонецПериода : Дата
Комментарий : Строка
РасчетыЧерезОтдельногоКонтрагента : Булево
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
НомерВходящегоДокумента : Строка
ДатаВходящегоДокумента : Дата
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
Договор : Справочник.Договор между организациями
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
ВидыЗапасовУказаныВручную : Булево
ПорядокРасчетов : Детализация расчетов
ИдентификаторПлатежа : Строка
НаправлениеДеятельности : Справочник.Направление деятельности
ДоговорПродажи : Справочник.Договор с контрагентом
ДоговорПокупки : Справочник.Договор с контрагентом
ПорядокОплаты : Порядок оплаты
ГруппаФинансовогоУчетаПолучателя : Справочник.Группа финансового учета расчетов
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ВидЦены : Справочник.Вид цены
Цена : Число 15, 2
Сумма : Число 15, 2
СуммаНДС : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаСНДС : Число 15, 2
ЦенаПродажи : Число 15, 2
СуммаПродажиНДС : Число 15, 2
СуммаПродажи : Число 15, 2
СуммаВознаграждения : Число 15, 2
СуммаНДСВознаграждения : Число 15, 2
ДатаСчетаФактурыКомиссионера : Дата
Покупатель : Справочник.Организация\rСправочник.Контрагент
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
СчетФактураВыставленныйКомиссионера : Документ.Счет-фактура выданный\rДокумент.Счет-фактура выданный комиссионеру (агенту)
ИдентификаторСтроки : Строка
..Табличная часть \n ВидыЗапасов..
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
СуммаСНДС : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаВознаграждения : Число 15, 2
СуммаНДСВознаграждения : Число 15, 2
ДатаСчетаФактурыКомиссионера : Дата
Покупатель : Справочник.Организация\rСправочник.Контрагент
ИдентификаторСтроки : Строка
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ВидЗапасовКомитента : Справочник.Вид запасов
СчетФактураВыставленныйКомиссионера : Документ.Счет-фактура выданный\rДокумент.Счет-фактура выданный комиссионеру (агенту)
..Табличная часть \n РасшифровкаПлатежаСКлиентом..
Заказ : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
Сумма : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
..Табличная часть \n РасшифровкаПлатежаСПоставщиком..
Заказ : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Приобретение товаров и услуг\r...
Сумма : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
..Табличная часть \n РасшифровкаПлатежаСКлиентомВознаграждение..
Заказ : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
Сумма : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
..Табличная часть \n РасшифровкаПлатежаСПоставщикомВознаграждение..
Заказ : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Приобретение товаров и услуг\r...
Сумма : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
..Движения..
ПрочиеДоходы : Остатки
РасчетыСКлиентами : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииТоваровПереданныеНаКомиссию : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ДвиженияКонтрагентДоходыРасходы : Обороты
ТоварыКОформлениюОтчетовКомитенту : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСН : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
РасчетыСПоставщиками : Остатки
ТоварыПереданныеНаКомиссию : Остатки
Международный : РегистрБухгалтерии
Закупки : Обороты
РасходыПриУСНТовары : Остатки
НДСЗаписиКнигиПродаж : Обороты
РасчетыСКлиентамиПоДокументам : Остатки
РасчетыСПоставщикамиПоДокументам : Остатки
КнигаУчетаДоходовИРасходов : Обороты
ВыручкаИСебестоимостьПродаж : Обороты
УслугиКОформлениюОтчетовПринципалу : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
