@startuml РегистрацияЦенНоменклатурыПоставщика
'!include templates.wsd
'..\include templates.wsd
class Документ.РегистрацияЦенНоменклатурыПоставщика as "Регистрация цен номенклатуры поставщика" <<Документы>>
{
..Реквизиты..
Партнер : Справочник.Партнер
Ответственный : Справочник.Пользователь
Комментарий : Строка
ДокументОснование : Документ.Приобретение товаров и услуг\rДокумент.Заказ поставщику\rДокумент.Поступление товаров\r...
..Табличная часть \n Товары..
Цена : Число 15, 2
НоменклатураПоставщика : Справочник.Номенклатура поставщика
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
ВидЦеныПоставщика : Справочник.Вид цены поставщика
Упаковка : Справочник.Упаковка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ЦеныНоменклатурыПоставщиков : РегистрСведений
}
@enduml
