@startuml ПринятиеКУчетуНМА2_4
'!include templates.wsd
'..\include templates.wsd
class Документ.ПринятиеКУчетуНМА2_4 as "Принятие к учету НМА" <<Документы>>
{
..Реквизиты..
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
АналитикаРасходовБУ : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаРасходовУУ : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ВариантПримененияЦелевогоФинансирования : Варианты применения целевого финансирования
ВариантРаздельногоУчетаНДС : Варианты раздельного учета НДС
ВидОбъектаУчета : Виды объектов учета НМА
ГруппаФинансовогоУчета : Справочник.Группа финансового учета внеоборотных активов
ДокументВДругомУчете : Документ.Ввод остатков внеоборотных активов\rДокумент.Принятие к учету НМА
Комментарий : Строка
КоэффициентБУ : Число 4, 3
КоэффициентУскоренияУУ : Число 4, 3
ЛиквидационнаяСтоимостьУУ : Число 15, 2
НалогообложениеНДС : Типы налогообложения НДС
НаправлениеДеятельности : Справочник.Направление деятельности
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
ОбъемНаработки : Число 15, 3
Организация : Справочник.Организация
ОрганизацияПолучательРасходов : Справочник.Организация
Ответственный : Справочник.Пользователь
ОтражатьВРеглУчете : Булево
ОтражатьВУпрУчете : Булево
ПервоначальнаяСтоимостьБУ : Число 15, 2
ПервоначальнаяСтоимостьУУ : Число 15, 2
ПередаватьРасходыВДругуюОрганизацию : Булево
Подразделение : Справочник.Подразделение
ПорядокУчетаБУ : Порядок учета стоимости внеоборотных активов
ПорядокУчетаНУ : Порядок учета стоимости внеоборотных активов
ПорядокУчетаУУ : Порядок учета стоимости внеоборотных активов
СпециальныйКоэффициентНУ : Число 6, 2
СпособНачисленияАмортизацииБУ : Способы начисления амортизации нематериальных активов
СпособНачисленияАмортизацииУУ : Способы начисления амортизации нематериальных активов
СпособПоступления : Способы поступления активов
СрокИспользованияБУ : Число 10, 0
СрокИспользованияНУ : Число 10, 0
СрокИспользованияУУ : Число 10, 0
СтатьяДоходов : Статьи доходов
СтатьяРасходовБУ : Статья расходов
СтатьяРасходовУУ : Статья расходов
СуммаЦелевыхСредств : Число 15, 2
..Табличная часть \n ЦелевоеФинансирование..
Счет : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Сумма : Число 15, 2
..Движения..
ПервоначальныеСведенияНМАНалоговыйУчет : РегистрСведений
ПорядокУчетаНМА : РегистрСведений
СчетаБухгалтерскогоУчетаНМА : РегистрСведений
ПорядокУчетаНМАУУ : РегистрСведений
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
ПараметрыЦелевогоФинансированияНМА : РегистрСведений
НачислениеАмортизацииНМАСпециальныйКоэффициентНалоговыйУчет : РегистрСведений
ПервоначальныеСведенияНМА : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
СтоимостьНМА : Остатки
Хозрасчетный : РегистрБухгалтерии
ПорядокУчетаНМАБУ : РегистрСведений
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
СостоянияНМАОрганизаций : РегистрСведений
ПараметрыАмортизацииНМАБУ : РегистрСведений
МестоУчетаНМА : РегистрСведений
ПервоначальныеСведенияНМАБухгалтерскийУчет : РегистрСведений
ВыручкаИСебестоимостьПродаж : Обороты
ПараметрыАмортизацииНМАУУ : РегистрСведений
СпособыОтраженияРасходовПоАмортизацииНМАБухгалтерскийУчет : РегистрСведений
}
@enduml
