@startuml ЭкземплярФинансовогоОтчета
'!include templates.wsd
'..\include templates.wsd
class Документ.ЭкземплярФинансовогоОтчета as "Экземпляр финансового отчета" <<Документы>>
{
..Реквизиты..
ВидОтчета : Справочник.Вид финансового отчета
КомплектОтчетности : Справочник.Комплект финансовых отчетов
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
НачалоПериода : Дата
КонецПериода : Дата
РезультатОтчета : Хранилище значения
Ответственный : Справочник.Пользователь
Комментарий : Строка
Ресурс : Строка
Валюта : Справочник.Валюта
СуммыВТысячах : Булево
}
@enduml
