@startuml ЭтапПроизводства2_2
'!include templates.wsd
'..\include templates.wsd
class Документ.ЭтапПроизводства2_2 as "Этап производства" <<Документы>>
{
..Реквизиты..
Распоряжение : Документ.Заказ на производство
Статус : Статусы этапов производства
ВыпускающийЭтап : Документ.Этап производства
Спецификация : Справочник.Ресурсная спецификация
Этап : Справочник.Этап ресурсной спецификации
Подразделение : Справочник.Подразделение
Назначение : Справочник.Назначение
НазначениеПродукция : Справочник.Назначение
НазначениеМатериалы : Справочник.Назначение
Организация : Справочник.Организация
ВыпускПодДеятельность : Типы налогообложения НДС
Ответственный : Справочник.Пользователь
Комментарий : Строка
НаименованиеЭтапа : Строка
Запланировано : Число 15, 3
Выполнено : Число 15, 3
ЕдиницаИзмеренияПартииВыпуска : Справочник.Упаковка
ФактическоеНачалоЭтапа : Дата
ФактическоеОкончаниеЭтапа : Дата
ПричинаЗадержкиВыполненияЭтапа : Справочник.Причина задержки выполнения этапов производства
РучноеРазмещениеВГрафике : Булево
ЗаполненоАвтоматически : Булево
ОсновноеИзделиеНоменклатура : Справочник.Номенклатура
ОсновноеИзделиеХарактеристика : Справочник.Характеристика номенклатуры
ПроизводствоНаСтороне : Булево
Непрерывный : Булево
ПланироватьРаботуВидовРабочихЦентров : Булево
ДлительностьЭтапа : Число 10, 0
ЕдиницаИзмеренияДлительностиЭтапа : Единицы измерения времени
ПредварительныйБуфер : Число 10, 0
ЗавершающийБуфер : Число 10, 0
ЕдиницаИзмеренияПредварительногоБуфера : Единицы измерения времени
ЕдиницаИзмеренияЗавершающегоБуфера : Единицы измерения времени
МаршрутнаяКарта : Справочник.Маршрутная карта
КоэффициентМаршрутнойКарты : Число 15, 3
СтатьяКалькуляции : Справочник.Статьи калькуляции
МаксимальныйКодСтрокиИзделия : Число 10, 0
МаксимальныйКодСтрокиОбеспечение : Число 10, 0
МаксимальныйКодСтрокиЭкономия : Число 10, 0
МаксимальныйКодСтрокиТрудозатраты : Число 10, 0
ЖелаемаяДатаОбеспечения : Дата
ДатаОтгрузки : Дата
НомерЭтапа : Число 4, 0
НомерСледующегоЭтапа : Число 4, 0
НаправлениеДеятельности : Справочник.Направление деятельности
ВидЦены : Справочник.Вид цены
ЗаказПереработчику : Документ.Заказ переработчику
ПроизводствоОднойДатой : Булево
ДатаПроизводства : Дата
НеОтгружатьЧастями : Булево
РасходОднойДатой : Булево
ДатаРасхода : Дата
ХозяйственнаяОперация : Хозяйственные операции
Партнер : Справочник.Партнер
Договор : Справочник.Договор с контрагентом
НомерПартииЗапуска : Число 6, 0
НомерЭтапаВПартииЗапуска : Число 6, 0
Исполнитель : Справочник.Физическое лицо
КомментарийПриКонвертации : Строка
ЕстьМаркируемаяПродукцияГИСМ : Булево
ТребуетсяЗаполнитьПоОперациям : Булево
ПорядокРаботыВидовРабочихЦентров : Порядок работы видов рабочих центров
ПланироватьНеРанее : Дата
НомерНаПечать : Строка
Валюта : Справочник.Валюта
ВариантПриемкиТоваров : Варианты приемки товаров
..Табличная часть \n ВыходныеИзделия..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Упаковка : Справочник.Упаковка
Получатель : Справочник.Подразделение\rСправочник.Склад (складская территория)
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
Произведено : Булево
ДатаПроизводства : Дата
СтатусУказанияСерий : Число 2, 0
СтатусУказанияСерийОтправитель : Число 2, 0
СтатусУказанияСерийПолучатель : Число 2, 0
ДоляСтоимости : Число 10, 0
СписатьНаРасходы : Булево
СтатьяРасходов : Статья расходов\rСтатья актива/пассива
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ВидЗапасов : Справочник.Вид запасов
ИдентификаторСтроки : Строка
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
КодСтроки : Число 10, 0
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
ПередатьДавальцу : Булево
ЭтапПотребитель : Документ.Этап производства
..Табличная часть \n ВыходныеИзделияСерии..
Серия : Справочник.Серия номенклатуры
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Получатель : Справочник.Подразделение\rСправочник.Склад (складская территория)
Назначение : Справочник.Назначение
Произведено : Булево
Количество : Число 15, 3
ДатаПроизводства : Дата
..Табличная часть \n ПобочныеИзделия..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Упаковка : Справочник.Упаковка
Получатель : Справочник.Подразделение\rСправочник.Склад (складская территория)
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
Произведено : Булево
ДатаПроизводства : Дата
СтатусУказанияСерий : Число 2, 0
СтатусУказанияСерийОтправитель : Число 2, 0
СтатусУказанияСерийПолучатель : Число 2, 0
Цена : Число 15, 2
Сумма : Число 15, 2
СписатьНаРасходы : Булево
СтатьяРасходов : Статья расходов\rСтатья актива/пассива
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ВидЗапасов : Справочник.Вид запасов
ИдентификаторСтроки : Строка
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
СтатьяКалькуляции : Справочник.Статьи калькуляции
КодСтроки : Число 10, 0
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
УдалитьПередатьНаСледующийЭтап : Булево
ПередатьДавальцу : Булево
ЭтапПотребитель : Документ.Этап производства
..Табличная часть \n ПобочныеИзделияСерии..
Серия : Справочник.Серия номенклатуры
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Получатель : Справочник.Подразделение\rСправочник.Склад (складская территория)
Назначение : Справочник.Назначение
Произведено : Булево
Количество : Число 15, 3
ДатаПроизводства : Дата
..Табличная часть \n ОбеспечениеМатериаламиИРаботами..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Серия : Справочник.Серия номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ВариантОбеспечения : Варианты обеспечения
ДатаОтгрузки : Дата
Склад : Справочник.Склад (складская территория)
Производится : Булево
Спецификация : Справочник.Ресурсная спецификация
СтатусУказанияСерий : Число 2, 0
СтатусУказанияСерийОтправитель : Число 2, 0
СтатусУказанияСерийПолучатель : Число 2, 0
КодСтроки : Число 10, 0
ИспользуетсяАвтовыбор : Булево
СведенияАвтовыбора : Строка
ПрименениеМатериала : Строка
КлючСвязиСпецификация : Уникальный идентификатор
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
СтатьяКалькуляции : Справочник.Статьи калькуляции
..Табличная часть \n РасходМатериаловИРабот..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Упаковка : Справочник.Упаковка
ДатаРасхода : Дата
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
СтатьяКалькуляции : Справочник.Статьи калькуляции
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
..Табличная часть \n ЭкономияМатериалов..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Упаковка : Справочник.Упаковка
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
СтатусУказанияСерийОтправитель : Число 2, 0
СтатусУказанияСерийПолучатель : Число 2, 0
Склад : Справочник.Склад (складская территория)
СтатьяРасходов : Статья расходов\rСтатья актива/пассива
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
СписатьНаРасходы : Булево
ДатаОперации : Дата
КодСтроки : Число 10, 0
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
Обособить : Булево
ИдентификаторСтроки : Строка
..Табличная часть \n ЭкономияМатериаловСерии..
Серия : Справочник.Серия номенклатуры
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Количество : Число 15, 3
Склад : Справочник.Склад (складская территория)
ДатаОперации : Дата
Обособить : Булево
..Табличная часть \n Трудозатраты..
ВидРабот : Справочник.Вид работ сотрудников
Количество : Число 15, 3
СтатьяКалькуляции : Справочник.Статьи калькуляции
НазначениеРабот : Строка
Исполнитель : Справочник.Бригады\rСправочник.Физическое лицо
КодСтроки : Число 10, 0
Выполнено : Булево
ДатаВыполнения : Дата
УдалитьКодСтрокиМаршрутногоЛиста : Число 10, 0
УдалитьМаршрутныйЛистПроизводства : Документ.Маршрутный лист производства
..Табличная часть \n ВидыРабочихЦентров..
ВидРабочегоЦентра : Справочник.Вид рабочего центра
ВремяРаботы : Число 10, 1
ЕдиницаИзмерения : Единицы измерения времени
Использовать : Булево
ВариантНаладки : Справочник.Вариант наладки
КлючСвязи : Уникальный идентификатор
..Табличная часть \n АльтернативныеВидыРабочихЦентров..
ВидРабочегоЦентра : Справочник.Вид рабочего центра
ВремяРаботы : Число 10, 1
ЕдиницаИзмерения : Единицы измерения времени
Использовать : Булево
ВариантНаладки : Справочник.Вариант наладки
КлючСвязиВидыРабочихЦентров : Уникальный идентификатор
..Табличная часть \n ЗанятостьВидовРабочихЦентров..
ВидРабочегоЦентра : Справочник.Вид рабочего центра
ДатаИнтервала : Дата
Количество : Число 8, 1
..Табличная часть \n Последователи..
Этап : Документ.Этап производства
ТипСвязи : Число 1, 0
..Табличная часть \n ВидыЗапасовОбеспечение..
АналитикаУчетаНоменклатуры : Справочник.Номенклатура\rСправочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
НазначениеПолучателя : Справочник.Назначение
ДатаОтгрузки : Дата
Серия : Справочник.Серия номенклатуры
..Табличная часть \n ВидыЗапасовЭкономия..
АналитикаУчетаНоменклатуры : Справочник.Номенклатура\rСправочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
Серия : Справочник.Серия номенклатуры
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
НазначениеПолучателя : Справочник.Назначение
ДатаОперации : Дата
Склад : Справочник.Склад (складская территория)
СтатьяРасходов : Статья расходов\rСтатья актива/пассива
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
СписатьНаРасходы : Булево
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
ИдентификаторСтроки : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ТоварыКОтгрузке : Остатки
ЗаказыМатериаловВПроизводство : Остатки
ТрудозатратыНезавершенногоПроизводства : Остатки
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
ГрафикОтгрузкиТоваров : Остатки
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ТоварыКОформлениюОтчетовКомитенту : Остатки
РаспоряженияНаПередачуИзПроизводства : Остатки
ПродукцияИПолуфабрикатыВПроизводстве : Обороты
ДоступностьВидовРабочихЦентров : Обороты
Хозрасчетный : РегистрБухгалтерии
УслугиДавальцуКОформлению : Остатки
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ЗаказыКлиентов : Остатки
ОбеспечениеЗаказов : Остатки
Международный : РегистрБухгалтерии
ДвижениеТоваров : Обороты
НДСЗаписиКнигиПродаж : Обороты
ОбеспечениеЗаказовРаботами : Остатки
ТоварыОрганизацийКПередаче : Остатки
МатериалыИРаботыВПроизводстве : Остатки
СвободныеОстатки : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
ТрудозатратыКОформлению : Остатки
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
ГрафикПоступленияТоваров : Остатки
ПрочиеРасходыНезавершенногоПроизводства : Остатки
ЗаказыПоставщикам : Остатки
ВыпускПродукции : Обороты
ТоварыКПоступлению : Остатки
}
@enduml
