@startuml РегистрацияЗемельныхУчастков
'!include templates.wsd
'..\include templates.wsd
class Документ.РегистрацияЗемельныхУчастков as "Регистрация земельных участков" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
КодКатегорииЗемель : Строка
ПостановкаНаУчетВНалоговомОргане : Постановка на учет в налоговом органе
НалоговыйОрган : Справочник.Регистрация в налоговом органе
КодПоОКТМО : Строка
КодПоОКАТО : Строка
КБК : Строка
НалоговаяСтавка : Число 5, 4
НалоговаяЛьготаПоНалоговойБазе : Вид налоговой льготы по налоговой базе по земельному налогу
КодНалоговойЛьготыОсвобождениеОтНалогообложенияПоСтатье395 : Строка
КодНалоговойЛьготыУменьшениеНалоговойБазыПоСтатье391 : Строка
УменьшениеНалоговойБазыПоСтатье391 : Булево
УменьшениеНалоговойБазыНаСумму : Булево
ДоляНеОблагаемойНалогомПлощадиЧислитель : Число 10, 0
ДоляНеОблагаемойНалогомПлощадиЗнаменатель : Число 10, 0
НеОблагаемаяНалогомСумма : Число 15, 2
СниженнаяНалоговаяСтавка : Число 5, 4
ПроцентУменьшенияСуммыНалога : Число 7, 4
СуммаУменьшенияСуммыНалога : Число 15, 2
Ответственный : Справочник.Пользователь
Комментарий : Строка
УказаныСпособыОтражениеРасходов : Булево
..Табличная часть \n ОС..
ОсновноеСредство : Справочник.Объект эксплуатации
КадастровыйНомер : Строка
КадастроваяСтоимость : Число 15, 2
ОбщаяСобственность : Булево
ДоляВПравеОбщейСобственностиЧислитель : Число 10, 0
ДоляВПравеОбщейСобственностиЗнаменатель : Число 10, 0
ЖилищноеСтроительство : Булево
ДатаНачалаПроектирования : Дата
ДатаРегистрацииПравНаОбъектНедвижимости : Дата
..Табличная часть \n ОтражениеРасходов..
Подразделение : Справочник.Подразделение
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Коэффициент : Число 10, 0
..Движения..
РегистрацияЗемельныхУчастков : РегистрСведений
СпособыОтраженияРасходовПоИмущественнымНалогам : РегистрСведений
}
@enduml
