@startuml СведенияОЗаработкеСтажеЗастрахованныхЛицСЗВ_ИСХ
'!include templates.wsd
'..\include templates.wsd
class Документ.СведенияОЗаработкеСтажеЗастрахованныхЛицСЗВ_ИСХ as "Сведения о заработке и стаже застрахованных лиц, СЗВ-ИСХ" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ОтчетныйПериод : Дата
РегистрационныйНомерПФР : Строка
КПП : Строка
ИНН : Строка
ИмяФайлаДляПФР : Строка
ДокументПринятВПФР : Булево
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ФайлСформирован : Булево
ОкончаниеОтчетногоПериода : Дата
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Физическое лицо
СтраховойНомерПФР : Строка
Фамилия : Строка
Имя : Строка
Отчество : Строка
Заработок : Число 15, 2
Начислено : Число 15, 2
Уплачено : Число 15, 2
ТипДоговора : Типы договоров СЗВ-6-3
НомерДоговора : Строка
ДатаДоговора : Дата
ДополнительныйТариф : Булево
ФиксСтаж : Булево
ФиксНачисленныеВзносы : Булево
ФиксЗаработок : Булево
ИдентификаторСтрокиСотрудника : Число 7, 0
..Табличная часть \n СведенияОЗаработке..
Сотрудник : Справочник.Физическое лицо
КодМесяца : Строка
КатегорияЗастрахованныхЛиц : Категории застрахованных лиц для ПФР
Заработок : Число 15, 2
ОблагаетсяВзносамиДоПредельнойВеличины : Число 15, 2
ПоДоговорамГПХДоПредельнойВеличины : Число 15, 2
ОблагаетсяВзносамиСвышеПредельнойВеличины : Число 15, 2
ПоДоговорамГПХСвышеПредельнойВеличины : Число 15, 2
ИдентификаторСтрокиСотрудника : Число 7, 0
..Табличная часть \n СведенияОЗаработкеНаВредныхИТяжелыхРаботах..
Сотрудник : Справочник.Физическое лицо
КодМесяца : Строка
КлассУсловийТруда : Классы условий труда по результатам специальной оценки
ОблагаетсяВзносамиЗаЗанятыхНаПодземныхИВредныхРаботах : Число 15, 2
ОблагаетсяВзносамиЗаЗанятыхНаТяжелыхИПрочихРаботах : Число 15, 2
ИдентификаторСтрокиСотрудника : Число 7, 0
..Табличная часть \n ЗаписиОСтаже..
Сотрудник : Справочник.Физическое лицо
НомерОсновнойЗаписи : Число 2, 0
НомерДополнительнойЗаписи : Число 2, 0
ДатаНачалаПериода : Дата
ДатаОкончанияПериода : Дата
ОсобыеУсловияТруда : Справочник.Особое условие труда\rСправочник.Особое условие труда для СЗВ-К
КодПозицииСписка : Справочник.Льготная профессия (ПФР)
ОснованиеИсчисляемогоСтажа : Справочник.Основание для исчисления стажа
ПервыйПараметрИсчисляемогоСтажа : Число 3, 0
ВторойПараметрИсчисляемогоСтажа : Число 2, 0
ТретийПараметрИсчисляемогоСтажа : Справочник.Доп. сведение для исчисления стажа
ОснованиеВыслугиЛет : Справочник.Основание для досрочной пенсии\rСправочник.Основание для досрочной пенсии (СЗВ-К)
ПервыйПараметрВыслугиЛет : Число 4, 0
ВторойПараметрВыслугиЛет : Число 4, 0
ТретийПараметрВыслугиЛет : Число 5, 2
ТерриториальныеУсловия : Справочник.Территориальное условие
ПараметрТерриториальныхУсловий : Число 3, 2
ИдентификаторСтрокиСотрудника : Число 7, 0
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Табличная часть \n НачисленныеВзносы..
Сотрудник : Справочник.Физическое лицо
СВпоТарифуНеПревышающие : Число 15, 2
Страховая : Число 15, 2
Накопительная : Число 15, 2
СВстрахователя : Число 15, 2
СВизЗаработка : Число 15, 2
СВпоТарифу : Число 15, 2
СВпоДопТарифу : Число 15, 2
ИдентификаторСтрокиСотрудника : Число 7, 0
..Табличная часть \n СведенияОбУплаченныхВзносах..
Сотрудник : Справочник.Физическое лицо
УплаченоСтраховая : Число 15, 2
УплаченоНакопительная : Число 15, 2
ИдентификаторСтрокиСотрудника : Число 7, 0
..Табличная часть \n НачисленныеУплаченныеВзносы..
ВидСтраховыхВзносов : Виды страховых взносов ПФР
ЗадолженностьНаНачалоПериода : Число 15, 2
Начислено : Число 15, 2
Уплачено : Число 15, 2
ЗадолженностьНаКонецПериода : Число 15, 2
..Табличная часть \n УплаченныеВзносыРасшифровка..
Год : Число 4, 0
НаСтраховуюПенсию : Число 15, 2
НаНакопительнуюПенсию : Число 15, 2
ПоТарифуСтраховыхВзносов : Число 15, 2
..Табличная часть \n ДосрочноеНазначениеПенсии..
Подразделение : Справочник.Подразделение
Должность : Справочник.Должность
КоличествоРабочихМест : Число 10, 2
КоличествоРаботающих : Число 10, 0
ХарактерВыполняемыхРабот : Строка
ПервичныеДокументы : Строка
ОснованиеВыслугиЛет : Справочник.Особое условие труда\rСправочник.Особое условие труда для СЗВ-К
КодПозицииСписка : Справочник.Льготная профессия (ПФР)
}
@enduml
