@startuml УстановкаЗначенийНефинансовыхПоказателей
'!include templates.wsd
'..\include templates.wsd
class Документ.УстановкаЗначенийНефинансовыхПоказателей as "Значения нефинансовых показателей" <<Документы>>
{
..Реквизиты..
НефинансовыйПоказатель : Справочник.Нефинансовые показатели бюджетов
НачалоПериода : Дата
ОкончаниеПериода : Дата
ПредставлениеПериода : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
ВидОперации : Виды операций установки значений нефинансовых показателей
ШаблонВвода : Справочник.Шаблоны ввода нефинансовых показателей
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Сценарий : Справочник.Сценарии бюджетирования
Аналитика1 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика2 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика3 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика4 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика5 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика6 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТипПериода : Строка
ПредставлениеНефинансовыхПоказателей : Строка
..Табличная часть \n ЗначенияКолонок..
Значение : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
ИмяИзмерения : Строка
Аналитика : Аналитики статей бюджетов
..Табличная часть \n СтрокиДокумента..
НомерСтрокиДокумента : Число 10, 0
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Сценарий : Справочник.Сценарии бюджетирования
Период : Дата
НомерПодПериода : Число 3, 0
Аналитика1 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика2 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика3 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика4 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика5 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика6 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
..Табличная часть \n КолонкиДокумента..
НомерСтрокиДокумента : Число 10, 0
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Сценарий : Справочник.Сценарии бюджетирования
Период : Дата
НомерПодПериода : Число 3, 0
Аналитика1 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика2 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика3 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика4 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика5 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика6 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
НефинансовыйПоказатель : Справочник.Нефинансовые показатели бюджетов
Значение : Число 15, 2
Валюта : Справочник.Валюта
..Табличная часть \n ЗначенияПоказателей..
Показатель : Справочник.Нефинансовые показатели бюджетов
Значение : Число 15, 2
Валюта : Справочник.Валюта
..Движения..
ЗначенияНефинансовыхПоказателей : РегистрСведений
}
@enduml
