@startuml ПередачаОСАрендатору2_4
'!include templates.wsd
'..\include templates.wsd
class Документ.ПередачаОСАрендатору2_4 as "Передача ОС арендатору" <<Документы>>
{
..Реквизиты..
АдресМестонахожденияАрендатора : Строка
АналитикаРасходовБУ : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаРасходовУУ : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Арендатор : Справочник.Организация\rСправочник.Контрагент
ГруппаФинансовогоУчета : Справочник.Группа финансового учета внеоборотных активов
Комментарий : Строка
МОЛ : Справочник.Физическое лицо
МОЛАрендатора : Справочник.Физическое лицо
НачислятьАмортизациюБУ : Булево
НачислятьАмортизациюУУ : Булево
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
ОтражатьВРеглУчете : Булево
ОтражатьВУпрУчете : Булево
Подразделение : Справочник.Подразделение
ПодразделениеАрендатора : Справочник.Подразделение
ПодразделениеПолучатель : Справочник.Подразделение
РасчетыМеждуОрганизациямиАрендатор : Булево
СтатьяРасходовБУ : Статья расходов
СтатьяРасходовУУ : Статья расходов
..Табличная часть \n ОС..
ОсновноеСредство : Справочник.Объект эксплуатации
ЗалоговаяСтоимость : Число 15, 2
..Движения..
МестонахождениеОСБухгалтерскийУчет : РегистрСведений
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
СпособыОтраженияРасходовПоАмортизацииОСБухгалтерскийУчет : РегистрСведений
ПорядокУчетаОСБУ : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
СостоянияОСОрганизаций : РегистрСведений
Международный : РегистрБухгалтерии
НачислениеАмортизацииОСБухгалтерскийУчет : РегистрСведений
МестонахождениеОС : РегистрСведений
ПорядокУчетаОСУУ : РегистрСведений
СчетаБухгалтерскогоУчетаОС : РегистрСведений
ПорядокУчетаОС : РегистрСведений
АмортизацияОС : Остатки
СтоимостьОС : Остатки
НачислениеАмортизацииОСНалоговыйУчет : РегистрСведений
}
@enduml
