@startuml ПакетЭД
'!include templates.wsd
'..\include templates.wsd
class Документ.ПакетЭД as "Пакет электронных документов" <<Документы>>
{
..Реквизиты..
АдресРесурсаКонтрагента : Строка
АдресРесурсаОрганизации : Строка\rСправочник.Учетная запись электронной почты
ВерсияФорматаПакета : Версии формата пакета электронных документов
ВнешнийУИД : Строка
ДанныеЗашифрованы : Булево
Комментарий : Строка
Контрагент : Справочник.Контрагент
Направление : Направления ЭД
НастройкаЭДО : Справочник.Настройка ЭДО
Организация : Справочник.Организация
Отправитель : Строка
Получатель : Строка
ПрофильНастроекЭДО : Справочник.Профиль настроек ЭДО
СертификатШифрования : Строка
СпособОбменаЭД : Способы обмена электронными документами
СтатусПакета : Статусы пакетов электронных документов
..Табличная часть \n ЭлектронныеДокументы..
ОбъектВладелец : Документ.Сторнирование начислений\rДокумент.Внутреннее потребление товаров\rДокумент.Назначение планового начисления\r...
УдалитьДанныеЗашифрованы : Булево
УдалитьСертификатШифрования : Строка
ЭлектронныйДокумент : Строка\rСправочник.Присоединенный файл (Электронный документ)
}
@enduml
