@startuml ИзменениеОплатыТруда
'!include templates.wsd
'..\include templates.wsd
class Документ.ИзменениеОплатыТруда as "Изменение оплаты труда" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ДатаИзменения : Дата
СпособРасчетаАванса : Способы расчета аванса
Аванс : Число 15, 2
ИзменитьНачисления : Булево
ИзменитьАванс : Булево
ПорядокРасчетаСтоимостиЕдиницыВремени : Порядок расчета стоимости часа (дня) оплаты труда сотрудников
СовокупнаяТарифнаяСтавка : Число 15, 5
ВидТарифнойСтавки : Виды тарифных ставок
РазрядКатегория : Справочник.Квалификационный разряд (категория)
Грейд : Строка
ПКУ : Справочник.Квалификационный разряд (категория)
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Начисления..
Действие : Действия с начислениями и удержаниями
Начисление : Начисление
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Размер : Число 15, 2
ХарактерНачисления : Характер планового начисления
..Табличная часть \n Показатели..
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Показатель : Справочник.Показатель
Значение : Число 15, 5
Действие : Действия с начислениями и удержаниями
..Движения..
ПорядокРасчетаСтоимостиЕдиницыВремениСотрудников : РегистрСведений
ЗанятыеПозицииШтатногоРасписания : Остатки
УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников : РегистрСведений
ПКУСотрудников : РегистрСведений
ПрименениеДополнительныхПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
ПлановыеАвансы : РегистрСведений
РазрядыКатегорииСотрудников : РегистрСведений
ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
БухучетПлановыхНачислений : РегистрСведений
ПлановыеНачисления : РегистрСведений
}
@enduml
