@startuml АктПостановкиНаБалансЕГАИС
'!include templates.wsd
'..\include templates.wsd
class Документ.АктПостановкиНаБалансЕГАИС as "Акт постановки на баланс ЕГАИС" <<Документы>>
{
..Реквизиты..
ВидДокумента : Виды документов ЕГАИС
ОрганизацияЕГАИС : Справочник.Организация ЕГАИС
Идентификатор : Строка
ИдентификаторЕГАИС : Строка
УдалитьСтатусОбработки : Статусы обработки акта постановки на баланс ЕГАИС
ПричинаПостановкиНаБаланс : Причины постановки на баланс ЕГАИС
ДокументОснование : Документ.Пересортица товаров\rДокумент.Оприходование излишков товаров
Ответственный : Справочник.Пользователь
АктСписанияЕГАИС : Документ.Акт списания ЕГАИС
ДатаРегистрацииДвижений : Дата
Комментарий : Строка
..Табличная часть \n Товары..
АлкогольнаяПродукция : Справочник.Алкогольная продукция ЕГАИС
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
КоличествоПоСправке1 : Число 15, 3
НомерТТН : Строка
ДатаТТН : Дата
ДатаРозлива : Дата
НомерПодтвержденияЕГАИС : Строка
ДатаПодтвержденияЕГАИС : Дата
Справка2 : Справочник.Справка к ТТН по форме 2
ИдентификаторСтроки : Строка
УдалитьСправка1 : Справочник.Справка к ТТН по форме 1
..Табличная часть \n АкцизныеМарки..
КодАкцизнойМарки : Строка
ИдентификаторСтроки : Строка
..Движения..
ОстаткиАлкогольнойПродукцииЕГАИС : Остатки
}
@enduml
