@startuml РегистраторГрафикаДвиженияТоваров
'!include templates.wsd
'..\include templates.wsd
class Документ.РегистраторГрафикаДвиженияТоваров as "Регистратор графика движения товаров" <<Документы>>
{
..Реквизиты..
Распоряжение : Справочник.Договор с контрагентом\rСправочник.Соглашение об условиях закупок
..Движения..
ГрафикПоступленияТоваров : Остатки
}
@enduml
