@startuml РеестрСЗВ_6_2
'!include templates.wsd
'..\include templates.wsd
class Документ.РеестрСЗВ_6_2 as "Реестр СЗВ-6-2" <<Документы>>
{
..Реквизиты..
ОтчетныйПериод : Дата
Организация : Справочник.Организация
КатегорияЗастрахованныхЛиц : Категории застрахованных лиц для ПФР
ТипСведенийСЗВ : Типы сведений СЗВ
КорректируемыйПериод : Дата
НомерПачки : Число 5, 0
ИмяФайлаДляПФР : Строка
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ДокументПринятВПФР : Булево
ФайлСформирован : Булево
ОкончаниеОтчетногоПериода : Дата
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
АдресДляИнформирования : Строка
СтраховойНомерПФР : Строка
Фамилия : Строка
Имя : Строка
Отчество : Строка
НачисленоСтраховая : Число 15, 2
УплаченоСтраховая : Число 15, 2
НачисленоНакопительная : Число 15, 2
УплаченоНакопительная : Число 15, 2
ДоначисленоСтраховая : Число 15, 2
ДоначисленоНакопительная : Число 15, 2
Сотрудник : Справочник.Физическое лицо
АдресДляИнформированияПредставление : Строка
ПериодыСтажаСтрока : Строка
ДоУплаченоНакопительная : Число 15, 2
ДоУплаченоСтраховая : Число 15, 2
ФиксУплаченныеВзносы : Булево
ФиксСтаж : Булево
ФиксНачисленныеВзносы : Булево
..Табличная часть \n ЗаписиОСтаже..
Сотрудник : Справочник.Физическое лицо
ДатаНачалаПериода : Дата
ДатаОкончанияПериода : Дата
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Движения..
СтраховыеВзносыПереданныеВПФР : Остатки
}
@enduml
