@startuml БлокировкаВычетаНДС
'!include templates.wsd
'..\include templates.wsd
class Документ.БлокировкаВычетаНДС as "Блокировка вычета НДС" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Состояние : Состояния блокировки вычета НДС
Комментарий : Строка
Ответственный : Справочник.Пользователь
..Табличная часть \n СчетаФактуры..
СчетФактура : Документ.Запись книги покупок\rДокумент.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\r...
..Движения..
СостоянияБлокировкиВычетаНДСПоСчетамФактурам : РегистрСведений
}
@enduml
