@startuml СчетФактураВыданный
'!include templates.wsd
'..\include templates.wsd
class Документ.СчетФактураВыданный as "Счет-фактура выданный" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Контрагент : Справочник.Организация\rСправочник.Контрагент
ДокументОснование : Документ.Отчет комиссионера (агента) о продажах\rДокумент.Отчет давальцу\rДокумент.Возврат товаров поставщику\r...
СчетФактураОснование : Документ.Счет-фактура выданный
СтрокаПлатежноРасчетныеДокументы : Строка
Исправление : Булево
НомерИсправления : Строка
Корректировочный : Булево
Валюта : Справочник.Валюта
ВыставленВЭлектронномВиде : Булево
ДатаВыставления : Дата
КодВидаОперации : Строка
ИдентификаторПлатежа : Строка
КППКонтрагента : Строка
КодВидаОперацииНаУменьшение : Строка
Подразделение : Справочник.Подразделение
Ответственный : Справочник.Пользователь
СводныйКорректировочный : Булево
ИННКонтрагента : Строка
ИдентификаторГосКонтракта : Строка
..Табличная часть \n ДокументыОснования..
ДокументОснование : Документ.Отчет комиссионера (агента) о продажах\rДокумент.Отчет давальцу\rДокумент.Возврат товаров поставщику\r...
ИсходныйДокумент : Документ.Счет-фактура выданный
НомерИсходногоДокумента : Строка
ДатаИсходногоДокумента : Дата
НомерИсправленияИсходногоДокумента : Строка
ДатаИсправленияИсходногоДокумента : Дата
..Табличная часть \n ПлатежноРасчетныеДокументы..
НомерПлатежноРасчетногоДокумента : Строка
ДатаПлатежноРасчетногоДокумента : Дата
..Движения..
ОтражениеДокументовВРеглУчете : РегистрСведений
НДСПредъявленный : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
НДСЗаписиКнигиПродаж : Обороты
НДСЗаписиКнигиПокупок : Обороты
ЖурналУчетаСчетовФактур : РегистрСведений
}
@enduml
