@startuml НачисленияКредитовИДепозитов
'!include templates.wsd
'..\include templates.wsd
class Документ.НачисленияКредитовИДепозитов as "Начисления по кредитам и депозитам" <<Документы>>
{
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
Комментарий : Строка
ДатаНачала : Дата
ДатаОкончания : Дата
..Табличная часть \n Начисления..
Дата : Дата
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
Договор : Справочник.Договор кредита (депозита)
СтатьяДоходовРасходов : Статья расходов\rСтатьи доходов
ТипСуммыГрафика : Типы сумм графика кредитов и депозитов
СуммаВзаиморасчетов : Число 15, 2
ВалютаВзаиморасчетов : Справочник.Валюта
ИдентификаторСтроки : Строка
..Движения..
ПрочиеДоходы : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияКонтрагентДоходыРасходы : Обороты
РасходыПриУСН : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
Закупки : Обороты
ДвиженияДенежныеСредстваДоходыРасходы : Обороты
КнигаУчетаДоходовИРасходов : Обороты
ВыручкаИСебестоимостьПродаж : Обороты
РасчетыПоДоговорамКредитовИДепозитов : Остатки
}
@enduml
