@startuml ПриобретениеУслугПоЛизингу
'!include templates.wsd
'..\include templates.wsd
class Документ.ПриобретениеУслугПоЛизингу as "Приобретение услуг по лизингу" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Контрагент : Справочник.Контрагент
Подразделение : Справочник.Подразделение
СуммаДокумента : Число 15, 2
Комментарий : Строка
Ответственный : Справочник.Пользователь
Валюта : Справочник.Валюта
НалогообложениеНДС : Типы налогообложения НДС
ВалютаВзаиморасчетов : Справочник.Валюта
ЦенаВключаетНДС : Булево
НомерВходящегоДокумента : Строка
ДатаВходящегоДокумента : Дата
Договор : Справочник.Договор лизинга
ЗакупкаПодДеятельность : Типы налогообложения НДС
СуммаВзаиморасчетов : Число 15, 2
Курс : Число 10, 4
Кратность : Число 10, 0
..Табличная часть \n Начисления..
Содержание : Строка
ТипНачисления : Типы начислений по лизингу
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
СуммаВзаиморасчетов : Число 15, 2
СуммаНДСВзаиморасчетов : Число 15, 2
УдалитьАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
Подразделение : Справочник.Подразделение
ИдентификаторСтроки : Строка
ОбеспечительныйПлатеж : Документ.Расходный кассовый ордер\rДокумент.Списание безналичных ДС\rСтрока
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
НДСПредъявленный : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСН : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
КнигаУчетаДоходовИРасходов : Обороты
}
@enduml
