@startuml ОписьОДВ_1
'!include templates.wsd
'..\include templates.wsd
class Документ.ОписьОДВ_1 as "Опись ОДВ-1" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ТипСведений : Типы сведений СЗВ
ИмяФайлаДляПФР : Строка
ДокументПринятВПФР : Булево
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ФайлСформирован : Булево
ОтчетныйПериод : Дата
ОкончаниеОтчетногоПериода : Дата
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ДосрочноеНазначениеПенсии..
Подразделение : Справочник.Подразделение
Должность : Справочник.Должность
КоличествоРабочихМест : Число 10, 2
КоличествоРаботающих : Число 10, 0
ХарактерВыполняемыхРабот : Строка
ПервичныеДокументы : Строка
ОснованиеВыслугиЛет : Справочник.Особое условие труда\rСправочник.Особое условие труда для СЗВ-К
КодПозицииСписка : Справочник.Льготная профессия (ПФР)
}
@enduml
