@startuml ИзменениеПараметровНМА
'!include templates.wsd
'..\include templates.wsd
class Документ.ИзменениеПараметровНМА as "Изменение параметров НМА (2.2)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
Комментарий : Строка
ОтражениеАмортизационныхРасходовФлаг : Булево
СпециальныйКоэффициентНУ : Число 5, 2
СпециальныйКоэффициентНУФлаг : Булево
ДокументОснование : Документ.Принятие к учету НМА
..Табличная часть \n НМА..
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
..Табличная часть \n ОтражениеАмортизационныхРасходов..
Подразделение : Справочник.Подразделение
НаправлениеДеятельности : Справочник.Направление деятельности
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ПередаватьРасходыВДругуюОрганизацию : Булево
ОрганизацияПолучательРасходов : Справочник.Организация
СчетПередачиРасходов : Счет бухгалтерского учета
Коэффициент : Число 10, 0
..Движения..
НачислениеАмортизацииНМАСпециальныйКоэффициентНалоговыйУчет : РегистрСведений
ВыручкаИСебестоимостьПродаж : Обороты
СпособыОтраженияРасходовПоАмортизацииНМАБухгалтерскийУчет : РегистрСведений
}
@enduml
