@startuml НачислениеОценочныхОбязательствПоОтпускам
'!include templates.wsd
'..\include templates.wsd
class Документ.НачислениеОценочныхОбязательствПоОтпускам as "Начисление оценочных обязательств по отпускам" <<Документы>>
{
..Реквизиты..
ПериодРегистрации : Дата
Организация : Справочник.Организация
ОбязательстваОтраженыВБухучете : Булево
Бухгалтер : Справочник.Пользователь
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
КорректировкаОбязательств : Булево
ДоляРасходов : Число 15, 2
..Табличная часть \n РасчетРезерваОтпусков..
Сотрудник : Справочник.Сотрудник
ФОТ : Число 12, 2
ОстатокОтпуска : Число 5, 2
СреднийЗаработок : Число 15, 2
СуммаРезерва : Число 15, 2
СуммаРезерваНУ : Число 15, 2
СуммаРезерваНакоплено : Число 15, 2
СуммаРезерваНакопленоНУ : Число 15, 2
СуммаРезерваИсчислено : Число 15, 2
СуммаРезерваИсчисленоНУ : Число 15, 2
СтраховыеВзносы : Число 15, 2
ТекущаяСтавкаСтраховыхВзносов : Число 7, 4
СуммаРезерваСтраховыхВзносов : Число 15, 2
СуммаРезерваСтраховыхВзносовНУ : Число 15, 2
СуммаРезерваСтраховыхВзносовНакоплено : Число 15, 2
СуммаРезерваСтраховыхВзносовНакопленоНУ : Число 15, 2
СуммаРезерваСтраховыхВзносовИсчислено : Число 15, 2
СуммаРезерваСтраховыхВзносовИсчисленоНУ : Число 15, 2
ФССНесчастныеСлучаи : Число 15, 2
ТекущаяСтавкаФССНесчастныеСлучаи : Число 7, 4
СуммаРезерваФССНесчастныеСлучаи : Число 15, 2
СуммаРезерваФССНесчастныеСлучаиНУ : Число 15, 2
СуммаРезерваФССНесчастныеСлучаиНакоплено : Число 15, 2
СуммаРезерваФССНесчастныеСлучаиНакопленоНУ : Число 15, 2
СуммаРезерваФССНесчастныеСлучаиИсчислено : Число 15, 2
СуммаРезерваФССНесчастныеСлучаиИсчисленоНУ : Число 15, 2
ОтпускАвансом : Число 5, 2
..Табличная часть \n ОценочныеОбязательстваПоСотрудникам..
ОблагаетсяЕНВД : Булево
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
СтатьяФинансирования : Справочник.Статья финансирования
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
СуммаРезерва : Число 15, 2
СуммаРезерваСтраховыхВзносов : Число 15, 2
СуммаРезерваНУ : Число 15, 2
СуммаРезерваСтраховыхВзносовНУ : Число 15, 2
СуммаРезерваФССНесчастныеСлучаи : Число 15, 2
СуммаРезерваФССНесчастныеСлучаиНУ : Число 15, 2
МестоВСтруктуреПредприятия : Справочник.Подразделение
КорректировкаОбязательств : Булево
..Табличная часть \n ОценочныеОбязательства..
ОблагаетсяЕНВД : Булево
Подразделение : Справочник.Подразделение
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
СуммаРезерва : Число 15, 2
СуммаРезерваНУ : Число 15, 2
СуммаРезерваСтраховыхВзносов : Число 15, 2
СуммаРезерваСтраховыхВзносовНУ : Число 15, 2
СуммаРезерваФССНесчастныеСлучаи : Число 15, 2
СуммаРезерваФССНесчастныеСлучаиНУ : Число 15, 2
СтатьяФинансирования : Справочник.Статья финансирования
МестоВСтруктуреПредприятия : Справочник.Подразделение
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Движения..
ОценочныеОбязательства : Остатки
ПрочиеРасходы : Остатки
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
ДетализацияПартийТоваровДляНДСиУСН : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасчетРезерваОтпусков : РегистрСведений
ОценочныеОбязательстваПоСотрудникам : Остатки
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
Закупки : Обороты
}
@enduml
