@startuml ЗаявлениеИЗапросВПФРОЗаработке
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаявлениеИЗапросВПФРОЗаработке as "Заявление и запрос в ПФР о заработке" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
Страхователь : Справочник.Работодатель
ВидПособия : Перечень пособий социального страхования
ПериодРаботыС : Дата
ПериодРаботыПо : Дата
СтраховательПрекратилДеятельность : Булево
ИныеПричиныОтсутствияСправки : Строка
НаименованиеТерриториальногоОрганаПФР : Строка
АдресОрганизации : Строка
ТелефонОрганизации : Строка
СтраховойНомерПФР : Строка
ДатаРождения : Дата
Фамилия : Строка
Имя : Строка
Отчество : Строка
Адрес : Строка
Телефон : Строка
ВидДокумента : Справочник.Вид документа физических лиц
СерияДокумента : Строка
НомерДокумента : Строка
ДатаВыдачиДокумента : Дата
КемВыданДокумент : Строка
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ФиксацияИзменений..
ИмяРеквизита : Строка
Путь : Строка
ИдентификаторСтроки : Число 5, 0
}
@enduml
