@startuml КорректировкаЗаказаМатериаловВПроизводство
'!include templates.wsd
'..\include templates.wsd
class Документ.КорректировкаЗаказаМатериаловВПроизводство as "Корректировка заказа материалов в производство" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Распоряжение : Документ.Заказ на производство
Ответственный : Справочник.Пользователь
МаксимальныйКодСтроки : Число 10, 0
..Табличная часть \n МатериалыИУслуги..
ВариантОбеспечения : Варианты обеспечения
ВариантОбеспеченияИсходный : Варианты обеспечения
ДатаПотребности : Дата
ДатаПотребностиИсходный : Дата
ЗаказатьНаСклад : Булево
ЗаказатьНаСкладИсходный : Булево
КодСтроки : Число 10, 0
КодСтрокиИсходный : Число 10, 0
КодСтрокиРаспоряжения : Число 10, 0
КодСтрокиЭтапы : Число 10, 0
Количество : Число 15, 3
КоличествоУпаковок : Число 15, 3
КорректировкаНовойСтроки : Булево
Назначение : Справочник.Назначение
НазначениеИсходный : Справочник.Назначение
Номенклатура : Справочник.Номенклатура
Отменено : Булево
ОтмененоИсходный : Булево
Серия : Справочник.Серия номенклатуры
СерияИсходный : Справочник.Серия номенклатуры
Склад : Справочник.Склад (складская территория)
СкладИсходный : Справочник.Склад (складская территория)
СтатусУказанияСерий : Число 2, 0
СтатусУказанияСерийОтправитель : Число 2, 0
СтатусУказанияСерийПолучатель : Число 2, 0
Упаковка : Справочник.Упаковка
УпаковкаИсходный : Справочник.Упаковка
Характеристика : Справочник.Характеристика номенклатуры
..Движения..
ТоварыКОтгрузке : Остатки
ЗаказыМатериаловВПроизводство : Остатки
ГрафикОтгрузкиТоваров : Остатки
ФактическиеДанныеБюджетирования : Обороты
ОбеспечениеЗаказов : Остатки
ОбеспечениеЗаказовРаботами : Остатки
ЗаказыМатериаловСУчетомКорректировок : Обороты
СвободныеОстатки : Остатки
}
@enduml
