@startuml КомпенсацияЗаЗадержкуЗарплаты
'!include templates.wsd
'..\include templates.wsd
class Документ.КомпенсацияЗаЗадержкуЗарплаты as "Компенсация за задержку выплаты заработной платы" <<Документы>>
{
..Реквизиты..
ПериодРегистрации : Дата
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ПериодВзаиморасчетов : Дата
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
ПорядокВыплаты : Характер выплаты зарплаты
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
КраткийСоставДокумента : Строка
СуммаПоДокументу : Число 15, 2
Ответственный : Справочник.Пользователь
Комментарий : Строка
РегистрироватьДоходыСтраховыхВзносов : Булево
..Табличная часть \n Начисления..
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
СтатьяФинансирования : Справочник.Статья финансирования
СуммаКомпенсации : Число 15, 2
ПериодВзаиморасчетов : Дата
СтатьяРасходов : Справочник.Статья расходов
ДокументОснование : Документ.Единовременное пособие\rДокумент.Перенос затрат\rДокумент.Возврат НДФЛ\r...
СуммаКВыплате : Число 15, 2
ДатаС : Дата
ДатаПо : Дата
Ставка : Число 7, 5
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Табличная часть \n Состав..
Сотрудник : Справочник.Сотрудник
..Движения..
ВзаиморасчетыССотрудниками : Остатки
НачисленияУдержанияПоСотрудникам : Обороты
ПорядокВыплатыДокументов : РегистрСведений
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
СведенияОДоходахСтраховыеВзносы : Обороты
БухучетНачисленияУдержанияПоСотрудникам : Обороты
ЗарплатаКВыплате : Остатки
}
@enduml
