@startuml ВыкупВозвратнойТарыКлиентом
'!include templates.wsd
'..\include templates.wsd
class Документ.ВыкупВозвратнойТарыКлиентом as "Выкуп возвратной тары клиентом" <<Документы>>
{
..Реквизиты..
БанковскийСчетОрганизации : Справочник.Банковский счет организации
БанковскийСчетКонтрагента : Справочник.Банковский счет
БанковскийСчетГрузоотправителя : Справочник.Банковский счет
БанковскийСчетГрузополучателя : Справочник.Банковский счет
БанковскийСчетПеревозчика : Справочник.Банковский счет
Валюта : Справочник.Валюта
ВалютаВзаиморасчетов : Справочник.Валюта
Грузоотправитель : Справочник.Контрагент
Грузополучатель : Справочник.Контрагент
ДатаПлатежа : Дата
ДоверенностьВыдана : Строка
ДоверенностьДата : Дата
ДоверенностьЛицо : Строка
ДоверенностьНомер : Строка
Организация : Справочник.Организация
Контрагент : Справочник.Контрагент
Менеджер : Справочник.Пользователь
НалогообложениеНДС : Типы налогообложения НДС
СуммаДокумента : Число 15, 2
Партнер : Справочник.Партнер
Перевозчик : Справочник.Контрагент
Подразделение : Справочник.Подразделение
Соглашение : Справочник.Соглашение об условиях продаж
СуммаВзаиморасчетов : Число 15, 2
Комментарий : Строка
ФормаОплаты : Формы оплаты
ЦенаВключаетНДС : Булево
Касса : Справочник.Касса
Отпустил : Справочник.Физическое лицо
ОтпустилДолжность : Строка
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
Договор : Справочник.Договор с контрагентом
Основание : Строка
Автор : Справочник.Пользователь
КонтактноеЛицо : Справочник.Контактное лицо
ПорядокРасчетов : Детализация расчетов
Сделка : Справочник.Сделка с клиентом
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
ВидыЗапасовУказаныВручную : Булево
ПредусмотренЗалогЗаТару : Булево
ОснованиеДата : Дата
ОснованиеНомер : Строка
ИдентификаторПлатежа : Строка
НаправлениеДеятельности : Справочник.Направление деятельности
Курс : Число 10, 4
Кратность : Число 10, 0
ПорядокОплаты : Порядок оплаты
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ВидЦены : Справочник.Вид цены
Цена : Число 15, 2
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
ИдентификаторСтроки : Строка
ДокументРеализации : Документ.Реализация товаров и услуг\rДокумент.Передача сырья переработчику
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
..Табличная часть \n ВидыЗапасов..
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
СуммаСНДС : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
ИдентификаторСтроки : Строка
СуммаВзаиморасчетов : Число 15, 2
СкладОтгрузки : Справочник.Склад (складская территория)
ДокументРеализации : Документ.Реализация товаров и услуг\rДокумент.Передача сырья переработчику
УдалитьАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
ВидЗапасовОтгрузки : Справочник.Вид запасов
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n РасшифровкаПлатежа..
Заказ : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
Сумма : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
..Движения..
ПрочиеДоходы : Остатки
РасчетыСКлиентами : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
НДСПредъявленный : Остатки
ДвиженияКонтрагентДоходыРасходы : Обороты
ПереданнаяВозвратнаяТара : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
НДСЗаписиКнигиПродаж : Обороты
РасчетыСКлиентамиПоДокументам : Остатки
НДСЗаписиКнигиПокупок : Обороты
}
@enduml
