@startuml ТранспортнаяНакладная
'!include templates.wsd
'..\include templates.wsd
class Документ.ТранспортнаяНакладная as "Транспортная накладная" <<Документы>>
{
..Реквизиты..
АвтомобильВместимостьВКубическихМетрах : Число 6, 3
АвтомобильГосударственныйНомер : Строка
АвтомобильГрузоподъемностьВТоннах : Число 6, 3
АвтомобильМарка : Строка
АвтомобильТип : Строка
АдресДоставки : Строка
АдресДоставкиЗначенияПолей : Строка
АдресПогрузки : Строка
АдресПогрузкиЗначенияПолей : Строка
БанковскийСчетЗаказчикаПеревозки : Справочник.Банковский счет\rСправочник.Банковский счет организации
БанковскийСчетПлательщика : Справочник.Банковский счет\rСправочник.Банковский счет организации
БанковскийСчетПеревозчика : Справочник.Банковский счет
ВидПеревозки : Строка
Водитель : Строка
ВыводДанныхОТоварномСоставе : Варианты вывода данных о товарном составе
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
ГосударственныйНомерПрицепа : Строка
Грузоотправитель : Справочник.Организация\rСправочник.Контрагент
Грузополучатель : Справочник.Организация\rСправочник.Контрагент
ДоверенностьВыдана : Строка
ДоверенностьДата : Дата
ДоверенностьЛицо : Строка
ДоверенностьНомер : Строка
ЗаданиеНаПеревозку : Документ.Задание на перевозку
Комментарий : Строка
ЗаказчикПеревозки : Справочник.Организация\rСправочник.Контрагент
ЛицензионнаяКарточкаВид : Строка
ЛицензионнаяКарточкаНомер : Строка
ЛицензионнаяКарточкаРегистрационныйНомер : Строка
ЛицензионнаяКарточкаСерия : Строка
МассаБрутто : Число 15, 3
МассаНетто : Число 15, 3
Организация : Справочник.Организация
Отпустил : Справочник.Физическое лицо
ОтпустилДолжность : Строка
Плательщик : Справочник.Организация\rСправочник.Контрагент
Перевозчик : Справочник.Контрагент
Прицеп : Строка
Руководитель : Справочник.Лицо с правом подписи
СрокДоставки : Дата
УдостоверениеНомер : Строка
УдостоверениеСерия : Строка
..Табличная часть \n ДокументыОснования..
ДокументОснование : Документ.Передача давальцу\rДокумент.Возврат товаров поставщику\rДокумент.Отгрузка товаров с хранения\r...
}
@enduml
