@startuml УдержаниеВСчетРасчетовПоПрочимОперациям
'!include templates.wsd
'..\include templates.wsd
class Документ.УдержаниеВСчетРасчетовПоПрочимОперациям as "Удержание по прочим операциям" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
РабочееМесто : Справочник.Сотрудник
Удержание : Удержание
ДатаНачала : Дата
ДатаОкончания : Дата
Действие : Действия с удержаниями
Размер : Число 15, 2
ДокументОснование : Документ.Удержание по прочим операциям
Ответственный : Справочник.Пользователь
Комментарий : Строка
БухучетЗаданВДокументе : Булево
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
УдалитьДействие : Действия с начислениями и удержаниями
ПрекратитьПоДостижениюПредела : Булево
Предел : Число 15, 2
..Табличная часть \n Показатели..
Показатель : Справочник.Показатель
Значение : Число 15, 5
..Движения..
БухучетПлановыхУдержаний : РегистрСведений
УдержанияДоПределаПоСотрудникам : Остатки
РабочиеМестаУдержаний : РегистрСведений
ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
ПредельныеСуммыУдержанийСотрудников : РегистрСведений
ПлановыеУдержания : РегистрСведений
}
@enduml
