@startuml ОжидаемоеПоступлениеДенежныхСредств
'!include templates.wsd
'..\include templates.wsd
class Документ.ОжидаемоеПоступлениеДенежныхСредств as "Ожидаемое поступление денежных средств" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
СуммаДокумента : Число 15, 2
Валюта : Справочник.Валюта
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
НазначениеПлатежа : Строка
ФормаОплаты : Формы оплаты
БанковскийСчет : Справочник.Банковский счет организации
Касса : Справочник.Касса
Подразделение : Справочник.Подразделение
КассаБанковскийСчет : Справочник.Банковский счет организации\rСправочник.Касса
}
@enduml
