@startuml КомандировкиСотрудников
'!include templates.wsd
'..\include templates.wsd
class Документ.КомандировкиСотрудников as "Командировка группы" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
КраткийСоставДокумента : Строка
ДатаСобытия : Дата
Основание : Строка
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
Ответственный : Справочник.Пользователь
Комментарий : Строка
УдалитьДокументОснование : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ДатаНачала : Дата
ДатаОкончания : Дата
ДнейВПути : Число 3, 0
МестоНазначения : Строка
ОрганизацияНазначения : Строка
Цель : Строка
КомандировкаЗаСчетСредств : Строка
Командировка : Документ.Командировка
}
@enduml
