@startuml Отгул
'!include templates.wsd
'..\include templates.wsd
class Документ.Отгул as "Отгул" <<Документы>>
{
..Реквизиты..
ПериодРегистрации : Дата
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ВидРасчета : Начисление
ДатаНачала : Дата
ДатаОкончания : Дата
ДатаОтсутствия : Дата
Начислено : Число 13, 2
КоличествоДнейОтгула : Число 4, 2
ОтсутствиеВТечениеЧастиСмены : Булево
КоличествоЧасовОтгула : Число 4, 2
ВидВремениЗамещаемый : Справочник.Вид рабочего времени
ИсправленныйДокумент : Документ.Отгул
ПерерасчетВыполнен : Булево
Рассчитал : Справочник.Пользователь
ПредставлениеПериода : Строка
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
РасходДнейОтгула : Число 5, 2
РасходЧасовОтгула : Число 5, 2
ОсвобождатьСтавку : Булево
Ответственный : Справочник.Пользователь
Комментарий : Строка
ДоначислитьЗарплатуПриНеобходимости : Булево
..Табличная часть \n Начисления..
Начисление : Начисление
ДатаНачала : Дата
ДатаОкончания : Дата
Результат : Число 13, 2
Подразделение : Справочник.Подразделение
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
Сотрудник : Справочник.Сотрудник
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ВидУчетаВремени : Справочник.Вид рабочего времени
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
ВремяВЧасах : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ПериодРегистрацииВремени : Дата
СуммаВычета : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
ОплаченоДней : Число 15, 2
ОплаченоЧасов : Число 15, 2
ПериодДействия : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n НачисленияПерерасчет..
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Результат : Число 13, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
Сторно : Булево
СторнируемыйДокумент : Документ.Приз, подарок\rДокумент.Простой сотрудников\rДокумент.Отпуск без сохранения оплаты списком\r...
Сотрудник : Справочник.Сотрудник
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
СуммаВычета : Число 15, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
ФиксСторно : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ПериодРегистрацииВремени : Дата
ВремяВЧасах : Булево
ВидУчетаВремени : Справочник.Вид рабочего времени
ОплаченоДней : Число 15, 2
ОплаченоЧасов : Число 15, 2
РезультатВТомЧислеЗаСчетФБ : Число 15, 2
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ПериодДействия : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n Показатели..
Показатель : Справочник.Показатель
Значение : Число 15, 5
ИдентификаторСтрокиВидаРасчета : Число 7, 0
..Табличная часть \n РаспределениеРезультатовНачислений..
ИдентификаторСтроки : Число 7, 0
Территория : Справочник.Территория
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОблагаетсяЕНВД : Булево
Результат : Число 13, 2
..Табличная часть \n РаспределениеПоТерриториямУсловиямТруда..
ИдентификаторСтроки : Число 7, 0
Территория : Справочник.Территория
УсловияТруда : Справочник.Условия труда
ДоляРаспределения : Число 15, 5
Результат : Число 15, 2
ИдентификаторСтрокиПоказателей : Число 7, 0
СуммаВычета : Число 13, 0
..Табличная часть \n НачисленияПерерасчетНулевыеСторно..
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Сторно : Булево
СторнируемыйДокумент : Документ.Приз, подарок\rДокумент.Простой сотрудников\rДокумент.Отпуск без сохранения оплаты списком\r...
Сотрудник : Справочник.Сотрудник
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ФиксСторно : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ПериодДействия : Дата
Результат : Число 13, 2
ФиксРасчет : Булево
ФиксЗаполнение : Булево
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
..Движения..
ДанныеОперативногоУчетаРабочегоВремениСотрудников : Обороты
ДанныеОВремениДляРасчетаСреднегоФСС : РегистрСведений
ВзаиморасчетыССотрудниками : Остатки
НачисленияУдержанияПоСотрудникам : Обороты
ЗанятыеПозицииШтатногоРасписания : Остатки
ОтработанноеВремяПоСотрудникамКорректировка : Обороты
ДанныеСостоянийСотрудников : РегистрСведений
РаспределениеПоТерриториямУсловиямТруда : РегистрСведений
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
ДанныеОВремениДляРасчетаСреднегоОбщий : Обороты
ВытесняемоеПлановоеВремяСотрудников : Обороты
СведенияОДоходахСтраховыеВзносы : Обороты
ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаОбщий : Обороты
ЗначенияПоказателейНачислений : РегистрСведений
ОтработанноеВремяПоСотрудникам : Обороты
Начисления : РегистрРасчета
СведенияОДоходахНДФЛ : Обороты
ДниЧасыОтгулов : Остатки
БухучетНачисленияУдержанияПоСотрудникам : Обороты
ЗарплатаКВыплате : Остатки
ДанныеТабельногоУчетаРабочегоВремениСотрудников : Обороты
ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаФСС : Обороты
}
@enduml
