@startuml ДоговорАвторскогоЗаказа
'!include templates.wsd
'..\include templates.wsd
class Документ.ДоговорАвторскогоЗаказа as "Договор авторского заказа" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ДатаНачала : Дата
ДатаОкончания : Дата
МесяцНачисления : Дата
УдалитьОплатаПоАктамВыполненныхРабот : Булево
Сумма : Число 13, 2
СуммаВычета : Число 15, 2
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОтношениеКЕНВД : Отношение к ЕНВД затрат на зарплату
СуммаЕНВД : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
ВидАвторскогоДоговора : Справочник.Вид договора авторского заказа
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
Ответственный : Справочник.Пользователь
Комментарий : Строка
СпособОплаты : Способы оплаты по договору ГПХ
РазмерПлатежа : Число 15, 2
Территория : Справочник.Территория
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ПлановыеНачисленияПоДоговорам : РегистрСведений
УсловияДоговораГПХ : РегистрСведений
ПериодыДействияДоговоровГражданскоПравовогоХарактера : РегистрСведений
ПараметрыПериодовСтажаПФР : РегистрСведений
}
@enduml
