@startuml РассылкаКлиентам
'!include templates.wsd
'..\include templates.wsd
class Документ.РассылкаКлиентам as "Рассылка клиентам" <<Документы>>
{
..Реквизиты..
ДатаРассылки : Дата
ДатаАктуальности : Дата
Основание : Справочник.Маркетинговое мероприятие\rДокумент.Проведение опроса
ГруппаРассылокИОповещений : Справочник.Группа рассылок и оповещений
ПредназначенаДляЭлектронныхПисем : Булево
ПредназначенаДляSMS : Булево
Тема : Строка
ТекстПисьма : Строка
ТекстПисьмаHTML : Строка
ТекстSMS : Строка
ОтборАдресатов : Хранилище значения
ТипТекстаПисьма : Способы редактирования электронных писем
Статус : Статусы рассылок клиентам
ОтправлятьВТранслите : Булево
Комментарий : Строка
ПредставлениеОтбора : Строка
Ответственный : Справочник.Пользователь
ЕстьВложения : Булево
..Табличная часть \n ДополнительныеПолучатели..
Контакт : Справочник.Партнер\rСправочник.Контактное лицо
КонтактнаяИнформация : Строка
}
@enduml
