@startuml ЗаказДавальца
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаказДавальца as "Заказ давальца" <<Документы>>
{
..Реквизиты..
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
Организация : Справочник.Организация
Сделка : Справочник.Сделка с клиентом
Склад : Справочник.Склад (складская территория)
Валюта : Справочник.Валюта
Менеджер : Справочник.Пользователь
ЦенаВключаетНДС : Булево
Статус : Статусы заказов давальцев
СуммаДокумента : Число 15, 2
СуммаЗалоговая : Число 15, 2
ДополнительнаяИнформация : Строка
ЖелаемаяДатаПоступления : Дата
ПродукцияМаксимальныйКодСтроки : Число 10, 0
Согласован : Булево
ДатаПервогоПоступления : Дата
НалогообложениеНДС : Типы налогообложения НДС
ХозяйственнаяОперация : Хозяйственные операции
ЖелаемаяДатаОтгрузки : Дата
ДатаОтгрузки : Дата
АдресДоставки : Строка
СкидкиРассчитаны : Булево
НеОтгружатьЧастями : Булево
ФормаОплаты : Формы оплаты
БанковскийСчет : Справочник.Банковский счет организации
Касса : Справочник.Касса
ГрафикОплаты : Справочник.График оплаты
СуммаАвансаДоОбеспечения : Число 15, 2
СуммаПредоплатыДоОтгрузки : Число 15, 2
МатериалыМаксимальныйКодСтроки : Число 10, 0
Комментарий : Строка
Грузоотправитель : Справочник.Контрагент
Грузополучатель : Справочник.Контрагент
БанковскийСчетГрузоотправителя : Справочник.Банковский счет
БанковскийСчетГрузополучателя : Справочник.Банковский счет
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
Договор : Справочник.Договор с контрагентом
ДатаПоступления : Дата
ПоступлениеОднойДатой : Булево
ПорядокРасчетов : Детализация расчетов
ВидДокументаПокупателя : Справочник.Вид документа физических лиц
СерияДокументаПокупателя : Строка
НомерДокументаПокупателя : Строка
ДатаВыдачиДокументаПокупателя : Дата
СрокДействияДокументаПокупателя : Дата
КемВыданДокументПокупателя : Строка
КодПодразделенияДокументаПокупателя : Строка
УдалитьДатаРожденияПокупателя : Дата
Покупатель : Строка
ПричинаВозврата : Строка
СпособДоставки : Способы доставки
ПеревозчикПартнер : Справочник.Партнер
ЗонаДоставки : Справочник.Зоны доставки
ВремяДоставкиС : Дата
ВремяДоставкиПо : Дата
АдресДоставкиПеревозчика : Строка
АдресДоставкиЗначенияПолей : Строка
АдресДоставкиПеревозчикаЗначенияПолей : Строка
ДополнительнаяИнформацияПоДоставке : Строка
Назначение : Справочник.Назначение
Подразделение : Справочник.Подразделение
КонтактноеЛицо : Справочник.Контактное лицо
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
Спецификация : Справочник.Ресурсная спецификация
НомерПоДаннымПартнера : Строка
ДатаПоДаннымПартнера : Дата
ВидЦены : Справочник.Вид цены
БанковскийСчетКонтрагента : Справочник.Банковский счет
НазначениеПлатежа : Строка
СкладПоступления : Справочник.Склад (складская территория)
Автор : Справочник.Пользователь
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
СтавкаНДС : Ставки НДС
Содержание : Строка
ВернутьМногооборотнуюТару : Булево
СрокВозвратаМногооборотнойТары : Число 3, 0
СостояниеЗаполненияМногооборотнойТары : Состояния заполнения многооборотной тары
Приоритет : Справочник.Приоритет
ИдентификаторПлатежа : Строка
ТребуетсяЗалогЗаТару : Булево
ОсобыеУсловияПеревозки : Булево
ОсобыеУсловияПеревозкиОписание : Строка
НаправлениеДеятельности : Справочник.Направление деятельности
УправлениеПроизводством2_2 : Булево
ПорядокОплаты : Порядок оплаты
НазначениеМатериалы : Справочник.Назначение
ДоговорНеОбязателен : Булево
ВариантПриемкиТоваров : Варианты приемки товаров
..Табличная часть \n Продукция..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ДатаОтгрузки : Дата
Цена : Число 15, 2
ЦенаСобственныхМатериалов : Число 15, 2
Сумма : Число 15, 2
КодСтроки : Число 10, 0
Отменено : Булево
ПричинаОтмены : Справочник.Причина отмены заказов клиентов
Склад : Справочник.Склад (складская территория)
ВидЦены : Справочник.Вид цены
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
СуммаСобственныхМатериалов : Число 15, 2
СуммаУслуги : Число 15, 2
Спецификация : Справочник.Ресурсная спецификация
ВариантОбеспечения : Варианты обеспечения
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
..Табличная часть \n Материалы..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ВидЦены : Справочник.Вид цены
Цена : Число 15, 2
Сумма : Число 15, 2
Склад : Справочник.Склад (складская территория)
ДатаПоступления : Дата
КодСтроки : Число 10, 0
УдалитьКодСтрокиПродукция : Строка\rЧисло 10, 0
Назначение : Справочник.Назначение
Спецификация : Справочник.Ресурсная спецификация
..Табличная часть \n ЭтапыГрафикаОплаты..
ВариантОплаты : Варианты оплаты клиентом
ДатаПлатежа : Дата
ПроцентПлатежа : Число 5, 2
СуммаПлатежа : Число 15, 2
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ТоварыКОтгрузке : Остатки
РасчетыСКлиентами : Остатки
ГрафикОтгрузкиТоваров : Остатки
ФактическиеДанныеБюджетирования : Обороты
УслугиДавальцуКОформлению : Остатки
ЗаказыКлиентов : Остатки
ОбеспечениеЗаказов : Остатки
ДвижениеТоваров : Обороты
РасчетыСКлиентамиПоДокументам : Остатки
СвободныеОстатки : Остатки
ГрафикПоступленияТоваров : Остатки
ЗаказыПоставщикам : Остатки
ТоварыКПоступлению : Остатки
}
@enduml
