@startuml НачислениеПоДоговорам
'!include templates.wsd
'..\include templates.wsd
class Документ.НачислениеПоДоговорам as "Начисление по договорам" <<Документы>>
{
..Реквизиты..
МесяцНачисления : Дата
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Начислено : Число 13, 2
Удержано : Число 13, 2
ПорядокВыплаты : Характер выплаты зарплаты
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n НачисленияПоДоговорам..
Сотрудник : Справочник.Сотрудник
ДатаНачала : Дата
ДатаОкончания : Дата
Подразделение : Справочник.Подразделение
КодВычета : Справочник.Вид вычетов НДФЛ
СуммаВычета : Число 15, 2
ДокументОснование : Документ.Договор авторского заказа\rДокумент.Акт приемки выполненных работ\rДокумент.Договор (работы, услуги)
Результат : Число 13, 2
ФиксРасчет : Булево
ФиксСтрока : Булево
КодДохода : Справочник.Вид дохода НДФЛ
ПланируемаяДатаВыплаты : Дата
ИдентификаторСтроки : Число 7, 0
КодДоходаСтраховыеВзносы : Справочник.Вид дохода по страховым взносам
..Табличная часть \n НДФЛ..
ФизическоеЛицо : Справочник.Физическое лицо
МесяцНалоговогоПериода : Дата
Подразделение : Справочник.Территория\rСправочник.Подразделение
Налог : Число 10, 0
ЗачтеноАвансовыхПлатежей : Число 10, 0
ПримененныйВычетЛичный : Число 12, 2
ПримененныйВычетЛичныйКодВычета : Справочник.Вид вычетов НДФЛ
ПримененныйВычетЛичныйКЗачетуВозврату : Число 12, 2
ПримененныйВычетЛичныйКЗачетуВозвратуКодВычета : Справочник.Вид вычетов НДФЛ
ИдентификаторСтрокиНДФЛ : Число 7, 0
ФиксСтрока : Булево
ФиксРасчет : Булево
КатегорияДохода : Категории доходов НДФЛ
..Табличная часть \n Показатели..
Показатель : Справочник.Показатель
Значение : Число 15, 5
ИдентификаторСтрокиВидаРасчета : Число 7, 0
..Табличная часть \n ПримененныеВычетыНаДетейИИмущественные..
КодВычета : Справочник.Вид вычетов НДФЛ
РазмерВычета : Число 12, 2
ИдентификаторСтрокиНДФЛ : Число 7, 0
..Табличная часть \n РаспределениеРезультатовНачислений..
ИдентификаторСтроки : Число 7, 0
Территория : Справочник.Территория
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОблагаетсяЕНВД : Булево
Результат : Число 13, 2
..Табличная часть \n РаспределениеРезультатовУдержаний..
ИдентификаторСтроки : Число 7, 0
ВидУдержания : Виды особых начислений и удержаний\rУдержание
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
Результат : Число 13, 2
..Табличная часть \n ПредставлениеРаспределенияРезультатовРасчета..
ИдентификаторСтроки : Число 7, 0
НомерСтрокиРаспределения : Число 10, 0
НомерЭлементаПредставления : Число 10, 0
КоличествоЭлементовПредставления : Число 10, 0
ПредставлениеРезультата : Строка
ЕстьОшибкиЗаполнения : Булево
РаспределениеНачислений : Булево
..Табличная часть \n Удержания..
ФизическоеЛицо : Справочник.Физическое лицо
ДатаНачала : Дата
ДатаОкончания : Дата
ДокументОснование : Документ.Удержание по прочим операциям\rДокумент.Удержание добровольных взносов в НПФ\rДокумент.Удержание профсоюзных взносов\r...
Получатель : Справочник.Контрагент
ПлатежныйАгент : Справочник.Контрагент
Удержание : Удержание
ФиксРасчет : Булево
Результат : Число 13, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ФиксЗаполнение : Булево
ФиксСтрока : Булево
Сотрудник : Справочник.Сотрудник
ФиксСторно : Булево
..Табличная часть \n КорректировкиВыплаты..
ФизическоеЛицо : Справочник.Физическое лицо
КорректировкаВыплаты : Число 10, 0
ИдентификаторСтроки : Число 7, 0
ФиксСтрока : Булево
ФиксРасчет : Булево
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Табличная часть \n РаспределениеПоТерриториямУсловиямТруда..
ИдентификаторСтроки : Число 7, 0
Территория : Справочник.Территория
УсловияТруда : Справочник.Условия труда
ДоляРаспределения : Число 15, 5
Результат : Число 15, 2
ИдентификаторСтрокиПоказателей : Число 7, 0
СуммаВычета : Число 13, 0
..Движения..
Удержания : РегистрРасчета
ОплаченныеДоговоры : РегистрСведений
РасчетыНалогоплательщиковСБюджетомПоНДФЛ : Остатки
ЗначенияПоказателейУдержаний : РегистрСведений
ВзаиморасчетыССотрудниками : Остатки
НачисленияУдержанияПоСотрудникам : Обороты
ПорядокВыплатыДокументов : РегистрСведений
УдержанияДоПределаПоСотрудникам : Остатки
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
СведенияОДоходахСтраховыеВзносы : Обороты
ИмущественныеВычетыНДФЛ : Остатки
ЗначенияПоказателейНачислений : РегистрСведений
ПредоставленныеСтандартныеИСоциальныеВычетыНДФЛ : Обороты
НачисленияПоДоговорамГПХ : Обороты
УдержанияПоИсполнительнымДокументам : Обороты
СведенияОДоходахНДФЛ : Обороты
БухучетНачисленияУдержанияПоСотрудникам : Обороты
ЗарплатаКВыплате : Остатки
АвансовыеПлатежиИностранцевПоНДФЛ : Остатки
}
@enduml
