@startuml ИнвентаризационнаяОпись
'!include templates.wsd
'..\include templates.wsd
class Документ.ИнвентаризационнаяОпись as "Инвентаризационная опись" <<Документы>>
{
..Реквизиты..
ДатаНачала : Дата
ДатаОкончания : Дата
Комментарий : Строка
Ответственный : Справочник.Пользователь
Склад : Справочник.Склад (складская территория)
Организация : Справочник.Организация
ВидЦены : Справочник.Вид цены
ИсточникИнформацииОЦенахДляПечати : Источники информации о ценах для печати
Подразделение : Справочник.Подразделение
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
