@startuml СогласиеНаОбработкуПерсональныхДанных
'!include templates.wsd
'..\include templates.wsd
class Документ.СогласиеНаОбработкуПерсональныхДанных as "Согласие на обработку персональных данных" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
НаименованиеОрганизации : Строка
ЮридическийАдресОрганизации : Строка
ОтветственныйЗаОбработкуПерсональныхДанных : Справочник.Пользователь
Субъект : Справочник.Физическое лицо
ФИОСубъекта : Строка
АдресСубъекта : Строка
ПаспортныеДанные : Строка
ДатаПолучения : Дата
СрокДействия : Дата
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Движения..
СогласияНаОбработкуПерсональныхДанных : РегистрСведений
}
@enduml
