@startuml ВедомостьНаВыплатуЗарплатыВКассу
'!include templates.wsd
'..\include templates.wsd
class Документ.ВедомостьНаВыплатуЗарплатыВКассу as "Ведомость в кассу" <<Документы>>
{
..Реквизиты..
ПериодРегистрации : Дата
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
Касса : Справочник.Касса
СпособВыплаты : Справочник.Способ выплаты зарплаты
Округление : Справочник.Способ округления
ПроцентВыплаты : Число 3, 0
СуммаПоДокументу : Число 15, 2
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ГлавныйБухгалтер : Справочник.Физическое лицо
Кассир : Справочник.Физическое лицо
ДолжностьКассира : Справочник.Должность
Бухгалтер : Справочник.Физическое лицо
ВводНачальныхДанных : Булево
ДатаВыплаты : Дата
ПеречислениеНДФЛВыполнено : Булево
ПеречислениеНДФЛРеквизиты : Строка
Составил : Справочник.Физическое лицо
ДолжностьСоставившего : Справочник.Должность
Проверил : Справочник.Физическое лицо
ДолжностьПроверившего : Справочник.Должность
Раздатчик : Справочник.Физическое лицо
ДолжностьРаздатчика : Справочник.Должность
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Состав..
ИдентификаторСтроки : Уникальный идентификатор
ФизическоеЛицо : Справочник.Физическое лицо
..Табличная часть \n Зарплата..
ИдентификаторСтроки : Уникальный идентификатор
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
Подразделение : Справочник.Подразделение
ПериодВзаиморасчетов : Дата
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
ДокументОснование : Документ.Единовременное пособие\rДокумент.Перенос затрат\rДокумент.Возврат НДФЛ\r...
КВыплате : Число 15, 2
КомпенсацияЗаЗадержкуЗарплаты : Число 15, 2
..Табличная часть \n Основания..
Документ : Документ.Сторнирование начислений\rДокумент.Внутреннее потребление товаров\rДокумент.Назначение планового начисления\r...
..Табличная часть \n НДФЛ..
ИдентификаторСтроки : Уникальный идентификатор
ФизическоеЛицо : Справочник.Физическое лицо
СтавкаНалогообложенияРезидента : НДФЛ ставки налогообложения резидента
МесяцНалоговогоПериода : Дата
КодДохода : Справочник.Вид дохода НДФЛ
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
Подразделение : Справочник.Территория\rСправочник.Подразделение
ВключатьВДекларациюПоНалогуНаПрибыль : Булево
ДокументОснование : Документ.Сторнирование начислений\rДокумент.Перенос затрат\rДокумент.Приз, подарок\r...
Сумма : Число 13, 0
КатегорияДохода : Категории доходов НДФЛ
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Движения..
РасчетыНалогоплательщиковСБюджетомПоНДФЛ : Остатки
ВзаиморасчетыССотрудниками : Остатки
НачисленияУдержанияПоСотрудникам : Обороты
УплатаНДФЛНалоговымиАгентамиКРаспределению : Остатки
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
ЗарплатаКВыплатеАвансом : Остатки
РасчетыНалоговыхАгентовСБюджетомПоНДФЛ : Остатки
СведенияОДоходахНДФЛ : Обороты
БухучетНачисленияУдержанияПоСотрудникам : Обороты
ЗарплатаКВыплате : Остатки
}
@enduml
