@startuml ВедомостьУплатыАДВ_11
'!include templates.wsd
'..\include templates.wsd
class Документ.ВедомостьУплатыАДВ_11 as "Ведомость уплаты взносов АДВ-11" <<Документы>>
{
..Реквизиты..
ОтчетныйПериод : Число 4, 0
Организация : Справочник.Организация
ОкончаниеОтчетногоПериода : Дата
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ДокументПринятВПФР : Булево
НомерПачки : Число 5, 0
ИмяФайлаДляПФР : Строка
ФайлСформирован : Булево
КодКатегории : Категории застрахованных лиц для ПФР
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n СведенияОЗадолженности..
ТипСтроки : Разделы АДВ-11
Год : Число 4, 0
СтраховаяЧасть : Число 15, 2
НакопительнаяЧасть : Число 15, 2
ДополнительныйТариф : Число 15, 2
}
@enduml
