@startuml ВыкупПринятыхНаХранениеТоваров
'!include templates.wsd
'..\include templates.wsd
class Документ.ВыкупПринятыхНаХранениеТоваров as "Выкуп товаров с хранения" <<Документы>>
{
..Реквизиты..
Валюта : Справочник.Валюта
Партнер : Справочник.Партнер
Соглашение : Справочник.Соглашение об условиях закупок
ХозяйственнаяОперация : Хозяйственные операции
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
МестоХранения : Справочник.Подразделение\rСправочник.Склад (складская территория)
Контрагент : Справочник.Контрагент
СуммаДокумента : Число 15, 2
Менеджер : Справочник.Пользователь
ЦенаВключаетНДС : Булево
ВалютаВзаиморасчетов : Справочник.Валюта
Комментарий : Строка
ДатаПлатежа : Дата
ФормаОплаты : Формы оплаты
НалогообложениеНДС : Типы налогообложения НДС
СуммаВзаиморасчетов : Число 15, 2
НомерВходящегоДокумента : Строка
ДатаВходящегоДокумента : Дата
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
Договор : Справочник.Договор с контрагентом
ПорядокРасчетов : Детализация расчетов
НаправлениеДеятельности : Справочник.Направление деятельности
Курс : Число 10, 4
Кратность : Число 10, 0
БанковскийСчетОрганизации : Справочник.Банковский счет организации
БанковскийСчетКонтрагента : Справочник.Банковский счет
ПорядокОплаты : Порядок оплаты
Сделка : Справочник.Сделка с клиентом
ВыкупПодДеятельность : Типы налогообложения НДС
ВидЦеныПоставщика : Справочник.Вид цены поставщика
..Табличная часть \n Товары..
НоменклатураПоставщика : Справочник.Номенклатура поставщика
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Цена : Число 15, 2
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
СтатусУказанияСерий : Число 2, 0
СуммаВзаиморасчетов : Число 15, 2
СуммаНДСВзаиморасчетов : Число 15, 2
ИдентификаторСтроки : Строка
ВидЗапасов : Справочник.Вид запасов
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n ВидыЗапасов..
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
СуммаСНДС : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
ИдентификаторСтроки : Строка
Цена : Число 15, 2
ВидЗапасовВыкупаемый : Справочник.Вид запасов
СуммаВзаиморасчетов : Число 15, 2
СуммаНДСВзаиморасчетов : Число 15, 2
..Движения..
ПрочиеДоходы : Остатки
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ДвиженияДенежныеСредстваКонтрагент : Обороты
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНМатериалы : Остатки
РасходыПриУСН : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
РасчетыСПоставщиками : Остатки
Международный : РегистрБухгалтерии
Закупки : Обороты
РасходыПриУСНТовары : Остатки
ТоварыПринятые : Остатки
НДСЗаписиКнигиПродаж : Обороты
РасчетыСПоставщикамиПоДокументам : Остатки
КнигаУчетаДоходовИРасходов : Обороты
ДвиженияКонтрагентКонтрагент : Обороты
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
}
@enduml
