@startuml ЗапросНаИнформационноеОбслуживаниеСтрахователя
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗапросНаИнформационноеОбслуживаниеСтрахователя as "Запрос на информационное обслуживание страхователя" <<Документы>>
{
..Реквизиты..
ВидУслуги : Виды услуг при информационном обслуживании страхователя
НаДату : Дата
Организация : Справочник.Организация
Получатель : Справочник.Органы ПФР
..Табличная часть \n ЗастрахованныеЛица..
Фамилия : Строка
Имя : Строка
Отчество : Строка
СтраховойНомер : Строка
}
@enduml
