@startuml ЧекККМВозврат
'!include templates.wsd
'..\include templates.wsd
class Документ.ЧекККМВозврат as "Чек ККМ на возврат" <<Документы>>
{
..Реквизиты..
Архивный : Булево
Валюта : Справочник.Валюта
ВидЦены : Справочник.Вид цены
КассаККМ : Справочник.Кассы ККМ
Кассир : Справочник.Пользователь
Комментарий : Строка
НалогообложениеНДС : Типы налогообложения НДС
Организация : Справочник.Организация
Склад : Справочник.Склад (складская территория)
СуммаДокумента : Число 15, 2
ЦенаВключаетНДС : Булево
ЧекККМ : Документ.Чек ККМ
Статус : Статусы чеков ККМ
Партнер : Справочник.Партнер
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
СуммаБонусныхБалловКВозврату : Число 15, 2
КартаЛояльности : Справочник.Карты лояльности
ВыданоНаличными : Число 15, 2
УдалитьАдресЧекаЕГАИС : Строка
УдалитьПодписьЧекаЕГАИС : Строка
КассоваяСмена : Документ.Кассовая смена
УдалитьНомерЧекаККМ : Число 8, 0
УдалитьВариантОтправкиЭлектронногоЧека : Варианты отправки электронного чека покупателю
УдалитьКонтактныеДанныеЭлектронногоЧека : Строка
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Цена : Число 15, 2
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СтатусУказанияСерий : Число 2, 0
Продавец : Справочник.Пользователь
Помещение : Справочник.Помещение
Серия : Справочник.Серия номенклатуры
НоменклатураНабора : Справочник.Номенклатура
ХарактеристикаНабора : Справочник.Характеристика номенклатуры
Штрихкод : Строка
ИдентификаторСтроки : Строка
НоменклатураЕГАИС : Справочник.Алкогольная продукция ЕГАИС
..Табличная часть \n ОплатаПлатежнымиКартами..
ЭквайринговыйТерминал : Справочник.Эквайринговый терминал
НомерПлатежнойКарты : Строка
Сумма : Число 15, 2
СсылочныйНомер : Строка
КодАвторизации : Строка
НомерЧекаЭТ : Строка
ОплатаОтменена : Булево
..Табличная часть \n Серии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Помещение : Справочник.Помещение
..Табличная часть \n БонусныеБаллы..
БонуснаяПрограммаЛояльности : Справочник.Бонусные программы лояльности
ДатаНачисления : Дата
ДатаСписания : Дата
СуммаБонусныхБаллов : Число 15, 2
..Табличная часть \n АкцизныеМарки..
ИдентификаторСтроки : Строка
КодАкцизнойМарки : Строка
..Движения..
ДвиженияСерийТоваров : Обороты
ПрочиеАктивыПассивы : Остатки
ДенежныеСредстваВПути : Остатки
ФактическиеДанныеБюджетирования : Обороты
ДенежныеСредстваВКассахККМ : Остатки
ТоварыНаСкладах : Остатки
СвободныеОстатки : Остатки
БонусныеБаллы : Остатки
РасчетыПоЭквайрингу : Остатки
}
@enduml
