@startuml ПачкаДокументовАДВ_2
'!include templates.wsd
'..\include templates.wsd
class Документ.ПачкаДокументовАДВ_2 as "Пачка документов АДВ-2" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
НомерПачки : Число 5, 0
ИмяФайлаДляПФР : Строка
ДокументПринятВПФР : Булево
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
Исполнитель : Справочник.Физическое лицо
ФайлСформирован : Булево
ОкончаниеОтчетногоПериода : Дата
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Физическое лицо
ДатаПолученияСвидетельства : Дата
СтраховойНомерПФРВСвидетельстве : Строка
ФамилияВСвидетельстве : Строка
ИмяВСвидетельстве : Строка
ОтчествоВСвидетельстве : Строка
Фамилия : Строка
Имя : Строка
Отчество : Строка
Пол : Пол физического лица
ДатаРождения : Дата
МестоРождения : Строка
Гражданство : Справочник.Страна мира
АдресРегистрации : Строка
АдресФактический : Строка
Телефоны : Строка
ПризнакОтменыОтчества : Булево
ПризнакОтменыМестаРождения : Булево
ВидДокумента : Справочник.Вид документа физических лиц
СерияДокумента : Строка
НомерДокумента : Строка
ДатаВыдачи : Дата
КемВыдан : Строка
МестоРожденияПредставление : Строка
АдресРегистрацииПредставление : Строка
АдресФактическийПредставление : Строка
}
@enduml
