@startuml ГрафикИсполненияДоговора
'!include templates.wsd
'..\include templates.wsd
class Документ.ГрафикИсполненияДоговора as "График исполнения договора" <<Документы>>
{
..Реквизиты..
Договор : Справочник.Договор с контрагентом
ПорядокРасчетов : Детализация расчетов
..Табличная часть \n ЭтапыГрафикаИсполненияДоговора..
ДатаПоГрафику : Дата
ПроцентОплаты : Число 5, 2
СуммаОплаты : Число 15, 2
ПроцентИсполнения : Число 5, 2
СуммаИсполнения : Число 15, 2
Комментарий : Строка
..Движения..
РасчетыСКлиентами : Остатки
РасчетыСПоставщиками : Остатки
РасчетыСКлиентамиПоДокументам : Остатки
РасчетыСПоставщикамиПоДокументам : Остатки
}
@enduml
