@startuml ДепонированиеЗарплаты
'!include templates.wsd
'..\include templates.wsd
class Документ.ДепонированиеЗарплаты as "Депонирование зарплаты" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Ведомость : Документ.Ведомость через раздатчика\rДокумент.Ведомость в кассу
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
Бухгалтер : Справочник.Лицо с правом подписи
Кассир : Справочник.Лицо с правом подписи
Ответственный : Справочник.Пользователь
Комментарий : Строка
ПроводкиПоРаботникам : Булево
..Табличная часть \n Депоненты..
ФизическоеЛицо : Справочник.Физическое лицо
Сумма : Число 15, 2
..Движения..
РасчетыНалогоплательщиковСБюджетомПоНДФЛ : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
УплатаНДФЛНалоговымиАгентамиКРаспределению : Остатки
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
РасчетыНалоговыхАгентовСБюджетомПоНДФЛ : Остатки
СведенияОДоходахНДФЛ : Обороты
БухучетНачисленияУдержанияПоСотрудникам : Обороты
ОплатаВедомостейНаВыплатуЗарплаты : РегистрСведений
}
@enduml
