@startuml СчетФактураНалоговыйАгент
'!include templates.wsd
'..\include templates.wsd
class Документ.СчетФактураНалоговыйАгент as "Счет-фактура налогового агента" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ДокументОснование : Документ.Расходный кассовый ордер\rДокумент.Первичный документ\rДокумент.Списание безналичных ДС\r...
СтрокаПлатежноРасчетныеДокументы : Строка
Валюта : Справочник.Валюта
КодВидаОперации : Строка
Поставщик : Справочник.Контрагент
СуммаСНДС : Число 15, 2
СуммаНДС : Число 14, 2
Сумма : Число 15, 2
Договор : Справочник.Договор с контрагентом
УдалитьСуммаКПоступлению : Число 15, 2
ВидАгентскогоДоговора : Виды агентских договоров
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
УдалитьНалогПеречислен : Булево
УдалитьДатаДокументаПеречисленияНалога : Дата
УдалитьНомерДокументаПеречисленияНалога : Строка
УдалитьДатаПеречисленияНалога : Дата
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n РасшифровкаСуммы..
Содержание : Строка
Сумма : Число 15, 2
СуммаСНДС : Число 14, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 14, 2
..Табличная часть \n УдалитьДокументыПоступления..
ДатаПоступления : Дата
Документ : Документ.Приобретение товаров и услуг\rДокумент.Приобретение услуг и прочих активов
СуммаОплаты : Число 15, 2
..Движения..
ПрочиеРасходы : Остатки
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
Закупки : Обороты
НДСЗаписиКнигиПродаж : Обороты
ВыручкаИСебестоимостьПродаж : Обороты
НДСЗаписиКнигиПокупок : Обороты
ЖурналУчетаСчетовФактур : РегистрСведений
}
@enduml
