@startuml ИнвентаризацияОС
'!include templates.wsd
'..\include templates.wsd
class Документ.ИнвентаризацияОС as "Инвентаризация ОС" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ПодразделениеОрганизации : Справочник.Подразделение
ДокументОснованиеВид : Строка
ДокументОснованиеНомер : Строка
ДокументОснованиеДата : Дата
ДатаНачалаИнвентаризации : Дата
ДатаОкончанияИнвентаризации : Дата
ПричинаПроведенияИнвентаризации : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ОС..
ОсновноеСредство : Справочник.Объект эксплуатации
СтоимостьПоДаннымУчета : Число 15, 2
НаличиеПоДаннымУчета : Булево
СтоимостьФактическая : Число 15, 2
НаличиеФактическое : Булево
СчетУчета : Счет бухгалтерского учета
МОЛ : Справочник.Физическое лицо
ИзлишекСумма : Число 15, 2
ИзлишекКоличество : Число 1, 0
НедостачаСумма : Число 15, 2
НедостачаКоличество : Число 1, 0
Действие : Действия на основании инвентаризации ОС
..Табличная часть \n ИнвентаризационнаяКомиссия..
ФизЛицо : Справочник.Физическое лицо
Председатель : Булево
}
@enduml
