@startuml ВнесениеДенежныхСредствВКассуККМ
'!include templates.wsd
'..\include templates.wsd
class Документ.ВнесениеДенежныхСредствВКассуККМ as "Внесение денежных средств в кассу ККМ" <<Документы>>
{
..Реквизиты..
ДокументОснование : Документ.Расходный кассовый ордер
Касса : Справочник.Касса
КассаККМ : Справочник.Кассы ККМ
Кассир : Справочник.Пользователь
Организация : Справочник.Организация
СуммаДокумента : Число 15, 2
Валюта : Справочник.Валюта
Комментарий : Строка
..Движения..
ДвиженияДенежныхСредств : Обороты
СуммыДокументовВВалютеРегл : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДенежныеСредстваНаличные : Остатки
ДенежныеСредстваВПути : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ДенежныеСредстваВКассахККМ : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
}
@enduml
