@startuml ПеремещениеНМАМеждународныйУчет
'!include templates.wsd
'..\include templates.wsd
class Документ.ПеремещениеНМАМеждународныйУчет as "Перемещение НМА (международный учет)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ПодразделениеПолучатель : Справочник.Подразделение
Ответственный : Справочник.Пользователь
Комментарий : Строка
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
..Движения..
НематериальныеАктивыМеждународныйУчет : РегистрСведений
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ФактическиеДанныеБюджетирования : Обороты
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
ВыручкаИСебестоимостьПродаж : Обороты
}
@enduml
