@startuml ОтборРазмещениеТоваров
'!include templates.wsd
'..\include templates.wsd
class Документ.ОтборРазмещениеТоваров as "Отбор (размещение) товаров" <<Документы>>
{
..Реквизиты..
ВидОперации : Виды операций отбора размещения товаров
ЗонаОтгрузки : Справочник.Складская ячейка
ЗонаПриемки : Справочник.Складская ячейка
Исполнитель : Справочник.Пользователь
Комментарий : Строка
Ответственный : Справочник.Пользователь
РабочийУчасток : Справочник.Рабочий участок
Распоряжение : Документ.Расходный ордер на товары\rДокумент.Ордер на перемещение товаров
Склад : Справочник.Склад (складская территория)
Помещение : Справочник.Помещение
Статус : Статусы отборов размещений товаров
ОбъемОтбор : Число 18, 6
ОбъемРазмещение : Число 18, 6
ВесОтбор : Число 15, 3
ВесРазмещение : Число 15, 3
ДатаНачалаВыполнения : Дата
ДатаОкончанияВыполнения : Дата
..Табличная часть \n ТоварыОтбор..
Количество : Число 15, 3
КоличествоОтобрано : Число 15, 3
КоличествоУпаковок : Число 15, 3
КоличествоУпаковокОтобрано : Число 15, 3
Номенклатура : Справочник.Номенклатура
Упаковка : Справочник.Упаковка
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Ячейка : Справочник.Складская ячейка
ОбъемУпаковки : Число 18, 6
ВесУпаковки : Число 18, 6
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
..Табличная часть \n ТоварыРазмещение..
Количество : Число 15, 3
КоличествоРазмещено : Число 15, 3
КоличествоУпаковок : Число 15, 3
КоличествоУпаковокРазмещено : Число 15, 3
Номенклатура : Справочник.Номенклатура
Упаковка : Справочник.Упаковка
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Ячейка : Справочник.Складская ячейка
ОбъемУпаковки : Число 18, 6
ВесУпаковки : Число 18, 6
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
..Движения..
ТоварыКОтбору : Остатки
ТоварыВЯчейках : Остатки
}
@enduml
