@startuml СписаниеИзЭксплуатации
'!include templates.wsd
'..\include templates.wsd
class Документ.СписаниеИзЭксплуатации as "Списание из эксплуатации" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
ПартияТМЦВЭксплуатации : Справочник.Партии ТМЦ в эксплуатации
Количество : Число 15, 3
ФизическоеЛицо : Справочник.Физическое лицо
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
..Движения..
ФактическиеДанныеБюджетирования : Обороты
ТМЦВЭксплуатации : Обороты
}
@enduml
