@startuml ЗаданиеНаПеревозку
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаданиеНаПеревозку as "Задание на перевозку" <<Документы>>
{
..Реквизиты..
ДополнительнаяИнформация : Строка
Статус : Статусы заданий на перевозку
Комментарий : Строка
Ответственный : Справочник.Пользователь
ДатаВремяРейсаПланС : Дата
ДатаВремяРейсаПланПо : Дата
ДатаВремяРейсаФактС : Дата
ДатаВремяРейсаФактПо : Дата
ТранспортноеСредство : Справочник.Транспортное средство\rСправочник.Типы транспортных средств
КурьерЭкспедитор : Справочник.Физическое лицо
Водитель : Справочник.Физическое лицо
Склад : Справочник.Склад (складская территория)
Вес : Число 18, 6
Объем : Число 18, 6
КоличествоПунктов : Число 5, 0
Приоритет : Справочник.Приоритет
Операция : Виды доставки
Перевозчик : Справочник.Партнер
Контрагент : Справочник.Контрагент
УдалитьКонтрагент : Справочник.Контрагент
ЗаданиеВыполняет : Типы исполнителей заданий на перевозку
БанковскийСчетПеревозчика : Справочник.Банковский счет
ВодительФИО : Строка
УдостоверениеНомер : Строка
УдостоверениеСерия : Строка
АвтомобильГосударственныйНомер : Строка
АвтомобильМарка : Строка
ВидПеревозки : Строка
АвтомобильТип : Строка
АвтомобильВместимостьВКубическихМетрах : Число 6, 3
АвтомобильГрузоподъемностьВТоннах : Число 6, 3
ЛицензионнаяКарточкаВид : Строка
ЛицензионнаяКарточкаНомер : Строка
ЛицензионнаяКарточкаРегистрационныйНомер : Строка
ЛицензионнаяКарточкаСерия : Строка
Прицеп : Строка
ГосударственныйНомерПрицепа : Строка
..Табличная часть \n Маршрут..
Адрес : Строка
Зона : Справочник.Зоны доставки
ВремяС : Дата
ВремяПо : Дата
Вес : Число 15, 3
Объем : Число 15, 3
КлючСвязи : Строка
Доставлено : Булево
ДополнительнаяИнформация : Строка
АдресЗначенияПолей : Строка
..Табличная часть \n Распоряжения..
КлючСвязи : Строка
Распоряжение : Документ.Передача давальцу\rДокумент.Приобретение товаров и услуг\rДокумент.Заказ поставщику\r...
Вес : Число 15, 3
Объем : Число 15, 3
Перевозчик : Справочник.Партнер
ПолучательОтправитель : Справочник.Подразделение\rСправочник.Партнер\rСтрока\r...
ВремяС : Дата
ВремяПо : Дата
ДополнительнаяИнформация : Строка
Доставлено : Булево
Склад : Справочник.Склад (складская территория)
ДоставляетсяПолностью : Булево
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
