@startuml ХодатайствоОБронированииГражданПребывающихВЗапасе
'!include templates.wsd
'..\include templates.wsd
class Документ.ХодатайствоОБронированииГражданПребывающихВЗапасе as "Ходатайство о бронировании" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
КраткийСоставДокумента : Строка
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
ФизическоеЛицо : Справочник.Физическое лицо
Подразделение : Справочник.Подразделение
Должность : Справочник.Должность
Звание : Справочник.Воинское звание
Состав : Справочник.Состав военнослужащих
ВУС : Строка
Годность : Годность к военной службе
НаличиеМобпредписания : Булево
НомерКомандыПартии : Строка
ПунктПеречня : Справочник.Должность (профессия) для бронирования
МотивХодатайства : Строка
ДанныеВоинскогоУчета : Строка
ИдентификаторСтрокиФикс : Число 5, 0
..Табличная часть \n ФиксацияИзменений..
ИмяРеквизита : Строка
Путь : Строка
ИдентификаторСтроки : Число 5, 0
}
@enduml
