@startuml УведомлениеОбИмпортеМаркированныхТоваровГИСМ
'!include templates.wsd
'..\include templates.wsd
class Документ.УведомлениеОбИмпортеМаркированныхТоваровГИСМ as "Уведомление об импорте маркированных товаров" <<Документы>>
{
..Реквизиты..
Основание : Документ.Приобретение товаров и услуг
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Количество : Число 12, 0
КлючСвязи : Число 10, 0
НоменклатураКиЗ : Справочник.Номенклатура
ХарактеристикаКиЗ : Справочник.Характеристика номенклатуры
КодТНВЭД : Строка
ВидМеха : Справочник.Вид меха ГИСМ
..Табличная часть \n НомераКиЗ..
КлючСвязи : Число 10, 0
НомерКиЗ : Строка
}
@enduml
