@startuml ОтчетКомитентуОСписании
'!include templates.wsd
'..\include templates.wsd
class Документ.ОтчетКомитентуОСписании as "Отчет комитенту о списании" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
Соглашение : Справочник.Соглашение об условиях закупок
Валюта : Справочник.Валюта
СуммаДокумента : Число 15, 2
Менеджер : Справочник.Пользователь
НалогообложениеНДС : Типы налогообложения НДС
ЦенаВключаетНДС : Булево
ФормаОплаты : Формы оплаты
ДатаПлатежа : Дата
НачалоПериода : Дата
КонецПериода : Дата
Подразделение : Справочник.Подразделение
Комментарий : Строка
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
Договор : Справочник.Договор с контрагентом
КонтактноеЛицо : Справочник.Контактное лицо
ПорядокРасчетов : Детализация расчетов
ВидыЗапасовУказаныВручную : Булево
НаправлениеДеятельности : Справочник.Направление деятельности
ПорядокОплаты : Порядок оплаты
..Табличная часть \n Товары..
НоменклатураПоставщика : Справочник.Номенклатура поставщика
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Цена : Число 15, 2
Сумма : Число 15, 2
СуммаНДС : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаСНДС : Число 15, 2
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
..Табличная часть \n ВидыЗапасов..
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
СуммаСНДС : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
ИдентификаторСтроки : Строка
УдалитьАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n РасшифровкаПлатежа..
Заказ : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Приобретение товаров и услуг\r...
Сумма : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
..Движения..
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
ТоварыКОформлениюОтчетовКомитенту : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
РасчетыСПоставщиками : Остатки
Международный : РегистрБухгалтерии
Закупки : Обороты
РасчетыСПоставщикамиПоДокументам : Остатки
}
@enduml
