@startuml ПодтверждениеЗачисленияЗарплаты
'!include templates.wsd
'..\include templates.wsd
class Документ.ПодтверждениеЗачисленияЗарплаты as "Подтверждение зачисления зарплаты" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ПервичныйДокумент : Документ.Списание безналичных ДС\rДокумент.Ведомость в банк\rДокумент.Ведомость прочих доходов в банк\r...
ЗарплатныйПроект : Справочник.Зарплатный проект
ХешФайла : Строка
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
ФизическоеЛицо : Справочник.Физическое лицо
НомерЛицевогоСчета : Строка
РезультатЗачисленияЗарплаты : Результаты зачисления зарплаты
Сумма : Число 15, 2
КомментарийРезультата : Строка
..Движения..
РасчетыНалогоплательщиковСБюджетомПоНДФЛ : Остатки
ВзаиморасчетыССотрудниками : Остатки
УплатаНДФЛНалоговымиАгентамиКРаспределению : Остатки
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
ЗарплатаКВыплатеАвансом : Остатки
РасчетыНалоговыхАгентовСБюджетомПоНДФЛ : Остатки
СведенияОДоходахНДФЛ : Обороты
ЗарплатаКВыплате : Остатки
ОплатаВедомостейНаВыплатуЗарплаты : РегистрСведений
}
@enduml
