@startuml ПачкаДокументовСЗВ_К
'!include templates.wsd
'..\include templates.wsd
class Документ.ПачкаДокументовСЗВ_К as "Пачка документов СЗВ К" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ТипСведений : Строка
СоставПачки : Виды СЗВ-К
НомерПачки : Число 5, 0
ИмяФайлаДляПФР : Строка
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ДокументПринятВПФР : Булево
ФайлСформирован : Булево
ОкончаниеОтчетногоПериода : Дата
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Физическое лицо
ТерриториальныеУсловияНа31_12_2001 : Справочник.Территориальное условие
УдалитьТерриториальныеУсловияНа31_12_2001 : Справочник.(не используется) Территориальные условия
РайонныйКоэффициентНа31_12_2001 : Число 5, 2
СтраховойНомерПФР : Строка
Фамилия : Строка
Имя : Строка
Отчество : Строка
..Табличная часть \n ЗаписиОСтаже..
Сотрудник : Справочник.Физическое лицо
НомерПериодаТрудовойДеятельности : Число 3, 0
НомерОсновнойЗаписи : Число 2, 0
НомерДополнительнойЗаписи : Число 2, 0
ОрганизацияТрудовойДеятельности : Строка
ВидДеятельности : Справочник.Вид общественно полезной деятельности
УдалитьВидДеятельности : Справочник.(не используется) Виды деятельности (СЗВ-К)
ДатаНачалаПериода : Дата
ДатаОкончанияПериода : Дата
ОсобыеУсловияТруда : Справочник.Особое условие труда для СЗВ-К
УдалитьОсобыеУсловияТруда : Справочник.(не используется) Условия труда (форма СЗВ-К)
КодПозицииСписка : Справочник.Льготная профессия (ПФР)
ОснованиеИсчисляемогоСтажа : Справочник.Основание для исчисления стажа
УдалитьОснованиеИсчисляемогоСтажа : Справочник.(не используется) Основания для исчисления стажа
НулевойПараметрИсчисляемогоСтажа : Число 2, 0
ПервыйПараметрИсчисляемогоСтажа : Число 3, 0
ВторойПараметрИсчисляемогоСтажа : Число 2, 0
ТретийПараметрИсчисляемогоСтажа : Справочник.Доп. сведение для исчисления стажа
УдалитьТретийПараметрИсчисляемогоСтажа : Справочник.(не используется) Доп. сведения для исчисления стажа
ОснованиеВыслугиЛет : Справочник.Основание для досрочной пенсии (СЗВ-К)
УдалитьОснованиеВыслугиЛет : Справочник.(не используется) Основания для досрочной пенсии (СЗВ-К)
ПервыйПараметрВыслугиЛет : Число 4, 0
ВторойПараметрВыслугиЛет : Число 4, 0
ТретийПараметрВыслугиЛет : Число 5, 2
ТерриториальныеУсловия : Справочник.Территориальное условие
УдалитьТерриториальныеУсловия : Справочник.(не используется) Территориальные условия
РайонныйКоэффициент : Число 4, 2
Должность : Строка
..Табличная часть \n СведенияДляОценкиПенсионныхПрав..
Сотрудник : Справочник.Физическое лицо
ВидСтажа : Виды трудового стажа
НомерЗаписи : Число 2, 0
КодСтажа : Справочник.Территориальное условие\rСправочник.Особое условие труда для СЗВ-К\rСправочник.Основание для досрочной пенсии (СЗВ-К)
УдалитьКодСтажа : Справочник.(не используется) Основания для досрочной пенсии (СЗВ-К)\rСправочник.(не используется) Условия труда (форма СЗВ-К)\rСправочник.(не используется) Территориальные условия
Лет : Число 2, 0
Месяцев : Число 2, 0
Дней : Число 2, 0
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
}
@enduml
