@startuml РаспределениеПрочихЗатрат
'!include templates.wsd
'..\include templates.wsd
class Документ.РаспределениеПрочихЗатрат as "Распределение расходов на себестоимость продукции" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Ответственный : Справочник.Пользователь
Комментарий : Строка
ПравилоРаспределенияПоЭтапам : Справочник.Правило распределения расходов
ПравилоРаспределенияПоПодразделениям : Справочник.Правило распределения расходов
ВариантРаспределения : Способы распределения статей расходов
СтатьяКалькуляции : Справочник.Статьи калькуляции
ДоляСтоимостиПоПравилам : Число 15, 2
БазаРаспределенияПоПодразделениям : Типы показателей для распределения статей расходов
БазаРаспределенияПоЭтапам : Типы показателей для распределения статей расходов
НаправлениеРаспределения : Способы распределения статей расходов
ВсегоДолейСтоимости : Число 15, 2
ДоляСтоимостиНаСтатьи : Число 15, 2
НаправлениеДеятельности : Справочник.Направление деятельности
ДоляСтоимостиВручную : Число 15, 2
..Табличная часть \n ПартииПроизводства..
ПартияПроизводства : Документ.Этап производства\rДокумент.Отчет переработчика\rДокумент.Выпуск продукции и выполнение работ\r...
Подразделение : Справочник.Подразделение
Этап : Документ.Этап производства\rДокумент.Производство без заказа
СтатьяКалькуляции : Справочник.Статьи калькуляции
ДоляСтоимости : Число 15, 2
АналитикаУчетаПартийПроизводства : Справочник.Ключ аналитики учета партий производства
..Табличная часть \n Вручную..
ЗаказНаПроизводство : Документ.Заказ на производство\rДокумент.Заказ переработчику
КодСтрокиПродукция : Число 10, 0
Этап : Справочник.Этап ресурсной спецификации
СтатьяКалькуляции : Справочник.Статьи калькуляции
ДоляСтоимости : Число 15, 2
СуммаУпрБезНДС : Число 15, 2
СуммаРегл : Число 15, 2
СуммаПР : Число 15, 2
СуммаВР : Число 15, 2
..Табличная часть \n ПоБазе..
Подразделение : Справочник.Подразделение
СтатьяКалькуляции : Справочник.Статьи калькуляции
ДоляСтоимости : Число 15, 2
УдалитьСуммаУпрБезНДС : Число 15, 2
УдалитьСуммаРегл : Число 15, 2
УдалитьСуммаПР : Число 15, 2
УдалитьСуммаВР : Число 15, 2
..Табличная часть \n ОтборПоПодразделениям..
Подразделение : Справочник.Подразделение
..Табличная часть \n ВыпускиБезРаспоряжения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Серия : Справочник.Серия номенклатуры
Назначение : Справочник.Назначение
ДокументВыпуска : Документ.Выпуск продукции и выполнение работ
КодСтроки : Число 10, 0
СтатьяКалькуляции : Справочник.Статьи калькуляции
КоличествоУпаковок : Число 15, 3
Упаковка : Справочник.Упаковка
Количество : Число 15, 3
ДоляСтоимости : Число 15, 2
..Табличная часть \n Списание..
СтатьяРасходов : Статья расходов\rСтатья актива/пассива
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ДоляСтоимости : Число 15, 2
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
НаправлениеДеятельности : Справочник.Направление деятельности
ИдентификаторСтроки : Строка
..Табличная часть \n ОтборПоМатериалам..
Материал : Справочник.Номенклатура
..Табличная часть \n ОтборПоВидамРабот..
ВидРабот : Справочник.Вид работ сотрудников
..Табличная часть \n ОтборПоГруппамПродукции..
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ПрочиеРасходы : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНМатериалы : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
РасходыПриУСНТовары : Остатки
КнигаУчетаДоходовИРасходов : Обороты
ПрочиеРасходыНезавершенногоПроизводства : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
