@startuml КорректировкаРегистров
'!include templates.wsd
'..\include templates.wsd
class Документ.КорректировкаРегистров as "Корректировка регистров" <<Документы>>
{
..Реквизиты..
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ТаблицаРегистров..
Имя : Строка
..Движения..
ПараметрыАмортизацииОСБухгалтерскийУчет : РегистрСведений
МестонахождениеОСБухгалтерскийУчет : РегистрСведений
РасчетНалогаНаИмущество : РегистрСведений
ПараметрыАмортизацииОСУУ : РегистрСведений
ТоварыКОтгрузке : Остатки
ДенежныеСредстваУПодотчетныхЛиц : Остатки
ОперацииМаршрутовПроизводства : РегистрСведений
ПланРемонтов : РегистрСведений
Ассортимент : РегистрСведений
ЗаказыМатериаловВПроизводство : Остатки
ПервоначальныеСведенияНМАНалоговыйУчет : РегистрСведений
ПорядокУчетаНМА : РегистрСведений
НематериальныеАктивыМеждународныйУчет : РегистрСведений
КонтролируемыеСделкиОрганизаций : Обороты
СчетаБухгалтерскогоУчетаНМА : РегистрСведений
ПрочиеДоходы : Остатки
ТоварныеМестаКОтражениюИзлишковНедостач : Остатки
ТрудозатратыНезавершенногоПроизводства : Остатки
НормативыРаспределенияПлановПродажПоКатегориям : РегистрСведений
ЗаявкиНаВозвратТоваровОтКлиентов : Остатки
ДвиженияСерийТоваров : Обороты
ТоварыУПартнеров : Остатки
ПлановыеМатериальныеЗатраты : Обороты
ДоступностьРабочихЦентров : РегистрСведений
РезервыТоваровОрганизаций : Остатки
ПорядокУчетаНМАУУ : РегистрСведений
ПараметрыАмортизацииОСНалоговыйУчет : РегистрСведений
РасчетыСКлиентами : Остатки
ДвиженияДенежныхСредств : Обороты
ПартииТоваровОрганизаций : Остатки
ИсторияПодарочныхСертификатов : РегистрСведений
ПрочиеРасходы : Остатки
ЗначенияНефинансовыхПоказателей : РегистрСведений
ГрафикОтгрузкиТоваров : Остатки
РасчетРезервовПоСомнительнымДолгам : РегистрСведений
ТоварыКОформлениюИзлишковНедостач : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ЗаказыНаСборку : Остатки
ПлановыеПрочиеЗатраты : Обороты
НаработкиТМЦВЭксплуатации : РегистрСведений
ПланыПродаж : Обороты
ДвиженияНоменклатураДоходыРасходы : Обороты
ВыполненныеРаботыСотрудников : Обороты
ПартииТоваровПереданныеНаКомиссию : Остатки
ПартииПрочихРасходов : Остатки
СобытияОСОрганизаций : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ПараметрыАмортизацииОСБУ : РегистрСведений
ОтражениеДокументовВРеглУчете : РегистрСведений
ДенежныеСредстваБезналичные : Остатки
БлокировкиСкладскихЯчеек : РегистрСведений
ЦеныНоменклатурыПоставщиков : РегистрСведений
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
ОборотыБюджетов : Обороты
ДетализацияПартийТоваровДляНДСиУСН : Остатки
ПервоначальныеСведенияОС : РегистрСведений
ПараметрыЦелевогоФинансированияНМА : РегистрСведений
ЭтапыПроизводства : Обороты
НДСПредъявленный : Остатки
ДвиженияКонтрагентДоходыРасходы : Обороты
СпособыОтраженияРасходовПоАмортизацииОСБухгалтерскийУчет : РегистрСведений
ПервоначальныеСведенияОСБухгалтерскийУчет : РегистрСведений
ТоварыКОформлениюОтчетовКомитенту : Остатки
ДенежныеСредстваНаличные : Остатки
ПланыЗакупок : Обороты
РаспоряженияНаПередачуИзПроизводства : Остатки
РасчетЗемельногоНалога : РегистрСведений
НачислениеАмортизацииНМАСпециальныйКоэффициентНалоговыйУчет : РегистрСведений
ПорядокУчетаОСБУ : РегистрСведений
ДвиженияДенежныеСредстваКонтрагент : Обороты
ПереданнаяВозвратнаяТара : Остатки
ПараметрыЦелевогоФинансированияОС : РегистрСведений
ПодарочныеСертификаты : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНОСиНМА : Остатки
ПервоначальныеСведенияНМА : РегистрСведений
РасходыПриУСНМатериалы : Остатки
РасходыПриУСН : Остатки
РемонтыРабочихЦентров : РегистрСведений
ГрафикиАмортизацииОСБухгалтерскийУчет : РегистрСведений
НаработкиОбъектовЭксплуатации : РегистрСведений
ДенежныеСредстваВПути : Остатки
ФактическиеДанныеБюджетирования : Обороты
ТоварыКОтбору : Остатки
ПродукцияИПолуфабрикатыВПроизводстве : Обороты
СтоимостьНМА : Остатки
ДоступностьВидовРабочихЦентров : Обороты
УслугиДавальцуКОформлению : Остатки
ЛимитыРасходаДенежныхСредств : Обороты
ПериодыАктуальностиОбъектовЭксплуатации : РегистрСведений
ДенежныеСредстваВКассахККМ : Остатки
ЗаказыНаПеремещение : Остатки
ПорядокУчетаНМАБУ : РегистрСведений
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
СостоянияОСОрганизаций : РегистрСведений
ОшибочныеРеквизитыКонтрагентов : РегистрСведений
РегистрацияЗемельныхУчастков : РегистрСведений
ЗаказыКлиентов : Остатки
ОбеспечениеЗаказов : Остатки
СтоимостьТоваров : РегистрСведений
АмортизацияНМА : Остатки
РасчетыСПоставщиками : Остатки
ТоварыПереданныеНаКомиссию : Остатки
РасчетРасходовПоАренде : РегистрСведений
ФинансовыеРезультаты : Обороты
ПланыЗанятостиТрудовыхРесурсов : Обороты
НачислениеАмортизацииОСБухгалтерскийУчет : РегистрСведений
УслугиПереработчиковКОформлению : Остатки
СостоянияНМАОрганизаций : РегистрСведений
ДенежныеСредстваКВыплате : Остатки
Закупки : Обороты
МестонахождениеОС : РегистрСведений
ДвижениеТоваров : Обороты
РасходыПриУСНТовары : Остатки
ПорядокУчетаОСУУ : РегистрСведений
ТоварыПринятые : Остатки
НДСЗаписиКнигиПродаж : Обороты
ОбеспечениеЗаказовРаботами : Остатки
СчетаБухгалтерскогоУчетаОС : РегистрСведений
ПланыПродажПоКатегориям : Обороты
ПараметрыАмортизацииНМАБУ : РегистрСведений
БракВПроизводстве : Остатки
МестоУчетаНМА : РегистрСведений
РегистрацияТранспортныхСредств : РегистрСведений
ОтражениеЗарплатыВФинансовомУчете : Обороты
КвотыАссортимента : РегистрСведений
РасчетыСКлиентамиПоДокументам : Остатки
СтавкиНалогаНаИмуществоПоОтдельнымОсновнымСредствам : РегистрСведений
ПорядокУчетаОС : РегистрСведений
ПланыПроизводства : Обороты
ТоварыОрганизацийКПередаче : Остатки
РасчетыСПоставщикамиПоДокументам : Остатки
ВыработкаНМА : Обороты
АналогиВПроизводстве : РегистрСведений
ДвиженияДенежныеСредстваДоходыРасходы : Обороты
КнигаУчетаДоходовИРасходов : Обороты
АмортизацияОС : Остатки
ПланыСборкиРазборки : Обороты
НачислениеАмортизацииОССпециальныйКоэффициентНалоговыйУчет : РегистрСведений
ЗаказыМатериаловСУчетомКорректировок : Обороты
ПланыОплатПоставщикам : Обороты
ЗаказыНаПроизводствоТрудозатраты : Остатки
ПланыЗанятостиВидовРабочихЦентров : Обороты
ТоварыПереданныеПереработчику : Остатки
ТоварыКОформлениюЗаявленийОВвозе : Остатки
ПервоначальныеСведенияНМАБухгалтерскийУчет : РегистрСведений
ПланыПотребленияКомплектующих : Обороты
МатериалыИРаботыВПроизводстве : Остатки
СпособыОтраженияРасходовПоИмущественнымНалогам : РегистрСведений
РасчетТранспортногоНалога : РегистрСведений
ВыручкаИСебестоимостьПродаж : Обороты
ДвиженияКонтрагентКонтрагент : Обороты
ДенежныеДокументы : Остатки
ЗаказыНаПроизводствоСпецификации : Остатки
РасчетыПоДоговорамКредитовИДепозитов : Остатки
СвободныеОстатки : Остатки
ТоварыКОформлениюТаможенныхДеклараций : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
ТрудозатратыКОформлению : Остатки
ОсновныеСредстваМеждународныйУчет : РегистрСведений
ПлановыеТрудозатраты : Обороты
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
СостоянияРабочихЦентров : Обороты
ПотребностьВМатериалахВПроизводстве : Обороты
ТМЦВЭксплуатации : Обороты
ПланыОплатКлиентов : Обороты
ПереработкаПоГрафикуПроизводства : Остатки
ПринятаяВозвратнаяТара : Остатки
НДССостояниеРеализации0 : РегистрСведений
БонусныеБаллы : Остатки
ЖурналУчетаСчетовФактур : РегистрСведений
ПервоначальныеСведенияОСНалоговыйУчет : РегистрСведений
ЦеныНоменклатуры : РегистрСведений
ПараметрыАмортизацииНМАУУ : РегистрСведений
ГрафикПоступленияТоваров : Остатки
РаспоряженияНаСписаниеПоНормативам : Остатки
ТоварыВЯчейках : Остатки
ПланыПотребленияМатериалов : Обороты
ПрочиеРасходыНезавершенногоПроизводства : Остатки
ЗаказыПоставщикам : Остатки
СтоимостьОС : Остатки
ПартииПроизводственныхЗатрат : Остатки
НачислениеАмортизацииОСНалоговыйУчет : РегистрСведений
РасчетыПоЭквайрингу : Остатки
ВыпускПродукции : Обороты
ТоварыПолученныеОтПереработчика : Остатки
ПартииНезавершенногоПроизводства : Остатки
ТоварыКПоступлению : Остатки
ЗаказыНаВнутреннееПотребление : Остатки
СпособыОтраженияРасходовПоАмортизацииНМАБухгалтерскийУчет : РегистрСведений
УслугиКОформлениюОтчетовПринципалу : Остатки
РаспоряженияНаВыпускПродукции : Остатки
НДСЗаписиРаздела7Декларации : Обороты
ПартииЗатратНаВыпуск : Остатки
}
@enduml
