@startuml СведенияОЗастрахованныхЛицахСЗВ_М
'!include templates.wsd
'..\include templates.wsd
class Документ.СведенияОЗастрахованныхЛицахСЗВ_М as "Сведения о застрахованных лицах, СЗВ-М" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ОтчетныйПериод : Дата
ТипФормы : ТипыСведенийСЗВ-М
ДокументПринятВПФР : Булево
ИмяФайлаДляПФР : Строка
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ФайлСформирован : Булево
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
ОкончаниеОтчетногоПериода : Дата
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Физическое лицо
Фамилия : Строка
Имя : Строка
Отчество : Строка
ИНН : Строка
СтраховойНомерПФР : Строка
}
@enduml
