@startuml ВводНачальныхОстатковОтпусков
'!include templates.wsd
'..\include templates.wsd
class Документ.ВводНачальныхОстатковОтпусков as "Ввод остатков отпусков" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
Ответственный : Справочник.Пользователь
Комментарий : Строка
ДатаОстатков : Дата
..Табличная часть \n ЕжегодныеОтпуска..
ВидЕжегодногоОтпуска : Справочник.Вид отпуска
Действие : Действия с ежегодными отпусками
КоличествоДнейВГод : Число 2, 0
ОстатокНаДатуОстатков : Число 5, 2
УдалитьРабочийГодНачало : Дата
УдалитьРабочийГодОкончание : Дата
..Табличная часть \n ОстаткиОтпусковПоРабочимГодам..
ВидЕжегодногоОтпуска : Справочник.Вид отпуска
РабочийГодНачало : Дата
РабочийГодОкончание : Дата
Остаток : Число 5, 2
..Движения..
ПоложенныеВидыЕжегодныхОтпусков : РегистрСведений
НачальныеОстаткиОтпусков : РегистрСведений
}
@enduml
