@startuml ЧекЕГАИС
'!include templates.wsd
'..\include templates.wsd
class Документ.ЧекЕГАИС as "Чек ЕГАИС" <<Документы>>
{
..Реквизиты..
ОрганизацияЕГАИС : Справочник.Организация ЕГАИС
УдалитьАдресЧекаЕГАИС : Строка
УдалитьПодписьЧекаЕГАИС : Строка
ДокументОснование : Документ.Внутреннее потребление товаров\rДокумент.Реализация товаров и услуг\rДокумент.Пересортица товаров\r...
Ответственный : Справочник.Пользователь
Комментарий : Строка
УдалитьСтатусОбработки : Статусы информирования ЕГАИС
НомерСмены : Число 10, 0
НомерЧекаККМ : Число 8, 0
ВидОперации : Виды операций чека ЕГАИС
СерийныйНомерККМ : Строка
..Табличная часть \n Товары..
ИдентификаторСтроки : Строка
АлкогольнаяПродукция : Справочник.Алкогольная продукция ЕГАИС
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Цена : Число 15, 2
Сумма : Число 15, 2
Штрихкод : Строка
..Табличная часть \n АкцизныеМарки..
КодАкцизнойМарки : Строка
ИдентификаторСтроки : Строка
}
@enduml
