@startuml ПриходныйКассовыйОрдер
'!include templates.wsd
'..\include templates.wsd
class Документ.ПриходныйКассовыйОрдер as "Приходный кассовый ордер" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Касса : Справочник.Касса
СуммаДокумента : Число 15, 2
ХозяйственнаяОперация : Хозяйственные операции
ПринятоОт : Строка
Основание : Строка
Приложение : Строка
Контрагент : Справочник.Контрагент
ПодотчетноеЛицо : Справочник.Физическое лицо
БанковскийСчет : Справочник.Банковский счет организации
Валюта : Справочник.Валюта
Кассир : Справочник.Пользователь
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
РаспоряжениеНаПеремещениеДенежныхСредств : Документ.Распоряжение
ВТомЧислеНДС : Строка
ДокументОснование : Документ.Расходный кассовый ордер\rДокумент.Отчет давальцу\rДокумент.Возврат товаров поставщику\r...
КассаККМ : Справочник.Кассы ККМ
КассаОтправитель : Справочник.Кассы ККМ\rСправочник.Касса
Комментарий : Строка
ВалютаКонвертации : Справочник.Валюта
КурсКонвертации : Число 10, 4
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
ДоверенностьВыданная : Документ.Доверенность
СуммаКонвертации : Число 15, 2
Подразделение : Справочник.Подразделение
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
НаправлениеДеятельности : Справочник.Направление деятельности
Договор : Справочник.Договор между организациями\rСправочник.Договор с контрагентом
УдалитьНомерЧекаККМ : Число 8, 0
УдалитьВариантОтправкиЭлектронногоЧека : Варианты отправки электронного чека покупателю
УдалитьКонтактныеДанныеЭлектронногоЧека : Строка
..Табличная часть \n РасшифровкаПлатежа..
Партнер : Справочник.Партнер
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
ОснованиеПлатежа : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\rДокумент.Таможенная декларация на импорт\r...
Заказ : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
Сумма : Число 15, 2
ВалютаВзаиморасчетов : Справочник.Валюта
СуммаВзаиморасчетов : Число 15, 2
СтатьяДоходов : Статья расходов\rСтатья актива/пассива\rСтатьи доходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Подразделение : Справочник.Подразделение
ДоговорКредитаДепозита : Справочник.Договор кредита (депозита)
ИдентификаторСтроки : Строка
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
ДоговорЗаймаСотруднику : Документ.Договор займа сотруднику
ТипСуммыКредитаДепозита : Типы сумм графика кредитов и депозитов
Организация : Справочник.Организация
НаправлениеДеятельности : Справочник.Направление деятельности
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ДенежныеСредстваУПодотчетныхЛиц : Остатки
РасчетыНалогоплательщиковСБюджетомПоНДФЛ : Остатки
ПрочиеДоходы : Остатки
РасчетыСКлиентами : Остатки
ДвиженияДенежныхСредств : Обороты
ВзаиморасчетыССотрудниками : Остатки
ПрочиеРасходы : Остатки
НачисленияУдержанияПоСотрудникам : Обороты
СуммыДокументовВВалютеРегл : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДенежныеСредстваБезналичные : Остатки
ДенежныеСредстваНаличные : Остатки
ДвиженияДенежныеСредстваКонтрагент : Обороты
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
ДенежныеСредстваВПути : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ДенежныеСредстваВКассахККМ : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
РасчетыСПоставщиками : Остатки
Международный : РегистрБухгалтерии
ДенежныеСредстваКВыплате : Остатки
РасчетыСКлиентамиПоДокументам : Остатки
РасчетыСПоставщикамиПоДокументам : Остатки
ДвиженияДенежныеСредстваДоходыРасходы : Обороты
КнигаУчетаДоходовИРасходов : Обороты
ДвиженияКонтрагентКонтрагент : Обороты
РасчетыПоДоговорамКредитовИДепозитов : Остатки
СведенияОДоходахНДФЛ : Обороты
БухучетНачисленияУдержанияПоСотрудникам : Обороты
ЗарплатаКВыплате : Остатки
ВзаиморасчетыПоЗаймамСотрудникам : Остатки
АвансовыеПлатежиИностранцевПоНДФЛ : Остатки
}
@enduml
