@startuml УведомлениеОСпецрежимахНалогообложения
'!include templates.wsd
'..\include templates.wsd
class Документ.УведомлениеОСпецрежимахНалогообложения as "Уведомление о спецрежимах налогообложения" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ВидУведомления : Виды уведомлений о спецрежимах налогообложения
ДанныеУведомления : Хранилище значения
РегистрацияВИФНС : Справочник.Регистрация в налоговом органе
ПодписантПризнак : Строка
ПодписантФамилия : Строка
ПодписантИмя : Строка
ПодписантОтчество : Строка
ПодписантДокумент : Строка
ДатаПодписи : Дата
ПодписантТелефон : Строка
ИмяОтчета : Строка
ИмяФормы : Строка
}
@enduml
