@startuml ОтпускБезСохраненияОплатыСписком
'!include templates.wsd
'..\include templates.wsd
class Документ.ОтпускБезСохраненияОплатыСписком as "Отпуск без сохранения оплаты списком" <<Документы>>
{
..Реквизиты..
ПериодРегистрации : Дата
Организация : Справочник.Организация
ВидОтпуска : Справочник.Вид отпуска
ВидРасчета : Начисление
ДатаОкончания : Дата
Основание : Строка
ИсправленныйДокумент : Документ.Отпуск без сохранения оплаты списком
КраткийСоставДокумента : Строка
ПерерасчетВыполнен : Булево
Рассчитал : Справочник.Пользователь
ПредставлениеПериода : Строка
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ДатаНачала : Дата
ДатаОкончания : Дата
Основание : Строка
..Табличная часть \n Начисления..
Начисление : Начисление
ДатаНачала : Дата
ДатаОкончания : Дата
Результат : Число 13, 2
Подразделение : Справочник.Подразделение
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
Сотрудник : Справочник.Сотрудник
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ВидУчетаВремени : Справочник.Вид рабочего времени
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
ВремяВЧасах : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ПериодРегистрацииВремени : Дата
СуммаВычета : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
ОплаченоДней : Число 15, 2
ОплаченоЧасов : Число 15, 2
ПериодДействия : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n НачисленияПерерасчет..
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Результат : Число 13, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
Сторно : Булево
СторнируемыйДокумент : Документ.Приз, подарок\rДокумент.Простой сотрудников\rДокумент.Отпуск без сохранения оплаты списком\r...
Сотрудник : Справочник.Сотрудник
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
СуммаВычета : Число 15, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
ФиксСторно : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ПериодРегистрацииВремени : Дата
ВремяВЧасах : Булево
ВидУчетаВремени : Справочник.Вид рабочего времени
ОплаченоДней : Число 15, 2
ОплаченоЧасов : Число 15, 2
РезультатВТомЧислеЗаСчетФБ : Число 15, 2
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ПериодДействия : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n Показатели..
Показатель : Справочник.Показатель
Значение : Число 15, 5
ИдентификаторСтрокиВидаРасчета : Число 7, 0
..Табличная часть \n РаспределениеРезультатовНачислений..
ИдентификаторСтроки : Число 7, 0
Территория : Справочник.Территория
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОблагаетсяЕНВД : Булево
Результат : Число 13, 2
..Табличная часть \n РаспределениеПоТерриториямУсловиямТруда..
ИдентификаторСтроки : Число 7, 0
Территория : Справочник.Территория
УсловияТруда : Справочник.Условия труда
ДоляРаспределения : Число 15, 5
Результат : Число 15, 2
ИдентификаторСтрокиПоказателей : Число 7, 0
СуммаВычета : Число 13, 0
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ДанныеОВремениДляРасчетаСреднегоФСС : РегистрСведений
ВзаиморасчетыССотрудниками : Остатки
НачисленияУдержанияПоСотрудникам : Обороты
ОтработанноеВремяПоСотрудникамКорректировка : Обороты
ДанныеСостоянийСотрудников : РегистрСведений
РаспределениеПоТерриториямУсловиямТруда : РегистрСведений
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
ДанныеОВремениДляРасчетаСреднегоОбщий : Обороты
ФактическиеОтпуска : Обороты
СведенияОДоходахСтраховыеВзносы : Обороты
ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаОбщий : Обороты
ЗначенияПоказателейНачислений : РегистрСведений
ОтработанноеВремяПоСотрудникам : Обороты
Начисления : РегистрРасчета
РеестрОтпусков : РегистрСведений
СведенияОДоходахНДФЛ : Обороты
БухучетНачисленияУдержанияПоСотрудникам : Обороты
ЗарплатаКВыплате : Остатки
ПараметрыПериодовСтажаПФР : РегистрСведений
ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаФСС : Обороты
}
@enduml
