@startuml СборкаТоваров
'!include templates.wsd
'..\include templates.wsd
class Документ.СборкаТоваров as "Сборка товаров" <<Документы>>
{
..Реквизиты..
ЗаказНаСборку : Документ.Заказ на сборку (разборку)
Количество : Число 15, 3
КоличествоУпаковок : Число 15, 3
Комментарий : Строка
Номенклатура : Справочник.Номенклатура
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
Склад : Справочник.Склад (складская территория)
ДатаРаспоряжения : Дата
Сделка : Справочник.Сделка с клиентом
ВариантКомплектации : Справочник.Вариант комплектации
Подразделение : Справочник.Подразделение
СтатусУказанияСерий : Число 2, 0
УдалитьВидЗапасов : Справочник.Вид запасов
УдалитьНомерГТД : Справочник.Номер ГТД
Статус : Статусы сборок товаров
СборкаПодДеятельность : Типы налогообложения НДС
ВидыЗапасовУказаныВручную : Булево
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
НоменклатураОсновногоКомпонента : Справочник.Номенклатура
ХарактеристикаОсновногоКомпонента : Справочник.Характеристика номенклатуры
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
НаправлениеДеятельности : Справочник.Направление деятельности
ХозяйственнаяОперация : Хозяйственные операции
ВариантПриемкиТоваров : Варианты приемки товаров
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ДоляСтоимости : Число 10, 0
КодСтроки : Число 10, 0
СтатусУказанияСерий : Число 2, 0
УдалитьВидЗапасов : Справочник.Вид запасов
УдалитьНомерГТД : Справочник.Номер ГТД
Серия : Справочник.Серия номенклатуры
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ИдентификаторСтроки : Строка
..Табличная часть \n ВидыЗапасовСписание..
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
УдалитьКоличествоКомплекта : Число 15, 3
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
..Табличная часть \n ВидыЗапасовОприходование..
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
..Табличная часть \n Серии..
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
..Движения..
ТоварыКОтгрузке : Остатки
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СебестоимостьТоваров : Остатки
ЗаказыНаСборку : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ТоварыКОформлениюОтчетовКомитенту : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
Международный : РегистрБухгалтерии
ДвижениеТоваров : Обороты
НДСЗаписиКнигиПродаж : Обороты
ТоварыОрганизацийКПередаче : Остатки
СвободныеОстатки : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
ГрафикПоступленияТоваров : Остатки
ТоварыКПоступлению : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
