@startuml РеестрСчетовФактурПоставщика
'!include templates.wsd
'..\include templates.wsd
class Документ.РеестрСчетовФактурПоставщика as "Реестр счетов-фактур поставщика" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Контрагент : Справочник.Контрагент
НалоговыйПериод : Дата
ПредставлениеНалоговогоПериода : Строка
ИдентификаторЗапроса : Строка
..Табличная часть \n СчетаФактуры..
ДатаСчетаФактуры : Дата
НомерСчетаФактуры : Строка
ДатаИсправления : Дата
НомерИсправления : Строка
ДатаКорректировочногоСчетаФактуры : Дата
НомерКорректировочногоСчетаФактуры : Строка
ДатаИсправленияКорректировочногоСчетаФактуры : Дата
НомерИсправленияКорректировочногоСчетаФактуры : Строка
НаАванс : Булево
СуммаДокумента : Число 15, 2
СуммаНДС : Число 15, 2
СуммаДокументаРазницаУвеличение : Число 15, 2
СуммаДокументаРазницаУменьшение : Число 15, 2
СуммаНДСРазницаУвеличение : Число 15, 2
СуммаНДСРазницаУменьшение : Число 15, 2
КодВалюты : Строка
}
@enduml
