@startuml СписаниеНМА
'!include templates.wsd
'..\include templates.wsd
class Документ.СписаниеНМА as "Списание НМА (2.2)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
Ответственный : Справочник.Пользователь
Комментарий : Строка
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ЧастичнаяЛиквидация : Булево
СуммаСписанияБУ : Число 15, 2
СуммаСписанияНУ : Число 15, 2
СуммаСписанияПР : Число 15, 2
СуммаСписанияВР : Число 15, 2
..Табличная часть \n НачисленнаяАмортизация..
ОбъектУчета : Справочник.Нематериальные активы и расходы на НИОКР
Подразделение : Справочник.Подразделение
СуммаБУ : Число 15, 2
СуммаНУ : Число 15, 2
СуммаПР : Число 15, 2
СуммаВР : Число 15, 2
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ПередаватьРасходыВДругуюОрганизацию : Булево
ОрганизацияПолучательРасходов : Справочник.Организация
СчетПередачиРасходов : Счет бухгалтерского учета
ЭтоЦелевыеСредства : Булево
НаправлениеДеятельности : Справочник.Направление деятельности
..Движения..
ПервоначальныеСведенияНМАНалоговыйУчет : РегистрСведений
ПрочиеДоходы : Остатки
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
СостоянияНМАОрганизаций : РегистрСведений
ПервоначальныеСведенияНМАБухгалтерскийУчет : РегистрСведений
ВыручкаИСебестоимостьПродаж : Обороты
}
@enduml
