@startuml УстановкаБлокировокЯчеек
'!include templates.wsd
'..\include templates.wsd
class Документ.УстановкаБлокировокЯчеек as "Установка блокировок ячеек" <<Документы>>
{
..Реквизиты..
Ответственный : Справочник.Пользователь
Комментарий : Строка
Склад : Справочник.Склад (складская территория)
Помещение : Справочник.Помещение
..Табличная часть \n СкладскиеЯчейки..
Ячейка : Справочник.Складская ячейка
ТипБлокировки : Типы блокировок складских ячеек
Отменено : Булево
..Движения..
БлокировкиСкладскихЯчеек : РегистрСведений
}
@enduml
