@startuml ВводОстатковВнеоборотныхАктивов
'!include templates.wsd
'..\include templates.wsd
class Документ.ВводОстатковВнеоборотныхАктивов as "Ввод остатков внеоборотных активов (2.2)" <<Документы>>
{
..Реквизиты..
ТипОперации : Типы операций ввода остатков
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ОС..
АдресМестонахождения : Строка
АмортизационнаяГруппа : Амортизационные группы
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
АналитикаРасходовАмортизации : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаРасходовАмортизационнойПремии : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаРасходовНалог : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ВариантРаздельногоУчетаНДС : Варианты раздельного учета НДС
ВключитьАмортизационнуюПремиюВСоставРасходов : Булево
ГрафикАмортизацииБУ : Справочник.Годовой график амортизации ОС
ГруппаОС : Группы ОС
ДатаМодернизации : Дата
ДатаПринятияКУчету : Дата
ДоговорЛизинга : Справочник.Договор лизинга
ЕстьРезервПереоценки : Булево
ЕстьСобытияМодернизации : Булево
ЗалоговаяСтоимость : Число 15, 2
ИнвентарныйНомер : Строка
КодПоОКОФ : Справочник.Элемент классификатора ОКОФ
Контрагент : Справочник.Организация\rСправочник.Контрагент
КорректировкаСтоимостиАрендованногоИмуществаНУ : Число 15, 2
КоэффициентАмортизацииБУ : Число 4, 2
КоэффициентУскоренияБУ : Число 5, 2
МетодНачисленияАмортизацииБУ : Способы начисления амортизации основных средств
МОЛ : Справочник.Физическое лицо
НазваниеДокументаМодернизации : Строка
НазваниеДокументаПринятияКУчету : Строка
НакопленнаяАмортизацияБУ : Число 15, 2
НакопленнаяАмортизацияБУЦФ : Число 15, 2
НакопленнаяАмортизацияНУ : Число 15, 2
НакопленнаяАмортизацияНУДо2009 : Число 15, 2
НакопленнаяАмортизацияНУЦФ : Число 15, 2
НакопленнаяАмортизацияПР : Число 15, 2
НакопленнаяАмортизацияПРЦФ : Число 15, 2
НалогообложениеНДС : Типы налогообложения НДС
НачислятьАмортизациюБУ : Булево
НачислятьАмортизациюНУ : Булево
НомерДокументаМодернизации : Строка
НомерДокументаПринятияКУчету : Строка
ОбъемНаработкиБУ : Число 10, 0
ОрганизацияПолучательРасходов : Справочник.Организация
ОсновноеСредство : Справочник.Объект эксплуатации
ПервоначальнаяСтоимостьБУ : Число 15, 2
ПервоначальнаяСтоимостьНУ : Число 15, 2
ПервоначальнаяСтоимостьОтличается : Булево
ПервоначальнаяСтоимостьПР : Число 15, 2
ПередаватьРасходыВДругуюОрганизацию : Булево
ПодразделениеАрендатора : Справочник.Подразделение
ПоказательНаработки : Справочник.Показатель наработки
ПорядокУчетаБУ : Порядок погашения стоимости ОС
ПорядокУчетаНУ : Порядок включения стоимости основных средств в состав расходов (НУ)
ПрименениеЦелевогоФинансирования : Булево
РасчетыМеждуОрганизациямиАрендатор : Булево
РезервПереоценкиАмортизации : Число 15, 2
РезервПереоценкиСтоимости : Число 15, 2
СобытиеМодернизации : Справочник.Событие ОС
СобытиеПринятияКУчету : Справочник.Событие ОС
СпециальныйКоэффициентНУ : Число 5, 2
СпособПоступления : Способы поступления активов
СрокИспользованияБУ : Число 4, 0
СрокИспользованияНУ : Число 4, 0
СрокИспользованияНУДо2009 : Число 4, 0
СтатьяДоходов : Статьи доходов
СтатьяРасходовАмортизации : Статья расходов
СтатьяРасходовАмортизационнойПремии : Статья расходов
СтатьяРасходовНалог : Статья расходов
СтоимостьДляВычисленияАмортизации : Число 15, 2
СуммаКапитальныхВложенийВключаемыхВРасходыНУ : Число 15, 2
СчетАмортизации : Счет бухгалтерского учета
СчетАмортизацииЦФ : Счет бухгалтерского учета
СчетПередачиРасходов : Счет бухгалтерского учета
СчетУчета : Счет бухгалтерского учета
СчетУчетаАрендатора : Счет бухгалтерского учета
СчетУчетаЦФ : Счет бухгалтерского учета
ТекущаяСтоимостьБУ : Число 15, 2
ТекущаяСтоимостьБУЦФ : Число 15, 2
ТекущаяСтоимостьНУ : Число 15, 2
ТекущаяСтоимостьНУЦФ : Число 15, 2
ТекущаяСтоимостьПР : Число 15, 2
ТекущаяСтоимостьПРЦФ : Число 15, 2
ШифрПоЕНАОФ : Справочник.Элемент классификатора ЕНАОФ
..Табличная часть \n НМА..
АмортизацияДо2009 : Число 15, 2
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
АналитикаРасходовАмортизации : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ВидОбъектаУчета : Виды объектов учета НМА
ДатаПринятияКУчетуРегл : Дата
ДатаПриобретения : Дата
ЕстьРезервПереоценки : Булево
КоэффициентБУ : Число 3, 2
МетодНачисленияАмортизацииНУ : Методы начисления амортизации
НакопленнаяАмортизацияБУ : Число 15, 2
НакопленнаяАмортизацияБУЦФ : Число 15, 2
НакопленнаяАмортизацияВР : Число 15, 2
НакопленнаяАмортизацияНУ : Число 15, 2
НакопленнаяАмортизацияНУЦФ : Число 15, 2
НакопленнаяАмортизацияПР : Число 15, 2
НакопленнаяАмортизацияПРЦФ : Число 15, 2
НачислятьАмортизациюБУ : Булево
НачислятьАмортизациюНУ : Булево
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
ОбъемПродукцииРаботДляВычисленияАмортизации : Число 10, 0
ОрганизацияПолучательРасходов : Справочник.Организация
ПервоначальнаяСтоимостьБУ : Число 15, 2
ПервоначальнаяСтоимостьНУ : Число 15, 2
ПервоначальнаяСтоимостьОтличается : Булево
ПередаватьРасходыВДругуюОрганизацию : Булево
ПорядокСписанияНИОКРНаРасходыНУ : Порядок списания НИОКР (НУ)
ПрименениеЦелевогоФинансирования : Булево
РезервПереоценкиАмортизации : Число 15, 2
РезервПереоценкиСтоимости : Число 15, 2
РеквизитыДокументаОплаты : Строка
СпециальныйКоэффициентНУ : Число 6, 2
СпособНачисленияАмортизацииБУ : Способы начисления амортизации нематериальных активов
СпособПоступления : Способы поступления активов
СрокПолезногоИспользованияБУ : Число 4, 0
СрокПолезногоИспользованияНУ : Число 4, 0
СтатьяДоходов : Статьи доходов
СтатьяРасходовАмортизации : Статья расходов
СчетАмортизации : Счет бухгалтерского учета
СчетАмортизацииЦФ : Счет бухгалтерского учета
СчетПередачиРасходов : Счет бухгалтерского учета
СчетУчета : Счет бухгалтерского учета
СчетУчетаЦФ : Счет бухгалтерского учета
ТекущаяСтоимостьБУ : Число 15, 2
ТекущаяСтоимостьБУЦФ : Число 15, 2
ТекущаяСтоимостьВР : Число 15, 2
ТекущаяСтоимостьНУ : Число 15, 2
ТекущаяСтоимостьНУЦФ : Число 15, 2
ТекущаяСтоимостьПР : Число 15, 2
ТекущаяСтоимостьПРЦФ : Число 15, 2
ФактическийСрокИспользованияДо2009 : Число 4, 0
..Табличная часть \n РасчетыПоДоговорамЛизинга..
Контрагент : Справочник.Контрагент
Договор : Справочник.Договор лизинга
ТипЗадолженности : Типы начислений по лизингу
СчетУчета : Счет бухгалтерского учета
Сумма : Число 15, 2
СуммаРегл : Число 15, 2
СальдоДебетовое : Булево
ДокументАванса : Документ.Списание безналичных ДС
..Движения..
ПараметрыАмортизацииОСБухгалтерскийУчет : РегистрСведений
МестонахождениеОСБухгалтерскийУчет : РегистрСведений
ПервоначальныеСведенияНМАНалоговыйУчет : РегистрСведений
СчетаБухгалтерскогоУчетаНМА : РегистрСведений
ПараметрыАмортизацииОСНалоговыйУчет : РегистрСведений
СобытияОСОрганизаций : РегистрСведений
ОтражениеДокументовВРеглУчете : РегистрСведений
ПараметрыЦелевогоФинансированияНМА : РегистрСведений
СпособыОтраженияРасходовПоАмортизацииОСБухгалтерскийУчет : РегистрСведений
ПервоначальныеСведенияОСБухгалтерскийУчет : РегистрСведений
НачислениеАмортизацииНМАСпециальныйКоэффициентНалоговыйУчет : РегистрСведений
ПараметрыЦелевогоФинансированияОС : РегистрСведений
ГрафикиАмортизацииОСБухгалтерскийУчет : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
СостоянияОСОрганизаций : РегистрСведений
Международный : РегистрБухгалтерии
НачислениеАмортизацииОСБухгалтерскийУчет : РегистрСведений
СостоянияНМАОрганизаций : РегистрСведений
СчетаБухгалтерскогоУчетаОС : РегистрСведений
НачислениеАмортизацииОССпециальныйКоэффициентНалоговыйУчет : РегистрСведений
ПервоначальныеСведенияНМАБухгалтерскийУчет : РегистрСведений
СпособыОтраженияРасходовПоИмущественнымНалогам : РегистрСведений
ПервоначальныеСведенияОСНалоговыйУчет : РегистрСведений
НачислениеАмортизацииОСНалоговыйУчет : РегистрСведений
СпособыОтраженияРасходовПоАмортизацииНМАБухгалтерскийУчет : РегистрСведений
}
@enduml
