@startuml ПервичныйДокумент
'!include templates.wsd
'..\include templates.wsd
class Документ.ПервичныйДокумент as "Первичный документ" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Контрагент : Справочник.Организация\rСправочник.Контрагент
Договор : Справочник.Договор между организациями\rСправочник.Договор с контрагентом
Валюта : Справочник.Валюта
СуммаДокумента : Число 15, 2
НомерВходящегоДокумента : Строка
ДатаВходящегоДокумента : Дата
Комментарий : Строка
Партнер : Справочник.Партнер
ТипПервичногоДокумента : Типы первичных документов
СуммаРегл : Число 15, 2
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
НаправлениеДеятельности : Справочник.Направление деятельности
Подразделение : Справочник.Подразделение
ПорядокРасчетов : Детализация расчетов
..Движения..
СебестоимостьТоваров : Остатки
ДетализацияПартийТоваровДляНДСиУСН : Остатки
}
@enduml
