@startuml ВыпускПродукции
'!include templates.wsd
'..\include templates.wsd
class Документ.ВыпускПродукции as "Выпуск продукции и выполнение работ" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Распоряжение : Документ.Маршрутный лист производства
Подразделение : Справочник.Подразделение
Склад : Справочник.Склад (складская территория)
ВидЦены : Справочник.Вид цены
Ответственный : Справочник.Пользователь
Комментарий : Строка
ВыпускПоРаспоряжениям : Булево
ВыпускПодДеятельность : Типы налогообложения НДС
НаправлениеВыпуска : Хозяйственные операции
Валюта : Справочник.Валюта
МаксимальныйКодСтроки : Число 10, 0
НаправлениеДеятельности : Справочник.Направление деятельности
ЕстьМаркируемаяПродукцияГИСМ : Булево
ВариантПриемкиТоваров : Варианты приемки товаров
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Спецификация : Справочник.Ресурсная спецификация
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Цена : Число 15, 2
Сумма : Число 15, 2
Распоряжение : Документ.Маршрутный лист производства
ТипСтоимости : Типы стоимости выходных изделий
СтатусУказанияСерий : Число 2, 0
УдалитьАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
ВидЗапасов : Справочник.Вид запасов
КодСтроки : Число 10, 0
ИдентификаторСтроки : Строка
Серия : Справочник.Серия номенклатуры
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
Назначение : Справочник.Назначение
СтатьяРасходов : Статья расходов\rСтатья актива/пассива
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
СписатьНаРасходы : Булево
Склад : Справочник.Склад (складская территория)
Подразделение : Справочник.Подразделение
Калькуляция : Документ.Плановая калькуляция
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
ПередатьДавальцу : Булево
..Табличная часть \n Серии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Склад : Справочник.Склад (складская территория)
Подразделение : Справочник.Подразделение
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ТрудозатратыНезавершенногоПроизводства : Остатки
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНМатериалы : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
УслугиДавальцуКОформлению : Остатки
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
Международный : РегистрБухгалтерии
ДвижениеТоваров : Обороты
РасходыПриУСНТовары : Остатки
НДСЗаписиКнигиПродаж : Обороты
ОбеспечениеЗаказовРаботами : Остатки
КнигаУчетаДоходовИРасходов : Обороты
МатериалыИРаботыВПроизводстве : Остатки
СвободныеОстатки : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
ГрафикПоступленияТоваров : Остатки
РаспоряженияНаСписаниеПоНормативам : Остатки
ПрочиеРасходыНезавершенногоПроизводства : Остатки
ПартииПроизводственныхЗатрат : Остатки
ВыпускПродукции : Обороты
ПартииНезавершенногоПроизводства : Остатки
ТоварыКПоступлению : Остатки
РаспоряженияНаВыпускПродукции : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
