@startuml ВыработкаСотрудников
'!include templates.wsd
'..\include templates.wsd
class Документ.ВыработкаСотрудников as "Выработка сотрудников" <<Документы>>
{
..Реквизиты..
Автораспределение : Булево
Бригада : Справочник.Бригады
Валюта : Справочник.Валюта
ВидНаряда : Виды бригадных нарядов
Комментарий : Строка
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
ИспользоватьКТУ : Булево
ИспользоватьТарифныеСтавки : Булево
ИспользоватьОтработанноеВремя : Булево
СуммаДокумента : Число 15, 2
Ответственный : Справочник.Пользователь
Подразделение : Справочник.Подразделение
УдалитьПоРаспоряжениям : Булево
УдалитьКТУОбщий : Число 15, 3
УдалитьРаспоряжение : Документ.Этап производства\rСтрока\rДокумент.Производство без заказа\r...
Исполнители : Строка
..Табличная часть \n ВидыРабот..
Работник : Справочник.Физическое лицо
ВидРабот : Справочник.Вид работ сотрудников
Распоряжение : Документ.Этап производства\rДокумент.Производство без заказа\rДокумент.Маршрутный лист производства\r...
СтатьяКалькуляции : Справочник.Статьи калькуляции
Количество : Число 15, 3
Сумма : Число 15, 2
Расценка : Число 15, 2
УдалитьКлючСтроки : Уникальный идентификатор
КодСтрокиРаспоряжения : Число 10, 0
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
СпособОтраженияЗарплаты : Справочник.Способ отражения зарплаты
КвалификацияИсполнителя : Справочник.Квалификационный разряд (категория)
..Табличная часть \n Работники..
Работник : Справочник.Физическое лицо
КТУ : Число 5, 2
Сумма : Число 15, 2
УдалитьКлючСтроки : Уникальный идентификатор
УдалитьКоличество : Число 15, 3
ТарифнаяСтавка : Число 15, 2
ОтработаноЧасов : Число 15, 2
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ТрудозатратыНезавершенногоПроизводства : Остатки
ФактическиеДанныеБюджетирования : Обороты
ЗначенияОперативныхПоказателейРасчетаЗарплатыСотрудников : Обороты
ТрудозатратыКОформлению : Остатки
}
@enduml
