@startuml ЗаявкаНаЗакрытиеЛицевыхСчетовСотрудников
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаявкаНаЗакрытиеЛицевыхСчетовСотрудников as "Заявка на закрытие лицевых счетов" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ЗарплатныйПроект : Справочник.Зарплатный проект
НомерРеестра : Число 10, 0
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ДатаЗакрытия : Дата
ЛицевойСчет : Строка
ИдентификаторСтрокиФикс : Число 5, 0
..Табличная часть \n ФиксацияИзменений..
ИмяРеквизита : Строка
Путь : Строка
ИдентификаторСтроки : Число 5, 0
}
@enduml
