@startuml ОтражениеЗарплатыВФинансовомУчете
'!include templates.wsd
'..\include templates.wsd
class Документ.ОтражениеЗарплатыВФинансовомУчете as "Отражение зарплаты в финансовом учете" <<Документы>>
{
..Реквизиты..
ПериодРегистрации : Дата
Организация : Справочник.Организация
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
УдалитьДетализацияНачисленийПоФизлицам : Булево
Сводно : Булево
ПроводкиПоРаботникам : Булево
..Табличная часть \n НачисленнаяЗарплатаИВзносы..
Организация : Справочник.Организация
ПодразделениеПредприятия : Справочник.Подразделение
ВидОперации : Виды операций по зарплате
УдалитьСтатьяРасходов : Статья расходов
УдалитьАналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОблагаетсяЕНВД : Булево
Сумма : Число 15, 2
ВзносыВсего : Число 15, 2
ПФРСтраховая : Число 15, 2
ПФРНакопительная : Число 15, 2
ПФРПоСуммарномуТарифу : Число 15, 2
ПФРНаДоплатуЛетчикам : Число 15, 2
ПФРНаДоплатуШахтерам : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботах : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботах : Число 15, 2
ФСС : Число 15, 2
ФФОМС : Число 15, 2
ТФОМС : Число 15, 2
ФССНесчастныеСлучаи : Число 15, 2
ВидНачисленияОплатыТрудаДляНУ : Виды начислений оплаты труда для налогового учета по налогу на прибыль
УдалитьСтатьяРасходовПФР : Статья расходов
УдалитьАналитикаРасходовПФР : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
УдалитьСтатьяРасходовФСС : Статья расходов
УдалитьАналитикаРасходовФСС : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
УдалитьСтатьяРасходовФОМС : Статья расходов
УдалитьАналитикаРасходовФОМС : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ПФРДоПредельнойВеличины : Число 15, 2
ПФРСПревышения : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахБезСпецОценки : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахСпецОценка : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахБезСпецОценки : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахСпецОценка : Число 15, 2
..Табличная часть \n НачисленнаяЗарплатаИВзносыПоФизлицам..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
ПодразделениеПредприятия : Справочник.Подразделение
ВидОперации : Виды операций по зарплате
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОблагаетсяЕНВД : Булево
УдалитьСтатьяРасходов : Статья расходов
УдалитьАналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Сумма : Число 15, 2
ПФРСтраховая : Число 15, 2
ПФРНакопительная : Число 15, 2
ПФРПоСуммарномуТарифу : Число 15, 2
ПФРНаДоплатуЛетчикам : Число 15, 2
ПФРНаДоплатуШахтерам : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботах : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботах : Число 15, 2
ФСС : Число 15, 2
ФФОМС : Число 15, 2
ТФОМС : Число 15, 2
ФССНесчастныеСлучаи : Число 15, 2
ВзносыВсего : Число 15, 2
ВидНачисленияОплатыТрудаДляНУ : Виды начислений оплаты труда для налогового учета по налогу на прибыль
УдалитьСтатьяРасходовПФР : Статья расходов
УдалитьАналитикаРасходовПФР : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
УдалитьСтатьяРасходовФСС : Статья расходов
УдалитьАналитикаРасходовФСС : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
УдалитьСтатьяРасходовФОМС : Статья расходов
УдалитьАналитикаРасходовФОМС : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ПФРДоПредельнойВеличины : Число 15, 2
ПФРСПревышения : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахБезСпецОценки : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахСпецОценка : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахБезСпецОценки : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахСпецОценка : Число 15, 2
..Табличная часть \n НачисленныйНДФЛ..
ФизическоеЛицо : Справочник.Физическое лицо
Организация : Справочник.Организация
ПодразделениеПредприятия : Справочник.Подразделение
ВидОперации : Виды операций по зарплате
СтавкаНДФЛ : Ставки НДФЛ
НДФЛСДивидендов : Булево
Сумма : Число 15, 2
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
ТипНалога : Типы налогов
..Табличная часть \n УдержаннаяЗарплата..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
ПодразделениеПредприятия : Справочник.Подразделение
ВидОперации : Виды операций по зарплате
Контрагент : Справочник.Контрагент
СтатьяАктивовПассивов : Статья актива/пассива
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
Сумма : Число 15, 2
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
ЦельВыдачи : Справочник.Статья движения денежных средств
СтатьяДоходов : Статьи доходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Табличная часть \n НачисленныеПроцентыПоЗаймам..
ФизическоеЛицо : Справочник.Физическое лицо
ПодразделениеПредприятия : Справочник.Подразделение
Сумма : Число 15, 2
СтатьяДоходов : Статьи доходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ДенежныеСредстваУПодотчетныхЛиц : Остатки
ПрочиеДоходы : Остатки
ТрудозатратыНезавершенногоПроизводства : Остатки
УдалитьВыплатаОтпусковЗаСчетРезерва : Обороты
ПрочиеРасходы : Остатки
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
ДетализацияПартийТоваровДляНДСиУСН : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНМатериалы : Остатки
РасходыПриУСН : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
Закупки : Обороты
РасходыПриУСНТовары : Остатки
ОтражениеЗарплатыВФинансовомУчете : Обороты
ДвиженияДенежныеСредстваДоходыРасходы : Обороты
КнигаУчетаДоходовИРасходов : Обороты
}
@enduml
