@startuml УстановкаНормативовПроизводственныхРасходов
'!include templates.wsd
'..\include templates.wsd
class Документ.УстановкаНормативовПроизводственныхРасходов as "Установка нормативов производственных расходов" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ДатаНачалаДействия : Дата
ДатаОкончанияДействия : Дата
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ВеличиныБазРаспределения..
ПравилоРаспределения : Справочник.Правило распределения расходов\rТипы показателей для распределения статей расходов
Величина : Число 15, 3
..Табличная часть \n НормыПостоянныхРасходов..
СтатьяКалькуляции : Справочник.Статьи калькуляции
СтатьяРасходов : Статья расходов
Сумма : Число 15, 2
Норматив : Число 10, 2
Кратность : Число 5, 0
РассчитанныйНорматив : Число 18, 5
..Табличная часть \n НормыПеременныхРасходов..
СтатьяКалькуляции : Справочник.Статьи калькуляции
СтатьяРасходов : Статья расходов
Сумма : Число 15, 2
Норматив : Число 10, 2
Кратность : Число 5, 0
РассчитанныйНорматив : Число 18, 5
}
@enduml
