@startuml СписаниеБезналичныхДенежныхСредств
'!include templates.wsd
'..\include templates.wsd
class Документ.СписаниеБезналичныхДенежныхСредств as "Списание безналичных денежных средств" <<Документы>>
{
..Реквизиты..
ДатаВходящегоДокумента : Дата
Контрагент : Справочник.Контрагент
НазначениеПлатежа : Строка
ХозяйственнаяОперация : Хозяйственные операции
НомерВходящегоДокумента : Строка
Организация : Справочник.Организация
ОчередностьПлатежа : Число 1, 0
БанковскийСчетПолучатель : Справочник.Банковский счет организации
КассаПолучатель : Справочник.Касса
ПодотчетноеЛицо : Справочник.Физическое лицо
ЗаявкаНаРасходованиеДенежныхСредств : Документ.Заявка на расходование ДС
РаспоряжениеНаПеремещениеДенежныхСредств : Документ.Распоряжение
СуммаДокумента : Число 15, 2
Валюта : Справочник.Валюта
БанковскийСчетКонтрагента : Справочник.Банковский счет
БанковскийСчет : Справочник.Банковский счет организации
ПеречислениеВБюджет : Булево
ВидПеречисленияВБюджет : Виды перечислений в бюджет
СтатусСоставителя : Строка
ПоказательТипа : Строка
КодБК : Строка
КодОКАТО : Строка
ПоказательОснования : Строка
ПоказательПериода : Строка
ПоказательНомера : Строка
ПоказательДаты : Строка
Комментарий : Строка
НеКонтролироватьЗаполнениеЗаявки : Булево
ВидПлатежа : Строка
ТипПлатежногоДокумента : Типы платежных документов
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
ВалютаКонвертации : Справочник.Валюта
КурсКонвертации : Число 10, 4
СуммаПослеКонвертации : Число 15, 2
Подразделение : Справочник.Подразделение
НомерВедомостиНаВыплатуЗарплаты : Строка
ДатаВедомостиНаВыплатуЗарплаты : Дата
ОплатаПоЗаявкам : Булево
ИдентификаторПлатежа : Строка
ПроводкиПоРаботникам : Булево
ДокументОснование : Документ.Приобретение товаров и услуг\rДокумент.Заказ поставщику\rДокумент.Распоряжение\r...
ПроведеноБанком : Булево
ДатаПроведенияБанком : Дата
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
ДатаВыгрузки : Дата
ДатаЗагрузки : Дата
ОшибкиЗагрузки : Строка
ФорматированноеНазначениеПлатежа : Строка
ДанныеВыписки : Строка
ИмяКонтрагента : Строка
ДатаАвансовогоОтчета : Дата
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
ПлатежиПо275ФЗ : Булево
ТипПлатежаФЗ275 : Справочник.Типы платежей 275-ФЗ
ДоговорСУчастникомГОЗ : Булево
ДоговорСЗаказчиком : Справочник.Договор между организациями\rСправочник.Договор с контрагентом
СтатьяКалькуляции : Справочник.Статьи калькуляции
ТипНалога : Типы налогов
НДФЛПоВедомостям : Булево
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
НаправлениеДеятельности : Справочник.Направление деятельности
Договор : Справочник.Договор между организациями\rСправочник.Договор с контрагентом
ИННПлательщика : Строка
КПППлательщика : Строка
ТекстПлательщика : Строка
..Табличная часть \n РасшифровкаПлатежа..
Партнер : Справочник.Партнер
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
Заказ : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
Сумма : Число 15, 2
ВалютаВзаиморасчетов : Справочник.Валюта
СуммаВзаиморасчетов : Число 15, 2
СтатьяРасходов : Статья расходов\rСтатья актива/пассива
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Подразделение : Справочник.Подразделение
ПериодВозникновенияРасхода : Дата
ДоговорКредитаДепозита : Справочник.Договор кредита (депозита)
ЗаявкаНаРасходованиеДенежныхСредств : Документ.Заявка на расходование ДС
Комментарий : Строка
ДоговорЛизинга : Справочник.Договор лизинга
ТипПлатежаПоЛизингу : Типы платежей по лизингу
ИдентификаторСтроки : Строка
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
ДоговорЗаймаСотруднику : Документ.Договор займа сотруднику
ТипСуммыКредитаДепозита : Типы сумм графика кредитов и депозитов
Организация : Справочник.Организация
ДоговорСЗаказчиком : Справочник.Договор с контрагентом
СтатьяКалькуляции : Справочник.Статьи калькуляции
НаправлениеДеятельности : Справочник.Направление деятельности
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
Ведомость : Документ.Ведомость через раздатчика\rДокумент.Ведомость на счета\rДокумент.Ведомость в банк\r...
..Табличная часть \n УдалитьВедомостиНаВыплатуЗарплаты..
Ведомость : Документ.Ведомость на счета\rДокумент.Ведомость в банк
Сумма : Число 15, 2
ФизическоеЛицо : Справочник.Физическое лицо
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ДенежныеСредстваУПодотчетныхЛиц : Остатки
РасчетыНалогоплательщиковСБюджетомПоНДФЛ : Остатки
ПрочиеДоходы : Остатки
РасчетыСКлиентами : Остатки
ДвиженияДенежныхСредств : Обороты
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДенежныеСредстваБезналичные : Остатки
УплатаНДФЛНалоговымиАгентамиКРаспределению : Остатки
ДетализацияПартийТоваровДляНДСиУСН : Остатки
РасчетыСФондамиПоСтраховымВзносам : Остатки
ДвиженияДенежныеСредстваКонтрагент : Обороты
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНОСиНМА : Остатки
РасходыПриУСНМатериалы : Остатки
РасходыПриУСН : Остатки
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
ДенежныеСредстваВПути : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ЛимитыРасходаДенежныхСредств : Обороты
ОтражениеДокументовВМеждународномУчете : РегистрСведений
РасчетыСПоставщиками : Остатки
Международный : РегистрБухгалтерии
ДенежныеСредстваКВыплате : Остатки
Закупки : Обороты
РасходыПриУСНТовары : Остатки
РасчетыСКлиентамиПоДокументам : Остатки
РасчетыСПоставщикамиПоДокументам : Остатки
ДвиженияДенежныеСредстваДоходыРасходы : Обороты
КнигаУчетаДоходовИРасходов : Обороты
РасчетыНалоговыхАгентовСБюджетомПоНДФЛ : Остатки
ВыручкаИСебестоимостьПродаж : Обороты
ДвиженияКонтрагентКонтрагент : Обороты
РасчетыПоДоговорамКредитовИДепозитов : Остатки
СведенияОДоходахНДФЛ : Обороты
БухучетНачисленияУдержанияПоСотрудникам : Обороты
ОплатаВедомостейНаВыплатуЗарплаты : РегистрСведений
ВзаиморасчетыПоЗаймамСотрудникам : Остатки
}
@enduml
