@startuml ДоверенностьВыданная
'!include templates.wsd
'..\include templates.wsd
class Документ.ДоверенностьВыданная as "Выданная доверенность" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
БанковскийСчет : Справочник.Банковский счет организации
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
ФизЛицо : Справочник.Физическое лицо
Должность : Строка
Комментарий : Строка
ДокументОснование : Документ.Отчет комиссионера (агента) о продажах\rДокумент.Отчет давальцу\rДокумент.Заказ поставщику\r...
Ответственный : Справочник.Пользователь
СрокДействия : Число 10, 0
ДатаОкончанияДействия : Дата
ПоДокументу : Строка
Статус : Статусы доверенностей
ВидДокументаФизЛица : Справочник.Вид документа физических лиц
СерияДокументаФизЛица : Строка
НомерДокументаФизЛица : Строка
КемВыданДокументФизлица : Строка
ДатаВыдачиДокументаФизЛица : Дата
ПредставлениеДокументаФизЛица : Строка
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
СуммаДокумента : Число 15, 2
Валюта : Справочник.Валюта
СуммаОплатПоДокументу : Число 15, 2
ТипДоверенности : Типы выданных доверенностей
..Табличная часть \n Товары..
НоменклатураПоставщика : Справочник.Номенклатура поставщика
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
..Табличная часть \n МатериальныеЦенности..
МатериальнаяЦенность : Строка
Количество : Число 15, 3
ЕдиницаИзмерения : Справочник.Упаковка
}
@enduml
