@startuml АктСписанияЕГАИС
'!include templates.wsd
'..\include templates.wsd
class Документ.АктСписанияЕГАИС as "Акт списания ЕГАИС" <<Документы>>
{
..Реквизиты..
ВидДокумента : Виды документов ЕГАИС
ОрганизацияЕГАИС : Справочник.Организация ЕГАИС
Идентификатор : Строка
ИдентификаторЕГАИС : Строка
ПричинаСписания : Причины списаний ЕГАИС
УдалитьСтатусОбработки : Статусы обработки акта списания ЕГАИС
ДатаРегистрацииДвижений : Дата
ДокументОснование : Документ.Внутреннее потребление товаров\rДокумент.Списание недостач товаров\rДокумент.Пересортица товаров\r...
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Товары..
АлкогольнаяПродукция : Справочник.Алкогольная продукция ЕГАИС
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Справка2 : Справочник.Справка к ТТН по форме 2
ИдентификаторСтроки : Строка
..Табличная часть \n АкцизныеМарки..
КодАкцизнойМарки : Строка
ИдентификаторСтроки : Строка
..Движения..
ОстаткиАлкогольнойПродукцииЕГАИС : Остатки
}
@enduml
