@startuml ИзменениеУсловийОплатыОтпускаПоУходуЗаРебенком
'!include templates.wsd
'..\include templates.wsd
class Документ.ИзменениеУсловийОплатыОтпускаПоУходуЗаРебенком as "Изменение условий оплаты отпуска по уходу за ребенком" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Сотрудник : Справочник.Физическое лицо
ОсновнойСотрудник : Справочник.Сотрудник
ДатаИзменения : Дата
Действие : Действия с начислениями и удержаниями
ДатаОкончанияПособияДоПолутораЛет : Дата
ДатаОкончанияПособияДоТрехЛет : Дата
КоличествоДетей : Число 2, 0
КоличествоПервыхДетей : Число 1, 0
ДокументОснование : Документ.Отпуск по уходу за ребенком
ВыплачиватьПособиеДоПолутораЛет : Булево
ПособиеДоПолутораЛет : Начисление
ВыплачиватьПособиеДоТрехЛет : Булево
ПособиеДоТрехЛет : Начисление
РазмерПособияДоТрехЛетФиксированнойСуммой : Число 15, 2
ИзменитьНачисления : Булево
ИзменитьАванс : Булево
ИзменитьПрименениеПлановыхНачислений : Булево
НачисленияУтверждены : Булево
ИсправленныйДокумент : Документ.Изменение условий оплаты отпуска по уходу за ребенком
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ИзменитьЛьготы : Булево
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Начисления..
Действие : Действия с начислениями и удержаниями
Начисление : Начисление
РабочееМесто : Справочник.Сотрудник
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Размер : Число 15, 2
..Табличная часть \n Показатели..
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Показатель : Справочник.Показатель
Значение : Число 15, 5
Действие : Действия с начислениями и удержаниями
РабочееМесто : Справочник.Сотрудник
..Табличная часть \n Авансы..
РабочееМесто : Справочник.Сотрудник
СпособРасчетаАванса : Способы расчета аванса
Аванс : Число 15, 2
..Табличная часть \n ПрименениеПлановыхНачислений..
РабочееМесто : Справочник.Сотрудник
Применение : Булево
..Табличная часть \n ПересчетТарифныхСтавок..
РабочееМесто : Справочник.Сотрудник
ПорядокРасчетаСтоимостиЕдиницыВремени : Порядок расчета стоимости часа (дня) оплаты труда сотрудников
СовокупнаяТарифнаяСтавка : Число 15, 5
ВидТарифнойСтавки : Виды тарифных ставок
..Табличная часть \n Льготы..
Действие : Действия с начислениями и удержаниями
Льгота : Начисление
РабочееМесто : Справочник.Сотрудник
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Размер : Число 15, 2
..Движения..
ПорядокРасчетаСтоимостиЕдиницыВремениСотрудников : РегистрСведений
ЗанятыеПозицииШтатногоРасписания : Остатки
УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников : РегистрСведений
УсловияОплатыОтпускаПоУходуЗаРебенком : РегистрСведений
ПрименениеДополнительныхПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
ДанныеСостоянийСотрудников : РегистрСведений
ПрименениеПлановыхНачислений : РегистрСведений
ПлановыеАвансы : РегистрСведений
ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
РеестрОтпусков : РегистрСведений
БухучетПлановыхНачислений : РегистрСведений
ПараметрыПериодовСтажаПФР : РегистрСведений
ПлановыеНачисления : РегистрСведений
}
@enduml
