@startuml ЗаказНаПроизводство2_2
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаказНаПроизводство2_2 as "Заказ на производство" <<Документы>>
{
..Реквизиты..
Приоритет : Справочник.Приоритет
Подразделение : Справочник.Подразделение
Статус : Статусы заказов на производство
Очередь : Число 31, 15
Организация : Справочник.Организация
ЗаказПодДеятельность : Типы налогообложения НДС
Ответственный : Справочник.Пользователь
ДокументОснование : Документ.Заказ на производство\rДокумент.Заказ материалов в производство\rДокумент.Заявка на возврат товаров от клиента\r...
Комментарий : Строка
РазмещениеВыпуска : Способы привязки операций производства
ДатаПотребности : Дата
НачатьНеРанее : Дата
Назначение : Справочник.Назначение
НаправлениеДеятельности : Справочник.Направление деятельности
ХозяйственнаяОперация : Хозяйственные операции
Партнер : Справочник.Партнер
Договор : Справочник.Договор с контрагентом
ВариантОбособления : Варианты обособления полуфабрикатов, материалов и работ в производстве
ДоговорНеОбязателен : Булево
..Табличная часть \n Продукция..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Спецификация : Справочник.Ресурсная спецификация
Склад : Справочник.Склад (складская территория)
Подразделение : Справочник.Подразделение
Назначение : Справочник.Назначение
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ФактическиеДанныеБюджетирования : Обороты
ПродукцияИПолуфабрикатыВПроизводстве : Обороты
ОбеспечениеЗаказов : Остатки
ДвижениеТоваров : Обороты
ОбеспечениеЗаказовРаботами : Остатки
ГрафикПоступленияТоваров : Остатки
}
@enduml
