@startuml ВозвратТоваровОтКлиента
'!include templates.wsd
'..\include templates.wsd
class Документ.ВозвратТоваровОтКлиента as "Возврат товаров от клиента" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Партнер : Справочник.Партнер
Соглашение : Справочник.Соглашение об условиях продаж
Сделка : Справочник.Сделка с клиентом
Валюта : Справочник.Валюта
СуммаДокумента : Число 15, 2
Склад : Справочник.Склад (складская территория)
ЦенаВключаетНДС : Булево
Подразделение : Справочник.Подразделение
Менеджер : Справочник.Пользователь
Комментарий : Строка
ДокументРеализации : Документ.Реализация товаров и услуг\rДокумент.Отчет о розничных продажах
НалогообложениеНДС : Типы налогообложения НДС
ХозяйственнаяОперация : Хозяйственные операции
ЧекККМ : Документ.Чек ККМ
ЗаявкаНаВозвратТоваровОтКлиента : Документ.Заявка на возврат товаров от клиента
НомерВходящегоДокумента : Строка
ДатаВходящегоДокумента : Дата
ВыданыДенежныеСредства : Булево
НомерРасходногоКассовогоОрдера : Строка
ДатаРасходногоКассовогоОрдера : Дата
ВозвратПорчи : Булево
Договор : Справочник.Договор с контрагентом
ВидДокументаПокупателя : Справочник.Вид документа физических лиц
СерияДокументаПокупателя : Строка
НомерДокументаПокупателя : Строка
ДатаВыдачиДокументаПокупателя : Дата
СрокДействияДокументаПокупателя : Дата
КемВыданДокументПокупателя : Строка
КодПодразделенияДокументаПокупателя : Строка
ДатаРожденияПокупателя : Дата
Покупатель : Строка
ПричинаВозврата : Строка
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
Руководитель : Справочник.Лицо с правом подписи
ВозвратПереданнойМногооборотнойТары : Булево
СостояниеЗаполненияМногооборотнойТары : Состояния заполнения многооборотной тары
ВидыЗапасовУказаныВручную : Булево
ПредусмотренЗалогЗаТару : Булево
СпособКомпенсации : Способы компенсации возвратов товаров
ПорядокРасчетов : Детализация расчетов
КонтактноеЛицо : Справочник.Контактное лицо
ПокупательНеПлательщикНДС : Булево
ДовозвратПоВозврату : Документ.Возврат товаров от клиента\rДокумент.Возврат товаров поставщику
НаправлениеДеятельности : Справочник.Направление деятельности
УдалитьАдресЧекаЕГАИС : Строка
УдалитьПодписьЧекаЕГАИС : Строка
Контрагент : Справочник.Контрагент
ПорядокОплаты : Порядок оплаты
ЕстьМаркируемаяПродукцияГИСМ : Булево
УдалитьЕстьАлкогольнаяПродукцияДляРеализацииРозницаЕГАИС : Булево
ВариантПриемкиТоваров : Варианты приемки товаров
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
НоменклатураОприходование : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
ХарактеристикаОприходование : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Цена : Число 15, 2
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
КодСтроки : Число 10, 0
Порча : Булево
СтатусУказанияСерий : Число 2, 0
ДокументРеализации : Документ.Реализация товаров и услуг\rДокумент.Отчет о розничных продажах
Серия : Справочник.Серия номенклатуры
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
НоменклатураНабора : Справочник.Номенклатура
ХарактеристикаНабора : Справочник.Характеристика номенклатуры
АналитикаУчетаНаборов : Справочник.Ключ аналитики учета наборов
Штрихкод : Строка
ИдентификаторСтроки : Строка
НоменклатураЕГАИС : Справочник.Алкогольная продукция ЕГАИС
СпособОпределенияСебестоимости : Способы определения себестоимости
Себестоимость : Число 15, 2
СебестоимостьБезНДС : Число 15, 2
СебестоимостьРегл : Число 15, 2
СебестоимостьПР : Число 15, 2
СебестоимостьВР : Число 15, 2
ВидЦеныСебестоимости : Справочник.Вид цены
ДатаЗаполненияСебестоимостиПоВидуЦены : Дата
Назначение : Справочник.Назначение
..Табличная часть \n ВидыЗапасов..
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
СуммаСНДС : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
УдалитьСкладОтгрузки : Справочник.Склад (складская территория)
НоменклатураОприходование : Справочник.Номенклатура
ХарактеристикаОприходование : Справочник.Характеристика номенклатуры
ВидЗапасовОтгрузки : Справочник.Вид запасов
ДокументРеализации : Документ.Реализация товаров и услуг\rДокумент.Отчет о розничных продажах
ИдентификаторСтроки : Строка
УдалитьАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
Серия : Справочник.Серия номенклатуры
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
АналитикаУчетаНаборов : Справочник.Ключ аналитики учета наборов
Себестоимость : Число 15, 2
СебестоимостьБезНДС : Число 15, 2
СебестоимостьРегл : Число 15, 2
СебестоимостьПР : Число 15, 2
СебестоимостьВР : Число 15, 2
СпособОпределенияСебестоимости : Способы определения себестоимости
АналитикаУчетаНоменклатурыОтгрузки : Справочник.Ключ аналитики учета номенклатуры
..Табличная часть \n РасшифровкаПлатежа..
Заказ : Документ.Возврат товаров от клиента\rДокумент.Отчет комиссионера (агента) о продажах\rДокумент.Отчет давальцу\r...
Сумма : Число 15, 2
ВалютаВзаиморасчетов : Справочник.Валюта
СуммаВзаиморасчетов : Число 15, 2
..Табличная часть \n Серии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
НоменклатураОприходование : Справочник.Номенклатура
ХарактеристикаОприходование : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
..Табличная часть \n НачислениеБонусныхБаллов..
БонуснаяПрограммаЛояльности : Справочник.Бонусные программы лояльности
ДатаНачисления : Дата
ДатаСписания : Дата
СуммаБонусныхБаллов : Число 15, 2
..Табличная часть \n ОплатаБонуснымиБаллами..
БонуснаяПрограммаЛояльности : Справочник.Бонусные программы лояльности
ДатаОплаты : Дата
СуммаБонусныхБаллов : Число 15, 2
..Табличная часть \n АкцизныеМарки..
ИдентификаторСтроки : Строка
КодАкцизнойМарки : Строка
..Движения..
ПрочиеДоходы : Остатки
ЗаявкиНаВозвратТоваровОтКлиентов : Остатки
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
РасчетыСКлиентами : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииТоваровПереданныеНаКомиссию : Остатки
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ТоварыКОформлениюОтчетовКомитенту : Остатки
ПереданнаяВозвратнаяТара : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНМатериалы : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
ТоварыПереданныеНаКомиссию : Остатки
Международный : РегистрБухгалтерии
ДвижениеТоваров : Обороты
РасходыПриУСНТовары : Остатки
НДСЗаписиКнигиПродаж : Обороты
РасчетыСКлиентамиПоДокументам : Остатки
ТоварыОрганизацийКПередаче : Остатки
КнигаУчетаДоходовИРасходов : Обороты
ВыручкаИСебестоимостьПродаж : Обороты
СвободныеОстатки : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
БонусныеБаллы : Остатки
ЖурналУчетаСчетовФактур : РегистрСведений
ТоварыКПоступлению : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
