@startuml ПериодыОплаченныеДоНачалаЭксплуатации
'!include templates.wsd
'..\include templates.wsd
class Документ.ПериодыОплаченныеДоНачалаЭксплуатации as "Периоды, оплаченные до начала эксплуатации" <<Документы>>
{
..Реквизиты..
ПериодРегистрации : Дата
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ВидРасчета : Начисление
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Начисления..
Сотрудник : Справочник.Сотрудник
ДатаНачала : Дата
ДатаОкончания : Дата
ВидПериода : Состояния сотрудника
Подразделение : Справочник.Подразделение
Результат : Число 13, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
ФиксРасчет : Булево
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ОплаченоДней : Число 15, 2
ОплаченоЧасов : Число 15, 2
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ВремяВЧасах : Булево
ПериодРегистрацииВремени : Дата
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ВидУчетаВремени : Справочник.Вид рабочего времени
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
СуммаВычета : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Движения..
ДанныеСостоянийСотрудников : РегистрСведений
Начисления : РегистрРасчета
}
@enduml
