@startuml ИзменениеГрафикаРаботыСписком
'!include templates.wsd
'..\include templates.wsd
class Документ.ИзменениеГрафикаРаботыСписком as "Изменение графика работы списком" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ГрафикРаботы : Справочник.График работы
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ГлавныйБухгалтер : Справочник.Физическое лицо
ИсправленныйДокумент : Документ.Изменение графика работы списком
ДатаИзменения : Дата
ДатаОкончания : Дата
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Сотрудник
ФиксСтрока : Булево
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Табличная часть \n НачисленияСотрудников..
Сотрудник : Справочник.Сотрудник
Начисление : Начисление
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
Размер : Число 15, 2
..Табличная часть \n ПересчетТарифныхСтавок..
Сотрудник : Справочник.Сотрудник
СовокупнаяТарифнаяСтавка : Число 15, 5
ВидТарифнойСтавки : Виды тарифных ставок
..Движения..
УдалитьЗначенияСовокупныхТарифныхСтавокСотрудников : РегистрСведений
ГрафикРаботыСотрудников : РегистрСведений
БухучетПлановыхНачислений : РегистрСведений
ПараметрыПериодовСтажаПФР : РегистрСведений
ПлановыеНачисления : РегистрСведений
}
@enduml
