@startuml ПриходныйОрдерНаТовары
'!include templates.wsd
'..\include templates.wsd
class Документ.ПриходныйОрдерНаТовары as "Приходный ордер на товары" <<Документы>>
{
..Реквизиты..
Склад : Справочник.Склад (складская территория)
Распоряжение : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\rДокумент.Этап производства\r...
Ответственный : Справочник.Пользователь
Исполнитель : Справочник.Пользователь
Комментарий : Строка
Статус : Статусы приходных ордеров
Помещение : Справочник.Помещение
ЗонаПриемки : Справочник.Складская ячейка
РаспоряжениеНаНесколькоСкладов : Булево
ДатаВходящегоДокумента : Дата
НомерВходящегоДокумента : Строка
СкладскаяОперация : Складские операции
СостояниеЗаполненияМногооборотнойТары : Состояния заполнения многооборотной тары
РежимПросмотраПоТоварам : Число 1, 0
ВсегоМест : Число 10, 0
Отправитель : Справочник.Подразделение\rСправочник.Партнер\rСправочник.Физическое лицо\r...
ЗакрыватьГрафикПоступления : Булево
ХозяйственнаяОперация : Хозяйственные операции
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
СтатусУказанияСерий : Число 2, 0
ДокументОтгрузки : Документ.Внутреннее потребление товаров\rДокумент.Акт о расхождениях после перемещения\rДокумент.Этап производства\r...
УпаковочныйЛист : Документ.Упаковочный лист
УпаковочныйЛистРодитель : Документ.Упаковочный лист
Штрихкод : Строка
ЭтоУпаковочныйЛист : Булево
ЭтоСлужебнаяСтрокаПустогоУпаковочногоЛиста : Число 1, 0
Комментарий : Строка
Серия : Справочник.Серия номенклатуры
..Движения..
ДвиженияСерийТоваров : Обороты
ТоварыКОформлениюИзлишковНедостач : Остатки
ТоварыНаСкладах : Остатки
ОбеспечениеЗаказов : Остатки
ДвижениеТоваров : Обороты
СвободныеОстатки : Остатки
ТоварыВЯчейках : Остатки
ТоварыКПоступлению : Остатки
}
@enduml
