@startuml УдалитьЗаявлениеАбонентаСпецоператораСвязи
'!include templates.wsd
'..\include templates.wsd
class Документ.УдалитьЗаявлениеАбонентаСпецоператораСвязи as "(не используется) Заявление абонента оператора электронного документооборота" <<Документы>>
{
..Реквизиты..
ИдентификаторДокументооборота : Строка
ТипЗаявления : (Удалить) Типы заявления абонента оператора электронного документооборота
Статус : (не используется) Статусы заявления абонента оператора электронного документооборота
УчетнаяЗапись : Справочник.(не используется) Учетные записи документооборота
ТипОрганизации : Булево
ИНН : Строка
КПП : Строка
ПолноеНаименование : Строка
КраткоеНаименование : Строка
ПризнакУполномоченногоПредставителя : Булево
ПризнакКрупнейшегоНалогоплательщика : Булево
ПризнакОбособленногоПодразделения : Булево
АдресЮридический : Строка
АдресФактический : Строка
РегНомерПФР : Строка
РегНомерФСС : Строка
ТелефонОсновной : Строка
ТелефонДополнительный : Строка
ЭлектроннаяПочта : Строка
ВладелецЭЦПФамилия : Строка
ВладелецЭЦПИмя : Строка
ВладелецЭЦПОтчество : Строка
ВладелецЭЦПДолжность : Строка
ВладелецЭЦППодразделение : Строка
ВладелецЭЦПВидДокумента : Справочник.Вид документа физических лиц
ВладелецЭЦПНомерДокумента : Строка
ВладелецЭЦПСерияДокумента : Строка
ВладелецЭЦПДатаВыдачиДокумента : Дата
ВладелецЭЦПКемВыданДокумент : Строка
ВладелецЭЦПТип : (не используется) Типы владельцев ЭЦП
ТипКриптопровайдера : (не используется) Типы крипто провайдеров
ПутьКонтейнерЗакрытогоКлюча : Строка
Комментарий : Строка
СтатусКомментарий : Строка
ДатаОтправкиЗаявления : Дата
СпецоператорСвязи : (не используется) Операторы электронного документооборота
Организация : Справочник.Организация
ДатаПолученияОтвета : Дата
Ответственный : Справочник.Пользователь
ДатаСозданияУчетнойЗаписи : Дата
ДополнительныйКодФСС : Строка
НомерОсновнойПоставки1с : Строка
..Табличная часть \n Получатели..
ТипПолучателя : (не используется) Типы контролирующих органов
КодПолучателя : Строка
КПП : Строка
}
@enduml
