@startuml СторнированиеНачислений
'!include templates.wsd
'..\include templates.wsd
class Документ.СторнированиеНачислений as "Сторнирование начислений" <<Документы>>
{
..Реквизиты..
ПериодРегистрации : Дата
Организация : Справочник.Организация
СторнируемыйДокумент : Документ.Приз, подарок\rДокумент.Простой сотрудников\rДокумент.Отпуск без сохранения оплаты списком\r...
Ответственный : Справочник.Пользователь
Комментарий : Строка
ДоначислитьЗарплатуПриНеобходимости : Булево
..Табличная часть \n Сторнировано..
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
ВидЗанятости : Виды занятости
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Результат : Число 13, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
Сторно : Булево
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
ФиксСторно : Булево
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
СуммаВычета : Число 15, 2
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ВидУчетаВремени : Справочник.Вид рабочего времени
ВремяВЧасах : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ПериодРегистрацииВремени : Дата
ОплаченоДней : Число 7, 2
ОплаченоЧасов : Число 7, 2
РезультатВТомЧислеЗаСчетФБ : Число 15, 2
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ПериодДействия : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n ДоначисленияИПерерасчеты..
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Результат : Число 13, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
ФиксСторно : Булево
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
СуммаВычета : Число 15, 2
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ВидУчетаВремени : Справочник.Вид рабочего времени
ВремяВЧасах : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ПериодРегистрацииВремени : Дата
ОплаченоДней : Число 7, 2
ОплаченоЧасов : Число 7, 2
РезультатВТомЧислеЗаСчетФБ : Число 15, 2
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
СторнируемыйДокумент : Документ.Сторнирование начислений\rДокумент.Внутреннее потребление товаров\rДокумент.Назначение планового начисления\r...
ПериодДействия : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
УдалитьСторно : Булево
..Табличная часть \n Показатели..
Показатель : Справочник.Показатель
Значение : Число 15, 5
ИдентификаторСтрокиВидаРасчета : Число 7, 0
..Табличная часть \n РаспределениеРезультатовНачислений..
ИдентификаторСтроки : Число 7, 0
Территория : Справочник.Территория
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОблагаетсяЕНВД : Булево
Результат : Число 13, 2
..Табличная часть \n РаспределениеПоТерриториямУсловиямТруда..
ИдентификаторСтроки : Число 7, 0
Территория : Справочник.Территория
УсловияТруда : Справочник.Условия труда
ДоляРаспределения : Число 15, 5
Результат : Число 15, 2
ИдентификаторСтрокиПоказателей : Число 7, 0
СуммаВычета : Число 13, 0
..Движения..
Удержания : РегистрРасчета
ДанныеОперативногоУчетаРабочегоВремениСотрудников : Обороты
РасчетыНалогоплательщиковСБюджетомПоНДФЛ : Остатки
ДанныеОВремениДляРасчетаСреднегоФСС : РегистрСведений
ВзаиморасчетыССотрудниками : Остатки
ОтработанноеВремяПоСотрудникамАвансом : Обороты
НачисленияУдержанияПоСотрудникам : Обороты
ЗанятыеПозицииШтатногоРасписания : Остатки
ОтработанноеВремяПоСотрудникамКорректировка : Обороты
РасчетыСФондамиПоСтраховымВзносам : Остатки
ПособияПоСоциальномуСтрахованию : Обороты
УдержанияДоПределаПоСотрудникам : Остатки
ДанныеСостоянийСотрудников : РегистрСведений
РаспределениеПоТерриториямУсловиямТруда : РегистрСведений
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
ДанныеОВремениДляРасчетаСреднегоОбщий : Обороты
ПериодыУходаЗаБольнымиРодственниками : Обороты
ВытесняемоеПлановоеВремяСотрудников : Обороты
ФактическиеОтпуска : Обороты
СведенияОДоходахСтраховыеВзносы : Обороты
ИмущественныеВычетыНДФЛ : Остатки
ПособияПоУходуЗаРебенком : Обороты
ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаОбщий : Обороты
ЗначенияПоказателейНачислений : РегистрСведений
ПредоставленныеСтандартныеИСоциальныеВычетыНДФЛ : Обороты
ЗарплатаКВыплатеАвансом : Остатки
УдержанияПоИсполнительнымДокументам : Обороты
ЗначенияПериодическихПоказателейРасчетаЗарплатыСотрудников : РегистрСведений
ОтработанноеВремяПоСотрудникам : Обороты
Начисления : РегистрРасчета
СведенияОДоходахНДФЛ : Обороты
НачисленияУдержанияПоСотрудникамАвансом : Обороты
ДниЧасыОтгулов : Остатки
БухучетНачисленияУдержанияПоСотрудникам : Обороты
ЗарплатаКВыплате : Остатки
ПараметрыПериодовСтажаПФР : РегистрСведений
ПлановыеНачисления : РегистрСведений
ДанныеТабельногоУчетаРабочегоВремениСотрудников : Обороты
ВзаиморасчетыПоЗаймамСотрудникам : Остатки
ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаФСС : Обороты
АвансовыеПлатежиИностранцевПоНДФЛ : Остатки
}
@enduml
