@startuml СправкиНДФЛДляПередачиВНалоговыйОрган
'!include templates.wsd
'..\include templates.wsd
class Документ.СправкиНДФЛДляПередачиВНалоговыйОрган as "2-НДФЛ для передачи в ИФНС" <<Документы>>
{
..Реквизиты..
НалоговыйПериод : Число 4, 0
Организация : Справочник.Организация
СправкуПодписал : Справочник.Физическое лицо
ДолжностьПодписавшегоЛица : Справочник.Должность
Телефон : Строка
ИдентификаторФайла : Строка
ОснованиеДляПредставленияСправок : Основания для представления справок2 НДФЛ
ФайлСформирован : Булево
ДокументПринятВНалоговыйОрган : Булево
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
НалоговыйПериодДата : Дата
КодИФНС : Строка
КраткийСоставДокумента : Строка
СпециальныйДокумент2013года : Булево
НеВключатьДоходыПоЦеннымБумагам : Булево
НомерКорректировки : Число 2, 0
КППОтправки : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
КППРеорганизованнойОрганизации : Строка
ИННРеорганизованнойОрганизации : Строка
НаименованиеРеорганизованнойОрганизации : Строка
ФормаРеорганизации : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Физическое лицо
ИНН : Строка
НомерСправки : Число 8, 0
Ставка : Ставки НДФЛ
Фамилия : Строка
Имя : Строка
Отчество : Строка
Адрес : Строка
ВидДокумента : Справочник.Вид документа физических лиц
СерияДокумента : Строка
НомерДокумента : Строка
Гражданство : Справочник.Страна мира
ДатаРождения : Дата
СтатусНалогоплательщика : Справочник.Статус налогоплательщика
УдалитьСтатусНалогоплательщика : Справочник.(не используется) Статусы налогоплательщиков (НДФЛ)
АдресЗарубежом : Строка
УдалитьДатаУведомления : Дата
УдалитьНомерУведомления : Строка
УдалитьКодНалоговогоОрганаУведомления : Строка
ФиксИНН : Булево
ФиксФамилия : Булево
ФиксИмя : Булево
ФиксОтчество : Булево
ФиксДатаРождения : Булево
ФиксАдрес : Булево
ФиксВидДокумента : Булево
ФиксСерияДокумента : Булево
ФиксНомерДокумента : Булево
ФиксГражданство : Булево
ФиксСтатусНалогоплательщика : Булево
ФиксАдресЗарубежом : Булево
ОбщаяСуммаДоходаПоСтавке13 : Число 15, 2
ОблагаемаяСуммаДоходаПоСтавке13 : Число 15, 2
ИсчисленоПоСтавке13 : Число 12, 0
УдержаноПоСтавке13 : Число 12, 0
ЗадолженностьПоСтавке13 : Число 12, 0
ИзлишнеУдержаноПоСтавке13 : Число 12, 0
ПеречисленоПоСтавке13 : Число 12, 0
ОбщаяСуммаДоходаПоСтавке30 : Число 15, 2
ОблагаемаяСуммаДоходаПоСтавке30 : Число 15, 2
ИсчисленоПоСтавке30 : Число 12, 0
УдержаноПоСтавке30 : Число 12, 0
ЗадолженностьПоСтавке30 : Число 12, 0
ИзлишнеУдержаноПоСтавке30 : Число 12, 0
ПеречисленоПоСтавке30 : Число 12, 0
ОбщаяСуммаДоходаПоСтавке9 : Число 15, 2
ОблагаемаяСуммаДоходаПоСтавке9 : Число 15, 2
ИсчисленоПоСтавке9 : Число 12, 0
УдержаноПоСтавке9 : Число 12, 0
ЗадолженностьПоСтавке9 : Число 12, 0
ИзлишнеУдержаноПоСтавке9 : Число 12, 0
ПеречисленоПоСтавке9 : Число 12, 0
ОбщаяСуммаДоходаПоСтавке15 : Число 15, 2
ОблагаемаяСуммаДоходаПоСтавке15 : Число 15, 2
ИсчисленоПоСтавке15 : Число 12, 0
УдержаноПоСтавке15 : Число 12, 0
ЗадолженностьПоСтавке15 : Число 12, 0
ИзлишнеУдержаноПоСтавке15 : Число 12, 0
ПеречисленоПоСтавке15 : Число 12, 0
ОбщаяСуммаДоходаПоСтавке35 : Число 15, 2
ОблагаемаяСуммаДоходаПоСтавке35 : Число 15, 2
ИсчисленоПоСтавке35 : Число 12, 0
УдержаноПоСтавке35 : Число 12, 0
ЗадолженностьПоСтавке35 : Число 12, 0
ИзлишнеУдержаноПоСтавке35 : Число 12, 0
ПеречисленоПоСтавке35 : Число 12, 0
ФиксНалоги : Булево
ФиксУведомление : Булево
ЗачтеноАвансовыхПлатежейПоСтавке9 : Число 10, 0
ЗачтеноАвансовыхПлатежейПоСтавке13 : Число 10, 0
ЗачтеноАвансовыхПлатежейПоСтавке35 : Число 10, 0
ЗачтеноАвансовыхПлатежейПоСтавке30 : Число 10, 0
ЗачтеноАвансовыхПлатежейПоСтавке15 : Число 10, 0
НомерУведомленияАвансовыеПлатежи : Строка
ДатаУведомленияАвансовыеПлатежи : Дата
КодНалоговогоОрганаУведомленияАвансовыеПлатежи : Строка
ИННвСтранеГражданства : Строка
ЗачтеноАвансовыхПлатежейПоСтавке5 : Число 10, 0
ЗачтеноАвансовыхПлатежейПоСтавке10 : Число 10, 0
ОбщаяСуммаДоходаПоСтавке5 : Число 15, 2
ОблагаемаяСуммаДоходаПоСтавке5 : Число 15, 2
ИсчисленоПоСтавке5 : Число 12, 0
УдержаноПоСтавке5 : Число 12, 0
ЗадолженностьПоСтавке5 : Число 12, 0
ИзлишнеУдержаноПоСтавке5 : Число 12, 0
ПеречисленоПоСтавке5 : Число 12, 0
ОбщаяСуммаДоходаПоСтавке10 : Число 15, 2
ОблагаемаяСуммаДоходаПоСтавке10 : Число 15, 2
ИсчисленоПоСтавке10 : Число 12, 0
УдержаноПоСтавке10 : Число 12, 0
ЗадолженностьПоСтавке10 : Число 12, 0
ИзлишнеУдержаноПоСтавке10 : Число 12, 0
ПеречисленоПоСтавке10 : Число 12, 0
ИсправляемаяСправка : Документ.2-НДФЛ для передачи в ИФНС
..Табличная часть \n СведенияОДоходах..
НомерСправки : Число 8, 0
МесяцНалоговогоПериода : Число 2, 0
Сотрудник : Справочник.Физическое лицо
Ставка : Ставки НДФЛ
КодДохода : Справочник.Вид дохода НДФЛ
СуммаДохода : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
СуммаВычета : Число 15, 2
УдалитьКодДохода : Справочник.(не используется) Виды доходов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
..Табличная часть \n СведенияОВычетах..
НомерСправки : Число 8, 0
Сотрудник : Справочник.Физическое лицо
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
КодВычета : Справочник.Вид вычетов НДФЛ
СуммаВычета : Число 15, 2
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Табличная часть \n УдалитьСуммыНалогов..
НомерСправки : Число 8, 0
Ставка : Ставки НДФЛ
ОбщаяСуммаДохода : Число 15, 2
ОблагаемаяСуммаДохода : Число 15, 2
Исчислено : Число 12, 0
Удержано : Число 12, 0
Перечислено : Число 12, 0
ИзлишнеУдержано : Число 12, 0
Задолженность : Число 12, 0
..Табличная часть \n УведомленияНОоПравеНаВычеты..
ДатаУведомления : Дата
НомерУведомления : Строка
КодНалоговогоОрганаУведомления : Строка
ГруппаВычета : Группы вычетов по НДФЛ
Сотрудник : Справочник.Физическое лицо
..Движения..
РасчетыНалогоплательщиковСБюджетомПоНДФЛ : Остатки
ВзаиморасчетыССотрудниками : Остатки
НачисленияУдержанияПоСотрудникам : Обороты
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
БухучетНачисленияУдержанияПоСотрудникам : Обороты
ЗарплатаКВыплате : Остатки
}
@enduml
