@startuml ОписьПачекСЗВ_6
'!include templates.wsd
'..\include templates.wsd
class Документ.ОписьПачекСЗВ_6 as "Опись пачек СЗВ-6" <<Документы>>
{
..Реквизиты..
ОтчетныйПериод : Дата
Организация : Справочник.Организация
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ДокументПринятВПФР : Булево
НомерПачки : Число 5, 0
ИмяФайлаДляПФР : Строка
ФайлСформирован : Булево
ОкончаниеОтчетногоПериода : Дата
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ПачкиДокументов..
ПачкаДокументов : Документ.Пачка документов СЗВ-6-4\rДокумент.Пачка документов СЗВ-6-1\rДокумент.Реестр СЗВ-6-2
}
@enduml
