@startuml РегистрацияПорядкаНалогообложенияПоНалогуНаИмущество
'!include templates.wsd
'..\include templates.wsd
class Документ.РегистрацияПорядкаНалогообложенияПоНалогуНаИмущество as "Регистрация порядка налогообложения по налогу на имущество" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ВидОбъектаНалогаНаИмущество : Виды объектов налога на имущество
Ответственный : Справочник.Пользователь
Комментарий : Строка
ПостановкаНаУчетВНалоговомОргане : Постановка на учет в налоговом органе
НалоговыйОрган : Справочник.Регистрация в налоговом органе
КодПоОКАТО : Строка
КодПоОКТМО : Строка
ПорядокНалогообложения : Порядок налогообложения имущества
НалоговаяСтавка : Число 3, 2
КодНалоговойЛьготыОсвобождениеОтНалогообложения : Строка
СниженнаяНалоговаяСтавка : Число 3, 2
УдалитьВидИмущества : Удалить виды имущества
НалоговаяБаза : Налоговая база по налогу на имущество
ИспользуетсяТолькоВДеятельностиОблагаемойЕНВД : Булево
ДвижимоеИмуществоПодлежащееНалогообложению : Булево
УказаныСпособыОтражениеРасходов : Булево
КодВидаИмущества : Строка
КБК : Строка
..Табличная часть \n ОС..
ОсновноеСредство : Справочник.Объект эксплуатации
ОбщаяСобственность : Булево
ДоляСтоимостиЧислитель : Число 10, 0
ДоляСтоимостиЗнаменатель : Число 10, 0
КадастровыйНомер : Строка
КадастровыйНомерПомещения : Строка
КадастроваяСтоимость : Число 15, 2
НеоблагаемаяКадастроваяСтоимость : Число 15, 2
ДатаРегистрацииПраваСобственности : Дата
ДатаПрекращенияПраваСобственности : Дата
ОтноситсяКТерриторииСубъектаРФВДоле : Булево
УсловныйНомер : Строка
КадастроваяСтоимостьОпределенаПоДолеПлощади : Булево
ДоляПлощадиЧислитель : Число 10, 0
ДоляПлощадиЗнаменатель : Число 10, 0
ДоляВПравеОбщейСобственностиЗнаменатель : Число 10, 0
ДоляВПравеОбщейСобственностиЧислитель : Число 10, 0
..Табличная часть \n ОтражениеРасходов..
Подразделение : Справочник.Подразделение
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Коэффициент : Число 10, 0
..Движения..
СтавкиНалогаНаИмуществоПоОтдельнымОсновнымСредствам : РегистрСведений
СпособыОтраженияРасходовПоИмущественнымНалогам : РегистрСведений
}
@enduml
