@startuml ЗаявлениеАбонентаСпецоператораСвязи
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗаявлениеАбонентаСпецоператораСвязи as "Заявление абонента оператора электронного документооборота" <<Документы>>
{
..Реквизиты..
АдресФактический : Строка
АдресЮридический : Строка
ВладелецЭЦП : Справочник.Физическое лицо
ВладелецЭЦПВидДокумента : Справочник.Вид документа физических лиц
ВладелецЭЦПГражданство : Справочник.Страна мира
ВладелецЭЦПДатаВыдачиДокумента : Дата
ВладелецЭЦПДатаРождения : Дата
ВладелецЭЦПДолжность : Строка
ВладелецЭЦПИмя : Строка
ВладелецЭЦПКемВыданДокумент : Строка
ВладелецЭЦПКодПодразделения : Строка
ВладелецЭЦПМестоРождения : Строка
ВладелецЭЦПНомерДокумента : Строка
ВладелецЭЦПОтчество : Строка
ВладелецЭЦППодразделение : Строка
ВладелецЭЦППол : Пол физического лица
ВладелецЭЦПСерияДокумента : Строка
ВладелецЭЦПСНИЛС : Строка
ВладелецЭЦПТип : Типы владельцев ЭЦП
ВладелецЭЦПФамилия : Строка
ГенерацияКлючейТолькоДляФСРАР : Булево
ДатаВыдачиЛицензииФСРАР : Дата
ДатаОтправкиЗаявления : Дата
ДатаПолученияОтвета : Дата
ДатаСозданияУчетнойЗаписи : Дата
ДополнительныйКодФСС : Строка
ИдентификаторДокументооборота : Строка
ИдентификаторКлючевогоКонтейнера : Строка
ИдентификаторПроверкиТелефонаДляПаролей : Строка
ИдентификаторПроверкиЭлектроннойПочтыДляПаролей : Строка
ИНН : Строка
КодНалоговогоОрганаЭДО : Строка
КодРегионаФСРАР : Строка
Комментарий : Строка
КПП : Строка
КраткоеНаименование : Строка
НастройкаЗавершена : Булево
НомерЛицензииФСРАР : Строка
НомерОсновнойПоставки1с : Строка
ОГРН : Строка
ОператорЭДО : Строка
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
ПодатьЗаявкуНаПодключениеРПН : Булево
ПодатьЗаявкуНаПодключениеФТС : Булево
ПодатьЗаявкуНаСертификатДляФСРАР : Булево
ПодключитьЭДО : Булево
ПодписатьЭП : Булево
ПолноеНаименование : Строка
ПризнакКрупнейшегоНалогоплательщика : Булево
ПризнакОбособленногоПодразделения : Булево
ПризнакУполномоченногоПредставителя : Булево
ПутьКонтейнерЗакрытогоКлюча : Строка
ПутьКонтейнерЗакрытогоКлючаФСРАР : Строка
РегНомерПФР : Строка
РегНомерФСС : Строка
СерияЛицензииФСРАР : Строка
Сертификат : Хранилище значения
СпецоператорСвязи : Операторы электронного документооборота
Статус : Статусы заявления абонента оператора электронного документооборота
СтатусКомментарий : Строка
ТелефонДополнительный : Строка
ТелефонМобильный : Строка
ТелефонМобильныйДляАвторизации : Строка
ТелефонОсновной : Строка
ТипДекларантаФСРАР : Типы декларантов ФСРАР
ТипЗаявления : Типы заявления абонента оператора электронного документооборота
ТипКриптопровайдера : Типы крипто провайдеров
ТипОрганизации : Булево
ТребуетсяРаспискаВПолученииСертификата : Булево
УдалитьВладелецЭЦППол : Строка
УдалитьВладелецЭЦПСНИЛС : Строка
УдалитьОГРН : Строка
УдалитьТекстОтправленногоЗаявления : Хранилище значения
УчетнаяЗапись : Справочник.Учетные записи документооборота
ЭлектроннаяПодписьВМоделиСервиса : Булево
ЭлектроннаяПочта : Строка
ЭлектроннаяПочтаАутентификация : Строка
РеквизитыСертификата : Хранилище значения
..Табличная часть \n Получатели..
ТипПолучателя : Типы контролирующих органов
КодПолучателя : Строка
КПП : Строка
..Табличная часть \n ИзменившиесяРеквизитыВторичногоЗаявления..
ИзмененныйРеквизит : Измененные параметры подключения к 1С-Отчетности
..Табличная часть \n ЭлектронныеДокументы..
Документ : Строка
Файл : Справочник.Присоединенные файлы (Заявление абонента оператора электронного документооборота)
Размер : Число 10, 0
}
@enduml
