@startuml ПеремещениеТоваров
'!include templates.wsd
'..\include templates.wsd
class Документ.ПеремещениеТоваров as "Перемещение товаров" <<Документы>>
{
..Реквизиты..
БанковскийСчетОрганизации : Справочник.Банковский счет организации
ВидЦены : Справочник.Вид цены
ДатаРаспоряжения : Дата
ЗаказНаПеремещение : Документ.Заказ на перемещение
Комментарий : Строка
Организация : Справочник.Организация
ОрганизацияПолучатель : Справочник.Организация
Ответственный : Справочник.Пользователь
ПеремещениеПоЗаказам : Булево
Подразделение : Справочник.Подразделение
Сделка : Справочник.Сделка с клиентом
СкладОтправитель : Справочник.Склад (складская территория)
СкладПолучатель : Справочник.Склад (складская территория)
Статус : Статусы перемещений товаров
ХозяйственнаяОперация : Хозяйственные операции
СпособДоставки : Способы доставки
ЗонаДоставки : Справочник.Зоны доставки
ПеревозчикПартнер : Справочник.Партнер
АдресДоставки : Строка
АдресДоставкиЗначенияПолей : Строка
АдресДоставкиПеревозчика : Строка
АдресДоставкиПеревозчикаЗначенияПолей : Строка
ДополнительнаяИнформацияПоДоставке : Строка
ВремяДоставкиС : Дата
ВремяДоставкиПо : Дата
ДокументОснование : Документ.Приобретение товаров и услуг\rДокумент.Поступление товаров\rДокумент.Приемка товаров на хранение
Руководитель : Справочник.Лицо с правом подписи
ГлавныйБухгалтер : Справочник.Лицо с правом подписи
ВидыЗапасовУказаныВручную : Булево
ПеремещениеПодДеятельность : Типы налогообложения НДС
СостояниеЗаполненияМногооборотнойТары : Состояния заполнения многооборотной тары
ПеремещениеАктаОРасхождениях : Документ.Перемещение товаров
ОсобыеУсловияПеревозки : Булево
ОсобыеУсловияПеревозкиОписание : Строка
УдалитьЕстьАлкогольнаяПродукцияДляРеализацииЕГАИС : Булево
НаправлениеДеятельности : Справочник.Направление деятельности
ВариантПриемкиТоваров : Варианты приемки товаров
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
КодСтроки : Число 10, 0
СтатусУказанияСерий : Число 2, 0
СтатусУказанияСерийОтправитель : Число 2, 0
СтатусУказанияСерийПолучатель : Число 2, 0
ЗаказНаПеремещение : Документ.Заказ на перемещение
Сделка : Справочник.Сделка с клиентом
Назначение : Справочник.Назначение
НазначениеОтправителя : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ИдентификаторСтроки : Строка
..Табличная часть \n ВидыЗапасов..
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
Сделка : Справочник.Сделка с клиентом
Назначение : Справочник.Назначение
ВидЗапасовПолучателя : Справочник.Вид запасов
Серия : Справочник.Серия номенклатуры
..Табличная часть \n Серии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
НазначениеОтправителя : Справочник.Назначение
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ТоварыКОтгрузке : Остатки
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ТоварыКОформлениюОтчетовКомитенту : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ЗаказыНаПеремещение : Остатки
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
Международный : РегистрБухгалтерии
ДвижениеТоваров : Обороты
НДСЗаписиКнигиПродаж : Обороты
ТоварыОрганизацийКПередаче : Остатки
СвободныеОстатки : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
ГрафикПоступленияТоваров : Остатки
ТоварыКПоступлению : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
