@startuml ДвижениеПродукцииИМатериалов
'!include templates.wsd
'..\include templates.wsd
class Документ.ДвижениеПродукцииИМатериалов as "Движение продукции и материалов" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ОрганизацияПолучатель : Справочник.Организация
Отправитель : Справочник.Подразделение\rСправочник.Склад (складская территория)
Получатель : Справочник.Подразделение\rСправочник.Склад (складская территория)
Распоряжение : Документ.Этап производства\rДокумент.Заказ материалов в производство
Ответственный : Справочник.Пользователь
Комментарий : Строка
ПоРаспоряжениям : Булево
ХозяйственнаяОперация : Хозяйственные операции
ВидыЗапасовУказаныВручную : Булево
НалогообложениеНДС : Типы налогообложения НДС
СостояниеЗаполненияМногооборотнойТары : Состояния заполнения многооборотной тары
Статус : Статусы движения продукции и материалов
НаправлениеДеятельности : Справочник.Направление деятельности
ВидЦены : Справочник.Вид цены
ЕстьМаркируемаяПродукцияГИСМ : Булево
ПоТоварамКОформлениюОтчетовКомитенту : Булево
ДокументОснование : Документ.Приобретение товаров и услуг\rДокумент.Поступление сырья от давальца\rДокумент.Распределение возвратных отходов\r...
ВариантПриемкиТоваров : Варианты приемки товаров
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Серия : Справочник.Серия номенклатуры
Назначение : Справочник.Назначение
НазначениеОтправителя : Справочник.Назначение
Упаковка : Справочник.Упаковка
Количество : Число 15, 3
КоличествоУпаковок : Число 15, 3
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ИдентификаторСтроки : Строка
СтатусУказанияСерий : Число 2, 0
СтатусУказанияСерийОтправитель : Число 2, 0
СтатусУказанияСерийПолучатель : Число 2, 0
Распоряжение : Документ.Этап производства\rДокумент.Заказ материалов в производство
КодСтроки : Число 10, 0
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
Цена : Число 15, 2
Сумма : Число 15, 2
..Табличная часть \n Серии..
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Серия : Справочник.Серия номенклатуры
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
НазначениеОтправителя : Справочник.Назначение
..Табличная часть \n ВидыЗапасов..
АналитикаУчетаНоменклатуры : Справочник.Номенклатура\rСправочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
Серия : Справочник.Серия номенклатуры
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
НазначениеПолучателя : Справочник.Назначение
ВидЗапасовПолучателя : Справочник.Вид запасов
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ТоварыКОтгрузке : Остатки
ЗаказыМатериаловВПроизводство : Остатки
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ТоварыКОформлениюОтчетовКомитенту : Остатки
РаспоряженияНаПередачуИзПроизводства : Остатки
РасходыПриУСНМатериалы : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
Международный : РегистрБухгалтерии
ДвижениеТоваров : Обороты
РасходыПриУСНТовары : Остатки
НДСЗаписиКнигиПродаж : Обороты
ОбеспечениеЗаказовРаботами : Остатки
ТоварыОрганизацийКПередаче : Остатки
КнигаУчетаДоходовИРасходов : Обороты
СвободныеОстатки : Остатки
ДвиженияНоменклатураНоменклатура : Обороты
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
ГрафикПоступленияТоваров : Остатки
ТоварыКПоступлению : Остатки
}
@enduml
