@startuml ОперацияНалоговогоУчетаПоНДФЛ
'!include templates.wsd
'..\include templates.wsd
class Документ.ОперацияНалоговогоУчетаПоНДФЛ as "Операция учета НДФЛ" <<Документы>>
{
..Реквизиты..
ДатаОперации : Дата
Организация : Справочник.Организация
Сотрудник : Справочник.Физическое лицо
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n СведенияОДоходах..
ДатаПолученияДохода : Дата
КодДохода : Справочник.Вид дохода НДФЛ
КатегорияДохода : Категории доходов НДФЛ
УдалитьКодДохода : Справочник.(не используется) Виды доходов НДФЛ
СуммаДохода : Число 15, 2
ОбособленноеПодразделение : Справочник.Территория\rСправочник.Подразделение
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
Количество : Число 2, 0
СуммаВычета : Число 15, 2
СуммаНалогаИсчисленная : Число 10, 0
ВключатьВДекларациюПоНалогуНаПрибыль : Булево
ИсточникДоходаЗаПределамиРФ : Булево
..Табличная часть \n НДФЛИсчисленныйПоСтавке13..
МесяцНалоговогоПериода : Дата
КатегорияДохода : Категории доходов НДФЛ
Сумма : Число 10, 0
ЗачтеноАвансовыхПлатежей : Число 10, 0
ОбособленноеПодразделение : Справочник.Территория\rСправочник.Подразделение
ВключатьВДекларациюПоНалогуНаПрибыль : Булево
..Табличная часть \n ПредоставленныеВычеты..
МесяцНалоговогоПериода : Дата
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
Сумма : Число 12, 2
ОбособленноеПодразделение : Справочник.Территория\rСправочник.Подразделение
ВключатьВДекларациюПоНалогуНаПрибыль : Булево
..Табличная часть \n НДФЛУдержанный..
МесяцНалоговогоПериода : Дата
СтавкаНалогообложения : НДФЛ ставки налогообложения резидента
Ставка : Ставки НДФЛ
Сумма : Число 10, 0
ОбособленноеПодразделение : Справочник.Территория\rСправочник.Подразделение
КодДохода : Справочник.Вид дохода НДФЛ
КатегорияДохода : Категории доходов НДФЛ
ВключатьВДекларациюПоНалогуНаПрибыль : Булево
СрокПеречисления : Сроки перечисляемого налога
СуммаВыплаченногоДохода : Число 15, 2
ДокументОснование : Документ.Сторнирование начислений\rДокумент.Перенос затрат\rДокумент.Приз, подарок\r...
УдалитьКодДохода : Справочник.(не используется) Виды доходов НДФЛ
..Табличная часть \n НДФЛПеречисленный..
МесяцНалоговогоПериода : Дата
Ставка : Ставки НДФЛ
Сумма : Число 10, 0
РеквизитыПлатежногоПоручения : Строка
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
ВключатьВДекларациюПоНалогуНаПрибыль : Булево
ИсчисленоПоДивидендам : Булево
..Движения..
РасчетыНалогоплательщиковСБюджетомПоНДФЛ : Остатки
ИмущественныеВычетыНДФЛ : Остатки
ПредоставленныеСтандартныеИСоциальныеВычетыНДФЛ : Обороты
РасчетыНалоговыхАгентовСБюджетомПоНДФЛ : Остатки
СведенияОДоходахНДФЛ : Обороты
АвансовыеПлатежиИностранцевПоНДФЛ : Остатки
}
@enduml
