@startuml РегистрацияДефекта
'!include templates.wsd
'..\include templates.wsd
class Документ.РегистрацияДефекта as "Регистрация дефекта" <<Документы>>
{
..Реквизиты..
ОбъектЭксплуатации : Справочник.Объект эксплуатации
ВидДефекта : Справочник.Виды дефектов
КраткоеОписаниеДефекта : Строка
ОписаниеДефекта : Строка
Решение : Строка
КрайнееВремяУстранения : Дата
Ответственный : Справочник.Пользователь
Комментарий : Строка
Статус : Статусы дефектов
Подразделение : Справочник.Подразделение
ТребуетсяЗаказНаРемонт : Булево
..Табличная часть \n ДефектныеУзлы..
Узел : Справочник.Узел объекта эксплуатации
ОписаниеДефекта : Строка
..Движения..
ПериодыАктуальностиОбъектовЭксплуатации : РегистрСведений
}
@enduml
