@startuml ОперацияПоЯндексКассе
'!include templates.wsd
'..\include templates.wsd
class Документ.ОперацияПоЯндексКассе as "Операция по Яндекс.Кассе" <<Документы>>
{
..Реквизиты..
НастройкаЯндексКассы : Справочник.Настройка Яндекс.Кассы
Эквайер : Справочник.Контрагент
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
Организация : Справочник.Организация
БанковскийСчет : Справочник.Банковский счет организации
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Подразделение : Справочник.Подразделение
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
ХозяйственнаяОперация : Хозяйственные операции
КонтейнерСообщения : Строка
ИдентификаторТранзакции : Число 20, 0
ИдентификаторПлатежа : Строка
ИдентификаторПеревода : Строка
ИдентификаторВозврата : Число 20, 0
СуммаСчета : Число 15, 2
ВалютаСчета : Справочник.Валюта
СуммаДокумента : Число 15, 2
Валюта : Справочник.Валюта
СуммаКомиссии : Число 15, 2
ВалютаКомиссии : Справочник.Валюта
СпособОплаты : Способы оплаты через Яндекс,Кассу
ОснованиеПлатежа : Документ.Операция по Яндекс.Кассе\rДокумент.Счет на оплату\rДокумент.Заказ клиента
ОбъектРасчетов : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
ОписаниеПричиныВозврата : Строка
ОтправительЗапросаНаВозврат : Строка
ТипОперацииВозврата : Типы операций возврата через яндекс кассу
ИнформацияОПроблеме : Строка
ЕстьПроблемы : Булево
КодПроблемы : Число 2, 0
Ответственный : Справочник.Пользователь
Комментарий : Строка
СуммаНДС18 : Число 15, 2
СуммаНДС10 : Число 15, 2
СуммаДокументаСНДС18 : Число 15, 2
СуммаДокументаСНДС10 : Число 15, 2
НазначениеПлатежа : Строка
..Движения..
РасчетыСКлиентами : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДенежныеСредстваКонтрагент : Обороты
ДенежныеСредстваВПути : Остатки
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
РасчетыСКлиентамиПоДокументам : Остатки
ДвиженияДенежныеСредстваДоходыРасходы : Обороты
}
@enduml
