@startuml ПередачаВРегистр2ЕГАИС
'!include templates.wsd
'..\include templates.wsd
class Документ.ПередачаВРегистр2ЕГАИС as "Передача в регистр №2 ЕГАИС" <<Документы>>
{
..Реквизиты..
ОрганизацияЕГАИС : Справочник.Организация ЕГАИС
Идентификатор : Строка
ИдентификаторЕГАИС : Строка
УдалитьСтатусОбработки : Статусы обработки передачи в регистр №2 ЕГАИС
ДатаРегистрацииДвижений : Дата
Комментарий : Строка
Ответственный : Справочник.Пользователь
ДокументОснование : Документ.Товарно-транспортная накладная ЕГАИС (входящая)
..Табличная часть \n Товары..
АлкогольнаяПродукция : Справочник.Алкогольная продукция ЕГАИС
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Справка2 : Справочник.Справка к ТТН по форме 2
..Движения..
ОстаткиАлкогольнойПродукцииЕГАИС : Остатки
}
@enduml
