@startuml АктОРасхожденияхПослеПеремещения
'!include templates.wsd
'..\include templates.wsd
class Документ.АктОРасхожденияхПослеПеремещения as "Акт о расхождениях после перемещения" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ОрганизацияПолучатель : Справочник.Организация
СкладОтправитель : Справочник.Склад (складская территория)
СкладПолучатель : Справочник.Склад (складская территория)
Менеджер : Справочник.Пользователь
Комментарий : Строка
Статус : Статусы акта о расхождениях
ХозяйственнаяОперация : Хозяйственные операции
СпособОтраженияРасхождений : Способы отражения расхождений акт приемки клиента
Подразделение : Справочник.Подразделение
ВариантПриемкиТоваров : Варианты приемки товаров
..Табличная часть \n Товары..
ТекстовоеОписание : Строка
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Заказ : Документ.Заказ на перемещение
КодСтроки : Число 10, 0
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
ДокументОснование : Документ.Перемещение товаров
ЗаполненоПоОснованию : Булево
КоличествоУпаковокПоДокументу : Число 15, 3
КоличествоПоДокументу : Число 15, 3
Действие : Варианты действий по расхождениям в акте после отгрузки
КомментарийПолучателя : Строка
КомментарийМенеджера : Строка
СтатусУказанияСерийОтправитель : Число 2, 0
СтатусУказанияСерийПолучатель : Число 2, 0
НазначениеОтправителя : Справочник.Назначение
..Табличная часть \n Серии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
НазначениеОтправителя : Справочник.Назначение
ЗаполненоПоОснованию : Булево
ДокументОснование : Документ.Перемещение товаров
Действие : Варианты действий по расхождениям в акте после отгрузки
КоличествоПоДокументу : Число 15, 3
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ТоварыКОтгрузке : Остатки
ДвиженияСерийТоваров : Обороты
ГрафикОтгрузкиТоваров : Остатки
ТоварыКОформлениюИзлишковНедостач : Остатки
ТоварыНаСкладах : Остатки
ОбеспечениеЗаказов : Остатки
ДвижениеТоваров : Обороты
СвободныеОстатки : Остатки
ТоварыКПоступлению : Остатки
}
@enduml
