@startuml СчетФактураПолученный
'!include templates.wsd
'..\include templates.wsd
class Документ.СчетФактураПолученный as "Счет-фактура полученный" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Исправление : Булево
НомерИсправления : Строка
ДатаИсправления : Дата
Корректировочный : Булево
СчетФактураОснование : Документ.Счет-фактура полученный
ПолученВЭлектронномВиде : Булево
Валюта : Справочник.Валюта
КодВидаОперации : Строка
Контрагент : Справочник.Организация\rСправочник.Контрагент
ДатаСоставления : Дата
ОтнестиКПредыдущемуОтчетномуКварталу : Булево
ДатаЗаписиКнигиПокупок : Дата
Подразделение : Справочник.Подразделение
Ответственный : Справочник.Пользователь
СоставленКомиссионеромОтИмениПродавца : Булево
СводныйКомиссионный : Булево
КодВидаОперацииНаУменьшение : Строка
СводныйКорректировочный : Булево
ИННКонтрагента : Строка
КППКонтрагента : Строка
..Табличная часть \n ДокументыОснования..
ДокументОснование : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\rДокумент.Приобретение услуг по лизингу\r...
ИсходныйДокумент : Документ.Счет-фактура полученный
НомерИсходногоДокумента : Строка
ДатаИсходногоДокумента : Дата
НомерИсправленияИсходногоДокумента : Строка
ДатаИсправленияИсходногоДокумента : Дата
..Табличная часть \n Продавцы..
Продавец : Справочник.Контрагент
ИННПродавца : Строка
КПППродавца : Строка
..Движения..
ОтражениеДокументовВРеглУчете : РегистрСведений
НДСПредъявленный : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
НДСЗаписиКнигиПродаж : Обороты
НДСЗаписиКнигиПокупок : Обороты
ЖурналУчетаСчетовФактур : РегистрСведений
}
@enduml
