@startuml РаботаВВыходныеИПраздничныеДни
'!include templates.wsd
'..\include templates.wsd
class Документ.РаботаВВыходныеИПраздничныеДни as "Работа в выходные и праздничные дни" <<Документы>>
{
..Реквизиты..
ПериодРегистрации : Дата
Организация : Справочник.Организация
КраткийСоставДокумента : Строка
СогласиеТребуется : Булево
Причина : Строка
СогласиеПолучено : Булево
ДатаНачалаСобытия : Дата
ВремяВЧасах : Булево
ВремяУчтено : Булево
ВремяУчел : Справочник.Пользователь
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Сотрудник
Дата : Дата
ОтработаноЧасов : Число 7, 2
СпособКомпенсацииПереработки : Способы компенсации переработки
НеРаботал : Булево
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Движения..
ДанныеОперативногоУчетаРабочегоВремениСотрудников : Обороты
ДниЧасыОтгулов : Остатки
ДанныеТабельногоУчетаРабочегоВремениСотрудников : Обороты
}
@enduml
