@startuml ОтпускаСотрудников
'!include templates.wsd
'..\include templates.wsd
class Документ.ОтпускаСотрудников as "Отпуск сотрудников" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
КраткийСоставДокумента : Строка
ПериодПринадлежности : Дата
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
Ответственный : Справочник.Пользователь
Комментарий : Строка
УдалитьДокументОснование : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ВидОтпуска : Справочник.Вид отпуска
ДатаНачала : Дата
ДатаОкончания : Дата
НачалоПериодаЗаКоторыйПредоставляетсяОтпуск : Дата
КонецПериодаЗаКоторыйПредоставляетсяОтпуск : Дата
Основание : Строка
КоличествоДней : Число 3, 0
КоличествоДнейКомпенсации : Число 5, 2
}
@enduml
