@startuml ОрдерНаПеремещениеТоваров
'!include templates.wsd
'..\include templates.wsd
class Документ.ОрдерНаПеремещениеТоваров as "Ордер на перемещение товаров" <<Документы>>
{
..Реквизиты..
ЗонаОтгрузки : Справочник.Складская ячейка
ЗонаПриемки : Справочник.Складская ячейка
Склад : Справочник.Склад (складская территория)
Ответственный : Справочник.Пользователь
Комментарий : Строка
ПомещениеОтправитель : Справочник.Помещение
ПомещениеПолучатель : Справочник.Помещение
Статус : Статусы ордеров на перемещение
ДатаОтгрузки : Дата
Автор : Справочник.Пользователь
Приоритет : Справочник.Приоритет
..Табличная часть \n ОтгружаемыеТовары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
Серия : Справочник.Серия номенклатуры
Назначение : Справочник.Назначение
Количество : Число 15, 3
КоличествоУпаковок : Число 15, 3
Действие : Действия со строками ордеров на отгрузку
СтатусУказанияСерий : Число 2, 0
..Движения..
ДвиженияСерийТоваров : Обороты
ТоварыКОтбору : Остатки
ТоварыНаСкладах : Остатки
ТоварыВЯчейках : Остатки
}
@enduml
