@startuml ВыкупВозвратнойТарыУПоставщика
'!include templates.wsd
'..\include templates.wsd
class Документ.ВыкупВозвратнойТарыУПоставщика as "Выкуп возвратной тары у поставщика" <<Документы>>
{
..Реквизиты..
Валюта : Справочник.Валюта
Партнер : Справочник.Партнер
Соглашение : Справочник.Соглашение об условиях закупок
Организация : Справочник.Организация
Контрагент : Справочник.Контрагент
СуммаДокумента : Число 15, 2
Менеджер : Справочник.Пользователь
ЦенаВключаетНДС : Булево
Комментарий : Строка
НалогообложениеНДС : Типы налогообложения НДС
НомерВходящегоДокумента : Строка
ДатаВходящегоДокумента : Дата
Договор : Справочник.Договор с контрагентом
ПредусмотренЗалогЗаТару : Булево
ВалютаВзаиморасчетов : Справочник.Валюта
ДатаПлатежа : Дата
СуммаВзаиморасчетов : Число 15, 2
ФормаОплаты : Формы оплаты
ПорядокРасчетов : Детализация расчетов
Подразделение : Справочник.Подразделение
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
НаправлениеДеятельности : Справочник.Направление деятельности
Курс : Число 10, 4
Кратность : Число 10, 0
ПорядокОплаты : Порядок оплаты
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
НоменклатураПоставщика : Справочник.Номенклатура поставщика
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Цена : Число 15, 2
ВидЦеныПоставщика : Справочник.Вид цены поставщика
Сумма : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
СуммаСНДС : Число 15, 2
ДокументПоступления : Документ.Приобретение товаров и услуг\rДокумент.Поступление сырья от давальца
ИдентификаторСтроки : Строка
СуммаВзаиморасчетов : Число 15, 2
СуммаНДСВзаиморасчетов : Число 15, 2
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n РасшифровкаПлатежа..
Заказ : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Приобретение товаров и услуг\r...
Сумма : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
..Движения..
ПрочиеДоходы : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
РасчетыСПоставщиками : Остатки
Международный : РегистрБухгалтерии
РасчетыСПоставщикамиПоДокументам : Остатки
ПринятаяВозвратнаяТара : Остатки
}
@enduml
