@startuml НачислениеЗарплаты
'!include templates.wsd
'..\include templates.wsd
class Документ.НачислениеЗарплаты as "Начисление зарплаты и взносов" <<Документы>>
{
..Реквизиты..
МесяцНачисления : Дата
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
РежимДоначисления : Булево
ПериодыПерерасчета : Строка
Начислено : Число 13, 2
Удержано : Число 13, 2
ПорядокВыплаты : Характер выплаты зарплаты
ПланируемаяДатаВыплаты : Дата
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
НачислениеЗарплатыВоеннослужащим : Булево
..Табличная часть \n Начисления..
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Результат : Число 13, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
СуммаВычета : Число 15, 2
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ВидУчетаВремени : Справочник.Вид рабочего времени
ВремяВЧасах : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ПериодРегистрацииВремени : Дата
ОплаченоДней : Число 7, 2
ОплаченоЧасов : Число 7, 2
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ПериодДействия : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n Удержания..
Удержание : Удержание
ДатаНачала : Дата
ДатаОкончания : Дата
ФизическоеЛицо : Справочник.Физическое лицо
Получатель : Справочник.Контрагент
ПлатежныйАгент : Справочник.Контрагент
Результат : Число 13, 2
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчет : Булево
ДокументОснование : Документ.Удержание по прочим операциям\rДокумент.Удержание добровольных взносов в НПФ\rДокумент.Удержание профсоюзных взносов\r...
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Сотрудник : Справочник.Сотрудник
ФиксСторно : Булево
..Табличная часть \n НачисленияПерерасчет..
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Результат : Число 13, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
СуммаВычета : Число 15, 2
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ВидУчетаВремени : Справочник.Вид рабочего времени
ВремяВЧасах : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ПериодРегистрацииВремени : Дата
ОплаченоДней : Число 7, 2
ОплаченоЧасов : Число 7, 2
Сторно : Булево
ФиксСторно : Булево
СторнируемыйДокумент : Документ.Приз, подарок\rДокумент.Простой сотрудников\rДокумент.Отпуск без сохранения оплаты списком\r...
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ПериодДействия : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n УправленческиеНачисления..
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Результат : Число 13, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ВидУчетаВремени : Справочник.Вид рабочего времени
ВремяВЧасах : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ПериодРегистрацииВремени : Дата
ОплаченоДней : Число 7, 2
ОплаченоЧасов : Число 7, 2
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ПериодДействия : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n НачисленияПоДоговорам..
Сотрудник : Справочник.Сотрудник
ДатаНачала : Дата
ДатаОкончания : Дата
Подразделение : Справочник.Подразделение
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
СуммаВычета : Число 15, 2
ДокументОснование : Документ.Договор авторского заказа\rДокумент.Акт приемки выполненных работ\rДокумент.Договор (работы, услуги)
Результат : Число 13, 2
ФиксРасчет : Булево
ФиксСтрока : Булево
КодДохода : Справочник.Вид дохода НДФЛ
УдалитьКодДохода : Справочник.(не используется) Виды доходов НДФЛ
ПланируемаяДатаВыплаты : Дата
ИдентификаторСтроки : Число 7, 0
КодДоходаСтраховыеВзносы : Справочник.Вид дохода по страховым взносам
..Табличная часть \n НДФЛ..
ФизическоеЛицо : Справочник.Физическое лицо
МесяцНалоговогоПериода : Дата
Подразделение : Справочник.Территория\rСправочник.Подразделение
Налог : Число 10, 0
КатегорияДохода : Категории доходов НДФЛ
ЗачтеноАвансовыхПлатежей : Число 10, 0
УдалитьНалогКЗачетуВозврату : Число 10, 0
ПримененныйВычетЛичный : Число 12, 2
ПримененныйВычетЛичныйКодВычета : Справочник.Вид вычетов НДФЛ
УдалитьПримененныйВычетЛичныйКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
ПримененныйВычетЛичныйКЗачетуВозврату : Число 12, 2
ПримененныйВычетЛичныйКЗачетуВозвратуКодВычета : Справочник.Вид вычетов НДФЛ
ФиксСтрока : Булево
ФиксРасчет : Булево
УдалитьПримененныйВычетЛичныйКЗачетуВозвратуКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
ИдентификаторСтрокиНДФЛ : Число 7, 0
..Табличная часть \n ПогашениеЗаймов..
ФизическоеЛицо : Справочник.Физическое лицо
ДоговорЗайма : Документ.Договор займа сотруднику
НачисленоПроцентов : Число 15, 2
ПогашениеПроцентов : Число 15, 2
ПогашениеЗайма : Число 15, 2
МатериальнаяВыгода : Число 15, 2
НалогНаМатериальнуюВыгоду : Число 13, 0
СтавкаНалогообложенияМатвыгоды : НДФЛ ставки налогообложения резидента
Подразделение : Справочник.Подразделение
ИдентификаторСтроки : Число 7, 0
..Табличная часть \n Показатели..
Показатель : Справочник.Показатель
Значение : Число 15, 5
ИдентификаторСтрокиВидаРасчета : Число 7, 0
..Табличная часть \n Пособия..
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
ВидЗанятости : Виды занятости
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Результат : Число 13, 2
РезультатВТомЧислеЗаСчетФБ : Число 15, 2
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ОплаченоДней : Число 7, 2
ОплаченоЧасов : Число 7, 2
СуммаВсегоПоУходуЗаПервымРебенком : Число 15, 2
СуммаСверхНормПоУходуЗаПервымРебенком : Число 15, 2
СуммаВсегоПоУходуЗаВторымРебенком : Число 15, 2
СуммаСверхНормПоУходуЗаВторымРебенком : Число 15, 2
ФинансированиеФедеральнымБюджетом : Основания финансирования пособия федеральным бюджетом
СтраховойСлучай : Документ.Отпуск по уходу за ребенком
КоличествоДетей : Число 2, 0
КоличествоПервыхДетей : Число 1, 0
ПериодДействия : Дата
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ПериодРегистрацииВремени : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n ПримененныеВычетыНаДетейИИмущественные..
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
РазмерВычета : Число 12, 2
ИдентификаторСтрокиНДФЛ : Число 7, 0
..Табличная часть \n Взносы..
ФизическоеЛицо : Справочник.Физическое лицо
ДатаПолученияДохода : Дата
ФФОМС : Число 15, 2
ФФОМСЕНВД : Число 15, 2
ТФОМС : Число 15, 2
ТФОМСЕНВД : Число 15, 2
ФСС : Число 15, 2
ФССЕНВД : Число 15, 2
ФССНесчастныеСлучаи : Число 15, 2
ПФРДоПредельнойВеличины : Число 15, 2
ПФРДоПредельнойВеличиныЕНВД : Число 15, 2
ПФРСПревышения : Число 15, 2
ПФРСПревышенияЕНВД : Число 15, 2
ПФРПоСуммарномуТарифу : Число 15, 2
ПФРПоСуммарномуТарифуЕНВД : Число 15, 2
ПФРНакопительная : Число 15, 2
ПФРНакопительнаяЕНВД : Число 15, 2
ПФРСтраховая : Число 15, 2
ПФРСтраховаяЕНВД : Число 15, 2
ПФРНаДоплатуЛетчикам : Число 15, 2
ПФРНаДоплатуШахтерам : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботах : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботах : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахОпасный : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный1 : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный2 : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный3 : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный4 : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахОпасный : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный1 : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный2 : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный3 : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный4 : Число 15, 2
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Табличная часть \n РаспределениеРезультатовНачислений..
ИдентификаторСтроки : Число 7, 0
Территория : Справочник.Территория
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОблагаетсяЕНВД : Булево
Результат : Число 13, 2
..Табличная часть \n РаспределениеРезультатовУдержаний..
ИдентификаторСтроки : Число 7, 0
ВидУдержания : Виды особых начислений и удержаний\rУдержание
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
Результат : Число 13, 2
..Табличная часть \n ПредставлениеРаспределенияРезультатовРасчета..
ИдентификаторСтроки : Число 7, 0
НомерСтрокиРаспределения : Число 10, 0
НомерЭлементаПредставления : Число 10, 0
КоличествоЭлементовПредставления : Число 10, 0
ПредставлениеРезультата : Строка
ЕстьОшибкиЗаполнения : Булево
РаспределениеНачислений : Булево
..Табличная часть \n Льготы..
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Результат : Число 13, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
СуммаВычета : Число 15, 2
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ВидУчетаВремени : Справочник.Вид рабочего времени
ВремяВЧасах : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ПериодРегистрацииВремени : Дата
ОплаченоДней : Число 7, 2
ОплаченоЧасов : Число 7, 2
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ПериодДействия : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n РаспределениеПоТерриториямУсловиямТруда..
ИдентификаторСтроки : Число 7, 0
Территория : Справочник.Территория
УсловияТруда : Справочник.Условия труда
ДоляРаспределения : Число 15, 5
Результат : Число 15, 2
ИдентификаторСтрокиПоказателей : Число 7, 0
СуммаВычета : Число 13, 0
..Табличная часть \n ПособияПерерасчет..
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
ВидЗанятости : Виды занятости
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Результат : Число 13, 2
РезультатВТомЧислеЗаСчетФБ : Число 15, 2
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ОплаченоДней : Число 7, 2
ОплаченоЧасов : Число 7, 2
СуммаВсегоПоУходуЗаПервымРебенком : Число 15, 2
СуммаСверхНормПоУходуЗаПервымРебенком : Число 15, 2
СуммаВсегоПоУходуЗаВторымРебенком : Число 15, 2
СуммаСверхНормПоУходуЗаВторымРебенком : Число 15, 2
ФинансированиеФедеральнымБюджетом : Основания финансирования пособия федеральным бюджетом
СтраховойСлучай : Документ.Отпуск по уходу за ребенком
КоличествоДетей : Число 2, 0
КоличествоПервыхДетей : Число 1, 0
ФиксСторно : Булево
Сторно : Булево
СторнируемыйДокумент : Документ.Приз, подарок\rДокумент.Простой сотрудников\rДокумент.Отпуск без сохранения оплаты списком\r...
ПериодДействия : Дата
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ПериодРегистрацииВремени : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n КорректировкиВыплаты..
ФизическоеЛицо : Справочник.Физическое лицо
КорректировкаВыплаты : Число 15, 2
ИдентификаторСтроки : Число 7, 0
ФиксСтрока : Булево
ФиксРасчет : Булево
..Табличная часть \n УдержанияПерерасчет..
ФизическоеЛицо : Справочник.Физическое лицо
ДатаНачала : Дата
ДатаОкончания : Дата
ДокументОснование : Документ.Удержание по прочим операциям\rДокумент.Удержание добровольных взносов в НПФ\rДокумент.Удержание профсоюзных взносов\r...
Получатель : Справочник.Контрагент
ПлатежныйАгент : Справочник.Контрагент
Удержание : Удержание
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчет : Булево
Результат : Число 13, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Сотрудник : Справочник.Сотрудник
ФиксСторно : Булево
..Табличная часть \n ЛьготыПерерасчет..
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Результат : Число 13, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
СуммаВычета : Число 15, 2
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ВидУчетаВремени : Справочник.Вид рабочего времени
ВремяВЧасах : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ПериодРегистрацииВремени : Дата
ОплаченоДней : Число 7, 2
ОплаченоЧасов : Число 7, 2
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ПериодДействия : Дата
Сторно : Булево
ФиксСторно : Булево
СторнируемыйДокумент : Документ.Приз, подарок\rДокумент.Простой сотрудников\rДокумент.Отпуск без сохранения оплаты списком\r...
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Движения..
Удержания : РегистрРасчета
ОплаченныеДоговоры : РегистрСведений
ОценочныеОбязательства : Остатки
РасчетыНалогоплательщиковСБюджетомПоНДФЛ : Остатки
ДанныеОВремениДляРасчетаСреднегоФСС : РегистрСведений
УдалитьВыплатаОтпусковЗаСчетРезерва : Обороты
ЗначенияПоказателейУдержаний : РегистрСведений
ВзаиморасчетыССотрудниками : Остатки
НачисленияУдержанияПоСотрудникам : Обороты
ОтработанноеВремяПоСотрудникамКорректировка : Обороты
РасчетыСФондамиПоСтраховымВзносам : Остатки
ПорядокВыплатыДокументов : РегистрСведений
ПособияПоСоциальномуСтрахованию : Обороты
УдержанияДоПределаПоСотрудникам : Остатки
РаспределениеПоТерриториямУсловиямТруда : РегистрСведений
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
ДанныеОВремениДляРасчетаСреднегоОбщий : Обороты
ОценочныеОбязательстваПоСотрудникам : Остатки
ФактическиеОтпуска : Обороты
СведенияОДоходахСтраховыеВзносы : Обороты
ИмущественныеВычетыНДФЛ : Остатки
ПособияПоУходуЗаРебенком : Обороты
ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаОбщий : Обороты
ЗначенияПоказателейНачислений : РегистрСведений
СтраховыеВзносыПоФизическимЛицам : Обороты
ПредоставленныеСтандартныеИСоциальныеВычетыНДФЛ : Обороты
НачисленияПоДоговорамГПХ : Обороты
УдержанияПоИсполнительнымДокументам : Обороты
ОтработанноеВремяПоСотрудникам : Обороты
Начисления : РегистрРасчета
ИсчисленныеСтраховыеВзносы : Обороты
СведенияОДоходахНДФЛ : Обороты
БухучетНачисленияУдержанияПоСотрудникам : Обороты
ЗарплатаКВыплате : Остатки
ВзаиморасчетыПоЗаймамСотрудникам : Остатки
ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаФСС : Обороты
АвансовыеПлатежиИностранцевПоНДФЛ : Остатки
}
@enduml
