@startuml МаркировкаТоваровГИСМ
'!include templates.wsd
'..\include templates.wsd
class Документ.МаркировкаТоваровГИСМ as "Маркировка товаров" <<Документы>>
{
..Реквизиты..
Основание : Документ.Уведомление об импорте маркированных товаров\rДокумент.Возврат товаров от клиента\rДокумент.Этап производства\r...
ОперацияМаркировки : Операции маркировки ГИСМ
КиЗГИСМВид : Виды КиЗ
КиЗГИСМСпособВыпускаВОборот : Способы выпуска в оборот ГИСМ
КиЗГИСМРазмер : Размеры КиЗ
КиЗГИСМСИндивидуализацией : Булево
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Склад : Справочник.Склад (складская территория)
Ответственный : Справочник.Пользователь
Комментарий : Строка
НазначениеКиЗ : Справочник.Назначение
НаправлениеДеятельности : Справочник.Направление деятельности
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ВидыЗапасовУказаныВручную : Булево
МаркировкаДляДеятельности : Типы налогообложения НДС
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
GTIN : Строка
НоменклатураКиЗ : Справочник.Номенклатура
ХарактеристикаКиЗ : Справочник.Характеристика номенклатуры
Количество : Число 15, 3
СтатусУказанияСерий : Число 2, 0
ИдентификаторСтроки : Строка
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
КодТаможенногоОргана : Строка
ДатаРегистрацииДекларации : Дата
РегистрационныйНомерДекларации : Строка
НомерТовараВДекларации : Число 5, 0
..Табличная часть \n Серии..
Серия : Справочник.Серия номенклатуры
Количество : Число 15, 3
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
GTIN : Строка
НоменклатураКиЗ : Справочник.Номенклатура
ХарактеристикаКиЗ : Справочник.Характеристика номенклатуры
КодТаможенногоОргана : Строка
ДатаРегистрацииДекларации : Дата
РегистрационныйНомерДекларации : Строка
НомерТовараВДекларации : Число 5, 0
..Табличная часть \n СерииКиЗ..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Серия : Справочник.Серия номенклатуры
GTIN : Строка
Количество : Число 15, 3
..Табличная часть \n ВидыЗапасов..
АналитикаУчетаНоменклатуры : Справочник.Номенклатура\rСправочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
Количество : Число 15, 3
ИдентификаторСтроки : Строка
..Движения..
ДвиженияСерийТоваров : Обороты
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНМатериалы : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ТоварыНаСкладах : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
ОбеспечениеЗаказов : Остатки
Международный : РегистрБухгалтерии
РасходыПриУСНТовары : Остатки
НДСЗаписиКнигиПродаж : Обороты
ТоварыОрганизацийКПередаче : Остатки
СвободныеОстатки : Остатки
ТоварыКОформлениюТаможенныхДеклараций : Остатки
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
ПартииПроизводственныхЗатрат : Остатки
ПартииЗатратНаВыпуск : Остатки
}
@enduml
