@startuml НачислениеИСписаниеБонусныхБаллов
'!include templates.wsd
'..\include templates.wsd
class Документ.НачислениеИСписаниеБонусныхБаллов as "Начисление и списание бонусных баллов" <<Документы>>
{
..Реквизиты..
МаркетинговоеМероприятие : Справочник.Маркетинговое мероприятие
БонуснаяПрограммаЛояльности : Справочник.Бонусные программы лояльности
Комментарий : Строка
ПравилоНачисления : Справочник.Правила начисления и списания бонусных баллов
ПериодДействия : Периодичность
КоличествоПериодовДействия : Число 10, 0
КоличествоПериодовОтсрочкиНачалаДействия : Число 10, 0
ПериодОтсрочкиНачалаДействия : Периодичность
ДатаОкончанияСрокаДействия : Дата
ВидПравила : Виды правил начисления бонусных баллов
..Табличная часть \n Начисление..
Партнер : Справочник.Партнер
Баллы : Число 15, 2
..Табличная часть \n Списание..
Партнер : Справочник.Партнер
Баллы : Число 15, 2
..Движения..
БонусныеБаллы : Остатки
}
@enduml
