@startuml ТаможеннаяДекларацияИмпорт
'!include templates.wsd
'..\include templates.wsd
class Документ.ТаможеннаяДекларацияИмпорт as "Таможенная декларация на импорт" <<Документы>>
{
..Реквизиты..
ВариантОформления : Хозяйственные операции
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Менеджер : Справочник.Пользователь
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
Соглашение : Справочник.Соглашение об условиях закупок
Договор : Справочник.Договор с контрагентом
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
Поставщик : Справочник.Партнер
Статус : Статусы таможенных деклараций
Валюта : Справочник.Валюта
ВалютаВзаиморасчетов : Справочник.Валюта
СуммаДокумента : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
ТаможенныйСбор : Число 15, 2
СтатьяРасходовСбор : Статья расходов
АналитикаРасходовСбор : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ТаможенныйШтраф : Число 15, 2
СтатьяРасходовШтраф : Статья расходов
АналитикаРасходовШтраф : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ДатаПлатежа : Дата
ФормаОплаты : Формы оплаты
БанковскийСчетОрганизации : Справочник.Банковский счет организации
БанковскийСчетКонтрагента : Справочник.Банковский счет
Комментарий : Строка
ПорядокРасчетов : Детализация расчетов
НомерДекларации : Строка
НумероватьПоТоварам : Булево
УдалитьАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
КонтрагентПоставщика : Справочник.Контрагент
НаправлениеДеятельности : Справочник.Направление деятельности
ПорядокОплаты : Порядок оплаты
..Табличная часть \n Разделы..
НомерРаздела : Число 3, 0
ТаможеннаяСтоимость : Число 15, 2
СтавкаПошлины : Число 6, 3
СуммаПошлины : Число 15, 2
СтавкаНДС : Ставки НДС
СуммаНДС : Число 15, 2
Склад : Справочник.Склад (складская территория)
СтранаПроисхождения : Справочник.Страна мира
НомерДляСФ : Строка
..Табличная часть \n Товары..
НомерРаздела : Число 3, 0
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ТаможеннаяСтоимость : Число 15, 2
СуммаПошлины : Число 15, 2
СуммаНДС : Число 15, 2
Склад : Справочник.Склад (складская территория)
ВидЗапасов : Справочник.Вид запасов
СтранаПроисхождения : Справочник.Страна мира
НомерДляСФ : Строка
НомерГТД : Справочник.Номер ГТД
УдалитьАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
Серия : Справочник.Серия номенклатуры
СтатусУказанияСерий : Число 2, 0
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ДокументПоступления : Документ.Приобретение товаров и услуг
ЗакупкаПодДеятельность : Типы налогообложения НДС
Назначение : Справочник.Назначение
ХозяйственнаяОперация : Хозяйственные операции
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n УдалитьДокументыОплатыНалога..
НомерДокумента : Строка
ДатаДокумента : Дата
..Табличная часть \n РасшифровкаПлатежа..
Заказ : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Приобретение товаров и услуг\r...
Сумма : Число 15, 2
СуммаВзаиморасчетов : Число 15, 2
..Движения..
ПрочиеДоходы : Остатки
ТоварыУПартнеров : Остатки
РезервыТоваровОрганизаций : Остатки
ПартииТоваровОрганизаций : Остатки
ПрочиеРасходы : Остатки
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДетализацияПартийТоваровДляНДСиУСН : Остатки
НДСПредъявленный : Остатки
ДвиженияКонтрагентДоходыРасходы : Обороты
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНМатериалы : Остатки
РасходыПриУСН : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
РасчетыСПоставщиками : Остатки
Международный : РегистрБухгалтерии
Закупки : Обороты
РасходыПриУСНТовары : Остатки
НДСЗаписиКнигиПродаж : Обороты
РасчетыСПоставщикамиПоДокументам : Остатки
КнигаУчетаДоходовИРасходов : Обороты
ВыручкаИСебестоимостьПродаж : Обороты
ТоварыКОформлениюТаможенныхДеклараций : Остатки
ТоварыОрганизаций : Остатки
НДСЗаписиКнигиПокупок : Обороты
ЖурналУчетаСчетовФактур : РегистрСведений
}
@enduml
