@startuml ИзменениеАссортимента
'!include templates.wsd
'..\include templates.wsd
class Документ.ИзменениеАссортимента as "Изменение ассортимента" <<Документы>>
{
..Реквизиты..
Операция : Операции изменения ассортимента
Стадия : Стадии ассортимента
ОбъектПланирования : Справочник.Форматы магазинов\rСправочник.Склад (складская территория)
ДатаНачалаДействия : Дата
Ответственный : Справочник.Пользователь
Комментарий : Строка
Этап : Этапы изменения ассортимента
КоллекцияНоменклатуры : Справочник.Коллекция (сезон)
ДатаНачалаЗакупок : Дата
ДатаЗапретаЗакупки : Дата
ДатаНачалаПродаж : Дата
ДатаЗапретаПродажи : Дата
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
РольАссортимента : Роли ассортимента
ВидЦены : Справочник.Вид цены
РейтингПродаж : Справочник.Рейтинг продаж номенклатуры
..Табличная часть \n НаборыЗначенийДоступа..
НомерНабора : Число 10, 0
ЗначениеДоступа : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
Уточнение : Справочник.Идентификатор объекта метаданных
Чтение : Булево
Изменение : Булево
..Движения..
Ассортимент : РегистрСведений
}
@enduml
