@startuml АктПроверкиСтраховыхВзносов
'!include templates.wsd
'..\include templates.wsd
class Документ.АктПроверкиСтраховыхВзносов as "Акт проверки страховых взносов" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ПериодРегистрации : Дата
РасчетныйПериод : Число 4, 0
ОснованиеДляДоначисления : Основания для доначисления страховых взносов
Ответственный : Справочник.Пользователь
Комментарий : Строка
КраткийСоставДокумента : Строка
..Табличная часть \n Взносы..
ФизическоеЛицо : Справочник.Физическое лицо
МесяцРасчетногоПериода : Дата
ФФОМС : Число 15, 2
ФФОМСЕНВД : Число 15, 2
ТФОМС : Число 15, 2
ТФОМСЕНВД : Число 15, 2
ФСС : Число 15, 2
ФССЕНВД : Число 15, 2
ФССНесчастныеСлучаи : Число 15, 2
ПФРДоПредельнойВеличины : Число 15, 2
ПФРДоПредельнойВеличиныЕНВД : Число 15, 2
ПФРСПревышения : Число 15, 2
ПФРСПревышенияЕНВД : Число 15, 2
ПФРПоСуммарномуТарифу : Число 15, 2
ПФРПоСуммарномуТарифуЕНВД : Число 15, 2
ПФРНакопительная : Число 15, 2
ПФРНакопительнаяЕНВД : Число 15, 2
ПФРСтраховая : Число 15, 2
ПФРСтраховаяЕНВД : Число 15, 2
ПФРНаДоплатуЛетчикам : Число 15, 2
ПФРНаДоплатуШахтерам : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботах : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботах : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахОпасный : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный1 : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный2 : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный3 : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный4 : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахОпасный : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный1 : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный2 : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный3 : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный4 : Число 15, 2
ПФРСтраховаяСПревышения : Число 15, 2
ПФРПоСуммарномуТарифуСПревышения : Число 15, 2
..Табличная часть \n СведенияОДоходах..
ФизическоеЛицо : Справочник.Физическое лицо
МесяцРасчетногоПериода : Дата
ВидДохода : Справочник.Вид дохода по страховым взносам
УдалитьВидДохода : Справочник.(не используется) Виды доходов (взносы)
Сумма : Число 15, 2
Скидка : Число 15, 2
ОблагаетсяЕНВД : Булево
ОблагаетсяВзносамиНаДоплатуЛетчикам : Булево
ОблагаетсяВзносамиНаДоплатуШахтерам : Булево
ЯвляетсяДоходомФармацевта : Булево
ЯвляетсяДоходомЧленаЭкипажаСуднаПодФлагомРФ : Булево
ОблагаетсяВзносамиЗаЗанятыхНаРаботахСДосрочнойПенсией : Виды работ с досрочной пенсией
КлассУсловийТруда : Классы условий труда по результатам специальной оценки
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Движения..
РасчетыСФондамиПоСтраховымВзносам : Остатки
ПособияПоСоциальномуСтрахованию : Обороты
СведенияОДоходахСтраховыеВзносы : Обороты
СтраховыеВзносыПоФизическимЛицам : Обороты
ИсчисленныеСтраховыеВзносы : Обороты
}
@enduml
