@startuml РеестрДСВ_3
'!include templates.wsd
'..\include templates.wsd
class Документ.РеестрДСВ_3 as "Реестр ДСВ-3" <<Документы>>
{
..Реквизиты..
ОтчетныйПериод : Дата
Организация : Справочник.Организация
НомерПлатежногоПоручения : Строка
ДатаПлатежногоПоручения : Дата
ДатаИсполненияПлатежногоПоручения : Дата
НомерПачки : Число 5, 0
ИмяФайлаДляПФР : Строка
ДокументПринятВПФР : Булево
ГлавныйБухгалтер : Справочник.Физическое лицо
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ФайлСформирован : Булево
ОкончаниеОтчетногоПериода : Дата
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Физическое лицо
Фамилия : Строка
Имя : Строка
Отчество : Строка
СтраховойНомерПФР : Строка
ВзносыРаботника : Число 15, 2
ВзносыРаботодателя : Число 15, 2
..Движения..
НачисленияУдержанияПоСотрудникам : Обороты
СведенияОДоходахСтраховыеВзносы : Обороты
СведенияОДоходахНДФЛ : Обороты
}
@enduml
