@startuml РазрешениеНаЗаменуМатериалов
'!include templates.wsd
'..\include templates.wsd
class Документ.РазрешениеНаЗаменуМатериалов as "Разрешение на замену материалов" <<Документы>>
{
..Реквизиты..
ЗаказНаПроизводство : Документ.Заказ на производство\rДокумент.Заказ на производство
Спецификация : Справочник.Ресурсная спецификация
Изделие : Справочник.Номенклатура
ХарактеристикаИзделия : Справочник.Характеристика номенклатуры
ЗаказКлиента : Документ.Заказ клиента
ДатаНачалаДействия : Дата
ДатаОкончанияДействия : Дата
Статус : Статусы разрешений на замену материалов
УказаниеПоПрименению : Строка
Ответственный : Справочник.Пользователь
Подразделение : Справочник.Подразделение
..Табличная часть \n Материалы..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Количество : Число 15, 3
КоличествоУпаковок : Число 15, 3
Упаковка : Справочник.Упаковка
КлючСвязиСпецификация : Уникальный идентификатор
..Табличная часть \n Аналоги..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Количество : Число 15, 3
КоличествоУпаковок : Число 15, 3
Упаковка : Справочник.Упаковка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
АналогиВПроизводстве : РегистрСведений
}
@enduml
