@startuml ОплатаДнейУходаЗаДетьмиИнвалидами
'!include templates.wsd
'..\include templates.wsd
class Документ.ОплатаДнейУходаЗаДетьмиИнвалидами as "Оплата дней ухода за детьми-инвалидами" <<Документы>>
{
..Реквизиты..
ПериодРегистрации : Дата
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
ВидРасчета : Начисление
ДатаНачалаСобытия : Дата
ПериодРасчетаСреднегоЗаработкаНачало : Дата
ПериодРасчетаСреднегоЗаработкаОкончание : Дата
ФиксПериодРасчетаСреднегоЗаработка : Булево
УдалитьПереноситьДанныеВДругойУчетСреднегоЗаработка : Булево
СреднийЗаработок : Число 15, 2
Начислено : Число 13, 2
Удержано : Число 13, 2
ДатаНачала : Дата
ДатаОкончания : Дата
ПорядокВыплаты : Характер выплаты зарплаты
ПланируемаяДатаВыплаты : Дата
ИсправленныйДокумент : Документ.Оплата дней ухода за детьми-инвалидами
ДокументРассчитан : Булево
Рассчитал : Справочник.Пользователь
ПредставлениеПериода : Строка
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ГлавныйБухгалтер : Справочник.Физическое лицо
Бухгалтер : Справочник.Физическое лицо
Исполнитель : Справочник.Физическое лицо
ДолжностьИсполнителя : Справочник.Должность
СведенияОВторомРодителе : Строка
КоличествоЛистовПриложенныхДокументов : Число 2, 0
Ответственный : Справочник.Пользователь
Комментарий : Строка
СохраняемоеДенежноеСодержание : Число 13, 2
РасчетДенежногоСодержания : Булево
ДоначислитьЗарплатуПриНеобходимости : Булево
..Табличная часть \n ДанныеОбИндексации..
Сотрудник : Справочник.Сотрудник
Период : Дата
КоэффициентИндексации : Число 9, 8
..Табличная часть \n ДниУхода..
Дата : Дата
..Табличная часть \n НДФЛ..
ФизическоеЛицо : Справочник.Физическое лицо
МесяцНалоговогоПериода : Дата
Подразделение : Справочник.Территория\rСправочник.Подразделение
Налог : Число 10, 0
ЗачтеноАвансовыхПлатежей : Число 10, 0
УдалитьНалогКЗачетуВозврату : Число 10, 0
ПримененныйВычетЛичный : Число 12, 2
ПримененныйВычетЛичныйКодВычета : Справочник.Вид вычетов НДФЛ
УдалитьПримененныйВычетЛичныйКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
ПримененныйВычетЛичныйКЗачетуВозврату : Число 12, 2
ПримененныйВычетЛичныйКЗачетуВозвратуКодВычета : Справочник.Вид вычетов НДФЛ
УдалитьПримененныйВычетЛичныйКЗачетуВозвратуКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
ИдентификаторСтрокиНДФЛ : Число 7, 0
ФиксСтрока : Булево
ФиксРасчет : Булево
КатегорияДохода : Категории доходов НДФЛ
..Табличная часть \n Начисления..
Начисление : Начисление
ДатаНачала : Дата
ДатаОкончания : Дата
Результат : Число 13, 2
Подразделение : Справочник.Подразделение
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
Сотрудник : Справочник.Сотрудник
ВидЗанятости : Виды занятости
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ВидУчетаВремени : Справочник.Вид рабочего времени
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
ВремяВЧасах : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ПериодРегистрацииВремени : Дата
СуммаВычета : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
ОплаченоДней : Число 15, 2
ОплаченоЧасов : Число 15, 2
ПериодДействия : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n НачисленияПерерасчет..
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Результат : Число 13, 2
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
НормаДней : Число 7, 2
НормаЧасов : Число 7, 2
Сторно : Булево
СторнируемыйДокумент : Документ.Приз, подарок\rДокумент.Простой сотрудников\rДокумент.Отпуск без сохранения оплаты списком\r...
Сотрудник : Справочник.Сотрудник
ВидЗанятости : Виды занятости
РасчетнаяБазаЗаЕдиницуНормыВремени : Число 15, 2
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
СуммаВычета : Число 15, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ФиксСтрока : Булево
ФиксЗаполнение : Булево
ФиксРасчетВремени : Булево
ФиксРасчет : Булево
ФиксСторно : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ПериодРегистрацииВремени : Дата
ВремяВЧасах : Булево
ВидУчетаВремени : Справочник.Вид рабочего времени
ОплаченоДней : Число 15, 2
ОплаченоЧасов : Число 15, 2
РезультатВТомЧислеЗаСчетФБ : Число 15, 2
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ПериодДействия : Дата
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
..Табличная часть \n ОтработанноеВремяДляСреднегоОбщий..
Сотрудник : Справочник.Сотрудник
ПорядокРасчета : Порядок расчета среднего заработка общий
Период : Дата
ОтработаноДней : Число 7, 2
ОтработаноДнейПятидневка : Число 7, 2
ОтработаноЧасов : Число 7, 2
ОтработаноДнейШестидневка : Число 7, 2
ОтработаноДнейКалендарных : Число 7, 2
НормаДнейПроизводственныйКалендарь : Число 7, 2
ОтработаноЧасовПятидневка : Число 5, 2
НормаЧасовПроизводственныйКалендарь : Число 5, 2
УдалитьКорректировка : Булево
Источник : Источники данных для расчета среднего заработка
..Табличная часть \n Показатели..
Показатель : Справочник.Показатель
Значение : Число 15, 5
ИдентификаторСтрокиВидаРасчета : Число 7, 0
..Табличная часть \n ПримененныеВычетыНаДетейИИмущественные..
КодВычета : Справочник.Вид вычетов НДФЛ
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
РазмерВычета : Число 12, 2
ИдентификаторСтрокиНДФЛ : Число 7, 0
..Табличная часть \n СреднийЗаработокОбщий..
Сотрудник : Справочник.Сотрудник
ПорядокРасчета : Порядок расчета среднего заработка общий
СоставнаяЧасть : Учет начислений в среднем заработке общий
СтатьяФинансирования : Справочник.Статья финансирования
Период : Дата
Индексируется : Булево
Сумма : Число 15, 2
УдалитьКорректировка : Булево
Год : Число 4, 0
ДатаНачалаБазовогоПериода : Дата
КоличествоМесяцев : Число 3, 0
Источник : Источники данных для расчета среднего заработка
..Табличная часть \n Удержания..
ФизическоеЛицо : Справочник.Физическое лицо
ДатаНачала : Дата
ДатаОкончания : Дата
ДокументОснование : Документ.Удержание по прочим операциям\rДокумент.Удержание добровольных взносов в НПФ\rДокумент.Удержание профсоюзных взносов\r...
Получатель : Справочник.Контрагент
ПлатежныйАгент : Справочник.Контрагент
Удержание : Удержание
ФиксРасчет : Булево
Результат : Число 13, 2
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Сотрудник : Справочник.Сотрудник
ФиксСторно : Булево
..Табличная часть \n РаспределениеРезультатовНачислений..
ИдентификаторСтроки : Число 7, 0
Территория : Справочник.Территория
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОблагаетсяЕНВД : Булево
Результат : Число 13, 2
..Табличная часть \n РаспределениеРезультатовУдержаний..
ИдентификаторСтроки : Число 7, 0
ВидУдержания : Виды особых начислений и удержаний\rУдержание
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
Результат : Число 13, 2
..Табличная часть \n РаспределениеПоТерриториямУсловиямТруда..
ИдентификаторСтроки : Число 7, 0
Территория : Справочник.Территория
УсловияТруда : Справочник.Условия труда
ДоляРаспределения : Число 15, 5
Результат : Число 15, 2
ИдентификаторСтрокиПоказателей : Число 7, 0
СуммаВычета : Число 13, 0
..Табличная часть \n КорректировкиВыплаты..
ФизическоеЛицо : Справочник.Физическое лицо
КорректировкаВыплаты : Число 15, 2
ИдентификаторСтроки : Число 7, 0
ФиксСтрока : Булево
ФиксРасчет : Булево
..Табличная часть \n НачисленияПерерасчетНулевыеСторно..
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ДатаОкончания : Дата
Начисление : Начисление
Сторно : Булево
СторнируемыйДокумент : Документ.Приз, подарок\rДокумент.Простой сотрудников\rДокумент.Отпуск без сохранения оплаты списком\r...
Сотрудник : Справочник.Сотрудник
ВидЗанятости : Виды занятости
ИдентификаторСтрокиВидаРасчета : Число 7, 0
ГрафикРаботы : Справочник.Сотрудник\rСправочник.График работы
ФиксСторно : Булево
ГрафикРаботыНорма : Справочник.Сотрудник\rСправочник.График работы
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ПериодДействия : Дата
Результат : Число 13, 2
ФиксРасчет : Булево
ФиксЗаполнение : Булево
ОбщийГрафик : Справочник.График работы
ПериодРегистрацииНормыВремени : Дата
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
..Табличная часть \n ДенежноеСодержание..
Сотрудник : Справочник.Сотрудник
Начисление : Начисление
НазначениеРасчета : Строка
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Результат : Число 15, 2
ФиксРасчет : Булево
..Табличная часть \n ДенежноеСодержаниеФактическиеНачисления..
Сотрудник : Справочник.Сотрудник
НазначениеРасчета : Строка
Период : Дата
Сумма : Число 15, 2
Корректировка : Булево
Начисление : Начисление
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
Удержания : РегистрРасчета
РасчетыНалогоплательщиковСБюджетомПоНДФЛ : Остатки
ДанныеОВремениДляРасчетаСреднегоФСС : РегистрСведений
ЗначенияПоказателейУдержаний : РегистрСведений
ВзаиморасчетыССотрудниками : Остатки
ОтработанноеВремяПоСотрудникамАвансом : Обороты
НачисленияУдержанияПоСотрудникам : Обороты
ОтработанноеВремяПоСотрудникамКорректировка : Обороты
РасчетыСФондамиПоСтраховымВзносам : Остатки
ПорядокВыплатыДокументов : РегистрСведений
ПособияПоСоциальномуСтрахованию : Обороты
УдержанияДоПределаПоСотрудникам : Остатки
ДанныеСостоянийСотрудников : РегистрСведений
РаспределениеПоТерриториямУсловиямТруда : РегистрСведений
БухгалтерскиеВзаиморасчетыССотрудниками : Остатки
ДанныеОВремениДляРасчетаСреднегоОбщий : Обороты
ФактическиеОтпуска : Обороты
СведенияОДоходахСтраховыеВзносы : Обороты
ИмущественныеВычетыНДФЛ : Остатки
ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаОбщий : Обороты
ЗначенияПоказателейНачислений : РегистрСведений
ПредоставленныеСтандартныеИСоциальныеВычетыНДФЛ : Обороты
ЗарплатаКВыплатеАвансом : Остатки
УдержанияПоИсполнительнымДокументам : Обороты
ОтработанноеВремяПоСотрудникам : Обороты
Начисления : РегистрРасчета
СведенияОДоходахНДФЛ : Обороты
НачисленияУдержанияПоСотрудникамАвансом : Обороты
БухучетНачисленияУдержанияПоСотрудникам : Обороты
ЗарплатаКВыплате : Остатки
ПараметрыПериодовСтажаПФР : РегистрСведений
ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаФСС : Обороты
АвансовыеПлатежиИностранцевПоНДФЛ : Остатки
}
@enduml
