@startuml НазначениеОпросов
'!include templates.wsd
'..\include templates.wsd
class Документ.НазначениеОпросов as "Проведение опросов" <<Документы>>
{
..Реквизиты..
ШаблонАнкеты : Справочник.Шаблон анкеты
ТипРеспондентов : Справочник.Пользователь\rСправочник.Партнер\rСправочник.Контактное лицо\r...
ДатаНачала : Дата
ДатаОкончания : Дата
ВозможностьПредварительногоСохранения : Булево
СвободныйОпрос : Булево
Наименование : Строка
ПоказыватьВАрхивеАнкет : Булево
Комментарий : Строка
..Табличная часть \n Респонденты..
Респондент : Справочник.Пользователь\rСправочник.Партнер\rСправочник.Контактное лицо\r...
}
@enduml
