@startuml ПачкаРазделов6РасчетаРСВ_1
'!include templates.wsd
'..\include templates.wsd
class Документ.ПачкаРазделов6РасчетаРСВ_1 as "Пачка разделов 6 РСВ-1" <<Документы>>
{
..Реквизиты..
ОтчетныйПериод : Дата
Организация : Справочник.Организация
ТипСведенийСЗВ : Типы сведений СЗВ
КорректируемыйПериод : Дата
НомерПачки : Число 5, 0
РегистрационныйНомерПФРвКорректируемыйПериод : Строка
ИмяФайлаДляПФР : Строка
ДокументПринятВПФР : Булево
Руководитель : Справочник.Физическое лицо
ДолжностьРуководителя : Справочник.Должность
ФайлСформирован : Булево
ОкончаниеОтчетногоПериода : Дата
КраткийСоставДокумента : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
СпециальныйДокумент2015года : Булево
..Табличная часть \n Сотрудники..
Сотрудник : Справочник.Физическое лицо
СтраховойНомерПФР : Строка
Фамилия : Строка
Имя : Строка
Отчество : Строка
СотрудникУволен : Булево
НачисленоСтраховая : Число 15, 2
ДоначисленоСтраховая : Число 15, 2
ФиксСтаж : Булево
ФиксНачисленныеВзносы : Булево
ФиксЗаработок : Булево
..Табличная часть \n СведенияОЗаработке..
Сотрудник : Справочник.Физическое лицо
КатегорияЗастрахованныхЛиц : Категории застрахованных лиц для ПФР
Месяц : Число 2, 0
Заработок : Число 15, 2
ОблагаетсяВзносамиДоПредельнойВеличины : Число 15, 2
ПоДоговорамГПХДоПредельнойВеличины : Число 15, 2
ОблагаетсяВзносамиСвышеПредельнойВеличины : Число 15, 2
..Табличная часть \n СведенияОЗаработкеНаВредныхИТяжелыхРаботах..
Сотрудник : Справочник.Физическое лицо
КлассУсловийТруда : Классы условий труда по результатам специальной оценки
Месяц : Число 2, 0
ОблагаетсяВзносамиЗаЗанятыхНаПодземныхИВредныхРаботах : Число 15, 2
ОблагаетсяВзносамиЗаЗанятыхНаТяжелыхИПрочихРаботах : Число 15, 2
..Табличная часть \n ЗаписиОСтаже..
Сотрудник : Справочник.Физическое лицо
НомерОсновнойЗаписи : Число 2, 0
НомерДополнительнойЗаписи : Число 2, 0
ДатаНачалаПериода : Дата
ДатаОкончанияПериода : Дата
ОсобыеУсловияТруда : Справочник.Особое условие труда
УдалитьОсобыеУсловияТруда : Справочник.(не используется) Особые условия труда ПФР
КодПозицииСписка : Справочник.Льготная профессия (ПФР)
ОснованиеИсчисляемогоСтажа : Справочник.Основание для исчисления стажа
УдалитьОснованиеИсчисляемогоСтажа : Справочник.(не используется) Основания для исчисления стажа
ПервыйПараметрИсчисляемогоСтажа : Число 3, 0
ВторойПараметрИсчисляемогоСтажа : Число 2, 0
ТретийПараметрИсчисляемогоСтажа : Справочник.Доп. сведение для исчисления стажа
УдалитьТретийПараметрИсчисляемогоСтажа : Справочник.(не используется) Доп. сведения для исчисления стажа
ОснованиеВыслугиЛет : Справочник.Основание для досрочной пенсии
УдалитьОснованиеВыслугиЛет : Справочник.(не используется) Основания для досрочной пенсии
ПервыйПараметрВыслугиЛет : Число 4, 0
ВторойПараметрВыслугиЛет : Число 4, 0
ТретийПараметрВыслугиЛет : Число 5, 2
ТерриториальныеУсловия : Справочник.Территориальное условие
УдалитьТерриториальныеУсловия : Справочник.(не используется) Территориальные условия
ПараметрТерриториальныхУсловий : Число 3, 2
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
..Табличная часть \n КорректирующиеСведения..
Сотрудник : Справочник.Физическое лицо
КорректируемыйПериод : Дата
ДоначисленоНаОПС : Число 15, 2
ДоначисленоСтраховая : Число 15, 2
ДоначисленоНакопительная : Число 15, 2
..Движения..
СтраховыеВзносыПереданныеВПФР : Остатки
}
@enduml
