@startuml РегламентнаяОперацияМеждународныйУчет
'!include templates.wsd
'..\include templates.wsd
class Документ.РегламентнаяОперацияМеждународныйУчет as "Регламентная операция (международный учет)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ТипОперации : Типы регламентных операций (международный учет)
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Движения..
ФактическиеДанныеБюджетирования : Обороты
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
}
@enduml
