@startuml ПрочиеДоходыРасходы
'!include templates.wsd
'..\include templates.wsd
class Документ.ПрочиеДоходыРасходы as "Отражение прочих доходов и расходов" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ОрганизацияПолучатель : Справочник.Организация
Комментарий : Строка
Валюта : Справочник.Валюта
Ответственный : Справочник.Пользователь
Основание : Строка
ХозяйственнаяОперация : Хозяйственные операции
РаспределитьРасходыУпр : Булево
РаспределитьРасходыРегл : Строка
..Табличная часть \n ПрочиеРасходы..
Подразделение : Справочник.Подразделение
НаправлениеДеятельности : Справочник.Направление деятельности
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
СтатьяАктивовПассивов : Статья актива/пассива
КорНаправлениеДеятельности : Справочник.Направление деятельности
КорСтатьяРасходов : Статья расходов
КорАналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
Сумма : Число 15, 2
СуммаБезНДС : Число 15, 2
СуммаРегл : Число 15, 2
ПостояннаяРазница : Число 15, 2
ВременнаяРазница : Число 15, 2
ДатаОтражения : Дата
ИдентификаторСтроки : Строка
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
КорПодразделение : Справочник.Подразделение
СуммаУпр : Число 15, 2
..Табличная часть \n ПрочиеДоходы..
Подразделение : Справочник.Подразделение
НаправлениеДеятельности : Справочник.Направление деятельности
СтатьяДоходов : Статьи доходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
СтатьяАктивовПассивов : Статья актива/пассива
КорНаправлениеДеятельности : Справочник.Направление деятельности
КорСтатьяДоходов : Статьи доходов
КорАналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
Сумма : Число 15, 2
ДатаОтражения : Дата
ИдентификаторСтроки : Строка
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
КорПодразделение : Справочник.Подразделение
СуммаРегл : Число 15, 2
ПостояннаяРазница : Число 15, 2
ВременнаяРазница : Число 15, 2
СуммаУпр : Число 15, 2
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Движения..
ПрочиеДоходы : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
ДетализацияПартийТоваровДляНДСиУСН : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
РасходыПриУСНМатериалы : Остатки
РасходыПриУСН : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
Закупки : Обороты
РасходыПриУСНТовары : Остатки
КнигаУчетаДоходовИРасходов : Обороты
ВыручкаИСебестоимостьПродаж : Обороты
}
@enduml
