@startuml РасчетКурсовыхРазниц
'!include templates.wsd
'..\include templates.wsd
class Документ.РасчетКурсовыхРазниц as "Расчет курсовых разниц" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ХозяйственнаяОперация : Хозяйственные операции
ПереоценкаПоДням : Булево
Комментарий : Строка
..Движения..
ДенежныеСредстваУПодотчетныхЛиц : Остатки
ПрочиеДоходы : Остатки
ПрочиеРасходы : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДенежныеСредстваБезналичные : Остатки
ДвиженияКонтрагентДоходыРасходы : Обороты
ДенежныеСредстваНаличные : Остатки
ДенежныеСредстваВПути : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ДенежныеСредстваВКассахККМ : Остатки
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
РасчетыСКлиентамиПоДокументам : Остатки
РасчетыСПоставщикамиПоДокументам : Остатки
ДвиженияДенежныеСредстваДоходыРасходы : Обороты
ДенежныеДокументы : Остатки
РасчетыПоДоговорамКредитовИДепозитов : Остатки
}
@enduml
