@startuml АмортизацияНМАМеждународныйУчет
'!include templates.wsd
'..\include templates.wsd
class Документ.АмортизацияНМАМеждународныйУчет as "Амортизация НМА (международный учет)" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Движения..
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ФактическиеДанныеБюджетирования : Обороты
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
ВыручкаИСебестоимостьПродаж : Обороты
}
@enduml
