@startuml ОписьЗаявленийСотрудниковНаВыплатуПособий
'!include templates.wsd
'..\include templates.wsd
class Документ.ОписьЗаявленийСотрудниковНаВыплатуПособий as "Опись заявлений сотрудников на выплату пособий" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
СтатусДокумента : Статусы заявлений и реестров на выплату пособий
НаименованиеОрганизации : Строка
РегистрационныйНомерФСС : Строка
КодПодчиненностиФСС : Строка
ИНН : Строка
КПП : Строка
ДополнительныйКодФСС : Строка
НаименованиеТерриториальногоОрганаФСС : Строка
Телефон : Строка
ДолжностьУполномоченного : Справочник.Должность
ФИОУполномоченного : Строка
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n Заявления..
Заявление : Документ.Заявление сотрудника на выплату пособия
КраткоеНаименованиеДокументов : Строка
КоличествоСтраниц : Число 2, 0
..Табличная часть \n ФизическиеЛица..
ФизическоеЛицо : Справочник.Физическое лицо
}
@enduml
