@startuml РаспределениеРасходовБудущихПериодов
'!include templates.wsd
'..\include templates.wsd
class Документ.РаспределениеРасходовБудущихПериодов as "Распределение расходов будущих периодов" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
СуммаДокумента : Число 15, 2
НачалоПериода : Дата
КонецПериода : Дата
КоличествоМесяцев : Число 10, 0
Ответственный : Справочник.Пользователь
Комментарий : Строка
СуммаДокументаРегл : Число 15, 2
СуммаДокументаПР : Число 15, 2
СуммаДокументаВР : Число 15, 2
НаправлениеДеятельности : Справочник.Направление деятельности
СуммаДокументаУпр : Число 15, 2
ПравилоРаспределения : Правила распределения РБП
ВариантУказанияСуммыУпр : Варианты указания суммы РБП
ВариантУказанияСуммыРегл : Варианты указания суммы РБП
..Табличная часть \n РаспределениеРасходов..
Дата : Дата
Подразделение : Справочник.Подразделение
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Сумма : Число 15, 2
СуммаРегл : Число 15, 2
ПостояннаяРазница : Число 15, 2
ВременнаяРазница : Число 15, 2
ДоляСтоимости : Число 15, 2
СуммаУпр : Число 15, 2
..Движения..
ПрочиеРасходы : Остатки
СебестоимостьТоваров : Остатки
ДвиженияНоменклатураДоходыРасходы : Обороты
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
ДетализацияПартийТоваровДляНДСиУСН : Остатки
ПартииРасходовНаСебестоимостьТоваров : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
Закупки : Обороты
}
@enduml
