@startuml ИзменениеПараметровНМА2_4
'!include templates.wsd
'..\include templates.wsd
class Документ.ИзменениеПараметровНМА2_4 as "Изменение параметров НМА" <<Документы>>
{
..Реквизиты..
ОтражатьВУпрУчете : Булево
ОтражатьВРеглУчете : Булево
Организация : Справочник.Организация
ПорядокУчета : Порядок учета стоимости внеоборотных активов
ПорядокУчетаФлаг : Булево
СпособНачисленияАмортизацииУУ : Способы начисления амортизации нематериальных активов
СпособНачисленияАмортизацииУУФлаг : Булево
СрокИспользованияУУ : Число 10, 0
СрокИспользованияУУФлаг : Булево
ОбъемНаработки : Число 15, 3
ОбъемНаработкиФлаг : Булево
КоэффициентУскоренияУУ : Число 4, 3
КоэффициентУскоренияУУФлаг : Булево
СпециальныйКоэффициентНУ : Число 5, 2
СпециальныйКоэффициентНУФлаг : Булево
ЛиквидационнаяСтоимость : Число 15, 2
ЛиквидационнаяСтоимостьФлаг : Булево
ГруппаФинансовогоУчета : Справочник.Группа финансового учета внеоборотных активов
ГруппаФинансовогоУчетаФлаг : Булево
АмортизационныеРасходыФлаг : Булево
СуммаКоэффициентовАмортизации : Число 10, 0
ДокументОснование : Документ.Принятие к учету НМА\rДокумент.Перемещение НМА
ДокументВДругомУчете : Документ.Изменение параметров НМА
Ответственный : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n НМА..
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
..Табличная часть \n АмортизационныеРасходы..
Подразделение : Справочник.Подразделение
НаправлениеДеятельности : Справочник.Направление деятельности
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ПередаватьРасходыВДругуюОрганизацию : Булево
ОрганизацияПолучательРасходов : Справочник.Организация
Коэффициент : Число 10, 0
СуммаКоэффициентовПредыдущихСтрок : Число 10, 0
..Движения..
ПорядокУчетаНМА : РегистрСведений
СчетаБухгалтерскогоУчетаНМА : РегистрСведений
ПорядокУчетаНМАУУ : РегистрСведений
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияДоходыРасходыПрочиеАктивыПассивы : Обороты
НачислениеАмортизацииНМАСпециальныйКоэффициентНалоговыйУчет : РегистрСведений
СтоимостьНМА : Остатки
Хозрасчетный : РегистрБухгалтерии
ПорядокУчетаНМАБУ : РегистрСведений
ОтражениеДокументовВМеждународномУчете : РегистрСведений
АмортизацияНМА : Остатки
Международный : РегистрБухгалтерии
ПараметрыАмортизацииНМАБУ : РегистрСведений
ПараметрыАмортизацииНМАУУ : РегистрСведений
СпособыОтраженияРасходовПоАмортизацииНМАБухгалтерскийУчет : РегистрСведений
}
@enduml
