@startuml СписаниеЗадолженности
'!include templates.wsd
'..\include templates.wsd
class Документ.СписаниеЗадолженности as "Корректировка задолженности" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Контрагент : Справочник.Организация\rСправочник.Контрагент
ХозяйственнаяОперация : Хозяйственные операции
СтатьяРасходов : Статья расходов\rСтатья актива/пассива
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
СтатьяДоходов : Статья актива/пассива\rСтатьи доходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
Подразделение : Справочник.Подразделение
Комментарий : Строка
РасчетыМеждуОрганизациями : Булево
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
Основание : Документ.Приобретение товаров и услуг
АктОРасхожденияхОснование : Документ.Акт о расхождениях после приемки
..Табличная часть \n Задолженность..
ТипРасчетов : Типы расчетов с партнерами
Партнер : Справочник.Партнер
Заказ : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
ВалютаВзаиморасчетов : Справочник.Валюта
Сумма : Число 15, 2
ИдентификаторСтроки : Строка
..Движения..
ПрочиеДоходы : Остатки
РасчетыСКлиентами : Остатки
ПрочиеРасходы : Остатки
СуммыДокументовВВалютеРегл : РегистрСведений
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ДвиженияКонтрагентДоходыРасходы : Обороты
РасходыПриУСНОСиНМА : Остатки
РасходыПриУСНМатериалы : Остатки
РасходыПриУСН : Остатки
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
РасчетыСПоставщиками : Остатки
Международный : РегистрБухгалтерии
РасходыПриУСНТовары : Остатки
РасчетыСКлиентамиПоДокументам : Остатки
РасчетыСПоставщикамиПоДокументам : Остатки
КнигаУчетаДоходовИРасходов : Обороты
}
@enduml
