@startuml ЗапросНаВыпискуИзЕГРЮЛ_ЕГРИП
'!include templates.wsd
'..\include templates.wsd
class Документ.ЗапросНаВыпискуИзЕГРЮЛ_ЕГРИП as "Запрос на выписку из ЕГРЮЛ/ЕГРИП" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
ПараметрЗапроса : Строка
ВидПараметраЗапроса : Виды параметров запроса на выписку из ЕГРЮЛ/ЕГРИП
Контрагент : Справочник.Контрагент
}
@enduml
