@startuml ПогашениеСтоимостиТМЦВЭксплуатации
'!include templates.wsd
'..\include templates.wsd
class Документ.ПогашениеСтоимостиТМЦВЭксплуатации as "Погашение стоимости ТМЦ в эксплуатации" <<Документы>>
{
..Реквизиты..
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
НомерПакета : Число 10, 0
Комментарий : Строка
..Табличная часть \n Расходы..
Подразделение : Справочник.Подразделение
Номенклатура : Справочник.Номенклатура
ФизическоеЛицо : Справочник.Физическое лицо
ПартияТМЦВЭксплуатации : Справочник.Партии ТМЦ в эксплуатации
СуммаБУ : Число 15, 2
СуммаНУ : Число 15, 2
СуммаПР : Число 15, 2
СуммаВР : Число 15, 2
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Количество : Число 15, 3
..Табличная часть \n Списания..
Подразделение : Справочник.Подразделение
Номенклатура : Справочник.Номенклатура
ФизическоеЛицо : Справочник.Физическое лицо
ПартияТМЦВЭксплуатации : Справочник.Партии ТМЦ в эксплуатации
СуммаБУ : Число 15, 2
СуммаНУ : Число 15, 2
СуммаПР : Число 15, 2
СуммаВР : Число 15, 2
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Количество : Число 15, 3
..Табличная часть \n Перемещения..
Подразделение : Справочник.Подразделение
Номенклатура : Справочник.Номенклатура
ФизическоеЛицо : Справочник.Физическое лицо
ПартияТМЦВЭксплуатации : Справочник.Партии ТМЦ в эксплуатации
СуммаБУ : Число 15, 2
СуммаНУ : Число 15, 2
СуммаПР : Число 15, 2
СуммаВР : Число 15, 2
ПодразделениеПолучатель : Справочник.Подразделение
ФизическоеЛицоПолучатель : Справочник.Физическое лицо
Количество : Число 15, 3
..Табличная часть \n СписанияЗабалансовыйУчет..
Подразделение : Справочник.Подразделение
Номенклатура : Справочник.Номенклатура
ФизическоеЛицо : Справочник.Физическое лицо
ПартияТМЦВЭксплуатации : Справочник.Партии ТМЦ в эксплуатации
Сумма : Число 15, 2
Количество : Число 15, 3
..Табличная часть \n ПеремещенияЗабалансовыйУчет..
Подразделение : Справочник.Подразделение
Номенклатура : Справочник.Номенклатура
ФизическоеЛицо : Справочник.Физическое лицо
ПартияТМЦВЭксплуатации : Справочник.Партии ТМЦ в эксплуатации
Сумма : Число 15, 2
ПодразделениеПолучатель : Справочник.Подразделение
ФизическоеЛицоПолучатель : Справочник.Физическое лицо
Количество : Число 15, 3
..Табличная часть \n Доходы..
Подразделение : Справочник.Подразделение
Номенклатура : Справочник.Номенклатура
ФизическоеЛицо : Справочник.Физическое лицо
ПартияТМЦВЭксплуатации : Справочник.Партии ТМЦ в эксплуатации
СуммаБУ : Число 15, 2
СуммаНУ : Число 15, 2
СуммаПР : Число 15, 2
СуммаВР : Число 15, 2
СтатьяДоходов : Статьи доходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
Количество : Число 15, 3
Склад : Справочник.Склад (складская территория)
..Табличная часть \n Возвраты..
Подразделение : Справочник.Подразделение
Номенклатура : Справочник.Номенклатура
ФизическоеЛицо : Справочник.Физическое лицо
ПартияТМЦВЭксплуатации : Справочник.Партии ТМЦ в эксплуатации
СуммаБУ : Число 15, 2
СуммаНУ : Число 15, 2
СуммаПР : Число 15, 2
СуммаВР : Число 15, 2
Количество : Число 15, 3
Склад : Справочник.Склад (складская территория)
..Движения..
ПрочиеРасходы : Остатки
ПартииПрочихРасходов : Остатки
ПрочиеАктивыПассивы : Остатки
ОтражениеДокументовВРеглУчете : РегистрСведений
ФактическиеДанныеБюджетирования : Обороты
Хозрасчетный : РегистрБухгалтерии
ОтражениеДокументовВМеждународномУчете : РегистрСведений
Международный : РегистрБухгалтерии
ВыручкаИСебестоимостьПродаж : Обороты
}
@enduml
