@startuml УчетныеЗаписиСинхронизацииФайлов
'!include templates.wsd
'..\include templates.wsd
class Справочник.УчетныеЗаписиСинхронизацииФайлов as "Учетные записи синхронизации файлов" <<Справочники>>
{
..Реквизиты..
Сервис : Строка
КорневаяПапка : Строка
АвторФайлов : Справочник.Внешний пользователь\rСправочник.Пользователь
}
@enduml
