@startuml НаборыДополнительныхРеквизитовИСведений
'!include templates.wsd
'..\include templates.wsd
class Справочник.НаборыДополнительныхРеквизитовИСведений as "Наборы дополнительных реквизитов и сведений" <<Справочники>>
{
..Реквизиты..
КоличествоРеквизитов : Строка
КоличествоСведений : Строка
Используется : Булево
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
ПометкаУдаления : Булево
..Табличная часть \n ДополнительныеСведения..
Свойство : Дополнительный реквизит / сведение
ПометкаУдаления : Булево
}
@enduml
