@startuml ВидыДокументовВводДанныхДляРасчетаЗарплаты
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыДокументовВводДанныхДляРасчетаЗарплаты as "Шаблоны ввода исходных данных" <<Справочники>>
{
..Реквизиты..
РеквизитДопУпорядочивания : Число 5, 0
ПредставлениеДокумента : Строка
Подсказка : Строка
НесколькоОрганизаций : Булево
НесколькоПодразделений : Булево
НесколькоСотрудников : Булево
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ЗаполнятьСписокОбъектов : Булево
ПоказыватьПодразделение : Булево
ПроверятьЗаполнениеПодразделения : Булево
СпособПримененияЗначенийПоказателей : Способы применения значений показателей расчета зарплаты
ИспользоватьПериодОкончания : Булево
ЗначенияПоказателейВводятсяНаРазныеДаты : Булево
ВремяВводитсяСводно : Булево
ВремяВводитсяЗаМесяц : Булево
УдалитьИдентификаторОбъекта : Строка
ВидыРаботЗаполняютсяВДокументе : Булево
ВыполненныеРаботыРаспределяютсяПоСотрудникам : Булево
ВыполненныеРаботыРаспределяютсяСУчетомКоэффициентов : Булево
ВыполненныеРаботыРаспределяютсяСУчетомТарифныхСтавок : Булево
ВыполненныеРаботыРаспределяютсяСУчетомОтработанногоВремени : Булево
ВыполненныеРаботыВводятсяСводно : Булево
КраткийСостав : Строка
НеИспользуется : Булево
..Табличная часть \n Показатели..
Показатель : Справочник.Показатель
..Табличная часть \n ВидыВремени..
ВидВремени : Справочник.Вид рабочего времени
..Табличная часть \n ВидыРабот..
ВидРабот : Справочник.Вид работ сотрудников
..Табличная часть \n ВнешниеПечатныеФормы..
ПечатнаяФорма : Справочник.Дополнительный отчет или обработка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
