@startuml ГосударственныеКонтракты
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГосударственныеКонтракты as "Государственные контракты" <<Справочники>>
{
..Реквизиты..
ГоловнойИсполнитель : Справочник.Организация\rСправочник.Контрагент
УполномоченныйБанк : Справочник.Банк
Состояние : Состояния государственных контрактов
ДатаЗаключения : Дата
ГодЗаключения : Число 4, 0
ГодОкончанияСрокаДействия : Число 4, 0
КодСпособаОпределенияПоставщика : Число 1, 0
КодГосударственногоЗаказчика : Строка
ВидЦены : Число 1, 0
ДополнительныеРазряды : Строка
ПорядковыйНомер : Строка
Комментарий : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
