@startuml ВидыИспользованияРабочегоВремени
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыИспользованияРабочегоВремени as "Виды использования рабочего времени" <<Справочники>>
{
..Реквизиты..
УдалитьИдентификаторОбъекта : Строка
БуквенныйКод : Строка
ЦифровойКод : Строка
БуквенныйКодБюджетный : Строка
БуквенныйКодБюджетный2009 : Строка
ПолноеНаименование : Строка
РабочееВремя : Булево
ОсновноеВремя : Справочник.Вид рабочего времени
Целосменное : Булево
НеИспользуется : Булево
}
@enduml
