@startuml ВидыФинансовыхОтчетов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыФинансовыхОтчетов as "Виды финансовых отчетов" <<Справочники>>
{
..Реквизиты..
Комментарий : Строка
ВыводитьКодСтроки : Булево
ВыводитьПримечание : Булево
ВидПоказателей : Виды показателей отчетности
}
@enduml
