@startuml ОбщероссийскийКлассификаторПродукции
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОбщероссийскийКлассификаторПродукции as "ОКП" <<Справочники>>
{
..Реквизиты..
НаименованиеПолное : Строка
}
@enduml
