@startuml ПапкиЭлектронныхПисем
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПапкиЭлектронныхПисем as "Папки электронных писем" <<Справочники>>
{
..Реквизиты..
ПредопределеннаяПапка : Булево
}
@enduml
