@startuml СтрокиОтчетностиМониторингаРаботниковСоциальнойСферы
'!include templates.wsd
'..\include templates.wsd
class Справочник.СтрокиОтчетностиМониторингаРаботниковСоциальнойСферы as "Строки отчетности мониторинга работников социальной сферы" <<Справочники>>
{
..Реквизиты..
КодКатегорииПерсонала : Строка
ФормаМониторинга : Виды форм мониторинга работников социальной сферы
Пояснение : Строка
}
@enduml
