@startuml ИнформационныеСсылкиДляФорм
'!include templates.wsd
'..\include templates.wsd
class Справочник.ИнформационныеСсылкиДляФорм as "Информационные ссылки для форм" <<Справочники>>
{
..Реквизиты..
Адрес : Строка
УдалитьВерсияКонфигурацииДо : Число 20, 0
УдалитьВерсияКонфигурацииОт : Число 20, 0
Вес : Число 10, 0
ДатаНачалаАктуальности : Дата
ДатаОбновления : Дата
ИзКонфигурации : Булево
ДатаОкончанияАктуальности : Дата
Идентификатор : Строка
Подсказка : Строка
ПолныйПутьКФорме : Справочник.Путь к форме
}
@enduml
