@startuml КонтактныеЛицаПартнеров
'!include templates.wsd
'..\include templates.wsd
class Справочник.КонтактныеЛицаПартнеров as "Контактные лица" <<Справочники>>
{
..Реквизиты..
ДатаРегистрацииСвязи : Дата
ДатаПрекращенияСвязи : Дата
Автор : Справочник.Внешний пользователь\rСправочник.Пользователь
Комментарий : Строка
ДополнительнаяИнформация : Строка
ДолжностьПоВизитке : Строка
Пол : Пол физического лица
ДатаРождения : Дата
..Табличная часть \n КонтактнаяИнформация..
Тип : Типы контактной информации
Вид : Справочник.Вид контактной информации
Представление : Строка
ЗначенияПолей : Строка
Страна : Строка
Регион : Строка
Город : Строка
АдресЭП : Строка
ДоменноеИмяСервера : Строка
НомерТелефона : Строка
НомерТелефонаБезКодов : Строка
ВидДляСписка : Справочник.Вид контактной информации
..Табличная часть \n РолиКонтактногоЛица..
РольКонтактногоЛица : Справочник.Роль контактного лица партнера
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
