@startuml ПравилаРаспределенияРасходов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПравилаРаспределенияРасходов as "Правила распределения расходов" <<Справочники>>
{
..Реквизиты..
НазначениеПравила : Назначение показателей для распределения затрат
БазаРаспределения : Типы показателей для распределения статей расходов
СтатьяКалькуляции : Справочник.Статьи калькуляции
НаправлениеРаспределения : Способы распределения статей расходов
ПредставлениеПравила : Строка
..Табличная часть \n ОтборПоГруппамПродукции..
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
..Табличная часть \n ОтборПоМатериалам..
Материал : Справочник.Номенклатура
..Табличная часть \n ОтборПоВидамРабот..
ВидРабот : Справочник.Вид работ сотрудников
..Табличная часть \n ОтборПоПодразделениям..
Подразделение : Справочник.Подразделение
}
@enduml
