@startuml СерверыДокументооборота
'!include templates.wsd
'..\include templates.wsd
class Справочник.СерверыДокументооборота as "Серверы документооборота" <<Справочники>>
{
..Реквизиты..
АдресЭлектроннойПочтыФНС : Строка
ДлительностьОжиданияСервера : Число 5, 0
Сертификат : Строка
АдресЭлектроннойПочтыПФР : Строка
АдресЭлектроннойПочтыФСГС : Строка
}
@enduml
