@startuml ТарифыПлатежныхАгентов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ТарифыПлатежныхАгентов as "Тарифы платежных агентов" <<Справочники>>
{
..Реквизиты..
ИспользуетсяШкала : Булево
СпособВводаСуммы : Число 1, 0
..Табличная часть \n Шкала..
Порог : Число 15, 2
Процент : Число 4, 2
Сумма : Число 15, 2
МинимальнаяСумма : Число 15, 2
МаксимальнаяСумма : Число 15, 2
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
