@startuml СоставыВоеннослужащих
'!include templates.wsd
'..\include templates.wsd
class Справочник.СоставыВоеннослужащих as "Составы военнослужащих" <<Справочники>>
{
..Реквизиты..
РеквизитДопУпорядочивания : Число 5, 0
ОфицерскийСостав : Булево
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
