@startuml ОрганыПФР
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОрганыПФР as "Органы ПФР" <<Справочники>>
{
..Реквизиты..
ПринимаетМакетыПенсионныхДел : Булево
..Табличная часть \n Сертификаты..
Сертификат : Строка
}
@enduml
