@startuml УдалитьДокументыРеализацииПолномочийНалоговыхОрганов
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьДокументыРеализацииПолномочийНалоговыхОрганов as "(не используется) Документы реализации полномочий налоговых органов" <<Справочники>>
{
..Реквизиты..
НалоговыйОрган : Справочник.(не используется) Налоговые органы
Организация : Справочник.Организация
Идентификатор : Строка
ИдентификаторОснования : Строка
ВидДокумента : Строка\r(не используется) Виды налоговых документов
НомерДокумента : Строка
ДатаДокумента : Дата
ДатаСообщения : Дата
ДатаОтправки : Дата
}
@enduml
