@startuml ТипыПлатежейФЗ275
'!include templates.wsd
'..\include templates.wsd
class Справочник.ТипыПлатежейФЗ275 as "Типы платежей 275-ФЗ" <<Справочники>>
{
..Реквизиты..
ОписаниеПунктаЗакона : Строка
НомерПунктаЗакона : Строка
НеТребуютсяДокументыПодтвержденияИсполненияКонтракта : Булево
..Табличная часть \n ПодтверждающиеДокументы..
ВидДокумента : Справочник.Вид документа
}
@enduml
