@startuml СегментыПартнеров
'!include templates.wsd
'..\include templates.wsd
class Справочник.СегментыПартнеров as "Сегменты клиентов" <<Справочники>>
{
..Реквизиты..
ДатаОчистки : Дата
ДатаСоздания : Дата
Описание : Строка
Ответственный : Справочник.Пользователь
СпособФормирования : Способы формирования сегментов
СхемаКомпоновкиДанных : Хранилище значения
ПроверятьНаВхождениеПриСозданииНового : Булево
РегламентноеЗадание : Уникальный идентификатор
ХранилищеНастроекКомпоновкиДанных : Хранилище значения
ИмяШаблонаСКД : Строка
ЗапретОтгрузки : Булево
..Табличная часть \n ПартнерыПоСегменту..
Партнер : Справочник.Партнер
}
@enduml
