@startuml ВидыКонтактнойИнформации
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыКонтактнойИнформации as "Виды контактной информации" <<Справочники>>
{
..Реквизиты..
ТолькоНациональныйАдрес : Булево
ВидПоляДругое : Строка
ВключатьСтрануВПредставление : Булево
ЗапретитьРедактированиеПользователем : Булево
Используется : Булево
МожноИзменятьСпособРедактирования : Булево
ОбязательноеЗаполнение : Булево
ПроверятьКорректность : Булево
ПроверятьПоФИАС : Булево
РазрешитьВводНесколькихЗначений : Булево
РедактированиеТолькоВДиалоге : Булево
РеквизитДопУпорядочивания : Число 5, 0
СкрыватьНеактуальныеАдреса : Булево
ТелефонCДобавочнымНомером : Булево
Тип : Типы контактной информации
УдалитьМногострочноеПоле : Булево
УказыватьОКТМО : Булево
ХранитьИсториюИзменений : Булево
}
@enduml
