@startuml ТехнологическиеОперации
'!include templates.wsd
'..\include templates.wsd
class Справочник.ТехнологическиеОперации as "Технологические операции" <<Справочники>>
{
..Реквизиты..
НомерОперации : Число 5, 0
НомерСледующейОперации : Число 5, 0
РабочийЦентр : Справочник.Рабочий центр\rСправочник.Вид рабочего центра
СодержитВложенныйМаршрут : Булево
ВложенныйМаршрут : Справочник.Маршрутная карта
ВремяШтучное : Число 10, 1
ВремяШтучноеЕдИзм : Единицы измерения времени
ВремяПЗ : Число 10, 1
ВремяПЗЕдИзм : Единицы измерения времени
ВариантНаладки : Справочник.Вариант наладки
Загрузка : Число 15, 3
Непрерывная : Булево
Описание : Строка
Количество : Число 15, 3
ЕдиницаИзмерения : Справочник.Упаковка
Идентификатор : Число 5, 0
ПередаточнаяПартия : Число 10, 0
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n ВспомогательныеРабочиеЦентры..
РабочийЦентр : Справочник.Рабочий центр\rСправочник.Вид рабочего центра
}
@enduml
