@startuml ОснованияИсчисляемогоСтраховогоСтажа
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОснованияИсчисляемогоСтраховогоСтажа as "Основания для исчисления стажа" <<Справочники>>
{
}
@enduml
