@startuml ОчередьЗаданий
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОчередьЗаданий as "Очередь заданий" <<Справочники>>
{
..Реквизиты..
Использование : Булево
ЗапланированныйМоментЗапуска : Дата
СостояниеЗадания : Состояния заданий
ИсполняющееФоновоеЗадание : Уникальный идентификатор
ЭксклюзивноеВыполнение : Булево
НомерПопытки : Число 3, 0
ИмяМетода : Строка
Параметры : Хранилище значения
ДатаНачалаПоследнегоЗапуска : Дата
ДатаЗавершенияПоследнегоЗапуска : Дата
Ключ : Строка
ИнтервалПовтораПриАварийномЗавершении : Число 10, 0
Расписание : Хранилище значения
КоличествоПовторовПриАварийномЗавершении : Число 10, 0
}
@enduml
