@startuml НомераГТД
'!include templates.wsd
'..\include templates.wsd
class Справочник.НомераГТД as "Номера ГТД" <<Справочники>>
{
..Реквизиты..
СтранаПроисхождения : Справочник.Страна мира
РегистрационныйНомер : Строка
СтранаВвозаНеРФ : Булево
ПорядковыйНомерТовара : Строка
}
@enduml
