@startuml ЗначенияСвойствОбъектовИерархия
'!include templates.wsd
'..\include templates.wsd
class Справочник.ЗначенияСвойствОбъектовИерархия as "Дополнительные значения (иерархия)" <<Справочники>>
{
..Реквизиты..
Вес : Число 10, 2
ПолноеНаименование : Строка
}
@enduml
