@startuml МаршрутныеКарты
'!include templates.wsd
'..\include templates.wsd
class Справочник.МаршрутныеКарты as "Маршрутные карты" <<Справочники>>
{
..Реквизиты..
Статус : Статусы маршрутных карт
НачалоДействия : Дата
КонецДействия : Дата
ДляВидаИзделий : Справочник.Вид номенклатуры
Подразделение : Справочник.Подразделение
ПредварительныйБуфер : Число 10, 0
ЗавершающийБуфер : Число 10, 0
ЕдиницаИзмеренияПредварительногоБуфера : Единицы измерения времени
ЕдиницаИзмеренияЗавершающегоБуфера : Единицы измерения времени
ИспользоватьОперации : Булево
ИспользоватьВыходныеИзделия : Булево
ИспользоватьМатериалы : Булево
ИспользоватьТрудозатраты : Булево
МаксимальноеКоличествоЕдиницПартийИзделия : Число 15, 0
Ответственный : Справочник.Пользователь
Описание : Строка
РассчитыватьКоэффициент : Булево
КоэффициентЧислитель : Число 15, 3
КоэффициентЗнаменатель : Число 15, 3
..Табличная часть \n ВыходныеИзделия..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Упаковка : Справочник.Упаковка
Операция : Справочник.Операция
ОперацияРедактирование : Справочник.Операция
ДоляСтоимости : Число 10, 0
..Табличная часть \n ВозвратныеОтходы..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
Операция : Справочник.Операция
ОперацияРедактирование : Справочник.Операция
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
СтатьяКалькуляции : Справочник.Статьи калькуляции
ОписаниеИзделия : Строка
..Табличная часть \n МатериалыИУслуги..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Упаковка : Справочник.Упаковка
СтатьяКалькуляции : Справочник.Статьи калькуляции
СпособАвтовыбораНоменклатуры : Способы автовыбора номенклатуры
СпособАвтовыбораХарактеристики : Способы автовыбора характеристики
СвойствоСодержащееНоменклатуру : Дополнительный реквизит / сведение
ОтборСвойство : Дополнительный реквизит / сведение
ОтборЗначениеСвойства : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
АлгоритмРасчетаКоличества : Строка
ПрименениеМатериала : Строка
Операция : Справочник.Операция
ОперацияРедактирование : Справочник.Операция
КлючСвязи : Уникальный идентификатор
..Табличная часть \n Трудозатраты..
ВидРабот : Справочник.Вид работ сотрудников
Количество : Число 15, 3
СтатьяКалькуляции : Справочник.Статьи калькуляции
Операция : Справочник.Операция
ОперацияРедактирование : Справочник.Операция
НазначениеРабот : Строка
ОтборСвойство : Дополнительный реквизит / сведение
ОтборЗначениеСвойства : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
АлгоритмРасчетаКоличества : Строка
..Табличная часть \n СоответствиеСвойств..
СвойствоМатериала : Дополнительный реквизит / сведение
СвойствоПродукции : Дополнительный реквизит / сведение
ЗначениеСвойства : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ПредопределенноеЗначение : Булево
КлючСвязиМатериал : Уникальный идентификатор
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
