@startuml НематериальныеАктивы
'!include templates.wsd
'..\include templates.wsd
class Справочник.НематериальныеАктивы as "Нематериальные активы и расходы на НИОКР" <<Справочники>>
{
..Реквизиты..
НаименованиеПолное : Строка
ВидНМА : Виды НМА
АмортизационнаяГруппа : Амортизационные группы
ПрочиеСведения : Строка
ВидОбъектаУчета : Виды объектов учета НМА
ГруппаНМАМеждународныйУчет : Справочник.Группа нематериальных активов
НаправлениеДеятельности : Справочник.Направление деятельности
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
