@startuml ДоговорыКонтрагентов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ДоговорыКонтрагентов as "Договоры с контрагентами" <<Справочники>>
{
..Реквизиты..
БанковскийСчет : Справочник.Банковский счет организации
БанковскийСчетКонтрагента : Справочник.Банковский счет
ВалютаВзаиморасчетов : Справочник.Валюта
Комментарий : Строка
ДатаНачалаДействия : Дата
ДатаОкончанияДействия : Дата
Организация : Справочник.Организация
Контрагент : Справочник.Контрагент
Менеджер : Справочник.Пользователь
НаименованиеДляПечати : Строка
УчетАгентскогоНДС : Булево
ВидАгентскогоДоговора : Виды агентских договоров
Дата : Дата
Номер : Строка
Партнер : Справочник.Партнер
Подразделение : Справочник.Подразделение
ПорядокОплаты : Порядок оплаты
ПорядокРасчетов : Детализация расчетов
Согласован : Булево
Статус : Статусы договоров контрагентов
ХозяйственнаяОперация : Хозяйственные операции
ТипДоговора : Типы договоров
ОграничиватьСуммуЗадолженности : Булево
ДопустимаяСуммаЗадолженности : Число 15, 2
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
ЗапрещаетсяПросроченнаяЗадолженность : Булево
КонтактноеЛицо : Справочник.Контактное лицо
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
ИдентификаторПлатежа : Строка
УстановленСрокОплаты : Булево
СрокОплаты : Число 5, 0
Сумма : Число 15, 2
ЗаданГрафикИсполнения : Булево
ДоговорСУчастникомГОЗ : Булево
ГосударственныйКонтракт : Справочник.Государственный контракт
ПлатежиПо275ФЗ : Булево
ТипПлатежаФЗ275 : Справочник.Типы платежей 275-ФЗ
ИностранныйИсполнительВУтвержденномПеречнеГОЗ : Булево
ГрафикИсполненияДоговора : Документ.График исполнения договора
СуммаПрибыли : Число 15, 2
СуммаПредоплатыДоОтгрузки : Число 15, 2
НаправлениеДеятельности : Справочник.Направление деятельности
СтавкаНДС : Ставки НДС
ВариантОформленияЗакупок : Варианты оформления закупок
ОплатаРасходовПоТарифамСГосрегулированием : Булево
СтатьяКалькуляции : Справочник.Статьи калькуляции
КодРаздел7ДекларацииНДС : Справочник.Коды операций раздела 7 декларации по НДС
Назначение : Справочник.Назначение
ВыполненыОбязательстваПоДоговоруГОЗ : Булево
ВариантПриемкиТоваров : Варианты приемки товаров
ИдентификаторГосКонтракта : Строка
СпособДоставки : Способы доставки
ПеревозчикПартнер : Справочник.Партнер
ЗонаДоставки : Справочник.Зоны доставки
ВремяДоставкиС : Дата
ВремяДоставкиПо : Дата
АдресДоставки : Строка
АдресДоставкиЗначенияПолей : Строка
ДополнительнаяИнформацияПоДоставке : Строка
АдресДоставкиПеревозчика : Строка
АдресДоставкиПеревозчикаЗначенияПолей : Строка
АдресДоставкиДляПоставщика : Строка
..Табличная часть \n КалькуляцияЗатрат..
СтатьяКалькуляции : Справочник.Статьи калькуляции
Сумма : Число 15, 2
СуммаКВозмещению : Число 15, 2
..Табличная часть \n ДоговорыСЗаказчиками..
ДоговорСЗаказчиком : Справочник.Договор между организациями\rСправочник.Договор с контрагентом
Процент : Число 5, 2
..Табличная часть \n ПодтверждающиеДокументы..
ВидДокумента : Справочник.Вид документа
Номер : Строка
Дата : Дата
Сумма : Число 15, 2
Файл : Справочник.Присоединенный файл (Договоры с контрагентами)
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
