@startuml ИсточникиДанныхПланирования
'!include templates.wsd
'..\include templates.wsd
class Справочник.ИсточникиДанныхПланирования as "Источники данных планирования" <<Справочники>>
{
..Реквизиты..
СхемаКомпоновкиДанных : Хранилище значения
ОграничениеВыборкиПоПериоду : Число 1, 0
Описание : Строка
ИмяШаблонаСКД : Строка
ХранилищеНастроекКомпоновкиДанных : Хранилище значения
ВерсияШаблонаСКД : Число 10, 0
}
@enduml
