@startuml КлючиАналитикиУчетаПартийПроизводства
'!include templates.wsd
'..\include templates.wsd
class Справочник.КлючиАналитикиУчетаПартийПроизводства as "Ключи аналитики учета партий производства" <<Справочники>>
{
..Реквизиты..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Спецификация : Справочник.Ресурсная спецификация
Назначение : Справочник.Назначение
}
@enduml
