@startuml ДоговорыКредитовИДепозитов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ДоговорыКредитовИДепозитов as "Договоры кредитов и депозитов" <<Справочники>>
{
..Реквизиты..
БанковскийСчет : Справочник.Банковский счет организации
БанковскийСчетКомиссии : Справочник.Банковский счет
БанковскийСчетКонтрагента : Справочник.Банковский счет
БанковскийСчетПроцентов : Справочник.Банковский счет
ВалютаВзаиморасчетов : Справочник.Валюта
Дата : Дата
ДатаПервогоТранша : Дата
ДатаПоследнегоПлатежа : Дата
Касса : Справочник.Касса
Комментарий : Строка
Контрагент : Справочник.Контрагент
НаименованиеДляПечати : Строка
Номер : Строка
Организация : Справочник.Организация
Ответственный : Справочник.Пользователь
Партнер : Справочник.Партнер
Подразделение : Справочник.Подразделение
ПорядокОплаты : Порядок оплаты
Согласован : Булево
СрокДней : Число 5, 0
СрокМес : Число 5, 0
Статус : Статусы договоров контрагентов
СтатьяДДСКомиссии : Справочник.Статья движения денежных средств
СтатьяДДСОсновногоДолга : Справочник.Статья движения денежных средств
СтатьяДДСПоступленияВыдачи : Справочник.Статья движения денежных средств
СтатьяДДСПроцентов : Справочник.Статья движения денежных средств
СтатьяДоходовРасходовКомиссии : Статья расходов\rСтатьи доходов
СтатьяДоходовРасходовПроцентов : Статья расходов\rСтатьи доходов
СуммаКомиссии : Число 15, 2
СуммаЛимита : Число 15, 2
СуммаПроцентов : Число 15, 2
СуммаТраншей : Число 15, 2
ТипДоговора : Типы договора кредитов и депозитов
ТипКомиссии : Тип Комиссии
ТипСрочности : Тип срочности
ФормаОплаты : Формы оплаты
ХарактерДоговора : Характер договора кредитов и депозитов
ГруппаФинансовогоУчетаДенежныхСредств : Справочник.Группа финансового учета денежных средств
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
НаправлениеДеятельности : Справочник.Направление деятельности
ТипПлатежаФЗ275 : Справочник.Типы платежей 275-ФЗ
КодРаздел7ДекларацииНДС : Справочник.Коды операций раздела 7 декларации по НДС
..Табличная часть \n Обеспечение..
НомерДоговора : Строка
Контрагент : Справочник.Контрагент
Статус : Статусы договоров контрагентов
Комментарий : Строка
ДатаНачала : Дата
ДатаОкончания : Дата
ТипОбеспечения : Тип обеспечительного договора
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n ПодтверждающиеДокументы..
ВидДокумента : Справочник.Вид документа
Номер : Строка
Дата : Дата
Сумма : Число 15, 2
Файл : Справочник.Присоединенный файл (Договоры кредитов и депозитов)
}
@enduml
