@startuml СоглашенияОбИспользованииЭД
'!include templates.wsd
'..\include templates.wsd
class Справочник.СоглашенияОбИспользованииЭД as "Настройки ЭДО" <<Справочники>>
{
..Реквизиты..
АвтоПереходНаНовыеФорматы : Булево
ВерсияФорматаПакета : Версии формата пакета электронных документов
ДатаИзмененияСтатуса : Дата
ДоговорКонтрагента : Справочник.Договор с контрагентом
ИдентификаторКонтрагента : Строка
ИдентификаторОрганизации : Строка
ИзменитьФорматПакетаЭД : Булево
КаталогВходящихДокументов : Строка
КаталогВходящихДокументовFTP : Строка
КаталогИсходящихДокументов : Строка
КаталогИсходящихДокументовFTP : Строка
Комментарий : Строка
Контрагент : Справочник.Организация\rСправочник.Контрагент
ОписаниеОшибки : Строка
Организация : Справочник.Организация
ПроверятьСертификатыПодписей : Булево
ПрофильНастроекЭДО : Справочник.Профиль настроек ЭДО
РасширенныйРежимНастройкиСоглашения : Булево
РесурсВходящихДокументов : Строка\rСправочник.Учетная запись электронной почты
РесурсИсходящихДокументов : Строка
СертификатКонтрагентаДляШифрования : Хранилище значения
СертификатОрганизацииДляРасшифровки : Справочник.Сертификат ключа электронной подписи и шифрования
СостояниеСоглашения : Состояния соглашений ЭД
СпособОбменаЭД : Способы обмена электронными документами
СтатусПодключения : Статусы участников обмена ЭД
СтатусСоглашения : Статусы соглашений ЭД
ТекстПриглашения : Строка
УдалитьАдресСервера : Строка
УдалитьАутентификацияПоСертификату : Булево
УдалитьВнешняяКомпонента : Хранилище значения
УдалитьДата : Дата
УдалитьДополнительнаяОбработка : Справочник.Дополнительный отчет или обработка
УдалитьИспользуетсяКриптография : Булево
УдалитьКоличествоНеобходимыхПодписей : Число 1, 0
УдалитьЛогинАбонента : Строка
УдалитьНомер : Строка
УдалитьПароль : Строка
УдалитьПартнер : Строка
УдалитьПассивноеСоединениеFTP : Булево
УдалитьПользователь : Строка
УдалитьПортFTP : Число 4, 0
УдалитьПрограммаБанка : Программы банка
УдалитьСертификатАбонента : Строка
УдалитьСертификатОрганизацииДляРасшифровки : Строка
УдалитьСжиматьДанныеПакетаЭД : Булево
УдалитьСрокДействия : Дата
УдалитьТиповоеСоглашение : Справочник.Настройка ЭДО
УдалитьЭтоТиповое : Булево
ШифроватьДанныеПакетаЭД : Булево
ЭлектроннаяПочтаДляПриглашения : Строка
ЭлектроннаяПочтаКонтрагента : Строка
ЭтоИнтеркампани : Булево
ИспользоватьУПД : Булево
ИспользоватьУКД : Булево
..Табличная часть \n ИсходящиеДокументы..
ВерсияФормата : Строка
ДокументУчета : Строка
ИдентификаторКонтрагента : Строка
ИдентификаторОрганизации : Строка
ИспользоватьЭП : Булево
ИсходящийДокумент : Виды электронных документов
ОжидатьКвитанциюОДоставке : Булево
Приоритет : Число 10, 0
ПрофильНастроекЭДО : Справочник.Профиль настроек ЭДО
СпособОбменаЭД : Способы обмена электронными документами
ТребуетсяИзвещениеОПолучении : Булево
ТребуетсяОтветнаяПодпись : Булево
Формировать : Булево
МаршрутПодписания : Справочник.Маршрут подписания
..Табличная часть \n СертификатыПодписейКонтрагента..
Отпечаток : Строка
Сертификат : Хранилище значения
ПредставлениеСертификатаКонтрагента : Строка
..Табличная часть \n СертификатыПодписейОрганизации..
Сертификат : Справочник.Сертификат ключа электронной подписи и шифрования
УдалитьСертификат : Справочник.Сертификат электронной подписи
..Табличная часть \n ВходящиеДокументы..
ВходящийДокумент : Виды электронных документов
ИспользоватьЭП : Булево
ОжидатьКвитанциюОДоставке : Булево
Формировать : Булево
СпособОбработки : Строка
..Табличная часть \n УдалитьФорматыФайловОбмена..
Использовать : Булево
ФорматФайла : Форматы файлов обмена ЭД
}
@enduml
