@startuml Заметки
'!include templates.wsd
'..\include templates.wsd
class Справочник.Заметки as "Заметки" <<Справочники>>
{
..Реквизиты..
Автор : Справочник.Пользователь
Предмет : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
Содержание : Хранилище значения
ТекстСодержания : Строка
ДляРабочегоСтола : Булево
Пометка : Цвета заметок
ДатаИзменения : Дата
ПредставлениеПредмета : Строка
}
@enduml
