@startuml ВидыДоходовНДФЛ
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыДоходовНДФЛ as "Виды доходов НДФЛ" <<Справочники>>
{
..Реквизиты..
СтавкаНалогообложенияРезидента : НДФЛ ставки налогообложения резидента
НеОблагаетсяУНалоговогоАгента : Булево
КодПрименяемыйВНалоговойОтчетностиС2010Года : Строка
ВычетРассчитываетсяАвтоматически : Булево
ВычетПоУмолчанию : Справочник.Вид вычетов НДФЛ
ИмеетЕдинственныйВычет : Булево
СоответствуетОплатеТруда : Булево
}
@enduml
