@startuml СкладскиеПомещения
'!include templates.wsd
'..\include templates.wsd
class Справочник.СкладскиеПомещения as "Складские помещения" <<Справочники>>
{
..Реквизиты..
ИспользоватьАдресноеХранение : Булево
ИспользоватьАдресноеХранениеСправочно : Булево
НастройкаАдресногоХранения : Настройки адресного хранения
ТекущийОтветственный : Справочник.Физическое лицо
ТекущаяДолжностьОтветственного : Строка
ИспользованиеРабочихУчастков : Использование определяется в помещениях
ДатаНачалаАдресногоХраненияОстатков : Дата
}
@enduml
