@startuml Файлы
'!include templates.wsd
'..\include templates.wsd
class Справочник.Файлы as "Файлы" <<Справочники>>
{
..Реквизиты..
Автор : Справочник.Внешний пользователь\rСправочник.Учетная запись синхронизации файлов\rСправочник.Пользователь
ВладелецФайла : Задание\rСправочник.Папка\rДокумент.Регистр учета\r...
ДатаЗаема : Дата
ДатаМодификацииУниверсальная : Дата
ДатаСоздания : Дата
Зашифрован : Булево
ИндексКартинки : Число 10, 0
Описание : Строка
ПодписанЭП : Булево
УдалитьПолноеНаименование : Строка
Редактирует : Справочник.Учетная запись синхронизации файлов\rСправочник.Пользователь
ТекстХранилище : Хранилище значения
ТекущаяВерсия : Справочник.Версия файла
Изменил : Справочник.Пользователь
УдалитьТекущаяВерсияДатаМодификацииФайла : Дата
УдалитьТекущаяВерсияДатаСоздания : Дата
УдалитьТекущаяВерсияКод : Строка
УдалитьТекущаяВерсияНомерВерсии : Число 5, 0
ПутьКФайлу : Строка
Размер : Число 10, 0
Расширение : Строка
Том : Справочник.Том хранения файлов
ХранитьВерсии : Булево
ТипХраненияФайла : Типы хранения файлов
СтатусИзвлеченияТекста : Статусы извлечения текста файлов
ФайлХранилище : Хранилище значения
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n УдалитьСертификатыШифрования..
Отпечаток : Строка
Представление : Строка
Сертификат : Хранилище значения
}
@enduml
