@startuml УчетныеПолитикиОрганизаций
'!include templates.wsd
'..\include templates.wsd
class Справочник.УчетныеПолитикиОрганизаций as "Учетные политики организаций" <<Справочники>>
{
..Реквизиты..
МетодОценкиСтоимостиТоваров : Методы оценки стоимости товаров
СистемаНалогообложения : Системы налогообложения
ПрименяетсяЕНВД : Булево
ПрименяетсяУчетНДСПоФактическомуИспользованию : Булево
ПрименяетсяПБУ18 : Булево
УчетГотовойПродукцииПоПлановойСтоимости : Булево
ИспользоватьСчет40 : Булево
Учитывать5ПроцентныйПорог : Булево
ФормироватьРезервыПоСомнительнымДолгамБУ : Булево
ФормироватьРезервыПоСомнительнымДолгамНУ : Булево
ЗабалансовыйУчетТМЦВЭксплуатации : Булево
ПроводкиПоРаботникам : Булево
ВзаимозачетЧерезСчет76 : Булево
ЯвляетсяПлательщикомНДПИ : Булево
МетодНачисленияАмортизацииНУ : Методы начисления амортизации
ФормироватьРезервОтпусковБУ : Булево
ФормироватьРезервОтпусковНУ : Булево
МетодНачисленияРезерваОтпусков : Методы начисления резервов отпусков
НормативОтчисленийВРезервОтпусков : Число 4, 2
ПредельнаяВеличинаОтчисленийВРезервОтпусков : Число 15, 2
ОбъектНалогообложенияУСН : Объекты налогообложения по УСН
ДатаПереходаНаУСН : Дата
УведомлениеНомерУСН : Строка
УведомлениеДатаУСН : Дата
СтавкаНалогаУСН : Число 5, 2
БазаРаспределенияКосвенныхРасходовПоВидамДеятельности : Базы распределения косвенных расходов по видам деятельности
УдалитьСхемаУчетаСтоимостиОСвНУ : (не используется) Схемы учета стоимости ОС в НУ
ВариантУчетаНДСПриИзмененииВидаДеятельности : Варианты учета НДС при изменении вида деятельности на необлагаемую
СтатьяРасходовНеНДС : Статья расходов
АналитикаРасходовНеНДС : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
СтатьяРасходовЕНВД : Статья расходов
АналитикаРасходовЕНВД : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
УдалитьВариантУчетаСтоимостиТоваров : (не используется) Варианты учета стоимости ТМЦ
ВключатьВСоставНалоговыхРасходовЛизинговыеПлатежи : Булево
СборкаТоваровЧерезСчет20 : Булево
ПрименяетсяОсвобождениеОтУплатыНДС : Булево
УдалитьСборкаТоваровЧерез20СчетНеТребуетОбновления : Булево
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
