@startuml ВидыДоговоровАвторскогоЗаказа
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыДоговоровАвторскогоЗаказа as "Виды авторских договоров" <<Справочники>>
{
..Реквизиты..
КодДоходаНДФЛ : Справочник.Вид дохода НДФЛ
УдалитьКодДоходаНДФЛ : Справочник.(не используется) Виды доходов НДФЛ
КодДоходаСтраховыеВзносы : Справочник.Вид дохода по страховым взносам
УдалитьКодДоходаСтраховыеВзносы : Справочник.(не используется) Виды доходов (взносы)
УдалитьИдентификаторОбъекта : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
