@startuml ГорячиеКлавиши
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГорячиеКлавиши as "Горячие клавиши" <<Справочники>>
{
..Реквизиты..
БыстрыеТовары : Хранилище значения
КомандыФормы : Хранилище значения
}
@enduml
