@startuml Должности
'!include templates.wsd
'..\include templates.wsd
class Справочник.Должности as "Должности" <<Справочники>>
{
..Реквизиты..
РеквизитДопУпорядочивания : Число 5, 0
ДатаВвода : Дата
ИсключенаИзШтатногоРасписания : Булево
ДатаИсключения : Дата
ВведенаВШтатноеРасписание : Булево
ЯвляетсяДолжностьюЛетногоЭкипажа : Булево
ЯвляетсяШахтерскойДолжностью : Булево
ЯвляетсяФармацевтическойДолжностью : Булево
ОснованиеДосрочногоНазначенияПенсии : Справочник.Основание для досрочной пенсии
УдалитьОснованиеДосрочногоНазначенияПенсии : Справочник.(не используется) Основания для досрочной пенсии
ВзимаютсяВзносыЗаЗанятыхНаРаботахСДосрочнойПенсией : Виды работ с досрочной пенсией
КатегорияВоинскогоУчета : Категории должностей для воинского учета
КатегорияУчетаЗабронированных : Категории должностей для учета забронированных
ЛетноПодъемныйСостав : Булево
Плавсостав : Булево
УдалитьСтрокаОтчетностиМониторингаРаботниковСоциальнойСферы : Справочник.Строка отчетности статистического наблюдения
ОсобыеУсловияТрудаПФР : Справочник.Особое условие труда
УдалитьОсобыеУсловияТрудаПФР : Справочник.(не используется) Особые условия труда ПФР
КодПозицииСпискаПФР : Справочник.Льготная профессия (ПФР)
НаименованиеКраткое : Строка
ТарифнаяСетка : Справочник.Тарифная группа
РазрядКатегория : Справочник.Квалификационный разряд (категория)
ТарифнаяСеткаНадбавки : Справочник.Тарифная группа
РазрядКатегорияНадбавки : Справочник.Квалификационный разряд (категория)
ПроцентНадбавкиЗаВредность : Число 5, 2
ВыплачиваетсяНадбавкаЗаВредность : Булево
КоличествоДнейДополнительногоОтпускаВГод : Число 2, 0
ОКПДТРКод : Строка
ОКПДТРКЧ : Строка
ОКПДТРКатегория : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n Специальности..
Специальность : Справочник.Специальность
..Табличная часть \n ЗависимыеСтажи..
ВидСтажа : Справочник.Вид стажа
}
@enduml
