@startuml ЛентыНовостей
'!include templates.wsd
'..\include templates.wsd
class Справочник.ЛентыНовостей as "Ленты новостей" <<Справочники>>
{
..Реквизиты..
ОбязательныйКанал : Булево
Протокол : Строка
Сайт : Строка
ИмяФайла : Строка
ВариантЛогинаПароля : Вариант логина / пароля для ленты новостей
Логин : Строка
Пароль : Хранилище значения
УдалитьПароль : Строка
ЗагруженоССервера : Булево
ВидимостьПоУмолчанию : Булево
ЧастотаОбновления : Число 1, 0
Комментарий : Строка
ПропускатьЗагрузкуБинарныхДанных : Булево
ЛокальнаяЛентаНовостей : Булево
..Табличная часть \n ДоступныеКатегорииНовостей..
КатегорияНовостей : Категория новостей
РазрешеноНастраиватьПользователям : Булево
ОтборНастраиваетсяНаСервере : Булево
..Табличная часть \n ИсключенияВидимости..
Пользователь : Справочник.Пользователь
}
@enduml
