@startuml ГруппировкиТоварныхОграничений
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГруппировкиТоварныхОграничений as "Группировки товарных ограничений" <<Справочники>>
{
}
@enduml
