@startuml ФорматыМагазинов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ФорматыМагазинов as "Форматы магазинов" <<Справочники>>
{
..Реквизиты..
ПлощадьТорговогоЗалаМинимальная : Число 10, 0
ПлощадьТорговогоЗалаМаксимальная : Число 10, 0
КоличествоАссортиментныхПозиций : Число 10, 0
ЦелевоеМестоположение : Строка
ТехнологияРазмещенияТовараИОбслуживанияПокупателей : Строка
РозничныйВидЦены : Справочник.Вид цены
ЦелевыеГруппыПокупателей : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
