@startuml ШаблоныАнкет
'!include templates.wsd
'..\include templates.wsd
class Справочник.ШаблоныАнкет as "Шаблоны анкет" <<Справочники>>
{
..Реквизиты..
Заголовок : Строка
Вступление : Строка
Заключение : Строка
РедактированиеШаблонаЗавершено : Булево
}
@enduml
