@startuml УзлыОбъектовЭксплуатации
'!include templates.wsd
'..\include templates.wsd
class Справочник.УзлыОбъектовЭксплуатации as "Узлы объектов эксплуатации" <<Справочники>>
{
..Реквизиты..
НаименованиеПолное : Строка
Класс : Справочник.Класс объектов эксплуатации
Подкласс : Справочник.Подкласс объектов эксплуатации
Статус : Статусы объектов эксплуатации
СтатьяРасходов : Статья расходов
ВлияетНаДоступностьРЦ : Булево
РемонтирующееПодразделение : Справочник.Подразделение
Описание : Строка
Модель : Строка
СерийныйНомер : Строка
Расположение : Строка
Принадлежность : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n ПараметрыУчетаНаработок..
ПоказательНаработки : Справочник.Показатель наработки
НазначенныйРесурс : Число 15, 3
Источник : Справочник.Объект эксплуатации\rСправочник.Узел объекта эксплуатации
СмещениеЗначения : Число 15, 3
}
@enduml
