@startuml СтатьиРасходовЗарплата
'!include templates.wsd
'..\include templates.wsd
class Справочник.СтатьиРасходовЗарплата as "Статьи расходов" <<Справочники>>
{
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
