@startuml ОбластиХранения
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОбластиХранения as "Области хранения" <<Справочники>>
{
..Реквизиты..
Описание : Строка
Помещение : Справочник.Помещение
ПриоритетРазмещенияВСвободныеЯчейки : Число 1, 0
ПриоритетРазмещенияВМонотоварныеЯчейки : Число 1, 0
ПриоритетРазмещенияВСмешанныеЯчейки : Число 1, 0
ПриоритетРазмещенияВЯчейкиСДругимТоваром : Число 1, 0
ПриоритетОтбораИзМонотоварныхЯчеек : Число 1, 0
ПриоритетОтбораИзСмешанныхЯчеек : Число 1, 0
ПриоритетОтбораПодОстаток : Число 1, 0
ОписаниеМонотоварности : Описание монотоварности
СтрогаяМонотоварность : Булево
ИспользованиеПериодичностиИнвентаризацииЯчеек : Варианты использования периодической инвентаризации ячеек
КоличествоДнейМеждуИнвентаризациями : Число 10, 0
ОбластьОбособленногоХранения : Булево
КонтролироватьОбособление : Булево
}
@enduml
