@startuml ПользовательскиеНастройкиОтчетов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПользовательскиеНастройкиОтчетов as "Пользовательские настройки отчетов" <<Справочники>>
{
..Реквизиты..
Вариант : Справочник.Вариант отчета
Пользователь : Справочник.Внешний пользователь\rСправочник.Пользователь
КлючПользовательскойНастройки : Строка
}
@enduml
