@startuml ОтправкиРПН
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОтправкиРПН as "Отправки в РПН" <<Справочники>>
{
..Реквизиты..
ОтчетСсылка : Справочник.Загруженный отчет\rДокумент.Регламентированный отчет\rДокумент.Уведомление о спецрежимах налогообложения
ИдентификаторОтправкиНаСервере : Строка
ЗашифрованныйПакет : Хранилище значения
ИмяФайлаПакета : Строка
СтатусОтправки : Статусы отправки
Протокол : Хранилище значения
ДатаОтправки : Дата
ДатаПолученияРезультата : Дата
Организация : Справочник.Организация
ДатаНачалаПериода : Дата
ДатаОкончанияПериода : Дата
Период : Строка
Версия : Число 3, 0
ВидОтчета : Справочник.Виды отправляемых документов
ДатаЗакрытия : Дата
СтатусПроверкиНаПортале : Статусы отправки
ПредставлениеПериода : Строка
ПредставлениеВидаДокумента : Строка
ИдентификаторОтправкиОператору : Число 10, 0
}
@enduml
