@startuml ДоговорыЛизинга
'!include templates.wsd
'..\include templates.wsd
class Справочник.ДоговорыЛизинга as "Договоры лизинга" <<Справочники>>
{
..Реквизиты..
БанковскийСчет : Справочник.Банковский счет организации
БанковскийСчетКонтрагента : Справочник.Банковский счет
ВалютаВзаиморасчетов : Справочник.Валюта
Комментарий : Строка
Организация : Справочник.Организация
Контрагент : Справочник.Контрагент
Ответственный : Справочник.Пользователь
Дата : Дата
Номер : Строка
Подразделение : Справочник.Подразделение
ПорядокОплаты : Порядок оплаты
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
ВариантУчетаИмущества : Варианты учета имущества при лизинге
СчетУчетаВыкупПредметаЛизинга : Счет бухгалтерского учета
СчетУчетаАрендныеОбязательства : Счет бухгалтерского учета
СчетУчетаОбеспечительныйПлатеж : Счет бухгалтерского учета
СчетУчетаУслугиПоЛизингу : Счет бухгалтерского учета
ДатаНачалаДействия : Дата
ДатаОкончанияДействия : Дата
Партнер : Справочник.Партнер
КонтактноеЛицо : Справочник.Контактное лицо
ЕстьОбеспечительныйПлатеж : Булево
ЕстьВыкупПредметаЛизинга : Булево
Статус : Статусы договоров контрагентов
Согласован : Булево
НаправлениеДеятельности : Справочник.Направление деятельности
СтавкаНДС : Ставки НДС
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
