@startuml ГруппыФинансовогоУчетаДоходовРасходов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГруппыФинансовогоУчетаДоходовРасходов as "Группы настроек финансового учета доходов/расходов" <<Справочники>>
{
..Реквизиты..
Описание : Строка
}
@enduml
