@startuml РабочиеУчастки
'!include templates.wsd
'..\include templates.wsd
class Справочник.РабочиеУчастки as "Рабочие участки" <<Справочники>>
{
..Реквизиты..
Помещение : Справочник.Помещение
ОграничиватьПоВесу : Булево
ОграничениеПоВесу : Число 7, 0
ОграничиватьПоОбъему : Булево
ОграничениеПоОбъему : Число 7, 0
ПорядокОбработкиСкладскогоЗадания : Порядок обработки складского задания
..Табличная часть \n РаботникиУчастка..
РаботникУчастка : Справочник.Пользователь
}
@enduml
