@startuml Награды
'!include templates.wsd
'..\include templates.wsd
class Справочник.Награды as "Награды" <<Справочники>>
{
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
