@startuml ПроизводственныеКалендари
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПроизводственныеКалендари as "Производственные календари" <<Справочники>>
{
..Реквизиты..
БазовыйКалендарь : Справочник.Производственный календарь
}
@enduml
