@startuml Календари
'!include templates.wsd
'..\include templates.wsd
class Справочник.Календари as "Графики работы" <<Справочники>>
{
..Реквизиты..
ПроизводственныйКалендарь : Справочник.Производственный календарь
СпособЗаполнения : Способы заполнения графика работы
ДатаНачала : Дата
ДатаОкончания : Дата
ДатаОтсчета : Дата
УчитыватьПраздники : Булево
Описание : Строка
ГоризонтПланирования : Число 3, 0
ВладелецГрафика : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rСправочник.Присоединенные файлы (Поступление безналичных денежных средств)\r...
УдалитьВидКалендаря : (не используется) Виды календарей
..Табличная часть \n ШаблонЗаполнения..
ДеньВключенВГрафик : Булево
..Табличная часть \n РасписаниеРаботы..
НомерДня : Число 7, 0
ВремяНачала : Дата
ВремяОкончания : Дата
}
@enduml
