@startuml ФизическиеЛица
'!include templates.wsd
'..\include templates.wsd
class Справочник.ФизическиеЛица as "Физические лица" <<Справочники>>
{
..Реквизиты..
ДатаРождения : Дата
Пол : Пол физического лица
ИНН : Строка
СтраховойНомерПФР : Строка
МестоРождения : Строка
ГруппаДоступа : Справочник.Группа доступа физических лиц
ИмеетНаучныеТруды : Булево
ИмеетИзобретения : Булево
ФИО : Строка
УточнениеНаименования : Строка
УдалитьПроцентСевернойНадбавкиФизическогоЛица : Число 5, 2
УдалитьПроцентСевернойНадбавкиФизическогоЛицаИзменяется : Булево
УдалитьПорядокИсчисленияПроцентаСевернойНадбавки : Порядок начисления северных надбавок
ДатаРегистрации : Дата
НаименованиеСлужебное : Строка
ЛьготаПриНачисленииПособий : Основания финансирования пособия федеральным бюджетом
УдалитьФотографияФайлом : Справочник.Присоединенный файл (Физические лица)
УдалитьФотография : Справочник.Файл
ПостоянноПроживалВКрыму18Марта2014Года : Булево
Фамилия : Строка
Имя : Строка
Отчество : Строка
ИнициалыИмени : Строка
..Табличная часть \n КонтактнаяИнформация..
Тип : Типы контактной информации
Вид : Справочник.Вид контактной информации
Представление : Строка
ЗначенияПолей : Строка
Страна : Строка
Регион : Строка
Город : Строка
АдресЭП : Строка
ДоменноеИмяСервера : Строка
НомерТелефона : Строка
НомерТелефонаБезКодов : Строка
ВидДляСписка : Справочник.Вид контактной информации
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n УдалитьСоставСемьи..
СтепеньРодства : Справочник.Степень родства
Имя : Строка
ДатаРождения : Дата
..Табличная часть \n УдалитьОбразование..
ВидОбразования : Справочник.Вид образования
УчебноеЗаведение : Справочник.Учебное заведение
Специальность : Справочник.Специальность
Диплом : Строка
ГодОкончания : Число 4, 0
Квалификация : Строка
..Табличная часть \n УдалитьТрудоваяДеятельность..
Организация : Строка
ДатаНачала : Дата
ДатаОкончания : Дата
Должность : Строка
..Табличная часть \n УдалитьЗнаниеЯзыков..
Язык : Справочник.Язык
СтепеньЗнанияЯзыка : Справочник.Степень знания языка
..Табличная часть \n УдалитьПрофессии..
Профессия : Справочник.Профессия рабочего
..Табличная часть \n УдалитьСтажи..
ВидСтажа : Справочник.Вид стажа
ДатаОтсчета : Дата
РазмерМесяцев : Число 3, 0
РазмерДней : Число 2, 0
..Табличная часть \n УдалитьНаграды..
Награда : Справочник.Награда
НомерПриказа : Строка
ДатаПриказа : Дата
ЧейПриказ : Строка
..Табличная часть \n УдалитьУченыеСтепени..
УченаяСтепень : Справочник.Ученая степень
ДатаПрисужденияУченойСтепени : Дата
ОтрасльНауки : Строка
ДиссертационныйСовет : Строка
ДипломСерияНомер : Строка
ДипломВыданОрганизация : Строка
..Табличная часть \n УдалитьУченыеЗвания..
УченоеЗвание : Справочник.Ученое звание
ДатаПрисвоенияУченогоЗвания : Дата
АттестатСерия : Строка
АттестатНомер : Строка
АттестатВыданОрганизация : Строка
НаучнаяСпециальность : Справочник.Специальность
}
@enduml
