@startuml ЕГАИСПрисоединенныеФайлы
'!include templates.wsd
'..\include templates.wsd
class Справочник.ЕГАИСПрисоединенныеФайлы as "Протокол обмена ЕГАИС" <<Справочники>>
{
..Реквизиты..
Автор : Справочник.Пользователь
ВладелецФайла : Справочник.Организация ЕГАИС
ДатаМодификацииУниверсальная : Дата
ДатаСоздания : Дата
Зашифрован : Булево
Изменил : Справочник.Пользователь
ИндексКартинки : Число 10, 0
Описание : Строка
ПутьКФайлу : Строка
Размер : Число 10, 0
Расширение : Строка
Редактирует : Справочник.Пользователь
СтатусИзвлеченияТекста : Статусы извлечения текста файлов
ТекстХранилище : Хранилище значения
ТипХраненияФайла : Типы хранения файлов
Том : Справочник.Том хранения файлов
ФайлХранилище : Хранилище значения
Операция : Виды документов ЕГАИС
ОперацияКвитанции : Виды документов ЕГАИС
ТипСообщения : Типы запросов ЕГАИС
СообщениеОснование : Справочник.Сообщение обмена с ЕГАИС
СтатусОбработки : Состояния обработки сообщений ЕГАИС
ПодписанЭП : Булево
Версия : Число 10, 0
ХешСумма : Строка
ФорматОбмена : Форматы обмена ЕГАИС
ИдентификаторЗапроса : Строка
Документ : Документ.Товарно-транспортная накладная ЕГАИС (входящая)\rДокумент.Чек ККМ на возврат\rДокумент.Чек ЕГАИС на возврат\r...
ДатаЗаема : Дата
ХранитьВерсии : Булево
}
@enduml
