@startuml УчетныеЗаписиЭлектроннойПочты
'!include templates.wsd
'..\include templates.wsd
class Справочник.УчетныеЗаписиЭлектроннойПочты as "Учетные записи электронной почты" <<Справочники>>
{
..Реквизиты..
SMTPАутентификация : Варианты SMTP аутентификации
АдресЭлектроннойПочты : Строка
ВремяОжидания : Число 3, 0
ИмяПользователя : Строка
ИспользоватьБезопасныйВходНаСерверВходящейПочты : Булево
ИспользоватьБезопасныйВходНаСерверИсходящейПочты : Булево
ИспользоватьДляОтправки : Булево
ИспользоватьДляПолучения : Булево
ИспользоватьЗащищенноеСоединениеДляВходящейПочты : Булево
ИспользоватьЗащищенноеСоединениеДляИсходящейПочты : Булево
ОставлятьКопииСообщенийНаСервере : Булево
ПериодХраненияСообщенийНаСервере : Число 3, 0
Пользователь : Строка
ПользовательSMTP : Строка
ПортСервераВходящейПочты : Число 5, 0
ПортСервераИсходящейПочты : Число 5, 0
ПротоколВходящейПочты : Строка
СерверВходящейПочты : Строка
СерверИсходящейПочты : Строка
СпособPOP3Аутентификации : Способы POP3 аутентификации
СпособSMTPАутентификации : Способы SMTP аутентификации
ТребуетсяВходНаСерверПередОтправкой : Булево
УдалитьВПредставлениеВключатьИмяПользователя : Булево
УдалитьОтветственныйЗаОбработкуПисем : Справочник.Пользователь
УдалитьПароль : Строка
УдалитьПарольSMTP : Строка
ОтправлятьСкрытыеКопииПисемНаЭтотАдрес : Булево
ВладелецУчетнойЗаписи : Справочник.Пользователь
}
@enduml
