@startuml СоответствияСчетовМеждународногоУчета
'!include templates.wsd
'..\include templates.wsd
class Справочник.СоответствияСчетовМеждународногоУчета as "Соответствия счетов международного учета" <<Справочники>>
{
..Реквизиты..
СчетРеглУчета : Счет бухгалтерского учета
СчетМеждународногоУчета : Международный план счетов
ДополнительныйОтбор : Хранилище значения
ПредставлениеОтбора : Строка
РеквизитДопУпорядочивания : Число 3, 0
УстановленДополнительныйОтбор : Булево
..Табличная часть \n НастройкиЗаполненияСубконто..
ВидСубконто : Виды субконто международные
ЗаполнятьИзИсточника : Булево
УказанноеЗначение : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСтатья расходов\r...
Выражение : Строка
}
@enduml
