@startuml МедицинскиеОрганизации
'!include templates.wsd
'..\include templates.wsd
class Справочник.МедицинскиеОрганизации as "Медицинские организации" <<Справочники>>
{
..Реквизиты..
ОГРН : Строка
Адрес : Строка
АдресКодПоКЛАДР : Строка
АдресВнутреннееПредставление : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
