@startuml ОснованияДосрочногоНазначенияПенсииДляСЗВК
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОснованияДосрочногоНазначенияПенсииДляСЗВК as "Основания для досрочной пенсии (СЗВ-К)" <<Справочники>>
{
}
@enduml
