@startuml ОснованияЗаключенияСрочныхТрудовыхДоговоров
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОснованияЗаключенияСрочныхТрудовыхДоговоров as "Основания заключения срочных трудовых договоров" <<Справочники>>
{
..Реквизиты..
ТекстОснования : Строка
}
@enduml
