@startuml СпискиПрофессийДолжностейЛьготногоПенсионногоОбеспечения
'!include templates.wsd
'..\include templates.wsd
class Справочник.СпискиПрофессийДолжностейЛьготногоПенсионногоОбеспечения as "Список льготных профессий (ПФР)" <<Справочники>>
{
..Реквизиты..
НаименованиеПрофессии : Строка
}
@enduml
