@startuml ПравилаОбработкиЭлектроннойПочты
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПравилаОбработкиЭлектроннойПочты as "Правила обработки электронной почты" <<Справочники>>
{
..Реквизиты..
КомпоновщикНастроек : Хранилище значения
ПомещатьВПапку : Справочник.Папка электронных писем
РеквизитДопУпорядочивания : Число 5, 0
ПредставлениеОтбора : Строка
}
@enduml
