@startuml СтатьиДвиженияДенежныхСредств
'!include templates.wsd
'..\include templates.wsd
class Справочник.СтатьиДвиженияДенежныхСредств as "Статьи движения денежных средств" <<Справочники>>
{
..Реквизиты..
КорреспондирующийСчет : Строка
Описание : Строка
ВидДвиженияДенежныхСредств : Виды движений денежных средств
РеквизитДопУпорядочивания : Число 5, 0
ПриоритетОплаты : Справочник.Приоритет оплаты
..Табличная часть \n ХозяйственныеОперации..
ХозяйственнаяОперация : Хозяйственные операции
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
