@startuml ВариантыОтветовАнкет
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВариантыОтветовАнкет as "Варианты ответов анкет" <<Справочники>>
{
..Реквизиты..
ТребуетОткрытогоОтвета : Булево
РеквизитДопУпорядочивания : Число 5, 0
}
@enduml
