@startuml УдалитьВидыОбъектовЕГАИС
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьВидыОбъектовЕГАИС as "(не используется) Виды объектов ЕГАИС" <<Справочники>>
{
..Реквизиты..
ПространствоИмен : Строка
ПрефиксПространстваИмен : Строка
ПутьНаСервере : Строка
}
@enduml
