@startuml Сотрудники
'!include templates.wsd
'..\include templates.wsd
class Справочник.Сотрудники as "Сотрудники" <<Справочники>>
{
..Реквизиты..
ФизическоеЛицо : Справочник.Физическое лицо
ГоловнаяОрганизация : Справочник.Организация
УдалитьВидЗанятости : Виды занятости
ТекущийПроцентСевернойНадбавки : Число 4, 2
ВАрхиве : Булево
УточнениеНаименования : Строка
ГоловнойСотрудник : Справочник.Сотрудник
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n УдалитьНаборыЗначенийДоступа..
НомерНабора : Число 10, 0
ЗначениеДоступа : Справочник.Статьи бюджетов\rСправочник.Вид номенклатуры\rСправочник.Номенклатура\r...
Чтение : Булево
Изменение : Булево
Уточнение : Справочник.Идентификатор объекта метаданных
}
@enduml
