@startuml ВидыСвязейМеждуПартнерами
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыСвязейМеждуПартнерами as "Виды связей между партнерами" <<Справочники>>
{
..Реквизиты..
Комментарий : Строка
РольПартнера1 : Строка
РольПартнера2 : Строка
ОбратноеНаименование : Строка
}
@enduml
