@startuml БанковскиеСчетаКонтрагентов
'!include templates.wsd
'..\include templates.wsd
class Справочник.БанковскиеСчетаКонтрагентов as "Банковские счета" <<Справочники>>
{
..Реквизиты..
НомерСчета : Строка
Банк : Справочник.Банк
БанкДляРасчетов : Справочник.Банк
ТекстКорреспондента : Строка
ТекстНазначения : Строка
ВалютаДенежныхСредств : Справочник.Валюта
БИКБанка : Строка
РучноеИзменениеРеквизитовБанка : Булево
НаименованиеБанка : Строка
КоррСчетБанка : Строка
ГородБанка : Строка
АдресБанка : Строка
ТелефоныБанка : Строка
БИКБанкаДляРасчетов : Строка
РучноеИзменениеРеквизитовБанкаДляРасчетов : Булево
НаименованиеБанкаДляРасчетов : Строка
КоррСчетБанкаДляРасчетов : Строка
ГородБанкаДляРасчетов : Строка
АдресБанкаДляРасчетов : Строка
ТелефоныБанкаДляРасчетов : Строка
СВИФТБанка : Строка
СВИФТБанкаДляРасчетов : Строка
ИностранныйБанк : Булево
СчетВБанкеДляРасчетов : Строка
Закрыт : Булево
ОтдельныйСчетГОЗ : Булево
ГосударственныйКонтракт : Справочник.Государственный контракт
ИННКорреспондента : Строка
КППКорреспондента : Строка
}
@enduml
