@startuml СканированныеДокументыДляПередачиВЭлектронномВиде
'!include templates.wsd
'..\include templates.wsd
class Справочник.СканированныеДокументыДляПередачиВЭлектронномВиде as "Сканированные документы для передачи в электронном виде" <<Справочники>>
{
..Реквизиты..
Организация : Справочник.Организация
ВидДокумента : Виды представляемых документов
НомерДокумента : Строка
ДатаДокумента : Дата
СуммаВсего : Число 17, 2
СуммаНалога : Число 17, 2
НомерОснования : Строка
ДатаОснования : Дата
ПредметДокумента : Строка
НачалоПериода : Дата
КонецПериода : Дата
Направление : Направления документа по требованию ФНС
Источник : Документ.Приобретение товаров и услуг\rДокумент.Таможенная декларация на импорт\rДокумент.Возврат товаров поставщику\r...
НомерСтрокиИсточника : Число 3, 0
ВерсияПриказа : Приказ описи исходящих документов
СведенияДокументаОснования : Строка
СведенияДокумента : Строка
..Табличная часть \n РеквизитыУчастников..
Контрагент : Справочник.Контрагент
УдалитьРольУчастника : Строка
Роль : Роли участников сделки документа по требованию ФНС
ЮрЛицоНаименование : Строка
ЮрЛицоИНН : Строка
ЮрЛицоКПП : Строка
ФизЛицоФамилия : Строка
ФизЛицоИмя : Строка
ФизЛицоОтчество : Строка
ФизЛицоИНН : Строка
ЯвляетсяЮрЛицом : Булево
}
@enduml
