@startuml ДоговорыМеждуОрганизациями
'!include templates.wsd
'..\include templates.wsd
class Справочник.ДоговорыМеждуОрганизациями as "Договоры между организациями" <<Справочники>>
{
..Реквизиты..
БанковскийСчет : Справочник.Банковский счет организации
БанковскийСчетПолучателя : Справочник.Банковский счет организации
ВалютаВзаиморасчетов : Справочник.Валюта
Комментарий : Строка
ДатаНачалаДействия : Дата
ДатаОкончанияДействия : Дата
Организация : Справочник.Организация
Менеджер : Справочник.Пользователь
НаименованиеДляПечати : Строка
Дата : Дата
Номер : Строка
ОрганизацияПолучатель : Справочник.Организация
Подразделение : Справочник.Подразделение
ПорядокОплаты : Порядок оплаты
ПорядокРасчетов : Детализация расчетов
Согласован : Булево
Статус : Статусы договоров контрагентов
ТипДоговора : Типы договоров между организациями
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
ИдентификаторПлатежа : Строка
СтатьяДвиженияДенежныхСредствПолучателя : Справочник.Статья движения денежных средств
НаправлениеДеятельности : Справочник.Направление деятельности
УстановленСрокОплаты : Булево
СрокОплаты : Число 5, 0
СтавкаНДС : Ставки НДС
ДоговорСУчастникомГОЗ : Булево
ГосударственныйКонтракт : Справочник.Государственный контракт
ПлатежиПо275ФЗ : Булево
ТипПлатежаФЗ275 : Справочник.Типы платежей 275-ФЗ
СуммаПрибыли : Число 15, 2
Сумма : Число 15, 2
ОплатаРасходовПоТарифамСГосрегулированием : Булево
СтатьяКалькуляции : Справочник.Статьи калькуляции
ВыполненыОбязательстваПоДоговоруГОЗ : Булево
ИностранныйИсполнительВУтвержденномПеречнеГОЗ : Булево
ГруппаФинансовогоУчетаПолучателя : Справочник.Группа финансового учета расчетов
ИдентификаторГосКонтракта : Строка
КодРаздел7ДекларацииНДС : Справочник.Коды операций раздела 7 декларации по НДС
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n КалькуляцияЗатрат..
СтатьяКалькуляции : Справочник.Статьи калькуляции
Сумма : Число 15, 2
СуммаКВозмещению : Число 15, 2
..Табличная часть \n ДоговорыСЗаказчиками..
ДоговорСЗаказчиком : Справочник.Договор между организациями\rСправочник.Договор с контрагентом
Процент : Число 5, 2
..Табличная часть \n ПодтверждающиеДокументы..
ВидДокумента : Справочник.Вид документа
Номер : Строка
Дата : Дата
Сумма : Число 15, 2
Файл : Справочник.Присоединенный файл (Договоры между организациями)
}
@enduml
