@startuml РолиКонтактныхЛицВСделкахИПроектах
'!include templates.wsd
'..\include templates.wsd
class Справочник.РолиКонтактныхЛицВСделкахИПроектах as "Роли контактных лиц в сделках и проектах" <<Справочники>>
{
..Реквизиты..
Описание : Строка
}
@enduml
