@startuml РодственникиФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class Справочник.РодственникиФизическихЛиц as "Родственники сотрудников" <<Справочники>>
{
..Реквизиты..
СтепеньРодства : Справочник.Степень родства
ДатаРождения : Дата
НаИждивении : Булево
НаименованиеСлужебное : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
