@startuml ОчередьЭлектронныхЧековКОтправке
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОчередьЭлектронныхЧековКОтправке as "Очередь электронных чеков к отправке" <<Справочники>>
{
..Реквизиты..
ТипРассылки : Типы рассылки электронных чеков
ДатаПостановкиВОчередь : Дата
ПараметрыСообщения : Хранилище значения
ПроизошлаОшибкаПередачи : Булево
ОписаниеОшибки : Строка
}
@enduml
