@startuml ЭтапыПодготовкиБюджетов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ЭтапыПодготовкиБюджетов as "Этапы подготовки бюджетов" <<Справочники>>
{
..Реквизиты..
Описание : Строка
ПредставлениеРасписания : Строка
Действие : Типы действий этапов подготовки бюджетов
НастройкиКонтрольныхОтчетов : Хранилище значения
НастройкаДействия : Хранилище значения
ПредставлениеНастройкиДействия : Строка
Ответственный : Справочник.Пользователь
Длительность : Число 3, 0
ТипДлительности : Типы сроков этапов подготовки бюджетов
ПредставлениеДлительности : Строка
Периодичность : Периодичность
ПорядокВыполненияЭтапов : Порядок выполнения этапов подготовки бюджетов
ОписаниеЗадачи : Строка
УсловиеЗапуска : Типы условий запуска этапов подготовки бюджетов
Срок : Число 3, 0
ТипСрока : Типы сроков этапов подготовки бюджетов
НеВыполняется : Булево
ВыполнятьАвтоматически : Булево
}
@enduml
