@startuml УдалитьВидыДоходовПоСтраховымВзносам
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьВидыДоходовПоСтраховымВзносам as "(не используется) Виды доходов (взносы)" <<Справочники>>
{
..Реквизиты..
ВходитВБазуПФР : Булево
ВходитВБазуФСС : Булево
ВходитВБазуФОМС : Булево
РеквизитДопУпорядочивания : Число 5, 0
ОблагаетсяВзносамиЧастично : Булево
}
@enduml
