@startuml РазрядыКатегорииДолжностей
'!include templates.wsd
'..\include templates.wsd
class Справочник.РазрядыКатегорииДолжностей as "Квалификационные разряды (категории)" <<Справочники>>
{
..Реквизиты..
РеквизитДопУпорядочивания : Число 5, 0
НаименованиеПолное : Строка
ТарифнаяСетка : Справочник.Тарифная группа
}
@enduml
