@startuml Сертификаты1СОтчетности
'!include templates.wsd
'..\include templates.wsd
class Справочник.Сертификаты1СОтчетности as "Сертификаты 1С-Отчетности" <<Справочники>>
{
..Реквизиты..
ДатаНачала : Дата
ДатаОкончания : Дата
Идентификатор : Строка
Сертификат : Хранилище значения
СерийныйНомер : Хранилище значения
Отпечаток : Хранилище значения
ОтпечатокПредставление : Строка
СерийныйНомерПредставление : Строка
ОткрытыйКлючПредставление : Строка
Криптопровайдер : Типы крипто провайдеров
}
@enduml
