@startuml МакетыПенсионныхДел
'!include templates.wsd
'..\include templates.wsd
class Справочник.МакетыПенсионныхДел as "Макеты пенсионных дел" <<Справочники>>
{
..Реквизиты..
Статус : Статусы писем
Организация : Справочник.Организация
Отправитель : Справочник.Организация
Получатель : Справочник.Органы ПФР
Содержание : Строка
ДатаСоздания : Дата
ДатаОтправки : Дата
Идентификатор : Строка
ИдентификаторОснования : Строка
ДатаВыходаНаПенсию : Дата
Стаж : Виды стажа для назначения пенсии
Сотрудник : Справочник.Сотрудник
ОрганПФРПоМестуНазначенияПенсии : Строка
СтраховойНомерПФР : Строка
АдресРегистрации : Строка
Телефон : Строка
ФИО : Строка
Тип : Типы переписки с контролирующими органами
..Табличная часть \n ЭлектронныеДокументы..
Документ : Строка
Файл : Справочник.Присоединенные файлы (Макеты пенсионных дел)
Страница1 : Число 2, 0
Страница2 : Число 2, 0
Размер : Число 10, 0
}
@enduml
