@startuml ТарифныеСетки
'!include templates.wsd
'..\include templates.wsd
class Справочник.ТарифныеСетки as "Тарифные группы" <<Справочники>>
{
..Реквизиты..
ПрименениеТарифныхКоэффициентов : Булево
УдалитьВидТарифа : Виды тарифных ставок
НаименованиеПолное : Строка
ВидТарифнойСетки : Виды тарифных сеток
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
