@startuml МаршрутыПодписания
'!include templates.wsd
'..\include templates.wsd
class Справочник.МаршрутыПодписания as "Маршруты подписания" <<Справочники>>
{
..Реквизиты..
СхемаПодписания : Схемы подписания ЭД
Организация : Справочник.Организация
КлючАвтоматическойНастройки : Строка
..Табличная часть \n ТаблицаТребований..
Идентификатор : Строка
ИдентификаторРодителя : Строка
Порядок : Число 10, 0
Требование : Требования к подписанию ЭД
Подписант : Справочник.Пользователь
Сертификат : Справочник.Сертификат ключа электронной подписи и шифрования
}
@enduml
