@startuml ОтправкиФСС
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОтправкиФСС as "Отправки в ФСС" <<Справочники>>
{
..Реквизиты..
ОтчетСсылка : Справочник.Загруженный отчет\rДокумент.Реестр сведений, необходимых для назначения и выплаты пособий\rДокумент.Реестр ЭЛН для отправки в ФСС\r...
ИдентификаторОтправкиНаСервере : Строка
ЗашифрованныйПакет : Хранилище значения
ИмяФайлаПакета : Строка
СтатусОтправки : Статусы отправки
Протокол : Хранилище значения
ДатаОтправки : Дата
ДатаПолученияРезультата : Дата
Организация : Справочник.Организация
КодОрганаФСС : Строка
Квитанция : Хранилище значения
ДатаНачалаПериода : Дата
ДатаОкончанияПериода : Дата
Период : Строка
Версия : Число 3, 0
ВидОтчета : Справочник.Виды отправляемых документов
ДатаЗакрытия : Дата
ПредставлениеПериода : Строка
ПредставлениеВидаДокумента : Строка
}
@enduml
