@startuml НастройкиХозяйственныхОпераций
'!include templates.wsd
'..\include templates.wsd
class Справочник.НастройкиХозяйственныхОпераций as "Хозяйственные операции" <<Справочники>>
{
..Реквизиты..
ИсточникДанных : Строка
ПредставлениеИсточникаДанных : Строка
Приход : Типы данных учета
Расход : Типы данных учета
Описание : Строка
ХозяйственнаяОперация : Хозяйственные операции
ИспользоватьВБюджетировании : Булево
ИспользоватьВМеждународномУчете : Булево
ИспользоватьДляВыбора : Булево
ИспользоватьВРеестреДокументов : Булево
..Табличная часть \n ПоказателиРегистра..
Показатель : Показатели аналитических регистров
Использование : Булево
..Табличная часть \n Документы..
ИмяДокумента : Строка
ПредставлениеДокумента : Строка
ИдентификаторОбъектаМетаданных : Справочник.Идентификатор объекта метаданных
..Табличная часть \n ФункциональныеОпции..
ИмяФункциональнойОпции : Строка
}
@enduml
