@startuml ТомаХраненияФайлов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ТомаХраненияФайлов as "Тома хранения файлов" <<Справочники>>
{
..Реквизиты..
Комментарий : Строка
МаксимальныйРазмер : Число 10, 0
ПолныйПутьLinux : Строка
ПолныйПутьWindows : Строка
ПорядокЗаполнения : Число 3, 0
}
@enduml
