@startuml СпособыРаспределенияПоНаправлениямДеятельности
'!include templates.wsd
'..\include templates.wsd
class Справочник.СпособыРаспределенияПоНаправлениямДеятельности as "Способы распределения по направлениям деятельности" <<Справочники>>
{
..Реквизиты..
ПравилоРаспределения : Правила распределения по направлениям деятельности
..Табличная часть \n НаправленияДеятельности..
НаправлениеДеятельности : Справочник.Направление деятельности
Коэффициент : Число 15, 3
}
@enduml
