@startuml ЕдиныеНормыАмортизационныхОтчисленийОсновныхФондов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ЕдиныеНормыАмортизационныхОтчисленийОсновныхФондов as "Классификатор ЕНАОФ" <<Справочники>>
{
..Реквизиты..
НормаАмортизационныхОтчислений : Число 4, 2
ПроцентОтСтоимостиМашины : Число 4, 2
}
@enduml
