@startuml НаборыУпаковок
'!include templates.wsd
'..\include templates.wsd
class Справочник.НаборыУпаковок as "Наборы упаковок" <<Справочники>>
{
..Реквизиты..
ЕдиницаИзмерения : Справочник.Упаковка
ЕдиницаДляОтчетов : Справочник.Упаковка
КоэффициентЕдиницыДляОтчетов : Число 15, 3
}
@enduml
