@startuml УдалитьОтправкиФСС
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьОтправкиФСС as "(не используется) Отправки в ФСС" <<Справочники>>
{
..Реквизиты..
ОтчетСсылка : Документ.Регламентированный отчет\rСправочник.(не используется) Электронные представления регламентированных отчетов
ИдентификаторОтправкиНаСервере : Строка
ЗашифрованныйПакет : Хранилище значения
ИмяФайлаПакета : Строка
СтатусОтправки : Статусы отправки
Протокол : Хранилище значения
ДатаОтправки : Дата
ДатаПолученияРезультата : Дата
Организация : Справочник.Организация
КодОрганаФСС : Строка
Квитанция : Хранилище значения
}
@enduml
