@startuml ГруппыФинансовогоУчетаРасчетов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГруппыФинансовогоУчетаРасчетов as "Группы настроек фин. учета расчетов" <<Справочники>>
{
..Реквизиты..
ПорядокОплаты : Порядок оплаты
Описание : Строка
СчетУчетаРасчетовСКлиентами : Счет бухгалтерского учета
СчетУчетаАвансовПолученных : Счет бухгалтерского учета
УдалитьСчетУчетаРасчетовПоВознаграждению : Счет бухгалтерского учета
СчетУчетаРасчетовСПоставщиками : Счет бухгалтерского учета
СчетУчетаАвансовВыданных : Счет бухгалтерского учета
СчетУчетаРасчетовПоПретензиям : Счет бухгалтерского учета
СчетУчетаРасчетовСКлиентамиТара : Счет бухгалтерского учета
СчетУчетаРасчетовСПоставщикамиТара : Счет бухгалтерского учета
СчетУчетаРасчетовСКредиторамиОсновнойДолг : Счет бухгалтерского учета
СчетУчетаРасчетовСКредиторамиПроценты : Счет бухгалтерского учета
СчетУчетаРасчетовСКредиторамиКомиссия : Счет бухгалтерского учета
СчетУчетаРасчетовСДебиторамиОсновнойДолг : Счет бухгалтерского учета
СчетУчетаРасчетовСДебиторамиПроценты : Счет бухгалтерского учета
СчетУчетаРасчетовСДебиторамиКомиссия : Счет бухгалтерского учета
СчетУчетаНеотфактурованныеПоставки : Счет бухгалтерского учета
РасчетыСКлиентами : Булево
РасчетыСПоставщиками : Булево
РасчетыСКомиссионерами : Булево
РасчетыСКомитентами : Булево
РасчетыСКредиторами : Булево
РасчетыСДебиторами : Булево
}
@enduml
