@startuml УсловияТруда
'!include templates.wsd
'..\include templates.wsd
class Справочник.УсловияТруда as "Условия труда" <<Справочники>>
{
..Реквизиты..
ВзимаютсяВзносыЗаЗанятыхНаРаботахСДосрочнойПенсией : Виды работ с досрочной пенсией
ОснованиеДосрочногоНазначенияПенсии : Справочник.Основание для досрочной пенсии
ОсобыеУсловияТрудаПФР : Справочник.Особое условие труда
ПроцентНадбавкиЗаВредность : Число 5, 2
ВыплачиваетсяНадбавкаЗаВредность : Булево
КоличествоДнейДополнительногоОтпускаВГод : Число 2, 0
КодПозицииСпискаПФР : Справочник.Льготная профессия (ПФР)
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
