@startuml СкладскиеЯчейки
'!include templates.wsd
'..\include templates.wsd
class Справочник.СкладскиеЯчейки as "Складские ячейки" <<Справочники>>
{
..Реквизиты..
Линия : Строка
ОбластьХранения : Справочник.Область хранения
Позиция : Строка
ПорядокОбхода : Число 6, 0
РабочийУчасток : Справочник.Рабочий участок
Секция : Строка
Помещение : Справочник.Помещение
Стеллаж : Строка
Типоразмер : Справочник.Типоразмер ячейки
ТипСкладскойЯчейки : Типы складских ячеек
УровеньДоступности : Число 2, 0
Ярус : Строка
МаксимальныйКоэффициентНаполненностиПоВесу : Число 3, 0
МаксимальныйКоэффициентНаполненностиПоОбъему : Число 3, 0
ИспользованиеПериодичностиИнвентаризацииЯчейки : Варианты использования периодической инвентаризации ячеек
КоличествоДнейМеждуИнвентаризациями : Число 10, 0
}
@enduml
