@startuml СобытияОтправкиОтчетности
'!include templates.wsd
'..\include templates.wsd
class Справочник.СобытияОтправкиОтчетности as "События отправки отчетности" <<Справочники>>
{
..Реквизиты..
ДатаПолучения : Дата
Отправка : Строка\rСправочник.Отправки отчетности
ИсходныйСтатус : Статусы отправки отчетности
Статус : Статусы отправки отчетности
ТребуетАудита : Булево
АудитПроведен : Булево
Комментарий : Строка
..Табличная часть \n ПричиныОтказа..
ИсходнаяПричина : Строка
НеПоказывать : Булево
Причина : Строка
ПояснениеАудитора : Строка
}
@enduml
