@startuml ПрограммыЭлектроннойПодписиИШифрования
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПрограммыЭлектроннойПодписиИШифрования as "Программы электронной подписи и шифрования" <<Справочники>>
{
..Реквизиты..
ИмяПрограммы : Строка
ТипПрограммы : Число 9, 0
АлгоритмПодписи : Строка
АлгоритмХеширования : Строка
АлгоритмШифрования : Строка
ЭтоПрограммаОблачногоСервиса : Булево
}
@enduml
