@startuml НастройкиОбменСБанками
'!include templates.wsd
'..\include templates.wsd
class Справочник.НастройкиОбменСБанками as "Настройки обмена с банками" <<Справочники>>
{
..Реквизиты..
АдресСервера : Строка
АутентификацияПоСертификату : Булево
Банк : Справочник.Банк
УдалитьВерсияВнешнейКомпоненты : Строка
ВерсияФормата : Строка
УдалитьВнешняяКомпонента : Хранилище значения
ИдентификаторОрганизации : Строка
ИмяВнешнегоМодуля : Строка
ИмяПользователя : Строка
ИспользуетсяКриптография : Булево
Комментарий : Строка
Недействительна : Булево
Организация : Справочник.Организация
ПрограммаБанка : Программы банка
РесурсВходящихДокументов : Строка
РесурсИсходящихДокументов : Строка
СертификатБанка : Хранилище значения
СжиматьДанныеПакетаЭД : Булево
УдалитьДополнительнаяОбработка : Справочник.Дополнительный отчет или обработка
..Табличная часть \n ИсходящиеДокументы..
ИсходящийДокумент : Виды электронных документов обмена с банками
ИспользоватьЭП : Булево
Формировать : Булево
МаршрутПодписания : Справочник.Маршрут подписания
..Табличная часть \n СертификатыПодписейОрганизации..
СертификатЭП : Справочник.Сертификат ключа электронной подписи и шифрования
}
@enduml
