@startuml ОписиВходящихДокументовИзНалоговыхОрганов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОписиВходящихДокументовИзНалоговыхОрганов as "Описи входящих документов, полученных из налоговых органов" <<Справочники>>
{
..Реквизиты..
НалоговыйОрган : Справочник.Налоговые органы
Организация : Справочник.Организация
Идентификатор : Строка
ИдентификаторОснования : Строка
ДатаСообщения : Дата
ДатаОтправки : Дата
..Табличная часть \n ВходящиеДокументы..
СсылкаНаОбъект : Справочник.Документы реализации полномочий налоговых органов
}
@enduml
