@startuml СтатистическиеПоказатели
'!include templates.wsd
'..\include templates.wsd
class Справочник.СтатистическиеПоказатели as "Статистические показатели" <<Справочники>>
{
..Реквизиты..
Детализировать : Булево
ХарактеристикаОбъектаНаблюдения : Строка
}
@enduml
