@startuml ВидыОбразованияФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыОбразованияФизическихЛиц as "Виды образования" <<Справочники>>
{
..Реквизиты..
ФасетОКИН : Число 2, 0
}
@enduml
