@startuml ВидыЦенПоставщиков
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыЦенПоставщиков as "Виды цен поставщиков" <<Справочники>>
{
..Реквизиты..
Валюта : Справочник.Валюта
ЦенаВключаетНДС : Булево
ДоступноДляЗакупки : Булево
ДоступноДляПродажиКлиентам : Булево
РеквизитДопУпорядочивания : Число 5, 0
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
