@startuml ВариантыКомплектацииНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВариантыКомплектацииНоменклатуры as "Варианты комплектации номенклатуры" <<Справочники>>
{
..Реквизиты..
Характеристика : Справочник.Характеристика номенклатуры
Основной : Булево
НоменклатураОсновногоКомпонента : Справочник.Номенклатура
ХарактеристикаОсновногоКомпонента : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
ДлительностьСборкиРазборки : Число 3, 0
ВариантРасчетаЦеныНабора : Варианты расчета цен наборов
ВариантПредставленияНабораВПечатныхФормах : Варианты представления наборов в печатных формах
СодержитТовары : Булево
СодержитУслуги : Булево
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
ДоляСтоимости : Число 10, 0
Количество : Число 15, 3
}
@enduml
