@startuml ВидыРаботСотрудников
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыРаботСотрудников as "Виды работ сотрудников" <<Справочники>>
{
..Реквизиты..
ЕдиницаИзмерения : Справочник.Упаковка
Трудоемкость : Число 15, 3
КратностьТрудоемкости : Число 15, 3
КвалификационныйРазряд : Справочник.Квалификационный разряд (категория)
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
