@startuml ВидыВыплатБывшимСотрудникам
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыВыплатБывшимСотрудникам as "Виды выплат бывшим сотрудникам" <<Справочники>>
{
..Реквизиты..
КодДоходаНДФЛ : Справочник.Вид дохода НДФЛ
УдалитьКодДоходаНДФЛ : Справочник.(не используется) Виды доходов НДФЛ
КодДоходаСтраховыеВзносы : Справочник.Вид дохода по страховым взносам
УдалитьКодДоходаСтраховыеВзносы : Справочник.(не используется) Виды доходов (взносы)
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
