@startuml Пользователи
'!include templates.wsd
'..\include templates.wsd
class Справочник.Пользователи as "Пользователи" <<Справочники>>
{
..Реквизиты..
Недействителен : Булево
Подразделение : Справочник.Подразделение
ФизическоеЛицо : Справочник.Физическое лицо
Комментарий : Строка
Служебный : Булево
Подготовлен : Булево
ИдентификаторПользователяИБ : Уникальный идентификатор
ИдентификаторПользователяСервиса : Уникальный идентификатор
СвойстваПользователяИБ : Хранилище значения
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n КонтактнаяИнформация..
Тип : Типы контактной информации
Вид : Справочник.Вид контактной информации
Представление : Строка
ЗначенияПолей : Строка
Страна : Строка
Регион : Строка
Город : Строка
АдресЭП : Строка
ДоменноеИмяСервера : Строка
НомерТелефона : Строка
НомерТелефонаБезКодов : Строка
ВидДляСписка : Справочник.Вид контактной информации
}
@enduml
