@startuml НемонетарныеПоказатели
'!include templates.wsd
'..\include templates.wsd
class Справочник.НемонетарныеПоказатели as "Немонетарные показатели финансовой отчетности" <<Справочники>>
{
..Реквизиты..
НаименованиеДляПечати : Строка
Комментарий : Строка
}
@enduml
