@startuml СпособыОкругленияПриРасчетеЗарплаты
'!include templates.wsd
'..\include templates.wsd
class Справочник.СпособыОкругленияПриРасчетеЗарплаты as "Способы округления зарплаты" <<Справочники>>
{
..Реквизиты..
Точность : Число 7, 2
ПравилоОкругления : Правила округления (для целей расчета зарплаты)
}
@enduml
