@startuml Организации
'!include templates.wsd
'..\include templates.wsd
class Справочник.Организации as "Организации" <<Справочники>>
{
..Реквизиты..
ВидОбменаСКонтролирующимиОрганами : Виды обмена с контролирующими органами
Военкомат : Справочник.Военкомат
ГоловнаяОрганизация : Справочник.Организация
ГрафикРаботы : Справочник.График работы
ИНН : Строка
ДатаРегистрации : Дата
ДополнительныйКодФСС : Строка
ЕстьОбособленныеПодразделения : Булево
ИндивидуальныйПредприниматель : Справочник.Физическое лицо
КодНалоговогоОргана : Строка
ИностраннаяОрганизация : Булево
ИПКодПодчиненностиФСС : Строка
ИПРегистрационныйНомерПФР : Строка
ИПРегистрационныйНомерТФОМС : Строка
ИПРегистрационныйНомерФСС : Строка
КодВСтранеРегистрации : Строка
КодНалоговогоОрганаПолучателя : Строка
КодОрганаПФР : Строка
КодОрганаФСГС : Строка
КодОКОНХ : Строка
КодПоОКАТО : Строка
КодПоОКПО : Строка
КодПодчиненностиФСС : Строка
КрупнейшийНалогоплательщик : Булево
НаименованиеПолное : Строка
НаименованиеСокращенное : Строка
НаименованиеТерриториальногоОрганаПФР : Строка
НаименованиеТерриториальногоОрганаФСС : Строка
НаименованиеИнострОрганизации : Строка
НаименованиеНалоговогоОргана : Строка
ОбменКаталогОтправкиДанныхОтчетности : Строка
ОбменКаталогПрограммыЭлектроннойПочты : Строка
ОбменКодАбонента : Строка
ОбособленноеПодразделение : Булево
ОГРН : Строка
КПП : Строка
ПрименятьРайонныйКоэффициент : Булево
ПрименятьСевернуюНадбавку : Булево
РайонныйКоэффициент : Число 3, 2
Префикс : Строка
РегистрационныйНомерФСС : Строка
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
УдалитьТерриториальныеУсловияПФР : Справочник.(не используется) Территориальные условия
РегистрационныйНомерПФР : Строка
СвидетельствоДатаВыдачи : Дата
УчетнаяЗаписьОбмена : Справочник.Учетные записи документооборота
КодОКВЭД : Строка
НаименованиеОКВЭД : Строка
КодОКОПФ : Строка
РегистрационныйНомерТФОМС : Строка
НаименованиеОКОПФ : Строка
КодОКФС : Строка
РайонныйКоэффициентРФ : Число 3, 2
СвидетельствоСерияНомер : Строка
СтранаПостоянногоМестонахождения : Справочник.Страна мира
СтранаРегистрации : Справочник.Страна мира
ГрафикРаботыСотрудников : Справочник.График работы
НаименованиеОКФС : Строка
ЦифровойИндексОбособленногоПодразделения : Число 5, 0
ПроцентСевернойНадбавки : Число 5, 2
ЮрФизЛицо : Юр/Физлицо
ЮридическоеФизическоеЛицо : Юридическое / физическое лицо
ФайлЛоготип : Справочник.Присоединенный файл (Организации)
ФайлФаксимильнаяПечать : Справочник.Присоединенный файл (Организации)
ДопускаютсяВзаиморасчетыЧерезГоловнуюОрганизацию : Булево
ЗарегистрированВОЭЗ : Булево
КодОКВЭД2 : Строка
НаименованиеОКВЭД2 : Строка
..Табличная часть \n КонтактнаяИнформация..
Тип : Типы контактной информации
Вид : Справочник.Вид контактной информации
Представление : Строка
ЗначенияПолей : Строка
Страна : Строка
Регион : Строка
Город : Строка
АдресЭП : Строка
ДоменноеИмяСервера : Строка
НомерТелефона : Строка
НомерТелефонаБезКодов : Строка
ВидДляСписка : Справочник.Вид контактной информации
ДействуетС : Дата
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
