@startuml ПакетОбменСБанкамиПрисоединенныеФайлы
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПакетОбменСБанкамиПрисоединенныеФайлы as "Присоединенные файлы (Пакет обмена с банками)" <<Справочники>>
{
..Реквизиты..
Автор : Справочник.Внешний пользователь\rСправочник.Учетная запись синхронизации файлов\rСправочник.Пользователь
ВладелецФайла : Документ.Пакет прямого обмена с банками
ДатаМодификацииУниверсальная : Дата
ДатаСоздания : Дата
Зашифрован : Булево
Изменил : Справочник.Внешний пользователь\rСправочник.Учетная запись синхронизации файлов\rСправочник.Пользователь
ИндексКартинки : Число 10, 0
Описание : Строка
ПодписанЭП : Булево
ПутьКФайлу : Строка
Размер : Число 10, 0
Расширение : Строка
Редактирует : Справочник.Внешний пользователь\rСправочник.Учетная запись синхронизации файлов\rСправочник.Пользователь
СтатусИзвлеченияТекста : Статусы извлечения текста файлов
ТекстХранилище : Хранилище значения
ТипХраненияФайла : Типы хранения файлов
Том : Справочник.Том хранения файлов
ФайлХранилище : Хранилище значения
ХранитьВерсии : Булево
ДатаЗаема : Дата
..Табличная часть \n УдалитьЭлектронныеПодписи..
ДатаПодписи : Дата
ИмяФайлаПодписи : Строка
Комментарий : Строка
КомуВыданСертификат : Строка
Отпечаток : Строка
Подпись : Хранилище значения
УстановившийПодпись : Справочник.Пользователь
Сертификат : Хранилище значения
ДатаПроверкиПодписи : Дата
ПодписьВерна : Булево
..Табличная часть \n УдалитьСертификатыШифрования..
Отпечаток : Строка
Представление : Строка
Сертификат : Хранилище значения
}
@enduml
