@startuml ОбъектыСтатистическогоНаблюдения
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОбъектыСтатистическогоНаблюдения as "Объекты наблюдения" <<Справочники>>
{
..Реквизиты..
ИсточникДанных : Источники данных статистических показателей
Детализация : Виды свободных строк форм статистики
ДатаИзменения : Дата
ТребуетНастройки : Булево
Настройка : Строка
РеквизитДопУпорядочивания : Число 5, 0
}
@enduml
