@startuml МоделиПооперационногоПланирования
'!include templates.wsd
'..\include templates.wsd
class Справочник.МоделиПооперационногоПланирования as "Модели пооперационного планирования" <<Справочники>>
{
..Реквизиты..
ВесМинимизироватьВремя : Число 4, 3
ВесМинимизироватьСтоимость : Число 4, 3
СпособЗагрузки : Способы загрузки вида рабочего центра
}
@enduml
