@startuml ВедомостьПрочихДоходовВКассуПрисоединенныеФайлы
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВедомостьПрочихДоходовВКассуПрисоединенныеФайлы as "Присоединенные файлы (Ведомость прочих доходов в кассу)" <<Справочники>>
{
..Реквизиты..
Автор : Справочник.Учетная запись синхронизации файлов\rСправочник.Пользователь
ВладелецФайла : Документ.Ведомость прочих доходов в кассу
ДатаМодификацииУниверсальная : Дата
ДатаСоздания : Дата
Зашифрован : Булево
Изменил : Справочник.Учетная запись синхронизации файлов\rСправочник.Пользователь
ИндексКартинки : Число 10, 0
Описание : Строка
ПодписанЭП : Булево
ПутьКФайлу : Строка
Размер : Число 10, 0
Расширение : Строка
Редактирует : Справочник.Учетная запись синхронизации файлов\rСправочник.Пользователь
СтатусИзвлеченияТекста : Статусы извлечения текста файлов
ТекстХранилище : Хранилище значения
ТипХраненияФайла : Типы хранения файлов
Том : Справочник.Том хранения файлов
ФайлХранилище : Хранилище значения
ДатаЗаема : Дата
ХранитьВерсии : Булево
}
@enduml
