@startuml ДокументыРеализацииПолномочийНалоговыхОрганов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ДокументыРеализацииПолномочийНалоговыхОрганов as "Документы реализации полномочий налоговых органов" <<Справочники>>
{
..Реквизиты..
НалоговыйОрган : Справочник.Налоговые органы
Организация : Справочник.Организация
Идентификатор : Строка
ИдентификаторОснования : Строка
ВидДокумента : Виды налоговых документов\rСтрока
НомерДокумента : Строка
ДатаДокумента : Дата
ДатаСообщения : Дата
ДатаОтправки : Дата
ПодписантДолжность : Строка
ПодписантТелефон : Строка
ПодписантПочта : Строка
ПодписантФИО : Строка
ДокументОснование : Документ.Выгрузка регламентированных отчетов\rДокумент.Сведения о заработке и стаже застрахованных лиц, СЗВ-ИСХ\rДокумент.2-НДФЛ для передачи в ИФНС\r...
}
@enduml
