@startuml Военкоматы
'!include templates.wsd
'..\include templates.wsd
class Справочник.Военкоматы as "Военкоматы" <<Справочники>>
{
..Реквизиты..
Адрес : Строка
АдресВнутреннееПредставление : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
