@startuml ПричиныОтменыЗаказовКлиентов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПричиныОтменыЗаказовКлиентов as "Причины отмены заказов клиентов" <<Справочники>>
{
..Реквизиты..
Описание : Строка
ДоступнаДляУказанияКлиентом : Булево
}
@enduml
