@startuml КомплектыФинансовыхОтчетов
'!include templates.wsd
'..\include templates.wsd
class Справочник.КомплектыФинансовыхОтчетов as "Комплекты финансовых отчетов" <<Справочники>>
{
..Реквизиты..
Описание : Строка
Статус : Статусы комплектов финансовой отчетности
НачалоПериодаДействия : Дата
ОкончаниеПериодаДействия : Дата
РеквизитДопУпорядочивания : Число 5, 0
ВидПоказателей : Виды показателей отчетности
..Табличная часть \n ВидыОтчетов..
ВидФинансовогоОтчета : Справочник.Вид финансового отчета
}
@enduml
