@startuml ПартииТМЦВЭксплуатации
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПартииТМЦВЭксплуатации as "Партии ТМЦ в эксплуатации" <<Справочники>>
{
..Реквизиты..
Документ : Документ.Внутреннее потребление товаров\rДокумент.Первичный документ\rДокумент.Ввод начальных остатков
Дата : Дата
КатегорияЭксплуатации : Справочник.Категории эксплуатации
ИнвентарныйУчет : Булево
ИнвентарныйНомер : Строка
СрокЭксплуатации : Число 5, 0
ДатаЗавершенияЭксплуатации : Дата
СпособПогашенияСтоимостиБУ : Способы погашения стоимости ТМЦ
ЕдиницаИзмеренияНаработки : Справочник.Упаковка
ОбъемНаработки : Число 15, 3
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ФизическоеЛицо : Справочник.Физическое лицо
СпособПогашенияСтоимостиНУ : Способы погашения стоимости ТМЦ
НаправлениеДеятельности : Справочник.Направление деятельности
}
@enduml
