@startuml Справки1ЕГАИС
'!include templates.wsd
'..\include templates.wsd
class Справочник.Справки1ЕГАИС as "Справки 1 ЕГАИС" <<Справочники>>
{
..Реквизиты..
РегистрационныйНомер : Строка
НомерТТН : Строка
ДатаТТН : Дата
Грузоотправитель : Справочник.Организация ЕГАИС
Грузополучатель : Справочник.Организация ЕГАИС
ДатаОтгрузки : Дата
АлкогольнаяПродукция : Справочник.Алкогольная продукция ЕГАИС
ДатаРозлива : Дата
Количество : Число 15, 3
НомерПодтвержденияЕГАИС : Строка
ДатаПодтвержденияЕГАИС : Дата
}
@enduml
