@startuml ПодпискиНаРассылкиИОповещенияКлиентам
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПодпискиНаРассылкиИОповещенияКлиентам as "Подписки на рассылки и оповещения клиентам" <<Справочники>>
{
..Реквизиты..
ГруппаРассылокИОповещений : Справочник.Группа рассылок и оповещений
ОтправлятьПартнеру : Булево
ВидКИПартнераДляПисем : Справочник.Вид контактной информации
ВидКИПартнераДляSMS : Справочник.Вид контактной информации
ОтправлятьКонтактномуЛицуОбъектаОповещения : Булево
ВидКИКонтактногоЛицаОбъектаОповещенияДляПисем : Справочник.Вид контактной информации
ВидКИКонтактногоЛицаОбъектаОповещенияДляSMS : Справочник.Вид контактной информации
ПодпискаДействует : Булево
КоличествоКонтактныхЛицАдресатов : Число 10, 0
..Табличная часть \n КонтактныеЛица..
КонтактноеЛицо : Справочник.Контактное лицо
ВидКИДляПисем : Справочник.Вид контактной информации
ВидКИДляSMS : Справочник.Вид контактной информации
}
@enduml
