@startuml ВидыРегистровУчета
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыРегистровУчета as "Виды регистров учета" <<Справочники>>
{
..Реквизиты..
Отчет : Справочник.Идентификатор объекта метаданных
ВариантОтчета : Строка
}
@enduml
