@startuml ОбщероссийскийКлассификаторОсновныхФондов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОбщероссийскийКлассификаторОсновныхФондов as "Классификатор ОКОФ" <<Справочники>>
{
..Реквизиты..
КонтрольноеЧисло : Строка
НаименованиеГруппировки : Строка
}
@enduml
