@startuml КодыОперацийРаздела7ДекларацииПоНДС
'!include templates.wsd
'..\include templates.wsd
class Справочник.КодыОперацийРаздела7ДекларацииПоНДС as "Коды операций раздела 7 декларации по НДС" <<Справочники>>
{
..Реквизиты..
ОперацияНеПодлежитНалогообложению : Булево
ВидНеоблагаемойОперации : Строка
ВключаетсяВРеестрПодтверждающихДокументов : Булево
}
@enduml
