@startuml КлассификаторОрганизацийЕГАИС
'!include templates.wsd
'..\include templates.wsd
class Справочник.КлассификаторОрганизацийЕГАИС as "Классификатор организаций ЕГАИС" <<Справочники>>
{
..Реквизиты..
ТипОрганизации : Типы организаций ЕГАИС
НаименованиеПолное : Строка
ИНН : Строка
КПП : Строка
ИдентификаторОрганизацииТС : Строка
КодСтраны : Число 3, 0
КодРегиона : Число 3, 0
ПочтовыйИндекс : Число 6, 0
ПредставлениеАдреса : Строка
Сопоставлено : Булево
СоответствуетОрганизации : Булево
Контрагент : Справочник.Организация\rСправочник.Контрагент
ТорговыйОбъект : Справочник.Партнер\rСправочник.Склад (складская территория)
НаходитсяВСельскойМестности : Булево
ФорматОбмена : Форматы обмена ЕГАИС
Адрес : Строка
УдалитьУНП : Строка
УдалитьРНН : Строка
УдалитьОрганизация : Справочник.Организация
УдалитьПартнер : Справочник.Партнер
}
@enduml
