@startuml ПоставщикиУслугСервиса
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПоставщикиУслугСервиса as "Поставщики услуг сервиса" <<Справочники>>
{
..Реквизиты..
Идентификатор : Строка
}
@enduml
