@startuml РегламентированныеОтчеты
'!include templates.wsd
'..\include templates.wsd
class Справочник.РегламентированныеОтчеты as "Регламентированные отчеты" <<Справочники>>
{
..Реквизиты..
ИсточникОтчета : Строка
Описание : Строка
Периоды : Хранилище значения
ВнешнийОтчетИспользовать : Булево
ВнешнийОтчетХранилище : Хранилище значения
ВнешнийОтчетВерсия : Строка
УИДОтчета : Строка
}
@enduml
