@startuml ПодклассыОбъектовЭксплуатации
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПодклассыОбъектовЭксплуатации as "Подклассы объектов эксплуатации" <<Справочники>>
{
..Реквизиты..
РемонтныйЦиклПоИнтервалуНаработки : Булево
Описание : Строка
..Табличная часть \n РемонтныйЦикл..
ВидРемонта : Справочник.Вид ремонта
ИнтервалВремени : Число 15, 0
ЕдиницаВремени : Единицы измерения времени
ИнтервалНаработки : Число 15, 3
ПоказательНаработки : Справочник.Показатель наработки
..Табличная часть \n ПрочиеРемонты..
ВидРемонта : Справочник.Вид ремонта
ПоИнтервалуНаработки : Булево
ИнтервалВремени : Число 15, 0
ЕдиницаВремени : Единицы измерения времени
ИнтервалНаработки : Число 15, 3
ПоказательНаработки : Справочник.Показатель наработки
}
@enduml
