@startuml ПрофилиНастроекЭДО
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПрофилиНастроекЭДО as "Профили настроек ЭДО" <<Справочники>>
{
..Реквизиты..
АдресСервера : Строка
Город : Строка
Дом : Строка
ИдентификаторОрганизации : Строка
Индекс : Строка
Квартира : Строка
КодНалоговогоОргана : Строка
КодРегиона : Строка
Корпус : Строка
Логин : Строка
НаселенныйПункт : Строка
ОператорЭДО : Строка
ОператорЭДОИд : Строка
ОператорЭДОИНН : Строка
ОператорЭДОКПП : Строка
ОператорЭДООГРН : Строка
Организация : Справочник.Организация
Пароль : Строка
ПассивноеСоединение : Булево
Порт : Число 5, 0
Район : Строка
Регион : Строка
РесурсВходящихДокументов : Строка\rСправочник.Учетная запись электронной почты
СпособОбменаЭД : Способы обмена электронными документами
Улица : Строка
ШаблонТекстаПриглашений : Строка
ЭлектроннаяПочтаДляУведомлений : Строка
ИспользоватьУПД : Булево
ИспользоватьУКД : Булево
..Табличная часть \n СертификатыПодписейОрганизации..
НомерКонтейнера : Число 2, 0
Сертификат : Справочник.Сертификат ключа электронной подписи и шифрования
УдалитьСертификат : Справочник.Сертификат электронной подписи
..Табличная часть \n ИсходящиеДокументы..
ВерсияФормата : Строка
ДокументУчета : Строка
ИспользоватьЭП : Булево
ИсходящийДокумент : Виды электронных документов
Приоритет : Число 10, 0
ТребуетсяИзвещениеОПолучении : Булево
ТребуетсяОтветнаяПодпись : Булево
Формировать : Булево
МаршрутПодписания : Справочник.Маршрут подписания
}
@enduml
