@startuml ПравилаИнтеграцииС1СДокументооборотом
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПравилаИнтеграцииС1СДокументооборотом as "Правила интеграции с 1С:Документооборотом" <<Справочники>>
{
..Реквизиты..
ТипОбъектаПотребителя : Строка
ТипОбъектаДокументооборота : Строка
Комментарий : Строка
ТипФайловСохраненияПечатныхФорм : Типы файлов сохранения печатных форм объектов
ВыгружатьИзменения : Булево
ЗагружатьИзменения : Булево
ШаблонЗапрещаетИзменение : Булево
Шаблон : Строка
ШаблонТип : Строка
ШаблонID : Строка
УсловиеПрименимостиПриВыгрузке : Строка
УсловиеПрименимостиПриЗагрузке : Строка
ПредставлениеОбъектаПотребителя : Строка
ПредставлениеОбъектаДокументооборота : Строка
НеСоздаватьСвязиПоСсылкам : Булево
..Табличная часть \n ПравилаЗаполненияРеквизитовПриВыгрузке..
ИмяРеквизитаОбъектаДокументооборота : Строка
ВариантПравилаЗаполненияРеквизитов : Варианты правил заполнения реквизитов
ИмяРеквизитаОбъектаПотребителя : Строка
ЗначениеРеквизитаДокументооборота : Булево\rСтрока\rДата\r...
ИдентификаторЗначенияРеквизита : Строка
ТипЗначенияРеквизита : Строка
ВычисляемоеВыражение : Строка
ДополнительныйРеквизитОбъекта : Булево
ДополнительныйРеквизитОбъектаСвойство : Дополнительный реквизит / сведение
ДополнительныйРеквизитДокументооборота : Булево
ДополнительныйРеквизитДокументооборотаID : Строка
ДополнительныйРеквизитДокументооборотаТип : Строка
ОбновлятьЗначение : Булево
ЗаполненВШаблоне : Булево
Ключевой : Булево
ШаблонЗначение : Булево\rСтрока\rДата\r...
ШаблонИдентификатор : Строка
ШаблонТип : Строка
..Табличная часть \n ПравилаЗаполненияРеквизитовПриЗагрузке..
ИмяРеквизитаОбъектаПотребителя : Строка
ВариантПравилаЗаполненияРеквизитов : Варианты правил заполнения реквизитов
ИмяРеквизитаОбъектаДокументооборота : Строка
ЗначениеРеквизитаПотребителя : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
ВычисляемоеВыражение : Строка
ДополнительныйРеквизитДокументооборота : Булево
ДополнительныйРеквизитДокументооборотаID : Строка
ДополнительныйРеквизитДокументооборотаТип : Строка
ДополнительныйРеквизитОбъекта : Булево
ДополнительныйРеквизитОбъектаСвойство : Дополнительный реквизит / сведение
ОбновлятьЗначение : Булево
Ключевой : Булево
..Табличная часть \n ПрисоединяемыеПечатныеФормы..
МенеджерПечати : Строка
ИмяКоманды : Строка
ПредставлениеКоманды : Строка
ОбновлятьЗначение : Булево
}
@enduml
