@startuml ЭтапыПроизводства
'!include templates.wsd
'..\include templates.wsd
class Справочник.ЭтапыПроизводства as "Этапы ресурсной спецификации" <<Справочники>>
{
..Реквизиты..
НомерЭтапа : Число 4, 0
НомерСледующегоЭтапа : Число 4, 0
Подразделение : Справочник.Подразделение
ОдновременноПроизводимоеКоличествоЕдиницПартийИзделий : Число 15, 3
ПланироватьРаботуВидовРабочихЦентров : Булево
ДлительностьЭтапа : Число 10, 0
ЕдиницаИзмеренияДлительностиЭтапа : Единицы измерения времени
ПредварительныйБуфер : Число 10, 0
ЗавершающийБуфер : Число 10, 0
ЕдиницаИзмеренияПредварительногоБуфера : Единицы измерения времени
ЕдиницаИзмеренияЗавершающегоБуфера : Единицы измерения времени
МаршрутнаяКарта : Справочник.Маршрутная карта
Описание : Строка
Непрерывный : Булево
ПроизводствоНаСтороне : Булево
Партнер : Справочник.Партнер
ГрафикРаботыПартнера : Справочник.График работы
МаксимальноеКоличествоЕдиницПартийИзделия : Число 15, 0
ЗанимаемаяМощность : Число 3, 0
УдалитьДнейДоОкончания : Число 10, 0
ПодходитНовойКонцепции : Булево
УслугаПереработчика : Справочник.Номенклатура
ХарактеристикаУслугиПереработчика : Справочник.Характеристика номенклатуры
СтатьяКалькуляции : Справочник.Статьи калькуляции
КоэффициентМаршрутнойКарты : Число 15, 3
ПорядокРаботыВидовРабочихЦентров : Порядок работы видов рабочих центров
..Табличная часть \n ВидыРабочихЦентров..
ВидРабочегоЦентра : Справочник.Вид рабочего центра
ВремяРаботы : Число 10, 1
ЕдиницаИзмерения : Единицы измерения времени
ВариантНаладки : Справочник.Вариант наладки
Загрузка : Число 15, 3
КлючСвязи : Уникальный идентификатор
Занятость : Число 15, 0
ОтборСвойство : Дополнительный реквизит / сведение
ОтборЗначениеСвойства : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
АлгоритмРасчетаКоличества : Строка
..Табличная часть \n АльтернативныеВидыРабочихЦентров..
ВидРабочегоЦентра : Справочник.Вид рабочего центра
ВремяРаботы : Число 10, 1
ЕдиницаИзмерения : Единицы измерения времени
ВариантНаладки : Справочник.Вариант наладки
Загрузка : Число 15, 3
КлючСвязиВидыРабочихЦентров : Уникальный идентификатор
ОтборСвойство : Дополнительный реквизит / сведение
ОтборЗначениеСвойства : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
АлгоритмРасчетаКоличества : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
