@startuml ГруппыФинансовогоУчетаНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГруппыФинансовогоУчетаНоменклатуры as "Группы настроек фин. учета номенклатуры" <<Справочники>>
{
..Реквизиты..
Описание : Строка
СчетУчетаПередачиНаКомиссию : Счет бухгалтерского учета
СчетУчетаВыручкиОтПродаж : Счет бухгалтерского учета
СчетУчетаСебестоимостиПродаж : Счет бухгалтерского учета
СчетУчетаНДСПриПродаже : Счет бухгалтерского учета
СчетУчетаНаСкладе : Счет бухгалтерского учета
СчетУчетаВПути : Счет бухгалтерского учета
СчетУчетаНДСВПути : Счет бухгалтерского учета
СчетУчетаНДСПриЗакупке : Счет бухгалтерского учета
СтатьяДоходовОСНО : Статьи доходов
ВидЦенностиНДС : Виды ценностей
СчетУчетаВыручкиОтПродажЕНВД : Счет бухгалтерского учета
СчетУчетаСебестоимостиПродажЕНВД : Счет бухгалтерского учета
СчетУчетаПередачиВПереработку : Счет бухгалтерского учета
СтатьяДоходовЕНВД : Статьи доходов
СчетУчетаЗатратыНаПриобретение : Счет бухгалтерского учета
}
@enduml
