@startuml ГруппыФинансовогоУчетаДенежныхСредств
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГруппыФинансовогоУчетаДенежныхСредств as "Группы настроек финансового учета денежных средств" <<Справочники>>
{
..Реквизиты..
Описание : Строка
}
@enduml
