@startuml НаправленияИспользованияПрибыли
'!include templates.wsd
'..\include templates.wsd
class Справочник.НаправленияИспользованияПрибыли as "Направления использования прибыли" <<Справочники>>
{
}
@enduml
