@startuml УбыткиПрошлыхЛет
'!include templates.wsd
'..\include templates.wsd
class Справочник.УбыткиПрошлыхЛет as "Убытки прошлых лет" <<Справочники>>
{
..Реквизиты..
ВидРБП : Виды РБП
ДатаНачалаСписания : Дата
ДатаОкончанияСписания : Дата
}
@enduml
