@startuml РабочиеЦентры
'!include templates.wsd
'..\include templates.wsd
class Справочник.РабочиеЦентры as "Рабочие центры" <<Справочники>>
{
..Реквизиты..
ВидРабочегоЦентра : Справочник.Вид рабочего центра
КоэффициентВремениРаботы : Число 5, 2
МаксимальнаяЗагрузка : Число 15, 3
Календарь : Справочник.График работы
Описание : Строка
РасценкаРабота : Число 15, 2
РасценкаПереналадка : Число 15, 2
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
