@startuml ВидыЦен
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыЦен as "Виды цен (Колонки прайс-листа)" <<Справочники>>
{
..Реквизиты..
ВалютаЦены : Справочник.Валюта
ЦенаВключаетНДС : Булево
ИспользоватьПриПродаже : Булево
ИспользоватьПриПередачеМеждуОрганизациями : Булево
ИспользоватьПриВыпускеПродукции : Булево
СпособЗаданияЦены : Способы задания цен
Формула : Строка
ОкруглятьВБольшуюСторону : Булево
РеквизитДопУпорядочивания : Число 5, 0
Идентификатор : Строка
ПорогСрабатывания : Число 10, 2
СхемаКомпоновкиДанных : Строка
ХранилищеСхемыКомпоновкиДанных : Хранилище значения
ХранилищеНастроекКомпоновкиДанных : Хранилище значения
БазовыйВидЦены : Справочник.Вид цены
Наценка : Число 10, 2
ТочностьОкругления : Число 15, 2
Округлять : Булево
УстанавливатьЦенуПриВводеНаОсновании : Булево
ИспользоватьПриПередачеПродукцииДавальцу : Булево
ВариантОкругления : Варианты округления
Статус : Статусы действия видов цен
..Табличная часть \n ВлияющиеВидыЦен..
ВлияющийВидЦен : Справочник.Вид цены
..Табличная часть \n ЦеновыеГруппы..
ЦеноваяГруппа : Справочник.Ценовая группа
Формула : Строка
БазовыйВидЦены : Справочник.Вид цены
Наценка : Число 10, 2
..Табличная часть \n ПравилаОкругленияЦены..
НижняяГраницаДиапазонаЦен : Число 15, 2
ТочностьОкругления : Число 15, 2
ПсихологическоеОкругление : Число 15, 2
..Табличная часть \n ПорогиСрабатывания..
ЦеноваяГруппа : Справочник.Ценовая группа
ПорогСрабатывания : Число 15, 2
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
