@startuml Склады
'!include templates.wsd
'..\include templates.wsd
class Справочник.Склады as "Склады" <<Справочники>>
{
..Реквизиты..
ВыборГруппы : Выбор группы складов
ИспользоватьАдресноеХранение : Булево
ИспользоватьАдресноеХранениеСправочно : Булево
ИспользоватьОрдернуюСхемуПриОтгрузке : Булево
ИспользоватьОрдернуюСхемуПриОтраженииИзлишковНедостач : Булево
ИспользоватьОрдернуюСхемуПриПоступлении : Булево
ИспользоватьСерииНоменклатуры : Булево
ИспользоватьСкладскиеПомещения : Булево
Календарь : Справочник.График работы
КонтролироватьОперативныеОстатки : Булево
НастройкаАдресногоХранения : Настройки адресного хранения
Подразделение : Справочник.Подразделение
БизнесРегион : Справочник.Бизнес-регион
РозничныйВидЦены : Справочник.Вид цены
ТекущаяДолжностьОтветственного : Строка
ТекущийОтветственный : Справочник.Физическое лицо
ТипСклада : Типы складов
УровеньОбслуживания : Уровни обслуживания
УчетныйВидЦены : Справочник.Вид цены
НачинатьОтгрузкуПослеФормированияЗаданияНаПеревозку : Булево
ИспользованиеРабочихУчастков : Использование определяется в помещениях
ИсточникИнформацииОЦенахДляПечати : Источники информации о ценах для печати
ИспользоватьСтатусыРасходныхОрдеров : Булево
ИспользоватьСтатусыПриходныхОрдеров : Булево
ИспользоватьСтатусыПересчетовТоваров : Булево
ДатаНачалаОрдернойСхемыПриОтгрузке : Дата
ДатаНачалаОрдернойСхемыПриПоступлении : Дата
ДатаНачалаОрдернойСхемыПриОтраженииИзлишковНедостач : Дата
ДатаНачалаИспользованияСкладскихПомещений : Дата
ДатаНачалаАдресногоХраненияОстатков : Дата
УчитыватьСебестоимостьПоСериям : Булево
КонтролироватьОбеспечение : Булево
СкладОтветственногоХранения : Булево
ВидПоклажедержателя : Виды поклажедержателей
Поклажедержатель : Справочник.Организация\rСправочник.Контрагент
СрокОтветственногоХранения : Число 3, 0
ОтветственноеХранениеДоВостребования : Булево
ОсобыеОтметки : Строка
УсловияХраненияТоваров : Строка
ЦеховаяКладовая : Булево
..Табличная часть \n КонтактнаяИнформация..
Тип : Типы контактной информации
Вид : Справочник.Вид контактной информации
Представление : Строка
ЗначенияПолей : Строка
Страна : Строка
Регион : Строка
Город : Строка
АдресЭП : Строка
ДоменноеИмяСервера : Строка
НомерТелефона : Строка
НомерТелефонаБезКодов : Строка
ВидДляСписка : Справочник.Вид контактной информации
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
