@startuml ПерепискаСКонтролирующимиОрганами
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПерепискаСКонтролирующимиОрганами as "Переписка с контролирующими органами" <<Справочники>>
{
..Реквизиты..
Тип : Типы переписки с контролирующими органами
Статус : Статусы писем
Организация : Справочник.Организация
Отправитель : Справочник.Налоговые органы\rСправочник.Органы ФСГС\rСправочник.Организация\r...
Получатель : Справочник.Налоговые органы\rСправочник.Органы ФСГС\rСправочник.Организация\r...
Содержание : Строка
ДатаСообщения : Дата
ДатаОтправки : Дата
Идентификатор : Строка
ИдентификаторОснования : Строка
Ретроконверсия : Булево
Требование : Справочник.Документы реализации полномочий налоговых органов
}
@enduml
