@startuml ГодовыеГрафикиАмортизацииОС
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГодовыеГрафикиАмортизацииОС as "Годовые графики амортизации ОС" <<Справочники>>
{
..Реквизиты..
Коэффициент1 : Число 6, 3
Коэффициент2 : Число 6, 3
Коэффициент3 : Число 6, 3
Коэффициент4 : Число 6, 3
Коэффициент5 : Число 6, 3
Коэффициент6 : Число 6, 3
Коэффициент7 : Число 6, 3
Коэффициент8 : Число 6, 3
Коэффициент9 : Число 6, 3
Коэффициент10 : Число 6, 3
Коэффициент11 : Число 6, 3
Коэффициент12 : Число 6, 3
Комментарий : Строка
}
@enduml
