@startuml УпаковкиЕдиницыИзмерения
'!include templates.wsd
'..\include templates.wsd
class Справочник.УпаковкиЕдиницыИзмерения as "Упаковки и единицы измерения" <<Справочники>>
{
..Реквизиты..
Безразмерная : Булево
Вес : Число 15, 3
ВесЕдиницаИзмерения : Справочник.Упаковка
Высота : Число 15, 3
ВысотаЕдиницаИзмерения : Справочник.Упаковка
Глубина : Число 15, 3
ГлубинаЕдиницаИзмерения : Справочник.Упаковка
ЕдиницаИзмерения : Справочник.Упаковка
Числитель : Число 15, 3
Знаменатель : Число 15, 3
ЛинейныеРазмерыПредставление : Строка
Объем : Число 18, 6
ОбъемЕдиницаИзмерения : Справочник.Упаковка
СкладскаяГруппа : Справочник.Складская группа упаковок
Типоразмер : Справочник.Типоразмер упаковки
Ширина : Число 15, 3
ШиринаЕдиницаИзмерения : Справочник.Упаковка
КоличествоУпаковок : Число 10, 0
ПоставляетсяВМногооборотнойТаре : Булево
НоменклатураМногооборотнаяТара : Справочник.Номенклатура
ХарактеристикаМногооборотнаяТара : Справочник.Характеристика номенклатуры
МинимальноеКоличествоУпаковокМногооборотнойТары : Число 10, 0
ТипИзмеряемойВеличины : Типы измеряемых величин
НаименованиеПолное : Строка
МеждународноеСокращение : Строка
ТипУпаковки : Типы упаковок номенклатуры
}
@enduml
