@startuml ПричиныПроигрышаСделок
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПричиныПроигрышаСделок as "Причины проигрыша сделок" <<Справочники>>
{
..Реквизиты..
Описание : Строка
}
@enduml
