@startuml УдалитьСертификатыЭП
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьСертификатыЭП as "(не используется) Сертификаты ЭП" <<Справочники>>
{
..Реквизиты..
ДатаОкончания : Дата
ДолжностьПоСертификату : Строка
ЗапомнитьПарольКСертификату : Булево
Назначение : Строка
ОграничитьДоступКСертификату : Булево
ОповещенОСрокеДействия : Булево
Организация : Справочник.Организация
Отозван : Булево
Отпечаток : Строка
ПарольПользователя : Строка
Пользователь : Справочник.Пользователь
ПроверятьСоставИсполнителей : Булево
ПрограммаБанка : Программы банка
ФайлСертификата : Хранилище значения
Фамилия : Строка
Имя : Строка
Отчество : Строка
СсылкаНаНовыйСертификат : Справочник.Сертификат ключа электронной подписи и шифрования
..Табличная часть \n ВидыДокументов..
ВидДокумента : Виды электронных документов
ИспользоватьДляПодписи : Булево
..Табличная часть \n СоставИсполнителей..
Исполнитель : Справочник.Пользователь
}
@enduml
