@startuml УдалитьВидыВычетовНДФЛ
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьВидыВычетовНДФЛ as "(не используется) Виды вычетов НДФЛ" <<Справочники>>
{
..Реквизиты..
КодПрименяемыйВНалоговойОтчетностиС2011Года : Строка
КодПрименяемыйВНалоговойОтчетностиС2010Года : Строка
ВычетКДоходу : Булево
ГруппаВычета : Группы вычетов по НДФЛ
НеПредоставляетсяНерезидентам : Булево
}
@enduml
