@startuml ЭквайринговыеТерминалы
'!include templates.wsd
'..\include templates.wsd
class Справочник.ЭквайринговыеТерминалы as "Эквайринговые терминалы" <<Справочники>>
{
..Реквизиты..
БанковскийСчет : Справочник.Банковский счет организации
Эквайер : Справочник.Контрагент
РазрешитьПлатежиБезУказанияЗаявок : Булево
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
