@startuml СтраныМира
'!include templates.wsd
'..\include templates.wsd
class Справочник.СтраныМира as "Страны мира" <<Справочники>>
{
..Реквизиты..
НаименованиеПолное : Строка
КодАльфа2 : Строка
КодАльфа3 : Строка
УчастникЕАЭС : Булево
}
@enduml
