@startuml ТерриторииОсуществленияТорговойДеятельности
'!include templates.wsd
'..\include templates.wsd
class Справочник.ТерриторииОсуществленияТорговойДеятельности as "Территории осуществления торговой деятельности" <<Справочники>>
{
}
@enduml
