@startuml ПереченьДолжностейДляБронированияГраждан
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПереченьДолжностейДляБронированияГраждан as "Перечень должностей для бронирования" <<Справочники>>
{
..Реквизиты..
ОписаниеПункта : Строка
}
@enduml
