@startuml ПоказателиРасчетаЗарплаты
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПоказателиРасчетаЗарплаты as "Показатели расчета зарплаты" <<Справочники>>
{
..Реквизиты..
КраткоеНаименование : Строка
Идентификатор : Строка
НазначениеПоказателя : Назначения показателей расчета зарплаты
ТипПоказателя : Типы показателей расчета зарплаты
ЗначениеРассчитываетсяАвтоматически : Булево
СпособПримененияЗначений : Способы применения значений показателей расчета зарплаты
СпособВводаЗначений : Способы ввода значений показателей расчета зарплаты
ВидСтажа : Справочник.Вид стажа
Точность : Число 1, 0
ОтображатьВДокументахНачисления : Булево
ИдентификаторСлужебный : Строка
БазовыйПоказатель : Справочник.Показатель
ВидТарифнойСтавки : Виды тарифных ставок
УдалитьИдентификаторОбъекта : Строка
НеИспользуется : Булево
РеквизитДопУпорядочивания : Число 5, 0
ДопускаетсяНулевоеЗначение : Булево
ПериодическийПоказательСотрудника : Булево
ПериодическийПоказательОрганизации : Булево
ПериодическийПоказательПодразделения : Булево
РазовыйПоказательСотрудника : Булево
РазовыйПоказательОрганизации : Булево
РазовыйПоказательПодразделения : Булево
ОперативныйПоказательСотрудника : Булево
ОперативныйПоказательОрганизации : Булево
ОперативныйПоказательПодразделения : Булево
..Табличная часть \n ШкалаОценкиСтажа..
ВерхняяГраницаИнтервалаСтажа : Число 15, 3
ЗначениеПоказателя : Число 15, 3
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
