@startuml КатегорииЦелей
'!include templates.wsd
'..\include templates.wsd
class Справочник.КатегорииЦелей as "Категории целей" <<Справочники>>
{
..Реквизиты..
РеквизитДопУпорядочивания : Число 5, 0
РеквизитДопУпорядочиванияИерархического : Строка
}
@enduml
