@startuml ПоставляемыеРасширения
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПоставляемыеРасширения as "Поставляемые расширения" <<Справочники>>
{
..Реквизиты..
Имя : Строка
Версия : Строка
ХранилищеРасширения : Хранилище значения
Информация : Строка
ИдентификаторВерсии : Уникальный идентификатор
Отключено : Булево
ПричинаОтключения : Причины отключения расширений в модели сервиса
..Табличная часть \n Совместимость..
МинимальнаяВерсия : Строка
МаксимальнаяВерсия : Строка
..Табличная часть \n Разрешения..
ВидРазрешения : Строка
Параметры : Хранилище значения
}
@enduml
