@startuml ОписиИсходящихДокументовВНалоговыеОрганы
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОписиИсходящихДокументовВНалоговыеОрганы as "Ответы на требования о представлении документов" <<Справочники>>
{
..Реквизиты..
Организация : Справочник.Организация
ОписьВходящихДокументов : Справочник.Описи входящих документов, полученных из налоговых органов
Требование : Справочник.Документы реализации полномочий налоговых органов
Статус : Статусы писем
НалоговыйОрган : Справочник.Налоговые органы
ДатаСоздания : Дата
..Табличная часть \n ПредставляемыеДокументы..
ЯвляетсяИнформацией : Булево
ПорядковыйНомер : Число 2, 0
ВидДокумента : Виды представляемых документов
СсылкаНаОбъект : Документ.Приобретение товаров и услуг\rДокумент.Доп. лист книги продаж для передачи в электронном виде\rДокумент.Счет-фактура полученный (аванс)\r...
Загружен : Булево
Загружен_Номер : Строка
Загружен_Дата : Дата
Загружен_Контрагент : Строка
НомерДокументаОснования : Строка
ДатаДокументаОснования : Дата
КНД : Строка
Загружен_Направление : Строка
ИмяФайлаДанных : Строка
ИмяФайлаПодписи : Строка
ВерсияФайлаДанных : Строка
ПодтверждениеКНД : Строка
ПодтверждениеИмяФайлаДанных : Строка
ПодтверждениеИмяФайлаПодписи : Строка
СведенияДокументаОснования : Строка
}
@enduml
