@startuml ПричиныНеудовлетворенияПервичногоСпроса
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПричиныНеудовлетворенияПервичногоСпроса as "Причины неудовлетворения первичного спроса" <<Справочники>>
{
..Реквизиты..
Описание : Строка
}
@enduml
