@startuml ВидыНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыНоменклатуры as "Виды номенклатуры" <<Справочники>>
{
..Реквизиты..
АлкогольнаяПродукция : Булево
ВариантОказанияУслуг : Варианты оказания услуг
ВариантОформленияПродажи : Варианты оформления продажи
ВариантПредставленияНабораВПечатныхФормах : Варианты представления наборов в печатных формах
ВариантРасчетаЦеныНабора : Варианты расчета цен наборов
ВестиУчетПоГТД : Булево
ВестиУчетСертификатовНоменклатуры : Булево
ВидАлкогольнойПродукции : Справочник.Вид алкогольной (спиртосодержащей) продукции
ВладелецСерий : Справочник.Вид номенклатуры
ВладелецТоварныхКатегорий : Справочник.Вид номенклатуры
ВладелецХарактеристик : Справочник.Вид номенклатуры
ГруппаАналитическогоУчета : Справочник.Группа аналитического учета номенклатуры
ГруппаДоступа : Справочник.Группа доступа номенклатуры
ГруппаФинансовогоУчета : Справочник.Группа финансового учета номенклатуры
ЕдиницаДляОтчетов : Справочник.Упаковка
ЕдиницаИзмерения : Справочник.Упаковка
ЗапретРедактированияНаименованияДляПечатиНоменклатуры : Булево
ЗапретРедактированияНаименованияДляПечатиХарактеристики : Булево
ЗапретРедактированияРабочегоНаименованияНоменклатуры : Булево
ЗапретРедактированияРабочегоНаименованияХарактеристики : Булево
ИмпортнаяАлкогольнаяПродукция : Булево
ИспользованиеХарактеристик : Варианты использования характеристик номенклатуры
ИспользоватьИндивидуальноеНаименованиеПриПечати : Булево
ИспользоватьКоличествоСерии : Булево
ИспользоватьНомерСерии : Булево
ИспользоватьСерии : Булево
ИспользоватьСрокГодностиСерии : Булево
ИспользоватьУпаковки : Булево
ИспользоватьХарактеристики : Булево
КонтролироватьДублиНоменклатуры : Булево
КонтролироватьДублиХарактеристик : Булево
КоэффициентЕдиницыДляОтчетов : Число 15, 3
НаборСвойств : Справочник.Набор дополнительных реквизитов и сведений
НаборСвойствСерий : Справочник.Набор дополнительных реквизитов и сведений
НаборСвойствХарактеристик : Справочник.Набор дополнительных реквизитов и сведений
НаборУпаковок : Справочник.Набор упаковок
НаименованиеДляПечати : Строка
НастройкаИспользованияСерий : Настройки использования серий номенклатуры
НоменклатураМногооборотнаяТара : Справочник.Номенклатура
ОбособленнаяЗакупкаПродажа : Булево
НастройкиСерийБерутсяИзДругогоВидаНоменклатуры : Булево
Описание : Строка
ПодакцизныйТовар : Булево
ПоставляетсяВМногооборотнойТаре : Булево
СезоннаяГруппа : Справочник.Сезонные группы номенклатуры
УдалитьПолитикаУчетаСерийДляПодразделений : Справочник.Политика учета серий
ПолитикаУчетаСерий : Справочник.Политика учета серий
СкладскаяГруппа : Справочник.Складская группа номенклатуры
СодержитДрагоценныеМатериалы : Булево
ТипНоменклатуры : Типы номенклатуры
ТочностьУказанияСрокаГодностиСерии : Точности указания срока годности
СтавкаНДС : Ставки НДС
ХарактеристикаМногооборотнаяТара : Справочник.Характеристика номенклатуры
ТоварныеКатегорииОбщиеСДругимВидомНоменклатуры : Булево
ШаблонНаименованияДляПечатиНоменклатуры : Строка
ШаблонНаименованияДляПечатиХарактеристики : Строка
ШаблонРабочегоНаименованияНоменклатуры : Строка
ШаблонРабочегоНаименованияСерии : Строка
ШаблонРабочегоНаименованияХарактеристики : Строка
ШаблонЦенника : Справочник.Шаблон этикетки (ценника)
ШаблонЭтикетки : Справочник.Шаблон этикетки (ценника)
ШаблонЭтикеткиСерии : Справочник.Шаблон этикетки (ценника)
КодОКВЭД : Справочник.ОКВЭД
КодТНВЭД : Справочник.ТН ВЭД
КодОКП : Справочник.ОКП
СхемаОбеспечения : Справочник.Схема обеспечения
СпособОбеспеченияПотребностей : Справочник.Способ обеспечения потребностей
ЦеноваяГруппа : Справочник.Ценовая группа
Крепость : Число 5, 3
ОсобенностьУчета : Особенности учета номенклатуры
ПродукцияМаркируемаяДляГИСМ : Булево
КиЗГИСМ : Булево
ИспользоватьRFIDМеткиСерии : Булево
ИспользоватьНомерКИЗГИСМСерии : Булево
УдалитьВариантНастройкиСерийДляСкладов : (не используется) варианты настроек серий
УдалитьВариантНастройкиСерийДляПодразделений : (не используется) варианты настроек серий
УдалитьСырьевойТовар : Булево
КодРаздел7ДекларацииНДС : Справочник.Коды операций раздела 7 декларации по НДС
..Табличная часть \n РеквизитыДляКонтроляНоменклатуры..
Уникален : Булево
ИмяРеквизита : Строка
ПредставлениеРеквизита : Строка
ЭтоДопРеквизит : Булево
ОбязателенДляЗаполнения : Булево
ОтборПриВыборе : Булево
Свойство : Дополнительный реквизит / сведение
ОтображатьПриСоздании : Булево
ДоступностьУникален : Булево
ДоступностьОбязателенДляЗаполнения : Булево
ДоступностьОтображатьПриСоздании : Булево
..Табличная часть \n РеквизитыДляКонтроляХарактеристик..
Использование : Булево
ИмяРеквизита : Строка
ПредставлениеРеквизита : Строка
ЭтоДопРеквизит : Булево
Уникален : Булево
ОбязателенДляЗаполнения : Булево
Свойство : Дополнительный реквизит / сведение
ОтображатьПриСоздании : Булево
ДоступностьУникален : Булево
ДоступностьОбязателенДляЗаполнения : Булево
ДоступностьОтображатьПриСоздании : Булево
..Табличная часть \n РеквизитыДляКонтроляСерий..
Использование : Булево
ИмяРеквизита : Строка
ПредставлениеРеквизита : Строка
ЭтоДопРеквизит : Булево
Свойство : Дополнительный реквизит / сведение
ОбязателенДляЗаполнения : Булево
ДоступностьОбязателенДляЗаполнения : Булево
..Табличная часть \n РеквизитыБыстрогоОтбораНоменклатуры..
ИмяРеквизита : Строка
ПредставлениеРеквизита : Строка
ЭтоДопРеквизит : Булево
Свойство : Дополнительный реквизит / сведение
Используется : Булево
..Табличная часть \n РеквизитыБыстрогоОтбораХарактеристик..
ИмяРеквизита : Строка
ПредставлениеРеквизита : Строка
ЭтоДопРеквизит : Булево
Свойство : Дополнительный реквизит / сведение
Используется : Булево
..Табличная часть \n ПолитикиУчетаСерий..
Склад : Справочник.Подразделение\rСправочник.Склад (складская территория)
ПолитикаУчетаСерий : Справочник.Политика учета серий
}
@enduml
