@startuml СправкиФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class Справочник.СправкиФизическихЛиц as "Справки физических лиц" <<Справочники>>
{
..Реквизиты..
ВидСправки : Справочник.Вид справки
НомерСправки : Строка
ДатаС : Дата
ДатаПо : Дата
ДатаСправки : Дата
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
