@startuml ГруппыВнешнихПользователей
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГруппыВнешнихПользователей as "Группы внешних пользователей" <<Справочники>>
{
..Реквизиты..
Комментарий : Строка
УдалитьТипОбъектовАвторизации : Справочник.Партнер\rСправочник.Контактное лицо
ВсеОбъектыАвторизации : Булево
..Табличная часть \n Состав..
ВнешнийПользователь : Справочник.Внешний пользователь
..Табличная часть \n Роли..
Роль : Справочник.Идентификатор объекта метаданных
УдалитьРоль : Строка
..Табличная часть \n Назначение..
ТипПользователей : Справочник.Партнер\rСправочник.Контактное лицо
}
@enduml
