@startuml ТранспортныеСредства
'!include templates.wsd
'..\include templates.wsd
class Справочник.ТранспортныеСредства as "Транспортные средства" <<Справочники>>
{
..Реквизиты..
ВидПеревозки : Строка
ГосударственныйНомерПрицепа : Строка
ЛицензионнаяКарточкаВид : Строка
ЛицензионнаяКарточкаНомер : Строка
ЛицензионнаяКарточкаРегистрационныйНомер : Строка
ЛицензионнаяКарточкаСерия : Строка
Марка : Строка
Прицеп : Строка
Тип : Справочник.Типы транспортных средств
ГрузоподъемностьВТоннах : Число 9, 3
ВместимостьВКубическихМетрах : Число 9, 3
ВместимостьПредставление : Строка
}
@enduml
