@startuml КлассификаторАлкогольнойПродукцииЕГАИС
'!include templates.wsd
'..\include templates.wsd
class Справочник.КлассификаторАлкогольнойПродукцииЕГАИС as "Классификатор алкогольной продукции ЕГАИС" <<Справочники>>
{
..Реквизиты..
Объем : Число 18, 6
Крепость : Число 5, 3
ВидПродукции : Справочник.Вид алкогольной (спиртосодержащей) продукции
Производитель : Справочник.Организация ЕГАИС
Импортер : Справочник.Организация ЕГАИС
НаименованиеПолное : Строка
УдалитьНоменклатура : Справочник.Номенклатура
УдалитьХарактеристика : Справочник.Характеристика номенклатуры
УдалитьСопоставлено : Булево
ТипПродукции : Типы продукции ЕГАИС
..Табличная часть \n УдалитьУпаковки..
ИдентификаторУпаковки : Строка
Упаковка : Справочник.Упаковка
}
@enduml
