@startuml УдалитьПерепискаСКонтролирующимиОрганами
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьПерепискаСКонтролирующимиОрганами as "(не используется) Переписка с контролирующими органами" <<Справочники>>
{
..Реквизиты..
Тип : (не используется) Типы переписки с контролирующими органами
Статус : Статусы писем
Организация : Справочник.Организация
Отправитель : Справочник.(не используется) Налоговые органы\rСправочник.Органы ФСГС\rСправочник.(не используется) Органы ПФР\r...
Получатель : Справочник.(не используется) Налоговые органы\rСправочник.Органы ФСГС\rСправочник.(не используется) Органы ПФР\r...
Содержание : Строка
ДатаСообщения : Дата
ДатаОтправки : Дата
Идентификатор : Строка
ИдентификаторОснования : Строка
Ретроконверсия : Булево
}
@enduml
