@startuml ВидыПланов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыПланов as "Виды планов" <<Справочники>>
{
..Реквизиты..
ТипПлана : Типы планов
ЗаполнятьПартнера : Булево
ЗаполнятьСоглашение : Булево
ЗаполнятьСклад : Булево
ЗаполнятьПодразделение : Булево
ЗаполнятьПартнераВТЧ : Булево
ЗаполнятьСоглашениеВТЧ : Булево
ЗаполнятьСкладВТЧ : Булево
ЗаполнятьНазначениеВТЧ : Булево
ЗаполнятьМенеджера : Булево
СтруктураНастроек : Хранилище значения
ЗапретитьРедактированиеПравила : Булево
ЗаполнятьПланОплат : Булево
ЗаполнятьПоФормуле : Булево
ОтражаетсяВБюджетировании : Булево
СтатьяБюджетов : Справочник.Статьи бюджетов
Описание : Строка
ЗаполнятьФорматМагазина : Булево
ОтражаетсяВБюджетированииОплаты : Булево
СтатьяБюджетовОплат : Справочник.Статьи бюджетов
ОтражаетсяВБюджетированииОплатыКредит : Булево
СтатьяБюджетовОплатКредит : Справочник.Статьи бюджетов
КоличествоПериодов : Число 2, 0
ЗаполнятьСпецификациюПоПериодам : Булево
Замещающий : Булево
ПланироватьПолуфабрикатыАвтоматически : Булево
..Табличная часть \n ПравилоЗаполнения..
Использование : Булево
Исключать : Булево
ВариантПреобразования : Варианты преобразования
Источник : Справочник.Источник данных планирования
Период : Хранилище значения
Дата : Хранилище значения
ТипЭлемента : Число 1, 0
НомерСтрокиРодитель : Число 5, 0
ПользовательскиеНастройки : Хранилище значения
ИзменитьРезультатНа : Число 5, 2
Присоединять : Булево
}
@enduml
