@startuml ОбъектыЭксплуатации
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОбъектыЭксплуатации as "Объекты эксплуатации" <<Справочники>>
{
..Реквизиты..
ГруппаОСМеждународныйУчет : Справочник.Группа основных средств
ИнвентарныйНомер : Строка
ДатаВыпуска : Дата
КодПоОКОФ : Справочник.Элемент классификатора ОКОФ
ШифрПоЕНАОФ : Справочник.Элемент классификатора ЕНАОФ
ДатаСведений : Дата
ЗаводскойНомер : Строка
Изготовитель : Строка
Класс : Справочник.Класс объектов эксплуатации
Комментарий : Строка
Модель : Строка
НаименованиеПолное : Строка
НомерПаспорта : Строка
ОбъектБытовогоНазначения : Булево
Подкласс : Справочник.Подкласс объектов эксплуатации
Расположение : Строка
РемонтирующееПодразделение : Справочник.Подразделение
СерийныйНомер : Строка
Статус : Статусы объектов эксплуатации
СтатьяРасходов : Статья расходов
ЭксплуатирующееПодразделение : Справочник.Подразделение
СпособОтраженияЗарплаты : Справочник.Способ отражения зарплаты
НаправлениеДеятельности : Справочник.Направление деятельности
ГруппаОС : Группы ОС
АмортизационнаяГруппа : Амортизационные группы
ЗарегистрированоВРеестреСистемыПлатон : Булево
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n ПараметрыУчетаНаработок..
ПоказательНаработки : Справочник.Показатель наработки
НазначенныйРесурс : Число 15, 3
Источник : Справочник.Объект эксплуатации
СмещениеЗначения : Число 15, 3
..Табличная часть \n РабочиеЦентры..
РабочийЦентр : Справочник.Рабочий центр
..Табличная часть \n ДрагоценныеМатериалы..
ДрагоценныйМатериал : Справочник.Драгоценный материал
Количество : Число 15, 3
Комментарий : Строка
Расположение : Расположение драгоценных камней
}
@enduml
