@startuml УдалитьПараметрыИсчисляемогоСтраховогоСтажа
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьПараметрыИсчисляемогоСтраховогоСтажа as "(не используется) Доп. сведения для исчисления стажа" <<Справочники>>
{
..Реквизиты..
ИспользуетсяС2014Года : Булево
}
@enduml
