@startuml ВидыПодтверждающихДокументов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыПодтверждающихДокументов as "Виды подтверждающих документов" <<Справочники>>
{
..Реквизиты..
КраткоеНаименование : Строка
ПодтверждаетИсполнениеКонтракта : Булево
}
@enduml
