@startuml ВидыОбщественноПолезнойДеятельностиСЗВК
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыОбщественноПолезнойДеятельностиСЗВК as "Виды деятельности (СЗВ-К)" <<Справочники>>
{
}
@enduml
