@startuml ТипыДокументовПодтверждающихЛьготуНДС
'!include templates.wsd
'..\include templates.wsd
class Справочник.ТипыДокументовПодтверждающихЛьготуНДС as "Типы документов подтверждающих льготу по НДС" <<Справочники>>
{
..Реквизиты..
ПолноеНаименование : Строка
}
@enduml
