@startuml ПоляФормСтатистики
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПоляФормСтатистики as "Поля форм статистики" <<Справочники>>
{
..Реквизиты..
НомерСтрокиОтчета : Строка
ИмяПоля : Строка
Период : Относительные периоды отчетности
СНачалаГода : Булево
СтатистическийПоказатель : Справочник.Статистические показатели
ДополнительныйАлгоритм : Дополнительные алгоритмы заполнения форм статистики
}
@enduml
