@startuml КлассификаторБанков
'!include templates.wsd
'..\include templates.wsd
class Справочник.КлассификаторБанков as "Классификатор банков" <<Справочники>>
{
..Реквизиты..
КоррСчет : Строка
Город : Строка
Адрес : Строка
Телефоны : Строка
ДеятельностьПрекращена : Булево
СВИФТБИК : Строка
ИНН : Строка
}
@enduml
