@startuml ГруппыПользователей
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГруппыПользователей as "Группы пользователей" <<Справочники>>
{
..Реквизиты..
Комментарий : Строка
..Табличная часть \n Состав..
Пользователь : Справочник.Пользователь
}
@enduml
