@startuml КлассификаторПродукцииПоВидамДеятельности
'!include templates.wsd
'..\include templates.wsd
class Справочник.КлассификаторПродукцииПоВидамДеятельности as "Классификатор продукции по видам деятельности (ОКПД)" <<Справочники>>
{
..Реквизиты..
НаименованиеПолное : Строка
ЕдиницаСтатистическогоУчета : Справочник.Упаковка
ВидСвободныхСтрокФормСтатистики : Виды свободных строк форм статистики
}
@enduml
