@startuml УдалитьОрганыПФР
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьОрганыПФР as "(не используется) Органы ПФР" <<Справочники>>
{
..Табличная часть \n Сертификаты..
Сертификат : Строка
}
@enduml
