@startuml Бригады
'!include templates.wsd
'..\include templates.wsd
class Справочник.Бригады as "Бригады" <<Справочники>>
{
..Реквизиты..
ПрименятьРаспределениеПоКТУ : Булево
Подразделение : Справочник.Подразделение
Организация : Справочник.Организация
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
