@startuml ВидыДокументовФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыДокументовФизическихЛиц as "Виды документов физических лиц" <<Справочники>>
{
..Реквизиты..
КодМВД : Строка
КодПФР : Строка
РеквизитДопУпорядочивания : Число 5, 0
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
