@startuml ШаблоныСообщений
'!include templates.wsd
'..\include templates.wsd
class Справочник.ШаблоныСообщений as "Шаблоны сообщений" <<Справочники>>
{
..Реквизиты..
Автор : Справочник.Пользователь
ВладелецШаблона : Справочник.Идентификатор объекта метаданных
ВнешняяОбработка : Справочник.Дополнительный отчет или обработка
Назначение : Строка
Отправитель : Строка
ОтправлятьВТранслите : Булево
ПолноеИмяТипаПараметраВводаНаОсновании : Строка
ПредназначенДляSMS : Булево
ПредназначенДляВводаНаОсновании : Булево
ПредназначенДляЭлектронныхПисем : Булево
ТекстШаблонаSMS : Строка
ТекстШаблонаПисьма : Строка
ТекстШаблонаПисьмаHTML : Строка
ТемаПисьма : Строка
ТипТекстаПисьма : Способы редактирования электронных писем
ТолькоДляАвтора : Булево
ТранслитерироватьИменаФайлов : Булево
УпаковатьВАрхив : Булево
ФорматВложений : Хранилище значения
ШаблонПоВнешнейОбработке : Булево
..Табличная часть \n ПечатныеФормыИВложения..
Идентификатор : Строка
Имя : Строка
..Табличная часть \n Параметры..
ИмяПараметра : Строка
ТипПараметра : Хранилище значения
ПредставлениеПараметра : Строка
..Табличная часть \n УдалитьПараметры..
ИмяПараметра : Строка
ТипПараметра : Хранилище значения
ЭтоПредопределенныйПараметр : Булево
ПредставлениеПараметра : Строка
..Табличная часть \n УдалитьПечатныеФормы..
ПечатнаяФорма : Строка
}
@enduml
