@startuml СобытияОС
'!include templates.wsd
'..\include templates.wsd
class Справочник.СобытияОС as "События ОС" <<Справочники>>
{
..Реквизиты..
Комментарий : Строка
ВидСобытияОС : Виды событий с основными средствами
}
@enduml
