@startuml ПоказателиНаработки
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПоказателиНаработки as "Показатели наработки" <<Справочники>>
{
..Реквизиты..
ЕдиницаИзмерения : Справочник.Упаковка
}
@enduml
