@startuml НаправленияДеятельности
'!include templates.wsd
'..\include templates.wsd
class Справочник.НаправленияДеятельности as "Направления деятельности" <<Справочники>>
{
..Реквизиты..
Статус : Статусы направления деятельности
УчетДоходов : Булево
УчетЗатрат : Булево
УчетДенежныхСредствРаздельно : Булево
УчетДенежныхСредствПоКорреспонденции : Булево
УчетВнеоборотныхАктивов : Булево
Назначение : Справочник.Назначение
УдалитьВариантОбособления : (не используется) Варианты обособления по направлению деятельности
Комментарий : Строка
ТипНаправленияДеятельности : Типы направлений деятельности
ДатаЗавершения : Дата
ОбъемФинансированияКонтракта : Число 15, 2
СуммаНДС : Число 15, 2
ЗатратыНаМатериалы : Число 15, 2
ЗатратыНаОплатуТруда : Число 15, 2
ПрочиеПроизводственныеЗатраты : Число 15, 2
ОбщепроизводственныеЗатраты : Число 15, 2
ОбщехозяйственныеЗатраты : Число 15, 2
КоммерческиеРасходы : Число 15, 2
ПрибыльКонтракта : Число 15, 2
УправленческиеРасходы : Число 15, 2
ДопускаетсяОбособлениеСверхПотребности : Булево
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
