@startuml КлючевыеОперации
'!include templates.wsd
'..\include templates.wsd
class Справочник.КлючевыеОперации as "Ключевые операции" <<Справочники>>
{
..Реквизиты..
Имя : Строка
МинимальноДопустимыйУровень : Уровни производительности
Приоритет : Число 15, 0
ЦелевоеВремя : Число 15, 2
ИмяХеш : Строка
ВыполненаСОшибкой : Булево
Длительная : Булево
}
@enduml
