@startuml ГрафикиРаботыСотрудников
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГрафикиРаботыСотрудников as "Графики работы сотрудников" <<Справочники>>
{
..Реквизиты..
ПроизводственныйКалендарь : Справочник.Производственный календарь
СуммированныйУчетРабочегоВремени : Булево
ДатаОтсчета : Дата
ДлительностьРабочейНедели : Число 7, 2
НеполноеРабочееВремя : Булево
СокращеннаяРабочаяНеделя : Булево
НеполныйРабочийДень : Булево
ГрафикПолногоРабочегоВремени : Справочник.График работы
УчитыватьПраздники : Булево
СпособЗаполнения : Способы заполнения графика работы
РабочихДнейВНеделе : Число 1, 0
СпособОпределенияНормыСуммированногоУчета : Способы определения нормы суммированного учета
ГрафикНормыПриСуммированномУчете : Справочник.График работы
..Табличная часть \n ШаблонЗаполнения..
ДеньВключенВГрафик : Булево
..Табличная часть \n ВидыВремени..
ВидВремени : Справочник.Вид рабочего времени
..Табличная часть \n ДанныеОРабочихЧасах..
НомерДняЦикла : Число 2, 0
ВидВремени : Справочник.Вид рабочего времени
Часов : Число 4, 2
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
