@startuml УдалитьОсобыеУсловияТрудаДляСЗВКПФР
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьОсобыеУсловияТрудаДляСЗВКПФР as "(не используется) Условия труда (форма СЗВ-К)" <<Справочники>>
{
}
@enduml
