@startuml ТипоразмерыУпаковок
'!include templates.wsd
'..\include templates.wsd
class Справочник.ТипоразмерыУпаковок as "Типоразмеры упаковок" <<Справочники>>
{
..Реквизиты..
Высота : Число 15, 3
ВысотаЕдиницаИзмерения : Справочник.Упаковка
Ширина : Число 15, 3
ШиринаЕдиницаИзмерения : Справочник.Упаковка
Глубина : Число 15, 3
ГлубинаЕдиницаИзмерения : Справочник.Упаковка
Объем : Число 18, 6
ОбъемЕдиницаИзмерения : Справочник.Упаковка
Безразмерная : Булево
}
@enduml
