@startuml КассыККМ
'!include templates.wsd
'..\include templates.wsd
class Справочник.КассыККМ as "Кассы ККМ" <<Справочники>>
{
..Реквизиты..
Склад : Справочник.Склад (складская территория)
ТипКассы : Типы касс ККМ
ВалютаДенежныхСредств : Справочник.Валюта
РегистрационныйНомер : Строка
СерийныйНомер : Строка
Подразделение : Справочник.Подразделение
}
@enduml
