@startuml ДополнительныеВнешниеКомпоненты
'!include templates.wsd
'..\include templates.wsd
class Справочник.ДополнительныеВнешниеКомпоненты as "Дополнительные внешние компоненты" <<Справочники>>
{
..Реквизиты..
Идентификатор : Строка
Версия : Строка
ДанныеВК : Хранилище значения
Адрес : Строка
}
@enduml
