@startuml ВидыСтажа
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыСтажа as "Виды стажа" <<Справочники>>
{
..Реквизиты..
КатегорияСтажа : Категории стажа
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
