@startuml МобильныеКомпьютеры
'!include templates.wsd
'..\include templates.wsd
class Справочник.МобильныеКомпьютеры as "Мобильные компьютеры" <<Справочники>>
{
..Реквизиты..
СерийныйНомер : Строка
РегистрационныйНомерКомплекта : Строка
РегистрационныйКод : Строка
КодАктивации : Строка
}
@enduml
