@startuml УдалитьВидыОтправляемыхДокументов
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьВидыОтправляемыхДокументов as "(не используется) Виды отправляемых документов" <<Справочники>>
{
..Реквизиты..
Описание : Строка
Источник : Строка
ТипПолучателя : (не используется) Типы контролирующих органов
ТипДокумента : (не используется) Типы отправляемых документов
}
@enduml
