@startuml ВидыРемонтов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыРемонтов as "Виды ремонтов" <<Справочники>>
{
..Реквизиты..
ОбщийВидРемонта : Справочник.Общий вид ремонта
Длительность : Число 10, 1
ЧастотаПланирования : Частота планирования ремонтов
Упреждение : Число 10, 1
Комментарий : Строка
..Табличная часть \n МатериалыИРаботы..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
..Табличная часть \n Трудозатраты..
ВидРабот : Справочник.Вид работ сотрудников
Количество : Число 15, 3
}
@enduml
