@startuml ВидыСделокСКлиентами
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыСделокСКлиентами as "Виды сделок с клиентами" <<Справочники>>
{
..Реквизиты..
Описание : Строка
Ответственный : Справочник.Пользователь
ТипСделки : Типы сделок с клиентами
ИспользованиеРазрешено : Булево
ИспользоватьСпрос : Булево
ОбособленныйУчетТоваровПоСделке : Булево
..Табличная часть \n ЭтапыСделкиПоПродаже..
ЭтапПроцессаПродажи : Справочник.Этап процесса
}
@enduml
