@startuml ОбщиеДанныеИнформационногоЦентра
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОбщиеДанныеИнформационногоЦентра as "Общие данные информационного центра" <<Справочники>>
{
..Реквизиты..
Вложения : Хранилище значения
ВнешняяСсылка : Строка
Дата : Дата
ДатаНачалаАктуальности : Дата
ДатаОкончанияАктуальности : Дата
Идентификатор : Уникальный идентификатор
Критичность : Число 10, 0
ТекстHTML : Строка
ТипИнформации : Справочник.Типы информации
}
@enduml
