@startuml СтрокиОтчетностиРасходовИЧисленностиРаботниковГосударственныхОрганов
'!include templates.wsd
'..\include templates.wsd
class Справочник.СтрокиОтчетностиРасходовИЧисленностиРаботниковГосударственныхОрганов as "Строки отчетности расходов и численности работников государственных органов" <<Справочники>>
{
..Реквизиты..
КодКатегорииПерсонала : Строка
ФормаОтчета : Виды форм отчетов о расходах и численности работников государственных органов
Пояснение : Строка
}
@enduml
