@startuml ЗадачиПроектов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ЗадачиПроектов as "Задачи проектов" <<Справочники>>
{
..Реквизиты..
Стадия : Стадии задач
ОписаниеЗадачи : Строка
Куратор : Справочник.Пользователь
Исполнитель : Справочник.Пользователь
ПлановаяДатаНачала : Дата
ДатаНачала : Дата
ПлановаяПродолжительность : Число 10, 0
ДатаОкончания : Дата
ПроцентВыполнения : Число 3, 0
ОписаниеРезультата : Строка
Закрыта : Булево
}
@enduml
