@startuml МоделиБюджетирования
'!include templates.wsd
'..\include templates.wsd
class Справочник.МоделиБюджетирования as "Модели бюджетирования" <<Справочники>>
{
..Реквизиты..
Статус : Статусы моделей бюджетирования
НачалоДействия : Дата
КонецДействия : Дата
ИспользоватьУтверждениеБюджетов : Булево
БюджетыПоОрганизациям : Булево
БюджетыПоПодразделениям : Булево
Периодичность : Периодичность
АвтоматическиФормироватьЗадачи : Булево
РегламентноеЗадание : Уникальный идентификатор
}
@enduml
