@startuml ВнешниеПользователи
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВнешниеПользователи as "Внешние пользователи" <<Справочники>>
{
..Реквизиты..
Недействителен : Булево
ОбъектАвторизации : Справочник.Партнер\rСправочник.Контактное лицо
УстановитьРолиНепосредственно : Булево
Комментарий : Строка
Подготовлен : Булево
ИдентификаторПользователяИБ : Уникальный идентификатор
ИдентификаторПользователяСервиса : Уникальный идентификатор
СвойстваПользователяИБ : Хранилище значения
УдалитьПароль : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
