@startuml ВидыОперацийРасчетаЗарплаты
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыОперацийРасчетаЗарплаты as "Виды операций расчета зарплаты" <<Справочники>>
{
..Реквизиты..
Начисление : Булево
Договоры : Булево
Пособия : Булево
Льготы : Булево
Удержания : Булево
НДФЛ : Булево
Займы : Булево
Взносы : Булево
ВАрхиве : Булево
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
