@startuml ПодарочныеСертификаты
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПодарочныеСертификаты as "Подарочные сертификаты" <<Справочники>>
{
..Реквизиты..
Штрихкод : Строка
МагнитныйКод : Строка
}
@enduml
