@startuml УсловияОбслуживанияПартнеровТорговымиПредставителями
'!include templates.wsd
'..\include templates.wsd
class Справочник.УсловияОбслуживанияПартнеровТорговымиПредставителями as "Условия обслуживания клиентов торговыми представителями" <<Справочники>>
{
..Реквизиты..
Соглашение : Справочник.Соглашение об условиях продаж
Куратор : Справочник.Пользователь
ТорговыйПредставитель : Справочник.Пользователь
Комментарий : Строка
..Табличная часть \n ГрафикПосещения..
ДеньНедели : Дни недели
ВремяНачала : Дата
ВремяОкончания : Дата
}
@enduml
