@startuml ШаблоныЭтикетокИЦенников
'!include templates.wsd
'..\include templates.wsd
class Справочник.ШаблоныЭтикетокИЦенников as "Шаблоны этикеток и ценников" <<Справочники>>
{
..Реквизиты..
Шаблон : Хранилище значения
Назначение : Назначения шаблонов этикеток и ценников
Ширина : Число 3, 0
Высота : Число 3, 0
РазмерЯчейки : Число 15, 0
ДляЧего : Справочник.Номенклатура\rСправочник.Складская ячейка\rСправочник.Серия номенклатуры\r...
}
@enduml
