@startuml ПроверкиСостоянияСистемы
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПроверкиСостоянияСистемы as "Проверки состояния учета" <<Справочники>>
{
..Реквизиты..
РегламентноеЗаданиеGUID : Уникальный идентификатор
РегламентноеЗаданиеПредставление : Строка
Используется : Булево
Важность : Варианты важности проблемы состояния системы
ОписаниеДополнительныхПараметров : Хранилище значения
ПоОтдельномуРасписанию : Булево
Расписание : Хранилище значения
ДополнительныеПараметрыАвтопроверки : Хранилище значения
Комментарий : Строка
КонтекстВыполнения : Документ.Плановая калькуляция\rОперации закрытия месяца
Идентификатор : Строка
УточнениеКонтекстаВыполнения : Момент запуска проверки операции закрытия месяца
ВыполняетсяТолькоВКонтексте : Булево
ПредшествующаяПроверка : Справочник.Проверка
Обработчик : Строка
СпособВыполнения : Способы выполнения проверок состояния системы
ДетализацияДоОрганизации : Булево
ДетализацияДоПериода : Булево
ВозможноИзменениеВажности : Булево
}
@enduml
