@startuml ОтправкиФТС
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОтправкиФТС as "Отправки в ФТС" <<Справочники>>
{
..Реквизиты..
ОтчетСсылка : Справочник.Загруженный отчет\rДокумент.Регламентированный отчет
ИдентификаторОтправкиНаСервере : Строка
ВыгрузкаДляПодписи : Хранилище значения
Подпись : Хранилище значения
ИмяФайлаВыгрузки : Строка
СтатусОтправки : Статусы отправки
Протокол : Хранилище значения
ДатаОтправки : Дата
ДатаПолученияРезультата : Дата
Организация : Справочник.Организация
НаКонтроле : Булево
Квитанция : Хранилище значения
ДатаНачалаПериода : Дата
ДатаОкончанияПериода : Дата
Период : Строка
Версия : Число 3, 0
ВидОтчета : Справочник.Виды отправляемых документов
ДатаЗакрытия : Дата
ПредставлениеПериода : Строка
ПредставлениеВидаДокумента : Строка
}
@enduml
