@startuml СегментыНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Справочник.СегментыНоменклатуры as "Сегменты номенклатуры" <<Справочники>>
{
..Реквизиты..
ДатаОчистки : Дата
ДатаСоздания : Дата
Описание : Строка
Ответственный : Справочник.Пользователь
СпособФормирования : Способы формирования сегментов
СхемаКомпоновкиДанных : Хранилище значения
РегламентноеЗадание : Уникальный идентификатор
ХранилищеНастроекКомпоновкиДанных : Хранилище значения
ИмяШаблонаСКД : Строка
}
@enduml
