@startuml ГруппыСотрудников
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГруппыСотрудников as "Группы сотрудников" <<Справочники>>
{
..Реквизиты..
ФормироватьАвтоматически : Булево
ХранилищеНастроек : Хранилище значения
}
@enduml
