@startuml ПретензииКлиентов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПретензииКлиентов as "Претензии клиентов" <<Справочники>>
{
..Реквизиты..
Ответственный : Справочник.Пользователь
ДатаРегистрации : Дата
ДатаОкончания : Дата
Завершен : Булево
Комментарий : Строка
РезультатыОтработки : Строка
ОписаниеПретензии : Строка
ПричинаВозникновения : Справочник.Причина возникновения претензий
Партнер : Справочник.Партнер
Статус : Статусы претензий клиентов
ВиновноеПодразделение : Справочник.Подразделение
ВиновныйСотрудник : Справочник.Пользователь
Основание : Документ.Акт о расхождениях после отгрузки\rДокумент.Возврат товаров от клиента\rДокумент.Отчет комиссионера (агента) о продажах\r...
..Табличная часть \n ПартнерыИКонтактныеЛица..
Партнер : Справочник.Партнер
РольПартнера : Справочник.Роль партнера в сделке или проекте
КонтактноеЛицо : Справочник.Контактное лицо
РольКонтактногоЛица : Справочник.Роль контактного лица партнера в сделках и проектах
Комментарий : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
