@startuml СертификатыНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Справочник.СертификатыНоменклатуры as "Сертификаты номенклатуры" <<Справочники>>
{
..Реквизиты..
ДатаНачалаСрокаДействия : Дата
ДатаОкончанияСрокаДействия : Дата
Бессрочный : Булево
ОрганВыдавшийДокумент : Строка
ТипСертификата : Строка
Номер : Строка
Представление : Строка
Статус : Статусы сертификатов номенклатуры
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
