@startuml УдалитьВидыНалоговыхОрганов
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьВидыНалоговыхОрганов as "(не используется) Виды налоговых органов" <<Справочники>>
{
}
@enduml
