@startuml СоглашенияСПоставщиками
'!include templates.wsd
'..\include templates.wsd
class Справочник.СоглашенияСПоставщиками as "Соглашения об условиях закупок" <<Справочники>>
{
..Реквизиты..
Номер : Строка
Дата : Дата
Контрагент : Справочник.Контрагент
Партнер : Справочник.Партнер
Организация : Справочник.Организация
Валюта : Справочник.Валюта
ЦенаВключаетНДС : Булево
СрокПоставки : Число 10, 0
Склад : Справочник.Склад (складская территория)
ДатаНачалаДействия : Дата
ДатаОкончанияДействия : Дата
Комментарий : Строка
Статус : Статусы соглашений с поставщиками
Согласован : Булево
Менеджер : Справочник.Пользователь
НалогообложениеНДС : Типы налогообложения НДС
СпособРасчетаВознаграждения : Способы расчета комиссионного вознаграждения
ПроцентВознаграждения : Число 5, 2
УдержатьВознаграждение : Булево
ХозяйственнаяОперация : Хозяйственные операции
ПроцентРучнойСкидки : Число 5, 2
ПроцентРучнойНаценки : Число 5, 2
КонтролироватьЦеныЗакупки : Булево
ФормаОплаты : Формы оплаты
ВариантПриемкиТоваров : Варианты приемки товаров
ПорядокОплаты : Порядок оплаты
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
РегистрироватьЦеныПоставщика : Булево
ИспользуютсяДоговорыКонтрагентов : Булево
ПорядокРасчетов : Детализация расчетов
ВозвращатьМногооборотнуюТару : Булево
СрокВозвратаМногооборотнойТары : Число 3, 0
РассчитыватьДатуВозвратаТарыПоКалендарю : Булево
Календарь : Справочник.Производственный календарь
ТребуетсяЗалогЗаТару : Булево
КалендарьВозвратаТары : Справочник.Производственный календарь
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
ИспользоватьУказанныеАгентскиеУслуги : Булево
ВидЦеныПоставщика : Справочник.Вид цены поставщика
КодНаименованияСделки : Строка
СпособОпределенияЦеныСделки : Справочник.Способ определения цены контролируемой сделки
КодУсловийПоставки : Строка
НаправлениеДеятельности : Справочник.Направление деятельности
ВалютаВзаиморасчетов : Справочник.Валюта
СпособДоставки : Способы доставки
ПеревозчикПартнер : Справочник.Партнер
ЗонаДоставки : Справочник.Зоны доставки
ВремяДоставкиС : Дата
ВремяДоставкиПо : Дата
АдресДоставки : Строка
АдресДоставкиЗначенияПолей : Строка
ДополнительнаяИнформацияПоДоставке : Строка
АдресДоставкиПеревозчика : Строка
АдресДоставкиПеревозчикаЗначенияПолей : Строка
АдресДоставкиДляПоставщика : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n ЭтапыГрафикаОплаты..
ВариантОплаты : Варианты оплаты поставщику
Сдвиг : Число 10, 0
ПроцентПлатежа : Число 5, 2
ПроцентЗалогаЗаТару : Число 5, 2
..Табличная часть \n АгентскиеУслуги..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
}
@enduml
