@startuml РесурсныеСпецификации
'!include templates.wsd
'..\include templates.wsd
class Справочник.РесурсныеСпецификации as "Ресурсные спецификации" <<Справочники>>
{
..Реквизиты..
Статус : Статусы спецификаций
НачалоДействия : Дата
КонецДействия : Дата
МинимальнаяПартияВыпуска : Число 15, 3
МногоэтапныйПроизводственныйПроцесс : Булево
ВыпускПроизвольнымиПорциями : Булево
Ответственный : Справочник.Пользователь
Описание : Строка
ОптимальнаяПартияВыпуска : Число 15, 3
ОграниченСрокПролеживанияВыходныхИзделий : Булево
МаксимальныйСрокПролеживанияВыходныхИзделий : Число 3, 0
ОптимальноеКоличествоПередачиМеждуЭтапами : Число 15, 0
ПечатьМаршрутнойКарты : Варианты печати маршрутной карты на продукцию
УдалитьСтатьяКалькуляцииПФР : Справочник.Статьи калькуляции
УдалитьСтатьяКалькуляцииФСС : Справочник.Статьи калькуляции
УдалитьСтатьяКалькуляцииФОМС : Справочник.Статьи калькуляции
..Табличная часть \n ВыходныеИзделия..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Этап : Справочник.Этап ресурсной спецификации
ЭтапРедактирование : Справочник.Этап ресурсной спецификации
ДоляСтоимости : Число 10, 0
ТребуетсяУказыватьСерии : Булево
..Табличная часть \n ВозвратныеОтходы..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Этап : Справочник.Этап ресурсной спецификации
ЭтапРедактирование : Справочник.Этап ресурсной спецификации
СтатьяКалькуляции : Справочник.Статьи калькуляции
ОписаниеИзделия : Строка
УдалитьТребуетсяУказыватьСерии : Булево
..Табличная часть \n МатериалыИУслуги..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
КоличествоУпаковок : Число 15, 3
Количество : Число 15, 3
Этап : Справочник.Этап ресурсной спецификации
ЭтапРедактирование : Справочник.Этап ресурсной спецификации
СтатьяКалькуляции : Справочник.Статьи калькуляции
СпособАвтовыбораНоменклатуры : Способы автовыбора номенклатуры
СпособАвтовыбораХарактеристики : Способы автовыбора характеристики
СвойствоСодержащееНоменклатуру : Дополнительный реквизит / сведение
ОтборСвойство : Дополнительный реквизит / сведение
ОтборЗначениеСвойства : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
АлгоритмРасчетаКоличества : Строка
ПрименениеМатериала : Строка
КлючСвязи : Уникальный идентификатор
ПроизводитсяВПроцессе : Булево
СпособПолученияМатериала : Способы получения материалов спецификации
ТребуетсяУказыватьСерии : Булево
ИсточникПолученияПолуфабриката : Справочник.Ресурсная спецификация\rСправочник.Этап ресурсной спецификации
..Табличная часть \n Трудозатраты..
ВидРабот : Справочник.Вид работ сотрудников
Количество : Число 15, 3
СтатьяКалькуляции : Справочник.Статьи калькуляции
Этап : Справочник.Этап ресурсной спецификации
ЭтапРедактирование : Справочник.Этап ресурсной спецификации
НазначениеРабот : Строка
ОтборСвойство : Дополнительный реквизит / сведение
ОтборЗначениеСвойства : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
АлгоритмРасчетаКоличества : Строка
..Табличная часть \n СоответствиеСвойств..
СвойствоМатериала : Дополнительный реквизит / сведение
СвойствоПродукции : Дополнительный реквизит / сведение
ЗначениеСвойства : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ПредопределенноеЗначение : Булево
КлючСвязиМатериал : Уникальный идентификатор
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
