@startuml СпособыВыплатыЗарплаты
'!include templates.wsd
'..\include templates.wsd
class Справочник.СпособыВыплатыЗарплаты as "Способы выплаты зарплаты" <<Справочники>>
{
..Реквизиты..
Поставляемый : Булево
ХарактерВыплаты : Характер выплаты зарплаты
ВидДокументаОснования : Виды документов межрасчетных начислений
ГруппаВидовДоговоров : Группы видов договоров с сотрудникам для выплаты зарплаты
Округление : Справочник.Способ округления
ПроцентВыплаты : Число 3, 0
УдалитьИдентификаторОбъекта : Строка
УдалитьСпособПолученияЗарплатыКВыплате : (не используется) Способы получения зарплаты к выплате
}
@enduml
