@startuml УдалитьКомплектыВедомостейНаВыплатуЗарплатыЧерезБанк
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьКомплектыВедомостейНаВыплатуЗарплатыЧерезБанк as "(не используется) Комплекты ведомостей на выплату зарплаты через банк" <<Справочники>>
{
..Реквизиты..
Организация : Справочник.Организация
ЗарплатныйПроект : Справочник.Зарплатный проект
ДатаПлатежногоДокумента : Дата
НомерПлатежногоДокумента : Строка
}
@enduml
