@startuml УдалитьОснованияДосрочногоНазначенияПенсииДляСЗВК
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьОснованияДосрочногоНазначенияПенсииДляСЗВК as "(не используется) Основания для досрочной пенсии (СЗВ-К)" <<Справочники>>
{
}
@enduml
