@startuml РолиИсполнителей
'!include templates.wsd
'..\include templates.wsd
class Справочник.РолиИсполнителей as "Роли исполнителей" <<Справочники>>
{
..Реквизиты..
ИспользуетсяБезОбъектовАдресации : Булево
КраткоеПредставление : Строка
ИспользуетсяСОбъектамиАдресации : Булево
Комментарий : Строка
ТипыДополнительногоОбъектаАдресации : Объект адресации задач
ТипыОсновногоОбъектаАдресации : Объект адресации задач
ВнешняяРоль : Булево
УзелОбмена : Строка
..Табличная часть \n Назначение..
ТипПользователей : Справочник.Пользователь\rСправочник.Партнер\rСправочник.Контактное лицо
}
@enduml
