@startuml БонусныеПрограммыЛояльности
'!include templates.wsd
'..\include templates.wsd
class Справочник.БонусныеПрограммыЛояльности as "Бонусные программы лояльности" <<Справочники>>
{
..Реквизиты..
КурсКонвертацииБонусовВВалюту : Число 15, 4
МаксимальныйПроцентОплатыБонусами : Число 5, 2
ВалютаКонвертацииБонусов : Справочник.Валюта
НеНачислятьБаллыПриОплатеБонусами : Булево
СегментНоменклатуры : Справочник.Сегмент номенклатуры
Комментарий : Строка
..Табличная часть \n ЦеновыеГруппы..
МаксимальныйПроцентОплатыБонусами : Число 5, 2
ЦеноваяГруппа : Справочник.Ценовая группа
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
