@startuml УдалитьОснованияДосрочногоНазначенияПенсии
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьОснованияДосрочногоНазначенияПенсии as "(не используется) Основания для досрочной пенсии" <<Справочники>>
{
}
@enduml
