@startuml ГИСМПрисоединенныеФайлы
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГИСМПрисоединенныеФайлы as "Протокол обмена ГИСМ" <<Справочники>>
{
..Реквизиты..
Автор : Справочник.Пользователь
Версия : Число 10, 0
ВладелецФайла : Документ.Уведомление об импорте маркированных товаров\rДокумент.Уведомление о списании КиЗ для маркировки\rДокумент.Уведомление о поступлении маркированных товаров\r...
ДатаЗаема : Дата
ДатаМодификацииУниверсальная : Дата
ДатаПроверкиПодписи : Дата
ДатаСоздания : Дата
Зашифрован : Булево
Изменил : Справочник.Пользователь
ИндексКартинки : Число 10, 0
Операция : Операции обмена ГИСМ
Описание : Строка
ПодписанЭП : Булево
ПодписьВерна : Булево
ПутьКФайлу : Строка
Размер : Число 10, 0
Расширение : Строка
Редактирует : Справочник.Пользователь
СообщениеОснование : Справочник.Сообщение обмена с ГИСМ
СообщениеОснованиеСтатусОбработки : Состояния обработки сообщений ГИСМ
СтатусИзвлеченияТекста : Статусы извлечения текста файлов
СтатусОбработкиЭмитентом : Статусы обработки эмитентом КиЗ
ТекстХранилище : Хранилище значения
ТипСообщения : Типы сообщений ГИСМ
ТипХраненияФайла : Типы хранения файлов
Том : Справочник.Том хранения файлов
ФайлХранилище : Хранилище значения
ХешСумма : Строка
ХранитьВерсии : Булево
}
@enduml
