@startuml ДополнительныеОтчетыИОбработки
'!include templates.wsd
'..\include templates.wsd
class Справочник.ДополнительныеОтчетыИОбработки as "Дополнительные отчеты и обработки" <<Справочники>>
{
..Реквизиты..
БезопасныйРежим : Булево
Версия : Строка
Вид : Виды дополнительных отчетов и обработок
ИмяОбъекта : Строка
ИмяФайла : Строка
Информация : Строка
ИспользоватьДляФормыОбъекта : Булево
ИспользоватьДляФормыСписка : Булево
Комментарий : Строка
Ответственный : Справочник.Пользователь
Публикация : Варианты публикации дополнительных отчетов и обработок
ХранилищеНастроек : Хранилище значения
ХранилищеОбработки : Хранилище значения
ИспользуетХранилищеВариантов : Булево
ТеснаяИнтеграцияСФормойОтчета : Булево
РежимСовместимостиРазрешений : Режимы совместимости разрешений дополнительных отчетов и обработок
..Табличная часть \n Команды..
Идентификатор : Строка
ВариантЗапуска : Способы вызова дополнительных обработок
Представление : Строка
ПоказыватьОповещение : Булево
Модификатор : Строка
РегламентноеЗаданиеGUID : Уникальный идентификатор
Скрыть : Булево
ЗаменяемыеКоманды : Строка
..Табличная часть \n Назначение..
ОбъектНазначения : Справочник.Идентификатор объекта метаданных
УдалитьПолноеИмяОбъектаМетаданных : Строка
..Табличная часть \n Разделы..
Раздел : Справочник.Идентификатор объекта метаданных
УдалитьИмяРаздела : Строка
..Табличная часть \n Разрешения..
ВидРазрешения : Строка
Параметры : Хранилище значения
}
@enduml
