@startuml ШаблоныЗаданийОчереди
'!include templates.wsd
'..\include templates.wsd
class Справочник.ШаблоныЗаданийОчереди as "Шаблоны заданий очереди" <<Справочники>>
{
..Реквизиты..
Использование : Булево
ИмяМетода : Строка
Ключ : Строка
КоличествоПовторовПриАварийномЗавершении : Число 10, 0
ИнтервалПовтораПриАварийномЗавершении : Число 10, 0
Расписание : Хранилище значения
Имя : Строка
}
@enduml
