@startuml СтатьиБюджетов
'!include templates.wsd
'..\include templates.wsd
class Справочник.СтатьиБюджетов as "Статьи бюджетов" <<Справочники>>
{
..Реквизиты..
Описание : Строка
АдресАналитикиКоличество : Число 1, 0
АналитикаВалюты : Аналитики статей бюджетов
АналитикаЕдиницыИзмерения : Аналитики статей бюджетов
ВалютаОпределяетсяАналитикой : Булево
АдресАналитикиВалюта : Число 1, 0
ВидАналитики1 : Аналитики статей бюджетов
ВидАналитики2 : Аналитики статей бюджетов
ВидАналитики3 : Аналитики статей бюджетов
ВидАналитики4 : Аналитики статей бюджетов
ВидАналитики5 : Аналитики статей бюджетов
ЕдиницаИзмерения : Справочник.Упаковка
ЕдиницаИзмеренияОпределяетсяАналитикой : Булево
ВидАналитики6 : Аналитики статей бюджетов
КоличествоИспользуемыхАналитик : Число 1, 0
УчитыватьПоВалюте : Булево
УчитыватьПоКоличеству : Булево
ГруппаДоступа : Справочник.Группы доступа статей и показателей бюджетов
}
@enduml
