@startuml ВидыОтправляемыхДокументов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыОтправляемыхДокументов as "Виды отправляемых документов" <<Справочники>>
{
..Реквизиты..
Описание : Строка
Источник : Строка
ТипПолучателя : Типы контролирующих органов
ТипДокумента : Типы отправляемых документов
}
@enduml
