@startuml ПолитикиУчетаСерий
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПолитикиУчетаСерий as "Политики учета серий" <<Справочники>>
{
..Реквизиты..
Описание : Строка
ТипПолитики : Типы политик указания серий
УказыватьПриПроизводствеПродукции : Булево
УказыватьПриРасходеМатериалов : Булево
УказыватьПоФактуОтбора : Булево
УказыватьПриВозвратеНаСклад : Булево
УказыватьПриОтгрузке : Булево
УказыватьПриВыпускеВПодразделение : Булево
УказыватьПриДвиженииМатериалов : Булево
УказыватьПриДвиженииПродукции : Булево
УказыватьПриОтгрузкеВРозницу : Булево
УказыватьПриОтгрузкеКлиенту : Булево
УказыватьПриОтгрузкеКомплектовДляРазборки : Булево
УказыватьПриОтгрузкеКомплектующихДляСборки : Булево
УказыватьПриОтгрузкеНаВнутренниеНужды : Булево
УказыватьПриОтгрузкеПоВозвратуПоставщику : Булево
УказыватьПриОтгрузкеПоПеремещению : Булево
УказыватьПриОтраженииИзлишков : Булево
УказыватьПриОтраженииЗатратНаПроизводство : Булево
УказыватьПриОтраженииНедостач : Булево
УказыватьПриПеремещенииМеждуПомещениями : Булево
УказыватьПриПересчетеТоваров : Булево
УказыватьПриПланированииОтбора : Булево
УказыватьПриПланированииОтгрузки : Булево
УказыватьПриПриемке : Булево
УказыватьПриПолученииМатериалов : Булево
УказыватьПриПриемкеКомплектующихПослеРазборки : Булево
УказыватьПриПриемкеОтПоставщика : Булево
УказыватьПриПриемкеПоВозвратуОтКлиента : Булево
УказыватьПриПриемкеПоПеремещению : Булево
УказыватьПриПриемкеПоПрочемуОприходованию : Булево
УказыватьПриПриемкеПродукцииИзПроизводства : Булево
УказыватьПриПриемкеСобранныхКомплектов : Булево
УчетСерийПоFEFO : Булево
УчитыватьОстаткиСерий : Булево
УчитыватьСебестоимостьПоСериям : Булево
УказыватьПриВозвратеНепринятыхПолучателемТоваров : Булево
ДляСклада : Булево
ДляПроизводства : Булево
УказыватьПриМаркировкеПродукцииДляГИСМ : Булево
УчетСерийВНеотфактурованныхПоставкахТоваров : Булево
УчетТоваровВПутиОтПоставщикаПоСериям : Булево
}
@enduml
