@startuml ВидыПодарочныхСертификатов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыПодарочныхСертификатов as "Виды подарочных сертификатов" <<Справочники>>
{
..Реквизиты..
Номинал : Число 15, 2
Валюта : Справочник.Валюта
Комментарий : Строка
СегментНоменклатуры : Справочник.Сегмент номенклатуры
ТипКарты : Типы карт
ПериодДействия : Периодичность
КоличествоПериодовДействия : Число 3, 0
ЧастичнаяОплата : Булево
СчетУчета : Счет бухгалтерского учета
СтатьяДоходов : Статьи доходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
НаправлениеДеятельности : Справочник.Направление деятельности
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n ШаблоныКодовПодарочныхСертификатов..
ДлинаШтрихкода : Число 3, 0
НачалоДиапазонаШтрихкода : Строка
КонецДиапазонаШтрихкода : Строка
ДлинаМагнитногоКода : Число 3, 0
НачалоДиапазонаМагнитногоКода : Строка
КонецДиапазонаМагнитногоКода : Строка
ШаблонМагнитнойКарты : Справочник.Шаблон магнитных карт
}
@enduml
