@startuml ПодключаемоеОборудование
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПодключаемоеОборудование as "Подключаемое оборудование" <<Справочники>>
{
..Реквизиты..
ТипОборудования : Типы подключаемого оборудования
ИдентификаторУстройства : Строка
ДрайверОборудования : Справочник.Драйвер оборудования
РабочееМесто : Справочник.Рабочее место
ТребуетсяПереустановка : Булево
ТребуетсяУстановка : Булево
СерийныйНомер : Строка
УдалитьОбработчикДрайвера : Обработчики драйверов подключаемого оборудования
ИдентификаторWebСервисОборудования : Строка
ВерсияФорматаОбмена : Число 5, 0
Организация : Справочник.Организация
УстройствоИспользуется : Булево
ПравилоОбмена : Справочник.Правила обмена с подключаемым оборудованием offline
УзелИнформационнойБазы : Обмен с подключаемым оборудованием Offline
Параметры : Хранилище значения
СпособФорматоЛогическогоКонтроля : Способы формато-логического контроля
ДопустимоеРасхождениеФорматоЛогическогоКонтроля : Число 10, 2
..Табличная часть \n ПараметрыРегистрации..
НаименованиеПараметра : Строка
ЗначениеПараметра : Строка
}
@enduml
