@startuml ПоступлениеСырьяОтДавальцаПрисоединенныеФайлы
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПоступлениеСырьяОтДавальцаПрисоединенныеФайлы as "Присоединенные файлы (Поступление сырья от давальца)" <<Справочники>>
{
..Реквизиты..
Автор : Справочник.Пользователь
ВладелецФайла : Документ.Поступление сырья от давальца
ДатаЗаема : Дата
ДатаМодификацииУниверсальная : Дата
ДатаСоздания : Дата
Зашифрован : Булево
Изменил : Справочник.Пользователь
ИндексКартинки : Число 10, 0
Описание : Строка
ПодписанЭП : Булево
ПутьКФайлу : Строка
Размер : Число 10, 0
Расширение : Строка
Редактирует : Справочник.Пользователь
СтатусИзвлеченияТекста : Статусы извлечения текста файлов
ТекстХранилище : Хранилище значения
ТипХраненияФайла : Типы хранения файлов
Том : Справочник.Том хранения файлов
ФайлХранилище : Хранилище значения
ХранитьВерсии : Булево
..Табличная часть \n УдалитьЭлектронныеПодписи..
ДатаПодписи : Дата
ИмяФайлаПодписи : Строка
Комментарий : Строка
КомуВыданСертификат : Строка
Отпечаток : Строка
Подпись : Хранилище значения
УстановившийПодпись : Справочник.Пользователь
Сертификат : Хранилище значения
ДатаПроверкиПодписи : Дата
ПодписьВерна : Булево
..Табличная часть \n УдалитьСертификатыШифрования..
Отпечаток : Строка
Представление : Строка
Сертификат : Хранилище значения
}
@enduml
