@startuml ВидыДоходовПоСтраховымВзносам
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыДоходовПоСтраховымВзносам as "Виды доходов (взносы)" <<Справочники>>
{
..Реквизиты..
ВходитВБазуПФР : Булево
ВходитВБазуФСС : Булево
ВходитВБазуФОМС : Булево
РеквизитДопУпорядочивания : Число 5, 0
ОблагаетсяВзносамиЧастично : Булево
ВходитВБазуФСС_НС : Булево
АвторскиеВознаграждения : Булево
}
@enduml
