@startuml Контрагенты
'!include templates.wsd
'..\include templates.wsd
class Справочник.Контрагенты as "Контрагенты" <<Справочники>>
{
..Реквизиты..
ИНН : Строка
ОбособленноеПодразделение : Булево
ЮридическоеФизическоеЛицо : Юридическое / физическое лицо
ГоловнойКонтрагент : Справочник.Контрагент
КодПоОКПО : Строка
КПП : Строка
НаименованиеПолное : Строка
ДополнительнаяИнформация : Строка
Партнер : Справочник.Партнер
ЮрФизЛицо : Юр/Физлицо
НДСПоСтавкам4и2 : Булево
СтранаРегистрации : Справочник.Страна мира
РегистрационныйНомер : Строка
НалоговыйНомер : Строка
..Табличная часть \n КонтактнаяИнформация..
Тип : Типы контактной информации
Вид : Справочник.Вид контактной информации
Представление : Строка
ЗначенияПолей : Строка
Страна : Строка
Регион : Строка
Город : Строка
АдресЭП : Строка
ДоменноеИмяСервера : Строка
НомерТелефона : Строка
НомерТелефонаБезКодов : Строка
ВидДляСписка : Справочник.Вид контактной информации
ДействуетС : Дата
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n ИсторияКПП..
Период : Дата
КПП : Строка
..Табличная часть \n ИсторияНаименований..
Период : Дата
НаименованиеПолное : Строка
}
@enduml
