@startuml ДенежныеДокументы
'!include templates.wsd
'..\include templates.wsd
class Справочник.ДенежныеДокументы as "Денежные документы" <<Справочники>>
{
..Реквизиты..
Цена : Число 15, 2
Валюта : Справочник.Валюта
}
@enduml
