@startuml ВариантыАнализаЦелевыхПоказателей
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВариантыАнализаЦелевыхПоказателей as "Варианты анализа целевых показателей" <<Справочники>>
{
..Реквизиты..
ВариантОтображенияПоУмолчанию : Варианты отображения вариантов анализа
ВидПериодаАктуальностиРасчета : Виды периодов актуальности расчета
ВключатьНоль : Булево
ВыводитьМаркерТочекПрогноза : Булево
ВыводитьМаркерыТочек : Булево
ВыводитьПодписиКДиаграммам : Булево
ВыделятьМаксимальноеЗначениеДляПокомпонентногоСравнения : Булево
ГлубинаАнализаПрогноза : Число 3, 0
ГоризонтПрогноза : Число 3, 0
ГрадиентДляПокомпонентногоСравнения : Булево
ЗначениеАнализа : Хранилище значения
ЗначениеАнализаДополнительное : Хранилище значения
КратностьЗначений : Виды представления чисел
МетодРасчетаЗначений : Методы расчета вариантов анализа целевых показателей
ОбъектАнализа : Хранилище значения
ОкантовкаДиаграмм : Булево
Ответственный : Справочник.Пользователь
ОтображатьЛегенду : Булево
ПериодАктуальностиРасчета : Число 6, 0
ПериодАнализа : Хранилище значения
ПериодичностьКонтроля : Периодичность
ПериодичностьРасчетаПоказателя : Периодичность
ПериодСравнения : Хранилище значения
РассчитыватьПрогноз : Булево
РежимПокомпонентногоСравнения : Число 1, 0
РежимСглаживанияДиаграмм : Булево
РежимШкалыЗначений : Режим шкалы значений диаграмм
РеквизитДопУпорядочивания : Число 5, 0
ТипАнализа : Типы анализа показателей
ТипДиаграммы : Типы диаграмм показателей
ТолькоЦветОсновнойСерии : Булево
ТочностьРасчетаДробнойЧасти : Число 1, 0
ХранилищеДемонстрационныхДанных : Хранилище значения
ХранилищеНастроекОформления : Хранилище значения
ХранилищеПользовательскихНастроекКомпоновкиДанных : Хранилище значения
..Табличная часть \n НастройкиДоступности..
Пользователь : Справочник.Пользователь
ВариантОтображения : Варианты отображения вариантов анализа
..Табличная часть \n ОтчетыДляРасшифровки..
ВариантОтчета : Справочник.Вариант отчета
}
@enduml
