@startuml ШаблоныМагнитныхКарт
'!include templates.wsd
'..\include templates.wsd
class Справочник.ШаблоныМагнитныхКарт as "Шаблоны магнитных карт" <<Справочники>>
{
..Реквизиты..
ДоступностьДорожки1 : Булево
Префикс1 : Строка
ДлинаКода1 : Число 5, 0
Суффикс1 : Строка
РазделительБлоков1 : Строка
ДоступностьДорожки2 : Булево
Префикс2 : Строка
ДлинаКода2 : Число 5, 0
Суффикс2 : Строка
РазделительБлоков2 : Строка
ДоступностьДорожки3 : Булево
Префикс3 : Строка
ДлинаКода3 : Число 5, 0
Суффикс3 : Строка
РазделительБлоков3 : Строка
..Табличная часть \n ПоляДорожки1..
Поле : Поля шаблонов магнитных карт
НомерБлока : Число 3, 0
НомерПервогоСимволаПоля : Число 3, 0
ДлинаПоля : Число 3, 0
..Табличная часть \n ПоляДорожки2..
Поле : Поля шаблонов магнитных карт
НомерБлока : Число 3, 0
НомерПервогоСимволаПоля : Число 3, 0
ДлинаПоля : Число 3, 0
..Табличная часть \n ПоляДорожки3..
Поле : Поля шаблонов магнитных карт
НомерБлока : Число 3, 0
НомерПервогоСимволаПоля : Число 3, 0
ДлинаПоля : Число 3, 0
}
@enduml
