@startuml СкладскиеГруппыНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Справочник.СкладскиеГруппыНоменклатуры as "Складские группы номенклатуры" <<Справочники>>
{
..Реквизиты..
Описание : Строка
ТипНоменклатуры : Типы номенклатуры
ФизическиРазличаетсяОтНазначения : Булево
ОграничиватьПоВесу : Булево
ОграничиватьПоОбъему : Булево
}
@enduml
