@startuml ЗакладкиВзаимодействий
'!include templates.wsd
'..\include templates.wsd
class Справочник.ЗакладкиВзаимодействий as "Закладки взаимодействий" <<Справочники>>
{
..Реквизиты..
КомпоновщикНастроек : Хранилище значения
}
@enduml
