@startuml ВидыБюджетов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыБюджетов as "Виды бюджетов" <<Справочники>>
{
..Реквизиты..
Комментарий : Строка
ИспользоватьДляВводаПлана : Булево
Периодичность : Периодичность
СпособПланирования : Способы составления бюджетов
ВариантРасположенияГраницыФактическихДанных : Варианты расположения границы фактически данных
КоличествоПериодовСкользящегоБюджета : Число 10, 0
СмещениеГраницыФакта : Число 10, 0
ПериодичностьГраницыФакта : Периодичность
ОсновнойСпособВвода : Способы редактирования бюджета
ВключитьЗащитуТабличногоДокумента : Булево
СохранятьБюджетВТабличнойФормеВЭкземпляреБюджета : Булево
ПроводитьЭкземплярыБюджетовОтложено : Булево
ГруппаДоступа : Справочник.Группа доступа видов бюджетов
РежимПолученияДанных : Режим получения данных бюджетирования
ЕстьПривилегированныйДоступКДанным : Булево
..Табличная часть \n АналитикиШапки..
ВидАналитики : Аналитики статей бюджетов
..Табличная часть \n КэшСтатейИПоказателей..
СтатьяПоказатель : Справочник.Статьи бюджетов\rСправочник.Показатели бюджетов\rСправочник.Нефинансовые показатели бюджетов
ПривилегированныйРежим : Булево
}
@enduml
