@startuml ГруппыРассылокИОповещений
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГруппыРассылокИОповещений as "Группы рассылок и оповещений" <<Справочники>>
{
..Реквизиты..
Описание : Строка
Принудительная : Булево
ПредназначенаДляЭлектронныхПисем : Булево
ПредназначенаДляSMS : Булево
СрокХраненияСообщений : Число 10, 0
УчетнаяЗапись : Справочник.Учетная запись электронной почты
ВидКонтактнойИнформацииПартнераДляПисем : Справочник.Вид контактной информации
ВидКонтактнойИнформацииПартнераДляSMS : Справочник.Вид контактной информации
ВидКонтактнойИнформацииКонтактногоЛицаДляПисем : Справочник.Вид контактной информации
ВидКонтактнойИнформацииКонтактногоЛицаДляSMS : Справочник.Вид контактной информации
ОтправлятьПартнеру : Булево
ОтправлятьКонтактномуЛицуОбъектаОповещения : Булево
ОтправлятьКонтактнымЛицамРоли : Булево
РольКонтактногоЛица : Справочник.Роль контактного лица партнера
Ответственный : Справочник.Пользователь
}
@enduml
