@startuml ГруппыФинансовогоУчетаВнеоборотныхАктивов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГруппыФинансовогоУчетаВнеоборотныхАктивов as "Группы финансового учета внеоборотных активов" <<Справочники>>
{
..Реквизиты..
ВидАктива : Виды внеоборотных активов
СчетУчета : Счет бухгалтерского учета
СчетУчетаЦФ : Счет бухгалтерского учета
СчетУчетаАмортизации : Счет бухгалтерского учета
СчетУчетаАмортизацииЦФ : Счет бухгалтерского учета
СчетУчетаВыбытия : Счет бухгалтерского учета
СчетУчетаРезерваДооценки : Счет бухгалтерского учета
СчетЗабалансовогоУчета : Счет бухгалтерского учета
Описание : Строка
}
@enduml
