@startuml СкладскиеГруппыУпаковок
'!include templates.wsd
'..\include templates.wsd
class Справочник.СкладскиеГруппыУпаковок as "Складские группы упаковок" <<Справочники>>
{
..Реквизиты..
Описание : Строка
}
@enduml
