@startuml СтруктураЦелей
'!include templates.wsd
'..\include templates.wsd
class Справочник.СтруктураЦелей as "Структура целей" <<Справочники>>
{
..Реквизиты..
КатегорияЦели : Справочник.Категория цели
ЦельИзмеримая : Булево
ЦелевойПоказатель : Строка
КраткоеНаименованиеЦелевогоПоказателя : Строка
Описание : Строка
ФормулаРасчета : Строка
СхемаКомпоновкиДанных : Строка
ХранилищеСхемыКомпоновкиДанных : Хранилище значения
ХранилищеНастроекКомпоновкиДанных : Хранилище значения
Размерность : Строка
ЦелевойТренд : Виды целевых трендов показателей
РеквизитДопУпорядочивания : Число 5, 0
РеквизитДопУпорядочиванияИерархического : Строка
}
@enduml
