@startuml КоллекцииНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Справочник.КоллекцииНоменклатуры as "Коллекции (сезоны)" <<Справочники>>
{
..Реквизиты..
ДатаНачалаПродаж : Дата
ДатаЗапретаПродажи : Дата
ДатаНачалаЗакупок : Дата
ДатаЗапретаЗакупки : Дата
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
