@startuml МестаРаботы
'!include templates.wsd
'..\include templates.wsd
class Справочник.МестаРаботы as "Места работы" <<Справочники>>
{
..Табличная часть \n Начисления..
Начисление : Начисление
ИдентификаторСтрокиВидаРасчета : Число 7, 0
..Табличная часть \n Показатели..
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Показатель : Справочник.Показатель
Значение : Число 15, 5
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
