@startuml ВидыОповещенийКлиентам
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыОповещенийКлиентам as "Виды оповещений клиентам" <<Справочники>>
{
..Реквизиты..
ГруппаРассылокИОповещений : Справочник.Группа рассылок и оповещений
ПредназначенаДляЭлектронныхПисем : Булево
ПредназначенаДляSMS : Булево
ШаблонСообщенияSMS : Справочник.Шаблон сообщения
ШаблонЭлектронногоПисьма : Справочник.Шаблон сообщения
ИспользуетсяУсловиеОтправки : Булево
УсловиеОтправки : Строка
РегламентноеЗадание : Уникальный идентификатор
ТипСобытия : Типы событий оповещений
Комментарий : Строка
..Табличная часть \n ПараметрыУсловия..
ЭтоПараметрПредыдущегоСообщения : Булево
ИмяПараметра : Строка
}
@enduml
