@startuml ЗамещениеГосударственныхМуниципальныхДолжностейПФР
'!include templates.wsd
'..\include templates.wsd
class Справочник.ЗамещениеГосударственныхМуниципальныхДолжностейПФР as "Замещение государственных муниципальных должностей ПФР" <<Справочники>>
{
}
@enduml
