@startuml Справки2ЕГАИС
'!include templates.wsd
'..\include templates.wsd
class Справочник.Справки2ЕГАИС as "Справки 2 ЕГАИС" <<Справочники>>
{
..Реквизиты..
РегистрационныйНомер : Строка
АлкогольнаяПродукция : Справочник.Алкогольная продукция ЕГАИС
НомерСправки1 : Строка
Справка1 : Справочник.Справка к ТТН по форме 1
ДокументОснование : Документ.Товарно-транспортная накладная ЕГАИС (входящая)\rДокумент.Товарно-транспортная накладная ЕГАИС (исходящая)\rДокумент.Акт постановки на баланс ЕГАИС
Количество : Число 15, 3
НомерПодтвержденияЕГАИС : Строка
ДатаПодтвержденияЕГАИС : Дата
ЕстьДиапазонНомеровАкцизныхМарок : Булево
УдалитьНомерТТН : Строка
УдалитьДатаТТН : Дата
УдалитьГрузоотправитель : Справочник.Организация ЕГАИС
УдалитьГрузополучатель : Справочник.Организация ЕГАИС
УдалитьДатаОтгрузки : Дата
..Табличная часть \n ДиапазоныНомеровАкцизныхМарок..
ТипМарки : Строка
СерияМарки : Строка
НачальныйНомер : Строка
КонечныйНомер : Строка
}
@enduml
