@startuml НастройкиРМК
'!include templates.wsd
'..\include templates.wsd
class Справочник.НастройкиРМК as "Настройки РМК" <<Справочники>>
{
..Реквизиты..
ГорячиеКлавиши : Справочник.Горячие клавиши
РабочееМесто : Справочник.Рабочее место
ИспользоватьАвторизацию : Булево
КассирМожетБытьПродавцом : Булево
МенеджерТорговогоЗалаМожетБытьПродавцом : Булево
..Табличная часть \n Кассы..
Касса : Справочник.Касса
ПодключаемоеОборудование : Справочник.Экземпляр подключаемого оборудования
..Табличная часть \n КассыККМ..
КассаККМ : Справочник.Кассы ККМ
ИспользоватьБезПодключенияОборудования : Булево
АвтоматическаяИнкассация : Булево
ПодключаемоеОборудование : Справочник.Экземпляр подключаемого оборудования
..Табличная часть \n ЭквайринговыеТерминалы..
ЭквайринговыйТерминал : Справочник.Эквайринговый терминал
ИспользоватьБезПодключенияОборудования : Булево
ПодключаемоеОборудование : Справочник.Экземпляр подключаемого оборудования
ПодключаемоеОборудованиеККТ : Справочник.Экземпляр подключаемого оборудования
}
@enduml
