@startuml ПрочиеАктивыПассивы
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПрочиеАктивыПассивы as "Прочие активы и пассивы" <<Справочники>>
{
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
