@startuml ВидыСвязейМеждуФизЛицами
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыСвязейМеждуФизЛицами as "Виды связей между физическими лицами" <<Справочники>>
{
..Реквизиты..
Комментарий : Строка
РольФизЛица1 : Строка
РольФизЛица2 : Строка
ОбратноеНаименование : Строка
}
@enduml
