@startuml КартыЛояльности
'!include templates.wsd
'..\include templates.wsd
class Справочник.КартыЛояльности as "Карты лояльности" <<Справочники>>
{
..Реквизиты..
Штрихкод : Строка
МагнитныйКод : Строка
Статус : Статусы карт лояльности
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
Соглашение : Справочник.Соглашение об условиях продаж
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
