@startuml ЭДПрисоединенныеФайлы
'!include templates.wsd
'..\include templates.wsd
class Справочник.ЭДПрисоединенныеФайлы as "Присоединенные файлы (Электронные документы)" <<Справочники>>
{
..Реквизиты..
Автор : Справочник.Внешний пользователь\rСправочник.Учетная запись синхронизации файлов\rСправочник.Пользователь
ВладелецФайла : Документ.Входящий электронный документ\rДокумент.Возврат товаров от клиента\rДокумент.Исходящий электронный документ\r...
ДатаЗаема : Дата
ДатаИзмененияСтатусаЭД : Дата
ДатаМодификацииУниверсальная : Дата
ДатаСоздания : Дата
ДатаФормированияЭДОтправителем : Дата
ДополнительнаяИнформация : Строка
ДополнительныеРеквизиты : Хранилище значения
Загружен : Булево
Зашифрован : Булево
Изменил : Справочник.Внешний пользователь\rСправочник.Учетная запись синхронизации файлов\rСправочник.Пользователь
ИндексКартинки : Число 10, 0
НаименованиеФайла : Строка
НаправлениеЭД : Направления ЭД
НомерЭД : Строка
Описание : Строка
ОтправительЭД : Строка
ПодписанЭП : Булево
ПолучательЭД : Строка
ПредставлениеПрогрессаПодписания : Строка
ПутьКФайлу : Строка
Размер : Число 10, 0
Расширение : Строка
Редактирует : Справочник.Внешний пользователь\rСправочник.Учетная запись синхронизации файлов\rСправочник.Пользователь
СтатусИзвлеченияТекста : Статусы извлечения текста файлов
СтатусЭД : Статусы ЭД
ТекстХранилище : Хранилище значения
ТипХраненияФайла : Типы хранения файлов
ТипЭлементаВерсииЭД : Типы элементов версии электронных документов
Том : Справочник.Том хранения файлов
УдалитьВерсияРегламентаЭДО : Версии регламента обмена1 С
УдалитьВидЭД : Виды электронных документов
УдалитьВладелецФайла : Документ.Сторнирование начислений\rДокумент.Внутреннее потребление товаров\rДокумент.Назначение планового начисления\r...
УдалитьДатаВыпискиБанка : Дата
УдалитьДатаДокументаОтправителя : Дата
УдалитьДатаИзмененияВнешнегоСтатусаЭД : Дата
УдалитьКонтрагент : Справочник.Организация\rСправочник.Контрагент
УдалитьНомерВерсииЭД : Число 3, 0
УдалитьНомерДокументаОтправителя : Строка
УдалитьОрганизация : Справочник.Организация
УдалитьОтветственный : Справочник.Пользователь
УдалитьПричинаОтклонения : Строка
УдалитьПрофильНастроекЭДО : Справочник.Профиль настроек ЭДО
УдалитьСоглашениеЭД : Справочник.Настройка ЭДО
УдалитьСуммаДокумента : Число 15, 2
УникальныйИД : Строка
УникальныйИДВнешний : Строка
ФайлХранилище : Хранилище значения
ХранитьВерсии : Булево
ЭлектронныйДокументВладелец : Справочник.Присоединенный файл (Электронный документ)
..Табличная часть \n УдалитьСертификатыШифрования..
Отпечаток : Строка
Представление : Строка
Сертификат : Хранилище значения
..Табличная часть \n УдалитьЭлектронныеПодписи..
ДатаПодписи : Дата
ДатаПроверкиПодписи : Дата
ИмяФайлаПодписи : Строка
Комментарий : Строка
КомуВыданСертификат : Строка
Отпечаток : Строка
Подпись : Хранилище значения
ПодписьВерна : Булево
Сертификат : Хранилище значения
УстановившийПодпись : Справочник.Пользователь
..Табличная часть \n ИдентификаторыОснованийВладельцаФайла..
ИдентификаторДокументаОснования : Строка
ИдентификаторЭДДокументаОснования : Строка
}
@enduml
