@startuml КлючиАналитикиУчетаПоПартнерам
'!include templates.wsd
'..\include templates.wsd
class Справочник.КлючиАналитикиУчетаПоПартнерам as "Ключи аналитики учета по партнерам" <<Справочники>>
{
..Реквизиты..
Партнер : Справочник.Партнер
Организация : Справочник.Организация
Контрагент : Справочник.Организация\rСправочник.Контрагент
Договор : Справочник.Договор между организациями\rСправочник.Договор с контрагентом
НаправлениеДеятельности : Справочник.Направление деятельности
}
@enduml
