@startuml ВариантыКлассификацииЗадолженности
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВариантыКлассификацииЗадолженности as "Варианты классификации задолженности" <<Справочники>>
{
..Реквизиты..
Календарь : Справочник.Производственный календарь
..Табличная часть \n Интервалы..
НижняяГраницаИнтервала : Число 10, 0
ВерхняяГраницаИнтервала : Число 10, 0
НаименованиеИнтервала : Строка
}
@enduml
