@startuml ВидыАлкогольнойПродукции
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыАлкогольнойПродукции as "Виды алкогольной и спиртосодержащей продукции" <<Справочники>>
{
..Реквизиты..
ВидЛицензии : Виды лицензий алкогольной (спиртосодержащей) продукции
Маркируемый : Булево
}
@enduml
