@startuml ОтветственныеЛицаОрганизаций
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОтветственныеЛицаОрганизаций as "Ответственные лица организаций" <<Справочники>>
{
..Реквизиты..
ОтветственноеЛицо : Ответственные лица организаций
ФизическоеЛицо : Справочник.Физическое лицо
ДолжностьСсылка : Справочник.Должность
Должность : Строка
ПравоПодписиПоДоверенности : Булево
ОснованиеПраваПодписи : Строка
ДатаНачала : Дата
ДатаОкончания : Дата
ДокументПраваПодписи : Строка
НомерДокументаПраваПодписи : Строка
ДатаДокументаПраваПодписи : Дата
}
@enduml
