@startuml ПоставляемыеДополнительныеОтчетыИОбработки
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПоставляемыеДополнительныеОтчетыИОбработки as "Поставляемые дополнительные отчеты и обработки" <<Справочники>>
{
..Реквизиты..
Вид : Виды дополнительных отчетов и обработок
ИспользоватьДляФормыОбъекта : Булево
ИспользоватьДляФормыСписка : Булево
Публикация : Варианты публикации дополнительных отчетов и обработок
ПричинаОтключения : Причины отключения дополнительных отчетов и обработок в модели сервиса
Информация : Строка
Версия : Строка
БезопасныйРежим : Булево
ИмяОбъекта : Строка
ИмяФайла : Строка
ХранилищеОбработки : Хранилище значения
ХранилищеВариантов : Строка
ВерсияGUID : Уникальный идентификатор
КонтролироватьСовместимостьСВерсиямиКонфигурации : Булево
ИспользуетХранилищеВариантов : Булево
РежимСовместимостиРазрешений : Режимы совместимости разрешений дополнительных отчетов и обработок
..Табличная часть \n Команды..
Идентификатор : Строка
ВариантЗапуска : Способы вызова дополнительных обработок
Представление : Строка
ПоказыватьОповещение : Булево
Модификатор : Строка
Скрыть : Булево
..Табличная часть \n Совместимость..
Версия : Строка
..Табличная часть \n Разрешения..
ВидРазрешения : Строка
Параметры : Хранилище значения
}
@enduml
