@startuml УдалитьСтатусыНалогоплательщиковПоНДФЛ
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьСтатусыНалогоплательщиковПоНДФЛ as "(не используется) Статусы налогоплательщиков (НДФЛ)" <<Справочники>>
{
..Реквизиты..
УдалитьИдентификаторОбъекта : Строка
КодФНС : Строка
РеквизитДопУпорядочивания : Число 5, 0
}
@enduml
