@startuml ПоставляемыеДанные
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПоставляемыеДанные as "Поставляемые данные" <<Справочники>>
{
..Реквизиты..
ВидДанных : Строка
ДатаДобавления : Дата
ХранимыйФайл : Хранилище значения
ПутьКФайлу : Строка
Том : Справочник.Том хранения файлов
ТипХраненияФайла : Типы хранения файлов
ИдентификаторФайла : Уникальный идентификатор
Описание : Строка
..Табличная часть \n ХарактеристикиДанных..
Характеристика : Строка
Значение : Строка
}
@enduml
