@startuml СостоянияПроцессов
'!include templates.wsd
'..\include templates.wsd
class Справочник.СостоянияПроцессов as "Этапы процессов" <<Справочники>>
{
..Реквизиты..
Описание : Строка
РеквизитДопУпорядочивания : Число 7, 0
}
@enduml
