@startuml Проекты
'!include templates.wsd
'..\include templates.wsd
class Справочник.Проекты as "Проекты" <<Справочники>>
{
..Реквизиты..
Ответственный : Справочник.Пользователь
ПлановаяДатаНачала : Дата
ДатаНачала : Дата
ПлановаяДатаОкончания : Дата
ДатаОкончания : Дата
Завершен : Булево
Комментарий : Строка
..Табличная часть \n ПартнерыИКонтактныеЛица..
Партнер : Справочник.Партнер
РольПартнера : Справочник.Роль партнера в сделке или проекте
КонтактноеЛицо : Справочник.Контактное лицо
Комментарий : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
