@startuml ТиповыеОперацииМеждународныйУчет
'!include templates.wsd
'..\include templates.wsd
class Справочник.ТиповыеОперацииМеждународныйУчет as "Типовые операции (международный учет)" <<Справочники>>
{
..Реквизиты..
Организация : Справочник.Организация
СодержаниеОперации : Строка
Комментарий : Строка
..Табличная часть \n Проводки..
СчетДт : Международный план счетов
ПодразделениеДт : Справочник.Подразделение
НаправлениеДеятельностиДт : Справочник.Направление деятельности
СубконтоДт1 : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСтатья расходов\r...
СубконтоДт2 : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСтатья расходов\r...
СубконтоДт3 : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСтатья расходов\r...
ВалютаДт : Справочник.Валюта
ВалютнаяСуммаДт : Число 15, 2
СчетКт : Международный план счетов
ПодразделениеКт : Справочник.Подразделение
НаправлениеДеятельностиКт : Справочник.Направление деятельности
СубконтоКт1 : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСтатья расходов\r...
СубконтоКт2 : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСтатья расходов\r...
СубконтоКт3 : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСтатья расходов\r...
ВалютаКт : Справочник.Валюта
ВалютнаяСуммаКт : Число 15, 2
Сумма : Число 15, 2
СуммаПредставления : Число 15, 2
Содержание : Строка
ТипПроводки : Типы проводок международный учет
}
@enduml
