@startuml СтруктураПредприятия
'!include templates.wsd
'..\include templates.wsd
class Справочник.СтруктураПредприятия as "Структура предприятия" <<Справочники>>
{
..Реквизиты..
ТекущийРуководитель : Справочник.Физическое лицо
ВариантОбособленногоУчетаТоваров : Варианты обособленного учета товаров
Источник : Справочник.Организация\rСправочник.Подразделение
СоответствуетСтруктуреЮридическихЛиц : Булево
ПроизводственноеПодразделение : Булево
ГрафикРаботы : Справочник.График работы
ИнтервалПланирования : Точность графика производства
НачалоИнтервалаПланирования : Дата
ОкончаниеИнтервалаПланирования : Дата
УправлениеМаршрутнымиЛистами : Управление маршрутными листами
РеквизитДопУпорядочивания : Число 5, 0
ЗаполнениеДоступностиДляРасписанияРЦКоличествоИнтервалов : Число 3, 0
ЗаполнениеДоступностиДляРасписанияРЦНапоминаниеДней : Число 3, 0
ЗаполнениеДоступностиДляГрафикаПроизводстваКоличествоИнтервалов : Число 3, 0
СпособПооперационногоУправления : Способы управления операциями
ЗаполнениеДоступностиДляГрафикаПроизводстваНапоминаниеДней : Число 3, 0
ПодразделениеДиспетчер : Булево
ИспользоватьСерииНоменклатуры : Булево
ВремяНаРегистрациюВыполнения : Число 10, 0
ВремяНаРегистрациюВыполненияЕдИзм : Единицы измерения времени
УчитыватьСебестоимостьПоСериям : Булево
ПроизводствоПоЗаказам : Булево
ПроизводствоБезЗаказов : Булево
ИспользуетсяСписаниеЗатратНаВыпуск : Булево
СпособПолученияПолуфабрикатов : Способы получения полуфабрикатов производимых в процессе
ИспользоватьПооперационноеУправление : Булево
ИспользоватьМатериалыВОперациях : Булево
ИспользоватьВыходныеИзделияВОперациях : Булево
ИспользоватьПооперационноеПланирование : Булево
ПериодичностьОформленияВыработки : Периодичность оформления выработки сотрудников
ИспользоватьКТУ : Булево
ИспользоватьТарифныеСтавки : Булево
ИспользоватьОтработанноеВремя : Булево
ИспользоватьБригадныеНаряды : Булево
ИспользоватьПерсональныеНаряды : Булево
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
