@startuml ОбразованиеФизическихЛиц
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОбразованиеФизическихЛиц as "Образование физических лиц" <<Справочники>>
{
..Реквизиты..
УдалитьОсновноеОбразование : Булево
ВидОбразования : Справочник.Вид образования
ВидПослевузовскогоОбразования : Справочник.Вид образования
УчебноеЗаведение : Справочник.Учебное заведение
Специальность : Справочник.Специальность
ВидДокумента : Справочник.Вид документа об образовании
Серия : Строка
Номер : Строка
ДатаВыдачи : Дата
Квалификация : Строка
Начало : Дата
Окончание : Дата
НаименованиеКурса : Строка
КоличествоЧасов : Число 4, 0
ВидДополнительногоОбучения : Виды профессиональной подготовки
Основание : Строка
УдалитьДокументОснование : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
