@startuml ПравилаНачисленияИСписанияБонусныхБаллов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПравилаНачисленияИСписанияБонусныхБаллов as "Правила начисления и списания бонусных баллов" <<Справочники>>
{
..Реквизиты..
СхемаКомпоновкиДанных : Строка
РегламентноеЗадание : Уникальный идентификатор
ХранилищеСхемыКомпоновкиДанных : Хранилище значения
ХранилищеНастроекКомпоновкиДанных : Хранилище значения
ПериодДействия : Периодичность
КоличествоПериодовДействия : Число 10, 0
КоличествоПериодовОтсрочкиНачалаДействия : Число 10, 0
ПериодОтсрочкиНачалаДействия : Периодичность
ВидПравила : Виды правил начисления бонусных баллов
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
