@startuml СтроковыеКонтактыВзаимодействий
'!include templates.wsd
'..\include templates.wsd
class Справочник.СтроковыеКонтактыВзаимодействий as "Строковые контакты взаимодействий" <<Справочники>>
{
}
@enduml
