@startuml ЦиклыОбмена
'!include templates.wsd
'..\include templates.wsd
class Справочник.ЦиклыОбмена as "Циклы обмена" <<Справочники>>
{
..Реквизиты..
УчетнаяЗапись : Справочник.(не используется) Учетные записи документооборота\rСправочник.Учетные записи документооборота
Тип : Типы циклов обмена
Идентификатор : Строка
Предмет : Документ.Выгрузка регламентированных отчетов\rДокумент.Сведения о заработке и стаже застрахованных лиц, СЗВ-ИСХ\rДокумент.2-НДФЛ для передачи в ИФНС\r...
Организация : Справочник.Организация
ВнешняяОрганизация : Справочник.(не используется) Налоговые органы\rСправочник.Налоговые органы\rСправочник.Органы ФСГС\r...
ДатаСоздания : Дата
ДатаЗакрытия : Дата
ДатаПоследнегоСообщения : Дата
ДатаНачалаПериода : Дата
ДатаОкончанияПериода : Дата
ВидДокумента : Число 3, 0
ВидУслуги : Виды услуг при информационном обслуживании налогоплательщика\rВиды услуг при информационном обслуживании страхователя
ФорматОтвета : Формат ответа на запрос на информационное обслуживание налогоплательщика
Период : Строка
Вид : Виды циклов обмена\r(не используется) Виды циклов обмена
ФорматДокументооборота : Форматы документооборота с ФНС\r(не используется) Форматы документооборота с ФНС
ПредставлениеПериода : Строка
ПредставлениеВидаДокумента : Строка
УдалитьВидОтчета : Справочник.Виды отправляемых документов\rСправочник.Регламентированные отчеты\rСправочник.(не используется) Виды отправляемых документов\r...
ВидОтчета : Справочник.Виды отправляемых документов\rСправочник.Регламентированные отчеты\rСправочник.(не используется) Виды отправляемых документов\r...
..Табличная часть \n ДополнительныеПредметы..
Предмет : Документ.Выгрузка регламентированных отчетов\rДокумент.Сведения о заработке и стаже застрахованных лиц, СЗВ-ИСХ\rДокумент.2-НДФЛ для передачи в ИФНС\r...
}
@enduml
