@startuml ЛицензииПоставщиковАлкогольнойПродукции
'!include templates.wsd
'..\include templates.wsd
class Справочник.ЛицензииПоставщиковАлкогольнойПродукции as "Лицензии поставщиков на алкогольную и спиртосодержащую продукцию" <<Справочники>>
{
..Реквизиты..
ВидЛицензии : Виды лицензий алкогольной (спиртосодержащей) продукции
ДатаНачала : Дата
ДатаОкончания : Дата
КемВыдана : Строка
}
@enduml
