@startuml ВариантыНаладки
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВариантыНаладки as "Варианты наладки" <<Справочники>>
{
..Реквизиты..
ВремяРаботы : Число 10, 1
ЕдиницаИзмерения : Единицы измерения времени
ЦветОформления : Хранилище значения
Описание : Строка
}
@enduml
