@startuml УдалитьГосударственныеКонтрактыПрисоединенныеФайлы
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьГосударственныеКонтрактыПрисоединенныеФайлы as "(не используется) Государственные контракты (присоединенные файлы)" <<Справочники>>
{
..Реквизиты..
Автор : Справочник.Пользователь
Валюта : Справочник.Валюта
ВидДокумента : Справочник.Вид документа
ВладелецФайла : Справочник.Договор между организациями\rСправочник.Договор с контрагентом\rСправочник.Договор кредита (депозита)
Дата : Дата
ДатаЗаема : Дата
ДатаМодификацииУниверсальная : Дата
ДатаСоздания : Дата
Зашифрован : Булево
Изменил : Справочник.Пользователь
ИндексКартинки : Число 10, 0
Контракт : Справочник.Договор с контрагентом
Номер : Строка
НомерКорректировки : Число 3, 0
Описание : Строка
ПодписанЭП : Булево
Покупатель : Справочник.Организация\rСправочник.Контрагент
Поставщик : Справочник.Организация\rСправочник.Контрагент
ПутьКФайлу : Строка
Размер : Число 10, 0
Расширение : Строка
Редактирует : Справочник.Пользователь
СтатусИзвлеченияТекста : Статусы извлечения текста файлов
Сумма : Число 15, 2
ТекстХранилище : Хранилище значения
ТипХраненияФайла : Типы хранения файлов
Том : Справочник.Том хранения файлов
ФайлХранилище : Хранилище значения
ХранитьВерсии : Булево
..Табличная часть \n УдалитьЭлектронныеПодписи..
ДатаПодписи : Дата
ИмяФайлаПодписи : Строка
Комментарий : Строка
КомуВыданСертификат : Строка
Отпечаток : Строка
Подпись : Хранилище значения
УстановившийПодпись : Справочник.Пользователь
Сертификат : Хранилище значения
..Табличная часть \n УдалитьСертификатыШифрования..
Отпечаток : Строка
Представление : Строка
Сертификат : Хранилище значения
}
@enduml
