@startuml НастройкиПродажДляПользователей
'!include templates.wsd
'..\include templates.wsd
class Справочник.НастройкиПродажДляПользователей as "Настройки продаж" <<Справочники>>
{
..Реквизиты..
ОграничиватьРучныеСкидки : Булево
ЕстьУточненияПоЦеновымГруппам : Булево
ПроцентРучнойНаценки : Число 5, 2
ПроцентРучнойСкидки : Число 5, 2
РМК_Использовать : Булево
РМК_ВозвратТовара : Булево
РМК_ВнесениеДенег : Булево
РМК_ВыемкаДенег : Булево
РМК_КорректировкаСтрок : Булево
РМК_Отложить : Булево
РМК_Зарезервировать : Булево
РМК_ОткрытьСмену : Булево
РМК_ЗакрытьСмену : Булево
РМК_ИзменениеКартЛояльности : Булево
РМК_РедактированиеИнформацииОКлиенте : Булево
..Табличная часть \n ЦеновыеГруппы..
ЦеноваяГруппа : Справочник.Ценовая группа
ПроцентРучнойСкидки : Число 5, 2
ПроцентРучнойНаценки : Число 5, 2
}
@enduml
