@startuml ВидыКартЛояльности
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыКартЛояльности as "Виды карт лояльности" <<Справочники>>
{
..Реквизиты..
Статус : Статусы видов карт лояльности
ДатаНачалаДействия : Дата
ДатаОкончанияДействия : Дата
Комментарий : Строка
Персонализирована : Булево
АвтоматическаяРегистрацияПриПервомСчитывании : Булево
ТипКарты : Типы карт
Организация : Справочник.Организация
БонуснаяПрограммаЛояльности : Справочник.Бонусные программы лояльности
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n ШаблоныКодовКартЛояльности..
ДлинаШтрихкода : Число 3, 0
НачалоДиапазонаШтрихкода : Строка
КонецДиапазонаШтрихкода : Строка
ДлинаМагнитногоКода : Число 3, 0
НачалоДиапазонаМагнитногоКода : Строка
КонецДиапазонаМагнитногоКода : Строка
ШаблонМагнитнойКарты : Справочник.Шаблон магнитных карт
}
@enduml
