@startuml ДрагоценныеМатериалы
'!include templates.wsd
'..\include templates.wsd
class Справочник.ДрагоценныеМатериалы as "Драгоценные металлы и камни" <<Справочники>>
{
..Реквизиты..
ЕдиницаИзмерения : Справочник.Упаковка
}
@enduml
