@startuml КлассификаторВидовЭкономическойДеятельности
'!include templates.wsd
'..\include templates.wsd
class Справочник.КлассификаторВидовЭкономическойДеятельности as "ОКВЭД" <<Справочники>>
{
..Реквизиты..
НаименованиеПолное : Строка
}
@enduml
