@startuml ОбъектыСтроительства
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОбъектыСтроительства as "Объекты строительства" <<Справочники>>
{
..Реквизиты..
Адрес : Строка
СпособСтроительства : Способы строительства
СостояниеСтроительства : Состояния объектов строительства
Описание : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
