@startuml ПравилаЛимитовПоДаннымБюджетирования
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПравилаЛимитовПоДаннымБюджетирования as "Правила лимитов по данным бюджетирования" <<Справочники>>
{
..Реквизиты..
СтатьяБюджета : Справочник.Статьи бюджетов
Сценарий : Справочник.Сценарии бюджетирования
Периодичность : Периодичность
ПредставлениеАналитик : Строка
ТипЛимита : Типы лимитов расходования ДС
..Табличная часть \n ИспользуемыеАналитики..
ВидАналитики : Аналитики статей бюджетов
ИмяИзмерения : Строка
}
@enduml
