@startuml СтатьиКалькуляции
'!include templates.wsd
'..\include templates.wsd
class Справочник.СтатьиКалькуляции as "Статьи калькуляции" <<Справочники>>
{
..Реквизиты..
ТипЗатрат : Типы затрат
РеквизитДопУпорядочивания : Число 5, 0
Идентификатор : Строка
УдалитьПредопределеннаяСтатьяМатериалов : Булево
УдалитьПредопределеннаяСтатьяВозвратныхОтходов : Булево
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
