@startuml КассовыеКниги
'!include templates.wsd
'..\include templates.wsd
class Справочник.КассовыеКниги as "Кассовые книги" <<Справочники>>
{
..Реквизиты..
Префикс : Строка
ИспользоватьПрефикс : Булево
СтруктурноеПодразделение : Строка
}
@enduml
