@startuml СкидкиНаценки
'!include templates.wsd
'..\include templates.wsd
class Справочник.СкидкиНаценки as "Скидки (наценки)" <<Справочники>>
{
..Реквизиты..
ВалютаПредоставления : Справочник.Валюта
ВариантСовместногоПрименения : Варианты совместного применения скидок наценок
ВидЦены : Справочник.Вид цены
ЗначениеСкидкиНаценки : Число 15, 3
РеквизитДопУпорядочивания : Число 5, 0
СпособПредоставления : Справочник.Дополнительный отчет или обработка\rСпособы предоставления скидок наценок
Управляемая : Булево
ТекстСообщения : Строка
ВидКартыЛояльности : Справочник.Вид карт лояльности
СегментПодарков : Справочник.Сегмент номенклатуры
ИспользоватьКратность : Булево
УсловиеДляСкидкиКоличеством : Число 10, 3
ТочностьОкругления : Число 15, 2
ПсихологическоеОкругление : Число 15, 2
ОкруглятьВБольшуюСторону : Булево
СпособПримененияСкидки : Способы применения скидок (наценок)
БонуснаяПрограммаЛояльности : Справочник.Бонусные программы лояльности
ПериодДействия : Периодичность
КоличествоПериодовДействия : Число 10, 0
ПериодОтсрочкиНачалаДействия : Периодичность
КоличествоПериодовОтсрочкиНачалаДействия : Число 10, 0
ВариантРасчетаРезультатаСовместногоПрименения : Варианты расчета результата совместного применения
ВариантОтбораНоменклатуры : Варианты отбора номенклатуры для расчета скидок наценок
СегментНоменклатурыОграничения : Справочник.Сегмент номенклатуры
ПараметрыВнешнейОбработки : Хранилище значения
ВариантОкругления : Варианты округления
ХранилищеНастроекКомпоновкиДанных : Хранилище значения
УстановленДополнительныйОтбор : Булево
ПрименятьУмножениеВРамкахВышестоящейГруппы : Булево
УчитыватьХарактеристики : Булево
..Табличная часть \n УсловияПредоставления..
УсловиеПредоставления : Справочник.Условие предоставления скидки (наценки)
..Табличная часть \n ЦеновыеГруппы..
ЦеноваяГруппа : Справочник.Ценовая группа
ЗначениеСкидкиНаценки : Число 15, 2
}
@enduml
