@startuml УдалитьВидыТарифовСтраховыхВзносов
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьВидыТарифовСтраховыхВзносов as "(не используется) Виды тарифов страховых взносов" <<Справочники>>
{
..Реквизиты..
УдалитьИдентификаторОбъекта : Строка
КодПФР2011 : Строка
КодФСС2011 : Строка
КодПФР2012 : Строка
КодФСС2012 : Строка
ПрименяетсяПоОтдельнымДоходам : Булево
РеквизитДопУпорядочивания : Число 5, 0
}
@enduml
