@startuml УслугиСервиса
'!include templates.wsd
'..\include templates.wsd
class Справочник.УслугиСервиса as "Услуги сервиса" <<Справочники>>
{
..Реквизиты..
Идентификатор : Строка
ПоказыватьПриДобавленииВТариф : Булево
ПоставщикУслуги : Справочник.Внешний сервис
Тарифицируется : Булево
ТипУслуги : Типы услуг
}
@enduml
