@startuml УдалитьУчетныеЗаписиДокументооборота
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьУчетныеЗаписиДокументооборота as "(не используется) Учетные записи документооборота" <<Справочники>>
{
..Реквизиты..
ИмяПользователяPOP3 : Строка
ПарольPOP3 : Строка
СерверPOP3 : Строка
ПортPOP3 : Число 5, 0
ИмяПользователяSMTP : Строка
ПарольSMTP : Строка
СерверSMTP : Строка
ПортSMTP : Число 5, 0
ТребуетсяSMTPАутентификация : Булево
АдресЭлектроннойПочты : Строка
НалоговыйОрган : Справочник.(не используется) Налоговые органы
СерверДокументооборота : Справочник.(не используется) Серверы документооборота
СертификатРуководителя : Строка
СертификатГлавногоБухгалтера : Строка
СертификатДляШифрования : Строка
УдалитьАвтоматическоеОпределениеНабораПодписей : Булево
ИспользуютсяСъемныеКлючевыеНосители : Булево
УдалитьНестандартныеТаймауты : Булево
УдалитьТаймаутНалоговогоОргана : Число 2, 0
УдалитьТаймаутНалогоплательщика : Число 2, 0
УдалитьИспользуетсяОбособленнымиПодразделениями : Булево
ОбменНапрямую : Булево
ОбменНапрямуюСФСГС : Булево
НеФормироватьПодтвержденияАвтоматически : Булево
РежимАвтонастройки : Режимы автоматической настройки учетной записи налогоплательщика
ИспользоватьСервисОнлайнПроверкиОтчетов : Булево
ПредназначенаДляДокументооборотаСФНС : Булево
ПредназначенаДляДокументооборотаСПФР : Булево
ПредназначенаДляДокументооборотаСФСГС : Булево
ИдентификаторСпецоператора : Строка
ИдентификаторАбонента : Строка
ИдентификаторСистемыОтправителяПФР : Строка
ИдентификаторСистемыОтправителяФСГС : Строка
ЯвляетсяУчетнойЗаписьюУполномоченногоПредставителя : Булево
ИННУполномоченногоПредставителя : Строка
КППУполномоченногоПредставителя : Строка
ПолноеНаименованиеУполномоченногоПредставителя : Строка
СтатусУчетнойЗаписи : (не используется) Статусы учетной записи документооборота
СпецоператорСвязи : (не используется) Операторы электронного документооборота\rОператоры электронного документооборота
ОтключитьАвтообмен : Булево
}
@enduml
