@startuml СценарииТоварногоПланирования
'!include templates.wsd
'..\include templates.wsd
class Справочник.СценарииТоварногоПланирования as "Сценарии товарного планирования" <<Справочники>>
{
..Реквизиты..
Валюта : Справочник.Валюта
Периодичность : Периодичность
ИспользоватьВПланированииЗакупок : Булево
ИспользоватьДляЗаказовПоставщику : Булево
ИспользоватьВПланированииПродаж : Булево
ИспользоватьВПланированииПроизводства : Булево
ИспользоватьВПланированииСборкиРазборки : Булево
ИспользоватьДляЗаказовНаСборкуРазборку : Булево
ПланЗакупокПланироватьПоСумме : Булево
ПланПродажПланироватьПоСумме : Булево
ОтображатьНомерПериода : Булево
Описание : Строка
ОтражаетсяВБюджетировании : Булево
СценарийБюджетирования : Справочник.Сценарии бюджетирования
ИспользоватьВПланированииПродажПоКатегориям : Булево
ИспользоватьДляЗаказовНаПроизводство : Булево
ИспользоватьДляЗаказовНаВнутреннееПотребление : Булево
ИспользоватьДляПланированияМатериалов : Булево
ИспользоватьРасчетПоСкоростиПродаж : Булево
ПолучатьДанныеПлановВСтатусе : Статусы планов
ПланированиеПоНазначениям : Булево
Календарь : Справочник.График работы
}
@enduml
