@startuml ОснованияДосрочногоНазначенияПенсии
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОснованияДосрочногоНазначенияПенсии as "Основания для досрочной пенсии" <<Справочники>>
{
..Реквизиты..
КодДляОтчетности2010 : Строка
КодДляОтчетности2015 : Строка
КодДляОтчетности2002 : Строка
}
@enduml
