@startuml ГруппыДоступа
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГруппыДоступа as "Группы доступа" <<Справочники>>
{
..Реквизиты..
Профиль : Справочник.Профиль групп доступа
Пользователь : Справочник.Внешний пользователь\rСправочник.Пользователь
Комментарий : Строка
Ответственный : Справочник.Пользователь
ОсновнаяГруппаДоступаПоставляемогоПрофиля : Булево
..Табличная часть \n Пользователи..
Пользователь : Справочник.Внешний пользователь\rСправочник.Пользователь\rСправочник.Группа внешних пользователей\r...
..Табличная часть \n ВидыДоступа..
ВидДоступа : Справочник.Статьи бюджетов\rСправочник.Вид номенклатуры\rСправочник.Номенклатура\r...
ВсеРазрешены : Булево
..Табличная часть \n ЗначенияДоступа..
ВидДоступа : Справочник.Статьи бюджетов\rСправочник.Вид номенклатуры\rСправочник.Номенклатура\r...
ЗначениеДоступа : Справочник.Статьи бюджетов\rСправочник.Вид номенклатуры\rСправочник.Номенклатура\r...
}
@enduml
