@startuml УченыеСтепени
'!include templates.wsd
'..\include templates.wsd
class Справочник.УченыеСтепени as "Ученые степени" <<Справочники>>
{
..Реквизиты..
ОтрасльНауки : Справочник.Отрасль науки
}
@enduml
