@startuml ГруппыДоступаПартнеров
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГруппыДоступаПартнеров as "Группы доступа партнеров" <<Справочники>>
{
..Реквизиты..
ГруппаДоступа : Справочник.Группа доступа партнеров
}
@enduml
