@startuml СеансыСвязиСКонтролирующимиОрганами
'!include templates.wsd
'..\include templates.wsd
class Справочник.СеансыСвязиСКонтролирующимиОрганами as "Сеансы связи с контролирующими органами" <<Справочники>>
{
..Реквизиты..
Начало : Дата
Окончание : Дата
ИнициаторСеанса : Инициаторы сеансов связи с контролирующими органами
УчетнаяЗапись : Справочник.Учетные записи документооборота
Успешно : Булево
..Табличная часть \n ПротоколСеанса..
Процесс : Строка
Результат : Строка
Описание : Строка
Начало : Дата
Окончание : Дата
}
@enduml
