@startuml ПараметрыИсчисляемогоСтраховогоСтажа
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПараметрыИсчисляемогоСтраховогоСтажа as "Доп. сведения для исчисления стажа" <<Справочники>>
{
..Реквизиты..
ИспользуетсяС2014Года : Булево
}
@enduml
