@startuml ЗначенияСвойствОбъектов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ЗначенияСвойствОбъектов as "Дополнительные значения" <<Справочники>>
{
..Реквизиты..
Вес : Число 10, 2
ПолноеНаименование : Строка
}
@enduml
