@startuml КатегорииЭксплуатации
'!include templates.wsd
'..\include templates.wsd
class Справочник.КатегорииЭксплуатации as "Категории эксплуатации" <<Справочники>>
{
..Реквизиты..
ИнвентарныйУчет : Булево
СпособПогашенияСтоимостиБУ : Способы погашения стоимости ТМЦ
СрокЭксплуатации : Число 5, 0
ОбъемНаработки : Число 15, 3
ЕдиницаИзмеренияНаработки : Справочник.Упаковка
СтатьяРасходов : Статья расходов
Описание : Строка
СчетУчета : Счет бухгалтерского учета
СчетЗабалансовогоУчета : Счет бухгалтерского учета
СпособПогашенияСтоимостиНУ : Способы погашения стоимости ТМЦ
}
@enduml
