@startuml УдалитьРегламентированныеОтчеты
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьРегламентированныеОтчеты as "(не используется) Регламентированные отчеты" <<Справочники>>
{
..Реквизиты..
ИсточникОтчета : Строка
Описание : Строка
Периоды : Хранилище значения
УдалитьНеПоказыватьВСписке : Булево
УдалитьВнешнийОтчетИспользовать : Булево
УдалитьВнешнийОтчетХранилище : Хранилище значения
УдалитьВнешнийОтчетВерсия : Строка
}
@enduml
