@startuml ОбщиеВидыРемонтов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОбщиеВидыРемонтов as "Общие виды ремонтов" <<Справочники>>
{
..Реквизиты..
СтатьяРасходов : Статья расходов
ЗаданаСтатьяРасходов : Булево
}
@enduml
