@startuml ОтправкиОтчетности
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОтправкиОтчетности as "Отправки отчетности" <<Справочники>>
{
..Реквизиты..
Отчет : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
ТипНаправления : Типы направлений сдачи отчетности
КодНаправления : Строка
ДатаОткрытия : Дата
ДатаОтправки : Дата
ДатаПоследнегоОбновления : Дата
ДатаЗакрытия : Дата
Статус : Статусы отправки отчетности
Идентификатор : Строка
Организация : Справочник.Организация
ДатаНачалаПериода : Дата
ДатаОкончанияПериода : Дата
ВидДокумента : Число 3, 0
ПредставлениеПериода : Строка
ВидОтчета : Справочник.Регламентированные отчеты
УдалитьВидОтчета : Справочник.(не используется) Регламентированные отчеты
..Табличная часть \n ПричиныОтказа..
Причина : Строка
Пояснение : Строка
}
@enduml
