@startuml ВариантыОтчетов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВариантыОтчетов as "Отчеты" <<Справочники>>
{
..Реквизиты..
Автор : Справочник.Внешний пользователь\rСправочник.Пользователь
ВидимостьПоУмолчанию : Булево
ВидимостьПоУмолчаниюПереопределена : Булево
ИнтерактивнаяПометкаУдаления : Булево
КлючВарианта : Строка
КлючевыеСлова : Строка
НаименованияПараметровИОтборов : Строка
НаименованияПолей : Строка
Настройки : Хранилище значения
Описание : Строка
Отчет : Справочник.Идентификатор объекта метаданных расширения\rСтрока\rСправочник.Дополнительный отчет или обработка\r...
Пользовательский : Булево
ПредопределенныйВариант : Справочник.Предопределенный вариант отчета\rСправочник.Предопределенный вариант отчета
ТипОтчета : Типы отчетов
ТолькоДляАвтора : Булево
УдалитьКлючОбъекта : Строка
УдалитьПредставлениеОбъекта : Строка
ХешНастроек : Строка
..Табличная часть \n Размещение..
Использование : Булево
Подсистема : Справочник.Идентификатор объекта метаданных расширения\rСправочник.Идентификатор объекта метаданных
Важный : Булево
СмТакже : Булево
УдалитьПредопределенная : Булево
УдалитьНазвание : Строка
УдалитьПодсистема : Строка
..Табличная часть \n УдалитьИсключенияБыстрогоДоступа..
УдалитьПользователь : Справочник.Пользователь
}
@enduml
