@startuml ПравилаПолученияФактаПоПоказателямБюджетов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПравилаПолученияФактаПоПоказателямБюджетов as "Правила получения фактических данных по показателям бюджетов" <<Справочники>>
{
..Реквизиты..
ТипИтога : Типы итогов монетарных показателей
КомпоновщикНастроек : Хранилище значения
ПредставлениеОтбора : Строка
СхемаИсточникаДанных : Хранилище значения
РасширеныйРежимНастройкиЗаполненияАналитики : Булево
ВыражениеЗаполненияАналитики1 : Строка
ВыражениеЗаполненияАналитики2 : Строка
ВыражениеЗаполненияАналитики3 : Строка
ВыражениеЗаполненияАналитики4 : Строка
ВыражениеЗаполненияАналитики5 : Строка
ВыражениеЗаполненияАналитики6 : Строка
ЗаполнятьУказаннымЗначениемАналитику1 : Булево
ЗаполнятьУказаннымЗначениемАналитику2 : Булево
ЗаполнятьУказаннымЗначениемАналитику3 : Булево
ЗаполнятьУказаннымЗначениемАналитику4 : Булево
ЗаполнятьУказаннымЗначениемАналитику5 : Булево
ЗаполнятьУказаннымЗначениемАналитику6 : Булево
ЗначениеАналитики1 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ЗначениеАналитики2 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ЗначениеАналитики3 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ЗначениеАналитики4 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ЗначениеАналитики5 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ЗначениеАналитики6 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ПоказательБюджетов : Справочник.Показатели бюджетов
ИсточникДанных : Международный план счетов\rСчет бухгалтерского учета\rСтатья актива/пассива\r...
РазделИсточникаДанных : Разделы источников данных бюджетирования
ТипПравила : Тип правила получения фактических данных бюджетирования
Коэффициент : Число 5, 0
ХешНастроек : Строка
ХешСхемыКомпоновкиДанных : Строка
УдалитьХешиПересчитаны_2_4_1 : Булево
Комментарий : Строка
}
@enduml
