@startuml СерииНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Справочник.СерииНоменклатуры as "Серии номенклатуры" <<Справочники>>
{
..Реквизиты..
ГоденДо : Дата
ВидНоменклатуры : Справочник.Вид номенклатуры
Номер : Строка
НомерКиЗГИСМ : Строка
RFIDTID : Строка
RFIDUser : Строка
RFIDEPC : Строка
EPCGTIN : Строка
RFIDМеткаНеЧитаемая : Булево
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
