@startuml ОснованияУвольнения
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОснованияУвольнения as "Основания увольнения" <<Справочники>>
{
..Реквизиты..
ТекстОснования : Строка
УдалитьИдентификаторОбъекта : Строка
}
@enduml
