@startuml УдалитьВидыОбщественноПолезнойДеятельностиСЗВК
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьВидыОбщественноПолезнойДеятельностиСЗВК as "(не используется) Виды деятельности (СЗВ-К)" <<Справочники>>
{
}
@enduml
