@startuml ТипыСобытийСПАРКРиски
'!include templates.wsd
'..\include templates.wsd
class Справочник.ТипыСобытийСПАРКРиски as "Типы событий 1СПАРК Риски" <<Справочники>>
{
..Реквизиты..
Название : Строка
Описание : Строка
Критичное : Булево
Идентификатор : Уникальный идентификатор
}
@enduml
