@startuml СпособыОбеспеченияПотребностей
'!include templates.wsd
'..\include templates.wsd
class Справочник.СпособыОбеспеченияПотребностей as "Способы обеспечения потребностей" <<Справочники>>
{
..Реквизиты..
ИсточникОбеспеченияПотребностей : Справочник.Партнер\rСправочник.Склад (складская территория)
Организация : Справочник.Организация
Соглашение : Справочник.Соглашение об условиях закупок
ТипОбеспечения : Типы обеспечения
ВидЦеныПоставщика : Справочник.Вид цены поставщика
Календарь : Справочник.График работы
СрокИсполненияЗаказа : Число 10, 0
ДлительностьВДнях : Число 10, 0
ОбеспечиваемыйПериод : Число 10, 0
Подразделение : Справочник.Подразделение
ДатаСледующейПоставки : Дата
ПлановаяДатаПоставки : Дата
ФормироватьПлановыеЗаказы : Булево
ПлановаяДатаЗаказа : Дата
ГарантированныйСрокОтгрузки : Число 10, 0
}
@enduml
