@startuml ЗарплатныеПроекты
'!include templates.wsd
'..\include templates.wsd
class Справочник.ЗарплатныеПроекты as "Зарплатные проекты" <<Справочники>>
{
..Реквизиты..
Банк : Справочник.Банк
Валюта : Справочник.Валюта
ДатаДоговора : Дата
ИспользоватьЭлектронныйДокументооборотСБанком : Булево
КодировкаФайла : Кодировка файлов обмена по зарплатному проекту
НомерДоговора : Строка
Организация : Справочник.Организация
ОтделениеБанка : Строка
РасчетныйСчет : Строка
ФилиалОтделенияБанка : Строка
ФорматФайла : Форматы файлов обмена по зарплатному проекту
УдалитьБанк : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n СистемыРасчетовПоБанковскимКартам..
СистемаРасчетовПоБанковскимКартам : Строка
}
@enduml
