@startuml ТерриторииВыполненияРабот
'!include templates.wsd
'..\include templates.wsd
class Справочник.ТерриторииВыполненияРабот as "Территории" <<Справочники>>
{
..Реквизиты..
РайонныйКоэффициент : Число 3, 2
РайонныйКоэффициентРФ : Число 3, 2
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
СоответствуетСудамЗарегистрированнымВРоссийскомМеждународномРеестреСудов : Булево
УдалитьКоличествоДополнительныхДнейОтпускаВГод : Число 2, 0
ПроцентСевернойНадбавки : Число 5, 2
..Табличная часть \n ЗависимыеСтажи..
ВидСтажа : Справочник.Вид стажа
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
