@startuml ПриоритетыОплаты
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПриоритетыОплаты as "Приоритеты оплаты" <<Справочники>>
{
..Реквизиты..
РеквизитДопУпорядочивания : Число 5, 0
Цвет : Хранилище значения
}
@enduml
