@startuml ГруппыИсполнителейЗадач
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГруппыИсполнителейЗадач as "Группы исполнителей задач" <<Справочники>>
{
..Реквизиты..
РольИсполнителя : Справочник.Роль исполнителя
ОсновнойОбъектАдресации : Справочник.Организация\rСправочник.Подразделение\rСправочник.Склад (складская территория)
ДополнительныйОбъектАдресации : Справочник.Организация\rСправочник.Подразделение\rСправочник.Склад (складская территория)
}
@enduml
