@startuml ГруппыАналитическогоУчетаНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГруппыАналитическогоУчетаНоменклатуры as "Группы аналитического учета номенклатуры" <<Справочники>>
{
..Реквизиты..
Описание : Строка
}
@enduml
