@startuml ПредопределенныеВариантыОтчетовРасширений
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПредопределенныеВариантыОтчетовРасширений as "Предопределенные варианты отчетов расширений" <<Справочники>>
{
..Реквизиты..
Отчет : Справочник.Идентификатор объекта метаданных расширения
КлючВарианта : Строка
Включен : Булево
ГруппироватьПоОтчету : Булево
ВидимостьПоУмолчанию : Булево
Описание : Строка
ХешНастроек : Строка
НаименованияПолей : Строка
НаименованияПараметровИОтборов : Строка
КлючевыеСлова : Строка
КлючЗамеров : Строка
..Табличная часть \n Размещение..
Подсистема : Справочник.Идентификатор объекта метаданных расширения\rСправочник.Идентификатор объекта метаданных
Важный : Булево
СмТакже : Булево
}
@enduml
