@startuml УчетныеПолитики
'!include templates.wsd
'..\include templates.wsd
class Справочник.УчетныеПолитики as "Учетные политики" <<Справочники>>
{
..Реквизиты..
Комментарий : Строка
Описание : Хранилище значения
СчетУчетаДоходов : Международный план счетов
СчетУчетаРасходов : Международный план счетов
СчетУчетаНераспределеннойПрибылиУбытка : Международный план счетов
ДоходыКР : Международный план счетов
СтатьяДоходовКР : Статьи доходов
РасходыКР : Международный план счетов
СтатьяРасходовКР : Статья расходов
ДоходыОтРазницПриПересчетеВП : Международный план счетов
СтатьяДоходовОтРазницПересчета : Статьи доходов
РасходыОтРазницПриПересчетеВП : Международный план счетов
СтатьяРасходовОтРазницПересчета : Статья расходов
..Табличная часть \n СчетаДоходов..
Счет : Международный план счетов
..Табличная часть \n СчетаРасходов..
Счет : Международный план счетов
..Табличная часть \n СчетаПрибылейУбытков..
Счет : Международный план счетов
..Табличная часть \n ИсключитьИзПересчетаВП..
Счет : Международный план счетов
}
@enduml
