@startuml ОтчетОператораСистемыПлатонПрисоединенныеФайлы
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОтчетОператораСистемыПлатонПрисоединенныеФайлы as "Присоединенные файлы (Отчет оператора системы "Платон")" <<Справочники>>
{
..Реквизиты..
Автор : Справочник.Пользователь
ВладелецФайла : Документ.Отчет оператора системы "Платон"
ДатаЗаема : Дата
ДатаМодификацииУниверсальная : Дата
ДатаСоздания : Дата
Зашифрован : Булево
Изменил : Справочник.Пользователь
ИндексКартинки : Число 10, 0
Описание : Строка
ПодписанЭП : Булево
ПутьКФайлу : Строка
Размер : Число 10, 0
Расширение : Строка
Редактирует : Справочник.Пользователь
СтатусИзвлеченияТекста : Статусы извлечения текста файлов
ТекстХранилище : Хранилище значения
ТипХраненияФайла : Типы хранения файлов
Том : Справочник.Том хранения файлов
ФайлХранилище : Хранилище значения
ХранитьВерсии : Булево
}
@enduml
