@startuml КлассификаторУслугНаселению
'!include templates.wsd
'..\include templates.wsd
class Справочник.КлассификаторУслугНаселению as "Классификатор услуг населению (ОКУН)" <<Справочники>>
{
..Реквизиты..
НаименованиеПолное : Строка
}
@enduml
