@startuml СоответствияОборотовМеждународногоУчета
'!include templates.wsd
'..\include templates.wsd
class Справочник.СоответствияОборотовМеждународногоУчета as "Соответствия оборотов международного учета" <<Справочники>>
{
..Реквизиты..
СчетРеглУчетаДт : Счет бухгалтерского учета
СчетРеглУчетаКт : Счет бухгалтерского учета
ПредставлениеОтбора : Строка
ДополнительныйОтбор : Хранилище значения
СчетМеждународногоУчетаДт : Международный план счетов
СчетМеждународногоУчетаКт : Международный план счетов
УстановленДополнительныйОтбор : Булево
ВариантСовместногоПрименения : Варианты совместного применения шаблонов проводок
РеквизитДопУпорядочивания : Число 3, 0
РучноеУточнениеПроводки : Булево
НеОтражаетсяВМеждународномУчете : Булево
..Табличная часть \n НастройкиЗаполненияСубконто..
ПоложениеСубконто : Строка
ВидСубконто : Виды субконто международные
ЗаполнятьИзИсточника : Булево
УказанноеЗначение : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСтатья расходов\r...
Выражение : Строка
}
@enduml
