@startuml Назначения
'!include templates.wsd
'..\include templates.wsd
class Справочник.Назначения as "Назначения" <<Справочники>>
{
..Реквизиты..
Заказ : Документ.Этап производства\rДокумент.Заказ на производство\rДокумент.Заказ материалов в производство\r...
НаправлениеДеятельности : Справочник.Направление деятельности
Партнер : Справочник.Партнер
Договор : Справочник.Договор с контрагентом
ТипНазначения : Типы назначений
КонтролироватьТолькоНаличие : Булево
ДвиженияПоСкладскимРегистрам : Булево
}
@enduml
