@startuml ВерсииМобильныхПриложений
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВерсииМобильныхПриложений as "Версии мобильных приложений" <<Справочники>>
{
..Реквизиты..
МобильноеПриложение : Строка
ИспользуемыеМетаданные : Строка
ПараметрыОбмена : Хранилище значения
}
@enduml
