@startuml РолиПартнеровВСделкахИПроектах
'!include templates.wsd
'..\include templates.wsd
class Справочник.РолиПартнеровВСделкахИПроектах as "Роли партнеров в сделках и проектах" <<Справочники>>
{
..Реквизиты..
Описание : Строка
}
@enduml
