@startuml ПричиныОтменыЗаказовПоставщикам
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПричиныОтменыЗаказовПоставщикам as "Причины отмены заказов поставщикам" <<Справочники>>
{
..Реквизиты..
Описание : Строка
ИнициаторОтменыЗаказовПоставщикам : Инициатор отмены заказов поставщикам
}
@enduml
