@startuml УдалитьВидыДоходовНДФЛ
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьВидыДоходовНДФЛ as "(не используется) Виды доходов НДФЛ" <<Справочники>>
{
..Реквизиты..
СтавкаНалогообложенияРезидента : НДФЛ ставки налогообложения резидента
НеОблагаетсяУНалоговогоАгента : Булево
КодПрименяемыйВНалоговойОтчетностиС2010Года : Строка
ВычетРассчитываетсяАвтоматически : Булево
ВычетПоУмолчанию : Справочник.(не используется) Виды вычетов НДФЛ
ИмеетЕдинственныйВычет : Булево
СоответствуетОплатеТруда : Булево
}
@enduml
