@startuml Валюты
'!include templates.wsd
'..\include templates.wsd
class Справочник.Валюты as "Валюты" <<Справочники>>
{
..Реквизиты..
ЗагружаетсяИзИнтернета : Булево
НаименованиеПолное : Строка
Наценка : Число 10, 2
ОсновнаяВалюта : Справочник.Валюта
ПараметрыПрописи : Строка
ФормулаРасчетаКурса : Строка
СпособУстановкиКурса : Способы установки курса валюты
}
@enduml
