@startuml ТипыИнформацииИнформационногоЦентра
'!include templates.wsd
'..\include templates.wsd
class Справочник.ТипыИнформацииИнформационногоЦентра as "Типы информации информационного центра" <<Справочники>>
{
}
@enduml
