@startuml ГруппыНМАМеждународныйУчет
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГруппыНМАМеждународныйУчет as "Группы НМА (международный учет)" <<Справочники>>
{
..Реквизиты..
ПериодичностьОценки : Число 10, 0
ПорядокУчета : Порядок учета стоимости внеоборотных активов
}
@enduml
