@startuml ВидыЗапасов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыЗапасов as "Виды запасов" <<Справочники>>
{
..Реквизиты..
Организация : Справочник.Организация
ТипЗапасов : Типы запасов
НалогообложениеНДС : Типы налогообложения НДС
ВладелецТовара : Справочник.Организация\rСправочник.Партнер
Соглашение : Справочник.Соглашение об условиях закупок
Валюта : Справочник.Валюта
РеализацияЗапасовДругойОрганизации : Булево
ВидЗапасовВладельца : Справочник.Вид запасов
СпособПередачиТоваров : Способы передачи товаров
УстарелоПоставщик : Справочник.Организация\rСправочник.Партнер
УстарелоПредназначение : Типы предназначения видов запасов
УстарелоПодразделение : Справочник.Подразделение
УстарелоМенеджер : Справочник.Пользователь
УстарелоСделка : Справочник.Сделка с клиентом
ГруппаФинансовогоУчета : Справочник.Группа финансового учета номенклатуры
Контрагент : Справочник.Организация\rСправочник.Контрагент
Договор : Справочник.Договор между организациями\rСправочник.Договор с контрагентом
УстарелоНазначение : Справочник.Назначение
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
ВидЦены : Справочник.Вид цены поставщика
ЭтоДубль : Булево
Устаревший : Булево
}
@enduml
