@startuml ВидыТарифовСтраховыхВзносов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыТарифовСтраховыхВзносов as "Виды тарифов страховых взносов" <<Справочники>>
{
..Реквизиты..
КодФНС : Строка
КодПФР2011 : Строка
КодФСС2011 : Строка
КодПФР2012 : Строка
КодФСС2012 : Строка
ПрименяетсяПоОтдельнымДоходам : Булево
РеквизитДопУпорядочивания : Число 5, 0
УдалитьИдентификаторОбъекта : Строка
}
@enduml
