@startuml Приоритеты
'!include templates.wsd
'..\include templates.wsd
class Справочник.Приоритеты as "Приоритеты" <<Справочники>>
{
..Реквизиты..
РеквизитДопУпорядочивания : Число 5, 0
Цвет : Хранилище значения
}
@enduml
