@startuml ТипоразмерыЯчеек
'!include templates.wsd
'..\include templates.wsd
class Справочник.ТипоразмерыЯчеек as "Типоразмеры ячеек" <<Справочники>>
{
..Реквизиты..
Высота : Число 15, 3
ВысотаЕдиницаИзмерения : Справочник.Упаковка
Глубина : Число 15, 3
ГлубинаЕдиницаИзмерения : Справочник.Упаковка
ВесЕдиницаИзмерения : Справочник.Упаковка
Грузоподъемность : Число 15, 3
НеОграниченаПоГрузоподъемности : Булево
НеОграниченаПоРазмерам : Булево
Объем : Число 18, 6
ОбъемЕдиницаИзмерения : Справочник.Упаковка
Ширина : Число 15, 3
ШиринаЕдиницаИзмерения : Справочник.Упаковка
}
@enduml
