@startuml Кассы
'!include templates.wsd
'..\include templates.wsd
class Справочник.Кассы as "Кассы" <<Справочники>>
{
..Реквизиты..
КассоваяКнига : Справочник.Кассовая книга
ВалютаДенежныхСредств : Справочник.Валюта
Подразделение : Справочник.Подразделение
РазрешитьПлатежиБезУказанияЗаявок : Булево
СрокИнкассации : Число 1, 0
ГруппаФинансовогоУчета : Справочник.Группа финансового учета денежных средств
ЭтоКассаОбособленногоПодразделения : Булево
СчетУчета : Счет бухгалтерского учета
НаправлениеДеятельности : Справочник.Направление деятельности
..Табличная часть \n ПолучателиПлатежейПриПеремещенииДС..
ПолучательПлатежа : Справочник.Касса
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
