@startuml РолиКонтактныхЛицПартнеров
'!include templates.wsd
'..\include templates.wsd
class Справочник.РолиКонтактныхЛицПартнеров as "Роли контактных лиц " <<Справочники>>
{
..Реквизиты..
Описание : Строка
}
@enduml
