@startuml СертификатыКлючейЭлектроннойПодписиИШифрования
'!include templates.wsd
'..\include templates.wsd
class Справочник.СертификатыКлючейЭлектроннойПодписиИШифрования as "Сертификаты ключей электронной подписи и шифрования" <<Справочники>>
{
..Реквизиты..
КомуВыдан : Строка
Фирма : Строка
Фамилия : Строка
Имя : Строка
Отчество : Строка
Должность : Строка
КемВыдан : Строка
ДействителенДо : Дата
Подписание : Булево
Шифрование : Булево
Отпечаток : Строка
ДанныеСертификата : Хранилище значения
Программа : Справочник.Программа электронной подписи и шифрования
Отозван : Булево
УсиленнаяЗащитаЗакрытогоКлюча : Булево
Организация : Справочник.Организация
Пользователь : Справочник.Пользователь
ПользовательОповещенОСрокеДействия : Булево
Добавил : Справочник.Пользователь
СостояниеЗаявления : Состояния заявления на выпуск сертификата
СодержаниеЗаявления : Хранилище значения
}
@enduml
