@startuml СообщенияОбластейДанных
'!include templates.wsd
'..\include templates.wsd
class Справочник.СообщенияОбластейДанных as "Сообщения областей данных" <<Справочники>>
{
..Реквизиты..
ТелоСообщения : Хранилище значения
Отправитель : Конечная точка
Получатель : Конечная точка
Заблокировано : Булево
КоличествоПопытокОбработкиСообщения : Число 2, 0
ПодробноеПредставлениеОшибки : Строка
ЭтоБыстроеСообщение : Булево
}
@enduml
