@startuml КомплектыОтчетностиПерсучета
'!include templates.wsd
'..\include templates.wsd
class Справочник.КомплектыОтчетностиПерсучета as "Комплекты отчетности персонифицированного учета" <<Справочники>>
{
..Реквизиты..
Организация : Справочник.Организация
ОтчетныйПериод : Дата
ПериодФормирования : Дата
НомерКомплекта : Число 2, 0
СостояниеКомплекта : Состояние комплекта отчетности персучета
ОписьПачекСЗВ : Документ.Опись сведений АДВ-6-2
ВедомостьУплатыАДВ11 : Документ.Ведомость уплаты взносов АДВ-11
РСВ_1 : Документ.Регламентированный отчет
АдресФайлаВыгрузкиРСВ : Строка
ИмяФайлаВыгрузкиРСВ : Строка
НулевойКомплект : Булево
СоставКомплектаПредставление : Строка
КорректирующаяФормаРСВ_1 : Булево
СодержитТолькоКорректирующиеФормы : Булево
СпециальныйДокумент2015года : Булево
..Табличная часть \n СписокПачекСЗВ..
ПачкаДокументов : Документ.Пачка документов СЗВ-6-4\rДокумент.Пачка документов СЗВ-6-1\rДокумент.Реестр СЗВ-6-2\r...
..Табличная часть \n СписокПачекСЗВ6_3..
ПачкаДокументов : Документ.Пачка документов СЗВ-6-3
..Табличная часть \n КорректируемыеПериоды..
Период : Дата
ВариантФормирования : Варианты формирования корректирующих сведений в ПФР
НулевойКомплектСведений : Справочник.Комплект отчетности персонифицированного учета
}
@enduml
