@startuml ЗванияГражданскогоВоинскогоУчета
'!include templates.wsd
'..\include templates.wsd
class Справочник.ЗванияГражданскогоВоинскогоУчета as "Воинские звания" <<Справочники>>
{
..Реквизиты..
ОбщевойсковоеЗвание : Классификатор воинских званий
РеквизитДопУпорядочивания : Число 5, 0
Состав : Справочник.Состав военнослужащих
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
