@startuml БизнесРегионы
'!include templates.wsd
'..\include templates.wsd
class Справочник.БизнесРегионы as "Бизнес-регионы" <<Справочники>>
{
..Реквизиты..
ОсновнойМенеджер : Справочник.Пользователь
ЗначениеГеографическогоРегиона : Строка\rЧисло 25, 0
ГеографическийРегион : Строка
СезоннаяГруппа : Справочник.Сезонные группы бизнес-регионов
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
