@startuml ВидыРабочихЦентров
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыРабочихЦентров as "Виды рабочих центров" <<Справочники>>
{
..Реквизиты..
Подразделение : Справочник.Подразделение
ПланироватьРаботу : Булево
МинимальныйЗначимыйБуфер : Число 2, 0
УчитыватьДоступностьПоГрафикуРаботы : Булево
Календарь : Справочник.График работы
МаксимальнаяДоступностьРЦ : Число 7, 0
ЕдиницаИзмеренияДоступностиРЦ : Единицы измерения времени
ПериодОжидания : Число 5, 0
ИспользуютсяВариантыНаладки : Булево
ЕдиницаВремениПереналадки : Единицы измерения времени
Описание : Строка
РезервДоступности : Число 3, 0
ПараллельнаяЗагрузка : Булево
ЕдиницаИзмеренияЗагрузки : Строка
ВариантЗагрузки : Варианты загрузки рабочих центров
ВремяРаботы : Число 10, 1
ЕдиницаИзмерения : Единицы измерения времени
ПланироватьРаботуРабочихЦентров : Булево
КоличествоРабочихЦентров : Число 6, 1
ВводитьДоступностьДляВидаРЦ : Булево
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
