@startuml НаправленияСдачиОтчетности
'!include templates.wsd
'..\include templates.wsd
class Справочник.НаправленияСдачиОтчетности as "Направления сдачи отчетности" <<Справочники>>
{
..Реквизиты..
Организация : Строка
ТипНаправления : Типы направлений сдачи отчетности
Направление : Строка
ДатаАктуализации : Дата
}
@enduml
