@startuml ПрочиеРасходы
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПрочиеРасходы as "Прочие расходы" <<Справочники>>
{
..Реквизиты..
РеквизитДопУпорядочивания : Число 5, 0
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
