@startuml Сайты
'!include templates.wsd
'..\include templates.wsd
class Справочник.Сайты as "Сайты" <<Справочники>>
{
..Реквизиты..
АдресСайта : Строка
Организация : Справочник.Организация
ИмяПользователя : Строка
ТипСайта : Число 2, 0
URLАдминЗоны : Строка
}
@enduml
