@startuml ПравилаОбменаСПодключаемымОборудованиемOffline
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПравилаОбменаСПодключаемымОборудованиемOffline as "Правила обмена с подключаемым оборудованием offline" <<Справочники>>
{
..Реквизиты..
Склад : Справочник.Склад (складская территория)
МаксимальныйКод : Число 15, 0
НастройкиКомпоновкиДанных : Хранилище значения
ТипПодключаемогоОборудования : Типы подключаемого оборудования
ЕдиницаИзмеренияВеса : Справочник.Упаковка
ВыгружатьИзменения : Булево
}
@enduml
