@startuml ПричиныЗадержкиВыполненияЭтаповПроизводства
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПричиныЗадержкиВыполненияЭтаповПроизводства as "Причины задержки выполнения этапов производства" <<Справочники>>
{
..Реквизиты..
Описание : Строка
}
@enduml
