@startuml Сценарии
'!include templates.wsd
'..\include templates.wsd
class Справочник.Сценарии as "Сценарии бюджетирования" <<Справочники>>
{
..Реквизиты..
Валюта : Справочник.Валюта
ИспользоватьКурсыДругогоСценария : Булево
СценарийКурсов : Справочник.Сценарии бюджетирования
ТребоватьУказанияКурсовДляКаждогоПериода : Булево
}
@enduml
