@startuml СценарииПооперационногоПланирования
'!include templates.wsd
'..\include templates.wsd
class Справочник.СценарииПооперационногоПланирования as "Сценарии пооперационного планирования" <<Справочники>>
{
..Табличная часть \n РабочиеЦентрыДобавить..
ВидРабочегоЦентра : Справочник.Вид рабочего центра
Количество : Число 3, 0
Аналог : Справочник.Рабочий центр
..Табличная часть \n РабочиеЦентрыИсключить..
ВидРабочегоЦентра : Справочник.Вид рабочего центра
РабочийЦентр : Справочник.Рабочий центр
..Табличная часть \n ГрафикиРаботы..
Подразделение : Справочник.Подразделение
ВидРабочегоЦентра : Справочник.Вид рабочего центра
РабочийЦентр : Справочник.Рабочий центр
График : Справочник.График работы
}
@enduml
