@startuml ПрофилиКлючевыхОпераций
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПрофилиКлючевыхОпераций as "Профили ключевых операций" <<Справочники>>
{
..Табличная часть \n КлючевыеОперацииПрофиля..
КлючеваяОперация : Справочник.Ключевая операция
ЦелевоеВремя : Число 5, 1
Приоритет : Число 5, 0
}
@enduml
