@startuml ОчередьЗаданийОбластейДанных
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОчередьЗаданийОбластейДанных as "Очередь заданий областей данных" <<Справочники>>
{
..Реквизиты..
Использование : Булево
ЗапланированныйМоментЗапуска : Дата
СостояниеЗадания : Состояния заданий
ИсполняющееФоновоеЗадание : Уникальный идентификатор
ЭксклюзивноеВыполнение : Булево
Шаблон : Справочник.Шаблон задания
НомерПопытки : Число 3, 0
ИмяМетода : Строка
Параметры : Хранилище значения
ДатаНачалаПоследнегоЗапуска : Дата
ДатаЗавершенияПоследнегоЗапуска : Дата
Ключ : Строка
ИнтервалПовтораПриАварийномЗавершении : Число 10, 0
Расписание : Хранилище значения
КоличествоПовторовПриАварийномЗавершении : Число 10, 0
}
@enduml
