@startuml УдалитьОснованияИсчисляемогоСтраховогоСтажа
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьОснованияИсчисляемогоСтраховогоСтажа as "(не используется) Основания для исчисления стажа" <<Справочники>>
{
}
@enduml
