@startuml ВариантыГрафиковКредитовИДепозитов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВариантыГрафиковКредитовИДепозитов as "Варианты графиков" <<Справочники>>
{
..Реквизиты..
АвторИзменения : Справочник.Пользователь
ДатаИзменения : Дата
ДатаПервогоТранша : Дата
ДатаПоследнегоПлатежа : Дата
Используется : Булево
Комментарий : Строка
СрокДней : Число 5, 0
СрокМес : Число 5, 0
СуммаКомиссии : Число 15, 2
СуммаПроцентов : Число 15, 2
СуммаТраншей : Число 15, 2
Утвержден : Булево
}
@enduml
