@startuml УдалитьОсобыеУсловияТрудаПФР
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьОсобыеУсловияТрудаПФР as "(не используется) Особые условия труда ПФР" <<Справочники>>
{
}
@enduml
