@startuml РассылкиОтчетов
'!include templates.wsd
'..\include templates.wsd
class Справочник.РассылкиОтчетов as "Рассылки отчетов" <<Справочники>>
{
..Реквизиты..
FTPКаталог : Строка
FTPЛогин : Строка
FTPПассивноеСоединение : Булево
FTPПорт : Число 5, 0
FTPСервер : Строка
Автор : Справочник.Пользователь
АдресОтвета : Строка
Архивировать : Булево
ВидПочтовогоАдресаПолучателей : Справочник.Вид контактной информации
ВыполнятьПоРасписанию : Булево
ИмяАрхива : Строка
ИспользоватьFTPРесурс : Булево
ИспользоватьПапку : Булево
ИспользоватьСетевойКаталог : Булево
ИспользоватьЭлектроннуюПочту : Булево
КартинкиПисьмаВФорматеHTML : Хранилище значения
Личная : Булево
Папка : Справочник.Папка
ПериодичностьРасписания : Периодичности расписаний рассылок отчетов
Персонализирована : Булево
ПисьмоВФорматеHTML : Булево
Подготовлена : Булево
РегламентноеЗадание : Уникальный идентификатор
СетевойКаталогLinux : Строка
СетевойКаталогWindows : Строка
СкрытыеКопии : Булево
ТекстПисьма : Строка
ТекстПисьмаВФорматеHTML : Строка
ТемаПисьма : Строка
ТипПолучателейРассылки : Справочник.Идентификатор объекта метаданных
ТолькоУведомить : Булево
ТранслитерироватьИменаФайлов : Булево
УдалитьFTPПароль : Строка
УдалитьПарольАрхива : Строка
УчетнаяЗапись : Справочник.Учетная запись электронной почты
..Табличная часть \n Отчеты..
Отчет : Справочник.Дополнительный отчет или обработка\rСправочник.Вариант отчета
ОтправлятьЕслиПустой : Булево
Настройки : Хранилище значения
..Табличная часть \n ФорматыОтчетов..
Отчет : Справочник.Дополнительный отчет или обработка\rСправочник.Вариант отчета
Формат : Форматы сохранения отчетов
..Табличная часть \n Получатели..
Получатель : Справочник.Организация\rСправочник.Пользователь\rСправочник.Группа пользователей\r...
Исключен : Булево
}
@enduml
