@startuml ВидыОтпусков
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыОтпусков as "Виды отпусков" <<Справочники>>
{
..Реквизиты..
ОтпускЯвляетсяЕжегодным : Булево
СпособРасчетаОтпуска : Способы расчета отпуска
ПредоставлятьОтпускВсемСотрудникам : Булево
КоличествоДнейВГод : Число 2, 0
НаименованиеПолное : Строка
ОтпускБезОплаты : Булево
УдалитьИдентификаторОбъекта : Строка
Недействителен : Булево
ОсновнойОтпуск : Булево
НакопительныйОтпуск : Булево
ХарактерЗависимостиДнейОтпуска : Характер зависимости количества дней отпуска
ВидСтажа : Справочник.Вид стажа
..Табличная часть \n ШкалаОценкиСтажа..
ВерхняяГраницаИнтервалаСтажа : Число 3, 0
КоличествоДнейВГод : Число 2, 0
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
