@startuml ПолныеПутиКФормам
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПолныеПутиКФормам as "Полные пути к формам" <<Справочники>>
{
..Реквизиты..
ПолныйПутьКФорме : Строка
Хеш : Строка
}
@enduml
