@startuml Партнеры
'!include templates.wsd
'..\include templates.wsd
class Справочник.Партнеры as "Партнеры" <<Справочники>>
{
..Реквизиты..
БизнесРегион : Справочник.Бизнес-регион
ГруппаДоступа : Справочник.Группа доступа партнеров
ДатаРегистрации : Дата
Клиент : Булево
Комментарий : Строка
Поставщик : Булево
НаименованиеПолное : Строка
ОсновнойМенеджер : Справочник.Пользователь
Конкурент : Булево
ПрочиеОтношения : Булево
ОбслуживаетсяТорговымиПредставителями : Булево
ДополнительнаяИнформация : Строка
Перевозчик : Булево
ШаблонЭтикетки : Справочник.Шаблон этикетки (ценника)
ЮрФизЛицо : Компания частное лицо
Пол : Пол физического лица
ДатаРождения : Дата
НазначениеПереработчика : Справочник.Назначение
ВариантОтправкиЭлектронногоЧека : Варианты отправки электронного чека покупателю
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n КонтактнаяИнформация..
Тип : Типы контактной информации
Вид : Справочник.Вид контактной информации
Представление : Строка
ЗначенияПолей : Строка
Страна : Строка
Регион : Строка
Город : Строка
АдресЭП : Строка
ДоменноеИмяСервера : Строка
НомерТелефона : Строка
НомерТелефонаБезКодов : Строка
ВидДляСписка : Справочник.Вид контактной информации
}
@enduml
