@startuml ИдентификаторыОбъектовРасширений
'!include templates.wsd
'..\include templates.wsd
class Справочник.ИдентификаторыОбъектовРасширений as "Идентификаторы объектов расширений" <<Справочники>>
{
..Реквизиты..
ПорядокКоллекции : Число 2, 0
Имя : Строка
Синоним : Строка
ПолноеИмя : Строка
ПолныйСиноним : Строка
БезДанных : Булево
ЗначениеПустойСсылки : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
КлючОбъектаМетаданных : Хранилище значения
НоваяСсылка : Справочник.Идентификатор объекта метаданных расширения
ИмяРасширения : Строка
ХешСуммаРасширения : Строка
}
@enduml
