@startuml УчетныеЗаписиДокументооборота
'!include templates.wsd
'..\include templates.wsd
class Справочник.УчетныеЗаписиДокументооборота as "Учетные записи документооборота" <<Справочники>>
{
..Реквизиты..
АдресЭлектроннойПочты : Строка
ДатаПодключения : Дата
ИдентификаторАбонента : Строка
ИдентификаторДокументооборота : Строка
ИдентификаторСистемыОтправителяПФР : Строка
ИдентификаторСистемыОтправителяФСГС : Строка
ИдентификаторСпецоператора : Строка
ИмяПользователяPOP3 : Строка
ИмяПользователяSMTP : Строка
ИННУполномоченногоПредставителя : Строка
ИспользоватьСервисОнлайнПроверкиОтчетов : Булево
ИспользуютсяСъемныеКлючевыеНосители : Булево
КППУполномоченногоПредставителя : Строка
ЛицензияДатаНачала : Дата
ЛицензияДатаОкончания : Дата
ЛицензияНаименование : Строка
ЛицензияТребуетсяНапоминаниеОбОкончанииСрокаДействия : Булево
НалоговыйОрган : Справочник.Налоговые органы
ЕстьОшибкиСменыМоделиХраненияКлючей : Булево
НеФормироватьПодтвержденияАвтоматически : Булево
ОбменНапрямую : Булево
ОбменНапрямуюСФСГС : Булево
ОтключитьАвтообмен : Булево
ПарольPOP3 : Строка
ПарольSMTP : Строка
ПолноеНаименованиеУполномоченногоПредставителя : Строка
ПортPOP3 : Число 5, 0
ПортSMTP : Число 5, 0
ПредназначенаДляДокументооборотаСПФР : Булево
ПредназначенаДляДокументооборотаСФНС : Булево
ПредназначенаДляДокументооборотаСФСГС : Булево
РежимАвтонастройки : Режимы автоматической настройки учетной записи налогоплательщика
СерверPOP3 : Строка
СерверSMTP : Строка
СерверДокументооборота : Справочник.Серверы документооборота
СертификатГлавногоБухгалтера : Строка
СертификатДляШифрования : Строка
СертификатРуководителя : Строка
СпецоператорСвязи : Операторы электронного документооборота
СтатусУчетнойЗаписи : Статусы учетной записи документооборота
ТелефонМобильныйДляАвторизации : Строка
ТребуетсяSMTPАутентификация : Булево
УдалитьАвтоматическоеОпределениеНабораПодписей : Булево
УдалитьИспользуетсяОбособленнымиПодразделениями : Булево
УдалитьНестандартныеТаймауты : Булево
УдалитьТаймаутНалоговогоОргана : Число 2, 0
УдалитьТаймаутНалогоплательщика : Число 2, 0
ЭлектроннаяПодписьВМоделиСервиса : Булево
ЯвляетсяУчетнойЗаписьюУполномоченногоПредставителя : Булево
..Табличная часть \n ПредыдущиеСертификаты..
Сертификат : Справочник.Сертификат 1С-Отчетности
}
@enduml
