@startuml ДрайверыОборудования
'!include templates.wsd
'..\include templates.wsd
class Справочник.ДрайверыОборудования as "Драйверы оборудования" <<Справочники>>
{
..Реквизиты..
ТипОборудования : Типы подключаемого оборудования
ИдентификаторОбъекта : Строка
ОбработчикДрайвера : Обработчики драйверов подключаемого оборудования
ПоставляетсяДистрибутивом : Булево
ЗагруженныйДрайвер : Хранилище значения
ИмяФайлаДрайвера : Строка
ИмяМакетаДрайвера : Строка
ВерсияДрайвера : Строка
СнятСПоддержки : Булево
}
@enduml
