@startuml Номенклатура
'!include templates.wsd
'..\include templates.wsd
class Справочник.Номенклатура as "Номенклатура" <<Справочники>>
{
..Реквизиты..
ЕдиницаИзмерения : Справочник.Упаковка
Артикул : Строка
ВариантОформленияПродажи : Варианты оформления продажи
ВесЕдиницаИзмерения : Справочник.Упаковка
ВесЗнаменатель : Число 15, 3
ВесИспользовать : Булево
ВесМожноУказыватьВДокументах : Булево
ВесЧислитель : Число 15, 3
ВестиУчетПоГТД : Булево
ВестиУчетСертификатовНоменклатуры : Булево
ВидАлкогольнойПродукции : Справочник.Вид алкогольной (спиртосодержащей) продукции
ВидНоменклатуры : Справочник.Вид номенклатуры
ГруппаДоступа : Справочник.Группа доступа номенклатуры
АлкогольнаяПродукция : Булево
НаименованиеПолное : Строка
ЕдиницаИзмеренияСрокаГодности : Единицы измерения времени
ЕстьТоварыДругогоКачества : Булево
ИмпортнаяАлкогольнаяПродукция : Булево
ДлинаЕдиницаИзмерения : Справочник.Упаковка
ДлинаЗнаменатель : Число 15, 3
ДлинаИспользовать : Булево
ДлинаМожноУказыватьВДокументах : Булево
ДлинаЧислитель : Число 15, 3
ИспользованиеХарактеристик : Варианты использования характеристик номенклатуры
ИспользоватьИндивидуальныйШаблонЦенника : Булево
ИспользоватьИндивидуальныйШаблонЭтикетки : Булево
ИспользоватьУпаковки : Булево
Качество : Градации качества
КодДляПоиска : Строка
Марка : Справочник.Марка (бренд)
НаборУпаковок : Справочник.Набор упаковок
ГруппаФинансовогоУчета : Справочник.Группа финансового учета номенклатуры
НоменклатураМногооборотнаяТара : Справочник.Номенклатура
ОбъемДАЛ : Число 18, 6
Описание : Строка
ПодакцизныйТовар : Булево
ПоставляетсяВМногооборотнойТаре : Булево
Производитель : Справочник.Производитель
ПроизводительИмпортерДляДекларацийАлко : Справочник.Контрагент
СкладскаяГруппа : Справочник.Складская группа номенклатуры
СрокГодности : Число 15, 0
СтавкаНДС : Ставки НДС
ТипНоменклатуры : Типы номенклатуры
ТоварнаяКатегория : Справочник.Товарные категории
ФайлКартинки : Справочник.Присоединенный файл (Номенклатура)
ФайлОписанияДляСайта : Справочник.Присоединенный файл (Номенклатура)
ОбъемЕдиницаИзмерения : Справочник.Упаковка
ОбъемЗнаменатель : Число 15, 3
ОбъемИспользовать : Булево
ОбъемМожноУказыватьВДокументах : Булево
ОбъемЧислитель : Число 15, 3
ХарактеристикаМногооборотнаяТара : Справочник.Характеристика номенклатуры
ПлощадьЕдиницаИзмерения : Справочник.Упаковка
ПлощадьЗнаменатель : Число 15, 3
СхемаОбеспечения : Справочник.Схема обеспечения
СпособОбеспеченияПотребностей : Справочник.Способ обеспечения потребностей
ПлощадьИспользовать : Булево
ПлощадьМожноУказыватьВДокументах : Булево
ПлощадьЧислитель : Число 15, 3
ЦеноваяГруппа : Справочник.Ценовая группа
ШаблонЦенника : Справочник.Шаблон этикетки (ценника)
ЕдиницаДляОтчетов : Справочник.Упаковка
КоэффициентЕдиницыДляОтчетов : Число 15, 3
ШаблонЭтикетки : Справочник.Шаблон этикетки (ценника)
СезоннаяГруппа : Справочник.Сезонные группы номенклатуры
КоллекцияНоменклатуры : Справочник.Коллекция (сезон)
Принципал : Справочник.Организация\rСправочник.Партнер
Контрагент : Справочник.Организация\rСправочник.Контрагент
РейтингПродаж : Справочник.Рейтинг продаж номенклатуры
ОбособленнаяЗакупкаПродажа : Булево
ГруппаАналитическогоУчета : Справочник.Группа аналитического учета номенклатуры
КодТНВЭД : Справочник.ТН ВЭД
КодОКВЭД : Справочник.ОКВЭД
КодОКП : Справочник.ОКП
ОблагаетсяНДПИПоПроцентнойСтавке : Булево
ВладелецСерий : Справочник.Вид номенклатуры
ВладелецХарактеристик : Справочник.Вид номенклатуры
ВладелецТоварныхКатегорий : Справочник.Вид номенклатуры
Крепость : Число 5, 3
ОсобенностьУчета : Особенности учета номенклатуры
ПродукцияМаркируемаяДляГИСМ : Булево
КиЗГИСМ : Булево
КиЗГИСМВид : Виды КиЗ
КиЗГИСМСпособВыпускаВОборот : Способы выпуска в оборот ГИСМ
КиЗГИСМGTIN : Строка
КиЗГИСМРазмер : Размеры КиЗ
УдалитьСырьевойТовар : Булево
АлкогольнаяПродукцияВоВскрытойТаре : Булево
КодРаздел7ДекларацииНДС : Справочник.Коды операций раздела 7 декларации по НДС
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n ДрагоценныеМатериалы..
ДрагоценныйМатериал : Справочник.Драгоценный материал
Количество : Число 15, 3
Расположение : Расположение драгоценных камней
Комментарий : Строка
}
@enduml
