@startuml ПрофилиГруппДоступа
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПрофилиГруппДоступа as "Профили групп доступа" <<Справочники>>
{
..Реквизиты..
ИдентификаторПоставляемыхДанных : Уникальный идентификатор
ПоставляемыйПрофильИзменен : Булево
Комментарий : Строка
..Табличная часть \n Роли..
Роль : Справочник.Идентификатор объекта метаданных расширения\rСправочник.Идентификатор объекта метаданных
УдалитьРоль : Строка
..Табличная часть \n ВидыДоступа..
ВидДоступа : Справочник.Статьи бюджетов\rСправочник.Вид номенклатуры\rСправочник.Номенклатура\r...
Предустановленный : Булево
ВсеРазрешены : Булево
..Табличная часть \n ЗначенияДоступа..
ВидДоступа : Справочник.Статьи бюджетов\rСправочник.Вид номенклатуры\rСправочник.Номенклатура\r...
ЗначениеДоступа : Справочник.Статьи бюджетов\rСправочник.Вид номенклатуры\rСправочник.Номенклатура\r...
..Табличная часть \n Назначение..
ТипПользователей : Справочник.Пользователь\rСправочник.Партнер\rСправочник.Контактное лицо
}
@enduml
