@startuml РегистрацииВНалоговомОргане
'!include templates.wsd
'..\include templates.wsd
class Справочник.РегистрацииВНалоговомОргане as "Регистрации в налоговом органе" <<Справочники>>
{
..Реквизиты..
Доверенность : Справочник.Доверенности налогоплательщика
ДокументПредставителя : Строка
КодПоОКТМО : Строка
КодПоОКАТО : Строка
ЦифровойИндексОбособленногоПодразделения : Число 5, 0
КПП : Строка
НаименованиеИФНС : Строка
НаименованиеОбособленногоПодразделения : Строка
Представитель : Справочник.Контрагент\rСправочник.Физическое лицо
УполномоченноеЛицоПредставителя : Строка
..Табличная часть \n КонтактнаяИнформация..
Тип : Типы контактной информации
Вид : Справочник.Вид контактной информации
Представление : Строка
ЗначенияПолей : Строка
Страна : Строка
Регион : Строка
Город : Строка
АдресЭП : Строка
ДоменноеИмяСервера : Строка
НомерТелефона : Строка
НомерТелефонаБезКодов : Строка
ВидДляСписка : Справочник.Вид контактной информации
}
@enduml
