@startuml ЭлементыФинансовыхОтчетов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ЭлементыФинансовыхОтчетов as "Элементы финансовых отчетов" <<Справочники>>
{
..Реквизиты..
ВидЭлемента : Виды элементов финансового отчета
НаименованиеДляПечати : Строка
ОбратныйЗнак : Булево
Комментарий : Строка
ДополнительныйОтбор : Хранилище значения
ЕстьНастройки : Булево
ЗначениеАналитики : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
СвязанныйЭлемент : Справочник.Элемент финансового отчета
..Табличная часть \n РеквизитыВидаЭлемента..
Реквизит : Реквизиты элементов финансовых отчетов
Значение : Справочник.Статьи бюджетов\rПредставление периода\rВиды субконто международные\r...
..Табличная часть \n ОперандыФормулы..
Идентификатор : Строка
Операнд : Справочник.Элемент финансового отчета
..Табличная часть \n ЭлементыТаблицы..
Строка : Справочник.Элемент финансового отчета
Колонка : Справочник.Элемент финансового отчета
Элемент : Справочник.Элемент финансового отчета
..Табличная часть \n ДополнительныеПоля..
Реквизит : Строка
Наименование : Строка
ВыводитьЗаголовок : Булево
ВОтдельнойКолонке : Булево
..Табличная часть \n ЭлементыОформления..
Оформление : Хранилище значения
Условие : Хранилище значения
ТипОформляемойОбласти : Типы оформляемых областей бюджетных отчетов
КлючЭлементаОформления : Уникальный идентификатор
..Табличная часть \n ОформляемыеСтроки..
ЭлементОтчета : Справочник.Элемент финансового отчета
КлючЭлементаОформления : Уникальный идентификатор
..Табличная часть \n ОформляемыеКолонки..
ЭлементОтчета : Справочник.Элемент финансового отчета
КлючЭлементаОформления : Уникальный идентификатор
..Табличная часть \n РасшифровкаПолейОтбораЭО..
ЭлементОтчета : Справочник.Элемент финансового отчета
КлючЭлементаОформления : Уникальный идентификатор
ИмяПоляОтбора : Строка
ИмяРесурса : Строка
..Табличная часть \n ИсточникиЗначений..
Источник : Справочник.Элемент финансового отчета
ДобавляемыеЗначенияДокумента : Булево
}
@enduml
