@startuml ПапкиФайлов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПапкиФайлов as "Папки" <<Справочники>>
{
..Реквизиты..
Описание : Строка
Ответственный : Справочник.Пользователь
ДатаСоздания : Дата
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
