@startuml ПодразделенияОрганизаций
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПодразделенияОрганизаций as "Подразделения организаций" <<Справочники>>
{
..Реквизиты..
РеквизитДопУпорядочивания : Число 5, 0
РайонныйКоэффициент : Число 3, 2
РайонныйКоэффициентРФ : Число 3, 2
ОбособленноеПодразделение : Булево
Сформировано : Булево
ДатаСоздания : Дата
Расформировано : Булево
ДатаРасформирования : Дата
ГоловнаяОрганизация : Справочник.Организация
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
СоответствуетСудамЗарегистрированнымВРоссийскомМеждународномРеестреСудов : Булево
РеквизитДопУпорядочиванияИерархического : Строка
УдалитьТерриториальныеУсловияПФР : Справочник.(не используется) Территориальные условия
ГрафикРаботыСотрудников : Справочник.График работы
КодОКВЭД : Строка
НаименованиеОКВЭД : Строка
ИмеетНомерТерриториальногоОрганаРосстата : Булево
НомерТерриториальногоОрганаРосстата : Строка
ПроцентСевернойНадбавки : Число 5, 2
УдалитьКоличествоДополнительныхДнейОтпускаВГод : Число 2, 0
КодОрганаФСГС : Строка
КодОКВЭД2 : Строка
НаименованиеОКВЭД2 : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n ЗависимыеСтажи..
ВидСтажа : Справочник.Вид стажа
}
@enduml
