@startuml ВидыВычетовНДФЛ
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыВычетовНДФЛ as "Виды вычетов НДФЛ" <<Справочники>>
{
..Реквизиты..
КодПрименяемыйВНалоговойОтчетностиС2011Года : Строка
КодПрименяемыйВНалоговойОтчетностиС2010Года : Строка
ВычетКДоходу : Булево
ГруппаВычета : Группы вычетов по НДФЛ
НеПредоставляетсяНерезидентам : Булево
КодПрименяемыйВНалоговойОтчетностиС2015Года : Строка
ПолноеНаименование : Строка
КодПрименяемыйВНалоговойОтчетностиС2016Года : Строка
}
@enduml
