@startuml СделкиСКлиентами
'!include templates.wsd
'..\include templates.wsd
class Справочник.СделкиСКлиентами as "Сделки с клиентами" <<Справочники>>
{
..Реквизиты..
ВалютаПервичногоСпроса : Справочник.Валюта
ВероятностьУспешногоЗавершения : Число 3, 0
ВидСделки : Справочник.Вид сделки
ДатаНачала : Дата
ДатаОкончания : Дата
Закрыта : Булево
Комментарий : Строка
Ответственный : Справочник.Пользователь
Партнер : Справочник.Партнер
ПереведенаНаУправлениеВРучную : Булево
ПотенциальнаяСуммаПродажи : Число 15, 2
ПричинаПроигрышаСделки : Справочник.Причина проигрыша сделки
Статус : Статусы сделок
СоглашениеСКлиентом : Справочник.Соглашение об условиях продаж
ОбособленныйУчетТоваровПоСделке : Булево
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n ПартнерыИКонтактныеЛица..
Партнер : Справочник.Партнер
РольПартнера : Справочник.Роль партнера в сделке или проекте
КонтактноеЛицо : Справочник.Контактное лицо
РольКонтактногоЛица : Справочник.Роль контактного лица партнера в сделках и проектах
Комментарий : Строка
ВыигралСделку : Булево
..Табличная часть \n ПервичныйСпрос..
ТекстовоеОписание : Строка
Сумма : Число 15, 2
ПроцентУдовлетворения : Число 3, 0
Комментарий : Строка
ПричинаНеудовлетворения : Справочник.Причина неудовлетворения первичного спроса
..Табличная часть \n НаборыЗначенийДоступа..
НомерНабора : Число 4, 0
ЗначениеДоступа : Справочник.Статьи бюджетов\rСправочник.Вид номенклатуры\rСправочник.Номенклатура\r...
Уточнение : Справочник.Идентификатор объекта метаданных
Чтение : Булево
Изменение : Булево
}
@enduml
