@startuml ГрафикиОплаты
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГрафикиОплаты as "Графики оплаты" <<Справочники>>
{
..Реквизиты..
ФормаОплаты : Формы оплаты
ТолькоКредитныеЭтапы : Булево
Календарь : Справочник.Производственный календарь
..Табличная часть \n Этапы..
ВариантОплаты : Варианты оплаты клиентом
Сдвиг : Число 10, 0
ПроцентПлатежа : Число 5, 2
ПроцентЗалогаЗаТару : Число 5, 2
}
@enduml
