@startuml КлючиАналитикиУчетаНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Справочник.КлючиАналитикиУчетаНоменклатуры as "Ключи аналитики учета номенклатуры" <<Справочники>>
{
..Реквизиты..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Серия : Справочник.Серия номенклатуры
Склад : Справочник.Организация\rСправочник.Подразделение\rСправочник.Партнер\r...
Назначение : Справочник.Назначение
СтатьяКалькуляции : Справочник.Статьи калькуляции
}
@enduml
