@startuml ВерсииРасширений
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВерсииРасширений as "Версии расширений" <<Справочники>>
{
..Реквизиты..
ОписаниеМетаданных : Строка
ПоследняяДатаДобавленияВторойВерсии : Дата
ДатаПервогоВходаПослеУдаленияВсехРасширений : Дата
}
@enduml
