@startuml СтатусыНалогоплательщиковПоНДФЛ
'!include templates.wsd
'..\include templates.wsd
class Справочник.СтатусыНалогоплательщиковПоНДФЛ as "Статусы налогоплательщиков (НДФЛ)" <<Справочники>>
{
..Реквизиты..
УдалитьИдентификаторОбъекта : Строка
КодФНС : Строка
РеквизитДопУпорядочивания : Число 5, 0
КодФНС_2015 : Строка
}
@enduml
