@startuml ПричиныВозникновенияПретензий
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПричиныВозникновенияПретензий as "Причины возникновения претензий" <<Справочники>>
{
..Реквизиты..
Описание : Строка
}
@enduml
