@startuml ГруппыДоступаСтатейИПоказателейБюджетов
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГруппыДоступаСтатейИПоказателейБюджетов as "Группы доступа статей и показателей бюджетов" <<Справочники>>
{
}
@enduml
