@startuml ВопросыШаблонаАнкеты
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВопросыШаблонаАнкеты as "Вопросы шаблона анкеты" <<Справочники>>
{
..Реквизиты..
Формулировка : Строка
Обязательный : Булево
ТипВопроса : Типы вопросов шаблона анкеты
ТипТабличногоВопроса : Типы табличных вопросов
ЭлементарныйВопрос : Вопрос для анкетирования
РодительВопрос : Справочник.Вопрос шаблона анкеты
Заметки : Строка
Подсказка : Строка
СпособОтображенияПодсказки : Способы отображения подсказок
..Табличная часть \n СоставТабличногоВопроса..
ЭлементарныйВопрос : Вопрос для анкетирования
..Табличная часть \n ПредопределенныеОтветы..
ЭлементарныйВопрос : Вопрос для анкетирования
Ответ : Булево\rСтрока\rДата\r...
..Табличная часть \n СоставКомплексногоВопроса..
ЭлементарныйВопрос : Вопрос для анкетирования
}
@enduml
