@startuml ВидыДокументовОбОбразовании
'!include templates.wsd
'..\include templates.wsd
class Справочник.ВидыДокументовОбОбразовании as "Виды документов об образовании" <<Справочники>>
{
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
