@startuml УсловияПредоставленияСкидокНаценок
'!include templates.wsd
'..\include templates.wsd
class Справочник.УсловияПредоставленияСкидокНаценок as "Условия предоставления скидок (наценок)" <<Справочники>>
{
..Реквизиты..
УсловиеПредоставления : Справочник.Дополнительный отчет или обработка\rУсловия предоставления скидок наценок
ВариантОпределенияПериодаНакопительнойСкидки : Варианты определения периода накопительной скидки
ВариантНакопления : Варианты накопления кумулятивной скидки наценки
КритерийОграниченияПримененияЗаОбъемПродаж : Критерии ограничения применения скидки наценки за объем продаж
ВалютаОграничения : Справочник.Валюта
ГрафикОплаты : Справочник.График оплаты
ФормаОплаты : Формы оплаты
ЗначениеУсловияОграничения : Число 15, 3
СегментНоменклатурыОграничения : Справочник.Сегмент номенклатуры
ПериодНакопления : Периодичность
ТипСравнения : Типы сравнения значений скидок наценок
ГруппаПользователей : Справочник.Группа пользователей
ВидКартыЛояльности : Справочник.Вид карт лояльности
СегментПартнеров : Справочник.Сегмент клиентов
КоличествоПериодовНакопления : Число 3, 0
ВариантОтбораНоменклатуры : Варианты отбора номенклатуры для расчета скидок наценок
КоличествоДнейДоДняРождения : Число 5, 0
КоличествоДнейПослеДняРождения : Число 5, 0
ВключатьТекущуюПродажуВНакопленныйОбъемПродаж : Булево
УчитыватьХарактеристики : Булево
ПараметрыВнешнейОбработки : Хранилище значения
ХранилищеНастроекКомпоновкиДанных : Хранилище значения
..Табличная часть \n ВремяДействия..
ДеньНедели : Дни недели
ВремяНачала : Дата
ВремяОкончания : Дата
}
@enduml
