@startuml СценарииОбменовДанными
'!include templates.wsd
'..\include templates.wsd
class Справочник.СценарииОбменовДанными as "Сценарии синхронизации данных" <<Справочники>>
{
..Реквизиты..
ИспользоватьРегламентноеЗадание : Булево
Комментарий : Строка
РегламентноеЗаданиеGUID : Строка
..Табличная часть \n НастройкиОбмена..
УзелИнформационнойБазы : Синхронизация данных через универсальный формат\rОбмен с подключаемым оборудованием Offline\rОбрабатываемый объект\r...
ВидТранспортаОбмена : Виды транспорта сообщений обмена
ВыполняемоеДействие : Действия при обмене
}
@enduml
