@startuml УдалитьТерриториальныеУсловияПФР
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьТерриториальныеУсловияПФР as "(не используется) Территориальные условия" <<Справочники>>
{
}
@enduml
