@startuml УдалитьЭлектронныеПредставленияРегламентированныхОтчетов
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьЭлектронныеПредставленияРегламентированныхОтчетов as "(не используется) Электронные представления регламентированных отчетов" <<Справочники>>
{
..Реквизиты..
Организация : Справочник.Организация
Получатель : Справочник.(не используется) Налоговые органы\rСправочник.Органы ФСГС\rСправочник.(не используется) Органы ПФР\r...
ДатаНачала : Дата
ДатаОкончания : Дата
Версия : Число 3, 0
Комментарий : Строка
Периодичность : Периодичность
ДатаИмпорта : Дата
ПредставлениеПериода : Строка
ПредставлениеВерсии : Строка
ТипПолучателя : (не используется) Типы контролирующих органов
УдалитьВидОтчета : Справочник.Регламентированные отчеты\rСправочник.(не используется) Виды отправляемых документов\rСправочник.(не используется) Регламентированные отчеты
ВидОтчета : Справочник.Виды отправляемых документов\rСправочник.Регламентированные отчеты\rСправочник.(не используется) Виды отправляемых документов\r...
}
@enduml
