@startuml ПараметрыКонтекстныхФункциональныхОпций
'!include templates.wsd
'..\include templates.wsd
class Справочник.ПараметрыКонтекстныхФункциональныхОпций as "Параметры контекстных функциональных опций" <<Справочники>>
{
..Реквизиты..
ИспользоватьДанныеПартнераКлиента : Булево
ИспользоватьДанныеПартнераПоставщика : Булево
ИспользоватьДанныеПоставщикаИлиКонкурента : Булево
ИспользоватьДанныеКонтрагентаФизическогоЛица : Булево
ИспользоватьДанныеТорговогоПредставителя : Булево
ИспользоватьДанныеПартнераСоглашенияСКлиентами : Булево
ИспользоватьМатериалыВЭксплуатации : Булево
ИспользоватьВариантыНаладки : Булево
ИспользоватьДанныеПодписок : Булево
ИспользоватьДоговорыКредитовИДепозитов : Булево
ИспользоватьУстанавливаемыйНефинансовыйПоказательБюджетов : Булево
ИспользоватьСвязиСтатейБюджетов : Булево
}
@enduml
