@startuml ТорговыеТочки
'!include templates.wsd
'..\include templates.wsd
class Справочник.ТорговыеТочки as "Торговые точки" <<Справочники>>
{
..Реквизиты..
Организация : Справочник.Организация
Склад : Справочник.Склад (складская территория)
НаправлениеДеятельности : Справочник.Направление деятельности
..Табличная часть \n КонтактнаяИнформация..
Тип : Типы контактной информации
Вид : Справочник.Вид контактной информации
Представление : Строка
ЗначенияПолей : Строка
Страна : Строка
Регион : Строка
Город : Строка
АдресЭП : Строка
ДоменноеИмяСервера : Строка
НомерТелефона : Строка
НомерТелефонаБезКодов : Строка
ВидДляСписка : Справочник.Вид контактной информации
}
@enduml
