@startuml КлючиАналитикиУчетаНаборов
'!include templates.wsd
'..\include templates.wsd
class Справочник.КлючиАналитикиУчетаНаборов as "Ключи аналитики учета наборов" <<Справочники>>
{
..Реквизиты..
НоменклатураНабора : Справочник.Номенклатура
ХарактеристикаНабора : Справочник.Характеристика номенклатуры
}
@enduml
