@startuml ГруппыОСМеждународныйУчет
'!include templates.wsd
'..\include templates.wsd
class Справочник.ГруппыОСМеждународныйУчет as "Группы ОС (международный учет)" <<Справочники>>
{
..Реквизиты..
ПериодичностьОценки : Число 10, 0
ПорядокУчета : Порядок учета стоимости внеоборотных активов
}
@enduml
