@startuml КлассификаторТНВЭД
'!include templates.wsd
'..\include templates.wsd
class Справочник.КлассификаторТНВЭД as "ТН ВЭД" <<Справочники>>
{
..Реквизиты..
НаименованиеПолное : Строка
ЕдиницаИзмерения : Справочник.Упаковка
ЭлементОбработан : Булево
СырьевойТовар : Булево
}
@enduml
