@startuml УдалитьНалоговыеОрганы
'!include templates.wsd
'..\include templates.wsd
class Справочник.УдалитьНалоговыеОрганы as "(не используется) Налоговые органы" <<Справочники>>
{
..Реквизиты..
Вид : Справочник.(не используется) Виды налоговых органов
ПолноеНаименование : Строка
УчетНалогоплательщиков : Булево
ПриемНалоговойОтчетности : Булево
ИНН : Строка
КПП : Строка
Адрес : Строка
Телефон : Строка
АдресЭлектроннойПочты : Строка
АдресСайта : Строка
Комментарий : Строка
УдалитьСертификат : Строка
АдресЭлектроннойПочтыДляЦелейДокументооборотаСНалогоплательщиками : Строка
..Табличная часть \n Сертификаты..
Сертификат : Строка
}
@enduml
