@startuml НастройкиЯндексКассы
'!include templates.wsd
'..\include templates.wsd
class Справочник.НастройкиЯндексКассы as "Настройки Яндекс.Кассы" <<Справочники>>
{
..Реквизиты..
Организация : Справочник.Организация
БанковскийСчет : Справочник.Банковский счет организации
ИдентификаторМагазина : Число 20, 0
ИдентификаторВитрины : Число 20, 0
Недействительна : Булево
СДоговором : Булево
СтатьяДвиженияДенежныхСредствОплаты : Справочник.Статья движения денежных средств
СтатьяДвиженияДенежныхСредствВозвраты : Справочник.Статья движения денежных средств
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
Подразделение : Справочник.Подразделение
Эквайер : Справочник.Контрагент
ОтправкаЧековЧерезЯндекс : Булево
}
@enduml
