@startuml Новости
'!include templates.wsd
'..\include templates.wsd
class Справочник.Новости as "Новости" <<Справочники>>
{
..Реквизиты..
ЛентаНовостей : Справочник.Лента новостей
УИННовости : Строка
ДатаПубликации : Дата
СкрыватьВОбщемСпискеНовостей : Булево
ДатаЗавершения : Дата
Подзаголовок : Строка
ТекстНовости : Строка
ТекстНовостиДляВнешнихИсточников : Строка
СсылкаНаПолныйТекстНовости : Строка
Важность : Число 1, 0
ДатаСбросаВажности : Дата
АвтоСбросНапоминанияПриПрочтении : Булево
ПриОткрытииСразуПереходитьПоСсылке : Булево
..Табличная часть \n Действия..
УИНДействия : Строка
Действие : Строка
..Табличная часть \n ПараметрыДействий..
УИНДействия : Строка
Параметр : Строка
ЗначениеПараметра : Строка
..Табличная часть \n ПривязкаКМетаданным..
Метаданные : Строка
Форма : Строка
Событие : Строка
ПоказыватьВФормеОбъекта : Булево
ДатаСбросаПоказаВФормеОбъекта : Дата
Важность : Число 1, 0
ДатаСбросаВажности : Дата
ЭтоПостояннаяНовость : Булево
ДатаСбросаПостояннойНовости : Дата
..Табличная часть \n БинарныеДанные..
УИН : Строка
Заголовок : Строка
Данные : Хранилище значения
ИнтернетСсылка : Строка
ПорядокСортировки : Число 2, 0
}
@enduml
