@startuml ХарактеристикиНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Справочник.ХарактеристикиНоменклатуры as "Характеристики номенклатуры" <<Справочники>>
{
..Реквизиты..
НаименованиеПолное : Строка
Принципал : Справочник.Организация\rСправочник.Партнер
Контрагент : Справочник.Организация\rСправочник.Контрагент
КиЗГИСМGTIN : Строка
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
}
@enduml
