@startuml СоглашенияСКлиентами
'!include templates.wsd
'..\include templates.wsd
class Справочник.СоглашенияСКлиентами as "Соглашения об условиях продаж" <<Справочники>>
{
..Реквизиты..
Номер : Строка
Дата : Дата
СегментПартнеров : Справочник.Сегмент клиентов
Контрагент : Справочник.Контрагент
Партнер : Справочник.Партнер
Организация : Справочник.Организация
Валюта : Справочник.Валюта
ГрафикОплаты : Справочник.График оплаты
СуммаДокумента : Число 15, 2
Типовое : Булево
СрокПоставки : Число 10, 0
ВидЦен : Справочник.Вид цены
ЦенаВключаетНДС : Булево
ИспользуетсяВРаботеТорговыхПредставителей : Булево
Соглашение : Справочник.Соглашение об условиях продаж
Склад : Справочник.Склад (складская территория)
СегментНоменклатуры : Справочник.Сегмент номенклатуры
ДатаНачалаДействия : Дата
ДатаОкончанияДействия : Дата
Комментарий : Строка
Регулярное : Булево
Период : Периодичность
КоличествоПериодов : Число 3, 0
Статус : Статусы соглашений с клиентами
Согласован : Булево
Менеджер : Справочник.Пользователь
НалогообложениеНДС : Типы налогообложения НДС
ХозяйственнаяОперация : Хозяйственные операции
СпособРасчетаВознаграждения : Способы расчета комиссионного вознаграждения
ПроцентВознаграждения : Число 5, 2
УдержатьВознаграждение : Булево
ПроцентРучнойСкидки : Число 5, 2
ПроцентРучнойНаценки : Число 5, 2
ДоступноВнешнимПользователям : Булево
ПорядокОплаты : Порядок оплаты
ГруппаФинансовогоУчета : Справочник.Группа финансового учета расчетов
ИспользуютсяДоговорыКонтрагентов : Булево
ОграничиватьРучныеСкидки : Булево
ФормаОплаты : Формы оплаты
КонтактноеЛицо : Справочник.Контактное лицо
ПорядокРасчетов : Детализация расчетов
ВозвращатьМногооборотнуюТару : Булево
СрокВозвратаМногооборотнойТары : Число 3, 0
РассчитыватьДатуВозвратаТарыПоКалендарю : Булево
Календарь : Справочник.Производственный календарь
ВариантРасчетаЦен : Варианты расчета цен по соглашениям с клиентами
СценарийПланирования : Справочник.Сценарии товарного планирования
ВидПлана : Справочник.Вид плана
ТребуетсяЗалогЗаТару : Булево
КалендарьВозвратаТары : Справочник.Производственный календарь
ВидСоглашенияДляОграниченияЧтения : Вид соглашения с клиентами (для ограничение доступа на чтение)
ВидСоглашенияДляОграниченияИзменения : Вид соглашения с клиентами (для ограничение доступа на изменение)
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
ВозможнаРеализацияБезПереходаПраваСобственности : Булево
ОбеспечиватьЗаказыОбособленно : Булево
КодНаименованияСделки : Строка
СпособОпределенияЦеныСделки : Справочник.Способ определения цены контролируемой сделки
КодУсловийПоставки : Строка
НаправлениеДеятельности : Справочник.Направление деятельности
ВалютаВзаиморасчетов : Справочник.Валюта
РазбиватьРасходныеОрдераПоРаспоряжениям : Булево
МинимальнаяСуммаЗаказа : Число 15, 2
ЧастотаЗаказа : Число 5, 0
..Табличная часть \n Товары..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
ВидЦены : Справочник.Вид цены
Цена : Число 15, 2
СрокПоставки : Число 10, 0
..Табличная часть \n ЦеновыеГруппы..
ЦеноваяГруппа : Справочник.Ценовая группа
ВидЦен : Справочник.Вид цены
СрокПоставки : Число 10, 0
ПроцентРучнойСкидки : Число 5, 2
ПроцентРучнойНаценки : Число 5, 2
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n ЭтапыГрафикаОплаты..
ВариантОплаты : Варианты оплаты клиентом
Сдвиг : Число 10, 0
ПроцентПлатежа : Число 5, 2
ПроцентЗалогаЗаТару : Число 5, 2
}
@enduml
