@startuml НоменклатураПоставщиков
'!include templates.wsd
'..\include templates.wsd
class Справочник.НоменклатураПоставщиков as "Номенклатура поставщиков" <<Справочники>>
{
..Реквизиты..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Упаковка : Справочник.Упаковка
Артикул : Строка
Идентификатор : Строка
}
@enduml
