@startuml ОбщиеВнешниеКомпоненты
'!include templates.wsd
'..\include templates.wsd
class Справочник.ОбщиеВнешниеКомпоненты as "Общие внешние компоненты" <<Справочники>>
{
..Реквизиты..
Идентификатор : Строка
Версия : Строка
ДатаВерсии : Дата
ХранилищеКомпоненты : Хранилище значения
Windows_x86 : Булево
Windows_x86_64 : Булево
Linux_x86 : Булево
Linux_x86_64 : Булево
Windows_x86_Firefox : Булево
Linux_x86_Firefox : Булево
Linux_x86_64_Firefox : Булево
Windows_x86_MSIE : Булево
Windows_x86_64_MSIE : Булево
Windows_x86_Chrome : Булево
Linux_x86_Chrome : Булево
Linux_x86_64_Chrome : Булево
MacOS_x86_64_Safari : Булево
}
@enduml
