@startuml ШаблоныВводаНефинансовыхПоказателей
'!include templates.wsd
'..\include templates.wsd
class Справочник.ШаблоныВводаНефинансовыхПоказателей as "Шаблоны ввода нефинансовых показателей" <<Справочники>>
{
..Реквизиты..
ПредставлениеПоказателей : Строка
ТипФормыВводаПоказателей : Типы форм шаблонов нефинансовых показателей
ПоказателиВТабличнойЧасти : Булево
..Табличная часть \n ПоказателиШаблона..
Показатель : Справочник.Нефинансовые показатели бюджетов
Заполнять : Булево
СхемаКомпоновкиДанных : Строка
ХранилищеСхемыКомпоновкиДанных : Хранилище значения
ХранилищеНастроекКомпоновкиДанных : Хранилище значения
..Табличная часть \n РедактироватьВСтроках..
Аналитика : Аналитики статей бюджетов
ИмяИзмерения : Строка
..Табличная часть \n РедактироватьВШапке..
Аналитика : Аналитики статей бюджетов
ИмяИзмерения : Строка
..Табличная часть \n ЗначенияСложнойТаблицыПоУмолчанию..
Значение : Справочник.Классификатор продукции по видам деятельности (ОКПД)\rСправочник.Присоединенный файл (Отчет комиссионера)\rДокумент.Сторнирование начислений\r...
ИмяИзмерения : Строка
Аналитика : Аналитики статей бюджетов
..Табличная часть \n РедактироватьВКолонках..
Аналитика : Аналитики статей бюджетов
ИмяИзмерения : Строка
}
@enduml
