@startuml КлассыОбъектовЭксплуатации
'!include templates.wsd
'..\include templates.wsd
class Справочник.КлассыОбъектовЭксплуатации as "Классы объектов эксплуатации" <<Справочники>>
{
..Реквизиты..
НаборСвойств : Справочник.Набор дополнительных реквизитов и сведений
Описание : Строка
ИспользуютсяПодклассы : Булево
РемонтныйЦиклПоИнтервалуНаработки : Булево
ЭтоКлассУзла : Булево
..Табличная часть \n РеквизитыДляКонтроля..
ИмяРеквизита : Строка
ОбязателенДляЗаполнения : Булево
..Табличная часть \n ПоказателиНаработки..
ПоказательНаработки : Справочник.Показатель наработки
РассчитыватьОстаточныйРесурс : Булево
РегистрироватьОтИсточника : Булево
ПериодичностьРегистрации : Число 10, 0
ПересчитыватьСреднесуточноеЗначение : Булево
МинимальныйПериодРасчета : Число 10, 0
МаксимальныйПериодРасчета : Число 10, 0
..Табличная часть \n РемонтныйЦикл..
ВидРемонта : Справочник.Вид ремонта
ИнтервалВремени : Число 15, 0
ЕдиницаВремени : Единицы измерения времени
ИнтервалНаработки : Число 15, 3
ПоказательНаработки : Справочник.Показатель наработки
..Табличная часть \n ПрочиеРемонты..
ВидРемонта : Справочник.Вид ремонта
ПоИнтервалуНаработки : Булево
ИнтервалВремени : Число 15, 0
ЕдиницаВремени : Единицы измерения времени
ИнтервалНаработки : Число 15, 3
ПоказательНаработки : Справочник.Показатель наработки
}
@enduml
