@startuml ШтатноеРасписание
'!include templates.wsd
'..\include templates.wsd
class Справочник.ШтатноеРасписание as "Штатное расписание" <<Справочники>>
{
..Реквизиты..
Подразделение : Справочник.Подразделение
Должность : Справочник.Должность
РазрядКатегория : Справочник.Квалификационный разряд (категория)
ГрафикРаботыСотрудников : Справочник.График работы
КоличествоСтавок : Число 7, 2
Утверждена : Булево
ДатаУтверждения : Дата
Закрыта : Булево
ДатаЗакрытия : Дата
ОкладТариф : Число 15, 3
ОкладТарифМин : Число 15, 3
ОкладТарифМакс : Число 15, 3
Описание : Строка
ФОТ : Число 19, 2
ФОТМин : Число 19, 2
ФОТМакс : Число 19, 2
РайонныйКоэффициентРазмер : Число 15, 2
РайонныйКоэффициентРазмерМин : Число 15, 2
РайонныйКоэффициентРазмерМакс : Число 15, 2
СевернаяНадбавкаРазмер : Число 15, 2
СевернаяНадбавкаРазмерМин : Число 15, 2
СевернаяНадбавкаРазмерМакс : Число 15, 2
УсловияПриема : Строка
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОтношениеКЕНВД : Отношение к ЕНВД затрат на зарплату
СтатьяФинансирования : Справочник.Статья финансирования
ТарифнаяСетка : Справочник.Тарифная группа
ТарифнаяСеткаНадбавки : Справочник.Тарифная группа
РазрядКатегорияНадбавки : Справочник.Квалификационный разряд (категория)
НадбавкаЗаВредностьРазмер : Число 15, 2
НадбавкаЗаВредностьРазмерМин : Число 15, 2
НадбавкаЗаВредностьРазмерМакс : Число 15, 2
ВзимаютсяВзносыЗаЗанятыхНаРаботахСДосрочнойПенсией : Виды работ с досрочной пенсией
ОснованиеДосрочногоНазначенияПенсии : Справочник.Основание для досрочной пенсии
ОсобыеУсловияТрудаПФР : Справочник.Особое условие труда
КодПозицииСпискаПФР : Справочник.Льготная профессия (ПФР)
ВыплачиваетсяНадбавкаЗаВредность : Булево
ПроцентНадбавкиЗаВредность : Число 5, 2
ФОТУправленческий : Число 19, 2
ФОТУправленческийМин : Число 19, 2
ФОТУправленческийМакс : Число 19, 2
ГруппаПозицийПодразделения : Булево
..Табличная часть \n Начисления..
Начисление : Начисление
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Размер : Число 15, 2
РазмерМин : Число 15, 2
РазмерМакс : Число 15, 2
..Табличная часть \n Показатели..
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Показатель : Справочник.Показатель
Значение : Число 15, 5
ЗначениеМин : Число 15, 5
ЗначениеМакс : Число 15, 5
..Табличная часть \n ДополнительныеРеквизиты..
Свойство : Дополнительный реквизит / сведение
Значение : Справочник.Профессия рабочего\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
ТекстоваяСтрока : Строка
..Табличная часть \n ЕжегодныеОтпуска..
ВидЕжегодногоОтпуска : Справочник.Вид отпуска
КоличествоДнейВГод : Число 2, 0
..Табличная часть \n Специальности..
Специальность : Справочник.Специальность
..Табличная часть \n УправленческиеНачисления..
Начисление : Начисление
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Размер : Число 15, 2
РазмерМин : Число 15, 2
РазмерМакс : Число 15, 2
..Табличная часть \n УправленческиеПоказатели..
ИдентификаторСтрокиВидаРасчета : Число 7, 0
Показатель : Справочник.Показатель
Значение : Число 15, 5
ЗначениеМин : Число 15, 5
ЗначениеМакс : Число 15, 5
..Табличная часть \n ЗависимыеСтажи..
ВидСтажа : Справочник.Вид стажа
}
@enduml
