@startuml ПартииЗатратНаВыпуск
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПартииЗатратНаВыпуск as "Партии затрат на выпуск" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
АналитикаУчетаПродукции : Справочник.Ключ аналитики учета номенклатуры
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
ДокументВыпуска : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\rДокумент.Таможенная декларация на импорт\r...
ДокументПоступления : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\rДокумент.Таможенная декларация на импорт\r...
АналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
..Ресурсы..
Количество : Число 15, 3
Стоимость : Число 15, 2
СтоимостьБезНДС : Число 15, 2
СтоимостьРегл : Число 15, 2
НДСРегл : Число 15, 2
ПостояннаяРазница : Число 15, 2
ВременнаяРазница : Число 15, 2
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
НалогообложениеНДС : Типы налогообложения НДС
СтатьяРасходовСписания : Статья расходов\rСтатья актива/пассива
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
ПодразделениеРасходов : Справочник.Подразделение
КорАналитикаУчетаПродукции : Справочник.Ключ аналитики учета номенклатуры
КорВидЗапасов : Справочник.Вид запасов
Знаменатель : Число 15, 3
ДокументИсточник : Документ.Внутреннее потребление товаров\rДокумент.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\r...
СтатьяСписанияНДС : Статья расходов
АналитикаСписанияНДС : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ИдентификаторСтроки : Строка
}
@enduml
