@startuml СостоянияРабочихЦентров
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.СостоянияРабочихЦентров as "Состояния рабочих центров" <<РегистрыНакопления>>
{
..Измерения..
Подразделение : Справочник.Подразделение
ВидРабочегоЦентра : Справочник.Вид рабочего центра
РабочийЦентр : Справочник.Рабочий центр
МаршрутныйЛист : Документ.Маршрутный лист производства
..Ресурсы..
ВремяДоступен : Число 10, 0
ВремяРаботы : Число 10, 0
ВремяПереналадки : Число 10, 0
}
@enduml
