@startuml ПрочиеДоходы
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПрочиеДоходы as "Прочие доходы" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
НаправлениеДеятельности : Справочник.Направление деятельности
СтатьяДоходов : Статьи доходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
..Ресурсы..
Сумма : Число 15, 2
СуммаРегл : Число 15, 2
СуммаУпр : Число 15, 2
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
УдалитьСуммаРегл : Число 15, 2
РасчетСебестоимости : Булево
КорНаправлениеДеятельности : Справочник.Направление деятельности
}
@enduml
