@startuml РасчетыНалогоплательщиковСБюджетомПоНДФЛ
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.РасчетыНалогоплательщиковСБюджетомПоНДФЛ as "Расчеты налогоплательщиков с бюджетом по НДФЛ" <<РегистрыНакопления>>
{
..Измерения..
ГоловнаяОрганизация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
СтавкаНалогообложенияРезидента : НДФЛ ставки налогообложения резидента
МесяцНалоговогоПериода : Дата
КатегорияДохода : Категории доходов НДФЛ
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
Организация : Справочник.Организация
УдалитьКодДохода : Справочник.(не используется) Виды доходов НДФЛ
КодДохода : Справочник.Вид дохода НДФЛ
..Ресурсы..
Сумма : Число 13, 0
..Реквизиты..
Подразделение : Справочник.Территория\rСправочник.Подразделение
ДокументОснование : Документ.Сторнирование начислений\rДокумент.Перенос затрат\rДокумент.Приз, подарок\r...
ВариантУдержания : Варианты удержания НДФЛ
ВключатьВДекларациюПоНалогуНаПрибыль : Булево
РасчетМежрасчетногоПериода : Булево
УдалитьОрганизация : Справочник.Организация
СуммаВыплаченногоДохода : Число 15, 2
СрокПеречисления : Сроки перечисляемого налога
КрайнийСрокУплаты : Дата
УчитыватьВыплаченныйДоходВ6НДФЛ : Булево
ДатаПолученияДоходаФиксирована : Булево
УстаревшаяДатаПолученияДохода : Дата
Сторно : Булево
}
@enduml
