@startuml ПланыПроизводства
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПланыПроизводства as "Планы производства" <<РегистрыНакопления>>
{
..Измерения..
Сценарий : Справочник.Сценарии товарного планирования
Статус : Статусы планов
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Подразделение : Справочник.Подразделение
ПланПроизводства : Документ.План производства
Спецификация : Справочник.Ресурсная спецификация
Назначение : Справочник.Назначение
ДатаВыпускаПолуфабриката : Дата
ДатаЗапуска : Дата
ЭтоПолуфабрикат : Булево
ВидПлана : Справочник.Вид плана
..Ресурсы..
Количество : Число 15, 3
..Реквизиты..
ПовторноеРазузлование : Булево
РучнаяКорректировка : Булево
ДатаКорректировки : Дата
АвторКорректировки : Справочник.Пользователь
Комментарий : Строка
}
@enduml
