@startuml ПринятаяВозвратнаяТара
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПринятаяВозвратнаяТара as "Принятая возвратная тара" <<РегистрыНакопления>>
{
..Измерения..
Партнер : Справочник.Партнер
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
ДокументПоступления : Документ.Приобретение товаров и услуг\rДокумент.Поступление сырья от давальца
ПредусмотренЗалог : Булево
..Ресурсы..
Количество : Число 15, 3
Сумма : Число 15, 2
..Реквизиты..
Выкуп : Булево
}
@enduml
