@startuml РасчетыСФондамиПоСтраховымВзносам
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.РасчетыСФондамиПоСтраховымВзносам as "Расчеты с фондами по страховым взносам" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ВидОбязательногоСтрахованияСотрудников : Виды обязательного страхования сотрудников
ЭтоСтраховыеВзносы : Булево
ЭтоРасчетыПоНачислениюУплатеВзносовВФСС : Булево
ГодЗадолженностиПоЕСН : Число 4, 0
..Ресурсы..
Сумма : Число 15, 2
..Реквизиты..
РасчетыПоПособиям : Виды расчетов по средствам ФСС
ЭтоДоначислениеПоАктуПроверки : Булево
ПлатежноеПоручениеНомер : Строка
ПлатежноеПоручениеДата : Дата
Сторно : Булево
}
@enduml
