@startuml ПланыПотребленияМатериалов
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПланыПотребленияМатериалов as "Планы потребления материалов" <<РегистрыНакопления>>
{
..Измерения..
Сценарий : Справочник.Сценарии товарного планирования
Статус : Статусы планов
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
ПодразделениеДиспетчер : Справочник.Подразделение
ПодразделениеИсполнитель : Справочник.Подразделение
Склад : Справочник.Склад (складская территория)
ПланПроизводства : Документ.План производства
ДатаВыпуска : Дата
ЭтоПолуфабрикат : Булево
УдалитьДатаВыпускаПолуфабриката : Дата
УдалитьСпецификацияПолуфабриката : Справочник.Ресурсная спецификация
НоменклатураПродукции : Справочник.Номенклатура
ХарактеристикаПродукции : Справочник.Характеристика номенклатуры
НазначениеПродукции : Справочник.Назначение
..Ресурсы..
Количество : Число 15, 3
..Реквизиты..
Спецификация : Справочник.Ресурсная спецификация
КоличествоНаЕдиницуПродукции : Число 15, 6
СодержитРасчетноеКоличество : Булево
}
@enduml
