@startuml ТрудозатратыНезавершенногоПроизводства
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ТрудозатратыНезавершенногоПроизводства as "Трудозатраты незавершенного производства" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ПартияПроизводства : Документ.Этап производства\rДокумент.Отчет переработчика\rДокумент.Выпуск продукции и выполнение работ\r...
ЗаказНаПроизводство : Документ.Заказ на производство
КодСтрокиПродукция : Число 10, 0
Этап : Справочник.Этап ресурсной спецификации
СтатьяКалькуляции : Справочник.Статьи калькуляции
ВидРабот : Справочник.Вид работ сотрудников
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
ВидФондаВзносов : Виды фондов взносов
..Ресурсы..
Количество : Число 15, 3
НормативнаяСтоимость : Число 15, 2
Стоимость : Число 15, 2
СтоимостьРегл : Число 15, 2
..Реквизиты..
Продукция : Справочник.Номенклатура
ХарактеристикаПродукции : Справочник.Характеристика номенклатуры
КоличествоПродукции : Число 15, 3
Сотрудник : Справочник.Физическое лицо
КорАналитикаУчетаПродукции : Справочник.Ключ аналитики учета номенклатуры
КорРазделУчета : Разделы учета себестоимости товаров
КорВидЗапасовПродукции : Справочник.Вид запасов
СтатьяКалькуляцииБезЗаказа : Справочник.Статьи калькуляции
ДокументВыпуска : Документ.Выпуск продукции и выполнение работ\rДокумент.Поступление от переработчика
КодСтроки : Число 10, 0
РасчетПартий : Булево
АналитикаУчетаПартийПроизводства : Справочник.Ключ аналитики учета партий производства
КорАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
РасчетНеЗавершен : Булево
}
@enduml
