@startuml ПланыЗанятостиВидовРабочихЦентров
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПланыЗанятостиВидовРабочихЦентров as "Планы занятости видов рабочих центров" <<РегистрыНакопления>>
{
..Измерения..
Сценарий : Справочник.Сценарии товарного планирования
Статус : Статусы планов
ВидРабочегоЦентра : Справочник.Вид рабочего центра
ПодразделениеДиспетчер : Справочник.Подразделение
ПодразделениеИсполнитель : Справочник.Подразделение
ПланПроизводства : Документ.План производства
ДатаВыпуска : Дата
НоменклатураПродукции : Справочник.Номенклатура
ХарактеристикаПродукции : Справочник.Характеристика номенклатуры
..Ресурсы..
Занятость : Число 15, 0
..Реквизиты..
Спецификация : Справочник.Ресурсная спецификация
КоличествоНаЕдиницуПродукции : Число 15, 6
ОдновременноПроизводимоеКоличествоЕдиницПартийИзделий : Число 15, 3
НазначениеПродукции : Справочник.Назначение
}
@enduml
