@startuml ГрафикПоступленияТоваров
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ГрафикПоступленияТоваров as "График поступления товаров" <<РегистрыНакопления>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Склад : Справочник.Склад (складская территория)
ДатаСобытия : Дата
Назначение : Справочник.Назначение
..Ресурсы..
КоличествоИзЗаказов : Число 15, 3
КоличествоПодЗаказ : Число 15, 3
КоличествоИзЗаказовСНеподтвержденными : Число 15, 3
КоличествоПодЗаказСНеподтвержденными : Число 15, 3
}
@enduml
