@startuml ФинансовыеРезультаты
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ФинансовыеРезультаты as "Финансовые результаты" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
НаправлениеДеятельности : Справочник.Направление деятельности
СтатьяДоходов : Статьи доходов
СтатьяРасходов : Статья расходов
..Ресурсы..
Доходы : Число 15, 2
Расходы : Число 15, 2
..Реквизиты..
СпособРаспределения : Справочник.Способ распределения доходов и расходов по направлениям деятельности
РасчетСебестоимости : Булево
}
@enduml
