@startuml БракВПроизводстве
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.БракВПроизводстве as "Брак в производстве" <<РегистрыНакопления>>
{
..Измерения..
МаршрутныйЛист : Документ.Маршрутный лист производства
..Ресурсы..
Количество : Число 15, 0
}
@enduml
