@startuml РасчетыСПоставщиками
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.РасчетыСПоставщиками as "Расчеты с поставщиками" <<РегистрыНакопления>>
{
..Измерения..
АналитикаУчетаПоПартнерам : Справочник.Ключ аналитики учета по партнерам
ЗаказПоставщику : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Приобретение товаров и услуг\r...
Валюта : Справочник.Валюта
..Ресурсы..
Сумма : Число 15, 2
Оплачивается : Число 15, 2
КОплате : Число 15, 2
КПоступлению : Число 15, 2
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
ФормаОплаты : Формы оплаты
ЗаявкаНаРасходованиеДенежныхСредств : Документ.Заявка на расходование ДС
ЗакупкаПоЗаказу : Документ.Заказ поставщику\rДокумент.Заказ переработчику
ДатаРегистратора : Дата
ДатаПлатежа : Дата
СуммаРегл : Число 15, 2
СуммаУпр : Число 15, 2
ЗалогЗаТару : Число 15, 2
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
РасчетныйДокумент : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Приобретение товаров и услуг\r...
}
@enduml
