@startuml РасходыПриУСНОСиНМА
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.РасходыПриУСНОСиНМА as "Расходы по ОС и НМА при УСН" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ДокументВозникновенияРасходов : Документ.Приобретение товаров и услуг\rДокумент.Первичный документ\rДокумент.Приобретение услуг и прочих активов
ВидРасходов : Виды расходов УСН
ЭлементРасходов : Справочник.Объект эксплуатации\rСправочник.Нематериальные активы и расходы на НИОКР
..Ресурсы..
СуммаРасходов : Число 15, 2
НДС : Число 15, 2
СуммаОплаты : Число 15, 2
..Реквизиты..
ДатаОплаты : Дата
}
@enduml
