@startuml ДоступностьВидовРабочихЦентров
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДоступностьВидовРабочихЦентров as "Доступность видов рабочих центров" <<РегистрыНакопления>>
{
..Измерения..
ВидРабочегоЦентра : Справочник.Вид рабочего центра
ДатаИнтервала : Дата
..Ресурсы..
Занято : Число 8, 0
ДоступностьПоВидуРЦ : Число 8, 0
ДоступностьПоРЦ : Число 8, 0
УдалитьЗанятоСозданнымМЛ : Число 8, 0
..Реквизиты..
МаксимальнаяДоступность : Число 8, 1
МаксимальнаяДоступностьПоВидуРЦ : Число 8, 1
КодСтрокиПродукция : Число 10, 0
КодСтрокиЭтапыГрафик : Число 10, 0
ВариантНаладки : Справочник.Вариант наладки
ЭтоДвижениеВводаДоступности : Булево
ЭтоДвижениеЗаказаНаПроизводство : Булево
ЭтоДвижениеМаршрутногоЛиста : Булево
Распоряжение : Документ.Заказ на производство
Подразделение : Справочник.Подразделение
}
@enduml
