@startuml ПособияПоУходуЗаРебенком
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПособияПоУходуЗаРебенком as "Пособия по уходу за ребенком" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
ВидЗанятости : Виды занятости
ФинансированиеФедеральнымБюджетом : Основания финансирования пособия федеральным бюджетом
..Ресурсы..
СтраховыеСлучаи : Число 5, 0
СтраховыеСлучаиПоУходуЗаПервымРебенком : Число 5, 0
СуммаВсегоПоУходуЗаПервымРебенком : Число 15, 2
СуммаСверхНормПоУходуЗаПервымРебенком : Число 15, 2
СтраховыеСлучаиПоУходуЗаВторымРебенком : Число 5, 0
СуммаВсегоПоУходуЗаВторымРебенком : Число 15, 2
СуммаСверхНормПоУходуЗаВторымРебенком : Число 15, 2
..Реквизиты..
Сотрудник : Справочник.Сотрудник
ДатаСтраховогоСлучая : Дата
Сторно : Булево
}
@enduml
