@startuml ЗарплатаКВыплатеАвансом
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ЗарплатаКВыплатеАвансом as "Зарплата к выплате авансом" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
ПериодВзаиморасчетов : Дата
ДокументОснование : Документ.Единовременное пособие\rДокумент.Перенос затрат\rДокумент.Возврат НДФЛ\r...
УдалитьДокументОснование : Документ.Единовременное пособие\rДокумент.Перенос затрат\rДокумент.Возврат НДФЛ\r...
..Ресурсы..
СуммаКВыплате : Число 15, 2
..Реквизиты..
Сторно : Булево
}
@enduml
