@startuml УдержанияПоИсполнительнымДокументам
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.УдержанияПоИсполнительнымДокументам as "Удержания по исполнительным документам" <<РегистрыНакопления>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
Организация : Справочник.Организация
ИсполнительныйДокумент : Документ.Исполнительный лист
Получатель : Справочник.Контрагент
ПлатежныйАгент : Справочник.Контрагент
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
..Ресурсы..
СуммаУдержания : Число 15, 2
СуммаВознагражденияПлатежногоАгента : Число 15, 2
..Реквизиты..
Сторно : Булево
}
@enduml
