@startuml ПотребностьВМатериалахВПроизводстве
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПотребностьВМатериалахВПроизводстве as "Потребность в материалах в производстве" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Распоряжение : Документ.Заказ на производство
КодСтрокиЭтапыГрафик : Число 10, 0
..Ресурсы..
Количество : Число 15, 3
}
@enduml
