@startuml НДСПредъявленный
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.НДСПредъявленный as "НДС предъявленный" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
СчетФактура : Документ.Запись книги покупок\rДокумент.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\r...
Поставщик : Справочник.Организация\rСправочник.Контрагент
ВидЦенности : Виды ценностей
СтавкаНДС : Ставки НДС
ВидДеятельностиНДС : Типы налогообложения НДС
ИсправленныйСчетФактура : Документ.Корректировка приобретения\rДокумент.Счет-фактура выданный\rДокумент.Счет-фактура полученный
РеализацияЭкспорт : Документ.Первичный документ\rДокумент.Реализация товаров и услуг\rДокумент.Акт выполненных работ
..Ресурсы..
СуммаБезНДС : Число 15, 2
НДС : Число 15, 2
НДСУпр : Число 15, 2
..Реквизиты..
Событие : События НДС предъявленный
КорВидДеятельностиНДС : Типы налогообложения НДС
ИдентификаторСтроки : Строка
РегламентнаяОперация : Булево
Подразделение : Справочник.Подразделение
НаправлениеДеятельности : Справочник.Направление деятельности
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
}
@enduml
