@startuml ДвиженияНоменклатураНоменклатура
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДвиженияНоменклатураНоменклатура as "Движения Номенклатура - Номенклатура" <<РегистрыНакопления>>
{
..Измерения..
ХозяйственнаяОперация : Хозяйственные операции
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
НаправлениеДеятельности : Справочник.Направление деятельности
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
Склад : Справочник.Подразделение\rСправочник.Партнер\rСправочник.Склад (складская территория)
ТипЗапасов : Типы запасов
ВидЗапасов : Справочник.Вид запасов
КорНаправлениеДеятельности : Справочник.Направление деятельности
КорАналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
КорСклад : Справочник.Подразделение\rСправочник.Партнер\rСправочник.Склад (складская территория)
КорТипЗапасов : Типы запасов
КорВидЗапасов : Справочник.Вид запасов
..Ресурсы..
Количество : Число 15, 3
КорКоличество : Число 15, 3
Стоимость : Число 15, 2
СтоимостьБезНДС : Число 15, 2
СтоимостьУпр : Число 15, 2
СтоимостьРегл : Число 15, 2
СтоимостьЗабалансовая : Число 15, 2
СтоимостьЗабалансоваяРегл : Число 15, 2
ДопРасходы : Число 15, 2
ДопРасходыБезНДС : Число 15, 2
ДопРасходыУпр : Число 15, 2
ДопРасходыРегл : Число 15, 2
ПостатейныеПостоянныеСНДС : Число 15, 2
ПостатейныеПостоянныеБезНДС : Число 15, 2
ПостатейныеПостоянныеУпр : Число 15, 2
ПостатейныеПостоянныеРегл : Число 15, 2
Трудозатраты : Число 15, 2
ТрудозатратыУпр : Число 15, 2
ТрудозатратыРегл : Число 15, 2
ПостатейныеПеременныеСНДС : Число 15, 2
ПостатейныеПеременныеБезНДС : Число 15, 2
ПостатейныеПеременныеУпр : Число 15, 2
ПостатейныеПеременныеРегл : Число 15, 2
ПостояннаяРазница : Число 15, 2
ВременнаяРазница : Число 15, 2
..Реквизиты..
ИсточникГФУНоменклатуры : Справочник.Номенклатура\rСправочник.Вид запасов
КорИсточникГФУНоменклатуры : Справочник.Номенклатура\rСправочник.Вид запасов
ДокументДвижения : Документ.Внутреннее потребление товаров\rДокумент.Перемещение материалов в производстве\rДокумент.Возврат товаров от клиента\r...
КорОрганизация : Справочник.Организация
РасчетСебестоимости : Булево
}
@enduml
