@startuml ЗаказыМатериаловВПроизводство
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ЗаказыМатериаловВПроизводство as "Заказы материалов в производство" <<РегистрыНакопления>>
{
..Измерения..
Распоряжение : Документ.Этап производства\rДокумент.Заказ на производство\rДокумент.Заказ материалов в производство\r...
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КодСтроки : Число 10, 0
Склад : Справочник.Склад (складская территория)
Подразделение : Справочник.Подразделение
Серия : Справочник.Серия номенклатуры
Назначение : Справочник.Назначение
НазначениеОтправителя : Справочник.Назначение
Получатель : Справочник.Подразделение\rСправочник.Склад (складская территория)
..Ресурсы..
Заказано : Число 15, 3
ВРезерве : Число 15, 3
КОформлению : Число 15, 3
ОтгруженоНеПринято : Число 15, 3
}
@enduml
