@startuml НачисленияУдержанияПоКонтрагентамАкционерам
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.НачисленияУдержанияПоКонтрагентамАкционерам as "Начисления удержания по контрагентам, акционерам" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
НачислениеУдержание : Справочник.Вид выплаты бывшему сотруднику\rСправочник.Вид прочего дохода\rВиды особых начислений и удержаний\r...
..Ресурсы..
Сумма : Число 15, 2
..Реквизиты..
ГруппаНачисленияУдержанияВыплаты : Группы начисления удержания выплаты
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
ДокументОснование : Документ.Выплата бывшим сотрудникам\rДокумент.Начисление прочих доходов\rДокумент.Исполнительный лист
ТерриторияВыполненияРаботВОрганизации : Справочник.Территория\rСправочник.Подразделение
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
Контрагент : Справочник.Контрагент
Сторно : Булево
}
@enduml
