@startuml ЗаказыПоставщикам
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ЗаказыПоставщикам as "Заказы поставщикам" <<РегистрыНакопления>>
{
..Измерения..
ЗаказПоставщику : Документ.Заказ поставщику\rДокумент.Заказ на производство\rДокумент.Заказ переработчику\r...
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КодСтроки : Число 10, 0
Склад : Справочник.Склад (складская территория)
..Ресурсы..
Заказано : Число 15, 3
КОформлению : Число 15, 3
..Реквизиты..
ПричинаОтмены : Справочник.Причина отмены заказов поставщикам
}
@enduml
