@startuml ДенежныеСредстваКВыплате
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДенежныеСредстваКВыплате as "Денежные средства к выплате" <<РегистрыНакопления>>
{
..Измерения..
ЗаявкаНаРасходованиеДенежныхСредств : Документ.Распоряжение\rДокумент.Ведомость через раздатчика\rДокумент.Ведомость на счета\r...
БанковскийСчетКасса : Справочник.Банковский счет организации\rСправочник.Касса
Получатель : Справочник.Организация\rСправочник.Контрагент\rСправочник.Физическое лицо
Организация : Справочник.Организация
..Ресурсы..
Сумма : Число 15, 2
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
}
@enduml
