@startuml НДСЗаписиКнигиПродаж
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.НДСЗаписиКнигиПродаж as "НДС Продажи" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
Покупатель : Справочник.Организация\rСправочник.Контрагент
СчетФактура : Документ.Запись книги покупок\rДокумент.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\r...
ВидЦенности : Виды ценностей
СтавкаНДС : Ставки НДС
ДатаОплаты : Дата
ДокументОплаты : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
Событие : События по НДС (продажи)
ДатаСобытия : Дата
ЗаписьДополнительногоЛиста : Булево
КорректируемыйПериод : Дата
СторнирующаяЗаписьДопЛиста : Булево
ДоговорКонтрагента : Справочник.Договор с контрагентом\rСправочник.Договор лизинга
ИсправленныйСчетФактура : Документ.Счет-фактура выданный (аванс)\rДокумент.Корректировка реализации\rДокумент.Корректировка приобретения\r...
Исправление : Булево
ДатаСчетаФактурыКомиссионера : Дата
..Ресурсы..
СуммаБезНДС : Число 15, 2
НДС : Число 15, 2
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
НомерДокументаОплаты : Строка
ДатаДокументаОплаты : Дата
КодВидаОперации : Строка
РегламентнаяОперация : Булево
ВидДеятельностиНДС : Типы налогообложения НДС
НДСУпр : Число 15, 2
}
@enduml
