@startuml ПрочиеРасходы
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПрочиеРасходы as "Прочие расходы" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
НаправлениеДеятельности : Справочник.Направление деятельности
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
..Ресурсы..
Сумма : Число 15, 2
СуммаБезНДС : Число 15, 2
СуммаРегл : Число 15, 2
ПостояннаяРазница : Число 15, 2
ВременнаяРазница : Число 15, 2
СуммаУпр : Число 15, 2
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
СчетКт : Счет бухгалтерского учета
СуммаПрочихАктивов : Число 15, 2
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
ДокументДвижения : Документ.Распределение расходов на себестоимость продукции
КорСтатьяРасходов : Статья расходов
КорОрганизация : Справочник.Организация
ДоляСтоимости : Число 15, 5
КорПодразделение : Справочник.Подразделение
КорАналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
КорСтатьяКалькуляции : Справочник.Статьи калькуляции
РасчетСебестоимости : Булево
РасчетПартий : Булево
ИдентификаторСтроки : Строка
КорНаправлениеДеятельности : Справочник.Направление деятельности
ИсточникДвижений : Источники движений
}
@enduml
