@startuml РасчетыСПоставщикамиПоДокументам
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.РасчетыСПоставщикамиПоДокументам as "Расчеты с поставщиками по документам" <<РегистрыНакопления>>
{
..Измерения..
АналитикаУчетаПоПартнерам : Справочник.Ключ аналитики учета по партнерам
ЗаказПоставщику : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Приобретение товаров и услуг\r...
РасчетныйДокумент : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Приобретение товаров и услуг\r...
Валюта : Справочник.Валюта
УдалитьДатаПлатежа : Дата
..Ресурсы..
УдалитьКПоступлению : Число 15, 2
УдалитьКОплате : Число 15, 2
КВозврату : Число 15, 2
Долг : Число 15, 2
ДолгУпр : Число 15, 2
ДолгРегл : Число 15, 2
Предоплата : Число 15, 2
ПредоплатаУпр : Число 15, 2
ПредоплатаРегл : Число 15, 2
ЗалогЗаТару : Число 15, 2
ЗалогЗаТаруРегл : Число 15, 2
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
ДатаПлатежа : Дата
}
@enduml
