@startuml ТоварыКПоступлению
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ТоварыКПоступлению as "Товары к поступлению" <<РегистрыНакопления>>
{
..Измерения..
ДокументПоступления : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\rДокумент.Этап производства\r...
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Склад : Справочник.Склад (складская территория)
Отправитель : Справочник.Подразделение\rСправочник.Партнер\rСправочник.Физическое лицо\r...
ХозяйственнаяОперация : Хозяйственные операции
Серия : Справочник.Серия номенклатуры
..Ресурсы..
КОформлениюНакладныхПоРаспоряжению : Число 15, 3
КОформлениюПоступленийПоРаспоряжению : Число 15, 3
КОформлениюПоступленийПоНакладным : Число 15, 3
КОформлениюПоступленийПоОрдерам : Число 15, 3
КОформлениюОрдеров : Число 15, 3
Принимается : Число 15, 3
}
@enduml
