@startuml ПлановыеПрочиеЗатраты
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПлановыеПрочиеЗатраты as "Плановые прочие затраты" <<РегистрыНакопления>>
{
..Измерения..
Калькуляция : Документ.Плановая калькуляция
ПартияСпецификация : Документ.Этап производства\rСправочник.Ресурсная спецификация\rДокумент.Производство без заказа
Подразделение : Справочник.Подразделение
СтатьяКалькуляции : Справочник.Статьи калькуляции
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
..Ресурсы..
Стоимость : Число 15, 2
СтоимостьБезНДС : Число 15, 2
СтоимостьРегл : Число 15, 2
}
@enduml
