@startuml СведенияОДоходахНДФЛ
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.СведенияОДоходахНДФЛ as "Учет доходов для исчисления НДФЛ" <<РегистрыНакопления>>
{
..Измерения..
ГоловнаяОрганизация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
МесяцНалоговогоПериода : Дата
КодДохода : Справочник.Вид дохода НДФЛ
КодВычета : Справочник.Вид вычетов НДФЛ
КатегорияДохода : Категории доходов НДФЛ
СтавкаНалогообложения : Ставки НДФЛ
ИсточникДоходаЗаПределамиРФ : Булево
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
Организация : Справочник.Организация
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
УдалитьКодДохода : Справочник.(не используется) Виды доходов НДФЛ
..Ресурсы..
СуммаДохода : Число 15, 2
СуммаВычета : Число 15, 2
..Реквизиты..
Начисление : Справочник.Вид выплаты бывшему сотруднику\rСправочник.Вид прочего дохода\rВиды особых начислений и удержаний\r...
Подразделение : Справочник.Территория\rСправочник.Подразделение
Сотрудник : Справочник.Сотрудник
ДатаПолученияДохода : Дата
ДоходМежрасчетногоПериода : Булево
ВключатьВДекларациюПоНалогуНаПрибыль : Булево
ПодразделениеСотрудника : Справочник.Подразделение
УдалитьОрганизация : Справочник.Организация
НеУчитыватьДоходВ6НДФЛ : Булево
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
ДатаПолученияДоходаФиксирована : Булево
УстаревшаяДатаПолученияДохода : Дата
ДокументОснование : Документ.Сторнирование начислений\rДокумент.Перенос затрат\rДокумент.Приз, подарок\r...
Сторно : Булево
}
@enduml
