@startuml ТоварыКОтгрузке
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ТоварыКОтгрузке as "Товары к отгрузке" <<РегистрыНакопления>>
{
..Измерения..
Склад : Справочник.Склад (складская территория)
Получатель : Справочник.Подразделение\rСправочник.Партнер\rСправочник.Физическое лицо\r...
ДокументОтгрузки : Документ.Внутреннее потребление товаров\rДокумент.Акт о расхождениях после перемещения\rДокумент.Этап производства\r...
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
..Ресурсы..
ВРезерве : Число 15, 3
КОтгрузке : Число 15, 3
КОформлению : Число 15, 3
КСборке : Число 15, 3
Собирается : Число 15, 3
Собрано : Число 15, 3
..Реквизиты..
ЗаданиеНаПеревозку : Документ.Задание на перевозку
}
@enduml
