@startuml ФактическиеДанныеБюджетирования
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ФактическиеДанныеБюджетирования as "Фактические данные бюджетирования" <<РегистрыНакопления>>
{
..Измерения..
СтатьяБюджетов : Справочник.Статьи бюджетов
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Валюта : Справочник.Валюта
Аналитика1 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика2 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика3 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика4 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика5 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика6 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Правило : Справочник.Правила получения фактических данных по статьям бюджетов
..Ресурсы..
Количество : Число 15, 3
СуммаВВалюте : Число 15, 2
СуммаУпр : Число 15, 2
СуммаРегл : Число 15, 2
}
@enduml
