@startuml ДенежныеСредстваВПути
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДенежныеСредстваВПути as "Денежные средства в пути" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ВидПереводаДенежныхСредств : Виды переводов денежных средств
Получатель : Справочник.Кассы ККМ\rСправочник.Банковский счет организации\rСправочник.Касса
Отправитель : Справочник.Кассы ККМ\rСправочник.Банковский счет организации\rСправочник.Касса
Контрагент : Справочник.Контрагент
Валюта : Справочник.Валюта
..Ресурсы..
Сумма : Число 15, 2
СуммаУпр : Число 15, 2
СуммаРегл : Число 15, 2
..Реквизиты..
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
ХозяйственнаяОперация : Хозяйственные операции
}
@enduml
