@startuml РасчетыПоДоговорамКредитовИДепозитов
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.РасчетыПоДоговорамКредитовИДепозитов as "Расчеты по договорам кредитов и депозитов" <<РегистрыНакопления>>
{
..Измерения..
АналитикаУчетаПоПартнерам : Справочник.Ключ аналитики учета по партнерам
Договор : Справочник.Договор кредита (депозита)
ТипСуммы : Типы сумм графика кредитов и депозитов
..Ресурсы..
СуммаВВалюте : Число 15, 2
СуммаУпр : Число 15, 2
СуммаРегл : Число 15, 2
..Реквизиты..
ТипГрафика : Типы графика кредитов и депозитов
СтатьяАналитики : Статья расходов\rСправочник.Статья движения денежных средств\rСтатьи доходов
}
@enduml
