@startuml ПланыСборкиРазборки
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПланыСборкиРазборки as "Планы сборки (разборки)" <<РегистрыНакопления>>
{
..Измерения..
Сценарий : Справочник.Сценарии товарного планирования
Статус : Статусы планов
Склад : Справочник.Склад (складская территория)
ХозяйственнаяОперация : Хозяйственные операции
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
ВариантКомплектации : Справочник.Вариант комплектации
ПланСборкиРазборки : Документ.План сборки (разборки)
Назначение : Справочник.Назначение
ВидПлана : Справочник.Вид плана
..Ресурсы..
Количество : Число 15, 3
}
@enduml
