@startuml ПлановыеТрудозатраты
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПлановыеТрудозатраты as "Плановые трудозатраты" <<РегистрыНакопления>>
{
..Измерения..
Калькуляция : Документ.Плановая калькуляция
ПартияСпецификация : Документ.Этап производства\rСправочник.Ресурсная спецификация\rДокумент.Производство без заказа
Подразделение : Справочник.Подразделение
СтатьяКалькуляции : Справочник.Статьи калькуляции
ВидРабот : Справочник.Вид работ сотрудников
..Ресурсы..
Количество : Число 15, 3
Стоимость : Число 15, 2
СтоимостьРегл : Число 15, 2
..Реквизиты..
ПериодЗатрат : Дата
}
@enduml
