@startuml ДанныеИндивидуальныхГрафиковСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДанныеИндивидуальныхГрафиковСотрудников as "Данные индивидуальных графиков сотрудников" <<РегистрыНакопления>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ПериодРегистрации : Дата
ВидУчетаВремени : Справочник.Вид рабочего времени
..Ресурсы..
Дни : Число 1, 0
Часы : Число 5, 3
}
@enduml
