@startuml ИсчисленныеСтраховыеВзносы
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ИсчисленныеСтраховыеВзносы as "Исчисленные страховые взносы" <<РегистрыНакопления>>
{
..Измерения..
ГоловнаяОрганизация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
Организация : Справочник.Организация
..Ресурсы..
ПФРДоПредельнойВеличины : Число 15, 2
ПФРДоПредельнойВеличиныЕНВД : Число 15, 2
ПФРСПревышения : Число 15, 2
ПФРСПревышенияЕНВД : Число 15, 2
ПФРПоСуммарномуТарифу : Число 15, 2
ПФРПоСуммарномуТарифуЕНВД : Число 15, 2
ПФРПоСуммарномуТарифуСПревышения : Число 15, 2
ФСС : Число 15, 2
ФССЕНВД : Число 15, 2
ФССНесчастныеСлучаи : Число 15, 2
ФФОМС : Число 15, 2
ФФОМСЕНВД : Число 15, 2
ПФРСтраховая : Число 15, 2
ПФРНакопительная : Число 15, 2
ПФРСтраховаяЕНВД : Число 15, 2
ПФРСтраховаяСПревышения : Число 15, 2
ПФРНакопительнаяЕНВД : Число 15, 2
ПФРНаДоплатуЛетчикам : Число 15, 2
ПФРНаДоплатуШахтерам : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботах : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахОпасный : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный1 : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный2 : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный3 : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахВредный4 : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботах : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахОпасный : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный1 : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный2 : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный3 : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахВредный4 : Число 15, 2
ТФОМС : Число 15, 2
ТФОМСЕНВД : Число 15, 2
..Реквизиты..
ДатаПолученияДохода : Дата
ОснованиеДляДоначисления : Основания для доначисления страховых взносов
Сторно : Булево
}
@enduml
