@startuml ДенежныеСредстваНаличные
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДенежныеСредстваНаличные as "Денежные средства (наличные)" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
Касса : Справочник.Касса
..Ресурсы..
Сумма : Число 15, 2
СуммаУпр : Число 15, 2
СуммаРегл : Число 15, 2
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
АналитикаУчетаПоПартнерам : Справочник.Ключ аналитики учета по партнерам
Заказ : Документ.Заказ поставщику\rДокумент.Заказ клиента
}
@enduml
