@startuml ДниЧасыОтгулов
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДниЧасыОтгулов as "Дни часы отгулов" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
..Ресурсы..
Дни : Число 5, 2
Часы : Число 5, 2
..Реквизиты..
Сторно : Булево
}
@enduml
