@startuml ВыручкаИСебестоимостьПродаж
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ВыручкаИСебестоимостьПродаж as "Выручка и себестоимость продаж" <<РегистрыНакопления>>
{
..Измерения..
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ЗаказКлиента : Документ.Отчет давальцу\rДокумент.Заявка на возврат товаров от клиента\rДокумент.Реализация товаров и услуг\r...
АналитикаУчетаПоПартнерам : Справочник.Ключ аналитики учета по партнерам
Подразделение : Справочник.Подразделение
ТипЗапасов : Типы запасов
ВидЗапасов : Справочник.Вид запасов
РазделУчета : Разделы учета себестоимости товаров
Партия : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\rДокумент.Таможенная декларация на импорт\r...
АналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
АналитикаФинансовогоУчета : Справочник.Подразделение\rСправочник.Пользователь\rСправочник.Сделка с клиентом\r...
ВидДеятельностиНДС : Типы налогообложения НДС
Менеджер : Справочник.Пользователь
Склад : Справочник.Организация\rСправочник.Подразделение\rСправочник.Партнер\r...
Соглашение : Справочник.Соглашение об условиях продаж
Договор : Справочник.Договор между организациями\rСправочник.Договор с контрагентом
ХозяйственнаяОперация : Хозяйственные операции
АналитикаУчетаНаборов : Справочник.Ключ аналитики учета наборов
НаправлениеДеятельностиКонтрагента : Справочник.Направление деятельности
НаправлениеДеятельностиНоменклатуры : Справочник.Направление деятельности
..Ресурсы..
Количество : Число 15, 3
СуммаВыручки : Число 15, 2
СуммаВыручкиБезНДС : Число 15, 2
Стоимость : Число 15, 2
СтоимостьБезНДС : Число 15, 2
ДопРасходы : Число 15, 2
ДопРасходыБезНДС : Число 15, 2
СтоимостьУпр : Число 15, 2
СтоимостьРегл : Число 15, 2
СтоимостьЗабалансовая : Число 15, 2
СтоимостьЗабалансоваяРегл : Число 15, 2
СуммаВыручкиРегл : Число 15, 2
ПостояннаяРазница : Число 15, 2
ДопРасходыУпр : Число 15, 2
ДопРасходыРегл : Число 15, 2
ПостатейныеПостоянныеСНДС : Число 15, 2
ПостатейныеПостоянныеБезНДС : Число 15, 2
ПостатейныеПостоянныеУпр : Число 15, 2
ПостатейныеПостоянныеРегл : Число 15, 2
Трудозатраты : Число 15, 2
ТрудозатратыУпр : Число 15, 2
ТрудозатратыРегл : Число 15, 2
ПостатейныеПеременныеСНДС : Число 15, 2
ПостатейныеПеременныеБезНДС : Число 15, 2
ПостатейныеПеременныеУпр : Число 15, 2
ПостатейныеПеременныеРегл : Число 15, 2
ВременнаяРазница : Число 15, 2
СуммаВыручкиСНДСРегл : Число 15, 2
СуммаРучнойСкидки : Число 15, 2
СуммаАвтоматическойСкидки : Число 15, 2
..Реквизиты..
НалогообложениеНДС : Типы налогообложения НДС
ВалютаВзаиморасчетов : Справочник.Валюта
СуммаВВалютеВзаиморасчетов : Число 15, 2
СуммаБезНДСВВалютеВзаиморасчетов : Число 15, 2
ВалютаДокумента : Справочник.Валюта
СуммаВВалютеДокумента : Число 15, 2
СуммаБезНДСВВалютеДокумента : Число 15, 2
ИсточникГФУНоменклатуры : Справочник.Номенклатура\rСправочник.Вид запасов
ИсточникГФУРасчетов : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\rДокумент.Таможенная декларация на импорт\r...
ДокументДвижения : Документ.Возврат товаров от клиента\rДокумент.Отчет комиссионера (агента) о продажах\rДокумент.Отчет давальцу\r...
РасчетСебестоимости : Булево
РасчетПартий : Булево
РасчетНеЗавершен : Булево
}
@enduml
