@startuml ДвиженияДенежныеСредстваКонтрагент
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДвиженияДенежныеСредстваКонтрагент as "Движения Денежные средства - Контрагент" <<РегистрыНакопления>>
{
..Измерения..
ХозяйственнаяОперация : Хозяйственные операции
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
НаправлениеДеятельностиДС : Справочник.Направление деятельности
ДенежныеСредства : Справочник.Денежный документ\rСправочник.Кассы ККМ\rСправочник.Договор кредита (депозита)\r...
ТипДенежныхСредств : Типы денежных средств
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
ВалютаПлатежа : Справочник.Валюта
СтатьяКалькуляции : Справочник.Статьи калькуляции
ТипПлатежаФЗ275 : Справочник.Типы платежей 275-ФЗ
НаправлениеДеятельностиКонтрагента : Справочник.Направление деятельности
Партнер : Справочник.Партнер
Контрагент : Справочник.Организация\rСправочник.Контрагент
Договор : Справочник.Договор между организациями\rСправочник.Договор с контрагентом\rСправочник.Договор кредита (депозита)
ОбъектРасчетов : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
РасчетныйДокумент : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
..Ресурсы..
СуммаОплаты : Число 15, 2
СуммаОплатыРегл : Число 15, 2
СуммаОплатыВВалютеПлатежа : Число 15, 2
СуммаПостоплаты : Число 15, 2
СуммаПостоплатыРегл : Число 15, 2
СуммаПостоплатыВВалютеПлатежа : Число 15, 2
СуммаПредоплаты : Число 15, 2
СуммаПредоплатыРегл : Число 15, 2
СуммаПредоплатыВВалютеПлатежа : Число 15, 2
СуммаКВыплатеВРамкахЛимита : Число 15, 2
СуммаКВыплатеСверхЛимита : Число 15, 2
СуммаНДС : Число 15, 2
СуммаНДСРегл : Число 15, 2
СуммаНДСВВалютеПлатежа : Число 15, 2
..Реквизиты..
ВалютаВзаиморасчетов : Справочник.Валюта
СуммаОплатыВВалютеВзаиморасчетов : Число 15, 2
СуммаПостоплатыВВалютеВзаиморасчетов : Число 15, 2
СуммаПредоплатыВВалютеВзаиморасчетов : Число 15, 2
ИсточникГФУДенежныхСредств : Справочник.Договор кредита (депозита)\rСправочник.Банковский счет организации\rСправочник.Касса
ИсточникГФУРасчетов : Документ.Приобретение товаров и услуг\rДокумент.Таможенная декларация на импорт\rДокумент.Отчет комиссионера (агента) о продажах\r...
ОтложенноеПроведение : Булево
СтавкаНДС : Ставки НДС
}
@enduml
