@startuml ПособияПоСоциальномуСтрахованию
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПособияПоСоциальномуСтрахованию as "Пособия по социальному страхованию" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ВидПособияСоциальногоСтрахования : Перечень пособий социального страхования
ФизическоеЛицо : Справочник.Физическое лицо
ВидЗанятости : Виды занятости
ФинансированиеФедеральнымБюджетом : Основания финансирования пособия федеральным бюджетом
..Ресурсы..
СтраховыеСлучаи : Число 5, 0
ОплаченныеДни : Число 5, 0
СуммаВсего : Число 15, 2
СуммаСверхНорм : Число 15, 2
СуммаФинансируемаяРаботодателем : Число 15, 2
..Реквизиты..
Сотрудник : Справочник.Сотрудник\rСправочник.Физическое лицо
ДатаСтраховогоСлучая : Дата
Сторно : Булево
}
@enduml
