@startuml ДанныеОперативногоУчетаРабочегоВремениСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДанныеОперативногоУчетаРабочегоВремениСотрудников as "Данные оперативного учета рабочего времени сотрудников" <<РегистрыНакопления>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ПериодРегистрации : Дата
ВидУчетаВремени : Справочник.Вид рабочего времени
ВидДанных : Виды данных учета времени сотрудников
..Ресурсы..
Дни : Число 1, 0
Часы : Число 5, 3
}
@enduml
