@startuml УплатаНДФЛНалоговымиАгентамиКРаспределению
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.УплатаНДФЛНалоговымиАгентамиКРаспределению as "Уплата НДФЛ налоговыми агентами (к распределению)" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
РеквизитыПлатежногоПоручения : Строка
ДатаПлатежа : Дата
МесяцНалоговогоПериода : Дата
..Ресурсы..
Сумма : Число 15, 2
..Реквизиты..
Сторно : Булево
}
@enduml
