@startuml КонтролируемыеСделкиОрганизаций
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.КонтролируемыеСделкиОрганизаций as "Контролируемые сделки организаций" <<РегистрыНакопления>>
{
..Измерения..
Уведомление : Документ.Уведомление о контролируемых сделках
Организация : Справочник.Организация
Контрагент : Справочник.Организация\rСправочник.Контрагент
УдалитьАналитика : Справочник.Договор с контрагентом\rСправочник.Соглашение об условиях закупок\rСправочник.Договор кредита (депозита)\r...
ПредметСделки : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР
РасчетныйДокумент : Документ.Передача давальцу\rДокумент.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\r...
ХозяйственнаяОперация : Хозяйственные операции контролируемых сделок
Валюта : Справочник.Валюта
ЕдиницаИзмерения : Справочник.Упаковка
Договор : Справочник.Договор между организациями\rСправочник.Договор с контрагентом\rСправочник.Договор кредита (депозита)\r...
Соглашение : Справочник.Соглашение об условиях закупок\rСправочник.Соглашение об условиях продаж
..Ресурсы..
Количество : Число 15, 3
СуммаБезНДСВРублях : Число 15, 2
СуммаНДСВРублях : Число 15, 2
СуммаБезНДСВВалютеРасчетов : Число 15, 2
СуммаНДСВВалютеРасчетов : Число 15, 2
..Реквизиты..
НаименованиеПредметаСделки : Строка
ТипПредметаСделки : Типы предметов контролируемых сделок
СтранаПроисхожденияПредметаСделки : Справочник.Страна мира
СтавкаНДС : Ставки НДС
ТипКонтролируемойСделки : Типы контролируемых сделок
Грузоотправитель : Справочник.Организация\rСправочник.Контрагент
Грузополучатель : Справочник.Организация\rСправочник.Контрагент
ОперацияОблагаетсяЕНВД : Булево
}
@enduml
