@startuml ЗначенияОперативныхПоказателейРасчетаЗарплатыСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ЗначенияОперативныхПоказателейРасчетаЗарплатыСотрудников as "Значения оперативных показателей расчета зарплаты (для сотрудников)" <<РегистрыНакопления>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
Показатель : Справочник.Показатель
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
Значение : Число 15, 5
..Реквизиты..
Сторно : Булево
}
@enduml
