@startuml УслугиДавальцуКОформлению
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.УслугиДавальцуКОформлению as "Услуги давальцу к оформлению" <<РегистрыНакопления>>
{
..Измерения..
ЗаказДавальца : Документ.Заказ давальца
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
..Ресурсы..
Заказано : Число 15, 3
КОформлению : Число 15, 3
Сумма : Число 15, 2
..Реквизиты..
ПричинаОтмены : Справочник.Причина отмены заказов клиентов
НалогообложениеНДС : Типы налогообложения НДС
}
@enduml
