@startuml ДвижениеТоваров
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДвижениеТоваров as "Движение товаров" <<РегистрыНакопления>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Склад : Справочник.Склад (складская территория)
Назначение : Справочник.Назначение
Распоряжение : Документ.Расходный ордер на товары\rДокумент.Приобретение товаров и услуг\rДокумент.Этап производства\r...
..Ресурсы..
ПланируемоеПоступление : Число 15, 3
ПланируемоеПоступлениеПодЗаказ : Число 15, 3
ПланируемоеПоступлениеСНеподтвержденными : Число 15, 3
ПланируемоеПоступлениеПодЗаказСНеподтвержденными : Число 15, 3
..Реквизиты..
Корректировка : Булево
ДатаРаспоряжения : Дата
}
@enduml
