@startuml ВыпускПродукции
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ВыпускПродукции as "Выпуск продукции" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
Распоряжение : Документ.Этап производства\rДокумент.Маршрутный лист производства
КодСтроки : Число 10, 0
Заказ : Документ.Заказ поставщику\rДокумент.Заказ на производство\rДокумент.Заказ материалов в производство\r...
ВидЗапасов : Справочник.Вид запасов
Спецификация : Справочник.Ресурсная спецификация
Подразделение : Справочник.Подразделение
СтатьяРасходов : Статья расходов\rСтатья актива/пассива
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
..Ресурсы..
Количество : Число 10, 3
..Реквизиты..
АналитикаУчетаПродукции : Справочник.Ключ аналитики учета номенклатуры
}
@enduml
