@startuml ВытесняемоеПлановоеВремяСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ВытесняемоеПлановоеВремяСотрудников as "Вытесняемое плановое время сотрудников" <<РегистрыНакопления>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ПериодРегистрации : Дата
ВидУчетаВремени : Справочник.Вид рабочего времени
..Ресурсы..
Часы : Число 5, 3
}
@enduml
