@startuml НДСЗаписиКнигиПокупок
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.НДСЗаписиКнигиПокупок as "НДС Покупки" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
Поставщик : Справочник.Организация\rСправочник.Контрагент
СчетФактура : Документ.Запись книги покупок\rДокумент.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\r...
ВидЦенности : Виды ценностей
СтавкаНДС : Ставки НДС
СчетУчетаНДС : Счет бухгалтерского учета
ДатаОплаты : Дата
ДокументОплаты : Документ.Запись книги покупок\rДокумент.Расходный кассовый ордер\rДокумент.Первичный документ\r...
Событие : События по НДС (покупки)
ДатаСобытия : Дата
ЗаписьДополнительногоЛиста : Булево
КорректируемыйПериод : Дата
ДоговорКонтрагента : Справочник.Договор с контрагентом\rСправочник.Договор лизинга
ИсправленныйСчетФактура : Документ.Счет-фактура полученный (аванс)\rДокумент.Счет-фактура выданный (аванс)\rДокумент.Корректировка реализации\r...
..Ресурсы..
СуммаБезНДС : Число 15, 2
НДС : Число 15, 2
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
НомерДокументаОплаты : Строка
ДатаДокументаОплаты : Дата
КодВидаОперации : Строка
РегламентнаяОперация : Булево
ДокументОтгрузки : Документ.Реализация товаров и услуг\rДокумент.Акт выполненных работ
ВидДеятельностиНДС : Типы налогообложения НДС
НДСУпр : Число 15, 2
}
@enduml
