@startuml ПредоставленныеСтандартныеИСоциальныеВычетыНДФЛ
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПредоставленныеСтандартныеИСоциальныеВычетыНДФЛ as "Предоставленные стандартные и социальные вычеты (НДФЛ)" <<РегистрыНакопления>>
{
..Измерения..
ГоловнаяОрганизация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
МесяцНалоговогоПериода : Дата
КодВычета : Справочник.Вид вычетов НДФЛ
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
Организация : Справочник.Организация
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
..Ресурсы..
Сумма : Число 15, 2
..Реквизиты..
УдалитьОрганизация : Справочник.Организация
Подразделение : Справочник.Территория\rСправочник.Подразделение
ВычетМежрасчетногоПериода : Булево
ВключатьВДекларациюПоНалогуНаПрибыль : Булево
Сторно : Булево
}
@enduml
