@startuml ТоварыОрганизацийКПередаче
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ТоварыОрганизацийКПередаче as "Товары организаций к передаче" <<РегистрыНакопления>>
{
..Измерения..
ОрганизацияВладелец : Справочник.Организация
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ВидЗапасовПродавца : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
..Ресурсы..
Количество : Число 15, 3
Возвращено : Число 15, 3
..Реквизиты..
НалогообложениеНДС : Типы налогообложения НДС
ХозяйственнаяОперация : Хозяйственные операции
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КорВидЗапасов : Справочник.Вид запасов
Первичное : Булево
ДокументРеализации : Документ.Внутреннее потребление товаров\rДокумент.Приобретение товаров и услуг\rДокумент.Этап производства\r...
}
@enduml
