@startuml ЗаказыНаВнутреннееПотребление
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ЗаказыНаВнутреннееПотребление as "Заказы на внутреннее потребление" <<РегистрыНакопления>>
{
..Измерения..
ЗаказНаВнутреннееПотребление : Документ.Заказ на ремонт\rДокумент.Заказ на внутреннее потребление
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КодСтроки : Число 10, 0
Склад : Справочник.Склад (складская территория)
Серия : Справочник.Серия номенклатуры
..Ресурсы..
Заказано : Число 15, 3
КОформлению : Число 15, 3
}
@enduml
