@startuml ЗаказыМатериаловСУчетомКорректировок
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ЗаказыМатериаловСУчетомКорректировок as "Заказы материалов с учетом корректировок" <<РегистрыНакопления>>
{
..Измерения..
Распоряжение : Документ.Заказ на производство\rДокумент.Заказ материалов в производство
КодСтрокиРаспоряжения : Число 10, 0
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ВариантОбеспечения : Варианты обеспечения
ДатаПотребности : Дата
КодСтроки : Число 10, 0
Отменено : Булево
ПроизводствоНаСтороне : Булево
Серия : Справочник.Серия номенклатуры
Склад : Справочник.Склад (складская территория)
Упаковка : Справочник.Упаковка
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
..Ресурсы..
Количество : Число 15, 3
КоличествоУпаковок : Число 15, 3
}
@enduml
