@startuml ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаФСС
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаФСС as "Данные о начислениях для расчета среднего заработка (ФСС)" <<РегистрыНакопления>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
ГоловнаяОрганизация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ПорядокРасчета : Порядок расчета среднего заработка ФСС
СтатьяФинансирования : Справочник.Статья финансирования
..Ресурсы..
Сумма : Число 15, 2
..Реквизиты..
Сторно : Булево
}
@enduml
