@startuml ОценочныеОбязательстваПоСотрудникам
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ОценочныеОбязательстваПоСотрудникам as "Оценочные обязательства по сотрудникам" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
СтатьяФинансирования : Справочник.Статья финансирования
..Ресурсы..
СуммаРезерва : Число 15, 2
СуммаРезерваСтраховыхВзносов : Число 15, 2
СуммаРезерваФССНесчастныеСлучаи : Число 15, 2
СуммаРезерваНУ : Число 15, 2
СуммаРезерваСтраховыхВзносовНУ : Число 15, 2
СуммаРезерваФССНесчастныеСлучаиНУ : Число 15, 2
..Реквизиты..
Сторно : Булево
}
@enduml
