@startuml СтраховыеВзносыПоФизическимЛицам
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.СтраховыеВзносыПоФизическимЛицам as "Страховые взносы по физическим лицам" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
Начисление : Справочник.Вид выплаты бывшему сотруднику\rСправочник.Вид прочего дохода\rВиды особых начислений и удержаний\r...
..Ресурсы..
ПФРДоПредельнойВеличины : Число 15, 2
ПФРСПревышения : Число 15, 2
ПФРПоСуммарномуТарифу : Число 15, 2
ФСС : Число 15, 2
ФССНесчастныеСлучаи : Число 15, 2
ФФОМС : Число 15, 2
ПФРНаДоплатуЛетчикам : Число 15, 2
ПФРНаДоплатуШахтерам : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботах : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботах : Число 15, 2
ПФРСтраховая : Число 15, 2
ПФРНакопительная : Число 15, 2
ТФОМС : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахБезСпецОценки : Число 15, 2
ПФРЗаЗанятыхНаПодземныхИВредныхРаботахСпецОценка : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахБезСпецОценки : Число 15, 2
ПФРЗаЗанятыхНаТяжелыхИПрочихРаботахСпецОценка : Число 15, 2
..Реквизиты..
ОблагаетсяЕНВД : Булево
ДатаНачала : Дата
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
Сторно : Булево
}
@enduml
