@startuml УслугиПереработчиковКОформлению
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.УслугиПереработчиковКОформлению as "Услуги переработчиков к оформлению" <<РегистрыНакопления>>
{
..Измерения..
ЗаказПереработчику : Документ.Заказ переработчику
..Ресурсы..
Сумма : Число 15, 2
}
@enduml
