@startuml СвободныеОстатки
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.СвободныеОстатки as "Свободные остатки" <<РегистрыНакопления>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Склад : Справочник.Склад (складская территория)
..Ресурсы..
ВНаличии : Число 15, 3
ВРезервеСоСклада : Число 15, 3
ВРезервеПодЗаказ : Число 15, 3
}
@enduml
