@startuml ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаОбщий
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДанныеОНачисленияхДляРасчетаСреднегоЗаработкаОбщий as "Данные о начислениях для расчета среднего заработка (общий)" <<РегистрыНакопления>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ПорядокРасчета : Порядок расчета среднего заработка общий
СоставнаяЧасть : Учет начислений в среднем заработке общий
СтатьяФинансирования : Справочник.Статья финансирования
Индексируется : Булево
Год : Число 4, 0
ДатаНачалаБазовогоПериода : Дата
КоличествоМесяцев : Число 3, 0
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
Сумма : Число 15, 2
..Реквизиты..
Сторно : Булево
}
@enduml
