@startuml УслугиКОформлениюОтчетовПринципалу
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.УслугиКОформлениюОтчетовПринципалу as "Услуги к оформлению отчетов принципалу" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
Соглашение : Справочник.Соглашение об условиях закупок
Валюта : Справочник.Валюта
..Ресурсы..
Количество : Число 15, 3
СуммаВыручки : Число 15, 2
СуммаНДС : Число 15, 2
..Реквизиты..
СуммаВознаграждения : Число 15, 2
ДокументРеализации : Документ.Реализация товаров и услуг\rДокумент.Акт выполненных работ\rДокумент.Отчет о розничных продажах\r...
ДатаСчетаФактуры : Дата
Покупатель : Справочник.Контрагент
НомерСчетаФактуры : Строка
}
@enduml
