@startuml ПланыПродаж
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПланыПродаж as "Планы продаж" <<РегистрыНакопления>>
{
..Измерения..
Сценарий : Справочник.Сценарии товарного планирования
Статус : Статусы планов
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Подразделение : Справочник.Подразделение
Склад : Справочник.Склад (складская территория)
Партнер : Справочник.Партнер
Соглашение : Справочник.Соглашение об условиях продаж
ПланПродаж : Документ.План продаж
ФорматМагазина : Справочник.Форматы магазинов
Менеджер : Справочник.Пользователь
Назначение : Справочник.Назначение
ВидПлана : Справочник.Вид плана
..Ресурсы..
Количество : Число 15, 3
Сумма : Число 15, 2
}
@enduml
