@startuml ЗаказыНаСборку
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ЗаказыНаСборку as "Заказы на сборку" <<РегистрыНакопления>>
{
..Измерения..
ЗаказНаСборку : Документ.Заказ на сборку (разборку)
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
ТипСборки : Типы движения запасов
КодСтроки : Число 10, 0
Серия : Справочник.Серия номенклатуры
..Ресурсы..
Заказано : Число 15, 3
КОформлению : Число 15, 3
}
@enduml
