@startuml ТоварыКОформлениюОтчетовКомитенту
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ТоварыКОформлениюОтчетовКомитенту as "Товары к оформлению отчетов комитенту" <<РегистрыНакопления>>
{
..Измерения..
ВидЗапасов : Справочник.Вид запасов
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
Валюта : Справочник.Валюта
НомерГТД : Справочник.Номер ГТД
..Ресурсы..
Количество : Число 15, 3
СуммаВыручки : Число 15, 2
КоличествоСписано : Число 15, 3
КоличествоКОформлению : Число 15, 3
СуммаВыручкиКОформлению : Число 15, 2
КоличествоСписаноКОформлению : Число 15, 3
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
СуммаВознаграждения : Число 15, 2
ДокументРеализации : Документ.Внутреннее потребление товаров\rДокумент.Этап производства\rДокумент.Движение продукции и материалов\r...
ДатаСчетаФактуры : Дата
Покупатель : Справочник.Организация\rСправочник.Контрагент
КорВидЗапасов : Справочник.Вид запасов
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
НомерСчетаФактуры : Строка
КорАналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
НалогообложениеНДС : Типы налогообложения НДС
}
@enduml
