@startuml РаспоряженияНаСписаниеПоНормативам
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.РаспоряженияНаСписаниеПоНормативам as "Распоряжения на списание по нормативам" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
УдалитьСерия : Справочник.Серия номенклатуры
УдалитьСпецификация : Справочник.Ресурсная спецификация
Распоряжение : Документ.Выпуск продукции и выполнение работ
КодСтроки : Число 10, 0
Назначение : Справочник.Назначение
..Ресурсы..
Количество : Число 15, 3
..Реквизиты..
АналитикаУчетаПродукции : Справочник.Ключ аналитики учета номенклатуры
КорРазделУчета : Разделы учета себестоимости товаров
КорВидЗапасов : Справочник.Вид запасов
}
@enduml
