@startuml БухучетНачисленияУдержанияПоСотрудникам
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.БухучетНачисленияУдержанияПоСотрудникам as "Бухучет начисления удержания по сотрудникам" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
НачислениеУдержание : Виды взаиморасчетов с сотрудниками\rВиды особых начислений и удержаний\rНачисление\r...
..Ресурсы..
Сумма : Число 15, 2
..Реквизиты..
ГруппаНачисленияУдержанияВыплаты : Группы начисления удержания выплаты
ПериодДействия : Дата
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Приз, подарок\rДокумент.Удержание по прочим операциям\r...
Контрагент : Справочник.Контрагент
ДатаНачала : Дата
ДатаОкончания : Дата
ИдентификаторСтроки : Число 7, 0
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОблагаетсяЕНВД : Булево
ВидОперации : Виды операций по зарплате
НеУчитыватьВРаспределенииПриОкончательномРасчете : Булево
ПервичныйРегистратор : Документ.Сторнирование начислений\rДокумент.Единовременное пособие\rДокумент.Перенос затрат\r...
ТерриторияВыполненияРаботВОрганизации : Справочник.Территория\rСправочник.Подразделение
ДатаПолученияДохода : Дата
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
ДатаПолученияДоходаФиксирована : Булево
УстаревшаяДатаПолученияДохода : Дата
КатегорияДохода : Категории доходов НДФЛ
Сторно : Булево
}
@enduml
