@startuml ГрафикОтгрузкиТоваров
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ГрафикОтгрузкиТоваров as "График отгрузки товаров" <<РегистрыНакопления>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Склад : Справочник.Склад (складская территория)
Назначение : Справочник.Назначение
ДатаОтгрузки : Дата
..Ресурсы..
КоличествоИзЗаказов : Число 15, 3
КоличествоПодЗаказ : Число 15, 3
КоличествоНеобеспечено : Число 15, 3
..Реквизиты..
Распоряжение : Документ.Заказ на производство
}
@enduml
