@startuml УдалитьВыплатаОтпусковЗаСчетРезерва
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.УдалитьВыплатаОтпусковЗаСчетРезерва as "(Не используется) Выплата отпусков за счет резерва" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
Сотрудник : Справочник.Сотрудник
ФизическоеЛицо : Справочник.Физическое лицо
..Ресурсы..
СуммаРезерваВыбыло : Число 15, 2
СуммаРезерваСтраховыхВзносовВыбыло : Число 15, 2
СуммаРезерваВыбылоНУ : Число 15, 2
СуммаРезерваСтраховыхВзносовВыбылоНУ : Число 15, 2
СуммаРезерваФССНесчастныеСлучаиВыбыло : Число 15, 2
СуммаРезерваФССНесчастныеСлучаиВыбылоНУ : Число 15, 2
..Реквизиты..
Сторно : Булево
}
@enduml
