@startuml Закупки
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.Закупки as "Закупки" <<РегистрыНакопления>>
{
..Измерения..
ХозяйственнаяОперация : Хозяйственные операции
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Менеджер : Справочник.Пользователь
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
Склад : Справочник.Подразделение\rСправочник.Партнер\rСправочник.Склад (складская территория)
ТипЗапасов : Типы запасов
ВидЗапасов : Справочник.Вид запасов
Партнер : Справочник.Партнер
Контрагент : Справочник.Организация\rСправочник.Контрагент
Соглашение : Справочник.Соглашение об условиях закупок
Договор : Справочник.Договор между организациями\rСправочник.Договор с контрагентом
Заказ : Документ.Приобретение товаров и услуг\rДокумент.Заказ поставщику\rДокумент.Заявка на возврат товаров от клиента\r...
НаправлениеДеятельностиНоменклатуры : Справочник.Направление деятельности
НаправлениеДеятельностиКонтрагента : Справочник.Направление деятельности
ПодотчетноеЛицо : Справочник.Физическое лицо
..Ресурсы..
Количество : Число 15, 3
Сумма : Число 15, 2
СуммаБезНДС : Число 15, 2
СуммаРегл : Число 15, 2
СуммаРеглБезНДС : Число 15, 2
СуммаСкидки : Число 15, 2
Стоимость : Число 15, 2
СтоимостьБезНДС : Число 15, 2
СтоимостьРегл : Число 15, 2
СуммаДопРасходов : Число 15, 2
СуммаДопРасходовБезНДС : Число 15, 2
..Реквизиты..
ВалютаДокумента : Справочник.Валюта
СуммаВВалютеДокумента : Число 15, 2
СуммаБезНДСВВалютеДокумента : Число 15, 2
ВалютаВзаиморасчетов : Справочник.Валюта
СуммаВВалютеВзаиморасчетов : Число 15, 2
СуммаБезНДСВВалютеВзаиморасчетов : Число 15, 2
ИсточникГФУНоменклатуры : Справочник.Номенклатура\rСправочник.Вид запасов
ИсточникГФУРасчетов : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\rДокумент.Таможенная декларация на импорт\r...
ДокументДвижения : Документ.Расходный кассовый ордер\rДокумент.Приобретение товаров и услуг\rДокумент.Таможенная декларация на импорт\r...
РасчетСебестоимости : Булево
}
@enduml
