@startuml ФактическиеОтпуска
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ФактическиеОтпуска as "Фактические отпуска" <<РегистрыНакопления>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ВидЕжегодногоОтпуска : Справочник.Вид отпуска
..Ресурсы..
Количество : Число 5, 2
..Реквизиты..
ДатаНачала : Дата
ДатаОкончания : Дата
Компенсация : Булево
ДатаРегистрации : Дата
РабочийПериодС : Дата
РабочийПериодПо : Дата
Основание : Строка
ПериодНачисления : Дата
Сторно : Булево
}
@enduml
