@startuml СебестоимостьТоваров
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.СебестоимостьТоваров as "Себестоимость товаров" <<РегистрыНакопления>>
{
..Измерения..
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
РазделУчета : Разделы учета себестоимости товаров
ВидЗапасов : Справочник.Вид запасов
Организация : Справочник.Организация
Партия : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\rДокумент.Таможенная декларация на импорт\r...
АналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
АналитикаФинансовогоУчета : Справочник.Подразделение\rСправочник.Пользователь\rСправочник.Сделка с клиентом\r...
ВидДеятельностиНДС : Типы налогообложения НДС
..Ресурсы..
Количество : Число 15, 3
Стоимость : Число 15, 2
СтоимостьБезНДС : Число 15, 2
СтоимостьЗабалансовая : Число 15, 2
ДопРасходы : Число 15, 2
ДопРасходыБезНДС : Число 15, 2
Трудозатраты : Число 15, 2
ПостатейныеПостоянныеСНДС : Число 15, 2
ПостатейныеПеременныеСНДС : Число 15, 2
ПостатейныеПостоянныеБезНДС : Число 15, 2
ПостатейныеПеременныеБезНДС : Число 15, 2
СтоимостьРегл : Число 15, 2
СтоимостьЗабалансоваяРегл : Число 15, 2
ДопРасходыРегл : Число 15, 2
ТрудозатратыРегл : Число 15, 2
ПостатейныеПостоянныеРегл : Число 15, 2
ПостатейныеПеременныеРегл : Число 15, 2
ПостояннаяРазница : Число 15, 2
ВременнаяРазница : Число 15, 2
СтоимостьУпр : Число 15, 2
ДопРасходыУпр : Число 15, 2
ТрудозатратыУпр : Число 15, 2
ПостатейныеПостоянныеУпр : Число 15, 2
ПостатейныеПеременныеУпр : Число 15, 2
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
КорАналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
КорРазделУчета : Разделы учета себестоимости товаров
КорВидЗапасов : Справочник.Вид запасов
КорОрганизация : Справочник.Организация
КорСтоимость : Число 15, 2
АналитикаУчетаПоПартнерам : Справочник.Ключ аналитики учета по партнерам
ЗаказКлиента : Документ.Передача давальцу\rДокумент.Заявка на возврат товаров от клиента\rДокумент.Реализация товаров и услуг\r...
Подразделение : Справочник.Подразделение
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
СтатьяРасходовСписания : Статья расходов
СтатьяДоходов : Статьи доходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
ПериодПродажи : Дата
СтатьяАктивовПассивов : Статья актива/пассива
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
ДокументДвижения : Документ.Внутреннее потребление товаров\rДокумент.Расходный кассовый ордер\rДокумент.Передача давальцу\r...
ИдентификаторСтроки : Строка
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
РасчетПартий : Булево
РасчетСебестоимости : Булево
КорПартия : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\rДокумент.Таможенная декларация на импорт\r...
КорАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
КорАналитикаФинансовогоУчета : Справочник.Подразделение\rСправочник.Пользователь\rСправочник.Сделка с клиентом\r...
КорВидДеятельностиНДС : Типы налогообложения НДС
НДСРегл : Число 15, 2
СтатьяКалькуляции : Справочник.Статьи калькуляции
ТипЗаписи : Типы записей партий
ДокументИсточник : Документ.Внутреннее потребление товаров\rДокумент.Расходный кассовый ордер\rДокумент.Перемещение материалов в производстве\r...
АналитикаУчетаПартийПроизводства : Справочник.Ключ аналитики учета партий производства
НДСУпр : Число 15, 2
КодСтроки : Число 10, 0
КорНаправлениеДеятельности : Справочник.Направление деятельности
РасчетНеЗавершен : Булево
}
@enduml
