@startuml ВзаиморасчетыССотрудниками
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ВзаиморасчетыССотрудниками as "Взаиморасчеты с сотрудниками" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
..Ресурсы..
СуммаВзаиморасчетов : Число 15, 2
..Реквизиты..
ВидВзаиморасчетов : Виды взаиморасчетов с сотрудниками
ГруппаНачисленияУдержанияВыплаты : Группы начисления удержания выплаты
Сторно : Булево
}
@enduml
