@startuml ПлановыеМатериальныеЗатраты
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПлановыеМатериальныеЗатраты as "Плановые материальные затраты" <<РегистрыНакопления>>
{
..Измерения..
Калькуляция : Документ.Плановая калькуляция
ПартияСпецификация : Документ.Этап производства\rСправочник.Ресурсная спецификация\rДокумент.Производство без заказа
Подразделение : Справочник.Подразделение
СтатьяКалькуляции : Справочник.Статьи калькуляции
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
..Ресурсы..
Количество : Число 15, 3
Стоимость : Число 15, 2
СтоимостьБезНДС : Число 15, 2
СтоимостьРегл : Число 15, 2
..Реквизиты..
ЭтоПолуфабрикат : Булево
ПериодЗатрат : Дата
}
@enduml
