@startuml ПодарочныеСертификаты
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПодарочныеСертификаты as "Подарочные сертификаты" <<РегистрыНакопления>>
{
..Измерения..
ПодарочныйСертификат : Справочник.Подарочный сертификат
..Ресурсы..
Сумма : Число 15, 2
..Реквизиты..
СуммаРегл : Число 15, 2
}
@enduml
