@startuml СтраховыеВзносыПереданныеВПФР
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.СтраховыеВзносыПереданныеВПФР as "Страховые взносы переданные в ПФР" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
УдалитьКатегорияЗастрахованныхЛиц : Категории застрахованных лиц для ПФР
..Ресурсы..
Страховая : Число 15, 2
Накопительная : Число 15, 2
СтраховаяЧленамЭкипажейМорскихСудов : Число 15, 2
НакопительнаяЧленамЭкипажейМорскихСудов : Число 15, 2
..Реквизиты..
КатегорияЗастрахованныхЛиц : Категории застрахованных лиц для ПФР
ТипДоговора : Типы договоров СЗВ-6-3
Сторно : Булево
}
@enduml
