@startuml ПереработкаПоГрафикуПроизводства
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПереработкаПоГрафикуПроизводства as "Переработка на стороне по графику производства" <<РегистрыНакопления>>
{
..Измерения..
ЗаказНаПроизводство : Документ.Заказ на производство
КодСтрокиЭтапыГрафик : Число 10, 0
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Склад : Справочник.Склад (складская территория)
..Ресурсы..
КЗаказу : Число 15, 3
}
@enduml
