@startuml ДенежныеДокументы
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДенежныеДокументы as "Движение денежных документов" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
МОЛ : Справочник.Физическое лицо
ДенежныйДокумент : Справочник.Денежный документ
..Ресурсы..
Количество : Число 15, 3
Сумма : Число 15, 2
СуммаУпр : Число 15, 2
СуммаРегл : Число 15, 2
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
}
@enduml
