@startuml РасчетыСКлиентамиПоДокументам
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.РасчетыСКлиентамиПоДокументам as "Расчеты с клиентами по документам" <<РегистрыНакопления>>
{
..Измерения..
АналитикаУчетаПоПартнерам : Справочник.Ключ аналитики учета по партнерам
ЗаказКлиента : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
РасчетныйДокумент : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
Валюта : Справочник.Валюта
УдалитьДатаПлатежа : Дата
..Ресурсы..
УдалитьКОтгрузке : Число 15, 2
УдалитьКОплате : Число 15, 2
КВозврату : Число 15, 2
Долг : Число 15, 2
ДолгУпр : Число 15, 2
ДолгРегл : Число 15, 2
Предоплата : Число 15, 2
ПредоплатаУпр : Число 15, 2
ПредоплатаРегл : Число 15, 2
ЗалогЗаТару : Число 15, 2
ЗалогЗаТаруРегл : Число 15, 2
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
ДатаПлатежа : Дата
}
@enduml
