@startuml ДенежныеСредстваБезналичные
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДенежныеСредстваБезналичные as "Денежные средства (безналичные)" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
БанковскийСчет : Справочник.Банковский счет организации
..Ресурсы..
Сумма : Число 15, 2
СуммаУпр : Число 15, 2
СуммаРегл : Число 15, 2
КЗачислению : Число 15, 2
КСписанию : Число 15, 2
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
ТипПлатежаФЗ275 : Справочник.Типы платежей 275-ФЗ
АналитикаУчетаПоПартнерам : Справочник.Ключ аналитики учета по партнерам
Заказ : Документ.Заказ поставщику\rДокумент.Заказ клиента
ПлатежныйДокумент : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Списание безналичных ДС\r...
СтатьяКалькуляции : Справочник.Статьи калькуляции
}
@enduml
