@startuml МатериалыИРаботыВПроизводстве
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.МатериалыИРаботыВПроизводстве as "Материалы и работы в производстве" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Подразделение : Справочник.Подразделение\rСправочник.Партнер
Серия : Справочник.Серия номенклатуры
Назначение : Справочник.Назначение
УдалитьАналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
..Ресурсы..
Количество : Число 15, 3
..Реквизиты..
СтатьяКалькуляции : Справочник.Статьи калькуляции
ЗаказНаПроизводство : Документ.Списание затрат на выпуск\rДокумент.Заказ на производство\rДокумент.Заказ переработчику\r...
КодСтрокиПродукция : Число 10, 0
Этап : Справочник.Этап ресурсной спецификации
ДатаРегистратора : Дата
НалогообложениеНДС : Типы налогообложения НДС
АналитикаУчетаПродукции : Справочник.Ключ аналитики учета номенклатуры
Спецификация : Справочник.Ресурсная спецификация
СтатьяРасходов : Статья расходов\rСтатья актива/пассива
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
НаправлениеДеятельности : Справочник.Направление деятельности
ПодразделениеПолучатель : Справочник.Подразделение
Первичное : Булево
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
РасчетПартий : Булево
БазаРаспределения : Типы показателей для распределения статей расходов
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
ИдентификаторСтроки : Строка
РасчетНеЗавершен : Булево
}
@enduml
