@startuml НачисленияПоДоговорамГПХ
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.НачисленияПоДоговорамГПХ as "Начисления по договорам ГПХ" <<РегистрыНакопления>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
Организация : Справочник.Организация
Договор : Документ.Договор авторского заказа\rДокумент.Договор (работы, услуги)
..Ресурсы..
Сумма : Число 15, 2
..Реквизиты..
Сторно : Булево
}
@enduml
