@startuml ТоварыКОформлениюЗаявленийОВвозе
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ТоварыКОформлениюЗаявленийОВвозе as "Товары к оформлению заявлений о ввозе из стран ЕАЭС" <<РегистрыНакопления>>
{
..Измерения..
ДокументПоступления : Документ.Приобретение товаров и услуг
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Серия : Справочник.Серия номенклатуры
Склад : Справочник.Склад (складская территория)
..Ресурсы..
КОформлению : Число 15, 3
ФактурнаяСтоимость : Число 15, 2
}
@enduml
