@startuml ТМЦВЭксплуатации
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ТМЦВЭксплуатации as "ТМЦ в эксплуатации" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ФизическоеЛицо : Справочник.Физическое лицо
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Партия : Справочник.Партии ТМЦ в эксплуатации
..Ресурсы..
Количество : Число 15, 3
}
@enduml
