@startuml БухучетНачисленияУдержанияПоСотрудникамАвансом
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.БухучетНачисленияУдержанияПоСотрудникамАвансом as "Бухучет начисления удержания по сотрудникам авансом" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
НачислениеУдержание : Виды взаиморасчетов с сотрудниками\rВиды особых начислений и удержаний\rНачисление\r...
..Ресурсы..
Сумма : Число 15, 2
..Реквизиты..
ГруппаНачисленияУдержанияВыплаты : Группы начисления удержания выплаты
ПериодДействия : Дата
ИдентификаторСтроки : Число 7, 0
СпособОтраженияЗарплатыВБухучете : Справочник.Способ отражения зарплаты
ОблагаетсяЕНВД : Булево
ВидОперации : Виды операций по зарплате
Сторно : Булево
}
@enduml
