@startuml ЗанятыеПозицииШтатногоРасписания
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ЗанятыеПозицииШтатногоРасписания as "Занятые позиции штатного расписания" <<РегистрыНакопления>>
{
..Измерения..
ПозицияШтатногоРасписания : Справочник.Позиция
..Ресурсы..
КоличествоСтавок : Число 25, 20
..Реквизиты..
Сотрудник : Справочник.Сотрудник
УсловноеДвижение : Булево
УсловноеКоличествоСтавок : Число 25, 20
ДатаОтменыУсловногоДвижения : Дата
БронированиеПозиции : Булево
ВременноеДвижение : Булево
Сторно : Булево
}
@enduml
