@startuml ДвиженияКонтрагентКонтрагент
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДвиженияКонтрагентКонтрагент as "Движения Контрагент - Контрагент" <<РегистрыНакопления>>
{
..Измерения..
ХозяйственнаяОперация : Хозяйственные операции
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
НаправлениеДеятельности : Справочник.Направление деятельности
Партнер : Справочник.Партнер
Контрагент : Справочник.Организация\rСправочник.Контрагент
Договор : Справочник.Договор между организациями\rСправочник.Договор с контрагентом\rСправочник.Договор кредита (депозита)
ОбъектРасчетов : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
КорНаправлениеДеятельности : Справочник.Направление деятельности
КорПартнер : Справочник.Партнер
КорКонтрагент : Справочник.Организация\rСправочник.Контрагент
КорДоговор : Справочник.Договор между организациями\rСправочник.Договор с контрагентом\rСправочник.Договор кредита (депозита)
КорОбъектРасчетов : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
ТипСуммы : Типы сумм задолженности
КорТипСуммы : Типы сумм задолженности
..Ресурсы..
Сумма : Число 15, 2
СуммаБезНДС : Число 15, 2
СуммаРегл : Число 15, 2
СуммаРеглБезНДС : Число 15, 2
..Реквизиты..
Валюта : Справочник.Валюта
СуммаВВалюте : Число 15, 2
СуммаБезНДСВВалюте : Число 15, 2
ВалютаВзаиморасчетов : Справочник.Валюта
СуммаВВалютеВзаиморасчетов : Число 15, 2
СуммаБезНДСВВалютеВзаиморасчетов : Число 15, 2
КорВалютаВзаиморасчетов : Справочник.Валюта
КорСуммаВВалютеВзаиморасчетов : Число 15, 2
КорСуммаБезНДСВВалютеВзаиморасчетов : Число 15, 2
ИсточникГФУРасчетов : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
КорИсточникГФУРасчетов : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
}
@enduml
