@startuml ОтработанноеВремяПоСотрудникам
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ОтработанноеВремяПоСотрудникам as "Отработанное время по сотрудникам" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
Начисление : Начисление
..Ресурсы..
ОтработаноДней : Число 7, 2
ОтработаноЧасов : Число 7, 2
ОплаченоДней : Число 7, 2
ОплаченоЧасов : Число 7, 2
..Реквизиты..
ГруппаНачисленияУдержанияВыплаты : Группы начисления удержания выплаты
ПериодДействия : Дата
ВремяВЧасах : Булево
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Приз, подарок\rДокумент.Удержание по прочим операциям\r...
ДатаНачала : Дата
ИдентификаторСтроки : Число 7, 0
Сторно : Булево
}
@enduml
