@startuml ТоварыКОформлениюИзлишковНедостач
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ТоварыКОформлениюИзлишковНедостач as "Товары к оформлению излишков и недостач" <<РегистрыНакопления>>
{
..Измерения..
Склад : Справочник.Склад (складская территория)
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
..Ресурсы..
КОформлениюАктов : Число 15, 3
}
@enduml
