@startuml СтоимостьНМА
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.СтоимостьНМА as "Стоимость НМА" <<РегистрыНакопления>>
{
..Измерения..
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ГруппаФинансовогоУчета : Справочник.Группа финансового учета внеоборотных активов
НаправлениеДеятельности : Справочник.Направление деятельности
..Ресурсы..
Стоимость : Число 15, 2
СтоимостьРегл : Число 15, 2
СтоимостьНУ : Число 15, 2
СтоимостьПР : Число 15, 2
СтоимостьВР : Число 15, 2
СтоимостьЦФ : Число 15, 2
СтоимостьНУЦФ : Число 15, 2
СтоимостьПРЦФ : Число 15, 2
СтоимостьВРЦФ : Число 15, 2
РезервПереоценкиСтоимости : Число 15, 2
РезервПереоценкиСтоимостиРегл : Число 15, 2
ПредварительнаяСтоимость : Число 15, 2
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
КорОрганизация : Справочник.Организация
КорПодразделение : Справочник.Подразделение
КорНаправлениеДеятельности : Справочник.Направление деятельности
КорСтатьяРасходов : Статья расходов
КорАналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
КорГруппаФинансовогоУчета : Справочник.Группа финансового учета внеоборотных активов
КорПостояннаяРазница : Число 15, 2
КорВременнаяРазница : Число 15, 2
ВариантПримененияЦелевогоФинансирования : Варианты применения целевого финансирования
ОтражатьВРеглУчете : Булево
ОтражатьВУпрУчете : Булево
РасчетСтоимости : Булево
НалогообложениеНДС : Типы налогообложения НДС
}
@enduml
