@startuml ТоварыВЯчейках
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ТоварыВЯчейках as "Товары в ячейках" <<РегистрыНакопления>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Упаковка : Справочник.Упаковка
Ячейка : Справочник.Складская ячейка
Серия : Справочник.Серия номенклатуры
..Ресурсы..
ВНаличии : Число 15, 3
КОтбору : Число 15, 3
КРазмещению : Число 15, 3
}
@enduml
