@startuml ДанныеСтрахователейДляРасчетаСреднегоЗаработкаФСС
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДанныеСтрахователейДляРасчетаСреднегоЗаработкаФСС as "Данные страхователей для расчета среднего заработка (ФСС)" <<РегистрыНакопления>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
ГоловнаяОрганизация : Справочник.Организация
Год : Число 4, 0
Страхователь : Справочник.Работодатель\rСправочник.Организация
..Ресурсы..
Сумма : Число 15, 2
ДнейБолезниУходаЗаДетьми : Число 5, 2
..Реквизиты..
НачалоПериода : Дата
ОкончаниеПериода : Дата
Сторно : Булево
}
@enduml
