@startuml ВыполненныеРаботыСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ВыполненныеРаботыСотрудников as "Выполненные работы сотрудников" <<РегистрыНакопления>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ВидРабот : Справочник.Вид работ сотрудников
..Ресурсы..
ОбъемВыполненныхРабот : Число 15, 3
}
@enduml
