@startuml ОтражениеЗарплатыВФинансовомУчете
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ОтражениеЗарплатыВФинансовомУчете as "Отражение зарплаты в финансовом учете" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ВидНачисленияОплатыТруда : Виды начислений оплаты труда для налогового учета по налогу на прибыль
ВидОперацииПоЗарплате : Виды операций по зарплате
СтатьяРасходов : Статья расходов\rСтатья актива/пассива
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ВидРабот : Справочник.Вид работ сотрудников
ФизическоеЛицо : Справочник.Физическое лицо
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
ТипНалога : Виды операций по зарплате\rТипы налогов
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
СчетУчета : Счет бухгалтерского учета
Субконто1 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто2 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
Субконто3 : Документ.Внутреннее потребление товаров\rДокумент.Запись книги покупок\rДокумент.Расходный ордер на товары\r...
НаправлениеДеятельности : Справочник.Направление деятельности
ВидПлатежаВГосБюджет : Виды платежей в бюджет (фонды)
..Ресурсы..
СуммаРегл : Число 15, 2
}
@enduml
