@startuml ПланыОплатКлиентов
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПланыОплатКлиентов as "Планы оплат клиентов" <<РегистрыНакопления>>
{
..Измерения..
Сценарий : Справочник.Сценарии товарного планирования
Статус : Статусы планов
Партнер : Справочник.Партнер
Договор : Справочник.Договор с контрагентом
План : Документ.План продаж
..Ресурсы..
Сумма : Число 15, 2
}
@enduml
