@startuml ОценочныеОбязательства
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ОценочныеОбязательства as "Оценочные обязательства" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ТипОценочногоОбязательства : Типы оценочных обязательств
СтатьяФинансирования : Справочник.Статья финансирования
..Ресурсы..
Сумма : Число 15, 2
СуммаНУ : Число 15, 2
..Реквизиты..
Сторно : Булево
}
@enduml
