@startuml ЗаявкиНаВозвратТоваровОтКлиентов
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ЗаявкиНаВозвратТоваровОтКлиентов as "Заявки на возврат товаров от клиентов" <<РегистрыНакопления>>
{
..Измерения..
ЗаявкаНаВозвратТоваровОтКлиента : Документ.Заявка на возврат товаров от клиента
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КодСтроки : Число 10, 0
..Ресурсы..
Заявлено : Число 15, 3
КОформлению : Число 15, 3
}
@enduml
