@startuml ТоварыНаСкладах
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ТоварыНаСкладах as "Товары на складах" <<РегистрыНакопления>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Склад : Справочник.Склад (складская территория)
Помещение : Справочник.Помещение
Серия : Справочник.Серия номенклатуры
..Ресурсы..
ВНаличии : Число 15, 3
КОтгрузке : Число 15, 3
..Реквизиты..
КонтролироватьОстатки : Булево
}
@enduml
