@startuml ТоварыПринятые
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ТоварыПринятые as "Товары принятые" <<РегистрыНакопления>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Серия : Справочник.Серия номенклатуры
Назначение : Справочник.Назначение
НомерГТД : Справочник.Номер ГТД
ВидЗапасов : Справочник.Вид запасов
Договор : Справочник.Договор с контрагентом
Владелец : Справочник.Партнер
..Ресурсы..
Получено : Число 15, 3
}
@enduml
