@startuml УдержанияДоПределаПоСотрудникам
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.УдержанияДоПределаПоСотрудникам as "Удержания до предела по сотрудникам" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
Удержание : Удержание
ДокументОснование : Документ.Удержание по прочим операциям\rДокумент.Удержание добровольных взносов в НПФ\rДокумент.Удержание профсоюзных взносов\r...
..Ресурсы..
Сумма : Число 15, 2
..Реквизиты..
Сторно : Булево
}
@enduml
