@startuml ОбеспечениеЗаказов
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ОбеспечениеЗаказов as "Обеспечение заказов" <<РегистрыНакопления>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Склад : Справочник.Склад (складская территория)
Назначение : Справочник.Назначение
..Ресурсы..
Потребность : Число 15, 3
КЗаказу : Число 15, 3
НаличиеПодЗаказ : Число 15, 3
..Реквизиты..
КонтролироватьТолькоНаличиеПодЗаказ : Булево
}
@enduml
