@startuml ПартииТоваровПереданныеНаКомиссию
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПартииТоваровПереданныеНаКомиссию as "Партии товаров переданные на комиссию" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ДокументПоступления : Документ.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\rДокумент.Таможенная декларация на импорт\r...
ВидЗапасов : Справочник.Вид запасов
АналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
ДокументПередачиНаКомиссию : Документ.Ввод начальных остатков\rДокумент.Реализация товаров и услуг\rДокумент.Передача товаров
..Ресурсы..
Количество : Число 15, 3
Стоимость : Число 15, 2
СтоимостьБезНДС : Число 15, 2
СтоимостьРегл : Число 15, 2
НДСРегл : Число 15, 2
ПостояннаяРазница : Число 15, 2
ВременнаяРазница : Число 15, 2
..Реквизиты..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
НалогообложениеНДС : Типы налогообложения НДС
ХозяйственнаяОперация : Хозяйственные операции
КорАналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
}
@enduml
