@startuml КнигаУчетаДоходовИРасходовРаздел2
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.КнигаУчетаДоходовИРасходовРаздел2 as "Книга учета доходов и расходов (раздел II)" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ЭлементРасходов : Справочник.Объект эксплуатации\rСправочник.Нематериальные активы и расходы на НИОКР
ДатаОплаты : Дата
ДокументМодернизации : Документ.Модернизация ОС
ДокументВозникновенияРасходов : Документ.Приобретение товаров и услуг\rДокумент.Первичный документ\rДокумент.Приобретение услуг и прочих активов
..Ресурсы..
Графа13_СуммаРасходовЗаКвартал : Число 15, 2
..Реквизиты..
Графа3_ДатаВводаВЭксплуатацию : Дата
Графа4_ГосударственнаяРегистрация : Дата
Графа5_ПервоначальнаяСтоимость : Число 15, 2
Графа6_ОстаточнаяСтоимость : Число 15, 2
Графа7_СрокПолезногоИспользования : Число 15, 2
Графа8_КолКварталовВОтчетномПериоде : Число 10, 0
Графа9_КолКварталовВНалПериоде : Число 10, 0
Графа10_ДоляРасходовЗаНалПериод : Число 10, 2
Графа11_ДоляРасходовЗаКвартал : Число 10, 2
Графа12_СуммаРасходовЗаОтчетнПериод : Число 15, 2
Графа14_РасходыПрошлыхПериодов : Число 15, 2
Графа15_ОстатокРасходов : Число 15, 2
Графа16_ДатаВыбытия : Дата
}
@enduml
