@startuml ПланыПродажПоКатегориям
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПланыПродажПоКатегориям as "Планы продаж по категориям" <<РегистрыНакопления>>
{
..Измерения..
Сценарий : Справочник.Сценарии товарного планирования
Статус : Статусы планов
ТоварнаяКатегория : Справочник.Товарные категории
ФорматМагазина : Справочник.Форматы магазинов
Склад : Справочник.Склад (складская территория)
Подразделение : Справочник.Подразделение
РейтингПродаж : Справочник.Рейтинг продаж номенклатуры
ПланПродажПоКатегориям : Документ.План продаж по категориям
Назначение : Справочник.Назначение
ВидПлана : Справочник.Вид плана
..Ресурсы..
Количество : Число 15, 3
}
@enduml
