@startuml ПрочиеРасходыНезавершенногоПроизводства
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПрочиеРасходыНезавершенногоПроизводства as "Прочие расходы незавершенного производства" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
ПартияПроизводства : Документ.Этап производства\rДокумент.Отчет переработчика\rДокумент.Выпуск продукции и выполнение работ\r...
ЗаказНаПроизводство : Документ.Списание затрат на выпуск\rДокумент.Заказ на производство\rДокумент.Заказ переработчику\r...
КодСтрокиПродукция : Число 10, 0
Этап : Справочник.Этап ресурсной спецификации
СтатьяКалькуляции : Справочник.Статьи калькуляции
СтатьяРасходов : Статья расходов
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
ГруппаПродукции : Справочник.Группа аналитического учета номенклатуры
ПравилоОтнесенияНаВыпуск : Правила отнесения на выпуск
..Ресурсы..
Стоимость : Число 15, 2
СтоимостьБезНДС : Число 15, 2
СтоимостьРегл : Число 15, 2
ПостояннаяРазница : Число 15, 2
ВременнаяРазница : Число 15, 2
ДоляСтоимости : Число 15, 2
СтоимостьУпр : Число 15, 2
ПоказательОтнесенияНаВыпуск : Число 23, 10
..Реквизиты..
Продукция : Справочник.Номенклатура
ХарактеристикаПродукции : Справочник.Характеристика номенклатуры
КоличествоПродукции : Число 15, 3
АналитикаУчетаПродукции : Справочник.Ключ аналитики учета номенклатуры
РазделУчета : Разделы учета себестоимости товаров
ВидЗапасов : Справочник.Вид запасов
ДокументДвижения : Документ.Отчет давальцу\rДокумент.Распределение расходов на себестоимость продукции\rДокумент.Отчет переработчика\r...
ДокументИсточник : Документ.Распределение расходов на себестоимость продукции
ДокументВыпуска : Документ.Этап производства\rДокумент.Заказ на производство\rДокумент.Отчет переработчика\r...
РасчетСебестоимости : Булево
РасчетПартий : Булево
ПоказательОтнесенияНаПартию : Число 23, 10
АналитикаУчетаПартийПроизводства : Справочник.Ключ аналитики учета партий производства\rСправочник.Ключ аналитики учета номенклатуры\rДокумент.Маршрутный лист производства
КорАналитикаУчетаПартий : Справочник.Ключ аналитики учета партий
}
@enduml
