@startuml ИмущественныеВычетыНДФЛ
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ИмущественныеВычетыНДФЛ as "Вычеты, предост. по уведомлению НО (НДФЛ)" <<РегистрыНакопления>>
{
..Измерения..
ГоловнаяОрганизация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
КодВычета : Справочник.Вид вычетов НДФЛ
Год : Число 4, 0
Организация : Справочник.Организация
УдалитьКодВычета : Справочник.(не используется) Виды вычетов НДФЛ
..Ресурсы..
Сумма : Число 15, 2
..Реквизиты..
Подразделение : Справочник.Территория\rСправочник.Подразделение
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
ВычетМежрасчетногоПериода : Булево
УдалитьОрганизация : Справочник.Организация
МесяцРегистрации : Дата
Сторно : Булево
}
@enduml
