@startuml ТоварыПереданныеНаКомиссию
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ТоварыПереданныеНаКомиссию as "Товары переданные на комиссию" <<РегистрыНакопления>>
{
..Измерения..
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
Соглашение : Справочник.Соглашение об условиях продаж
Организация : Справочник.Организация
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
..Ресурсы..
Количество : Число 15, 3
..Реквизиты..
СуммаВыручки : Число 15, 2
СуммаВознаграждения : Число 15, 2
КорАналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ДокументРеализации : Документ.Реализация товаров и услуг\rДокумент.Передача товаров
ХозяйственнаяОперация : Хозяйственные операции
НалогообложениеНДС : Типы налогообложения НДС
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
}
@enduml
