@startuml РасчетыПоЭквайрингу
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.РасчетыПоЭквайрингу as "Расчеты по эквайрингу" <<РегистрыНакопления>>
{
..Измерения..
ТипДенежныхСредств : Типы денежных средств по эквайрингу
Организация : Справочник.Организация
Валюта : Справочник.Валюта
ЭквайринговыйТерминал : Справочник.Эквайринговый терминал
НомерПлатежнойКарты : Строка
ДатаПлатежа : Дата
..Ресурсы..
Сумма : Число 15, 2
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
АналитикаУчетаПоПартнерам : Справочник.Ключ аналитики учета по партнерам
Заказ : Документ.Заказ поставщику\rДокумент.Заказ клиента
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
КодАвторизации : Строка
}
@enduml
