@startuml ОтработанноеВремяПоСотрудникамКорректировка
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ОтработанноеВремяПоСотрудникамКорректировка as "Отработанное время по сотрудникам (корректировка)" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
Начисление : Начисление
..Ресурсы..
ОтработаноДней : Число 7, 2
ОплаченоДней : Число 7, 2
..Реквизиты..
ГруппаНачисленияУдержанияВыплаты : Группы начисления удержания выплаты
ПериодДействия : Дата
ДокументОснование : Документ.Назначение планового начисления\rДокумент.Совмещение должностей\rДокумент.Отпуск\r...
ДатаНачала : Дата
ИдентификаторСтроки : Число 7, 0
Сторно : Булево
}
@enduml
