@startuml ДанныеОВремениДляРасчетаСреднегоОбщий
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДанныеОВремениДляРасчетаСреднегоОбщий as "Данные о времени для расчета среднего (общий)" <<РегистрыНакопления>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ПорядокРасчета : Порядок расчета среднего заработка общий
..Ресурсы..
ОтработаноДней : Число 5, 2
ОтработаноЧасов : Число 5, 2
ОтработаноДнейШестидневка : Число 5, 2
ОтработаноДнейПятидневка : Число 5, 2
ОтработаноЧасовПятидневка : Число 5, 2
ОтработаноДнейКалендарных : Число 5, 2
..Реквизиты..
Сторно : Булево
}
@enduml
