@startuml ОборотыБюджетов
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ОборотыБюджетов as "Обороты бюджетов" <<РегистрыНакопления>>
{
..Измерения..
ПериодПланирования : Дата
Сценарий : Справочник.Сценарии бюджетирования
Статус : Статусы планов
СтатьяБюджетов : Справочник.Статьи бюджетов\rСправочник.Показатели бюджетов
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
Валюта : Справочник.Валюта
Аналитика1 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика2 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика3 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика4 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика5 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
Аналитика6 : Справочник.Вид номенклатуры\rСправочник.Объект эксплуатации\rСправочник.Номенклатура\r...
..Ресурсы..
Количество : Число 15, 3
СуммаУпр : Число 15, 2
СуммаСценария : Число 15, 2
СуммаРегл : Число 15, 2
СуммаВВалюте : Число 15, 2
}
@enduml
