@startuml ДвиженияНоменклатураДоходыРасходы
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДвиженияНоменклатураДоходыРасходы as "Движения Номенклатура - Доходы/Расходы" <<РегистрыНакопления>>
{
..Измерения..
ХозяйственнаяОперация : Хозяйственные операции
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
НаправлениеДеятельностиНоменклатуры : Справочник.Направление деятельности
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
Склад : Справочник.Подразделение\rСправочник.Партнер\rСправочник.Склад (складская территория)
ТипЗапасов : Типы запасов
ВидЗапасов : Справочник.Вид запасов
НаправлениеДеятельностиСтатьи : Справочник.Направление деятельности
СтатьяДоходовРасходов : Статья расходов\rСтатья актива/пассива\rСтатьи доходов
АналитикаДоходов : Справочник.Объект эксплуатации\rДокумент.Заказ поставщику\rСправочник.Нематериальные активы и расходы на НИОКР\r...
АналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
АналитикаАктивовПассивов : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
..Ресурсы..
Количество : Число 15, 3
Стоимость : Число 15, 2
СтоимостьБезНДС : Число 15, 2
СтоимостьУпр : Число 15, 2
СтоимостьРегл : Число 15, 2
СтоимостьЗабалансовая : Число 15, 2
СтоимостьЗабалансоваяРегл : Число 15, 2
ДопРасходы : Число 15, 2
ДопРасходыБезНДС : Число 15, 2
ДопРасходыУпр : Число 15, 2
ДопРасходыРегл : Число 15, 2
ПостатейныеПостоянныеСНДС : Число 15, 2
ПостатейныеПостоянныеБезНДС : Число 15, 2
ПостатейныеПостоянныеУпр : Число 15, 2
ПостатейныеПостоянныеРегл : Число 15, 2
Трудозатраты : Число 15, 2
ТрудозатратыУпр : Число 15, 2
ТрудозатратыРегл : Число 15, 2
ПостатейныеПеременныеСНДС : Число 15, 2
ПостатейныеПеременныеБезНДС : Число 15, 2
ПостатейныеПеременныеУпр : Число 15, 2
ПостатейныеПеременныеРегл : Число 15, 2
ПостояннаяРазница : Число 15, 2
ВременнаяРазница : Число 15, 2
..Реквизиты..
ИсточникГФУНоменклатуры : Справочник.Номенклатура\rСправочник.Вид запасов
ДокументДвижения : Документ.Внутреннее потребление товаров\rДокумент.Расходный кассовый ордер\rДокумент.Перемещение материалов в производстве\r...
РасчетПартий : Булево
РасчетСебестоимости : Булево
}
@enduml
