@startuml ЗаказыКлиентов
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ЗаказыКлиентов as "Заказы клиентов" <<РегистрыНакопления>>
{
..Измерения..
ЗаказКлиента : Документ.Заказ переработчику\rДокумент.Заявка на возврат товаров от клиента\rДокумент.Заказ клиента\r...
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КодСтроки : Число 10, 0
Склад : Справочник.Склад (складская территория)
Серия : Справочник.Серия номенклатуры
..Ресурсы..
Заказано : Число 15, 3
КОформлению : Число 15, 3
Сумма : Число 15, 2
..Реквизиты..
ПричинаОтмены : Справочник.Причина отмены заказов клиентов
}
@enduml
