@startuml ОбеспечениеЗаказовРаботами
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ОбеспечениеЗаказовРаботами as "Обеспечение заказов работами" <<РегистрыНакопления>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Подразделение : Справочник.Подразделение
..Ресурсы..
КОбеспечению : Число 15, 3
}
@enduml
