@startuml ДенежныеСредстваВКассахККМ
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДенежныеСредстваВКассахККМ as "Денежные средства в кассах ККМ" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
КассаККМ : Справочник.Кассы ККМ
..Ресурсы..
Сумма : Число 15, 2
СуммаУпр : Число 15, 2
СуммаРегл : Число 15, 2
УдалитьКПоступлениюВКассуККМ : Число 15, 2
УдалитьКПоступлениюВКассуОрганизации : Число 15, 2
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
}
@enduml
