@startuml ДанныеСводногоУчетаРабочегоВремениСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДанныеСводногоУчетаРабочегоВремениСотрудников as "Данные сводного учета рабочего времени сотрудников" <<РегистрыНакопления>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ПериодРегистрации : Дата
ВидУчетаВремени : Справочник.Вид рабочего времени
..Ресурсы..
Дни : Число 6, 3
Часы : Число 7, 3
}
@enduml
