@startuml РаспоряженияНаПередачуИзПроизводства
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.РаспоряженияНаПередачуИзПроизводства as "Распоряжения на передачу из производства" <<РегистрыНакопления>>
{
..Измерения..
Отправитель : Справочник.Подразделение
Получатель : Справочник.Подразделение\rСправочник.Склад (складская территория)
Распоряжение : Документ.Этап производства
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
НазначениеОтправителя : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
Операция : Хозяйственные операции
КодСтроки : Число 10, 0
..Ресурсы..
Количество : Число 15, 3
}
@enduml
