@startuml НДСЗаписиРаздела7Декларации
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.НДСЗаписиРаздела7Декларации as "Записи раздела 7 декларации по НДС" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
КодОперации : Справочник.Коды операций раздела 7 декларации по НДС
..Ресурсы..
СуммаРеализации : Число 15, 2
СуммаПриобретения : Число 10, 0
СуммаНДС : Число 15, 2
}
@enduml
