@startuml ТоварыПереданныеПереработчику
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ТоварыПереданныеПереработчику as "Товары переданные переработчику" <<РегистрыНакопления>>
{
..Измерения..
ВидЗапасов : Справочник.Вид запасов
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
..Ресурсы..
Количество : Число 15, 3
}
@enduml
