@startuml РасходыПриУСН
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.РасходыПриУСН as "Расходы при УСН" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ДокументВозникновенияРасходов : Документ.Расходный кассовый ордер\rДокумент.Движение прочих активов и пассивов\rДокумент.Приобретение товаров и услуг\r...
ВидРасходов : Виды расходов УСН
СтатьяРасходов : Статья расходов\rТипы налогов\rВиды налогов
..Ресурсы..
СуммаРасходов : Число 15, 2
НДС : Число 15, 2
СуммаОплаты : Число 15, 2
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
}
@enduml
