@startuml ПериодыУходаЗаБольнымиРодственниками
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПериодыУходаЗаБольнымиРодственниками as "Периоды ухода за больными родственниками" <<РегистрыНакопления>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
Родственник : Справочник.Родственник
СлучайУходаЗаБольнымРебенком : Случаи ухода за больными детьми
..Ресурсы..
КоличествоДней : Число 3, 0
ОплаченоДней : Число 3, 0
..Реквизиты..
НачалоПериода : Дата
ОкончаниеПериода : Дата
НачалоПериодаОплаты : Дата
ОкончаниеПериодаОплаты : Дата
Сторно : Булево
}
@enduml
