@startuml ПланыПотребленияКомплектующих
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПланыПотребленияКомплектующих as "Планы потребления комплектующих" <<РегистрыНакопления>>
{
..Измерения..
Сценарий : Справочник.Сценарии товарного планирования
Статус : Статусы планов
ХозяйственнаяОперация : Хозяйственные операции
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Склад : Справочник.Склад (складская территория)
ПланСборкиРазборки : Документ.План сборки (разборки)
ДатаВыпуска : Дата
Назначение : Справочник.Назначение
..Ресурсы..
Количество : Число 15, 3
..Реквизиты..
ВариантКомплектации : Справочник.Вариант комплектации
}
@enduml
