@startuml ВзаиморасчетыПоЗаймамСотрудникам
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ВзаиморасчетыПоЗаймамСотрудникам as "Взаиморасчеты по займам сотрудникам" <<РегистрыНакопления>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
Организация : Справочник.Организация
ДоговорЗайма : Документ.Договор займа сотруднику
..Ресурсы..
СуммаЗайма : Число 15, 2
Проценты : Число 15, 2
..Реквизиты..
ВнеочередноеПогашение : Булево
Сторно : Булево
}
@enduml
