@startuml ЗначенияОперативныхПоказателейРасчетаЗарплатыОрганизаций
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ЗначенияОперативныхПоказателейРасчетаЗарплатыОрганизаций as "Значения оперативных показателей расчета зарплаты (для организаций)" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
Показатель : Справочник.Показатель
..Ресурсы..
Значение : Число 15, 5
..Реквизиты..
Сторно : Булево
}
@enduml
