@startuml ТоварныеМестаКОтражениюИзлишковНедостач
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ТоварныеМестаКОтражениюИзлишковНедостач as "Товарные места к отражению излишков и недостач" <<РегистрыНакопления>>
{
..Измерения..
Склад : Справочник.Склад (складская территория)
Помещение : Справочник.Помещение
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
ТоварноеМесто : Справочник.Упаковка
..Ресурсы..
Количество : Число 15, 3
}
@enduml
