@startuml ЗначенияОперативныхПоказателейРасчетаЗарплатыПодразделений
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ЗначенияОперативныхПоказателейРасчетаЗарплатыПодразделений as "Значения оперативных показателей расчета зарплаты (для подразделений)" <<РегистрыНакопления>>
{
..Измерения..
Подразделение : Справочник.Подразделение
Показатель : Справочник.Показатель
Организация : Справочник.Организация
..Ресурсы..
Значение : Число 15, 5
..Реквизиты..
Сторно : Булево
}
@enduml
