@startuml ЗарплатаКВыплате
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ЗарплатаКВыплате as "Зарплата к выплате" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
ПериодВзаиморасчетов : Дата
ДокументОснование : Документ.Единовременное пособие\rДокумент.Перенос затрат\rДокумент.Возврат НДФЛ\r...
..Ресурсы..
СуммаКВыплате : Число 15, 2
..Реквизиты..
УдалитьДокументОснование : Документ.Единовременное пособие\rДокумент.Возврат НДФЛ\rДокумент.Простой сотрудников\r...
Сторно : Булево
}
@enduml
