@startuml ДенежныеСредстваУПодотчетныхЛиц
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДенежныеСредстваУПодотчетныхЛиц as "Денежные средства у подотчетных лиц" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ПодотчетноеЛицо : Справочник.Физическое лицо
Подразделение : Справочник.Подразделение
ЦельВыдачи : Справочник.Статья движения денежных средств
Валюта : Справочник.Валюта
..Ресурсы..
Сумма : Число 15, 2
СуммаУпр : Число 15, 2
СуммаРегл : Число 15, 2
КОтчету : Число 15, 2
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
Заказ : Документ.Заказ поставщику\rДокумент.Заказ клиента
}
@enduml
