@startuml СведенияОДоходахСтраховыеВзносы
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.СведенияОДоходахСтраховыеВзносы as "Учет доходов для исчисления страховых взносов" <<РегистрыНакопления>>
{
..Измерения..
ГоловнаяОрганизация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
Организация : Справочник.Организация
ВидДохода : Справочник.Вид дохода по страховым взносам
УдалитьВидДохода : Справочник.(не используется) Виды доходов (взносы)
ОблагаетсяЕНВД : Булево
ЯвляетсяДоходомФармацевта : Булево
ОблагаетсяВзносамиНаДоплатуЛетчикам : Булево
ОблагаетсяВзносамиНаДоплатуШахтерам : Булево
ЯвляетсяДоходомЧленаЭкипажаСуднаПодФлагомРФ : Булево
ОблагаетсяВзносамиЗаЗанятыхНаРаботахСДосрочнойПенсией : Виды работ с досрочной пенсией
КлассУсловийТруда : Классы условий труда по результатам специальной оценки
..Ресурсы..
Сумма : Число 15, 2
Скидка : Число 15, 2
..Реквизиты..
Сотрудник : Справочник.Сотрудник
Начисление : Справочник.Вид выплаты бывшему сотруднику\rСправочник.Вид прочего дохода\rВиды особых начислений и удержаний\r...
Подразделение : Справочник.Подразделение
ДатаНачала : Дата
ДатаПолученияДохода : Дата
ПоАктуПроверки : Булево
Сторно : Булево
}
@enduml
