@startuml РасчетыСКлиентами
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.РасчетыСКлиентами as "Расчеты с клиентами" <<РегистрыНакопления>>
{
..Измерения..
АналитикаУчетаПоПартнерам : Справочник.Ключ аналитики учета по партнерам
ЗаказКлиента : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
Валюта : Справочник.Валюта
..Ресурсы..
Сумма : Число 15, 2
КОплате : Число 15, 2
Оплачивается : Число 15, 2
КОтгрузке : Число 15, 2
Отгружается : Число 15, 2
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
ФормаОплаты : Формы оплаты
СчетНаОплату : Документ.Счет на оплату
ПродажаПоЗаказу : Документ.Заявка на возврат товаров от клиента\rДокумент.Заказ клиента
ДатаРегистратора : Дата
ДатаПлатежа : Дата
СуммаРегл : Число 15, 2
СуммаУпр : Число 15, 2
ИсключатьПриКонтроле : Булево
ДопустимаяСуммаЗадолженности : Число 15, 2
ЗалогЗаТару : Число 15, 2
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
РасчетныйДокумент : Документ.Расходный кассовый ордер\rДокумент.Приходный кассовый ордер\rДокумент.Возврат товаров от клиента\r...
}
@enduml
