@startuml ПланыОплатПоставщикам
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПланыОплатПоставщикам as "Планы оплат поставщикам" <<РегистрыНакопления>>
{
..Измерения..
Сценарий : Справочник.Сценарии товарного планирования
Статус : Статусы планов
Партнер : Справочник.Партнер
План : Документ.План закупок
..Ресурсы..
Сумма : Число 15, 2
}
@enduml
