@startuml КнигаУчетаДоходовИРасходов
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.КнигаУчетаДоходовИРасходов as "Книга учета доходов и расходов (раздел I)" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ДокументВозникновенияРасходов : Документ.Внутреннее потребление товаров\rДокумент.Расходный кассовый ордер\rДокумент.Движение прочих активов и пассивов\r...
ВидРасходов : Виды расходов УСН
Статья : Справочник.Объект эксплуатации\rСтатья расходов\rСправочник.Нематериальные активы и расходы на НИОКР\r...
Партия : Документ.Внутреннее потребление товаров\rДокумент.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\r...
..Ресурсы..
Графа4 : Число 15, 2
Графа5 : Число 15, 2
Графа6 : Число 15, 2
Графа7 : Число 15, 2
НДС : Число 15, 2
ДоходЕНВД : Число 15, 2
РасходЕНВД : Число 15, 2
..Реквизиты..
Содержание : Строка
РеквизитыПервичногоДокумента : Строка
УдалитьСтрокаДокумента : Число 10, 0
УдалитьТабличнаяЧасть : Строка
УдалитьЭтапПроведения : Число 1, 0
}
@enduml
