@startuml АмортизацияОС
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.АмортизацияОС as "Амортизация ОС" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ОсновноеСредство : Справочник.Объект эксплуатации
Подразделение : Справочник.Подразделение
ГруппаФинансовогоУчета : Справочник.Группа финансового учета внеоборотных активов
НаправлениеДеятельности : Справочник.Направление деятельности
..Ресурсы..
Амортизация : Число 15, 2
АмортизацияРегл : Число 15, 2
АмортизацияНУ : Число 15, 2
АмортизацияПР : Число 15, 2
АмортизацияВР : Число 15, 2
АмортизацияЦФ : Число 15, 2
АмортизацияНУЦФ : Число 15, 2
АмортизацияПРЦФ : Число 15, 2
АмортизацияВРЦФ : Число 15, 2
РезервПереоценкиАмортизации : Число 15, 2
РезервПереоценкиАмортизацииРегл : Число 15, 2
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
КорОрганизация : Справочник.Организация
КорПодразделение : Справочник.Подразделение
КорНаправлениеДеятельности : Справочник.Направление деятельности
КорСтатьяРасходов : Статья расходов
КорАналитикаРасходов : Справочник.Объект эксплуатации\rСправочник.Маркетинговое мероприятие\rДокумент.Приобретение товаров и услуг\r...
КорГруппаФинансовогоУчета : Справочник.Группа финансового учета внеоборотных активов
НачислятьИзнос : Булево
}
@enduml
