@startuml БонусныеБаллы
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.БонусныеБаллы as "Бонусные баллы" <<РегистрыНакопления>>
{
..Измерения..
БонуснаяПрограммаЛояльности : Справочник.Бонусные программы лояльности
Партнер : Справочник.Партнер
..Ресурсы..
Начислено : Число 15, 2
КСписанию : Число 15, 2
}
@enduml
