@startuml ДанныеТабельногоУчетаРабочегоВремениСотрудников
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДанныеТабельногоУчетаРабочегоВремениСотрудников as "Данные табельного учета рабочего времени сотрудников" <<РегистрыНакопления>>
{
..Измерения..
Сотрудник : Справочник.Сотрудник
ПериодРегистрации : Дата
ВидУчетаВремени : Справочник.Вид рабочего времени
Территория : Справочник.Территория
УсловияТруда : Справочник.Условия труда
..Ресурсы..
Дни : Число 5, 2
Часы : Число 5, 2
..Реквизиты..
УдалитьПлан : Булево
УдалитьВнутрисменное : Булево
УдалитьВЦеломЗаПериод : Булево
УдалитьВидВремениВытесняемый : Справочник.Вид рабочего времени
УдалитьИтоговыеДанные : Булево
УдалитьСторно : Булево
}
@enduml
