@startuml ПрочиеАктивыПассивы
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПрочиеАктивыПассивы as "Активы и пассивы" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
НаправлениеДеятельности : Справочник.Направление деятельности
Статья : Статья актива/пассива
Аналитика : Справочник.Объект эксплуатации\rСправочник.Номенклатура\rСправочник.Нематериальные активы и расходы на НИОКР\r...
..Ресурсы..
Сумма : Число 15, 2
..Реквизиты..
РасчетСебестоимости : Булево
ВидИсточника : Виды источников управленческого баланса
Источник : Источники управленческого баланса
ИсточникДвижений : Источники движений
}
@enduml
