@startuml ТоварыПолученныеОтПереработчика
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ТоварыПолученныеОтПереработчика as "Товары полученные от переработчика" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
Распоряжение : Документ.Заказ переработчику\rДокумент.Поступление от переработчика
КодСтроки : Число 10, 0
ТипСтоимости : Типы стоимости выходных изделий
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
..Ресурсы..
Количество : Число 15, 3
}
@enduml
