@startuml РасходыПриУСНТовары
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.РасходыПриУСНТовары as "Расходы при УСН по товарам" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ДокументВозникновенияРасходов : Документ.Внутреннее потребление товаров\rДокумент.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\r...
Партия : Документ.Внутреннее потребление товаров\rДокумент.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\r...
ВидРасходов : Виды расходов УСН
..Ресурсы..
СуммаРасходов : Число 15, 2
НДС : Число 15, 2
СуммаОплаты : Число 15, 2
СуммаОтгрузки : Число 15, 2
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
}
@enduml
