@startuml ЛимитыРасходаДенежныхСредств
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ЛимитыРасходаДенежныхСредств as "Лимиты расхода денежных средств" <<РегистрыНакопления>>
{
..Измерения..
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
..Ресурсы..
Лимит : Число 15, 2
РасходВПределахЛимита : Число 15, 2
РасходСверхЛимита : Число 15, 2
}
@enduml
