@startuml ТоварыУПартнеров
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ТоварыУПартнеров as "Товары у партнеров" <<РегистрыНакопления>>
{
..Измерения..
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Серия : Справочник.Серия номенклатуры
Назначение : Справочник.Назначение
ВидЗапасов : Справочник.Вид запасов
Партнер : Справочник.Партнер
Контрагент : Справочник.Контрагент
НомерГТД : Справочник.Номер ГТД
Договор : Справочник.Договор с контрагентом
..Ресурсы..
Передано : Число 15, 3
}
@enduml
