@startuml ДвиженияСерийТоваров
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДвиженияСерийТоваров as "Движения серий товаров" <<РегистрыНакопления>>
{
..Измерения..
Серия : Справочник.Серия номенклатуры
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Документ : Документ.Внутреннее потребление товаров\rДокумент.Акт о расхождениях после перемещения\rДокумент.Расходный ордер на товары\r...
Отправитель : Справочник.Подразделение\rСправочник.Партнер\rСправочник.Склад (складская территория)
ПомещениеОтправителя : Справочник.Помещение
СкладскаяОперация : Складские операции
Получатель : Справочник.Номенклатура\rСправочник.Подразделение\rСправочник.Партнер\r...
ПомещениеПолучателя : Справочник.Помещение
ХарактеристикаПолучателя : Справочник.Характеристика номенклатуры
ЭтоСкладскоеДвижение : Булево
..Ресурсы..
Количество : Число 15, 3
}
@enduml
