@startuml РасходыПриУСНМатериалы
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.РасходыПриУСНМатериалы as "Расходы при УСН по материалам" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ДокументВозникновенияРасходов : Документ.Внутреннее потребление товаров\rДокумент.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\r...
Партия : Документ.Внутреннее потребление товаров\rДокумент.Возврат товаров от клиента\rДокумент.Приобретение товаров и услуг\r...
ВидРасходов : Виды расходов УСН
..Ресурсы..
СуммаРасходов : Число 15, 2
НДС : Число 15, 2
СуммаОплаты : Число 15, 2
..Реквизиты..
ХозяйственнаяОперация : Хозяйственные операции
СтатьяРасходов : Статья расходов
}
@enduml
