@startuml ПланыЗанятостиТрудовыхРесурсов
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПланыЗанятостиТрудовыхРесурсов as "Планы занятости трудовых ресурсов" <<РегистрыНакопления>>
{
..Измерения..
Сценарий : Справочник.Сценарии товарного планирования
Статус : Статусы планов
ВидРабот : Справочник.Вид работ сотрудников
ПодразделениеДиспетчер : Справочник.Подразделение
ПодразделениеИсполнитель : Справочник.Подразделение
ПланПроизводства : Документ.План производства
ДатаВыпуска : Дата
НоменклатураПродукции : Справочник.Номенклатура
ХарактеристикаПродукции : Справочник.Характеристика номенклатуры
..Ресурсы..
Количество : Число 15, 3
..Реквизиты..
Спецификация : Справочник.Ресурсная спецификация
КоличествоНаЕдиницуПродукции : Число 15, 6
НазначениеПродукции : Справочник.Назначение
}
@enduml
