@startuml ТоварыКОтбору
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ТоварыКОтбору as "Товары к отбору" <<РегистрыНакопления>>
{
..Измерения..
Распоряжение : Документ.Расходный ордер на товары\rДокумент.Ордер на перемещение товаров
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Назначение : Справочник.Назначение
Серия : Справочник.Серия номенклатуры
ТоварноеМесто : Справочник.Упаковка
..Ресурсы..
КОтбору : Число 15, 3
Отбирается : Число 15, 3
Отобрано : Число 15, 3
}
@enduml
