@startuml РезервыТоваровОрганизаций
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.РезервыТоваровОрганизаций as "Резервы товаров организаций" <<РегистрыНакопления>>
{
..Измерения..
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
Организация : Справочник.Организация
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
ЭтоСторно : Булево
..Ресурсы..
Количество : Число 15, 3
..Реквизиты..
КорОрганизация : Справочник.Организация
КорВидЗапасов : Справочник.Вид запасов
НалогообложениеНДС : Типы налогообложения НДС
}
@enduml
