@startuml ПереданнаяВозвратнаяТара
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПереданнаяВозвратнаяТара as "Переданная возвратная тара" <<РегистрыНакопления>>
{
..Измерения..
Партнер : Справочник.Партнер
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
ДокументПередачи : Документ.Реализация товаров и услуг\rДокумент.Передача сырья переработчику
ВидЗапасов : Справочник.Вид запасов
НомерГТД : Справочник.Номер ГТД
ПредусмотренЗалог : Булево
..Ресурсы..
Количество : Число 15, 3
Сумма : Число 15, 2
..Реквизиты..
Выкуп : Булево
}
@enduml
