@startuml АвансовыеПлатежиИностранцевПоНДФЛ
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.АвансовыеПлатежиИностранцевПоНДФЛ as "Авансовые платежи иностранцев по НДФЛ" <<РегистрыНакопления>>
{
..Измерения..
ГоловнаяОрганизация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
Год : Число 4, 0
Организация : Справочник.Организация
..Ресурсы..
Сумма : Число 15, 2
..Реквизиты..
Подразделение : Справочник.Территория\rСправочник.Подразделение
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
СтавкаНалогообложенияРезидента : НДФЛ ставки налогообложения резидента
МесяцНалоговогоПериода : Дата
КодДохода : Справочник.Вид дохода НДФЛ
Сторно : Булево
}
@enduml
