@startuml ДвиженияДенежныхСредств
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ДвиженияДенежныхСредств as "Движения Денежные средства - Денежные средства" <<РегистрыНакопления>>
{
..Измерения..
ХозяйственнаяОперация : Хозяйственные операции
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
НаправлениеДеятельности : Справочник.Направление деятельности
ДенежныеСредства : Справочник.Денежный документ\rСправочник.Кассы ККМ\rСправочник.Договор кредита (депозита)\r...
ТипДенежныхСредств : Типы денежных средств
СтатьяДвиженияДенежныхСредств : Справочник.Статья движения денежных средств
СтатьяКалькуляции : Справочник.Статьи калькуляции
ТипПлатежаФЗ275 : Справочник.Типы платежей 275-ФЗ
Валюта : Справочник.Валюта
КорДенежныеСредства : Справочник.Денежный документ\rСправочник.Кассы ККМ\rСправочник.Договор кредита (депозита)\r...
КорТипДенежныхСредств : Типы денежных средств
КорНаправлениеДеятельности : Справочник.Направление деятельности
КорВалюта : Справочник.Валюта
..Ресурсы..
Сумма : Число 15, 2
СуммаРегл : Число 15, 2
СуммаВВалюте : Число 15, 2
СуммаКВыплатеВРамкахЛимита : Число 15, 2
СуммаКВыплатеСверхЛимита : Число 15, 2
СуммаВКорВалюте : Число 15, 2
..Реквизиты..
ИсточникГФУДенежныхСредств : Справочник.Договор кредита (депозита)\rСправочник.Банковский счет организации\rСправочник.Касса
ИсточникКорГФУДенежныхСредств : Справочник.Договор кредита (депозита)\rСправочник.Банковский счет организации\rСправочник.Касса
}
@enduml
