@startuml РаспоряженияНаВыпускПродукции
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.РаспоряженияНаВыпускПродукции as "Распоряжения на выпуск продукции" <<РегистрыНакопления>>
{
..Измерения..
Распоряжение : Документ.Маршрутный лист производства
Подразделение : Справочник.Подразделение
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КодСтроки : Число 10, 0
Склад : Справочник.Подразделение\rСправочник.Склад (складская территория)
..Ресурсы..
Заказано : Число 15, 3
КОформлению : Число 15, 3
..Реквизиты..
ДоляСтоимости : Число 10, 0
ТипСтоимости : Типы стоимости выходных изделий
ВидЗапасов : Справочник.Вид запасов
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
Назначение : Справочник.Назначение
}
@enduml
