@startuml ОстаткиАлкогольнойПродукцииЕГАИС
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ОстаткиАлкогольнойПродукцииЕГАИС as "Остатки алкогольной продукции ЕГАИС" <<РегистрыНакопления>>
{
..Измерения..
ОрганизацияЕГАИС : Справочник.Организация ЕГАИС
АлкогольнаяПродукция : Справочник.Алкогольная продукция ЕГАИС
Справка2 : Справочник.Справка к ТТН по форме 2
..Ресурсы..
Количество : Число 15, 3
СвободныйОстаток : Число 15, 3
}
@enduml
