@startuml РасчетыНалоговыхАгентовСБюджетомПоНДФЛ
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.РасчетыНалоговыхАгентовСБюджетомПоНДФЛ as "Расчеты налоговых агентов с бюджетом по НДФЛ" <<РегистрыНакопления>>
{
..Измерения..
ФизическоеЛицо : Справочник.Физическое лицо
Организация : Справочник.Организация
Ставка : Ставки НДФЛ
МесяцНалоговогоПериода : Дата
РегистрацияВНалоговомОргане : Справочник.Регистрация в налоговом органе
ВключатьВДекларациюПоНалогуНаПрибыль : Булево
ИсчисленоПоДивидендам : Булево
..Ресурсы..
Сумма : Число 15, 2
..Реквизиты..
УдалитьПлатежноеПоручениеНомер : Строка
УдалитьПлатежноеПоручениеДата : Дата
РеквизитыПлатежногоПоручения : Строка
Сторно : Булево
}
@enduml
