@startuml ТоварыКОформлениюТаможенныхДеклараций
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ТоварыКОформлениюТаможенныхДеклараций as "Товары к оформлению таможенных деклараций" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
Поставщик : Справочник.Партнер
АналитикаУчетаНоменклатуры : Справочник.Ключ аналитики учета номенклатуры
ВидЗапасов : Справочник.Вид запасов
ДокументПоступления : Документ.Приобретение товаров и услуг
..Ресурсы..
Количество : Число 15, 3
Сумма : Число 15, 2
..Реквизиты..
НомерГТД : Справочник.Номер ГТД
Первичное : Булево
}
@enduml
