@startuml ПродукцияИПолуфабрикатыВПроизводстве
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ПродукцияИПолуфабрикатыВПроизводстве as "Продукция и полуфабрикаты в производстве" <<РегистрыНакопления>>
{
..Измерения..
Распоряжение : Документ.Заказ на производство
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
Спецификация : Справочник.Ресурсная спецификация
Получатель : Справочник.Подразделение\rСправочник.Склад (складская территория)
Назначение : Справочник.Назначение
Этап : Документ.Этап производства
..Ресурсы..
Требуется : Число 15, 3
Запланировано : Число 15, 3
ПереданоКПроизводству : Число 15, 3
ОжидаетПроизводства : Число 15, 3
Производится : Число 15, 3
Произведено : Число 15, 3
}
@enduml
