@startuml НачисленияУдержанияПоСотрудникамАвансом
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.НачисленияУдержанияПоСотрудникамАвансом as "Начисления удержания по сотрудникам авансом" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
Сотрудник : Справочник.Сотрудник
Подразделение : Справочник.Подразделение
НачислениеУдержание : Виды взаиморасчетов с сотрудниками\rВиды особых начислений и удержаний\rНачисление\r...
..Ресурсы..
Сумма : Число 15, 2
УдалитьОтработаноДней : Число 7, 2
УдалитьОтработаноЧасов : Число 7, 2
УдалитьОплаченоДней : Число 7, 2
УдалитьОплаченоЧасов : Число 7, 2
..Реквизиты..
ГруппаНачисленияУдержанияВыплаты : Группы начисления удержания выплаты
ПериодДействия : Дата
ДатаНачала : Дата
ДатаОкончания : Дата
ИдентификаторСтроки : Число 7, 0
Сторно : Булево
}
@enduml
