@startuml ВзаиморасчетыСКонтрагентамиАкционерами
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ВзаиморасчетыСКонтрагентамиАкционерами as "Взаиморасчеты с контрагентами и акционерами" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
ФизическоеЛицо : Справочник.Физическое лицо
СпособРасчетов : Способы расчетов с физическими лицами
СтатьяФинансирования : Справочник.Статья финансирования
СтатьяРасходов : Справочник.Статья расходов
ДокументОснование : Документ.Единовременное пособие\rДокумент.Выплата бывшим сотрудникам\rДокумент.Начисление прочих доходов
..Ресурсы..
СуммаВзаиморасчетов : Число 15, 2
..Реквизиты..
ГруппаНачисленияУдержанияВыплаты : Группы начисления удержания выплаты
Сотрудник : Справочник.Сотрудник
}
@enduml
