@startuml ВыработкаНМА
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ВыработкаНМА as "Выработка НМА" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
НематериальныйАктив : Справочник.Нематериальные активы и расходы на НИОКР
..Ресурсы..
Количество : Число 15, 3
}
@enduml
