@startuml ЗаказыНаПеремещение
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ЗаказыНаПеремещение as "Заказы на перемещение" <<РегистрыНакопления>>
{
..Измерения..
ЗаказНаПеремещение : Документ.Заказ на перемещение
Номенклатура : Справочник.Номенклатура
Характеристика : Справочник.Характеристика номенклатуры
КодСтроки : Число 10, 0
Серия : Справочник.Серия номенклатуры
..Ресурсы..
Заказано : Число 15, 3
КОформлению : Число 15, 3
}
@enduml
