@startuml ТрудозатратыКОформлению
'!include templates.wsd
'..\include templates.wsd
class РегистрНакопления.ТрудозатратыКОформлению as "Трудозатраты к оформлению" <<РегистрыНакопления>>
{
..Измерения..
Организация : Справочник.Организация
Распоряжение : Документ.Этап производства\rДокумент.Производство без заказа\rДокумент.Маршрутный лист производства\r...
ВидРабот : Справочник.Вид работ сотрудников
Исполнитель : Справочник.Бригады\rСправочник.Физическое лицо
КодСтрокиРаспоряжения : Число 10, 0
Подразделение : Справочник.Подразделение
..Ресурсы..
Количество : Число 15, 3
}
@enduml
