@startuml АнализОстатковТоваровОрганизаций
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализОстатковТоваровОрганизаций as "Анализ остатков товаров организаций" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
