@startuml АнализОпроса
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализОпроса as "Анализ опроса" <<Отчеты>>
{
..Макеты..
МакетОтветы : ТабличныйДокумент
ПростыеВопросы : СхемаКомпоновкиДанных
МакетОтветившие : ТабличныйДокумент
}
@enduml
