@startuml УсловияЗакупок
'!include templates.wsd
'..\include templates.wsd
class Отчет.УсловияЗакупок as "Условия закупок" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
