@startuml ТоварыПринятыеНаХранение
'!include templates.wsd
'..\include templates.wsd
class Отчет.ТоварыПринятыеНаХранение as "Товары, принятые на хранение" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
