@startuml РегламентированныйОтчетУтилизационныйСбор
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетУтилизационныйСбор as "Расчет суммы утилизационного сбора в отношении колесных транспортных средств (шасси) и (или) прицепов к ним" <<Отчеты>>
{
..Макеты..
МБ_1151091_5_01000_01_tif : ДвоичныеДанные
МБ_1151091_5_02000_02_tif : ДвоичныеДанные
МБ_1151091_5_03000_03_tif : ДвоичныеДанные
МБ_1151091_5_04000_04_tif : ДвоичныеДанные
ПечатныйБланк2014Кв1_Раздел1 : ТабличныйДокумент
ПечатныйБланк2014Кв1_Сведения : ТабличныйДокумент
ПечатныйБланк2014Кв1_Титульный : ТабличныйДокумент
ПечатныйБланк2014Кв3_Раздел1 : ТабличныйДокумент
ПечатныйБланк2014Кв3_Сведения : ТабличныйДокумент
ПечатныйБланк2014Кв3_Титульный : ТабличныйДокумент
ПечатныйБланк2016Кв1_Раздел1 : ТабличныйДокумент
ПечатныйБланк2016Кв1_Сведения : ТабличныйДокумент
ПечатныйБланк2016Кв1_Титульный : ТабличныйДокумент
ПечатныйБланк2016Кв4_Раздел1 : ТабличныйДокумент
ПечатныйБланк2016Кв4_Сведения : ТабличныйДокумент
ПечатныйБланк2016Кв4_Титульный : ТабличныйДокумент
СоставПоказателей2014Кв1 : ТабличныйДокумент
СоставПоказателей2014Кв3 : ТабличныйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
СоставПоказателей2016Кв4 : ТабличныйДокумент
СпискиВыбора2014Кв1 : ТабличныйДокумент
СпискиВыбора2014Кв3 : ТабличныйДокумент
СпискиВыбора2016Кв1 : ТабличныйДокумент
СпискиВыбора2016Кв4 : ТабличныйДокумент
СтруктураXML501 : ТабличныйДокумент
СтруктураXML502 : ТабличныйДокумент
СхемаВыгрузки503 : ТабличныйДокумент
СхемаВыгрузки504 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2014Кв1_Сведения : ТабличныйДокумент
ФормаОтчета2014Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2014Кв3_Раздел1 : ТабличныйДокумент
ФормаОтчета2014Кв3_Сведения : ТабличныйДокумент
ФормаОтчета2014Кв3_Титульный : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2016Кв1_Сведения : ТабличныйДокумент
ФормаОтчета2016Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2016Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2016Кв4_Сведения : ТабличныйДокумент
ФормаОтчета2016Кв4_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2016Кв4 : ТекстовыйДокумент
}
@enduml
