@startuml СвязиПоказателейБюджетов
'!include templates.wsd
'..\include templates.wsd
class Отчет.СвязиПоказателейБюджетов as "Связи показателей бюджетов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
