@startuml АнализЗатрат
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализЗатрат as "Анализ затрат" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
