@startuml ВоинскийУчетОбщий
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВоинскийУчетОбщий as "Воинский учет (общий)" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
ПФ_MXL_СписокГражданПодлежащихПостановкеНаВоинскийУчет : ТабличныйДокумент
ПФ_MXL_СписокЮношейДляОВК : ТабличныйДокумент
ПФ_MXL_СписокПервоначальнойПостановкиНаВоинскийУчет : ТабличныйДокумент
ПФ_MXL_СписокДляСверкиСВоенкоматом : ТабличныйДокумент
ПФ_MXL_КарточкаОповещения : ТабличныйДокумент
ПФ_MXL_РаспискаПриПриемеДокументов : ТабличныйДокумент
ПФ_MXL_КарточкаУчета : ТабличныйДокумент
ПФ_MXL_ИзвещениеОПриемеУвольнении : ТабличныйДокумент
ПФ_MXL_КарточкаУчета2015 : ТабличныйДокумент
ПФ_MXL_ИзвещениеОПриемеУвольнении2017 : ТабличныйДокумент
ПФ_MXL_СписокГражданПодлежащихПостановкеНаВоинскийУчет2017 : ТабличныйДокумент
ПФ_MXL_СписокЮношейДляОВК2017 : ТабличныйДокумент
ПФ_MXL_СписокДляСверкиСВоенкоматом2017 : ТабличныйДокумент
}
@enduml
