@startuml ИсполнениеПланаПроизводства
'!include templates.wsd
'..\include templates.wsd
class Отчет.ИсполнениеПланаПроизводства as "Исполнение плана производства" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
