@startuml РасшифровкаПоказателейНДС
'!include templates.wsd
'..\include templates.wsd
class Отчет.РасшифровкаПоказателейНДС as "Расшифровка показателей НДС" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
РежимРасшифровки : Булево
ВключатьОбособленныеПодразделения : Булево
РазмещениеДополнительныхПолей : Число 1, 0
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
