@startuml РасшифровкаРСВ1
'!include templates.wsd
'..\include templates.wsd
class Отчет.РасшифровкаРСВ1 as "Расшифровка РСВ-1" <<Отчеты>>
{
..Макеты..
Раздел21Доходы2013 : СхемаКомпоновкиДанных
Раздел21Взносы2013 : СхемаКомпоновкиДанных
Раздел22Доходы2013 : СхемаКомпоновкиДанных
Раздел22Взносы2013 : СхемаКомпоновкиДанных
Раздел312013 : СхемаКомпоновкиДанных
Раздел21Доходы2014 : СхемаКомпоновкиДанных
Раздел21Взносы2014 : СхемаКомпоновкиДанных
Раздел22Доходы2014 : СхемаКомпоновкиДанных
Раздел22Взносы2014 : СхемаКомпоновкиДанных
Раздел24Доходы2014 : СхемаКомпоновкиДанных
Раздел24Взносы2014 : СхемаКомпоновкиДанных
Раздел21Взносы2015 : СхемаКомпоновкиДанных
}
@enduml
