@startuml ПлановаяИФактическаяСебестоимостьПродукции
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПлановаяИФактическаяСебестоимостьПродукции as "Плановая и фактическая себестоимость продукции" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
