@startuml РасшифровкаПоступлениеМатериаловВПроизводство
'!include templates.wsd
'..\include templates.wsd
class Отчет.РасшифровкаПоступлениеМатериаловВПроизводство as "Расшифровка поступление материалов в производство" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
