@startuml СправкаРасчетПоказателяБюджетов
'!include templates.wsd
'..\include templates.wsd
class Отчет.СправкаРасчетПоказателяБюджетов as "Справка расчет показателя бюджетов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
