@startuml СтоимостьМатериаловИРаботСпецификации
'!include templates.wsd
'..\include templates.wsd
class Отчет.СтоимостьМатериаловИРаботСпецификации as "Стоимость материалов и работ спецификации" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
