@startuml МониторБюджетныхПроцессов
'!include templates.wsd
'..\include templates.wsd
class Отчет.МониторБюджетныхПроцессов as "Монитор бюджетных процессов" <<Отчеты>>
{
..Реквизиты..
МодельБюджетирования : Справочник.Модели бюджетирования
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
