@startuml ПланФактныйАнализКредитовИДепозитов
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПланФактныйАнализКредитовИДепозитов as "План-фактный анализ оплат и начислений" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
