@startuml ПроизводственныеЗатратыПостатейные
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПроизводственныеЗатратыПостатейные as "Движение постатейных расходов в производстве" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
