@startuml СостояниеРасчетовСКлиентами
'!include templates.wsd
'..\include templates.wsd
class Отчет.СостояниеРасчетовСКлиентами as "Задолженность клиентов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
