@startuml ВыручкаИСебестоимостьПродаж
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВыручкаИСебестоимостьПродаж as "Продажи" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
