@startuml АнализЖурналаРегистрации
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализЖурналаРегистрации as "Анализ журнала регистрации" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
МакетОтчетаПоОшибкамВЖурналеРегистрации : ТабличныйДокумент
ПродолжительностьРаботыРегламентныхЗаданий : ТабличныйДокумент
РасшифровкаРегламентныхЗаданий : ТабличныйДокумент
}
@enduml
