@startuml ОтклоненияВыпускаПродукцииОтГрафика
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОтклоненияВыпускаПродукцииОтГрафика as "Отклонения выпуска продукции от графика" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
