@startuml ВероятностныйПрогноз
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВероятностныйПрогноз as "Вероятностный прогноз" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
