@startuml РегламентированныйОтчетСтатистикаФорма1ИЖС
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма1ИЖС as "Форма 1-ИЖС "Сведения о построенных населением жилых домах"" <<Отчеты>>
{
..Макеты..
СхемаВыгрузкиXML2012Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2012Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2014Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2014Кв1 : ТабличныйДокумент
ФормаОтчета2012Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2014Кв1_ФормаОтчета : ТабличныйДокумент
НастройкиЗагрузкиXML2014Кв1 : ТекстовыйДокумент
}
@enduml
