@startuml ЭффективностьСделокСКлиентами
'!include templates.wsd
'..\include templates.wsd
class Отчет.ЭффективностьСделокСКлиентами as "Эффективность сделок с клиентами" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
