@startuml РасшифровкаПоступленийПоНоменклатуре
'!include templates.wsd
'..\include templates.wsd
class Отчет.РасшифровкаПоступленийПоНоменклатуре as "Расшифровка поступлений по номенклатуре" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
