@startuml РекомендацииПоПовышениюСкоростиРасчетаЭкземпляраБюджета
'!include templates.wsd
'..\include templates.wsd
class Отчет.РекомендацииПоПовышениюСкоростиРасчетаЭкземпляраБюджета as "Рекомендации по повышению скорости расчета экземпляра бюджета" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
