@startuml РегламентированноеУведомлениеСообщениеОбУчастии
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеСообщениеОбУчастии as "Регламентированное уведомление С-09-2" <<Отчеты>>
{
..Макеты..
Форма2014_1 : ТабличныйДокумент
ПараметрыФорма2014_1 : ТабличныйДокумент
СхемаВыгрузкиФорма2014_1 : ТабличныйДокумент
Печать_MXL_Форма2014_1 : ТабличныйДокумент
}
@enduml
