@startuml РегламентированныйОтчетПрибыльИностраннойОрганизации
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетПрибыльИностраннойОрганизации as "Декларация по налогу на прибыль иностранной организации" <<Отчеты>>
{
..Макеты..
МБ_1151038_3_00003_04_tif : ДвоичныеДанные
МБ_1151038_3_00004_05_tif : ДвоичныеДанные
ПечатнаяФормаОтчета2007Кв1_Раздел1_1 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел1_2 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел1_3 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел10 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел10_Прил1 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел11 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел11_Прил1 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел11_Прил2 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел2 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел3 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел4 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел5 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел6 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел7 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел8 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел9 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_ФизЛица : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел1_1 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел1_2 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел1_3 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел10 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел10_Прил1 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел11 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел11_Прил1 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел11_Прил2 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел2 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел3 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел4 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел5 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел6 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел7 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел8 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел9 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_ФизЛица : ТабличныйДокумент
СоставПоказателей2007Кв1 : ТабличныйДокумент
СоставПоказателей2014Кв1 : ТабличныйДокумент
Списки2005Кв1 : ТабличныйДокумент
Списки2014Кв1 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел1_1 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел1_2 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел1_3 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел10 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел10_Прил1 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел11 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел11_Прил1 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел11_Прил2 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел4 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел5 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел6 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел7 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел8 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел9 : ТабличныйДокумент
ФормаОтчета2007Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2007Кв1_ФизЛица : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел1_1 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел1_2 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел1_3 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел10 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел10_Прил1 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел11 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел11_Прил1 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел11_Прил2 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел4 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел5 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел6 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел7 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел8 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел9 : ТабличныйДокумент
ФормаОтчета2014Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2014Кв1_ФизЛица : ТабличныйДокумент
НастройкиЗагрузкиXML2014Кв1 : ТекстовыйДокумент
}
@enduml
