@startuml СостояниеВыполненияЗаказовНаПроизводство
'!include templates.wsd
'..\include templates.wsd
class Отчет.СостояниеВыполненияЗаказовНаПроизводство as "Состояние выполнения заказов на производство" <<Отчеты>>
{
}
@enduml
