@startuml РегламентированныйОтчетСтатистикаФорма1Т
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма1Т as "Форма 1-торги "Сведения о проведении торгов и других способов размещения заказов на поставки товаров, выполнение работ, оказание услуг для государственных и муниципальных нужд"" <<Отчеты>>
{
..Макеты..
СхемаВыгрузкиXML2010Кв4 : ТабличныйДокумент
АтрибВыгрузкиXML2010Кв4 : ТабличныйДокумент
СхемаВыгрузкиXML2012Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2012Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2013Кв1 : ТабличныйДокумент
ФормаОтчета2010Кв4_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2012Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2013Кв1_ФормаОтчета : ТабличныйДокумент
НастройкиЗагрузкиXML2012Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2013Кв1 : ТекстовыйДокумент
}
@enduml
