@startuml ПереданнаяВозвратнаяТара
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПереданнаяВозвратнаяТара as "Переданная возвратная тара" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
