@startuml ДиаграммаСмежныхЭтаповПроизводства
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДиаграммаСмежныхЭтаповПроизводства as "Диаграмма смежных этапов производства" <<Отчеты>>
{
}
@enduml
