@startuml ВедомостьАмортизацииОСБухгалтерскийУчет
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВедомостьАмортизацииОСБухгалтерскийУчет as "Ведомость амортизации ОС" <<Отчеты>>
{
..Реквизиты..
ВключатьОбособленныеПодразделения : Булево
КонецПериода : Дата
НачалоПериода : Дата
Организация : Справочник.Организация
Подразделение : Справочник.Подразделение
РазмещениеДополнительныхПолей : Число 1, 0
РежимРасшифровки : Булево
ПоказательНУ : Булево
ПоказательБУ : Булево
ПоказательВР : Булево
ПоказательПР : Булево
ПоказательКонтроль : Булево
..Макеты..
СхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
