@startuml ТоварыКОтбору
'!include templates.wsd
'..\include templates.wsd
class Отчет.ТоварыКОтбору as "Выполнение отбора товаров" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
