@startuml РегламентированныйОтчетФорма2ТПОтходы
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетФорма2ТПОтходы as "Форма 2-ТП (отходы) "Сведения об образовании, использовании, обезвреживании, транспортировании и размещении отходов производства и потребления"" <<Отчеты>>
{
..Макеты..
Списки2012Кв1 : ТабличныйДокумент
Списки2017Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2012Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
ФормаОтчета2012Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2017Кв1_ФормаОтчета : ТабличныйДокумент
СоставПоказателей2012Кв1 : ТабличныйДокумент
СоставПоказателей2017Кв1 : ТабличныйДокумент
НастройкиЗагрузкиXML2012Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
}
@enduml
