@startuml КарточкаРасчетовСКлиентами
'!include templates.wsd
'..\include templates.wsd
class Отчет.КарточкаРасчетовСКлиентами as "Карточка расчетов с клиентами" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
