@startuml АнализПричинОтменыЗаказовПоставщикам
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализПричинОтменыЗаказовПоставщикам as "Анализ причин отмены заказов поставщикам" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
