@startuml ОтражениеЗарплатыВФинансовомУчете
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОтражениеЗарплатыВФинансовомУчете as "Отражение зарплаты в финансовом учете" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
