@startuml РегламентированныйОтчетАлкоПриложение10
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетАлкоПриложение10 as "Декларация об использовании мощностей по производству этилового спирта и алкогольной продукции" <<Отчеты>>
{
..Макеты..
ПечатнаяФормаОтчета2012Кв3_Лицензии : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Титульный_20140101 : ТабличныйДокумент
СоставПоказателей2012Кв3 : ТабличныйДокумент
Списки2012Кв3 : ТабличныйДокумент
Списки2012Кв3_20131101 : ТабличныйДокумент
Списки2014Кв1 : ТабличныйДокумент
Списки2015Кв3 : ТабличныйДокумент
СхемаВыгрузки420 : ТабличныйДокумент
СхемаВыгрузки430 : ТабличныйДокумент
СхемаВыгрузки430_2014Кв1 : ТабличныйДокумент
ФормаОтчета2012Кв3_Декларация : ТабличныйДокумент
ФормаОтчета2012Кв3_Декларация_20140101 : ТабличныйДокумент
ФормаОтчета2012Кв3_Лицензии : ТабличныйДокумент
ФормаОтчета2012Кв3_Титульный : ТабличныйДокумент
ФормаОтчета2012Кв3_Титульный_20140101 : ТабличныйДокумент
СхемаВыгрузки431 : ТабличныйДокумент
НастройкиЗагрузкиXML2012Кв3 : ТекстовыйДокумент
}
@enduml
