@startuml ЖурналУчетаСчетовФактур
'!include templates.wsd
'..\include templates.wsd
class Отчет.ЖурналУчетаСчетовФактур as "Журнал счетов-фактур" <<Отчеты>>
{
..Реквизиты..
Период : Дата
НачалоПериода : Дата
КонецПериода : Дата
Организация : Справочник.Организация
ГруппироватьПоКонтрагентам : Булево
КонтрагентДляОтбора : Справочник.Организация\rСправочник.Контрагент
ОтбиратьПоКонтрагенту : Булево
СформироватьОтчетПоСтандартнойФорме : Булево
ВключатьОбособленныеПодразделения : Булево
}
@enduml
