@startuml ИнформацияОбОрганизацииЕГАИС
'!include templates.wsd
'..\include templates.wsd
class Отчет.ИнформацияОбОрганизацииЕГАИС as "Информация об организации ЕГАИС" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
