@startuml РегламентированныйОтчетСтатистикаФорма1ИПуслуги
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма1ИПуслуги as "Форма № 1-ИП (услуги) "Сведения об объеме платных услуг, оказанных населению индивидуальным предпринимателем"" <<Отчеты>>
{
..Макеты..
Списки2017кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
ФормаОтчета2017Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1 : ТабличныйДокумент
ШаблонРосстата2017Кв1 : ДвоичныеДанные
СоставПоказателей2017Кв1 : ТабличныйДокумент
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
}
@enduml
