@startuml ПродажиСравнениеАналогичныхПериодов
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПродажиСравнениеАналогичныхПериодов as "Сравнение продаж аналогичных периодов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
