@startuml АнализПричинЗадержекВыполненияМаршрутныхЛистов
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализПричинЗадержекВыполненияМаршрутныхЛистов as "Анализ причин задержек выполнения маршрутных листов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
