@startuml ЗаявлениеДСВ1
'!include templates.wsd
'..\include templates.wsd
class Отчет.ЗаявлениеДСВ1 as "Заявление ДСВ-1" <<Отчеты>>
{
..Макеты..
ПФ_MXL_ФормаДСВ_1 : ТабличныйДокумент
МакетГруппировки : ТабличныйДокумент
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
