@startuml СправкаРасчетПостоянныхИВременныхРазниц
'!include templates.wsd
'..\include templates.wsd
class Отчет.СправкаРасчетПостоянныхИВременныхРазниц as "Справка-расчет "Постоянные и временные разницы"" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
ВключатьОбособленныеПодразделения : Булево
ПоказательБУ : Булево
ПоказательНУ : Булево
ПоказательПР : Булево
ПоказательВР : Булево
РежимРасшифровки : Булево
НаборПоказателейОтчета : Число 1, 0
СНачалаГода : Булево
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
