@startuml РегламентированныйОтчетПрибыльСколковоРасчетПрибыли
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетПрибыльСколковоРасчетПрибыли as "Расчет совокупного размера прибыли (убытка) участника "Сколково"" <<Отчеты>>
{
..Макеты..
ФормаОтчета2011Кв3_Титульный : ТабличныйДокумент
ФормаОтчета2011Кв3_Расчет : ТабличныйДокумент
СоставПоказателей2011Кв3 : ТабличныйДокумент
МЧБ_2011Кв3_1 : ТабличныйДокумент
МЧБ_2011Кв3_2 : ТабличныйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
МБ_1150021_5_01000_01_tif : ДвоичныеДанные
НастройкиЗагрузкиXML2011Кв3 : ТекстовыйДокумент
}
@enduml
