@startuml РегламентированныйОтчетУтилизационныйСборСамоходныеМашины
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетУтилизационныйСборСамоходныеМашины as "Расчет суммы утилизационного сбора в отношении самоходных машин и (или) прицепов к ним" <<Отчеты>>
{
..Макеты..
МБ_1151101_5_01000_01_tif : ДвоичныеДанные
МБ_1151101_5_01000_02_tif : ДвоичныеДанные
ПечатныйБланк2016Кв1_Раздел1 : ТабличныйДокумент
ПечатныйБланк2016Кв1_Сведения : ТабличныйДокумент
ПечатныйБланк2016Кв1_Титульный : ТабличныйДокумент
ПечатныйБланк2016Кв4_Раздел1 : ТабличныйДокумент
ПечатныйБланк2016Кв4_Сведения : ТабличныйДокумент
ПечатныйБланк2016Кв4_Титульный : ТабличныйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
СоставПоказателей2016Кв4 : ТабличныйДокумент
СпискиВыбора2016Кв1 : ТабличныйДокумент
СпискиВыбора2016Кв4 : ТабличныйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
СхемаВыгрузки501_2016Кв4 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2016Кв1_Сведения : ТабличныйДокумент
ФормаОтчета2016Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2016Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2016Кв4_Сведения : ТабличныйДокумент
ФормаОтчета2016Кв4_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2016Кв4 : ТекстовыйДокумент
}
@enduml
