@startuml СравнениеОС
'!include templates.wsd
'..\include templates.wsd
class Отчет.СравнениеОС as "Сравнение ОС в регламентированном и международном учете" <<Отчеты>>
{
..Макеты..
Макет : ТабличныйДокумент
}
@enduml
