@startuml РегламентированноеУведомлениеФормаР24001
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеФормаР24001 as "Заявление о внесении изменений по ИП" <<Отчеты>>
{
..Макеты..
СпискиВыбора2014_1 : ТабличныйДокумент
СхемаВыгрузкиФорма2014_1 : ТабличныйДокумент
TIFF_2014_1 : ДвоичныеДанные
Форма2014_1_Страница1 : ТабличныйДокумент
Форма2014_1_Страница2 : ТабличныйДокумент
Форма2014_1_Страница3 : ТабличныйДокумент
Форма2014_1_Страница4 : ТабличныйДокумент
Форма2014_1_Страница5 : ТабличныйДокумент
Форма2014_1_Страница6 : ТабличныйДокумент
Форма2014_1_Страница7 : ТабличныйДокумент
Форма2014_1_Страница8 : ТабличныйДокумент
Форма2014_1_Страница9 : ТабличныйДокумент
Печать_Форма2014_1_Страница1 : ТабличныйДокумент
Печать_Форма2014_1_Страница2 : ТабличныйДокумент
Печать_Форма2014_1_Страница3 : ТабличныйДокумент
Печать_Форма2014_1_Страница4 : ТабличныйДокумент
Печать_Форма2014_1_Страница5 : ТабличныйДокумент
Печать_Форма2014_1_Страница6 : ТабличныйДокумент
Печать_Форма2014_1_Страница7 : ТабличныйДокумент
Печать_Форма2014_1_Страница8 : ТабличныйДокумент
Печать_Форма2014_1_Страница9 : ТабличныйДокумент
}
@enduml
