@startuml РегламентированныйОтчетФинансовыйРезультатИнвестиционногоТоварищества
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетФинансовыйРезультатИнвестиционногоТоварищества as "Расчет финансового результата инвестиционного товарищества" <<Отчеты>>
{
..Макеты..
МБ_1150023_5_01000_01_tif : ДвоичныеДанные
МЧБ_2012Кв3_Раздел1 : ТабличныйДокумент
МЧБ_2012Кв3_Раздел2 : ТабличныйДокумент
МЧБ_2012Кв3_Раздел3 : ТабличныйДокумент
МЧБ_2012Кв3_Титульный : ТабличныйДокумент
СоставПоказателей2012Кв3 : ТабличныйДокумент
СпискиВыбора2012Кв3 : ТабличныйДокумент
СтруктураXML501 : ТабличныйДокумент
ФормаОтчета2012Кв3_Раздел1 : ТабличныйДокумент
ФормаОтчета2012Кв3_Раздел2 : ТабличныйДокумент
ФормаОтчета2012Кв3_Раздел3 : ТабличныйДокумент
ФормаОтчета2012Кв3_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2012Кв3 : ТекстовыйДокумент
}
@enduml
