@startuml ЗависшиеЗадачи
'!include templates.wsd
'..\include templates.wsd
class Отчет.ЗависшиеЗадачи as "Зависшие задачи" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
