@startuml ПредметыКонтролируемыхСделок
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПредметыКонтролируемыхСделок as "Предметы контролируемых сделок" <<Отчеты>>
{
..Реквизиты..
Уведомление : Документ.Уведомление о контролируемых сделках
ОтчетныйГод : Число 4, 0
Организация : Справочник.Организация
РазмещениеДополнительныхПолей : Число 1, 0
КонецПериода : Дата
НачалоПериода : Дата
РежимРасшифровки : Булево
ВключатьОбособленныеПодразделения : Булево
..Макеты..
СхемаКомпоновкиДанныхПредметы : СхемаКомпоновкиДанных
}
@enduml
