@startuml РегламентированныйОтчетПереченьЗаявленийОВвозеТоваров
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетПереченьЗаявленийОВвозеТоваров as "Перечень заявлений о ввозе товаров и уплате косвенных налогов" <<Отчеты>>
{
..Макеты..
МБ_1150035_5_01000_01_tif : ДвоичныеДанные
ПечатныйБланк2015Кв2_Раздел1 : ТабличныйДокумент
ПечатныйБланк2015Кв2_Титульный : ТабличныйДокумент
СоставПоказателей2015Кв2 : ТабличныйДокумент
СпискиВыбора2015Кв2 : ТабличныйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
ФормаОтчета2015Кв2_Раздел1 : ТабличныйДокумент
ФормаОтчета2015Кв2_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2015Кв2 : ТекстовыйДокумент
}
@enduml
