@startuml КарточкаСубконто
'!include templates.wsd
'..\include templates.wsd
class Отчет.КарточкаСубконто as "Карточка субконто" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
ВключатьОбособленныеПодразделения : Булево
Периодичность : Число 2, 0
СписокВидовСубконто : Список значений
РежимРасшифровки : Булево
ПоказательБУ : Булево
ПоказательНУ : Булево
ПоказательПР : Булево
ПоказательВР : Булево
ПоказательКоличество : Булево
ПоказательВалютнаяСумма : Булево
ПоказательУУ : Булево
ПоказательФО : Булево
ПоказательРазницаБУиУУ : Булево
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
СхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
