@startuml ЗаполненностьСклада
'!include templates.wsd
'..\include templates.wsd
class Отчет.ЗаполненностьСклада as "Размещение товаров на адресном складе" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
