@startuml РасшифровкаФормулыБюджетногоОтчета
'!include templates.wsd
'..\include templates.wsd
class Отчет.РасшифровкаФормулыБюджетногоОтчета as "Расшифровка формулы бюджетного отчета" <<Отчеты>>
{
..Реквизиты..
АдресПараметровОтчета : Строка
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
