@startuml БонусныеБаллы
'!include templates.wsd
'..\include templates.wsd
class Отчет.БонусныеБаллы as "Бонусные баллы" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
