@startuml РегламентированноеУведомлениеПрекращениеУСН
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеПрекращениеУСН as "Регламентированное уведомление прекращение деятельности по УСН" <<Отчеты>>
{
..Макеты..
Форма2014_1 : ТабличныйДокумент
ПараметрыФорма2014_1 : ТабличныйДокумент
СхемаВыгрузкиФорма2014_1 : ТабличныйДокумент
Печать_MXL_Форма2014_1 : ТабличныйДокумент
TIFF_2014_1 : ДвоичныеДанные
}
@enduml
