@startuml АнализПретензийКлиентов
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализПретензийКлиентов as "Претензии клиентов" <<Отчеты>>
{
..Макеты..
Макет : СхемаКомпоновкиДанных
}
@enduml
