@startuml ОрганизационнаяСтруктура
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОрганизационнаяСтруктура as "Организационная структура" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
ПФ_MXL_ОрганизационнаяСтруктура : ТабличныйДокумент
}
@enduml
