@startuml ИспользуемыеВнешниеРесурсы
'!include templates.wsd
'..\include templates.wsd
class Отчет.ИспользуемыеВнешниеРесурсы as "Внешние ресурсы, используемые программой и дополнительными модулями" <<Отчеты>>
{
..Макеты..
ПредставленияРазрешений : ТабличныйДокумент
}
@enduml
