@startuml РегламентированноеУведомлениеПостановкаСнятиеВКачествеАгента
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеПостановкаСнятиеВКачествеАгента as "Заявление о постановке (снятии) с учета в качестве налогового агента" <<Отчеты>>
{
..Макеты..
Печать_Форма2017_1_Титульная : ТабличныйДокумент
Печать_Форма2017_1_СведМО : ТабличныйДокумент
СхемаВыгрузкиФорма2017_1 : ТабличныйДокумент
СпискиВыбора2017_1 : ТабличныйДокумент
Титульная : ТабличныйДокумент
СведМО : ТабличныйДокумент
ОбщиеЭлементы : ТабличныйДокумент
}
@enduml
