@startuml СертификатыНоменклатурыСИстекающимСрокомДействия
'!include templates.wsd
'..\include templates.wsd
class Отчет.СертификатыНоменклатурыСИстекающимСрокомДействия as "Сертификаты номенклатуры с истекающим сроком действия" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
