@startuml РегламентированноеУведомлениеПолучениеДокументаНалоговогоРезидента
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеПолучениеДокументаНалоговогоРезидента as "Заявление о представлении документа, подтверждающего статус налогового резидента РФ" <<Отчеты>>
{
..Макеты..
Печать_Форма2017_1_Титульная : ТабличныйДокумент
Печать_Форма2017_1_СведЮЛ : ТабличныйДокумент
Печать_Форма2017_1_СведФЛ : ТабличныйДокумент
СпискиВыбора2017_1 : ТабличныйДокумент
Титульная : ТабличныйДокумент
СведЮЛ : ТабличныйДокумент
СведФЛ : ТабличныйДокумент
}
@enduml
