@startuml СправкаРасчетНалогаНаИмущество
'!include templates.wsd
'..\include templates.wsd
class Отчет.СправкаРасчетНалогаНаИмущество as "Расчет налога (авансового платежа по налогу) на имущество" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
РежимРасшифровки : Булево
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
