@startuml КонтрольКорректностиЗаполненияОбъектовЭксплуатации
'!include templates.wsd
'..\include templates.wsd
class Отчет.КонтрольКорректностиЗаполненияОбъектовЭксплуатации as "Контроль корректности заполнения объектов эксплуатации" <<Отчеты>>
{
..Реквизиты..
ОбъектЭксплуатации : Справочник.Объект эксплуатации
..Макеты..
МакетОтчета : ТабличныйДокумент
}
@enduml
