@startuml РегламентированныйОтчетСведенияОСреднесписочнойЧисленностиРаботников
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСведенияОСреднесписочнойЧисленностиРаботников as "Сведения о среднесписочной численности работников за предшествующий календарный год" <<Отчеты>>
{
..Макеты..
МБ_1110018_4_01000_04_tif : ДвоичныеДанные
МБ_1110018_4_01000_06_tif : ДвоичныеДанные
СоставПоказателей2007Кв1 : ТабличныйДокумент
СтруктураXML2007 : ТабличныйДокумент
ФормаОтчета2007Кв1_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2007Кв1 : ТекстовыйДокумент
}
@enduml
