@startuml РеестрУчетныхДанных
'!include templates.wsd
'..\include templates.wsd
class Отчет.РеестрУчетныхДанных as "Реестр учетных данных" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
