@startuml ИсполнениеРаспоряженийНаПеремещениеСборку
'!include templates.wsd
'..\include templates.wsd
class Отчет.ИсполнениеРаспоряженийНаПеремещениеСборку as "Исполнение распоряжений на перемещение и сборку" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
