@startuml ВедомостьПоПринятойВозвратнойТаре
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВедомостьПоПринятойВозвратнойТаре as "Ведомость по принятой возвратной таре" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
