@startuml ПричиныЗапретаОтгрузки
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПричиныЗапретаОтгрузки as "Причины запрета отгрузки" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
