@startuml СравнительныйАнализДинамикиАссортиментаИПродаж
'!include templates.wsd
'..\include templates.wsd
class Отчет.СравнительныйАнализДинамикиАссортиментаИПродаж as "Динамика ассортимента и продаж" <<Отчеты>>
{
..Реквизиты..
АнализируемыйПериод : Стандартный период
ПериодДляСравнения : Стандартный период
ВыбранныйВариант : Строка
НомерКолонкиРасшифровки : Число 1, 0
..Макеты..
Макет : ТабличныйДокумент
СхемаДляОтбора : СхемаКомпоновкиДанных
}
@enduml
