@startuml УниверсальныйОтчет
'!include templates.wsd
'..\include templates.wsd
class Отчет.УниверсальныйОтчет as "Универсальный отчет" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
