@startuml ВыполнениеУсловийСоглашенийСКлиентами
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВыполнениеУсловийСоглашенийСКлиентами as "Выполнение регулярных условий соглашений с клиентами" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
