@startuml ДоступностьВариантовАнализаЦелевыхПоказателей
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДоступностьВариантовАнализаЦелевыхПоказателей as "Доступность вариантов анализа целевых показателей" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
