@startuml ОборотноСальдоваяВедомостьАктивовПассивов
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОборотноСальдоваяВедомостьАктивовПассивов as "Оборотно-сальдовая ведомость активов и пассивов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
