@startuml РегламентированныйОтчет4аФСС
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчет4аФСС as "Расчет страховых взносов в ФСС по временной нетрудоспособности  (форма 4а-ФСС)" <<Отчеты>>
{
..Макеты..
СоставПоказателей2010Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML01 : ТабличныйДокумент
ФормаОтчета2010Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2010Кв1_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2010Кв1 : ТекстовыйДокумент
}
@enduml
