@startuml ДеревоСебестоимостиПродукции
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДеревоСебестоимостиПродукции as "Дерево себестоимости продукции" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
