@startuml АнализЦенПоставщиков
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализЦенПоставщиков as "Анализ цен" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
