@startuml ОплатаЗаявокНаРасходованиеДенежныхСредств
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОплатаЗаявокНаРасходованиеДенежныхСредств as "Оплата заявок на расходование денежных средств" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
