@startuml РегламентированныйОтчетСведенияОСчетахвВиностраннойВалюте
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСведенияОСчетахвВиностраннойВалюте as "Сведения о счетах в иностранной валюте" <<Отчеты>>
{
..Макеты..
ФормаОтчета2005Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2015Кв1_ФормаОтчета : ТабличныйДокумент
}
@enduml
