@startuml УправленческийБалансКонтроль
'!include templates.wsd
'..\include templates.wsd
class Отчет.УправленческийБалансКонтроль as "Управленческий баланс (контроль)" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
