@startuml РегламентированныйОтчетСтатистикаФорма1Тчзп
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма1Тчзп as "Форма 1-Т "Сведения о численности и заработной плате работников"" <<Отчеты>>
{
..Макеты..
Списки2013кв1 : ТабличныйДокумент
Списки2014кв1 : ТабличныйДокумент
Списки2016кв1 : ТабличныйДокумент
Списки2017кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2013Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2014Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2014Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2016Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
ФормаОтчета2013Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2014Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2016Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2017Кв1_ФормаОтчета : ТабличныйДокумент
ШаблонРосстата2016Кв1 : ДвоичныеДанные
ШаблонРосстата2017Кв1 : ДвоичныеДанные
НастройкиЗагрузкиXML2014Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
}
@enduml
