@startuml РасчетыСПоставщиками
'!include templates.wsd
'..\include templates.wsd
class Отчет.РасчетыСПоставщиками as "Ведомость расчетов с поставщиками" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
