@startuml РегламентированныйОтчетУСН
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетУСН as "Декларация по налогу, уплачиваемому в связи с применением УСН" <<Отчеты>>
{
..Макеты..
МБ_1152017_5_01000_06_tif : ДвоичныеДанные
МБ_1152017_5_02000_07_tif : ДвоичныеДанные
МБ_1152017_5_03000_08_tif : ДвоичныеДанные
МБ_1152017_5_04000_09_tif : ДвоичныеДанные
МБ_1152017_5_05000_11_tif : ДвоичныеДанные
МЧБ_2009Кв1_1 : ТабличныйДокумент
МЧБ_2009Кв1_1_2010 : ТабличныйДокумент
МЧБ_2009Кв1_2 : ТабличныйДокумент
МЧБ_2009Кв1_3 : ТабличныйДокумент
МЧБ_2009Кв1_3_2010 : ТабличныйДокумент
ПечатныйБланк2014Кв1_Вспом_Раздел11 : ТабличныйДокумент
ПечатныйБланк2014Кв1_Вспом_Раздел12 : ТабличныйДокумент
ПечатныйБланк2014Кв1_Вспом_Раздел21 : ТабличныйДокумент
ПечатныйБланк2014Кв1_Вспом_Раздел22 : ТабличныйДокумент
ПечатныйБланк2014Кв1_Вспом_Раздел3 : ТабличныйДокумент
ПечатныйБланк2014Кв1_Вспом_Титульный : ТабличныйДокумент
ПечатныйБланк2014Кв1_Раздел11 : ТабличныйДокумент
ПечатныйБланк2014Кв1_Раздел12 : ТабличныйДокумент
ПечатныйБланк2014Кв1_Раздел21 : ТабличныйДокумент
ПечатныйБланк2014Кв1_Раздел22 : ТабличныйДокумент
ПечатныйБланк2014Кв1_Раздел3 : ТабличныйДокумент
ПечатныйБланк2014Кв1_Титульный : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел11 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел12 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел21 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел22 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел3 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Титульный : ТабличныйДокумент
СоставПоказателей2009Кв1 : ТабличныйДокумент
СоставПоказателей2014Кв1 : ТабличныйДокумент
СоставПоказателей2015Кв1 : ТабличныйДокумент
Списки2009Кв1 : ТабличныйДокумент
СпискиВыбора2014Кв1 : ТабличныйДокумент
СпискиВыбора2015Кв1 : ТабличныйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
СхемаВыгрузки504 : ТабличныйДокумент
СхемаВыгрузки505 : ТабличныйДокумент
ФормаОтчета2009Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2009Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2009Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел11 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел12 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел21 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел22 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2014Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел11 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел12 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел21 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел22 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2015Кв1_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2014Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2015Кв1 : ТекстовыйДокумент
}
@enduml
