@startuml РегламентированныйОтчетДоходыИностраннымОрганизациям
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетДоходыИностраннымОрганизациям as "Налоговый расчет о суммах выплаченных иностранным организациям доходов и удержанных налогов" <<Отчеты>>
{
..Макеты..
МБ_1151056_3_00004_05_tif : ДвоичныеДанные
МБ_1151056_3_00005_06_tif : ДвоичныеДанные
МБ_1151056_5_01000_02_tif : ДвоичныеДанные
ПечатнаяФормаОтчета2007Кв1_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел2 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_ФизЛица : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел2 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_ФизЛица : ТабличныйДокумент
ПечатныйБланк2016Кв1_Раздел1 : ТабличныйДокумент
ПечатныйБланк2016Кв1_Раздел2 : ТабличныйДокумент
ПечатныйБланк2016Кв1_Раздел31 : ТабличныйДокумент
ПечатныйБланк2016Кв1_Раздел32_Лист1 : ТабличныйДокумент
ПечатныйБланк2016Кв1_Раздел32_Лист2 : ТабличныйДокумент
ПечатныйБланк2016Кв1_Раздел33_Лист1 : ТабличныйДокумент
ПечатныйБланк2016Кв1_Раздел33_Лист2 : ТабличныйДокумент
ПечатныйБланк2016Кв1_Титульный : ТабличныйДокумент
СоставПоказателей2007Кв1 : ТабличныйДокумент
СоставПоказателей2014Кв1 : ТабличныйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
Списки2007Кв1 : ТабличныйДокумент
Списки2014Кв1 : ТабличныйДокумент
СпискиВыбора2016Кв1 : ТабличныйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2007Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2007Кв1_ФизЛица : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2014Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2014Кв1_ФизЛица : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел31 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел32 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел33 : ТабличныйДокумент
ФормаОтчета2016Кв1_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
}
@enduml
