@startuml ВедомостьПоСериямНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВедомостьПоСериямНоменклатуры as "Ведомость по сериям номенклатуры" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
