@startuml ПересеченияСегментаНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПересеченияСегментаНоменклатуры as "Пересечения сегмента номенклатуры" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
