@startuml СправкаРасчетФСС
'!include templates.wsd
'..\include templates.wsd
class Отчет.СправкаРасчетФСС as "Справка-расчет для ФСС" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
ПФ_MXL_СправкаРасчет : ТабличныйДокумент
}
@enduml
