@startuml СогласияНаОбработкуПерсональныхДанныхДействующие
'!include templates.wsd
'..\include templates.wsd
class Отчет.СогласияНаОбработкуПерсональныхДанныхДействующие as "Согласия на обработку персональных данных действующие" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
