@startuml СостояниеРасчетовСПоставщиками
'!include templates.wsd
'..\include templates.wsd
class Отчет.СостояниеРасчетовСПоставщиками as "Задолженность поставщикам" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
