@startuml РегламентированноеУведомлениеЗачетНалога
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеЗачетНалога as "Заявление о зачете излишне уплаченного налога" <<Отчеты>>
{
..Макеты..
Печать_Форма2017_1_Титульная : ТабличныйДокумент
Печать_Форма2017_1_Лист002 : ТабличныйДокумент
СхемаВыгрузкиФорма2017_1 : ТабличныйДокумент
TIFF_2017_1 : ДвоичныеДанные
СпискиВыбора2017_1 : ТабличныйДокумент
Титульная : ТабличныйДокумент
Лист002 : ТабличныйДокумент
}
@enduml
