@startuml РегламентированноеУведомлениеСогласиеНаРаскрытиеНалоговойТайны
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеСогласиеНаРаскрытиеНалоговойТайны as "Согласие на раскрытие налоговой тайны" <<Отчеты>>
{
..Макеты..
Печать_Форма2017_1_Титульная : ТабличныйДокумент
Печать_Форма2017_1_Лист002 : ТабличныйДокумент
СхемаВыгрузкиФорма2017_1 : ТабличныйДокумент
TIFF_2017_1 : ДвоичныеДанные
СпискиВыбора2017_1 : ТабличныйДокумент
Титульная : ТабличныйДокумент
Лист002 : ТабличныйДокумент
ОбщиеЭлементы : ТабличныйДокумент
}
@enduml
