@startuml УсловияПродаж
'!include templates.wsd
'..\include templates.wsd
class Отчет.УсловияПродаж as "Условия продаж" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
