@startuml РегламентированныйОтчетТранспортныйНалог
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетТранспортныйНалог as "Декларация по транспортному налогу (годовая)" <<Отчеты>>
{
..Макеты..
МБ_1152004_4_01000_05_tif : ДвоичныеДанные
МБ_1152004_5_01000_06_tif : ДвоичныеДанные
МБ_1152004_5_02000_08_tif : ДвоичныеДанные
МБ_1152004_5_03000_09_tif : ДвоичныеДанные
МБ_1152004_5_04000_10_tif : ДвоичныеДанные
МЧБ_2012Кв1_Раздел1 : ТабличныйДокумент
МЧБ_2012Кв1_Раздел2 : ТабличныйДокумент
МЧБ_2012Кв1_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2013Кв4 : ТекстовыйДокумент
НастройкиЗагрузкиXML2014Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел2 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Титульный : ТабличныйДокумент
ПечатныйБланк2013Кв4_Раздел1 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Раздел2 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Титульный : ТабличныйДокумент
ПечатныйБланк2014Кв1_Раздел1 : ТабличныйДокумент
ПечатныйБланк2014Кв1_Раздел2 : ТабличныйДокумент
ПечатныйБланк2014Кв1_Титульный : ТабличныйДокумент
ПечатныйБланк2016Кв1_Раздел1 : ТабличныйДокумент
ПечатныйБланк2016Кв1_Раздел2 : ТабличныйДокумент
ПечатныйБланк2016Кв1_Титульный : ТабличныйДокумент
СоставПоказателей2007Кв1 : ТабличныйДокумент
СоставПоказателей2012Кв1 : ТабличныйДокумент
СоставПоказателей2012Кв4 : ТабличныйДокумент
СоставПоказателей2013Кв4 : ТабличныйДокумент
СоставПоказателей2014Кв1 : ТабличныйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
Списки2007Кв1 : ТабличныйДокумент
Списки2012Кв1 : ТабличныйДокумент
СпискиВыбора2013Кв4 : ТабличныйДокумент
СпискиВыбора2014Кв1 : ТабличныйДокумент
СпискиВыбора2016Кв1 : ТабличныйДокумент
СтруктураXML2007 : ТабличныйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
СхемаВыгрузки502 : ТабличныйДокумент
СхемаВыгрузки503 : ТабличныйДокумент
СхемаВыгрузки504 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2007Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2012Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2012Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2012Кв4_Раздел2 : ТабличныйДокумент
ФормаОтчета2012Кв4_Титульный : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел2 : ТабличныйДокумент
ФормаОтчета2013Кв4_Титульный : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2014Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2016Кв1_Титульный : ТабличныйДокумент
}
@enduml
