@startuml РегламентированныйОтчетСтатистикаФормаЗПОбразование
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФормаЗПОбразование as "Форма ЗП-образование "Сведения о численности и оплате труда  работников сферы образования по категориям персонала" (Приложение № 1)" <<Отчеты>>
{
..Макеты..
Список2013кв1 : ТабличныйДокумент
Список2014кв1 : ТабличныйДокумент
Список2015кв1 : ТабличныйДокумент
Список2016кв1 : ТабличныйДокумент
Список2017кв1 : ТабличныйДокумент
Список2018кв1 : ТабличныйДокумент
СоставПоказателей2013Кв1 : ТабличныйДокумент
СоставПоказателей2014Кв1 : ТабличныйДокумент
СоставПоказателей2015Кв1 : ТабличныйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
СоставПоказателей2017Кв1 : ТабличныйДокумент
СоставПоказателей2018Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2013Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2014Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2014Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2015Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2016Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2018Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2018Кв1_месяц : ТабличныйДокумент
АтрибВыгрузкиXML2018Кв1_квартал : ТабличныйДокумент
ФормаОтчета2013Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2014Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2015Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2016Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2017Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2018Кв1_ФормаОтчета_месяц : ТабличныйДокумент
ФормаОтчета2018Кв1_ФормаОтчета_квартал : ТабличныйДокумент
ШаблонРосстата2016Кв1 : ДвоичныеДанные
ШаблонРосстата2017Кв1 : ДвоичныеДанные
ШаблонРосстата2018Кв1_месяц : ДвоичныеДанные
ШаблонРосстата2018Кв1_квартал : ДвоичныеДанные
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2018Кв1 : ТекстовыйДокумент
}
@enduml
