@startuml ПроизводственныеЗатратыПоПартиямПроизводства
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПроизводственныеЗатратыПоПартиямПроизводства as "Затраты по партиям производства" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
