@startuml РеестрДоговоровЛизинга
'!include templates.wsd
'..\include templates.wsd
class Отчет.РеестрДоговоровЛизинга as "Реестр договоров лизинга" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
