@startuml БазаРаспределенияМатериаловИРабот
'!include templates.wsd
'..\include templates.wsd
class Отчет.БазаРаспределенияМатериаловИРабот as "База распределения материалов и работ" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
