@startuml ТоварныйКалендарь
'!include templates.wsd
'..\include templates.wsd
class Отчет.ТоварныйКалендарь as "Товарный календарь" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
ВнешнийИсточникДанных : СхемаКомпоновкиДанных
ВнешнийИсточникДанныхСРегистратором : СхемаКомпоновкиДанных
}
@enduml
