@startuml РегламентированныйОтчетСтатистикаФорма57Т
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма57Т as "Форма 57-Т "Сведения о заработной плате работников по профессиям и должностям"" <<Отчеты>>
{
..Макеты..
СхемаВыгрузкиXML2015Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1 : ТабличныйДокумент
ФормаОтчета2015Кв1_ФормаОтчета : ТабличныйДокумент
СоставПоказателей2015Кв1 : ТабличныйДокумент
Списки2015Кв1 : ТабличныйДокумент
ШаблонРосстата2015Кв1 : ДвоичныеДанные
НастройкиЗагрузкиXML2015Кв1 : ТекстовыйДокумент
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1 : ТабличныйДокумент
ФормаОтчета2017Кв1_ФормаОтчета : ТабличныйДокумент
СоставПоказателей2017Кв1 : ТабличныйДокумент
Списки2017Кв1 : ТабличныйДокумент
ШаблонРосстата2017Кв1 : ДвоичныеДанные
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
}
@enduml
