@startuml РегламентированныйОтчетСтатистикаФорма11НА
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма11НА as "Форма 11-НА "Сведения о наличии, движении и составе контрактов, договоров аренды, лицензий, маркетинговых активов и гудвилла (деловой репутации организации)"" <<Отчеты>>
{
..Макеты..
АтрибВыгрузкиXML2013Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2015Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2016Кв1 : ТабличныйДокумент
ФормаОтчета2013Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2015Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2016Кв1_ФормаОтчета : ТабличныйДокумент
СоставПоказателей2013Кв1 : ТабличныйДокумент
СоставПоказателей2015Кв1 : ТабличныйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
Списки2013кв1 : ТабличныйДокумент
Списки2015кв1 : ТабличныйДокумент
Списки2016кв1 : ТабличныйДокумент
ШаблонРосстата2016Кв1 : ДвоичныеДанные
НастройкиЗагрузкиXML2015Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
АтрибВыгрузкиXML2017Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
ФормаОтчета2017Кв1_ФормаОтчета : ТабличныйДокумент
СоставПоказателей2017Кв1 : ТабличныйДокумент
Списки2017кв1 : ТабличныйДокумент
ШаблонРосстата2017Кв1 : ДвоичныеДанные
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
}
@enduml
