@startuml КалендарьСобытий
'!include templates.wsd
'..\include templates.wsd
class Отчет.КалендарьСобытий as "Календарь событий" <<Отчеты>>
{
..Реквизиты..
ПартнерыНеактуальныеРасчеты : Список значений
ЕстьНеактуальныеРасчетыСКлиентами : Булево
ЕстьНеактуальныеРасчетыСПоставщиками : Булево
..Макеты..
СхемаОтборы : СхемаКомпоновкиДанных
ВыводДанных : ТабличныйДокумент
}
@enduml
