@startuml КонтактнаяИнформацияСотрудников
'!include templates.wsd
'..\include templates.wsd
class Отчет.КонтактнаяИнформацияСотрудников as "Контактная информация сотрудников" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
