@startuml РегламентированныйОтчетСтатистикаФорма1ТОРГ
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма1ТОРГ as "Форма 1-ТОРГ "Сведения о продаже товаров организациями оптовой и розничной торговли"" <<Отчеты>>
{
..Макеты..
Списки2013Кв1 : ТабличныйДокумент
Списки2014Кв1 : ТабличныйДокумент
Списки2017Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2013Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2014Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2014Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
ФормаОтчета2013Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2014Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2017Кв1_ФормаОтчета : ТабличныйДокумент
ШаблонРосстата2014Кв1 : ДвоичныеДанные
ШаблонРосстата2017Кв1 : ДвоичныеДанные
НастройкиЗагрузкиXML2014Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
}
@enduml
