@startuml КонтрольОформленияТоваровВПутиИНеотфактурованныхПоставок
'!include templates.wsd
'..\include templates.wsd
class Отчет.КонтрольОформленияТоваровВПутиИНеотфактурованныхПоставок as "Контроль оформления товаров в пути и неотфактурованных поставок" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
