@startuml РегламентированныйОтчетРасчетЧистыхАктивов
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетРасчетЧистыхАктивов as "Расчет чистых активов акционерного общества" <<Отчеты>>
{
..Макеты..
СоставПоказателей2011Кв1 : ТабличныйДокумент
ФормаОтчета2011Кв1_ФормаОтчета : ТабличныйДокумент
}
@enduml
