@startuml ФинансовоеСостояние
'!include templates.wsd
'..\include templates.wsd
class Отчет.ФинансовоеСостояние as "Финансовое состояние" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
