@startuml ПоступленияБезДокументовГИСМ
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПоступленияБезДокументовГИСМ as "Поступления без документов ГИСМ" <<Отчеты>>
{
..Реквизиты..
ПоступленияЗаказанныхКиЗ : Булево
ПоступленияМаркированныхТоваров : Булево
ОтборОрганизация : Справочник.Организация
ОтборКонтрагент : Справочник.Контрагент
..Макеты..
Макет : ТабличныйДокумент
}
@enduml
