@startuml ОстаткиТоваровПринятыхНаКомиссию
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОстаткиТоваровПринятыхНаКомиссию as "Остатки товаров, принятых на комиссию" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
