@startuml ШтатноеРасписаниеНачисления
'!include templates.wsd
'..\include templates.wsd
class Отчет.ШтатноеРасписаниеНачисления as "Штатное расписание начисления" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
ПФ_MXL_Т3 : ТабличныйДокумент
}
@enduml
