@startuml РегламентированныйОтчетСтатистикаФорма2ДМприл
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма2ДМприл as "Приложение к форме 2-ДМ "Сведения об остатках, поступлении и сдаче драгоценных металлов в виде лома и отходов для последующей переработки и аффинажа"" <<Отчеты>>
{
..Макеты..
ФормаОтчета2012Кв1_ФормаОтчета : ТабличныйДокумент
СоставПоказателей2012Кв1 : ТабличныйДокумент
}
@enduml
