@startuml Расшифровка4ФСС
'!include templates.wsd
'..\include templates.wsd
class Отчет.Расшифровка4ФСС as "Расшифровка 4-ФСС" <<Отчеты>>
{
..Макеты..
Доходы2013 : СхемаКомпоновкиДанных
ДоходыИнвалидов2013 : СхемаКомпоновкиДанных
ПособияПоНетрудоспособности2013 : СхемаКомпоновкиДанных
ПособияПоУходу2013 : СхемаКомпоновкиДанных
ПособияПоНетрудоспособностиСверхНорм2013 : СхемаКомпоновкиДанных
ПособияПоУходуСверхНорм2013 : СхемаКомпоновкиДанных
Доходы2015 : СхемаКомпоновкиДанных
ПособияПоНетрудоспособности2015 : СхемаКомпоновкиДанных
ПособияПоУходу2015 : СхемаКомпоновкиДанных
ПособияПоНетрудоспособностиСверхНорм2015 : СхемаКомпоновкиДанных
Доходы2016 : СхемаКомпоновкиДанных
ПособияПоНетрудоспособностиСверхНорм2016 : СхемаКомпоновкиДанных
Доходы2017 : СхемаКомпоновкиДанных
ПособияПоНетрудоспособности2017 : СхемаКомпоновкиДанных
}
@enduml
