@startuml РегламентированныйОтчетСтатистикаФорма1П
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма1П as "Форма 1-предприятие "Основные сведения о деятельности предприятия"" <<Отчеты>>
{
..Макеты..
Списки2014Кв1 : ТабличныйДокумент
Списки2015Кв1 : ТабличныйДокумент
Списки2016Кв1 : ТабличныйДокумент
Списки2017Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2013Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2014Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2014Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2015Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2016Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1 : ТабличныйДокумент
ФормаОтчета2011Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2011Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2011Кв1_Раздел2_3 : ТабличныйДокумент
ФормаОтчета2011Кв1_Раздел4_6 : ТабличныйДокумент
ФормаОтчета2011Кв1_Раздел7 : ТабличныйДокумент
ФормаОтчета2011Кв1_Раздел8 : ТабличныйДокумент
ФормаОтчета2011Кв1_Раздел9 : ТабличныйДокумент
ФормаОтчета2011Кв1_Раздел10 : ТабличныйДокумент
ФормаОтчета2011Кв1_Подписи : ТабличныйДокумент
ФормаОтчета2012Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел2_3 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел4_6 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел7 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел8 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел9 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел10 : ТабличныйДокумент
ФормаОтчета2012Кв1_Подписи : ТабличныйДокумент
ФормаОтчета2013Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2013Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2013Кв1_Раздел2_3 : ТабличныйДокумент
ФормаОтчета2013Кв1_Раздел4_6 : ТабличныйДокумент
ФормаОтчета2013Кв1_Раздел7 : ТабличныйДокумент
ФормаОтчета2013Кв1_Раздел8 : ТабличныйДокумент
ФормаОтчета2013Кв1_Раздел9 : ТабличныйДокумент
ФормаОтчета2013Кв1_Раздел10 : ТабличныйДокумент
ФормаОтчета2013Кв1_Подписи : ТабличныйДокумент
ФормаОтчета2014Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел2_3 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел4_6 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел7 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел8 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел9 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел10 : ТабличныйДокумент
ФормаОтчета2014Кв1_Подписи : ТабличныйДокумент
ФормаОтчета2015Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел2_3 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел4_6 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел7 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел8 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел9 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел10 : ТабличныйДокумент
ФормаОтчета2015Кв1_Подписи : ТабличныйДокумент
ФормаОтчета2016Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел2_3 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел4_6 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел7 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел8 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел9 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел10 : ТабличныйДокумент
ФормаОтчета2016Кв1_Подписи : ТабличныйДокумент
ФормаОтчета2016Кв1_ПриложенияДляВыгрузки : ТабличныйДокумент
ФормаОтчета2017Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел2_3 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел4_6 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел7 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел8 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел9 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел10 : ТабличныйДокумент
ФормаОтчета2017Кв1_Подписи : ТабличныйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
СоставПоказателей2017Кв1 : ТабличныйДокумент
ШаблонРосстата2016Кв1 : ДвоичныеДанные
ШаблонРосстата2017Кв1 : ДвоичныеДанные
НастройкиЗагрузкиXML2015Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
}
@enduml
