@startuml ПроверкаСвязейПоказателейБюджетов
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПроверкаСвязейПоказателейБюджетов as "Проверка связей показателей бюджетов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
