@startuml СправкаРасчетРезервыПоСомнительнымДолгам
'!include templates.wsd
'..\include templates.wsd
class Отчет.СправкаРасчетРезервыПоСомнительнымДолгам as "Справка-расчет "Резервы по сомнительным долгам"" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
ПоказательБУ : Булево
ПоказательНУ : Булево
ПоказательПР : Булево
ПоказательВР : Булево
РежимРасшифровки : Булево
НаборПоказателейОтчета : Число 1, 0
ВключатьОбособленныеПодразделения : Булево
СНачалаГода : Булево
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
СхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
