@startuml НастройкиПрограммыЗарплатаКадры
'!include templates.wsd
'..\include templates.wsd
class Отчет.НастройкиПрограммыЗарплатаКадры as "Настройки расчета зарплаты и кадрового учета" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
