@startuml ОценкаПроизводительности
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОценкаПроизводительности as "Оценка производительности" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
