@startuml АнализУплатыНДФЛ
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализУплатыНДФЛ as "Анализ уплаты НДФЛ" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
