@startuml РегламентированныйОтчетРасчетЭкологическийСбор
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетРасчетЭкологическийСбор as "Расчет суммы экологического сбора" <<Отчеты>>
{
..Макеты..
Списки2016Кв1 : ТабличныйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2016Кв1 : ТабличныйДокумент
ФормаОтчета2016Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2016Кв1_Товары : ТабличныйДокумент
ФормаОтчета2016Кв1_Упаковка : ТабличныйДокумент
ФормаОтчета2016Кв1_Итоги : ТабличныйДокумент
ФормаОтчета2016Кв1_ПФ : ТабличныйДокумент
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
}
@enduml
