@startuml ДиагностикаЭтапаПроизводства
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДиагностикаЭтапаПроизводства as "Диагностика этапа производства" <<Отчеты>>
{
..Макеты..
ДиагностикаЭтапа : ТабличныйДокумент
}
@enduml
