@startuml РегламентированноеУведомлениеФормаР13001
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеФормаР13001 as "Заявление о регистрации изменений в документах юридического лица" <<Отчеты>>
{
..Макеты..
СпискиВыбора2014_1 : ТабличныйДокумент
Форматы2014_1 : ТабличныйДокумент
СхемаВыгрузкиФорма2014_1 : ТабличныйДокумент
TIFF_2014_1 : ДвоичныеДанные
Форма2014_1_Страница1 : ТабличныйДокумент
Форма2014_1_СтраницаА : ТабличныйДокумент
Форма2014_1_СтраницаБ : ТабличныйДокумент
Форма2014_1_СтраницаВ : ТабличныйДокумент
Форма2014_1_СтраницаГ : ТабличныйДокумент
Форма2014_1_СтраницаД : ТабличныйДокумент
Форма2014_1_СтраницаЕ : ТабличныйДокумент
Форма2014_1_СтраницаЖ1 : ТабличныйДокумент
Форма2014_1_СтраницаЖ2_4 : ТабличныйДокумент
Форма2014_1_СтраницаЗ : ТабличныйДокумент
Форма2014_1_СтраницаИ : ТабличныйДокумент
Форма2014_1_СтраницаК : ТабличныйДокумент
Форма2014_1_СтраницаЛ1 : ТабличныйДокумент
Форма2014_1_СтраницаЛ2 : ТабличныйДокумент
Форма2014_1_СтраницаМ : ТабличныйДокумент
Печать_Форма2014_1_Страница1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаА : ТабличныйДокумент
Печать_Форма2014_1_СтраницаБ : ТабличныйДокумент
Печать_Форма2014_1_СтраницаВ : ТабличныйДокумент
Печать_Форма2014_1_СтраницаГ : ТабличныйДокумент
Печать_Форма2014_1_СтраницаД1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаД2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЕ1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЕ2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЖ1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЖ2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЖ3 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЖ4 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЗ1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЗ2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаИ : ТабличныйДокумент
Печать_Форма2014_1_СтраницаК1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаК2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЛ1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЛ2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаМ1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаМ2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаМ3 : ТабличныйДокумент
}
@enduml
