@startuml АнализФинансовыхРезультатов
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализФинансовыхРезультатов as "Финансовые результаты" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
