@startuml КарточкаОСМеждународныйУчет
'!include templates.wsd
'..\include templates.wsd
class Отчет.КарточкаОСМеждународныйУчет as "Карточка ОС (Международный учет)" <<Отчеты>>
{
..Макеты..
Макет : ТабличныйДокумент
}
@enduml
