@startuml СогласияНаОбработкуПерсональныхДанныхИстекающие
'!include templates.wsd
'..\include templates.wsd
class Отчет.СогласияНаОбработкуПерсональныхДанныхИстекающие as "Согласия на обработку персональных данных истекающие" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
