@startuml ДатыЗапретаИзменения
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДатыЗапретаИзменения as "Даты запрета изменения" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
