@startuml ОстаткиАлкогольнойПродукцииЕГАИС
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОстаткиАлкогольнойПродукцииЕГАИС as "Остатки алкогольной продукции" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
