@startuml ТоварыКОтгрузке
'!include templates.wsd
'..\include templates.wsd
class Отчет.ТоварыКОтгрузке as "Выполнение сборки и отгрузки товаров" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
