@startuml КартаПродаж
'!include templates.wsd
'..\include templates.wsd
class Отчет.КартаПродаж as "Карта продаж" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
