@startuml РезультатыСогласованияЗаявкиНаВозвратТоваровОтКлиента
'!include templates.wsd
'..\include templates.wsd
class Отчет.РезультатыСогласованияЗаявкиНаВозвратТоваровОтКлиента as "Результаты согласования заявки на возврат товаров от клиента" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
