@startuml РегламентированныйОтчетСтатистикаФорма1РП
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма1РП as "Форма 1-РП (срочная) "Сведения о состоянии расчетов за отгруженную продукцию, выполненные работы (услуги)"" <<Отчеты>>
{
..Макеты..
СхемаВыгрузкиXML2012Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2012Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2015Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1_год : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1_квартал : ТабличныйДокумент
ФормаОтчета2010Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2012Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2013Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2014Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2015Кв1_ФормаОтчета : ТабличныйДокумент
СоставПоказателей2013Кв1 : ТабличныйДокумент
СоставПоказателей2014Кв1 : ТабличныйДокумент
СоставПоказателей2015Кв1 : ТабличныйДокумент
ШаблонРосстата2015Кв1_год : ДвоичныеДанные
ШаблонРосстата2015Кв1_квартал : ДвоичныеДанные
НастройкиЗагрузкиXML2014Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2015Кв1 : ТекстовыйДокумент
}
@enduml
