@startuml ПередачаМатериаловПоЗаказу
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПередачаМатериаловПоЗаказу as "Передача материалов по заказу" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
