@startuml КнигаПокупок
'!include templates.wsd
'..\include templates.wsd
class Отчет.КнигаПокупок as "Книга покупок" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
ФормироватьДополнительныеЛисты : Булево
ДополнительныеЛистыЗаТекущийПериод : Булево
ГруппироватьПоКонтрагентам : Булево
КонтрагентДляОтбора : Справочник.Организация\rСправочник.Контрагент
ВыводитьТолькоДопЛисты : Булево
ВключатьОбособленныеПодразделения : Булево
ВыводитьПокупателейПоАвансам : Булево
}
@enduml
