@startuml АнализПричинОтменыЗаказовПоставщикамПоДокументу
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализПричинОтменыЗаказовПоставщикамПоДокументу as "Анализ причин отмены заказов поставщикам по документу" <<Отчеты>>
{
..Макеты..
АнализПричиныОтмены : ТабличныйДокумент
}
@enduml
