@startuml РасшифровкаСостоянияВыполненияЗаказовПереработчикам
'!include templates.wsd
'..\include templates.wsd
class Отчет.РасшифровкаСостоянияВыполненияЗаказовПереработчикам as "Расшифровка состояния выполнения заказов переработчикам" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
