@startuml РеестрТорговыхДокументов
'!include templates.wsd
'..\include templates.wsd
class Отчет.РеестрТорговыхДокументов as "Реестр торговых документов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
