@startuml ХодРемонтныхМероприятий
'!include templates.wsd
'..\include templates.wsd
class Отчет.ХодРемонтныхМероприятий as "Ход ремонтных мероприятий" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
