@startuml АнализСебестоимостиВыпущеннойПродукции
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализСебестоимостиВыпущеннойПродукции as "Анализ себестоимости выпущенной продукции" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
