@startuml УнифицированнаяФормаТ2
'!include templates.wsd
'..\include templates.wsd
class Отчет.УнифицированнаяФормаТ2 as "Унифицированная форма Т-2" <<Отчеты>>
{
..Макеты..
УнифицированнаяФормаТ2Базовая : СхемаКомпоновкиДанных
ПФ_MXL_Т2 : ТабличныйДокумент
УнифицированнаяФормаТ2Расширенная : СхемаКомпоновкиДанных
}
@enduml
