@startuml РегламентированныйОтчетАлкоПриложение5
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетАлкоПриложение5 as "Декларация об объеме оборота этилового спирта, алкогольной и спиртосодержащей продукции" <<Отчеты>>
{
..Макеты..
ПечатнаяФормаОтчета2009Кв4_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2009Кв4_ФизЛица : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Декларация : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Декларация_20140101 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Лицензии : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Титульный_20140101 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Декларация : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Лицензии : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Титульный : ТабличныйДокумент
СоставПоказателей2006Кв3 : ТабличныйДокумент
СоставПоказателей2012Кв3 : ТабличныйДокумент
СоставПоказателей2014Кв1 : ТабличныйДокумент
Списки2006Кв1 : ТабличныйДокумент
Списки2012Кв3 : ТабличныйДокумент
Списки2012Кв3_20120726 : ТабличныйДокумент
Списки2012Кв3_20131101 : ТабличныйДокумент
Списки2014Кв1 : ТабличныйДокумент
Списки2015Кв3 : ТабличныйДокумент
СхемаВыгрузки401 : ТабличныйДокумент
СхемаВыгрузки420 : ТабличныйДокумент
СхемаВыгрузки430 : ТабличныйДокумент
СхемаВыгрузки430_2014Кв1 : ТабличныйДокумент
ФормаОтчета2009Кв4_Декларация : ТабличныйДокумент
ФормаОтчета2009Кв4_Титульный : ТабличныйДокумент
ФормаОтчета2009Кв4_ФизЛица : ТабличныйДокумент
ФормаОтчета2012Кв3_Декларация : ТабличныйДокумент
ФормаОтчета2012Кв3_Декларация_20140101 : ТабличныйДокумент
ФормаОтчета2012Кв3_Лицензии : ТабличныйДокумент
ФормаОтчета2012Кв3_Титульный : ТабличныйДокумент
ФормаОтчета2012Кв3_Титульный_20140101 : ТабличныйДокумент
ФормаОтчета2014Кв1_Декларация : ТабличныйДокумент
ФормаОтчета2014Кв1_Лицензии : ТабличныйДокумент
ФормаОтчета2014Кв1_Титульный : ТабличныйДокумент
СхемаВыгрузки431 : ТабличныйДокумент
НастройкиЗагрузкиXML2014Кв1 : ТекстовыйДокумент
}
@enduml
