@startuml ЗагрузкаРабочихЦентров
'!include templates.wsd
'..\include templates.wsd
class Отчет.ЗагрузкаРабочихЦентров as "Загрузка рабочих центров" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
