@startuml РегламентированныйОтчетСтатистикаФормаП2к
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФормаП2к as "Форма П-2 (краткая) "Сведения об инвестициях в основной капитал"" <<Отчеты>>
{
..Макеты..
СхемаВыгрузкиXML2012Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2012Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2015Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1 : ТабличныйДокумент
ФормаОтчета2011Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2012Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2014Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2015Кв1_ФормаОтчета : ТабличныйДокумент
СхемаВыгрузкиXML2014Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2014Кв1 : ТабличныйДокумент
СоставПоказателей2012Кв1 : ТабличныйДокумент
СоставПоказателей2014Кв1 : ТабличныйДокумент
СоставПоказателей2015Кв1 : ТабличныйДокумент
НастройкиЗагрузкиXML2014Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2015Кв1 : ТекстовыйДокумент
}
@enduml
