@startuml СправкаРасчетЗемельногоНалога
'!include templates.wsd
'..\include templates.wsd
class Отчет.СправкаРасчетЗемельногоНалога as "Расчет земельного налога (авансового платежа по налогу)" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
РежимРасшифровки : Булево
ВключатьОбособленныеПодразделения : Булево
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
