@startuml ИсполнительныеДокументы
'!include templates.wsd
'..\include templates.wsd
class Отчет.ИсполнительныеДокументы as "Исполнительные документы" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
