@startuml РегламентированныйОтчетСтатистикаФорма3СБвывоз
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма3СБвывоз as "Форма 3-СБ (вывоз) "Сведения о вывозе потребительских товаров"" <<Отчеты>>
{
..Макеты..
СхемаВыгрузкиXML2013Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2013Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2015Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1 : ТабличныйДокумент
Списки2013Кв1 : ТабличныйДокумент
Списки2015Кв1 : ТабличныйДокумент
ФормаОтчета2013Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2013Кв1_РазделВывозимыеТовары : ТабличныйДокумент
ФормаОтчета2013Кв1_Подписи : ТабличныйДокумент
ФормаОтчета2015Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2015Кв1_РазделВывозимыеТовары : ТабличныйДокумент
ФормаОтчета2015Кв1_Подписи : ТабличныйДокумент
ШаблонРосстата2015Кв1 : ДвоичныеДанные
НастройкиЗагрузкиXML2015Кв1 : ТекстовыйДокумент
}
@enduml
