@startuml ТоварыПринятыеНаКомиссию
'!include templates.wsd
'..\include templates.wsd
class Отчет.ТоварыПринятыеНаКомиссию as "Товары, принятые на комиссию" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
