@startuml РегламентированныйОтчетСтатистикаФормаМПмсх
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФормаМПмсх as "Форма МП(микро)-сх "Сведения об основных показателях деятельности микропредприятия, осуществляющего сельскохозяйственную деятельность"" <<Отчеты>>
{
..Макеты..
Список2013Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2013Кв1 : ТабличныйДокумент
ФормаОтчета2013Кв1_МПм : ТабличныйДокумент
ФормаОтчета2013Кв1_Приложение3 : ТабличныйДокумент
НастройкиЗагрузкиXML2013Кв1 : ТекстовыйДокумент
}
@enduml
