@startuml РегламентированныйОтчетВода
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетВода as "Декларация по водному налогу" <<Отчеты>>
{
..Макеты..
МБ_1151072_3_00002_04_tif : ДвоичныеДанные
МБ_1151072_3_00003_05_tif : ДвоичныеДанные
МБ_1151072_5_01000_01_tif : ДвоичныеДанные
ПечатнаяФормаОтчета2007Кв1_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел2 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел22 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел23 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел24 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_ФизЛица : ТабличныйДокумент
ПечатнаяФормаОтчета2016Кв1_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2016Кв1_Раздел2 : ТабличныйДокумент
ПечатнаяФормаОтчета2016Кв1_Раздел22 : ТабличныйДокумент
ПечатнаяФормаОтчета2016Кв1_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2016Кв1_ФизЛицо : ТабличныйДокумент
СоставПоказателей2007Кв1 : ТабличныйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
Списки2007Кв1 : ТабличныйДокумент
СпискиВыбора2016Кв1 : ТабличныйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел22 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел23 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел24 : ТабличныйДокумент
ФормаОтчета2007Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2007Кв1_ФизЛица : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел21 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел22 : ТабличныйДокумент
ФормаОтчета2016Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2016Кв1_ФизЛицо : ТабличныйДокумент
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
}
@enduml
