@startuml КонтрольПоставкиСырьяИМатериаловДавальцем
'!include templates.wsd
'..\include templates.wsd
class Отчет.КонтрольПоставкиСырьяИМатериаловДавальцем as "Контроль поставки сырья и материалов давальцем" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
