@startuml РегламентированныйОтчетРСВ2
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетРСВ2 as "Расчет по страховым взносам в ПФР, ФФОМС, ТФОМС для ИП (форма РСВ-2 ПФР)" <<Отчеты>>
{
..Макеты..
ПечатнаяФормаОтчета2010Кв1_Раздел12 : ТабличныйДокумент
ПечатнаяФормаОтчета2010Кв1_Раздел22 : ТабличныйДокумент
ПечатнаяФормаОтчета2010Кв1_Раздел30 : ТабличныйДокумент
ПечатнаяФормаОтчета2010Кв1_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв4_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв4_Раздел2 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв4_Раздел3 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв4_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв4_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв4_Раздел2 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв4_Раздел3 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв4_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2015Кв4_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2015Кв4_Раздел2 : ТабличныйДокумент
ПечатнаяФормаОтчета2015Кв4_Раздел3 : ТабличныйДокумент
ПечатнаяФормаОтчета2015Кв4_Титульный : ТабличныйДокумент
СоставПоказателей2010Кв1 : ТабличныйДокумент
СоставПоказателей2012Кв4 : ТабличныйДокумент
СоставПоказателей2014Кв4 : ТабличныйДокумент
СоставПоказателей2015Кв4 : ТабличныйДокумент
Списки2010Кв1 : ТабличныйДокумент
Списки2012Кв4 : ТабличныйДокумент
Списки2014Кв4 : ТабличныйДокумент
СпискиВыбора2015Кв4 : ТабличныйДокумент
СхемаВыгрузки700 : ТабличныйДокумент
СхемаВыгрузки700_2013 : ТабличныйДокумент
СхемаВыгрузки700_2014 : ТабличныйДокумент
СхемаВыгрузкиПФР_2015Кв4 : ТабличныйДокумент
ФормаОтчета2010Кв1_Раздел12 : ТабличныйДокумент
ФормаОтчета2010Кв1_Раздел22 : ТабличныйДокумент
ФормаОтчета2010Кв1_Раздел30 : ТабличныйДокумент
ФормаОтчета2010Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2012Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2012Кв4_Раздел2 : ТабличныйДокумент
ФормаОтчета2012Кв4_Раздел3 : ТабличныйДокумент
ФормаОтчета2012Кв4_Титульный : ТабличныйДокумент
ФормаОтчета2014Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2014Кв4_Раздел2 : ТабличныйДокумент
ФормаОтчета2014Кв4_Раздел3 : ТабличныйДокумент
ФормаОтчета2014Кв4_Титульный : ТабличныйДокумент
ФормаОтчета2015Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2015Кв4_Раздел2 : ТабличныйДокумент
ФормаОтчета2015Кв4_Раздел3 : ТабличныйДокумент
ФормаОтчета2015Кв4_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2015Кв4 : ТекстовыйДокумент
}
@enduml
