@startuml АнализВзносовВФонды
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализВзносовВФонды as "Анализ взносов в фонды" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
