@startuml ГрафикПроизводстваПродукции2_2
'!include templates.wsd
'..\include templates.wsd
class Отчет.ГрафикПроизводстваПродукции2_2 as "График производства продукции (2.2)" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
