@startuml РегламентированноеУведомлениеУчастникаСколковоОсвобождениеНалогообложения
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеУчастникаСколковоОсвобождениеНалогообложения as "Уведомлени участника Сколково об освобождении от исполнения обязанностей налогоплательщика" <<Отчеты>>
{
..Макеты..
Печать_Форма2017_1_Титульная : ТабличныйДокумент
СхемаВыгрузкиФорма2017_1 : ТабличныйДокумент
TIFF_2017_1 : ДвоичныеДанные
СпискиВыбора2017_1 : ТабличныйДокумент
Титульная : ТабличныйДокумент
}
@enduml
