@startuml РегламентированныйОтчетСоответствиеУсловийТруда
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСоответствиеУсловийТруда as "Декларация соответствия условий труда государственным нормативным требованиям охраны труда" <<Отчеты>>
{
..Макеты..
ФормаОтчета2014Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2017Кв1_ФормаОтчета : ТабличныйДокумент
}
@enduml
