@startuml РегламентированноеУведомлениеРеорганизацияЛиквидация
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеРеорганизацияЛиквидация as "Регламентированное уведомление о реорганизации или ликвидации организации" <<Отчеты>>
{
..Макеты..
Форма2014_1 : ТабличныйДокумент
ПараметрыФорма2014_1 : ТабличныйДокумент
СхемаВыгрузкиФорма2014_1 : ТабличныйДокумент
Печать_MXL_Форма2014_1 : ТабличныйДокумент
TIFF_2014_1 : ДвоичныеДанные
}
@enduml
