@startuml ОборотыМеждуСубконто
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОборотыМеждуСубконто as "Обороты между субконто" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
ВключатьОбособленныеПодразделения : Булево
СписокВидовСубконто : Список значений
СписокВидовКорСубконто : Список значений
РазмещениеДополнительныхПолей : Число 1, 0
РежимРасшифровки : Булево
ПоказательБУ : Булево
ПоказательНУ : Булево
ПоказательПР : Булево
ПоказательВР : Булево
ПоказательКоличество : Булево
ПоказательВалютнаяСумма : Булево
ПоказательУУ : Булево
ПоказательФО : Булево
ПоказательРазницаБУиУУ : Булево
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
СхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
