@startuml ВедомостьПоПереданнойВозвратнойТаре
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВедомостьПоПереданнойВозвратнойТаре as "Ведомость по переданной возвратной таре" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
