@startuml ШахматнаяВедомостьМеждународный
'!include templates.wsd
'..\include templates.wsd
class Отчет.ШахматнаяВедомостьМеждународный as "Шахматная ведомость (международный учет)" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
Подразделение : Справочник.Подразделение
ВключатьОбособленныеПодразделения : Булево
ПоказательБУ : Булево
ПоказательВалютнаяСумма : Булево
РежимРасшифровки : Булево
ПоСубсчетам : Булево
ВыводитьЗабалансовыеСчета : Булево
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
