@startuml МеждународныйОтчет
'!include templates.wsd
'..\include templates.wsd
class Отчет.МеждународныйОтчет as "Международный отчет" <<Отчеты>>
{
..Реквизиты..
КомплектОтчетности : Справочник.Комплект финансовых отчетов
ВидОтчета : Справочник.Вид финансового отчета
НачалоПериода : Дата
КонецПериода : Дата
СуммыВТысячах : Булево
..Макеты..
РасшифровкаПроизводногоПоказателя : ТабличныйДокумент
ОперандыПроизводногоПоказателя : СхемаКомпоновкиДанных
}
@enduml
