@startuml ПринятаяВозвратнаяТара
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПринятаяВозвратнаяТара as "Принятая возвратная тара" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
