@startuml РасшифровкаРасходовНаПроизводство
'!include templates.wsd
'..\include templates.wsd
class Отчет.РасшифровкаРасходовНаПроизводство as "Расшифровка расходов на производство" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
