@startuml ИндексыЦенНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Отчет.ИндексыЦенНоменклатуры as "Индексы цен номенклатуры" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
