@startuml ПлановаяСебестоимостьПродукции
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПлановаяСебестоимостьПродукции as "Плановая себестоимость продукции" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
