@startuml СостояниеВыполненияДокументов
'!include templates.wsd
'..\include templates.wsd
class Отчет.СостояниеВыполненияДокументов as "Состояние выполнения документов" <<Отчеты>>
{
..Макеты..
Макет : ТабличныйДокумент
}
@enduml
