@startuml РезультатыТестирования
'!include templates.wsd
'..\include templates.wsd
class Отчет.РезультатыТестирования as "Результаты тестирования" <<Отчеты>>
{
..Реквизиты..
ПутьКФайлу : Строка
АдресХранилища : Строка
..Макеты..
Макет : СхемаКомпоновкиДанных
}
@enduml
