@startuml ПроверкаЦелостностиТома
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПроверкаЦелостностиТома as "Проверка целостности тома" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
