@startuml ВедомостьПоТоварамНаСкладахВЦенахНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВедомостьПоТоварамНаСкладахВЦенахНоменклатуры as "Ведомость по товарам в ценах номенклатуры" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
