@startuml ОтклоненияСуммыВзаиморасчетовПоПоставщикам
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОтклоненияСуммыВзаиморасчетовПоПоставщикам as "Отклонения суммы взаиморасчетов по поставщикам" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
