@startuml Договорники
'!include templates.wsd
'..\include templates.wsd
class Отчет.Договорники as "Договорники" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
