@startuml РегламентированныйОтчетНДПИ
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетНДПИ as "Декларация по налогу на добычу полезных ископаемых" <<Отчеты>>
{
..Макеты..
МБ_1151054_3_00004_04_tif : ДвоичныеДанные
МБ_1151054_5_01000_05_tif : ДвоичныеДанные
МБ_1151054_5_02000_06_tif : ДвоичныеДанные
МБ_1151054_5_03000_07_tif : ДвоичныеДанные
МБ_1151054_5_04000_08_tif : ДвоичныеДанные
МЧБ_2011кв2_01_Титул : ТабличныйДокумент
МЧБ_2011кв2_02_Раздел1 : ТабличныйДокумент
МЧБ_2011кв2_03_Раздел2 : ТабличныйДокумент
МЧБ_2011кв2_04_Раздел3 : ТабличныйДокумент
МЧБ_2011кв2_05_Раздел41 : ТабличныйДокумент
МЧБ_2011кв2_06_Раздел42 : ТабличныйДокумент
МЧБ_2011кв2_07_Раздел43 : ТабличныйДокумент
МЧБ_2012Кв1_1_Титульный : ТабличныйДокумент
МЧБ_2012Кв1_2_Раздел1 : ТабличныйДокумент
МЧБ_2012Кв1_3_Раздел2 : ТабличныйДокумент
МЧБ_2012Кв1_4_Раздел3 : ТабличныйДокумент
МЧБ_2012Кв1_5_Раздел4_1 : ТабличныйДокумент
МЧБ_2012Кв1_6_Раздел4_2 : ТабличныйДокумент
МЧБ_2012Кв1_7_Раздел4_3 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Раздел1 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Раздел2 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Раздел3 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Раздел41 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Раздел42 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Раздел43 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Титульный : ТабличныйДокумент
ПечатныйБланк2015Кв2_Раздел1 : ТабличныйДокумент
ПечатныйБланк2015Кв2_Раздел2 : ТабличныйДокумент
ПечатныйБланк2015Кв2_Раздел211 : ТабличныйДокумент
ПечатныйБланк2015Кв2_Раздел3 : ТабличныйДокумент
ПечатныйБланк2015Кв2_Раздел4 : ТабличныйДокумент
ПечатныйБланк2015Кв2_Раздел5 : ТабличныйДокумент
ПечатныйБланк2015Кв2_Раздел6 : ТабличныйДокумент
ПечатныйБланк2015Кв2_Раздел7 : ТабличныйДокумент
ПечатныйБланк2015Кв2_Раздел72 : ТабличныйДокумент
ПечатныйБланк2015Кв2_Раздел73 : ТабличныйДокумент
ПечатныйБланк2015Кв2_Титульный : ТабличныйДокумент
СоставПоказателей2011Кв2 : ТабличныйДокумент
СоставПоказателей2012Кв1 : ТабличныйДокумент
СоставПоказателей2013Кв4 : ТабличныйДокумент
СоставПоказателей2015Кв2 : ТабличныйДокумент
Списки2011Кв2 : ТабличныйДокумент
Списки2012Кв1 : ТабличныйДокумент
СпискиВыбора2013Кв4 : ТабличныйДокумент
СпискиВыбора2015Кв2 : ТабличныйДокумент
СтруктураXML501 : ТабличныйДокумент
СтруктураXML502 : ТабличныйДокумент
СхемаВыгрузки503 : ТабличныйДокумент
СхемаВыгрузки504 : ТабличныйДокумент
ФормаОтчета2011Кв2_Раздел1 : ТабличныйДокумент
ФормаОтчета2011Кв2_Раздел2 : ТабличныйДокумент
ФормаОтчета2011Кв2_Раздел3 : ТабличныйДокумент
ФормаОтчета2011Кв2_Раздел41 : ТабличныйДокумент
ФормаОтчета2011Кв2_Раздел42 : ТабличныйДокумент
ФормаОтчета2011Кв2_Раздел43 : ТабличныйДокумент
ФормаОтчета2011Кв2_Титульный : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел41 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел42 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел43 : ТабличныйДокумент
ФормаОтчета2012Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел2 : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел3 : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел41 : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел42 : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел43 : ТабличныйДокумент
ФормаОтчета2013Кв4_Титульный : ТабличныйДокумент
ФормаОтчета2015Кв2_Раздел1 : ТабличныйДокумент
ФормаОтчета2015Кв2_Раздел2 : ТабличныйДокумент
ФормаОтчета2015Кв2_Раздел21 : ТабличныйДокумент
ФормаОтчета2015Кв2_Раздел212 : ТабличныйДокумент
ФормаОтчета2015Кв2_Раздел3 : ТабличныйДокумент
ФормаОтчета2015Кв2_Раздел31 : ТабличныйДокумент
ФормаОтчета2015Кв2_Раздел311 : ТабличныйДокумент
ФормаОтчета2015Кв2_Раздел4 : ТабличныйДокумент
ФормаОтчета2015Кв2_Раздел5 : ТабличныйДокумент
ФормаОтчета2015Кв2_Раздел51 : ТабличныйДокумент
ФормаОтчета2015Кв2_Раздел6 : ТабличныйДокумент
ФормаОтчета2015Кв2_Раздел7 : ТабличныйДокумент
ФормаОтчета2015Кв2_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2013Кв4 : ТекстовыйДокумент
НастройкиЗагрузкиXML2015Кв2 : ТекстовыйДокумент
}
@enduml
