@startuml РегламентированныйОтчетБухОтчетностьСОНКО
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетБухОтчетностьСОНКО as "Бухгалтерская отчетность социально ориентированных некоммерческих организаций (до 2015 года)" <<Отчеты>>
{
..Макеты..
МБ_0710097_5_01000_01_tif : ДвоичныеДанные
МБ_0710097_5_02000_02_tif : ДвоичныеДанные
НастройкиЗагрузкиXML2012Кв4 : ТекстовыйДокумент
СоставПоказателей2012Кв4 : ТабличныйДокумент
СпискиВыбора2012Кв4 : ТабличныйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
СхемаВыгрузки502 : ТабличныйДокумент
ФормаОтчета2012Кв4_Баланс : ТабличныйДокумент
ФормаОтчета2012Кв4_Изменения : HTMLДокумент
ФормаОтчета2012Кв4_ОФР : ТабличныйДокумент
ФормаОтчета2012Кв4_ОЦИС : ТабличныйДокумент
ФормаПечати2012Кв1_КНД0710097_1 : ТабличныйДокумент
ФормаПечати2012Кв1_КНД0710097_2 : ТабличныйДокумент
ФормаПечати2013Кв1_КНД0710097_1 : ТабличныйДокумент
ФормаПечати2013Кв1_КНД0710097_2 : ТабличныйДокумент
}
@enduml
