@startuml РегламентированноеУведомлениеФормаР14001
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеФормаР14001 as "Заявление о внесении изменений в реестр" <<Отчеты>>
{
..Макеты..
СпискиВыбора2014_1 : ТабличныйДокумент
Форматы2014_1 : ТабличныйДокумент
СхемаВыгрузкиФорма2014_1 : ТабличныйДокумент
TIFF_2014_1 : ДвоичныеДанные
Форма2014_1_Страница1 : ТабличныйДокумент
Форма2014_1_СтраницаА : ТабличныйДокумент
Форма2014_1_СтраницаБ : ТабличныйДокумент
Форма2014_1_СтраницаВ1 : ТабличныйДокумент
Форма2014_1_СтраницаВ2_4 : ТабличныйДокумент
Форма2014_1_СтраницаГ1_2 : ТабличныйДокумент
Форма2014_1_СтраницаГ3_5 : ТабличныйДокумент
Форма2014_1_СтраницаД : ТабличныйДокумент
Форма2014_1_СтраницаД3_5 : ТабличныйДокумент
Форма2014_1_СтраницаЕ1 : ТабличныйДокумент
Форма2014_1_СтраницаЕ2 : ТабличныйДокумент
Форма2014_1_СтраницаЕ3_4 : ТабличныйДокумент
Форма2014_1_СтраницаЕ5_7 : ТабличныйДокумент
Форма2014_1_СтраницаЖ1_2 : ТабличныйДокумент
Форма2014_1_СтраницаЖ3_5 : ТабличныйДокумент
Форма2014_1_СтраницаЗ : ТабличныйДокумент
Форма2014_1_СтраницаИ : ТабличныйДокумент
Форма2014_1_СтраницаК : ТабличныйДокумент
Форма2014_1_СтраницаЛ : ТабличныйДокумент
Форма2014_1_СтраницаМ : ТабличныйДокумент
Форма2014_1_СтраницаН1 : ТабличныйДокумент
Форма2014_1_СтраницаН2 : ТабличныйДокумент
Форма2014_1_СтраницаО : ТабличныйДокумент
Форма2014_1_СтраницаП : ТабличныйДокумент
Форма2014_1_СтраницаР : ТабличныйДокумент
Печать_Форма2014_1_Страница1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаА : ТабличныйДокумент
Печать_Форма2014_1_СтраницаБ : ТабличныйДокумент
Печать_Форма2014_1_СтраницаВ1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаВ2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаВ3 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаВ4 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаГ1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаГ2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаГ3 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаГ4 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаГ5 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаД1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаД2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаД3 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаД4 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаД5 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаД6 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаД7 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаД8 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаД9 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЕ1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЕ2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЕ3 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЕ4 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЕ5 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЕ6 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЕ7 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЖ1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЖ2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЖ3 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЖ4 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЖ5 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЗ : ТабличныйДокумент
Печать_Форма2014_1_СтраницаИ : ТабличныйДокумент
Печать_Форма2014_1_СтраницаК1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаК2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЛ1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЛ2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЛ3 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаМ1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаМ2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаН1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаН2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаО1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаО2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаП : ТабличныйДокумент
Печать_Форма2014_1_СтраницаР1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаР2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаР3 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаР4 : ТабличныйДокумент
}
@enduml
