@startuml РеестрНормативноСправочнойИнформации
'!include templates.wsd
'..\include templates.wsd
class Отчет.РеестрНормативноСправочнойИнформации as "Реестр нормативно - справочной информации" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
