@startuml РезультатыСогласованияЦенНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Отчет.РезультатыСогласованияЦенНоменклатуры as "Результаты согласования цен номенклатуры" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
