@startuml РегламентированныйОтчетСтраховыеВзносыНСИПЗ
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтраховыеВзносыНСИПЗ as "Отчет об использование сумм страховых взносов от НС и ПЗ" <<Отчеты>>
{
..Макеты..
СоставПоказателей2013Кв1 : ТабличныйДокумент
СоставПоказателей2014Кв1 : ТабличныйДокумент
СоставПоказателей2017Кв1 : ТабличныйДокумент
ФормаОтчета2008Кв4_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2013Кв1_Таблица1 : ТабличныйДокумент
ФормаОтчета2013Кв1_Таблица2 : ТабличныйДокумент
ФормаОтчета2014Кв1_Таблица1 : ТабличныйДокумент
ФормаОтчета2014Кв1_Таблица2 : ТабличныйДокумент
ФормаОтчета2015Кв3_Таблица1 : ТабличныйДокумент
ФормаОтчета2015Кв3_Таблица2 : ТабличныйДокумент
ФормаОтчета2017Кв1_Таблица1 : ТабличныйДокумент
ФормаОтчета2017Кв1_Таблица2 : ТабличныйДокумент
}
@enduml
