@startuml КарточкаПартииПоВидамНалогообложения
'!include templates.wsd
'..\include templates.wsd
class Отчет.КарточкаПартииПоВидамНалогообложения as "Карточка партии по видам налогообложения" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
