@startuml КонтрольНомеровГТДТоваров
'!include templates.wsd
'..\include templates.wsd
class Отчет.КонтрольНомеровГТДТоваров as "Контроль номеров ГТД товаров" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
