@startuml РегламентированныйОтчетСведенияОрублевыхСчетах
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСведенияОрублевыхСчетах as "Сведения о рублевых счетах" <<Отчеты>>
{
..Макеты..
ФормаОтчета2005Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2015Кв1_ФормаОтчета : ТабличныйДокумент
}
@enduml
