@startuml НалогиИВзносыКратко
'!include templates.wsd
'..\include templates.wsd
class Отчет.НалогиИВзносыКратко as "Налоги и взносы (кратко)" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
