@startuml СведенияОКооперации
'!include templates.wsd
'..\include templates.wsd
class Отчет.СведенияОКооперации as "Сведения о кооперации" <<Отчеты>>
{
..Реквизиты..
ДоговорСЗаказчиком : Справочник.Договор между организациями\rСправочник.Договор с контрагентом
..Макеты..
ПФ_Приложение1 : ТабличныйДокумент
ПФ_Приложение2 : ТабличныйДокумент
ПФ_Приложение3 : ТабличныйДокумент
}
@enduml
