@startuml РегламентированныйОтчетСтатистикаФормаТЗВбюджет
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФормаТЗВбюджет as "Форма ТЗВ-бюджет "Сведения о расходах бюджетного, автономного и казенного учереждения"" <<Отчеты>>
{
..Макеты..
Списки2016Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2016Кв1 : ТабличныйДокумент
ФормаОтчета2016Кв1_ФормаОтчета : ТабличныйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
ШаблонРосстата2016Кв1 : ДвоичныеДанные
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
}
@enduml
