@startuml КнигаУчетаДепонентов
'!include templates.wsd
'..\include templates.wsd
class Отчет.КнигаУчетаДепонентов as "Книга учета депонентов" <<Отчеты>>
{
..Макеты..
ПФ_MXL_КнигаУчетаДепонентов : ТабличныйДокумент
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
