@startuml АнализПооперационногоРасписания2_2
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализПооперационногоРасписания2_2 as "Анализ пооперационного расписания (2.2)" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
