@startuml АнализПричинПроигрышаСделок
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализПричинПроигрышаСделок as "Анализ причин проигрыша сделок" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
