@startuml ПрименениеСерииНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПрименениеСерииНоменклатуры as "Применение серии номенклатуры" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
ПФ_MXL_ПрименениеСерииНоменклатуры : ТабличныйДокумент
}
@enduml
