@startuml ЗаполнениеСвойствПартнеров
'!include templates.wsd
'..\include templates.wsd
class Отчет.ЗаполнениеСвойствПартнеров as "Заполнение свойств клиентов, поставщиков" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
