@startuml ДиаграммаСостоянияЭДО
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДиаграммаСостоянияЭДО as "Диаграмма состояния электронного документооборота" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
