@startuml РегламентированныйОтчетАлкоПриложение11
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетАлкоПриложение11 as "Декларация об объеме розничной продажи алкогольной (за исключением пива и пивных напитков) и спиртосодержащей продукции" <<Отчеты>>
{
..Макеты..
ПечатнаяФормаОтчета2012Кв3_Лицензии : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Раздел1_20140101 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Раздел2 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Раздел2_20140101 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Титульный_20140101 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Лицензии : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел2 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Титульный : ТабличныйДокумент
СоставПоказателей2012Кв3 : ТабличныйДокумент
СоставПоказателей2014Кв1 : ТабличныйДокумент
Списки2012Кв3 : ТабличныйДокумент
Списки2012Кв3_20131101 : ТабличныйДокумент
Списки2014Кв1 : ТабличныйДокумент
Списки2015Кв3 : ТабличныйДокумент
СхемаВыгрузки420 : ТабличныйДокумент
СхемаВыгрузки430 : ТабличныйДокумент
СхемаВыгрузки430_2014Кв1 : ТабличныйДокумент
ФормаОтчета2012Кв3_Лицензии : ТабличныйДокумент
ФормаОтчета2012Кв3_Раздел1 : ТабличныйДокумент
ФормаОтчета2012Кв3_Раздел1_20140101 : ТабличныйДокумент
ФормаОтчета2012Кв3_Раздел2 : ТабличныйДокумент
ФормаОтчета2012Кв3_Раздел2_20140101 : ТабличныйДокумент
ФормаОтчета2012Кв3_Титульный : ТабличныйДокумент
ФормаОтчета2012Кв3_Титульный_20140101 : ТабличныйДокумент
ФормаОтчета2014Кв1_Лицензии : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2014Кв1_Титульный : ТабличныйДокумент
СоставПоказателей2015Кв1 : ТабличныйДокумент
СхемаВыгрузки431 : ТабличныйДокумент
НастройкиЗагрузкиXML2014Кв1 : ТекстовыйДокумент
ШаблоныСообщенийОбОшибках2014Кв1 : ТабличныйДокумент
}
@enduml
