@startuml ПоступлениеИОтгрузкаТоваров
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПоступлениеИОтгрузкаТоваров as "Поступление и отгрузка товаров" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
