@startuml РегистрНалоговогоУчетаПоНДФЛ
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегистрНалоговогоУчетаПоНДФЛ as "Регистр налогового учета по НДФЛ" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
ПФ_MXL_ФормаРегистрНалоговогоУчетаПоНДФЛ : ТабличныйДокумент
}
@enduml
