@startuml РегламентированныйОтчетСтатистикаФормаС2
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФормаС2 as "Форма С-2 "Сведения о ходе строительства строек и объектов, включенных в федеральную адресную инвестиционную программу"" <<Отчеты>>
{
..Макеты..
Списки2012Кв1 : ТабличныйДокумент
Списки2017Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2012Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2012Кв1_месяц : ТабличныйДокумент
АтрибВыгрузкиXML2012Кв1_год : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1_месяц : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1_год : ТабличныйДокумент
ФормаОтчета2012Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2017Кв1_ФормаОтчета : ТабличныйДокумент
НастройкиЗагрузкиXML2012Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
}
@enduml
