@startuml СостояниеОбъектовЭксплуатации
'!include templates.wsd
'..\include templates.wsd
class Отчет.СостояниеОбъектовЭксплуатации as "Состояние объектов эксплуатации" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
