@startuml РегламентированныйОтчетРВ3
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетРВ3 as "Расчет по страховым взносам в ПФР для летчиков (форма РВ-3 ПФР)" <<Отчеты>>
{
..Макеты..
ПечатнаяФормаОтчета2010Кв1_Раздел12 : ТабличныйДокумент
ПечатнаяФормаОтчета2010Кв1_Раздел30 : ТабличныйДокумент
ПечатнаяФормаОтчета2010Кв1_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2011Кв4_Раздел12 : ТабличныйДокумент
ПечатнаяФормаОтчета2011Кв4_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2015Кв3_Раздел12 : ТабличныйДокумент
ПечатнаяФормаОтчета2015Кв3_Раздел3 : ТабличныйДокумент
ПечатнаяФормаОтчета2015Кв3_Титульный : ТабличныйДокумент
СоставПоказателей2010Кв1 : ТабличныйДокумент
СоставПоказателей2011Кв4 : ТабличныйДокумент
СоставПоказателей2015Кв3 : ТабличныйДокумент
Списки2010Кв1 : ТабличныйДокумент
СпискиВыбора2015Кв3 : ТабличныйДокумент
СхемаВыгрузки700 : ТабличныйДокумент
СхемаВыгрузки700_2011Кв4 : ТабличныйДокумент
СхемаВыгрузкиПФР_2015Кв3 : ТабличныйДокумент
ФормаОтчета2010Кв1_Раздел12 : ТабличныйДокумент
ФормаОтчета2010Кв1_Раздел30 : ТабличныйДокумент
ФормаОтчета2010Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2011Кв4_Раздел12 : ТабличныйДокумент
ФормаОтчета2011Кв4_Титульный : ТабличныйДокумент
ФормаОтчета2015Кв3_Раздел12 : ТабличныйДокумент
ФормаОтчета2015Кв3_Раздел3 : ТабличныйДокумент
ФормаОтчета2015Кв3_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2015Кв3 : ТекстовыйДокумент
}
@enduml
