@startuml РасшифровкаРСВ
'!include templates.wsd
'..\include templates.wsd
class Отчет.РасшифровкаРСВ as "Расшифровка РСВ" <<Отчеты>>
{
..Макеты..
Подразделы12Доходы2017 : СхемаКомпоновкиДанных
Подразделы12Взносы2017 : СхемаКомпоновкиДанных
Подраздел31Доходы2017 : СхемаКомпоновкиДанных
Подраздел31Взносы2017 : СхемаКомпоновкиДанных
Подраздел32Доходы2017 : СхемаКомпоновкиДанных
Подраздел32Взносы2017 : СхемаКомпоновкиДанных
Подраздел4Доходы2017 : СхемаКомпоновкиДанных
Подраздел4Взносы2017 : СхемаКомпоновкиДанных
ДоходыФСС2017 : СхемаКомпоновкиДанных
ПособияПоНетрудоспособности2017 : СхемаКомпоновкиДанных
ПособияПоУходу2017 : СхемаКомпоновкиДанных
ПособияПоНетрудоспособностиСверхНорм2017 : СхемаКомпоновкиДанных
ПособияПоУходуСверхНорм2017 : СхемаКомпоновкиДанных
}
@enduml
