@startuml РегламентированныйОтчетСтатистикаФормаПУслуги
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФормаПУслуги as "Форма П(услуги) "Сведения об объеме платных услуг населению по видам"" <<Отчеты>>
{
..Макеты..
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2018Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1_месяц : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1_квартал : ТабличныйДокумент
АтрибВыгрузкиXML2018Кв1_месяц : ТабличныйДокумент
АтрибВыгрузкиXML2018Кв1_квартал : ТабличныйДокумент
ФормаОтчета2017Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2018Кв1_ФормаОтчета : ТабличныйДокумент
СоставПоказателей2017Кв1 : ТабличныйДокумент
СоставПоказателей2018Кв1 : ТабличныйДокумент
ШаблонРосстата2017Кв1_месяц : ДвоичныеДанные
ШаблонРосстата2017Кв1_квартал : ДвоичныеДанные
ШаблонРосстата2018Кв1_месяц : ДвоичныеДанные
ШаблонРосстата2018Кв1_квартал : ДвоичныеДанные
МакетПереносаДанных2017Кв1 : ТабличныйДокумент
МакетПереносаДанных2018Кв1 : ТабличныйДокумент
Списки2017кв1 : ТабличныйДокумент
Списки2018кв1 : ТабличныйДокумент
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2018Кв1 : ТекстовыйДокумент
}
@enduml
