@startuml СравнениеСегментовПартнеров
'!include templates.wsd
'..\include templates.wsd
class Отчет.СравнениеСегментовПартнеров as "Сравнение сегментов клиентов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
