@startuml РегламентированныйОтчетСтатистикаФорма7Травматизм
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма7Травматизм as "Форма 7-травматизм "Сведения о травматизме на производстве и профессиональных заболеваниях"" <<Отчеты>>
{
..Макеты..
СхемаВыгрузкиXML2013Кв1_форма : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв1_прил : ТабличныйДокумент
АтрибВыгрузкиXML2013Кв1_форма : ТабличныйДокумент
АтрибВыгрузкиXML2013Кв1_прил : ТабличныйДокумент
ФормаОтчета2013Кв1_Форма7Травматизм : ТабличныйДокумент
ФормаОтчета2013Кв1_Приложение : ТабличныйДокумент
ШаблонРосстата2013Кв1_форма : ДвоичныеДанные
ШаблонРосстата2013Кв1_прил : ДвоичныеДанные
НастройкиЗагрузкиXML2013Кв1 : ТекстовыйДокумент
ФормаОтчета2016Кв1_ФормаОтчета : ТабличныйДокумент
СхемаВыгрузкиXML2016Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1 : ТабличныйДокумент
ШаблонРосстата2016Кв1 : ДвоичныеДанные
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
}
@enduml
