@startuml ВедомостьПоПартиямТоваров
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВедомостьПоПартиямТоваров as "Ведомость по партиям товаров" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
