@startuml СравнениеПлановыхИФактическихНачислений
'!include templates.wsd
'..\include templates.wsd
class Отчет.СравнениеПлановыхИФактическихНачислений as "Сравнение плановых и фактических начислений" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
