@startuml РегламентированныйОтчетРеестрАкцизыПриложение2
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетРеестрАкцизыПриложение2 as "Реестр по акцизам: Приложение 02" <<Отчеты>>
{
..Макеты..
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
СпискиВыбора2017Кв1 : ТабличныйДокумент
СхемаВыгрузки501_1 : ТабличныйДокумент
СхемаВыгрузки501_2 : ТабличныйДокумент
СхемаВыгрузки502_1 : ТабличныйДокумент
ФормаОтчета2017Кв1_Реестр : ТабличныйДокумент
ФормаОтчета2017Кв1_Титульный : ТабличныйДокумент
}
@enduml
