@startuml ДебиторскаяЗадолженность
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДебиторскаяЗадолженность as "Задолженность клиентов по срокам" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
