@startuml ОтклонениеЗаказаФактаОтКалькуляции
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОтклонениеЗаказаФактаОтКалькуляции as "Анализ отклонений по заказам на производство" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
