@startuml АнализПервичногоИнтереса
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализПервичногоИнтереса as "Первичный интерес" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
