@startuml ЛицевыеСчетаСотрудников
'!include templates.wsd
'..\include templates.wsd
class Отчет.ЛицевыеСчетаСотрудников as "Лицевые счета сотрудников" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
ПФ_MXL_Т54 : ТабличныйДокумент
ПФ_MXL_Т54а : ТабличныйДокумент
}
@enduml
