@startuml РегламентированныйОтчетСтатистикаФорма2ГСГЗ
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма2ГСГЗ as "Форма 2-ГС (ГЗ) "Сведения о дополнительном профессиональном образовании федеральных государственных гражданских служащих и государственных гражданских служащих субъектов Российской Федерации"" <<Отчеты>>
{
..Макеты..
АтрибВыгрузкиXML2013Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2014Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2014Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1_рег : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1_фед : ТабличныйДокумент
СхемаВыгрузкиXML2015Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1_рег : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1_фед : ТабличныйДокумент
СхемаВыгрузкиXML2016Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1_рег : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1_фед : ТабличныйДокумент
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
ФормаОтчета2013Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2014Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2015Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2016Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2017Кв1_ФормаОтчета : ТабличныйДокумент
ШаблонРосстата2015Кв1_рег : ДвоичныеДанные
ШаблонРосстата2015Кв1_фед : ДвоичныеДанные
ШаблонРосстата2016Кв1_рег : ДвоичныеДанные
ШаблонРосстата2016Кв1_фед : ДвоичныеДанные
ШаблонРосстата2017Кв1_рег : ДвоичныеДанные
ШаблонРосстата2017Кв1_фед : ДвоичныеДанные
НастройкиЗагрузкиXML2015Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
СоставПоказателей2017Кв1 : ТабличныйДокумент
}
@enduml
