@startuml ЖурналУчетаИсполнительныхДокументов
'!include templates.wsd
'..\include templates.wsd
class Отчет.ЖурналУчетаИсполнительныхДокументов as "Журнал учета исполнительных документов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
ПФ_MXL_ЖурналУчетаИсполнительныхДокументов : ТабличныйДокумент
}
@enduml
