@startuml РегламентированныйОтчетАлкоПриложение15
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетАлкоПриложение15 as "Декларация об объеме винограда, использованного для производства винодельческой продукции с защищенным географическим указанием, с защищенным наименованием места происхождения и полного цикла производства дистиллятов" <<Отчеты>>
{
..Макеты..
НастройкиЗагрузкиXML2016Кв2 : ТекстовыйДокумент
ПечатнаяФормаОтчета2016Кв2_Декларация : ТабличныйДокумент
ПечатнаяФормаОтчета2016Кв2_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2016Кв4_Декларация : ТабличныйДокумент
ПечатнаяФормаОтчета2016Кв4_Титульный : ТабличныйДокумент
СоставПоказателей2016Кв2 : ТабличныйДокумент
СоставПоказателей2016Кв4 : ТабличныйДокумент
Списки2016Кв2 : ТабличныйДокумент
Списки2016Кв4 : ТабличныйДокумент
Списки2017Кв1 : ТабличныйДокумент
СхемаВыгрузки431 : ТабличныйДокумент
СхемаВыгрузки432 : ТабличныйДокумент
ФормаОтчета2016Кв2_Декларация : ТабличныйДокумент
ФормаОтчета2016Кв2_Титульный : ТабличныйДокумент
ШаблоныСообщенийОбОшибках2016Кв4 : ТабличныйДокумент
}
@enduml
