@startuml СостояниеШтатногоРасписания
'!include templates.wsd
'..\include templates.wsd
class Отчет.СостояниеШтатногоРасписания as "Состояние штатного расписания" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
