@startuml РегламентированныйОтчетСтатистикаФорма5З
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма5З as "Форма 5-З "Сведения о затратах на производство и реализацию продукции (работ, услуг)"" <<Отчеты>>
{
..Макеты..
СхемаВыгрузкиXML2011Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2011Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2013Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2014Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2014Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2015Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2016Кв1 : ТабличныйДокумент
ФормаОтчета2011Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2012Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2013Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2014Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2015Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2016Кв1_ФормаОтчета : ТабличныйДокумент
СоставПоказателей2013Кв1 : ТабличныйДокумент
СоставПоказателей2014Кв1 : ТабличныйДокумент
СоставПоказателей2015Кв1 : ТабличныйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
ШаблонРосстата2016Кв1 : ДвоичныеДанные
МакетПереносаДанных2016Кв1 : ТабличныйДокумент
НастройкиЗагрузкиXML2015Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
}
@enduml
