@startuml РегламентированноеУведомлениеПрекращениеПатент
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеПрекращениеПатент as "Регламентированное уведомление прекращение деятельности по патентной системе" <<Отчеты>>
{
..Макеты..
Форма2014_1 : ТабличныйДокумент
ПараметрыФорма2014_1 : ТабличныйДокумент
СхемаВыгрузкиФорма2014_1 : ТабличныйДокумент
Печать_MXL_Форма2014_1 : ТабличныйДокумент
СоставПоказателей2014_1 : ТабличныйДокумент
}
@enduml
