@startuml РегламентированныйОтчетНДС
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетНДС as "Декларация по налогу на добавленную стоимость" <<Отчеты>>
{
..Макеты..
МБ_1151001_5_01000_05_tif : ДвоичныеДанные
МБ_1151001_5_02000_06_tif : ДвоичныеДанные
МБ_1151001_5_03000_07_tif : ДвоичныеДанные
МБ_1151001_5_04000_09_tif : ДвоичныеДанные
МБ_1151001_5_05000_10_tif : ДвоичныеДанные
МЧБ_2009Кв4_1 : ТабличныйДокумент
МЧБ_2009Кв4_10 : ТабличныйДокумент
МЧБ_2009Кв4_2 : ТабличныйДокумент
МЧБ_2009Кв4_3 : ТабличныйДокумент
МЧБ_2009Кв4_4 : ТабличныйДокумент
МЧБ_2009Кв4_5 : ТабличныйДокумент
МЧБ_2009Кв4_6 : ТабличныйДокумент
МЧБ_2009Кв4_7 : ТабличныйДокумент
МЧБ_2009Кв4_8 : ТабличныйДокумент
МЧБ_2009Кв4_9 : ТабличныйДокумент
НастройкиЗагрузкиXML2015Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
ПечатныйБланк2015Кв1_Раздел1 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел10 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел10_Прод : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел11 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел11_Прод : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел12 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел2 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел3 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел3_Прил1 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел3_Прил2 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел4 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел5 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел6 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел7 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел8 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел8_Прил1 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел8_Прил1_Прод : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел8_Прод : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел9 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел9_Прил1 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел9_Прил1_Прод1 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел9_Прил1_Прод2 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел9_Прил1_Прод3 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел9_Прод1 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел9_Прод2 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Титульный : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел1 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел10 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел10_Прод : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел11 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел11_Прод : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел12 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел2 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел3 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел3_Прил1 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел3_Прил2 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел4 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел5 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел6 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел7 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел8 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел8_Прил1 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел8_Прил1_Прод : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел8_Прод : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел9 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел9_Прил1 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел9_Прил1_Прод1 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел9_Прил1_Прод2 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел9_Прил1_Прод3 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел9_Прод1 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел9_Прод2 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Титульный : ТабличныйДокумент
СоставПоказателей2009Кв4 : ТабличныйДокумент
СоставПоказателей2015Кв1 : ТабличныйДокумент
СоставПоказателей2017Кв1 : ТабличныйДокумент
Списки2009Кв4 : ТабличныйДокумент
Списки2015Кв1 : ТабличныйДокумент
Списки2017Кв1 : ТабличныйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
СхемаВыгрузки502 : ТабличныйДокумент
СхемаВыгрузки503 : ТабличныйДокумент
СхемаВыгрузки504 : ТабличныйДокумент
СхемаВыгрузки505 : ТабличныйДокумент
ФормаОтчета2009Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2009Кв4_Раздел2 : ТабличныйДокумент
ФормаОтчета2009Кв4_Раздел3 : ТабличныйДокумент
ФормаОтчета2009Кв4_Раздел3_Прил1 : ТабличныйДокумент
ФормаОтчета2009Кв4_Раздел3_Прил2 : ТабличныйДокумент
ФормаОтчета2009Кв4_Раздел4 : ТабличныйДокумент
ФормаОтчета2009Кв4_Раздел5 : ТабличныйДокумент
ФормаОтчета2009Кв4_Раздел6 : ТабличныйДокумент
ФормаОтчета2009Кв4_Раздел7 : ТабличныйДокумент
ФормаОтчета2009Кв4_Титульный : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел10 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел11 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел12 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел3_Прил1 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел3_Прил2 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел4 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел5 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел6 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел7 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел8 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел8_Прил1 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел9 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел9_Прил1 : ТабличныйДокумент
ФормаОтчета2015Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел10 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел11 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел12 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел3_Прил1 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел3_Прил2 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел4 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел5 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел6 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел7 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел8 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел8_Прил1 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел9 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел9_Прил1 : ТабличныйДокумент
ФормаОтчета2017Кв1_Титульный : ТабличныйДокумент
ШаблоныСообщенийОбОшибках2015Кв1 : ТабличныйДокумент
ШаблоныСообщенийОбОшибках2017Кв1 : ТабличныйДокумент
}
@enduml
