@startuml АнализИсполненияАссортимента
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализИсполненияАссортимента as "Исполнение ассортимента" <<Отчеты>>
{
..Реквизиты..
ПериодРасшифровки : Дата
ВыбранныйВариант : Строка
..Макеты..
Макет : ТабличныйДокумент
СхемаДляОтбора : СхемаКомпоновкиДанных
}
@enduml
