@startuml СправкаРасчетТорговогоСбора
'!include templates.wsd
'..\include templates.wsd
class Отчет.СправкаРасчетТорговогоСбора as "Расчет торгового сбора" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
РежимРасшифровки : Булево
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
СхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
