@startuml РегламентированныйОтчетСтатистикаФорма1ГС
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма1ГС as "Форма 1-ГС "Сведения о составе работников, замещавших государственные должности и должности государственной гражданской службы, по полу, возрасту, стажу государственной службы, образованию"" <<Отчеты>>
{
..Макеты..
СоставПоказателей2013Кв1 : ТабличныйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2013Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2016Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1_рег : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1_фед : ТабличныйДокумент
ФормаОтчета2013Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2016Кв1_ФормаОтчета : ТабличныйДокумент
ШаблонРосстата2016Кв1_рег : ДвоичныеДанные
ШаблонРосстата2016Кв1_фед : ДвоичныеДанные
НастройкиЗагрузкиXML2013Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
}
@enduml
