@startuml СостояниеАссортимента
'!include templates.wsd
'..\include templates.wsd
class Отчет.СостояниеАссортимента as "Состояние ассортимента" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
