@startuml РегламентированныйОтчетЖивотныйМир
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетЖивотныйМир as "Расчет сбора за пользование объектами животного мира" <<Отчеты>>
{
..Макеты..
МБ_1110012_3_00001_04_tif : ДвоичныеДанные
МБ_1110012_3_00002_05_tif : ДвоичныеДанные
ПечатнаяФормаОтчета2006кв1_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2006кв1_Раздел2 : ТабличныйДокумент
ПечатнаяФормаОтчета2006кв1_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2013Кв4_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2013Кв4_Раздел2 : ТабличныйДокумент
ПечатнаяФормаОтчета2013Кв4_Титульный : ТабличныйДокумент
СоставПоказателей2006Кв1 : ТабличныйДокумент
СоставПоказателей2013Кв4 : ТабличныйДокумент
Списки2006Кв1 : ТабличныйДокумент
СпискиВыбора2013Кв4 : ТабличныйДокумент
ФормаОтчета2006кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2006кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2006кв1_Титульный : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел2 : ТабличныйДокумент
ФормаОтчета2013Кв4_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2013Кв4 : ТекстовыйДокумент
}
@enduml
