@startuml СтраховыеВзносыПереданныеВПФР
'!include templates.wsd
'..\include templates.wsd
class Отчет.СтраховыеВзносыПереданныеВПФР as "Страховые взносы, переданные в ПФР" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
