@startuml РасчетыСПартнерами
'!include templates.wsd
'..\include templates.wsd
class Отчет.РасчетыСПартнерами as "Сводная ведомость расчетов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
