@startuml СостояниеРасчетовСКлиентамиСамообслуживание
'!include templates.wsd
'..\include templates.wsd
class Отчет.СостояниеРасчетовСКлиентамиСамообслуживание as "Состояние расчетов с клиентами самообслуживание" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
