@startuml КарточкаРасчетовПоПереданнойВозвратнойТаре
'!include templates.wsd
'..\include templates.wsd
class Отчет.КарточкаРасчетовПоПереданнойВозвратнойТаре as "Карточка расчетов по переданной возвратной таре" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
