@startuml СоставыСемейСотрудников
'!include templates.wsd
'..\include templates.wsd
class Отчет.СоставыСемейСотрудников as "Составы семей сотрудников" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
