@startuml ПубликуемыеТорговыеПредложения
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПубликуемыеТорговыеПредложения as "Публикуемые торговые предложения" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
