@startuml РегламентированныйОтчетВодныеБиоресурсы
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетВодныеБиоресурсы as "Расчет сбора за пользование объектами водных биологических ресурсов" <<Отчеты>>
{
..Макеты..
МБ_1110011_5_01000_05_tif : ДвоичныеДанные
МБ_1110011_5_02000_06_tif : ДвоичныеДанные
МБ_1110011_5_03000_07_tif : ДвоичныеДанные
МЧБ_2010кв4_01_Титульный : ТабличныйДокумент
МЧБ_2010кв4_02_Раздел1 : ТабличныйДокумент
МЧБ_2010кв4_03_Раздел2 : ТабличныйДокумент
НастройкиЗагрузкиXML2013Кв4 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв4 : ТекстовыйДокумент
ПечатныйБланк2013Кв4_Раздел1 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Раздел2 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Титульный : ТабличныйДокумент
ПечатныйБланк2017Кв4_Раздел1 : ТабличныйДокумент
ПечатныйБланк2017Кв4_Раздел2 : ТабличныйДокумент
ПечатныйБланк2017Кв4_Титульный : ТабличныйДокумент
СоставПоказателей2010Кв4 : ТабличныйДокумент
СоставПоказателей2013Кв4 : ТабличныйДокумент
Списки2010кв4 : ТабличныйДокумент
СпискиВыбора2013кв4 : ТабличныйДокумент
СпискиВыбора2017Кв4 : ТабличныйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
СхемаВыгрузки502 : ТабличныйДокумент
СхемаВыгрузки503 : ТабличныйДокумент
ФормаОтчета2010Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2010Кв4_Раздел2 : ТабличныйДокумент
ФормаОтчета2010Кв4_Титульный : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел2 : ТабличныйДокумент
ФормаОтчета2013Кв4_Титульный : ТабличныйДокумент
ФормаОтчета2017Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2017Кв4_Раздел2 : ТабличныйДокумент
ФормаОтчета2017Кв4_Титульный : ТабличныйДокумент
}
@enduml
