@startuml РегламентированныйОтчет6НДФЛ
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчет6НДФЛ as "Расчет сумм налога на доходы физических лиц, исчисленных и удержанных налоговым агентом" <<Отчеты>>
{
..Макеты..
МБ_1151099_5_01000_01_tif : ДвоичныеДанные
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв4 : ТекстовыйДокумент
ПечатныйБланк2016Кв1_Раздел12 : ТабличныйДокумент
ПечатныйБланк2016Кв1_Титульный : ТабличныйДокумент
ПечатныйБланк2017Кв4_Раздел12 : ТабличныйДокумент
ПечатныйБланк2017Кв4_Титульный : ТабличныйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
СоставПоказателей2017Кв4 : ТабличныйДокумент
СпискиВыбора2016Кв1 : ТабличныйДокумент
СпискиВыбора2017Кв4 : ТабличныйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
СхемаВыгрузки502 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2016Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2017Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2017Кв4_Раздел2 : ТабличныйДокумент
ФормаОтчета2017Кв4_Титульный : ТабличныйДокумент
}
@enduml
