@startuml ВзаимозависимыеЛицаКонтролируемыхСделок
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВзаимозависимыеЛицаКонтролируемыхСделок as "Взаимозависимые лица контролируемых сделок" <<Отчеты>>
{
..Реквизиты..
Уведомление : Документ.Уведомление о контролируемых сделках
Организация : Справочник.Организация
ОтчетныйГод : Число 4, 0
РазмещениеДополнительныхПолей : Число 1, 0
КонецПериода : Дата
НачалоПериода : Дата
РежимРасшифровки : Булево
..Макеты..
СхемаКомпоновкиДанныхКонтрагенты : СхемаКомпоновкиДанных
}
@enduml
