@startuml Расшифровка6НДФЛ
'!include templates.wsd
'..\include templates.wsd
class Отчет.Расшифровка6НДФЛ as "Расшифровка 6-НДФЛ" <<Отчеты>>
{
..Макеты..
Раздел1Доходы : СхемаКомпоновкиДанных
Раздел1Вычеты : СхемаКомпоновкиДанных
Раздел1Налоги : СхемаКомпоновкиДанных
Раздел2 : СхемаКомпоновкиДанных
}
@enduml
