@startuml ВедомостьПоТоварамОрганизаций
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВедомостьПоТоварамОрганизаций as "Ведомость по товарам организаций" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
