@startuml ИсполнениеПланаЗакупок
'!include templates.wsd
'..\include templates.wsd
class Отчет.ИсполнениеПланаЗакупок as "Исполнение плана закупок" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
