@startuml ИндексыЦенПоставщиков
'!include templates.wsd
'..\include templates.wsd
class Отчет.ИндексыЦенПоставщиков as "Индексы цен поставщиков" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
