@startuml ВыплатыНезарплатныхДоходов
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВыплатыНезарплатныхДоходов as "Выплаты незарплатных доходов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
