@startuml ИзменениеABCXYZРаспределенияКлиентов
'!include templates.wsd
'..\include templates.wsd
class Отчет.ИзменениеABCXYZРаспределенияКлиентов as "Изменение ABC/XYZ - распределения клиентов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
