@startuml СобытияМониторингаСПАРКРиски
'!include templates.wsd
'..\include templates.wsd
class Отчет.СобытияМониторингаСПАРКРиски as "События мониторинга 1СПАРК Риски" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
ОписаниеОшибок : ТабличныйДокумент
}
@enduml
