@startuml РегламентированноеУведомлениеС_ИО
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеС_ИО as "Сообщение об участниках иностранной организации" <<Отчеты>>
{
..Макеты..
Печать_Форма2017_1_Титульная : ТабличныйДокумент
Печать_Форма2017_1_Лист002 : ТабличныйДокумент
Печать_Форма2017_1_ЛистА : ТабличныйДокумент
Печать_Форма2017_1_ЛистБ : ТабличныйДокумент
Печать_Форма2017_1_ЛистВ : ТабличныйДокумент
Печать_Форма2017_1_ЛистГ : ТабличныйДокумент
Печать_Форма2017_1_ЛистД : ТабличныйДокумент
Печать_Форма2017_1_ЛистЕ : ТабличныйДокумент
Печать_Форма2017_1_ЛистЖ : ТабличныйДокумент
Печать_Форма2017_1_ЛистЗ : ТабличныйДокумент
СхемаВыгрузкиФорма2017_1 : ТабличныйДокумент
TIFF_2017_1 : ДвоичныеДанные
СпискиВыбора2017_1 : ТабличныйДокумент
ОбщиеЭлементы : ТабличныйДокумент
Титульная : ТабличныйДокумент
Лист002 : ТабличныйДокумент
ЛистА : ТабличныйДокумент
ЛистБ : ТабличныйДокумент
ЛистВ : ТабличныйДокумент
ЛистГ : ТабличныйДокумент
ЛистД : ТабличныйДокумент
ЛистЕ : ТабличныйДокумент
ЛистЖ : ТабличныйДокумент
ЛистЗ : ТабличныйДокумент
}
@enduml
