@startuml СостоянияСотрудников
'!include templates.wsd
'..\include templates.wsd
class Отчет.СостоянияСотрудников as "Состояния сотрудников" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
