@startuml АнализВыполненияМаршрутныхЛистов
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализВыполненияМаршрутныхЛистов as "Анализ выполнения маршрутных листов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
