@startuml ИндексыСПАРКРиски
'!include templates.wsd
'..\include templates.wsd
class Отчет.ИндексыСПАРКРиски as "Индексы 1СПАРК Риски" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
ОписаниеОшибок : ТабличныйДокумент
}
@enduml
