@startuml РегламентированныйОтчетСтатистикаФорма2МПинн
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма2МПинн as "Форма 2-МП-инновация "Сведения о технологических инновациях малого предприятия"" <<Отчеты>>
{
..Макеты..
АтрибВыгрузкиXML2013Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2015Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
ФормаОтчета2013Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2015Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2017Кв1_ФормаОтчета : ТабличныйДокумент
СоставПоказателей2013Кв1 : ТабличныйДокумент
СоставПоказателей2015Кв1 : ТабличныйДокумент
СоставПоказателей2017Кв1 : ТабличныйДокумент
ШаблонРосстата2015Кв1 : ДвоичныеДанные
ШаблонРосстата2017Кв1 : ДвоичныеДанные
НастройкиЗагрузкиXML2013Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2015Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
}
@enduml
