@startuml КонтрольПлатежаНаСоответствие275ФЗ
'!include templates.wsd
'..\include templates.wsd
class Отчет.КонтрольПлатежаНаСоответствие275ФЗ as "Контроль платежа на соответствие 275-ФЗ" <<Отчеты>>
{
..Реквизиты..
КонтролируемыйДокумент : Документ.Списание безналичных ДС\rДокумент.Заявка на расходование ДС
ТолькоСОшибками : Булево
ТолькоКонтролируемыеПользователем : Булево
..Макеты..
СоставКонтролей : ТабличныйДокумент
}
@enduml
