@startuml СправкаРасчетНалогаУСН
'!include templates.wsd
'..\include templates.wsd
class Отчет.СправкаРасчетНалогаУСН as "Расчет налога (авансового платежа по налогу), уплачиваемого при УСН" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
ПоказательБУ : Булево
ПоказательНУ : Булево
ПоказательПР : Булево
ПоказательВР : Булево
РежимРасшифровки : Булево
НаборПоказателейОтчета : Число 1, 0
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
