@startuml ЗначенияНефинансовыхПоказателей
'!include templates.wsd
'..\include templates.wsd
class Отчет.ЗначенияНефинансовыхПоказателей as "Значения нефинансовых показателей" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
