@startuml ПересеченияСегментаПартнеров
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПересеченияСегментаПартнеров as "Пересечения сегмента партнеров" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
