@startuml РегламентированныйОтчетРасчетПоОплатеЗаВоду
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетРасчетПоОплатеЗаВоду as "Расчет по оплате за воду" <<Отчеты>>
{
..Макеты..
СоставПоказателей : ТабличныйДокумент
ФормаОтчета2004кв1_ФормаОтчета : ТабличныйДокумент
}
@enduml
