@startuml ДосьеКонтрагента
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДосьеКонтрагента as "Досье контрагента" <<Отчеты>>
{
..Макеты..
Главное : ТабличныйДокумент
ДанныеГосРеестров : ТабличныйДокумент
БухгалтерскаяОтчетность : ТабличныйДокумент
АнализОтчетности : ТабличныйДокумент
ФинансовыйАнализ : ТабличныйДокумент
ДанныеПрограммы : ТабличныйДокумент
ПредельныеЗначенияРентабельностиИНалоговойНагрузки : ТабличныйДокумент
Проверки : ТабличныйДокумент
}
@enduml
