@startuml РегламентированныйОтчетСведенияОДолеДоходовОрганизацииПоСоцУслугам
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСведенияОДолеДоходовОрганизацииПоСоцУслугам as "Сведения о доле доходов организации от осуществления деятельности по предоставлению социальных услуг гражданам в общей сумме доходов организации и о численности работников в штате организации" <<Отчеты>>
{
..Макеты..
МБ_1150045_5_01000_01_tif : ДвоичныеДанные
ПечатныйБланк2015Кв4_Расчет : ТабличныйДокумент
ПечатныйБланк2015Кв4_Титульный : ТабличныйДокумент
СоставПоказателей2015Кв4 : ТабличныйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
ФормаОтчета2015Кв4_Расчет : ТабличныйДокумент
ФормаОтчета2015Кв4_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2015Кв4 : ТекстовыйДокумент
}
@enduml
