@startuml ДинамикаИзмененияЦенНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДинамикаИзмененияЦенНоменклатуры as "Динамика цен номенклатуры" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
