@startuml КарточкаРасчетовПоПринятойВозвратнойТаре
'!include templates.wsd
'..\include templates.wsd
class Отчет.КарточкаРасчетовПоПринятойВозвратнойТаре as "Карточка расчетов по принятой возвратной таре" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
