@startuml СверкаДанныхПартионногоУчетаИСебестоимости
'!include templates.wsd
'..\include templates.wsd
class Отчет.СверкаДанныхПартионногоУчетаИСебестоимости as "Сверка данных партионного учета и себестоимости" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
