@startuml ПаспортКонтракта
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПаспортКонтракта as "Паспорт контракта" <<Отчеты>>
{
..Реквизиты..
Контракт : Справочник.Договор между организациями\rСправочник.Договор с контрагентом
..Макеты..
ПечатнаяФорма : ТабличныйДокумент
}
@enduml
