@startuml ГрафикОтпусков
'!include templates.wsd
'..\include templates.wsd
class Отчет.ГрафикОтпусков as "График отпусков" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
ПФ_MXL_Т7 : ТабличныйДокумент
}
@enduml
