@startuml ПартнерыКоторымОтгрузкаЗапрещена
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПартнерыКоторымОтгрузкаЗапрещена as "Клиенты, которым отгрузка запрещена" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
