@startuml РегламентированныйОтчетСтатистикаБухОтчетность
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаБухОтчетность as "Бухгалтерская отчетность в Росстат" <<Отчеты>>
{
}
@enduml
