@startuml СтатистикаПерсонала
'!include templates.wsd
'..\include templates.wsd
class Отчет.СтатистикаПерсонала as "Статистика персонала" <<Отчеты>>
{
..Макеты..
СхемаКомпоновкиДанныхКадры : СхемаКомпоновкиДанных
СхемаКомпоновкиДанныхЗарплата : СхемаКомпоновкиДанных
СхемаКомпоновкиДанныхФормаП4НЗ : СхемаКомпоновкиДанных
}
@enduml
