@startuml ВоронкаПродаж
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВоронкаПродаж as "Воронка продаж" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
