@startuml АналитическийОтчетПоАнкетированию
'!include templates.wsd
'..\include templates.wsd
class Отчет.АналитическийОтчетПоАнкетированию as "Аналитический отчет по анкетированию" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
