@startuml ШтатноеРасписание
'!include templates.wsd
'..\include templates.wsd
class Отчет.ШтатноеРасписание as "Штатное расписание" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
ПФ_MXL_ШтатноеРасписаниеНаПодпись : ТабличныйДокумент
}
@enduml
