@startuml МестаИспользованияСсылок
'!include templates.wsd
'..\include templates.wsd
class Отчет.МестаИспользованияСсылок as "Места использования ссылок" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
