@startuml РегламентированныйОтчетСтатистикаФормаУчетаПеремещенияТоваровТС
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФормаУчетаПеремещенияТоваровТС as "Статистическая форма учета перемещения товаров во взаимной торговле Российской Федерации с государствами - членами ТС" <<Отчеты>>
{
..Макеты..
СоставПоказателей2011Кв1 : ТабличныйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2011Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2015Кв2 : ТабличныйДокумент
СхемаВыгрузкиXML2016Кв1 : ТабличныйДокумент
Списки2011кв1 : ТабличныйДокумент
Списки2015кв2 : ТабличныйДокумент
Списки2016кв1 : ТабличныйДокумент
ФормаОтчета2011Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2016Кв1_ФормаОтчета : ТабличныйДокумент
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
}
@enduml
