@startuml РегламентированныйОтчетСтатистикаФормаМПмикронатура
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФормаМПмикронатура as "Форма МП (микро)-натура "Сведения о производстве продукции микропредприятием"" <<Отчеты>>
{
..Макеты..
Списки2017кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
ФормаОтчета2017Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1 : ТабличныйДокумент
ШаблонРосстата2017Кв1 : ДвоичныеДанные
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
}
@enduml
