@startuml РегламентированныйОтчетВодныеБиоресурсыПрилов
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетВодныеБиоресурсыПрилов as "Расчет единовременного взноса за разрешенный прилов" <<Отчеты>>
{
..Макеты..
МБ_1110022_5_01000_01_tif : ДвоичныеДанные
МБ_1110022_5_02000_02_tif : ДвоичныеДанные
МЧБ_2010кв4_01_Титульный : ТабличныйДокумент
МЧБ_2010кв4_02_Раздел1 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Раздел1 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Титульный : ТабличныйДокумент
СоставПоказателей2010Кв4 : ТабличныйДокумент
СоставПоказателей2013Кв4 : ТабличныйДокумент
Списки2010кв4 : ТабличныйДокумент
СпискиВыбора2013Кв4 : ТабличныйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
СхемаВыгрузки502 : ТабличныйДокумент
ФормаОтчета2010Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2010Кв4_Титульный : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2013Кв4_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2013Кв4 : ТекстовыйДокумент
}
@enduml
