@startuml КарточкаСчетаМеждународный
'!include templates.wsd
'..\include templates.wsd
class Отчет.КарточкаСчетаМеждународный as "Карточка счета (международный учет)" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
