@startuml ГрафикПроизводстваПродукции
'!include templates.wsd
'..\include templates.wsd
class Отчет.ГрафикПроизводстваПродукции as "График производства продукции" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
