@startuml КонтактнаяИнформация
'!include templates.wsd
'..\include templates.wsd
class Отчет.КонтактнаяИнформация as "Контактная информация" <<Отчеты>>
{
..Макеты..
ОтборПоПартнерам : СхемаКомпоновкиДанных
ВыводДанных : ТабличныйДокумент
}
@enduml
