@startuml РегламентированныйОтчетЕСХН
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетЕСХН as "Декларация по единому сельскохозяйственному налогу" <<Отчеты>>
{
..Макеты..
МБ_1151059_5_01000_05_tif : ДвоичныеДанные
МБ_1151059_5_02000_06_tif : ДвоичныеДанные
МБ_1151059_5_03000_07_tif : ДвоичныеДанные
МБ_1151059_5_04000_08_tif : ДвоичныеДанные
МЧБ_2009Кв1_1 : ТабличныйДокумент
МЧБ_2009Кв1_2 : ТабличныйДокумент
МЧБ_2009Кв1_3 : ТабличныйДокумент
ПечатныйБланк2014Кв1_Раздел12 : ТабличныйДокумент
ПечатныйБланк2014Кв1_Раздел21 : ТабличныйДокумент
ПечатныйБланк2014Кв1_Раздел3 : ТабличныйДокумент
ПечатныйБланк2014Кв1_Титульный : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел12 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел21 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел3 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Титульный : ТабличныйДокумент
СоставПоказателей2009Кв1 : ТабличныйДокумент
СоставПоказателей2014Кв1 : ТабличныйДокумент
СоставПоказателей2015Кв1 : ТабличныйДокумент
Списки2009Кв1 : ТабличныйДокумент
СпискиВыбора2014Кв1 : ТабличныйДокумент
СпискиВыбора2015Кв1 : ТабличныйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
СхемаВыгрузки503 : ТабличныйДокумент
СхемаВыгрузки504 : ТабличныйДокумент
ФормаОтчета2009Кв1_Раздел12 : ТабличныйДокумент
ФормаОтчета2009Кв1_Раздел21 : ТабличныйДокумент
ФормаОтчета2009Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел12 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел12_Строка045 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел21 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2014Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел12 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел21 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2015Кв1_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2014Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2015Кв1 : ТекстовыйДокумент
}
@enduml
