@startuml ВоинскийУчетБронирование
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВоинскийУчетБронирование as "Воинский учет (бронирование)" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
ПФ_MXL_ЧисленностьРаботающихИЗабронированныхГражданЗапаса : ТабличныйДокумент
ПФ_MXL_ДонесениеОКоличествеГражданВЗапасе : ТабличныйДокумент
ПФ_MXL_АнализОбеспеченностиТрудовымиРесурсами : ТабличныйДокумент
ПФ_MXL_ЧисленностьРаботающихИЗабронированныхГражданЗапаса2015 : ТабличныйДокумент
ПФ_MXL_СведенияОбОбеспеченностиТрудовымиРесурсами : ТабличныйДокумент
}
@enduml
