@startuml АнализЗадолженностиПоЗарплате
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализЗадолженностиПоЗарплате as "Анализ задолженности по зарплате" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
