@startuml ИзменениеШтатногоРасписания
'!include templates.wsd
'..\include templates.wsd
class Отчет.ИзменениеШтатногоРасписания as "Изменение штатного расписания" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
