@startuml СводныйОтчетЕГАИС
'!include templates.wsd
'..\include templates.wsd
class Отчет.СводныйОтчетЕГАИС as "Сводный отчет ЕГАИС" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
