@startuml ОтклоненияСуммыВзаиморасчетовПоКлиентам
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОтклоненияСуммыВзаиморасчетовПоКлиентам as "Отклонения суммы взаиморасчетов по клиентам" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
