@startuml ЖурналУчетаРозничнойПродажиАлкогольнойПродукции
'!include templates.wsd
'..\include templates.wsd
class Отчет.ЖурналУчетаРозничнойПродажиАлкогольнойПродукции as "Журнал учета продаж алкоголя" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
Склад : Справочник.Склад (складская территория)
НачалоПериода : Дата
КонецПериода : Дата
ВключатьОбособленныеПодразделения : Булево
..Макеты..
Макет : ТабличныйДокумент
ПФ_MXL_164 : ТабличныйДокумент
}
@enduml
