@startuml РегламентированныйОтчетАкцизыПриложение7
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетАкцизыПриложение7 as "Декларация по акцизу на минеральное сырье (природный газ)" <<Отчеты>>
{
..Макеты..
СоставПоказателей2005Кв1 : ТабличныйДокумент
Списки2005Кв1 : ТабличныйДокумент
ФормаОтчета2005Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2005Кв1_ФизЛица : ТабличныйДокумент
ФормаОтчета2005Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2005Кв1_Раздел2 : ТабличныйДокумент
ПечатнаяФормаОтчета2005Кв1_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2005Кв1_ФизЛица : ТабличныйДокумент
ПечатнаяФормаОтчета2005Кв1_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2005Кв1_Раздел2 : ТабличныйДокумент
НастройкиЗагрузкиXML2005Кв1 : ТекстовыйДокумент
}
@enduml
