@startuml РегламентированныйОтчетСтатистикаФорма1ДМ
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма1ДМ as "Форма 1-ДМ "Сведения об остатках, поступлении и расходе алмазов в инструменте, порошках и пастах"" <<Отчеты>>
{
..Макеты..
ФормаОтчета2012Кв1_ФормаОтчета : ТабличныйДокумент
СоставПоказателей2012Кв1 : ТабличныйДокумент
}
@enduml
