@startuml ТоварыСИстекающимиСертификатами
'!include templates.wsd
'..\include templates.wsd
class Отчет.ТоварыСИстекающимиСертификатами as "Товары с истекающими сертификатами" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
