@startuml АнализСебестоимостиТоваровРасширенный
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализСебестоимостиТоваровРасширенный as "Себестоимость товаров" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
