@startuml КонтрольПоставкиПродукцииПереработчиком
'!include templates.wsd
'..\include templates.wsd
class Отчет.КонтрольПоставкиПродукцииПереработчиком as "Контроль поставки продукции переработчиком" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
