@startuml СтруктураСерииНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Отчет.СтруктураСерииНоменклатуры as "Структура серии номенклатуры" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
ПФ_MXL_СтруктураСерииНоменклатуры : ТабличныйДокумент
}
@enduml
