@startuml РезультатыСогласованияЗакупки
'!include templates.wsd
'..\include templates.wsd
class Отчет.РезультатыСогласованияЗакупки as "Результаты согласования закупки" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
