@startuml ОстаткиТоваровПереданныхПереработчикам
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОстаткиТоваровПереданныхПереработчикам as "Остатки сырья и материалов у переработчиков" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
