@startuml РегламентированныйОтчетАкцизыАлкоголь
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетАкцизыАлкоголь as "Декларация по акцизам на этиловый спирт, алкогольную и (или) подакцизную спиртосодержащую продукцию" <<Отчеты>>
{
..Макеты..
МБ_1151090_5_01000_01_tif : ДвоичныеДанные
ПечатныйБланк2016Кв2_Приложение1 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Приложение21 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Приложение22 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Приложение31 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Приложение32 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Приложение4 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Приложение5 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Приложение6 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Приложение7 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Приложение8 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Раздел1 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Раздел2 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Раздел31 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Раздел32 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Раздел33 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Титульный : ТабличныйДокумент
СоставПоказателей2016Кв2 : ТабличныйДокумент
СпискиВыбора2016Кв2 : ТабличныйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
ФормаОтчета2016Кв2_Приложение1 : ТабличныйДокумент
ФормаОтчета2016Кв2_Приложение21 : ТабличныйДокумент
ФормаОтчета2016Кв2_Приложение22 : ТабличныйДокумент
ФормаОтчета2016Кв2_Приложение31 : ТабличныйДокумент
ФормаОтчета2016Кв2_Приложение32 : ТабличныйДокумент
ФормаОтчета2016Кв2_Приложение4 : ТабличныйДокумент
ФормаОтчета2016Кв2_Приложение5 : ТабличныйДокумент
ФормаОтчета2016Кв2_Приложение6 : ТабличныйДокумент
ФормаОтчета2016Кв2_Приложение7 : ТабличныйДокумент
ФормаОтчета2016Кв2_Приложение8 : ТабличныйДокумент
ФормаОтчета2016Кв2_Раздел11 : ТабличныйДокумент
ФормаОтчета2016Кв2_Раздел12 : ТабличныйДокумент
ФормаОтчета2016Кв2_Раздел2 : ТабличныйДокумент
ФормаОтчета2016Кв2_Раздел31 : ТабличныйДокумент
ФормаОтчета2016Кв2_Раздел32 : ТабличныйДокумент
ФормаОтчета2016Кв2_Раздел33 : ТабличныйДокумент
ФормаОтчета2016Кв2_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2016Кв2 : ТекстовыйДокумент
}
@enduml
