@startuml ПланФактныйАнализМатериаловРаботВСебестоимостиВыпущеннойПродукции
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПланФактныйАнализМатериаловРаботВСебестоимостиВыпущеннойПродукции as "План-фактный анализ материалов и работ в себестоимости выпущенной продукции" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
