@startuml СправкаРасчетНалогаНаПрибыль
'!include templates.wsd
'..\include templates.wsd
class Отчет.СправкаРасчетНалогаНаПрибыль as "Расчет налога на прибыль" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
ВключатьОбособленныеПодразделения : Булево
ПоказательБУ : Булево
ПоказательНУ : Булево
ПоказательПР : Булево
ПоказательВР : Булево
РежимРасшифровки : Булево
НаборПоказателейОтчета : Число 1, 0
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
СхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
