@startuml РегламентированноеУведомлениеФормаР11001
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеФормаР11001 as "Заявление о регистрации юридического лица" <<Отчеты>>
{
..Макеты..
TIFF_2014_1 : ДвоичныеДанные
Печать_Форма2014_1_Страница1 : ТабличныйДокумент
Печать_Форма2014_1_Страница1_1 : ТабличныйДокумент
Печать_Форма2014_1_Страница1_2 : ТабличныйДокумент
Печать_Форма2014_1_Страница4 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаА : ТабличныйДокумент
Печать_Форма2014_1_СтраницаБ : ТабличныйДокумент
Печать_Форма2014_1_СтраницаВ1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаВ2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаГ1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаГ2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаГ3 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаД : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЕ1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЕ2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЖ1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЖ2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЖ3 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЗ1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЗ2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаИ : ТабличныйДокумент
Печать_Форма2014_1_СтраницаК : ТабличныйДокумент
Печать_Форма2014_1_СтраницаЛ : ТабличныйДокумент
Печать_Форма2014_1_СтраницаМ : ТабличныйДокумент
Печать_Форма2014_1_СтраницаН1 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаН2 : ТабличныйДокумент
Печать_Форма2014_1_СтраницаН3 : ТабличныйДокумент
СпискиВыбора2014_1 : ТабличныйДокумент
СхемаВыгрузкиФорма2014_1 : ТабличныйДокумент
Форма2014_1_Страница1 : ТабличныйДокумент
Форма2014_1_СтраницаА : ТабличныйДокумент
Форма2014_1_СтраницаБ : ТабличныйДокумент
Форма2014_1_СтраницаВ : ТабличныйДокумент
Форма2014_1_СтраницаГ1 : ТабличныйДокумент
Форма2014_1_СтраницаГ2_3 : ТабличныйДокумент
Форма2014_1_СтраницаД : ТабличныйДокумент
Форма2014_1_СтраницаЕ : ТабличныйДокумент
Форма2014_1_СтраницаЖ : ТабличныйДокумент
Форма2014_1_СтраницаЗ : ТабличныйДокумент
Форма2014_1_СтраницаИ : ТабличныйДокумент
Форма2014_1_СтраницаК : ТабличныйДокумент
Форма2014_1_СтраницаЛ : ТабличныйДокумент
Форма2014_1_СтраницаМ : ТабличныйДокумент
Форма2014_1_СтраницаН : ТабличныйДокумент
Форматы2014_1 : ТабличныйДокумент
}
@enduml
