@startuml ТекущаяНаполненностьАссортимента
'!include templates.wsd
'..\include templates.wsd
class Отчет.ТекущаяНаполненностьАссортимента as "Наполненность ассортимента" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
