@startuml ТоварныйОтчетТОРГ29
'!include templates.wsd
'..\include templates.wsd
class Отчет.ТоварныйОтчетТОРГ29 as "Товарный отчет (ТОРГ-29)" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
Склад : Справочник.Склад (складская территория)
НомерОтчета : Число 10, 0
ДатаНачала : Дата
ДатаОкончания : Дата
..Макеты..
Макет : ТабличныйДокумент
}
@enduml
