@startuml ВедомостьПоТоварамНаСкладах
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВедомостьПоТоварамНаСкладах as "Ведомость по товарам на складах" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
