@startuml РегламентированныйОтчетСтатистикаФорма26ЖКХ
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма26ЖКХ as "Форма 26-ЖКХ "Сведения о предоставлении гражданам социальной поддержки по оплате жилого помещения и коммунальных услуг"" <<Отчеты>>
{
..Макеты..
СхемаВыгрузкиXML2012Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2012Кв1 : ТабличныйДокумент
ФормаОтчета2012Кв1_ФормаОтчета : ТабличныйДокумент
ШаблонРосстата2012Кв1 : ДвоичныеДанные
НастройкиЗагрузкиXML2012Кв1 : ТекстовыйДокумент
}
@enduml
