@startuml СправкаПоОтпускам
'!include templates.wsd
'..\include templates.wsd
class Отчет.СправкаПоОтпускам as "Справка по отпускам" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
