@startuml ОценкаРентабельностиПродаж
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОценкаРентабельностиПродаж as "Оценка рентабельности продаж" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
