@startuml РегламентированныйОтчетСведенияОДолеДоходовОтОбразовательнойИлиМедДеятельности
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСведенияОДолеДоходовОтОбразовательнойИлиМедДеятельности as "Сведения о доле доходов организации от осуществления образовательной и (или) медицинской деятельности" <<Отчеты>>
{
..Макеты..
МБ_1150022_5_01000_01_tif : ДвоичныеДанные
МЧБ_2011Кв4_1 : ТабличныйДокумент
МЧБ_2011Кв4_2 : ТабличныйДокумент
СоставПоказателей2011Кв4 : ТабличныйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
ФормаОтчета2011Кв4_Расчет : ТабличныйДокумент
ФормаОтчета2011Кв4_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2011Кв4 : ТекстовыйДокумент
}
@enduml
