@startuml МониторЦелевыхПоказателей
'!include templates.wsd
'..\include templates.wsd
class Отчет.МониторЦелевыхПоказателей as "Монитор целевых показателей" <<Отчеты>>
{
..Макеты..
ВебЦветаВRGB : ТабличныйДокумент
МакетОбозначенийЭлектроннойФормыПоказателя : ТабличныйДокумент
МакетСводнойСтраницы : ТабличныйДокумент
МакетСтраницыПоказателя : ТабличныйДокумент
МатрицаСостоянийПоказателей : ТабличныйДокумент
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
