@startuml СправкаРасчетАмортизационнойПремии
'!include templates.wsd
'..\include templates.wsd
class Отчет.СправкаРасчетАмортизационнойПремии as "Справка-расчет "Амортизационная премия"" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
ВключатьОбособленныеПодразделения : Булево
ПоказательБУ : Булево
ПоказательНУ : Булево
ПоказательПР : Булево
ПоказательВР : Булево
РежимРасшифровки : Булево
НаборПоказателейОтчета : Число 1, 0
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
