@startuml ПрайсЛистДляПриемаЗаказов
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПрайсЛистДляПриемаЗаказов as "Прайс-лист (для приема заказов)" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
