@startuml ОборотнаяВедомостьБюджетирования
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОборотнаяВедомостьБюджетирования as "Оборотная ведомость бюджетирования" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
ОборотыПлан : СхемаКомпоновкиДанных
}
@enduml
