@startuml ОборотыСчета
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОборотыСчета as "Обороты счета" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
Счет : Счет бухгалтерского учета
ВключатьОбособленныеПодразделения : Булево
ПоСубсчетам : Булево
Периодичность : Число 2, 0
ПоСубсчетамКорСчетов : Булево
СальдоНаНачалоДт : Булево
СальдоНаНачалоКт : Булево
СальдоНаКонецДт : Булево
СальдоНаКонецКт : Булево
ОборотыЗаПериодДт : Булево
ОборотыЗаПериодКт : Булево
ОборотыСоСчетамиДт : Булево
ОборотыСоСчетамиКт : Булево
ПоказательБУ : Булево
ПоказательНУ : Булево
ПоказательПР : Булево
ПоказательВР : Булево
ПоказательКонтроль : Булево
ПоказательВалютнаяСумма : Булево
ПоказательКоличество : Булево
РазвернутоеСальдо : Булево
РазмещениеДополнительныхПолей : Число 1, 0
РежимРасшифровки : Булево
ПоказательУУ : Булево
ПоказательФО : Булево
ПоказательРазницаБУиУУ : Булево
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
СхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
