@startuml ДинамикаИзмененияЦенНоменклатурыПоставщика
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДинамикаИзмененияЦенНоменклатурыПоставщика as "Динамика изменения цен номенклатуры поставщика" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
