@startuml РеестрСчетовФактурДляСверки
'!include templates.wsd
'..\include templates.wsd
class Отчет.РеестрСчетовФактурДляСверки as "Реестр счетов-фактур для сверки" <<Отчеты>>
{
..Реквизиты..
ПериодРегистрации : Дата
Организация : Справочник.Организация
Контрагент : Справочник.Контрагент
ЧастьЖурнала : Части журнала учета счетов-фактур
..Макеты..
Макет : ТабличныйДокумент
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
