@startuml ИсполнениеПланаПродаж
'!include templates.wsd
'..\include templates.wsd
class Отчет.ИсполнениеПланаПродаж as "Исполнение плана продаж" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
