@startuml КонтрольДвиженияПродукцииИМатериаловПоЭтапуПроизводства
'!include templates.wsd
'..\include templates.wsd
class Отчет.КонтрольДвиженияПродукцииИМатериаловПоЭтапуПроизводства as "Контроль движения продукции и материалов по этапу производства" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
