@startuml ВедомостьПоТоварамОрганизацийВЦенахНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВедомостьПоТоварамОрганизацийВЦенахНоменклатуры as "Ведомость по товарам организаций в ценах номенклатуры" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
