@startuml РеестрКредитовИДепозитов
'!include templates.wsd
'..\include templates.wsd
class Отчет.РеестрКредитовИДепозитов as "Реестр договоров по кредитам и депозитам" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
