@startuml РегламентированныйОтчетСтатистикаФормаП1Приложение3
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФормаП1Приложение3 as "Приложение №3 к форме №П-1 "Сведения об объеме платных услуг населению"" <<Отчеты>>
{
..Макеты..
СхемаВыгрузкиXML2010Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2010Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2012Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2012Кв1 : ТабличныйДокумент
ФормаОтчета2010Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2012Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2013Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2016Кв1_ФормаОтчета : ТабличныйДокумент
СоставПоказателей2013Кв1 : ТабличныйДокумент
МакетПереносаДанных2016Кв1 : ТабличныйДокумент
НастройкиЗагрузкиXML2013Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
}
@enduml
