@startuml РегламентированныйОтчетСтатистикаФормаМПм
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФормаМПм as "Форма МП(микро) "Сведения об основных показателях деятельности микропредприятия"" <<Отчеты>>
{
..Макеты..
Список2011Кв1 : ТабличныйДокумент
Список2012Кв1 : ТабличныйДокумент
Список2013Кв1 : ТабличныйДокумент
Список2014Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2011Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2011Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2012Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2012Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2013Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2014Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2014Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2016Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
ФормаОтчета2011Кв1_МПм : ТабличныйДокумент
ФормаОтчета2011Кв1_Приложение1 : ТабличныйДокумент
ФормаОтчета2011Кв1_Приложение2 : ТабличныйДокумент
ФормаОтчета2011Кв1_Приложение3 : ТабличныйДокумент
ФормаОтчета2012Кв1_МПм : ТабличныйДокумент
ФормаОтчета2012Кв1_Приложение1 : ТабличныйДокумент
ФормаОтчета2012Кв1_Приложение2 : ТабличныйДокумент
ФормаОтчета2012Кв1_Приложение3 : ТабличныйДокумент
ФормаОтчета2013Кв1_МПм : ТабличныйДокумент
ФормаОтчета2013Кв1_Приложение1 : ТабличныйДокумент
ФормаОтчета2013Кв1_Приложение2 : ТабличныйДокумент
ФормаОтчета2013Кв1_Приложение3 : ТабличныйДокумент
ФормаОтчета2014Кв1_МПм : ТабличныйДокумент
ФормаОтчета2014Кв1_Приложение1 : ТабличныйДокумент
ФормаОтчета2014Кв1_Приложение2 : ТабличныйДокумент
ФормаОтчета2014Кв1_Приложение3 : ТабличныйДокумент
ФормаОтчета2016Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2017Кв1_ФормаОтчета : ТабличныйДокумент
НастройкиЗагрузкиXML2014Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
ШаблонРосстата2016Кв1 : ДвоичныеДанные
ШаблонРосстата2017Кв1 : ДвоичныеДанные
СоставПоказателей2016Кв1 : ТабличныйДокумент
СоставПоказателей2017Кв1 : ТабличныйДокумент
}
@enduml
