@startuml ОстаткиОтпусков
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОстаткиОтпусков as "Остатки отпусков" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
