@startuml БухгалтерскийОтчетМеждународный
'!include templates.wsd
'..\include templates.wsd
class Отчет.БухгалтерскийОтчетМеждународный as "Бухгалтерский отчет (международный учет)" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
