@startuml РеестрПолучателейСтраховогоОбеспечения
'!include templates.wsd
'..\include templates.wsd
class Отчет.РеестрПолучателейСтраховогоОбеспечения as "Реестр пособий (за счет ФСС)" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
