@startuml ОтчетыПоСотрудникам
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОтчетыПоСотрудникам as "Отчеты по сотрудникам" <<Отчеты>>
{
..Макеты..
ОтчетыПоСотрудникамБазовый : СхемаКомпоновкиДанных
ОтчетыПоСотрудникамРасширенный : СхемаКомпоновкиДанных
ПФ_MXL_Т4 : ТабличныйДокумент
}
@enduml
