@startuml СхемаМаршрутнойКарты
'!include templates.wsd
'..\include templates.wsd
class Отчет.СхемаМаршрутнойКарты as "Схема маршрутной карты" <<Отчеты>>
{
..Реквизиты..
МаршрутнаяКарта : Справочник.Маршрутная карта
ПоказатьОперацииВложенныхМаршрутов : Булево
..Макеты..
Макет : ТабличныйДокумент
}
@enduml
