@startuml ВыручкаИСебестоимостьРозничныхПродаж
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВыручкаИСебестоимостьРозничныхПродаж as "Выручка и себестоимость розничных продаж" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
