@startuml РегламентированноеУведомлениеУтратаПраваПатент
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеУтратаПраваПатент as "Регламентированное уведомление утрата права на патентную систему налогообложения" <<Отчеты>>
{
..Макеты..
Форма2014_1 : ТабличныйДокумент
ПараметрыФорма2014_1 : ТабличныйДокумент
СхемаВыгрузкиФорма2014_1 : ТабличныйДокумент
Печать_MXL_Форма2014_1 : ТабличныйДокумент
TIFF_2014_1 : ДвоичныеДанные
СоставПоказателей2014_1 : ТабличныйДокумент
}
@enduml
