@startuml ПлановыеИФактическиеЗатратыПеределов
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПлановыеИФактическиеЗатратыПеределов as "Плановые и фактические затраты переделов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
