@startuml РегламентированныйОтчетЕУНД
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетЕУНД as "Единая (упрощенная) налоговая декларация" <<Отчеты>>
{
..Макеты..
МБ_1151085_4_01000_04_tif : ДвоичныеДанные
МБ_1151085_4_02000_05_tif : ДвоичныеДанные
ПечатнаяФормаОтчета2007Кв3_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв3_ФизЛица : ТабличныйДокумент
СоставПоказателей2007Кв3 : ТабличныйДокумент
СтруктураXML2007 : ТабличныйДокумент
СтруктураXML402 : ТабличныйДокумент
ФормаОтчета2007Кв3_Титульный : ТабличныйДокумент
ФормаОтчета2007Кв3_ФизЛица : ТабличныйДокумент
НастройкиЗагрузкиXML2007Кв3 : ТекстовыйДокумент
}
@enduml
