@startuml ФактическаяСебестоимостьПродукции
'!include templates.wsd
'..\include templates.wsd
class Отчет.ФактическаяСебестоимостьПродукции as "Фактическая себестоимость продукции" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
