@startuml РегламентированноеУведомлениеПостановкаОбъектаНВОС
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеПостановкаОбъектаНВОС as "Регламентированное уведомление постановка объекта НВОС" <<Отчеты>>
{
..Макеты..
Форма2015_1 : ТабличныйДокумент
Печать_MXL_Форма2015_1 : ТабличныйДокумент
ORG_INFO : ТабличныйДокумент
EMISS_OBJECT : ТабличныйДокумент
WATER_OBJECT : ТабличныйДокумент
WASTE_OBJECT : ТабличныйДокумент
EMISS_DEP_OBJECT : ТабличныйДокумент
ОбщиеЭлементы : ТабличныйДокумент
Форматы2016_1 : ТабличныйДокумент
СпискиВыбора2016_1 : ТабличныйДокумент
СхемаВыгрузкиФорма2016_1 : ТабличныйДокумент
}
@enduml
