@startuml ТоварыВЯчейках
'!include templates.wsd
'..\include templates.wsd
class Отчет.ТоварыВЯчейках as "Товары в ячейках" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
