@startuml АнализДоходовРасходов
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализДоходовРасходов as "Доходы и расходы" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
