@startuml ПримененныеСкидкиВДокументе
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПримененныеСкидкиВДокументе as "Примененные скидки в документе" <<Отчеты>>
{
..Макеты..
Макет : ТабличныйДокумент
}
@enduml
