@startuml ОборотноСальдоваяВедомостьБюджетирования
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОборотноСальдоваяВедомостьБюджетирования as "Оборотно-сальдовая ведомость по показателям бюджетов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
ОборотыПлан : СхемаКомпоновкиДанных
РасчетНачальныхОстатков : СхемаКомпоновкиДанных
}
@enduml
