@startuml РезультатыСогласованияПродажи
'!include templates.wsd
'..\include templates.wsd
class Отчет.РезультатыСогласованияПродажи as "Результаты согласования продажи" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
