@startuml ПроблемыПроверкиКонтрагентов
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПроблемыПроверкиКонтрагентов as "Проблемы проверки контрагентов" <<Отчеты>>
{
..Реквизиты..
ВыводитьСправочники : Булево
ВыводитьДокументы : Булево
НачалоПериода : Дата
КонецПериода : Дата
..Макеты..
Макет : ТабличныйДокумент
}
@enduml
