@startuml ТекущиеКвотыАссортимента
'!include templates.wsd
'..\include templates.wsd
class Отчет.ТекущиеКвотыАссортимента as "Квоты ассортимента" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
