@startuml РегламентированныйОтчетСтатистикаФорма1Предприниматель
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма1Предприниматель as "Форма 1-предприниматель «Сведения о деятельности индивидуального предпринимателя  за 2015 год»" <<Отчеты>>
{
..Макеты..
Списки2015Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2015Кв1 : ТабличныйДокумент
ФормаОтчета2015Кв1_ФормаОтчета : ТабличныйДокумент
СоставПоказателей2015Кв1 : ТабличныйДокумент
ПечатныйБланк_2015Кв1_Лист1 : ТабличныйДокумент
ПечатныйБланк_2015Кв1_Лист2 : ТабличныйДокумент
ПечатныйБланк_2015Кв1_Лист3 : ТабличныйДокумент
ПечатныйБланк_2015Кв1_Лист4 : ТабличныйДокумент
ШаблонРосстата2015Кв1 : ДвоичныеДанные
НастройкиЗагрузкиXML2015Кв1 : ТекстовыйДокумент
}
@enduml
