@startuml АнализСуточнойЗагрузки
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализСуточнойЗагрузки as "Анализ суточной загрузки" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
