@startuml РегламентированныйОтчет3НДФЛ
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчет3НДФЛ as "Декларация 3-НДФЛ" <<Отчеты>>
{
..Макеты..
КодыДоходовИВычетов2014кв1 : ТабличныйДокумент
КодыДоходовИВычетов2015кв1 : ТабличныйДокумент
МБ_1151020_5_07000_10_tif : ДвоичныеДанные
МБ_1151020_5_08000_10_tif : ДвоичныеДанные
МБ_1151020_5_08000_11_tif : ДвоичныеДанные
МБ_1151020_5_09000_12_tif : ДвоичныеДанные
МЧБ_2011_01_Титульный : ТабличныйДокумент
МЧБ_2011_02_Титул_002 : ТабличныйДокумент
МЧБ_2011_03_Раздел_1 : ТабличныйДокумент
МЧБ_2011_04_Раздел_2 : ТабличныйДокумент
МЧБ_2011_05_Раздел_3 : ТабличныйДокумент
МЧБ_2011_06_Раздел_4 : ТабличныйДокумент
МЧБ_2011_07_Раздел_5 : ТабличныйДокумент
МЧБ_2011_08_Раздел_6 : ТабличныйДокумент
МЧБ_2011_09_Лист_А : ТабличныйДокумент
МЧБ_2011_10_Лист_Б : ТабличныйДокумент
МЧБ_2011_11_Лист_В : ТабличныйДокумент
МЧБ_2011_12_Лист_Г1 : ТабличныйДокумент
МЧБ_2011_13_Лист_Г2 : ТабличныйДокумент
МЧБ_2011_14_Лист_Д : ТабличныйДокумент
МЧБ_2011_15_Лист_Е : ТабличныйДокумент
МЧБ_2011_16_Лист_Ж1 : ТабличныйДокумент
МЧБ_2011_17_Лист_Ж2 : ТабличныйДокумент
МЧБ_2011_18_Лист_Ж3 : ТабличныйДокумент
МЧБ_2011_21_Лист_З : ТабличныйДокумент
МЧБ_2011_22_Лист_З_Продолжение : ТабличныйДокумент
МЧБ_2011_24_Лист_И : ТабличныйДокумент
МЧБ_2011_27_Лист_Г1_Продолжение : ТабличныйДокумент
МЧБ_2011_28_Лист_Г3 : ТабличныйДокумент
МЧБ_2014_01_Титульный : ТабличныйДокумент
МЧБ_2014_02_Титул_002 : ТабличныйДокумент
МЧБ_2014_03_Раздел_1 : ТабличныйДокумент
МЧБ_2014_04_Раздел_2 : ТабличныйДокумент
МЧБ_2014_05_Раздел_3 : ТабличныйДокумент
МЧБ_2014_06_Раздел_4 : ТабличныйДокумент
МЧБ_2014_07_Раздел_5 : ТабличныйДокумент
МЧБ_2014_08_Раздел_6 : ТабличныйДокумент
МЧБ_2014_09_Лист_А : ТабличныйДокумент
МЧБ_2014_10_Лист_Б : ТабличныйДокумент
МЧБ_2014_11_Лист_В : ТабличныйДокумент
МЧБ_2014_12_Лист_Г1 : ТабличныйДокумент
МЧБ_2014_13_Лист_Г2 : ТабличныйДокумент
МЧБ_2014_14_Лист_Д : ТабличныйДокумент
МЧБ_2014_15_Лист_Е : ТабличныйДокумент
МЧБ_2014_16_Лист_Ж1 : ТабличныйДокумент
МЧБ_2014_17_Лист_Ж2 : ТабличныйДокумент
МЧБ_2014_18_Лист_Ж3 : ТабличныйДокумент
МЧБ_2014_21_Лист_З : ТабличныйДокумент
МЧБ_2014_22_Лист_З_Продолжение : ТабличныйДокумент
МЧБ_2014_24_Лист_И : ТабличныйДокумент
МЧБ_2014_27_Лист_Г1_Продолжение : ТабличныйДокумент
МЧБ_2014_28_Лист_Г3 : ТабличныйДокумент
МЧБ_2015Кв1_01_Титульный : ТабличныйДокумент
МЧБ_2015Кв1_02_Раздел1 : ТабличныйДокумент
МЧБ_2015Кв1_03_Раздел2 : ТабличныйДокумент
МЧБ_2015Кв1_04_ЛистА : ТабличныйДокумент
МЧБ_2015Кв1_05_ЛистБ : ТабличныйДокумент
МЧБ_2015Кв1_06_ЛистВ : ТабличныйДокумент
МЧБ_2015Кв1_07_ЛистГ : ТабличныйДокумент
МЧБ_2015Кв1_08_ЛистД1 : ТабличныйДокумент
МЧБ_2015Кв1_09_ЛистД2 : ТабличныйДокумент
МЧБ_2015Кв1_10_ЛистЕ1 : ТабличныйДокумент
МЧБ_2015Кв1_11_ЛистЕ2 : ТабличныйДокумент
МЧБ_2015Кв1_12_ЛистЖ : ТабличныйДокумент
МЧБ_2015Кв1_13_ЛистЗ : ТабличныйДокумент
МЧБ_2015Кв1_14_ЛистЗПродолжение : ТабличныйДокумент
МЧБ_2015Кв1_15_ЛистЗПродолжение2 : ТабличныйДокумент
МЧБ_2015Кв1_17_ЛистЗПродолжение3 : ТабличныйДокумент
МЧБ_2015Кв1_17_ЛистЗПродолжение4 : ТабличныйДокумент
МЧБ_2015Кв1_18_ЛистИ : ТабличныйДокумент
МЧБ_2015Кв1_19_ЛистИПродолжение : ТабличныйДокумент
СоставПоказателей2011кв1 : ТабличныйДокумент
СоставПоказателей2014кв1 : ТабличныйДокумент
СоставПоказателей2015кв1 : ТабличныйДокумент
Списки2011кв1 : ТабличныйДокумент
Списки2014кв1 : ТабличныйДокумент
Списки2015кв1 : ТабличныйДокумент
СтруктураXML507 : ТабличныйДокумент
СтруктураXML508 : ТабличныйДокумент
СтруктураXML509 : ТабличныйДокумент
ФормаОтчета2011кв1_ЛистА : ТабличныйДокумент
ФормаОтчета2011кв1_ЛистА_Без_Итога : ТабличныйДокумент
ФормаОтчета2011кв1_ЛистБ : ТабличныйДокумент
ФормаОтчета2011кв1_ЛистБ_Без_Итога : ТабличныйДокумент
ФормаОтчета2011кв1_ЛистВ : ТабличныйДокумент
ФормаОтчета2011кв1_ЛистВ_Без_Итога : ТабличныйДокумент
ФормаОтчета2011кв1_ЛистГ1 : ТабличныйДокумент
ФормаОтчета2011кв1_ЛистГ1Продолжение : ТабличныйДокумент
ФормаОтчета2011кв1_ЛистГ2 : ТабличныйДокумент
ФормаОтчета2011кв1_ЛистГ2_Без_Итога : ТабличныйДокумент
ФормаОтчета2011кв1_ЛистГ3 : ТабличныйДокумент
ФормаОтчета2011кв1_ЛистГ3_Без_Итога : ТабличныйДокумент
ФормаОтчета2011кв1_ЛистД : ТабличныйДокумент
ФормаОтчета2011кв1_ЛистЕ : ТабличныйДокумент
ФормаОтчета2011кв1_ЛистЖ1 : ТабличныйДокумент
ФормаОтчета2011кв1_ЛистЖ2 : ТабличныйДокумент
ФормаОтчета2011кв1_ЛистЖ3 : ТабличныйДокумент
ФормаОтчета2011кв1_ЛистЖ3_Без_Итога : ТабличныйДокумент
ФормаОтчета2011кв1_ЛистЗ : ТабличныйДокумент
ФормаОтчета2011кв1_ЛистЗПродолжение : ТабличныйДокумент
ФормаОтчета2011кв1_ЛистИ : ТабличныйДокумент
ФормаОтчета2011кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2011кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2011кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2011кв1_Раздел4 : ТабличныйДокумент
ФормаОтчета2011кв1_Раздел5 : ТабличныйДокумент
ФормаОтчета2011кв1_Раздел6 : ТабличныйДокумент
ФормаОтчета2011кв1_Титульный : ТабличныйДокумент
ФормаОтчета2011кв1_Титульный002 : ТабличныйДокумент
ФормаОтчета2014кв1_ЛистА : ТабличныйДокумент
ФормаОтчета2014кв1_ЛистА_Без_Итога : ТабличныйДокумент
ФормаОтчета2014кв1_ЛистБ : ТабличныйДокумент
ФормаОтчета2014кв1_ЛистБ_Без_Итога : ТабличныйДокумент
ФормаОтчета2014кв1_ЛистВ : ТабличныйДокумент
ФормаОтчета2014кв1_ЛистВ_Без_Итога : ТабличныйДокумент
ФормаОтчета2014кв1_ЛистГ1 : ТабличныйДокумент
ФормаОтчета2014кв1_ЛистГ1Продолжение : ТабличныйДокумент
ФормаОтчета2014кв1_ЛистГ2 : ТабличныйДокумент
ФормаОтчета2014кв1_ЛистГ2_Без_Итога : ТабличныйДокумент
ФормаОтчета2014кв1_ЛистГ3 : ТабличныйДокумент
ФормаОтчета2014кв1_ЛистГ3_Без_Итога : ТабличныйДокумент
ФормаОтчета2014кв1_ЛистД : ТабличныйДокумент
ФормаОтчета2014кв1_ЛистЕ : ТабличныйДокумент
ФормаОтчета2014кв1_ЛистЖ1 : ТабличныйДокумент
ФормаОтчета2014кв1_ЛистЖ2 : ТабличныйДокумент
ФормаОтчета2014кв1_ЛистЖ3 : ТабличныйДокумент
ФормаОтчета2014кв1_ЛистЖ3_Без_Итога : ТабличныйДокумент
ФормаОтчета2014кв1_ЛистЗ : ТабличныйДокумент
ФормаОтчета2014кв1_ЛистЗПродолжение : ТабличныйДокумент
ФормаОтчета2014кв1_ЛистИ : ТабличныйДокумент
ФормаОтчета2014кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2014кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2014кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2014кв1_Раздел4 : ТабличныйДокумент
ФормаОтчета2014кв1_Раздел5 : ТабличныйДокумент
ФормаОтчета2014кв1_Раздел6 : ТабличныйДокумент
ФормаОтчета2014кв1_Титульный : ТабличныйДокумент
ФормаОтчета2014кв1_Титульный002 : ТабличныйДокумент
ФормаОтчета2015кв1_ЛистА : ТабличныйДокумент
ФормаОтчета2015кв1_ЛистБ : ТабличныйДокумент
ФормаОтчета2015кв1_ЛистБ_Без_Итога : ТабличныйДокумент
ФормаОтчета2015кв1_ЛистВ : ТабличныйДокумент
ФормаОтчета2015кв1_ЛистВ_Без_Итога : ТабличныйДокумент
ФормаОтчета2015кв1_ЛистГ : ТабличныйДокумент
ФормаОтчета2015кв1_ЛистД1 : ТабличныйДокумент
ФормаОтчета2015кв1_ЛистД1_Без_Итога : ТабличныйДокумент
ФормаОтчета2015кв1_ЛистД2 : ТабличныйДокумент
ФормаОтчета2015кв1_ЛистЕ1 : ТабличныйДокумент
ФормаОтчета2015кв1_ЛистЕ2 : ТабличныйДокумент
ФормаОтчета2015кв1_ЛистЕ2_Без_Итога : ТабличныйДокумент
ФормаОтчета2015кв1_ЛистЖ : ТабличныйДокумент
ФормаОтчета2015кв1_ЛистЗ : ТабличныйДокумент
ФормаОтчета2015кв1_ЛистЗПродолжение : ТабличныйДокумент
ФормаОтчета2015кв1_ЛистЗПродолжение2 : ТабличныйДокумент
ФормаОтчета2015кв1_ЛистЗПродолжение3 : ТабличныйДокумент
ФормаОтчета2015кв1_ЛистЗПродолжение4 : ТабличныйДокумент
ФормаОтчета2015кв1_ЛистИ : ТабличныйДокумент
ФормаОтчета2015кв1_ЛистИПродолжение : ТабличныйДокумент
ФормаОтчета2015кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2015кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2015кв1_Титульный : ТабличныйДокумент
ФормаОтчета2016Кв1_ЛистА : ТабличныйДокумент
ФормаОтчета2016Кв1_ЛистБ : ТабличныйДокумент
ФормаОтчета2016Кв1_ЛистВ : ТабличныйДокумент
ФормаОтчета2016Кв1_ЛистВ_Без_Итога : ТабличныйДокумент
ФормаОтчета2016Кв1_ЛистГ : ТабличныйДокумент
ФормаОтчета2016Кв1_ЛистД1 : ТабличныйДокумент
ФормаОтчета2016Кв1_ЛистД1_Без_Итога : ТабличныйДокумент
ФормаОтчета2016Кв1_ЛистД2 : ТабличныйДокумент
ФормаОтчета2016Кв1_ЛистЕ1 : ТабличныйДокумент
ФормаОтчета2016Кв1_ЛистЕ2 : ТабличныйДокумент
ФормаОтчета2016Кв1_ЛистЕ2_Без_Итога : ТабличныйДокумент
ФормаОтчета2016Кв1_ЛистЖ : ТабличныйДокумент
ФормаОтчета2016Кв1_ЛистЗ : ТабличныйДокумент
ФормаОтчета2016Кв1_ЛистЗПродолжение : ТабличныйДокумент
ФормаОтчета2016Кв1_ЛистЗПродолжение2 : ТабличныйДокумент
ФормаОтчета2016Кв1_ЛистЗПродолжение3 : ТабличныйДокумент
ФормаОтчета2016Кв1_ЛистЗПродолжение4 : ТабличныйДокумент
ФормаОтчета2016Кв1_ЛистИ : ТабличныйДокумент
ФормаОтчета2016Кв1_ЛистИПродолжение : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2016Кв1_Титульный : ТабличныйДокумент
МЧБ_2016Кв1_01_Титульный : ТабличныйДокумент
МЧБ_2016Кв1_02_Раздел1 : ТабличныйДокумент
МЧБ_2016Кв1_03_Раздел2 : ТабличныйДокумент
МЧБ_2016Кв1_04_ЛистА : ТабличныйДокумент
МЧБ_2016Кв1_05_ЛистБ : ТабличныйДокумент
МЧБ_2016Кв1_06_ЛистВ : ТабличныйДокумент
МЧБ_2016Кв1_07_ЛистГ : ТабличныйДокумент
МЧБ_2016Кв1_08_ЛистД1 : ТабличныйДокумент
МЧБ_2016Кв1_09_ЛистД2 : ТабличныйДокумент
МЧБ_2016Кв1_10_ЛистЕ1 : ТабличныйДокумент
МЧБ_2016Кв1_11_ЛистЕ2 : ТабличныйДокумент
МЧБ_2016Кв1_12_ЛистЖ : ТабличныйДокумент
МЧБ_2016Кв1_13_ЛистЗ : ТабличныйДокумент
МЧБ_2016Кв1_14_ЛистЗПродолжение : ТабличныйДокумент
МЧБ_2016Кв1_15_ЛистЗПродолжение2 : ТабличныйДокумент
МЧБ_2016Кв1_17_ЛистЗПродолжение3 : ТабличныйДокумент
МЧБ_2016Кв1_17_ЛистЗПродолжение4 : ТабличныйДокумент
МЧБ_2016Кв1_18_ЛистИ : ТабличныйДокумент
МЧБ_2016Кв1_19_ЛистИПродолжение : ТабличныйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
Списки2016Кв1 : ТабличныйДокумент
СтруктураXML510 : ТабличныйДокумент
НастройкиЗагрузкиXML2016кв1 : ТекстовыйДокумент
МБ_1151020_5_10000_13_tif : ДвоичныеДанные
ФормаОтчета2017Кв1_ЛистА : ТабличныйДокумент
ФормаОтчета2017Кв1_ЛистБ : ТабличныйДокумент
ФормаОтчета2017Кв1_ЛистВ : ТабличныйДокумент
ФормаОтчета2017Кв1_ЛистВ_Без_Итога : ТабличныйДокумент
ФормаОтчета2017Кв1_ЛистГ : ТабличныйДокумент
ФормаОтчета2017Кв1_ЛистД1 : ТабличныйДокумент
ФормаОтчета2017Кв1_ЛистД1_Без_Итога : ТабличныйДокумент
ФормаОтчета2017Кв1_ЛистД2 : ТабличныйДокумент
ФормаОтчета2017Кв1_ЛистЕ1 : ТабличныйДокумент
ФормаОтчета2017Кв1_ЛистЕ2 : ТабличныйДокумент
ФормаОтчета2017Кв1_ЛистЕ2_Без_Итога : ТабличныйДокумент
ФормаОтчета2017Кв1_ЛистЖ : ТабличныйДокумент
ФормаОтчета2017Кв1_ЛистЗ : ТабличныйДокумент
ФормаОтчета2017Кв1_ЛистЗПродолжение : ТабличныйДокумент
ФормаОтчета2017Кв1_ЛистЗПродолжение2 : ТабличныйДокумент
ФормаОтчета2017Кв1_ЛистЗПродолжение3 : ТабличныйДокумент
ФормаОтчета2017Кв1_ЛистЗПродолжение4 : ТабличныйДокумент
ФормаОтчета2017Кв1_ЛистИ : ТабличныйДокумент
ФормаОтчета2017Кв1_ЛистИПродолжение : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2017Кв1_Титульный : ТабличныйДокумент
МЧБ_2017Кв1_01_Титульный : ТабличныйДокумент
МЧБ_2017Кв1_02_Раздел1 : ТабличныйДокумент
МЧБ_2017Кв1_03_Раздел2 : ТабличныйДокумент
МЧБ_2017Кв1_04_ЛистА : ТабличныйДокумент
МЧБ_2017Кв1_05_ЛистБ : ТабличныйДокумент
МЧБ_2017Кв1_06_ЛистВ : ТабличныйДокумент
МЧБ_2017Кв1_07_ЛистГ : ТабличныйДокумент
МЧБ_2017Кв1_08_ЛистД1 : ТабличныйДокумент
МЧБ_2017Кв1_09_ЛистД2 : ТабличныйДокумент
МЧБ_2017Кв1_10_ЛистЕ1 : ТабличныйДокумент
МЧБ_2017Кв1_11_ЛистЕ2 : ТабличныйДокумент
МЧБ_2017Кв1_12_ЛистЖ : ТабличныйДокумент
МЧБ_2017Кв1_13_ЛистЗ : ТабличныйДокумент
МЧБ_2017Кв1_14_ЛистЗПродолжение : ТабличныйДокумент
МЧБ_2017Кв1_15_ЛистЗПродолжение2 : ТабличныйДокумент
МЧБ_2017Кв1_17_ЛистЗПродолжение3 : ТабличныйДокумент
МЧБ_2017Кв1_17_ЛистЗПродолжение4 : ТабличныйДокумент
МЧБ_2017Кв1_18_ЛистИ : ТабличныйДокумент
МЧБ_2017Кв1_19_ЛистИПродолжение : ТабличныйДокумент
СоставПоказателей2017Кв1 : ТабличныйДокумент
Списки2017Кв1 : ТабличныйДокумент
СтруктураXML511 : ТабличныйДокумент
НастройкиЗагрузкиXML2017кв1 : ТекстовыйДокумент
МБ_1151020_5_11000_15_tif : ДвоичныеДанные
ФормаОтчета2018Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2018Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2018Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2018Кв1_ЛистА : ТабличныйДокумент
ФормаОтчета2018Кв1_ЛистБ : ТабличныйДокумент
ФормаОтчета2018Кв1_ЛистВ : ТабличныйДокумент
ФормаОтчета2018Кв1_ЛистВ_Без_Итога : ТабличныйДокумент
ФормаОтчета2018Кв1_ЛистГ : ТабличныйДокумент
ФормаОтчета2018Кв1_ЛистД1 : ТабличныйДокумент
ФормаОтчета2018Кв1_ЛистД1_Без_Итога : ТабличныйДокумент
ФормаОтчета2018Кв1_ЛистД2 : ТабличныйДокумент
ФормаОтчета2018Кв1_ЛистЕ1 : ТабличныйДокумент
ФормаОтчета2018Кв1_ЛистЕ2 : ТабличныйДокумент
ФормаОтчета2018Кв1_ЛистЕ2_Без_Итога : ТабличныйДокумент
ФормаОтчета2018Кв1_ЛистЖ : ТабличныйДокумент
ФормаОтчета2018Кв1_ЛистЗ : ТабличныйДокумент
ФормаОтчета2018Кв1_ЛистЗПродолжение : ТабличныйДокумент
ФормаОтчета2018Кв1_ЛистЗПродолжение2 : ТабличныйДокумент
ФормаОтчета2018Кв1_ЛистЗПродолжение3 : ТабличныйДокумент
ФормаОтчета2018Кв1_ЛистЗПродолжение4 : ТабличныйДокумент
ФормаОтчета2018Кв1_ЛистИ : ТабличныйДокумент
ФормаОтчета2018Кв1_ЛистИПродолжение : ТабличныйДокумент
ФормаОтчета2018Кв1_РасчетДоходаОтПродажиНедвижимости : ТабличныйДокумент
МЧБ_2018Кв1_Титульный : ТабличныйДокумент
МЧБ_2018Кв1_Раздел1 : ТабличныйДокумент
МЧБ_2018Кв1_Раздел2 : ТабличныйДокумент
МЧБ_2018Кв1_ЛистА : ТабличныйДокумент
МЧБ_2018Кв1_ЛистБ : ТабличныйДокумент
МЧБ_2018Кв1_ЛистВ : ТабличныйДокумент
МЧБ_2018Кв1_ЛистГ : ТабличныйДокумент
МЧБ_2018Кв1_ЛистД1 : ТабличныйДокумент
МЧБ_2018Кв1_ЛистД2 : ТабличныйДокумент
МЧБ_2018Кв1_ЛистЕ1 : ТабличныйДокумент
МЧБ_2018Кв1_ЛистЕ2 : ТабличныйДокумент
МЧБ_2018Кв1_ЛистЖ : ТабличныйДокумент
МЧБ_2018Кв1_ЛистЗ : ТабличныйДокумент
МЧБ_2018Кв1_ЛистЗПродолжение : ТабличныйДокумент
МЧБ_2018Кв1_ЛистЗПродолжение2 : ТабличныйДокумент
МЧБ_2018Кв1_ЛистЗПродолжение3 : ТабличныйДокумент
МЧБ_2018Кв1_ЛистЗПродолжение4 : ТабличныйДокумент
МЧБ_2018Кв1_ЛистИ : ТабличныйДокумент
МЧБ_2018Кв1_ЛистИПродолжение : ТабличныйДокумент
МЧБ_2018Кв1_РасчетДоходаОтПродажиНедвижимости : ТабличныйДокумент
СоставПоказателей2018Кв1 : ТабличныйДокумент
Списки2018Кв1 : ТабличныйДокумент
СтруктураXML512 : ТабличныйДокумент
НастройкиЗагрузкиXML2018кв1 : ТекстовыйДокумент
МБ_1151020_5_12000_16_tif : ДвоичныеДанные
}
@enduml
