@startuml ДебиторскаяЗадолженностьДоляПросрочки
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДебиторскаяЗадолженностьДоляПросрочки as "Дебиторская задолженность - доля просрочки" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
