@startuml ВаловаяПрибыльПоОплаченнымОтгрузкам
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВаловаяПрибыльПоОплаченнымОтгрузкам as "Прибыль по оплате отгрузок" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
