@startuml КарточкаНМАМеждународныйУчет
'!include templates.wsd
'..\include templates.wsd
class Отчет.КарточкаНМАМеждународныйУчет as "Карточка НМА (Международный учет)" <<Отчеты>>
{
..Макеты..
Макет : ТабличныйДокумент
}
@enduml
