@startuml МатериалыВПроизводствеПоСрокамГодности
'!include templates.wsd
'..\include templates.wsd
class Отчет.МатериалыВПроизводствеПоСрокамГодности as "Материалы в производстве по срокам годности" <<Отчеты>>
{
..Макеты..
ЗапросОстатковПоСправочномуУчетуСроковГодности : СхемаКомпоновкиДанных
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
