@startuml РегламентированныйОтчетАлкоЗаявлениеОКорректировке
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетАлкоЗаявлениеОКорректировке as "Заявление о представлении корректирующих алкогольных деклараций" <<Отчеты>>
{
..Макеты..
ПечатнаяФормаОтчета2017Кв3_Титульный : ТабличныйДокумент
}
@enduml
