@startuml ПотребностьВМатериалахПоМоделиГрафикаПроизводства
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПотребностьВМатериалахПоМоделиГрафикаПроизводства as "Потребность в материалах по модели графика производства" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
