@startuml ПлановаяПотребностьВПолуфабрикатах
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПлановаяПотребностьВПолуфабрикатах as "Плановая потребность в полуфабрикатах" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
