@startuml КонтрольПередачиСырьяИМатериаловПереработчику
'!include templates.wsd
'..\include templates.wsd
class Отчет.КонтрольПередачиСырьяИМатериаловПереработчику as "Контроль передачи сырья и материалов переработчику" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
