@startuml ПлановыеИФактическиеНормативыПроизводственныхРасходов
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПлановыеИФактическиеНормативыПроизводственныхРасходов as "Плановые и фактические нормативы производственных расходов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
