@startuml КредиторскаяЗадолженность
'!include templates.wsd
'..\include templates.wsd
class Отчет.КредиторскаяЗадолженность as "Задолженность поставщикам по срокам" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
