@startuml РегламентированныйОтчетРасчетПоСтраховымВзносам
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетРасчетПоСтраховымВзносам as "Расчет по страховым взносам" <<Отчеты>>
{
..Макеты..
МБ_1151111_5_01000_01_tif : ДвоичныеДанные
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
ПечатныйБланк2017Кв1_Раздел1_Лист1 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел1_Лист2 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел1Прил10_Лист1 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел1Прил10_Лист2 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел1Прил1Подр1_1и1_2 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел1Прил1Подр1_3_1 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел1Прил1Подр1_3_2 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел1Прил1Подр1_4 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел1Прил2 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел1Прил3 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел1Прил4 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел1Прил5_6 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел1Прил7 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел1Прил8 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел1Прил9 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел2 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел2Прил1 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел3_Лист1 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел3_Лист2 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Реестр : ТабличныйДокумент
ПечатныйБланк2017Кв1_Титульный : ТабличныйДокумент
ПечатныйБланк2017Кв1_ФизЛицо : ТабличныйДокумент
СпискиВыбора2017Кв1 : ТабличныйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
НастройкиКС2017Кв1 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1Прил1 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1Прил10 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1Прил1Подр1_1и1_2 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1Прил1Подр1_3_1 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1Прил1Подр1_3_2 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1Прил1Подр1_4 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1Прил2 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1Прил3 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1Прил4 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1Прил5_6 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1Прил7 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1Прил8 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1Прил9 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2017Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2017Кв1_ФизЛицо : ТабличныйДокумент
}
@enduml
