@startuml КонтрольПередачТоваровМеждуОрганизациями
'!include templates.wsd
'..\include templates.wsd
class Отчет.КонтрольПередачТоваровМеждуОрганизациями as "Контроль передач и возвратов товаров между организациями" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
