@startuml РегламентированныйОтчетИзвещениеОбУплатеАвансовогоПлатежаАкциза
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетИзвещениеОбУплатеАвансовогоПлатежаАкциза as "Извещение об уплате авансового платежа акциза по алкогольной и (или) спиртосодержащей продукции" <<Отчеты>>
{
..Макеты..
СоставПоказателей2011Кв2 : ТабличныйДокумент
СоставПоказателей2012Кв3 : ТабличныйДокумент
Списки2011Кв2 : ТабличныйДокумент
Списки2012Кв3 : ТабличныйДокумент
СтруктураXML501 : ТабличныйДокумент
СтруктураXML502 : ТабличныйДокумент
ФормаОтчета2011кв2_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2012Кв3_Извещение : ТабличныйДокумент
НастройкиЗагрузкиXML2012Кв3 : ТекстовыйДокумент
}
@enduml
