@startuml РегламентированныйОтчетЕдиныйНалогНаВмененныйДоход
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетЕдиныйНалогНаВмененныйДоход as "Декларация по единому налогу на вмененный доход для отдельных видов деятельности" <<Отчеты>>
{
..Макеты..
МБ_1152016_5_02000_06_tif : ДвоичныеДанные
МБ_1152016_5_03000_07_tif : ДвоичныеДанные
МБ_1152016_5_04000_08_tif : ДвоичныеДанные
МБ_1152016_5_05000_09_tif : ДвоичныеДанные
МБ_1152016_5_06000_10_tif : ДвоичныеДанные
МБ_1152016_5_07000_12_tif : ДвоичныеДанные
МЧБ_2010Кв1_1 : ТабличныйДокумент
МЧБ_2010Кв1_2 : ТабличныйДокумент
МЧБ_2010Кв1_3 : ТабличныйДокумент
МЧБ_2010Кв1_4 : ТабличныйДокумент
МЧБ_2012Кв1_Раздел1 : ТабличныйДокумент
МЧБ_2012Кв1_Раздел2 : ТабличныйДокумент
МЧБ_2012Кв1_Раздел3 : ТабличныйДокумент
МЧБ_2012Кв1_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2015Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
ПечатныйБланк2013Кв4_Раздел1 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Раздел2 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Раздел3 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Титульный : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел1 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел2 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Раздел3 : ТабличныйДокумент
ПечатныйБланк2015Кв1_Титульный : ТабличныйДокумент
ПечатныйБланк2016Кв1_Раздел1 : ТабличныйДокумент
ПечатныйБланк2016Кв1_Раздел2 : ТабличныйДокумент
ПечатныйБланк2016Кв1_Раздел3 : ТабличныйДокумент
ПечатныйБланк2016Кв1_Титульный : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел1 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел2 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Раздел3 : ТабличныйДокумент
ПечатныйБланк2017Кв1_Титульный : ТабличныйДокумент
СоставПоказателей2010Кв1 : ТабличныйДокумент
СоставПоказателей2012Кв1 : ТабличныйДокумент
СоставПоказателей2013Кв4 : ТабличныйДокумент
СоставПоказателей2015Кв1 : ТабличныйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
СоставПоказателей2017Кв1 : ТабличныйДокумент
Списки2010Кв1 : ТабличныйДокумент
Списки2012Кв1 : ТабличныйДокумент
СпискиВыбора2013Кв4 : ТабличныйДокумент
СпискиВыбора2015Кв1 : ТабличныйДокумент
СпискиВыбора2016Кв1 : ТабличныйДокумент
СпискиВыбора2017Кв1 : ТабличныйДокумент
СхемаВыгрузки502 : ТабличныйДокумент
СхемаВыгрузки503 : ТабличныйДокумент
СхемаВыгрузки504 : ТабличныйДокумент
СхемаВыгрузки505 : ТабличныйДокумент
СхемаВыгрузки506 : ТабличныйДокумент
СхемаВыгрузки507 : ТабличныйДокумент
ФормаОтчета2010Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2010Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2010Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2010Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2012Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел2 : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел3 : ТабличныйДокумент
ФормаОтчета2013Кв4_Титульный : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел2_Строка105 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2015Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2016Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2017Кв1_Титульный : ТабличныйДокумент
}
@enduml
