@startuml ПроизводственныеЗатраты
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПроизводственныеЗатраты as "Движение ТМЦ и затрат в производстве" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
