@startuml ОтклоненияОтУсловийПродаж
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОтклоненияОтУсловийПродаж as "Отклонения от условий продаж" <<Отчеты>>
{
..Макеты..
Макет : ТабличныйДокумент
}
@enduml
