@startuml ОстаткиИДоступностьТоваров
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОстаткиИДоступностьТоваров as "Остатки и доступность товаров" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
