@startuml ЖурналФискальныхОпераций
'!include templates.wsd
'..\include templates.wsd
class Отчет.ЖурналФискальныхОпераций as "Журнал фискальных операций" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
