@startuml НаличиеСчетовФактур
'!include templates.wsd
'..\include templates.wsd
class Отчет.НаличиеСчетовФактур as "Наличие счетов-фактур" <<Отчеты>>
{
..Реквизиты..
НачалоПериода : Дата
КонецПериода : Дата
Организация : Справочник.Организация
НаличиеСчетаФактуры : 
ВсеКромеСпискаДокументов : Булево
..Макеты..
НаличиеСчетовФактур : ТабличныйДокумент
}
@enduml
