@startuml ЗаймыСотрудникам
'!include templates.wsd
'..\include templates.wsd
class Отчет.ЗаймыСотрудникам as "Займы сотрудникам" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
