@startuml РегламентированныйОтчетДвижениеСредствПоСчетуВБанкеЗаПределамиРФ
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетДвижениеСредствПоСчетуВБанкеЗаПределамиРФ as "Движение средств по счету в банке за пределами РФ" <<Отчеты>>
{
..Макеты..
ПечатныйБланк2015Кв3_ДвижениеСредств : ТабличныйДокумент
ПечатныйБланк2015Кв3_Справочно : ТабличныйДокумент
ПечатныйБланк2015Кв3_Титульный : ТабличныйДокумент
ФормаОтчета2015Кв3_ДвижениеСредств : ТабличныйДокумент
ФормаОтчета2015Кв3_Титульный : ТабличныйДокумент
}
@enduml
