@startuml СведенияОбИзмененияхДляВоенкомата
'!include templates.wsd
'..\include templates.wsd
class Отчет.СведенияОбИзмененияхДляВоенкомата as "Сведения об изменениях для военкомата" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
ПФ_MXL_СведенияОбИзмененияхДляВоенкомата : ТабличныйДокумент
}
@enduml
