@startuml ТоварыКПоступлению
'!include templates.wsd
'..\include templates.wsd
class Отчет.ТоварыКПоступлению as "Товары к поступлению" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
