@startuml ПрогрессОтложенногоОбновления
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПрогрессОтложенногоОбновления as "Прогресс отложенного обновления" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
