@startuml РегламентированныйОтчетДоходыЗаПределамиРФ
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетДоходыЗаПределамиРФ as "Декларация о доходах, полученных российской организацией от источников за пределами РФ" <<Отчеты>>
{
..Макеты..
МБ_1151024_3_00003_04_tif : ДвоичныеДанные
МБ_1151024_3_00004_05_tif : ДвоичныеДанные
ПечатнаяФормаОтчета2007Кв1_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_ФизЛица : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел1_2 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел2 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел3 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел4 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_ФизЛица : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Раздел1_2 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Раздел2 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Раздел3 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Раздел4 : ТабличныйДокумент
СоставПоказателей2007Кв1 : ТабличныйДокумент
Списки2007Кв1 : ТабличныйДокумент
ФормаОтчета2007Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2007Кв1_ФизЛица : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел1_2 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел4 : ТабличныйДокумент
ФормаОтчета2012Кв3_Титульный : ТабличныйДокумент
ФормаОтчета2012Кв3_ФизЛица : ТабличныйДокумент
ФормаОтчета2012Кв3_Раздел1 : ТабличныйДокумент
ФормаОтчета2012Кв3_Раздел1_2 : ТабличныйДокумент
ФормаОтчета2012Кв3_Раздел2 : ТабличныйДокумент
ФормаОтчета2012Кв3_Раздел3 : ТабличныйДокумент
ФормаОтчета2012Кв3_Раздел4 : ТабличныйДокумент
НастройкиЗагрузкиXML2012Кв3 : ТекстовыйДокумент
}
@enduml
