@startuml РегламентированныйОтчетПодтверждениеВидаДеятельности
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетПодтверждениеВидаДеятельности as "Документы для подтверждения основного вида деятельности страхователя" <<Отчеты>>
{
..Макеты..
ПечатнаяФормаОтчета2013Кв1_Приложение1 : ТабличныйДокумент
ПечатнаяФормаОтчета2013Кв1_Приложение2 : ТабличныйДокумент
ПечатнаяФормаОтчета2013Кв1_Приложение3_1 : ТабличныйДокумент
ПечатнаяФормаОтчета2013Кв1_Приложение3_2 : ТабличныйДокумент
ПечатнаяФормаОтчета2013Кв1_Приложение3_1_ВРедакцииПриказа75н : ТабличныйДокумент
ПечатнаяФормаОтчета2013Кв1_Приложение3_2_ВРедакцииПриказа75н : ТабличныйДокумент
СоставПоказателей2013Кв1 : ТабличныйДокумент
ФормаОтчета2013Кв1_Приложение1 : ТабличныйДокумент
ФормаОтчета2013Кв1_Приложение2 : ТабличныйДокумент
ФормаОтчета2013Кв1_Приложение3 : ТабличныйДокумент
ФормаОтчета2013Кв1_Приложение3_ВРедакцииПриказа75н : ТабличныйДокумент
}
@enduml
