@startuml ЛимитыРасходаДенежныхСредств
'!include templates.wsd
'..\include templates.wsd
class Отчет.ЛимитыРасходаДенежныхСредств as "Лимиты расхода денежных средств" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
