@startuml РегламентированныйОтчетОтходыСубъектовМСП
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетОтходыСубъектовМСП as "Отчет по отходам субъектов МСП" <<Отчеты>>
{
..Макеты..
Списки2011Кв1 : ТабличныйДокумент
СоставПоказателей2011Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2011Кв1 : ТабличныйДокумент
ФормаОтчета2011Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2011Кв1_ОргСвед : ТабличныйДокумент
ФормаОтчета2011Кв1_ОтхСвед : ТабличныйДокумент
НастройкиЗагрузкиXML2011Кв1 : ТекстовыйДокумент
}
@enduml
