@startuml ПроизводственныеЗатратыТМЦ
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПроизводственныеЗатратыТМЦ as "Движение материалов, продукции и работ в производстве" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
