@startuml ДинамикаПлановыхНачислений
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДинамикаПлановыхНачислений as "Динамика плановых начислений" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
