@startuml СоставПродажи
'!include templates.wsd
'..\include templates.wsd
class Отчет.СоставПродажи as "Состав продажи" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
