@startuml РасчетыСКлиентами
'!include templates.wsd
'..\include templates.wsd
class Отчет.РасчетыСКлиентами as "Ведомость расчетов с клиентами" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
