@startuml АнализНачисленийИУдержаний
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализНачисленийИУдержаний as "Анализ начислений и удержаний" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
ПФ_MXL_РасчетныйЛисток : ТабличныйДокумент
ПФ_MXL_ФормаКНД1151087 : ТабличныйДокумент
}
@enduml
