@startuml СправочноеРазмещениеНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Отчет.СправочноеРазмещениеНоменклатуры as "Справочное размещение номенклатуры" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
