@startuml ИсполнениеПланаСборкиРазборки
'!include templates.wsd
'..\include templates.wsd
class Отчет.ИсполнениеПланаСборкиРазборки as "Исполнение плана сборки (разборки)" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
