@startuml ПланФактныйАнализРаботыТорговыхПредставителейПоКоличеству
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПланФактныйАнализРаботыТорговыхПредставителейПоКоличеству as "План-фактный анализ работы торговых представителей" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
