@startuml УнифицированнаяФормаТ13
'!include templates.wsd
'..\include templates.wsd
class Отчет.УнифицированнаяФормаТ13 as "Табель учета рабочего времени (Т-13)" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
