@startuml ИсполнениеСметКонтрактовСЗаказчиками
'!include templates.wsd
'..\include templates.wsd
class Отчет.ИсполнениеСметКонтрактовСЗаказчиками as "Исполнение смет контрактов с заказчиками" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
