@startuml ИсполнениеКонтрактовГОЗ
'!include templates.wsd
'..\include templates.wsd
class Отчет.ИсполнениеКонтрактовГОЗ as "Исполнение контрактов ГОЗ" <<Отчеты>>
{
..Макеты..
ИсполнениеКонтрактов : ТабличныйДокумент
}
@enduml
