@startuml АнализРасходовПриУСН
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализРасходовПриУСН as "Анализ расходов по УСН" <<Отчеты>>
{
..Реквизиты..
НачалоПериода : Дата
КонецПериода : Дата
Организация : Справочник.Организация
..Макеты..
МакетРасшифровкиРасходов : СхемаКомпоновкиДанных
}
@enduml
