@startuml РегламентированныйОтчетПрибыльСколковоРасчетНалоговойБазы
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетПрибыльСколковоРасчетНалоговойБазы as "Расчет налоговой базы по налогу на прибыль участника "Сколково"" <<Отчеты>>
{
..Макеты..
СоставПоказателей2011Кв3 : ТабличныйДокумент
ФормаОтчета2011Кв3_Расчет : ТабличныйДокумент
}
@enduml
