@startuml ОформлениеИзлишковНедостачТоваров
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОформлениеИзлишковНедостачТоваров as "Неоформленные недостачи и излишки товаров" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
