@startuml ПроизводительностьРаботниковСклада
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПроизводительностьРаботниковСклада as "Производительность работников склада" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
