@startuml РегламентированныйОтчетСтатистикаПрочиеФормы
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаПрочиеФормы as "Прочие формы статистической отчетности" <<Отчеты>>
{
..Макеты..
ФормаОтчета : ТабличныйДокумент
ТитульныйПодписи : ТабличныйДокумент
ТабельФормСтатистики : ТабличныйДокумент
}
@enduml
