@startuml РегламентированныйОтчетСтатистикаФормаП1СХ
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФормаП1СХ as "Форма П-1 (СХ) "Сведения о производстве и отгрузке сельскохозяйственной продукции"" <<Отчеты>>
{
..Макеты..
Списки2014Кв1 : ТабличныйДокумент
Списки2015Кв1 : ТабличныйДокумент
Списки2016Кв1 : ТабличныйДокумент
Списки2017Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2014Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2014Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2015Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2016Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1 : ТабличныйДокумент
ФормаОтчета2014Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел1_2 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел3_5 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел5 : ТабличныйДокумент
ФормаОтчета2014Кв1_Подписи : ТабличныйДокумент
ФормаОтчета2015Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел1_2 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел3_5 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел5 : ТабличныйДокумент
ФормаОтчета2015Кв1_Подписи : ТабличныйДокумент
ФормаОтчета2016Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел1_2 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел3_5 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел5 : ТабличныйДокумент
ФормаОтчета2016Кв1_Подписи : ТабличныйДокумент
ФормаОтчета2017Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1_2 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел3_5 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел5 : ТабличныйДокумент
ФормаОтчета2017Кв1_Подписи : ТабличныйДокумент
ШаблонРосстата2016Кв1 : ДвоичныеДанные
ШаблонРосстата2017Кв1 : ДвоичныеДанные
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
}
@enduml
