@startuml РегламентированныйОтчетСтатистикаФормаТОРГм
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФормаТОРГм as "Форма ТОРГ (микро) "Сведения об оборотах розничной торговли и общественного питания микропредприятия"" <<Отчеты>>
{
..Макеты..
СхемаВыгрузкиXML2015Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1 : ТабличныйДокумент
ФормаОтчета2015Кв1_ФормаОтчета : ТабличныйДокумент
СоставПоказателей2015Кв1 : ТабличныйДокумент
ШаблонРосстата2015Кв1 : ДвоичныеДанные
НастройкиЗагрузкиXML2015Кв1 : ТекстовыйДокумент
}
@enduml
