@startuml ОшибкиУточненияСчетов
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОшибкиУточненияСчетов as "Ошибки уточнения счетов (международный учет)" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
