@startuml ФактическиеОтпускаСотрудников
'!include templates.wsd
'..\include templates.wsd
class Отчет.ФактическиеОтпускаСотрудников as "Фактические отпуска сотрудников" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
