@startuml КарточкаСчета
'!include templates.wsd
'..\include templates.wsd
class Отчет.КарточкаСчета as "Карточка счета" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
Счет : Счет бухгалтерского учета
ВключатьОбособленныеПодразделения : Булево
Периодичность : Число 2, 0
ПоказательБУ : Булево
ПоказательПР : Булево
ПоказательНУ : Булево
ПоказательКоличество : Булево
ПоказательВР : Булево
ПоказательВалютнаяСумма : Булево
РежимРасшифровки : Булево
ПоказательУУ : Булево
ПоказательФО : Булево
ПоказательРазницаБУиУУ : Булево
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
СхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
