@startuml РегламентированноеУведомлениеВыплатыПодразделенийФизЛицам
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеВыплатыПодразделенийФизЛицам as "Сообщение о наделении обособленного подразделения полномочиями по начислению выплат и вознаграждений в пользу физлиц." <<Отчеты>>
{
..Макеты..
СхемаВыгрузкиФорма2017_1 : ТабличныйДокумент
TIFF_2017_1 : ДвоичныеДанные
СпискиВыбора2017_1 : ТабличныйДокумент
Печать_Форма2017_Титульный : ТабличныйДокумент
Печать_Форма2017_Подразделение : ТабличныйДокумент
Титульный : ТабличныйДокумент
Подразделение : ТабличныйДокумент
}
@enduml
