@startuml СверкаДанныхОУиБУ
'!include templates.wsd
'..\include templates.wsd
class Отчет.СверкаДанныхОУиБУ as "Сверка данных оперативного и бухгалтерского учета" <<Отчеты>>
{
..Реквизиты..
КлючВарианта : Строка
НачалоПериода : Дата
КонецПериода : Дата
МассивОрганизаций : 
РазделУчета : Число 2, 0
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
