@startuml СверкаРасчетовСПартнерами
'!include templates.wsd
'..\include templates.wsd
class Отчет.СверкаРасчетовСПартнерами as "Сверка расчетов" <<Отчеты>>
{
..Макеты..
ФормированиеСпискаСверокВзаиморасчетов : СхемаКомпоновкиДанных
ВыводРезультата : СхемаКомпоновкиДанных
}
@enduml
