@startuml КарточкаУчетаПоСтраховымВзносам
'!include templates.wsd
'..\include templates.wsd
class Отчет.КарточкаУчетаПоСтраховымВзносам as "Карточка учета страховых взносов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
ПФ_MXL_КарточкаСтраховыхВзносов : ТабличныйДокумент
ПФ_MXL_КарточкаСтраховыхВзносов2012 : ТабличныйДокумент
ПФ_MXL_КарточкаСтраховыхВзносов2013 : ТабличныйДокумент
ПФ_MXL_КарточкаСтраховыхВзносов2014 : ТабличныйДокумент
ПФ_MXL_КарточкаСтраховыхВзносов2015 : ТабличныйДокумент
ПФ_MXL_КарточкаСтраховыхВзносов2017 : ТабличныйДокумент
}
@enduml
