@startuml РасшифровкаСтоимостиПереработки
'!include templates.wsd
'..\include templates.wsd
class Отчет.РасшифровкаСтоимостиПереработки as "Расшифровка стоимости переработки" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
