@startuml РегламентированноеУведомлениеНалоговаяЛьготаРегИнвестПроекты
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеНалоговаяЛьготаРегИнвестПроекты as "Заявление о применении налоговой льготы участниками региональных инвестиционных проектов" <<Отчеты>>
{
..Макеты..
Печать_Форма2017_1_Титульная : ТабличныйДокумент
Печать_Форма2017_1_ДопЛист : ТабличныйДокумент
СхемаВыгрузкиФорма2017_1 : ТабличныйДокумент
СпискиВыбора2017_1 : ТабличныйДокумент
Титульная : ТабличныйДокумент
ДопЛист : ТабличныйДокумент
Регионы : ТабличныйДокумент
ОбщиеЭлементы : ТабличныйДокумент
}
@enduml
