@startuml ФинансовыйАнализ
'!include templates.wsd
'..\include templates.wsd
class Отчет.ФинансовыйАнализ as "Финансовый анализ" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
Период : Дата
..Макеты..
Главное : ТабличныйДокумент
БухгалтерскаяОтчетность : ТабличныйДокумент
БухгалтерскаяОтчетностьПрогноз : ТабличныйДокумент
АнализОтчетности : ТабличныйДокумент
АнализОтчетностиПрогноз : ТабличныйДокумент
Коэффициенты : ТабличныйДокумент
Рентабельность : ТабличныйДокумент
Оценки : ТабличныйДокумент
}
@enduml
