@startuml ТоварыПереданныеПереработчикам
'!include templates.wsd
'..\include templates.wsd
class Отчет.ТоварыПереданныеПереработчикам as "Сырье и материалы, переданные переработчикам" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
