@startuml ЗагрузкаВидовРабочихЦентров
'!include templates.wsd
'..\include templates.wsd
class Отчет.ЗагрузкаВидовРабочихЦентров as "Загрузка видов рабочих центров" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
