@startuml НаградыСотрудников
'!include templates.wsd
'..\include templates.wsd
class Отчет.НаградыСотрудников as "Награды сотрудников" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
