@startuml ПлановаяПотребностьВТрудовыхРесурсах
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПлановаяПотребностьВТрудовыхРесурсах as "Плановая потребность в трудовых ресурсах" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
