@startuml РегламентированныйОтчетСтатистикаФорма11К
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма11К as "Форма 11 (краткая) "Сведения о наличии и движении основных фондов (средств) некоммерческих организаций"" <<Отчеты>>
{
..Макеты..
АтрибВыгрузкиXML2012Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2012Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2013Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2015Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2016Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2018Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2018Кв1 : ТабличныйДокумент
ФормаОтчета2010Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2011Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2012Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2013Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2015Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2015Кв1_Подразделения : ТабличныйДокумент
ФормаОтчета2016Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2016Кв1_Подразделения : ТабличныйДокумент
ФормаОтчета2017Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2017Кв1_Подразделения : ТабличныйДокумент
ФормаОтчета2018Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2018Кв1_Подразделения : ТабличныйДокумент
СоставПоказателей2013Кв1 : ТабличныйДокумент
СоставПоказателей2015Кв1 : ТабличныйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
ШаблонРосстата2016Кв1 : ДвоичныеДанные
ШаблонРосстата2017Кв1 : ДвоичныеДанные
ШаблонРосстата2018Кв1 : ДвоичныеДанные
Списки2016кв1 : ТабличныйДокумент
Списки2017кв1 : ТабличныйДокумент
Списки2018кв1 : ТабличныйДокумент
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2018Кв1 : ТекстовыйДокумент
}
@enduml
