@startuml ДосьеПартнера
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДосьеПартнера as "Досье партнера" <<Отчеты>>
{
..Реквизиты..
Контакты : Булево
ТекущаяАктивность : Булево
ДанныеКлиента : Булево
ДанныеПоставщика : Булево
Классификация : Булево
ЕстьНеактуальныеРасчетыСКлиентами : Булево
ЕстьНеактуальныеРасчетыСПоставщиками : Булево
ВариантКлассификацииЗадолженности : Справочник.Варианты классификации задолженности
..Макеты..
Макет : ТабличныйДокумент
}
@enduml
