@startuml ОстаткиТоваровПереданныхНаКомиссию
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОстаткиТоваровПереданныхНаКомиссию as "Остатки товаров, переданных на комиссию" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
