@startuml ЖурналУчетаТМЦСданныхНаХранение
'!include templates.wsd
'..\include templates.wsd
class Отчет.ЖурналУчетаТМЦСданныхНаХранение as "Журнал учета ТМЦ, сданных на хранение (МХ-2)" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
ДатаНачала : Дата
ДатаОкончания : Дата
..Макеты..
ПФ_MXL_МХ2 : ТабличныйДокумент
}
@enduml
