@startuml АнализЭффективностиРаботыТорговыхПредставителей
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализЭффективностиРаботыТорговыхПредставителей as "Анализ эффективности работы торговых представителей" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
