@startuml АнализПервичногоСпроса
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализПервичногоСпроса as "Первичный спрос" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
