@startuml КарточкаОбъектаЭксплуатации
'!include templates.wsd
'..\include templates.wsd
class Отчет.КарточкаОбъектаЭксплуатации as "Карточка объекта эксплуатации" <<Отчеты>>
{
..Реквизиты..
ПаспортныеХарактеристики : Булево
ПодчиненныеУзлы : Булево
Наработки : Булево
ТекущиеРемонты : Булево
ЗакрытыеРемонты : Булево
ТекущиеДефекты : Булево
ЗакрытыеДефекты : Булево
ОтчетПоУзлам : Булево
..Макеты..
МакетКарточкаОбъектаЭксплуатации : ТабличныйДокумент
}
@enduml
