@startuml РегламентированноеУведомлениеПредоставлениеРассрочки
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеПредоставлениеРассрочки as "Заявление о предоставлении отсрочки (рассрочки) по уплате страховых взносов, пеней и штрафов" <<Отчеты>>
{
..Макеты..
ОбщиеЭлементы : ТабличныйДокумент
Заявление : ТабличныйДокумент
Обязательство : ТабличныйДокумент
График : ТабличныйДокумент
Печать_Форма2017_1_Заявление : ТабличныйДокумент
Печать_Форма2017_1_Обязательство : ТабличныйДокумент
Печать_Форма2017_1_График : ТабличныйДокумент
}
@enduml
