@startuml СравнениеГрафиковКредитовИДепозитов
'!include templates.wsd
'..\include templates.wsd
class Отчет.СравнениеГрафиковКредитовИДепозитов as "Сравнение графиков кредитов (депозитов)" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
