@startuml РегламентированныйОтчетСтатистикаФорма2ДМДавальческоеСырье
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма2ДМДавальческоеСырье as "Форма 2-ДМ (давальческое сырье) "Сведения об остатках, поступлении и расходе драгоценных металлов, полученных для выполнения давальческих заказов"" <<Отчеты>>
{
..Макеты..
ФормаОтчета2012Кв1_ФормаОтчета : ТабличныйДокумент
СоставПоказателей2012Кв1 : ТабличныйДокумент
}
@enduml
