@startuml ДиаграммаПроизводстваПартииЗапуска
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДиаграммаПроизводстваПартииЗапуска as "Диаграмма производства партии запуска" <<Отчеты>>
{
}
@enduml
