@startuml ГрафикОплатНачисленийКредитовИДепозитов
'!include templates.wsd
'..\include templates.wsd
class Отчет.ГрафикОплатНачисленийКредитовИДепозитов as "График оплат и начислений кредитов и депозитов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
