@startuml ДиаграммаПооперационногоРасписания
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДиаграммаПооперационногоРасписания as "Диаграмма пооперационного расписания" <<Отчеты>>
{
}
@enduml
