@startuml АнализРасхожденийПриПоступленииАлкогольнойПродукции
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализРасхожденийПриПоступленииАлкогольнойПродукции as "Расхождения при поступлении ТТН ЕГАИС" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
