@startuml ОшибкиРасчетаКалькуляцииПродукции
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОшибкиРасчетаКалькуляцииПродукции as "Ошибки расчета калькуляции продукции" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
