@startuml ДвижениеМатериаловПолуфабрикатовРаботВПроизводстве
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДвижениеМатериаловПолуфабрикатовРаботВПроизводстве as "Движение материалов, полуфабрикатов, работ в производстве" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
