@startuml АнализСтатейКредитовИДепозитов
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализСтатейКредитовИДепозитов as "Анализ статей кредитных (депозитных) договоров" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
