@startuml РегламентированныйОтчетСтатистикаФормаИЖС
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФормаИЖС as "Форма ИЖС "Сведения о построенных населением жилых домах"" <<Отчеты>>
{
..Макеты..
СхемаВыгрузкиXML2016Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2018Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1_месяц : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1_год : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1_месяц : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1_год : ТабличныйДокумент
АтрибВыгрузкиXML2018Кв1_месяц : ТабличныйДокумент
АтрибВыгрузкиXML2018Кв1_год : ТабличныйДокумент
ФормаОтчета2016Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2017Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2018Кв1_ФормаОтчета : ТабличныйДокумент
ШаблонРосстата2016Кв1_месяц : ДвоичныеДанные
ШаблонРосстата2016Кв1_год : ДвоичныеДанные
ШаблонРосстата2017Кв1_месяц : ДвоичныеДанные
ШаблонРосстата2017Кв1_год : ДвоичныеДанные
ШаблонРосстата2018Кв1_месяц : ДвоичныеДанные
ШаблонРосстата2018Кв1_год : ДвоичныеДанные
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2018Кв1 : ТекстовыйДокумент
}
@enduml
