@startuml ПлановаяПотребностьВВидахРЦ
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПлановаяПотребностьВВидахРЦ as "Плановая потребность в видах РЦ" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
