@startuml АнализЗависимостиОтКлиентовABC
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализЗависимостиОтКлиентовABC as "Зависимость от клиентов (ABC)" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
