@startuml НеобработанныеТТНЕГАИС
'!include templates.wsd
'..\include templates.wsd
class Отчет.НеобработанныеТТНЕГАИС as "Необработанные ТТН ЕГАИС" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
