@startuml РегламентированныйОтчетСтатистикаФорма3Информ
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма3Информ as "Форма 3-информ "Сведения об использовании информационных и коммуникационных технологий и производстве вычислительной техники, программного обеспечения и оказания услуг в этих сферах"" <<Отчеты>>
{
..Макеты..
АтрибВыгрузкиXML2011Кв4 : ТабличныйДокумент
СхемаВыгрузкиXML2011Кв4 : ТабличныйДокумент
АтрибВыгрузкиXML2012Кв4 : ТабличныйДокумент
СхемаВыгрузкиXML2012Кв4 : ТабличныйДокумент
АтрибВыгрузкиXML2013Кв4 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв4 : ТабличныйДокумент
АтрибВыгрузкиXML2014Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2014Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2015Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2016Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
ФормаОтчета2011Кв4_Титульный : ТабличныйДокумент
ФормаОтчета2011Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2011Кв4_Раздел2 : ТабличныйДокумент
ФормаОтчета2012Кв4_Титульный : ТабличныйДокумент
ФормаОтчета2012Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2012Кв4_Раздел2 : ТабличныйДокумент
ФормаОтчета2013Кв4_Титульный : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел2 : ТабличныйДокумент
ФормаОтчета2014Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2015Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2016Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2017Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел2 : ТабличныйДокумент
ШаблонРосстата2015Кв1 : ДвоичныеДанные
ШаблонРосстата2016Кв1 : ДвоичныеДанные
ШаблонРосстата2017Кв1 : ДвоичныеДанные
НастройкиЗагрузкиXML2015Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
}
@enduml
