@startuml РегламентированныйОтчетРеестрНДСПриложение8
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетРеестрНДСПриложение8 as "Реестр по НДС: Приложение 08" <<Отчеты>>
{
..Макеты..
СпискиВыбора2015Кв4 : ТабличныйДокумент
СхемаВыгрузки501_1 : ТабличныйДокумент
СхемаВыгрузки501_2 : ТабличныйДокумент
ФормаОтчета2015Кв4_Реестр : ТабличныйДокумент
ФормаОтчета2015Кв4_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2015Кв4 : ТекстовыйДокумент
}
@enduml
