@startuml РегламентированныйОтчетАкцизыТабак
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетАкцизыТабак as "Декларация по акцизам на табачные изделия" <<Отчеты>>
{
..Макеты..
МБ_1151074_3_00004_05_tif : ДвоичныеДанные
МБ_1151074_3_00005_06_tif : ДвоичныеДанные
МБ_1151074_3_00006_07_tif : ДвоичныеДанные
МБ_1151074_3_00007_08_tif : ДвоичныеДанные
ПечатнаяФормаОтчета2007Кв1_Приложение1 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Приложение2 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Приложение3 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Приложение4 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Приложение5 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Приложение6 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел2 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел3 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел4 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Титульный : ТабличныйДокумент
СоставПоказателей2007Кв1 : ТабличныйДокумент
Списки2007Кв1 : ТабличныйДокумент
ФормаОтчета2007Кв1_Приложение1 : ТабличныйДокумент
ФормаОтчета2007Кв1_Приложение2 : ТабличныйДокумент
ФормаОтчета2007Кв1_Приложение3 : ТабличныйДокумент
ФормаОтчета2007Кв1_Приложение4 : ТабличныйДокумент
ФормаОтчета2007Кв1_Приложение5 : ТабличныйДокумент
ФормаОтчета2007Кв1_Приложение6 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел4 : ТабличныйДокумент
ФормаОтчета2007Кв1_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2007Кв1 : ТекстовыйДокумент
}
@enduml
