@startuml РегламентированныйОтчетСтатистикаФормаПМПром
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФормаПМПром as "Форма ПМ-пром "Сведения о производстве продукции малым предприятием"" <<Отчеты>>
{
..Макеты..
Списки2013кв1 : ТабличныйДокумент
Списки2014кв1 : ТабличныйДокумент
Списки2015кв1 : ТабличныйДокумент
Списки2016кв1 : ТабличныйДокумент
Списки2017кв1 : ТабличныйДокумент
Списки2018кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2013Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2014Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2018Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
КонтрольныеСоотношения2013Кв1 : ТабличныйДокумент
КонтрольныеСоотношения2014Кв1 : ТабличныйДокумент
КонтрольныеСоотношения2015Кв1 : ТабличныйДокумент
КонтрольныеСоотношения2016Кв1 : ТабличныйДокумент
ФормаОтчета2013Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2013Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2014Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2015Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2016Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2017Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2017Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2018Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2018Кв1_Раздел1 : ТабличныйДокумент
ШаблонРосстата2016Кв1 : ДвоичныеДанные
ШаблонРосстата2017Кв1 : ДвоичныеДанные
ШаблонРосстата2018Кв1 : ДвоичныеДанные
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2018Кв1 : ТекстовыйДокумент
СоставПоказателей2018Кв1 : ТабличныйДокумент
}
@enduml
