@startuml ТоварыСхемыОбеспечения
'!include templates.wsd
'..\include templates.wsd
class Отчет.ТоварыСхемыОбеспечения as "Товары схемы обеспечения" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
