@startuml ОтклоненияОтУсловийЗакупок
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОтклоненияОтУсловийЗакупок as "Отклонения от условий закупок" <<Отчеты>>
{
..Макеты..
Макет : ТабличныйДокумент
}
@enduml
