@startuml ОшибкиНастройкиШаблоновПроводок
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОшибкиНастройкиШаблоновПроводок as "Ошибки настройки шаблонов проводок (международный учет)" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
