@startuml РегламентированныйОтчетСтатистикаФормаТЗВМП
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФормаТЗВМП as "Форма ТЗВ-МП "Сведения о расходах на производство и продажу продукции (товаров, работ и услуг) и результатах деятельности малого предприятия"" <<Отчеты>>
{
..Макеты..
ФормаОтчета2016Кв1_ФормаОтчета : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2016Кв1 : ТабличныйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
ШаблонРосстата2016Кв1 : ДвоичныеДанные
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
}
@enduml
