@startuml РегламентированныйОтчетСтатистикаФорма11ТЭР
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма11ТЭР as "Форма 11-ТЭР "Сведения об использовании топлива, теплоэнергии и электроэнергии на производство отдельных видов продукции, работ (услуг)"" <<Отчеты>>
{
..Макеты..
Списки2013Кв1 : ТабличныйДокумент
Списки2014Кв1 : ТабличныйДокумент
Списки2015Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2013Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2014Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2014Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2015Кв1 : ТабличныйДокумент
ФормаОтчета2013Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2014Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2015Кв1_ФормаОтчета : ТабличныйДокумент
НастройкиЗагрузкиXML2014Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2015Кв1 : ТекстовыйДокумент
}
@enduml
