@startuml ШахматнаяВедомость
'!include templates.wsd
'..\include templates.wsd
class Отчет.ШахматнаяВедомость as "Шахматная ведомость" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
ВключатьОбособленныеПодразделения : Булево
ПоказательБУ : Булево
ПоказательВалютнаяСумма : Булево
РежимРасшифровки : Булево
ПоСубсчетам : Булево
ВыводитьЗабалансовыеСчета : Булево
ПоказательУУ : Булево
ПоказательФО : Булево
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
СхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
