@startuml ТрудоваяДеятельностьСотрудников
'!include templates.wsd
'..\include templates.wsd
class Отчет.ТрудоваяДеятельностьСотрудников as "Трудовая деятельность сотрудников" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
