@startuml ОборачиваемостьЗапасов
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОборачиваемостьЗапасов as "Оборачиваемость запасов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
СхемаКомпоновкиДанныхТаблица : СхемаКомпоновкиДанных
}
@enduml
