@startuml СравнениеКалькуляцииИРесурснойСпецификации
'!include templates.wsd
'..\include templates.wsd
class Отчет.СравнениеКалькуляцииИРесурснойСпецификации as "Сравнение калькуляции и ресурсной спецификации" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
