@startuml РегламентированныйОтчетСтатистикаФорма2Приватизация
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма2Приватизация as "Форма 2-приватизация "Сведения о приватизации имущественного комплекса государственного или муниципального унитарного предприятия"" <<Отчеты>>
{
..Макеты..
АтрибВыгрузкиXML2013Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2015Кв1 : ТабличныйДокумент
ФормаОтчета2013Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2015Кв1_ФормаОтчета : ТабличныйДокумент
ШаблонРосстата2015Кв1 : ДвоичныеДанные
НастройкиЗагрузкиXML2013Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2015Кв1 : ТекстовыйДокумент
}
@enduml
