@startuml КонтрольВыданныхПодотчетномуЛицуАвансовПоЗаявке
'!include templates.wsd
'..\include templates.wsd
class Отчет.КонтрольВыданныхПодотчетномуЛицуАвансовПоЗаявке as "Контроль выданных подотчетному лицу авансов по заявке" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
