@startuml ДатыЗапретаЗагрузки
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДатыЗапретаЗагрузки as "Даты запрета загрузки" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
