@startuml РеестрДокументовПодтверждающихНалоговуюЛьготуПоНДС
'!include templates.wsd
'..\include templates.wsd
class Отчет.РеестрДокументовПодтверждающихНалоговуюЛьготуПоНДС as "Реестр к разделу 7 декларации" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
..Макеты..
РеестрПодтверждающихДокументов : ТабличныйДокумент
}
@enduml
