@startuml ГлавнаяКнига
'!include templates.wsd
'..\include templates.wsd
class Отчет.ГлавнаяКнига as "Главная книга" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
ВыводитьРазвернутоеСальдо : Булево
РазбитьПоЛистам : Булево
ПоСубсчетамКорСчетов : Булево
ПоСубсчетам : Булево
НачалоПериода : Дата
КонецПериода : Дата
ВключатьОбособленныеПодразделения : Булево
Периодичность : Число 2, 0
..Макеты..
ГлавнаяКнига : ТабличныйДокумент
}
@enduml
