@startuml КонтролируемыеСделкиДляВключенияВУведомление
'!include templates.wsd
'..\include templates.wsd
class Отчет.КонтролируемыеСделкиДляВключенияВУведомление as "Контролируемые сделки для включения в уведомление" <<Отчеты>>
{
..Реквизиты..
Уведомление : Документ.Уведомление о контролируемых сделках
ОтчетныйГод : Число 4, 0
Организация : Справочник.Организация
РазмещениеДополнительныхПолей : Число 1, 0
КонецПериода : Дата
НачалоПериода : Дата
РежимРасшифровки : Булево
ВключатьОбособленныеПодразделения : Булево
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
