@startuml ИнвентарнаяКнигаОС
'!include templates.wsd
'..\include templates.wsd
class Отчет.ИнвентарнаяКнигаОС as "Инвентарная книга ОС (ОС-6б)" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
Ответственный : Справочник.Физическое лицо
Подразделение : Справочник.Подразделение
МОЛ : Справочник.Физическое лицо
СписокСформированныхЛистов : Список значений
..Макеты..
Обложка : ТабличныйДокумент
Страницы : ТабличныйДокумент
}
@enduml
