@startuml РегламентированноеУведомлениеФормаР21001
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеФормаР21001 as "Заявление о регистрации ИП" <<Отчеты>>
{
..Макеты..
TIFF_2014_1 : ДвоичныеДанные
Печать_Форма2014_1_Страница1 : ТабличныйДокумент
Печать_Форма2014_1_Страница2 : ТабличныйДокумент
Печать_Форма2014_1_Страница3 : ТабличныйДокумент
Печать_Форма2014_1_Страница4 : ТабличныйДокумент
Печать_Форма2014_1_Страница5 : ТабличныйДокумент
СпискиВыбора2014_1 : ТабличныйДокумент
СхемаВыгрузкиФорма2014_1 : ТабличныйДокумент
Форма2014_1_Страница1 : ТабличныйДокумент
Форма2014_1_Страница2 : ТабличныйДокумент
Форма2014_1_Страница3 : ТабличныйДокумент
Форма2014_1_Страница4 : ТабличныйДокумент
Форма2014_1_Страница5 : ТабличныйДокумент
}
@enduml
