@startuml ИспользованиеСчетовИСубконтоМеждународныйУчет
'!include templates.wsd
'..\include templates.wsd
class Отчет.ИспользованиеСчетовИСубконтоМеждународныйУчет as "Использование счетов и субконто в настройках" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
ПоказателиОтчетов : СхемаКомпоновкиДанных
}
@enduml
