@startuml ДиаграммаПооперационногоРасписания2_2
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДиаграммаПооперационногоРасписания2_2 as "Диаграмма пооперационного расписания" <<Отчеты>>
{
}
@enduml
