@startuml ИмпортныеТоварыКОформлению
'!include templates.wsd
'..\include templates.wsd
class Отчет.ИмпортныеТоварыКОформлению as "Импортные товары к оформлению" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
