@startuml СостояниеРасчетовСКомиссионерами
'!include templates.wsd
'..\include templates.wsd
class Отчет.СостояниеРасчетовСКомиссионерами as "Состояние расчетов с комиссионерами" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
