@startuml РегламентированныйОтчетЗаявлениеОВвозеТоваров
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетЗаявлениеОВвозеТоваров as "Заявление о ввозе товаров и уплате косвенных налогов" <<Отчеты>>
{
..Макеты..
ПечатнаяФормаОтчета2012Кв3_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2015Кв1_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2015Кв1_Раздел3 : ТабличныйДокумент
СоставПоказателей2007Кв1 : ТабличныйДокумент
Списки2011Кв2 : ТабличныйДокумент
Списки2012Кв1 : ТабличныйДокумент
СпискиВыбора2015Кв1 : ТабличныйДокумент
СтруктураXML503 : ТабличныйДокумент
СтруктураXML504 : ТабличныйДокумент
СтруктураXML505 : ТабличныйДокумент
СтруктураXML506 : ТабличныйДокумент
СхемаВыгрузки507 : ТабличныйДокумент
ФормаОтчета2011кв3_Зачет : ТабличныйДокумент
ФормаОтчета2011кв3_Приложение : ТабличныйДокумент
ФормаОтчета2011кв3_Раздел1 : ТабличныйДокумент
ФормаОтчета2011кв3_Раздел2 : ТабличныйДокумент
ФормаОтчета2011кв3_Раздел3 : ТабличныйДокумент
ФормаОтчета2011кв3_Сведения : ТабличныйДокумент
ФормаОтчета2012кв1_Зачет : ТабличныйДокумент
ФормаОтчета2012кв1_Приложение : ТабличныйДокумент
ФормаОтчета2012кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2012кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2012кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2012кв1_Сведения : ТабличныйДокумент
ФормаОтчета2012кв2_Зачет : ТабличныйДокумент
ФормаОтчета2012кв2_Приложение : ТабличныйДокумент
ФормаОтчета2012кв2_Раздел1 : ТабличныйДокумент
ФормаОтчета2012кв2_Раздел2 : ТабличныйДокумент
ФормаОтчета2012кв2_Раздел3 : ТабличныйДокумент
ФормаОтчета2012кв2_Сведения : ТабличныйДокумент
ФормаОтчета2012кв3_Зачет : ТабличныйДокумент
ФормаОтчета2012кв3_Приложение : ТабличныйДокумент
ФормаОтчета2012кв3_Раздел1 : ТабличныйДокумент
ФормаОтчета2012кв3_Раздел2 : ТабличныйДокумент
ФормаОтчета2012кв3_Раздел3 : ТабличныйДокумент
ФормаОтчета2012кв3_Сведения : ТабличныйДокумент
ФормаОтчета2012кв4_Зачет : ТабличныйДокумент
ФормаОтчета2012кв4_Приложение : ТабличныйДокумент
ФормаОтчета2012кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2012кв4_Раздел2 : ТабличныйДокумент
ФормаОтчета2012кв4_Раздел3 : ТабличныйДокумент
ФормаОтчета2012кв4_Сведения : ТабличныйДокумент
ФормаОтчета2015кв1_Приложение : ТабличныйДокумент
ФормаОтчета2015кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2015кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2015кв1_Раздел3 : ТабличныйДокумент
НастройкиЗагрузкиXML2015кв1 : ТекстовыйДокумент
}
@enduml
