@startuml РегламентированныйОтчетРозничныеЦеныНаТабак
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетРозничныеЦеныНаТабак as "Уведомление о розничных ценах на табачные изделия" <<Отчеты>>
{
..Макеты..
МБ_1111056_5_01000_01_tif : ДвоичныеДанные
ПечатныйБланк2014Кв1_Сведения : ТабличныйДокумент
ПечатныйБланк2014Кв1_Титульный : ТабличныйДокумент
ПечатныйБланк2014Кв3_Сведения : ТабличныйДокумент
ПечатныйБланк2014Кв3_Титульный : ТабличныйДокумент
СоставПоказателей2014Кв1 : ТабличныйДокумент
СоставПоказателей2014Кв3 : ТабличныйДокумент
СпискиВыбора2014Кв1 : ТабличныйДокумент
СпискиВыбора2014Кв3 : ТабличныйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
ФормаОтчета2014Кв1_Сведения : ТабличныйДокумент
ФормаОтчета2014Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2014Кв3_Сведения : ТабличныйДокумент
ФормаОтчета2014Кв3_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2014Кв3 : ТекстовыйДокумент
}
@enduml
