@startuml ОбработанныеЧекиЕГАИС
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОбработанныеЧекиЕГАИС as "Обработанные чеки ЕГАИС" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
