@startuml КнигаУчетаДоходовИРасходов
'!include templates.wsd
'..\include templates.wsd
class Отчет.КнигаУчетаДоходовИРасходов as "Книга доходов и расходов УСН" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
СписокСформированныхЛистов : Список значений
CНачалаГода : Булево
Период : Дата
ВыводитьРасшифровки : Булево
РежимПечатиНДС : Число 1, 0
РежимПечатиГраф4и6 : Число 1, 0
УСН : Системы налогообложения
ОбъектНалогообложенияУСН : Объекты налогообложения по УСН
..Макеты..
Раздел1 : ТабличныйДокумент
Раздел2 : ТабличныйДокумент
Раздел3 : ТабличныйДокумент
ТитульныйЛист : ТабличныйДокумент
ТитульныйЛист_167н : ТабличныйДокумент
Раздел2_167н : ТабличныйДокумент
Раздел3_167н : ТабличныйДокумент
ТитульныйЛист_154н : ТабличныйДокумент
Раздел2_154н : ТабличныйДокумент
Раздел3_154н : ТабличныйДокумент
ТитульныйЛист_135н : ТабличныйДокумент
Раздел2_135н : ТабличныйДокумент
Раздел3_135н : ТабличныйДокумент
Раздел4 : ТабличныйДокумент
}
@enduml
