@startuml ВыполнениеЗадачБюджетногоПроцесса
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВыполнениеЗадачБюджетногоПроцесса as "Выполнение задач бюджетного процесса" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
