@startuml КонтрольОперацийСДенежнымиСредствами
'!include templates.wsd
'..\include templates.wsd
class Отчет.КонтрольОперацийСДенежнымиСредствами as "Контроль операций с денежными средствами" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
