@startuml РегламентированныйОтчетАлкоПриложение4
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетАлкоПриложение4 as "Декларация об объеме использования алкогольной и спиртосодержащей продукции" <<Отчеты>>
{
..Макеты..
ПечатнаяФормаОтчета2009Кв4_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2009Кв4_ФизЛица : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Лицензии : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Титульный_20140101 : ТабличныйДокумент
СоставПоказателей2006Кв3 : ТабличныйДокумент
СоставПоказателей2012Кв3 : ТабличныйДокумент
Списки2006Кв1 : ТабличныйДокумент
Списки2012Кв3 : ТабличныйДокумент
Списки2012Кв3_20120726 : ТабличныйДокумент
Списки2012Кв3_20131101 : ТабличныйДокумент
Списки2015Кв3 : ТабличныйДокумент
СхемаВыгрузки401 : ТабличныйДокумент
СхемаВыгрузки420 : ТабличныйДокумент
СхемаВыгрузки430 : ТабличныйДокумент
ФормаОтчета2009Кв4_Декларация : ТабличныйДокумент
ФормаОтчета2009Кв4_Титульный : ТабличныйДокумент
ФормаОтчета2009Кв4_ФизЛица : ТабличныйДокумент
ФормаОтчета2012Кв3_Декларация : ТабличныйДокумент
ФормаОтчета2012Кв3_Лицензии : ТабличныйДокумент
ФормаОтчета2012Кв3_Титульный : ТабличныйДокумент
ФормаОтчета2012Кв3_Титульный_20140101 : ТабличныйДокумент
СхемаВыгрузки431 : ТабличныйДокумент
НастройкиЗагрузкиXML2012Кв3 : ТекстовыйДокумент
}
@enduml
