@startuml РегламентированноеУведомлениеТС2
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеТС2 as "Регламентированное уведомление ТС-2" <<Отчеты>>
{
..Макеты..
Форма2015_1 : ТабличныйДокумент
ПараметрыФорма2015_1 : ТабличныйДокумент
СхемаВыгрузкиФорма2015_1 : ТабличныйДокумент
Печать_MXL_Форма2015_1 : ТабличныйДокумент
TIFF_2015_1 : ДвоичныеДанные
}
@enduml
