@startuml РегламентированныйОтчетСтатистикаФорма3Приватизация
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма3Приватизация as "Форма 3-приватизация "Сведения о средствах от приватизации государственного и муниципального имущества"" <<Отчеты>>
{
..Макеты..
АтрибВыгрузкиXML2013Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2015Кв1 : ТабличныйДокумент
ФормаОтчета2013Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2015Кв1_ФормаОтчета : ТабличныйДокумент
ШаблонРосстата2015Кв1 : ДвоичныеДанные
НастройкиЗагрузкиXML2015Кв1 : ТекстовыйДокумент
}
@enduml
