@startuml ОбразованияСотрудников
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОбразованияСотрудников as "Образования сотрудников" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
