@startuml ДвижениеСерииНоменклатуры
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДвижениеСерииНоменклатуры as "Движение серии номенклатуры" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
