@startuml ПлановыеУдержанияСотрудников
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПлановыеУдержанияСотрудников as "Плановые удержания сотрудников" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
