@startuml ОформлениеОтчетовКомитенту
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОформлениеОтчетовКомитенту as "Оформление отчетов комитенту" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
