@startuml АнализПлановыхНачислений
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализПлановыхНачислений as "Анализ плановых начислений" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
