@startuml РегистрИнформацииОбОбъектеОС
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегистрИнформацииОбОбъектеОС as "Регистр информации об объекте ОС" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
ВключатьОбособленныеПодразделения : Булево
ПоказательБУ : Булево
ПоказательНУ : Булево
ПоказательПР : Булево
ПоказательВР : Булево
РежимРасшифровки : Булево
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
РегистрИнформацииОбОбъектеОС : ТабличныйДокумент
}
@enduml
