@startuml ОтчетПоНекорректнымКонтрагентам
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОтчетПоНекорректнымКонтрагентам as "Отчет по некорректным контрагентам" <<Отчеты>>
{
..Макеты..
Макет : ТабличныйДокумент
}
@enduml
