@startuml ВыпускПродукции
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВыпускПродукции as "Выпуск продукции" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
