@startuml СверкаОборотовМУиБУ
'!include templates.wsd
'..\include templates.wsd
class Отчет.СверкаОборотовМУиБУ as "Сверка оборотов международного и регл. учетов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
