@startuml МатериалыВЭксплуатации
'!include templates.wsd
'..\include templates.wsd
class Отчет.МатериалыВЭксплуатации as "ТМЦ в эксплуатации" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
