@startuml СбалансированностьПлановУП
'!include templates.wsd
'..\include templates.wsd
class Отчет.СбалансированностьПлановУП as "Сбалансированность планов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
