@startuml ДвиженияДокумента
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДвиженияДокумента as "Движения документа" <<Отчеты>>
{
..Макеты..
ПустаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
Заголовок : ТабличныйДокумент
}
@enduml
