@startuml ЗаблокированныеЯчейки
'!include templates.wsd
'..\include templates.wsd
class Отчет.ЗаблокированныеЯчейки as "Отчет по заблокированным ячейкам" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
