@startuml ПлановаяПотребностьВМатериалах
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПлановаяПотребностьВМатериалах as "Плановая потребность в материалах" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
