@startuml РегламентированныйОтчетАкцизыГСМ
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетАкцизыГСМ as "Декларация по акцизам на ГСМ, природный газ, автомобили и мотоциклы" <<Отчеты>>
{
..Макеты..
МБ_1151089_5_01000_01_tif : ДвоичныеДанные
ПечатныйБланк2016Кв2_Приложение1 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Приложение21 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Приложение22 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Приложение3 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Приложение4 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Раздел1 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Раздел2 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Раздел3 : ТабличныйДокумент
ПечатныйБланк2016Кв2_Титульный : ТабличныйДокумент
СоставПоказателей2016Кв2 : ТабличныйДокумент
СпискиВыбора2016Кв2 : ТабличныйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
ФормаОтчета2016Кв2_Приложение1 : ТабличныйДокумент
ФормаОтчета2016Кв2_Приложение21 : ТабличныйДокумент
ФормаОтчета2016Кв2_Приложение22 : ТабличныйДокумент
ФормаОтчета2016Кв2_Приложение3 : ТабличныйДокумент
ФормаОтчета2016Кв2_Приложение4 : ТабличныйДокумент
ФормаОтчета2016Кв2_Раздел1 : ТабличныйДокумент
ФормаОтчета2016Кв2_Раздел2 : ТабличныйДокумент
ФормаОтчета2016Кв2_Раздел3 : ТабличныйДокумент
ФормаОтчета2016Кв2_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2016Кв2 : ТекстовыйДокумент
}
@enduml
