@startuml РегламентированныйОтчетСтатистикаФорма1ТГМС
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма1ТГМС as "Форма 1-Т (ГМС) "Сведения о численности и оплате труда работников государственных органов и органов местного самоуправления по категориям персонала"" <<Отчеты>>
{
..Макеты..
АтрибВыгрузкиXML2013Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2015Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1_фед : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1_рег : ТабличныйДокумент
СхемаВыгрузкиXML2016Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1_фед : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1_рег : ТабличныйДокумент
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2018Кв1_фед : ТабличныйДокумент
АтрибВыгрузкиXML2018Кв1_рег : ТабличныйДокумент
СхемаВыгрузкиXML2018Кв1 : ТабличныйДокумент
ФормаОтчета2013Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2015Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2016Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2017Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2018Кв1_ФормаОтчета : ТабличныйДокумент
ШаблонРосстата2016Кв1_фед : ДвоичныеДанные
ШаблонРосстата2016Кв1_рег : ДвоичныеДанные
ШаблонРосстата2017Кв1_фед : ДвоичныеДанные
ШаблонРосстата2017Кв1_рег : ДвоичныеДанные
ШаблонРосстата2018Кв1_фед : ДвоичныеДанные
ШаблонРосстата2018Кв1_рег : ДвоичныеДанные
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2018Кв1 : ТекстовыйДокумент
СоставПоказателей2017Кв1 : ТабличныйДокумент
СоставПоказателей2018Кв1 : ТабличныйДокумент
}
@enduml
