@startuml РегламентированныйОтчетАкцизыПриложение5
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетАкцизыПриложение5 as "Декларация по акцизам на нефтепродукты" <<Отчеты>>
{
..Макеты..
ПечатнаяФормаОтчета2006Кв1_Приложение1 : ТабличныйДокумент
ПечатнаяФормаОтчета2006Кв1_Приложение2 : ТабличныйДокумент
ПечатнаяФормаОтчета2006Кв1_Приложение3 : ТабличныйДокумент
ПечатнаяФормаОтчета2006Кв1_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2006Кв1_Раздел21 : ТабличныйДокумент
ПечатнаяФормаОтчета2006Кв1_Раздел22 : ТабличныйДокумент
ПечатнаяФормаОтчета2006Кв1_Раздел23 : ТабличныйДокумент
ПечатнаяФормаОтчета2006Кв1_Титульный : ТабличныйДокумент
СоставПоказателей2006Кв1 : ТабличныйДокумент
Списки2006Кв1 : ТабличныйДокумент
ФормаОтчета2006Кв1_Приложение1 : ТабличныйДокумент
ФормаОтчета2006Кв1_Приложение2 : ТабличныйДокумент
ФормаОтчета2006Кв1_Приложение3 : ТабличныйДокумент
ФормаОтчета2006Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2006Кв1_Раздел21 : ТабличныйДокумент
ФормаОтчета2006Кв1_Раздел22 : ТабличныйДокумент
ФормаОтчета2006Кв1_Раздел23 : ТабличныйДокумент
ФормаОтчета2006Кв1_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2006Кв1 : ТекстовыйДокумент
}
@enduml
