@startuml ТоварыПереданныеНаКомиссию
'!include templates.wsd
'..\include templates.wsd
class Отчет.ТоварыПереданныеНаКомиссию as "Товары, переданные на комиссию" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
