@startuml ПродажиМеждуОрганизациями
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПродажиМеждуОрганизациями as "Продажи между организациями" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
