@startuml ЛимитыРасходаДенежныхСредствПоДаннымБюджетирования
'!include templates.wsd
'..\include templates.wsd
class Отчет.ЛимитыРасходаДенежныхСредствПоДаннымБюджетирования as "Лимиты расхода денежных средств по данным бюджетирования" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
