@startuml АнализВерсийОбъектов
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализВерсийОбъектов as "Анализ версий объектов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
