@startuml АнализЛояльностиКлиентовXYZ
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализЛояльностиКлиентовXYZ as "Лояльность клиентов (XYZ)" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
