@startuml РегистрНалоговогоУчетаФинРезультатовОтРеализацииАмортизируемогоИмущества
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегистрНалоговогоУчетаФинРезультатовОтРеализацииАмортизируемогоИмущества as "Регистр налогового учета финансовых результатов от реализации амортизируемого имущества" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
Подразделение : Справочник.Подразделение
ВключатьОбособленныеПодразделения : Булево
РежимРасшифровки : Булево
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
