@startuml РегламентированныйОтчетСтатистикаФормаП1
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФормаП1 as "Форма П-1 "Сведения о производстве и отгрузке товаров и услуг"" <<Отчеты>>
{
..Макеты..
Списки2010Кв1 : ТабличныйДокумент
Списки2012Кв1 : ТабличныйДокумент
Списки2014Кв1 : ТабличныйДокумент
Списки2015Кв1 : ТабличныйДокумент
Списки2016Кв1 : ТабличныйДокумент
Списки2017Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2010Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2010Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2012Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2012Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2014Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2014Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2015Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2016Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1 : ТабличныйДокумент
ФормаОтчета2010Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2014Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2015Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2016Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2017Кв1_ФормаОтчета : ТабличныйДокумент
СоставПоказателей2012Кв1 : ТабличныйДокумент
СоставПоказателей2014Кв1 : ТабличныйДокумент
СоставПоказателей2015Кв1 : ТабличныйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
СоставПоказателей2017Кв1 : ТабличныйДокумент
ШаблонРосстата2016Кв1 : ДвоичныеДанные
ШаблонРосстата2017Кв1 : ДвоичныеДанные
МакетПереносаДанных2016Кв1 : ТабличныйДокумент
МакетПереносаДанных2017Кв1 : ТабличныйДокумент
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
Списки2018Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2018Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2018Кв1 : ТабличныйДокумент
ФормаОтчета2018Кв1_ФормаОтчета : ТабличныйДокумент
СоставПоказателей2018Кв1 : ТабличныйДокумент
ШаблонРосстата2018Кв1 : ДвоичныеДанные
МакетПереносаДанных2018Кв1 : ТабличныйДокумент
НастройкиЗагрузкиXML2018Кв1 : ТекстовыйДокумент
}
@enduml
