@startuml ДанныеДляБазыРаспределенияРасходов
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДанныеДляБазыРаспределенияРасходов as "Данные для базы распределения расходов" <<Отчеты>>
{
..Реквизиты..
НачалоПериода : Дата
ОкончаниеПериода : Дата
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
