@startuml БухгалтерскаяОтчетностьВБанк
'!include templates.wsd
'..\include templates.wsd
class Отчет.БухгалтерскаяОтчетностьВБанк as "Бухгалтерская отчетность для предоставления в банк" <<Отчеты>>
{
..Макеты..
НастройкаСоставаПоказателей2011Кв4 : ТабличныйДокумент
СоставПоказателей2011Кв4 : ТабличныйДокумент
СтруктураМногострочныхЧастей2011Кв4 : ТекстовыйДокумент
ФормаОтчета2011Кв4_Баланс_2012Кв4_3 : ТабличныйДокумент
ФормаОтчета2011Кв4_БалансНКО_2012Кв4_3 : ТабличныйДокумент
ФормаОтчета2011Кв4_ОПУ_ЕНВД : ТабличныйДокумент
ФормаОтчета2011Кв4_ОПУ_НеЕНВД : ТабличныйДокумент
ФормаОтчета2011Кв4_ОИК : ТабличныйДокумент
ФормаОтчета2011Кв4_ОДДС : ТабличныйДокумент
ФормаОтчета2011Кв4_ДополнительныеПоказатели : ТабличныйДокумент
СхемаВыгрузки506 : ТабличныйДокумент
ФормаОтчета2011Кв4_РасшифровкиОбеспечений : ТабличныйДокумент
ФормаОтчета2011Кв4_ОСВ_008 : ТабличныйДокумент
ФормаОтчета2011Кв4_ОСВ_009 : ТабличныйДокумент
ФормаОтчета2011Кв4_ЗадолженностьПоКредитамЗаймам : ТабличныйДокумент
ФормаОтчета2011Кв4_ОСВ_66 : ТабличныйДокумент
ФормаОтчета2011Кв4_ОСВ_67 : ТабличныйДокумент
ФормаОтчета2011Кв4_ЛизингОбязательства : ТабличныйДокумент
ФормаОтчета2011Кв4_ДенежныеСредства : ТабличныйДокумент
ФормаОтчета2011Кв4_Анализ_50 : ТабличныйДокумент
ФормаОтчета2011Кв4_Анализ_51 : ТабличныйДокумент
ФормаОтчета2011Кв4_Анализ_52 : ТабличныйДокумент
ФормаОтчета2011Кв4_Анализ_55 : ТабличныйДокумент
СпискиВыбора2017Кв3 : ТабличныйДокумент
СхемаВыгрузки506_29 : ТабличныйДокумент
ФормаОтчета2017Кв3_АнализСчета : ТабличныйДокумент
ФормаОтчета2017Кв3_АнализСчета_СписокСтраниц : ТабличныйДокумент
ФормаОтчета2017Кв3_Баланс : ТабличныйДокумент
ФормаОтчета2017Кв3_ДенежныеСредства : ТабличныйДокумент
ФормаОтчета2017Кв3_ДенежныеСредства50 : ТабличныйДокумент
ФормаОтчета2017Кв3_ДенежныеСредства51 : ТабличныйДокумент
ФормаОтчета2017Кв3_ДенежныеСредства52 : ТабличныйДокумент
ФормаОтчета2017Кв3_ДенежныеСредства55 : ТабличныйДокумент
ФормаОтчета2017Кв3_ДополнительныеПоказатели : ТабличныйДокумент
ФормаОтчета2017Кв3_ЗадолженностьПоКредитамЗаймам : ТабличныйДокумент
ФормаОтчета2017Кв3_ЗадолженностьПоКредитамЗаймамКраткосрочная : ТабличныйДокумент
ФормаОтчета2017Кв3_ЗадолженностьПоКредитамЗаймамДолгосрочная : ТабличныйДокумент
ФормаОтчета2017Кв3_ЛизингОбязательства : ТабличныйДокумент
ФормаОтчета2017Кв3_ОДДС : ТабличныйДокумент
ФормаОтчета2017Кв3_ОИК : ТабличныйДокумент
ФормаОтчета2017Кв3_ОСВ : ТабличныйДокумент
ФормаОтчета2017Кв3_ОСВПоСчету : ТабличныйДокумент
ФормаОтчета2017Кв3_ОСВПоСчету_СписокСтраниц : ТабличныйДокумент
ФормаОтчета2017Кв3_ОФР : ТабличныйДокумент
ФормаОтчета2017Кв3_ОЦИС : ТабличныйДокумент
ФормаОтчета2017Кв3_РасшифровкиОбеспечений : ТабличныйДокумент
ФормаОтчета2017Кв3_РасшифровкиОбеспеченийПолученные : ТабличныйДокумент
ФормаОтчета2017Кв3_РасшифровкиОбеспеченийВыданные : ТабличныйДокумент
ФормаОтчета2017Кв3_Титульный : ТабличныйДокумент
}
@enduml
