@startuml КарточкаРасчетовСПоставщиками
'!include templates.wsd
'..\include templates.wsd
class Отчет.КарточкаРасчетовСПоставщиками as "Карточка расчетов с поставщиками" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
