@startuml РегламентированныйОтчетСтатистика1Квотирование
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистика1Квотирование as "Форма 1-квотирование (Москва)" <<Отчеты>>
{
..Макеты..
ФормаОтчета2009Кв3_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2012Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2013Кв3_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2015Кв2_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2017Кв1_ФормаОтчета : ТабличныйДокумент
}
@enduml
