@startuml ПросроченныеЗадачи
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПросроченныеЗадачи as "Просроченные задачи" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
