@startuml РегламентированныйОтчетДекларацияПлатаНВОС
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетДекларацияПлатаНВОС as "Декларация о плате за негативное воздействие на окружающую среду" <<Отчеты>>
{
..Макеты..
Списки2016Кв1 : ТабличныйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2016Кв1 : ТабличныйДокумент
ФормаОтчета2016Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2016Кв1_Расчет : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел1_0 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел1_1 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел1_2 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2016Кв1_Раздел3_1 : ТабличныйДокумент
ФормаОтчета2016Кв1_Приложения : ТабличныйДокумент
ПечатнаяФормаОтчета2016Кв1_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2016Кв1_Расчет : ТабличныйДокумент
ПечатнаяФормаОтчета2016Кв1_Раздел1_0 : ТабличныйДокумент
ПечатнаяФормаОтчета2016Кв1_Раздел1_1 : ТабличныйДокумент
ПечатнаяФормаОтчета2016Кв1_Раздел1_2 : ТабличныйДокумент
ПечатнаяФормаОтчета2016Кв1_Раздел2 : ТабличныйДокумент
ПечатнаяФормаОтчета2016Кв1_Раздел3ч1 : ТабличныйДокумент
ПечатнаяФормаОтчета2016Кв1_Раздел3ч2 : ТабличныйДокумент
ПечатнаяФормаОтчета2016Кв1_Раздел3_1 : ТабличныйДокумент
}
@enduml
