@startuml ПродажиСравнениеДвухПериодов
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПродажиСравнениеДвухПериодов as "Сравнение продаж двух периодов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
