@startuml ОценкаРискаНалоговойПроверки
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОценкаРискаНалоговойПроверки as "Оценка риска налоговой проверки" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
..Макеты..
ОписаниеРезультатовПроверки : ТабличныйДокумент
ПредельныеЗначенияЗарплаты2013 : ТабличныйДокумент
МакетОтчета : ТабличныйДокумент
ПечатнаяФорма : ТабличныйДокумент
}
@enduml
