@startuml РегламентированныйОтчетПрибыльСРП
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетПрибыльСРП as "Декларация по налогу на прибыль организаций при выполнении соглашений о разделе продукции" <<Отчеты>>
{
..Макеты..
МБ_1151082_3_00001_04_tif : ДвоичныеДанные
МБ_1151082_3_00002_05_tif : ДвоичныеДанные
МБ_1151082_5_01000_06_tif : ДвоичныеДанные
НастройкиЗагрузкиXML2007Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв3 : ТекстовыйДокумент
ПечатнаяФормаОтчета2007Кв1_Лист02 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Лист02_Прил1 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Лист02_Прил2 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Лист02_Прил3 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Лист02_Прил4 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2007Кв1_Титульный : ТабличныйДокумент
ПечатныйБланк2017Кв3_Раздел1 : ТабличныйДокумент
ПечатныйБланк2017Кв3_Раздел2 : ТабличныйДокумент
ПечатныйБланк2017Кв3_Раздел21 : ТабличныйДокумент
ПечатныйБланк2017Кв3_Раздел22 : ТабличныйДокумент
ПечатныйБланк2017Кв3_Раздел23 : ТабличныйДокумент
ПечатныйБланк2017Кв3_Раздел24 : ТабличныйДокумент
ПечатныйБланк2017Кв3_Титульный : ТабличныйДокумент
СоставПоказателей2007Кв1 : ТабличныйДокумент
Списки2006Кв1 : ТабличныйДокумент
СпискиВыбора2017Кв3 : ТабличныйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
ФормаОтчета2007Кв1_Лист02 : ТабличныйДокумент
ФормаОтчета2007Кв1_Лист02_Прил1 : ТабличныйДокумент
ФормаОтчета2007Кв1_Лист02_Прил2 : ТабличныйДокумент
ФормаОтчета2007Кв1_Лист02_Прил3 : ТабличныйДокумент
ФормаОтчета2007Кв1_Лист02_Прил4 : ТабличныйДокумент
ФормаОтчета2007Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2007Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2017Кв3_Раздел1 : ТабличныйДокумент
ФормаОтчета2017Кв3_Раздел2 : ТабличныйДокумент
ФормаОтчета2017Кв3_Раздел21 : ТабличныйДокумент
ФормаОтчета2017Кв3_Раздел22 : ТабличныйДокумент
ФормаОтчета2017Кв3_Раздел23 : ТабличныйДокумент
ФормаОтчета2017Кв3_Раздел24 : ТабличныйДокумент
ФормаОтчета2017Кв3_Титульный : ТабличныйДокумент
}
@enduml
