@startuml РегламентированныйОтчетКосвенныеНалогиТамСоюз
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетКосвенныеНалогиТамСоюз as "Косвенные налоги при импорте товаров" <<Отчеты>>
{
..Макеты..
МБ_1151088_5_01000_01_tif : ДвоичныеДанные
МБ_1151088_5_02000_02_tif : ДвоичныеДанные
МБ_1151088_5_03000_03_tif : ДвоичныеДанные
МЧБ_2010Кв3_Прил : ТабличныйДокумент
МЧБ_2010Кв3_Раздел1 : ТабличныйДокумент
МЧБ_2010Кв3_Раздел2 : ТабличныйДокумент
МЧБ_2010Кв3_Титул : ТабличныйДокумент
НастройкиЗагрузкиXML2010Кв3 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв4 : ТекстовыйДокумент
ПечатныйБланк2017Кв4_Раздел1 : ТабличныйДокумент
ПечатныйБланк2017Кв4_Раздел2 : ТабличныйДокумент
ПечатныйБланк2017Кв4_Раздел3 : ТабличныйДокумент
ПечатныйБланк2017Кв4_Титульный : ТабличныйДокумент
СоставПоказателей2010Кв3 : ТабличныйДокумент
Списки2010Кв3 : ТабличныйДокумент
СпискиВыбора2017Кв4 : ТабличныйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
СхемаВыгрузки502 : ТабличныйДокумент
СхемаВыгрузки503 : ТабличныйДокумент
ФормаОтчета2010Кв3_Раздел1 : ТабличныйДокумент
ФормаОтчета2010Кв3_Раздел2 : ТабличныйДокумент
ФормаОтчета2010Кв3_Раздел2_Прил1 : ТабличныйДокумент
ФормаОтчета2010Кв3_Титульный : ТабличныйДокумент
ФормаОтчета2017Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2017Кв4_Раздел2 : ТабличныйДокумент
ФормаОтчета2017Кв4_Раздел3 : ТабличныйДокумент
ФормаОтчета2017Кв4_Титульный : ТабличныйДокумент
}
@enduml
