@startuml АнализПричинОтменыЗаказовКлиентов
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализПричинОтменыЗаказовКлиентов as "Причины отмены заказов клиентов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
