@startuml РегламентированноеУведомлениеКИК
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеКИК as "Уведомление о контролируемых иностранных компаниях" <<Отчеты>>
{
..Макеты..
Печать_Форма2017_1_Титульная : ТабличныйДокумент
Печать_Форма2017_1_ЛистСведФЛ : ТабличныйДокумент
Печать_Форма2017_1_ЛистА : ТабличныйДокумент
Печать_Форма2017_1_ЛистА1 : ТабличныйДокумент
Печать_Форма2017_1_ЛистБ : ТабличныйДокумент
Печать_Форма2017_1_ЛистБ1 : ТабличныйДокумент
Печать_Форма2017_1_ЛистВ : ТабличныйДокумент
Печать_Форма2017_1_ЛистГ : ТабличныйДокумент
Печать_Форма2017_1_ЛистГ1 : ТабличныйДокумент
Печать_Форма2017_1_ЛистГ2 : ТабличныйДокумент
СхемаВыгрузкиФорма2017_1 : ТабличныйДокумент
TIFF_2017_1 : ДвоичныеДанные
Форматы2017_1 : ТабличныйДокумент
СпискиВыбора2017_1 : ТабличныйДокумент
ОбщиеЭлементы : ТабличныйДокумент
Титульная : ТабличныйДокумент
ЛистСведФЛ : ТабличныйДокумент
ЛистА : ТабличныйДокумент
ЛистБ : ТабличныйДокумент
ЛистВ : ТабличныйДокумент
ЛистГ : ТабличныйДокумент
ЛистГ1 : ТабличныйДокумент
ЛистГ2 : ТабличныйДокумент
}
@enduml
