@startuml АнализСостоянияНалоговогоУчетаПоНалогуНаПрибыль
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализСостоянияНалоговогоУчетаПоНалогуНаПрибыль as "Анализ учета по налогу на прибыль" <<Отчеты>>
{
..Реквизиты..
НачалоПериода : Дата
КонецПериода : Дата
Организация : Справочник.Организация
СохраняемыеРеквизиты : 
ВключатьОбособленныеПодразделения : Булево
ОрганизацияРасшифровки : Справочник.Организация
ИмяРасшифровки : Строка
..Макеты..
Карта : ГрафическаяСхема
КартаЕНВД : ГрафическаяСхема
РасчетНалогаНаПрибыль : ГрафическаяСхема
Доходы : ГрафическаяСхема
Расходы : ГрафическаяСхема
РасходыЕНВД : ГрафическаяСхема
КосвенныеРасходы : ГрафическаяСхема
РасходыОбычные : ГрафическаяСхема
РасходыПроизводства : ГрафическаяСхема
РасходыПроизводстваЕНВД : ГрафическаяСхема
ТранспортныеРасходы : ГрафическаяСхема
РасходыРаспределяемые : ГрафическаяСхема
РасходыПрочие : ГрафическаяСхема
РасходыПрочиеЕНВД : ГрафическаяСхема
СтоимостьСписанияТоваров : ГрафическаяСхема
СтоимостьСписанияТоваровЕНВД : ГрафическаяСхема
СтоимостьТоваров : ГрафическаяСхема
Карта82 : ГрафическаяСхема
КартаЕНВД82 : ГрафическаяСхема
РасчетНалогаНаПрибыль82 : ГрафическаяСхема
Доходы82 : ГрафическаяСхема
Расходы82 : ГрафическаяСхема
РасходыЕНВД82 : ГрафическаяСхема
КосвенныеРасходы82 : ГрафическаяСхема
РасходыОбычные82 : ГрафическаяСхема
РасходыПроизводства82 : ГрафическаяСхема
РасходыПроизводстваЕНВД82 : ГрафическаяСхема
ТранспортныеРасходы82 : ГрафическаяСхема
РасходыРаспределяемые82 : ГрафическаяСхема
РасходыПрочие82 : ГрафическаяСхема
РасходыПрочиеЕНВД82 : ГрафическаяСхема
СтоимостьСписанияТоваров82 : ГрафическаяСхема
СтоимостьСписанияТоваровЕНВД82 : ГрафическаяСхема
СтоимостьТоваров82 : ГрафическаяСхема
МакетЗаголовкаРасшифровки : ТабличныйДокумент
РасшифровкаАмортизация : СхемаКомпоновкиДанных
РасшифровкаАмортизацияРБПТоварыНеРеализация : СхемаКомпоновкиДанных
РасшифровкаВыручкаПоОбычнымВидамДеятельности : СхемаКомпоновкиДанных
РасшифровкаДоходыНеУчитываемыеВНалоговойБазе : СхемаКомпоновкиДанных
РасшифровкаДоходыУчитываемыеПриОпределенииНалоговойБазы : СхемаКомпоновкиДанных
РасшифровкаДругиеПрочиеРасходы : СхемаКомпоновкиДанных
РасшифровкаКосвенныеРаспределяемыеРасходыУчитываемыеВНУ : СхемаКомпоновкиДанных
РасшифровкаКосвенныеРасходы : СхемаКомпоновкиДанных
РасшифровкаКосвенныеРасходыЕНВД : СхемаКомпоновкиДанных
РасшифровкаКосвенныеРасходыНеВкл : СхемаКомпоновкиДанных
РасшифровкаКосвенныеРасходыНеВключенные : СхемаКомпоновкиДанных
РасшифровкаКосвенныеРасходыНеЕНВД : СхемаКомпоновкиДанных
РасшифровкаКосвенныеРасходыНеУчитываемыеВНУ : СхемаКомпоновкиДанных
РасшифровкаКосвенныеРасходыУчитываемыеВНУ : СхемаКомпоновкиДанных
РасшифровкаНезавершенноеПроизводство : СхемаКомпоновкиДанных
РасшифровкаНезавершенноеПроизводствоПрошлыхЛет : СхемаКомпоновкиДанных
РасшифровкаОПРиОХРСписанныеНаПрямые : СхемаКомпоновкиДанных
РасшифровкаОПРиОХРСписанныеНаПрямыеРаспределяемые : СхемаКомпоновкиДанных
РасшифровкаОприходованиеИзлишков : СхемаКомпоновкиДанных
РасшифровкаПрочиеДоходы : СхемаКомпоновкиДанных
РасшифровкаПрочиеДоходыУчитываемыеВНУ : СхемаКомпоновкиДанных
РасшифровкаПрочиеРасходы : СхемаКомпоновкиДанных
РасшифровкаПрочиеРасходыНеЕНВД : СхемаКомпоновкиДанных
РасшифровкаПрочиеРасходыНеУчитываемыеВНУ : СхемаКомпоновкиДанных
РасшифровкаПрочиеРасходыОтнесенныеНаЕНВД : СхемаКомпоновкиДанных
РасшифровкаПрочиеРасходыРаспределяемые : СхемаКомпоновкиДанных
РасшифровкаПрочиеРасходыУчитываемыеВНУ : СхемаКомпоновкиДанных
РасшифровкаПрямыеПроизводственныеРасходы : СхемаКомпоновкиДанных
РасшифровкаПрямыеРасходыЕНВД : СхемаКомпоновкиДанных
РасшифровкаПрямыеРасходыПоРеализованнымТоварамНеУчНУ : СхемаКомпоновкиДанных
РасшифровкаПрямыеРасходыПоРеализованнымТоварамУчНУ : СхемаКомпоновкиДанных
РасшифровкаПрямыеРасходыПоРеализованнымУслугам : СхемаКомпоновкиДанных
РасшифровкаРасходыНаПриобретениеТоваровАмортизируемогоИмуществаРБП : СхемаКомпоновкиДанных
РасшифровкаРасходыОтносящиесяКСтоимостиРеализованногоИмущества : СхемаКомпоновкиДанных
РасшифровкаСтоимостьВыпущеннойПродукции : СхемаКомпоновкиДанных
РасшифровкаСтоимостьНеСписанныхТоваровРБПАмортизируемогоИмущества : СхемаКомпоновкиДанных
РасшифровкаСтоимостьТоваровИАмортизацияНеСписаннаяВПрошлыхПериодах : СхемаКомпоновкиДанных
РасшифровкаСтоимостьТоваровРБП : СхемаКомпоновкиДанных
РасшифровкаТранспортныхРасходов : СхемаКомпоновкиДанных
РасшифровкаТранспортныхРасходовОтнесенныхНаНачалоПериода : СхемаКомпоновкиДанных
РасшифровкаТранспортныхРасходовОтнесенныхНаОстаток : СхемаКомпоновкиДанных
РасшифровкаТранспортныхРасходовУчитываемыхВНУ : СхемаКомпоновкиДанных
РасшифровкаУслугиСтороннихОрганизаций : СхемаКомпоновкиДанных
СписокОрганизаций : ТабличныйДокумент
}
@enduml
