@startuml ВедомостьПоДенежнымСредствам
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВедомостьПоДенежнымСредствам as "Ведомость по денежным средствам" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
