@startuml КонтрольПередачиПродукцииДавальцу
'!include templates.wsd
'..\include templates.wsd
class Отчет.КонтрольПередачиПродукцииДавальцу as "Контроль передачи продукции давальцу" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
