@startuml РегламентированныйОтчетБухОтчетностьМП
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетБухОтчетностьМП as "Бухгалтерская отчетность упрощенная" <<Отчеты>>
{
..Макеты..
МБ_0710096_5_01000_01_tif : ДвоичныеДанные
МБ_0710096_5_02000_02_tif : ДвоичныеДанные
МБ_0710098_5_01000_01_tif : ДвоичныеДанные
МБ_0710098_5_02000_02_tif : ДвоичныеДанные
МБ_0710098_5_03000_03_tif : ДвоичныеДанные
НастройкиЗагрузкиXML2015Кв4 : ТекстовыйДокумент
НастройкиСоставаОтчетов2012Кв4 : ТекстовыйДокумент
НастройкиСоставаОтчетов2012Кв4_2 : ТекстовыйДокумент
НастройкиСоставаОтчетов2015Кв4 : ТекстовыйДокумент
СоставПоказателей2012Кв4 : ТабличныйДокумент
СоставПоказателей2012Кв4_2 : ТабличныйДокумент
СоставПоказателей2015Кв4 : ТабличныйДокумент
СпискиВыбора2012Кв4 : ТабличныйДокумент
СпискиВыбора2012Кв4_2 : ТабличныйДокумент
СпискиВыбора2015Кв4 : ТабличныйДокумент
СтруктураМногострочныхЧастей2012Кв4 : ТекстовыйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
СхемаВыгрузки501_2015Кв4 : ТабличныйДокумент
СхемаВыгрузки502 : ТабличныйДокумент
СхемаВыгрузки502_2016Кв1 : ТабличныйДокумент
СхемаВыгрузки503 : ТабличныйДокумент
ФормаОтчета2012Кв4_2_Баланс : ТабличныйДокумент
ФормаОтчета2012Кв4_2_Изменения : HTMLДокумент
ФормаОтчета2012Кв4_2_ОДДС : ТабличныйДокумент
ФормаОтчета2012Кв4_2_ОИК : ТабличныйДокумент
ФормаОтчета2012Кв4_2_ОПУ : ТабличныйДокумент
ФормаОтчета2012Кв4_2_ОЦИПС : ТабличныйДокумент
ФормаОтчета2012Кв4_Баланс : ТабличныйДокумент
ФормаОтчета2012Кв4_ОДДС : ТабличныйДокумент
ФормаОтчета2012Кв4_ОИК : ТабличныйДокумент
ФормаОтчета2012Кв4_ОПУ : ТабличныйДокумент
ФормаОтчета2012Кв4_ОЦИПС : ТабличныйДокумент
ФормаОтчета2012Кв4_Пояснения1 : ТабличныйДокумент
ФормаОтчета2012Кв4_Пояснения2 : ТабличныйДокумент
ФормаОтчета2012Кв4_Пояснения3 : ТабличныйДокумент
ФормаОтчета2012Кв4_Пояснения4 : ТабличныйДокумент
ФормаОтчета2012Кв4_Пояснения5 : ТабличныйДокумент
ФормаОтчета2012Кв4_Пояснения6 : ТабличныйДокумент
ФормаОтчета2012Кв4_Пояснения7 : ТабличныйДокумент
ФормаОтчета2012Кв4_Пояснения8 : ТабличныйДокумент
ФормаОтчета2012Кв4_Пояснения9 : ТабличныйДокумент
ФормаОтчета2015Кв4_Баланс : ТабличныйДокумент
ФормаОтчета2015Кв4_БалансНКО : ТабличныйДокумент
ФормаОтчета2015Кв4_ОДДС : ТабличныйДокумент
ФормаОтчета2015Кв4_ОИК : ТабличныйДокумент
ФормаОтчета2015Кв4_ОПУ : ТабличныйДокумент
ФормаОтчета2015Кв4_ОЦИС : ТабличныйДокумент
ФормаПечати2012Кв1_КНД0710098_1 : ТабличныйДокумент
ФормаПечати2012Кв1_КНД0710098_2 : ТабличныйДокумент
ФормаПечати2013Кв1_КНД0710098_1 : ТабличныйДокумент
ФормаПечати2013Кв1_КНД0710098_2 : ТабличныйДокумент
ФормаПечати2015Кв4_КНД0710096_1 : ТабличныйДокумент
ФормаПечати2015Кв4_КНД0710096_2 : ТабличныйДокумент
ФормаПечати2016Кв1_КНД0710096_1 : ТабличныйДокумент
ФормаПечати2016Кв1_КНД0710096_2 : ТабличныйДокумент
}
@enduml
