@startuml СравнительныйАнализПоказателейРаботыМенеджеров
'!include templates.wsd
'..\include templates.wsd
class Отчет.СравнительныйАнализПоказателейРаботыМенеджеров as "Сравнительный анализ показателей работы менеджеров" <<Отчеты>>
{
..Макеты..
СравнительныйАнализМенеджеров : ТабличныйДокумент
СхемаДляОтбораПользователей : СхемаКомпоновкиДанных
}
@enduml
