@startuml РегламентированныйОтчетАлкоПриложение8
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетАлкоПриложение8 as "Декларация об объеме перевозки этилового спирта, алкогольной и спиртосодержащей продукции" <<Отчеты>>
{
..Макеты..
ПечатнаяФормаОтчета2012Кв3_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Лицензии : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Декларация : ТабличныйДокумент
СоставПоказателей2012Кв3 : ТабличныйДокумент
Списки2012Кв3 : ТабличныйДокумент
СхемаВыгрузки420 : ТабличныйДокумент
ФормаОтчета2012Кв3_Титульный : ТабличныйДокумент
ФормаОтчета2012Кв3_Лицензии : ТабличныйДокумент
ФормаОтчета2012Кв3_Декларация : ТабличныйДокумент
СхемаВыгрузки430 : ТабличныйДокумент
Списки2012Кв3_20131101 : ТабличныйДокумент
НастройкиЗагрузкиXML2012Кв3 : ТекстовыйДокумент
}
@enduml
