@startuml АнализПооперационногоРасписания
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализПооперационногоРасписания as "Анализ пооперационного расписания" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
