@startuml СправкиСотрудников
'!include templates.wsd
'..\include templates.wsd
class Отчет.СправкиСотрудников as "Справки сотрудников" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
