@startuml ОборотноСальдоваяВедомостьПоСчету
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОборотноСальдоваяВедомостьПоСчету as "Оборотно-сальдовая ведомость по счету" <<Отчеты>>
{
..Реквизиты..
ВключатьОбособленныеПодразделения : Булево
КонецПериода : Дата
НачалоПериода : Дата
Организация : Справочник.Организация
Периодичность : Число 2, 0
ПоСубсчетам : Булево
Счет : Счет бухгалтерского учета
ПоказательНУ : Булево
ПоказательБУ : Булево
ПоказательВалютнаяСумма : Булево
ПоказательВР : Булево
ПоказательПР : Булево
ПоказательКоличество : Булево
ПоказательКонтроль : Булево
РазвернутоеСальдо : Булево
РазмещениеДополнительныхПолей : Число 1, 0
РежимРасшифровки : Булево
ПоказательУУ : Булево
ПоказательФО : Булево
ПоказательРазницаБУиУУ : Булево
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
СхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
