@startuml РегистрыНалоговогоУчета
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегистрыНалоговогоУчета as "Регистры налогового учета" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
ВключатьОбособленныеПодразделения : Булево
РазмещениеДополнительныхПолей : Число 1, 0
РежимРасшифровки : Булево
ВыводитьОтбор : Булево
Регистр : Строка
НазваниеРегистра : Строка
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
СхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
