@startuml СостояниеРасчетовСКомитентами
'!include templates.wsd
'..\include templates.wsd
class Отчет.СостояниеРасчетовСКомитентами as "Состояние расчетов с комитентами" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
