@startuml РегламентированныйОтчетДеятельностьИнОргВРФ
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетДеятельностьИнОргВРФ as "Отчет о деятельности иностранной организации в РФ" <<Отчеты>>
{
..Макеты..
СоставПоказателей2004Кв1 : ТабличныйДокумент
ФормаОтчета2004Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2004Кв1_ФизЛица : ТабличныйДокумент
ФормаОтчета2004Кв1_Раздел1_1 : ТабличныйДокумент
ФормаОтчета2004Кв1_Раздел1_2 : ТабличныйДокумент
ФормаОтчета2004Кв1_Раздел1_3 : ТабличныйДокумент
ФормаОтчета2004Кв1_Раздел1_4 : ТабличныйДокумент
ПечатнаяФормаОтчета2004Кв1_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2004Кв1_ФизЛица : ТабличныйДокумент
ПечатнаяФормаОтчета2004Кв1_Раздел1_1 : ТабличныйДокумент
ПечатнаяФормаОтчета2004Кв1_Раздел1_2 : ТабличныйДокумент
ПечатнаяФормаОтчета2004Кв1_Раздел1_3 : ТабличныйДокумент
ПечатнаяФормаОтчета2004Кв1_Раздел1_4 : ТабличныйДокумент
}
@enduml
