@startuml РегламентированныйОтчетИмущество
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетИмущество as "Декларация по налогу на имущество организаций" <<Отчеты>>
{
..Макеты..
МБ_1152026_5_01000_05_tif : ДвоичныеДанные
МБ_1152026_5_02000_06_tif : ДвоичныеДанные
МБ_1152026_5_03000_07_tif : ДвоичныеДанные
МБ_1152026_5_04000_08_tif : ДвоичныеДанные
МЧБ_2008Кв1_1 : ТабличныйДокумент
МЧБ_2008Кв1_2 : ТабличныйДокумент
МЧБ_2008Кв1_3 : ТабличныйДокумент
МЧБ_2008Кв1_4 : ТабличныйДокумент
МЧБ_2011Кв3_1 : ТабличныйДокумент
МЧБ_2011Кв3_2 : ТабличныйДокумент
МЧБ_2011Кв3_3 : ТабличныйДокумент
МЧБ_2011Кв3_4 : ТабличныйДокумент
НастройкиЗагрузкиXML2013Кв4 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв4 : ТекстовыйДокумент
ПечатныйБланк_2013Кв4_Раздел1 : ТабличныйДокумент
ПечатныйБланк_2013Кв4_Раздел2 : ТабличныйДокумент
ПечатныйБланк_2013Кв4_Раздел3 : ТабличныйДокумент
ПечатныйБланк_2013Кв4_Титульный : ТабличныйДокумент
ПечатныйБланк2017Кв4_Раздел1 : ТабличныйДокумент
ПечатныйБланк2017Кв4_Раздел2 : ТабличныйДокумент
ПечатныйБланк2017Кв4_Раздел21 : ТабличныйДокумент
ПечатныйБланк2017Кв4_Раздел3 : ТабличныйДокумент
ПечатныйБланк2017Кв4_Титульный : ТабличныйДокумент
СоставПоказателей2008Кв1 : ТабличныйДокумент
СоставПоказателей2011Кв3 : ТабличныйДокумент
СоставПоказателей2013Кв4 : ТабличныйДокумент
Списки2008Кв1 : ТабличныйДокумент
Списки2011Кв3 : ТабличныйДокумент
СпискиВыбора2013Кв4 : ТабличныйДокумент
СпискиВыбора2017Кв4 : ТабличныйДокумент
СхемаВыгрузки501 : ТабличныйДокумент
СхемаВыгрузки502 : ТабличныйДокумент
СхемаВыгрузки503 : ТабличныйДокумент
СхемаВыгрузки504 : ТабличныйДокумент
ФормаОтчета2008Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2008Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2008Кв1_Раздел3 : ТабличныйДокумент
ФормаОтчета2008Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2011Кв3_Раздел1 : ТабличныйДокумент
ФормаОтчета2011Кв3_Раздел2 : ТабличныйДокумент
ФормаОтчета2011Кв3_Раздел3 : ТабличныйДокумент
ФормаОтчета2011Кв3_Титульный : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел2 : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел3 : ТабличныйДокумент
ФормаОтчета2013Кв4_Титульный : ТабличныйДокумент
ФормаОтчета2017Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2017Кв4_Раздел2 : ТабличныйДокумент
ФормаОтчета2017Кв4_Раздел21 : ТабличныйДокумент
ФормаОтчета2017Кв4_Раздел21_Печать : ТабличныйДокумент
ФормаОтчета2017Кв4_Раздел3 : ТабличныйДокумент
ФормаОтчета2017Кв4_Титульный : ТабличныйДокумент
}
@enduml
