@startuml РаспределениеТорговыхПредставителей
'!include templates.wsd
'..\include templates.wsd
class Отчет.РаспределениеТорговыхПредставителей as "Календарь визитов торговых представителей" <<Отчеты>>
{
..Реквизиты..
ПериодОтчета : Стандартный период
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
