@startuml РасчетыМеждуОрганизациями
'!include templates.wsd
'..\include templates.wsd
class Отчет.РасчетыМеждуОрганизациями as "Расчеты между организациями" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
