@startuml ПланПроизводстваПродукцииИПолуфабрикатов
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПланПроизводстваПродукцииИПолуфабрикатов as "План производства продукции и полуфабрикатов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
