@startuml АнализРаспределенияНДС
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализРаспределенияНДС as "Анализ распределения НДС" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
ВидОтчета : Число 1, 0
ВыручкаПоДокументам : Булево
ДокументРаспределения : Документ.Распределение НДС
..Макеты..
Таблица : ТабличныйДокумент
}
@enduml
