@startuml ОборотноСальдоваяВедомость
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОборотноСальдоваяВедомость as "Оборотно-сальдовая ведомость" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
ВключатьОбособленныеПодразделения : Булево
ПоСубсчетам : Булево
ВыводитьЗабалансовыеСчета : Булево
РазмещениеДополнительныхПолей : Число 1, 0
ПоказательБУ : Булево
ПоказательНУ : Булево
ПоказательПР : Булево
ПоказательВР : Булево
ПоказательКонтроль : Булево
ПоказательВалютнаяСумма : Булево
РежимРасшифровки : Булево
ПоказательУУ : Булево
ПоказательФО : Булево
ПоказательРазницаБУиУУ : Булево
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
СхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
