@startuml АнализСубконто
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализСубконто as "Анализ субконто" <<Отчеты>>
{
..Реквизиты..
НачалоПериода : Дата
КонецПериода : Дата
Организация : Справочник.Организация
ВключатьОбособленныеПодразделения : Булево
ПоСубсчетам : Булево
СписокВидовСубконто : Список значений
Периодичность : Число 2, 0
ПоказательБУ : Булево
ПоказательНУ : Булево
ПоказательПР : Булево
ПоказательВР : Булево
ПоказательКонтроль : Булево
ПоказательКоличество : Булево
ПоказательВалютнаяСумма : Булево
РазвернутоеСальдо : Булево
РежимРасшифровки : Булево
РазмещениеДополнительныхПолей : Число 1, 0
ПоказательУУ : Булево
ПоказательФО : Булево
ПоказательРазницаБУиУУ : Булево
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
СхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
