@startuml РегламентированноеУведомлениеИсключениеПроверки
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеИсключениеПроверки as "Регламентированное уведомление исключение проверки" <<Отчеты>>
{
..Макеты..
Форма2015_1 : ТабличныйДокумент
Печать_MXL_Форма2015_1 : ТабличныйДокумент
}
@enduml
