@startuml РеестрПлатежей
'!include templates.wsd
'..\include templates.wsd
class Отчет.РеестрПлатежей as "Реестр платежей" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
