@startuml ЗагрузкаОборудованияПоМоделиГрафикаПроизводства
'!include templates.wsd
'..\include templates.wsd
class Отчет.ЗагрузкаОборудованияПоМоделиГрафикаПроизводства as "Загрузка оборудования по модели графика производства" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
