@startuml ВедомостьБезналичныхДенежныхСредств
'!include templates.wsd
'..\include templates.wsd
class Отчет.ВедомостьБезналичныхДенежныхСредств as "Сверка банковских выписок" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
