@startuml ОстаткиТоваровОрганизаций
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОстаткиТоваровОрганизаций as "Остатки товаров организаций" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
