@startuml ДвиженияМеждуРегистрамиЕГАИС
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДвиженияМеждуРегистрамиЕГАИС as "Движения между регистрами ЕГАИС" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
