@startuml ПлатежнаяДисциплинаКлиентов
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПлатежнаяДисциплинаКлиентов as "Платежная дисциплина клиентов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
