@startuml ТоварыНаСкладахПоСрокамГодности
'!include templates.wsd
'..\include templates.wsd
class Отчет.ТоварыНаСкладахПоСрокамГодности as "Товары на складах по срокам годности" <<Отчеты>>
{
..Макеты..
ЗапросОстатковПоСправочномуУчетуСроковГодности : СхемаКомпоновкиДанных
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
