@startuml РегламентированныйОтчетСтатистикаФорма1И
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма1И as "Форма 1-ИНВЕСТ "Сведения об инвестициях в Россию из-за рубежа и инвестициях из России за рубеж"" <<Отчеты>>
{
..Макеты..
СхемаВыгрузкиXML2010Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2010Кв1 : ТабличныйДокумент
ФормаОтчета2010Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2013Кв1_ФормаОтчета : ТабличныйДокумент
НастройкиЗагрузкиXML2010Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2013Кв1 : ТекстовыйДокумент
}
@enduml
