@startuml РегламентированныйОтчетАлкоПриложение9
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетАлкоПриложение9 as "Декларация о перевозке этилового спирта и спиртосодержащей продукции" <<Отчеты>>
{
..Макеты..
ПечатнаяФормаОтчета2012Кв3_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Титульный_20140101 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв3_Лицензии : ТабличныйДокумент
СоставПоказателей2012Кв3 : ТабличныйДокумент
Списки2012Кв3 : ТабличныйДокумент
Списки2012Кв3_20131101 : ТабличныйДокумент
Списки2015Кв3 : ТабличныйДокумент
СхемаВыгрузки420 : ТабличныйДокумент
СхемаВыгрузки430 : ТабличныйДокумент
ФормаОтчета2012Кв3_Титульный : ТабличныйДокумент
ФормаОтчета2012Кв3_Титульный_20140101 : ТабличныйДокумент
ФормаОтчета2012Кв3_Лицензии : ТабличныйДокумент
ФормаОтчета2012Кв3_Декларация : ТабличныйДокумент
СхемаВыгрузки431 : ТабличныйДокумент
НастройкиЗагрузкиXML2012Кв3 : ТекстовыйДокумент
}
@enduml
