@startuml АнализИзмененийЛичныхДанныхСотрудников
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализИзмененийЛичныхДанныхСотрудников as "Анализ изменений личных данных сотрудников" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
