@startuml ОбъемНенужныхФайлов
'!include templates.wsd
'..\include templates.wsd
class Отчет.ОбъемНенужныхФайлов as "Объем ненужных файлов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
