@startuml РегламентированныйОтчетСтатистикаФорма1
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма1 as "Форма 1 "Сведения о распределении численности работников по размерам заработной платы"" <<Отчеты>>
{
..Макеты..
СхемаВыгрузкиXML2016Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1 : ТабличныйДокумент
ФормаОтчета2016Кв1_ФормаОтчета : ТабличныйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
ШаблонРосстата2016Кв1 : ДвоичныеДанные
}
@enduml
