@startuml РегламентированныйОтчетНедра
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетНедра as "Расчет регулярных платежей за пользование недрами" <<Отчеты>>
{
..Макеты..
МБ_1151026_3_00002_01_tif : ДвоичныеДанные
МБ_1151026_3_00003_02_tif : ДвоичныеДанные
ПечатнаяФормаОтчета2004Кв1_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2004Кв1_Раздел21 : ТабличныйДокумент
ПечатнаяФормаОтчета2004Кв1_Раздел22 : ТабличныйДокумент
ПечатнаяФормаОтчета2004Кв1_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2004Кв1_ФизЛица : ТабличныйДокумент
СоставПоказателей2004Кв1 : ТабличныйДокумент
Списки2004Кв1 : ТабличныйДокумент
ФормаОтчета2004Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2004Кв1_Раздел21 : ТабличныйДокумент
ФормаОтчета2004Кв1_Раздел22 : ТабличныйДокумент
ФормаОтчета2004Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2004Кв1_ФизЛица : ТабличныйДокумент
НастройкиЗагрузкиXML2004Кв1 : ТекстовыйДокумент
}
@enduml
