@startuml РегламентированноеУведомлениеДекларацияХарактеристикаОбъекта
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированноеУведомлениеДекларацияХарактеристикаОбъекта as "Декларация о характеристиках объекта недвижимости" <<Отчеты>>
{
..Макеты..
Форма2015_1 : ТабличныйДокумент
Печать_MXL_Форма2015_1 : ТабличныйДокумент
СпискиВыбора2015_1 : ТабличныйДокумент
}
@enduml
