@startuml СправкаРасчетПересчетСтоимостиОтложенныхНалоговыхАктивовИОбязательств
'!include templates.wsd
'..\include templates.wsd
class Отчет.СправкаРасчетПересчетСтоимостиОтложенныхНалоговыхАктивовИОбязательств as "Справка-расчет "Пересчет стоимости отложенных налоговых активов и обязательств"" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
ВключатьОбособленныеПодразделения : Булево
ПоказательБУ : Булево
ПоказательНУ : Булево
ПоказательПР : Булево
ПоказательВР : Булево
РежимРасшифровки : Булево
НаборПоказателейОтчета : Число 1, 0
СНачалаГода : Булево
Реформация : Булево
ФормаОтчета : Строка
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
