@startuml СведенияОПользователях
'!include templates.wsd
'..\include templates.wsd
class Отчет.СведенияОПользователях as "Сведения о пользователях" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
