@startuml СправкаРасчетРезервыОтпусков
'!include templates.wsd
'..\include templates.wsd
class Отчет.СправкаРасчетРезервыОтпусков as "Справка-расчет "Резервы отпусков"" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
