@startuml ДинамикаПоказателейРаботыТорговыхПредставителей
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДинамикаПоказателейРаботыТорговыхПредставителей as "Динамика показателей работы торговых представителей" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
