@startuml РегламентированныйОтчетСтатистикаФорма24Энергетика
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма24Энергетика as "Форма 24-энергетика "Электробаланс и отчет о работе электростанций (электрогенераторных установок)"" <<Отчеты>>
{
..Макеты..
Списки2013Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2013Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв1 : ТабличныйДокумент
ФормаОтчета2013Кв1_ФормаОтчета : ТабличныйДокумент
НастройкиЗагрузкиXML2013Кв1 : ТекстовыйДокумент
}
@enduml
