@startuml СбалансированностьПлановУТ
'!include templates.wsd
'..\include templates.wsd
class Отчет.СбалансированностьПлановУТ as "Сбалансированность планов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
