@startuml ДвиженияПоСправке2ЕГАИС
'!include templates.wsd
'..\include templates.wsd
class Отчет.ДвиженияПоСправке2ЕГАИС as "Движения по справке 2" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
