@startuml СравнениеНМА
'!include templates.wsd
'..\include templates.wsd
class Отчет.СравнениеНМА as "Сравнение НМА в бухгалтерском и международном учете" <<Отчеты>>
{
..Макеты..
Макет : ТабличныйДокумент
}
@enduml
