@startuml КадроваяИсторияСотрудников
'!include templates.wsd
'..\include templates.wsd
class Отчет.КадроваяИсторияСотрудников as "Кадровая история сотрудников" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
