@startuml РегламентированныйОтчетСтатистикаФормаП5М
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФормаП5М as "Форма П-5 (м) "Основные сведения о деятельности организации"" <<Отчеты>>
{
..Макеты..
Списки2013кв1 : ТабличныйДокумент
Списки2013кв4 : ТабличныйДокумент
Списки2014кв1 : ТабличныйДокумент
Списки2015кв1 : ТабличныйДокумент
Списки2016кв1 : ТабличныйДокумент
Списки2017кв1 : ТабличныйДокумент
Списки2018кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2013Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв4 : ТабличныйДокумент
АтрибВыгрузкиXML2013Кв4 : ТабличныйДокумент
СхемаВыгрузкиXML2014Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2014Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2015Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2015Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2016Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2016Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2018Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2018Кв1 : ТабличныйДокумент
ФормаОтчета2013Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2013Кв4_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2014Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2015Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2016Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2017Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2018Кв1_ФормаОтчета : ТабличныйДокумент
СоставПоказателей2013Кв1 : ТабличныйДокумент
СоставПоказателей2013Кв4 : ТабличныйДокумент
СоставПоказателей2014Кв1 : ТабличныйДокумент
СоставПоказателей2015Кв1 : ТабличныйДокумент
СоставПоказателей2016Кв1 : ТабличныйДокумент
СоставПоказателей2017Кв1 : ТабличныйДокумент
СоставПоказателей2018Кв1 : ТабличныйДокумент
ШаблонРосстата2016Кв1 : ДвоичныеДанные
ШаблонРосстата2017Кв1 : ДвоичныеДанные
ШаблонРосстата2018Кв1 : ДвоичныеДанные
МакетПереносаДанных2016Кв1 : ТабличныйДокумент
МакетПереносаДанных2017Кв1 : ТабличныйДокумент
МакетПереносаДанных2018Кв1 : ТабличныйДокумент
НастройкиЗагрузкиXML2016Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2018Кв1 : ТекстовыйДокумент
}
@enduml
