@startuml РегламентированныйОтчетРСВ1
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетРСВ1 as "Расчет по страховым взносам в ПФР, ФФОМС, ТФОМС (форма РСВ-1 ПФР)" <<Отчеты>>
{
..Макеты..
ПечатнаяФормаОтчета2010Кв4_Раздел12 : ТабличныйДокумент
ПечатнаяФормаОтчета2010Кв4_Раздел30 : ТабличныйДокумент
ПечатнаяФормаОтчета2010Кв4_Раздел41 : ТабличныйДокумент
ПечатнаяФормаОтчета2010Кв4_Раздел42 : ТабличныйДокумент
ПечатнаяФормаОтчета2010Кв4_Раздел43 : ТабличныйДокумент
ПечатнаяФормаОтчета2010Кв4_Раздел50 : ТабличныйДокумент
ПечатнаяФормаОтчета2010Кв4_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2011Кв1_Раздел12 : ТабличныйДокумент
ПечатнаяФормаОтчета2011Кв1_Раздел30 : ТабличныйДокумент
ПечатнаяФормаОтчета2011Кв1_Раздел41 : ТабличныйДокумент
ПечатнаяФормаОтчета2011Кв1_Раздел42 : ТабличныйДокумент
ПечатнаяФормаОтчета2011Кв1_Раздел43 : ТабличныйДокумент
ПечатнаяФормаОтчета2011Кв1_Раздел44 : ТабличныйДокумент
ПечатнаяФормаОтчета2011Кв1_Раздел50 : ТабличныйДокумент
ПечатнаяФормаОтчета2011Кв1_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв1_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв1_Раздел2 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв1_Раздел31 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв1_Раздел32 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв1_Раздел33 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв1_Раздел34 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв1_Раздел35 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв1_Раздел36 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв1_Раздел37 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв1_Раздел38 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв1_Раздел4 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв1_Раздел5 : ТабличныйДокумент
ПечатнаяФормаОтчета2012Кв1_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2013Кв1_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2013Кв1_Раздел2 : ТабличныйДокумент
ПечатнаяФормаОтчета2013Кв1_Раздел22 : ТабличныйДокумент
ПечатнаяФормаОтчета2013Кв1_Раздел31 : ТабличныйДокумент
ПечатнаяФормаОтчета2013Кв1_Раздел32 : ТабличныйДокумент
ПечатнаяФормаОтчета2013Кв1_Раздел34 : ТабличныйДокумент
ПечатнаяФормаОтчета2013Кв1_Раздел35 : ТабличныйДокумент
ПечатнаяФормаОтчета2013Кв1_Раздел36 : ТабличныйДокумент
ПечатнаяФормаОтчета2013Кв1_Раздел37 : ТабличныйДокумент
ПечатнаяФормаОтчета2013Кв1_Раздел38 : ТабличныйДокумент
ПечатнаяФормаОтчета2013Кв1_Раздел4 : ТабличныйДокумент
ПечатнаяФормаОтчета2013Кв1_Раздел5 : ТабличныйДокумент
ПечатнаяФормаОтчета2013Кв1_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел21 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел22 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел24 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел25 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел31 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел33 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел35 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел4 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Раздел5 : ТабличныйДокумент
ПечатнаяФормаОтчета2014Кв1_Титульный : ТабличныйДокумент
ПечатнаяФормаОтчета2015Кв1_Раздел1 : ТабличныйДокумент
ПечатнаяФормаОтчета2015Кв1_Раздел21 : ТабличныйДокумент
ПечатнаяФормаОтчета2015Кв1_Раздел22 : ТабличныйДокумент
ПечатнаяФормаОтчета2015Кв1_Раздел24 : ТабличныйДокумент
ПечатнаяФормаОтчета2015Кв1_Раздел25 : ТабличныйДокумент
ПечатнаяФормаОтчета2015Кв1_Раздел31 : ТабличныйДокумент
ПечатнаяФормаОтчета2015Кв1_Раздел32 : ТабличныйДокумент
ПечатнаяФормаОтчета2015Кв1_Раздел4 : ТабличныйДокумент
ПечатнаяФормаОтчета2015Кв1_Раздел5 : ТабличныйДокумент
ПечатнаяФормаОтчета2015Кв1_Титульный : ТабличныйДокумент
СоставПоказателей2010Кв4 : ТабличныйДокумент
СоставПоказателей2011Кв1 : ТабличныйДокумент
СоставПоказателей2012Кв1 : ТабличныйДокумент
СоставПоказателей2013Кв1 : ТабличныйДокумент
СоставПоказателей2014Кв1 : ТабличныйДокумент
СоставПоказателей2015Кв1 : ТабличныйДокумент
Списки2010Кв4 : ТабличныйДокумент
Списки2011Кв1 : ТабличныйДокумент
Списки2012Кв1 : ТабличныйДокумент
Списки2013Кв1 : ТабличныйДокумент
Списки2014Кв1 : ТабличныйДокумент
Списки2015Кв1 : ТабличныйДокумент
СхемаВыгрузки700_2010 : ТабличныйДокумент
СхемаВыгрузки700_2011 : ТабличныйДокумент
СхемаВыгрузки700_2012 : ТабличныйДокумент
СхемаВыгрузки700_2013 : ТабличныйДокумент
СхемаВыгрузки700_2014 : ТабличныйДокумент
СхемаВыгрузки700_2015 : ТабличныйДокумент
ФормаОтчета2010Кв4_Раздел12 : ТабличныйДокумент
ФормаОтчета2010Кв4_Раздел30 : ТабличныйДокумент
ФормаОтчета2010Кв4_Раздел41 : ТабличныйДокумент
ФормаОтчета2010Кв4_Раздел42 : ТабличныйДокумент
ФормаОтчета2010Кв4_Раздел43 : ТабличныйДокумент
ФормаОтчета2010Кв4_Раздел50 : ТабличныйДокумент
ФормаОтчета2010Кв4_Титульный : ТабличныйДокумент
ФормаОтчета2011Кв1_Раздел12 : ТабличныйДокумент
ФормаОтчета2011Кв1_Раздел30 : ТабличныйДокумент
ФормаОтчета2011Кв1_Раздел41 : ТабличныйДокумент
ФормаОтчета2011Кв1_Раздел42 : ТабличныйДокумент
ФормаОтчета2011Кв1_Раздел43 : ТабличныйДокумент
ФормаОтчета2011Кв1_Раздел44 : ТабличныйДокумент
ФормаОтчета2011Кв1_Раздел50 : ТабличныйДокумент
ФормаОтчета2011Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел31 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел32 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел33 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел34 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел35 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел36 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел37 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел38 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел4 : ТабличныйДокумент
ФормаОтчета2012Кв1_Раздел5 : ТабличныйДокумент
ФормаОтчета2012Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2013Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2013Кв1_Раздел2 : ТабличныйДокумент
ФормаОтчета2013Кв1_Раздел22 : ТабличныйДокумент
ФормаОтчета2013Кв1_Раздел31 : ТабличныйДокумент
ФормаОтчета2013Кв1_Раздел32 : ТабличныйДокумент
ФормаОтчета2013Кв1_Раздел34 : ТабличныйДокумент
ФормаОтчета2013Кв1_Раздел35 : ТабличныйДокумент
ФормаОтчета2013Кв1_Раздел36 : ТабличныйДокумент
ФормаОтчета2013Кв1_Раздел37 : ТабличныйДокумент
ФормаОтчета2013Кв1_Раздел38 : ТабличныйДокумент
ФормаОтчета2013Кв1_Раздел4 : ТабличныйДокумент
ФормаОтчета2013Кв1_Раздел5 : ТабличныйДокумент
ФормаОтчета2013Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел21 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел22 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел24 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел31 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел33 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел35 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел4 : ТабличныйДокумент
ФормаОтчета2014Кв1_Раздел5 : ТабличныйДокумент
ФормаОтчета2014Кв1_Титульный : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел1 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел21 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел22 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел24 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел31 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел32 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел4 : ТабличныйДокумент
ФормаОтчета2015Кв1_Раздел5 : ТабличныйДокумент
ФормаОтчета2015Кв1_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2015Кв1 : ТекстовыйДокумент
}
@enduml
