@startuml ЗадачиИстекающиеНаДату
'!include templates.wsd
'..\include templates.wsd
class Отчет.ЗадачиИстекающиеНаДату as "Задачи, истекающие на дату" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
