@startuml РегламентированныйОтчетСтатистикаФормаП4
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФормаП4 as "Форма П-4 "Сведения о численности, заработной плате и движении работников"" <<Отчеты>>
{
..Макеты..
Списки2017Кв1 : ТабличныйДокумент
Списки2018Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2012Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2012Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2013Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2013Кв1 : ТабличныйДокумент
СхемаВыгрузкиXML2014Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2014Кв1_месяц : ТабличныйДокумент
АтрибВыгрузкиXML2014Кв1_квартал : ТабличныйДокумент
СхемаВыгрузкиXML2017Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1_месяц : ТабличныйДокумент
АтрибВыгрузкиXML2017Кв1_квартал : ТабличныйДокумент
СхемаВыгрузкиXML2018Кв1 : ТабличныйДокумент
АтрибВыгрузкиXML2018Кв1_месяц : ТабличныйДокумент
АтрибВыгрузкиXML2018Кв1_квартал : ТабличныйДокумент
ФормаОтчета2018Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2011Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2012Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2013Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2014Кв1_ФормаОтчета : ТабличныйДокумент
ФормаОтчета2017Кв1_ФормаОтчета : ТабличныйДокумент
СоставПоказателей2014Кв1 : ТабличныйДокумент
СоставПоказателей2017Кв1 : ТабличныйДокумент
СоставПоказателей2018Кв1 : ТабличныйДокумент
ШаблонРосстата2014Кв1_месяц : ДвоичныеДанные
ШаблонРосстата2014Кв1_квартал : ДвоичныеДанные
ШаблонРосстата2017Кв1_месяц : ДвоичныеДанные
ШаблонРосстата2017Кв1_квартал : ДвоичныеДанные
ШаблонРосстата2018Кв1_месяц : ДвоичныеДанные
ШаблонРосстата2018Кв1_квартал : ДвоичныеДанные
НастройкиЗагрузкиXML2014Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2017Кв1 : ТекстовыйДокумент
НастройкиЗагрузкиXML2018Кв1 : ТекстовыйДокумент
}
@enduml
