@startuml СтажиСотрудников
'!include templates.wsd
'..\include templates.wsd
class Отчет.СтажиСотрудников as "Стажи сотрудников" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
