@startuml КонтрольОформленияДокументовТовародвижений
'!include templates.wsd
'..\include templates.wsd
class Отчет.КонтрольОформленияДокументовТовародвижений as "Контроль оформления документов товародвижения" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
