@startuml БазаРаспределенияПроизводственныхРасходов
'!include templates.wsd
'..\include templates.wsd
class Отчет.БазаРаспределенияПроизводственныхРасходов as "База распределения производственных расходов" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
