@startuml РезультатРаботыПравилПолученияФактическихДанных
'!include templates.wsd
'..\include templates.wsd
class Отчет.РезультатРаботыПравилПолученияФактическихДанных as "Результат работы правил получения фактических данных" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
