@startuml СправкаРасчетДолиНалоговойБазы
'!include templates.wsd
'..\include templates.wsd
class Отчет.СправкаРасчетДолиНалоговойБазы as "Справка-расчет "Доля налоговой базы обособленного подразделения"" <<Отчеты>>
{
..Реквизиты..
Организация : Справочник.Организация
НачалоПериода : Дата
КонецПериода : Дата
ПоказательБУ : Булево
ПоказательНУ : Булево
ПоказательПР : Булево
ПоказательВР : Булево
РежимРасшифровки : Булево
НаборПоказателейОтчета : Число 1, 0
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
