@startuml АнализНачисленийИУдержанийАвансом
'!include templates.wsd
'..\include templates.wsd
class Отчет.АнализНачисленийИУдержанийАвансом as "Анализ начислений и удержаний авансом" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
