@startuml ПлановаяИФактическаяСебестоимостьВыпущеннойПродукции
'!include templates.wsd
'..\include templates.wsd
class Отчет.ПлановаяИФактическаяСебестоимостьВыпущеннойПродукции as "Плановая и фактическая себестоимость выпущенной продукции" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
