@startuml УправленческийБаланс
'!include templates.wsd
'..\include templates.wsd
class Отчет.УправленческийБаланс as "Управленческий баланс" <<Отчеты>>
{
..Макеты..
ОсновнаяСхемаКомпоновкиДанных : СхемаКомпоновкиДанных
}
@enduml
