@startuml РегламентированныйОтчетАкцизыПриложение1
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетАкцизыПриложение1 as "Декларация по акцизам на подакцизные товары" <<Отчеты>>
{
..Макеты..
МБ_1151084_3_00000_04_tif : ДвоичныеДанные
МБ_1151084_5_01000_05_tif : ДвоичныеДанные
МБ_1151084_5_02000_06_tif : ДвоичныеДанные
МЧБ_2011кв2_01_Титульный : ТабличныйДокумент
МЧБ_2011кв2_02_Раздел1 : ТабличныйДокумент
МЧБ_2011кв2_03_Раздел12 : ТабличныйДокумент
МЧБ_2011кв2_04_Раздел13 : ТабличныйДокумент
МЧБ_2011кв2_05_Раздел2 : ТабличныйДокумент
МЧБ_2011кв2_06_Раздел24 : ТабличныйДокумент
МЧБ_2011кв2_07_Раздел25 : ТабличныйДокумент
МЧБ_2011кв2_08_Приложение1 : ТабличныйДокумент
МЧБ_2011кв2_09_Приложение2 : ТабличныйДокумент
МЧБ_2011кв2_10_Приложение3 : ТабличныйДокумент
МЧБ_2011кв2_11_Приложение4 : ТабличныйДокумент
МЧБ_2011кв2_12_Приложение5 : ТабличныйДокумент
МЧБ_2011кв2_13_Приложение6 : ТабличныйДокумент
МЧБ_2011кв2_14_Приложение7 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Приложение1 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Приложение2 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Приложение3 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Приложение4 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Приложение5 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Приложение6 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Приложение7 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Раздел1 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Раздел12 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Раздел13 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Раздел2 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Раздел24 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Раздел25 : ТабличныйДокумент
ПечатныйБланк2013Кв4_Титульный : ТабличныйДокумент
СоставПоказателей2011Кв2 : ТабличныйДокумент
СоставПоказателей2013Кв4 : ТабличныйДокумент
Списки2011Кв2 : ТабличныйДокумент
Списки2011Кв3 : ТабличныйДокумент
СпискиВыбора2013Кв4 : ТабличныйДокумент
СтруктураXML501 : ТабличныйДокумент
СхемаВыгрузки502 : ТабличныйДокумент
ФормаОтчета2011Кв2_Приложение1 : ТабличныйДокумент
ФормаОтчета2011Кв2_Приложение2 : ТабличныйДокумент
ФормаОтчета2011Кв2_Приложение3 : ТабличныйДокумент
ФормаОтчета2011Кв2_Приложение4 : ТабличныйДокумент
ФормаОтчета2011Кв2_Приложение5 : ТабличныйДокумент
ФормаОтчета2011Кв2_Приложение6 : ТабличныйДокумент
ФормаОтчета2011Кв2_Приложение7 : ТабличныйДокумент
ФормаОтчета2011Кв2_Раздел1 : ТабличныйДокумент
ФормаОтчета2011Кв2_Раздел12 : ТабличныйДокумент
ФормаОтчета2011Кв2_Раздел13 : ТабличныйДокумент
ФормаОтчета2011Кв2_Раздел2 : ТабличныйДокумент
ФормаОтчета2011Кв2_Раздел24 : ТабличныйДокумент
ФормаОтчета2011Кв2_Раздел25 : ТабличныйДокумент
ФормаОтчета2011Кв2_Титульный : ТабличныйДокумент
ФормаОтчета2013Кв4_Приложение1 : ТабличныйДокумент
ФормаОтчета2013Кв4_Приложение2 : ТабличныйДокумент
ФормаОтчета2013Кв4_Приложение3 : ТабличныйДокумент
ФормаОтчета2013Кв4_Приложение4 : ТабличныйДокумент
ФормаОтчета2013Кв4_Приложение5 : ТабличныйДокумент
ФормаОтчета2013Кв4_Приложение6 : ТабличныйДокумент
ФормаОтчета2013Кв4_Приложение7 : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел1 : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел12 : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел13 : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел2 : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел24 : ТабличныйДокумент
ФормаОтчета2013Кв4_Раздел25 : ТабличныйДокумент
ФормаОтчета2013Кв4_Титульный : ТабличныйДокумент
НастройкиЗагрузкиXML2013Кв4 : ТекстовыйДокумент
}
@enduml
