@startuml РегламентированныйОтчетСтатистикаФорма2ДМ
'!include templates.wsd
'..\include templates.wsd
class Отчет.РегламентированныйОтчетСтатистикаФорма2ДМ as "Форма 2-ДМ "Сведения об остатках, поступлении и расходе драгоценных металлов, и изделий из них"" <<Отчеты>>
{
..Макеты..
ФормаОтчета2012Кв1_ФормаОтчета : ТабличныйДокумент
СоставПоказателей2012Кв1 : ТабличныйДокумент
}
@enduml
